OpenFOAM: streamLineBase Class Reference
streamLineBase Class Reference abstract
#include <streamLineBase.H>
Public Types
enum trackDirType : char { FORWARD , BACKWARD , BIDIRECTIONAL }
Public Member Functions
TypeName ("streamLineBase")
streamLineBase (const word &name, const Time &runTime, const dictionary &dict)
streamLineBase (const word &name, const Time &runTime, const dictionary &dict, const wordList &fieldNames)
virtual ~streamLineBase ()
virtual bool read (const dictionary &)
virtual bool execute ()
virtual bool write ()
virtual void updateMesh (const mapPolyMesh &)
virtual void movePoints (const polyMesh &)
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
Static Public Attributes
static const Enum< trackDirType > trackDirTypeNames
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Protected Member Functions
const word & sampledSetAxis () const
const sampledSet & sampledSetPoints () const
autoPtr< indirectPrimitivePatch > wallPatch () const
refPtr< interpolation< vector > > initInterpolations (const label nSeeds, PtrList< interpolation< scalar > > &vsInterp, PtrList< interpolation< vector > > &vvInterp)
void storePoint (const label tracki, const scalar w, const label lefti, const label righti, DynamicList< point > &newTrack, DynamicList< List< scalar > > &newScalars, DynamicList< List< vector > > &newVectors) const
void trimToBox (const treeBoundBox &bb, const label tracki, PtrList< DynamicList< point > > &newTracks, PtrList< DynamicList< scalarList > > &newScalars, PtrList< DynamicList< vectorList > > &newVectors) const
void trimToBox (const treeBoundBox &bb)
virtual void track ()=0
virtual bool writeToFile ()
virtual void resetFieldNames (const word &newUName, const wordList &newFieldNames)
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes
autoPtr< sampledSet > sampledSetPtr_
word sampledSetAxis_
dictionary dict_
wordList fields_
word UName_
word interpolationScheme_
trackDirType trackDir_
label lifeTime_
scalar trackLength_
boundBox bounds_
word cloudName_
word seedSet_
wordList scalarNames_
wordList vectorNames_
autoPtr< coordSetWriter > trackWriterPtr_
DynamicList< List< point > > allTracks_
List< DynamicList< scalarList > > allScalars_
List< DynamicList< vectorList > > allVectors_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Detailed Description
See also
Foam::functionObjects::streamLine Foam::functionObjects::wallBoundedStreamLine
Source files
streamLineBase.H
streamLineBase.C
Definition at line 61 of file streamLineBase.H.
Member Enumeration Documentation
trackDirType
enum trackDirType : char
Enumerator
FORWARD
Use "forward" tracking.
BACKWARD
Use "backward" tracking.
BIDIRECTIONAL
Use "bidirectional" tracking.
Definition at line 70 of file streamLineBase.H.
Constructor & Destructor Documentation
streamLineBase() [1/2]
streamLineBase (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 810 of file streamLineBase.C.
streamLineBase() [2/2]
streamLineBase (const word & name, const Time & runTime, const dictionary & dict, const wordList & fieldNames)
Definition at line 823 of file streamLineBase.C.
~streamLineBase()
~streamLineBase () virtual
Definition at line 839 of file streamLineBase.C.
Member Function Documentation
sampledSetAxis()
const Foam::word & sampledSetAxis () const protected
Definition at line 60 of file streamLineBase.C.
References streamLineBase::sampledSetAxis_, streamLineBase::sampledSetPoints(), and streamLineBase::sampledSetPtr_.
sampledSetPoints()
const Foam::sampledSet & sampledSetPoints () const protected
Definition at line 72 of file streamLineBase.C.
References MeshObject< polyMesh, GeometricMeshObject, meshSearchMeshObject >::New(), and sampledSet::New().
Referenced by streamLineBase::sampledSetAxis(), and streamLine::track().
wallPatch()
Foam::autoPtr< Foam::indirectPrimitivePatch > wallPatch () const protected
Definition at line 92 of file streamLineBase.C.
References forAll, autoPtr< T >::New(), patches, pp(), and UPtrList< T >::size().
initInterpolations()
Foam::refPtr< Foam::interpolation< Foam::vector > > initInterpolations (const label nSeeds, PtrList< interpolation< scalar > > & vsInterp, PtrList< interpolation< vector > > & vvInterp) protected
Definition at line 136 of file streamLineBase.C.
References PtrList< T >::clear(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), forAll, Foam::nl, PtrList< T >::resize(), PtrList< T >::set(), and UPtrList< T >::size().
Referenced by streamLine::track().
storePoint()
void storePoint (const label tracki, const scalar w, const label lefti, const label righti, DynamicList< point > & newTrack, DynamicList< List< scalar > > & newScalars, DynamicList< List< vector > > & newVectors) const protected
Definition at line 255 of file streamLineBase.C.
References PtrList< T >::emplace_back(), forAll, Foam::lerp(), and PtrList< T >::push_back().
trimToBox() [1/2]
void trimToBox (const treeBoundBox & bb, const label tracki, PtrList< DynamicList< point > > & newTracks, PtrList< DynamicList< scalarList > > & newScalars, PtrList< DynamicList< vectorList > > & newVectors) const protected
Definition at line 297 of file streamLineBase.C.
References UPtrList< T >::back(), treeBoundBox::contains(), PtrList< T >::emplace_back(), treeBoundBox::intersects(), and UPtrList< T >::size().
trimToBox() [2/2]
void trimToBox (const treeBoundBox & bb) protected
Definition at line 442 of file streamLineBase.C.
References PtrList< T >::emplace_back(), forAll, PtrList< T >::setSize(), and UPtrList< T >::size().
track()
virtual void track () protected pure virtual
Implemented in streamLine, and wallBoundedStreamLine.
writeToFile()
bool writeToFile () protected virtual
Definition at line 506 of file streamLineBase.C.
References dictionary::add(), Pstream::broadcast(), mapDistributeBase::distribute(), UPtrList< T >::empty(), Foam::endl(), forAll, forAllConstIters, Log, UPstream::master(), Foam::mkDir(), n, Foam::name(), Foam::nl, UPstream::nProcs(), outputName(), functionObject::outputPrefix, UPstream::parRun(), points, propsDict(), PtrList< T >::resize(), UPstream::scheduled, PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), PtrList< T >::transfer(), and writer().
resetFieldNames()
void resetFieldNames (const word & newUName, const wordList & newFieldNames) protected virtual
Definition at line 797 of file streamLineBase.C.
TypeName()
TypeName ("streamLineBase")
read()
bool read (const dictionary & dict) virtual
Reimplemented from regionFunctionObject.
Reimplemented in streamLine, and wallBoundedStreamLine.
Definition at line 845 of file streamLineBase.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::Info, Foam::name(), coordSetWriter::New(), Foam::nl, functionObject::read(), setFormat(), and Foam::type().
Referenced by streamLine::read(), and wallBoundedStreamLine::read().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 940 of file streamLineBase.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 946 of file streamLineBase.C.
References Log, Foam::name(), Foam::nl, and Foam::type().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Reimplemented from functionObject.
Definition at line 959 of file streamLineBase.C.
References Foam::read().
movePoints()
void movePoints (const polyMesh & mpm) virtual
Reimplemented from functionObject.
Definition at line 968 of file streamLineBase.C.
References Foam::read().
Member Data Documentation
trackDirTypeNames
const Foam::Enum< Foam::functionObjects::streamLineBase::trackDirType > trackDirTypeNames static
Definition at line 78 of file streamLineBase.H.
sampledSetPtr_
autoPtr<sampledSet> sampledSetPtr_ mutable protected
Definition at line 84 of file streamLineBase.H.
Referenced by streamLineBase::sampledSetAxis().
sampledSetAxis_
word sampledSetAxis_ mutable protected
Definition at line 87 of file streamLineBase.H.
Referenced by streamLineBase::sampledSetAxis().
dict_
dictionary dict_ protected
Definition at line 90 of file streamLineBase.H.
Referenced by streamLine::streamLine(), wallBoundedStreamLine::wallBoundedStreamLine(), and wallBoundedStreamLine::wallBoundedStreamLine().
fields_
wordList fields_ protected
Definition at line 93 of file streamLineBase.H.
UName_
word UName_ protected
Definition at line 96 of file streamLineBase.H.
interpolationScheme_
word interpolationScheme_ protected
Definition at line 99 of file streamLineBase.H.
trackDir_
trackDirType trackDir_ protected
Definition at line 102 of file streamLineBase.H.
Referenced by streamLine::track().
lifeTime_
label lifeTime_ protected
Definition at line 105 of file streamLineBase.H.
Referenced by streamLine::track().
trackLength_
scalar trackLength_ protected
Definition at line 108 of file streamLineBase.H.
Referenced by streamLine::track().
bounds_
boundBox bounds_ protected
Definition at line 111 of file streamLineBase.H.
cloudName_
word cloudName_ protected
Definition at line 114 of file streamLineBase.H.
Referenced by streamLine::track().
seedSet_
word seedSet_ protected
Definition at line 117 of file streamLineBase.H.
scalarNames_
wordList scalarNames_ protected
Definition at line 120 of file streamLineBase.H.
vectorNames_
wordList vectorNames_ protected
Definition at line 123 of file streamLineBase.H.
trackWriterPtr_
autoPtr<coordSetWriter> trackWriterPtr_ mutable protected
Definition at line 129 of file streamLineBase.H.
allTracks_
DynamicList<List<point> > allTracks_ protected
Definition at line 135 of file streamLineBase.H.
Referenced by streamLine::track().
allScalars_
List<DynamicList<scalarList> > allScalars_ protected
Definition at line 138 of file streamLineBase.H.
Referenced by streamLine::track().
allVectors_
List<DynamicList<vectorList> > allVectors_ protected
Definition at line 141 of file streamLineBase.H.
Referenced by streamLine::track().
The documentation for this class was generated from the following files:
src/functionObjects/field/streamLine/streamLineBase.H
src/functionObjects/field/streamLine/streamLineBase.C