OpenFOAM: externalHeatFluxSource Class Reference
externalHeatFluxSource Class Reference
Applies a heat flux condition for a specified faMesh region to temperature on an external wall for compressible flows in one of three modes:
#include <externalHeatFluxSource.H>
Public Types
enum operationMode { fixedPower , fixedHeatFlux , fixedHeatTransferCoeff }
Public Types inherited from faceSetOption
enum selectionModeType { smAll , smFaceSet , smFaceZone , smPatch }
Public Member Functions
TypeName ("externalHeatFluxSource")
externalHeatFluxSource (const word &sourceName, const word &modelType, const dictionary &dict, const fvMesh &mesh)
externalHeatFluxSource (const externalHeatFluxSource &)=delete
void operator= (const externalHeatFluxSource &)=delete
virtual ~externalHeatFluxSource ()=default
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< scalar > &eqn, const label fieldi)
virtual bool read (const dictionary &dict)
Public Member Functions inherited from faceSetOption
TypeName ("faceSetOption")
faceSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
virtual ~faceSetOption ()=default
scalar timeStart () const noexcept
scalar duration () const noexcept
bool inTimeLimits (const scalar timeValue) const
bool useSubMesh () const noexcept
selectionModeType selectionMode () const noexcept
const wordRes & selectionNames () const noexcept
const wordRe & zoneName () const
scalar A () const noexcept
const labelList & faces () const noexcept
scalar timeStart (scalar val) noexcept
scalar duration (scalar val) noexcept
virtual bool isActive ()
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
const word & regionName () const noexcept
const faMesh & regionMesh () const
const volSurfaceMapping & vsm () const
bool active (const bool on) noexcept
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (const areaScalarField &h, faMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (faMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (faMatrix< vector > &eqn, const label fieldi)
virtual void constrain (faMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (faMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (faMatrix< tensor > &eqn, const label fieldi)
virtual void correct (areaScalarField &field)
virtual void correct (areaVectorField &field)
virtual void correct (areaSphericalTensorField &field)
virtual void correct (areaSymmTensorField &field)
virtual void correct (areaTensorField &field)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
Static Public Attributes
static const Enum< operationMode > operationModeNames
Static Public Attributes inherited from faceSetOption
static const Enum< selectionModeType > selectionModeTypeNames_
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Protected Member Functions inherited from faceSetOption
void setSelection (const dictionary &dict)
void setFaceSelection ()
void setArea ()
template<class Type >
void subsetFilter (List< Type > &field) const
Protected Member Functions inherited from option
void resetApplied ()
Protected Attributes inherited from faceSetOption
scalar timeStart_
scalar duration_
selectionModeType selectionMode_
wordRes selectionNames_
labelList faces_
scalar A_
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
word regionName_
Detailed Description
Applies a heat flux condition for a specified faMesh region to temperature on an external wall for compressible flows in one of three modes:
fixed power: supply Q
fixed heat flux: supply q
fixed heat transfer coefficient: supply h and Ta
where
= Power [W]
= Heat flux [W/m^2]
= Heat transfer coefficient [W/m^2/K]
= Ambient temperature [K]
The ambient temperature Ta is specified as a Foam::Function1 of time but uniform in space.
Usage
Minimal example by using constant/faOptions:
externalHeatFluxSource1
{
    // Mandatory entries (unmodifiable)
    type            externalHeatFluxSource;
    // Mandatory entries (runtime modifiable)
    mode            <mode>;
    // Optional entries (runtime modifiable)
    T               <Tname>;
    emissivity      0;
    // Conditional mandatory entries (runtime modifiable)
        // when mode=power
        Q           1.0;
        // when mode=flux
        q           1.0;
        // when mode=coefficient
        h           1.0;
        Ta          <Function1>;
    // Mandatory/Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: externalHeatFluxSource word yes -
mode Mode of heat flux condition word yes -
T Name of operand temperature field word no T
emissivity
Surface emissivity for radiative flux to ambient
scalar no 0
Q Fixed heat power [W] Function1 cndtnl -
q Fixed heat flux [W/m2] Function1 cndtnl -
h Heat transfer coefficient [W/m^2/K] Function1 cndtnl -
Ta Ambient temperature [K] Function1 cndtnl -
The inherited entries are elaborated in:
faOption.H
faceSetOption.H
Options for the mode entry:
      power       | Use fixed power (supply Q)
      flux        | Use fixed heat flux (supply q)
      coefficient | Use fixes heat transfer coefficient (supply h and T)
See also
Foam::Function1
Source files
externalHeatFluxSource.H
externalHeatFluxSource.C
Definition at line 203 of file externalHeatFluxSource.H.
Member Enumeration Documentation
operationMode
enum operationMode
Enumerator
fixedPower
Fixed heat power [W].
fixedHeatFlux
Fixed heat flux [W/m2].
fixedHeatTransferCoeff
Fixed heat transfer coefficient.
Definition at line 212 of file externalHeatFluxSource.H.
Constructor & Destructor Documentation
externalHeatFluxSource() [1/2]
externalHeatFluxSource (const word & sourceName, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 56 of file externalHeatFluxSource.C.
References dict, option::fieldNames_, externalHeatFluxSource::read(), option::resetApplied(), and List< T >::resize().
externalHeatFluxSource() [2/2]
externalHeatFluxSource (const externalHeatFluxSource &) delete
~externalHeatFluxSource()
virtual ~externalHeatFluxSource () virtual default
Member Function Documentation
TypeName()
TypeName ("externalHeatFluxSource")
operator=()
void operator= (const externalHeatFluxSource &) delete
addSup()
void addSup (const areaScalarField & h, const areaScalarField & rho, faMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented from option.
Definition at line 83 of file externalHeatFluxSource.C.
References faceSetOption::A(), DebugInfo, Foam::dimLength, Foam::dimPower, Foam::dimTemperature, Foam::endl(), faceSetOption::faces(), Foam::name(), DimensionedField< Type, GeoMesh >::New(), Foam::pow3(), Foam::sqr(), faceSetOption::subsetFilter(), Foam::fam::SuSp(), faceSetOption::useSubMesh(), and Foam::Zero.
read()
bool read (const dictionary & dict) virtual
Reimplemented from faceSetOption.
Definition at line 191 of file externalHeatFluxSource.C.
References dict, UPtrList< T >::get(), and option::read().
Referenced by externalHeatFluxSource::externalHeatFluxSource().
Member Data Documentation
operationModeNames
const Foam::Enum< Foam::fa::externalHeatFluxSource::operationMode > operationModeNames static
Definition at line 220 of file externalHeatFluxSource.H.
The documentation for this class was generated from the following files:
src/faOptions/sources/derived/externalHeatFluxSource/externalHeatFluxSource.H
src/faOptions/sources/derived/externalHeatFluxSource/externalHeatFluxSource.C