OpenFOAM: surfaceNormalFixedValueFvPatchVectorField Class Reference
surfaceNormalFixedValueFvPatchVectorField Class Reference
Boundary conditions » Generic | Boundary conditions » Inlet
This boundary condition provides a surface-normal vector boundary condition by its magnitude.
#include <surfaceNormalFixedValueFvPatchVectorField.H>
Public Member Functions
TypeName ("surfaceNormalFixedValue")
surfaceNormalFixedValueFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
surfaceNormalFixedValueFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
surfaceNormalFixedValueFvPatchVectorField (const surfaceNormalFixedValueFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
surfaceNormalFixedValueFvPatchVectorField (const surfaceNormalFixedValueFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
surfaceNormalFixedValueFvPatchVectorField (const surfaceNormalFixedValueFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a surface-normal vector boundary condition by its magnitude.
Usage
Property Description Required Default
refValue reference value yes
ramp time-based ramping no
Example of the boundary condition specification:
    <patchName>
    {
        type            surfaceNormalFixedValue;
        refValue        uniform -10;           // 10 INTO the domain
    }
Note
Sign conventions:
the value is positive for outward-pointing vectors
See also
Foam::fixedValueFvPatchField
Source files
surfaceNormalFixedValueFvPatchVectorField.H
surfaceNormalFixedValueFvPatchVectorField.C
Definition at line 91 of file surfaceNormalFixedValueFvPatchVectorField.H.
Constructor & Destructor Documentation
surfaceNormalFixedValueFvPatchVectorField() [1/5]
surfaceNormalFixedValueFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 29 of file surfaceNormalFixedValueFvPatchVectorField.C.
surfaceNormalFixedValueFvPatchVectorField() [2/5]
surfaceNormalFixedValueFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 42 of file surfaceNormalFixedValueFvPatchVectorField.C.
References fvPatchField< vector >::operator=().
surfaceNormalFixedValueFvPatchVectorField() [3/5]
surfaceNormalFixedValueFvPatchVectorField (const surfaceNormalFixedValueFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 65 of file surfaceNormalFixedValueFvPatchVectorField.C.
References fvPatchField< vector >::operator=().
surfaceNormalFixedValueFvPatchVectorField() [4/5]
surfaceNormalFixedValueFvPatchVectorField (const surfaceNormalFixedValueFvPatchVectorField & ptf)
Definition at line 94 of file surfaceNormalFixedValueFvPatchVectorField.C.
surfaceNormalFixedValueFvPatchVectorField() [5/5]
surfaceNormalFixedValueFvPatchVectorField (const surfaceNormalFixedValueFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 106 of file surfaceNormalFixedValueFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("surfaceNormalFixedValue")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 144 of file surfaceNormalFixedValueFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 160 of file surfaceNormalFixedValueFvPatchVectorField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & mapper) virtual
Definition at line 121 of file surfaceNormalFixedValueFvPatchVectorField.C.
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Definition at line 131 of file surfaceNormalFixedValueFvPatchVectorField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 146 of file surfaceNormalFixedValueFvPatchVectorField.C.
References fvPatchField< vector >::operator=(), and fvPatchField< vector >::updateCoeffs().
write()
void write (Ostream & os) const virtual
Definition at line 165 of file surfaceNormalFixedValueFvPatchVectorField.C.
References os(), and fvPatchField< Type >::write().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/surfaceNormalFixedValue/surfaceNormalFixedValueFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/surfaceNormalFixedValue/surfaceNormalFixedValueFvPatchVectorField.C