OpenFOAM: HrenyaSinclair Class Reference
HrenyaSinclair Class Reference
#include <HrenyaSinclairViscosity.H>
Public Member Functions
TypeName ("HrenyaSinclair")
HrenyaSinclair (const dictionary &dict)
virtual ~HrenyaSinclair ()
tmp< volScalarField > nu (const volScalarField &alpha1, const volScalarField &Theta, const volScalarField &g0, const volScalarField &rho1, const volScalarField &da, const dimensionedScalar &e) const
virtual bool read ()
TypeName ("HrenyaSinclair")
HrenyaSinclair (const dictionary &dict)
virtual ~HrenyaSinclair ()
tmp< volScalarField > nu (const volScalarField &alpha1, const volScalarField &Theta, const volScalarField &g0, const volScalarField &rho1, const volScalarField &da, const dimensionedScalar &e) const
virtual bool read ()
Public Member Functions inherited from viscosityModel
TypeName ("viscosityModel")
declareRunTimeSelectionTable (autoPtr, viscosityModel, dictionary,(const dictionary &dict),(dict))
viscosityModel (const dictionary &dict)
virtual ~viscosityModel ()=default
TypeName ("viscosityModel")
declareRunTimeSelectionTable (autoPtr, viscosityModel, dictionary,(const dictionary &dict),(dict))
viscosityModel (const dictionary &dict)
virtual ~viscosityModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from viscosityModel
static autoPtr< viscosityModel > New (const dictionary &dict)
static autoPtr< viscosityModel > New (const dictionary &dict)
Protected Attributes inherited from viscosityModel
const dictionary & dict_
Detailed Description
Source files
HrenyaSinclairViscosity.H
HrenyaSinclairViscosity.C
Source files
HrenyaSinclairViscosity.H
HrenyaSinclairViscosity.C
Definition at line 49 of file HrenyaSinclairViscosity.H.
Constructor & Destructor Documentation
HrenyaSinclair() [1/2]
HrenyaSinclair (const dictionary & dict)
Definition at line 48 of file HrenyaSinclairViscosity.C.
References Foam::dimLength.
~HrenyaSinclair() [1/2]
~HrenyaSinclair () virtual
Definition at line 61 of file HrenyaSinclairViscosity.C.
HrenyaSinclair() [2/2]
HrenyaSinclair (const dictionary & dict)
~HrenyaSinclair() [2/2]
virtual ~HrenyaSinclair () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("HrenyaSinclair")
nu() [1/2]
Foam::tmp< Foam::volScalarField > nu (const volScalarField & alpha1, const volScalarField & Theta, const volScalarField & g0, const volScalarField & rho1, const volScalarField & da, const dimensionedScalar & e) const virtual
Implements viscosityModel.
Definition at line 68 of file HrenyaSinclairViscosity.C.
References alpha1, e, Foam::constant::mathematical::pi(), Foam::sqr(), and Foam::sqrt().
read() [1/2]
bool read () virtual
Reimplemented from viscosityModel.
Definition at line 93 of file HrenyaSinclairViscosity.C.
TypeName() [2/2]
TypeName ("HrenyaSinclair")
nu() [2/2]
tmp< volScalarField > nu (const volScalarField & alpha1, const volScalarField & Theta, const volScalarField & g0, const volScalarField & rho1, const volScalarField & da, const dimensionedScalar & e) const virtual
Implements viscosityModel.
read() [2/2]
virtual bool read () virtual
Reimplemented from viscosityModel.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/viscosityModel/HrenyaSinclair/HrenyaSinclairViscosity.H
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/viscosityModel/HrenyaSinclair/HrenyaSinclairViscosity.H
src/phaseSystemModels/reactingEuler/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/viscosityModel/HrenyaSinclair/HrenyaSinclairViscosity.C
src/phaseSystemModels/twoPhaseEuler/phaseCompressibleTurbulenceModels/kineticTheoryModels/viscosityModel/HrenyaSinclair/HrenyaSinclairViscosity.C