OpenFOAM: powerSeriesReactionRate Class Reference
powerSeriesReactionRate Class Reference
Power series reaction rate.
#include <powerSeriesReactionRate.H>
Public Member Functions
powerSeriesReactionRate (const scalar A, const scalar beta, const scalar Ta, const FixedList< scalar, nCoeff_ > coeffs)
powerSeriesReactionRate (const speciesTable &species, const dictionary &dict)
scalar operator() (const scalar p, const scalar T, const scalarField &c) const
void write (Ostream &os) const
Static Public Member Functions
static word type ()
Friends
Ostream & operator<< (Ostream &, const powerSeriesReactionRate &)
Detailed Description
Power series reaction rate.
Source files
powerSeriesReactionRate.H
powerSeriesReactionRateI.H
Definition at line 55 of file powerSeriesReactionRate.H.
Constructor & Destructor Documentation
powerSeriesReactionRate() [1/2]
powerSeriesReactionRate (const scalar A, const scalar beta, const scalar Ta, const FixedList< scalar, nCoeff_ > coeffs) inline
Definition at line 23 of file powerSeriesReactionRateI.H.
powerSeriesReactionRate() [2/2]
powerSeriesReactionRate (const speciesTable & species, const dictionary & dict) inline
Definition at line 38 of file powerSeriesReactionRateI.H.
Member Function Documentation
type()
static word type () inline static
Definition at line 91 of file powerSeriesReactionRate.H.
operator()()
Foam::scalar operator() (const scalar p, const scalar T, const scalarField & c) const inline
Definition at line 53 of file powerSeriesReactionRateI.H.
References Foam::exp(), forAll, Foam::mag(), n, Foam::pow(), and T.
write()
void write (Ostream & os) const inline
Definition at line 80 of file powerSeriesReactionRateI.H.
References os(), and Ostream::writeEntry().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const powerSeriesReactionRate &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/powerSeries/powerSeriesReactionRate.H
src/thermophysicalModels/specie/reaction/reactionRate/powerSeries/powerSeriesReactionRateI.H