OpenFOAM: binaryNode< CompType, ThermoType > Class Template Reference
binaryNode< CompType, ThermoType > Class Template Reference
Node of the binary tree.
#include <binaryNode.H>
Public Member Functions
void calcV (chemPointISAT< CompType, ThermoType > *&elementLeft, chemPointISAT< CompType, ThermoType > *&elementRight, scalarField &v)
scalar calcA (chemPointISAT< CompType, ThermoType > *elementLeft, chemPointISAT< CompType, ThermoType > *elementRight)
binaryNode ()
binaryNode (chemPointISAT< CompType, ThermoType > *elementLeft, chemPointISAT< CompType, ThermoType > *elementRight, binaryNode< CompType, ThermoType > *parent)
chemPointISAT< CompType, ThermoType > *& leafLeft ()
chemPointISAT< CompType, ThermoType > *& leafRight ()
binaryNode< CompType, ThermoType > *& nodeLeft ()
binaryNode< CompType, ThermoType > *& nodeRight ()
binaryNode< CompType, ThermoType > *& parent ()
const scalarField & v () const
scalarField & v ()
const scalar & a () const
scalar & a ()
Public Attributes
chemPointISAT< CompType, ThermoType > * leafLeft_
chemPointISAT< CompType, ThermoType > * leafRight_
binaryNode< CompType, ThermoType > * nodeLeft_
binaryNode< CompType, ThermoType > * nodeRight_
binaryNode< CompType, ThermoType > * parent_
label nAdditionalEqns_
scalarField v_
scalar a_
Detailed Description
template<class CompType, class ThermoType>
class Foam::binaryNode< CompType, ThermoType >
Node of the binary tree.
SourceFile binaryNode.C
Definition at line 45 of file binaryNode.H.
Constructor & Destructor Documentation
binaryNode() [1/2]
template<class CompType , class ThermoType > binaryNode ()
Definition at line 26 of file binaryNode.C.
binaryNode() [2/2]
template<class CompType , class ThermoType > binaryNode (chemPointISAT< CompType, ThermoType > * elementLeft, chemPointISAT< CompType, ThermoType > * elementRight, binaryNode< CompType, ThermoType > * parent)
Definition at line 38 of file binaryNode.C.
References binaryNode< CompType, ThermoType >::a_, binaryNode< CompType, ThermoType >::calcA(), binaryNode< CompType, ThermoType >::calcV(), binaryNode< CompType, ThermoType >::nAdditionalEqns_, and binaryNode< CompType, ThermoType >::v_.
Member Function Documentation
calcV()
template<class CompType , class ThermoType > void calcV (chemPointISAT< CompType, ThermoType > *& elementLeft, chemPointISAT< CompType, ThermoType > *& elementRight, scalarField & v)
Definition at line 69 of file binaryNode.C.
References k, Foam::min(), and Foam::sqr().
Referenced by binaryNode< CompType, ThermoType >::binaryNode().
calcA()
template<class CompType , class ThermoType > Foam::scalar calcA (chemPointISAT< CompType, ThermoType > * elementLeft, chemPointISAT< CompType, ThermoType > * elementRight)
Definition at line 156 of file binaryNode.C.
References forAll.
Referenced by binaryNode< CompType, ThermoType >::binaryNode().
leafLeft()
template<class CompType , class ThermoType > chemPointISAT< CompType, ThermoType > *& leafLeft () inline
Definition at line 138 of file binaryNode.H.
References binaryNode< CompType, ThermoType >::leafLeft_.
Referenced by binaryTree< CompType, ThermoType >::binaryTreeSearch().
leafRight()
template<class CompType , class ThermoType > chemPointISAT< CompType, ThermoType > *& leafRight () inline
Definition at line 143 of file binaryNode.H.
References binaryNode< CompType, ThermoType >::leafRight_.
Referenced by binaryTree< CompType, ThermoType >::binaryTreeSearch().
nodeLeft()
template<class CompType , class ThermoType > binaryNode< CompType, ThermoType > *& nodeLeft () inline
Definition at line 148 of file binaryNode.H.
References binaryNode< CompType, ThermoType >::nodeLeft_.
Referenced by binaryTree< CompType, ThermoType >::binaryTreeSearch().
nodeRight()
template<class CompType , class ThermoType > binaryNode< CompType, ThermoType > *& nodeRight () inline
Definition at line 153 of file binaryNode.H.
References binaryNode< CompType, ThermoType >::nodeRight_.
Referenced by binaryTree< CompType, ThermoType >::binaryTreeSearch().
parent()
template<class CompType , class ThermoType > binaryNode< CompType, ThermoType > *& parent () inline
Definition at line 158 of file binaryNode.H.
References binaryNode< CompType, ThermoType >::parent_.
Referenced by binaryTree< CompType, ThermoType >::deleteLeaf().
v() [1/2]
template<class CompType , class ThermoType > const scalarField & v () const inline
Definition at line 165 of file binaryNode.H.
References binaryNode< CompType, ThermoType >::v_.
Referenced by binaryTree< CompType, ThermoType >::binaryTreeSearch().
v() [2/2]
template<class CompType , class ThermoType > scalarField & v () inline
Definition at line 170 of file binaryNode.H.
References binaryNode< CompType, ThermoType >::v_.
a() [1/2]
template<class CompType , class ThermoType > const scalar & a () const inline
Definition at line 175 of file binaryNode.H.
References binaryNode< CompType, ThermoType >::a_.
Referenced by binaryTree< CompType, ThermoType >::binaryTreeSearch().
a() [2/2]
template<class CompType , class ThermoType > scalar & a () inline
Definition at line 180 of file binaryNode.H.
References binaryNode< CompType, ThermoType >::a_.
Member Data Documentation
leafLeft_
template<class CompType , class ThermoType > chemPointISAT<CompType, ThermoType>* leafLeft_
Definition at line 51 of file binaryNode.H.
Referenced by binaryNode< CompType, ThermoType >::leafLeft().
leafRight_
template<class CompType , class ThermoType > chemPointISAT<CompType, ThermoType>* leafRight_
Definition at line 54 of file binaryNode.H.
Referenced by binaryNode< CompType, ThermoType >::leafRight().
nodeLeft_
template<class CompType , class ThermoType > binaryNode<CompType, ThermoType>* nodeLeft_
Definition at line 57 of file binaryNode.H.
Referenced by binaryNode< CompType, ThermoType >::nodeLeft().
nodeRight_
template<class CompType , class ThermoType > binaryNode<CompType, ThermoType>* nodeRight_
Definition at line 60 of file binaryNode.H.
Referenced by binaryNode< CompType, ThermoType >::nodeRight().
parent_
template<class CompType , class ThermoType > binaryNode<CompType, ThermoType>* parent_
Definition at line 63 of file binaryNode.H.
Referenced by binaryNode< CompType, ThermoType >::parent().
nAdditionalEqns_
template<class CompType , class ThermoType > label nAdditionalEqns_
Definition at line 66 of file binaryNode.H.
Referenced by binaryNode< CompType, ThermoType >::binaryNode().
v_
template<class CompType , class ThermoType > scalarField v_
Definition at line 68 of file binaryNode.H.
Referenced by binaryNode< CompType, ThermoType >::binaryNode(), binaryNode< CompType, ThermoType >::v(), and binaryNode< CompType, ThermoType >::v().
a_
template<class CompType , class ThermoType > scalar a_
Definition at line 70 of file binaryNode.H.
Referenced by binaryNode< CompType, ThermoType >::a(), binaryNode< CompType, ThermoType >::a(), and binaryNode< CompType, ThermoType >::binaryNode().
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/ISAT/binaryNode/binaryNode.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/ISAT/binaryNode/binaryNode.C