OpenFOAM: Enum< EnumType > Class Template Reference
Enum< EnumType > Class Template Reference
Enum is a wrapper around a list of names/values that represent particular enumeration (or int) values. All dictionary searches use a literal (not regex).
#include <Enum.H>
Classes
class const_iterator
Public Types
typedef word key_type
typedef EnumType value_type
Public Member Functions
Enum () noexcept=default
Enum (std::initializer_list< std::pair< EnumType, const char * > > list)
bool empty () const noexcept
label size () const noexcept
const List< word > & names () const noexcept
const List< int > & values () const noexcept
const List< word > & toc () const noexcept
List< word > sortedToc () const
void clear ()
void push_back (std::initializer_list< std::pair< EnumType, const char * > > list)
bool contains (const word &enumName) const
bool contains (const EnumType e) const
label find (const word &enumName) const
label find (const EnumType e) const
EnumType get (const word &enumName) const
const word & get (const EnumType e) const
EnumType lookup (const word &enumName, const EnumType deflt) const
EnumType get (const word &key, const dictionary &dict) const
EnumType getOrDefault (const word &key, const dictionary &dict, const EnumType deflt, const bool failsafe=false) const
bool readEntry (const word &key, const dictionary &dict, EnumType &val, const bool mandatory=true) const
bool readIfPresent (const word &key, const dictionary &dict, EnumType &val) const
EnumType read (Istream &is) const
bool read (Istream &is, EnumType &val, const bool mandatory=true) const
void write (const EnumType e, Ostream &os) const
template<class OS >
OS & writeList (OS &os, const label ununsed=0) const
EnumType operator[] (const word &enumName) const
const word & operator[] (const EnumType e) const
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
EnumType lookupOrDefault (const word &key, const dictionary &dict, const EnumType deflt, const bool failsafe=false) const
const word & operator() (const EnumType e) const
EnumType operator() (const word &key, const EnumType deflt) const
EnumType get (const word &key, const EnumType deflt) const
EnumType lookup (const word &key, const dictionary &dict) const
void append (std::initializer_list< std::pair< EnumType, const char * > > list)
bool found (const word &enumName) const
bool found (const EnumType e) const
Detailed Description
template<class EnumType>
class Foam::Enum< EnumType >
Enum is a wrapper around a list of names/values that represent particular enumeration (or int) values. All dictionary searches use a literal (not regex).
Source files
Enum.H
Enum.C
EnumI.H
Definition at line 56 of file Enum.H.
Member Typedef Documentation
key_type
template<class EnumType > typedef word key_type
Definition at line 79 of file Enum.H.
value_type
template<class EnumType > typedef EnumType value_type
Definition at line 82 of file Enum.H.
Constructor & Destructor Documentation
Enum() [1/2]
template<class EnumType > Enum () default noexcept
Enum() [2/2]
template<class EnumType > Enum (std::initializer_list< std::pair< EnumType, const char * > > list) explicit
Definition at line 27 of file Enum.C.
Member Function Documentation
empty()
template<class EnumType > bool empty () const inline noexcept
Definition at line 24 of file EnumI.H.
References UPtrList< T >::empty().
size()
template<class EnumType > Foam::label size () const inline noexcept
Definition at line 31 of file EnumI.H.
References UPtrList< T >::size().
names()
template<class EnumType > const Foam::List< Foam::word > & names () const inline noexcept
Definition at line 39 of file EnumI.H.
values()
template<class EnumType > const Foam::List< int > & values () const inline noexcept
Definition at line 47 of file EnumI.H.
toc()
template<class EnumType > const Foam::List< Foam::word > & toc () const inline noexcept
Definition at line 55 of file EnumI.H.
sortedToc()
template<class EnumType > Foam::List< Foam::word > sortedToc () const inline
Definition at line 63 of file EnumI.H.
References Foam::sort().
clear()
template<class EnumType > void clear () inline
Definition at line 74 of file EnumI.H.
References PtrList< T >::clear().
push_back()
template<class EnumType > void push_back (std::initializer_list< std::pair< EnumType, const char * > > list)
Definition at line 48 of file Enum.C.
References UPtrList< T >::size().
Referenced by Enum< EnumType >::append().
contains() [1/2]
template<class EnumType > bool contains (const word & enumName) const inline
Definition at line 96 of file EnumI.H.
Referenced by Enum< EnumType >::found(), and Enum< EnumType >::found().
contains() [2/2]
template<class EnumType > bool contains (const EnumType e) const inline
Definition at line 103 of file EnumI.H.
find() [1/2]
template<class EnumType > Foam::label find (const word & enumName) const inline
Definition at line 82 of file EnumI.H.
find() [2/2]
template<class EnumType > Foam::label find (const EnumType e) const inline
Definition at line 89 of file EnumI.H.
References e.
get() [1/4]
template<class EnumType > EnumType get (const word & enumName) const
Definition at line 68 of file Enum.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
Referenced by Enum< EnumType >::lookup(), and Enum< EnumType >::operator()().
get() [2/4]
template<class EnumType > const Foam::word & get (const EnumType e) const inline
Definition at line 110 of file EnumI.H.
References e.
lookup() [1/2]
template<class EnumType > EnumType lookup (const word & enumName, const EnumType deflt) const
Definition at line 84 of file Enum.C.
get() [3/4]
template<class EnumType > EnumType get (const word & key, const dictionary & dict) const
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
Definition at line 149 of file Enum.C.
getOrDefault()
template<class EnumType > EnumType getOrDefault (const word & key, const dictionary & dict, const EnumType deflt, const bool failsafe = false) const
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
deflt fallback if not found
failsafe Warn only on bad enumeration
Definition at line 171 of file Enum.C.
References dict, dictionary::findEntry(), and keyType::LITERAL.
Referenced by Enum< EnumType >::lookupOrDefault().
readEntry()
template<class EnumType > bool readEntry (const word & key, const dictionary & dict, EnumType & val, const bool mandatory = true) const
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
val the value to read into
mandatory the keyword is mandatory
Definition at line 214 of file Enum.C.
readIfPresent()
template<class EnumType > bool readIfPresent (const word & key, const dictionary & dict, EnumType & val) const inline
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
val the value to read into
Definition at line 124 of file EnumI.H.
read() [1/2]
template<class EnumType > EnumType read (Istream & is) const
Definition at line 102 of file Enum.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::nl.
read() [2/2]
template<class EnumType > bool read (Istream & is, EnumType & val, const bool mandatory = true) const
Definition at line 120 of file Enum.C.
write()
template<class EnumType > void write (const EnumType e, Ostream & os) const inline
Definition at line 137 of file EnumI.H.
writeList()
template<class EnumType > template<class OS > OS & writeList (OS & os, const label ununsed = 0) const inline
Definition at line 150 of file EnumI.H.
References k, and os().
operator[]() [1/2]
template<class EnumType > EnumType operator[] (const word & enumName) const inline
Definition at line 243 of file EnumI.H.
operator[]() [2/2]
template<class EnumType > const Foam::word & operator[] (const EnumType e) const inline
Definition at line 253 of file EnumI.H.
References e.
cbegin()
template<class EnumType > Foam::Enum< EnumType >::const_iterator cbegin () const inline noexcept
Definition at line 226 of file EnumI.H.
Referenced by Enum< EnumType >::begin().
cend()
template<class EnumType > Foam::Enum< EnumType >::const_iterator cend () const inline noexcept
Definition at line 234 of file EnumI.H.
Referenced by Enum< EnumType >::end().
begin()
template<class EnumType > const_iterator begin () const inline noexcept
Definition at line 295 of file Enum.H.
References Enum< EnumType >::cbegin().
end()
template<class EnumType > const_iterator end () const inline noexcept
Definition at line 296 of file Enum.H.
References Enum< EnumType >::cend().
lookupOrDefault()
template<class EnumType > EnumType lookupOrDefault (const word & key, const dictionary & dict, const EnumType deflt, const bool failsafe = false) const inline
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
deflt fallback if not found
failsafe Warn only on bad enumeration
Definition at line 306 of file Enum.H.
References dict, and Enum< EnumType >::getOrDefault().
operator()() [1/2]
template<class EnumType > const word & operator() (const EnumType e) const inline
Definition at line 320 of file Enum.H.
References e, and Enum< EnumType >::get().
operator()() [2/2]
template<class EnumType > EnumType operator() (const word & key, const EnumType deflt) const inline
Definition at line 328 of file Enum.H.
get() [4/4]
template<class EnumType > EnumType get (const word & key, const EnumType deflt) const inline
Definition at line 336 of file Enum.H.
lookup() [2/2]
template<class EnumType > EnumType lookup (const word & key, const dictionary & dict) const inline
Definition at line 344 of file Enum.H.
References dict, and Enum< EnumType >::get().
append()
template<class EnumType > void append (std::initializer_list< std::pair< EnumType, const char * > > list) inline
Definition at line 351 of file Enum.H.
References Enum< EnumType >::push_back().
found() [1/2]
template<class EnumType > bool found (const word & enumName) const inline
Definition at line 360 of file Enum.H.
References Enum< EnumType >::contains().
found() [2/2]
template<class EnumType > bool found (const EnumType e) const inline
Definition at line 363 of file Enum.H.
References Enum< EnumType >::contains(), and e.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/options/IOstreamOption.H
src/OpenFOAM/primitives/enums/Enum.H
src/OpenFOAM/primitives/enums/Enum.C
src/OpenFOAM/primitives/enums/EnumI.H