OpenFOAM: adjointOutletVelocityFvPatchVectorField Class Reference
adjointOutletVelocityFvPatchVectorField Class Reference
Provides the adjoint outlet velocity values (i.e. adjoint velocity in case of a zeroGradient U boundary condition). Can have stability issues in cases of backflow of the primal velocity. The adjointOutletVelocityFlux should preferably be used.
#include <adjointOutletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("adjointOutletVelocity")
adjointOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
adjointOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
adjointOutletVelocityFvPatchVectorField (const adjointOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchVectorField > clone () const
adjointOutletVelocityFvPatchVectorField (const adjointOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual bool assignable () const
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
virtual void write (Ostream &) const
virtual void operator= (const fvPatchField< vector > &pvf)
TypeName ("adjointOutletVelocity")
adjointOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
adjointOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
adjointOutletVelocityFvPatchVectorField (const adjointOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchVectorField > clone () const
adjointOutletVelocityFvPatchVectorField (const adjointOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Public Member Functions inherited from adjointBoundaryCondition< Type >
TypeName ("adjointBoundaryCondition")
adjointBoundaryCondition (const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const word &solverName)
adjointBoundaryCondition (const adjointBoundaryCondition< Type > &)
virtual ~adjointBoundaryCondition ()=default
const word & objectiveManagerName () const
const word & adjointSolverName () const
const word & simulationType () const
void setBoundaryContributionPtr ()
boundaryAdjointContribution & getBoundaryAdjContribution ()
const ATCModel & getATC () const
virtual tmp< Field< typename Foam::outerProduct< Foam::vector, Type >::type > > dxdbMult () const
virtual void updatePrimalBasedQuantities ()
Additional Inherited Members
Protected Member Functions inherited from adjointBoundaryCondition< Type >
template<class Type2 >
tmp< Field< typename Foam::outerProduct< Foam::vector, Type2 >::type > > computePatchGrad (word name)
bool addATCUaGradUTerm ()
Protected Attributes inherited from adjointBoundaryCondition< Type >
const fvPatch & patch_
word managerName_
word adjointSolverName_
word simulationType_
autoPtr< boundaryAdjointContribution > boundaryContrPtr_
Switch addATCUaGradUTerm_
Detailed Description
Provides the adjoint outlet velocity values (i.e. adjoint velocity in case of a zeroGradient U boundary condition). Can have stability issues in cases of backflow of the primal velocity. The adjointOutletVelocityFlux should preferably be used.
Source files
adjointOutletVelocityFvPatchVectorField.H
adjointOutletVelocityFvPatchVectorField.C
Source files
adjointOutletVelocityFvPatchVectorField.H
adjointOutletVelocityFvPatchVectorField.C
Definition at line 55 of file adjointOutletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
adjointOutletVelocityFvPatchVectorField() [1/8]
adjointOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 90 of file adjointOutletVelocityFvPatchVectorField.C.
adjointOutletVelocityFvPatchVectorField() [2/8]
adjointOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 116 of file adjointOutletVelocityFvPatchVectorField.C.
References dict, and IOobjectOption::MUST_READ.
adjointOutletVelocityFvPatchVectorField() [3/8]
adjointOutletVelocityFvPatchVectorField (const adjointOutletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 102 of file adjointOutletVelocityFvPatchVectorField.C.
adjointOutletVelocityFvPatchVectorField() [4/8]
adjointOutletVelocityFvPatchVectorField (const adjointOutletVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 131 of file adjointOutletVelocityFvPatchVectorField.C.
adjointOutletVelocityFvPatchVectorField() [5/8]
adjointOutletVelocityFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > &)
adjointOutletVelocityFvPatchVectorField() [6/8]
adjointOutletVelocityFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > & , const dictionary &)
adjointOutletVelocityFvPatchVectorField() [7/8]
adjointOutletVelocityFvPatchVectorField (const adjointOutletVelocityFvPatchVectorField & , const fvPatch & , const DimensionedField< vector, volMesh > & , const fvPatchFieldMapper &)
adjointOutletVelocityFvPatchVectorField() [8/8]
adjointOutletVelocityFvPatchVectorField (const adjointOutletVelocityFvPatchVectorField & , const DimensionedField< vector, volMesh > &)
Member Function Documentation
TypeName() [1/2]
TypeName ("adjointOutletVelocity")
clone() [1/4]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 99 of file adjointOutletVelocityFvPatchVectorField.H.
clone() [2/4]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 115 of file adjointOutletVelocityFvPatchVectorField.H.
assignable()
virtual bool assignable () const inline virtual
Definition at line 132 of file adjointOutletVelocityFvPatchVectorField.H.
evaluate()
void evaluate (const Pstream::commsTypes commsType = Pstream::commsTypes::blocking) virtual
Definition at line 145 of file adjointOutletVelocityFvPatchVectorField.C.
References fvPatchField< vector >::evaluate().
write() [1/2]
void write (Ostream & os) const virtual
Definition at line 155 of file adjointOutletVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 165 of file adjointOutletVelocityFvPatchVectorField.C.
References fvPatchField< Type >::operator=().
TypeName() [2/2]
TypeName ("adjointOutletVelocity")
clone() [3/4]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 84 of file adjointOutletVelocityFvPatchVectorField.H.
clone() [4/4]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 100 of file adjointOutletVelocityFvPatchVectorField.H.
updateCoeffs()
virtual void updateCoeffs () virtual
write() [2/2]
virtual void write (Ostream &) const virtual
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/adjointBoundaryConditions/adjointOutletVelocity/adjointOutletVelocityFvPatchVectorField.H
applications/solvers/incompressible/adjointShapeOptimizationFoam/adjointOutletVelocity/adjointOutletVelocityFvPatchVectorField.H
src/optimisation/adjointOptimisation/adjoint/adjointBoundaryConditions/adjointOutletVelocity/adjointOutletVelocityFvPatchVectorField.C