OpenFOAM: RASModel< BasicTurbulenceModel > Class Template Reference
RASModel< BasicTurbulenceModel > Class Template Reference
Templated abstract base class for RAS turbulence models.
#include <RASModel.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("RAS")
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~RASModel ()=default
virtual bool read ()
const dimensionedScalar & kMin () const noexcept
const dimensionedScalar & epsilonMin () const noexcept
const dimensionedScalar & omegaMin () const noexcept
dimensionedScalar & kMin () noexcept
dimensionedScalar & epsilonMin () noexcept
dimensionedScalar & omegaMin () noexcept
virtual const dictionary & coeffDict () const
virtual tmp< volScalarField > nuEff () const
virtual tmp< scalarField > nuEff (const label patchi) const
virtual tmp< volScalarField > epsilon () const
virtual tmp< volScalarField > omega () const
virtual void correct ()
Public Member Functions inherited from RASModelBase
ClassName ("RASModelBase")
RASModelBase () noexcept=default
virtual ~RASModelBase ()=default
Static Public Member Functions
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Protected Member Functions
virtual void printCoeffs (const word &type)
RASModel (const RASModel &)=delete
void operator= (const RASModel &)=delete
Protected Attributes
dictionary RASDict_
Switch turbulence_
Switch printCoeffs_
dictionary coeffDict_
dimensionedScalar kMin_
dimensionedScalar epsilonMin_
dimensionedScalar omegaMin_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModel< BasicTurbulenceModel >
Templated abstract base class for RAS turbulence models.
Source files
RASModel.H
RASModel.C
Definition at line 71 of file RASModel.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 116 of file RASModel.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 117 of file RASModel.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 118 of file RASModel.H.
Constructor & Destructor Documentation
RASModel() [1/2]
template<class BasicTurbulenceModel > RASModel (const RASModel< BasicTurbulenceModel > &) protected delete
RASModel() [2/2]
template<class BasicTurbulenceModel > RASModel (const word & type, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Definition at line 39 of file RASModel.C.
~RASModel()
template<class BasicTurbulenceModel > virtual ~RASModel () virtual default
Member Function Documentation
printCoeffs()
template<class BasicTurbulenceModel > void printCoeffs (const word & type) protected virtual
Definition at line 27 of file RASModel.C.
References Foam::endl(), and Foam::Info.
Referenced by EBRSM< BasicTurbulenceModel >::EBRSM(), LRR< BasicTurbulenceModel >::LRR(), and SSG< BasicTurbulenceModel >::SSG().
operator=()
template<class BasicTurbulenceModel > void operator= (const RASModel< BasicTurbulenceModel > &) protected delete
TypeName()
template<class BasicTurbulenceModel > TypeName ("RAS")
declareRunTimeSelectionTable()
template<class BasicTurbulenceModel > declareRunTimeSelectionTable (autoPtr , RASModel< BasicTurbulenceModel > , dictionary , (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName) , (alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
New()
template<class BasicTurbulenceModel > Foam::autoPtr< Foam::RASModel< BasicTurbulenceModel > > New (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName) static
Definition at line 107 of file RASModel.C.
References dict, dictionary::getCompat(), IOobject::group(), IOobject::groupName(), IOobjectOption::MUST_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, dictionary::subDict(), and U.
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented in EBRSM< BasicTurbulenceModel >, LRR< BasicTurbulenceModel >, SSG< BasicTurbulenceModel >, linearViscousStress< RASModel< BasicTurbulenceModel > >, linearViscousStress< RASModel< EddyDiffusivity< compressible::turbulenceModel > > >, linearViscousStress< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, linearViscousStress< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, and ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 164 of file RASModel.C.
kMin() [1/2]
template<class BasicTurbulenceModel > const dimensionedScalar & kMin () const inline noexcept
Definition at line 189 of file RASModel.H.
epsilonMin() [1/2]
template<class BasicTurbulenceModel > const dimensionedScalar & epsilonMin () const inline noexcept
Definition at line 195 of file RASModel.H.
omegaMin() [1/2]
template<class BasicTurbulenceModel > const dimensionedScalar & omegaMin () const inline noexcept
Definition at line 201 of file RASModel.H.
kMin() [2/2]
template<class BasicTurbulenceModel > dimensionedScalar & kMin () inline noexcept
Definition at line 207 of file RASModel.H.
epsilonMin() [2/2]
template<class BasicTurbulenceModel > dimensionedScalar & epsilonMin () inline noexcept
Definition at line 213 of file RASModel.H.
omegaMin() [2/2]
template<class BasicTurbulenceModel > dimensionedScalar & omegaMin () inline noexcept
Definition at line 219 of file RASModel.H.
coeffDict()
template<class BasicTurbulenceModel > virtual const dictionary & coeffDict () const inline virtual
Definition at line 225 of file RASModel.H.
nuEff() [1/2]
template<class BasicTurbulenceModel > virtual tmp< volScalarField > nuEff () const inline virtual
Definition at line 232 of file RASModel.H.
References IOobject::groupName().
nuEff() [2/2]
template<class BasicTurbulenceModel > virtual tmp< scalarField > nuEff (const label patchi) const inline virtual
Definition at line 245 of file RASModel.H.
References nu, and nut.
epsilon()
template<class BasicTurbulenceModel > Foam::tmp< Foam::volScalarField > epsilon () const virtual
Reimplemented in EBRSM< BasicTurbulenceModel >, LRR< BasicTurbulenceModel >, and SSG< BasicTurbulenceModel >.
Definition at line 185 of file RASModel.C.
References IOobject::groupName(), and tmp< T >::New().
omega()
template<class BasicTurbulenceModel > Foam::tmp< Foam::volScalarField > omega () const virtual
Definition at line 204 of file RASModel.C.
References Foam::dimLength, Foam::dimTime, IOobject::groupName(), tmp< T >::New(), and Foam::sqr().
correct()
template<class BasicTurbulenceModel > void correct () virtual
Reimplemented in EBRSM< BasicTurbulenceModel >, LRR< BasicTurbulenceModel >, SSG< BasicTurbulenceModel >, linearViscousStress< RASModel< BasicTurbulenceModel > >, linearViscousStress< RASModel< EddyDiffusivity< compressible::turbulenceModel > > >, linearViscousStress< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, linearViscousStress< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, and ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 223 of file RASModel.C.
Member Data Documentation
RASDict_
template<class BasicTurbulenceModel > dictionary RASDict_ protected
Definition at line 81 of file RASModel.H.
turbulence_
template<class BasicTurbulenceModel > Switch turbulence_ protected
Definition at line 84 of file RASModel.H.
printCoeffs_
template<class BasicTurbulenceModel > Switch printCoeffs_ protected
Definition at line 87 of file RASModel.H.
coeffDict_
template<class BasicTurbulenceModel > dictionary coeffDict_ protected
Definition at line 90 of file RASModel.H.
kMin_
template<class BasicTurbulenceModel > dimensionedScalar kMin_ protected
Definition at line 93 of file RASModel.H.
Referenced by EBRSM< BasicTurbulenceModel >::EBRSM().
epsilonMin_
template<class BasicTurbulenceModel > dimensionedScalar epsilonMin_ protected
Definition at line 96 of file RASModel.H.
Referenced by EBRSM< BasicTurbulenceModel >::EBRSM(), LRR< BasicTurbulenceModel >::LRR(), and SSG< BasicTurbulenceModel >::SSG().
omegaMin_
template<class BasicTurbulenceModel > dimensionedScalar omegaMin_ protected
Definition at line 99 of file RASModel.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/RASModel/RASModel.H
src/TurbulenceModels/turbulenceModels/RAS/RASModel/RASModel.C