OpenFOAM: instant Class Reference
instant Class Reference
An instant of time. Contains the time value and name. Uses Foam::Time when formatting the name.
#include <instant.H>
Public Member Functions
instant ()=default
instant (const instant &)=default
instant (instant &&)=default
instant & operator= (const instant &)=default
instant & operator= (instant &&)=default
instant (scalar timeValue)
instant (const word &timeName)
instant (word &&timeName)
Public Member Functions inherited from Instant< word >
Instant (const Instant &)=default
Instant (Instant &&)=default
Instant ()
Instant (scalar val, const word &key)
Instant (scalar val, word &&key)
Instant & operator= (const Instant &)=default
Instant & operator= (Instant &&)=default
scalar value () const noexcept
scalar & value () noexcept
const word & name () const noexcept
word & name () noexcept
bool equal (scalar val) const noexcept
bool equal (const Instant< T2 > &other) const noexcept
Static Public Member Functions
static label findStart (const UList< instant > &times, const scalar timeVal)
static Pair< label > findRange (const UList< instant > &times, const scalar timeVal, const label start=-1)
Static Public Attributes
static const char *const typeName = "instant"
Detailed Description
An instant of time. Contains the time value and name. Uses Foam::Time when formatting the name.
Source files
instant.H
instant.C
Definition at line 53 of file instant.H.
Constructor & Destructor Documentation
instant() [1/6]
instant () default
instant() [2/6]
instant (const instant &) default
instant() [3/6]
instant (instant &&) default
instant() [4/6]
instant (scalar timeValue) explicit
Definition at line 92 of file instant.C.
instant() [5/6]
instant (const word & timeName) explicit
Definition at line 98 of file instant.C.
References Instant< word >::name(), and Instant< word >::value().
instant() [6/6]
instant (word && timeName) explicit
Definition at line 106 of file instant.C.
References Instant< word >::name(), and Instant< word >::value().
Member Function Documentation
operator=() [1/2]
instant & operator= (const instant &) default
operator=() [2/2]
instant & operator= (instant &&) default
findStart()
Foam::label findStart (const UList< instant > & times, const scalar timeVal) static
Definition at line 36 of file instant.C.
References UPtrList< T >::size(), and Instant< word >::value().
Referenced by noiseModel::findStartTimeIndex(), and surfaceNoise::initialise().
findRange()
Foam::Pair< Foam::label > findRange (const UList< instant > & times, const scalar timeVal, const label start = -1) static
Definition at line 53 of file instant.C.
References UPtrList< T >::first(), range, and UPtrList< T >::size().
Member Data Documentation
typeName
const char *const typeName = "instant" static
Definition at line 62 of file instant.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/Time/instant/instant.H
src/OpenFOAM/db/Time/instant/instant.C