OpenFOAM: coalescenceModel Class Reference
coalescenceModel Class Reference abstract
Base class for coalescence models.
#include <coalescenceModel.H>
Classes
class iNew
Public Member Functions
TypeName ("coalescenceModel")
declareRunTimeSelectionTable (autoPtr, coalescenceModel, dictionary,(const populationBalanceModel &popBal, const dictionary &dict),(popBal, dict))
coalescenceModel (const populationBalanceModel &popBal, const dictionary &dict)
autoPtr< coalescenceModel > clone () const
virtual ~coalescenceModel ()=default
virtual void correct ()
virtual void addToCoalescenceRate (volScalarField &coalescenceRate, const label i, const label j)=0
Static Public Member Functions
static autoPtr< coalescenceModel > New (const word &type, const populationBalanceModel &popBal, const dictionary &dict)
Protected Attributes
const populationBalanceModel & popBal_
Detailed Description
Base class for coalescence models.
Source files
coalescenceModel.H
coalescenceModel.C
Definition at line 48 of file coalescenceModel.H.
Constructor & Destructor Documentation
coalescenceModel()
coalescenceModel (const populationBalanceModel & popBal, const dictionary & dict)
Definition at line 65 of file coalescenceModel.C.
~coalescenceModel()
virtual ~coalescenceModel () virtual default
Member Function Documentation
TypeName()
TypeName ("coalescenceModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , coalescenceModel , dictionary , (const populationBalanceModel &popBal, const dictionary &dict) , (popBal, dict))
clone()
autoPtr< coalescenceModel > clone () const inline
Definition at line 109 of file coalescenceModel.H.
References NotImplemented.
New()
Foam::autoPtr< Foam::diameterModels::coalescenceModel > New (const word & type, const populationBalanceModel & popBal, const dictionary & dict) static
Definition at line 39 of file coalescenceModel.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::type().
Referenced by coalescenceModel::iNew::operator()().
correct()
void correct () virtual
Definition at line 77 of file coalescenceModel.C.
addToCoalescenceRate()
virtual void addToCoalescenceRate (volScalarField & coalescenceRate, const label i, const label j) pure virtual
Implemented in constantCoalescence, CoulaloglouTavlaridesCoalescence, hydrodynamic, LehrMilliesMewesCoalescence, Luo, and PrinceBlanch.
Member Data Documentation
popBal_
const populationBalanceModel& popBal_ protected
Definition at line 55 of file coalescenceModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/coalescenceModels/coalescenceModel/coalescenceModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/coalescenceModels/coalescenceModel/coalescenceModel.C