OpenFOAM: generalizedNewtonianViscosityModel Class Reference
generalizedNewtonianViscosityModel Class Reference abstract
An abstract base class for generalized Newtonian viscosity models.
#include <generalizedNewtonianViscosityModel.H>
Public Member Functions
TypeName ("generalizedNewtonianViscosityModel")
declareRunTimeSelectionTable (autoPtr, generalizedNewtonianViscosityModel, dictionary,(const dictionary &viscosityProperties),(viscosityProperties))
generalizedNewtonianViscosityModel (const generalizedNewtonianViscosityModel &)=delete
void operator= (const generalizedNewtonianViscosityModel &)=delete
generalizedNewtonianViscosityModel (const dictionary &viscosityProperties)
virtual ~generalizedNewtonianViscosityModel ()=default
const dictionary & viscosityProperties () const
virtual tmp< volScalarField > nu (const volScalarField &nu0, const volScalarField &strainRate) const =0
virtual bool read (const dictionary &viscosityProperties)=0
Static Public Member Functions
static autoPtr< generalizedNewtonianViscosityModel > New (const dictionary &dict)
Protected Attributes
dictionary viscosityProperties_
Detailed Description
An abstract base class for generalized Newtonian viscosity models.
Source files
generalizedNewtonianViscosityModel.H
generalizedNewtonianViscosityModel.C
generalizedNewtonianViscosityModelNew.C
Definition at line 60 of file generalizedNewtonianViscosityModel.H.
Constructor & Destructor Documentation
generalizedNewtonianViscosityModel() [1/2]
generalizedNewtonianViscosityModel (const generalizedNewtonianViscosityModel &) delete
generalizedNewtonianViscosityModel() [2/2]
generalizedNewtonianViscosityModel (const dictionary & viscosityProperties) explicit
Definition at line 37 of file generalizedNewtonianViscosityModel.C.
~generalizedNewtonianViscosityModel()
virtual ~generalizedNewtonianViscosityModel () virtual default
Member Function Documentation
TypeName()
TypeName ("generalizedNewtonianViscosityModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , generalizedNewtonianViscosityModel , dictionary , (const dictionary &viscosityProperties) , (viscosityProperties))
operator=()
void operator= (const generalizedNewtonianViscosityModel &) delete
New()
Foam::autoPtr< Foam::laminarModels::generalizedNewtonianViscosityModel > New (const dictionary & dict) static
Definition at line 27 of file generalizedNewtonianViscosityModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
viscosityProperties()
const dictionary & viscosityProperties () const inline
Definition at line 126 of file generalizedNewtonianViscosityModel.H.
References generalizedNewtonianViscosityModel::viscosityProperties_.
nu()
virtual tmp< volScalarField > nu (const volScalarField & nu0, const volScalarField & strainRate) const pure virtual
Implemented in BirdCarreau, Casson, CrossPowerLaw, HerschelBulkley, powerLaw, and strainRateFunction.
read()
bool read (const dictionary & viscosityProperties) pure virtual
Implemented in BirdCarreau, Casson, CrossPowerLaw, HerschelBulkley, powerLaw, and strainRateFunction.
Definition at line 49 of file generalizedNewtonianViscosityModel.C.
Referenced by BirdCarreau::read(), Casson::read(), CrossPowerLaw::read(), HerschelBulkley::read(), powerLaw::read(), and strainRateFunction::read().
Member Data Documentation
viscosityProperties_
dictionary viscosityProperties_ protected
Definition at line 66 of file generalizedNewtonianViscosityModel.H.
Referenced by generalizedNewtonianViscosityModel::viscosityProperties().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/laminar/generalizedNewtonian/generalizedNewtonianViscosityModels/generalizedNewtonianViscosityModel/generalizedNewtonianViscosityModel.H
src/TurbulenceModels/turbulenceModels/laminar/generalizedNewtonian/generalizedNewtonianViscosityModels/generalizedNewtonianViscosityModel/generalizedNewtonianViscosityModel.C
src/TurbulenceModels/turbulenceModels/laminar/generalizedNewtonian/generalizedNewtonianViscosityModels/generalizedNewtonianViscosityModel/generalizedNewtonianViscosityModelNew.C