OpenFOAM: hydrostaticPressure Class Reference
hydrostaticPressure Class Reference
Calculates and outputs the pressure fields p_rgh and ph_rgh.
#include <hydrostaticPressure.H>
Public Member Functions
TypeName ("hydrostaticPressure")
hydrostaticPressure (const word &name, const Time &runTime, const dictionary &dict)
virtual ~hydrostaticPressure ()=default
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Protected Member Functions
dimensionedScalar pRef () const
void calculateAndWrite ()
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes
word p_rghName_
word ph_rghName_
word pRefName_
scalar pRefValue_
word rhoName_
word UName_
word ghName_
word ghfName_
label nCorrectors_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Detailed Description
Calculates and outputs the pressure fields p_rgh and ph_rgh.
Usage
Example of function object specification to calculate hydrostatic pressure:
hydrostaticPressure1
{
    type        hydrostaticPressure;
    libs        (initialisationFunctionObjects);
    ...
}
Where the entries comprise:
Property Description Required Default value
log Log to standard output no yes
p_rgh Name of p_rgh field no p_rgh
ph_rgh Name of ph_rgh field no ph_rgh
pRef Name of pressure ref field no pRef
pRefValue Value of pressure ref when pRef set to pInf 0
rho Name of density field no rho
U Name of velocity field no U
gh Name of gravity*height volume field no gh
ghf Name of gravity*height surface field no ghf
nCorrectors Number of correctors when solving ph_rgh no 5
Note
Calculates the hydrostatic pressure on construction/re-initialisation; the execute and write functions are not used.
Source files
hydrostaticPressure.H
hydrostaticPressure.C
Definition at line 138 of file hydrostaticPressure.H.
Constructor & Destructor Documentation
hydrostaticPressure()
hydrostaticPressure (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 157 of file hydrostaticPressure.C.
References IOobjectOption::AUTO_WRITE, hydrostaticPressure::calculateAndWrite(), dict, fvMeshFunctionObject::mesh_, IOobjectOption::MUST_READ, hydrostaticPressure::ph_rghName_, hydrostaticPressure::read(), IOobjectOption::REGISTER, and runTime.
~hydrostaticPressure()
virtual ~hydrostaticPressure () virtual default
Member Function Documentation
pRef()
Foam::dimensionedScalar pRef () const protected
Definition at line 52 of file hydrostaticPressure.C.
References Foam::dimPressure, fvMeshFunctionObject::mesh_, hydrostaticPressure::pRefName_, hydrostaticPressure::pRefValue_, and Foam::Zero.
calculateAndWrite()
void calculateAndWrite () protected
Definition at line 69 of file hydrostaticPressure.C.
References basicThermo::dictName, Foam::fvc::div(), Foam::endl(), gh, ghf, Foam::Info, Foam::fvc::interpolate(), Foam::fvm::laplacian(), Log, Foam::max(), Foam::min(), Foam::nl, p, p_rgh, phig(), rho, rhof(), Foam::fvc::snGrad(), and U.
Referenced by hydrostaticPressure::hydrostaticPressure().
TypeName()
TypeName ("hydrostaticPressure")
read()
bool read (const dictionary & dict) virtual
Reimplemented from regionFunctionObject.
Definition at line 207 of file hydrostaticPressure.C.
References dict, UPtrList< T >::get(), and functionObject::read().
Referenced by hydrostaticPressure::hydrostaticPressure().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 233 of file hydrostaticPressure.C.
write()
bool write () virtual
Implements functionObject.
Definition at line 239 of file hydrostaticPressure.C.
Member Data Documentation
p_rghName_
word p_rghName_ protected
Definition at line 147 of file hydrostaticPressure.H.
ph_rghName_
word ph_rghName_ protected
Definition at line 150 of file hydrostaticPressure.H.
Referenced by hydrostaticPressure::hydrostaticPressure().
pRefName_
word pRefName_ protected
Definition at line 154 of file hydrostaticPressure.H.
Referenced by hydrostaticPressure::pRef().
pRefValue_
scalar pRefValue_ protected
Definition at line 157 of file hydrostaticPressure.H.
Referenced by hydrostaticPressure::pRef().
rhoName_
word rhoName_ protected
Definition at line 160 of file hydrostaticPressure.H.
UName_
word UName_ protected
Definition at line 163 of file hydrostaticPressure.H.
ghName_
word ghName_ protected
Definition at line 166 of file hydrostaticPressure.H.
ghfName_
word ghfName_ protected
Definition at line 169 of file hydrostaticPressure.H.
nCorrectors_
label nCorrectors_ protected
Definition at line 172 of file hydrostaticPressure.H.
The documentation for this class was generated from the following files:
src/functionObjects/initialisation/hydrostaticPressure/hydrostaticPressure.H
src/functionObjects/initialisation/hydrostaticPressure/hydrostaticPressure.C