OpenFOAM: kEqn< BasicTurbulenceModel > Class Template Reference
kEqn< BasicTurbulenceModel > Class Template Reference
Turbulence models » LES turbulence
One equation eddy-viscosity model.
#include <kEqn.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from LESeddyViscosity< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kEqn")
kEqn (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~kEqn ()=default
virtual bool read ()
virtual tmp< volScalarField > k () const
tmp< volScalarField > DkEff () const
virtual void correct ()
Public Member Functions inherited from LESeddyViscosity< BasicTurbulenceModel >
LESeddyViscosity (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
virtual ~LESeddyViscosity ()=default
Public Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
kEqn (const kEqn &)=delete
void operator= (const kEqn &)=delete
virtual void correctNut ()
virtual tmp< fvScalarMatrix > kSource () const
Protected Attributes
volScalarField k_
dimensionedScalar Ck_
Protected Attributes inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::kEqn< BasicTurbulenceModel >
One equation eddy-viscosity model.
Eddy viscosity SGS model using a modeled balance equation to simulate the behaviour of k.
Reference:
    Yoshizawa, A. (1986).
    Statistical theory for compressible turbulent shear flows,
    with the application to subgrid modeling.
    Physics of Fluids (1958-1988), 29(7), 2152-2164.
The default model coefficients are
    kEqnCoeffs
    {
        Ck                  0.094;
        Ce                  1.048;
    }
Source files
kEqn.H
kEqn.C
Definition at line 73 of file kEqn.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 106 of file kEqn.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 107 of file kEqn.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 108 of file kEqn.H.
Constructor & Destructor Documentation
kEqn() [1/2]
template<class BasicTurbulenceModel > kEqn (const kEqn< BasicTurbulenceModel > &) protected delete
kEqn() [2/2]
template<class BasicTurbulenceModel > kEqn (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 63 of file kEqn.C.
References Foam::bound(), kEqn< BasicTurbulenceModel >::k_, and Foam::type().
~kEqn()
template<class BasicTurbulenceModel > virtual ~kEqn () virtual default
Member Function Documentation
operator=()
template<class BasicTurbulenceModel > void operator= (const kEqn< BasicTurbulenceModel > &) protected delete
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Reimplemented in NicenoKEqn< BasicTurbulenceModel >.
Definition at line 35 of file kEqn.C.
References delta, options::New(), and Foam::sqrt().
kSource()
template<class BasicTurbulenceModel > tmp< fvScalarMatrix > kSource () const protected virtual
Reimplemented in continuousGasKEqn< BasicTurbulenceModel >, and NicenoKEqn< BasicTurbulenceModel >.
Definition at line 46 of file kEqn.C.
References Foam::dimTime, and Foam::dimVolume.
TypeName()
template<class BasicTurbulenceModel > TypeName ("kEqn< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented from LESeddyViscosity< BasicTurbulenceModel >.
Reimplemented in continuousGasKEqn< BasicTurbulenceModel >, and NicenoKEqn< BasicTurbulenceModel >.
Definition at line 122 of file kEqn.C.
k()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > k () const inline virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 141 of file kEqn.H.
References kEqn< BasicTurbulenceModel >::k_.
DkEff()
template<class BasicTurbulenceModel > tmp< volScalarField > DkEff () const inline
Definition at line 147 of file kEqn.H.
References nu, and eddyViscosity< LESModel< BasicTurbulenceModel > >::nut_.
correct()
template<class BasicTurbulenceModel > void correct () virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 136 of file kEqn.C.
References Foam::fvc::absolute(), alpha, Foam::bound(), PtrList< T >::clear(), linearViscousStress< BasicTurbulenceModel >::correct(), Foam::fvm::ddt(), delta, Foam::devTwoSymm(), Foam::fvc::div(), Foam::fvm::div(), divU, fvOptions, Foam::fvc::grad(), Foam::fvm::laplacian(), options::New(), nut, phi, rho, solve(), Foam::fvm::Sp(), Foam::sqrt(), Foam::fvm::SuSp(), and U.
Member Data Documentation
k_
template<class BasicTurbulenceModel > volScalarField k_ protected
Definition at line 83 of file kEqn.H.
Referenced by kEqn< BasicTurbulenceModel >::k(), and kEqn< BasicTurbulenceModel >::kEqn().
Ck_
template<class BasicTurbulenceModel > dimensionedScalar Ck_ protected
Definition at line 88 of file kEqn.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/kEqn/kEqn.H
src/TurbulenceModels/turbulenceModels/LES/kEqn/kEqn.C