OpenFOAM: STLReader Class Reference
STLReader Class Reference
Internal class used by the STLsurfaceFormat and triSurface.
#include <STLReader.H>
Public Member Functions
STLReader (const fileName &filename)
STLReader (const fileName &filename, const STLFormat format)
~STLReader ()=default
void clear ()
label mergePointsMap (labelList &pointMap) const
label mergePointsMap (const scalar mergeTol, labelList &pointMap) const
bool sorted () const
List< STLpoint > & points ()
List< label > & zoneIds ()
List< word > & names ()
List< label > & sizes ()
enum STLFormat stlFormat () const
Static Public Attributes
static int parserType
Additional Inherited Members
Public Types inherited from STLCore
enum STLFormat { ASCII , BINARY , UNKNOWN }
Protected Member Functions inherited from STLCore
STLCore ()=default
Static Protected Member Functions inherited from STLCore
static bool isBinaryName (const fileName &filename, const STLFormat format)
static int detectBinaryHeader (const fileName &filename)
static std::unique_ptr< std::istream > readBinaryHeader (const fileName &filename, label &nTrisEstimated)
static void writeBinaryHeader (ostream &os, uint32_t nTris)
Detailed Description
Internal class used by the STLsurfaceFormat and triSurface.
Source files
STLReader.H
STLReader.C
STLsurfaceFormatASCII.L
Definition at line 63 of file STLReader.H.
Constructor & Destructor Documentation
STLReader() [1/2]
STLReader (const fileName & filename)
Definition at line 200 of file STLReader.C.
References STLCore::UNKNOWN.
STLReader() [2/2]
STLReader (const fileName & filename, const STLFormat format)
Definition at line 217 of file STLReader.C.
References format().
~STLReader()
~STLReader () default
Member Function Documentation
clear()
void clear ()
Definition at line 237 of file STLReader.C.
References PtrList< T >::clear().
mergePointsMap() [1/2]
Foam::label mergePointsMap (labelList & pointMap) const
Definition at line 248 of file STLReader.C.
References Foam::doubleScalarSMALL.
Referenced by STLsurfaceFormat< Face >::read().
mergePointsMap() [2/2]
Foam::label mergePointsMap (const scalar mergeTol, labelList & pointMap) const
Definition at line 266 of file STLReader.C.
References Foam::mergePoints().
sorted()
bool sorted () const inline
Definition at line 156 of file STLReader.H.
Referenced by STLsurfaceFormat< Face >::read().
points()
List< STLpoint > & points () inline
Definition at line 162 of file STLReader.H.
Referenced by STLsurfaceFormat< Face >::read().
zoneIds()
List< label > & zoneIds () inline
Definition at line 168 of file STLReader.H.
Referenced by STLsurfaceFormat< Face >::read().
names()
List< word > & names () inline
Definition at line 174 of file STLReader.H.
Referenced by STLsurfaceFormat< Face >::read().
sizes()
List< label > & sizes () inline
Definition at line 180 of file STLReader.H.
Referenced by STLsurfaceFormat< Face >::read().
stlFormat()
enum STLFormat stlFormat () const inline
Definition at line 186 of file STLReader.H.
Member Data Documentation
parserType
int parserType static
Definition at line 123 of file STLReader.H.
The documentation for this class was generated from the following files:
src/fileFormats/stl/STLReader.H
src/fileFormats/stl/STLAsciiParseManual.C
src/fileFormats/stl/STLReader.C