OpenFOAM: ThermoPhaseModel< BasePhaseModel, ThermoType > Class Template Reference
ThermoPhaseModel< BasePhaseModel, ThermoType > Class Template Reference
Class which represents a phase with a thermodynamic model. Provides access to the thermodynamic variables. Note that the thermo model itself is not returned as this class could be substituted in the hierarchy for one which mirrors the functionality, but does not include a thermo model; an incompressible phase model, for example.
#include <ThermoPhaseModel.H>
Public Member Functions
ThermoPhaseModel (const phaseSystem &fluid, const word &phaseName, const label index)
virtual ~ThermoPhaseModel ()
virtual bool compressible () const
virtual const rhoThermo & thermo () const
virtual rhoThermo & thermoRef ()
virtual tmp< volScalarField > rho () const
virtual tmp< volScalarField > mu () const
virtual tmp< scalarField > mu (const label patchi) const
virtual tmp< volScalarField > nu () const
virtual tmp< scalarField > nu (const label patchi) const
virtual tmp< volScalarField > alpha () const
virtual tmp< scalarField > alpha (const label patchi) const
virtual tmp< volScalarField > kappa () const
virtual tmp< scalarField > kappa (const label patchi) const
virtual tmp< volScalarField > alphahe () const
virtual tmp< scalarField > alphahe (const label patchi) const
virtual tmp< volScalarField > kappaEff (const volScalarField &alphat) const
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
Protected Attributes
autoPtr< ThermoType > thermo_
Detailed Description
template<class BasePhaseModel, class ThermoType>
class Foam::ThermoPhaseModel< BasePhaseModel, ThermoType >
Class which represents a phase with a thermodynamic model. Provides access to the thermodynamic variables. Note that the thermo model itself is not returned as this class could be substituted in the hierarchy for one which mirrors the functionality, but does not include a thermo model; an incompressible phase model, for example.
Source files
ThermoPhaseModel.H
ThermoPhaseModel.C
Definition at line 53 of file ThermoPhaseModel.H.
Constructor & Destructor Documentation
ThermoPhaseModel()
template<class BasePhaseModel , class ThermoType > ThermoPhaseModel (const phaseSystem & fluid, const word & phaseName, const label index)
Definition at line 35 of file ThermoPhaseModel.C.
References IOobject::groupName(), Foam::name(), Foam::New(), ThermoPhaseModel< BasePhaseModel, ThermoType >::thermo_, and FieldBase::typeName.
~ThermoPhaseModel()
template<class BasePhaseModel , class ThermoType > ~ThermoPhaseModel () virtual
Definition at line 57 of file ThermoPhaseModel.C.
Member Function Documentation
compressible()
template<class BasePhaseModel , class ThermoType > bool compressible () const virtual
Definition at line 64 of file ThermoPhaseModel.C.
thermo()
template<class BasePhaseModel , class ThermoType > const Foam::rhoThermo & thermo () const virtual
Definition at line 72 of file ThermoPhaseModel.C.
thermoRef()
template<class BasePhaseModel , class ThermoType > Foam::rhoThermo & thermoRef () virtual
Definition at line 80 of file ThermoPhaseModel.C.
rho()
template<class BasePhaseModel , class ThermoType > Foam::tmp< Foam::volScalarField > rho () const virtual
Definition at line 88 of file ThermoPhaseModel.C.
mu() [1/2]
template<class BasePhaseModel , class ThermoType > Foam::tmp< Foam::volScalarField > mu () const virtual
Definition at line 96 of file ThermoPhaseModel.C.
mu() [2/2]
template<class BasePhaseModel , class ThermoType > Foam::tmp< Foam::scalarField > mu (const label patchi) const virtual
Definition at line 104 of file ThermoPhaseModel.C.
nu() [1/2]
template<class BasePhaseModel , class ThermoType > Foam::tmp< Foam::volScalarField > nu () const virtual
Definition at line 115 of file ThermoPhaseModel.C.
nu() [2/2]
template<class BasePhaseModel , class ThermoType > Foam::tmp< Foam::scalarField > nu (const label patchi) const virtual
Definition at line 123 of file ThermoPhaseModel.C.
alpha() [1/2]
template<class BasePhaseModel , class ThermoType > Foam::tmp< Foam::volScalarField > alpha () const virtual
Definition at line 195 of file ThermoPhaseModel.C.
alpha() [2/2]
template<class BasePhaseModel , class ThermoType > Foam::tmp< Foam::scalarField > alpha (const label patchi) const virtual
Definition at line 203 of file ThermoPhaseModel.C.
kappa() [1/2]
template<class BasePhaseModel , class ThermoType > Foam::tmp< Foam::volScalarField > kappa () const virtual
Definition at line 134 of file ThermoPhaseModel.C.
kappa() [2/2]
template<class BasePhaseModel , class ThermoType > Foam::tmp< Foam::scalarField > kappa (const label patchi) const virtual
Definition at line 142 of file ThermoPhaseModel.C.
alphahe() [1/2]
template<class BasePhaseModel , class ThermoType > Foam::tmp< Foam::volScalarField > alphahe () const virtual
Definition at line 153 of file ThermoPhaseModel.C.
alphahe() [2/2]
template<class BasePhaseModel , class ThermoType > Foam::tmp< Foam::scalarField > alphahe (const label patchi) const virtual
Definition at line 161 of file ThermoPhaseModel.C.
kappaEff() [1/2]
template<class BasePhaseModel , class ThermoType > Foam::tmp< Foam::volScalarField > kappaEff (const volScalarField & alphat) const virtual
Definition at line 172 of file ThermoPhaseModel.C.
kappaEff() [2/2]
template<class BasePhaseModel , class ThermoType > Foam::tmp< Foam::scalarField > kappaEff (const scalarField & alphat, const label patchi) const virtual
Definition at line 183 of file ThermoPhaseModel.C.
alphaEff() [1/2]
template<class BasePhaseModel , class ThermoType > Foam::tmp< Foam::volScalarField > alphaEff (const volScalarField & alphat) const virtual
Definition at line 214 of file ThermoPhaseModel.C.
alphaEff() [2/2]
template<class BasePhaseModel , class ThermoType > Foam::tmp< Foam::scalarField > alphaEff (const scalarField & alphat, const label patchi) const virtual
Definition at line 225 of file ThermoPhaseModel.C.
Member Data Documentation
thermo_
template<class BasePhaseModel , class ThermoType > autoPtr<ThermoType> thermo_ protected
Definition at line 62 of file ThermoPhaseModel.H.
Referenced by ThermoPhaseModel< BasePhaseModel, ThermoType >::ThermoPhaseModel().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/ThermoPhaseModel/ThermoPhaseModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/ThermoPhaseModel/ThermoPhaseModel.C