OpenFOAM: parLagrangianDistributor Class Reference
parLagrangianDistributor Class Reference
Lagrangian field redistributor.
#include <parLagrangianDistributor.H>
Public Member Functions
parLagrangianDistributor (const parLagrangianDistributor &)=delete
void operator= (const parLagrangianDistributor &)=delete
parLagrangianDistributor (const fvMesh &srcMesh, const fvMesh &tgtMesh, const label nOldCells, const mapDistributePolyMesh &distMap)
autoPtr< mapDistributeBase > distributeLagrangianPositions (passivePositionParticleCloud &cloud) const
autoPtr< mapDistributeBase > distributeLagrangianPositions (const word &cloudName) const
label distributeAllFields (const mapDistributeBase &lagrangianMap, const word &cloudName, const IOobjectList &cloudObjs, const wordRes &selectedFields) const
label distributeAllStoredFields (const mapDistributeBase &lagrangianMap, passivePositionParticleCloud &cloud) const
template<class Type >
label distributeFields (const mapDistributeBase &map, const word &cloudName, const IOobjectList &objects, const wordRes &selectedFields=wordRes()) const
template<class Type >
label distributeFieldFields (const mapDistributeBase &map, const word &cloudName, const IOobjectList &objects, const wordRes &selectedFields=wordRes()) const
template<class Container >
label distributeStoredFields (const mapDistributeBase &map, passivePositionParticleCloud &cloud) const
Static Public Member Functions
static void findClouds (const fvMesh &, wordList &cloudNames, List< wordList > &objectNames)
template<class Type >
static wordList filterObjects (const IOobjectList &objects, const wordRes &selectedFields=wordRes())
template<class Container >
static label readFields (const passivePositionParticleCloud &cloud, const IOobjectList &objects, const wordRes &selectedFields=wordRes())
static label readAllFields (const passivePositionParticleCloud &cloud, const IOobjectList &objects, const wordRes &selectedFields=wordRes())
static label readAllFields (const passivePositionParticleCloud &cloud, const wordRes &selectedFields=wordRes())
Static Public Attributes
static int verbose_
Detailed Description
Lagrangian field redistributor.
Runs in parallel. Redistributes from fromMesh to toMesh.
Source files
parLagrangianDistributor.H
parLagrangianDistributor.C
parLagrangianDistributorFields.C
parLagrangianDistributorTemplates.C
Definition at line 58 of file parLagrangianDistributor.H.
Constructor & Destructor Documentation
parLagrangianDistributor() [1/2]
parLagrangianDistributor (const parLagrangianDistributor &) delete
parLagrangianDistributor() [2/2]
parLagrangianDistributor (const fvMesh & srcMesh, const fvMesh & tgtMesh, const label nOldCells, const mapDistributePolyMesh & distMap)
Member Function Documentation
operator=()
void operator= (const parLagrangianDistributor &) delete
findClouds()
static void findClouds (const fvMesh & , wordList & cloudNames, List< wordList > & objectNames) static
Referenced by Foam::readLagrangian(), and Foam::reconstructLagrangian().
filterObjects()
template<class Type > static wordList filterObjects (const IOobjectList & objects, const wordRes & selectedFields = wordRes()) static
readFields()
template<class Container > static label readFields (const passivePositionParticleCloud & cloud, const IOobjectList & objects, const wordRes & selectedFields = wordRes()) static
readAllFields() [1/2]
static label readAllFields (const passivePositionParticleCloud & cloud, const IOobjectList & objects, const wordRes & selectedFields = wordRes()) static
Referenced by Foam::readLagrangian().
readAllFields() [2/2]
static label readAllFields (const passivePositionParticleCloud & cloud, const wordRes & selectedFields = wordRes()) static
distributeLagrangianPositions() [1/2]
autoPtr< mapDistributeBase > distributeLagrangianPositions (passivePositionParticleCloud & cloud) const
distributeLagrangianPositions() [2/2]
autoPtr< mapDistributeBase > distributeLagrangianPositions (const word & cloudName) const
distributeAllFields()
label distributeAllFields (const mapDistributeBase & lagrangianMap, const word & cloudName, const IOobjectList & cloudObjs, const wordRes & selectedFields) const
distributeAllStoredFields()
label distributeAllStoredFields (const mapDistributeBase & lagrangianMap, passivePositionParticleCloud & cloud) const
distributeFields()
template<class Type > label distributeFields (const mapDistributeBase & map, const word & cloudName, const IOobjectList & objects, const wordRes & selectedFields = wordRes()) const
distributeFieldFields()
template<class Type > label distributeFieldFields (const mapDistributeBase & map, const word & cloudName, const IOobjectList & objects, const wordRes & selectedFields = wordRes()) const
distributeStoredFields()
template<class Container > label distributeStoredFields (const mapDistributeBase & map, passivePositionParticleCloud & cloud) const
Member Data Documentation
verbose_
int verbose_ static
Definition at line 81 of file parLagrangianDistributor.H.
The documentation for this class was generated from the following file:
applications/utilities/parallelProcessing/redistributePar/parLagrangianDistributor.H