OpenFOAM: phaseChange Class Reference
phaseChange Class Reference
Drift induced by interfacial phase change. By default phase change mass flux is distributed between sizeGroups of each velocityGroup with phase change based on interfacial area of each size group.
#include <phaseChange.H>
Public Member Functions
TypeName ("phaseChange")
phaseChange (const populationBalanceModel &popBal, const dictionary &dict)
virtual ~phaseChange ()=default
virtual void correct ()
virtual void addToDriftRate (volScalarField &driftRate, const label i)
Public Member Functions inherited from driftModel
TypeName ("driftModel")
declareRunTimeSelectionTable (autoPtr, driftModel, dictionary,(const populationBalanceModel &popBal, const dictionary &dict),(popBal, dict))
driftModel (const populationBalanceModel &popBal, const dictionary &dict)
autoPtr< driftModel > clone () const
virtual ~driftModel ()=default
const populationBalanceModel & popBal () const
Additional Inherited Members
Static Public Member Functions inherited from driftModel
static autoPtr< driftModel > New (const word &type, const populationBalanceModel &popBal, const dictionary &dict)
Protected Attributes inherited from driftModel
const populationBalanceModel & popBal_
Detailed Description
Drift induced by interfacial phase change. By default phase change mass flux is distributed between sizeGroups of each velocityGroup with phase change based on interfacial area of each size group.
Source files
phaseChange.H
phaseChange.C
Definition at line 52 of file phaseChange.H.
Constructor & Destructor Documentation
phaseChange()
phaseChange (const populationBalanceModel & popBal, const dictionary & dict)
Definition at line 44 of file phaseChange.C.
References Foam::dimLength, Foam::dimVolume, fluid, forAll, IOobject::groupName(), Foam::inv(), phasePair::name(), driftModel::popBal_, IOobject::scopedName(), PtrList< T >::set(), Foam::type(), and Foam::Zero.
~phaseChange()
virtual ~phaseChange () virtual default
Member Function Documentation
TypeName()
TypeName ("phaseChange")
correct()
void correct () virtual
Reimplemented from driftModel.
Definition at line 86 of file phaseChange.C.
References phasePair::contains(), fluid, forAll, k, and Foam::max().
addToDriftRate()
void addToDriftRate (volScalarField & driftRate, const label i) virtual
Implements driftModel.
Definition at line 121 of file phaseChange.C.
References phasePair::contains(), Pair< T >::first(), forAll, IOobject::groupName(), k, DimensionedField< Type, GeoMesh >::mesh(), and phasePair::name().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/driftModels/phaseChange/phaseChange.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/driftModels/phaseChange/phaseChange.C