OpenFOAM: AABBTreeBase Class Reference
AABBTreeBase Class Reference
#include <AABBTree.H>
Public Member Functions
AABBTreeBase ()=default
Static Public Member Functions
static void writeOBJ (Ostream &os, const treeBoundBox &bb, label &vertIndex, const bool writeLinesOnly=false)
Static Protected Attributes
static scalar tolerance_ = 1e-4
Detailed Description
Definition at line 71 of file AABBTree.H.
Constructor & Destructor Documentation
AABBTreeBase()
AABBTreeBase () default
Member Function Documentation
writeOBJ()
void writeOBJ (Ostream & os, const treeBoundBox & bb, label & vertIndex, const bool writeLinesOnly = false) static
Definition at line 31 of file AABBTreeBase.C.
References e, treeBoundBox::edges, f(), treeBoundBox::faces, Foam::nl, os(), p, treeBoundBox::points(), pts, and UPtrList< T >::size().
Referenced by AABBTree< Type >::writeOBJ(), and AABBTree< Type >::writeOBJ().
Member Data Documentation
tolerance_
Foam::scalar tolerance_ = 1e-4 static protected
Definition at line 78 of file AABBTree.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/AABBTree/AABBTree.H
src/OpenFOAM/algorithms/AABBTree/AABBTreeBase.C