OpenFOAM: masterUncollatedFileOperation Class Reference
masterUncollatedFileOperation Class Reference
fileOperations that performs all file operations on the master processor. Requires the calls to be parallel synchronised!
#include <masterUncollatedFileOperation.H>
Classes
class chModOp
class cpOp
class existsOp
class fileOrNullOp
class fileSizeOp
class highResLastModifiedOp
class isDirOp
class isFileOp
class lastModifiedOp
class lnOp
class mkDirOp
class modeOp
class mvBakOp
class mvOp
class readDirOp
class rmDirOp
class rmOp
class typeOp
Public Member Functions
TypeName ("masterUncollated")
masterUncollatedFileOperation (bool verbose=false)
masterUncollatedFileOperation (const Tuple2< label, labelList > &commAndIORanks, const bool distributedRoots, bool verbose=false)
virtual ~masterUncollatedFileOperation ()
virtual void storeComm () const
virtual bool mkDir (const fileName &, mode_t=0777) const
virtual bool chMod (const fileName &, const mode_t) const
virtual mode_t mode (const fileName &, const bool followLink=true) const
virtual fileName::Type type (const fileName &, const bool followLink=true) const
virtual bool exists (const fileName &, const bool checkGzip=true, const bool followLink=true) const
virtual bool isDir (const fileName &, const bool followLink=true) const
virtual bool isFile (const fileName &, const bool checkGzip=true, const bool followLink=true) const
virtual off_t fileSize (const fileName &, const bool followLink=true) const
virtual time_t lastModified (const fileName &, const bool followLink=true) const
virtual double highResLastModified (const fileName &, const bool followLink=true) const
virtual fileNameList readDir (const fileName &, const fileName::Type=fileName::FILE, const bool filtergz=true, const bool followLink=true) const
virtual bool cp (const fileName &src, const fileName &dst, const bool followLink=true) const
virtual bool ln (const fileName &src, const fileName &dst) const
virtual bool mv (const fileName &src, const fileName &dst, const bool followLink=false) const
virtual bool mvBak (const fileName &, const std::string &ext="bak") const
virtual bool rm (const fileName &) const
virtual bool rmDir (const fileName &dir, const bool silent=false, const bool emptyOnly=false) const
virtual fileName filePath (const bool checkGlobal, const IOobject &io, const word &typeName, const bool search) const
virtual fileName dirPath (const bool checkGlobal, const IOobject &io, const bool search) const
virtual fileNameList readObjects (const objectRegistry &db, const fileName &instance, const fileName &local, word &newInstance) const
virtual bool readHeader (IOobject &, const fileName &, const word &typeName) const
virtual autoPtr< ISstream > readStream (regIOobject &, const fileName &, const word &typeName, const bool readOnProc=true) const
virtual bool read (regIOobject &, const bool masterOnly, const IOstreamOption::streamFormat format, const word &typeName) const
virtual bool writeObject (const regIOobject &io, IOstreamOption streamOpt=IOstreamOption(), const bool writeOnProc=true) const
virtual autoPtr< ISstream > NewIFstream (const fileName &) const
virtual autoPtr< OSstream > NewOFstream (const fileName &pathname, IOstreamOption streamOpt=IOstreamOption(), const bool writeOnProc=true) const
virtual autoPtr< OSstream > NewOFstream (IOstreamOption::atomicType atomic, const fileName &pathname, IOstreamOption streamOpt=IOstreamOption(), const bool writeOnProc=true) const
virtual label addWatch (const fileName &) const
virtual bool removeWatch (const label) const
virtual label findWatch (const labelList &watchIndices, const fileName &) const
virtual void addWatches (regIOobject &, const fileNameList &) const
virtual fileName getFile (const label) const
virtual void updateStates (const bool masterOnly, const bool syncPar) const
virtual fileMonitor::fileState getState (const label) const
virtual void setUnmodified (const label) const
virtual instantList findTimes (const fileName &, const word &) const
virtual IOobject findInstance (const IOobject &io, const scalar startValue, const word &stopInstance) const
virtual void setTime (const Time &) const
virtual void flush () const
virtual void sync ()
const HashPtrTable< DynamicList< instant > > & times () const noexcept
Public Member Functions inherited from fileOperation
TypeName ("fileOperation")
fileOperation (const label comm, const labelUList &ioRanks=labelUList::null(), const bool distributedRoots=false)
fileOperation (const Tuple2< label, labelList > &commAndIORanks, const bool distributedRoots=false)
declareRunTimeSelectionTable (autoPtr, fileOperation, word,(bool verbose),(verbose))
declareRunTimeSelectionTable (autoPtr, fileOperation, comm,(const Tuple2< label, labelList > &commAndIORanks, const bool distributedRoots, bool verbose),(commAndIORanks, distributedRoots, verbose))
virtual ~fileOperation ()=default
label comm () const noexcept
label comm (label communicator) const noexcept
bool distributed () const noexcept
bool distributed (bool on) const noexcept
const labelList & ioRanks () const noexcept
InfoProxy< fileOperation > info () const noexcept
virtual bool good () const
virtual bool broadcastCopy (const label comm, const bool writeOnProc, const fileName &src, const fileName &dst) const
virtual fileName objectPath (const IOobject &io, const word &typeName) const
virtual fileName filePath (const fileName &, const bool checkGzip=true, const bool followLink=true) const
virtual word processorsDir (const IOobject &io) const
virtual word processorsDir (const fileName &) const
label nProcs () const noexcept
label nProcs (const label numProcs) noexcept
virtual label nProcs (const fileName &dir, const fileName &local="") const
fileName processorsCasePath (const IOobject &io, const word &procDir) const
fileName processorsPath (const IOobject &io, const word &instance, const word &procDir) const
fileName processorsPath (const fileName &, const word &procDir) const
label setNProcs (label numProcs)
Static Public Attributes
static float maxMasterFileBufferSize
Static Public Attributes inherited from fileOperation
static const Enum< pathType > pathTypeNames_
static word processorsBaseDir = "processors"
static word defaultFileHandler
static refPtr< fileOperation > fileHandlerPtr_
Protected Member Functions
template<class Type >
Type scatterList (const UList< Type > &, const int, const label comm) const
template<class Type , class FileOp >
Type masterOp (const fileName &fName, const FileOp &fop, const int tag, const label comm) const
template<class Type , class FileOp >
Type masterOp (const fileName &src, const fileName &dest, const FileOp &fop, const int tag, const label comm) const
virtual fileName filePathInfo (const bool checkGlobal, const bool isFile, const IOobject &io, const dirIndexList &pDirs, const bool search, pathType &searchType, word &processorsDir, word &instance) const
fileName localObjectPath (const IOobject &, const pathType &searchType, const word &processorsDir, const word &instancePath) const
bool exists (const dirIndexList &, IOobject &io) const
Protected Member Functions inherited from fileOperation
fileMonitor & monitor () const
refPtr< dirIndexList > lookupAndCacheProcessorsPath (const fileName &objectPath, const bool syncPar) const
virtual refPtr< dirIndexList > lookupProcessorsPath (const fileName &objectPath) const
bool exists (IOobject &io) const
bool isIOrank (const label proci) const
void printRanks () const
Static Protected Member Functions
static word findInstancePath (const instantList &timeDirs, const instant &t)
static void readAndSend (const fileName &filePath, const labelUList &recvProcs, PstreamBuffers &pBufs)
static autoPtr< ISstream > read (IOobject &io, const label comm, const bool uniform, const fileNameList &filePaths, const boolUList &readOnProcs)
Static Protected Member Functions inherited from fileOperation
static void mergeTimes (const instantList &extraTimes, const word &constantName, instantList &times)
static bool isFileOrDir (const bool isFile, const fileName &)
static label getManagedComm (const label communicator)
Protected Attributes
HashPtrTable< DynamicList< instant > > times_
Protected Attributes inherited from fileOperation
label comm_
label nProcs_
bool distributed_
const labelList ioRanks_
HashTable< dirIndexList > procsDirs_
std::unique_ptr< fileMonitor > monitorPtr_
Additional Inherited Members
Public Types inherited from fileOperation
enum pathType : int {
NOTFOUND = 0 , ABSOLUTE , OBJECT , WRITEOBJECT ,
PROCUNCOLLATED , PROCBASEOBJECT = PROCUNCOLLATED + 1 , PROCOBJECT = PROCBASEOBJECT + 1 , PARENTOBJECT ,
FINDINSTANCE , PROCUNCOLLATEDINSTANCE , PROCBASEINSTANCE , PROCINSTANCE
}
typedef Tuple2< fileName, Tuple2< pathType, int > > dirIndex
typedef List< dirIndex > dirIndexList
typedef IntRange< int > procRangeType
Static Public Member Functions inherited from fileOperation
static refPtr< fileOperation > null ()
static autoPtr< fileOperation > New (const word &handlerType, bool verbose=false)
static autoPtr< fileOperation > New (const word &handlerType, const Tuple2< label, labelList > &commAndIORanks, const bool distributedRoots, bool verbose=false)
static autoPtr< fileOperation > New (const fileOperation &origHandler, const boolUList &useProc, bool verbose=false)
static autoPtr< fileOperation > New (const fileOperation &origHandler, const bitSet &useProc, bool verbose=false)
static autoPtr< fileOperation > NewUncollated ()
static const fileOperation & fileHandler ()
static refPtr< fileOperation > fileHandler (std::nullptr_t)
static refPtr< fileOperation > fileHandler (refPtr< fileOperation > &newHandler)
static refPtr< fileOperation > fileHandler (refPtr< fileOperation > &&newHandler)
static refPtr< fileOperation > fileHandler (autoPtr< fileOperation > &&newHandler)
static int cacheLevel () noexcept
static int cacheLevel (int level) noexcept
static instantList sortTimes (const fileNameList &dirEntries, const word &constantName="constant")
static bool uniformFile (const fileNameList &names)
static bool uniformFile (const label comm, const fileName &name)
static label splitProcessorPath (const fileName &objectPath, fileName &path, fileName &procDir, fileName &local, procRangeType &group, label &nProcs)
static label detectProcessorPath (const fileName &objPath)
static labelRange subRanks (const labelUList &mainIOranks)
static labelList getGlobalHostIORanks ()
static labelList getGlobalIORanks ()
Static Protected Attributes inherited from fileOperation
static int cacheLevel_
Detailed Description
fileOperations that performs all file operations on the master processor. Requires the calls to be parallel synchronised!
Limitations
no /processor in filename
no /uniform/ in the filename
The main logic is in filePath which returns a
same path on all processors. This can either be a global file (system/controlDict, processorXXX/0/uniform/) or a collated file (processors/0/p)
same path on all processors of the local communicator (processors4_0-1/0/p)
different path on all processors (processor0/0/p)
system/controlDict: filePath worldmaster: <globalRoot>/system/controlDict localmaster: ,, slave : ,,
processor0/uniform/time filePath worldmaster: <globalRoot>/processorXXX/uniform/time localmaster: ,, slave : ,,
processors0/0/p processors10/0/p processors10_2-4/0/p
Definition at line 78 of file masterUncollatedFileOperation.H.
Constructor & Destructor Documentation
masterUncollatedFileOperation() [1/2]
masterUncollatedFileOperation (bool verbose = false) explicit
Definition at line 718 of file masterUncollatedFileOperation.C.
masterUncollatedFileOperation() [2/2]
masterUncollatedFileOperation (const Tuple2< label, labelList > & commAndIORanks, const bool distributedRoots, bool verbose = false) explicit
Definition at line 734 of file masterUncollatedFileOperation.C.
~masterUncollatedFileOperation()
~masterUncollatedFileOperation () virtual
Definition at line 758 of file masterUncollatedFileOperation.C.
References UPstream::freeCommunicator().
Member Function Documentation
scatterList()
template<class Type > Type scatterList (const UList< Type > & allValues, const int tag, const label comm) const protected
Definition at line 28 of file masterUncollatedFileOperationTemplates.C.
References fileOperation::comm(), UPstream::master(), UPstream::masterNo(), UPstream::nonBlocking, os(), and UPstream::subProcs().
masterOp() [1/2]
template<class Type , class FileOp > Type masterOp (const fileName & fName, const FileOp & fop, const int tag, const label comm) const protected
Definition at line 63 of file masterUncollatedFileOperationTemplates.C.
References Foam::endl(), Pstream::gatherList(), UPstream::master(), UPstream::myProcNo(), Foam::name(), UPstream::nProcs(), UPstream::parRun(), Foam::Pout, and UPtrList< T >::size().
masterOp() [2/2]
template<class Type , class FileOp > Type masterOp (const fileName & src, const fileName & dest, const FileOp & fop, const int tag, const label comm) const protected
Definition at line 106 of file masterUncollatedFileOperationTemplates.C.
References Foam::endl(), Pstream::gatherList(), UPstream::master(), UPstream::myProcNo(), UPstream::nProcs(), UPstream::parRun(), Foam::Pout, and UPtrList< T >::size().
findInstancePath()
Foam::word findInstancePath (const instantList & timeDirs, const instant & t) static protected
Definition at line 82 of file masterUncollatedFileOperation.C.
References Instant< T >::equal(), and forAllReverse.
filePathInfo()
Foam::fileName filePathInfo (const bool checkGlobal, const bool isFile, const IOobject & io, const dirIndexList & pDirs, const bool search, pathType & searchType, word & processorsDir, word & instance) const protected virtual
Definition at line 107 of file masterUncollatedFileOperation.C.
References fileOperation::ABSOLUTE, PtrList< T >::clear(), fileOperation::FINDINSTANCE, UPtrList< T >::first(), io(), Foam::isFile(), fileOperation::NOTFOUND, fileOperation::OBJECT, fileOperation::PARENTOBJECT, fileOperation::PROCBASEINSTANCE, fileOperation::PROCBASEOBJECT, fileOperation::PROCINSTANCE, fileOperation::PROCOBJECT, fileOperation::PROCUNCOLLATED, fileOperation::PROCUNCOLLATEDINSTANCE, Foam::search(), UPtrList< T >::size(), and fileOperation::WRITEOBJECT.
localObjectPath()
Foam::fileName localObjectPath (const IOobject & io, const pathType & searchType, const word & processorsDir, const word & instancePath) const protected
Definition at line 279 of file masterUncollatedFileOperation.C.
References fileOperation::ABSOLUTE, fileOperation::FINDINSTANCE, io(), UPstream::myProcNo(), Foam::name(), fileName::name(), fileOperation::NOTFOUND, NotImplemented, fileOperation::OBJECT, fileOperation::PARENTOBJECT, UPstream::parRun(), fileOperation::PROCBASEINSTANCE, fileOperation::PROCBASEOBJECT, fileOperation::PROCINSTANCE, fileOperation::PROCOBJECT, fileOperation::PROCUNCOLLATED, fileOperation::PROCUNCOLLATEDINSTANCE, UPstream::worldComm, and fileOperation::WRITEOBJECT.
Referenced by collatedFileOperation::objectPath().
readAndSend()
void readAndSend (const fileName & filePath, const labelUList & recvProcs, PstreamBuffers & pBufs) static protected
Definition at line 421 of file masterUncollatedFileOperation.C.
References IOstreamOption::BINARY, IOstreamOption::COMPRESSED, UPtrList< T >::empty(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::fileSize(), os(), Foam::Pout, and UPtrList< T >::size().
read() [1/2]
Foam::autoPtr< Foam::ISstream > read (IOobject & io, const label comm, const bool uniform, const fileNameList & filePaths, const boolUList & readOnProcs) static protected
Definition at line 498 of file masterUncollatedFileOperation.C.
References UPstream::allProcs(), UPtrList< T >::empty(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, io(), UPstream::master(), UPstream::masterNo(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nProcs(), Foam::Pout, UPstream::procID(), PtrList< T >::push_back(), UPtrList< T >::size(), and UPstream::subProcs().
exists() [1/2]
bool exists (const dirIndexList & pDirs, IOobject & io) const protected
Definition at line 1365 of file masterUncollatedFileOperation.C.
References UPtrList< T >::empty(), UPtrList< T >::first(), io(), Foam::isFile(), and word::null.
TypeName()
TypeName ("masterUncollated")
storeComm()
void storeComm () const virtual
Implements fileOperation.
Reimplemented in collatedFileOperation, hostCollatedFileOperation, and hostUncollatedFileOperation.
Definition at line 749 of file masterUncollatedFileOperation.C.
mkDir()
bool mkDir (const fileName & dir, mode_t mode = 0777) const virtual
Implements fileOperation.
Definition at line 767 of file masterUncollatedFileOperation.C.
References Foam::mode(), and UPstream::msgType().
chMod()
bool chMod (const fileName & fName, const mode_t mode) const virtual
Implements fileOperation.
Definition at line 783 of file masterUncollatedFileOperation.C.
References Foam::mode(), and UPstream::msgType().
mode()
mode_t mode (const fileName & fName, const bool followLink = true) const virtual
Implements fileOperation.
Definition at line 799 of file masterUncollatedFileOperation.C.
References UPstream::msgType().
type()
Foam::fileName::Type type (const fileName & fName, const bool followLink = true) const virtual
Implements fileOperation.
Definition at line 815 of file masterUncollatedFileOperation.C.
References UPstream::msgType().
Referenced by collatedFileOperation::printBanner().
exists() [2/2]
bool exists (const fileName & fName, const bool checkGzip = true, const bool followLink = true) const virtual
Implements fileOperation.
Definition at line 834 of file masterUncollatedFileOperation.C.
References UPstream::msgType().
isDir()
bool isDir (const fileName & fName, const bool followLink = true) const virtual
Implements fileOperation.
Definition at line 851 of file masterUncollatedFileOperation.C.
References UPstream::msgType().
isFile()
bool isFile (const fileName & fName, const bool checkGzip = true, const bool followLink = true) const virtual
Implements fileOperation.
Definition at line 867 of file masterUncollatedFileOperation.C.
References UPstream::msgType().
fileSize()
off_t fileSize (const fileName & fName, const bool followLink = true) const virtual
Implements fileOperation.
Definition at line 884 of file masterUncollatedFileOperation.C.
References UPstream::msgType().
lastModified()
time_t lastModified (const fileName & fName, const bool followLink = true) const virtual
Implements fileOperation.
Definition at line 900 of file masterUncollatedFileOperation.C.
References UPstream::msgType(), and UPstream::worldComm.
highResLastModified()
double highResLastModified (const fileName & fName, const bool followLink = true) const virtual
Implements fileOperation.
Definition at line 916 of file masterUncollatedFileOperation.C.
References UPstream::msgType(), and UPstream::worldComm.
readDir()
Foam::fileNameList readDir (const fileName & dir, const fileName::Type type = fileName::FILE, const bool filtergz = true, const bool followLink = true) const virtual
Implements fileOperation.
Definition at line 980 of file masterUncollatedFileOperation.C.
References UPstream::msgType(), and Foam::type().
cp()
bool cp (const fileName & src, const fileName & dst, const bool followLink = true) const virtual
Implements fileOperation.
Definition at line 998 of file masterUncollatedFileOperation.C.
References UPstream::msgType().
ln()
bool ln (const fileName & src, const fileName & dst) const virtual
Implements fileOperation.
Definition at line 1016 of file masterUncollatedFileOperation.C.
References UPstream::msgType().
mv()
bool mv (const fileName & src, const fileName & dst, const bool followLink = false) const virtual
Implements fileOperation.
Definition at line 1033 of file masterUncollatedFileOperation.C.
References UPstream::msgType().
mvBak()
bool mvBak (const fileName & fName, const std::string & ext = "bak") const virtual
Implements fileOperation.
Definition at line 932 of file masterUncollatedFileOperation.C.
References UPstream::msgType().
rm()
bool rm (const fileName & fName) const virtual
Implements fileOperation.
Definition at line 948 of file masterUncollatedFileOperation.C.
References UPstream::msgType().
rmDir()
bool rmDir (const fileName & dir, const bool silent = false, const bool emptyOnly = false) const virtual
Implements fileOperation.
Definition at line 963 of file masterUncollatedFileOperation.C.
References UPstream::msgType().
filePath()
Foam::fileName filePath (const bool checkGlobal, const IOobject & io, const word & typeName, const bool search) const virtual
Implements fileOperation.
Definition at line 1053 of file masterUncollatedFileOperation.C.
References fileOperation::ABSOLUTE, Pstream::broadcast(), Pstream::broadcasts(), fileOperation::cacheLevel(), Foam::endl(), fileOperation::FINDINSTANCE, io(), UPstream::master(), UPstream::msgType(), fileOperation::NOTFOUND, fileOperation::OBJECT, fileOperation::PARENTOBJECT, UPstream::parRun(), fileOperation::pathTypeNames_, Foam::Pout, fileOperation::PROCBASEINSTANCE, fileOperation::PROCBASEOBJECT, fileOperation::PROCINSTANCE, fileOperation::PROCOBJECT, fileOperation::PROCUNCOLLATED, fileOperation::PROCUNCOLLATEDINSTANCE, Foam::search(), UPstream::worldComm, and fileOperation::WRITEOBJECT.
dirPath()
Foam::fileName dirPath (const bool checkGlobal, const IOobject & io, const bool search) const virtual
Implements fileOperation.
Definition at line 1209 of file masterUncollatedFileOperation.C.
References fileOperation::ABSOLUTE, Pstream::broadcast(), Pstream::broadcasts(), fileOperation::cacheLevel(), Foam::endl(), fileOperation::FINDINSTANCE, io(), UPstream::master(), UPstream::msgType(), fileOperation::NOTFOUND, fileOperation::OBJECT, fileOperation::PARENTOBJECT, UPstream::parRun(), fileOperation::pathTypeNames_, Foam::Pout, fileOperation::PROCBASEINSTANCE, fileOperation::PROCBASEOBJECT, fileOperation::PROCINSTANCE, fileOperation::PROCOBJECT, fileOperation::PROCUNCOLLATED, fileOperation::PROCUNCOLLATEDINSTANCE, Foam::search(), UPstream::worldComm, and fileOperation::WRITEOBJECT.
readObjects()
Foam::fileNameList readObjects (const objectRegistry & db, const fileName & instance, const fileName & local, word & newInstance) const virtual
Reimplemented from fileOperation.
Definition at line 1646 of file masterUncollatedFileOperation.C.
References Pstream::broadcasts(), fileOperation::cacheLevel(), PtrList< T >::clear(), UPtrList< T >::empty(), Foam::endl(), Instant< T >::equal(), fileOperation::findTimes(), forAllReverse, local, UPstream::master(), Foam::name(), IOobject::objectPath(), UPstream::parRun(), Foam::Pout, fileOperation::readObjects(), objectRegistry::time(), and UPstream::worldComm.
readHeader()
bool readHeader (IOobject & io, const fileName & fName, const word & typeName) const virtual
Implements fileOperation.
Definition at line 1733 of file masterUncollatedFileOperation.C.
References Pstream::broadcast(), Pstream::broadcasts(), Foam::endl(), forAll, Pstream::gatherList(), io(), UPstream::master(), UPstream::masterNo(), UPstream::msgType(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nProcs(), os(), Foam::Pout, decomposedBlockData::readHeader(), List< T >::resize(), PtrList< T >::resize(), fileOperation::uniformFile(), and UPstream::worldComm.
readStream()
Foam::autoPtr< Foam::ISstream > readStream (regIOobject & io, const fileName & fName, const word & typeName, const bool readOnProc = true) const virtual
Implements fileOperation.
Definition at line 1878 of file masterUncollatedFileOperation.C.
References Pstream::broadcast(), PtrList< T >::clear(), UPtrList< T >::empty(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::fileSize(), Foam::flatOutput(), Pstream::gatherList(), io(), decomposedBlockData::isCollatedType(), local, UPstream::master(), UPstream::msgType(), UPstream::myProcNo(), OSstream::name(), UPstream::nonBlocking, UPstream::nProcs(), UPstream::parRun(), path(), Foam::Pout, Foam::read(), decomposedBlockData::readBlock(), decomposedBlockData::readBlocks(), UPstream::reduceOr(), PtrList< T >::resize(), UPstream::scheduled, fileOperation::uniformFile(), and UPstream::worldComm.
read() [2/2]
bool read (regIOobject & io, const bool masterOnly, const IOstreamOption::streamFormat format, const word & typeName) const virtual
Implements fileOperation.
Definition at line 2131 of file masterUncollatedFileOperation.C.
References Pstream::broadcasts(), fileOperation::cacheLevel(), Foam::endl(), format(), io(), UPstream::master(), UPstream::masterNo(), UPstream::myProcNo(), OSstream::name(), UPstream::parRun(), Foam::Pout, and UPstream::worldComm.
writeObject()
bool writeObject (const regIOobject & io, IOstreamOption streamOpt = IOstreamOption(), const bool writeOnProc = true) const virtual
Reimplemented from fileOperation.
Reimplemented in collatedFileOperation.
Definition at line 2227 of file masterUncollatedFileOperation.C.
References Foam::endl(), io(), os(), Foam::Pout, setTime(), and IOobject::writeEndDivider().
NewIFstream()
Foam::autoPtr< Foam::ISstream > NewIFstream (const fileName & filePath) const virtual
Implements fileOperation.
Definition at line 2395 of file masterUncollatedFileOperation.C.
References UPtrList< T >::empty(), Foam::endl(), Pstream::gatherList(), Foam::identity(), UPstream::master(), UPstream::masterNo(), UPstream::msgType(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nProcs(), UPstream::parRun(), Foam::Pout, UPtrList< T >::size(), UPstream::subProcs(), and fileOperation::uniformFile().
NewOFstream() [1/2]
Foam::autoPtr< Foam::OSstream > NewOFstream (const fileName & pathname, IOstreamOption streamOpt = IOstreamOption(), const bool writeOnProc = true) const virtual
Implements fileOperation.
Definition at line 2506 of file masterUncollatedFileOperation.C.
References IOstreamOption::NON_APPEND.
NewOFstream() [2/2]
Foam::autoPtr< Foam::OSstream > NewOFstream (IOstreamOption::atomicType atomic, const fileName & pathname, IOstreamOption streamOpt = IOstreamOption(), const bool writeOnProc = true) const virtual
Implements fileOperation.
Definition at line 2528 of file masterUncollatedFileOperation.C.
References IOstreamOption::NON_APPEND.
addWatch()
Foam::label addWatch (const fileName & fName) const virtual
Reimplemented from fileOperation.
Definition at line 2633 of file masterUncollatedFileOperation.C.
References Pstream::broadcast(), UPstream::master(), UPstream::parRun(), and UPstream::worldComm.
removeWatch()
bool removeWatch (const label watchIndex) const virtual
Reimplemented from fileOperation.
Definition at line 2649 of file masterUncollatedFileOperation.C.
References Pstream::broadcast(), UPstream::master(), UPstream::parRun(), and UPstream::worldComm.
findWatch()
Foam::label findWatch (const labelList & watchIndices, const fileName & fName) const virtual
Reimplemented from fileOperation.
Definition at line 2665 of file masterUncollatedFileOperation.C.
References Pstream::broadcast(), forAll, UPstream::master(), UPstream::parRun(), and UPstream::worldComm.
addWatches()
void addWatches (regIOobject & rio, const fileNameList & files) const virtual
Reimplemented from fileOperation.
Definition at line 2690 of file masterUncollatedFileOperation.C.
References PtrList< T >::append(), and f().
getFile()
Foam::fileName getFile (const label watchIndex) const virtual
Reimplemented from fileOperation.
Definition at line 2727 of file masterUncollatedFileOperation.C.
References Pstream::broadcast(), UPstream::master(), UPstream::parRun(), and UPstream::worldComm.
updateStates()
void updateStates (const bool masterOnly, const bool syncPar) const virtual
Reimplemented from fileOperation.
Definition at line 2743 of file masterUncollatedFileOperation.C.
References UPstream::master(), UPstream::parRun(), and UPstream::worldComm.
getState()
Foam::fileMonitor::fileState getState (const label watchFd) const virtual
Reimplemented from fileOperation.
Definition at line 2757 of file masterUncollatedFileOperation.C.
References Pstream::broadcast(), UPstream::master(), UPstream::parRun(), fileMonitor::UNMODIFIED, and UPstream::worldComm.
setUnmodified()
void setUnmodified (const label watchFd) const virtual
Reimplemented from fileOperation.
Definition at line 2773 of file masterUncollatedFileOperation.C.
References UPstream::master(), UPstream::parRun(), and UPstream::worldComm.
findTimes()
Foam::instantList findTimes (const fileName & directory, const word & constantName) const virtual
Reimplemented from fileOperation.
Definition at line 2269 of file masterUncollatedFileOperation.C.
References Pstream::broadcast(), fileOperation::cacheLevel(), Foam::endl(), fileOperation::findTimes(), Foam::flatOutput(), UPstream::master(), Foam::nl, UPstream::parRun(), Foam::Pout, and UPstream::worldComm.
findInstance()
Foam::IOobject findInstance (const IOobject & io, const scalar startValue, const word & stopInstance) const virtual
Reimplemented from fileOperation.
Definition at line 1414 of file masterUncollatedFileOperation.C.
References Pstream::broadcast(), fileOperation::cacheLevel(), TimePaths::constant(), UPtrList< T >::empty(), Foam::endl(), Foam::exists(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, io(), UPstream::master(), OSstream::name(), Foam::name(), UPstream::parRun(), Foam::Pout, UPtrList< T >::size(), Time::timeName(), TimePaths::times(), and UPstream::worldComm.
setTime()
void setTime (const Time & tm) const virtual
Reimplemented from fileOperation.
Definition at line 2327 of file masterUncollatedFileOperation.C.
References PtrList< T >::append(), UPtrList< T >::empty(), Foam::endl(), Foam::findSortedIndex(), UPtrList< T >::last(), Foam::Pout, fileOperation::setTime(), UPtrList< T >::size(), and Foam::stableSort().
flush()
void flush () const virtual
Reimplemented from fileOperation.
Reimplemented in collatedFileOperation.
Definition at line 2551 of file masterUncollatedFileOperation.C.
References fileOperation::flush().
Referenced by collatedFileOperation::flush().
sync()
void sync () virtual
Reimplemented from fileOperation.
Definition at line 2558 of file masterUncollatedFileOperation.C.
References Pstream::broadcasts(), Foam::endl(), forAll, forAllConstIters, local, UPstream::master(), UPstream::myProcNo(), Foam::name(), Foam::New(), UPstream::parRun(), path(), Foam::Pout, List< T >::resize(), PtrList< T >::resize(), fileOperation::sync(), and UPstream::worldComm.
times()
const HashPtrTable< DynamicList< instant > > & times () const inline noexcept
Definition at line 774 of file masterUncollatedFileOperation.H.
References masterUncollatedFileOperation::times_.
Member Data Documentation
times_
HashPtrTable<DynamicList<instant> > times_ mutable protected
Definition at line 99 of file masterUncollatedFileOperation.H.
Referenced by masterUncollatedFileOperation::times().
maxMasterFileBufferSize
float maxMasterFileBufferSize static
Definition at line 478 of file masterUncollatedFileOperation.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/global/fileOperations/masterUncollatedFileOperation/masterUncollatedFileOperation.H
src/OpenFOAM/global/fileOperations/masterUncollatedFileOperation/masterUncollatedFileOperation.C
src/OpenFOAM/global/fileOperations/masterUncollatedFileOperation/masterUncollatedFileOperationTemplates.C