OpenFOAM: mesh Class Reference
mesh Class Reference
glTF mesh
#include <foamGltfMesh.H>
Public Member Functions
mesh ()
mesh (const word &name)
~mesh ()=default
label & accessorId () noexcept
void addField (const word &name, const label accessorId)
void addColour (const label accessorId)
void write (Ostream &os) const
Public Member Functions inherited from base
base ()
base (const word &name)
~base ()=default
label & id () noexcept
const word & name () const noexcept
void write (Ostream &os) const
void operator= (const base &gltf)
Additional Inherited Members
Protected Attributes inherited from base
word name_
label id_
Detailed Description
glTF mesh
Note
Implements the glTF v2 specification
Source files
foamGltfMesh.H
foamGltfMesh.C
Definition at line 60 of file foamGltfMesh.H.
Constructor & Destructor Documentation
mesh() [1/2]
mesh ()
Definition at line 25 of file foamGltfMesh.C.
mesh() [2/2]
mesh (const word & name) explicit
Definition at line 34 of file foamGltfMesh.C.
~mesh()
~mesh () default
Member Function Documentation
accessorId()
Foam::label & accessorId () noexcept
Definition at line 45 of file foamGltfMesh.C.
addField()
void addField (const word & name, const label accessorId)
Definition at line 51 of file foamGltfMesh.C.
References PtrList< T >::append(), and Foam::name().
addColour()
void addColour (const label accessorId)
Definition at line 57 of file foamGltfMesh.C.
References PtrList< T >::append(), and Foam::name().
write()
void write (Ostream & os) const
Definition at line 70 of file foamGltfMesh.C.
References Foam::decrIndent(), f(), UPtrList< T >::first(), Foam::incrIndent(), Foam::indent(), Foam::nl, os(), and base::write().
The documentation for this class was generated from the following files:
src/fileFormats/gltf/foamGltfMesh.H
src/fileFormats/gltf/foamGltfMesh.C