OpenFOAM: electrostaticDepositionFvPatchScalarField Class Reference
electrostaticDepositionFvPatchScalarField Class Reference
Boundary conditions » Generic
The electrostaticDeposition is a boundary condition to calculate electric potential (V) on a given boundary based on film thickness (h) and film resistance (R) fields which are updated based on a given patch-normal current density field (jn), Coulombic efficiency and film resistivity.
#include <electrostaticDepositionFvPatchScalarField.H>
Public Member Functions
TypeName ("electrostaticDeposition")
electrostaticDepositionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
electrostaticDepositionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
electrostaticDepositionFvPatchScalarField (const electrostaticDepositionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
electrostaticDepositionFvPatchScalarField (const electrostaticDepositionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
electrostaticDepositionFvPatchScalarField (const electrostaticDepositionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
const scalarField & h () const noexcept
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
tmp< scalarField > sigma () const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
The electrostaticDeposition is a boundary condition to calculate electric potential (V) on a given boundary based on film thickness (h) and film resistance (R) fields which are updated based on a given patch-normal current density field (jn), Coulombic efficiency and film resistivity.
where
= Patch-normal current density [A/m^2]
= Electric potential on film-fluid interface [volt = kg m^2/(A s^3)]
= Previous time-step electric potential on the interface [volt]
= Electric potential due to film resistance [volt]
= Electric potential due to body resistance [volt]
= Initial electric potential [volt]
= Film resistance (finite increment) [ohm m^2 = kg m^4/(A^2 s^3)]
= Body resistance [ohm m^2 = kg m^4/(A^2 s^3)]
= Isotropic film resistivity [ohm m = kg m^3/(A^2 s^3)]
= Film thickness [m]
= Volumetric Coulombic efficiency [m^3/(A s)]
= Minimum current density for deposition onset [A/m^2]
= Isotropic conductivity of mixture [S/m = A^2 s^3/(kg m^3)]
= Patch-normal unit vector [-]
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type                    electrostaticDeposition;
    h                       <scalarField>;
    CoulombicEfficiency     <PatchFunction1>;
    resistivity             <PatchFunction1>;
    // Conditional mandatory entries
        // Option-1: single-phase
        sigma       <scalar>;
        // Option-2: multiphase
        phases
        {
            alpha.air
            {
                sigma       <scalar>;
            }
            alpha.water
            {
                sigma       <scalar>;
            }
            alpha.mercury
            {
                sigma       <scalar>;
            }
            ...
        }
    // Optional entries
    jMin                    <scalar>;
    qMin                    <scalar>;
    Rbody                   <scalar>;
    Vi                      <scalar>;
    Vanode                  <scalar>;
    qCumulative             <scalarField>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: electrostaticDeposition word yes -
h Film thickness scalarField yes -
CoulombicEfficiency
Coulombic efficiency
PatchFunction1<scalar> yes -
resistivity
Isotropic film resistivity
PatchFunction1<scalar> yes -
sigma Isotropic electrical conductivity of phase scalar yes -
jMin Minimum current density for deposition onset scalar no 0
qMin
Minimum accumulative specific charge for deposition onset
scalar no 0
Rbody
Resistance due to main body and/or
pretreatment layers
scalar no 0
Vi Initial electric potential scalar no 0
Vanode Anode electric potential scalar no GREAT
qCumulative
Accumulative specific charge [A s/m^2]
scalarField no 0
The inherited entries are elaborated in:
fixedValueFvPatchFields.H
PatchFunction1.H
Note
Depletion or abrasion of material due to negative current is not allowed.
When accumulative specific charge (qCumulative) is less than minimum accumulative specific charge (qMin), no deposition occurs.
Boundary-condition updates are not allowed during outer corrections to prevent spurious accumulation of film thickness.
resistivity, jMin, qMin and Rbody are always non-negative.
Source files
electrostaticDepositionFvPatchScalarField.H
electrostaticDepositionFvPatchScalarField.C
Definition at line 315 of file electrostaticDepositionFvPatchScalarField.H.
Constructor & Destructor Documentation
electrostaticDepositionFvPatchScalarField() [1/5]
electrostaticDepositionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 132 of file electrostaticDepositionFvPatchScalarField.C.
electrostaticDepositionFvPatchScalarField() [2/5]
electrostaticDepositionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 160 of file electrostaticDepositionFvPatchScalarField.C.
References dict, Foam::dimCurrent, Foam::dimLength, Foam::dimMass, Foam::dimTime, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, forAll, MinMax< scalar >::ge(), dictionary::getCheck(), Foam::nl, phasei, Foam::pow3(), PtrList< T >::set(), List< T >::setSize(), PtrList< T >::setSize(), and Foam::sqr().
electrostaticDepositionFvPatchScalarField() [3/5]
electrostaticDepositionFvPatchScalarField (const electrostaticDepositionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 259 of file electrostaticDepositionFvPatchScalarField.C.
electrostaticDepositionFvPatchScalarField() [4/5]
electrostaticDepositionFvPatchScalarField (const electrostaticDepositionFvPatchScalarField & ptf)
Definition at line 289 of file electrostaticDepositionFvPatchScalarField.C.
electrostaticDepositionFvPatchScalarField() [5/5]
electrostaticDepositionFvPatchScalarField (const electrostaticDepositionFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 316 of file electrostaticDepositionFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("electrostaticDeposition")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 439 of file electrostaticDepositionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 455 of file electrostaticDepositionFvPatchScalarField.H.
h()
const scalarField & h () const inline noexcept
Definition at line 472 of file electrostaticDepositionFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 346 of file electrostaticDepositionFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 369 of file electrostaticDepositionFvPatchScalarField.C.
sigma()
Foam::tmp< Foam::scalarField > sigma () const
Definition at line 397 of file electrostaticDepositionFvPatchScalarField.C.
References tmp< T >::New(), and UPtrList< T >::size().
updateCoeffs()
void updateCoeffs () virtual
Definition at line 419 of file electrostaticDepositionFvPatchScalarField.C.
References Foam::endl(), forAll, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::Info, UPstream::master(), Foam::max(), Foam::min(), Foam::nl, Foam::operator==(), and timeIndex.
write()
void write (Ostream & os) const virtual
Definition at line 520 of file electrostaticDepositionFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/electrostaticDeposition/electrostaticDepositionFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/electrostaticDeposition/electrostaticDepositionFvPatchScalarField.C