OpenFOAM: directionalDiffusivity Class Reference
directionalDiffusivity Class Reference
Directional finite volume mesh motion diffusivity.
#include <directionalDiffusivity.H>
Public Member Functions
TypeName ("directional")
directionalDiffusivity (const fvMesh &mesh, Istream &mdData)
virtual ~directionalDiffusivity ()
virtual void correct ()
Public Member Functions inherited from uniformDiffusivity
TypeName ("uniform")
uniformDiffusivity (const fvMesh &mesh, Istream &mdData)
virtual ~uniformDiffusivity ()
virtual tmp< surfaceScalarField > operator() () const
Public Member Functions inherited from motionDiffusivity
TypeName ("motionDiffusivity")
declareRunTimeSelectionTable (autoPtr, motionDiffusivity, Istream,(const fvMesh &mesh, Istream &mdData),(mesh, mdData))
motionDiffusivity (const fvMesh &mesh)
virtual ~motionDiffusivity ()
const fvMesh & mesh () const
Additional Inherited Members
Static Public Member Functions inherited from motionDiffusivity
static autoPtr< motionDiffusivity > New (const fvMesh &mesh, Istream &mdData)
Protected Attributes inherited from uniformDiffusivity
surfaceScalarField faceDiffusivity_
Detailed Description
Directional finite volume mesh motion diffusivity.
Source files
directionalDiffusivity.H
directionalDiffusivity.C
Definition at line 46 of file directionalDiffusivity.H.
Constructor & Destructor Documentation
directionalDiffusivity()
directionalDiffusivity (const fvMesh & mesh, Istream & mdData)
Definition at line 41 of file directionalDiffusivity.C.
References directionalDiffusivity::correct().
~directionalDiffusivity()
~directionalDiffusivity () virtual
Definition at line 56 of file directionalDiffusivity.C.
Member Function Documentation
TypeName()
TypeName ("directional")
correct()
void correct () virtual
Reimplemented from uniformDiffusivity.
Definition at line 62 of file directionalDiffusivity.C.
References Foam::cmptMultiply(), mesh, and n.
Referenced by directionalDiffusivity::directionalDiffusivity().
The documentation for this class was generated from the following files:
src/fvMotionSolver/motionDiffusivity/directional/directionalDiffusivity.H
src/fvMotionSolver/motionDiffusivity/directional/directionalDiffusivity.C