OpenFOAM: constAnIsoSolidTransport< Thermo > Class Template Reference
constAnIsoSolidTransport< Thermo > Class Template Reference
Constant properties Transport package. Templated into a given Thermodynamics package (needed for thermal conductivity).
#include <constAnIsoSolidTransport.H>
Public Member Functions
constAnIsoSolidTransport (const word &, const constAnIsoSolidTransport &)
constAnIsoSolidTransport (const dictionary &dict)
scalar kappa (const scalar p, const scalar T) const
vector Kappa (const scalar p, const scalar T) const
scalar mu (const scalar p, const scalar T) const
vector alphah (const scalar p, const scalar T) const
void write (Ostream &os) const
void operator+= (const constAnIsoSolidTransport &)
Static Public Member Functions
static autoPtr< constAnIsoSolidTransport > New (const dictionary &dict)
static word typeName ()
Static Public Attributes
static const bool isotropic = false
Friends
constAnIsoSolidTransport operator* (const scalar, const constAnIsoSolidTransport &)
Ostream & operator<< (Ostream &, const constAnIsoSolidTransport &)
Detailed Description
template<class Thermo>
class Foam::constAnIsoSolidTransport< Thermo >
Constant properties Transport package. Templated into a given Thermodynamics package (needed for thermal conductivity).
Source files
constAnIsoSolidTransport.H
constAnIsoSolidTransportI.H
constAnIsoSolidTransport.C
Definition at line 68 of file constAnIsoSolidTransport.H.
Constructor & Destructor Documentation
constAnIsoSolidTransport() [1/2]
template<class Thermo > constAnIsoSolidTransport (const word & name, const constAnIsoSolidTransport< Thermo > & ct) inline
Definition at line 36 of file constAnIsoSolidTransportI.H.
References Foam::name().
constAnIsoSolidTransport() [2/2]
template<class Thermo > constAnIsoSolidTransport (const dictionary & dict) explicit
Definition at line 27 of file constAnIsoSolidTransport.C.
Member Function Documentation
New()
template<class Thermo > Foam::autoPtr< Foam::constAnIsoSolidTransport< Thermo > > New (const dictionary & dict) inline static
Definition at line 49 of file constAnIsoSolidTransportI.H.
References dict, and Foam::New().
typeName()
template<class Thermo > static word typeName () inline static
Definition at line 111 of file constAnIsoSolidTransport.H.
kappa()
template<class Thermo > Foam::scalar kappa (const scalar p, const scalar T) const inline
Definition at line 60 of file constAnIsoSolidTransportI.H.
References Foam::mag().
Kappa()
template<class Thermo > Foam::vector Kappa (const scalar p, const scalar T) const inline
Definition at line 67 of file constAnIsoSolidTransportI.H.
mu()
template<class Thermo > Foam::scalar mu (const scalar p, const scalar T) const inline
Definition at line 75 of file constAnIsoSolidTransportI.H.
References NotImplemented.
alphah()
template<class Thermo > Foam::vector alphah (const scalar p, const scalar T) const inline
Definition at line 84 of file constAnIsoSolidTransportI.H.
References Cp, and T.
write()
template<class Thermo > void write (Ostream & os) const
operator+=()
template<class Thermo > void operator+= (const constAnIsoSolidTransport< Thermo > &) inline
Definition at line 93 of file constAnIsoSolidTransportI.H.
References Y.
Friends And Related Symbol Documentation
operator*
template<class Thermo > constAnIsoSolidTransport operator* (const scalar , const constAnIsoSolidTransport< Thermo > &) friend
operator<<
template<class Thermo > Ostream & operator<< (Ostream & , const constAnIsoSolidTransport< Thermo > &) friend
Member Data Documentation
isotropic
template<class Thermo > const bool isotropic = false static
Definition at line 117 of file constAnIsoSolidTransport.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidSpecie/transport/const/constAnIsoSolidTransport.H
src/thermophysicalModels/solidSpecie/transport/const/constAnIsoSolidTransport.C
src/thermophysicalModels/solidSpecie/transport/const/constAnIsoSolidTransportI.H