OpenFOAM: option Class Reference
option Class Reference
Base abstract class for handling finite area options (i.e. faOption).
#include <faOption.H>
Classes
class iNew
Public Member Functions
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
const word & regionName () const noexcept
const faMesh & regionMesh () const
const volSurfaceMapping & vsm () const
bool active (const bool on) noexcept
virtual bool isActive ()
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (const areaScalarField &h, faMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (faMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (faMatrix< vector > &eqn, const label fieldi)
virtual void constrain (faMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (faMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (faMatrix< tensor > &eqn, const label fieldi)
virtual void correct (areaScalarField &field)
virtual void correct (areaVectorField &field)
virtual void correct (areaSphericalTensorField &field)
virtual void correct (areaSymmTensorField &field)
virtual void correct (areaTensorField &field)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
virtual bool read (const dictionary &dict)
Static Public Member Functions
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes
bool log
Protected Member Functions
void resetApplied ()
Protected Attributes
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
word regionName_
Detailed Description
Base abstract class for handling finite area options (i.e. faOption).
Usage
Minimal example by using constant/faOptions:
<userDefinedName1>
{
    // Mandatory entries (unmodifiable)
    type              <faOptionName>;
    // Mandatory entries (runtime modifiable)
    region            <regionName>;
    // Optional entries (unmodifiable/runtime modifiable)
    <faOption>Coeffs
    {
        // subdictionary entries
    }
    // Optional entries (runtime modifiable)
    active            true;
    log               true;
}
where the entries mean:
Property Description Type Reqd Dflt
type Name of operand faOption word yes -
region Name of operand region word yes -
<faOption>Coeffs
Dictionary containing settings of
the selected faOption settings
dictionary no -
active Flag to (de)activate faOption bool no true
log Flag to log faOption-related info bool no true
Note
Source/sink options are to be added to the right-hand side of equations.
Source files
faOption.H
faOption.C
faOptionIO.C
Definition at line 129 of file faOption.H.
Constructor & Destructor Documentation
option()
option (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 47 of file faOption.C.
References Foam::decrIndent(), Foam::endl(), Foam::incrIndent(), Foam::indent(), Log, and option::name_.
~option()
virtual ~option () virtual default
Member Function Documentation
resetApplied()
void resetApplied () protected
Definition at line 38 of file faOption.C.
References option::applied_, option::fieldNames_, List< T >::resize_nocopy(), and UList< T >::size().
Referenced by contactHeatFluxSource::contactHeatFluxSource(), externalFileSource::externalFileSource(), externalHeatFluxSource::externalHeatFluxSource(), and jouleHeatingSource::jouleHeatingSource().
TypeName()
TypeName ("option")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , option , dictionary , (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh) , (name, modelType, dict, mesh))
clone()
autoPtr< option > clone () const inline
Definition at line 225 of file faOption.H.
References NotImplemented.
New()
Foam::autoPtr< Foam::fa::option > New (const word & name, const dictionary & dict, const fvMesh & mesh) static
Definition at line 74 of file faOption.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::indent(), Foam::Info, mesh, and Foam::name().
Referenced by option::iNew::operator()(), and optionList::reset().
name()
const Foam::word & name () const inline noexcept
Definition at line 23 of file faOptionI.H.
References option::name_.
Referenced by contactHeatFluxSource::addSup().
mesh()
const Foam::fvMesh & mesh () const inline noexcept
Definition at line 29 of file faOptionI.H.
coeffs()
const Foam::dictionary & coeffs () const inline noexcept
Definition at line 35 of file faOptionI.H.
active() [1/2]
bool active () const inline noexcept
Definition at line 41 of file faOptionI.H.
setApplied()
void setApplied (const label fieldi) inline
Definition at line 55 of file faOptionI.H.
regionName()
const Foam::word & regionName () const inline noexcept
Definition at line 61 of file faOptionI.H.
regionMesh()
const Foam::faMesh & regionMesh () const inline
Definition at line 67 of file faOptionI.H.
vsm()
const Foam::volSurfaceMapping & vsm () const inline
Definition at line 77 of file faOptionI.H.
active() [2/2]
bool active (const bool on) inline noexcept
Definition at line 47 of file faOptionI.H.
isActive()
bool isActive () virtual
Reimplemented in faceSetOption.
Definition at line 112 of file faOption.C.
Referenced by faceSetOption::isActive().
applyToField()
Foam::label applyToField (const word & fieldName) const virtual
Definition at line 118 of file faOption.C.
checkApplied()
void checkApplied () const virtual
Definition at line 124 of file faOption.C.
References Foam::endl(), forAll, and WarningInFunction.
addSup() [1/10]
void addSup (const areaScalarField & h, faMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented in externalFileSource.
Definition at line 138 of file faOption.C.
addSup() [2/10]
void addSup (const areaScalarField & h, faMatrix< vector > & eqn, const label fieldi) virtual
Definition at line 147 of file faOption.C.
addSup() [3/10]
void addSup (const areaScalarField & h, faMatrix< symmTensor > & eqn, const label fieldi) virtual
Definition at line 165 of file faOption.C.
addSup() [4/10]
void addSup (const areaScalarField & h, faMatrix< sphericalTensor > & eqn, const label fieldi) virtual
Definition at line 156 of file faOption.C.
addSup() [5/10]
void addSup (const areaScalarField & h, faMatrix< tensor > & eqn, const label fieldi) virtual
Definition at line 174 of file faOption.C.
addSup() [6/10]
void addSup (const areaScalarField & h, const areaScalarField & rho, faMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented in contactHeatFluxSource, externalHeatFluxSource, and jouleHeatingSource.
Definition at line 183 of file faOption.C.
addSup() [7/10]
void addSup (const areaScalarField & h, const areaScalarField & rho, faMatrix< vector > & eqn, const label fieldi) virtual
Definition at line 193 of file faOption.C.
addSup() [8/10]
void addSup (const areaScalarField & h, const areaScalarField & rho, faMatrix< symmTensor > & eqn, const label fieldi) virtual
Definition at line 213 of file faOption.C.
addSup() [9/10]
void addSup (const areaScalarField & h, const areaScalarField & rho, faMatrix< sphericalTensor > & eqn, const label fieldi) virtual
Definition at line 203 of file faOption.C.
addSup() [10/10]
void addSup (const areaScalarField & h, const areaScalarField & rho, faMatrix< tensor > & eqn, const label fieldi) virtual
Definition at line 223 of file faOption.C.
constrain() [1/5]
void constrain (faMatrix< scalar > & eqn, const label fieldi) virtual
Definition at line 233 of file faOption.C.
constrain() [2/5]
void constrain (faMatrix< vector > & eqn, const label fieldi) virtual
Definition at line 237 of file faOption.C.
constrain() [3/5]
void constrain (faMatrix< sphericalTensor > & eqn, const label fieldi) virtual
Definition at line 241 of file faOption.C.
constrain() [4/5]
void constrain (faMatrix< symmTensor > & eqn, const label fieldi) virtual
Definition at line 249 of file faOption.C.
constrain() [5/5]
void constrain (faMatrix< tensor > & eqn, const label fieldi) virtual
Definition at line 257 of file faOption.C.
correct() [1/5]
void correct (areaScalarField & field) virtual
Reimplemented in limitHeight.
Definition at line 261 of file faOption.C.
correct() [2/5]
void correct (areaVectorField & field) virtual
Reimplemented in limitVelocity.
Definition at line 265 of file faOption.C.
correct() [3/5]
void correct (areaSphericalTensorField & field) virtual
Definition at line 269 of file faOption.C.
correct() [4/5]
void correct (areaSymmTensorField & field) virtual
Definition at line 273 of file faOption.C.
correct() [5/5]
void correct (areaTensorField & field) virtual
Definition at line 277 of file faOption.C.
writeHeader()
void writeHeader (Ostream & os) const virtual
Definition at line 25 of file faOptionIO.C.
References option::name_, and os().
writeFooter()
void writeFooter (Ostream & os) const virtual
Definition at line 31 of file faOptionIO.C.
References os().
writeData()
void writeData (Ostream & os) const virtual
Definition at line 37 of file faOptionIO.C.
References Foam::nl, os(), and Foam::type().
read()
bool read (const dictionary & dict) virtual
Reimplemented in limitHeight, limitVelocity, faceSetOption, contactHeatFluxSource, externalFileSource, externalHeatFluxSource, and jouleHeatingSource.
Definition at line 47 of file faOptionIO.C.
References dict.
Referenced by faceSetOption::read(), contactHeatFluxSource::read(), externalFileSource::read(), externalHeatFluxSource::read(), and jouleHeatingSource::read().
Member Data Documentation
name_
const word name_ protected
Definition at line 142 of file faOption.H.
Referenced by option::name(), option::option(), and option::writeHeader().
modelType_
const word modelType_ protected
Definition at line 145 of file faOption.H.
mesh_
const fvMesh& mesh_ protected
Definition at line 148 of file faOption.H.
dict_
dictionary dict_ protected
Definition at line 151 of file faOption.H.
coeffs_
dictionary coeffs_ protected
Definition at line 154 of file faOption.H.
Referenced by faceSetOption::faceSetOption(), and jouleHeatingSource::jouleHeatingSource().
fieldNames_
wordList fieldNames_ protected
Definition at line 157 of file faOption.H.
Referenced by contactHeatFluxSource::contactHeatFluxSource(), externalFileSource::externalFileSource(), externalHeatFluxSource::externalHeatFluxSource(), jouleHeatingSource::jouleHeatingSource(), limitVelocity::limitVelocity(), and option::resetApplied().
applied_
List<bool> applied_ protected
Definition at line 160 of file faOption.H.
Referenced by limitVelocity::limitVelocity(), and option::resetApplied().
regionName_
word regionName_ protected
Definition at line 163 of file faOption.H.
log
bool log
Definition at line 189 of file faOption.H.
The documentation for this class was generated from the following files:
src/faOptions/faOption/faOption.H
src/faOptions/faOption/faOption.C
src/faOptions/faOption/faOptionI.H
src/faOptions/faOption/faOptionIO.C