OpenFOAM: SymmTensor< Cmpt > Class Template Reference
SymmTensor< Cmpt > Class Template Reference
A templated (3 x 3) symmetric tensor of objects of <T>, effectively containing 6 elements, derived from VectorSpace.
#include <SymmTensor.H>
Public Types
enum components {
XX , XY , XZ , YY ,
YZ , ZZ
}
typedef SymmTensor< label > labelType
Public Types inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
typedef VectorSpace< SymmTensor< Cmpt >, Cmpt, Ncmpts > vsType
typedef Cmpt cmptType
typedef Cmpt magType
typedef Cmpt * iterator
typedef const Cmpt * const_iterator
Public Member Functions
SymmTensor ()=default
SymmTensor (const SymmTensor &)=default
SymmTensor & operator= (const SymmTensor &)=default
SymmTensor (const Foam::zero)
template<class Cmpt2 >
SymmTensor (const VectorSpace< SymmTensor< Cmpt2 >, Cmpt2, 6 > &)
SymmTensor (const SphericalTensor< Cmpt > &)
SymmTensor (const Vector< Cmpt > &x, const Vector< Cmpt > &y, const Vector< Cmpt > &z, const bool transposed=false)
SymmTensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyy, const Cmpt tyz, const Cmpt tzz)
SymmTensor (Istream &is)
const Cmpt & xx () const noexcept
const Cmpt & xy () const noexcept
const Cmpt & xz () const noexcept
const Cmpt & yx () const noexcept
const Cmpt & yy () const noexcept
const Cmpt & yz () const noexcept
const Cmpt & zx () const noexcept
const Cmpt & zy () const noexcept
const Cmpt & zz () const noexcept
Cmpt & xx () noexcept
Cmpt & xy () noexcept
Cmpt & xz () noexcept
Cmpt & yx () noexcept
Cmpt & yy () noexcept
Cmpt & yz () noexcept
Cmpt & zx () noexcept
Cmpt & zy () noexcept
Cmpt & zz () noexcept
Vector< Cmpt > cx () const
Vector< Cmpt > cy () const
Vector< Cmpt > cz () const
template<direction Idx>
Vector< Cmpt > col () const
Vector< Cmpt > col (const direction c) const
void col (const direction c, const Vector< Cmpt > &v)
void cols (const Vector< Cmpt > &x, const Vector< Cmpt > &y, const Vector< Cmpt > &z)
Vector< Cmpt > x () const
Vector< Cmpt > y () const
Vector< Cmpt > z () const
template<direction Row>
Vector< Cmpt > row () const
Vector< Cmpt > row (const direction r) const
template<direction Idx>
void row (const Vector< Cmpt > &v)
void row (const direction r, const Vector< Cmpt > &v)
void rows (const Vector< Cmpt > &x, const Vector< Cmpt > &y, const Vector< Cmpt > &z)
Vector< Cmpt > diag () const
void diag (const Vector< Cmpt > &v)
void addDiag (const Vector< Cmpt > &v)
void subtractDiag (const Vector< Cmpt > &v)
scalar diagSqr () const
const SymmTensor< Cmpt > & T () const noexcept
Cmpt det () const
Cmpt det2D (const direction excludeCmpt) const
SymmTensor< Cmpt > adjunct () const
SymmTensor< Cmpt > cof () const
SymmTensor< Cmpt > adjunct2D (const direction excludeCmpt) const
SymmTensor< Cmpt > inv () const
SymmTensor< Cmpt > safeInv () const
SymmTensor< Cmpt > inv2D (const direction excludeCmpt) const
void operator= (const SphericalTensor< Cmpt > &)
template<Foam::direction Idx>
Foam::Vector< Cmpt > row () const
Public Member Functions inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
VectorSpace ()=default
VectorSpace (const Foam::zero)
VectorSpace (const VectorSpace< SymmTensor< Cmpt >, Cmpt, Ncmpts > &vs)
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
VectorSpace (Istream &is)
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Cmpt * data () noexcept
const ConstBlock< SubVector, BStart > block () const
const Foam::VectorSpace< SymmTensor< Cmpt >, Cmpt, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< SymmTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< SymmTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< SymmTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
Static Public Attributes
static constexpr direction rank = 2
static const SymmTensor I
Static Public Attributes inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
static constexpr direction dim
static constexpr direction nComponents
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const SymmTensor< Cmpt > zero
static const SymmTensor< Cmpt > one
static const SymmTensor< Cmpt > max
static const SymmTensor< Cmpt > min
static const SymmTensor< Cmpt > rootMax
static const SymmTensor< Cmpt > rootMin
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
static constexpr direction size () noexcept
static SymmTensor< Cmpt > uniform (const Cmpt &s)
Public Attributes inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
Cmpt v_ [Ncmpts]
Detailed Description
template<class Cmpt>
class Foam::SymmTensor< Cmpt >
A templated (3 x 3) symmetric tensor of objects of <T>, effectively containing 6 elements, derived from VectorSpace.
Source files
SymmTensor.H
SymmTensorI.H
Definition at line 50 of file SymmTensor.H.
Member Typedef Documentation
labelType
template<class Cmpt > typedef SymmTensor<label> labelType
Definition at line 59 of file SymmTensor.H.
Member Enumeration Documentation
components
template<class Cmpt > enum components
Enumerator
XX
XY
XZ
YY
YZ
ZZ
Definition at line 74 of file SymmTensor.H.
Constructor & Destructor Documentation
SymmTensor() [1/8]
template<class Cmpt > SymmTensor () default
SymmTensor() [2/8]
template<class Cmpt > SymmTensor (const SymmTensor< Cmpt > &) default
SymmTensor() [3/8]
template<class Cmpt > SymmTensor (const Foam::zero) inline
Definition at line 27 of file SymmTensorI.H.
SymmTensor() [4/8]
template<class Cmpt > template<class Cmpt2 > SymmTensor (const VectorSpace< SymmTensor< Cmpt2 >, Cmpt2, 6 > & vs) inline
Definition at line 35 of file SymmTensorI.H.
SymmTensor() [5/8]
template<class Cmpt > SymmTensor (const SphericalTensor< Cmpt > & st) inline
Definition at line 45 of file SymmTensorI.H.
References Foam::Zero.
SymmTensor() [6/8]
template<class Cmpt > SymmTensor (const Vector< Cmpt > & x, const Vector< Cmpt > & y, const Vector< Cmpt > & z, const bool transposed = false) inline
Definition at line 54 of file SymmTensorI.H.
References x, and y.
SymmTensor() [7/8]
template<class Cmpt > SymmTensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyy, const Cmpt tyz, const Cmpt tzz) inline
Definition at line 67 of file SymmTensorI.H.
SymmTensor() [8/8]
template<class Cmpt > SymmTensor (Istream & is) inline explicit
Definition at line 81 of file SymmTensorI.H.
Member Function Documentation
operator=() [1/2]
template<class Cmpt > SymmTensor & operator= (const SymmTensor< Cmpt > &) default
xx() [1/2]
template<class Cmpt > const Cmpt & xx () const inline noexcept
Definition at line 126 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XX.
Referenced by turbulentDFSEMInletFvPatchVectorField::checkStresses(), and ReynoldsStress< LESModel< BasicTurbulenceModel > >::ReynoldsStress().
xy() [1/2]
template<class Cmpt > const Cmpt & xy () const inline noexcept
Definition at line 127 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XY.
Referenced by turbulentDFSEMInletFvPatchVectorField::checkStresses().
xz() [1/2]
template<class Cmpt > const Cmpt & xz () const inline noexcept
Definition at line 128 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XZ.
yx() [1/2]
template<class Cmpt > const Cmpt & yx () const inline noexcept
Definition at line 129 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XY.
yy() [1/2]
template<class Cmpt > const Cmpt & yy () const inline noexcept
Definition at line 130 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::YY.
Referenced by turbulentDFSEMInletFvPatchVectorField::checkStresses().
yz() [1/2]
template<class Cmpt > const Cmpt & yz () const inline noexcept
Definition at line 131 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::YZ.
zx() [1/2]
template<class Cmpt > const Cmpt & zx () const inline noexcept
Definition at line 132 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XZ.
zy() [1/2]
template<class Cmpt > const Cmpt & zy () const inline noexcept
Definition at line 133 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::YZ.
zz() [1/2]
template<class Cmpt > const Cmpt & zz () const inline noexcept
Definition at line 134 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::ZZ.
xx() [2/2]
template<class Cmpt > Cmpt & xx () inline noexcept
Definition at line 136 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XX.
xy() [2/2]
template<class Cmpt > Cmpt & xy () inline noexcept
Definition at line 137 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XY.
xz() [2/2]
template<class Cmpt > Cmpt & xz () inline noexcept
Definition at line 138 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XZ.
yx() [2/2]
template<class Cmpt > Cmpt & yx () inline noexcept
Definition at line 139 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XY.
yy() [2/2]
template<class Cmpt > Cmpt & yy () inline noexcept
Definition at line 140 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::YY.
yz() [2/2]
template<class Cmpt > Cmpt & yz () inline noexcept
Definition at line 141 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::YZ.
zx() [2/2]
template<class Cmpt > Cmpt & zx () inline noexcept
Definition at line 142 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XZ.
zy() [2/2]
template<class Cmpt > Cmpt & zy () inline noexcept
Definition at line 143 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::YZ.
zz() [2/2]
template<class Cmpt > Cmpt & zz () inline noexcept
Definition at line 144 of file SymmTensor.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::ZZ.
cx()
template<class Cmpt > Vector< Cmpt > cx () const inline
Definition at line 150 of file SymmTensor.H.
References SymmTensor< Cmpt >::x().
cy()
template<class Cmpt > Vector< Cmpt > cy () const inline
Definition at line 153 of file SymmTensor.H.
References SymmTensor< Cmpt >::y().
cz()
template<class Cmpt > Vector< Cmpt > cz () const inline
Definition at line 156 of file SymmTensor.H.
References SymmTensor< Cmpt >::z().
col() [1/3]
template<class Cmpt > template<direction Idx> Vector< Cmpt > col () const inline
Definition at line 160 of file SymmTensor.H.
col() [2/3]
template<class Cmpt > Vector< Cmpt > col (const direction c) const inline
Definition at line 163 of file SymmTensor.H.
References SymmTensor< Cmpt >::row().
col() [3/3]
template<class Cmpt > void col (const direction c, const Vector< Cmpt > & v) inline
Definition at line 166 of file SymmTensor.H.
References SymmTensor< Cmpt >::row().
cols()
template<class Cmpt > void cols (const Vector< Cmpt > & x, const Vector< Cmpt > & y, const Vector< Cmpt > & z) inline
Definition at line 169 of file SymmTensor.H.
References SymmTensor< Cmpt >::rows(), SymmTensor< Cmpt >::y(), and SymmTensor< Cmpt >::z().
x()
template<class Cmpt > Foam::Vector< Cmpt > x () const inline
Definition at line 90 of file SymmTensorI.H.
Referenced by SymmTensor< Cmpt >::cx().
y()
template<class Cmpt > Foam::Vector< Cmpt > y () const inline
Definition at line 97 of file SymmTensorI.H.
Referenced by SymmTensor< Cmpt >::cols(), and SymmTensor< Cmpt >::cy().
z()
template<class Cmpt > Foam::Vector< Cmpt > z () const inline
Definition at line 104 of file SymmTensorI.H.
Referenced by SymmTensor< Cmpt >::cols(), and SymmTensor< Cmpt >::cz().
row() [1/5]
template<class Cmpt > template<direction Row> Vector< Cmpt > row () const inline
Referenced by SymmTensor< Cmpt >::col(), and SymmTensor< Cmpt >::col().
row() [2/5]
template<class Cmpt > Foam::Vector< Cmpt > row (const direction r) const inline
Definition at line 124 of file SymmTensorI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, x, y, and Foam::Zero.
row() [3/5]
template<class Cmpt > template<Foam::direction Idx> void row (const Vector< Cmpt > & v) inline
Definition at line 142 of file SymmTensorI.H.
row() [4/5]
template<class Cmpt > void row (const direction r, const Vector< Cmpt > & v) inline
Definition at line 176 of file SymmTensorI.H.
rows()
template<class Cmpt > void rows (const Vector< Cmpt > & x, const Vector< Cmpt > & y, const Vector< Cmpt > & z) inline
Definition at line 162 of file SymmTensorI.H.
References x, and y.
Referenced by SymmTensor< Cmpt >::cols().
diag() [1/2]
template<class Cmpt > Foam::Vector< Cmpt > diag () const inline
Definition at line 195 of file SymmTensorI.H.
diag() [2/2]
template<class Cmpt > void diag (const Vector< Cmpt > & v) inline
Definition at line 202 of file SymmTensorI.H.
addDiag()
template<class Cmpt > void addDiag (const Vector< Cmpt > & v) inline
Definition at line 209 of file SymmTensorI.H.
subtractDiag()
template<class Cmpt > void subtractDiag (const Vector< Cmpt > & v) inline
Definition at line 216 of file SymmTensorI.H.
diagSqr()
template<class Cmpt > Foam::scalar diagSqr () const inline
Definition at line 223 of file SymmTensorI.H.
T()
template<class Cmpt > const SymmTensor< Cmpt > & T () const inline noexcept
Definition at line 235 of file SymmTensor.H.
det()
template<class Cmpt > Cmpt det () const inline
Definition at line 235 of file SymmTensorI.H.
det2D()
template<class Cmpt > Cmpt det2D (const direction excludeCmpt) const inline
Definition at line 247 of file SymmTensorI.H.
adjunct()
template<class Cmpt > Foam::SymmTensor< Cmpt > adjunct () const inline
Definition at line 268 of file SymmTensorI.H.
cof()
template<class Cmpt > Foam::SymmTensor< Cmpt > cof () const inline
Definition at line 281 of file SymmTensorI.H.
adjunct2D()
template<class Cmpt > Foam::SymmTensor< Cmpt > adjunct2D (const direction excludeCmpt) const inline
Definition at line 289 of file SymmTensorI.H.
References Foam::Zero.
inv()
template<class Cmpt > Foam::SymmTensor< Cmpt > inv () const inline
Definition at line 341 of file SymmTensorI.H.
References Foam::abort(), Foam::det(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), and Foam::nl.
safeInv()
template<class Cmpt > Foam::SymmTensor< Cmpt > safeInv () const inline
Definition at line 361 of file SymmTensorI.H.
References Foam::det(), Foam::mag(), Foam::magSqr(), and Foam::Zero.
inv2D()
template<class Cmpt > Foam::SymmTensor< Cmpt > inv2D (const direction excludeCmpt) const inline
Definition at line 328 of file SymmTensorI.H.
operator=() [2/2]
template<class Cmpt > void operator= (const SphericalTensor< Cmpt > & st) inline
Definition at line 419 of file SymmTensorI.H.
References Foam::Zero.
row() [5/5]
template<class Cmpt > template<Foam::direction Idx> Foam::Vector< Cmpt > row () const inline
Definition at line 112 of file SymmTensorI.H.
References x, and y.
Member Data Documentation
rank
template<class Cmpt > constexpr direction rank = 2 static constexpr
Definition at line 65 of file SymmTensor.H.
I
const Foam::labelSymmTensor I static
Definition at line 70 of file SymmTensor.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/SymmTensor/SymmTensor.H
src/OpenFOAM/primitives/SymmTensor/labelSymmTensor/labelSymmTensor.C
src/OpenFOAM/primitives/SymmTensor/SymmTensorI.H