OpenFOAM: fvFieldDecomposer::processorSurfacePatchFieldDecomposer Class Reference
fvFieldDecomposer::processorSurfacePatchFieldDecomposer Class Reference
#include <fvFieldDecomposer.H>
Public Member Functions
processorSurfacePatchFieldDecomposer (const labelUList &addressingSlice)
label size () const
bool direct () const
bool hasUnmapped () const
const labelListList & addressing () const
const scalarListList & weights () const
Public Member Functions inherited from fvPatchFieldMapper
fvPatchFieldMapper ()=default
Public Member Functions inherited from FieldMapper
FieldMapper ()=default
virtual ~FieldMapper ()=default
virtual bool distributed () const
virtual const labelUList & directAddressing () const
virtual const mapDistributeBase & distributeMap () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &fld) const
Detailed Description
Definition at line 162 of file fvFieldDecomposer.H.
Constructor & Destructor Documentation
processorSurfacePatchFieldDecomposer()
processorSurfacePatchFieldDecomposer (const labelUList & addressingSlice)
Definition at line 109 of file fvFieldDecomposer.C.
References forAll, Foam::mag(), and List< T >::resize().
Member Function Documentation
size()
label size () const inline virtual
Implements FieldMapper.
Definition at line 180 of file fvFieldDecomposer.H.
References UList< T >::size().
direct()
bool direct () const inline virtual
Implements FieldMapper.
Definition at line 185 of file fvFieldDecomposer.H.
hasUnmapped()
bool hasUnmapped () const inline virtual
Implements FieldMapper.
Definition at line 191 of file fvFieldDecomposer.H.
addressing()
const labelListList & addressing () const inline virtual
Reimplemented from FieldMapper.
Definition at line 196 of file fvFieldDecomposer.H.
weights()
const scalarListList & weights () const inline virtual
Reimplemented from FieldMapper.
Definition at line 201 of file fvFieldDecomposer.H.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompose/fvFieldDecomposer.H
src/parallel/decompose/decompose/fvFieldDecomposer.C