OpenFOAM: scotchDecomp Class Reference
scotchDecomp Class Reference
Scotch domain decomposition.
#include <scotchDecomp.H>
Public Member Functions
TypeName ("scotch")
scotchDecomp (const dictionary &decompDict, const word &regionName="")
virtual ~scotchDecomp ()=default
virtual bool parallelAware () const
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights) const
virtual labelList decompose (const polyMesh &mesh, const labelList &agglom, const pointField &regionPoints, const scalarField &regionWeights) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights) const
virtual labelList decompose (const pointField &points, const scalarField &pointWeights) const
virtual labelList decompose (const pointField &points) const
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights) const=0
virtual labelList decompose (const polyMesh &mesh, const pointField &points) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights) const=0
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc) const
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections) const
labelList decompose (const polyMesh &mesh, const scalarField &cWeights) const
Public Member Functions inherited from metisLikeDecomp
virtual ~metisLikeDecomp ()=default
labelList decompose (const polyMesh &mesh, const scalarField &cWeights) const
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompDict, const word &regionName),(decompDict, regionName))
decompositionMethod (const dictionary &decompDict, const word &regionName="")
virtual ~decompositionMethod ()=default
label nDomains () const noexcept
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp) const
labelList decompose (const polyMesh &mesh, const scalarField &cWeights) const
Protected Member Functions
virtual label decomposeSerial (const labelList &adjncy, const labelList &xadj, const List< scalar > &cWeights, labelList &decomp) const
scotchDecomp (const scotchDecomp &)=delete
void operator= (const scotchDecomp &)=delete
Protected Member Functions inherited from metisLikeDecomp
virtual label decomposeGeneral (const labelList &adjncy, const labelList &xadj, const List< scalar > &cellWeights, labelList &decomp) const
metisLikeDecomp (const metisLikeDecomp &)=delete
void operator= (const metisLikeDecomp &)=delete
metisLikeDecomp (const word &derivedType, const dictionary &decompDict, int select=selectionType::NULL_DICT)
metisLikeDecomp (const word &derivedType, const dictionary &decompDict, const word &regionName, int select=selectionType::NULL_DICT)
Protected Member Functions inherited from decompositionMethod
const dictionary & findCoeffsDict (const word &coeffsName, int select=selectionType::DEFAULT) const
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static label nDomains (const dictionary &decompDict, const word &regionName="")
static const dictionary & optionalRegionDict (const dictionary &decompDict, const word &regionName)
static autoPtr< decompositionMethod > New (const dictionary &decompDict, const word &regionName="")
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Protected Types inherited from decompositionMethod
enum selectionType { DEFAULT = 0 , EXACT = 1 , MANDATORY = 2 , NULL_DICT = 4 }
Static Protected Member Functions inherited from decompositionMethod
static const dictionary & findCoeffsDict (const dictionary &dict, const word &coeffsName, int select=selectionType::DEFAULT)
Protected Attributes inherited from metisLikeDecomp
const dictionary & coeffsDict_
Protected Attributes inherited from decompositionMethod
const dictionary & decompDict_
const dictionary & decompRegionDict_
label nDomains_
PtrList< decompositionConstraint > constraints_
Detailed Description
Scotch domain decomposition.
When run in parallel will collect the whole graph on to the master, decompose and send back. Use ptscotchDecomp for proper distributed decomposition.
Coefficients dictionary: scotchCoeffs, coeffs.
Quoting from the Scotch forum, on the 2008-08-22 10:09, Francois PELLEGRINI posted the following details:
RE: Graph mapping 'strategy' string
Strategy handling in Scotch is a bit tricky. In order
not to be confused, you must have a clear view of how they are built.
Here are some rules:
1- Strategies are made up of "methods" which are combined by means of
"operators".
2- A method is of the form "m{param=value,param=value,...}", where "m"
is a single character (this is your first error: "f" is a method name,
not a parameter name).
3- There exist different sort of strategies : bipartitioning strategies,
mapping strategies, ordering strategies, which cannot be mixed. For
instance, you cannot build a bipartitioning strategy and feed it to a
mapping method (this is your second error).
To use the "mapCompute" routine, you must create a mapping strategy, not
a bipartitioning one, and so use stratGraphMap() and not
stratGraphBipart(). Your mapping strategy should however be based on the
"recursive bipartitioning" method ("b"). For instance, a simple (and
hence not very efficient) mapping strategy can be :
"b{sep=f}"
which computes mappings with the recursive bipartitioning method "b",
this latter using the Fiduccia-Mattheyses method "f" to compute its
separators.
If you want an exact partition (see your previous post), try
"b{sep=fx}".
However, these strategies are not the most efficient, as they do not
make use of the multi-level framework.
To use the multi-level framework, try for instance:
"b{sep=m{vert=100,low=h,asc=f}x}"
The current default mapping strategy in Scotch can be seen by using the
"-vs" option of program gmap. It is, to date:
r
{
    job=t,
    map=t,
    poli=S,
    sep=
    (
        m
        {
            asc=b
            {
                bnd=
                (
                    d{pass=40,dif=1,rem=1}
                 |
                )
                f{move=80,pass=-1,bal=0.002491},
                org=f{move=80,pass=-1,bal=0.002491},
                width=3
            },
            low=h{pass=10}
            f{move=80,pass=-1,bal=0.002491},
            type=h,
            vert=80,
            rat=0.8
        }
      | m
        {
            asc=b
            {
                bnd=
                (
                    d{pass=40,dif=1,rem=1}
                  |
                )
                f{move=80,pass=-1,bal=0.002491},
                org=f{move=80,pass=-1,bal=0.002491},
                width=3
            },
            low=h{pass=10}
            f{move=80,pass=-1,bal=0.002491},
            type=h,
            vert=80,
            rat=0.8
        }
    )
}
Given that this information was written in 2008, this example strategy will unlikely work as-is with the more recent Scotch versions. Therefore, the steps for getting the current default strategy from within Scotch, is to do the following steps:
Edit the file system/decomposeParDict and use the following settings:
method          scotch;
scotchCoeffs
{
    writeGraph true;
}
Run decomposePar. For example, it will write a file named region0.grf.
Now, instead of using gmap, run gpart with the following command structure to get the default strategy:
gpart \<nProcs\> -vs \<grfFile\>
where:
<grfFile> is the file that was obtained with the option writeGraph=true, namely region0.grf.
<nProcs> is the numberOfSubdomains defined in the dictionary file.
At the end of the execution will be shown a long string, similar to the following example (complete line was cropped at [...]):
S    Strat=m{asc=b{width=3,bnd=d{pass=40,dif=1,rem=0}[...],type=h}
Edit the file system/decomposeParDict once again and add the strategy entry as exemplified:
method          scotch;
scotchCoeffs
{
    //writeGraph true;
    strategy "m{asc=b{width=3,bnd=d{pass=40,dif=1,rem=0}[...],type=h}";
}
Finally, run decomposePar once again, to at least test if it works as intended.
Also support for multi-level decomposition by specifying inter-level communication weights:
numberOfSubdomains  2048;
coeffs
{
    // Divide into 64 clusters, each of 32 cores
    domains (64 32);
    // Inside a cluster the communication weight is 1% of that inbetween
    // clusters
    domainWeights (1 0.01);
}
Alternatively the first-level decomposition can be left out by assuming weights are 1 for that level:
numberOfSubdomains  2048;
coeffs
{
    // Divide into 2048/32 clusters
    domains (32);
    // Inside a cluster the communication weight is 1% of that inbetween
    // clusters
    domainWeights (0.01);
}
Note
gpart can be found in the current search path by adding the respective bin folder from the Scotch installation, namely by running the following commands:
source $(foamEtcFile config.sh/scotch)
export PATH=$PATH:$SCOTCH_ARCH_PATH/bin
Source files
scotchDecomp.H
scotchDecomp.C
Definition at line 259 of file scotchDecomp.H.
Constructor & Destructor Documentation
scotchDecomp() [1/2]
scotchDecomp (const scotchDecomp &) protected delete
scotchDecomp() [2/2]
scotchDecomp (const dictionary & decompDict, const word & regionName = "") explicit
Definition at line 70 of file dummyScotchDecomp.C.
~scotchDecomp()
virtual ~scotchDecomp () virtual default
Member Function Documentation
decomposeSerial()
Foam::label decomposeSerial (const labelList & adjncy, const labelList & xadj, const List< scalar > & cWeights, labelList & decomp) const protected virtual
Implements metisLikeDecomp.
Definition at line 52 of file dummyScotchDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and notImplementedMessage.
operator=()
void operator= (const scotchDecomp &) protected delete
TypeName()
TypeName ("scotch")
parallelAware()
virtual bool parallelAware () const inline virtual
Implements decompositionMethod.
Definition at line 313 of file scotchDecomp.H.
decompose() [1/13]
Foam::labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) const virtual
Reimplemented from metisLikeDecomp.
Definition at line 82 of file dummyScotchDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and notImplementedMessage.
decompose() [2/13]
Foam::labelList decompose (const polyMesh & mesh, const labelList & agglom, const pointField & regionPoints, const scalarField & regionWeights) const virtual
Reimplemented from metisLikeDecomp.
Definition at line 96 of file dummyScotchDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and notImplementedMessage.
decompose() [3/13]
Foam::labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) const virtual
Reimplemented from metisLikeDecomp.
Definition at line 111 of file dummyScotchDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and notImplementedMessage.
decompose() [4/13]
Foam::labelList decompose (const pointField & points, const scalarField & pointWeights) const virtual
Reimplemented from metisLikeDecomp.
Definition at line 218 of file decompositionMethod.C.
decompose() [5/13]
Foam::labelList decompose (const pointField & points) const virtual
Reimplemented from metisLikeDecomp.
Definition at line 225 of file decompositionMethod.C.
decompose() [6/13]
virtual labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) const virtual
Reimplemented from metisLikeDecomp.
decompose() [7/13]
Foam::labelList decompose (const polyMesh & mesh, const pointField & points) const virtual
Reimplemented from metisLikeDecomp.
Definition at line 240 of file decompositionMethod.C.
decompose() [8/13]
Foam::labelList decompose (const polyMesh & mesh, const labelList & cellToRegion, const pointField & regionPoints, const scalarField & regionWeights) const virtual
Reimplemented from metisLikeDecomp.
Definition at line 254 of file decompositionMethod.C.
decompose() [9/13]
Foam::labelList decompose (const polyMesh & mesh, const labelList & cellToRegion, const pointField & regionPoints) const virtual
Reimplemented from metisLikeDecomp.
Definition at line 263 of file decompositionMethod.C.
decompose() [10/13]
virtual labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) const virtual
Reimplemented from metisLikeDecomp.
decompose() [11/13]
Foam::labelList decompose (const labelListList & globalCellCells, const pointField & cc) const virtual
Reimplemented from metisLikeDecomp.
Definition at line 288 of file decompositionMethod.C.
decompose() [12/13]
Foam::labelList decompose (const polyMesh & mesh, const scalarField & cellWeights, const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections) const virtual
Reimplemented from metisLikeDecomp.
Definition at line 363 of file decompositionMethod.C.
decompose() [13/13]
Foam::labelList decompose (const polyMesh & mesh, const scalarField & cWeights) const
Definition at line 383 of file decompositionMethod.C.
The documentation for this class was generated from the following files:
src/parallel/decompose/scotchDecomp/scotchDecomp.H
src/dummyThirdParty/scotchDecomp/dummyScotchDecomp.C
src/parallel/decompose/scotchDecomp/scotchDecomp.C