OpenFOAM: TRIReader Class Reference
TRIReader Class Reference
TRI (triangle) file reader.
#include <TRIReader.H>
Public Member Functions
TRIReader (const fileName &filename)
~TRIReader ()=default
void clear ()
label mergePointsMap (labelList &pointMap) const
label mergePointsMap (const scalar mergeTol, labelList &pointMap) const
bool sorted () const
List< STLpoint > & points ()
List< label > & zoneIds ()
List< word > & names ()
List< label > & sizes ()
Public Member Functions inherited from surfaceFormatsCore
surfaceFormatsCore ()=default
virtual ~surfaceFormatsCore ()=default
Additional Inherited Members
Static Public Member Functions inherited from surfaceFormatsCore
static bool checkSupport (const wordHashSet &available, const word &fileType, const bool verbose=false, const char *functionName=nullptr)
static fileName findFile (const IOobject &io, const bool isGlobal=true)
static fileName findFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
Static Public Attributes inherited from surfaceFormatsCore
static word nativeExt
Static Protected Member Functions inherited from surfaceFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
static labelList getSelectedPatches (const surfZoneList &patches, const wordRes &allow, const wordRes &deny=wordRes())
static fileName relativeFilePath (const IOobject &io, const fileName &f, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
Detailed Description
TRI (triangle) file reader.
For TRI format (eg, AC3D). Each input line has 9 floats (3 points, each 3 floats) followed by hex colour. The colour is used to build regions numbered from 0 upwards.
Reading and stitching similar to the STLReader.
Source files
TRIReader.H
TRIReader.C
Definition at line 57 of file TRIReader.H.
Constructor & Destructor Documentation
TRIReader()
TRIReader (const fileName & filename)
Definition at line 160 of file TRIReader.C.
~TRIReader()
~TRIReader () default
Member Function Documentation
clear()
void clear ()
Definition at line 177 of file TRIReader.C.
References PtrList< T >::clear().
mergePointsMap() [1/2]
Foam::label mergePointsMap (labelList & pointMap) const
Definition at line 187 of file TRIReader.C.
References Foam::doubleScalarSMALL.
Referenced by TRIsurfaceFormat< Face >::read().
mergePointsMap() [2/2]
Foam::label mergePointsMap (const scalar mergeTol, labelList & pointMap) const
Definition at line 201 of file TRIReader.C.
References Foam::mergePoints().
sorted()
bool sorted () const inline
Definition at line 111 of file TRIReader.H.
Referenced by TRIsurfaceFormat< Face >::read().
points()
List< STLpoint > & points () inline
Definition at line 117 of file TRIReader.H.
Referenced by TRIsurfaceFormat< Face >::read().
zoneIds()
List< label > & zoneIds () inline
Definition at line 123 of file TRIReader.H.
Referenced by TRIsurfaceFormat< Face >::read().
names()
List< word > & names () inline
Definition at line 129 of file TRIReader.H.
sizes()
List< label > & sizes () inline
Definition at line 135 of file TRIReader.H.
Referenced by TRIsurfaceFormat< Face >::read().
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/tri/TRIReader.H
src/surfMesh/surfaceFormats/tri/TRIReader.C