OpenFOAM: LangmuirHinshelwoodReactionRate Class Reference
LangmuirHinshelwoodReactionRate Class Reference
Power series reaction rate.
#include <LangmuirHinshelwoodReactionRate.H>
Public Member Functions
LangmuirHinshelwoodReactionRate (const scalar A[], const scalar Ta[], const label co, const label c3h6, const label no)
LangmuirHinshelwoodReactionRate (const speciesTable &species, const dictionary &dict)
scalar operator() (const scalar p, const scalar T, const scalarField &c) const
void write (Ostream &os) const
Static Public Member Functions
static word type ()
Friends
Ostream & operator<< (Ostream &, const LangmuirHinshelwoodReactionRate &)
Detailed Description
Power series reaction rate.
Source files
LangmuirHinshelwoodReactionRate.H
LangmuirHinshelwoodReactionRateI.H
Definition at line 54 of file LangmuirHinshelwoodReactionRate.H.
Constructor & Destructor Documentation
LangmuirHinshelwoodReactionRate() [1/2]
LangmuirHinshelwoodReactionRate (const scalar A[], const scalar Ta[], const label co, const label c3h6, const label no) inline
Definition at line 26 of file LangmuirHinshelwoodReactionRateI.H.
References A.
LangmuirHinshelwoodReactionRate() [2/2]
LangmuirHinshelwoodReactionRate (const speciesTable & species, const dictionary & dict) inline
Definition at line 47 of file LangmuirHinshelwoodReactionRateI.H.
References dict, UPtrList< T >::first(), and forAll.
Member Function Documentation
type()
static word type () inline static
Definition at line 92 of file LangmuirHinshelwoodReactionRate.H.
operator()()
Foam::scalar operator() (const scalar p, const scalar T, const scalarField & c) const inline
Definition at line 70 of file LangmuirHinshelwoodReactionRateI.H.
References Foam::exp(), Foam::pow(), Foam::sqr(), and T.
write()
void write (Ostream & os) const inline
Definition at line 87 of file LangmuirHinshelwoodReactionRateI.H.
References UPtrList< T >::first(), forAll, Foam::nl, os(), and Ostream::writeKeyword().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & , const LangmuirHinshelwoodReactionRate &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/LangmuirHinshelwood/LangmuirHinshelwoodReactionRate.H
src/thermophysicalModels/specie/reaction/reactionRate/LangmuirHinshelwood/LangmuirHinshelwoodReactionRateI.H