OpenFOAM: pairGAMGAgglomeration Class Reference
pairGAMGAgglomeration Class Reference
Agglomerate using the pair algorithm.
#include <pairGAMGAgglomeration.H>
Public Member Functions
TypeName ("pair")
pairGAMGAgglomeration (const lduMesh &mesh, const dictionary &controlDict)
virtual void agglomerate (const label nCellsInCoarsestLevel, const label startLevel, const scalarField &startFaceWeights, const bool doProcessorAgglomerate=true)
Public Member Functions inherited from GAMGAgglomeration
TypeName ("GAMGAgglomeration")
declareRunTimeSelectionTable (autoPtr, GAMGAgglomeration, lduMesh,(const lduMesh &mesh, const dictionary &controlDict),(mesh, controlDict))
declareRunTimeSelectionTable (autoPtr, GAMGAgglomeration, lduMatrix,(const lduMatrix &matrix, const dictionary &controlDict),(matrix, controlDict))
declareRunTimeSelectionTable (autoPtr, GAMGAgglomeration, geometry,(const lduMesh &mesh, const scalarField &cellVolumes, const vectorField &faceAreas, const dictionary &controlDict),(mesh, cellVolumes, faceAreas, controlDict))
GAMGAgglomeration (const lduMesh &mesh, const dictionary &controlDict)
~GAMGAgglomeration ()
label size () const
const lduMesh & meshLevel (const label leveli) const
bool hasMeshLevel (const label leveli) const
const lduInterfacePtrsList & interfaceLevel (const label leveli) const
const labelField & restrictAddressing (const label leveli) const
const labelList & faceRestrictAddressing (const label leveli) const
const labelListList & patchFaceRestrictAddressing (const label leveli) const
const boolList & faceFlipMap (const label leveli) const
label nCells (const label leveli) const
label nFaces (const label leveli) const
const labelList & nPatchFaces (const label leveli) const
template<class Type >
void restrictField (Field< Type > &cf, const Field< Type > &ff, const label fineLevelIndex, const bool procAgglom) const
template<class Type >
void restrictFaceField (Field< Type > &cf, const Field< Type > &ff, const label fineLevelIndex) const
template<class Type >
void restrictField (Field< Type > &cf, const Field< Type > &ff, const labelList &fineToCoarse) const
template<class Type >
void prolongField (Field< Type > &ff, const Field< Type > &cf, const label coarseLevelIndex, const bool procAgglom) const
bool processorAgglomerate () const
const labelList & procAgglomMap (const label fineLeveli) const
const labelList & agglomProcIDs (const label fineLeveli) const
bool hasProcMesh (const label fineLeveli) const
label procCommunicator (const label fineLeveli) const
const labelList & cellOffsets (const label fineLeveli) const
const labelListList & faceMap (const label fineLeveli) const
const labelListList & boundaryMap (const label fineLeveli) const
const labelListListList & boundaryFaceMap (const label fineLeveli) const
Public Member Functions inherited from MeshObject< lduMesh, GeometricMeshObject, GAMGAgglomeration >
MeshObject (const lduMesh &mesh)
MeshObject (const word &objName, const lduMesh &mesh)
virtual ~MeshObject ()=default
const lduMesh & mesh () const noexcept
virtual bool writeData (Ostream &os) const
Static Public Member Functions
static tmp< labelField > agglomerate (label &nCoarseCells, const lduAddressing &fineMatrixAddressing, const scalarField &faceWeights)
Static Public Member Functions inherited from GAMGAgglomeration
static const GAMGAgglomeration & New (const lduMesh &mesh, const dictionary &controlDict)
static const GAMGAgglomeration & New (const lduMatrix &matrix, const dictionary &controlDict)
static const GAMGAgglomeration & New (const lduMesh &mesh, const scalarField &cellVolumes, const vectorField &faceAreas, const dictionary &controlDict)
static void calculateRegionMaster (const label comm, const labelList &procAgglomMap, labelList &masterProcs, List< label > &agglomProcIDs)
static bool checkRestriction (labelList &newRestrict, label &nNewCoarse, const lduAddressing &fineAddressing, const labelUList &restriction, const label nCoarse)
Static Public Member Functions inherited from MeshObject< lduMesh, GeometricMeshObject, GAMGAgglomeration >
static const GAMGAgglomeration & New (const lduMesh &mesh, Args &&... args)
static const GAMGAgglomeration & New (const word &objName, const lduMesh &mesh, Args &&... args)
static bool Delete (const word &objName, const lduMesh &mesh)
static bool Delete (const lduMesh &mesh)
Protected Member Functions
pairGAMGAgglomeration (const pairGAMGAgglomeration &)=delete
void operator= (const pairGAMGAgglomeration &)=delete
Protected Member Functions inherited from GAMGAgglomeration
void agglomerateLduAddressing (const label fineLevelIndex)
void combineLevels (const label curLevel)
void compactLevels (const label nCreatedLevels, const bool doProcessorAgglomerate)
bool continueAgglomerating (const label nCellsInCoarsestLevel, const label nCells, const label nCoarseCells, const label comm) const
void clearLevel (const label leveli)
void printLevels () const
void procAgglomerateLduAddressing (const label comm, const labelList &procAgglomMap, const labelList &procIDs, const label allMeshComm, const label levelIndex)
void procAgglomerateRestrictAddressing (const label comm, const labelList &procIDs, const label levelIndex)
GAMGAgglomeration (const GAMGAgglomeration &)=delete
void operator= (const GAMGAgglomeration &)=delete
Additional Inherited Members
Protected Attributes inherited from GAMGAgglomeration
const label maxLevels_
label nCellsInCoarsestLevel_
const lduInterfacePtrsList meshInterfaces_
autoPtr< GAMGProcAgglomeration > procAgglomeratorPtr_
labelList nCells_
PtrList< labelField > restrictAddressing_
labelList nFaces_
PtrList< labelList > faceRestrictAddressing_
PtrList< boolList > faceFlipMap_
PtrList< labelList > nPatchFaces_
PtrList< labelListList > patchFaceRestrictAddressing_
PtrList< lduPrimitiveMesh > meshLevels_
PtrList< labelList > procAgglomMap_
PtrList< labelList > agglomProcIDs_
labelList procCommunicator_
PtrList< labelList > procCellOffsets_
PtrList< labelListList > procFaceMap_
PtrList< labelListList > procBoundaryMap_
PtrList< labelListListList > procBoundaryFaceMap_
Protected Attributes inherited from MeshObject< lduMesh, GeometricMeshObject, GAMGAgglomeration >
const lduMesh & mesh_
Detailed Description
Agglomerate using the pair algorithm.
Source files
pairGAMGAgglomeration.H
pairGAMGAgglomeration.C
pairGAMGAgglomerate.C
Definition at line 48 of file pairGAMGAgglomeration.H.
Constructor & Destructor Documentation
pairGAMGAgglomeration() [1/2]
pairGAMGAgglomeration (const pairGAMGAgglomeration &) protected delete
pairGAMGAgglomeration() [2/2]
pairGAMGAgglomeration (const lduMesh & mesh, const dictionary & controlDict)
Definition at line 35 of file pairGAMGAgglomeration.C.
Member Function Documentation
operator=()
void operator= (const pairGAMGAgglomeration &) protected delete
TypeName()
TypeName ("pair")
agglomerate() [1/2]
Foam::tmp< Foam::labelField > agglomerate (label & nCoarseCells, const lduAddressing & fineMatrixAddressing, const scalarField & faceWeights) static
Definition at line 151 of file pairGAMGAgglomerate.C.
References forAll, Foam::max(), tmp< T >::New(), UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
Referenced by pairGAMGAgglomeration::agglomerate(), algebraicPairGAMGAgglomeration::algebraicPairGAMGAgglomeration(), assemblyFaceAreaPairGAMGAgglomeration::assemblyFaceAreaPairGAMGAgglomeration(), assemblyFaceAreaPairGAMGAgglomeration::assemblyFaceAreaPairGAMGAgglomeration(), faceAreaPairGAMGAgglomeration::faceAreaPairGAMGAgglomeration(), and faceAreaPairGAMGAgglomeration::faceAreaPairGAMGAgglomeration().
agglomerate() [2/2]
void agglomerate (const label nCellsInCoarsestLevel, const label startLevel, const scalarField & startFaceWeights, const bool doProcessorAgglomerate = true) virtual
Implements GAMGAgglomeration.
Definition at line 27 of file pairGAMGAgglomerate.C.
References pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::agglomerateLduAddressing(), GAMGAgglomeration::agglomProcIDs_, GAMGAgglomeration::combineLevels(), GAMGAgglomeration::compactLevels(), GAMGAgglomeration::continueAgglomerating(), Foam::exit(), GAMGAgglomeration::faceFlipMap_, GAMGAgglomeration::faceRestrictAddressing_, Foam::FatalError, FatalErrorInFunction, GAMGAgglomeration::hasMeshLevel(), GAMGAgglomeration::maxLevels_, GAMGAgglomeration::meshLevel(), GAMGAgglomeration::meshLevels_, GAMGAgglomeration::nCells_, GAMGAgglomeration::nFaces_, GAMGAgglomeration::nPatchFaces_, GAMGAgglomeration::patchFaceRestrictAddressing_, GAMGAgglomeration::procAgglomMap_, GAMGAgglomeration::procBoundaryFaceMap_, GAMGAgglomeration::procBoundaryMap_, GAMGAgglomeration::procCellOffsets_, GAMGAgglomeration::procCommunicator_, GAMGAgglomeration::processorAgglomerate(), GAMGAgglomeration::procFaceMap_, List< T >::resize(), PtrList< T >::resize(), GAMGAgglomeration::restrictAddressing_, GAMGAgglomeration::restrictFaceField(), PtrList< T >::set(), GAMGAgglomeration::size(), and UList< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGAgglomerations/pairGAMGAgglomeration/pairGAMGAgglomeration.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGAgglomerations/pairGAMGAgglomeration/pairGAMGAgglomerate.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGAgglomerations/pairGAMGAgglomeration/pairGAMGAgglomeration.C