OpenFOAM: faMeshSubset Class Reference
faMeshSubset Class Reference
Holds a reference to the original mesh (the baseMesh) and optionally to a subset of that mesh (the subMesh) with mapping lists for points, faces, and cells.
#include <faMeshSubset.H>
Public Member Functions
faMeshSubset (const faMesh &baseMesh)
faMeshSubset (const faMesh &baseMesh, const Foam::zero)
const faMesh & baseMesh () const noexcept
const faMesh & mesh () const noexcept
bool hasSubMesh () const noexcept
const faMesh & subMesh () const
faMesh & subMesh ()
const labelList & pointMap () const
const labelList & faceMap () const
const labelList & edgeFlipMap () const
const labelList & cellMap () const
const labelList & patchMap () const
void clear ()
void reset ()
void reset (const Foam::zero)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &, const bool allowUnmapped=false) const
template<class Type >
tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faePatchField, edgeMesh > &, const bool allowUnmapped=false) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &vf, const faMesh &sMesh, const bool allowUnmapped)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > interpolate (const GeometricField< Type, faePatchField, edgeMesh > &vf, const faMesh &sMesh)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &vf, const bool allowUnmapped) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > interpolate (const GeometricField< Type, faePatchField, edgeMesh > &vf, const bool allowUnmapped) const
Static Public Member Functions
template<class Type >
static tmp< GeometricField< Type, faPatchField, areaMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &, const faMesh &sMesh, const bool allowUnmapped=false)
template<class Type >
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faePatchField, edgeMesh > &, const faMesh &sMesh)
Static Public Attributes
static word exposedPatchName
Protected Member Functions
bool checkHasSubMesh () const
faMeshSubset (const faMeshSubset &)=delete
void operator= (const faMeshSubset &)=delete
Detailed Description
Holds a reference to the original mesh (the baseMesh) and optionally to a subset of that mesh (the subMesh) with mapping lists for points, faces, and cells.
Caution Currently not really functional for subsetting beyond handling a simple zero-sized mesh.
Source files
faMeshSubset.H
faMeshSubset.C
faMeshSubsetI.H
faMeshSubsetTemplates.C
Definition at line 61 of file faMeshSubset.H.
Constructor & Destructor Documentation
faMeshSubset() [1/3]
faMeshSubset (const faMeshSubset &) protected delete
faMeshSubset() [2/3]
faMeshSubset (const faMesh & baseMesh) explicit
Definition at line 52 of file faMeshSubset.C.
faMeshSubset() [3/3]
faMeshSubset (const faMesh & baseMesh, const Foam::zero)
Definition at line 64 of file faMeshSubset.C.
References faMeshSubset::reset().
Member Function Documentation
checkHasSubMesh()
bool checkHasSubMesh () const protected
Definition at line 35 of file faMeshSubset.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
operator=()
void operator= (const faMeshSubset &) protected delete
baseMesh()
const Foam::faMesh & baseMesh () const inline noexcept
Definition at line 23 of file faMeshSubsetI.H.
mesh()
const Foam::faMesh & mesh () const inline noexcept
Definition at line 29 of file faMeshSubsetI.H.
hasSubMesh()
bool hasSubMesh () const inline noexcept
Definition at line 35 of file faMeshSubsetI.H.
subMesh() [1/2]
const Foam::faMesh & subMesh () const inline
Definition at line 41 of file faMeshSubsetI.H.
subMesh() [2/2]
Foam::faMesh & subMesh () inline
Definition at line 49 of file faMeshSubsetI.H.
pointMap()
const Foam::labelList & pointMap () const inline
Definition at line 57 of file faMeshSubsetI.H.
faceMap()
const Foam::labelList & faceMap () const inline
Definition at line 65 of file faMeshSubsetI.H.
edgeFlipMap()
const Foam::labelList & edgeFlipMap () const inline
Definition at line 73 of file faMeshSubsetI.H.
cellMap()
const Foam::labelList & cellMap () const inline
Definition at line 84 of file faMeshSubsetI.H.
patchMap()
const Foam::labelList & patchMap () const inline
Definition at line 92 of file faMeshSubsetI.H.
clear()
void clear ()
Definition at line 74 of file faMeshSubset.C.
References PtrList< T >::clear().
reset() [1/2]
void reset ()
Definition at line 86 of file faMeshSubset.C.
References clear().
Referenced by faMeshSubset::faMeshSubset().
reset() [2/2]
void reset (const Foam::zero)
Definition at line 92 of file faMeshSubset.C.
References clear(), forAll, Foam::identity(), PtrList< T >::set(), and UPtrList< T >::size().
interpolate() [1/8]
template<class Type > static tmp< GeometricField< Type, faPatchField, areaMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > & , const faMesh & sMesh, const bool allowUnmapped = false) static
interpolate() [2/8]
template<class Type > static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faePatchField, edgeMesh > & , const faMesh & sMesh) static
interpolate() [3/8]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > & , const bool allowUnmapped = false) const
interpolate() [4/8]
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faePatchField, edgeMesh > & , const bool allowUnmapped = false) const
interpolate() [5/8]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > & vf, const faMesh & sMesh, const bool allowUnmapped)
Definition at line 37 of file faMeshSubsetTemplates.C.
References faPatchFieldBase::calculatedType(), fld(), forAll, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, PtrList< T >::set(), and UPtrList< T >::size().
interpolate() [6/8]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > interpolate (const GeometricField< Type, faePatchField, edgeMesh > & vf, const faMesh & sMesh)
Definition at line 145 of file faMeshSubsetTemplates.C.
References faePatchFieldBase::calculatedType(), forAll, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, PtrList< T >::set(), and UPtrList< T >::size().
interpolate() [7/8]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > & vf, const bool allowUnmapped) const
Definition at line 229 of file faMeshSubsetTemplates.C.
References Foam::interpolate().
interpolate() [8/8]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > interpolate (const GeometricField< Type, faePatchField, edgeMesh > & vf, const bool allowUnmapped) const
Definition at line 249 of file faMeshSubsetTemplates.C.
References Foam::interpolate().
Member Data Documentation
exposedPatchName
Foam::word exposedPatchName static
Definition at line 112 of file faMeshSubset.H.
The documentation for this class was generated from the following files:
src/finiteArea/faMesh/faMeshSubset/faMeshSubset.H
src/finiteArea/faMesh/faMeshSubset/faMeshSubset.C
src/finiteArea/faMesh/faMeshSubset/faMeshSubsetI.H
src/finiteArea/faMesh/faMeshSubset/faMeshSubsetTemplates.C