OpenFOAM: patchMeshWriter Class Reference
patchMeshWriter Class Reference
Write OpenFOAM patches and patch fields in VTP or legacy vtk format.
#include <foamVtkPatchMeshWriter.H>
Public Member Functions
patchMeshWriter (const polyMesh &mesh, const labelList &patchIDs, const vtk::outputOptions opts=vtk::formatType::INLINE_BASE64)
patchMeshWriter (const polyMesh &mesh, const labelList &patchIDs, const fileName &file, bool parallel=Pstream::parRun())
patchMeshWriter (const polyMesh &mesh, const labelList &patchIDs, const vtk::outputOptions opts, const fileName &file, bool parallel=Pstream::parRun())
virtual ~patchMeshWriter ()=default
const labelList & patchIDs () const noexcept
virtual bool beginFile (std::string title="")
virtual bool writeGeometry ()
virtual bool beginCellData (label nFields=0)
virtual bool beginPointData (label nFields=0)
void writePatchIDs ()
bool writeProcIDs ()
bool writeNeighIDs ()
template<class Type >
void writeUniform (const word &fieldName, const Type &val)
Public Member Functions inherited from fileWriter
fileWriter (const vtk::fileTag contentType, const vtk::outputOptions opts)
virtual ~fileWriter ()
vtk::fileTag contentType () const noexcept
vtk::outputOptions opts () const noexcept
word ext () const
bool legacy () const noexcept
bool parallel () const noexcept
const word & state () const
const fileName & output () const noexcept
virtual bool open (const fileName &file, bool parallel=UPstream::parRun())
void close ()
bool beginFieldData (label nFields=0)
bool isCellData () const noexcept
bool isPointData () const noexcept
label nCellData () const noexcept
label nPointData () const noexcept
bool endFieldData ()
bool endCellData ()
bool endPointData ()
void writeTimeValue (scalar timeValue)
Static Public Member Functions
static word ext (vtk::outputOptions opts)
Protected Member Functions
void beginPiece ()
void writePoints ()
void writePolysLegacy (const label pointOffset)
void writePolys (const label pointOffset)
patchMeshWriter (const patchMeshWriter &)=delete
void operator= (const patchMeshWriter &)=delete
Protected Member Functions inherited from fileWriter
void checkFormatterValidity () const
Ostream & reportBadState (Ostream &, outputState expected) const
Ostream & reportBadState (Ostream &, outputState, outputState) const
std::ofstream & os () noexcept
vtk::formatter & format ()
bool isState (outputState test) const noexcept
bool notState (outputState test) const noexcept
template<class Type >
void beginDataArray (const word &fieldName, const label nValues)
void endDataArray ()
void beginPoints (const label nPoints)
void endPoints ()
bool enter_Piece ()
bool endPiece ()
bool enter_CellData (label nEntries, label nFields)
bool enter_PointData (label nEntries, label nFields)
bool exit_File ()
template<class Type >
void writeUniform (const word &fieldName, const Type &val, const label nValues)
template<class Type >
void writeBasicField (const word &fieldName, const UList< Type > &field)
bool writeProcIDs (const label nValues)
fileWriter (const fileWriter &)=delete
void operator= (const fileWriter &)=delete
Protected Attributes
label numberOfPoints_
label numberOfCells_
label nLocalPoints_
label nLocalPolys_
label nLocalPolyConn_
const polyMesh & mesh_
labelList patchIDs_
Protected Attributes inherited from fileWriter
outputState state_
vtk::fileTag contentType_
bool parallel_
vtk::outputOptions opts_
label nCellData_
label nPointData_
fileName outputFile_
autoPtr< vtk::formatter > format_
std::ofstream os_
Additional Inherited Members
Protected Types inherited from fileWriter
enum outputState : uint8_t {
CLOSED = 0 , OPENED , DECLARED , FIELD_DATA ,
PIECE , CELL_DATA , POINT_DATA
}
Static Protected Attributes inherited from fileWriter
static const Enum< outputState > stateNames
Detailed Description
Write OpenFOAM patches and patch fields in VTP or legacy vtk format.
The file output states are managed by the Foam::vtk::fileWriter class. FieldData (eg, TimeValue) must appear before any geometry pieces.
Note
Parallel output is combined into a single Piece without point merging, which is similar to using multi-piece data sets, but allows more convenient creation as a streaming process. In the future, the duplicate points at processor connections may be addressed using ghost points.
See also
Foam::vtk::patchWriter
Source files
foamVtkPatchMeshWriter.H
foamVtkPatchMeshWriter.C
foamVtkPatchMeshWriterTemplates.C
Definition at line 63 of file foamVtkPatchMeshWriter.H.
Constructor & Destructor Documentation
patchMeshWriter() [1/4]
patchMeshWriter (const patchMeshWriter &) protected delete
patchMeshWriter() [2/4]
patchMeshWriter (const polyMesh & mesh, const labelList & patchIDs, const vtk::outputOptions opts = vtk::formatType::INLINE_BASE64)
Definition at line 353 of file foamVtkPatchMeshWriter.C.
References outputOptions::append(), and fileWriter::opts_.
patchMeshWriter() [3/4]
patchMeshWriter (const polyMesh & mesh, const labelList & patchIDs, const fileName & file, bool parallel = Pstream::parRun())
Definition at line 375 of file foamVtkPatchMeshWriter.C.
References fileWriter::open(), and fileWriter::parallel().
patchMeshWriter() [4/4]
patchMeshWriter (const polyMesh & mesh, const labelList & patchIDs, const vtk::outputOptions opts, const fileName & file, bool parallel = Pstream::parRun())
Definition at line 389 of file foamVtkPatchMeshWriter.C.
References fileWriter::open(), and fileWriter::parallel().
~patchMeshWriter()
virtual ~patchMeshWriter () virtual default
Member Function Documentation
beginPiece()
void beginPiece () protected
Definition at line 29 of file foamVtkPatchMeshWriter.C.
References f(), fileWriter::format(), fileWriter::format_, fileWriter::legacy(), patchMeshWriter::mesh_, patchMeshWriter::nLocalPoints_, patchMeshWriter::nLocalPolyConn_, patchMeshWriter::nLocalPolys_, Foam::vtk::NUMBER_OF_POINTS, Foam::vtk::NUMBER_OF_POLYS, patchMeshWriter::numberOfCells_, patchMeshWriter::numberOfPoints_, fileWriter::parallel_, patches, patchId(), patchMeshWriter::patchIDs_, Foam::vtk::PIECE, pp(), Foam::reduce(), UPtrList< T >::size(), and formatter::tag().
writePoints()
void writePoints () protected
Definition at line 77 of file foamVtkPatchMeshWriter.C.
References UPstream::blocking, format(), UPstream::master(), UPstream::masterNo(), nPatches, patches, patchId(), pp(), UPtrList< T >::size(), UPstream::subProcs(), and Foam::vtk::writeList().
writePolysLegacy()
void writePolysLegacy (const label pointOffset) protected
Definition at line 139 of file foamVtkPatchMeshWriter.C.
References UList< T >::begin(), Foam::vtk::legacy::beginPolys(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, format(), patches, patchId(), pp(), Foam::reduce(), Foam::vtk::writeList(), and Foam::vtk::writeListParallel().
writePolys()
void writePolys (const label pointOffset) protected
Definition at line 210 of file foamVtkPatchMeshWriter.C.
References UList< T >::begin(), Foam::vtk::CONNECTIVITY, f(), format(), globalIndex::localStart(), Foam::vtk::OFFSETS, patches, patchId(), Foam::vtk::POLYS, pp(), Foam::reduce(), UPtrList< T >::size(), UList< T >::size(), Foam::vtk::writeList(), and Foam::vtk::writeListParallel().
operator=()
void operator= (const patchMeshWriter &) protected delete
ext()
static word ext (vtk::outputOptions opts) inline static
Definition at line 164 of file foamVtkPatchMeshWriter.H.
References outputOptions::ext(), fileWriter::opts(), and Foam::vtk::POLY_DATA.
patchIDs()
const labelList & patchIDs () const inline noexcept
Definition at line 170 of file foamVtkPatchMeshWriter.H.
References patchMeshWriter::patchIDs_.
beginFile()
bool beginFile (std::string title = "") virtual
Reimplemented from fileWriter.
Definition at line 406 of file foamVtkPatchMeshWriter.C.
References fileWriter::beginFile(), and Foam::name().
writeGeometry()
bool writeGeometry () virtual
Implements fileWriter.
Definition at line 456 of file foamVtkPatchMeshWriter.C.
References globalIndex::localStart().
beginCellData()
bool beginCellData (label nFields = 0) virtual
Implements fileWriter.
Definition at line 482 of file foamVtkPatchMeshWriter.C.
beginPointData()
bool beginPointData (label nFields = 0) virtual
Implements fileWriter.
Definition at line 488 of file foamVtkPatchMeshWriter.C.
writePatchIDs()
void writePatchIDs ()
Definition at line 494 of file foamVtkPatchMeshWriter.C.
References UPstream::blocking, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, format(), UPstream::master(), UPstream::masterNo(), Foam::nl, patches, patchId(), Foam::reduce(), UPtrList< T >::size(), UList< T >::size(), UPstream::subProcs(), and Foam::vtk::write().
writeProcIDs()
bool writeProcIDs ()
Definition at line 579 of file foamVtkPatchMeshWriter.C.
References fileWriter::writeProcIDs().
writeNeighIDs()
bool writeNeighIDs ()
Definition at line 589 of file foamVtkPatchMeshWriter.C.
References UPstream::blocking, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, format(), UPstream::master(), UPstream::masterNo(), Foam::nl, UPstream::parRun(), patches, patchId(), pp(), Foam::reduce(), Foam::returnReduceOr(), UPtrList< T >::size(), UList< T >::size(), UPstream::subProcs(), and Foam::vtk::write().
writeUniform()
template<class Type > void writeUniform (const word & fieldName, const Type & val)
Definition at line 27 of file foamVtkPatchMeshWriterTemplates.C.
References fileWriter::CELL_DATA, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, fileWriter::isState(), fileWriter::nCellData_, Foam::nl, patchMeshWriter::nLocalPoints_, patchMeshWriter::nLocalPolys_, fileWriter::nPointData_, fileWriter::POINT_DATA, and fileWriter::reportBadState().
Member Data Documentation
numberOfPoints_
label numberOfPoints_ protected
Definition at line 72 of file foamVtkPatchMeshWriter.H.
Referenced by patchMeshWriter::beginPiece().
numberOfCells_
label numberOfCells_ protected
Definition at line 75 of file foamVtkPatchMeshWriter.H.
Referenced by patchMeshWriter::beginPiece().
nLocalPoints_
label nLocalPoints_ protected
Definition at line 78 of file foamVtkPatchMeshWriter.H.
Referenced by patchMeshWriter::beginPiece(), patchWriter::write(), and patchMeshWriter::writeUniform().
nLocalPolys_
label nLocalPolys_ protected
Definition at line 81 of file foamVtkPatchMeshWriter.H.
Referenced by patchMeshWriter::beginPiece(), and patchMeshWriter::writeUniform().
nLocalPolyConn_
label nLocalPolyConn_ protected
Definition at line 84 of file foamVtkPatchMeshWriter.H.
Referenced by patchMeshWriter::beginPiece().
mesh_
const polyMesh& mesh_ protected
Definition at line 87 of file foamVtkPatchMeshWriter.H.
Referenced by patchMeshWriter::beginPiece().
patchIDs_
labelList patchIDs_ protected
Definition at line 90 of file foamVtkPatchMeshWriter.H.
Referenced by patchMeshWriter::beginPiece(), patchMeshWriter::patchIDs(), and patchWriter::write().
The documentation for this class was generated from the following files:
src/meshTools/output/vtk/patch/foamVtkPatchMeshWriter.H
src/meshTools/output/vtk/patch/foamVtkPatchMeshWriter.C
src/meshTools/output/vtk/patch/foamVtkPatchMeshWriterTemplates.C