OpenFOAM: Maxwell< BasicTurbulenceModel > Class Template Reference
Maxwell< BasicTurbulenceModel > Class Template Reference
Turbulence models » laminar transport model
Maxwell model for viscoelasticity using the upper-convected time derivative of the stress tensor. See http://en.wikipedia.org/wiki/Upper-convected_Maxwell_model.
#include <Maxwell.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from laminarModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("Maxwell")
Maxwell (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~Maxwell ()=default
virtual bool read ()
virtual tmp< volSymmTensorField > R () const
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
virtual void correct ()
Public Member Functions inherited from laminarModel< BasicTurbulenceModel >
TypeName ("laminar")
declareRunTimeSelectionTable (autoPtr, laminarModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
laminarModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~laminarModel ()=default
virtual const dictionary & coeffDict () const
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volScalarField > nuEff () const
virtual tmp< scalarField > nuEff (const label patchi) const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual tmp< volScalarField > omega () const
Protected Member Functions
tmp< volScalarField > nu0 () const
Protected Member Functions inherited from laminarModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
laminarModel (const laminarModel &)=delete
void operator= (const laminarModel &)=delete
Protected Attributes
dimensionedScalar nuM_
dimensionedScalar lambda_
volSymmTensorField sigma_
Protected Attributes inherited from laminarModel< BasicTurbulenceModel >
dictionary laminarDict_
Switch printCoeffs_
dictionary coeffDict_
Additional Inherited Members
Static Public Member Functions inherited from laminarModel< BasicTurbulenceModel >
static autoPtr< laminarModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Detailed Description
template<class BasicTurbulenceModel>
class Foam::laminarModels::Maxwell< BasicTurbulenceModel >
Maxwell model for viscoelasticity using the upper-convected time derivative of the stress tensor. See http://en.wikipedia.org/wiki/Upper-convected_Maxwell_model.
The model includes an additional viscosity (nu) from the transport model from which it is instantiated, which makes it equivalent to the Oldroyd-B model for the case of an incompressible transport model (where nu is non-zero). See https://en.wikipedia.org/wiki/Oldroyd-B_model
Reference:
    Amoreira, L. J., & Oliveira, P. J. (2010).
    Comparison of different formulations for the numerical calculation
    of unsteady incompressible viscoelastic fluid flow.
    Adv. Appl. Math. Mech, 4, 483-502.
    DOI:10.4208/aamm.10-m1010
Source files
Maxwell.H
Maxwell.C
Definition at line 70 of file Maxwell.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 101 of file Maxwell.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 102 of file Maxwell.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 103 of file Maxwell.H.
Constructor & Destructor Documentation
Maxwell()
template<class BasicTurbulenceModel > Maxwell (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 36 of file Maxwell.C.
References laminarModel< BasicTurbulenceModel >::printCoeffs(), and Foam::type().
~Maxwell()
template<class BasicTurbulenceModel > virtual ~Maxwell () virtual default
Member Function Documentation
nu0()
template<class BasicTurbulenceModel > tmp< volScalarField > nu0 () const inline protected
Definition at line 93 of file Maxwell.H.
References nu, and Maxwell< BasicTurbulenceModel >::nuM_.
TypeName()
template<class BasicTurbulenceModel > TypeName ("Maxwell< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented from laminarModel< BasicTurbulenceModel >.
Definition at line 87 of file Maxwell.C.
R()
template<class BasicTurbulenceModel > tmp< Foam::volSymmTensorField > R () const virtual
Reimplemented from laminarModel< BasicTurbulenceModel >.
Definition at line 103 of file Maxwell.C.
devRhoReff() [1/2]
template<class BasicTurbulenceModel > tmp< Foam::volSymmTensorField > devRhoReff () const virtual
Definition at line 111 of file Maxwell.C.
devRhoReff() [2/2]
template<class BasicTurbulenceModel > tmp< Foam::volSymmTensorField > devRhoReff (const volVectorField & U) const virtual
Definition at line 119 of file Maxwell.C.
References Foam::devTwoSymm(), Foam::fvc::grad(), IOobject::groupName(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and U.
divDevRhoReff() [1/2]
template<class BasicTurbulenceModel > tmp< Foam::fvVectorMatrix > divDevRhoReff (volVectorField & U) const virtual
Definition at line 143 of file Maxwell.C.
References Foam::dev2(), Foam::fvc::div(), Foam::fvc::grad(), Foam::fvm::laplacian(), nu, T, and U.
divDevRhoReff() [2/2]
template<class BasicTurbulenceModel > tmp< Foam::fvVectorMatrix > divDevRhoReff (const volScalarField & rho, volVectorField & U) const virtual
Definition at line 163 of file Maxwell.C.
References Foam::dev2(), Foam::fvc::div(), Foam::fvc::grad(), Foam::fvm::laplacian(), nu, rho, T, and U.
correct()
template<class BasicTurbulenceModel > void correct () virtual
Reimplemented from laminarModel< BasicTurbulenceModel >.
Definition at line 183 of file Maxwell.C.
References alpha, laminarModel< BasicTurbulenceModel >::correct(), Foam::fvm::ddt(), Foam::fvm::div(), fvOptions, Foam::fvc::grad(), IOobject::groupName(), options::New(), rho, solve(), Foam::fvm::Sp(), Foam::twoSymm(), and U.
Member Data Documentation
nuM_
template<class BasicTurbulenceModel > dimensionedScalar nuM_ protected
Definition at line 81 of file Maxwell.H.
Referenced by Maxwell< BasicTurbulenceModel >::nu0().
lambda_
template<class BasicTurbulenceModel > dimensionedScalar lambda_ protected
Definition at line 82 of file Maxwell.H.
sigma_
template<class BasicTurbulenceModel > volSymmTensorField sigma_ protected
Definition at line 87 of file Maxwell.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/laminar/Maxwell/Maxwell.H
src/TurbulenceModels/turbulenceModels/laminar/Maxwell/Maxwell.C