OpenFOAM: localPointRegion Class Reference
localPointRegion Class Reference
Takes mesh with 'baffles' (= boundary faces sharing points). Determines for selected points on boundary faces the 'point region' it is connected to. Each region can be visited by a cell-face-cell walk. Used in duplicating points after splitting baffles.
#include <localPointRegion.H>
Public Member Functions
ClassName ("localPointRegion")
localPointRegion (const polyMesh &mesh)
localPointRegion (const polyMesh &mesh, const labelList &candidatePoints)
localPointRegion (const polyMesh &mesh, const labelPairList &baffles, const labelList &candidatePoints)
const Map< label > & meshPointMap () const
const labelListList & pointRegions () const
const Map< label > & meshFaceMap () const
const faceList & faceRegions () const
void updateMesh (const mapPolyMesh &)
Static Public Member Functions
static labelList findDuplicateFaces (const primitiveMesh &, const labelList &)
static labelPairList findDuplicateFacePairs (const polyMesh &)
Detailed Description
Takes mesh with 'baffles' (= boundary faces sharing points). Determines for selected points on boundary faces the 'point region' it is connected to. Each region can be visited by a cell-face-cell walk. Used in duplicating points after splitting baffles.
Regions are not consecutive per processor. They will be -1..nRegions_.
Note: coupled boundaries (cyclics, parallel) not fully tested.
Source files
localPointRegion.H
localPointRegion.C
Definition at line 65 of file localPointRegion.H.
Constructor & Destructor Documentation
localPointRegion() [1/3]
localPointRegion (const polyMesh & mesh)
Definition at line 455 of file localPointRegion.C.
References coupled(), forAll, mesh, patches, and pp().
localPointRegion() [2/3]
localPointRegion (const polyMesh & mesh, const labelList & candidatePoints)
Definition at line 485 of file localPointRegion.C.
References forAll, and mesh.
localPointRegion() [3/3]
localPointRegion (const polyMesh & mesh, const labelPairList & baffles, const labelList & candidatePoints)
Definition at line 508 of file localPointRegion.C.
References forAll, and mesh.
Member Function Documentation
ClassName()
ClassName ("localPointRegion")
findDuplicateFaces()
Foam::labelList findDuplicateFaces (const primitiveMesh & mesh, const labelList & boundaryFaces) static
Definition at line 536 of file localPointRegion.C.
References Foam::abort(), f(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, primitiveMesh::nInternalFaces(), Foam::nl, pFaces, polyMesh::points(), and UPtrList< T >::size().
Referenced by meshRefinement::checkData().
findDuplicateFacePairs()
Foam::List< Foam::labelPair > findDuplicateFacePairs (const polyMesh & mesh) static
Definition at line 617 of file localPointRegion.C.
References Foam::abort(), PtrList< T >::append(), polyMesh::boundaryMesh(), primitiveMesh::faceCentres(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::identity(), mesh, primitiveMesh::nBoundaryFaces(), primitiveMesh::nInternalFaces(), Foam::nl, patches, and UPtrList< T >::size().
Referenced by preserveBaffles::add(), preserveBaffles::apply(), meshRefinement::balance(), snappySnapDriver::doSnap(), meshRefinement::mergeFreeStandingBaffles(), snappyLayerDriver::mergePatchFacesUndo(), meshRefinement::mergeZoneBaffles(), and displacementMeshMoverMotionSolver::meshMover().
meshPointMap()
const Map< label > & meshPointMap () const inline
Definition at line 171 of file localPointRegion.H.
pointRegions()
const labelListList & pointRegions () const inline
Definition at line 177 of file localPointRegion.H.
meshFaceMap()
const Map< label > & meshFaceMap () const inline
Definition at line 183 of file localPointRegion.H.
faceRegions()
const faceList & faceRegions () const inline
Definition at line 189 of file localPointRegion.H.
updateMesh()
void updateMesh (const mapPolyMesh & map)
Definition at line 677 of file localPointRegion.C.
References forAllConstIters, newPointi, mapPolyMesh::reverseFaceMap(), mapPolyMesh::reversePointMap(), and PtrList< T >::transfer().
The documentation for this class was generated from the following files:
src/meshTools/regionSplit/localPointRegion.H
src/meshTools/regionSplit/localPointRegion.C