OpenFOAM: repatchPolyTopoChanger Class Reference
repatchPolyTopoChanger Class Reference
A mesh which allows changes in the patch distribution of the boundary faces. The change in patching is set using changePatchID. For a boundary face, a new patch ID is given.
#include <repatchPolyTopoChanger.H>
Public Member Functions
repatchPolyTopoChanger (polyMesh &mesh)
virtual ~repatchPolyTopoChanger ()=default
void changePatches (polyPatchList &patches)
void changePatches (const List< polyPatch * > &patches)
void changePatchID (const label faceID, const label patchID)
void setFaceZone (const label faceID, const label zoneID, const bool zoneFlip)
void changeAnchorPoint (const label faceID, const label fp)
void repatch ()
Detailed Description
A mesh which allows changes in the patch distribution of the boundary faces. The change in patching is set using changePatchID. For a boundary face, a new patch ID is given.
Source files
repatchPolyTopoChanger.H
repatchPolyTopoChanger.C
Definition at line 50 of file repatchPolyTopoChanger.H.
Constructor & Destructor Documentation
repatchPolyTopoChanger()
repatchPolyTopoChanger (polyMesh & mesh) explicit
Definition at line 45 of file repatchPolyTopoChanger.C.
~repatchPolyTopoChanger()
virtual ~repatchPolyTopoChanger () virtual default
Member Function Documentation
changePatches() [1/2]
void changePatches (polyPatchList & patches)
Definition at line 54 of file repatchPolyTopoChanger.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and patches.
changePatches() [2/2]
void changePatches (const List< polyPatch * > & patches)
Definition at line 72 of file repatchPolyTopoChanger.C.
References patches.
changePatchID()
void changePatchID (const label faceID, const label patchID)
Definition at line 84 of file repatchPolyTopoChanger.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, patchID, and UPtrList< T >::size().
setFaceZone()
void setFaceZone (const label faceID, const label zoneID, const bool zoneFlip)
Definition at line 136 of file repatchPolyTopoChanger.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and UPtrList< T >::size().
changeAnchorPoint()
void changeAnchorPoint (const label faceID, const label fp)
Definition at line 172 of file repatchPolyTopoChanger.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, forAll, patchID, UPtrList< T >::size(), and UList< T >::size().
repatch()
void repatch ()
Definition at line 269 of file repatchPolyTopoChanger.C.
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/repatchPolyTopoChanger/repatchPolyTopoChanger.H
src/dynamicMesh/polyTopoChange/repatchPolyTopoChanger/repatchPolyTopoChanger.C