OpenFOAM: multiBandAbsorptionEmission Class Reference
multiBandAbsorptionEmission Class Reference
Thermophysical models » Radiation models » Sub-models » Absorption and emission sub-models
multiBandAbsorptionEmission radiation absorption/emission for solids.
#include <multiBandAbsorptionEmission.H>
Public Member Functions
TypeName ("multiBandAbsorptionEmission")
multiBandAbsorptionEmission (const dictionary &dict, const fvMesh &mesh)
virtual ~multiBandAbsorptionEmission ()
tmp< volScalarField > aCont (const label bandI) const
tmp< volScalarField > eCont (const label bandI) const
tmp< volScalarField > ECont (const label bandI) const
bool isGrey () const
label nBands () const
Public Member Functions inherited from absorptionEmissionModel
TypeName ("absorptionEmissionModel")
declareRunTimeSelectionTable (autoPtr, absorptionEmissionModel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
absorptionEmissionModel (const dictionary &dict, const fvMesh &mesh)
virtual ~absorptionEmissionModel ()
const fvMesh & mesh () const
const dictionary & dict () const
virtual tmp< volScalarField > a (const label bandI=0) const
virtual tmp< volScalarField > aDisp (const label bandI=0) const
virtual tmp< volScalarField > e (const label bandI=0) const
virtual tmp< volScalarField > eDisp (const label bandI=0) const
virtual tmp< volScalarField > E (const label bandI=0) const
virtual tmp< volScalarField > EDisp (const label bandI=0) const
virtual const Vector2D< scalar > & bands (const label n) const
virtual void correct (volScalarField &a, PtrList< volScalarField > &aj) const
Static Public Attributes
static const int maxBands_ = 5
Additional Inherited Members
Static Public Member Functions inherited from absorptionEmissionModel
static autoPtr< absorptionEmissionModel > New (const dictionary &dict, const fvMesh &mesh)
Protected Attributes inherited from absorptionEmissionModel
const dictionary dict_
const fvMesh & mesh_
Detailed Description
multiBandAbsorptionEmission radiation absorption/emission for solids.
Source files
multiBandAbsorptionEmission.H
multiBandAbsorptionEmission.C
Definition at line 53 of file multiBandAbsorptionEmission.H.
Constructor & Destructor Documentation
multiBandAbsorptionEmission()
multiBandAbsorptionEmission (const dictionary & dict, const fvMesh & mesh)
Definition at line 44 of file multiBandAbsorptionEmission.C.
References dictionary::readEntry(), and UList< T >::size().
~multiBandAbsorptionEmission()
~multiBandAbsorptionEmission () virtual
Definition at line 64 of file multiBandAbsorptionEmission.C.
Member Function Documentation
TypeName()
TypeName ("multiBandAbsorptionEmission")
aCont()
Foam::tmp< Foam::volScalarField > aCont (const label bandI) const virtual
Reimplemented from absorptionEmissionModel.
Definition at line 72 of file multiBandAbsorptionEmission.C.
References Foam::dimLength, Foam::dimless, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and timeName.
eCont()
Foam::tmp< Foam::volScalarField > eCont (const label bandI) const virtual
Reimplemented from absorptionEmissionModel.
Definition at line 99 of file multiBandAbsorptionEmission.C.
References Foam::dimLength, Foam::dimless, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and timeName.
ECont()
Foam::tmp< Foam::volScalarField > ECont (const label bandI) const virtual
Reimplemented from absorptionEmissionModel.
Definition at line 126 of file multiBandAbsorptionEmission.C.
References Foam::dimLength, Foam::dimMass, Foam::dimTime, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::pow3(), timeName, and Foam::Zero.
isGrey()
bool isGrey () const inline virtual
Reimplemented from absorptionEmissionModel.
Definition at line 124 of file multiBandAbsorptionEmission.H.
nBands()
label nBands () const inline virtual
Reimplemented from absorptionEmissionModel.
Definition at line 130 of file multiBandAbsorptionEmission.H.
Member Data Documentation
maxBands_
const int maxBands_ = 5 static
Definition at line 62 of file multiBandAbsorptionEmission.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/multiBandAbsorptionEmission/multiBandAbsorptionEmission.H
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/multiBandAbsorptionEmission/multiBandAbsorptionEmission.C