OpenFOAM: expressionEntry Class Reference
expressionEntry Class Reference
Convert dictionary entry to a stringified expression.
#include <expressionEntry.H>
Public Member Functions
TypeNameNoDebug ("expressionEntry")
declareRunTimeSelectionTable (autoPtr, expressionEntry, empty,(),())
expressionEntry () noexcept=default
virtual ~expressionEntry ()=default
virtual string toExpr (const entry &e) const
template<class Type >
Foam::string toExprStr (const Type &data)
template<class Type >
Foam::string toExprStr (ITstream &is)
Static Public Member Functions
static autoPtr< expressionEntry > New (const word &name)
static string evaluate (const entry &e)
static void inplaceExpand (std::string &s, const dictionary &dict)
static expressions::exprString expand (const std::string &str, const dictionary &dict)
Static Protected Member Functions
template<class Type >
static string toExprStr (const Type &data)
template<class Type >
static string toExprStr (ITstream &is)
Detailed Description
Convert dictionary entry to a stringified expression.
The general OpenFOAM dictionary expansions will result in space-separated values. For example,
    origin (0.21 0 0.01);
    condition  "mag(pos() - $centre) < 0.5";
this will expand to the following:
    condition  "mag(pos() - (0.21 0 0.01)) < 0.5";
For these type of expressions, we'd would like better control. Using instead the special expansions, we can add an effective type cast.
    condition  "mag(pos() - $[(vector)centre]) < 0.5";
which will expand to the following:
    condition  "mag(pos() - vector(0.21,0,0.01)) < 0.5";
Source files
expressionEntry.H
expressionEntry.C
expressionEntryI.H
Definition at line 81 of file expressionEntry.H.
Constructor & Destructor Documentation
expressionEntry()
expressionEntry () default noexcept
~expressionEntry()
virtual ~expressionEntry () virtual default
Member Function Documentation
toExprStr() [1/4]
template<class Type > static string toExprStr (const Type & data) static protected
toExprStr() [2/4]
template<class Type > static string toExprStr (ITstream & is) static protected
TypeNameNoDebug()
TypeNameNoDebug ("expressionEntry")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , expressionEntry , empty , () , ())
New()
Foam::autoPtr< Foam::exprTools::expressionEntry > New (const word & name) static
Definition at line 110 of file expressionEntry.C.
References Foam::exit(), Foam::FatalError, FatalErrorInLookup, and Foam::name().
Referenced by expressionEntry::inplaceExpand().
evaluate()
Foam::string evaluate (const entry & e) inline static
Definition at line 27 of file expressionEntryI.H.
References e.
Referenced by expressionEntry::toExpr().
inplaceExpand()
void inplaceExpand (std::string & s, const dictionary & dict) static
Definition at line 133 of file expressionEntry.C.
References dict, UPtrList< T >::empty(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::getVariableOrDie(), Foam::stringOps::inplaceExpand(), Foam::stringOps::inplaceTrim(), expressionEntry::New(), Foam::nl, s(), and UPtrList< T >::size().
Referenced by exprString::inplaceExpand().
expand()
Foam::expressions::exprString expand (const std::string & str, const dictionary & dict) static
Definition at line 264 of file expressionEntry.C.
References dict, and s().
toExpr()
virtual string toExpr (const entry & e) const inline virtual
Reimplemented in boolEntry, dimensionedScalarEntry, dimensionedVectorEntry, dimensionedTensorEntry, dimensionedSymmTensorEntry, dimensionedSphericalTensorEntry, stringEntry, vectorEntry, tensorEntry, symmTensorEntry, and sphericalTensorEntry.
Definition at line 157 of file expressionEntry.H.
References e, and expressionEntry::evaluate().
toExprStr() [3/4]
template<class Type > Foam::string toExprStr (const Type & data) inline
Definition at line 35 of file expressionEntryI.H.
References Foam::component(), and StringStreamAllocator< StreamType >::str().
toExprStr() [4/4]
template<class Type > Foam::string toExprStr (ITstream & is) inline
Definition at line 53 of file expressionEntryI.H.
References Foam::Zero.
The documentation for this class was generated from the following files:
src/OpenFOAM/expressions/exprEntry/expressionEntry.H
src/OpenFOAM/expressions/exprEntry/expressionEntry.C
src/OpenFOAM/expressions/exprEntry/expressionEntryI.H