OpenFOAM: DLListBase Class Reference
DLListBase Class Reference
Base for doubly-linked lists.
#include <DLListBase.H>
Classes
class const_iterator
class iterator
struct link
Public Member Functions
DLListBase ()=default
DLListBase (const DLListBase &)=delete
void operator= (const DLListBase &)=delete
~DLListBase ()=default
bool empty () const noexcept
label size () const noexcept
link * front ()
const link * front () const
link * back ()
const link * back () const
void push_front (link *item)
void push_back (link *item)
bool swapUp (link *item)
bool swapDown (link *item)
link * removeHead ()
link * remove (link *item)
link * remove (iterator &iter)
link * replace (link *oldLink, link *newLink)
link * replace (iterator &oldIter, link *newitem)
void clear ()
void swap (DLListBase &lst)
void transfer (DLListBase &lst)
iterator begin ()
const_iterator cbegin () const
const_iterator crbegin () const
const iterator & end ()
const const_iterator & cend () const
const const_iterator & crend () const
link * first ()
const link * first () const
link * last ()
const link * last () const
void prepend (link *item)
void append (link *item)
Protected Member Functions
template<class IteratorType >
IteratorType iterator_first () const
template<class IteratorType >
IteratorType iterator_last () const
Static Protected Member Functions
template<class IteratorType >
static const IteratorType & iterator_end ()
template<class IteratorType >
static const IteratorType & iterator_rend ()
Friends
class iterator
class const_iterator
Detailed Description
Base for doubly-linked lists.
The iterators associated with the list only have a core functionality for navigation, with additional functionality to be added by inheriting classes. The node iterators always have a node-pointer as the first member data, which allows reinterpret_cast from anything else with a nullptr as its first data member. The nullObject is such an item (with a nullptr data member).
Source files
DLListBase.H
DLListBaseI.H
DLListBase.C
Definition at line 57 of file DLListBase.H.
Constructor & Destructor Documentation
DLListBase() [1/2]
DLListBase () default
DLListBase() [2/2]
DLListBase (const DLListBase &) delete
~DLListBase()
~DLListBase () default
Member Function Documentation
iterator_end()
template<class IteratorType > const IteratorType & iterator_end () inline static protected
Definition at line 28 of file DLListBaseI.H.
References Foam::nullObjectPtr.
iterator_rend()
template<class IteratorType > const IteratorType & iterator_rend () inline static protected
Definition at line 35 of file DLListBaseI.H.
References Foam::nullObjectPtr.
iterator_first()
template<class IteratorType > IteratorType iterator_first () const inline protected
Definition at line 42 of file DLListBaseI.H.
iterator_last()
template<class IteratorType > IteratorType iterator_last () const inline protected
Definition at line 57 of file DLListBaseI.H.
operator=()
void operator= (const DLListBase &) delete
empty()
bool empty () const inline noexcept
Definition at line 149 of file DLListBase.H.
size()
label size () const inline noexcept
Definition at line 152 of file DLListBase.H.
Referenced by DLListBase::begin(), DLListBase::cbegin(), and DLListBase::crbegin().
front() [1/2]
Foam::DLListBase::link * front () inline
Definition at line 96 of file DLListBaseI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by DLListBase::first(), and DLListBase::first().
front() [2/2]
const Foam::DLListBase::link * front () const inline
Definition at line 109 of file DLListBaseI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
back() [1/2]
Foam::DLListBase::link * back () inline
Definition at line 122 of file DLListBaseI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by DLListBase::last(), and DLListBase::last().
back() [2/2]
const Foam::DLListBase::link * back () const inline
Definition at line 135 of file DLListBaseI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
push_front()
void push_front (DLListBase::link * item)
Definition at line 27 of file DLListBase.C.
References DLListBase::link::prev_.
Referenced by DLListBase::prepend().
push_back()
void push_back (DLListBase::link * item)
Definition at line 52 of file DLListBase.C.
Referenced by DLListBase::append().
swapUp()
bool swapUp (DLListBase::link * a)
Definition at line 77 of file DLListBase.C.
References DLListBase::link::next_, and DLListBase::link::prev_.
swapDown()
bool swapDown (DLListBase::link * a)
Definition at line 116 of file DLListBase.C.
References DLListBase::link::next_, and DLListBase::link::prev_.
removeHead()
Foam::DLListBase::link * removeHead ()
Definition at line 155 of file DLListBase.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
remove() [1/2]
Foam::DLListBase::link * remove (DLListBase::link * item)
Definition at line 181 of file DLListBase.C.
remove() [2/2]
Foam::DLListBase::link * remove (DLListBase::iterator & iter) inline
Definition at line 184 of file DLListBaseI.H.
replace() [1/2]
Foam::DLListBase::link * replace (DLListBase::link * oldLink, DLListBase::link * newLink)
Definition at line 213 of file DLListBase.C.
replace() [2/2]
Foam::DLListBase::link * replace (DLListBase::iterator & oldIter, DLListBase::link * newItem) inline
Definition at line 194 of file DLListBaseI.H.
clear()
void clear () inline
Definition at line 147 of file DLListBaseI.H.
swap()
void swap (DLListBase & lst) inline
Definition at line 155 of file DLListBaseI.H.
transfer()
void transfer (DLListBase & lst) inline
Definition at line 168 of file DLListBaseI.H.
References PtrList< T >::clear().
begin()
Foam::DLListBase::iterator begin () inline
Definition at line 295 of file DLListBaseI.H.
References DLListBase::end(), and DLListBase::size().
cbegin()
Foam::DLListBase::const_iterator cbegin () const inline
Definition at line 393 of file DLListBaseI.H.
References DLListBase::cend(), and DLListBase::size().
crbegin()
Foam::DLListBase::const_iterator crbegin () const inline
Definition at line 405 of file DLListBaseI.H.
References DLListBase::crend(), and DLListBase::size().
end()
const Foam::DLListBase::iterator & end () inline
Definition at line 73 of file DLListBaseI.H.
Referenced by DLListBase::begin().
cend()
const Foam::DLListBase::const_iterator & cend () const inline
Definition at line 80 of file DLListBaseI.H.
Referenced by DLListBase::cbegin().
crend()
const Foam::DLListBase::const_iterator & crend () const inline
Definition at line 87 of file DLListBaseI.H.
Referenced by DLListBase::crbegin().
first() [1/2]
link * first () inline
Definition at line 324 of file DLListBase.H.
References DLListBase::front().
first() [2/2]
const link * first () const inline
Definition at line 328 of file DLListBase.H.
References DLListBase::front().
last() [1/2]
link * last () inline
Definition at line 332 of file DLListBase.H.
References DLListBase::back().
last() [2/2]
const link * last () const inline
Definition at line 336 of file DLListBase.H.
References DLListBase::back().
prepend()
void prepend (link * item) inline
Definition at line 340 of file DLListBase.H.
References DLListBase::push_front().
append()
void append (link * item) inline
Definition at line 344 of file DLListBase.H.
References DLListBase::push_back().
Friends And Related Symbol Documentation
iterator
friend class iterator friend
Definition at line 125 of file DLListBase.H.
const_iterator
friend class const_iterator friend
Definition at line 128 of file DLListBase.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/LinkedLists/linkTypes/DLListBase/DLListBase.H
src/OpenFOAM/containers/LinkedLists/linkTypes/DLListBase/DLListBase.C
src/OpenFOAM/containers/LinkedLists/linkTypes/DLListBase/DLListBaseI.H