OpenFOAM: nutUBlendedWallFunctionFvPatchScalarField Class Reference
nutUBlendedWallFunctionFvPatchScalarField Class Reference
Turbulence models » Boundary conditions » Wall functions
This boundary condition provides a wall function for the turbulent viscosity (i.e. nut) based on velocity (i.e. U) using a binomial-function wall-function blending method between the viscous and inertial sublayer predictions of nut for low- and high-Reynolds number applications.
#include <nutUBlendedWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("nutUBlendedWallFunction")
nutUBlendedWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutUBlendedWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutUBlendedWallFunctionFvPatchScalarField (const nutUBlendedWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutUBlendedWallFunctionFvPatchScalarField (const nutUBlendedWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
nutUBlendedWallFunctionFvPatchScalarField (const nutUBlendedWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual tmp< scalarField > yPlus () const
virtual void write (Ostream &os) const
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
const wallFunctionCoefficients & wallCoeffs () const noexcept
virtual void updateCoeffs ()
Protected Member Functions
virtual tmp< scalarField > calcNut () const
tmp< scalarField > calcUTau (const scalarField &magGradU) const
void writeLocalEntries (Ostream &) const
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual const volVectorField & U (const turbulenceModel &turb) const
virtual void checkType ()
void writeLocalEntries (Ostream &) const
Protected Attributes
scalar n_
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
word UName_
wallFunctionCoefficients wallCoeffs_
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static const nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel &turbModel, const label patchi)
Detailed Description
This boundary condition provides a wall function for the turbulent viscosity (i.e. nut) based on velocity (i.e. U) using a binomial-function wall-function blending method between the viscous and inertial sublayer predictions of nut for low- and high-Reynolds number applications.
where
= Friction velocity
= Friction velocity in the viscous sublayer
= Friction velocity in the inertial sublayer
Reference:
        See the section that describes 'automatic wall treatment':
            Menter, F., Ferreira, J. C., Esch, T., Konno, B. (2003).
            The SST turbulence model with improved wall treatment
            for heat transfer predictions in gas turbines.
            In Proceedings of the International Gas Turbine Congress.
            November, 2003. Tokyo, Japan. pp. 2-7.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            nutUBlendedWallFunction;
    // Optional entries
    n               4.0;
    // Inherited entries
    ...
 }
where the entries mean:
Property Description Type Reqd Deflt
type Type name: nutUBlendedWallFunction word yes -
n Blending factor scalar no 4.0
The inherited entries are elaborated in:
nutWallFunctionFvPatchScalarField.H
Note
The full 'automatic wall treatment' description also requires use of the omegaWallFunctionFvPatchScalarField.H with the blending option binomial or with the deprecated blended flag set to on.
Suffers from non-exact restart since correctNut() (called through turbulence->validate) returns a slightly different value every time it is called. See nutUSpaldingWallFunctionFvPatchScalarField.C.
Source files
nutUBlendedWallFunctionFvPatchScalarField.H
nutUBlendedWallFunctionFvPatchScalarField.C
Definition at line 139 of file nutUBlendedWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutUBlendedWallFunctionFvPatchScalarField() [1/5]
nutUBlendedWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 131 of file nutUBlendedWallFunctionFvPatchScalarField.C.
nutUBlendedWallFunctionFvPatchScalarField() [2/5]
nutUBlendedWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 157 of file nutUBlendedWallFunctionFvPatchScalarField.C.
nutUBlendedWallFunctionFvPatchScalarField() [3/5]
nutUBlendedWallFunctionFvPatchScalarField (const nutUBlendedWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 143 of file nutUBlendedWallFunctionFvPatchScalarField.C.
nutUBlendedWallFunctionFvPatchScalarField() [4/5]
nutUBlendedWallFunctionFvPatchScalarField (const nutUBlendedWallFunctionFvPatchScalarField & wfpsf)
Definition at line 170 of file nutUBlendedWallFunctionFvPatchScalarField.C.
nutUBlendedWallFunctionFvPatchScalarField() [5/5]
nutUBlendedWallFunctionFvPatchScalarField (const nutUBlendedWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 181 of file nutUBlendedWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcNut()
Foam::tmp< Foam::scalarField > calcNut () const protected virtual
Implements nutWallFunctionFvPatchScalarField.
Definition at line 30 of file nutUBlendedWallFunctionFvPatchScalarField.C.
References nutUBlendedWallFunctionFvPatchScalarField::calcUTau(), IOobject::groupName(), Foam::mag(), Foam::max(), turbulenceModel::propertiesName, Foam::sqr(), and U.
calcUTau()
Foam::tmp< Foam::scalarField > calcUTau (const scalarField & magGradU) const protected
Definition at line 58 of file nutUBlendedWallFunctionFvPatchScalarField.C.
References e, forAll, IOobject::groupName(), Foam::log(), Foam::mag(), magUp, Foam::max(), n, tmp< T >::New(), fvPatchField< Type >::patchInternalField(), Foam::pow(), turbulenceModel::propertiesName, Foam::sqrt(), U, y, yPlus, and Foam::Zero.
Referenced by nutUBlendedWallFunctionFvPatchScalarField::calcNut().
writeLocalEntries()
void writeLocalEntries (Ostream & os) const protected
Definition at line 120 of file nutUBlendedWallFunctionFvPatchScalarField.C.
References os(), and Ostream::writeEntryIfDifferent().
TypeName()
TypeName ("nutUBlendedWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 204 of file nutUBlendedWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 220 of file nutUBlendedWallFunctionFvPatchScalarField.H.
yPlus()
Foam::tmp< Foam::scalarField > yPlus () const virtual
Implements nutWallFunctionFvPatchScalarField.
Definition at line 196 of file nutUBlendedWallFunctionFvPatchScalarField.C.
References IOobject::groupName(), Foam::mag(), turbulenceModel::propertiesName, fvPatchField< Type >::snGrad(), U, and y.
write()
void write (Ostream & os) const virtual
Reimplemented from nutWallFunctionFvPatchScalarField.
Definition at line 221 of file nutUBlendedWallFunctionFvPatchScalarField.C.
References os(), nutWallFunctionFvPatchScalarField::write(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
n_
scalar n_ protected
Definition at line 148 of file nutUBlendedWallFunctionFvPatchScalarField.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutUBlendedWallFunction/nutUBlendedWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutUBlendedWallFunction/nutUBlendedWallFunctionFvPatchScalarField.C