OpenFOAM: sliceRange Class Reference
sliceRange Class Reference
A set of labels defined by a start, a length and a stride.
#include <sliceRange.H>
Classes
class const_iterator
class const_reverse_iterator
class indexer
Public Types
typedef label value_type
typedef label size_type
Public Member Functions
constexpr sliceRange () noexcept
constexpr sliceRange (const label beg, const label len, const label stride) noexcept
sliceRange (const FixedList< label, 3 > &coeffs)
constexpr label start () const noexcept
constexpr label size () const noexcept
constexpr label stride () const noexcept
bool empty () const noexcept
constexpr label min () const noexcept
label max () const noexcept
List< label > labels () const
label operator[] (const label i) const noexcept
operator bool () const noexcept
indexer generator () const
const_iterator at (const label i) const
const_iterator begin () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator end () const noexcept
const_reverse_iterator rbegin () const noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator rend () const noexcept
const_reverse_iterator crend () const noexcept
Detailed Description
A set of labels defined by a start, a length and a stride.
Source files
sliceRange.H
sliceRange.C
sliceRangeI.H
Definition at line 52 of file sliceRange.H.
Member Typedef Documentation
value_type
typedef label value_type
Definition at line 71 of file sliceRange.H.
size_type
typedef label size_type
Definition at line 74 of file sliceRange.H.
Constructor & Destructor Documentation
sliceRange() [1/3]
constexpr sliceRange () inline constexpr noexcept
Definition at line 23 of file sliceRangeI.H.
sliceRange() [2/3]
constexpr sliceRange (const label beg, const label len, const label stride) inline constexpr noexcept
Definition at line 31 of file sliceRangeI.H.
sliceRange() [3/3]
sliceRange (const FixedList< label, 3 > & coeffs) explicit
Definition at line 28 of file sliceRange.C.
References Foam::max().
Member Function Documentation
start()
constexpr label start () const inline constexpr noexcept
Definition at line 109 of file sliceRange.H.
Referenced by Foam::operator<(), and Foam::operator==().
size()
constexpr label size () const inline constexpr noexcept
Definition at line 112 of file sliceRange.H.
Referenced by Foam::operator<(), and Foam::operator==().
stride()
constexpr label stride () const inline constexpr noexcept
Definition at line 115 of file sliceRange.H.
Referenced by Foam::operator<(), and Foam::operator==().
empty()
bool empty () const inline noexcept
Definition at line 118 of file sliceRange.H.
min()
constexpr label min () const inline constexpr noexcept
Definition at line 121 of file sliceRange.H.
max()
label max () const inline noexcept
Definition at line 125 of file sliceRange.H.
labels()
Foam::List< Foam::label > labels () const
Definition at line 38 of file sliceRange.C.
References UPtrList< T >::begin(), and UPtrList< T >::end().
operator[]()
label operator[] (const label i) const inline noexcept
Definition at line 134 of file sliceRange.H.
operator bool()
operator bool () const inline explicit noexcept
Definition at line 140 of file sliceRange.H.
generator()
Foam::sliceRange::indexer generator () const inline
Definition at line 289 of file sliceRangeI.H.
at()
Foam::sliceRange::const_iterator at (const label i) const inline
Definition at line 296 of file sliceRangeI.H.
begin()
Foam::sliceRange::const_iterator begin () const inline noexcept
Definition at line 308 of file sliceRangeI.H.
cbegin()
Foam::sliceRange::const_iterator cbegin () const inline noexcept
Definition at line 315 of file sliceRangeI.H.
cend()
Foam::sliceRange::const_iterator cend () const inline noexcept
Definition at line 329 of file sliceRangeI.H.
end()
Foam::sliceRange::const_iterator end () const inline noexcept
Definition at line 322 of file sliceRangeI.H.
rbegin()
Foam::sliceRange::const_reverse_iterator rbegin () const inline noexcept
Definition at line 336 of file sliceRangeI.H.
crbegin()
Foam::sliceRange::const_reverse_iterator crbegin () const inline noexcept
Definition at line 343 of file sliceRangeI.H.
rend()
Foam::sliceRange::const_reverse_iterator rend () const inline noexcept
Definition at line 350 of file sliceRangeI.H.
crend()
Foam::sliceRange::const_reverse_iterator crend () const inline noexcept
Definition at line 357 of file sliceRangeI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/ranges/sliceRange/sliceRange.H
src/OpenFOAM/primitives/ranges/sliceRange/sliceRange.C
src/OpenFOAM/primitives/ranges/sliceRange/sliceRangeI.H