OpenFOAM: linear Class Reference
linear Class Reference
A linear model for wall heat flux partitioning based on Ioilev et al. (2007) for boiling flows.
#include <linear.H>
Public Member Functions
TypeName ("linear")
linear (const dictionary &dict)
virtual ~linear ()=default
virtual tmp< scalarField > fLiquid (const scalarField &alphaLiquid) const
virtual void write (Ostream &os) const
Public Member Functions inherited from partitioningModel
TypeName ("partitioningModel")
declareRunTimeSelectionTable (autoPtr, partitioningModel, dictionary,(const dictionary &dict),(dict))
partitioningModel ()=default
virtual ~partitioningModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from partitioningModel
static autoPtr< partitioningModel > New (const dictionary &dict)
Detailed Description
A linear model for wall heat flux partitioning based on Ioilev et al. (2007) for boiling flows.
Reference:
    Ioilev, A., Samigulin, M., Ustinenko, V.,
    Kucherova, P., Tentner, A., Lo, S., & Splawski, A. (2007).
    Advances in the modeling of cladding heat transfer
    and critical heat flux in boiling water reactor fuel assemblies.
    In Proc. 12th International Topical Meeting on Nuclear Reactor
    Thermal Hydraulics (NURETH-12).
    Pittsburgh, Pennsylvania, USA.
Usage
Example of the model specification:
partitioningModel
{
    // Mandatory entries
    type            linear;
    alphaLiquid1    <scalar>;
    alphaLiquid0    <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: linear word yes -
alphaLiquid1
Model parameters for threshold liquid phase fraction
scalar yes -
alphaLiquid0
Model parameters for threshold liquid phase fraction
scalar yes -
Note
Proposed threshold liquid fractions:
alphaLiquid1 0.1
alphaLiquid0 0.05
Source files
linear.H
linear.C
Definition at line 118 of file linear.H.
Constructor & Destructor Documentation
linear()
linear (const dictionary & dict)
Definition at line 47 of file linear.C.
~linear()
virtual ~linear () virtual default
Member Function Documentation
TypeName()
TypeName ("linear")
fLiquid()
Foam::tmp< Foam::scalarField > fLiquid (const scalarField & alphaLiquid) const virtual
Implements partitioningModel.
Definition at line 59 of file linear.C.
References Foam::max(), and Foam::min().
write()
void write (Ostream & os) const virtual
Reimplemented from partitioningModel.
Definition at line 78 of file linear.C.
References os(), and partitioningModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/partitioningModels/linear/linear.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/partitioningModels/linear/linear.C