OpenFOAM: filmPyrolysisVelocityCoupledFvPatchVectorField Class Reference
filmPyrolysisVelocityCoupledFvPatchVectorField Class Reference
This boundary condition is designed to be used in conjunction with surface film and pyrolysis modelling.
#include <filmPyrolysisVelocityCoupledFvPatchVectorField.H>
Public Member Functions
TypeName ("filmPyrolysisVelocityCoupled")
filmPyrolysisVelocityCoupledFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
filmPyrolysisVelocityCoupledFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
filmPyrolysisVelocityCoupledFvPatchVectorField (const filmPyrolysisVelocityCoupledFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
filmPyrolysisVelocityCoupledFvPatchVectorField (const filmPyrolysisVelocityCoupledFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
filmPyrolysisVelocityCoupledFvPatchVectorField (const filmPyrolysisVelocityCoupledFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
const word & phiName () const
word & phiName ()
const word & rhoName () const
word & rhoName ()
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition is designed to be used in conjunction with surface film and pyrolysis modelling.
It provides a velocity boundary condition for patches on the primary region based on whether the patch is seen to be 'wet', retrieved from the film alpha field.
if the patch is wet, the velocity is set using the film velocity
otherwise, it is set using pyrolysis out-gassing velocity
Example of the boundary condition specification:
<patchName>
{
    type            filmPyrolysisVelocityCoupled;
    phi             phi;      // name of flux field (default = phi)
    rho             rho;      // name of density field (default = rho)
    deltaWet        1e-4;     // threshold height for 'wet' film
    value           uniform   (0 0 0); // initial velocity / [m/s]
}
Source files
filmPyrolysisVelocityCoupledFvPatchVectorField.H
filmPyrolysisVelocityCoupledFvPatchVectorField.C
Definition at line 65 of file filmPyrolysisVelocityCoupledFvPatchVectorField.H.
Constructor & Destructor Documentation
filmPyrolysisVelocityCoupledFvPatchVectorField() [1/5]
filmPyrolysisVelocityCoupledFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 30 of file filmPyrolysisVelocityCoupledFvPatchVectorField.C.
filmPyrolysisVelocityCoupledFvPatchVectorField() [2/5]
filmPyrolysisVelocityCoupledFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 62 of file filmPyrolysisVelocityCoupledFvPatchVectorField.C.
filmPyrolysisVelocityCoupledFvPatchVectorField() [3/5]
filmPyrolysisVelocityCoupledFvPatchVectorField (const filmPyrolysisVelocityCoupledFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 45 of file filmPyrolysisVelocityCoupledFvPatchVectorField.C.
filmPyrolysisVelocityCoupledFvPatchVectorField() [4/5]
filmPyrolysisVelocityCoupledFvPatchVectorField (const filmPyrolysisVelocityCoupledFvPatchVectorField & fpvpvf)
Definition at line 84 of file filmPyrolysisVelocityCoupledFvPatchVectorField.C.
filmPyrolysisVelocityCoupledFvPatchVectorField() [5/5]
filmPyrolysisVelocityCoupledFvPatchVectorField (const filmPyrolysisVelocityCoupledFvPatchVectorField & fpvpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 98 of file filmPyrolysisVelocityCoupledFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("filmPyrolysisVelocityCoupled")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 124 of file filmPyrolysisVelocityCoupledFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 140 of file filmPyrolysisVelocityCoupledFvPatchVectorField.H.
phiName() [1/2]
const word & phiName () const inline
Definition at line 157 of file filmPyrolysisVelocityCoupledFvPatchVectorField.H.
phiName() [2/2]
word & phiName () inline
Definition at line 163 of file filmPyrolysisVelocityCoupledFvPatchVectorField.H.
rhoName() [1/2]
const word & rhoName () const inline
Definition at line 169 of file filmPyrolysisVelocityCoupledFvPatchVectorField.H.
rhoName() [2/2]
word & rhoName () inline
Definition at line 175 of file filmPyrolysisVelocityCoupledFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 115 of file filmPyrolysisVelocityCoupledFvPatchVectorField.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPstream::msgType(), Foam::nl, and phi.
write()
void write (Ostream & os) const virtual
Definition at line 203 of file filmPyrolysisVelocityCoupledFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/regionModels/regionCoupling/derivedFvPatchFields/filmPyrolysisVelocityCoupled/filmPyrolysisVelocityCoupledFvPatchVectorField.H
src/regionModels/regionCoupling/derivedFvPatchFields/filmPyrolysisVelocityCoupled/filmPyrolysisVelocityCoupledFvPatchVectorField.C