OpenFOAM: HeterogeneousReactingModel< CloudType > Class Template Reference
HeterogeneousReactingModel< CloudType > Class Template Reference abstract
Base class for heterogeneous reacting models.
#include <HeterogeneousReactingModel.H>
Public Member Functions
TypeName ("heterogeneousReactionModel")
declareRunTimeSelectionTable (autoPtr, HeterogeneousReactingModel, dictionary,(const dictionary &dict, CloudType &cloud),(dict, cloud))
HeterogeneousReactingModel (CloudType &owner)
HeterogeneousReactingModel (const dictionary &dict, CloudType &cloud, const word &type)
HeterogeneousReactingModel (const HeterogeneousReactingModel< CloudType > &srm)
virtual autoPtr< HeterogeneousReactingModel< CloudType > > clone () const =0
virtual ~HeterogeneousReactingModel ()=default
virtual scalar calculate (const scalar dt, const scalar Re, const scalar nu, const label celli, const scalar d, const scalar T, const scalar Tc, const scalar pc, const scalar rhoc, const scalar mass, const scalarField &YSolid, scalarField &F, const scalar N, scalar &NCpW, scalarField &dMassSolid, scalarField &dMassSRCarrier) const =0
void addToSurfaceReactionMass (const scalar dMass)
virtual label nReactions () const =0
virtual label nF () const
virtual void info ()
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Static Public Member Functions
static autoPtr< HeterogeneousReactingModel< CloudType > > New (const dictionary &dict, CloudType &cloud)
Protected Attributes
scalar dMass_
label nF_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Detailed Description
template<class CloudType>
class Foam::HeterogeneousReactingModel< CloudType >
Base class for heterogeneous reacting models.
Source files
HeterogeneousReactingModel.H
HeterogeneousReactingModel.C
HeterogeneousReactingModelNew.C
Definition at line 55 of file HeterogeneousReactingModel.H.
Constructor & Destructor Documentation
HeterogeneousReactingModel() [1/3]
template<class CloudType > HeterogeneousReactingModel (CloudType & owner)
Definition at line 26 of file HeterogeneousReactingModel.C.
HeterogeneousReactingModel() [2/3]
template<class CloudType > HeterogeneousReactingModel (const dictionary & dict, CloudType & cloud, const word & type)
Definition at line 38 of file HeterogeneousReactingModel.C.
HeterogeneousReactingModel() [3/3]
template<class CloudType > HeterogeneousReactingModel (const HeterogeneousReactingModel< CloudType > & srm)
Definition at line 52 of file HeterogeneousReactingModel.C.
~HeterogeneousReactingModel()
template<class CloudType > virtual ~HeterogeneousReactingModel () virtual default
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("heterogeneousReactionModel")
declareRunTimeSelectionTable()
template<class CloudType > declareRunTimeSelectionTable (autoPtr , HeterogeneousReactingModel< CloudType > , dictionary , (const dictionary &dict, CloudType &cloud) , (dict, cloud))
clone()
template<class CloudType > virtual autoPtr< HeterogeneousReactingModel< CloudType > > clone () const pure virtual
Implemented in MUCSheterogeneousRate< CloudType >, and NoheterogeneousReacting< CloudType >.
New()
template<class CloudType > Foam::autoPtr< Foam::HeterogeneousReactingModel< CloudType > > New (const dictionary & dict, CloudType & cloud) static
Definition at line 27 of file HeterogeneousReactingModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and PtrList< T >::PtrList().
calculate()
template<class CloudType > virtual scalar calculate (const scalar dt, const scalar Re, const scalar nu, const label celli, const scalar d, const scalar T, const scalar Tc, const scalar pc, const scalar rhoc, const scalar mass, const scalarField & YSolid, scalarField & F, const scalar N, scalar & NCpW, scalarField & dMassSolid, scalarField & dMassSRCarrier) const pure virtual
Implemented in MUCSheterogeneousRate< CloudType >, and NoheterogeneousReacting< CloudType >.
addToSurfaceReactionMass()
template<class CloudType > void addToSurfaceReactionMass (const scalar dMass)
Definition at line 66 of file HeterogeneousReactingModel.C.
nReactions()
template<class CloudType > virtual label nReactions () const pure virtual
Implemented in MUCSheterogeneousRate< CloudType >, and NoheterogeneousReacting< CloudType >.
nF()
template<class CloudType > Foam::label nF () const virtual
Definition at line 76 of file HeterogeneousReactingModel.C.
info()
template<class CloudType > void info () virtual
Reimplemented from CloudSubModelBase< CloudType >.
Definition at line 83 of file HeterogeneousReactingModel.C.
References CloudSubModelBase< CloudType >::info(), Log_, Foam::nl, and Foam::returnReduce().
Member Data Documentation
dMass_
template<class CloudType > scalar dMass_ protected
Definition at line 64 of file HeterogeneousReactingModel.H.
nF_
template<class CloudType > label nF_ protected
Definition at line 67 of file HeterogeneousReactingModel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/ReactingHeterogeneousCloud/ReactingHeterogeneousCloud.H
src/lagrangian/intermediate/submodels/HeterogeneousReactingModel/HeterogeneousReactingModel/HeterogeneousReactingModel.H
src/lagrangian/intermediate/submodels/HeterogeneousReactingModel/HeterogeneousReactingModel/HeterogeneousReactingModel.C
src/lagrangian/intermediate/submodels/HeterogeneousReactingModel/HeterogeneousReactingModel/HeterogeneousReactingModelNew.C