OpenFOAM: ensightCase Class Reference
ensightCase Class Reference
Supports writing of ensight cases as well as providing common factory methods to open new files.
#include <ensightCase.H>
Classes
class options
Public Member Functions
ensightCase (const fileName &ensightDir, const word &caseName, const options &opts)
ensightCase (const fileName &ensightDir, const word &caseName, const IOstreamOption::streamFormat fmt=IOstreamOption::BINARY)
~ensightCase ()=default
const ensightCase::options & option () const
IOstreamOption::streamFormat format () const
const fileName & path () const noexcept
const word & mask () const
word padded (const label i) const
bool nodeValues () const
bool separateCloud () const
void nextTime (const scalar t)
void nextTime (const instant &t)
void setTime (const scalar t, const label index)
void setTime (const instant &t, const label index)
autoPtr< ensightGeoFile > newGeometry (bool moving=false) const
autoPtr< ensightFile > newCloud (const word &cloudName) const
template<class Type >
autoPtr< ensightFile > newData (const word &varName, const bool isPointData=false) const
template<class Type >
autoPtr< ensightFile > newPointData (const word &varName) const
template<class Type >
autoPtr< ensightFile > newCloudData (const word &cloudName, const word &varName) const
void rewind () const
void write () const
Ostream & operator() () const
Ostream & printInfo (Ostream &os) const
template<class Type >
Foam::autoPtr< Foam::ensightFile > newData (const word &name, const bool isPointData) const
template<class Type >
Foam::autoPtr< Foam::ensightFile > newPointData (const word &name) const
template<class Type >
Foam::autoPtr< Foam::ensightFile > newCloudData (const word &cloudName, const word &name) const
Static Public Member Functions
static word padded (const int nwidth, const label value)
static void printTimeset (OSstream &os, const label ts, const scalar timeValue)
static void printTimeset (OSstream &os, const label ts, const UList< scalar > &times)
static void printTimeset (OSstream &os, const label ts, const UList< scalar > &times, const bitSet &indices)
Static Public Attributes
static const char * dataDirName = "data"
static const char * geometryName = "geometry"
Detailed Description
Supports writing of ensight cases as well as providing common factory methods to open new files.
Source files
ensightCase.H
ensightCase.C
ensightCaseI.H
ensightCaseOptions.C
ensightCaseTemplates.C
Definition at line 64 of file ensightCase.H.
Constructor & Destructor Documentation
ensightCase() [1/2]
ensightCase (const fileName & ensightDir, const word & caseName, const options & opts)
Definition at line 510 of file ensightCase.C.
ensightCase() [2/2]
ensightCase (const fileName & ensightDir, const word & caseName, const IOstreamOption::streamFormat fmt = IOstreamOption::BINARY)
Definition at line 535 of file ensightCase.C.
~ensightCase()
~ensightCase () default
Member Function Documentation
padded() [1/2]
Foam::word padded (const int nwidth, const label value) static
Definition at line 38 of file ensightCase.C.
References Foam::name().
Referenced by ensightCase::newData(), ensightSurfaceReader::replaceMask(), ensightWriter::writeCollated(), and ensightWriter::writeCollated().
option()
const Foam::ensightCase::options & option () const inline
Definition at line 23 of file ensightCaseI.H.
format()
Foam::IOstreamOption::streamFormat format () const inline
Definition at line 29 of file ensightCaseI.H.
path()
const Foam::fileName & path () const inline noexcept
Definition at line 35 of file ensightCaseI.H.
mask()
const Foam::word & mask () const inline
Definition at line 41 of file ensightCaseI.H.
padded() [2/2]
Foam::word padded (const label i) const inline
Definition at line 47 of file ensightCaseI.H.
nodeValues()
bool nodeValues () const inline
Definition at line 53 of file ensightCaseI.H.
Referenced by Foam::writeVolField().
separateCloud()
bool separateCloud () const inline
Definition at line 59 of file ensightCaseI.H.
nextTime() [1/2]
void nextTime (const scalar t)
Definition at line 562 of file ensightCase.C.
References setTime(), and UPtrList< T >::size().
nextTime() [2/2]
void nextTime (const instant & t)
Definition at line 569 of file ensightCase.C.
References Instant< T >::value().
setTime() [1/2]
void setTime (const scalar t, const label index)
Definition at line 575 of file ensightCase.C.
References UPstream::master(), Foam::mkDir(), Foam::nl, and PtrList< T >::set().
setTime() [2/2]
void setTime (const instant & t, const label index)
Definition at line 600 of file ensightCase.C.
References setTime(), and Instant< T >::value().
newGeometry()
Foam::autoPtr< Foam::ensightGeoFile > newGeometry (bool moving = false) const
Definition at line 799 of file ensightCase.C.
References format(), UPstream::master(), Foam::mkDir(), autoPtr< T >::New(), Foam::output(), and path().
newCloud()
Foam::autoPtr< Foam::ensightFile > newCloud (const word & cloudName) const
Definition at line 833 of file ensightCase.C.
References cloudName(), UPstream::master(), Foam::output(), and cloud::prefix.
newData() [1/2]
template<class Type > autoPtr< ensightFile > newData (const word & varName, const bool isPointData = false) const
Referenced by Foam::writeAreaField(), Foam::writePointField(), Foam::writeVolField(), and ensightWrite::writeVolFieldsImpl().
newPointData() [1/2]
template<class Type > autoPtr< ensightFile > newPointData (const word & varName) const
newCloudData() [1/2]
template<class Type > autoPtr< ensightFile > newCloudData (const word & cloudName, const word & varName) const
rewind()
void rewind () const
Definition at line 858 of file ensightCase.C.
write()
void write () const
Definition at line 606 of file ensightCase.C.
References cloudName(), Foam::flush(), Foam::name(), Foam::nl, cloud::prefix, word::printf(), Foam::setw(), and Foam::writeHeader().
operator()()
Foam::Ostream & operator() () const inline
Definition at line 67 of file ensightCaseI.H.
printInfo()
Foam::Ostream & printInfo (Ostream & os) const
Definition at line 867 of file ensightCase.C.
References format(), Foam::nl, and os().
printTimeset() [1/3]
void printTimeset (OSstream & os, const label ts, const scalar timeValue) static
Definition at line 52 of file ensightCase.C.
References Foam::nl, and os().
Referenced by ensightWriter::writeCollated(), ensightWriter::writeCollated(), ensightWriter::writeUncollated(), and ensightWriter::writeUncollated().
printTimeset() [2/3]
void printTimeset (OSstream & os, const label ts, const UList< scalar > & times) static
Definition at line 73 of file ensightCase.C.
References Foam::nl, os(), Foam::setf(), and Foam::setw().
printTimeset() [3/3]
void printTimeset (OSstream & os, const label ts, const UList< scalar > & times, const bitSet & indices) static
Definition at line 108 of file ensightCase.C.
References bitSet::all(), bitSet::count(), Foam::nl, os(), Foam::setf(), Foam::setw(), and PackedList< Width >::size().
newData() [2/2]
template<class Type > Foam::autoPtr< Foam::ensightFile > newData (const word & name, const bool isPointData) const
Definition at line 28 of file ensightCaseTemplates.C.
References UPstream::master(), Foam::name(), Foam::output(), ensightCase::padded(), and PtrList< T >::set().
newPointData() [2/2]
template<class Type > Foam::autoPtr< Foam::ensightFile > newPointData (const word & name) const
Definition at line 68 of file ensightCaseTemplates.C.
References Foam::name().
newCloudData() [2/2]
template<class Type > Foam::autoPtr< Foam::ensightFile > newCloudData (const word & cloudName, const word & name) const
Definition at line 79 of file ensightCaseTemplates.C.
References cloudName(), UPstream::master(), Foam::name(), and Foam::output().
Member Data Documentation
dataDirName
const char * dataDirName = "data" static
Definition at line 74 of file ensightCase.H.
geometryName
const char * geometryName = "geometry" static
Definition at line 77 of file ensightCase.H.
Referenced by ensightWriter::writeCollated(), and ensightWriter::writeCollated().
The documentation for this class was generated from the following files:
src/fileFormats/ensight/file/ensightCase.H
src/fileFormats/ensight/file/ensightCase.C
src/fileFormats/ensight/file/ensightCaseI.H
src/fileFormats/ensight/file/ensightCaseTemplates.C