OpenFOAM: surfaceSets Class Reference
surfaceSets Class Reference
Various utilities to handle sets relating mesh to surface. Note: work in progress. Used in meshing tools.
#include <surfaceSets.H>
Static Public Member Functions
static void getSurfaceSets (const polyMesh &mesh, const fileName &surfName, const triSurface &surf, const triSurfaceSearch &querySurf, const pointField &outsidePts, const label nCutLayers, labelHashSet &inside, labelHashSet &outside, labelHashSet &cut)
static labelHashSet getHangingCells (const primitiveMesh &mesh, const labelHashSet &internalCells)
Detailed Description
Various utilities to handle sets relating mesh to surface. Note: work in progress. Used in meshing tools.
Source files
surfaceSets.H
surfaceSets.C
Definition at line 60 of file surfaceSets.H.
Member Function Documentation
getSurfaceSets()
void getSurfaceSets (const polyMesh & mesh, const fileName & surfName, const triSurface & surf, const triSurfaceSearch & querySurf, const pointField & outsidePts, const label nCutLayers, labelHashSet & inside, labelHashSet & outside, labelHashSet & cut) static
Definition at line 214 of file surfaceSets.C.
References cellClassification::CUT, forAll, HashSet< Key, Hash >::insert(), cellClassification::INSIDE, mesh, and cellClassification::OUTSIDE.
getHangingCells()
Foam::labelHashSet getHangingCells (const primitiveMesh & mesh, const labelHashSet & internalCells) static
Definition at line 273 of file surfaceSets.C.
References cells, primitiveMesh::cells(), f(), polyMesh::faces(), forAll, mesh, primitiveMesh::nCells(), primitiveMesh::nPoints(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/meshTools/surfaceSets/surfaceSets.H
src/meshTools/surfaceSets/surfaceSets.C