OpenFOAM: InjectedParticleInjection< CloudType > Class Template Reference
InjectedParticleInjection< CloudType > Class Template Reference
Replays an set of particle data based on an injectedParticleCloud, using the assumption of one particle per parcel.
#include <InjectedParticleInjection.H>
Public Member Functions
TypeName ("injectedParticleInjection")
InjectedParticleInjection (const dictionary &dict, CloudType &owner, const word &modelName)
InjectedParticleInjection (const InjectedParticleInjection< CloudType > &im)
virtual autoPtr< InjectionModel< CloudType > > clone () const
virtual ~InjectedParticleInjection ()=default
virtual void updateMesh ()
scalar timeEnd () const
virtual label parcelsToInject (const scalar time0, const scalar time1)
virtual scalar volumeToInject (const scalar time0, const scalar time1)
virtual void setPositionAndCell (const label parceli, const label nParcels, const scalar time, vector &position, label &cellOwner, label &tetFacei, label &tetPti)
virtual void setProperties (const label parceli, const label nParcels, const scalar time, typename CloudType::parcelType &parcel)
virtual bool fullyDescribed () const
virtual bool validInjection (const label parceli)
void info ()
Public Member Functions inherited from InjectionModel< CloudType >
TypeName ("injectionModel")
declareRunTimeSelectionTable (autoPtr, InjectionModel, dictionary,(const dictionary &dict, CloudType &owner, const word &modelType),(dict, owner, modelType))
InjectionModel (CloudType &owner)
InjectionModel (const dictionary &dict, CloudType &owner, const word &modelName, const word &modelType)
InjectionModel (const InjectionModel< CloudType > &im)
virtual ~InjectionModel ()=default
scalar timeStart () const
scalar volumeTotal () const
scalar massTotal () const
scalar massInjected () const
label injectorID () const
virtual scalar averageParcelMass ()
label nInjections () const
label parcelsAddedTotal () const
template<class TrackCloudType >
void inject (TrackCloudType &cloud, typename CloudType::parcelType::trackingData &td)
template<class TrackCloudType >
void injectSteadyState (TrackCloudType &cloud, typename CloudType::parcelType::trackingData &td, const scalar trackTime)
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Protected Member Functions
void initialise ()
Protected Member Functions inherited from InjectionModel< CloudType >
virtual bool prepareForNextTimeStep (const scalar time, label &newParcels, scalar &newVolumeFraction)
virtual bool findCellAtPosition (label &celli, label &tetFacei, label &tetPti, vector &position, bool errorOnNotFound=true)
virtual scalar setNumberOfParticles (const label parcels, const scalar volumeFraction, const scalar diameter, const scalar rho)
virtual void postInjectCheck (const label parcelsAdded, const scalar massAdded)
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes
const word cloudName_
labelList injectorCells_
labelList injectorTetFaces_
labelList injectorTetPts_
scalarList time_
vectorList position_
vector positionOffset_
scalarList diameter_
vectorList U_
scalarList volume_
Switch ignoreOutOfBounds_
label currentParticlei_
Protected Attributes inherited from InjectionModel< CloudType >
scalar SOI_
scalar volumeTotal_
scalar massTotal_
autoPtr< Function1< scalar > > massFlowRate_
scalar massInjected_
label nInjections_
label parcelsAddedTotal_
parcelBasis parcelBasis_
scalar nParticleFixed_
scalar time0_
scalar timeStep0_
scalar minParticlesPerParcel_
scalar delayedVolume_
label injectorID_
bool ignoreOutOfBounds_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Additional Inherited Members
Public Types inherited from InjectionModel< CloudType >
enum parcelBasis { pbNumber , pbMass , pbFixed }
typedef CloudType::parcelType parcelType
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from InjectionModel< CloudType >
static autoPtr< InjectionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
static autoPtr< InjectionModel< CloudType > > New (const dictionary &dict, const word &modelName, const word &modelType, CloudType &owner)
Public Attributes inherited from subModelBase
bool log
Detailed Description
template<class CloudType>
class Foam::InjectedParticleInjection< CloudType >
Replays an set of particle data based on an injectedParticleCloud, using the assumption of one particle per parcel.
Usage
model1
{
    type            injectedParticleInjection;
    SOI             0;
    massTotal       0; // Place holder only
    parcelBasisType fixed;
    nParticle       1; // 1 particle per parcel
    cloud           eulerianParticleCloud;
    positionOffset  (-0.025 2 -0.025);
}
Source files
InjectedParticleInjection.H
InjectedParticleInjection.C
See also
Foam::injectedParticle Foam::injectedParticleCloud Foam::functionObjects::extractEulerianParticles
Definition at line 71 of file InjectedParticleInjection.H.
Constructor & Destructor Documentation
InjectedParticleInjection() [1/2]
template<class CloudType > InjectedParticleInjection (const dictionary & dict, CloudType & owner, const word & modelName)
Definition at line 132 of file InjectedParticleInjection.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, InjectedParticleInjection< CloudType >::initialise(), InjectedParticleInjection< CloudType >::injectorCells_, InjectedParticleInjection< CloudType >::injectorTetFaces_, InjectedParticleInjection< CloudType >::injectorTetPts_, InjectionModel< CloudType >::massTotal_, subModelBase::modelName(), CloudSubModelBase< CloudType >::owner(), InjectionModel< CloudType >::parcelBasis_, InjectedParticleInjection< CloudType >::position_, List< T >::setSize(), UList< T >::size(), InjectedParticleInjection< CloudType >::time_, InjectedParticleInjection< CloudType >::updateMesh(), and InjectionModel< CloudType >::volumeTotal_.
InjectedParticleInjection() [2/2]
template<class CloudType > InjectedParticleInjection (const InjectedParticleInjection< CloudType > & im)
Definition at line 188 of file InjectedParticleInjection.C.
~InjectedParticleInjection()
template<class CloudType > virtual ~InjectedParticleInjection () virtual default
Member Function Documentation
initialise()
template<class CloudType > void initialise () protected
Definition at line 31 of file InjectedParticleInjection.C.
References Pstream::allGatherList(), Foam::endl(), forAll, Foam::Info, mesh, Foam::min(), UPstream::myProcNo(), UPstream::nProcs(), p, UPstream::parRun(), Foam::constant::mathematical::pi(), Foam::pow3(), PtrList< T >::PtrList(), HashTable< T, Key, Hash >::size(), UPtrList< T >::size(), Foam::sortedOrder(), PtrList< T >::transfer(), and U.
Referenced by InjectedParticleInjection< CloudType >::InjectedParticleInjection().
TypeName()
template<class CloudType > TypeName ("injectedParticleInjection")
clone()
template<class CloudType > virtual autoPtr< InjectionModel< CloudType > > clone () const inline virtual
Implements InjectionModel< CloudType >.
Definition at line 145 of file InjectedParticleInjection.H.
updateMesh()
template<class CloudType > void updateMesh () virtual
Reimplemented from InjectionModel< CloudType >.
Definition at line 212 of file InjectedParticleInjection.C.
References Foam::endl(), forAll, Foam::Info, and Foam::inplaceSubset().
Referenced by InjectedParticleInjection< CloudType >::InjectedParticleInjection().
timeEnd()
template<class CloudType > Foam::scalar timeEnd () const virtual
Implements InjectionModel< CloudType >.
Definition at line 255 of file InjectedParticleInjection.C.
References Foam::max().
parcelsToInject()
template<class CloudType > Foam::label parcelsToInject (const scalar time0, const scalar time1) virtual
Implements InjectionModel< CloudType >.
Definition at line 262 of file InjectedParticleInjection.C.
References forAll.
volumeToInject()
template<class CloudType > Foam::scalar volumeToInject (const scalar time0, const scalar time1) virtual
Implements InjectionModel< CloudType >.
Definition at line 282 of file InjectedParticleInjection.C.
References forAll.
setPositionAndCell()
template<class CloudType > void setPositionAndCell (const label parceli, const label nParcels, const scalar time, vector & position, label & cellOwner, label & tetFacei, label & tetPti) virtual
Implements InjectionModel< CloudType >.
Definition at line 302 of file InjectedParticleInjection.C.
setProperties()
template<class CloudType > void setProperties (const label parceli, const label nParcels, const scalar time, typename CloudType::parcelType & parcel) virtual
Implements InjectionModel< CloudType >.
Definition at line 326 of file InjectedParticleInjection.C.
fullyDescribed()
template<class CloudType > bool fullyDescribed () const virtual
Implements InjectionModel< CloudType >.
Definition at line 343 of file InjectedParticleInjection.C.
validInjection()
template<class CloudType > bool validInjection (const label parceli) virtual
Implements InjectionModel< CloudType >.
Definition at line 350 of file InjectedParticleInjection.C.
info()
template<class CloudType > void info () virtual
Reimplemented from InjectionModel< CloudType >.
Definition at line 360 of file InjectedParticleInjection.C.
References InjectionModel< CloudType >::info().
Member Data Documentation
cloudName_
template<class CloudType > const word cloudName_ protected
Definition at line 80 of file InjectedParticleInjection.H.
injectorCells_
template<class CloudType > labelList injectorCells_ protected
Definition at line 83 of file InjectedParticleInjection.H.
Referenced by InjectedParticleInjection< CloudType >::InjectedParticleInjection().
injectorTetFaces_
template<class CloudType > labelList injectorTetFaces_ protected
Definition at line 86 of file InjectedParticleInjection.H.
Referenced by InjectedParticleInjection< CloudType >::InjectedParticleInjection().
injectorTetPts_
template<class CloudType > labelList injectorTetPts_ protected
Definition at line 89 of file InjectedParticleInjection.H.
Referenced by InjectedParticleInjection< CloudType >::InjectedParticleInjection().
time_
template<class CloudType > scalarList time_ protected
Definition at line 92 of file InjectedParticleInjection.H.
Referenced by InjectedParticleInjection< CloudType >::InjectedParticleInjection().
position_
template<class CloudType > vectorList position_ protected
Definition at line 95 of file InjectedParticleInjection.H.
Referenced by InjectedParticleInjection< CloudType >::InjectedParticleInjection().
positionOffset_
template<class CloudType > vector positionOffset_ protected
Definition at line 98 of file InjectedParticleInjection.H.
diameter_
template<class CloudType > scalarList diameter_ protected
Definition at line 101 of file InjectedParticleInjection.H.
U_
template<class CloudType > vectorList U_ protected
Definition at line 104 of file InjectedParticleInjection.H.
volume_
template<class CloudType > scalarList volume_ protected
Definition at line 107 of file InjectedParticleInjection.H.
ignoreOutOfBounds_
template<class CloudType > Switch ignoreOutOfBounds_ protected
Definition at line 110 of file InjectedParticleInjection.H.
currentParticlei_
template<class CloudType > label currentParticlei_ protected
Definition at line 113 of file InjectedParticleInjection.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/InjectedParticleInjection/InjectedParticleInjection.H
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/InjectedParticleInjection/InjectedParticleInjection.C