OpenFOAM: meshWave Class Reference
meshWave Class Reference
Fast topological mesh-wave method for calculating the distance to nearest patch for all cells and boundary.
#include <meshWavePatchDistMethod.H>
Public Member Functions
TypeName ("meshWave")
meshWave (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs)
meshWave (const fvMesh &mesh, const labelHashSet &patchIDs, const bool correctWalls=true)
virtual bool correct (volScalarField &y)
virtual bool correct (volScalarField &y, volVectorField &n)
Public Member Functions inherited from patchDistMethod
TypeName ("patchDistMethod")
declareRunTimeSelectionTable (autoPtr, patchDistMethod, dictionary,(const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs),(dict, mesh, patchIDs))
patchDistMethod (const fvMesh &mesh, const labelHashSet &patchIDs)
virtual ~patchDistMethod ()
const labelHashSet & patchIDs () const
virtual bool movePoints ()
virtual void updateMesh (const mapPolyMesh &)
template<class Type >
Foam::wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Protected Attributes
const bool correctWalls_
label nUnset_
Protected Attributes inherited from patchDistMethod
const fvMesh & mesh_
const labelHashSet patchIDs_
Additional Inherited Members
Static Public Member Functions inherited from patchDistMethod
static autoPtr< patchDistMethod > New (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs, const word &defaultPatchDistMethod=word::null)
template<class Type >
static wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Protected Member Functions inherited from patchDistMethod
patchDistMethod (const patchDistMethod &)=delete
void operator= (const patchDistMethod &)=delete
Detailed Description
Fast topological mesh-wave method for calculating the distance to nearest patch for all cells and boundary.
For regular/un-distorted meshes this method is accurate but for skewed, non-orthogonal meshes it is approximate with the error increasing with the degree of mesh distortion. The distance from the near-wall cells to the boundary may optionally be corrected for mesh distortion by setting correctWalls = true.
Example of the wallDist specification in fvSchemes:
    wallDist
    {
        method meshWave;
        // Optional entry enabling the calculation
        // of the normal-to-wall field
        nRequired false;
    }
See also
Foam::patchDistMethod::Poisson Foam::wallDist
Source files
meshWavePatchDistMethod.H
meshWavePatchDistMethod.C
Definition at line 72 of file meshWavePatchDistMethod.H.
Constructor & Destructor Documentation
meshWave() [1/2]
meshWave (const dictionary & dict, const fvMesh & mesh, const labelHashSet & patchIDs)
Definition at line 44 of file meshWavePatchDistMethod.C.
meshWave() [2/2]
meshWave (const fvMesh & mesh, const labelHashSet & patchIDs, const bool correctWalls = true)
Definition at line 57 of file meshWavePatchDistMethod.C.
Member Function Documentation
TypeName()
TypeName ("meshWave")
correct() [1/2]
bool correct (volScalarField & y) virtual
Implements patchDistMethod.
Reimplemented in directionalMeshWave.
Definition at line 72 of file meshWavePatchDistMethod.C.
References Foam::dimLength, forAll, PtrList< T >::transfer(), and y.
correct() [2/2]
bool correct (volScalarField & y, volVectorField & n) virtual
Implements patchDistMethod.
Reimplemented in directionalMeshWave.
Definition at line 105 of file meshWavePatchDistMethod.C.
References Foam::dimLength, forAll, n, PtrList< T >::set(), PtrList< T >::transfer(), and y.
Member Data Documentation
correctWalls_
const bool correctWalls_ protected
Definition at line 81 of file meshWavePatchDistMethod.H.
nUnset_
label nUnset_ mutable protected
Definition at line 84 of file meshWavePatchDistMethod.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/patchDistMethods/meshWave/meshWavePatchDistMethod.H
src/finiteVolume/fvMesh/wallDist/patchDistMethods/meshWave/meshWavePatchDistMethod.C