OpenFOAM: magSqr< Type > Class Template Reference
magSqr< Type > Class Template Reference
#include <LimitFuncs.H>
Public Member Functions
magSqr ()
tmp< volScalarField > operator() (const GeometricField< Type, fvPatchField, volMesh > &) const
Foam::tmp< Foam::volScalarField > operator() (const volScalarField &phi) const
Foam::tmp< Foam::volScalarField > operator() (const volSymmTensorField &phi) const
Foam::tmp< Foam::volScalarField > operator() (const volTensorField &phi) const
tmp< volScalarField > operator() (const volScalarField &phi) const
tmp< volScalarField > operator() (const volSymmTensorField &phi) const
tmp< volScalarField > operator() (const volTensorField &phi) const
Detailed Description
template<class Type>
class Foam::limitFuncs::magSqr< Type >
Definition at line 83 of file LimitFuncs.H.
Constructor & Destructor Documentation
magSqr()
template<class Type > magSqr () inline
Definition at line 87 of file LimitFuncs.H.
Member Function Documentation
operator()() [1/7]
template<class Type > Foam::tmp< Foam::volScalarField > operator() (const GeometricField< Type, fvPatchField, volMesh > & phi) const inline
Definition at line 27 of file LimitFuncs.C.
References Foam::magSqr(), and phi.
operator()() [2/7]
Foam::tmp< Foam::volScalarField > operator() (const volScalarField & phi) const inline
Definition at line 38 of file LimitFuncs.C.
References phi.
operator()() [3/7]
Foam::tmp< Foam::volScalarField > operator() (const volSymmTensorField & phi) const inline
Definition at line 49 of file LimitFuncs.C.
References phi, and Foam::tr().
operator()() [4/7]
Foam::tmp< Foam::volScalarField > operator() (const volTensorField & phi) const inline
Definition at line 60 of file LimitFuncs.C.
References phi, and Foam::tr().
operator()() [5/7]
tmp< volScalarField > operator() (const volScalarField & phi) const inline
operator()() [6/7]
tmp< volScalarField > operator() (const volSymmTensorField & phi) const inline
operator()() [7/7]
tmp< volScalarField > operator() (const volTensorField & phi) const inline
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/LimitedScheme/LimitFuncs.H
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/LimitedScheme/LimitFuncs.C