OpenFOAM: PopulationBalancePhaseSystem< BasePhaseSystem > Class Template Reference
PopulationBalancePhaseSystem< BasePhaseSystem > Class Template Reference
Class which provides population balance functionality.
#include <PopulationBalancePhaseSystem.H>
Public Member Functions
PopulationBalancePhaseSystem (const fvMesh &)
virtual ~PopulationBalancePhaseSystem ()
virtual tmp< volScalarField > dmdt (const phasePairKey &key) const
virtual PtrList< volScalarField > dmdts () const
virtual autoPtr< phaseSystem::massTransferTable > massTransfer () const
virtual bool read ()
virtual void solve ()
Protected Types
typedef HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > pDmdtTable
Protected Member Functions
virtual tmp< volScalarField > pDmdt (const phasePairKey &key) const
Protected Attributes
PtrList< diameterModels::populationBalanceModel > populationBalances_
pDmdtTable pDmdt_
Detailed Description
template<class BasePhaseSystem>
class Foam::PopulationBalancePhaseSystem< BasePhaseSystem >
Class which provides population balance functionality.
See also
Foam::diameterModels::populationBalanceModel
Source files
PopulationBalancePhaseSystem.H
PopulationBalancePhaseSystem.C
Definition at line 51 of file PopulationBalancePhaseSystem.H.
Member Typedef Documentation
pDmdtTable
template<class BasePhaseSystem > typedef HashPtrTable<volScalarField, phasePairKey, phasePairKey::hash> pDmdtTable protected
Definition at line 60 of file PopulationBalancePhaseSystem.H.
Constructor & Destructor Documentation
PopulationBalancePhaseSystem()
template<class BasePhaseSystem > PopulationBalancePhaseSystem (const fvMesh & mesh)
Definition at line 47 of file PopulationBalancePhaseSystem.C.
References IOobjectOption::AUTO_WRITE, Foam::dimDensity, Foam::dimTime, UPtrList< T >::first(), forAll, forAllConstIter, IOobject::groupName(), phasePair::name(), phasePairKey::ordered(), PopulationBalancePhaseSystem< BasePhaseSystem >::pDmdt_, populationBalanceModel::phasePairs(), PopulationBalancePhaseSystem< BasePhaseSystem >::populationBalances_, IOobjectOption::READ_IF_PRESENT, and HashPtrTable< T, Key, Hash >::set().
~PopulationBalancePhaseSystem()
template<class BasePhaseSystem > ~PopulationBalancePhaseSystem () virtual
Definition at line 127 of file PopulationBalancePhaseSystem.C.
Member Function Documentation
pDmdt()
template<class BasePhaseSystem > Foam::tmp< Foam::volScalarField > pDmdt (const phasePairKey & key) const protected virtual
Definition at line 28 of file PopulationBalancePhaseSystem.C.
References phaseSystem::dmdt(), and PtrList< T >::PtrList().
dmdt()
template<class BasePhaseSystem > Foam::tmp< Foam::volScalarField > dmdt (const phasePairKey & key) const virtual
Definition at line 136 of file PopulationBalancePhaseSystem.C.
dmdts()
template<class BasePhaseSystem > Foam::PtrList< Foam::volScalarField > dmdts () const virtual
Definition at line 147 of file PopulationBalancePhaseSystem.C.
References forAllConstIter, phasePair::phase1(), and phasePair::phase2().
massTransfer()
template<class BasePhaseSystem > Foam::autoPtr< Foam::phaseSystem::massTransferTable > massTransfer () const virtual
Definition at line 166 of file PopulationBalancePhaseSystem.C.
References forAll, forAllConstIter, IOobject::groupName(), phase::name(), phaseModel::name(), Foam::name(), Foam::negPart(), phasePairKey::ordered(), phasePair::phase1(), phasePair::phase2(), Foam::posPart(), psi, and Foam::fvm::Sp().
read()
template<class BasePhaseSystem > bool read () virtual
Definition at line 226 of file PopulationBalancePhaseSystem.C.
solve()
template<class BasePhaseSystem > void solve () virtual
Definition at line 244 of file PopulationBalancePhaseSystem.C.
References forAll.
Member Data Documentation
populationBalances_
template<class BasePhaseSystem > PtrList<diameterModels::populationBalanceModel> populationBalances_ protected
Definition at line 66 of file PopulationBalancePhaseSystem.H.
Referenced by PopulationBalancePhaseSystem< BasePhaseSystem >::PopulationBalancePhaseSystem().
pDmdt_
template<class BasePhaseSystem > pDmdtTable pDmdt_ protected
Definition at line 69 of file PopulationBalancePhaseSystem.H.
Referenced by PopulationBalancePhaseSystem< BasePhaseSystem >::PopulationBalancePhaseSystem().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/PhaseSystems/PopulationBalancePhaseSystem/PopulationBalancePhaseSystem.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/PhaseSystems/PopulationBalancePhaseSystem/PopulationBalancePhaseSystem.C