OpenFOAM: polyline Class Reference
polyline Class Reference
Extrudes by transforming points along a polyline provided as a series of points and edge segments. Supports all blockMesh edge types, e.g. line, arc, spline. The surface points are rotated to follow the path.
#include <polyline.H>
Public Member Functions
TypeName ("polyline")
polyline (const dictionary &dict)
virtual ~polyline ()=default
point operator() (const point &surfacePoint, const vector &surfaceNormal, const label layer) const
void positionAndDirection (const scalar lambda, vector &p, vector &n) const
Public Member Functions inherited from extrudeModel
TypeName ("extrudeModel")
declareRunTimeSelectionTable (autoPtr, extrudeModel, dictionary,(const dictionary &dict),(dict))
extrudeModel (const word &modelType, const dictionary &dict)
virtual ~extrudeModel ()=default
label nLayers () const
scalar expansionRatio () const
scalar sumThickness (const label layer) const
Additional Inherited Members
Static Public Member Functions inherited from extrudeModel
static autoPtr< extrudeModel > New (const dictionary &dict)
Protected Member Functions inherited from extrudeModel
extrudeModel (const extrudeModel &)=delete
void operator= (const extrudeModel &)=delete
Protected Attributes inherited from extrudeModel
label nLayers_
const scalar expansionRatio_
const dictionary & coeffDict_
Detailed Description
Extrudes by transforming points along a polyline provided as a series of points and edge segments. Supports all blockMesh edge types, e.g. line, arc, spline. The surface points are rotated to follow the path.
Property Description Required Default
vertices List of vertices yes
edges List of blockEdge segments yes
toleranceCheck Relative tolerance for polyline checks no SMALL
Definition at line 74 of file polyline.H.
Constructor & Destructor Documentation
polyline()
polyline (const dictionary & dict) explicit
Definition at line 42 of file polyline.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, UPtrList< T >::last(), Foam::mag(), Foam::nl, Foam::normalised(), polyline::positionAndDirection(), UPtrList< T >::size(), and Foam::tab.
~polyline()
virtual ~polyline () virtual default
Member Function Documentation
TypeName()
TypeName ("polyline")
operator()()
point operator() (const point & surfacePoint, const vector & surfaceNormal, const label layer) const virtual
Implements extrudeModel.
Definition at line 124 of file polyline.C.
References Foam::endl(), Foam::mag(), n, Foam::normalised(), p, quaternion::transform(), and WarningInFunction.
positionAndDirection()
void positionAndDirection (const scalar lambda, vector & p, vector & n) const
Definition at line 167 of file polyline.C.
References Foam::interpolateXY(), lambda(), Foam::max(), Foam::min(), n, Foam::normalised(), p, s(), UPtrList< T >::size(), and y.
Referenced by polyline::polyline().
The documentation for this class was generated from the following files:
src/mesh/extrudeModel/polyline/polyline.H
src/mesh/extrudeModel/polyline/polyline.C