OpenFOAM: polyMeshAdder Class Reference
polyMeshAdder Class Reference
Adds two meshes without using any polyMesh morphing.
#include <polyMeshAdder.H>
Static Public Member Functions
static autoPtr< polyMesh > add (const IOobject &io, const polyMesh &mesh0, const polyMesh &mesh1, const faceCoupleInfo &coupleInfo, autoPtr< mapAddedPolyMesh > &mapPtr)
static autoPtr< mapAddedPolyMesh > add (polyMesh &mesh0, const polyMesh &mesh1, const faceCoupleInfo &coupleInfo, const bool validBoundary=true)
static Map< label > findSharedPoints (const polyMesh &, const scalar mergeTol)
static void mergePoints (const polyMesh &, const Map< label > &pointToMaster, polyTopoChange &meshMod)
static label procPatchPairs (const UPtrList< polyMesh > &meshes, List< DynamicList< label > > &localPatch, List< DynamicList< label > > &remoteMesh, List< DynamicList< label > > &remotePatch)
static void patchFacePairs (const UPtrList< polyMesh > &meshes, const List< DynamicList< label > > &localPatch, const List< DynamicList< label > > &remoteMesh, const List< DynamicList< label > > &remotePatch, labelListList &localBoundaryFace, labelListList &remoteFaceMesh, labelListList &remoteBoundaryFace)
static void add (const UPtrList< polyMesh > &meshes, const UList< labelList > &patchMap, const labelListList &localBoundaryFace, const labelListList &remoteFaceMesh, const labelListList &remoteBoundaryFace, const labelListList &remoteFaceStart, const UList< labelList > &pointZoneMap, const UList< labelList > &faceZoneMap, const UList< labelList > &cellZoneMap, polyTopoChange &meshMod, labelListList &cellProcAddressing, labelListList &faceProcAddressing, labelListList &pointProcAddressing)
Detailed Description
Adds two meshes without using any polyMesh morphing.
Gets faces to couple as faceCoupleInfo which is list of faces on both meshes. Returns map from last mesh addition.
Source files
polyMeshAdder.H
polyMeshAdder.C
Definition at line 57 of file polyMeshAdder.H.
Member Function Documentation
add() [1/3]
Foam::autoPtr< Foam::polyMesh > add (const IOobject & io, const polyMesh & mesh0, const polyMesh & mesh1, const faceCoupleInfo & coupleInfo, autoPtr< mapAddedPolyMesh > & mapPtr) static
Definition at line 1445 of file polyMeshAdder.C.
References polyMesh::addPatches(), Foam::identity(), io(), mesh, meshPtr, autoPtr< T >::New(), UPtrList< T >::size(), and Foam::Zero.
Referenced by fvMeshAdder::add(), and fvMeshAdder::add().
add() [2/3]
Foam::autoPtr< Foam::mapAddedPolyMesh > add (polyMesh & mesh0, const polyMesh & mesh1, const faceCoupleInfo & coupleInfo, const bool validBoundary = true) static
Definition at line 1665 of file polyMeshAdder.C.
References PtrList< T >::clear(), forAll, Foam::identity(), PtrList< T >::set(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), and Foam::Zero.
findSharedPoints()
Foam::Map< Foam::label > findSharedPoints (const polyMesh & mesh, const scalar mergeTol) static
Definition at line 1980 of file polyMeshAdder.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIters, polyMesh::globalData(), Foam::invertOneToMany(), Foam::labelMax, Foam::mergePoints(), mesh, Foam::min(), polyMesh::points(), PtrList< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
mergePoints()
void mergePoints (const polyMesh & mesh, const Map< label > & pointToMaster, polyTopoChange & meshMod) static
Definition at line 2187 of file polyMeshAdder.C.
References polyMesh::boundaryMesh(), f(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), polyMesh::faceZones(), forAll, mesh, patchID, polyMesh::points(), polyTopoChange::removePoint(), and polyTopoChange::setAction().
Referenced by meshRefinement::mergePoints().
procPatchPairs()
Foam::label procPatchPairs (const UPtrList< polyMesh > & meshes, List< DynamicList< label > > & localPatch, List< DynamicList< label > > & remoteMesh, List< DynamicList< label > > & remotePatch) static
Definition at line 2317 of file polyMeshAdder.C.
References PtrList< T >::append(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, meshes(), pbm, pp(), PtrList< T >::setSize(), and UPtrList< T >::size().
patchFacePairs()
void patchFacePairs (const UPtrList< polyMesh > & meshes, const List< DynamicList< label > > & localPatch, const List< DynamicList< label > > & remoteMesh, const List< DynamicList< label > > & remotePatch, labelListList & localBoundaryFace, labelListList & remoteFaceMesh, labelListList & remoteBoundaryFace) static
Definition at line 2438 of file polyMeshAdder.C.
References polyMesh::boundaryMesh(), forAll, mesh, meshes(), primitiveMesh::nInternalFaces(), pbm, pp(), PtrList< T >::setSize(), and UPtrList< T >::size().
add() [3/3]
void add (const UPtrList< polyMesh > & meshes, const UList< labelList > & patchMap, const labelListList & localBoundaryFace, const labelListList & remoteFaceMesh, const labelListList & remoteBoundaryFace, const labelListList & remoteFaceStart, const UList< labelList > & pointZoneMap, const UList< labelList > & faceZoneMap, const UList< labelList > & cellZoneMap, polyTopoChange & meshMod, labelListList & cellProcAddressing, labelListList & faceProcAddressing, labelListList & pointProcAddressing) static
Definition at line 2662 of file polyMeshAdder.C.
References polyTopoChange::addCell(), polyTopoChange::addFace(), polyTopoChange::addPoint(), polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), polyMesh::cellZones(), List< T >::clear(), Foam::endl(), f(), faceLabels(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), polyMesh::faceZones(), forAll, Foam::identity(), mesh, meshes(), IOobject::name(), primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), nPoints, primitiveMesh::nPoints(), pbm, pointLabels(), points, polyMesh::points(), polyMesh::pointZones(), pp(), face::reverseFace(), PtrList< T >::set(), List< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), Foam::Swap(), and WarningInFunction.
The documentation for this class was generated from the following files:
src/dynamicMesh/polyMeshAdder/polyMeshAdder.H
src/dynamicMesh/polyMeshAdder/polyMeshAdder.C