OpenFOAM: meshRefinement Class Reference
meshRefinement Class Reference
Helper class which maintains intersections of (changing) mesh with (static) surfaces.
#include <meshRefinement.H>
Public Types
enum debugType {
MESH = (1 << 0) , OBJINTERSECTIONS = (1 << 1) , FEATURESEEDS = (1 << 2) , ATTRACTION = (1 << 3) ,
LAYERINFO = (1 << 4)
}
enum writeType {
WRITEMESH = (1 << 0) , NOWRITEREFINEMENT = (1 << 1) , WRITELEVELS = (1 << 2) , WRITELAYERSETS = (1 << 3) ,
WRITELAYERFIELDS = (1 << 4)
}
enum mapType { MASTERONLY = 1 , KEEPALL = 2 , REMOVE = 4 }
enum FaceMergeType { NONE , GEOMETRIC , IGNOREPATCH }
Public Member Functions
ClassName ("meshRefinement")
meshRefinement (fvMesh &mesh, const scalar mergeDistance, const bool overwrite, const refinementSurfaces &, const refinementFeatures &, const shellSurfaces &, const shellSurfaces &, const labelUList &checkFaces, const bool dryRun)
const fvMesh & mesh () const
fvMesh & mesh ()
scalar mergeDistance () const
bool overwrite () const
const word & oldInstance () const
const refinementSurfaces & surfaces () const
const refinementFeatures & features () const
const shellSurfaces & shells () const
const shellSurfaces & limitShells () const
const hexRef8 & meshCutter () const
const labelList & surfaceIndex () const
labelList & surfaceIndex ()
const Map< label > & faceToCoupledPatch () const
const List< Tuple2< mapType, labelList > > & userFaceData () const
List< Tuple2< mapType, labelList > > & userFaceData ()
label countHits () const
autoPtr< mapDistributePolyMesh > balance (const bool keepZoneFaces, const bool keepBaffles, const scalarField &cellWeights, decompositionMethod &decomposer, fvMeshDistribute &distributor)
labelList intersectedFaces () const
labelList intersectedPoints () const
bool isGap (const scalar, const vector &, const vector &, const vector &, const vector &) const
bool isNormalGap (const scalar planarCos, const label level0, const vector &point0, const vector &normal0, const label level1, const vector &point1, const vector &normal1) const
labelList refineCandidates (const pointField &keepPoints, const scalar curvature, const scalar planarAngle, const bool featureRefinement, const bool featureDistanceRefinement, const bool internalRefinement, const bool surfaceRefinement, const bool curvatureRefinement, const bool smallFeatureRefinement, const bool gapRefinement, const bool bigGapRefinement, const bool spreadGapSize, const label maxGlobalCells, const label maxLocalCells) const
void markOutsideFaces (const labelList &cellLevel, const labelList &neiLevel, const labelList &refineCell, bitSet &isOutsideFace) const
label countFaceDirs (const bitSet &isOutsideFace, const label celli) const
void growSet (const labelList &neiLevel, const bitSet &isOutsideFace, labelList &refineCell, label &nRefine) const
autoPtr< mapPolyMesh > removeGapCells (const scalar planarAngle, const labelList &minSurfaceLevel, const labelList &globalToMasterPatch, const label growIter)
void selectIntersectedFaces (const labelList &surfaces, boolList &isBlockedFace) const
labelList detectLeakCells (const boolList &isBlockedFace, const labelList &leakFaces, const labelList &seedCells) const
autoPtr< mapPolyMesh > removeLeakCells (const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const pointField &locationsInMesh, const pointField &locationsOutsideMesh, const labelList &selectedSurfaces)
autoPtr< mapPolyMesh > blockLeakFaces (const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const pointField &locationsInMesh, const wordList &zonesInMesh, const pointField &locationsOutsideMesh, const labelList &selectedSurfaces)
autoPtr< mapPolyMesh > refine (const labelList &cellsToRefine)
autoPtr< mapDistributePolyMesh > balance (const string &msg, decompositionMethod &decomposer, fvMeshDistribute &distributor, labelList &cellsToRefine, const scalar maxLoadUnbalance, const label maxCellUnbalance)
autoPtr< mapDistributePolyMesh > refineAndBalance (const string &msg, decompositionMethod &decomposer, fvMeshDistribute &distributor, const labelList &cellsToRefine, const scalar maxLoadUnbalance, const label maxCellUnbalance)
autoPtr< mapDistributePolyMesh > balanceAndRefine (const string &msg, decompositionMethod &decomposer, fvMeshDistribute &distributor, const labelList &cellsToRefine, const scalar maxLoadUnbalance, const label maxCellUnbalance)
labelList directionalRefineCandidates (const label maxGlobalCells, const label maxLocalCells, const labelList &currentLevel, const direction dir) const
autoPtr< mapPolyMesh > directionalRefine (const string &msg, const direction cmpt, const labelList &cellsToRefine)
void baffleAndSplitMesh (const bool handleSnapProblems, const snapParameters &snapParams, const bool useTopologicalSnapDetection, const bool removeEdgeConnectedCells, const scalarField &perpendicularAngle, const label nErodeCellZones, const dictionary &motionDict, Time &runTime, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const pointField &locationsInMesh, const wordList &regionsInMesh, const pointField &locationsOutsideMesh, const bool exitIfLeakPath, const refPtr< coordSetWriter > &leakPathFormatter)
void mergeFreeStandingBaffles (const snapParameters &snapParams, const bool useTopologicalSnapDetection, const bool removeEdgeConnectedCells, const scalarField &perpendicularAngle, const scalar planarAngle, const dictionary &motionDict, Time &runTime, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const pointField &locationsInMesh, const pointField &locationsOutsideMesh)
autoPtr< mapPolyMesh > splitMesh (const label nBufferLayers, const label nErodeCellZones, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const pointField &locationsInMesh, const wordList &regionsInMesh, const pointField &locationsOutsideMesh, const bool exitIfLeakPath, const refPtr< coordSetWriter > &leakPathFormatter)
autoPtr< mapPolyMesh > removeLimitShells (const label nBufferLayers, const label nErodeCellZones, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const pointField &locationsInMesh, const wordList &regionsInMesh, const pointField &locationsOutsideMesh)
autoPtr< mapPolyMesh > dupNonManifoldPoints (const localPointRegion &)
autoPtr< mapPolyMesh > dupNonManifoldPoints ()
autoPtr< mapPolyMesh > dupNonManifoldBoundaryPoints ()
autoPtr< mapPolyMesh > mergePoints (const labelList &pointToDuplicate)
autoPtr< mapPolyMesh > createBaffles (const labelList &ownPatch, const labelList &neiPatch)
labelList getZones (const List< surfaceZonesInfo::faceZoneType > &fzTypes) const
void getZoneFaces (const labelList &zoneIDs, labelList &faceZoneID, labelList &ownPatch, labelList &neiPatch, labelList &nBaffles) const
autoPtr< mapPolyMesh > createZoneBaffles (const labelList &zoneIDs, List< labelPair > &baffles, labelList &originatingFaceZone)
autoPtr< mapPolyMesh > mergeBaffles (const List< labelPair > &, const Map< label > &faceToPatch)
autoPtr< mapPolyMesh > mergeZoneBaffles (const bool doInternalZones, const bool doBaffleZones)
autoPtr< mapPolyMesh > zonify (const bool allowFreeStandingZoneFaces, const label nErodeCellZones, const pointField &locationsInMesh, const wordList &regionsInMesh, const pointField &locationsOutsideMesh, const bool exitIfLeakPath, const refPtr< coordSetWriter > &leakPathFormatter, wordPairHashTable &zonesToFaceZone)
label addMeshedPatch (const word &name, const dictionary &)
labelList meshedPatches () const
label addFaceZone (const word &fzName, const word &masterPatch, const word &slavePatch, const surfaceZonesInfo::faceZoneType &fzType)
bool getFaceZoneInfo (const word &fzName, label &masterPatchID, label &slavePatchID, surfaceZonesInfo::faceZoneType &fzType) const
label addPointZone (const word &name)
labelList countEdgeFaces (const uindirectPrimitivePatch &pp) const
void selectSeparatedCoupledFaces (boolList &) const
void updateIntersections (const labelList &changedFaces)
void nearestIntersection (const labelList &surfacesToTest, const labelList &testFaces, labelList &surface1, List< pointIndexHit > &hit1, labelList &region1, labelList &surface2, List< pointIndexHit > &hit2, labelList &region2) const
autoPtr< mapPolyMesh > doRemoveCells (const labelList &cellsToRemove, const labelList &exposedFaces, const labelList &exposedPatchIDs, removeCells &cellRemover)
autoPtr< mapPolyMesh > splitMeshRegions (const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const pointField &locationsInMesh, const pointField &locationsOutsideMesh, const bool exitIfLeakPath, const refPtr< coordSetWriter > &leakPathFormatter)
void doSplitFaces (const labelList &splitFaces, const labelPairList &splits, polyTopoChange &meshMod) const
label splitFacesUndo (const labelList &splitFaces, const labelPairList &splits, const dictionary &motionDict, labelList &duplicateFace, List< labelPair > &baffles)
void distribute (const mapDistributePolyMesh &)
void updateMesh (const mapPolyMesh &, const labelList &changedFaces)
void storeData (const labelList &pointsToStore, const labelList &facesToStore, const labelList &cellsToStore)
void updateMesh (const mapPolyMesh &, const labelList &changedFaces, const Map< label > &pointsToRestore, const Map< label > &facesToRestore, const Map< label > &cellsToRestore)
label mergePatchFaces (const scalar minCos, const scalar concaveCos, const label mergeSize, const labelList &patchIDs, const meshRefinement::FaceMergeType mergeType)
label mergePatchFacesUndo (const scalar minCos, const scalar concaveCos, const labelList &patchIDs, const dictionary &motionDict, const labelList &preserveFaces, const meshRefinement::FaceMergeType mergeType)
autoPtr< mapPolyMesh > doRemovePoints (removePoints &pointRemover, const boolList &pointCanBeDeleted)
autoPtr< mapPolyMesh > doRestorePoints (removePoints &pointRemover, const labelList &facesToRestore)
labelList collectFaces (const labelList &candidateFaces, const labelHashSet &set) const
labelList growFaceCellFace (const labelUList &set) const
labelList growFaceCellFace (const labelHashSet &set) const
label mergeEdgesUndo (const scalar minCos, const dictionary &motionDict)
void checkData ()
template<class T >
void testSyncBoundaryFaceList (const scalar mergeDistance, const string &, const UList< T > &, const UList< T > &) const
void printMeshInfo (const bool, const string &) const
word timeName () const
void setInstance (const fileName &)
bool write () const
void dumpRefinementLevel () const
void dumpIntersections (const fileName &prefix) const
void write (const debugType debugFlags, const writeType writeFlags, const fileName &) const
Static Public Member Functions
static autoPtr< indirectPrimitivePatch > makePatch (const polyMesh &, const labelList &)
static tmp< pointVectorField > makeDisplacementField (const pointMesh &pMesh, const labelList &adaptPatchIDs)
static void checkCoupledFaceZones (const polyMesh &)
static void calculateEdgeWeights (const polyMesh &mesh, const bitSet &isMasterEdge, const labelList &meshPoints, const edgeList &edges, scalarField &edgeWeights, scalarField &invSumWeight)
template<class Type >
static void weightedSum (const polyMesh &mesh, const bitSet &isMasterEdge, const labelList &meshPoints, const edgeList &edges, const scalarField &edgeWeights, const Field< Type > &data, Field< Type > &sum)
static List< labelPair > subsetBaffles (const polyMesh &mesh, const labelList &zoneIDs, const List< labelPair > &baffles)
static label appendPatch (fvMesh &, const label insertPatchi, const word &, const dictionary &)
static label addPatch (fvMesh &, const word &name, const dictionary &)
static label findCell (const polyMesh &, const vector &perturbVec, const point &p)
static label findRegion (const polyMesh &, const labelList &cellRegion, const vector &perturbVec, const point &p)
static label findRegions (const polyMesh &, const vector &perturbVec, const pointField &locationsInMesh, const pointField &locationsOutsideMesh, const label nRegions, labelList &cellRegion, const boolList &blockedFace, const bool exitIfLeakPath, const refPtr< coordSetWriter > &leakPathFormatter)
template<class T >
static void updateList (const labelList &newToOld, const T &nullValue, List< T > &elems)
static void testSyncPointList (const string &msg, const polyMesh &mesh, const List< scalar > &fld)
static void testSyncPointList (const string &msg, const polyMesh &mesh, const List< point > &fld)
template<class T >
static void collectAndPrint (const UList< point > &points, const UList< T > &data)
static bitSet getMasterPoints (const polyMesh &mesh, const labelList &meshPoints)
static bitSet getMasterEdges (const polyMesh &mesh, const labelList &meshEdges)
static void removeFiles (const polyMesh &)
template<class T >
static T gAverage (const bitSet &isMasterElem, const UList< T > &values)
static writeType writeLevel ()
static void writeLevel (const writeType)
template<class EnumContainer >
static int readFlags (const EnumContainer &namedEnum, const wordList &words)
template<class Type >
static Type get (const dictionary &dict, const word &keyword, const bool noExit, enum keyType::option matchOpt=keyType::REGEX, const Type &deflt=Zero)
static const dictionary & subDict (const dictionary &dict, const word &keyword, const bool noExit, enum keyType::option matchOpt=keyType::REGEX)
static ITstream & lookup (const dictionary &dict, const word &keyword, const bool noExit, enum keyType::option matchOpt=keyType::REGEX)
Static Public Attributes
static const Enum< debugType > debugTypeNames
static const Enum< writeType > writeTypeNames
Detailed Description
Helper class which maintains intersections of (changing) mesh with (static) surfaces.
Maintains
per face any intersections of the cc-cc segment with any of the surfaces
Source files
meshRefinement.H
meshRefinement.C
meshRefinementBaffles.C
meshRefinementGapRefine.C
meshRefinementMerge.C
meshRefinementProblemCells.C
meshRefinementRefine.C
Definition at line 82 of file meshRefinement.H.
Member Enumeration Documentation
debugType
enum debugType
Enumerator
MESH
OBJINTERSECTIONS
FEATURESEEDS
ATTRACTION
LAYERINFO
Definition at line 89 of file meshRefinement.H.
writeType
enum writeType
Enumerator
WRITEMESH
NOWRITEREFINEMENT
WRITELEVELS
WRITELAYERSETS
WRITELAYERFIELDS
Definition at line 109 of file meshRefinement.H.
mapType
enum mapType
Enumerator
MASTERONLY
maintain master only
KEEPALL
have slaves (upon refinement) from master
REMOVE
set value to -1 any face that was refined
Definition at line 121 of file meshRefinement.H.
FaceMergeType
enum FaceMergeType
Enumerator
NONE
GEOMETRIC
IGNOREPATCH
Definition at line 130 of file meshRefinement.H.
Constructor & Destructor Documentation
meshRefinement()
meshRefinement (fvMesh & mesh, const scalar mergeDistance, const bool overwrite, const refinementSurfaces & surfaces, const refinementFeatures & features, const shellSurfaces & shells, const shellSurfaces & limitShells, const labelUList & checkFaces, const bool dryRun)
Definition at line 1677 of file meshRefinement.C.
References meshRefinement::updateIntersections().
Member Function Documentation
ClassName()
ClassName ("meshRefinement")
mesh() [1/2]
const fvMesh & mesh () const inline
Definition at line 988 of file meshRefinement.H.
Referenced by snappyLayerDriver::addLayersSinglePass().
mesh() [2/2]
fvMesh & mesh () inline
Definition at line 992 of file meshRefinement.H.
mergeDistance()
scalar mergeDistance () const inline
Definition at line 997 of file meshRefinement.H.
overwrite()
bool overwrite () const inline
Definition at line 1003 of file meshRefinement.H.
oldInstance()
const word & oldInstance () const inline
Definition at line 1009 of file meshRefinement.H.
surfaces()
const refinementSurfaces & surfaces () const inline
Definition at line 1015 of file meshRefinement.H.
Referenced by snappyVoxelMeshDriver::snappyVoxelMeshDriver().
features()
const refinementFeatures & features () const inline
Definition at line 1021 of file meshRefinement.H.
Referenced by snappyVoxelMeshDriver::snappyVoxelMeshDriver().
shells()
const shellSurfaces & shells () const inline
Definition at line 1027 of file meshRefinement.H.
Referenced by snappyVoxelMeshDriver::snappyVoxelMeshDriver().
limitShells()
const shellSurfaces & limitShells () const inline
Definition at line 1033 of file meshRefinement.H.
meshCutter()
const hexRef8 & meshCutter () const inline
Definition at line 1039 of file meshRefinement.H.
Referenced by snappyLayerDriver::addLayersSinglePass(), and snappyVoxelMeshDriver::snappyVoxelMeshDriver().
surfaceIndex() [1/2]
const Foam::labelList & surfaceIndex () const
Definition at line 1727 of file meshRefinement.C.
References Foam::identity(), and meshRefinement::updateIntersections().
surfaceIndex() [2/2]
Foam::labelList & surfaceIndex ()
Definition at line 1740 of file meshRefinement.C.
References Foam::identity().
faceToCoupledPatch()
const Map< label > & faceToCoupledPatch () const inline
Definition at line 1051 of file meshRefinement.H.
userFaceData() [1/2]
const List< Tuple2< mapType, labelList > > & userFaceData () const inline
Definition at line 1060 of file meshRefinement.H.
userFaceData() [2/2]
List< Tuple2< mapType, labelList > > & userFaceData () inline
Definition at line 1065 of file meshRefinement.H.
countHits()
Foam::label countHits () const
Definition at line 1750 of file meshRefinement.C.
References forAll, syncTools::getMasterFaces(), and UPtrList< T >::test().
balance() [1/2]
Foam::autoPtr< Foam::mapDistributePolyMesh > balance (const bool keepZoneFaces, const bool keepBaffles, const scalarField & cellWeights, decompositionMethod & decomposer, fvMeshDistribute & distributor)
Definition at line 1770 of file meshRefinement.C.
References coupled(), decompositionMethod::decompose(), Foam::endl(), localPointRegion::findDuplicateFacePairs(), UPtrList< T >::first(), forAll, Foam::Info, Pstream::listCombineReduce(), UPstream::parRun(), pbm, Foam::Pout, Foam::reduce(), Foam::returnReduce(), decompositionMethod::setConstraints(), PtrList< T >::setSize(), UPtrList< T >::size(), syncTools::syncFaceList(), timeName, and WarningInFunction.
Referenced by snappyLayerDriver::addLayersSinglePass().
intersectedFaces()
Foam::labelList intersectedFaces () const
Definition at line 2020 of file meshRefinement.C.
References forAll.
intersectedPoints()
Foam::labelList intersectedPoints () const
Definition at line 2048 of file meshRefinement.C.
References f(), forAll, PtrList< T >::set(), and UPtrList< T >::test().
makePatch()
Foam::autoPtr< Foam::indirectPrimitivePatch > makePatch (const polyMesh & mesh, const labelList & patchIDs) static
Definition at line 2120 of file meshRefinement.C.
References polyMesh::boundaryMesh(), polyMesh::faces(), forAll, mesh, autoPtr< T >::New(), patches, patchIDs(), polyMesh::points(), and pp().
Referenced by snappyLayerDriver::addLayers(), snappyLayerDriver::addLayersSinglePass(), snappySnapDriver::doSnap(), and snappySnapDriver::repatchToSurface().
makeDisplacementField()
Foam::tmp< Foam::pointVectorField > makeDisplacementField (const pointMesh & pMesh, const labelList & adaptPatchIDs) static
Definition at line 2162 of file meshRefinement.C.
References IOobjectOption::AUTO_WRITE, pointMesh::boundary(), Foam::dimLength, forAll, mesh, tmp< T >::New(), IOobjectOption::NO_READ, UPtrList< T >::size(), fvMesh::time(), and Foam::Zero.
Referenced by snappySnapDriver::doSnap().
checkCoupledFaceZones()
void checkCoupledFaceZones (const polyMesh & mesh) static
Definition at line 2216 of file meshRefinement.C.
References Foam::abort(), Pstream::allGatherList(), Foam::exit(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, UPstream::myProcNo(), primitiveMesh::nBoundaryFaces(), primitiveMesh::nInternalFaces(), Foam::nl, UPstream::nProcs(), and syncTools::swapBoundaryFaceList().
calculateEdgeWeights()
void calculateEdgeWeights (const polyMesh & mesh, const bitSet & isMasterEdge, const labelList & meshPoints, const edgeList & edges, scalarField & edgeWeights, scalarField & invSumWeight) static
Definition at line 2304 of file meshRefinement.C.
References e, forAll, Foam::mag(), Foam::max(), mesh, polyMesh::points(), pts, PtrList< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
Referenced by fieldSmoother::minSmoothField(), fieldSmoother::smoothLambdaMuDisplacement(), fieldSmoother::smoothNormals(), and fieldSmoother::smoothPatchNormals().
weightedSum()
template<class Type > void weightedSum (const polyMesh & mesh, const bitSet & isMasterEdge, const labelList & meshPoints, const edgeList & edges, const scalarField & edgeWeights, const Field< Type > & data, Field< Type > & sum) static
Definition at line 263 of file meshRefinementTemplates.C.
References Foam::abort(), e, Foam::FatalError, FatalErrorInFunction, forAll, mesh, PtrList< T >::setSize(), UPtrList< T >::size(), UList< T >::size(), Foam::sum(), syncTools::syncPointList(), UPtrList< T >::test(), and Foam::Zero.
Referenced by fieldSmoother::minSmoothField(), fieldSmoother::smoothLambdaMuDisplacement(), fieldSmoother::smoothNormals(), and fieldSmoother::smoothPatchNormals().
isGap()
bool isGap (const scalar planarCos, const vector & point0, const vector & normal0, const vector & point1, const vector & normal1) const
Definition at line 1731 of file meshRefinementRefine.C.
References Foam::mag(), Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
isNormalGap()
bool isNormalGap (const scalar planarCos, const label level0, const vector & point0, const vector & normal0, const label level1, const vector & point1, const vector & normal1) const
Definition at line 1778 of file meshRefinementRefine.C.
References Foam::cos(), Foam::degToRad(), Foam::mag(), Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
refineCandidates()
Foam::labelList refineCandidates (const pointField & keepPoints, const scalar curvature, const scalar planarAngle, const bool featureRefinement, const bool featureDistanceRefinement, const bool internalRefinement, const bool surfaceRefinement, const bool curvatureRefinement, const bool smallFeatureRefinement, const bool gapRefinement, const bool bigGapRefinement, const bool spreadGapSize, const label maxGlobalCells, const label maxLocalCells) const
Definition at line 2221 of file meshRefinementRefine.C.
References Foam::cos(), Foam::degToRad(), Foam::endl(), forAll, Foam::Info, Foam::labelMax, Foam::max(), UPstream::nProcs(), PtrList< T >::setSize(), and UPtrList< T >::size().
markOutsideFaces()
void markOutsideFaces (const labelList & cellLevel, const labelList & neiLevel, const labelList & refineCell, bitSet & isOutsideFace) const
Definition at line 170 of file meshRefinementBlock.C.
References polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, primitiveMesh::nBoundaryFaces(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), PtrList< T >::set(), PtrList< T >::setSize(), syncTools::swapBoundaryCellList(), and Foam::Zero.
countFaceDirs()
Foam::label countFaceDirs (const bitSet & isOutsideFace, const label celli) const
Definition at line 228 of file meshRefinementBlock.C.
References forAll, Foam::magSqr(), n, Foam::sqr(), and VectorSpace< Form, Cmpt, Ncmpts >::uniform().
growSet()
void growSet (const labelList & neiLevel, const bitSet & isOutsideFace, labelList & refineCell, label & nRefine) const
Definition at line 279 of file meshRefinementBlock.C.
References cells, and forAll.
removeGapCells()
Foam::autoPtr< Foam::mapPolyMesh > removeGapCells (const scalar planarAngle, const labelList & minSurfaceLevel, const labelList & globalToMasterPatch, const label growIter)
Definition at line 944 of file meshRefinementBlock.C.
References Foam::cos(), Foam::degToRad(), Foam::endl(), forAll, surfaceZonesInfo::getUnnamedSurfaces(), Foam::Info, Foam::labelMax, Foam::min(), UPstream::nProcs(), Foam::returnReduce(), s(), and UPtrList< T >::size().
selectIntersectedFaces()
void selectIntersectedFaces (const labelList & surfaces, boolList & isBlockedFace) const
Definition at line 1133 of file meshRefinementBlock.C.
References forAll, and PtrList< T >::setSize().
detectLeakCells()
labelList detectLeakCells (const boolList & isBlockedFace, const labelList & leakFaces, const labelList & seedCells) const
removeLeakCells()
autoPtr< mapPolyMesh > removeLeakCells (const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const pointField & locationsInMesh, const pointField & locationsOutsideMesh, const labelList & selectedSurfaces)
blockLeakFaces()
Foam::autoPtr< Foam::mapPolyMesh > blockLeakFaces (const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const pointField & locationsInMesh, const wordList & zonesInMesh, const pointField & locationsOutsideMesh, const labelList & selectedSurfaces)
Definition at line 1825 of file meshRefinementBlock.C.
References surfaceZonesInfo::addFaceZone(), PtrList< T >::append(), holeToFace::calcClosure(), ZoneMesh< ZoneType, MeshType >::clearAddressing(), e, PrimitivePatch< FaceList, PointField >::edges(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::findIndices(), forAll, meshRefinement::MESH, PrimitivePatch< FaceList, PointField >::meshPoints(), Foam::name(), Foam::nl, VectorSpace< Form, Cmpt, Ncmpts >::one, patches, Foam::Pout, pp(), Foam::reduce(), Foam::returnReduceOr(), PtrList< T >::set(), UPtrList< T >::size(), UList< T >::size(), syncTools::syncPointList(), timeName, WarningInFunction, write(), meshRefinement::writeLevel(), meshRefinement::WRITEMESH, and refinementParameters::zonePoints().
refine()
Foam::autoPtr< Foam::mapPolyMesh > refine (const labelList & cellsToRefine)
Definition at line 2551 of file meshRefinementRefine.C.
References polyTopoChange::changeMesh(), mapPolyMesh::hasMotionPoints(), mapPolyMesh::preMotionPoints(), and timeName.
balance() [2/2]
Foam::autoPtr< Foam::mapDistributePolyMesh > balance (const string & msg, decompositionMethod & decomposer, fvMeshDistribute & distributor, labelList & cellsToRefine, const scalar maxLoadUnbalance, const label maxCellUnbalance)
Definition at line 2595 of file meshRefinementRefine.C.
References Foam::checkData(), Foam::endl(), forAll, Foam::Info, Foam::mag(), meshRefinement::MESH, Foam::nl, UPstream::nProcs(), Foam::Pout, Foam::returnReduce(), UPtrList< T >::size(), timeName, and write().
refineAndBalance()
Foam::autoPtr< Foam::mapDistributePolyMesh > refineAndBalance (const string & msg, decompositionMethod & decomposer, fvMeshDistribute & distributor, const labelList & cellsToRefine, const scalar maxLoadUnbalance, const label maxCellUnbalance)
Definition at line 2711 of file meshRefinementRefine.C.
References Foam::checkData(), Foam::endl(), Foam::Info, meshRefinement::MESH, Foam::Pout, timeName, and write().
balanceAndRefine()
Foam::autoPtr< Foam::mapDistributePolyMesh > balanceAndRefine (const string & msg, decompositionMethod & decomposer, fvMeshDistribute & distributor, const labelList & cellsToRefine, const scalar maxLoadUnbalance, const label maxCellUnbalance)
Definition at line 2769 of file meshRefinementRefine.C.
References Foam::checkData(), Foam::endl(), Foam::Info, meshRefinement::MESH, Foam::Pout, timeName, and write().
directionalRefineCandidates()
Foam::labelList directionalRefineCandidates (const label maxGlobalCells, const label maxLocalCells, const labelList & currentLevel, const direction dir) const
Definition at line 2864 of file meshRefinementRefine.C.
References Foam::endl(), forAll, Foam::Info, Foam::labelMax, UPstream::nProcs(), Foam::Pout, and PtrList< T >::setSize().
directionalRefine()
Foam::autoPtr< Foam::mapPolyMesh > directionalRefine (const string & msg, const direction cmpt, const labelList & cellsToRefine)
Definition at line 2964 of file meshRefinementRefine.C.
References polyTopoChange::changeMesh(), forAll, UPtrList< T >::size(), timeName, and Foam::Zero.
baffleAndSplitMesh()
void baffleAndSplitMesh (const bool handleSnapProblems, const snapParameters & snapParams, const bool useTopologicalSnapDetection, const bool removeEdgeConnectedCells, const scalarField & perpendicularAngle, const label nErodeCellZones, const dictionary & motionDict, Time & runTime, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const pointField & locationsInMesh, const wordList & regionsInMesh, const pointField & locationsOutsideMesh, const bool exitIfLeakPath, const refPtr< coordSetWriter > & leakPathFormatter)
Definition at line 4520 of file meshRefinementBaffles.C.
References Foam::checkData(), cpuTimePosix::cpuTimeIncrement(), Foam::endl(), Foam::Info, Foam::nl, Time::path(), Foam::Pout, Foam::returnReduce(), runTime, PtrList< T >::setSize(), timeName, and write().
mergeFreeStandingBaffles()
void mergeFreeStandingBaffles (const snapParameters & snapParams, const bool useTopologicalSnapDetection, const bool removeEdgeConnectedCells, const scalarField & perpendicularAngle, const scalar planarAngle, const dictionary & motionDict, Time & runTime, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const pointField & locationsInMesh, const pointField & locationsOutsideMesh)
Definition at line 4710 of file meshRefinementBaffles.C.
References Foam::checkData(), cpuTimePosix::cpuTimeIncrement(), Foam::endl(), localPointRegion::findDuplicateFacePairs(), Foam::Info, Foam::nl, Foam::returnReduce(), runTime, and UPtrList< T >::size().
splitMesh()
Foam::autoPtr< Foam::mapPolyMesh > splitMesh (const label nBufferLayers, const label nErodeCellZones, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const pointField & locationsInMesh, const wordList & regionsInMesh, const pointField & locationsOutsideMesh, const bool exitIfLeakPath, const refPtr< coordSetWriter > & leakPathFormatter)
Definition at line 4804 of file meshRefinementBaffles.C.
References forAll, syncTools::syncFaceList(), and VectorSpace< Form, Cmpt, Ncmpts >::uniform().
removeLimitShells()
Foam::autoPtr< Foam::mapPolyMesh > removeLimitShells (const label nBufferLayers, const label nErodeCellZones, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const pointField & locationsInMesh, const wordList & regionsInMesh, const pointField & locationsOutsideMesh)
Definition at line 5359 of file meshRefinementBaffles.C.
References Foam::endl(), forAll, meshRefinement::MESH, Foam::Pout, timeName, write(), and Foam::Zero.
dupNonManifoldPoints() [1/2]
Foam::autoPtr< Foam::mapPolyMesh > dupNonManifoldPoints (const localPointRegion & regionSide)
Definition at line 5447 of file meshRefinementBaffles.C.
References polyTopoChange::changeMesh(), Foam::endl(), mapPolyMesh::hasMotionPoints(), Foam::Info, mapPolyMesh::preMotionPoints(), Foam::returnReduce(), and timeName.
dupNonManifoldPoints() [2/2]
Foam::autoPtr< Foam::mapPolyMesh > dupNonManifoldPoints ()
Definition at line 5511 of file meshRefinementBaffles.C.
dupNonManifoldBoundaryPoints()
Foam::autoPtr< Foam::mapPolyMesh > dupNonManifoldBoundaryPoints ()
Definition at line 5594 of file meshRefinementBaffles.C.
References surfaceZonesInfo::BAFFLE, surfaceZonesInfo::BOUNDARY, Foam::endl(), f(), surfaceZonesInfo::faceZoneTypeNames, forAll, Foam::Info, surfaceZonesInfo::INTERNAL, Foam::max(), n, Foam::returnReduce(), and syncTools::syncPointList().
Referenced by snappyLayerDriver::addLayersSinglePass().
mergePoints()
Foam::autoPtr< Foam::mapPolyMesh > mergePoints (const labelList & pointToDuplicate)
Definition at line 5520 of file meshRefinementBaffles.C.
References polyTopoChange::changeMesh(), forAll, mapPolyMesh::hasMotionPoints(), polyMeshAdder::mergePoints(), mapPolyMesh::preMotionPoints(), Foam::returnReduceOr(), and timeName.
createBaffles()
Foam::autoPtr< Foam::mapPolyMesh > createBaffles (const labelList & ownPatch, const labelList & neiPatch)
Definition at line 482 of file meshRefinementBaffles.C.
References Foam::abort(), polyTopoChange::changeMesh(), Foam::endl(), mapPolyMesh::faceMap(), Foam::faceMap(), Foam::FatalError, FatalErrorInFunction, forAll, mapPolyMesh::hasMotionPoints(), pbm, pp(), mapPolyMesh::preMotionPoints(), Foam::returnReduceOr(), mapPolyMesh::reverseFaceMap(), UPtrList< T >::size(), syncTools::syncFaceList(), and timeName.
getZones()
Foam::labelList getZones (const List< surfaceZonesInfo::faceZoneType > & fzTypes) const
Definition at line 661 of file meshRefinementBaffles.C.
References PtrList< T >::append(), forAll, UPtrList< T >::size(), and zoneIDs.
Referenced by snappyLayerDriver::addLayersSinglePass().
subsetBaffles()
Foam::List< Foam::labelPair > subsetBaffles (const polyMesh & mesh, const labelList & zoneIDs, const List< labelPair > & baffles) static
Definition at line 688 of file meshRefinementBaffles.C.
References PtrList< T >::append(), polyMesh::faceZones(), forAll, mesh, primitiveMesh::nFaces(), p, UPtrList< T >::size(), and zoneIDs.
Referenced by snappyLayerDriver::addLayers().
getZoneFaces()
void getZoneFaces (const labelList & zoneIDs, labelList & faceZoneID, labelList & ownPatch, labelList & neiPatch, labelList & nBaffles) const
Definition at line 721 of file meshRefinementBaffles.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, syncTools::getInternalOrCoupledFaces(), PtrList< T >::setSize(), UPtrList< T >::size(), Foam::Zero, and zoneIDs.
createZoneBaffles()
Foam::autoPtr< Foam::mapPolyMesh > createZoneBaffles (const labelList & zoneIDs, List< labelPair > & baffles, labelList & originatingFaceZone)
Definition at line 789 of file meshRefinementBaffles.C.
References Foam::abort(), PtrList< T >::clear(), Foam::endl(), Foam::faceMap(), surfaceZonesInfo::faceZoneTypeNames, Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, Pstream::listCombineReduce(), Foam::nl, Foam::Pout, Foam::returnReduce(), Foam::setf(), PtrList< T >::setSize(), Foam::setw(), UPtrList< T >::size(), Foam::sum(), timeName, write(), and zoneIDs.
Referenced by snappyLayerDriver::addLayersSinglePass().
mergeBaffles()
Foam::autoPtr< Foam::mapPolyMesh > mergeBaffles (const List< labelPair > & couples, const Map< label > & faceToPatch)
Definition at line 1181 of file meshRefinementBaffles.C.
References polyTopoChange::changeMesh(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), forAll, forAllConstIters, mapPolyMesh::hasMotionPoints(), mapPolyMesh::preMotionPoints(), Foam::returnReduceOr(), mapPolyMesh::reverseFaceMap(), polyTopoChange::setAction(), PtrList< T >::setSize(), UPtrList< T >::size(), timeName, and ZoneMesh< ZoneType, MeshType >::whichZone().
mergeZoneBaffles()
Foam::autoPtr< Foam::mapPolyMesh > mergeZoneBaffles (const bool doInternalZones, const bool doBaffleZones)
Definition at line 1365 of file meshRefinementBaffles.C.
References PtrList< T >::append(), surfaceZonesInfo::BAFFLE, localPointRegion::findDuplicateFacePairs(), surfaceZonesInfo::INTERNAL, Foam::returnReduceOr(), UPtrList< T >::size(), and zoneIDs.
zonify()
Foam::autoPtr< Foam::mapPolyMesh > zonify (const bool allowFreeStandingZoneFaces, const label nErodeCellZones, const pointField & locationsInMesh, const wordList & regionsInMesh, const pointField & locationsOutsideMesh, const bool exitIfLeakPath, const refPtr< coordSetWriter > & leakPathFormatter, wordPairHashTable & zonesToFaceZone)
Definition at line 5692 of file meshRefinementBaffles.C.
References Foam::abort(), surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZone(), surfaceZonesInfo::addFaceZonesToMesh(), polyTopoChange::changeMesh(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, ZoneMesh< ZoneType, MeshType >::findZoneID(), UPtrList< T >::first(), forAll, syncTools::getMasterFaces(), surfaceZonesInfo::getNamedSurfaces(), Foam::indent(), Foam::Info, Pstream::mapCombineReduce(), n, OFstream::name(), zoneIdentifier::name(), Foam::nl, patches, Foam::Pout, pp(), Foam::returnReduce(), UPtrList< T >::size(), UList< T >::size(), syncTools::swapBoundaryCellList(), UPtrList< T >::test(), timeName, and OBJstream::write().
appendPatch()
Foam::label appendPatch (fvMesh & mesh, const label insertPatchi, const word & patchName, const dictionary & patchDict) static
Definition at line 2360 of file meshRefinement.C.
References fvMesh::boundary(), polyMesh::boundaryMesh(), fvPatchFieldBase::calculatedType(), fvsPatchFieldBase::calculatedType(), fvMesh::clearOut(), mesh, fvPatch::New(), polyPatch::New(), PtrList< T >::set(), PtrList< T >::setSize(), and UPtrList< T >::size().
addPatch()
Foam::label addPatch (fvMesh & mesh, const word & name, const dictionary & patchInfo) static
Definition at line 2458 of file meshRefinement.C.
References fvMesh::boundary(), polyMesh::boundaryMesh(), forAll, mesh, primitiveMesh::nFaces(), pp(), UPtrList< T >::reorder(), PtrList< T >::set(), and UPtrList< T >::size().
addMeshedPatch()
Foam::label addMeshedPatch (const word & name, const dictionary & patchInfo)
Definition at line 2536 of file meshRefinement.C.
References Foam::name().
meshedPatches()
Foam::labelList meshedPatches () const
Definition at line 2587 of file meshRefinement.C.
References PtrList< T >::append(), polyPatch::constraintType(), Foam::endl(), forAll, patches, patchIDs(), Foam::type(), and WarningInFunction.
addFaceZone()
Foam::label addFaceZone (const word & fzName, const word & masterPatch, const word & slavePatch, const surfaceZonesInfo::faceZoneType & fzType)
Definition at line 2613 of file meshRefinement.C.
References surfaceZonesInfo::addFaceZone().
getFaceZoneInfo()
bool getFaceZoneInfo (const word & fzName, label & masterPatchID, label & slavePatchID, surfaceZonesInfo::faceZoneType & fzType) const
Definition at line 2637 of file meshRefinement.C.
References pbm.
Referenced by snappyLayerDriver::addLayersSinglePass().
addPointZone()
Foam::label addPointZone (const word & name)
Definition at line 2666 of file meshRefinement.C.
References ZoneMesh< ZoneType, MeshType >::clearAddressing(), ZoneMesh< ZoneType, MeshType >::findZoneID(), Foam::name(), PtrList< T >::set(), PtrList< T >::setSize(), and UPtrList< T >::size().
countEdgeFaces()
Foam::labelList countEdgeFaces (const uindirectPrimitivePatch & pp) const
Definition at line 2708 of file meshRefinement.C.
References mapDistributeBase::constructSize(), globalMeshData::coupledPatch(), PrimitivePatch< FaceList, PointField >::edgeFaces(), forAll, globalMeshData::globalEdgeSlaves(), globalMeshData::globalEdgeSlavesMap(), globalMeshData::globalEdgeTransformedSlaves(), PatchTools::matchEdges(), UPstream::parRun(), pp(), UList< T >::size(), globalMeshData::syncData(), and Foam::Zero.
selectSeparatedCoupledFaces()
void selectSeparatedCoupledFaces (boolList & selected) const
Definition at line 2693 of file meshRefinement.C.
References pp().
updateIntersections()
void updateIntersections (const labelList & changedFaces)
Definition at line 343 of file meshRefinement.C.
References UPtrList< T >::count(), Foam::endl(), forAll, syncTools::getMasterFaces(), Foam::Info, Foam::nl, Foam::reduce(), Foam::returnReduce(), UPtrList< T >::size(), UList< T >::size(), syncTools::syncFaceList(), and UPtrList< T >::test().
Referenced by meshRefinement::meshRefinement(), and meshRefinement::surfaceIndex().
nearestIntersection()
void nearestIntersection (const labelList & surfacesToTest, const labelList & testFaces, labelList & surface1, List< pointIndexHit > & hit1, labelList & region1, labelList & surface2, List< pointIndexHit > & hit2, labelList & region2) const
Definition at line 650 of file meshRefinement.C.
References UPtrList< T >::size().
doRemoveCells()
Foam::autoPtr< Foam::mapPolyMesh > doRemoveCells (const labelList & cellsToRemove, const labelList & exposedFaces, const labelList & exposedPatchIDs, removeCells & cellRemover)
Definition at line 1110 of file meshRefinement.C.
References polyTopoChange::changeMesh(), mapPolyMesh::hasMotionPoints(), mapPolyMesh::preMotionPoints(), Foam::renumber(), mapPolyMesh::reverseFaceMap(), and timeName.
findCell()
Foam::label findCell (const polyMesh & mesh, const vector & perturbVec, const point & p) static
Definition at line 2765 of file meshRefinement.C.
References polyMesh::findCell(), findCellMode(), mesh, p, Foam::returnReduceAnd(), and polyMesh::tetBasePtIs().
findRegion()
Foam::label findRegion (const polyMesh & mesh, const labelList & cellRegion, const vector & perturbVec, const point & p) static
Definition at line 2786 of file meshRefinement.C.
References polyMesh::findCell(), findCellMode(), mesh, p, Foam::reduce(), and polyMesh::tetBasePtIs().
findRegions()
Foam::label findRegions (const polyMesh & mesh, const vector & perturbVec, const pointField & locationsInMesh, const pointField & locationsOutsideMesh, const label nRegions, labelList & cellRegion, const boolList & blockedFace, const bool exitIfLeakPath, const refPtr< coordSetWriter > & leakPathFormatter) static
Definition at line 2973 of file meshRefinement.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, mesh, primitiveMesh::nCells(), PtrList< T >::set(), UList< T >::size(), UPtrList< T >::test(), and WarningInFunction.
splitMeshRegions()
Foam::autoPtr< Foam::mapPolyMesh > splitMeshRegions (const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const pointField & locationsInMesh, const pointField & locationsOutsideMesh, const bool exitIfLeakPath, const refPtr< coordSetWriter > & leakPathFormatter)
Definition at line 3090 of file meshRefinement.C.
References PtrList< T >::append(), Foam::endl(), forAll, Foam::Info, Foam::returnReduce(), PtrList< T >::setSize(), UPtrList< T >::size(), VectorSpace< Form, Cmpt, Ncmpts >::uniform(), and WarningInFunction.
doSplitFaces()
void doSplitFaces (const labelList & splitFaces, const labelPairList & splits, polyTopoChange & meshMod) const
Definition at line 1174 of file meshRefinement.C.
References polyTopoChange::addFace(), Foam::endl(), f(), UList< T >::fcIndex(), forAll, polyTopoChange::modifyFace(), Foam::Pout, UList< T >::size(), and split().
splitFacesUndo()
Foam::label splitFacesUndo (const labelList & splitFaces, const labelPairList & splits, const dictionary & motionDict, labelList & duplicateFace, List< labelPair > & baffles)
Definition at line 1293 of file meshRefinement.C.
References PtrList< T >::append(), polyTopoChange::changeMesh(), motionSmootherAlgo::checkMesh(), PtrList< T >::clear(), Foam::endl(), Foam::exit(), mapPolyMesh::faceMap(), polyTopoChange::faces(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), forAll, mapPolyMesh::hasMotionPoints(), Foam::Info, Foam::inplaceRenumber(), polyTopoChange::modifyFace(), n, Foam::nl, polyTopoChange::points(), mapPolyMesh::preMotionPoints(), polyTopoChange::removeFace(), Foam::renumber(), Foam::returnReduce(), mapPolyMesh::reverseFaceMap(), mapPolyMesh::reversePointMap(), polyTopoChange::setCapacity(), PtrList< T >::setSize(), UPtrList< T >::size(), timeName, and meshRefinement::updateList().
distribute()
void distribute (const mapDistributePolyMesh & map)
Definition at line 3199 of file meshRefinement.C.
References PtrList< T >::clear(), mapDistributePolyMesh::distributeFaceData(), e, treeBoundBox::extend(), Foam::faceMap(), forAll, meshBb(), and rndGen.
updateMesh() [1/2]
void updateMesh (const mapPolyMesh & map, const labelList & changedFaces)
Definition at line 3261 of file meshRefinement.C.
Referenced by snappyLayerDriver::addLayersSinglePass(), and meshRefinement::mergePatchFaces().
updateList()
template<class T > void updateList (const labelList & newToOld, const T & nullValue, List< T > & elems) static
Definition at line 30 of file meshRefinementTemplates.C.
References forAll, UPtrList< T >::size(), and PtrList< T >::transfer().
Referenced by snappyLayerDriver::addLayers(), snappyLayerDriver::addLayersSinglePass(), and meshRefinement::splitFacesUndo().
storeData()
void storeData (const labelList & pointsToStore, const labelList & facesToStore, const labelList & cellsToStore)
Definition at line 3273 of file meshRefinement.C.
updateMesh() [2/2]
void updateMesh (const mapPolyMesh & map, const labelList & changedFaces, const Map< label > & pointsToRestore, const Map< label > & facesToRestore, const Map< label > & cellsToRestore)
Definition at line 3290 of file meshRefinement.C.
References mapPolyMesh::faceMap(), forAll, forAllConstIters, mapPolyMesh::reverseFaceMap(), UPtrList< T >::size(), dictionary::transfer(), and PtrList< T >::transfer().
mergePatchFaces()
Foam::label mergePatchFaces (const scalar minCos, const scalar concaveCos, const label mergeSize, const labelList & patchIDs, const meshRefinement::FaceMergeType mergeType)
Definition at line 34 of file meshRefinementMerge.C.
References polyMesh::boundaryMesh(), polyTopoChange::changeMesh(), fvMesh::clearOut(), Foam::endl(), polyMesh::faceOwner(), forAll, meshRefinement::growFaceCellFace(), mapPolyMesh::hasMotionPoints(), meshRefinement::IGNOREPATCH, Foam::Info, HashSet< Key, Hash >::insert(), fvMesh::movePoints(), polyMesh::moving(), primitiveMesh::nBoundaryFaces(), Foam::nl, patches, patchIDs(), mapPolyMesh::preMotionPoints(), Foam::returnReduce(), mapPolyMesh::reverseFaceMap(), polyMesh::setInstance(), PtrList< T >::setSize(), UPtrList< T >::size(), meshRefinement::timeName(), meshRefinement::updateMesh(), and fvMesh::updateMesh().
mergePatchFacesUndo()
Foam::label mergePatchFacesUndo (const scalar minCos, const scalar concaveCos, const labelList & patchIDs, const dictionary & motionDict, const labelList & preserveFaces, const meshRefinement::FaceMergeType mergeType)
Definition at line 250 of file meshRefinementMerge.C.
References PtrList< T >::append(), polyTopoChange::changeMesh(), Foam::checkData(), motionSmootherAlgo::checkMesh(), Foam::endl(), forAll, forAllConstIters, Foam::Info, Foam::inplaceMapKey(), HashSet< Key, Hash >::insert(), meshRefinement::MESH, Foam::nl, patches, patchIDs(), Foam::Pout, Foam::returnReduce(), PtrList< T >::setSize(), UPtrList< T >::size(), timeName, and write().
doRemovePoints()
Foam::autoPtr< Foam::mapPolyMesh > doRemovePoints (removePoints & pointRemover, const boolList & pointCanBeDeleted)
Definition at line 630 of file meshRefinementMerge.C.
References polyTopoChange::changeMesh(), Foam::checkData(), Foam::endl(), mapPolyMesh::hasMotionPoints(), Foam::Pout, mapPolyMesh::preMotionPoints(), UPtrList< T >::size(), and timeName.
doRestorePoints()
Foam::autoPtr< Foam::mapPolyMesh > doRestorePoints (removePoints & pointRemover, const labelList & facesToRestore)
Definition at line 692 of file meshRefinementMerge.C.
References polyTopoChange::changeMesh(), Foam::checkData(), Foam::endl(), forAll, mapPolyMesh::hasMotionPoints(), Foam::Pout, mapPolyMesh::preMotionPoints(), mapPolyMesh::reverseFaceMap(), UPtrList< T >::size(), and timeName.
collectFaces()
Foam::labelList collectFaces (const labelList & candidateFaces, const labelHashSet & set) const
Definition at line 770 of file meshRefinementMerge.C.
References Foam::findIndices(), and syncTools::syncFaceList().
growFaceCellFace() [1/2]
Foam::labelList growFaceCellFace (const labelUList & set) const
Definition at line 833 of file meshRefinementMerge.C.
References Foam::findIndices(), Foam::markGrowFaceCellFace(), and syncTools::syncFaceList().
Referenced by meshRefinement::mergePatchFaces().
growFaceCellFace() [2/2]
Foam::labelList growFaceCellFace (const labelHashSet & set) const
Definition at line 856 of file meshRefinementMerge.C.
References Foam::findIndices(), Foam::markGrowFaceCellFace(), and syncTools::syncFaceList().
mergeEdgesUndo()
Foam::label mergeEdgesUndo (const scalar minCos, const dictionary & motionDict)
Definition at line 880 of file meshRefinementMerge.C.
References motionSmootherAlgo::checkMesh(), Foam::endl(), Foam::Info, meshRefinement::MESH, n, Foam::nl, Foam::Pout, Foam::returnReduce(), UPtrList< T >::size(), timeName, and write().
checkData()
void checkData ()
Definition at line 896 of file meshRefinement.C.
References Foam::endl(), localPointRegion::findDuplicateFaces(), forAll, Foam::identity(), Foam::Pout, UList< T >::size(), syncTools::swapBoundaryFaceList(), syncTools::syncBoundaryFacePositions(), and WarningInFunction.
testSyncPointList() [1/2]
void testSyncPointList (const string & msg, const polyMesh & mesh, const List< scalar > & fld) static
Definition at line 802 of file meshRefinement.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, fld(), forAll, Foam::mag(), mesh, Foam::nl, primitiveMesh::nPoints(), polyMesh::points(), Foam::Pout, UPtrList< T >::size(), and syncTools::syncPointList().
testSyncPointList() [2/2]
void testSyncPointList (const string & msg, const polyMesh & mesh, const List< point > & fld) static
Definition at line 849 of file meshRefinement.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, fld(), forAll, Foam::mag(), mesh, Foam::nl, primitiveMesh::nPoints(), polyMesh::points(), Foam::Pout, UPtrList< T >::size(), syncTools::syncPointList(), and VectorSpace< Form, Cmpt, Ncmpts >::zero.
testSyncBoundaryFaceList()
template<class T > void testSyncBoundaryFaceList (const scalar mergeDistance, const string & msg, const UList< T > & faceData, const UList< T > & syncedFaceData) const
Definition at line 97 of file meshRefinementTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), patches, pp(), UPtrList< T >::size(), and T.
collectAndPrint()
template<class T > void collectAndPrint (const UList< point > & points, const UList< T > & data) static
Definition at line 154 of file meshRefinementTemplates.C.
References UPstream::blocking, Foam::endl(), Foam::Info, Foam::mag(), UPstream::msgType(), points, UPtrList< T >::size(), and Foam::sortedOrder().
getMasterPoints()
Foam::bitSet getMasterPoints (const polyMesh & mesh, const labelList & meshPoints) static
Definition at line 3436 of file meshRefinement.C.
References forAll, Foam::identity(), Foam::labelMax, mesh, PtrList< T >::set(), UList< T >::size(), and syncTools::syncPointList().
Referenced by snappySnapDriver::calcNearestSurface(), snappySnapDriver::detectNearSurfaces(), and displacementMotionSolverMeshMover::move().
getMasterEdges()
Foam::bitSet getMasterEdges (const polyMesh & mesh, const labelList & meshEdges) static
Definition at line 3472 of file meshRefinement.C.
References forAll, Foam::identity(), Foam::labelMax, mesh, PtrList< T >::set(), UList< T >::size(), and syncTools::syncEdgeList().
Referenced by displacementMotionSolverMeshMover::move().
printMeshInfo()
void printMeshInfo (const bool debug, const string & msg) const
Pstream::broadcast(nCells);
Definition at line 3508 of file meshRefinement.C.
References UPtrList< T >::count(), Foam::endl(), forAll, syncTools::getMasterFaces(), syncTools::getMasterPoints(), Foam::gMax(), Foam::Info, Pstream::listCombineGather(), UPstream::master(), Foam::Pout, Foam::returnReduce(), and Foam::Zero.
timeName()
Foam::word timeName () const
Definition at line 3564 of file meshRefinement.C.
Referenced by snappyLayerDriver::addLayersSinglePass(), and meshRefinement::mergePatchFaces().
setInstance()
void setInstance (const fileName & inst)
Definition at line 1103 of file meshRefinement.C.
write() [1/2]
bool write () const
Definition at line 3401 of file meshRefinement.C.
References forAll, and s().
Referenced by snappyLayerDriver::addLayersSinglePass().
dumpRefinementLevel()
void dumpRefinementLevel () const
Definition at line 3575 of file meshRefinement.C.
References Foam::dimless, forAll, MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, Foam::Zero, and fvPatchFieldBase::zeroGradientType().
dumpIntersections()
void dumpIntersections (const fileName & prefix) const
Definition at line 3637 of file meshRefinement.C.
References Foam::endl(), forAll, OFstream::name(), Foam::nl, Foam::Pout, UPtrList< T >::size(), and Foam::meshTools::writeOBJ().
write() [2/2]
void write (const debugType debugFlags, const writeType writeFlags, const fileName & prefix) const
Definition at line 3705 of file meshRefinement.C.
References write().
removeFiles()
void removeFiles (const polyMesh & mesh) static
Definition at line 3738 of file meshRefinement.C.
References DebugVar, Foam::exists(), polyMesh::facesInstance(), io(), mesh, polyMesh::meshSubDir, IOobject::path(), hexRef8::removeFiles(), and Foam::rm().
gAverage()
template<class T > T gAverage (const bitSet & isMasterElem, const UList< T > & values) static
Definition at line 54 of file meshRefinementTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, n, Foam::reduce(), UPtrList< T >::size(), Foam::sum(), T, UPtrList< T >::test(), and Foam::Zero.
Referenced by snappySnapDriver::calcNearestSurface(), fieldSmoother::minSmoothField(), fieldSmoother::smoothLambdaMuDisplacement(), fieldSmoother::smoothNormals(), and fieldSmoother::smoothPatchNormals().
writeLevel() [1/2]
Foam::meshRefinement::writeType writeLevel () static
Definition at line 3762 of file meshRefinement.C.
Referenced by snappyLayerDriver::addLayers(), snappyLayerDriver::addLayers(), snappyLayerDriver::addLayersSinglePass(), meshRefinement::blockLeakFaces(), snappySnapDriver::doSnap(), snappySnapDriver::preSmoothPatch(), and snappySnapDriver::smoothDisplacement().
writeLevel() [2/2]
void writeLevel (const writeType flags) static
Definition at line 3768 of file meshRefinement.C.
readFlags()
template<class EnumContainer > int readFlags (const EnumContainer & namedEnum, const wordList & words) static
Definition at line 245 of file meshRefinementTemplates.C.
get()
template<class Type > Type get (const dictionary & dict, const word & keyword, const bool noExit, enum keyType::option matchOpt = keyType::REGEX, const Type & deflt = Zero) static
Definition at line 322 of file meshRefinementTemplates.C.
References dict, FatalIOErrorInFunction, IOobjectOption::MUST_READ, dictionary::name(), Foam::nl, IOobjectOption::READ_IF_PRESENT, and dictionary::readEntry().
subDict()
const Foam::dictionary & subDict (const dictionary & dict, const word & keyword, const bool noExit, enum keyType::option matchOpt = keyType::REGEX) static
Definition at line 3786 of file meshRefinement.C.
References dictionary::csearch(), dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::nl, dictionary::null, and dictionary::relativeName().
Referenced by layerParameters::layerParameters().
lookup()
Foam::ITstream & lookup (const dictionary & dict, const word & keyword, const bool noExit, enum keyType::option matchOpt = keyType::REGEX) static
Definition at line 3817 of file meshRefinement.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::findEntry(), UILList< LListBase, T >::first(), Foam::nl, and dictionary::relativeName().
Member Data Documentation
debugTypeNames
const Foam::Enum< Foam::meshRefinement::debugType > debugTypeNames static
Definition at line 98 of file meshRefinement.H.
writeTypeNames
const Foam::Enum< Foam::meshRefinement::writeType > writeTypeNames static
Definition at line 118 of file meshRefinement.H.
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/meshRefinement/meshRefinement.H
src/mesh/snappyHexMesh/meshRefinement/meshRefinement.C
src/mesh/snappyHexMesh/meshRefinement/meshRefinementBaffles.C
src/mesh/snappyHexMesh/meshRefinement/meshRefinementBlock.C
src/mesh/snappyHexMesh/meshRefinement/meshRefinementGapRefine.C
src/mesh/snappyHexMesh/meshRefinement/meshRefinementMerge.C
src/mesh/snappyHexMesh/meshRefinement/meshRefinementProblemCells.C
src/mesh/snappyHexMesh/meshRefinement/meshRefinementRefine.C
src/mesh/snappyHexMesh/meshRefinement/meshRefinementTemplates.C