OpenFOAM: gaussConvectionScheme< Type > Class Template Reference
gaussConvectionScheme< Type > Class Template Reference
Basic second-order convection using face-gradients and Gauss' theorem.
#include <gaussFaConvectionScheme.H>
Public Member Functions
TypeName ("Gauss")
gaussConvectionScheme (const faMesh &mesh, const edgeScalarField &faceFlux, const tmp< edgeInterpolationScheme< Type > > &scheme)
gaussConvectionScheme (const faMesh &mesh, const edgeScalarField &faceFlux, Istream &is)
tmp< GeometricField< Type, faePatchField, edgeMesh > > flux (const edgeScalarField &, const GeometricField< Type, faPatchField, areaMesh > &) const
tmp< faMatrix< Type > > famDiv (const edgeScalarField &, const GeometricField< Type, faPatchField, areaMesh > &) const
tmp< GeometricField< Type, faPatchField, areaMesh > > facDiv (const edgeScalarField &, const GeometricField< Type, faPatchField, areaMesh > &) const
Public Member Functions inherited from convectionScheme< Type >
declareRunTimeSelectionTable (tmp, convectionScheme, Istream,(const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
convectionScheme (const faMesh &mesh, const edgeScalarField &faceFlux)
virtual ~convectionScheme ()
const faMesh & mesh () const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from convectionScheme< Type >
static tmp< convectionScheme< Type > > New (const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData)
Detailed Description
template<class Type>
class Foam::fa::gaussConvectionScheme< Type >
Basic second-order convection using face-gradients and Gauss' theorem.
Source files
gaussFaConvectionScheme.H
gaussFaConvectionScheme.C
gaussFaConvectionSchemes.C
Definition at line 54 of file gaussFaConvectionScheme.H.
Constructor & Destructor Documentation
gaussConvectionScheme() [1/2]
template<class Type > gaussConvectionScheme (const faMesh & mesh, const edgeScalarField & faceFlux, const tmp< edgeInterpolationScheme< Type > > & scheme) inline
Definition at line 81 of file gaussFaConvectionScheme.H.
gaussConvectionScheme() [2/2]
template<class Type > gaussConvectionScheme (const faMesh & mesh, const edgeScalarField & faceFlux, Istream & is) inline
Definition at line 93 of file gaussFaConvectionScheme.H.
Member Function Documentation
TypeName()
template<class Type > TypeName ("Gauss")
flux()
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > flux (const edgeScalarField & faceFlux, const GeometricField< Type, faPatchField, areaMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 39 of file gaussFaConvectionScheme.C.
famDiv()
template<class Type > tmp< faMatrix< Type > > famDiv (const edgeScalarField & faceFlux, const GeometricField< Type, faPatchField, areaMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 51 of file gaussFaConvectionScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::fac::edgeIntegrate(), forAll, and GeometricField< Type, PatchField, GeoMesh >::internalField().
facDiv()
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > facDiv (const edgeScalarField & faceFlux, const GeometricField< Type, faPatchField, areaMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 104 of file gaussFaConvectionScheme.C.
References Foam::fac::edgeIntegrate().
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/convectionSchemes/gaussFaConvectionScheme/gaussFaConvectionScheme.H
src/finiteArea/finiteArea/convectionSchemes/gaussFaConvectionScheme/gaussFaConvectionScheme.C