OpenFOAM: vtkUnstructuredReader Class Reference
vtkUnstructuredReader Class Reference
Reader for vtk UNSTRUCTURED_GRID legacy files. Supports single CELLS, POINTS etc. entry only.
#include <vtkUnstructuredReader.H>
Public Types
enum vtkDataType {
VTK_INT , VTK_INT64 , VTK_UINT , VTK_LONG ,
VTK_ULONG , VTK_FLOAT , VTK_DOUBLE , VTK_STRING ,
VTK_ID
}
enum vtkDataSetType { VTK_FIELD , VTK_SCALARS , VTK_VECTORS }
enum parseMode {
NOMODE , UNSTRUCTURED_GRID , POLYDATA , CELL_DATA ,
POINT_DATA
}
Public Member Functions
ClassName ("vtkUnstructuredReader")
vtkUnstructuredReader (const objectRegistry &obr, ISstream &is)
const string & header () const noexcept
const string & title () const noexcept
const string & dataType () const noexcept
const pointField & points () const noexcept
pointField & points () noexcept
const cellShapeList & cells () const noexcept
cellShapeList & cells () noexcept
const labelList & cellMap () const noexcept
const faceList & faces () const noexcept
faceList & faces () noexcept
const labelList & faceMap () const noexcept
const labelListList & lines () const noexcept
labelListList & lines () noexcept
const labelList & lineMap () const noexcept
const objectRegistry & cellData () const noexcept
objectRegistry & cellData () noexcept
const objectRegistry & pointData () const noexcept
objectRegistry & pointData () noexcept
const objectRegistry & otherData () const noexcept
objectRegistry & otherData () noexcept
Static Public Member Functions
template<class Type >
static void printFieldStats (const objectRegistry &)
Static Public Attributes
static const Enum< vtkDataType > vtkDataTypeNames
static const Enum< vtkDataSetType > vtkDataSetTypeNames
static const Enum< parseMode > parseModeNames
Detailed Description
Reader for vtk UNSTRUCTURED_GRID legacy files. Supports single CELLS, POINTS etc. entry only.
all integer types (int, unsigned_int, long etc.) become Foam::label
all real types (float, double) become Foam::scalar
POINTS becomes OpenFOAM points
CELLS gets split into OpenFOAM
cells
faces
lines
CELL_DATA or POINT_DATA gets stored on the corresponding objectRegistry in original vtk numbering order so use e.g. faceMap() to go from entry in faces() back to vtk numbering.
Source files
vtkUnstructuredReader.H
vtkUnstructuredReader.C
Definition at line 63 of file vtkUnstructuredReader.H.
Member Enumeration Documentation
vtkDataType
enum vtkDataType
Enumerator
VTK_INT
VTK_INT64
VTK_UINT
VTK_LONG
VTK_ULONG
VTK_FLOAT
VTK_DOUBLE
VTK_STRING
VTK_ID
Definition at line 70 of file vtkUnstructuredReader.H.
vtkDataSetType
enum vtkDataSetType
Enumerator
VTK_FIELD
VTK_SCALARS
VTK_VECTORS
Definition at line 87 of file vtkUnstructuredReader.H.
parseMode
enum parseMode
Enumerator
NOMODE
UNSTRUCTURED_GRID
POLYDATA
CELL_DATA
POINT_DATA
Definition at line 98 of file vtkUnstructuredReader.H.
Constructor & Destructor Documentation
vtkUnstructuredReader()
vtkUnstructuredReader (const objectRegistry & obr, ISstream & is)
Definition at line 586 of file vtkUnstructuredReader.C.
Member Function Documentation
ClassName()
ClassName ("vtkUnstructuredReader")
header()
const string & header () const inline noexcept
Definition at line 232 of file vtkUnstructuredReader.H.
title()
const string & title () const inline noexcept
Definition at line 238 of file vtkUnstructuredReader.H.
dataType()
const string & dataType () const inline noexcept
Definition at line 244 of file vtkUnstructuredReader.H.
points() [1/2]
const pointField & points () const inline noexcept
Definition at line 251 of file vtkUnstructuredReader.H.
Referenced by VTKsurfaceFormat< Face >::read(), and VTKedgeFormat::read().
points() [2/2]
pointField & points () inline noexcept
Definition at line 256 of file vtkUnstructuredReader.H.
cells() [1/2]
const cellShapeList & cells () const inline noexcept
Definition at line 262 of file vtkUnstructuredReader.H.
cells() [2/2]
cellShapeList & cells () inline noexcept
Definition at line 267 of file vtkUnstructuredReader.H.
cellMap()
const labelList & cellMap () const inline noexcept
Definition at line 272 of file vtkUnstructuredReader.H.
faces() [1/2]
const faceList & faces () const inline noexcept
Definition at line 278 of file vtkUnstructuredReader.H.
Referenced by VTKsurfaceFormat< Face >::read().
faces() [2/2]
faceList & faces () inline noexcept
Definition at line 283 of file vtkUnstructuredReader.H.
faceMap()
const labelList & faceMap () const inline noexcept
Definition at line 288 of file vtkUnstructuredReader.H.
lines() [1/2]
const labelListList & lines () const inline noexcept
Definition at line 294 of file vtkUnstructuredReader.H.
Referenced by VTKedgeFormat::read().
lines() [2/2]
labelListList & lines () inline noexcept
Definition at line 299 of file vtkUnstructuredReader.H.
lineMap()
const labelList & lineMap () const inline noexcept
Definition at line 304 of file vtkUnstructuredReader.H.
cellData() [1/2]
const objectRegistry & cellData () const inline noexcept
Definition at line 310 of file vtkUnstructuredReader.H.
Referenced by VTKsurfaceFormat< Face >::read().
cellData() [2/2]
objectRegistry & cellData () inline noexcept
Definition at line 315 of file vtkUnstructuredReader.H.
pointData() [1/2]
const objectRegistry & pointData () const inline noexcept
Definition at line 321 of file vtkUnstructuredReader.H.
pointData() [2/2]
objectRegistry & pointData () inline noexcept
Definition at line 326 of file vtkUnstructuredReader.H.
otherData() [1/2]
const objectRegistry & otherData () const inline noexcept
Definition at line 332 of file vtkUnstructuredReader.H.
otherData() [2/2]
objectRegistry & otherData () inline noexcept
Definition at line 337 of file vtkUnstructuredReader.H.
printFieldStats()
template<class Type > void printFieldStats (const objectRegistry & obj) static
Definition at line 27 of file vtkUnstructuredReaderTemplates.C.
References Foam::endl(), Foam::Info, Foam::nl, and UList< T >::size().
Member Data Documentation
vtkDataTypeNames
const Foam::Enum< Foam::vtkUnstructuredReader::vtkDataType > vtkDataTypeNames static
Definition at line 83 of file vtkUnstructuredReader.H.
vtkDataSetTypeNames
const Foam::Enum< Foam::vtkUnstructuredReader::vtkDataSetType > vtkDataSetTypeNames static
Definition at line 94 of file vtkUnstructuredReader.H.
parseModeNames
const Foam::Enum< Foam::vtkUnstructuredReader::parseMode > parseModeNames static
Definition at line 107 of file vtkUnstructuredReader.H.
The documentation for this class was generated from the following files:
src/fileFormats/vtk/read/vtkUnstructuredReader.H
src/fileFormats/vtk/read/vtkUnstructuredReader.C
src/fileFormats/vtk/read/vtkUnstructuredReaderTemplates.C