OpenFOAM: tableReader< Type > Class Template Reference
tableReader< Type > Class Template Reference abstract
Base class to read table data for the interpolationTable.
#include <tableReader.H>
Public Member Functions
TypeName ("tableReader")
declareRunTimeSelectionTable (autoPtr, tableReader, dictionary,(const dictionary &dict),(dict))
tableReader ()=default
tableReader (const dictionary &dict)
virtual autoPtr< tableReader< Type > > clone () const =0
virtual ~tableReader ()=default
virtual void operator() (const fileName &fName, List< Tuple2< scalar, Type > > &data)=0
virtual void operator() (const fileName &fName, List< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &tbl)=0
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< tableReader > New (const dictionary &spec)
Detailed Description
template<class Type>
class Foam::tableReader< Type >
Base class to read table data for the interpolationTable.
Source files
tableReader.H
tableReader.C
Definition at line 56 of file tableReader.H.
Constructor & Destructor Documentation
tableReader() [1/2]
template<class Type > tableReader () default
tableReader() [2/2]
template<class Type > tableReader (const dictionary & dict)
Definition at line 58 of file tableReader.C.
~tableReader()
template<class Type > virtual ~tableReader () virtual default
Member Function Documentation
TypeName()
template<class Type > TypeName ("tableReader< Type >")
declareRunTimeSelectionTable()
template<class Type > declareRunTimeSelectionTable (autoPtr , tableReader< Type > , dictionary , (const dictionary &dict) , (dict))
clone()
template<class Type > virtual autoPtr< tableReader< Type > > clone () const pure virtual
Implemented in csvTableReader< Type >, and openFoamTableReader< Type >.
New()
template<class Type > Foam::autoPtr< Foam::tableReader< Type > > New (const dictionary & spec) static
Definition at line 27 of file tableReader.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and PtrList< T >::PtrList().
operator()() [1/2]
template<class Type > virtual void operator() (const fileName & fName, List< Tuple2< scalar, Type > > & data) pure virtual
Implemented in csvTableReader< Type >, and openFoamTableReader< Type >.
operator()() [2/2]
template<class Type > virtual void operator() (const fileName & fName, List< Tuple2< scalar, List< Tuple2< scalar, Type > > > > & tbl) pure virtual
Implemented in csvTableReader< Type >, and openFoamTableReader< Type >.
write()
template<class Type > void write (Ostream & os) const virtual
Reimplemented in csvTableReader< Type >.
Definition at line 65 of file tableReader.C.
References os(), Foam::type(), and Ostream::writeEntryIfDifferent().
Referenced by csvTableReader< Type >::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/interpolationTable/tableReaders/tableReader.H
src/OpenFOAM/interpolations/interpolationTable/tableReaders/tableReader.C