OpenFOAM: departureDiameterModel Class Reference
departureDiameterModel Class Reference abstract
Base class for bubble departure diameter models for boiling flows.
#include <departureDiameterModel.H>
Public Member Functions
TypeName ("departureDiameterModel")
declareRunTimeSelectionTable (autoPtr, departureDiameterModel, dictionary,(const dictionary &dict),(dict))
departureDiameterModel ()=default
virtual ~departureDiameterModel ()=default
virtual tmp< scalarField > dDeparture (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const =0
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< departureDiameterModel > New (const dictionary &dict)
Detailed Description
Base class for bubble departure diameter models for boiling flows.
Source files
departureDiameterModel.H
departureDiameterModel.C
Definition at line 53 of file departureDiameterModel.H.
Constructor & Destructor Documentation
departureDiameterModel()
departureDiameterModel () default
~departureDiameterModel()
virtual ~departureDiameterModel () virtual default
Member Function Documentation
TypeName()
TypeName ("departureDiameterModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , departureDiameterModel , dictionary , (const dictionary &dict) , (dict))
New()
Foam::autoPtr< Foam::wallBoilingModels::departureDiameterModel > New (const dictionary & dict) static
Definition at line 39 of file departureDiameterModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
Referenced by alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField().
dDeparture()
virtual tmp< scalarField > dDeparture (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const pure virtual
Implemented in KocamustafaogullariIshii, and TolubinskiKostanchuk.
write()
void write (Ostream & os) const virtual
Reimplemented in KocamustafaogullariIshii, and TolubinskiKostanchuk.
Definition at line 67 of file departureDiameterModel.C.
References os(), and Foam::type().
Referenced by KocamustafaogullariIshii::write(), and TolubinskiKostanchuk::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/departureDiameterModels/departureDiameterModel/departureDiameterModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/departureDiameterModels/departureDiameterModel/departureDiameterModel.C