OpenFOAM: Implicit< CloudType > Class Template Reference
Implicit< CloudType > Class Template Reference
Lagrangian particle models » Submodels » MP-PIC » Packing
Implicit model for applying an inter-particle stress to the particles.
#include <Implicit.H>
Public Member Functions
TypeName ("implicit")
Implicit (const dictionary &dict, CloudType &owner)
Implicit (const Implicit< CloudType > &cm)
virtual autoPtr< PackingModel< CloudType > > clone () const
virtual ~Implicit ()
virtual void cacheFields (const bool store)
virtual vector velocityCorrection (typename CloudType::parcelType &p, const scalar deltaT) const
Public Member Functions inherited from PackingModel< CloudType >
TypeName ("packingModel")
declareRunTimeSelectionTable (autoPtr, PackingModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
PackingModel (CloudType &owner)
PackingModel (const dictionary &dict, CloudType &owner, const word &type)
PackingModel (const PackingModel< CloudType > &cm)
virtual ~PackingModel ()
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from PackingModel< CloudType >
static autoPtr< PackingModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from PackingModel< CloudType >
autoPtr< ParticleStressModel > particleStressModel_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::PackingModels::Implicit< CloudType >
Implicit model for applying an inter-particle stress to the particles.
The time evolution of particulate volume fraction is solved for implicitly on the eulerian mesh. The computed flux is then applied to the lagrangian field. The gravity force can optionally be applied to the particles as part of this model, using the keyword "applyGravity".
Source files
Implicit.H
Implicit.C
Definition at line 57 of file Implicit.H.
Constructor & Destructor Documentation
Implicit() [1/2]
template<class CloudType > Implicit (const dictionary & dict, CloudType & owner)
Definition at line 33 of file Implicit.C.
References Foam::dimless, Foam::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and CloudSubModelBase< CloudType >::owner().
Implicit() [2/2]
template<class CloudType > Implicit (const Implicit< CloudType > & cm)
Definition at line 67 of file Implicit.C.
References GeometricField< Type, PatchField, GeoMesh >::oldTime().
~Implicit()
template<class CloudType > ~Implicit () virtual
Definition at line 88 of file Implicit.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("implicit")
clone()
template<class CloudType > virtual autoPtr< PackingModel< CloudType > > clone () const inline virtual
Implements PackingModel< CloudType >.
Definition at line 99 of file Implicit.H.
cacheFields()
template<class CloudType > void cacheFields (const bool store) virtual
Reimplemented from subModelBase.
Definition at line 95 of file Implicit.C.
References subModelBase::cacheFields(), cloudName(), Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::dimDensity, Foam::dimPressure, Foam::dimVelocity, Foam::fvm::div(), forAll, g, Foam::fvc::interpolate(), Foam::fvm::laplacian(), Foam::linearInterpolate(), Foam::max(), mesh, Foam::min(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, phi, Foam::fvc::reconstruct(), rho, timeName, U, Foam::Zero, and fvPatchFieldBase::zeroGradientType().
velocityCorrection()
template<class CloudType > Foam::vector velocityCorrection (typename CloudType::parcelType & p, const scalar deltaT) const virtual
Implements PackingModel< CloudType >.
Definition at line 326 of file Implicit.C.
References Foam::mag(), mesh, p, phi, and U.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/PackingModels/Implicit/Implicit.H
src/lagrangian/intermediate/submodels/MPPIC/PackingModels/Implicit/Implicit.C