OpenFOAM: pressureDirectedInletVelocityFvPatchVectorField Class Reference
pressureDirectedInletVelocityFvPatchVectorField Class Reference
Boundary conditions » Inlet
This velocity inlet boundary condition is applied to patches where the pressure is specified. The inflow velocity is obtained from the flux with the specified inlet direction" direction.
#include <pressureDirectedInletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("pressureDirectedInletVelocity")
pressureDirectedInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
pressureDirectedInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
pressureDirectedInletVelocityFvPatchVectorField (const pressureDirectedInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
pressureDirectedInletVelocityFvPatchVectorField (const pressureDirectedInletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
pressureDirectedInletVelocityFvPatchVectorField (const pressureDirectedInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual bool assignable () const
const word & rhoName () const
word & rhoName ()
const word & phiName () const
word & phiName ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This velocity inlet boundary condition is applied to patches where the pressure is specified. The inflow velocity is obtained from the flux with the specified inlet direction" direction.
Usage
Property Description Required Default value
phi flux field name no phi
rho density field name no rho
inletDirection inlet direction per patch face yes
Example of the boundary condition specification:
    <patchName>
    {
        type            pressureDirectedInletVelocity;
        phi             phi;
        rho             rho;
        inletDirection  uniform (1 0 0);
        value           uniform 0;
    }
Note
If reverse flow is possible or expected use the pressureDirectedInletOutletVelocityFvPatchVectorField condition instead.
See also
Foam::fixedValueFvPatchField Foam::pressureDirectedInletOutletVelocityFvPatchVectorField
Source files
pressureDirectedInletVelocityFvPatchVectorField.H
pressureDirectedInletVelocityFvPatchVectorField.C
Definition at line 101 of file pressureDirectedInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
pressureDirectedInletVelocityFvPatchVectorField() [1/5]
pressureDirectedInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 31 of file pressureDirectedInletVelocityFvPatchVectorField.C.
pressureDirectedInletVelocityFvPatchVectorField() [2/5]
pressureDirectedInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 61 of file pressureDirectedInletVelocityFvPatchVectorField.C.
pressureDirectedInletVelocityFvPatchVectorField() [3/5]
pressureDirectedInletVelocityFvPatchVectorField (const pressureDirectedInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 45 of file pressureDirectedInletVelocityFvPatchVectorField.C.
pressureDirectedInletVelocityFvPatchVectorField() [4/5]
pressureDirectedInletVelocityFvPatchVectorField (const pressureDirectedInletVelocityFvPatchVectorField & pivpvf)
Definition at line 76 of file pressureDirectedInletVelocityFvPatchVectorField.C.
pressureDirectedInletVelocityFvPatchVectorField() [5/5]
pressureDirectedInletVelocityFvPatchVectorField (const pressureDirectedInletVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 89 of file pressureDirectedInletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("pressureDirectedInletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 158 of file pressureDirectedInletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 174 of file pressureDirectedInletVelocityFvPatchVectorField.H.
assignable()
virtual bool assignable () const inline virtual
Definition at line 193 of file pressureDirectedInletVelocityFvPatchVectorField.H.
rhoName() [1/2]
const word & rhoName () const inline
Definition at line 199 of file pressureDirectedInletVelocityFvPatchVectorField.H.
rhoName() [2/2]
word & rhoName () inline
Definition at line 205 of file pressureDirectedInletVelocityFvPatchVectorField.H.
phiName() [1/2]
const word & phiName () const inline
Definition at line 211 of file pressureDirectedInletVelocityFvPatchVectorField.H.
phiName() [2/2]
word & phiName () inline
Definition at line 217 of file pressureDirectedInletVelocityFvPatchVectorField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 105 of file pressureDirectedInletVelocityFvPatchVectorField.C.
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Definition at line 115 of file pressureDirectedInletVelocityFvPatchVectorField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 130 of file pressureDirectedInletVelocityFvPatchVectorField.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::exit(), Foam::FatalError, FatalErrorInFunction, n, and Foam::operator==().
write()
void write (Ostream & os) const virtual
Definition at line 166 of file pressureDirectedInletVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 181 of file pressureDirectedInletVelocityFvPatchVectorField.C.
References fvPatchField< Type >::operator=().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/pressureDirectedInletVelocity/pressureDirectedInletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/pressureDirectedInletVelocity/pressureDirectedInletVelocityFvPatchVectorField.C