OpenFOAM: linearDamper Class Reference
linearDamper Class Reference
sixDoFRigidBodyMotionRestraints model. Linear spring.
#include <linearDamper.H>
Public Member Functions
TypeName ("linearDamper")
linearDamper (const word &name, const dictionary &sDoFRBMRDict)
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const
virtual ~linearDamper ()
virtual void restrain (const sixDoFRigidBodyMotion &motion, vector &restraintPosition, vector &restraintForce, vector &restraintMoment) const
virtual bool read (const dictionary &sDoFRBMRCoeff)
virtual void write (Ostream &) const
Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
TypeName ("sixDoFRigidBodyMotionRestraint")
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionRestraint, dictionary,(const word &name, const dictionary &sDoFRBMRDict),(name, sDoFRBMRDict))
sixDoFRigidBodyMotionRestraint (const word &name, const dictionary &sDoFRBMRDict)
virtual ~sixDoFRigidBodyMotionRestraint ()
const word & name () const
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
static autoPtr< sixDoFRigidBodyMotionRestraint > New (const word &name, const dictionary &sDoFRBMRDict)
Protected Attributes inherited from sixDoFRigidBodyMotionRestraint
word name_
dictionary sDoFRBMRCoeffs_
Detailed Description
sixDoFRigidBodyMotionRestraints model. Linear spring.
Source files
linearDamper.H
linearDamper.C
Definition at line 50 of file linearDamper.H.
Constructor & Destructor Documentation
linearDamper()
linearDamper (const word & name, const dictionary & sDoFRBMRDict)
Definition at line 45 of file linearDamper.C.
References Foam::name(), and linearDamper::read().
~linearDamper()
~linearDamper () virtual
Definition at line 60 of file linearDamper.C.
Member Function Documentation
TypeName()
TypeName ("linearDamper")
clone()
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const inline virtual
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 76 of file linearDamper.H.
restrain()
void restrain (const sixDoFRigidBodyMotion & motion, vector & restraintPosition, vector & restraintForce, vector & restraintMoment) const virtual
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 66 of file linearDamper.C.
References Foam::endl(), Foam::Info, sixDoFRigidBodyMotion::report(), sixDoFRigidBodyMotion::v(), and Foam::Zero.
read()
bool read (const dictionary & sDoFRBMRCoeff) virtual
Reimplemented from sixDoFRigidBodyMotionRestraint.
Definition at line 85 of file linearDamper.C.
References sixDoFRigidBodyMotionRestraint::read().
Referenced by linearDamper::linearDamper().
write()
void write (Ostream & os) const virtual
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 98 of file linearDamper.C.
References os().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/linearDamper/linearDamper.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/linearDamper/linearDamper.C