OpenFOAM: multiDimPolyFitter< T > Class Template Reference
multiDimPolyFitter< T > Class Template Reference
Fit a polynominal function with the help of multiDimPolyFunction.
#include <multiDimPolyFitter.H>
Public Member Functions
multiDimPolyFitter (const word &polyFunctionName, const labelVector &geomDirs)
void resetMatrix ()
label nCoeffs () const
void fillMatrix (const scalarField &polyTerms, const T &value)
void fillMatrix (const scalarField &polyTerms, const T &value, const scalar weight)
void fillMatrix (const scalarField &polyTerms, scalarSymmetricSquareMatrix &A)
Field< T > fitData (const List< scalarField > &listPolyTerms, const List< T > &listValue)
Field< T > fitData (const List< scalarField > &listPolyTerms, const List< T > &listValue, const List< scalar > &listWeight)
scalarSymmetricSquareMatrix computeInverse (const List< scalarField > &listPolyTerms)
Field< T > computeMatrixSource (const List< scalarField > &listPolyTerms, const List< T > &listValue)
Field< T > fitData (const List< vector > &positions, const List< T > &listValue)
Field< T > fitData (const List< vector > &positions, const List< T > &listValue, const List< scalar > &listWeight)
scalarSymmetricSquareMatrix computeInverse (const List< vector > &positions)
Field< T > computeMatrixSource (const List< vector > &positions, const List< T > &listValue)
Detailed Description
template<class T>
class Foam::multiDimPolyFitter< T >
Fit a polynominal function with the help of multiDimPolyFunction.
Original code supplied by Henning Scheufler, DLR (2019)
Source files
multiDimPolyFitter.H
multiDimPolyFitter.C
Definition at line 50 of file multiDimPolyFitter.H.
Constructor & Destructor Documentation
multiDimPolyFitter()
template<class T > multiDimPolyFitter (const word & polyFunctionName, const labelVector & geomDirs)
Definition at line 26 of file multiDimPolyFitter.C.
References Foam::New().
Member Function Documentation
resetMatrix()
template<class T > void resetMatrix ()
Definition at line 40 of file multiDimPolyFitter.C.
References UPtrList< T >::size(), and Foam::Zero.
nCoeffs()
template<class T > label nCoeffs () const inline
Definition at line 75 of file multiDimPolyFitter.H.
fillMatrix() [1/3]
template<class T > void fillMatrix (const scalarField & polyTerms, const T & value)
Definition at line 51 of file multiDimPolyFitter.C.
fillMatrix() [2/3]
template<class T > void fillMatrix (const scalarField & polyTerms, const T & value, const scalar weight)
Definition at line 76 of file multiDimPolyFitter.C.
fillMatrix() [3/3]
template<class T > void fillMatrix (const scalarField & polyTerms, scalarSymmetricSquareMatrix & A)
Definition at line 102 of file multiDimPolyFitter.C.
References A.
fitData() [1/4]
template<class T > Foam::Field< T > fitData (const List< scalarField > & listPolyTerms, const List< T > & listValue)
Definition at line 122 of file multiDimPolyFitter.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, and UPtrList< T >::size().
fitData() [2/4]
template<class T > Foam::Field< T > fitData (const List< scalarField > & listPolyTerms, const List< T > & listValue, const List< scalar > & listWeight)
Definition at line 156 of file multiDimPolyFitter.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, and UPtrList< T >::size().
computeInverse() [1/2]
template<class T > Foam::scalarSymmetricSquareMatrix computeInverse (const List< scalarField > & listPolyTerms)
Definition at line 194 of file multiDimPolyFitter.C.
References forAll, Foam::inv(), and Foam::Zero.
computeMatrixSource() [1/2]
template<class T > Foam::Field< T > computeMatrixSource (const List< scalarField > & listPolyTerms, const List< T > & listValue)
Definition at line 215 of file multiDimPolyFitter.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UPtrList< T >::size(), and Foam::Zero.
fitData() [3/4]
template<class T > Foam::Field< T > fitData (const List< vector > & positions, const List< T > & listValue)
Definition at line 245 of file multiDimPolyFitter.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, and UPtrList< T >::size().
fitData() [4/4]
template<class T > Foam::Field< T > fitData (const List< vector > & positions, const List< T > & listValue, const List< scalar > & listWeight)
Definition at line 278 of file multiDimPolyFitter.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, and UPtrList< T >::size().
computeInverse() [2/2]
template<class T > Foam::scalarSymmetricSquareMatrix computeInverse (const List< vector > & positions)
Definition at line 313 of file multiDimPolyFitter.C.
References forAll, Foam::inv(), and Foam::Zero.
computeMatrixSource() [2/2]
template<class T > Foam::Field< T > computeMatrixSource (const List< vector > & positions, const List< T > & listValue)
Definition at line 334 of file multiDimPolyFitter.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UPtrList< T >::size(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMatrices/solvers/multiDimPolyFitter/multiDimPolyFitter.H
src/finiteVolume/fvMatrices/solvers/multiDimPolyFitter/multiDimPolyFitter.C