OpenFOAM: alphaContactAngleFvPatchScalarField Class Reference
alphaContactAngleFvPatchScalarField Class Reference
#include <alphaContactAngleFvPatchScalarField.H>
Classes
class interfaceThetaProps
Public Types
typedef HashTable< interfaceThetaProps, multiphaseSystem::interfacePair, multiphaseSystem::interfacePair::symmHash > thetaPropsTable
Public Member Functions
TypeName ("multiphaseEuler::alphaContactAngle")
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchScalarField > clone () const
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
const thetaPropsTable & thetaProps () const
virtual void write (Ostream &) const
Detailed Description
Definition at line 51 of file alphaContactAngleFvPatchScalarField.H.
Member Typedef Documentation
thetaPropsTable
typedef HashTable< interfaceThetaProps, multiphaseSystem::interfacePair, multiphaseSystem::interfacePair::symmHash > thetaPropsTable
Definition at line 122 of file alphaContactAngleFvPatchScalarField.H.
Constructor & Destructor Documentation
alphaContactAngleFvPatchScalarField() [1/4]
alphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 73 of file alphaContactAngleFvPatchScalarField.C.
alphaContactAngleFvPatchScalarField() [2/4]
alphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 96 of file alphaContactAngleFvPatchScalarField.C.
alphaContactAngleFvPatchScalarField() [3/4]
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField & gcpsf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 83 of file alphaContactAngleFvPatchScalarField.C.
alphaContactAngleFvPatchScalarField() [4/4]
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField & gcpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 110 of file alphaContactAngleFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("multiphaseEuler::alphaContactAngle")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 166 of file alphaContactAngleFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 182 of file alphaContactAngleFvPatchScalarField.H.
thetaProps()
const thetaPropsTable & thetaProps () const inline
Definition at line 197 of file alphaContactAngleFvPatchScalarField.H.
write()
void write (Ostream & os) const virtual
Definition at line 123 of file alphaContactAngleFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseEuler/multiphaseSystem/derivedFvPatchFields/alphaContactAngle/alphaContactAngleFvPatchScalarField.H
src/phaseSystemModels/multiphaseEuler/multiphaseSystem/derivedFvPatchFields/alphaContactAngle/alphaContactAngleFvPatchScalarField.C