OpenFOAM: SprayParcel< ParcelType > Class Template Reference
SprayParcel< ParcelType > Class Template Reference
Reacting spray parcel, with added functionality for atomization and breakup.
#include <SprayParcel.H>
Classes
class constantProperties
class iNew
Public Types
typedef ParcelType::trackingData trackingData
Public Member Functions
TypeName ("SprayParcel")
AddToPropertyList (ParcelType, " d0"+" position0"+" sigma"+" mu"+" liquidCore"+" KHindex"+" y"+" yDot"+" tc"+" ms"+" injector"+" tMom"+" user")
SprayParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
SprayParcel (const polyMesh &mesh, const vector &position, const label celli)
SprayParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &f0, const vector &angularMomentum0, const vector &torque0, const scalarField &Y0, const scalar liquidCore, const scalar KHindex, const scalar y, const scalar yDot, const scalar tc, const scalar ms, const scalar injector, const scalar tMom, const scalar user, const typename ParcelType::constantProperties &constProps)
SprayParcel (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
SprayParcel (const SprayParcel &p, const polyMesh &mesh)
SprayParcel (const SprayParcel &p)
virtual autoPtr< particle > clone () const
virtual autoPtr< particle > clone (const polyMesh &mesh) const
scalar d0 () const
const vector & position0 () const
scalar sigma () const
scalar mu () const
scalar liquidCore () const
scalar KHindex () const
scalar y () const
scalar yDot () const
scalar tc () const
scalar ms () const
scalar injector () const
scalar tMom () const
scalar user () const
scalar & d0 ()
vector & position0 ()
scalar & sigma ()
scalar & mu ()
scalar & liquidCore ()
scalar & KHindex ()
scalar & y ()
scalar & yDot ()
scalar & tc ()
scalar & ms ()
scalar & injector ()
scalar & tMom ()
scalar & user ()
template<class TrackCloudType >
void setCellValues (TrackCloudType &cloud, trackingData &td)
template<class TrackCloudType >
void calcAtomization (TrackCloudType &cloud, trackingData &td, const scalar dt)
template<class TrackCloudType >
void calcBreakup (TrackCloudType &cloud, trackingData &td, const scalar dt)
template<class TrackCloudType >
void cellValueSourceCorrection (TrackCloudType &cloud, trackingData &td, const scalar dt)
template<class TrackCloudType >
void correctSurfaceValues (TrackCloudType &cloud, trackingData &td, const scalar T, const scalarField &Cs, scalar &rhos, scalar &mus, scalar &Pr, scalar &kappa)
template<class TrackCloudType >
void calc (TrackCloudType &cloud, trackingData &td, const scalar dt)
template<class TrackCloudType >
scalar chi (TrackCloudType &cloud, trackingData &td, const scalarField &X) const
template<class TrackCloudType >
void solveTABEq (TrackCloudType &cloud, trackingData &td, const scalar dt)
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly) const
template<class TrackCloudType >
Foam::scalar chi (TrackCloudType &cloud, trackingData &td, const scalarField &X) const
Static Public Member Functions
template<class CloudType , class CompositionType >
static void readFields (CloudType &c, const CompositionType &compModel)
template<class CloudType >
static void readFields (CloudType &c)
template<class CloudType , class CompositionType >
static void writeFields (const CloudType &c, const CompositionType &compModel)
template<class CloudType >
static void writeFields (const CloudType &c)
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
template<class CloudType , class CompositionType >
static void readObjects (CloudType &c, const CompositionType &compModel, const objectRegistry &obr)
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
template<class CloudType , class CompositionType >
static void writeObjects (const CloudType &c, const CompositionType &compModel, objectRegistry &obr)
Static Public Attributes
static const std::size_t sizeofFields
Protected Attributes
scalar d0_
vector position0_
scalar sigma_
scalar mu_
scalar liquidCore_
scalar KHindex_
scalar y_
scalar yDot_
scalar tc_
scalar ms_
scalar injector_
scalar tMom_
scalar user_
Friends
Ostream & operator<< (Ostream &, const SprayParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::SprayParcel< ParcelType >
Reacting spray parcel, with added functionality for atomization and breakup.
Definition at line 54 of file SprayParcel.H.
Member Typedef Documentation
trackingData
template<class ParcelType > typedef ParcelType::trackingData trackingData
Definition at line 121 of file SprayParcel.H.
Constructor & Destructor Documentation
SprayParcel() [1/6]
template<class ParcelType > SprayParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti) inline
Definition at line 103 of file SprayParcelI.H.
SprayParcel() [2/6]
template<class ParcelType > SprayParcel (const polyMesh & mesh, const vector & position, const label celli) inline
Definition at line 130 of file SprayParcelI.H.
SprayParcel() [3/6]
template<class ParcelType > SprayParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & f0, const vector & angularMomentum0, const vector & torque0, const scalarField & Y0, const scalar liquidCore, const scalar KHindex, const scalar y, const scalar yDot, const scalar tc, const scalar ms, const scalar injector, const scalar tMom, const scalar user, const typename ParcelType::constantProperties & constProps) inline
Definition at line 155 of file SprayParcelI.H.
SprayParcel() [4/6]
template<class ParcelType > SprayParcel (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Definition at line 42 of file SprayParcelIO.C.
References IOstreamOption::ASCII, SprayParcel< ParcelType >::d0_, VectorSpace< Form, Cmpt, Ncmpts >::data(), FUNCTION_NAME, SprayParcel< ParcelType >::injector_, SprayParcel< ParcelType >::KHindex_, SprayParcel< ParcelType >::liquidCore_, SprayParcel< ParcelType >::ms_, SprayParcel< ParcelType >::mu_, VectorSpace< Form, Cmpt, Ncmpts >::nComponents, SprayParcel< ParcelType >::position0_, SprayParcel< ParcelType >::readFields(), Foam::readFields(), SprayParcel< ParcelType >::sigma_, SprayParcel< ParcelType >::sizeofFields, SprayParcel< ParcelType >::tc_, SprayParcel< ParcelType >::tMom_, SprayParcel< ParcelType >::user_, SprayParcel< ParcelType >::y_, and SprayParcel< ParcelType >::yDot_.
SprayParcel() [5/6]
template<class ParcelType > SprayParcel (const SprayParcel< ParcelType > & p, const polyMesh & mesh)
SprayParcel() [6/6]
template<class ParcelType > SprayParcel (const SprayParcel< ParcelType > & p)
Member Function Documentation
TypeName()
template<class ParcelType > TypeName ("SprayParcel< ParcelType >")
AddToPropertyList()
template<class ParcelType > AddToPropertyList (ParcelType , " d0"+" position0"+" sigma"+" mu"+" liquidCore"+" KHindex"+" y"+" yDot"+" tc"+" ms"+" injector"+" tMom"+" user")
clone() [1/2]
template<class ParcelType > virtual autoPtr< particle > clone () const inline virtual
Definition at line 272 of file SprayParcel.H.
clone() [2/2]
template<class ParcelType > virtual autoPtr< particle > clone (const polyMesh & mesh) const inline virtual
Definition at line 278 of file SprayParcel.H.
References mesh.
d0() [1/2]
template<class ParcelType > Foam::scalar d0 () const inline
Definition at line 238 of file SprayParcelI.H.
position0() [1/2]
template<class ParcelType > const Foam::vector & position0 () const inline
Definition at line 245 of file SprayParcelI.H.
sigma() [1/2]
template<class ParcelType > Foam::scalar sigma () const inline
Definition at line 252 of file SprayParcelI.H.
mu() [1/2]
template<class ParcelType > Foam::scalar mu () const inline
Definition at line 259 of file SprayParcelI.H.
liquidCore() [1/2]
template<class ParcelType > Foam::scalar liquidCore () const inline
Definition at line 266 of file SprayParcelI.H.
KHindex() [1/2]
template<class ParcelType > Foam::scalar KHindex () const inline
Definition at line 273 of file SprayParcelI.H.
y() [1/2]
template<class ParcelType > Foam::scalar y () const inline
Definition at line 280 of file SprayParcelI.H.
yDot() [1/2]
template<class ParcelType > Foam::scalar yDot () const inline
Definition at line 287 of file SprayParcelI.H.
tc() [1/2]
template<class ParcelType > Foam::scalar tc () const inline
Definition at line 294 of file SprayParcelI.H.
ms() [1/2]
template<class ParcelType > Foam::scalar ms () const inline
Definition at line 301 of file SprayParcelI.H.
injector() [1/2]
template<class ParcelType > Foam::scalar injector () const inline
Definition at line 308 of file SprayParcelI.H.
tMom() [1/2]
template<class ParcelType > Foam::scalar tMom () const inline
Definition at line 315 of file SprayParcelI.H.
user() [1/2]
template<class ParcelType > Foam::scalar user () const inline
Definition at line 322 of file SprayParcelI.H.
d0() [2/2]
template<class ParcelType > Foam::scalar & d0 () inline
Definition at line 329 of file SprayParcelI.H.
position0() [2/2]
template<class ParcelType > Foam::vector & position0 () inline
Definition at line 336 of file SprayParcelI.H.
sigma() [2/2]
template<class ParcelType > Foam::scalar & sigma () inline
Definition at line 343 of file SprayParcelI.H.
mu() [2/2]
template<class ParcelType > Foam::scalar & mu () inline
Definition at line 350 of file SprayParcelI.H.
liquidCore() [2/2]
template<class ParcelType > Foam::scalar & liquidCore () inline
Definition at line 357 of file SprayParcelI.H.
KHindex() [2/2]
template<class ParcelType > Foam::scalar & KHindex () inline
Definition at line 364 of file SprayParcelI.H.
y() [2/2]
template<class ParcelType > Foam::scalar & y () inline
Definition at line 371 of file SprayParcelI.H.
yDot() [2/2]
template<class ParcelType > Foam::scalar & yDot () inline
Definition at line 378 of file SprayParcelI.H.
tc() [2/2]
template<class ParcelType > Foam::scalar & tc () inline
Definition at line 385 of file SprayParcelI.H.
ms() [2/2]
template<class ParcelType > Foam::scalar & ms () inline
Definition at line 392 of file SprayParcelI.H.
injector() [2/2]
template<class ParcelType > Foam::scalar & injector () inline
Definition at line 399 of file SprayParcelI.H.
tMom() [2/2]
template<class ParcelType > Foam::scalar & tMom () inline
Definition at line 406 of file SprayParcelI.H.
user() [2/2]
template<class ParcelType > Foam::scalar & user () inline
Definition at line 413 of file SprayParcelI.H.
setCellValues()
template<class ParcelType > template<class TrackCloudType > void setCellValues (TrackCloudType & cloud, trackingData & td)
Definition at line 30 of file SprayParcel.C.
calcAtomization()
template<class ParcelType > template<class TrackCloudType > void calcAtomization (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 143 of file SprayParcel.C.
References composition, IOobject::db(), Foam::mag(), Foam::max(), Foam::min(), Foam::pos(), R, rho, Foam::constant::thermodynamic::RR, T, U, and Urel.
calcBreakup()
template<class ParcelType > template<class TrackCloudType > void calcBreakup (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 212 of file SprayParcel.C.
References g, Foam::mag(), UPstream::myProcNo(), p, R, Foam::Re(), Foam::constant::thermodynamic::RR, T, U, and Urel.
cellValueSourceCorrection()
template<class ParcelType > template<class TrackCloudType > void cellValueSourceCorrection (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 42 of file SprayParcel.C.
correctSurfaceValues()
template<class ParcelType > template<class TrackCloudType > void correctSurfaceValues (TrackCloudType & cloud, trackingData & td, const scalar T, const scalarField & Cs, scalar & rhos, scalar & mus, scalar & Pr, scalar & kappa)
calc()
template<class ParcelType > template<class TrackCloudType > void calc (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 55 of file SprayParcel.C.
References Foam::cbrt(), composition, Cp, Foam::pow3(), rho, rho0, rho1, T, T0, and X0().
chi() [1/2]
template<class ParcelType > template<class TrackCloudType > scalar chi (TrackCloudType & cloud, trackingData & td, const scalarField & X) const
solveTABEq()
template<class ParcelType > template<class TrackCloudType > void solveTABEq (TrackCloudType & cloud, trackingData & td, const scalar dt)
Definition at line 363 of file SprayParcel.C.
References Foam::cos(), e, Foam::exp(), rho, s(), Foam::sin(), Foam::sqrt(), y, and Foam::y0().
readFields() [1/2]
template<class ParcelType > template<class CloudType , class CompositionType > void readFields (CloudType & c, const CompositionType & compModel) static
Definition at line 125 of file SprayParcelIO.C.
References mu, IOobjectOption::MUST_READ, p, UPtrList< T >::size(), and y.
Referenced by SprayParcel< ParcelType >::SprayParcel().
readFields() [2/2]
template<class ParcelType > template<class CloudType > void readFields (CloudType & c) static
Definition at line 117 of file SprayParcelIO.C.
writeFields() [1/2]
template<class ParcelType > template<class CloudType , class CompositionType > void writeFields (const CloudType & c, const CompositionType & compModel) static
Definition at line 250 of file SprayParcelIO.C.
References mu, IOobjectOption::NO_READ, p, UPtrList< T >::size(), and y.
writeFields() [2/2]
template<class ParcelType > template<class CloudType > void writeFields (const CloudType & c) static
Definition at line 242 of file SprayParcelIO.C.
writeProperties()
template<class ParcelType > void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly) const
Definition at line 323 of file SprayParcelIO.C.
References os(), and writeProp.
readObjects() [1/2]
template<class ParcelType > template<class CloudType > void readObjects (CloudType & c, const objectRegistry & obr) static
Definition at line 357 of file SprayParcelIO.C.
readObjects() [2/2]
template<class ParcelType > template<class CloudType , class CompositionType > void readObjects (CloudType & c, const CompositionType & compModel, const objectRegistry & obr) static
Definition at line 381 of file SprayParcelIO.C.
References mu, p, UPtrList< T >::size(), and y.
writeObjects() [1/2]
template<class ParcelType > template<class CloudType > void writeObjects (const CloudType & c, objectRegistry & obr) static
Definition at line 369 of file SprayParcelIO.C.
writeObjects() [2/2]
template<class ParcelType > template<class CloudType , class CompositionType > void writeObjects (const CloudType & c, const CompositionType & compModel, objectRegistry & obr) static
Definition at line 430 of file SprayParcelIO.C.
References mu, p, UPtrList< T >::size(), and y.
chi() [2/2]
template<class ParcelType > template<class TrackCloudType > Foam::scalar chi (TrackCloudType & cloud, trackingData & td, const scalarField & X) const
Definition at line 321 of file SprayParcel.C.
References Foam::clamp(), composition, forAll, p0, T, and T0.
Friends And Related Symbol Documentation
operator<<
template<class ParcelType > Ostream & operator<< (Ostream & , const SprayParcel< ParcelType > &) friend
Member Data Documentation
d0_
template<class ParcelType > scalar d0_ protected
Definition at line 131 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::SprayParcel().
position0_
template<class ParcelType > vector position0_ protected
Definition at line 134 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::SprayParcel().
sigma_
template<class ParcelType > scalar sigma_ protected
Definition at line 137 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::SprayParcel().
mu_
template<class ParcelType > scalar mu_ protected
Definition at line 140 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::SprayParcel().
liquidCore_
template<class ParcelType > scalar liquidCore_ protected
Definition at line 143 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::SprayParcel().
KHindex_
template<class ParcelType > scalar KHindex_ protected
Definition at line 146 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::SprayParcel().
y_
template<class ParcelType > scalar y_ protected
Definition at line 149 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::SprayParcel().
yDot_
template<class ParcelType > scalar yDot_ protected
Definition at line 152 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::SprayParcel().
tc_
template<class ParcelType > scalar tc_ protected
Definition at line 155 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::SprayParcel().
ms_
template<class ParcelType > scalar ms_ protected
Definition at line 158 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::SprayParcel().
injector_
template<class ParcelType > scalar injector_ protected
Definition at line 162 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::SprayParcel().
tMom_
template<class ParcelType > scalar tMom_ protected
Definition at line 165 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::SprayParcel().
user_
template<class ParcelType > scalar user_ protected
Definition at line 168 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::SprayParcel().
sizeofFields
template<class ParcelType > const std::size_t sizeofFields static
Definition at line 176 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::SprayParcel().
The documentation for this class was generated from the following files:
src/lagrangian/spray/parcels/Templates/SprayParcel/SprayParcel.H
src/lagrangian/spray/parcels/Templates/SprayParcel/SprayParcel.C
src/lagrangian/spray/parcels/Templates/SprayParcel/SprayParcelI.H
src/lagrangian/spray/parcels/Templates/SprayParcel/SprayParcelIO.C