OpenFOAM: oldCyclicPolyPatch Class Reference
oldCyclicPolyPatch Class Reference
'old' style cyclic polyPatch with all faces in single patch. Does ordering but cannot be used to run. Writes 'type cyclic' so foamUpgradeCyclics can be run afterwards. Used to get cyclics from mesh converters that assume cyclics in single patch (e.g. fluent3DMeshToFoam)
#include <oldCyclicPolyPatch.H>
Public Member Functions
TypeName ("oldCyclic")
oldCyclicPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform=UNKNOWN)
oldCyclicPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
oldCyclicPolyPatch (const oldCyclicPolyPatch &, const polyBoundaryMesh &)
oldCyclicPolyPatch (const oldCyclicPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
virtual ~oldCyclicPolyPatch ()
virtual bool owner () const
virtual void transformPosition (pointField &l) const
virtual void transformPosition (point &, const label facei) const
virtual void calcGeometry (const primitivePatch &referPatch, const pointField &thisCtrs, const vectorField &thisAreas, const pointField &thisCc, const pointField &nbrCtrs, const vectorField &nbrAreas, const pointField &nbrCc)
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
virtual void write (Ostream &) const
Public Member Functions inherited from coupledPolyPatch
TypeName ("coupled")
coupledPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform)
coupledPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
coupledPolyPatch (const coupledPolyPatch &, const polyBoundaryMesh &bm)
coupledPolyPatch (const coupledPolyPatch &, const labelList &faceCells)
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
virtual ~coupledPolyPatch ()
virtual bool coupled () const
virtual bool neighbour () const
virtual transformType transform () const
virtual transformType & transform ()
virtual bool separated () const
virtual const vectorField & separation () const
virtual bool parallel () const
virtual const tensorField & forwardT () const
virtual const tensorField & reverseT () const
virtual const boolList & collocated () const
scalar matchTolerance () const
Public Member Functions inherited from polyPatch
TypeName ("patch")
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &physicalType, const wordList &inGroups)
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
polyPatch (const polyPatch &, const polyBoundaryMesh &)
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
polyPatch (const polyPatch &p)
polyPatch (const polyPatch &p, const labelList &faceCells)
virtual autoPtr< polyPatch > clone (const labelList &faceCells) const
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
virtual ~polyPatch ()
virtual void newInternalProcFaces (label &, label &) const
virtual const labelUList & nbrCells () const
virtual label neighbPolyPatchID () const
virtual refPtr< labelListList > mapCollocatedFaces () const
virtual bool masterImplicit () const
virtual word neighbRegionID () const
label offset () const noexcept
label start () const noexcept
labelRange range () const
const polyBoundaryMesh & boundaryMesh () const noexcept
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
template<class T >
const List< T >::subList patchSlice (const UList< T > &values) const
template<class T >
const List< T >::subList boundarySlice (const List< T > &values) const
template<class T >
const Field< T >::subField patchSlice (const Field< T > &values) const
const vectorField::subField faceCentres () const
const vectorField::subField faceAreas () const
tmp< vectorField > faceCellCentres () const
tmp< scalarField > areaFraction () const
const labelUList & faceCells () const
const labelList & meshEdges () const
virtual void clearAddressing ()
label whichFace (const label facei) const noexcept
virtual bool changeTopology () const
virtual bool setTopology (polyTopoChange &)
void operator= (const polyPatch &)
Public Member Functions inherited from patchIdentifier
patchIdentifier (const patchIdentifier &)=default
patchIdentifier & operator= (const patchIdentifier &)=default
virtual ~patchIdentifier ()=default
patchIdentifier ()
patchIdentifier (const word &name, const label index)
patchIdentifier (const word &name, const label index, const word &physicalType, const wordList &inGroups=wordList())
patchIdentifier (const word &name, const dictionary &dict, const label index)
patchIdentifier (const patchIdentifier &ident, const label index)
const word & name () const noexcept
word & name () noexcept
label index () const noexcept
label & index () noexcept
const word & physicalType () const noexcept
word & physicalType () noexcept
const wordList & inGroups () const noexcept
wordList & inGroups () noexcept
bool inGroup (const word &name) const
void write (Ostream &os) const
Public Member Functions inherited from PrimitivePatch< FaceList, PointField >
PrimitivePatch (const FaceList &faces, const PointField &points)
PrimitivePatch (FaceList &&faces, const PointField &points)
PrimitivePatch (FaceList &faces, PointField &points, const bool reuse)
PrimitivePatch (const PrimitivePatch< FaceList, PointField > &pp)
virtual ~PrimitivePatch ()
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
const Field< point_type > & points () const noexcept
label nFaces () const noexcept
label nPoints () const
label nEdges () const
const edgeList & edges () const
const edgeList::subList internalEdges () const
const edgeList::subList boundaryEdges () const
label nInternalEdges () const
label nBoundaryEdges () const
bool isInternalEdge (const label edgei) const
const labelList & boundaryPoints () const
const labelListList & faceFaces () const
const labelListList & edgeFaces () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointFaces () const
const List< face_type > & localFaces () const
labelList boundaryFaces () const
labelList uniqBoundaryFaces () const
const labelList & meshPoints () const
const Map< label > & meshPointMap () const
const Field< point_type > & localPoints () const
const labelList & localPointOrder () const
label whichPoint (const label gp) const
edge meshEdge (const label edgei) const
edge meshEdge (const edge &e) const
label findEdge (const edge &e) const
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
label meshEdge (const label edgei, const edgeList &allEdges, const labelListList &pointEdges) const
labelList meshEdges (const labelUList &edgeLabels, const edgeList &allEdges, const labelListList &pointEdges) const
const Field< point_type > & faceCentres () const
const Field< point_type > & faceAreas () const
const Field< scalar > & magFaceAreas () const
const Field< point_type > & faceNormals () const
const Field< point_type > & pointNormals () const
Pair< point_type > box () const
scalar sphere (const label facei) const
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
bool hasBoundaryPoints () const
bool hasEdges () const
bool hasFaceFaces () const
bool hasEdgeFaces () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointFaces () const
bool hasMeshPoints () const
bool hasMeshPointMap () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
const labelListList & edgeLoops () const
surfaceTopo surfaceType (labelHashSet *badEdgesPtr=nullptr) const
bool checkTopology (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
bool checkPointManifold (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
void operator= (const PrimitivePatch< FaceList, PointField > &rhs)
void operator= (PrimitivePatch< FaceList, PointField > &&rhs)
label whichEdge (const edge &e) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Public Member Functions inherited from PrimitivePatchBase
ClassName ("PrimitivePatch")
PrimitivePatchBase ()=default
Protected Member Functions
virtual void initGeometry (PstreamBuffers &)
virtual void calcGeometry (PstreamBuffers &)
virtual void initMovePoints (PstreamBuffers &, const pointField &)
virtual void movePoints (PstreamBuffers &, const pointField &)
virtual void initUpdateMesh (PstreamBuffers &)
virtual void updateMesh (PstreamBuffers &)
Protected Member Functions inherited from coupledPolyPatch
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr, const scalarField &smallDist, const scalar absTol, const transformType=UNKNOWN) const
Protected Member Functions inherited from polyPatch
virtual void clearGeom ()
virtual void movePoints (const Field< point_type > &)
Additional Inherited Members
Public Types inherited from coupledPolyPatch
enum transformType {
UNKNOWN , ROTATIONAL , TRANSLATIONAL , COINCIDENTFULLMATCH ,
NOORDERING
}
Public Types inherited from PrimitivePatch< FaceList, PointField >
enum surfaceTopo { MANIFOLD , OPEN , ILLEGAL }
typedef std::remove_reference< FaceList >::type::value_type face_type
typedef std::remove_reference< PointField >::type::value_type point_type
typedef FaceList FaceListType
typedef PointField PointFieldType
typedef face_type FaceType
Static Public Member Functions inherited from coupledPolyPatch
static scalarField calcFaceTol (const UList< face > &faces, const pointField &points, const pointField &faceCentres)
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
static bool constraintType (const word &patchType)
static wordList constraintTypes ()
Static Public Member Functions inherited from patchIdentifier
static word defaultName (const label n=-1)
Static Public Attributes inherited from coupledPolyPatch
static const Enum< transformType > transformTypeNames
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Static Protected Member Functions inherited from coupledPolyPatch
static void writeOBJ (Ostream &os, const point &pt)
static void writeOBJ (Ostream &, const pointField &, const labelList &)
static void writeOBJ (const fileName &, const UList< face > &, const pointField &)
static void writeOBJ (Ostream &os, const point &p0, const point &p1, label &vertI)
static pointField getAnchorPoints (const UList< face > &, const pointField &, const transformType)
static label getRotation (const pointField &points, const face &f, const point &anchor, const scalar tol)
Detailed Description
'old' style cyclic polyPatch with all faces in single patch. Does ordering but cannot be used to run. Writes 'type cyclic' so foamUpgradeCyclics can be run afterwards. Used to get cyclics from mesh converters that assume cyclics in single patch (e.g. fluent3DMeshToFoam)
Source files
oldCyclicPolyPatch.H
oldCyclicPolyPatch.C
Definition at line 50 of file oldCyclicPolyPatch.H.
Constructor & Destructor Documentation
oldCyclicPolyPatch() [1/4]
oldCyclicPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType, const transformType transform = UNKNOWN)
Definition at line 559 of file oldCyclicPolyPatch.C.
oldCyclicPolyPatch() [2/4]
oldCyclicPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Definition at line 578 of file oldCyclicPolyPatch.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, patchIdentifier::name(), coupledPolyPatch::ROTATIONAL, coupledPolyPatch::transform(), and coupledPolyPatch::TRANSLATIONAL.
oldCyclicPolyPatch() [3/4]
oldCyclicPolyPatch (const oldCyclicPolyPatch & pp, const polyBoundaryMesh & bm)
Definition at line 627 of file oldCyclicPolyPatch.C.
oldCyclicPolyPatch() [4/4]
oldCyclicPolyPatch (const oldCyclicPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart)
Definition at line 641 of file oldCyclicPolyPatch.C.
~oldCyclicPolyPatch()
~oldCyclicPolyPatch () virtual
Definition at line 660 of file oldCyclicPolyPatch.C.
Member Function Documentation
initGeometry()
void initGeometry (PstreamBuffers & pBufs) protected virtual
Implements coupledPolyPatch.
Definition at line 666 of file oldCyclicPolyPatch.C.
References polyPatch::initGeometry().
calcGeometry() [1/2]
void calcGeometry (PstreamBuffers & pBufs) protected virtual
Implements coupledPolyPatch.
Definition at line 685 of file oldCyclicPolyPatch.C.
initMovePoints()
void initMovePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Implements coupledPolyPatch.
Definition at line 689 of file oldCyclicPolyPatch.C.
References polyPatch::initMovePoints(), and p.
movePoints()
void movePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Implements coupledPolyPatch.
Definition at line 699 of file oldCyclicPolyPatch.C.
References polyPatch::movePoints(), and p.
initUpdateMesh()
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Implements coupledPolyPatch.
Definition at line 709 of file oldCyclicPolyPatch.C.
References polyPatch::initUpdateMesh().
updateMesh()
void updateMesh (PstreamBuffers & pBufs) protected virtual
Implements coupledPolyPatch.
Definition at line 715 of file oldCyclicPolyPatch.C.
References polyPatch::updateMesh().
TypeName()
TypeName ("oldCyclic")
clone() [1/2]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm) const inline virtual
Reimplemented from polyPatch.
Definition at line 213 of file oldCyclicPolyPatch.H.
clone() [2/2]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Reimplemented from polyPatch.
Definition at line 220 of file oldCyclicPolyPatch.H.
References patchIdentifier::index().
owner()
virtual bool owner () const inline virtual
Implements coupledPolyPatch.
Definition at line 245 of file oldCyclicPolyPatch.H.
References NotImplemented.
transformPosition() [1/2]
virtual void transformPosition (pointField & l) const inline virtual
Implements coupledPolyPatch.
Definition at line 252 of file oldCyclicPolyPatch.H.
References NotImplemented.
transformPosition() [2/2]
virtual void transformPosition (point & , const label facei) const inline virtual
Implements coupledPolyPatch.
Definition at line 258 of file oldCyclicPolyPatch.H.
References NotImplemented.
calcGeometry() [2/2]
void calcGeometry (const primitivePatch & referPatch, const pointField & thisCtrs, const vectorField & thisAreas, const pointField & thisCc, const pointField & nbrCtrs, const vectorField & nbrAreas, const pointField & nbrCc) virtual
Implements coupledPolyPatch.
Definition at line 672 of file oldCyclicPolyPatch.C.
initOrder()
void initOrder (PstreamBuffers & , const primitivePatch & pp) const virtual
Implements coupledPolyPatch.
Definition at line 721 of file oldCyclicPolyPatch.C.
order()
bool order (PstreamBuffers & , const primitivePatch & pp, labelList & faceMap, labelList & rotation) const virtual
Implements coupledPolyPatch.
Definition at line 733 of file oldCyclicPolyPatch.C.
References Foam::abort(), Foam::endl(), f(), Foam::faceMap(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::identity(), PrimitivePatch< FaceList, PointField >::localFaces(), Foam::matchPoints(), mesh, Foam::name(), path(), pFaces, PrimitivePatch< FaceList, PointField >::pointFaces(), PrimitivePatch< FaceList, PointField >::points(), Foam::Pout, pp(), SeriousErrorInFunction, List< T >::setSize(), and PtrList< T >::setSize().
write()
void write (Ostream & os) const virtual
Reimplemented from coupledPolyPatch.
Definition at line 1217 of file oldCyclicPolyPatch.C.
References Foam::endl(), os(), Foam::transform(), WarningInFunction, patchIdentifier::write(), and Ostream::writeEntry().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/oldCyclic/oldCyclicPolyPatch.H
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/oldCyclic/oldCyclicPolyPatch.C