OpenFOAM: ODESolver Class Reference
ODESolver Class Reference abstract
Numerics » Ordinary Differential Equation (ODE) solvers
Abstract base-class for ODE system solvers.
#include <ODESolver.H>
Classes
class stepState
Public Member Functions
TypeName ("ODESolver")
declareRunTimeSelectionTable (autoPtr, ODESolver, dictionary,(const ODESystem &ode, const dictionary &dict),(ode, dict))
ODESolver (const ODESystem &ode, const dictionary &dict)
ODESolver (const ODESystem &ode, const scalarField &absTol, const scalarField &relTol)
virtual ~ODESolver ()=default
label nEqns () const
scalarField & absTol ()
scalarField & relTol ()
virtual bool resize ()=0
template<class Type >
void resizeField (UList< Type > &f) const
void resizeMatrix (scalarSquareMatrix &m) const
virtual void solve (scalar &x, scalarField &y, scalar &dxTry) const
virtual void solve (scalar &x, scalarField &y, stepState &step) const
virtual void solve (const scalar xStart, const scalar xEnd, scalarField &y, scalar &dxEst) const
Static Public Member Functions
static autoPtr< ODESolver > New (const ODESystem &ode, const dictionary &dict)
template<class Type >
static void resizeField (UList< Type > &f, const label n)
Protected Member Functions
scalar normalizeError (const scalarField &y0, const scalarField &y, const scalarField &err) const
ODESolver (const ODESolver &)=delete
void operator= (const ODESolver &)=delete
Protected Attributes
const ODESystem & odes_
const label maxN_
label n_
scalarField absTol_
scalarField relTol_
label maxSteps_
Friends
class ODESystem
Detailed Description
Abstract base-class for ODE system solvers.
Source files
ODESolver.H
ODESolver.C
Definition at line 52 of file ODESolver.H.
Constructor & Destructor Documentation
ODESolver() [1/3]
ODESolver (const ODESolver &) protected delete
ODESolver() [2/3]
ODESolver (const ODESystem & ode, const dictionary & dict)
Definition at line 56 of file ODESolver.C.
ODESolver() [3/3]
ODESolver (const ODESystem & ode, const scalarField & absTol, const scalarField & relTol)
Definition at line 67 of file ODESolver.C.
~ODESolver()
virtual ~ODESolver () virtual default
Member Function Documentation
normalizeError()
Foam::scalar normalizeError (const scalarField & y0, const scalarField & y, const scalarField & err) const protected
Definition at line 35 of file ODESolver.C.
References ODESolver::absTol_, forAll, Foam::mag(), Foam::max(), ODESolver::relTol_, y, and Foam::y0().
operator=()
void operator= (const ODESolver &) protected delete
TypeName()
TypeName ("ODESolver")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , ODESolver , dictionary , (const ODESystem &ode, const dictionary &dict) , (ode, dict))
New()
Foam::autoPtr< Foam::ODESolver > New (const ODESystem & ode, const dictionary & dict) static
Definition at line 26 of file ODESolverNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
Referenced by thermoCoupleProbes::thermoCoupleProbes().
nEqns()
Foam::label nEqns () const inline
Definition at line 24 of file ODESolverI.H.
References ODESolver::n_.
absTol()
Foam::scalarField & absTol () inline
Definition at line 30 of file ODESolverI.H.
relTol()
Foam::scalarField & relTol () inline
Definition at line 36 of file ODESolverI.H.
resize()
bool resize () pure virtual
Implemented in Euler, EulerSI, RKCK45, RKDP45, RKF45, rodas23, rodas34, Rosenbrock12, Rosenbrock23, Rosenbrock34, seulex, SIBS, and Trapezoid.
Definition at line 85 of file ODESolver.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by Euler::resize(), EulerSI::resize(), RKCK45::resize(), RKDP45::resize(), RKF45::resize(), rodas23::resize(), rodas34::resize(), Rosenbrock12::resize(), Rosenbrock23::resize(), Rosenbrock34::resize(), seulex::resize(), SIBS::resize(), and Trapezoid::resize().
resizeField() [1/2]
template<class Type > void resizeField (UList< Type > & f, const label n) inline static
Definition at line 43 of file ODESolverI.H.
References UList< T >::begin(), f(), n, and List< T >::shallowCopy().
Referenced by adaptiveSolver::resize().
resizeField() [2/2]
template<class Type > void resizeField (UList< Type > & f) const inline
Definition at line 50 of file ODESolverI.H.
References f().
resizeMatrix()
void resizeMatrix (scalarSquareMatrix & m) const inline
Definition at line 56 of file ODESolverI.H.
References SquareMatrix< Type >::shallowResize().
solve() [1/3]
void solve (scalar & x, scalarField & y, scalar & dxTry) const virtual
Reimplemented in Euler, Euler, EulerSI, EulerSI, RKCK45, RKCK45, RKDP45, RKDP45, RKF45, RKF45, rodas23, rodas23, rodas34, rodas34, Rosenbrock12, Rosenbrock12, Rosenbrock23, Rosenbrock23, Rosenbrock34, Rosenbrock34, SIBS, Trapezoid, and Trapezoid.
Definition at line 109 of file ODESolver.C.
References ODESolver::stepState::dxTry, solve(), x, and y.
solve() [2/3]
void solve (scalar & x, scalarField & y, stepState & step) const virtual
Reimplemented in Euler, EulerSI, RKCK45, RKDP45, RKF45, rodas23, rodas34, Rosenbrock12, Rosenbrock23, Rosenbrock34, seulex, and Trapezoid.
Definition at line 122 of file ODESolver.C.
References ODESolver::stepState::dxDid, ODESolver::stepState::dxTry, solve(), x, and y.
solve() [3/3]
void solve (const scalar xStart, const scalar xEnd, scalarField & y, scalar & dxEst) const virtual
Reimplemented in Euler, EulerSI, RKCK45, RKDP45, RKF45, rodas23, rodas34, Rosenbrock12, Rosenbrock23, Rosenbrock34, and Trapezoid.
Definition at line 135 of file ODESolver.C.
References ODESolver::stepState::dxDid, ODESolver::stepState::dxTry, Foam::exit(), Foam::FatalError, FatalErrorInFunction, ODESolver::stepState::first, ODESolver::stepState::last, Foam::nl, ODESolver::stepState::prevReject, ODESolver::stepState::reject, solve(), x, and y.
Friends And Related Symbol Documentation
ODESystem
friend class ODESystem friend
Definition at line 97 of file ODESolver.H.
Member Data Documentation
odes_
const ODESystem& odes_ protected
Definition at line 60 of file ODESolver.H.
maxN_
const label maxN_ protected
Definition at line 63 of file ODESolver.H.
n_
label n_ mutable protected
Definition at line 66 of file ODESolver.H.
Referenced by ODESolver::nEqns().
absTol_
scalarField absTol_ protected
Definition at line 69 of file ODESolver.H.
Referenced by ODESolver::normalizeError().
relTol_
scalarField relTol_ protected
Definition at line 72 of file ODESolver.H.
Referenced by ODESolver::normalizeError().
maxSteps_
label maxSteps_ protected
Definition at line 75 of file ODESolver.H.
The documentation for this class was generated from the following files:
src/ODE/ODESolvers/ODESolver/ODESolver.H
src/ODE/ODESolvers/ODESolver/ODESolver.C
src/ODE/ODESolvers/ODESolver/ODESolverI.H
src/ODE/ODESolvers/ODESolver/ODESolverNew.C