OpenFOAM: topoSetCellSource Class Reference
topoSetCellSource Class Reference
The topoSetCellSource is a intermediate class for handling topoSet sources for selecting cells.
#include <topoSetCellSource.H>
Public Member Functions
declareRunTimeSelectionTable (autoPtr, topoSetCellSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetCellSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetCellSource (const polyMesh &mesh)
topoSetCellSource (const polyMesh &mesh, const dictionary &dict)
autoPtr< topoSetCellSource > clone () const
virtual ~topoSetCellSource ()=default
virtual topoSetSource::sourceType setType () const
Public Member Functions inherited from topoSetSource
TypeName ("topoSetSource")
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh, bool verbose=true)
topoSetSource (const polyMesh &mesh, const dictionary &dict)
autoPtr< topoSetSource > clone () const
virtual ~topoSetSource ()=default
const polyMesh & mesh () const noexcept
bool verbose () const noexcept
bool verbose (bool on) noexcept
void verbose (const dictionary &dict)
virtual void applyToSet (const topoSetSource::setAction action, topoSet &set) const =0
Static Public Member Functions
static autoPtr< topoSetCellSource > New (const word &sourceType, const polyMesh &mesh, const dictionary &dict)
static autoPtr< topoSetCellSource > New (const word &sourceType, const polyMesh &mesh, Istream &is)
Static Public Member Functions inherited from topoSetSource
static Istream & checkIs (Istream &is)
static bool isSetSource (const sourceType t) noexcept
static bool isZoneSource (const sourceType t) noexcept
static bool isCell (const sourceType t) noexcept
static bool isFace (const sourceType t) noexcept
static bool isPoint (const sourceType t) noexcept
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
static setAction toAction (const word &actionName)
Additional Inherited Members
Public Types inherited from topoSetSource
enum sourceType {
UNKNOWN_SOURCE = 0 , CELL_TYPE = 0x1 , FACE_TYPE = 0x2 , POINT_TYPE = 0x4 ,
SET_SOURCE = 0x10 , CELLSET_SOURCE = (CELL_TYPE | SET_SOURCE) , FACESET_SOURCE = (FACE_TYPE | SET_SOURCE) , POINTSET_SOURCE = (POINT_TYPE | SET_SOURCE) ,
ZONE_SOURCE = 0x20 , CELLZONE_SOURCE = (CELL_TYPE | ZONE_SOURCE) , FACEZONE_SOURCE = (FACE_TYPE | ZONE_SOURCE) , POINTZONE_SOURCE = (POINT_TYPE | ZONE_SOURCE) ,
CELLSETSOURCE = CELLSET_SOURCE , FACESETSOURCE = FACESET_SOURCE , POINTSETSOURCE = POINTSET_SOURCE , CELLZONESOURCE = CELLZONE_SOURCE ,
FACEZONESOURCE = FACEZONE_SOURCE , POINTZONESOURCE = POINTZONE_SOURCE
}
enum setAction {
ADD , SUBTRACT , NEW , SUBSET ,
INVERT , CLEAR , REMOVE , LIST ,
IGNORE , DELETE = SUBTRACT
}
Static Public Attributes inherited from topoSetSource
static const Enum< setAction > actionNames
static const Enum< setAction > combineNames
Protected Member Functions inherited from topoSetSource
void addOrDelete (topoSet &set, const label id, const bool add) const
void addOrDelete (topoSet &set, const labelUList &labels, const bool add) const
void addOrDelete (topoSet &set, const bitSet &labels, const bool add) const
topoSetSource (const topoSetSource &)=delete
void operator= (const topoSetSource &)=delete
Static Protected Member Functions inherited from topoSetSource
static bool check (labelList &list, const label maxLabel)
Protected Attributes inherited from topoSetSource
const polyMesh & mesh_
bool verbose_
Static Protected Attributes inherited from topoSetSource
static const string illegalSource_
static HashTable< string > * usageTablePtr_ = nullptr
Detailed Description
The topoSetCellSource is a intermediate class for handling topoSet sources for selecting cells.
The class is not an executable topoSet itself, yet a provider for common entries to its derived topoSet.
Source files
topoSetCellSource.H
topoSetCellSource.C
Definition at line 50 of file topoSetCellSource.H.
Constructor & Destructor Documentation
topoSetCellSource() [1/2]
topoSetCellSource (const polyMesh & mesh) explicit
Definition at line 35 of file topoSetCellSource.C.
topoSetCellSource() [2/2]
topoSetCellSource (const polyMesh & mesh, const dictionary & dict)
Definition at line 41 of file topoSetCellSource.C.
~topoSetCellSource()
virtual ~topoSetCellSource () virtual default
Member Function Documentation
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , topoSetCellSource , word , (const polyMesh &mesh, const dictionary &dict) , (mesh, dict))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , topoSetCellSource , istream , (const polyMesh &mesh, Istream &is) , (mesh, is))
clone()
autoPtr< topoSetCellSource > clone () const inline
Definition at line 95 of file topoSetCellSource.H.
References NotImplemented.
New() [1/2]
Foam::autoPtr< Foam::topoSetCellSource > New (const word & sourceType, const polyMesh & mesh, const dictionary & dict) static
Definition at line 54 of file topoSetCellSource.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and mesh.
Referenced by cellBitSet::select().
New() [2/2]
Foam::autoPtr< Foam::topoSetCellSource > New (const word & sourceType, const polyMesh & mesh, Istream & is) static
Definition at line 79 of file topoSetCellSource.C.
References Foam::exit(), Foam::FatalError, FatalErrorInLookup, and mesh.
setType()
virtual topoSetSource::sourceType setType () const inline virtual
Implements topoSetSource.
Definition at line 128 of file topoSetCellSource.H.
References topoSetSource::CELLSET_SOURCE.
The documentation for this class was generated from the following files:
src/meshTools/topoSet/cellSources/topoSetCellSource/topoSetCellSource.H
src/meshTools/topoSet/cellSources/topoSetCellSource/topoSetCellSource.C