OpenFOAM: TGaussSeidelSmoother< Type, DType, LUType > Class Template Reference
TGaussSeidelSmoother< Type, DType, LUType > Class Template Reference
Foam::TGaussSeidelSmoother.
#include <TGaussSeidelSmoother.H>
Public Member Functions
TypeName ("GaussSeidel")
TGaussSeidelSmoother (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix)
virtual void smooth (Field< Type > &psi, const label nSweeps) const
Public Member Functions inherited from LduMatrix< Type, DType, LUType >::smoother
virtual const word & type () const =0
declareRunTimeSelectionTable (autoPtr, smoother, symMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix),(fieldName, matrix))
declareRunTimeSelectionTable (autoPtr, smoother, asymMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix),(fieldName, matrix))
smoother (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix)
virtual ~smoother ()=default
const word & fieldName () const noexcept
const LduMatrix< Type, DType, LUType > & matrix () const noexcept
Static Public Member Functions
static void smooth (const word &fieldName, Field< Type > &psi, const LduMatrix< Type, DType, LUType > &matrix, const Field< DType > &rD, const label nSweeps)
Static Public Member Functions inherited from LduMatrix< Type, DType, LUType >::smoother
static autoPtr< smoother > New (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &smootherDict)
Additional Inherited Members
Protected Attributes inherited from LduMatrix< Type, DType, LUType >::smoother
word fieldName_
const LduMatrix< Type, DType, LUType > & matrix_
Detailed Description
template<class Type, class DType, class LUType>
class Foam::TGaussSeidelSmoother< Type, DType, LUType >
Foam::TGaussSeidelSmoother.
Source files
TGaussSeidelSmoother.H
TGaussSeidelSmoother.C
Definition at line 47 of file TGaussSeidelSmoother.H.
Constructor & Destructor Documentation
TGaussSeidelSmoother()
template<class Type , class DType , class LUType > TGaussSeidelSmoother (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix)
Definition at line 27 of file TGaussSeidelSmoother.C.
References UPtrList< T >::begin(), UList< T >::begin(), Foam::diag(), Foam::inv(), LduMatrix< Type, DType, LUType >::smoother::matrix(), and UPtrList< T >::size().
Member Function Documentation
TypeName()
template<class Type , class DType , class LUType > TypeName ("GaussSeidel")
smooth() [1/2]
template<class Type , class DType , class LUType > void smooth (const word & fieldName, Field< Type > & psi, const LduMatrix< Type, DType, LUType > & matrix, const Field< DType > & rD, const label nSweeps) static
Definition at line 54 of file TGaussSeidelSmoother.C.
References UPtrList< T >::begin(), Foam::dot(), UPstream::nRequests(), psi, and UPtrList< T >::size().
smooth() [2/2]
template<class Type , class DType , class LUType > void smooth (Field< Type > & psi, const label nSweeps) const virtual
Implements LduMatrix< Type, DType, LUType >::smoother.
Definition at line 148 of file TGaussSeidelSmoother.C.
References psi.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/Smoothers/GaussSeidel/TGaussSeidelSmoother.H
src/OpenFOAM/matrices/LduMatrix/Smoothers/GaussSeidel/TGaussSeidelSmoother.C