OpenFOAM: surfaceSlipDisplacementPointPatchVectorField Class Reference
surfaceSlipDisplacementPointPatchVectorField Class Reference
Displacement follows a triSurface. Use in a displacementMotionSolver as a bc on the pointDisplacement field. Following is done by calculating the projection onto the surface according to the projectMode.
#include <surfaceSlipDisplacementPointPatchVectorField.H>
Public Types
enum projectMode { NEAREST , POINTNORMAL , FIXEDNORMAL }
Public Types inherited from pointPatchField< vector >
typedef vector value_type
typedef DimensionedField< vector, pointMesh > Internal
typedef pointPatch Patch
typedef calculatedPointPatchField< vector > Calculated
Public Member Functions
TypeName ("surfaceSlipDisplacement")
surfaceSlipDisplacementPointPatchVectorField (const pointPatch &, const DimensionedField< vector, pointMesh > &)
surfaceSlipDisplacementPointPatchVectorField (const pointPatch &, const DimensionedField< vector, pointMesh > &, const dictionary &)
surfaceSlipDisplacementPointPatchVectorField (const surfaceSlipDisplacementPointPatchVectorField &, const pointPatch &, const DimensionedField< vector, pointMesh > &, const pointPatchFieldMapper &)
surfaceSlipDisplacementPointPatchVectorField (const surfaceSlipDisplacementPointPatchVectorField &)
virtual autoPtr< pointPatchVectorField > clone () const
surfaceSlipDisplacementPointPatchVectorField (const surfaceSlipDisplacementPointPatchVectorField &, const DimensionedField< vector, pointMesh > &)
virtual autoPtr< pointPatchVectorField > clone (const DimensionedField< vector, pointMesh > &iF) const
const searchableSurfaces & surfaces () const
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
virtual void write (Ostream &) const
Public Member Functions inherited from pointPatchField< vector >
declareRunTimeSelectionTable (autoPtr, pointPatchField, patch,(const pointPatch &p, const DimensionedField< vector, pointMesh > &iF),(p, iF))
declareRunTimeSelectionTable (autoPtr, pointPatchField, patchMapper,(const pointPatchField< vector > &ptf, const pointPatch &p, const DimensionedField< vector, pointMesh > &iF, const pointPatchFieldMapper &m),(dynamic_cast< const pointPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr, pointPatchField, dictionary,(const pointPatch &p, const DimensionedField< vector, pointMesh > &iF, const dictionary &dict),(p, iF, dict))
pointPatchField (const pointPatch &, const DimensionedField< vector, pointMesh > &)
pointPatchField (const pointPatch &, const DimensionedField< vector, pointMesh > &, const dictionary &)
pointPatchField (const pointPatchField< vector > &, const pointPatch &, const DimensionedField< vector, pointMesh > &, const pointPatchFieldMapper &)
pointPatchField (const pointPatchField< vector > &)
pointPatchField (const pointPatchField< vector > &, const DimensionedField< vector, pointMesh > &)
Foam::autoPtr< Foam::pointPatchField< vector > > NewCalculatedType (const pointPatchField< Type2 > &pf)
virtual ~pointPatchField ()=default
label size () const
const DimensionedField< vector, pointMesh > & internalField () const noexcept
const Field< vector > & primitiveField () const noexcept
tmp< Field< vector > > patchInternalField () const
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelUList &meshPoints) const
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelUList &meshPoints) const
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelUList &points) const
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelUList &meshPoints) const
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
virtual void autoMap (const pointPatchFieldMapper &)
virtual void rmap (const pointPatchField< vector > &, const labelList &)
virtual void updateCoeffs ()
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
virtual void operator= (const pointPatchField< vector > &)
virtual void operator= (const Field< vector > &)
virtual void operator= (const vector &)
virtual void operator+= (const pointPatchField< vector > &)
virtual void operator+= (const Field< vector > &)
virtual void operator+= (const vector &)
virtual void operator-= (const pointPatchField< vector > &)
virtual void operator-= (const Field< vector > &)
virtual void operator-= (const vector &)
virtual void operator*= (const pointPatchField< scalar > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator*= (const scalar)
virtual void operator/= (const pointPatchField< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator/= (const scalar)
virtual void operator== (const pointPatchField< vector > &)
virtual void operator== (const Field< vector > &)
virtual void operator== (const vector &)
void negate ()
void normalise ()
Public Member Functions inherited from pointPatchFieldBase
TypeName ("pointPatchField")
pointPatchFieldBase (const pointPatch &p)
pointPatchFieldBase (const pointPatch &p, const word &patchType)
pointPatchFieldBase (const pointPatch &p, const dictionary &dict)
pointPatchFieldBase (const pointPatchFieldBase &, const pointPatch &p)
pointPatchFieldBase (const pointPatchFieldBase &)
virtual ~pointPatchFieldBase ()=default
virtual bool fixesValue () const
virtual bool coupled () const
virtual const word & constraintType () const
const objectRegistry & db () const
const pointPatch & patch () const noexcept
const word & patchType () const noexcept
word & patchType () noexcept
bool updated () const noexcept
bool manipulatedMatrix () const noexcept
void checkPatch (const pointPatchFieldBase &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from pointPatchField< vector >
static autoPtr< pointPatchField< vector > > New (const word &patchFieldType, const pointPatch &p, const DimensionedField< vector, pointMesh > &iF)
static autoPtr< pointPatchField< vector > > New (const word &patchFieldType, const word &actualPatchType, const pointPatch &p, const DimensionedField< vector, pointMesh > &iF)
static autoPtr< pointPatchField< vector > > New (const pointPatchField< vector > &, const pointPatch &, const DimensionedField< vector, pointMesh > &, const pointPatchFieldMapper &)
static autoPtr< pointPatchField< vector > > New (const pointPatch &, const DimensionedField< vector, pointMesh > &, const dictionary &)
static autoPtr< pointPatchField< vector > > NewCalculatedType (const pointPatchField< Type2 > &)
Static Public Member Functions inherited from pointPatchFieldBase
static const word & emptyType () noexcept
static const word & calculatedType () noexcept
static const word & zeroGradientType () noexcept
Static Public Attributes inherited from pointPatchFieldBase
static int disallowGenericPatchField
Protected Member Functions inherited from pointPatchFieldBase
virtual void readDict (const dictionary &dict)
void setUpdated (bool state) noexcept
void setManipulated (bool state) noexcept
Detailed Description
Displacement follows a triSurface. Use in a displacementMotionSolver as a bc on the pointDisplacement field. Following is done by calculating the projection onto the surface according to the projectMode.
NEAREST : nearest
POINTNORMAL : intersection with point normal
FIXEDNORMAL : intersection with fixed vector
Optionally (intersection only) removes a component ("wedgePlane") to stay in 2D.
Needs:
geometry : dictionary with searchableSurfaces. (usually triSurfaceMeshes in constant/triSurface)
projectMode : see above
projectDirection : if projectMode = fixedNormal
wedgePlane : -1 or component to knock out of intersection normal
frozenPointsZone : empty or name of pointZone containing points that do not move
Source files
surfaceSlipDisplacementPointPatchVectorField.H
surfaceSlipDisplacementPointPatchVectorField.C
Definition at line 65 of file surfaceSlipDisplacementPointPatchVectorField.H.
Member Enumeration Documentation
projectMode
enum projectMode
Enumerator
NEAREST
POINTNORMAL
FIXEDNORMAL
Definition at line 74 of file surfaceSlipDisplacementPointPatchVectorField.H.
Constructor & Destructor Documentation
surfaceSlipDisplacementPointPatchVectorField() [1/5]
surfaceSlipDisplacementPointPatchVectorField (const pointPatch & p, const DimensionedField< vector, pointMesh > & iF)
Definition at line 283 of file surfaceSlipDisplacementPointPatchVectorField.C.
surfaceSlipDisplacementPointPatchVectorField() [2/5]
surfaceSlipDisplacementPointPatchVectorField (const pointPatch & p, const DimensionedField< vector, pointMesh > & iF, const dictionary & dict)
Definition at line 297 of file surfaceSlipDisplacementPointPatchVectorField.C.
surfaceSlipDisplacementPointPatchVectorField() [3/5]
surfaceSlipDisplacementPointPatchVectorField (const surfaceSlipDisplacementPointPatchVectorField & ppf, const pointPatch & p, const DimensionedField< vector, pointMesh > & iF, const pointPatchFieldMapper &)
Definition at line 314 of file surfaceSlipDisplacementPointPatchVectorField.C.
surfaceSlipDisplacementPointPatchVectorField() [4/5]
surfaceSlipDisplacementPointPatchVectorField (const surfaceSlipDisplacementPointPatchVectorField & ppf)
Definition at line 332 of file surfaceSlipDisplacementPointPatchVectorField.C.
surfaceSlipDisplacementPointPatchVectorField() [5/5]
surfaceSlipDisplacementPointPatchVectorField (const surfaceSlipDisplacementPointPatchVectorField & ppf, const DimensionedField< vector, pointMesh > & iF)
Definition at line 347 of file surfaceSlipDisplacementPointPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("surfaceSlipDisplacement")
clone() [1/2]
virtual autoPtr< pointPatchVectorField > clone () const inline virtual
Implements pointPatchField< vector >.
Definition at line 158 of file surfaceSlipDisplacementPointPatchVectorField.H.
clone() [2/2]
virtual autoPtr< pointPatchVectorField > clone (const DimensionedField< vector, pointMesh > & iF) const inline virtual
Implements pointPatchField< vector >.
Definition at line 177 of file surfaceSlipDisplacementPointPatchVectorField.H.
surfaces()
const Foam::searchableSurfaces & surfaces () const
Definition at line 366 of file surfaceSlipDisplacementPointPatchVectorField.C.
References IOobjectOption::MUST_READ, and IOobjectOption::NO_WRITE.
evaluate()
void evaluate (const Pstream::commsTypes commsType = Pstream::commsTypes::blocking) virtual
Reimplemented from pointPatchField< vector >.
Definition at line 393 of file surfaceSlipDisplacementPointPatchVectorField.C.
References pointPatchField< vector >::evaluate().
write()
void write (Ostream & os) const virtual
Reimplemented from pointPatchField< vector >.
Definition at line 413 of file surfaceSlipDisplacementPointPatchVectorField.C.
References word::null, os(), pointPatchField< Type >::write(), Ostream::writeEntry(), and Ostream::writeEntryIfDifferent().
The documentation for this class was generated from the following files:
src/fvMotionSolver/pointPatchFields/derived/surfaceSlipDisplacement/surfaceSlipDisplacementPointPatchVectorField.H
src/fvMotionSolver/pointPatchFields/derived/surfaceSlipDisplacement/surfaceSlipDisplacementPointPatchVectorField.C