OpenFOAM: surfaceWriter Class Reference
surfaceWriter Class Reference abstract
Base class for surface writers.
#include <surfaceWriter.H>
Public Member Functions
TypeName ("surfaceWriter")
declareRunTimeSelectionTable (autoPtr, surfaceWriter, word,(),())
declareRunTimeSelectionTable (autoPtr, surfaceWriter, wordDict,(const dictionary &writeOpts),(writeOpts))
surfaceWriter ()
surfaceWriter (const dictionary &options)
virtual ~surfaceWriter ()
virtual bool enabled () const
virtual bool separateGeometry () const
virtual bool usesFaceIds () const
virtual bool needsUpdate () const
virtual bool wroteData () const
virtual bool expire ()
virtual void clear ()
virtual void setSurface (const meshedSurf &surf, bool parallel)
virtual void setSurface (const pointField &points, const faceList &faces, bool parallel)
virtual void setSurface (const meshedSurf &surf)
virtual void setSurface (const pointField &points, const faceList &faces)
bool is_open () const noexcept
bool hasSurface () const
bool empty () const
label size () const
label nFields () const noexcept
label nFields (const label n) noexcept
bool isPointData () const noexcept
bool isPointData (const bool on) noexcept
bool useTimeDir () const noexcept
bool useTimeDir (const bool on) noexcept
bool verbose () const noexcept
bool verbose (const bool on) noexcept
scalar mergeDim () const noexcept
scalar mergeDim (const scalar dist) noexcept
scalar scale () const noexcept
scalar scale (const scalar factor) noexcept
const coordSystem::cartesian & transform () const noexcept
bool hasTime () const
const word & timeName () const
scalar timeValue () const
void setTime (const instant &inst)
void setTime (scalar timeValue)
void setTime (scalar timeValue, const word &timeName)
void unsetTime ()
virtual void beginTime (const Time &t)
virtual void beginTime (const instant &inst)
virtual void endTime ()
virtual void open (const fileName &outputPath)
virtual void open (const pointField &points, const faceList &faces, const fileName &outputPath, bool parallel)
virtual void open (const meshedSurf &surf, const fileName &outputPath, bool parallel)
virtual void open (const pointField &points, const faceList &faces, const fileName &outputPath)
virtual void open (const meshedSurf &surf, const fileName &outputPath)
virtual void close ()
virtual fileName write ()=0
virtual fileName write (const word &fieldName, const Field< label > &values)=0
Write field of label (per face or vertex)
virtual fileName write (const word &fieldName, const Field< scalar > &values)=0
Write field of scalar (per face or vertex)
virtual fileName write (const word &fieldName, const Field< vector > &values)=0
Write field of vector (per face or vertex)
virtual fileName write (const word &fieldName, const Field< sphericalTensor > &values)=0
Write field of sphericalTensor (per face or vertex)
virtual fileName write (const word &fieldName, const Field< symmTensor > &values)=0
Write field of symmTensor (per face or vertex)
virtual fileName write (const word &fieldName, const Field< tensor > &values)=0
Write field of tensor (per face or vertex)
virtual InfoProxy< surfaceWriter > info () const noexcept
template<class Type >
Foam::tmp< Foam::Field< Type > > mergeFieldTemplate (const Field< Type > &fld) const
template<class Type >
Foam::tmp< Foam::Field< Type > > adjustFieldTemplate (const word &fieldName, const tmp< Field< Type > > &tfield) const
Static Public Member Functions
static dictionary formatOptions (const dictionary &dict, const word &formatName, const word &entryName="formatOptions")
static dictionary formatOptions (const dictionary &dict, const dictionary &surfDict, const word &formatName, const word &entryName="formatOptions")
static bool supportedType (const word &writeType)
static autoPtr< surfaceWriter > New (const word &writeType)
static autoPtr< surfaceWriter > New (const word &writeType, const dictionary &writeOptions)
Static Public Attributes
static scalar defaultMergeDim = 1e-8
Protected Member Functions
void checkOpen () const
virtual bool merge () const
const meshedSurf & surface () const
const meshedSurfRef & adjustSurface () const
template<class Type >
tmp< Field< Type > > mergeFieldTemplate (const Field< Type > &fld) const
template<class Type >
tmp< Field< Type > > adjustFieldTemplate (const word &fieldName, const tmp< Field< Type > > &tfield) const
tmp< Field< label > > mergeField (const Field< label > &fld) const
tmp< Field< label > > adjustField (const word &fieldName, const tmp< Field< label > > &tfield) const
tmp< Field< scalar > > mergeField (const Field< scalar > &fld) const
tmp< Field< scalar > > adjustField (const word &fieldName, const tmp< Field< scalar > > &tfield) const
tmp< Field< vector > > mergeField (const Field< vector > &fld) const
tmp< Field< vector > > adjustField (const word &fieldName, const tmp< Field< vector > > &tfield) const
tmp< Field< sphericalTensor > > mergeField (const Field< sphericalTensor > &fld) const
tmp< Field< sphericalTensor > > adjustField (const word &fieldName, const tmp< Field< sphericalTensor > > &tfield) const
tmp< Field< symmTensor > > mergeField (const Field< symmTensor > &fld) const
tmp< Field< symmTensor > > adjustField (const word &fieldName, const tmp< Field< symmTensor > > &tfield) const
tmp< Field< tensor > > mergeField (const Field< tensor > &fld) const
tmp< Field< tensor > > adjustField (const word &fieldName, const tmp< Field< tensor > > &tfield) const
template<class Type >
fileName writeTemplate (const word &fieldName, const Field< Type > &localValues)
Protected Attributes
meshedSurfRef surf_
mergedSurf mergedSurf_
meshedSurfRef adjustedSurf_
scalar mergeDim_
scalar geometryScale_
point geometryCentre_
coordSystem::cartesian geometryTransform_
bool upToDate_
bool wroteGeom_
bool parallel_
bool useTimeDir_
bool isPointData_
bool verbose_
UPstream::commsTypes commType_
label nFields_
instant currTime_
fileName outputPath_
dictionary fieldLevel_
dictionary fieldScale_
Friends
Ostream & operator<< (Ostream &os, const InfoProxy< surfaceWriter > &iproxy)
Detailed Description
Base class for surface writers.
The surfaceWriter interface is rather large since we need a writer that can either be initially defined without a surface association and have that added at a later stage, or be defined with a surface association.
formatOptions
{
    default
    {
        verbose     true;
        commsType   scheduled;
        fieldLevel
        {
            "p.*"   1e5;    // Absolute -> gauge [Pa]
            T       273.15; // [K] -> [C]
            U       #eval{ 10/sqrt(3) };  // Uniform magU=10
        }
    }
    someFormat // Eg, ensight, vtk, etc
    {
        fieldScale
        {
            "p.*"   0.01;   // [Pa] -> [mbar]
        }
        scale   1000;  // [m] -> [mm]
        transform
        {
            origin  (0 0 0);
            rotationCentre  (0 0 0);
            rotation axisAngle;
            axis    (1 0 0);
            angle   45;
        }
    }
}
Format options:
Property Description Reqd Default
verbose Additional output verbosity no no
commsType Communication type no scheduled
scale Output geometry scaling no 1
transform Output coordinate transform no
fieldLevel Subtract field level before scaling no empty dict
fieldScale Output field scaling no empty dict
Note
The transform sub-dictionary also supports a rotationCentre keyword which applies untranslate by that amount prior to the rotation, and subsequently followed by a translate.
For surface formats that require geometry in a separate file, it is the responsibility of the implementation (not the caller) to ensure that this occurs.
Source files
surfaceWriter.H
surfaceWriter.C
surfaceWriterI.H
Definition at line 172 of file surfaceWriter.H.
Constructor & Destructor Documentation
surfaceWriter() [1/2]
surfaceWriter ()
Definition at line 156 of file surfaceWriter.C.
References surfaceWriter::close().
surfaceWriter() [2/2]
surfaceWriter (const dictionary & options) explicit
Definition at line 182 of file surfaceWriter.C.
References coordinateSystem::clear(), UPstream::commsTypeNames, surfaceWriter::commType_, Foam::endl(), surfaceWriter::fieldLevel_, surfaceWriter::fieldScale_, dictionary::findDict(), surfaceWriter::geometryCentre_, surfaceWriter::geometryScale_, surfaceWriter::geometryTransform_, Foam::Info, surfaceWriter::isPointData(), IOobjectOption::LAZY_READ, keyType::LITERAL, dictionary::readIfPresent(), dictionary::subOrEmptyDict(), surfaceWriter::verbose_, and Foam::Zero.
~surfaceWriter()
~surfaceWriter () virtual
Definition at line 222 of file surfaceWriter.C.
Member Function Documentation
checkOpen()
void checkOpen () const protected
Definition at line 442 of file surfaceWriter.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and Foam::type().
Referenced by rawWriter::writeTemplate().
merge()
bool merge () const protected virtual
Definition at line 453 of file surfaceWriter.C.
References PtrList< T >::clear(), and UPstream::parRun().
Referenced by debugWriter::mergeField().
surface()
const Foam::meshedSurf & surface () const protected
Definition at line 483 of file surfaceWriter.C.
References UPstream::parRun().
adjustSurface()
const Foam::meshedSurfRef & adjustSurface () const protected
Definition at line 496 of file surfaceWriter.C.
References PtrList< T >::clear(), and Foam::magSqr().
Referenced by rawWriter::writeTemplate().
mergeFieldTemplate() [1/2]
template<class Type > tmp< Field< Type > > mergeFieldTemplate (const Field< Type > & fld) const protected
adjustFieldTemplate() [1/2]
template<class Type > tmp< Field< Type > > adjustFieldTemplate (const word & fieldName, const tmp< Field< Type > > & tfield) const protected
mergeField() [1/6]
tmp< Field< label > > mergeField (const Field< label > & fld) const protected
Referenced by rawWriter::writeTemplate().
adjustField() [1/6]
tmp< Field< label > > adjustField (const word & fieldName, const tmp< Field< label > > & tfield) const protected
Referenced by rawWriter::writeTemplate().
mergeField() [2/6]
tmp< Field< scalar > > mergeField (const Field< scalar > & fld) const protected
adjustField() [2/6]
tmp< Field< scalar > > adjustField (const word & fieldName, const tmp< Field< scalar > > & tfield) const protected
mergeField() [3/6]
Foam::tmp< Foam::Field< Foam::vector > > mergeField (const Field< vector > & fld) const protected
Definition at line 727 of file surfaceWriter.C.
adjustField() [3/6]
Foam::tmp< Foam::Field< Foam::vector > > adjustField (const word & fieldName, const tmp< Field< vector > > & tfield) const protected
Definition at line 727 of file surfaceWriter.C.
mergeField() [4/6]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > mergeField (const Field< sphericalTensor > & fld) const protected
Definition at line 728 of file surfaceWriter.C.
adjustField() [4/6]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > adjustField (const word & fieldName, const tmp< Field< sphericalTensor > > & tfield) const protected
Definition at line 728 of file surfaceWriter.C.
mergeField() [5/6]
Foam::tmp< Foam::Field< Foam::symmTensor > > mergeField (const Field< symmTensor > & fld) const protected
Definition at line 729 of file surfaceWriter.C.
adjustField() [5/6]
Foam::tmp< Foam::Field< Foam::symmTensor > > adjustField (const word & fieldName, const tmp< Field< symmTensor > > & tfield) const protected
Definition at line 729 of file surfaceWriter.C.
mergeField() [6/6]
Foam::tmp< Foam::Field< Foam::tensor > > mergeField (const Field< tensor > & fld) const protected
Definition at line 730 of file surfaceWriter.C.
adjustField() [6/6]
Foam::tmp< Foam::Field< Foam::tensor > > adjustField (const word & fieldName, const tmp< Field< tensor > > & tfield) const protected
Definition at line 730 of file surfaceWriter.C.
writeTemplate()
template<class Type > fileName writeTemplate (const word & fieldName, const Field< Type > & localValues) inline protected
Parameters
fieldName Name of field
localValues Local field values to write
Definition at line 293 of file surfaceWriter.H.
References fileName::null, surfaceWriter::write(), and surfaceWriter::wroteGeom_.
TypeName()
TypeName ("surfaceWriter")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , surfaceWriter , word , () , ())
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , surfaceWriter , wordDict , (const dictionary &writeOpts) , (writeOpts))
formatOptions() [1/2]
Foam::dictionary formatOptions (const dictionary & dict, const word & formatName, const word & entryName = "formatOptions") static
Definition at line 56 of file surfaceWriter.C.
References dict, and Foam::fileFormats::getFormatOptions().
Referenced by Curle::read(), surfaceFieldValue::read(), areaWrite::read(), surfaceNoise::read(), propellerInfo::setSampleDiskSurface(), FacePostProcessing< CloudType >::write(), and ParticleCollector< CloudType >::write().
formatOptions() [2/2]
Foam::dictionary formatOptions (const dictionary & dict, const dictionary & surfDict, const word & formatName, const word & entryName = "formatOptions") static
Definition at line 67 of file surfaceWriter.C.
References dict, and Foam::fileFormats::getFormatOptions().
supportedType()
bool supportedType (const word & writeType) static
Definition at line 45 of file surfaceWriter.C.
New() [1/2]
Foam::autoPtr< Foam::surfaceWriter > New (const word & writeType) static
Definition at line 80 of file surfaceWriter.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), Foam::nl, and MeshedSurfaceProxy< Face >::writeTypes().
Referenced by debugWriter::mergeField(), averageNeighbourFvGeometryScheme::movePoints(), Curle::read(), surfaceFieldValue::read(), areaWrite::read(), surfaceNoise::read(), propellerInfo::setSampleDiskSurface(), FacePostProcessing< CloudType >::write(), and ParticleCollector< CloudType >::write().
New() [2/2]
Foam::autoPtr< Foam::surfaceWriter > New (const word & writeType, const dictionary & writeOptions) static
Definition at line 110 of file surfaceWriter.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and MeshedSurfaceProxy< Face >::writeTypes().
enabled()
virtual bool enabled () const inline virtual
Reimplemented in nullWriter.
Definition at line 397 of file surfaceWriter.H.
separateGeometry()
virtual bool separateGeometry () const inline virtual
Reimplemented in ensightWriter, foamWriter, proxyWriter, and starcdWriter.
Definition at line 403 of file surfaceWriter.H.
usesFaceIds()
virtual bool usesFaceIds () const inline virtual
Reimplemented in abaqusWriter, nastranWriter, and starcdWriter.
Definition at line 411 of file surfaceWriter.H.
needsUpdate()
bool needsUpdate () const virtual
Reimplemented in nullWriter.
Definition at line 392 of file surfaceWriter.C.
wroteData()
bool wroteData () const virtual
Reimplemented in nullWriter.
Definition at line 398 of file surfaceWriter.C.
expire()
bool expire () virtual
Definition at line 404 of file surfaceWriter.C.
References PtrList< T >::clear().
clear()
void clear () virtual
Definition at line 340 of file surfaceWriter.C.
setSurface() [1/4]
void setSurface (const meshedSurf & surf, bool parallel) virtual
Reimplemented in nullWriter.
Definition at line 348 of file surfaceWriter.C.
References UPstream::parRun().
setSurface() [2/4]
void setSurface (const pointField & points, const faceList & faces, bool parallel) virtual
Reimplemented in nullWriter.
Definition at line 360 of file surfaceWriter.C.
References UPstream::parRun(), and points.
setSurface() [3/4]
void setSurface (const meshedSurf & surf) virtual
Definition at line 373 of file surfaceWriter.C.
setSurface() [4/4]
void setSurface (const pointField & points, const faceList & faces) virtual
Definition at line 382 of file surfaceWriter.C.
References points.
is_open()
bool is_open () const inline noexcept
Definition at line 23 of file surfaceWriterI.H.
References surfaceWriter::outputPath_.
hasSurface()
bool hasSurface () const
Definition at line 420 of file surfaceWriter.C.
empty()
bool empty () const
Definition at line 426 of file surfaceWriter.C.
References UPtrList< T >::empty(), and Foam::returnReduceAnd().
Referenced by rawWriter::writeTemplate().
size()
Foam::label size () const
Definition at line 434 of file surfaceWriter.C.
References Foam::returnReduce(), and UPtrList< T >::size().
nFields() [1/2]
Foam::label nFields () const inline noexcept
Definition at line 29 of file surfaceWriterI.H.
nFields() [2/2]
Foam::label nFields (const label n) inline noexcept
Definition at line 35 of file surfaceWriterI.H.
References n.
isPointData() [1/2]
bool isPointData () const inline noexcept
Definition at line 43 of file surfaceWriterI.H.
Referenced by debugWriter::debugWriter(), debugWriter::mergeField(), surfaceWriter::surfaceWriter(), and rawWriter::writeTemplate().
isPointData() [2/2]
bool isPointData (const bool on) inline noexcept
Definition at line 49 of file surfaceWriterI.H.
useTimeDir() [1/2]
bool useTimeDir () const inline noexcept
Definition at line 57 of file surfaceWriterI.H.
Referenced by rawWriter::writeTemplate().
useTimeDir() [2/2]
bool useTimeDir (const bool on) inline noexcept
Definition at line 63 of file surfaceWriterI.H.
verbose() [1/2]
bool verbose () const inline noexcept
Definition at line 71 of file surfaceWriterI.H.
verbose() [2/2]
bool verbose (const bool on) inline noexcept
Definition at line 77 of file surfaceWriterI.H.
mergeDim() [1/2]
Foam::scalar mergeDim () const inline noexcept
Definition at line 85 of file surfaceWriterI.H.
mergeDim() [2/2]
Foam::scalar mergeDim (const scalar dist) inline noexcept
Definition at line 91 of file surfaceWriterI.H.
scale() [1/2]
Foam::scalar scale () const inline noexcept
Definition at line 99 of file surfaceWriterI.H.
scale() [2/2]
Foam::scalar scale (const scalar factor) inline noexcept
Definition at line 105 of file surfaceWriterI.H.
transform()
const Foam::coordSystem::cartesian & transform () const inline noexcept
Definition at line 115 of file surfaceWriterI.H.
hasTime()
bool hasTime () const inline
Definition at line 121 of file surfaceWriterI.H.
References UPtrList< T >::size().
timeName()
const Foam::word & timeName () const inline
Definition at line 127 of file surfaceWriterI.H.
Referenced by rawWriter::writeTemplate().
timeValue()
Foam::scalar timeValue () const inline
Definition at line 133 of file surfaceWriterI.H.
References UPtrList< T >::empty().
setTime() [1/3]
void setTime (const instant & inst)
Definition at line 230 of file surfaceWriter.C.
setTime() [2/3]
void setTime (scalar timeValue)
Definition at line 236 of file surfaceWriter.C.
setTime() [3/3]
void setTime (scalar timeValue, const word & timeName)
Definition at line 242 of file surfaceWriter.C.
References timeName.
unsetTime()
void unsetTime ()
Definition at line 249 of file surfaceWriter.C.
References PtrList< T >::clear().
beginTime() [1/2]
void beginTime (const Time & t) virtual
Reimplemented in vtkWriter.
Definition at line 256 of file surfaceWriter.C.
References setTime(), Time::timeName(), and dimensioned< Type >::value().
Referenced by vtkWriter::beginTime(), and vtkWriter::beginTime().
beginTime() [2/2]
void beginTime (const instant & inst) virtual
Reimplemented in vtkWriter.
Definition at line 262 of file surfaceWriter.C.
References setTime().
endTime()
void endTime () virtual
Reimplemented in vtkWriter.
Definition at line 268 of file surfaceWriter.C.
Referenced by vtkWriter::endTime().
open() [1/5]
void open (const fileName & outputPath) virtual
Reimplemented in nullWriter.
Definition at line 274 of file surfaceWriter.C.
Referenced by abaqusWriter::abaqusWriter(), abaqusWriter::abaqusWriter(), boundaryDataWriter::boundaryDataWriter(), boundaryDataWriter::boundaryDataWriter(), debugWriter::debugWriter(), debugWriter::debugWriter(), ensightWriter::ensightWriter(), ensightWriter::ensightWriter(), foamWriter::foamWriter(), foamWriter::foamWriter(), nastranWriter::nastranWriter(), nastranWriter::nastranWriter(), proxyWriter::proxyWriter(), proxyWriter::proxyWriter(), rawWriter::rawWriter(), rawWriter::rawWriter(), starcdWriter::starcdWriter(), starcdWriter::starcdWriter(), vtkWriter::vtkWriter(), vtkWriter::vtkWriter(), NURBS3DSurface::writeVTK(), x3dWriter::x3dWriter(), and x3dWriter::x3dWriter().
open() [2/5]
void open (const pointField & points, const faceList & faces, const fileName & outputPath, bool parallel) virtual
Definition at line 294 of file surfaceWriter.C.
References points.
open() [3/5]
void open (const meshedSurf & surf, const fileName & outputPath, bool parallel) virtual
Definition at line 281 of file surfaceWriter.C.
open() [4/5]
void open (const pointField & points, const faceList & faces, const fileName & outputPath) virtual
Definition at line 320 of file surfaceWriter.C.
References points.
open() [5/5]
void open (const meshedSurf & surf, const fileName & outputPath) virtual
Definition at line 308 of file surfaceWriter.C.
close()
void close () virtual
Reimplemented in ensightWriter, and vtkWriter.
Definition at line 333 of file surfaceWriter.C.
References PtrList< T >::clear().
Referenced by ensightWriter::close(), vtkWriter::close(), and surfaceWriter::surfaceWriter().
write() [1/7]
virtual fileName write () pure virtual
Implemented in abaqusWriter, boundaryDataWriter, debugWriter, ensightWriter, foamWriter, nastranWriter, nullWriter, proxyWriter, rawWriter, starcdWriter, vtkWriter, and x3dWriter.
Referenced by surfaceWriter::writeTemplate().
write() [2/7]
virtual fileName write (const word & fieldName, const Field< label > & values) pure virtual
Write field of label (per face or vertex)
Parameters
fieldName Name of field
values Field values to write
write() [3/7]
virtual fileName write (const word & fieldName, const Field< scalar > & values) pure virtual
Write field of scalar (per face or vertex)
Parameters
fieldName Name of field
values Field values to write
write() [4/7]
virtual fileName write (const word & fieldName, const Field< vector > & values) pure virtual
Write field of vector (per face or vertex)
Parameters
fieldName Name of field
values Field values to write
write() [5/7]
virtual fileName write (const word & fieldName, const Field< sphericalTensor > & values) pure virtual
Write field of sphericalTensor (per face or vertex)
Parameters
fieldName Name of field
values Field values to write
write() [6/7]
virtual fileName write (const word & fieldName, const Field< symmTensor > & values) pure virtual
Write field of symmTensor (per face or vertex)
Parameters
fieldName Name of field
values Field values to write
write() [7/7]
virtual fileName write (const word & fieldName, const Field< tensor > & values) pure virtual
Write field of tensor (per face or vertex)
Parameters
fieldName Name of field
values Field values to write
info()
virtual InfoProxy< surfaceWriter > info () const inline virtual noexcept
Definition at line 647 of file surfaceWriter.H.
mergeFieldTemplate() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > mergeFieldTemplate (const Field< Type > & fld) const
Definition at line 554 of file surfaceWriter.C.
References fld(), Foam::inplaceReorder(), UPstream::master(), UPstream::msgType(), Foam::New(), UPstream::parRun(), PtrList< T >::resize(), UPtrList< T >::size(), and UPstream::worldComm.
adjustFieldTemplate() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > adjustFieldTemplate (const word & fieldName, const tmp< Field< Type > > & tfield) const
Definition at line 609 of file surfaceWriter.C.
References Foam::equal(), Foam::Info, keyType::REGEX, Foam::setComponent(), and Foam::transform().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const InfoProxy< surfaceWriter > & iproxy) friend
Member Data Documentation
surf_
meshedSurfRef surf_ protected
Definition at line 179 of file surfaceWriter.H.
mergedSurf_
mergedSurf mergedSurf_ mutable protected
Definition at line 182 of file surfaceWriter.H.
Referenced by debugWriter::mergeField().
adjustedSurf_
meshedSurfRef adjustedSurf_ mutable protected
Definition at line 185 of file surfaceWriter.H.
mergeDim_
scalar mergeDim_ protected
Definition at line 188 of file surfaceWriter.H.
geometryScale_
scalar geometryScale_ protected
Definition at line 191 of file surfaceWriter.H.
Referenced by surfaceWriter::surfaceWriter().
geometryCentre_
point geometryCentre_ protected
Definition at line 194 of file surfaceWriter.H.
Referenced by surfaceWriter::surfaceWriter().
geometryTransform_
coordSystem::cartesian geometryTransform_ protected
Definition at line 197 of file surfaceWriter.H.
Referenced by surfaceWriter::surfaceWriter().
upToDate_
bool upToDate_ mutable protected
Definition at line 205 of file surfaceWriter.H.
Referenced by debugWriter::mergeField().
wroteGeom_
bool wroteGeom_ mutable protected
Definition at line 208 of file surfaceWriter.H.
Referenced by surfaceWriter::writeTemplate(), and rawWriter::writeTemplate().
parallel_
bool parallel_ protected
Definition at line 211 of file surfaceWriter.H.
Referenced by debugWriter::mergeField(), and rawWriter::writeTemplate().
useTimeDir_
bool useTimeDir_ protected
Definition at line 214 of file surfaceWriter.H.
isPointData_
bool isPointData_ protected
Definition at line 217 of file surfaceWriter.H.
verbose_
bool verbose_ protected
Definition at line 220 of file surfaceWriter.H.
Referenced by surfaceWriter::surfaceWriter(), rawWriter::writeTemplate(), and x3dWriter::x3dWriter().
commType_
UPstream::commsTypes commType_ protected
Definition at line 223 of file surfaceWriter.H.
Referenced by debugWriter::debugWriter(), debugWriter::mergeField(), and surfaceWriter::surfaceWriter().
nFields_
label nFields_ protected
Definition at line 226 of file surfaceWriter.H.
currTime_
instant currTime_ protected
Definition at line 229 of file surfaceWriter.H.
outputPath_
fileName outputPath_ protected
Definition at line 232 of file surfaceWriter.H.
Referenced by surfaceWriter::is_open(), and rawWriter::writeTemplate().
fieldLevel_
dictionary fieldLevel_ protected
Definition at line 235 of file surfaceWriter.H.
Referenced by surfaceWriter::surfaceWriter().
fieldScale_
dictionary fieldScale_ protected
Definition at line 238 of file surfaceWriter.H.
Referenced by surfaceWriter::surfaceWriter().
defaultMergeDim
Foam::scalar defaultMergeDim = 1e-8 static
Definition at line 311 of file surfaceWriter.H.
The documentation for this class was generated from the following files:
src/surfMesh/writers/common/surfaceWriter.H
src/surfMesh/writers/common/surfaceWriter.C
src/surfMesh/writers/common/surfaceWriterI.H