OpenFOAM: pointConstraint Class Reference
pointConstraint Class Reference
Accumulates point constraints through successive applications of the applyConstraint function.
#include <pointConstraint.H>
Public Member Functions
pointConstraint ()
pointConstraint (const Tuple2< label, vector > &)
pointConstraint (Istream &)
void applyConstraint (const vector &cd)
void combine (const pointConstraint &)
tensor constraintTransformation () const
void unconstrainedDirections (label &n, tensor &vecs) const
vector constrainDisplacement (const vector &disp) const
Public Member Functions inherited from Tuple2< label, vector >
Tuple2 ()=default
Tuple2 (const label &f, const vector &s)
Tuple2 (label &&f, vector &&s)
Tuple2 (const std::pair< label, vector > &vals)
Tuple2 (std::pair< label, vector > &&vals)
Tuple2 (Istream &is)
const label & first () const noexcept
label & first () noexcept
const vector & second () const noexcept
vector & second () noexcept
Additional Inherited Members
Public Types inherited from Tuple2< label, vector >
typedef label first_type
typedef vector second_type
Detailed Description
Accumulates point constraints through successive applications of the applyConstraint function.
After all the constraints have been entered the resulting transformation tensor is returned by the constraintTransformation function.
Source files
pointConstraint.H
pointConstraintI.H
Definition at line 56 of file pointConstraint.H.
Constructor & Destructor Documentation
pointConstraint() [1/3]
pointConstraint () inline
Definition at line 23 of file pointConstraintI.H.
pointConstraint() [2/3]
pointConstraint (const Tuple2< label, vector > & pc) inline
Definition at line 29 of file pointConstraintI.H.
pointConstraint() [3/3]
pointConstraint (Istream & is) inline
Definition at line 35 of file pointConstraintI.H.
Member Function Documentation
applyConstraint()
void applyConstraint (const vector & cd) inline
Definition at line 43 of file pointConstraintI.H.
References e, Foam::mag(), and Foam::Zero.
Referenced by cyclicSlipPointPatch::applyConstraint(), emptyPointPatch::applyConstraint(), nonuniformTransformCyclicPointPatch::applyConstraint(), symmetryPointPatch::applyConstraint(), symmetryPlanePointPatch::applyConstraint(), wedgePointPatch::applyConstraint(), and plane::constrainTranslation().
combine()
void combine (const pointConstraint & pc) inline
Definition at line 72 of file pointConstraintI.H.
References e, Tuple2< T1, T2 >::first(), Foam::mag(), n, Tuple2< T1, T2 >::second(), and Foam::Zero.
Referenced by axis::constrainRotation(), orientation::constrainRotation(), line::constrainTranslation(), and point::constrainTranslation().
constraintTransformation()
Foam::tensor constraintTransformation () const inline
Definition at line 113 of file pointConstraintI.H.
References Foam::I, Foam::sqr(), and Foam::Zero.
unconstrainedDirections()
void unconstrainedDirections (label & n, tensor & vecs) const inline
Definition at line 134 of file pointConstraintI.H.
References e, Foam::mag(), n, UPtrList< T >::size(), x, and Foam::Zero.
constrainDisplacement()
Foam::vector constrainDisplacement (const vector & disp) const inline
Definition at line 180 of file pointConstraintI.H.
References Foam::Zero.
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointConstraint/pointConstraint.H
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointConstraint/pointConstraintI.H