OpenFOAM: KinematicParcel< ParcelType >::trackingData Class Reference
KinematicParcel< ParcelType >::trackingData Class Reference
#include <KinematicParcel.H>
Public Types
enum trackPart { tpVelocityHalfStep , tpLinearTrack , tpRotationalTrack }
Public Member Functions
template<class TrackCloudType >
trackingData (const TrackCloudType &cloud, trackPart part=tpLinearTrack)
const interpolation< scalar > & rhoInterp () const
const interpolation< vector > & UInterp () const
const interpolation< scalar > & muInterp () const
scalar rhoc () const
scalar & rhoc ()
const vector & Uc () const
vector & Uc ()
scalar muc () const
scalar & muc ()
const vector & g () const
trackPart part () const
trackPart & part ()
template<class TrackCloudType >
void updateAverages (const TrackCloudType &cloud)
Detailed Description
template<class ParcelType>
class Foam::KinematicParcel< ParcelType >::trackingData
Definition at line 159 of file KinematicParcel.H.
Member Enumeration Documentation
trackPart
template<class ParcelType > enum trackPart
Enumerator
tpVelocityHalfStep
tpLinearTrack
tpRotationalTrack
Definition at line 165 of file KinematicParcel.H.
Constructor & Destructor Documentation
trackingData()
template<class ParcelType > template<class TrackCloudType > trackingData (const TrackCloudType & cloud, trackPart part = tpLinearTrack) inline
Definition at line 28 of file KinematicParcelTrackingDataI.H.
References Foam::name(), and Foam::New().
Member Function Documentation
rhoInterp()
template<class ParcelType > const Foam::interpolation< Foam::scalar > & rhoInterp () const inline
Definition at line 169 of file KinematicParcelTrackingDataI.H.
UInterp()
template<class ParcelType > const Foam::interpolation< Foam::vector > & UInterp () const inline
Definition at line 177 of file KinematicParcelTrackingDataI.H.
muInterp()
template<class ParcelType > const Foam::interpolation< Foam::scalar > & muInterp () const inline
Definition at line 185 of file KinematicParcelTrackingDataI.H.
rhoc() [1/2]
template<class ParcelType > Foam::scalar rhoc () const inline
Definition at line 201 of file KinematicParcelTrackingDataI.H.
rhoc() [2/2]
template<class ParcelType > Foam::scalar & rhoc () inline
Definition at line 208 of file KinematicParcelTrackingDataI.H.
Uc() [1/2]
template<class ParcelType > const Foam::vector & Uc () const inline
Definition at line 216 of file KinematicParcelTrackingDataI.H.
Uc() [2/2]
template<class ParcelType > Foam::vector & Uc () inline
Definition at line 223 of file KinematicParcelTrackingDataI.H.
muc() [1/2]
template<class ParcelType > Foam::scalar muc () const inline
Definition at line 230 of file KinematicParcelTrackingDataI.H.
muc() [2/2]
template<class ParcelType > Foam::scalar & muc () inline
Definition at line 237 of file KinematicParcelTrackingDataI.H.
g()
template<class ParcelType > const Foam::vector & g () const inline
Definition at line 193 of file KinematicParcelTrackingDataI.H.
part() [1/2]
template<class ParcelType > Foam::KinematicParcel< ParcelType >::trackingData::trackPart part () const inline
Definition at line 245 of file KinematicParcelTrackingDataI.H.
part() [2/2]
template<class ParcelType > Foam::KinematicParcel< ParcelType >::trackingData::trackPart & part () inline
Definition at line 253 of file KinematicParcelTrackingDataI.H.
updateAverages()
template<class ParcelType > template<class TrackCloudType > void updateAverages (const TrackCloudType & cloud) inline
Definition at line 261 of file KinematicParcelTrackingDataI.H.
References IOobject::db(), f(), Foam::mag(), Foam::magSqr(), IOobject::name(), p, Foam::pow(), Foam::pow3(), Foam::sqr(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcel.H
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcelTrackingDataI.H