OpenFOAM: ensightFaMesh Class Reference
ensightFaMesh Class Reference
Encapsulation of area meshes for writing in ensight format.
#include <ensightFaMesh.H>
Public Member Functions
ensightFaMesh (const faMesh &mesh)
int verbose () const noexcept
int verbose (const int level) noexcept
const faMesh & mesh () const noexcept
const ensightFaces & areaPart () const noexcept
bool needsUpdate () const noexcept
bool expire ()
void correct ()
void write (ensightGeoFile &os, bool parallel=Pstream::parRun()) const
void write (autoPtr< ensightGeoFile > &os, bool parallel=Pstream::parRun()) const
Detailed Description
Encapsulation of area meshes for writing in ensight format.
Note
Currently restricted to a single faMesh representation. The face elements are created from a specified subset of polyMesh faces. The original ordering of these faces is retained in the ensightFaces faceOrder().
Source files
ensightFaMesh.H
ensightFaMesh.C
ensightFaMeshI.H
Definition at line 58 of file ensightFaMesh.H.
Constructor & Destructor Documentation
ensightFaMesh()
ensightFaMesh (const faMesh & mesh) explicit
Definition at line 43 of file ensightFaMesh.C.
References ensightFaMesh::correct().
Member Function Documentation
verbose() [1/2]
int verbose () const noexcept
Definition at line 62 of file ensightFaMesh.C.
verbose() [2/2]
int verbose (const int level) noexcept
Definition at line 68 of file ensightFaMesh.C.
mesh()
const faMesh & mesh () const inline noexcept
Definition at line 111 of file ensightFaMesh.H.
Referenced by Foam::writeAreaFields().
areaPart()
const ensightFaces & areaPart () const inline noexcept
Definition at line 117 of file ensightFaMesh.H.
Referenced by Foam::ensightOutput::writeAreaField().
needsUpdate()
bool needsUpdate () const inline noexcept
Definition at line 126 of file ensightFaMesh.H.
expire()
bool expire () inline
Definition at line 23 of file ensightFaMeshI.H.
correct()
void correct ()
Definition at line 76 of file ensightFaMesh.C.
References ensightFaces::classify(), clear(), ensightFaces::clear(), ensightPart::identifier(), ensightFaces::info(), Foam::Info, ensightFaces::reduce(), ensightPart::rename(), and Foam::renumber().
Referenced by ensightFaMesh::ensightFaMesh().
write() [1/2]
void write (ensightGeoFile & os, bool parallel = Pstream::parRun()) const
Definition at line 115 of file ensightFaMesh.C.
References os().
write() [2/2]
void write (autoPtr< ensightGeoFile > & os, bool parallel = Pstream::parRun()) const inline
Definition at line 38 of file ensightFaMeshI.H.
References os(), and write().
The documentation for this class was generated from the following files:
src/finiteArea/output/ensight/ensightFaMesh.H
src/finiteArea/output/ensight/ensightFaMesh.C
src/finiteArea/output/ensight/ensightFaMeshI.H