OpenFOAM: sigStopAtWriteNow Class Reference
sigStopAtWriteNow Class Reference
Signal handler to write and stop the job. The interrupt is defined by OptimisationSwitches::stopAtWriteNowSignal.
#include <sigStopAtWriteNow.H>
Public Member Functions
sigStopAtWriteNow ()
sigStopAtWriteNow (const Time &runTime, bool verbose=false)
~sigStopAtWriteNow ()
Static Public Member Functions
static bool active ()
static int signalNumber ()
static void set (bool verbose=false)
Friends
class addstopAtWriteNowSignalToOpt
Detailed Description
Signal handler to write and stop the job. The interrupt is defined by OptimisationSwitches::stopAtWriteNowSignal.
Source files
sigStopAtWriteNow.H
sigStopAtWriteNow.C
Definition at line 49 of file sigStopAtWriteNow.H.
Constructor & Destructor Documentation
sigStopAtWriteNow() [1/2]
sigStopAtWriteNow ()
Definition at line 107 of file sigStopAtWriteNow.C.
sigStopAtWriteNow() [2/2]
sigStopAtWriteNow (const Time & runTime, bool verbose = false)
Definition at line 111 of file sigStopAtWriteNow.C.
References runTime, and runTimePtr_.
~sigStopAtWriteNow()
~sigStopAtWriteNow ()
Definition at line 120 of file sigStopAtWriteNow.C.
References Foam::resetHandler().
Member Function Documentation
active()
bool active () static
Definition at line 133 of file sigStopAtWriteNow.C.
signalNumber()
int signalNumber () static
Definition at line 139 of file sigStopAtWriteNow.C.
set()
void set (bool verbose = false) static
Definition at line 145 of file sigStopAtWriteNow.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, Foam::setHandler(), and sigWriteNow::signalNumber().
Referenced by addstopAtWriteNowSignalToOpt::readData().
Friends And Related Symbol Documentation
addstopAtWriteNowSignalToOpt
friend class addstopAtWriteNowSignalToOpt friend
Definition at line 66 of file sigStopAtWriteNow.H.
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/signals/sigStopAtWriteNow.H
src/OSspecific/POSIX/signals/sigStopAtWriteNow.C