OpenFOAM: geomDecomp Class Reference
geomDecomp Class Reference abstract
Base for geometrical domain decomposition methods.
#include <geomDecomp.H>
Public Member Functions
geomDecomp (const word &derivedType, const dictionary &decompDict, int select=selectionType::DEFAULT)
geomDecomp (const word &derivedType, const dictionary &decompDict, const word &regionName, int select=selectionType::DEFAULT)
virtual labelList decompose (const pointField &points, const scalarField &pointWeights) const =0
virtual labelList decompose (const pointField &points) const =0
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompDict, const word &regionName),(decompDict, regionName))
decompositionMethod (const dictionary &decompDict, const word &regionName="")
virtual ~decompositionMethod ()=default
label nDomains () const noexcept
virtual bool parallelAware () const =0
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights) const =0
virtual labelList decompose (const polyMesh &mesh, const pointField &points) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights) const =0
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc) const
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp) const
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections) const
labelList decompose (const polyMesh &mesh, const scalarField &cWeights) const
Protected Member Functions
tmp< pointField > adjustPoints (const pointField &) const
void checkDecompositionDirections (const Vector< label > &) const
Protected Member Functions inherited from decompositionMethod
const dictionary & findCoeffsDict (const word &coeffsName, int select=selectionType::DEFAULT) const
Protected Attributes
Vector< label > n_
Vector< direction > order_
const dictionary & coeffsDict_
Protected Attributes inherited from decompositionMethod
const dictionary & decompDict_
const dictionary & decompRegionDict_
label nDomains_
PtrList< decompositionConstraint > constraints_
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static label nDomains (const dictionary &decompDict, const word &regionName="")
static const dictionary & optionalRegionDict (const dictionary &decompDict, const word &regionName)
static autoPtr< decompositionMethod > New (const dictionary &decompDict, const word &regionName="")
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Protected Types inherited from decompositionMethod
enum selectionType { DEFAULT = 0 , EXACT = 1 , MANDATORY = 2 , NULL_DICT = 4 }
Static Protected Member Functions inherited from decompositionMethod
static const dictionary & findCoeffsDict (const dictionary &dict, const word &coeffsName, int select=selectionType::DEFAULT)
Detailed Description
Base for geometrical domain decomposition methods.
Base coefficients:
Property Description Required Default
n (nx ny nz) yes
order order of operation no xyz
delta delta (jitter) for rotation matrix no 0.001
rotation coordinate rotation no
Source files
geomDecomp.H
geomDecomp.C
Definition at line 82 of file geomDecomp.H.
Constructor & Destructor Documentation
geomDecomp() [1/2]
geomDecomp (const word & derivedType, const dictionary & decompDict, int select = selectionType::DEFAULT)
Definition at line 145 of file geomDecomp.C.
geomDecomp() [2/2]
geomDecomp (const word & derivedType, const dictionary & decompDict, const word & regionName, int select = selectionType::DEFAULT)
Definition at line 163 of file geomDecomp.C.
Member Function Documentation
adjustPoints()
Foam::tmp< Foam::pointField > adjustPoints (const pointField & points) const protected
Definition at line 114 of file geomDecomp.C.
References points.
checkDecompositionDirections()
void checkDecompositionDirections (const Vector< label > & meshDirs) const protected
Definition at line 123 of file geomDecomp.C.
References Foam::endl(), and WarningInFunction.
Referenced by hierarchGeomDecomp::decompose(), hierarchGeomDecomp::decompose(), simpleGeomDecomp::decompose(), and simpleGeomDecomp::decompose().
decompose() [1/2]
virtual labelList decompose (const pointField & points, const scalarField & pointWeights) const pure virtual
Reimplemented from decompositionMethod.
Implemented in hierarchGeomDecomp, and simpleGeomDecomp.
decompose() [2/2]
virtual labelList decompose (const pointField & points) const pure virtual
Reimplemented from decompositionMethod.
Implemented in hierarchGeomDecomp, and simpleGeomDecomp.
Member Data Documentation
n_
Vector<label> n_ protected
Definition at line 111 of file geomDecomp.H.
order_
Vector<direction> order_ protected
Definition at line 114 of file geomDecomp.H.
coeffsDict_
const dictionary& coeffsDict_ protected
Definition at line 117 of file geomDecomp.H.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/geomDecomp/geomDecomp.H
src/parallel/decompose/decompositionMethods/geomDecomp/geomDecomp.C