OpenFOAM: optimisationType Class Reference
optimisationType Class Reference abstract
Abstract base class for optimisation methods.
#include <optimisationTypeIncompressible.H>
Public Member Functions
TypeName ("optimisationType")
declareRunTimeSelectionTable (autoPtr, optimisationType, dictionary,(fvMesh &mesh, const dictionary &dict, PtrList< adjointSolverManager > &adjointSolverManagers),(mesh, dict, adjointSolverManagers))
optimisationType (fvMesh &mesh, const dictionary &dict, PtrList< adjointSolverManager > &adjointSolverManagers)
virtual ~optimisationType ()=default
virtual void update ()
virtual void update (scalarField &correction)
virtual void storeDesignVariables ()=0
virtual void resetDesignVariables ()=0
virtual tmp< scalarField > computeDirection ()
virtual void updateGradientsAndValues (scalarField &objectiveSens, PtrList< scalarField > &constraintSens, scalar &objectiveValue, scalarField &constraintValues)
virtual scalar computeMeritFunction ()
virtual scalar meritFunctionDirectionalDerivative ()
virtual void updateOldCorrection (const scalarField &)
virtual void write ()
const autoPtr< volScalarField > & sourcePtr ()
autoPtr< lineSearch > & getLineSearch ()
Static Public Member Functions
static autoPtr< optimisationType > New (fvMesh &mesh, const dictionary &dict, PtrList< adjointSolverManager > &adjointSolverManagers)
Protected Member Functions
virtual void updateDesignVariables (scalarField &correction)=0
virtual void computeEta (scalarField &correction)=0
Protected Attributes
fvMesh & mesh_
const dictionary dict_
PtrList< adjointSolverManager > & adjointSolvManagers_
autoPtr< updateMethod > updateMethod_
autoPtr< volScalarField > sourcePtr_
autoPtr< lineSearch > lineSearch_
Detailed Description
Abstract base class for optimisation methods.
Source files
optimisationTypeIncompressible.H
optimisationType.C
Definition at line 54 of file optimisationTypeIncompressible.H.
Constructor & Destructor Documentation
optimisationType()
optimisationType (fvMesh & mesh, const dictionary & dict, PtrList< adjointSolverManager > & adjointSolverManagers)
Definition at line 42 of file optimisationTypeIncompressible.C.
References optimisationType::adjointSolvManagers_, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, optimisationType::updateMethod_, and WarningInFunction.
~optimisationType()
virtual ~optimisationType () virtual default
Member Function Documentation
updateDesignVariables()
virtual void updateDesignVariables (scalarField & correction) protected pure virtual
Implemented in shapeOptimisation.
Referenced by optimisationType::update().
computeEta()
virtual void computeEta (scalarField & correction) protected pure virtual
Implemented in shapeOptimisation.
Referenced by optimisationType::computeDirection().
TypeName()
TypeName ("optimisationType")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , optimisationType , dictionary , (fvMesh &mesh, const dictionary &dict, PtrList< adjointSolverManager > &adjointSolverManagers) , (mesh, dict, adjointSolverManagers))
New()
autoPtr< optimisationType > New (fvMesh & mesh, const dictionary & dict, PtrList< adjointSolverManager > & adjointSolverManagers) static
Definition at line 119 of file optimisationTypeIncompressible.C.
References adjointSolverManagers, dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and mesh.
Referenced by steadyOptimisation::steadyOptimisation().
update() [1/2]
void update () virtual
Definition at line 152 of file optimisationTypeIncompressible.C.
References optimisationType::computeDirection(), Foam::correction(), optimisationType::update(), optimisationType::updateOldCorrection(), and optimisationType::write().
Referenced by optimisationType::update().
update() [2/2]
void update (scalarField & correction) virtual
Definition at line 168 of file optimisationTypeIncompressible.C.
References Foam::correction(), optimisationType::lineSearch_, and optimisationType::updateDesignVariables().
storeDesignVariables()
virtual void storeDesignVariables () pure virtual
Implemented in shapeOptimisation.
resetDesignVariables()
virtual void resetDesignVariables () pure virtual
Implemented in shapeOptimisation.
computeDirection()
tmp< scalarField > computeDirection () virtual
Definition at line 182 of file optimisationTypeIncompressible.C.
References optimisationType::computeEta(), Foam::correction(), UPtrList< T >::size(), optimisationType::updateGradientsAndValues(), optimisationType::updateMethod_, and Foam::Zero.
Referenced by optimisationType::update().
updateGradientsAndValues()
void updateGradientsAndValues (scalarField & objectiveSens, PtrList< scalarField > & constraintSens, scalar & objectiveValue, scalarField & constraintValues) virtual
Definition at line 217 of file optimisationTypeIncompressible.C.
References optimisationType::adjointSolvManagers_, UPtrList< T >::empty(), forAll, PtrList< T >::set(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), and Foam::Zero.
Referenced by optimisationType::computeDirection().
computeMeritFunction()
scalar computeMeritFunction () virtual
Definition at line 275 of file optimisationTypeIncompressible.C.
References optimisationType::adjointSolvManagers_, UList< T >::empty(), List< T >::setSize(), UPtrList< T >::size(), optimisationType::updateMethod_, and Foam::Zero.
meritFunctionDirectionalDerivative()
scalar meritFunctionDirectionalDerivative () virtual
Definition at line 302 of file optimisationTypeIncompressible.C.
References optimisationType::updateMethod_.
updateOldCorrection()
void updateOldCorrection (const scalarField & oldCorrection) virtual
Definition at line 308 of file optimisationTypeIncompressible.C.
References optimisationType::updateMethod_.
Referenced by optimisationType::update().
write()
void write () virtual
Reimplemented in shapeOptimisation.
Definition at line 314 of file optimisationTypeIncompressible.C.
References optimisationType::updateMethod_.
Referenced by optimisationType::update(), and shapeOptimisation::write().
sourcePtr()
const autoPtr< volScalarField > & sourcePtr ()
Definition at line 320 of file optimisationTypeIncompressible.C.
References optimisationType::sourcePtr_.
getLineSearch()
autoPtr< lineSearch > & getLineSearch ()
Definition at line 326 of file optimisationTypeIncompressible.C.
References optimisationType::lineSearch_.
Member Data Documentation
mesh_
fvMesh& mesh_ protected
Definition at line 60 of file optimisationTypeIncompressible.H.
Referenced by shapeOptimisation::shapeOptimisation(), and shapeOptimisation::updateDesignVariables().
dict_
const dictionary dict_ protected
Definition at line 61 of file optimisationTypeIncompressible.H.
Referenced by shapeOptimisation::shapeOptimisation().
adjointSolvManagers_
PtrList<adjointSolverManager>& adjointSolvManagers_ protected
Definition at line 62 of file optimisationTypeIncompressible.H.
Referenced by optimisationType::computeMeritFunction(), optimisationType::optimisationType(), and optimisationType::updateGradientsAndValues().
updateMethod_
autoPtr<updateMethod> updateMethod_ protected
Definition at line 63 of file optimisationTypeIncompressible.H.
Referenced by optimisationType::computeDirection(), shapeOptimisation::computeEta(), optimisationType::computeMeritFunction(), optimisationType::meritFunctionDirectionalDerivative(), optimisationType::optimisationType(), shapeOptimisation::shapeOptimisation(), optimisationType::updateOldCorrection(), optimisationType::write(), and shapeOptimisation::write().
sourcePtr_
autoPtr<volScalarField> sourcePtr_ protected
Definition at line 64 of file optimisationTypeIncompressible.H.
Referenced by optimisationType::sourcePtr().
lineSearch_
autoPtr<lineSearch> lineSearch_ protected
Definition at line 65 of file optimisationTypeIncompressible.H.
Referenced by optimisationType::getLineSearch(), and optimisationType::update().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/optimisationType/incompressible/optimisationType/optimisationTypeIncompressible.H
src/optimisation/adjointOptimisation/adjoint/optimisation/optimisationType/incompressible/optimisationType/optimisationTypeIncompressible.C