OpenFOAM: mapPolyMesh Class Reference
mapPolyMesh Class Reference
Class containing mesh-to-mesh mapping information after a change in polyMesh topology.
#include <mapPolyMesh.H>
Public Member Functions
mapPolyMesh (const polyMesh &mesh)
mapPolyMesh (const polyMesh &mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, const labelList &pointMap, const List< objectMap > &pointsFromPoints, const labelList &faceMap, const List< objectMap > &facesFromPoints, const List< objectMap > &facesFromEdges, const List< objectMap > &facesFromFaces, const labelList &cellMap, const List< objectMap > &cellsFromPoints, const List< objectMap > &cellsFromEdges, const List< objectMap > &cellsFromFaces, const List< objectMap > &cellsFromCells, const labelList &reversePointMap, const labelList &reverseFaceMap, const labelList &reverseCellMap, const labelHashSet &flipFaceFlux, const labelListList &patchPointMap, const labelListList &pointZoneMap, const labelListList &faceZonePointMap, const labelListList &faceZoneFaceMap, const labelListList &cellZoneMap, const pointField &preMotionPoints, const labelList &oldPatchStarts, const labelList &oldPatchNMeshPoints, const autoPtr< scalarField > &oldCellVolumesPtr)
mapPolyMesh (const polyMesh &mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, labelList &pointMap, List< objectMap > &pointsFromPoints, labelList &faceMap, List< objectMap > &facesFromPoints, List< objectMap > &facesFromEdges, List< objectMap > &facesFromFaces, labelList &cellMap, List< objectMap > &cellsFromPoints, List< objectMap > &cellsFromEdges, List< objectMap > &cellsFromFaces, List< objectMap > &cellsFromCells, labelList &reversePointMap, labelList &reverseFaceMap, labelList &reverseCellMap, labelHashSet &flipFaceFlux, labelListList &patchPointMap, labelListList &pointZoneMap, labelListList &faceZonePointMap, labelListList &faceZoneFaceMap, labelListList &cellZoneMap, pointField &preMotionPoints, labelList &oldPatchStarts, labelList &oldPatchNMeshPoints, autoPtr< scalarField > &oldCellVolumesPtr, const bool reuse)
const polyMesh & mesh () const
label nOldPoints () const
label nOldInternalFaces () const
label nOldFaces () const
label nOldCells () const
const labelList & pointMap () const
const List< objectMap > & pointsFromPointsMap () const
const labelList & faceMap () const
const List< objectMap > & facesFromPointsMap () const
const List< objectMap > & facesFromEdgesMap () const
const List< objectMap > & facesFromFacesMap () const
const labelList & cellMap () const
const List< objectMap > & cellsFromPointsMap () const
const List< objectMap > & cellsFromEdgesMap () const
const List< objectMap > & cellsFromFacesMap () const
const List< objectMap > & cellsFromCellsMap () const
const labelList & reversePointMap () const
label mergedPoint (const label oldPointi) const
const labelList & reverseFaceMap () const
label mergedFace (const label oldFacei) const
const labelList & reverseCellMap () const
label mergedCell (const label oldCelli) const
const labelHashSet & flipFaceFlux () const
const labelListList & patchPointMap () const
const labelListList & pointZoneMap () const
const labelListList & faceZonePointMap () const
const labelListList & faceZoneFaceMap () const
const labelListList & cellZoneMap () const
const pointField & preMotionPoints () const
bool hasMotionPoints () const
const labelList & oldPatchSizes () const
const labelList & oldPatchStarts () const
const labelList & oldPatchNMeshPoints () const
bool hasOldCellVolumes () const
const scalarField & oldCellVolumes () const
Detailed Description
Class containing mesh-to-mesh mapping information after a change in polyMesh topology.
General:
pointMap/faceMap/cellMap:
from current mesh back to previous mesh. (so to 'pull' the information onto the current mesh)
reversePointMap/faceMap/cellMap:
from previous mesh to current. (so to 'push' information)
In the topology change points/faces/cells
can be unchanged. (faces might be renumbered though)
can be removed (into nothing)
can be removed into/merged with existing same entity (so point merged with other point, face with other face, cell with other cell. Note that probably only cell with cell is relevant)
can be added from existing same 'master' entity (so point from point, face from face and cell from cell)
can be inflated: face out of edge or point, cell out of face, edge or point.
can be appended: added 'out of nothing'.
All this information is necessary to correctly map fields.
points
unchanged:
pointMap[pointi] contains old point label
reversePointMap[oldPointi] contains new point label
removed:
reversePointMap[oldPointi] contains -1
merged into point:
reversePointMap[oldPointi] contains <-1 : -newPointi-2
pointMap[pointi] contains the old master point label
pointsFromPoints gives for pointi all the old point labels (including the old master point!)
added-from-same:
pointMap[pointi] contains the old master point label
appended:
pointMap[pointi] contains -1
faces
unchanged:
faceMap[facei] contains old face label
reverseFaceMap[oldFacei] contains new face label
removed:
reverseFaceMap[oldFacei] contains -1
merged into face:
reverseFaceMap[oldFacei] contains <-1 : -newFacei-2
faceMap[facei] contains the old master face label
facesFromFaces gives for facei all the old face labels (including the old master face!)
added-from-same:
faceMap[facei] contains the old master face label
inflated-from-edge:
faceMap[facei] contains -1
facesFromEdges contains an entry with
facei
list of faces(*) on old mesh that connected to the old edge
inflated-from-point:
faceMap[facei] contains -1
facesFromPoints contains an entry with
facei
list of faces(*) on old mesh that connected to the old point
appended:
faceMap[facei] contains -1
Note (*)
if the newly inflated face is a boundary face the list of faces will only be boundary faces; if the new face is an internal face they will only be internal faces.
cells
unchanged:
cellMap[celli] contains old cell label
reverseCellMap[oldCelli] contains new cell label
removed:
reverseCellMap[oldCelli] contains -1
merged into cell:
reverseCellMap[oldCelli] contains <-1 : -newCelli-2
cellMap[celli] contains the old master cell label
cellsFromCells gives for celli all the old cell labels (including the old master cell!)
added-from-same:
cellMap[celli] contains the old master cell label
inflated-from-face:
cellMap[celli] contains -1
cellsFromFaces contains an entry with
celli
list of cells on old mesh that connected to the old face
inflated-from-edge:
cellMap[celli] contains -1
cellsFromEdges contains an entry with
celli
list of cells on old mesh that connected to the old edge
inflated-from-point:
cellMap[celli] contains -1
cellsFromPoints contains an entry with
celli
list of cells on old mesh that connected to the old point
appended:
cellMap[celli] contains -1
Source files
mapPolyMesh.H
mapPolyMesh.C
Definition at line 157 of file mapPolyMesh.H.
Constructor & Destructor Documentation
mapPolyMesh() [1/3]
mapPolyMesh (const polyMesh & mesh)
Definition at line 27 of file mapPolyMesh.C.
References forAll, Foam::identity(), mapPolyMesh::mesh(), nPoints, and UPtrList< T >::size().
mapPolyMesh() [2/3]
mapPolyMesh (const polyMesh & mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, const labelList & pointMap, const List< objectMap > & pointsFromPoints, const labelList & faceMap, const List< objectMap > & facesFromPoints, const List< objectMap > & facesFromEdges, const List< objectMap > & facesFromFaces, const labelList & cellMap, const List< objectMap > & cellsFromPoints, const List< objectMap > & cellsFromEdges, const List< objectMap > & cellsFromFaces, const List< objectMap > & cellsFromCells, const labelList & reversePointMap, const labelList & reverseFaceMap, const labelList & reverseCellMap, const labelHashSet & flipFaceFlux, const labelListList & patchPointMap, const labelListList & pointZoneMap, const labelListList & faceZonePointMap, const labelListList & faceZoneFaceMap, const labelListList & cellZoneMap, const pointField & preMotionPoints, const labelList & oldPatchStarts, const labelList & oldPatchNMeshPoints, const autoPtr< scalarField > & oldCellVolumesPtr)
Definition at line 92 of file mapPolyMesh.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::min(), and UPtrList< T >::size().
mapPolyMesh() [3/3]
mapPolyMesh (const polyMesh & mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, labelList & pointMap, List< objectMap > & pointsFromPoints, labelList & faceMap, List< objectMap > & facesFromPoints, List< objectMap > & facesFromEdges, List< objectMap > & facesFromFaces, labelList & cellMap, List< objectMap > & cellsFromPoints, List< objectMap > & cellsFromEdges, List< objectMap > & cellsFromFaces, List< objectMap > & cellsFromCells, labelList & reversePointMap, labelList & reverseFaceMap, labelList & reverseCellMap, labelHashSet & flipFaceFlux, labelListList & patchPointMap, labelListList & pointZoneMap, labelListList & faceZonePointMap, labelListList & faceZoneFaceMap, labelListList & cellZoneMap, pointField & preMotionPoints, labelList & oldPatchStarts, labelList & oldPatchNMeshPoints, autoPtr< scalarField > & oldCellVolumesPtr, const bool reuse)
Definition at line 180 of file mapPolyMesh.C.
References Foam::abort(), PtrList< T >::clone(), Foam::FatalError, FatalErrorInFunction, Foam::min(), and UPtrList< T >::size().
Member Function Documentation
mesh()
const polyMesh & mesh () const inline
Definition at line 359 of file mapPolyMesh.H.
Referenced by mapPolyMesh::mapPolyMesh(), and hexRef8Data::updateMesh().
nOldPoints()
label nOldPoints () const inline
Definition at line 365 of file mapPolyMesh.H.
Referenced by hexRef8Data::updateMesh(), and hexRef8::updateMesh().
nOldInternalFaces()
label nOldInternalFaces () const inline
Definition at line 371 of file mapPolyMesh.H.
nOldFaces()
label nOldFaces () const inline
Definition at line 377 of file mapPolyMesh.H.
Referenced by snappyLayerDriver::addLayers().
nOldCells()
label nOldCells () const inline
Definition at line 383 of file mapPolyMesh.H.
Referenced by snappyLayerDriver::addLayers(), hexRef8Data::updateMesh(), and hexRef8::updateMesh().
pointMap()
const labelList & pointMap () const inline
Definition at line 392 of file mapPolyMesh.H.
Referenced by hexRef8Data::updateMesh(), and hexRef8::updateMesh().
pointsFromPointsMap()
const List< objectMap > & pointsFromPointsMap () const inline
Definition at line 398 of file mapPolyMesh.H.
faceMap()
const labelList & faceMap () const inline
Definition at line 406 of file mapPolyMesh.H.
Referenced by snappyLayerDriver::addLayers(), snappyLayerDriver::addLayers(), snappyLayerDriver::addLayersSinglePass(), meshRefinement::createBaffles(), meshRefinement::splitFacesUndo(), and meshRefinement::updateMesh().
facesFromPointsMap()
const List< objectMap > & facesFromPointsMap () const inline
Definition at line 412 of file mapPolyMesh.H.
facesFromEdgesMap()
const List< objectMap > & facesFromEdgesMap () const inline
Definition at line 418 of file mapPolyMesh.H.
facesFromFacesMap()
const List< objectMap > & facesFromFacesMap () const inline
Definition at line 424 of file mapPolyMesh.H.
cellMap()
const labelList & cellMap () const inline
Definition at line 431 of file mapPolyMesh.H.
Referenced by snappyLayerDriver::addLayers(), hexRef8Data::updateMesh(), refinementHistory::updateMesh(), and hexRef8::updateMesh().
cellsFromPointsMap()
const List< objectMap > & cellsFromPointsMap () const inline
Definition at line 437 of file mapPolyMesh.H.
cellsFromEdgesMap()
const List< objectMap > & cellsFromEdgesMap () const inline
Definition at line 443 of file mapPolyMesh.H.
cellsFromFacesMap()
const List< objectMap > & cellsFromFacesMap () const inline
Definition at line 449 of file mapPolyMesh.H.
cellsFromCellsMap()
const List< objectMap > & cellsFromCellsMap () const inline
Definition at line 455 of file mapPolyMesh.H.
reversePointMap()
const labelList & reversePointMap () const inline
Definition at line 465 of file mapPolyMesh.H.
Referenced by meshRefinement::splitFacesUndo(), createShellMesh::updateMesh(), meshCutAndRemove::updateMesh(), combineFaces::updateMesh(), duplicatePoints::updateMesh(), removePoints::updateMesh(), tetDecomposer::updateMesh(), localPointRegion::updateMesh(), and hexRef8::updateMesh().
mergedPoint()
label mergedPoint (const label oldPointi) const inline
Definition at line 472 of file mapPolyMesh.H.
References Foam::abort(), Foam::endl(), Foam::FatalError, and FatalErrorInFunction.
reverseFaceMap()
const labelList & reverseFaceMap () const inline
Definition at line 497 of file mapPolyMesh.H.
Referenced by meshRefinement::createBaffles(), meshRefinement::doRemoveCells(), meshRefinement::doRestorePoints(), meshRefinement::mergeBaffles(), meshRefinement::mergePatchFaces(), meshRefinement::splitFacesUndo(), createShellMesh::updateMesh(), meshCutAndRemove::updateMesh(), combineFaces::updateMesh(), removePoints::updateMesh(), localPointRegion::updateMesh(), and meshRefinement::updateMesh().
mergedFace()
label mergedFace (const label oldFacei) const inline
Definition at line 503 of file mapPolyMesh.H.
References Foam::abort(), Foam::endl(), Foam::FatalError, and FatalErrorInFunction.
reverseCellMap()
const labelList & reverseCellMap () const inline
Definition at line 528 of file mapPolyMesh.H.
Referenced by particle< Type >::autoMap(), createShellMesh::updateMesh(), meshCutAndRemove::updateMesh(), refinementHistory::updateMesh(), tetDecomposer::updateMesh(), and hexRef8::updateMesh().
mergedCell()
label mergedCell (const label oldCelli) const inline
Definition at line 534 of file mapPolyMesh.H.
References Foam::abort(), Foam::endl(), Foam::FatalError, and FatalErrorInFunction.
flipFaceFlux()
const labelHashSet & flipFaceFlux () const inline
Definition at line 558 of file mapPolyMesh.H.
patchPointMap()
const labelListList & patchPointMap () const inline
Definition at line 566 of file mapPolyMesh.H.
pointZoneMap()
const labelListList & pointZoneMap () const inline
Definition at line 577 of file mapPolyMesh.H.
faceZonePointMap()
const labelListList & faceZonePointMap () const inline
Definition at line 585 of file mapPolyMesh.H.
faceZoneFaceMap()
const labelListList & faceZoneFaceMap () const inline
Definition at line 593 of file mapPolyMesh.H.
cellZoneMap()
const labelListList & cellZoneMap () const inline
Definition at line 601 of file mapPolyMesh.H.
preMotionPoints()
const pointField & preMotionPoints () const inline
Definition at line 609 of file mapPolyMesh.H.
Referenced by snappyLayerDriver::addLayers(), snappyLayerDriver::addLayers(), snappyLayerDriver::addLayersSinglePass(), polyMeshFilter::copyMesh(), meshRefinement::createBaffles(), meshRefinement::doRemoveCells(), meshRefinement::doRemovePoints(), meshRefinement::doRestorePoints(), meshRefinement::dupNonManifoldPoints(), meshRefinement::mergeBaffles(), meshRefinement::mergePatchFaces(), meshRefinement::mergePoints(), meshRefinement::refine(), and meshRefinement::splitFacesUndo().
hasMotionPoints()
bool hasMotionPoints () const inline
Definition at line 615 of file mapPolyMesh.H.
References UList< T >::size().
Referenced by snappyLayerDriver::addLayers(), snappyLayerDriver::addLayers(), snappyLayerDriver::addLayersSinglePass(), polyMeshFilter::copyMesh(), meshRefinement::createBaffles(), meshRefinement::doRemoveCells(), meshRefinement::doRemovePoints(), meshRefinement::doRestorePoints(), meshRefinement::dupNonManifoldPoints(), meshRefinement::mergeBaffles(), meshRefinement::mergePatchFaces(), meshRefinement::mergePoints(), meshRefinement::refine(), and meshRefinement::splitFacesUndo().
oldPatchSizes()
const labelList & oldPatchSizes () const inline
Definition at line 622 of file mapPolyMesh.H.
oldPatchStarts()
const labelList & oldPatchStarts () const inline
Definition at line 628 of file mapPolyMesh.H.
oldPatchNMeshPoints()
const labelList & oldPatchNMeshPoints () const inline
Definition at line 634 of file mapPolyMesh.H.
hasOldCellVolumes()
bool hasOldCellVolumes () const inline
Definition at line 642 of file mapPolyMesh.H.
oldCellVolumes()
const scalarField & oldCellVolumes () const inline
Definition at line 647 of file mapPolyMesh.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapPolyMesh.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapPolyMesh.C