OpenFOAM: NonSphereDragForce< CloudType > Class Template Reference
NonSphereDragForce< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Kinematic » Forces
Particle-drag model wherein drag forces (per unit carrier-fluid velocity) are dynamically computed based on empirical expressions using a four-parameter general drag correlation for non-spherical particles.
#include <NonSphereDragForce.H>
Public Member Functions
TypeName ("nonSphereDrag")
NonSphereDragForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict)
NonSphereDragForce (const NonSphereDragForce< CloudType > &df)
virtual autoPtr< ParticleForce< CloudType > > clone () const
void operator= (const NonSphereDragForce< CloudType > &)=delete
virtual ~NonSphereDragForce ()=default
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
ParticleForce (const ParticleForce &pf)
virtual ~ParticleForce ()
const CloudType & owner () const
CloudType & owner ()
const fvMesh & mesh () const
const dictionary & coeffs () const
virtual void cacheFields (const bool store)
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
virtual scalar massAdd (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar mass) const
Protected Member Functions
scalar CdRe (const scalar Re) const
Protected Attributes
scalar phi_
scalar a_
scalar b_
scalar c_
scalar d_
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Detailed Description
template<class CloudType>
class Foam::NonSphereDragForce< CloudType >
Particle-drag model wherein drag forces (per unit carrier-fluid velocity) are dynamically computed based on empirical expressions using a four-parameter general drag correlation for non-spherical particles.
with
where
where
= Drag force per carrier-fluid velocity [kg/s]
= Particle drag coefficient
= Particle Reynolds number
= Particle mass density
= Dynamic viscosity of carrier at the cell occupying particle
= Particle diameter
= Density of carrier at the cell occupying particle
= Relative velocity between particle and carrier
= Surface area of sphere with the same volume as the particle
= Actual surface area of the particle
= Ratio of surface areas
Constraints:
Applicable to particles with a spatially homogeneous distribution.
References:
        Standard model (tag:HL), (Eq. 4,10-11):
            Haider, A., & Levenspiel, O. (1989).
            Drag coefficient and terminal velocity of
            spherical and nonspherical particles.
            Powder technology, 58(1), 63-70.
            DOI:10.1016/0032-5910(89)80008-7
Usage
Minimal example by using constant/<CloudProperties>:
subModels
{
    particleForces
    {
        nonSphereDrag
        {
            phi    <phi>;
        }
    }
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: nonSphereDrag word yes -
phi
Ratio of surface area of sphere having same
volume as particle to actual surface area of
particle
scalar yes -
Note
The drag coefficient model in (HL:Eq. 11) is good to within 2 to 4 % of RMS values from the corresponding experiment.
(HL:Eq. 12) also give a simplified model with greater error compared to results from the experiment, but since phi is presumed constant, Eq. 12 offers little benefit.
is weighted with the particle mass at the stage of a function return, so that it can later be normalised with the effective mass, if necessary (e.g. when using virtual-mass forces).
Source files
NonSphereDragForce.H
NonSphereDragForce.C
Definition at line 220 of file NonSphereDragForce.H.
Constructor & Destructor Documentation
NonSphereDragForce() [1/2]
template<class CloudType > NonSphereDragForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict)
Definition at line 37 of file NonSphereDragForce.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
NonSphereDragForce() [2/2]
template<class CloudType > NonSphereDragForce (const NonSphereDragForce< CloudType > & df)
Definition at line 62 of file NonSphereDragForce.C.
~NonSphereDragForce()
template<class CloudType > virtual ~NonSphereDragForce () virtual default
Member Function Documentation
CdRe()
template<class CloudType > Foam::scalar CdRe (const scalar Re) const protected
Definition at line 27 of file NonSphereDragForce.C.
References Foam::pow(), and Foam::Re().
TypeName()
template<class CloudType > TypeName ("nonSphereDrag")
clone()
template<class CloudType > virtual autoPtr< ParticleForce< CloudType > > clone () const inline virtual
Reimplemented from ParticleForce< CloudType >.
Definition at line 270 of file NonSphereDragForce.H.
operator=()
template<class CloudType > void operator= (const NonSphereDragForce< CloudType > &) delete
calcCoupled()
template<class CloudType > Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const typename CloudType::parcelType::trackingData & td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Reimplemented from ParticleForce< CloudType >.
Definition at line 79 of file NonSphereDragForce.C.
References p, Foam::Re(), Foam::sqr(), and Foam::Zero.
Member Data Documentation
phi_
template<class CloudType > scalar phi_ protected
Definition at line 230 of file NonSphereDragForce.H.
a_
template<class CloudType > scalar a_ protected
Definition at line 235 of file NonSphereDragForce.H.
b_
template<class CloudType > scalar b_ protected
Definition at line 237 of file NonSphereDragForce.H.
c_
template<class CloudType > scalar c_ protected
Definition at line 239 of file NonSphereDragForce.H.
d_
template<class CloudType > scalar d_ protected
Definition at line 241 of file NonSphereDragForce.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Drag/NonSphereDrag/NonSphereDragForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Drag/NonSphereDrag/NonSphereDragForce.C