OpenFOAM: atmTurbulentHeatFluxTemperatureFvPatchScalarField Class Reference
atmTurbulentHeatFluxTemperatureFvPatchScalarField Class Reference
This boundary condition provides a fixed heat constraint on temperature (i.e. T) to specify temperature gradient through an input heat source which can either be specified as absolute power [W], or as flux [W/m2].
#include <atmTurbulentHeatFluxTemperatureFvPatchScalarField.H>
Public Member Functions
TypeName ("atmTurbulentHeatFluxTemperature")
atmTurbulentHeatFluxTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
atmTurbulentHeatFluxTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
atmTurbulentHeatFluxTemperatureFvPatchScalarField (const atmTurbulentHeatFluxTemperatureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
atmTurbulentHeatFluxTemperatureFvPatchScalarField (const atmTurbulentHeatFluxTemperatureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
atmTurbulentHeatFluxTemperatureFvPatchScalarField (const atmTurbulentHeatFluxTemperatureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a fixed heat constraint on temperature (i.e. T) to specify temperature gradient through an input heat source which can either be specified as absolute power [W], or as flux [W/m2].
Required fields:
  nut    | Turbulent viscosity                   [m2/s]
  k      | Turbulent kinetic energy              [m2/s2]
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries (unmodifiable)
    type            atmTurbulentHeatFluxTemperature;
    heatSource      flux;
    alphaEff        alphaEff;
    // Mandatory entries (runtime modifiable)
    Cp0             0.001;
    q               uniform 10;
    // Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
heatSource Heat source type word yes -
alphaEff
Name of turbulent thermal diff. field [kg/m/s]
word yes -
Cp0
Specific heat capacity [m2/s2/K]
Function1<scalar> yes -
q
Heat source value [W (power) or W/m2 (flux)]
PatchFunction1<scalar> yes -
The inherited entries are elaborated in:
fixedGradientFvPatchScalarField.H
Function1.H
PatchFunction1.H
Options for the heatSource entry:
      power  | Absolute power heat source [W]
      flux   | Flux heat source           [W/m2]
Source files
atmTurbulentHeatFluxTemperatureFvPatchScalarField.H
atmTurbulentHeatFluxTemperatureFvPatchScalarField.C
Definition at line 139 of file atmTurbulentHeatFluxTemperatureFvPatchScalarField.H.
Constructor & Destructor Documentation
atmTurbulentHeatFluxTemperatureFvPatchScalarField() [1/5]
atmTurbulentHeatFluxTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 48 of file atmTurbulentHeatFluxTemperatureFvPatchScalarField.C.
atmTurbulentHeatFluxTemperatureFvPatchScalarField() [2/5]
atmTurbulentHeatFluxTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 80 of file atmTurbulentHeatFluxTemperatureFvPatchScalarField.C.
References dict, and Foam::Zero.
atmTurbulentHeatFluxTemperatureFvPatchScalarField() [3/5]
atmTurbulentHeatFluxTemperatureFvPatchScalarField (const atmTurbulentHeatFluxTemperatureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 63 of file atmTurbulentHeatFluxTemperatureFvPatchScalarField.C.
atmTurbulentHeatFluxTemperatureFvPatchScalarField() [4/5]
atmTurbulentHeatFluxTemperatureFvPatchScalarField (const atmTurbulentHeatFluxTemperatureFvPatchScalarField & atmpsf)
Definition at line 110 of file atmTurbulentHeatFluxTemperatureFvPatchScalarField.C.
atmTurbulentHeatFluxTemperatureFvPatchScalarField() [5/5]
atmTurbulentHeatFluxTemperatureFvPatchScalarField (const atmTurbulentHeatFluxTemperatureFvPatchScalarField & atmpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 124 of file atmTurbulentHeatFluxTemperatureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("atmTurbulentHeatFluxTemperature")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 212 of file atmTurbulentHeatFluxTemperatureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 228 of file atmTurbulentHeatFluxTemperatureFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 141 of file atmTurbulentHeatFluxTemperatureFvPatchScalarField.C.
References Field< scalar >::autoMap().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 151 of file atmTurbulentHeatFluxTemperatureFvPatchScalarField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 166 of file atmTurbulentHeatFluxTemperatureFvPatchScalarField.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::gSum(), and Foam::nl.
write()
void write (Ostream & os) const virtual
Definition at line 216 of file atmTurbulentHeatFluxTemperatureFvPatchScalarField.C.
References os(), fixedGradientFvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/atmosphericModels/derivedFvPatchFields/atmTurbulentHeatFluxTemperature/atmTurbulentHeatFluxTemperatureFvPatchScalarField.H
src/atmosphericModels/derivedFvPatchFields/atmTurbulentHeatFluxTemperature/atmTurbulentHeatFluxTemperatureFvPatchScalarField.C