OpenFOAM: sigma< BasicTurbulenceModel > Class Template Reference
sigma< BasicTurbulenceModel > Class Template Reference
Turbulence models » LES turbulence
The sigma SGS model.
#include <sigma.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from LESeddyViscosity< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("sigma")
sigma (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~sigma ()
virtual bool read ()
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual void correct ()
Public Member Functions inherited from LESeddyViscosity< BasicTurbulenceModel >
LESeddyViscosity (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
virtual ~LESeddyViscosity ()=default
Public Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
virtual void correctNut ()
Protected Attributes
dimensionedScalar Ck_
dimensionedScalar Cw_
dimensionedScalar Csigma_
Protected Attributes inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::sigma< BasicTurbulenceModel >
The sigma SGS model.
Reference:
    Nicoud, F., Toda, H. B., Cabrit, O., Bose, S., & Lee, J. (2011).
    Using singular values to build a subgrid-scale
    model for large eddy simulations.
    Physics of fluids, 23(8), 085106.
    DOI:10.1063/1.3623274
The default model coefficients correspond to the following:
    sigmaCoeffs
    {
        ck          0.094;
        Csigma      1.68;
    }
Note
The default value of the Csigma constant implemented was calibrated for OpenFOAM using decaying isotropic turbulence and is slightly higher than the value suggested in the reference publication.
Source files
sigma.H
sigma.C
Definition at line 77 of file sigma.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 107 of file sigma.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 108 of file sigma.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 109 of file sigma.H.
Constructor & Destructor Documentation
sigma()
template<class BasicTurbulenceModel > sigma (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 50 of file sigma.C.
References Foam::type().
~sigma()
template<class BasicTurbulenceModel > virtual ~sigma () inline virtual
Definition at line 133 of file sigma.H.
Member Function Documentation
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 36 of file sigma.C.
References delta, Foam::fvc::grad(), options::New(), Foam::sqr(), and DESModel< BasicTurbulenceModel >::Ssigma().
TypeName()
template<class BasicTurbulenceModel > TypeName ("sigma< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented from LESeddyViscosity< BasicTurbulenceModel >.
Definition at line 114 of file sigma.C.
k()
template<class BasicTurbulenceModel > tmp< volScalarField > k () const virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 130 of file sigma.C.
References delta, Foam::devSymm(), Foam::fvc::grad(), IOobject::groupName(), Foam::magSqr(), tmp< T >::New(), and Foam::sqr().
epsilon()
template<class BasicTurbulenceModel > tmp< volScalarField > epsilon () const virtual
Definition at line 143 of file sigma.C.
References delta, IOobject::groupName(), k, tmp< T >::New(), and Foam::sqrt().
correct()
template<class BasicTurbulenceModel > void correct () virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 154 of file sigma.C.
References linearViscousStress< BasicTurbulenceModel >::correct().
Member Data Documentation
Ck_
template<class BasicTurbulenceModel > dimensionedScalar Ck_ protected
Definition at line 94 of file sigma.H.
Cw_
template<class BasicTurbulenceModel > dimensionedScalar Cw_ protected
Definition at line 95 of file sigma.H.
Csigma_
template<class BasicTurbulenceModel > dimensionedScalar Csigma_ protected
Definition at line 96 of file sigma.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/sigma/sigma.H
src/TurbulenceModels/turbulenceModels/LES/sigma/sigma.C