OpenFOAM: MPPICParcel< ParcelType >::trackingData Class Reference
MPPICParcel< ParcelType >::trackingData Class Reference
#include <MPPICParcel.H>
Public Types
enum trackPart { tpLinearTrack , tpDampingNoTrack , tpPackingNoTrack , tpCorrectTrack }
Public Member Functions
template<class TrackCloudType >
trackingData (const TrackCloudType &cloud, trackPart part=tpLinearTrack)
template<class TrackCloudType >
void updateAverages (const TrackCloudType &cloud)
trackPart part () const
trackPart & part ()
Detailed Description
template<class ParcelType>
class Foam::MPPICParcel< ParcelType >::trackingData
Definition at line 83 of file MPPICParcel.H.
Member Enumeration Documentation
trackPart
template<class ParcelType > enum trackPart
Enumerator
tpLinearTrack
tpDampingNoTrack
tpPackingNoTrack
tpCorrectTrack
Definition at line 90 of file MPPICParcel.H.
Constructor & Destructor Documentation
trackingData()
template<class ParcelType > template<class TrackCloudType > trackingData (const TrackCloudType & cloud, trackPart part = tpLinearTrack) inline
Definition at line 28 of file MPPICParcelTrackingDataI.H.
References Foam::name(), and Foam::New().
Member Function Documentation
updateAverages()
template<class ParcelType > template<class TrackCloudType > void updateAverages (const TrackCloudType & cloud) inline
Definition at line 139 of file MPPICParcelTrackingDataI.H.
References IOobject::db(), f(), Foam::mag(), Foam::magSqr(), IOobject::name(), p, Foam::pow(), Foam::pow3(), Foam::sqr(), and Foam::Zero.
part() [1/2]
template<class ParcelType > Foam::MPPICParcel< ParcelType >::trackingData::trackPart part () const inline
Definition at line 242 of file MPPICParcelTrackingDataI.H.
part() [2/2]
template<class ParcelType > Foam::MPPICParcel< ParcelType >::trackingData::trackPart & part () inline
Definition at line 250 of file MPPICParcelTrackingDataI.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcel.H
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcelTrackingDataI.H