OpenFOAM: coupledFvPatch Class Reference
coupledFvPatch Class Reference abstract
An abstract base class for patches that couple regions of the computational domain e.g. cyclic and processor-processor links.
#include <coupledFvPatch.H>
Public Member Functions
TypeNameNoDebug (coupledPolyPatch::typeName_())
coupledFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
virtual ~coupledFvPatch ()=default
virtual bool coupled () const
virtual bool parallel () const =0
virtual const tensorField & forwardT () const =0
virtual const tensorField & reverseT () const =0
virtual const labelUList & faceCells () const
virtual tmp< vectorField > delta () const =0
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const =0
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData, const labelUList &faceCell) const =0
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList &iF) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList &iF, const labelUList &faceCell) const
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const =0
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF, const labelUList &faceCells) const
Public Member Functions inherited from lduInterface
TypeNameNoDebug ("lduInterface")
lduInterface () noexcept=default
virtual ~lduInterface ()=default
Public Member Functions inherited from fvPatch
virtual void makeDeltaCoeffs (scalarField &) const
virtual void makeNonOrthoDeltaCoeffs (scalarField &) const
virtual void makeNonOrthoCorrVectors (vectorField &) const
virtual void initMovePoints ()
virtual void movePoints ()
TypeName (polyPatch::typeName_())
declareRunTimeSelectionTable (autoPtr, fvPatch, polyPatch,(const polyPatch &patch, const fvBoundaryMesh &bm),(patch, bm))
fvPatch (const polyPatch &, const fvBoundaryMesh &)
virtual ~fvPatch ()
const polyPatch & patch () const noexcept
virtual const word & name () const
label index () const noexcept
label start () const noexcept
virtual label size () const
const fvBoundaryMesh & boundaryMesh () const noexcept
template<class T >
const List< T >::subList patchSlice (const List< T > &values) const
template<class T >
const List< T >::subList boundarySlice (const List< T > &values) const
const vectorField & Cf () const
tmp< vectorField > Cn () const
const vectorField & Sf () const
const scalarField & magSf () const
tmp< vectorField > unitSf () const
tmp< vectorField > nf () const
const scalarField & weights () const
const scalarField & deltaCoeffs () const
template<class Type >
void patchInternalField (const UList< Type > &internalData, const labelUList &addressing, Field< Type > &pfld) const
template<class Type >
void patchInternalField (const UList< Type > &internalData, Field< Type > &pfld) const
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &internalData) const
template<class GeometricField , class AnyType = bool>
const GeometricField::Patch & patchField (const GeometricField &gf) const
template<class GeometricField , class AnyType = bool>
const GeometricField::Patch & lookupPatchField (const word &name, const GeometricField *=nullptr, const AnyType *=nullptr) const
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &internalData) const
Protected Member Functions
virtual void makeWeights (scalarField &) const =0
Friends
class surfaceInterpolation
Additional Inherited Members
Public Types inherited from fvPatch
typedef fvBoundaryMesh BoundaryMesh
Static Public Member Functions inherited from fvPatch
static autoPtr< fvPatch > New (const polyPatch &, const fvBoundaryMesh &)
static const fvPatch & lookupPatch (const polyPatch &p)
static bool constraintType (const word &patchType)
static wordList constraintTypes ()
Detailed Description
An abstract base class for patches that couple regions of the computational domain e.g. cyclic and processor-processor links.
Source files
coupledFvPatch.H
coupledFvPatch.C
Definition at line 49 of file coupledFvPatch.H.
Constructor & Destructor Documentation
coupledFvPatch()
coupledFvPatch (const polyPatch & patch, const fvBoundaryMesh & bm) inline
Definition at line 79 of file coupledFvPatch.H.
~coupledFvPatch()
virtual ~coupledFvPatch () virtual default
Member Function Documentation
makeWeights()
virtual void makeWeights (scalarField &) const protected pure virtual
Reimplemented from fvPatch.
Implemented in cyclicFvPatch, cyclicACMIFvPatch, cyclicAMIFvPatch, and processorFvPatch.
TypeNameNoDebug()
TypeNameNoDebug (coupledPolyPatch::typeName_())
coupled()
virtual bool coupled () const inline virtual
Reimplemented from fvPatch.
Reimplemented in cyclicACMIFvPatch, cyclicAMIFvPatch, and processorFvPatch.
Definition at line 95 of file coupledFvPatch.H.
References coupledPolyPatch::coupled().
parallel()
virtual bool parallel () const pure virtual
Implemented in cyclicFvPatch, cyclicACMIFvPatch, cyclicAMIFvPatch, processorFvPatch, and processorCyclicFvPatch.
forwardT()
virtual const tensorField & forwardT () const pure virtual
Implemented in cyclicFvPatch, cyclicACMIFvPatch, cyclicAMIFvPatch, processorFvPatch, and processorCyclicFvPatch.
reverseT()
virtual const tensorField & reverseT () const pure virtual
Implemented in cyclicFvPatch, cyclicACMIFvPatch, cyclicAMIFvPatch, processorFvPatch, and processorCyclicFvPatch.
faceCells()
virtual const labelUList & faceCells () const inline virtual
Implements lduInterface.
Definition at line 110 of file coupledFvPatch.H.
References fvPatch::faceCells().
Referenced by cyclicACMIFvPatchField< Type >::patchNeighbourField().
delta()
Foam::tmp< Foam::vectorField > delta () const pure virtual
Reimplemented from fvPatch.
Implemented in cyclicFvPatch, cyclicACMIFvPatch, cyclicAMIFvPatch, and processorFvPatch.
Definition at line 33 of file coupledFvPatch.C.
References fvPatch::Cf(), and fvPatch::Cn().
Referenced by cyclicFvPatch::delta(), cyclicACMIFvPatch::delta(), cyclicAMIFvPatch::delta(), processorFvPatch::delta(), cyclicFvPatch::makeWeights(), cyclicACMIFvPatch::makeWeights(), cyclicAMIFvPatch::makeWeights(), and processorFvPatch::makeWeights().
interfaceInternalField() [1/2]
virtual tmp< labelField > interfaceInternalField (const labelUList & internalData) const pure virtual
Implements lduInterface.
Implemented in cyclicFvPatch, cyclicACMIFvPatch, cyclicAMIFvPatch, and processorFvPatch.
interfaceInternalField() [2/2]
virtual tmp< labelField > interfaceInternalField (const labelUList & internalData, const labelUList & faceCell) const pure virtual
Implements lduInterface.
Implemented in cyclicFvPatch, cyclicACMIFvPatch, cyclicAMIFvPatch, and processorFvPatch.
initInternalFieldTransfer() [1/4]
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList & iF) const inline virtual
Reimplemented in processorFvPatch.
Definition at line 141 of file coupledFvPatch.H.
initInternalFieldTransfer() [2/4]
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList & iF, const labelUList & faceCell) const inline virtual
Reimplemented in processorFvPatch.
Definition at line 149 of file coupledFvPatch.H.
internalFieldTransfer()
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const pure virtual
Implements lduInterface.
Implemented in cyclicFvPatch, cyclicACMIFvPatch, cyclicAMIFvPatch, and processorFvPatch.
initInternalFieldTransfer() [3/4]
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const inline virtual
Reimplemented from lduInterface.
Reimplemented in processorFvPatch, and processorFvPatch.
Definition at line 97 of file lduInterface.H.
initInternalFieldTransfer() [4/4]
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF, const labelUList & faceCells) const inline virtual
Reimplemented from lduInterface.
Reimplemented in processorFvPatch, and processorFvPatch.
Definition at line 106 of file lduInterface.H.
Friends And Related Symbol Documentation
surfaceInterpolation
friend class surfaceInterpolation friend
Definition at line 69 of file coupledFvPatch.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvPatches/basic/coupled/coupledFvPatch.H
src/finiteVolume/fvMesh/fvPatches/basic/coupled/coupledFvPatch.C