OpenFOAM: rawWriter Class Reference
rawWriter Class Reference
A coordSet(s) in raw format.
#include <rawCoordSetWriter.H>
Public Member Functions
TypeNameNoDebug ("raw")
rawWriter ()
rawWriter (const dictionary &options)
rawWriter (const coordSet &coords, const fileName &outputPath, const dictionary &options=dictionary())
rawWriter (const UPtrList< coordSet > &tracks, const fileName &outputPath, const dictionary &options=dictionary())
virtual ~rawWriter ()
virtual bool buffering (const bool on)
virtual fileName path () const
declareCoordSetWriterWriteMethod (label)
declareCoordSetWriterWriteMethod (scalar)
declareCoordSetWriterWriteMethod (vector)
declareCoordSetWriterWriteMethod (sphericalTensor)
declareCoordSetWriterWriteMethod (symmTensor)
declareCoordSetWriterWriteMethod (tensor)
template<class Type >
Foam::fileName writeTemplate (const word &fieldName, const Field< Type > &values)
template<class Type >
Foam::fileName writeTemplate (const word &fieldName, const List< Field< Type > > &fieldValues)
template<class Type >
Foam::fileName writeTemplate (const word &fieldName, const UPtrList< const Field< Type > > &fieldPtrs)
template<class Type >
Foam::fileName writeTemplate (const word &fieldName, const Field< Type > &localValues)
Public Member Functions inherited from coordSetWriter
TypeName ("coordSetWriter")
declareRunTimeSelectionTable (autoPtr, coordSetWriter, word,(),())
declareRunTimeSelectionTable (autoPtr, coordSetWriter, wordDict,(const dictionary &writeOptions),(writeOptions))
coordSetWriter ()
coordSetWriter (const dictionary &options)
virtual ~coordSetWriter ()
virtual bool buffering () const
virtual bool enabled () const
virtual bool needsUpdate () const
virtual bool wroteData () const
virtual bool expire ()
virtual void clear ()
virtual void setCoordinates (const coordSet *coords)
virtual void setCoordinates (const coordSet &coords)
virtual void setTracks (const UPtrList< coordSet > &tracks)
virtual void setTrackTimes (const UList< scalarField > &times)
label numPoints () const
label numTracks () const
bool hasCoords () const
bool empty () const
bool is_open () const noexcept
label nFields () const noexcept
label nFields (const label n) noexcept
bool useTracks () const noexcept
bool useTracks (const bool on) noexcept
bool useTimeDir () const noexcept
bool useTimeDir (const bool on) noexcept
bool verbose () const noexcept
bool verbose (bool on) noexcept
bool hasTime () const
const word & timeName () const
scalar timeValue () const
void setTime (const instant &inst)
void setTime (scalar timeValue)
void setTime (scalar timeValue, const word &timeName)
void unsetTime ()
virtual void beginTime (const Time &t)
virtual void beginTime (const instant &inst)
virtual void endTime ()
virtual void open (const fileName &outputPath)
TBD: virtual fileName write() = 0;.
virtual void open (const coordSet &coords, const fileName &outputPath)
virtual void open (const UPtrList< coordSet > &tracks, const fileName &outputPath)
virtual void close (bool force=false)
virtual InfoProxy< coordSetWriter > info () const
virtual fileName write (const word &fieldName, const Field< label > &field)=0
Write field of label (point data)
virtual fileName write (const word &fieldName, const List< Field< label > > &fieldValues)=0
Write track fields of label (point data)
virtual fileName write (const word &fieldName, const Field< scalar > &field)=0
Write field of scalar (point data)
virtual fileName write (const word &fieldName, const List< Field< scalar > > &fieldValues)=0
Write track fields of scalar (point data)
virtual fileName write (const word &fieldName, const Field< vector > &field)=0
Write field of vector (point data)
virtual fileName write (const word &fieldName, const List< Field< vector > > &fieldValues)=0
Write track fields of vector (point data)
virtual fileName write (const word &fieldName, const Field< sphericalTensor > &field)=0
Write field of sphericalTensor (point data)
virtual fileName write (const word &fieldName, const List< Field< sphericalTensor > > &fieldValues)=0
Write track fields of sphericalTensor (point data)
virtual fileName write (const word &fieldName, const Field< symmTensor > &field)=0
Write field of symmTensor (point data)
virtual fileName write (const word &fieldName, const List< Field< symmTensor > > &fieldValues)=0
Write track fields of symmTensor (point data)
virtual fileName write (const word &fieldName, const Field< tensor > &field)=0
Write field of tensor (point data)
virtual fileName write (const word &fieldName, const List< Field< tensor > > &fieldValues)=0
Write track fields of tensor (point data)
template<class Type >
Foam::UPtrList< const Foam::Field< Type > > repackageFields (const Field< Type > &field)
template<class Type >
Foam::UPtrList< const Foam::Field< Type > > repackageFields (const UList< Field< Type > > &fieldValues)
Protected Member Functions
virtual bool writeBuffered ()
Protected Member Functions inherited from coordSetWriter
void appendField (const word &fieldName, const Field< label > &vals)
void appendField (const word &fieldName, const Field< scalar > &vals)
void appendField (const word &fieldName, const Field< vector > &vals)
void appendField (const word &fieldName, const Field< sphericalTensor > &vals)
void appendField (const word &fieldName, const Field< symmTensor > &vals)
void appendField (const word &fieldName, const Field< tensor > &vals)
void clearBuffers ()
label nDataColumns () const
void writeBufferContents (Ostream &os, const coordSet &coords, const char *sep) const
void getBufferLine (DynamicList< scalar > &buf, const coordSet &coords, const label pointi) const
fileName getExpectedPath (const word &fileExt=word::null) const
fileName getFieldPrefixedPath (const word &fieldName, const word &fileExt=word::null) const
void checkOpen () const
virtual bool merge () const
template<class Type >
fileName writeTemplate (const word &fieldName, const Field< Type > &values)
template<class Type >
fileName writeTemplate (const word &fieldName, const List< Field< Type > > &fieldValues)
coordSetWriter (const coordSetWriter &)=delete
void operator= (const coordSetWriter &)=delete
Additional Inherited Members
Static Public Member Functions inherited from coordSetWriter
static dictionary formatOptions (const dictionary &dict, const word &formatName, const word &entryName="formatOptions")
static dictionary formatOptions (const dictionary &dict, const dictionary &setDict, const word &formatName, const word &entryName="formatOptions")
static bool supportedType (const word &writeType)
static autoPtr< coordSetWriter > New (const word &writeFormat)
static autoPtr< coordSetWriter > New (const word &writeFormat, const dictionary &writeOptions)
static word suffix (const word &fldName, const word &fileExt=word::null)
static word suffix (const wordList &fieldNames, const word &fileExt=word::null)
Static Protected Member Functions inherited from coordSetWriter
static void writeLine (Ostream &, const UList< word > &, const char *sep)
static void writeLine (Ostream &, const UList< scalar > &, const char *sep)
template<class Type >
static UPtrList< const Field< Type > > repackageFields (const Field< Type > &field)
template<class Type >
static UPtrList< const Field< Type > > repackageFields (const UList< Field< Type > > &fieldValues)
template<class Type >
static void writeTable (Ostream &os, const coordSet &coords, const UList< Type > &values, const char *sep)
Protected Attributes inherited from coordSetWriter
UPtrList< const coordSet > coords_
List< scalarField > trackTimes_
bool upToDate_
bool wroteGeom_
bool buffering_
bool useTracks_
bool useTimeDir_
bool verbose_
label nFields_
instant currTime_
fileName outputPath_
DynamicList< word > labelNames_
PtrDynList< Field< label > > labelFields_
DynamicList< word > scalarNames_
PtrDynList< Field< scalar > > scalarFields_
DynamicList< word > vectorNames_
PtrDynList< Field< vector > > vectorFields_
DynamicList< word > sphericalTensorNames_
PtrDynList< Field< sphericalTensor > > sphericalTensorFields_
DynamicList< word > symmTensorNames_
PtrDynList< Field< symmTensor > > symmTensorFields_
DynamicList< word > tensorNames_
PtrDynList< Field< tensor > > tensorFields_
Detailed Description
A coordSet(s) in raw format.
The formatOptions for raw:
Property Description Required Default
buffer Use buffered output no true
compression Use file compression no false
precision Write precision in ascii no same as IOstream
When called with a single coordSet, will buffer the output of all fields and output together in the order of label/scalar/vector/... each of which is sorted alphabetically according to the field name.
When called as a track writer (eg, with multiple coordSets), will emit one file per field.
Source files
rawCoordSetWriter.H
rawCoordSetWriter.C
Definition at line 83 of file rawCoordSetWriter.H.
Constructor & Destructor Documentation
rawWriter() [1/4]
rawWriter ()
Definition at line 52 of file rawCoordSetWriter.C.
References coordSetWriter::buffering_.
rawWriter() [2/4]
rawWriter (const dictionary & options) explicit
Definition at line 62 of file rawCoordSetWriter.C.
References coordSetWriter::buffering_, and dictionary::getOrDefault().
rawWriter() [3/4]
rawWriter (const coordSet & coords, const fileName & outputPath, const dictionary & options = dictionary())
Definition at line 79 of file rawCoordSetWriter.C.
References coordSetWriter::open().
rawWriter() [4/4]
rawWriter (const UPtrList< coordSet > & tracks, const fileName & outputPath, const dictionary & options = dictionary())
Definition at line 92 of file rawCoordSetWriter.C.
References coordSetWriter::open().
~rawWriter()
~rawWriter () virtual
Definition at line 107 of file rawCoordSetWriter.C.
Member Function Documentation
writeBuffered()
bool writeBuffered () protected virtual
Reimplemented from coordSetWriter.
Definition at line 136 of file rawCoordSetWriter.C.
References Foam::isDir(), Foam::mkDir(), os(), and path().
TypeNameNoDebug()
TypeNameNoDebug ("raw")
buffering()
bool buffering (const bool on) virtual
Reimplemented from coordSetWriter.
Definition at line 115 of file rawCoordSetWriter.C.
path()
Foam::fileName path () const virtual
Implements coordSetWriter.
Definition at line 125 of file rawCoordSetWriter.C.
declareCoordSetWriterWriteMethod() [1/6]
declareCoordSetWriterWriteMethod (label)
declareCoordSetWriterWriteMethod() [2/6]
declareCoordSetWriterWriteMethod (scalar)
declareCoordSetWriterWriteMethod() [3/6]
declareCoordSetWriterWriteMethod (vector)
declareCoordSetWriterWriteMethod() [4/6]
declareCoordSetWriterWriteMethod (sphericalTensor)
declareCoordSetWriterWriteMethod() [5/6]
declareCoordSetWriterWriteMethod (symmTensor)
declareCoordSetWriterWriteMethod() [6/6]
declareCoordSetWriterWriteMethod (tensor)
writeTemplate() [1/4]
template<class Type > Foam::fileName writeTemplate (const word & fieldName, const Field< Type > & values)
Definition at line 168 of file rawCoordSetWriter.C.
References fileName::null, and path().
writeTemplate() [2/4]
template<class Type > Foam::fileName writeTemplate (const word & fieldName, const List< Field< Type > > & fieldValues)
Definition at line 193 of file rawCoordSetWriter.C.
References fileName::null.
writeTemplate() [3/4]
template<class Type > Foam::fileName writeTemplate (const word & fieldName, const UPtrList< const Field< Type > > & fieldPtrs)
Definition at line 80 of file rawCoordSetWriterImpl.C.
References coordSetWriter::coords_, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, coordSetWriter::getFieldPrefixedPath(), Foam::Info, Foam::isDir(), Foam::mkDir(), Foam::nl, nPoints, os(), pts, UPtrList< T >::size(), coordSetWriter::verbose_, Foam::writeCoordHeader(), coordSetWriter::writeTable(), and coordSetWriter::wroteGeom_.
writeTemplate() [4/4]
template<class Type > Foam::fileName writeTemplate (const word & fieldName, const Field< Type > & localValues)
Definition at line 80 of file rawSurfaceWriterImpl.C.
References surfaceWriter::adjustField(), surfaceWriter::adjustSurface(), surfaceWriter::checkOpen(), surfaceWriter::empty(), Foam::endl(), f(), meshedSurfRef::faces(), forAll, Foam::Info, Foam::isDir(), surfaceWriter::isPointData(), UPstream::master(), surfaceWriter::mergeField(), Foam::mkDir(), fileName::name(), Foam::nl, os(), surfaceWriter::outputPath_, surfaceWriter::parallel_, fileName::path(), points, meshedSurfRef::points(), surfaceWriter::timeName(), surfaceWriter::useTimeDir(), surfaceWriter::verbose_, Foam::writeData(), Foam::writeHeaderArea(), Foam::writePoint(), and surfaceWriter::wroteGeom_.
The documentation for this class was generated from the following files:
src/meshTools/coordSet/writers/raw/rawCoordSetWriter.H
src/meshTools/coordSet/writers/raw/rawCoordSetWriter.C
src/meshTools/coordSet/writers/raw/rawCoordSetWriterImpl.C
src/surfMesh/writers/raw/rawSurfaceWriterImpl.C