OpenFOAM: simpleGeomDecomp Class Reference
simpleGeomDecomp Class Reference
Simple geometric decomposition, selectable as simple.
#include <simpleGeomDecomp.H>
Public Member Functions
void operator= (const simpleGeomDecomp &)=delete
simpleGeomDecomp (const simpleGeomDecomp &)=delete
TypeName ("simple")
simpleGeomDecomp (const dictionary &decompDict, const word &regionName="")
virtual ~simpleGeomDecomp ()=default
virtual bool parallelAware () const
virtual labelList decompose (const pointField &points) const
virtual labelList decompose (const pointField &points, const scalarField &weights) const
virtual labelList decompose (const polyMesh &mesh, const pointField &points) const
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &weights) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights) const
Public Member Functions inherited from geomDecomp
geomDecomp (const word &derivedType, const dictionary &decompDict, int select=selectionType::DEFAULT)
geomDecomp (const word &derivedType, const dictionary &decompDict, const word &regionName, int select=selectionType::DEFAULT)
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompDict, const word &regionName),(decompDict, regionName))
decompositionMethod (const dictionary &decompDict, const word &regionName="")
virtual ~decompositionMethod ()=default
label nDomains () const noexcept
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights) const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc) const
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp) const
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections) const
labelList decompose (const polyMesh &mesh, const scalarField &cWeights) const
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static label nDomains (const dictionary &decompDict, const word &regionName="")
static const dictionary & optionalRegionDict (const dictionary &decompDict, const word &regionName)
static autoPtr< decompositionMethod > New (const dictionary &decompDict, const word &regionName="")
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Protected Types inherited from decompositionMethod
enum selectionType { DEFAULT = 0 , EXACT = 1 , MANDATORY = 2 , NULL_DICT = 4 }
Protected Member Functions inherited from geomDecomp
tmp< pointField > adjustPoints (const pointField &) const
void checkDecompositionDirections (const Vector< label > &) const
Protected Member Functions inherited from decompositionMethod
const dictionary & findCoeffsDict (const word &coeffsName, int select=selectionType::DEFAULT) const
Static Protected Member Functions inherited from decompositionMethod
static const dictionary & findCoeffsDict (const dictionary &dict, const word &coeffsName, int select=selectionType::DEFAULT)
Protected Attributes inherited from geomDecomp
Vector< label > n_
Vector< direction > order_
const dictionary & coeffsDict_
Protected Attributes inherited from decompositionMethod
const dictionary & decompDict_
const dictionary & decompRegionDict_
label nDomains_
PtrList< decompositionConstraint > constraints_
Detailed Description
Simple geometric decomposition, selectable as simple.
Method coefficients:
Property Description Required Default
n (nx ny nz) yes
order order of operation (unused) no xyz
delta delta (jitter) for rotation matrix no 0.001
transform cartesian coordinate transformation no
Source files
simpleGeomDecomp.H
simpleGeomDecomp.C
Definition at line 79 of file simpleGeomDecomp.H.
Constructor & Destructor Documentation
simpleGeomDecomp() [1/2]
simpleGeomDecomp (const simpleGeomDecomp &) delete
simpleGeomDecomp() [2/2]
simpleGeomDecomp (const dictionary & decompDict, const word & regionName = "") explicit
Definition at line 310 of file simpleGeomDecomp.C.
~simpleGeomDecomp()
virtual ~simpleGeomDecomp () virtual default
Member Function Documentation
operator=()
void operator= (const simpleGeomDecomp &) delete
TypeName()
TypeName ("simple")
parallelAware()
virtual bool parallelAware () const inline virtual
Implements decompositionMethod.
Definition at line 138 of file simpleGeomDecomp.H.
decompose() [1/5]
Foam::labelList decompose (const pointField & points) const virtual
Implements geomDecomp.
Definition at line 322 of file simpleGeomDecomp.C.
References PtrList< T >::clear(), UPstream::master(), UPstream::parRun(), points, and UPtrList< T >::size().
Referenced by simpleGeomDecomp::decompose(), simpleGeomDecomp::decompose(), and simpleGeomDecomp::decompose().
decompose() [2/5]
Foam::labelList decompose (const pointField & points, const scalarField & weights) const virtual
Implements geomDecomp.
Definition at line 349 of file simpleGeomDecomp.C.
References PtrList< T >::clear(), UPstream::master(), UPstream::parRun(), points, Foam::returnReduceOr(), UPtrList< T >::size(), and UList< T >::size().
decompose() [3/5]
virtual labelList decompose (const polyMesh & mesh, const pointField & points) const inline virtual
Reimplemented from decompositionMethod.
Definition at line 154 of file simpleGeomDecomp.H.
References geomDecomp::checkDecompositionDirections(), simpleGeomDecomp::decompose(), mesh, and points.
decompose() [4/5]
virtual labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & weights) const inline virtual
Implements decompositionMethod.
Definition at line 165 of file simpleGeomDecomp.H.
References geomDecomp::checkDecompositionDirections(), simpleGeomDecomp::decompose(), mesh, and points.
decompose() [5/5]
virtual labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) const inline virtual
Implements decompositionMethod.
Definition at line 177 of file simpleGeomDecomp.H.
References simpleGeomDecomp::decompose().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/simpleGeomDecomp/simpleGeomDecomp.H
src/parallel/decompose/decompositionMethods/simpleGeomDecomp/simpleGeomDecomp.C