OpenFOAM: sixDoFSolver Class Reference
sixDoFSolver Class Reference abstract
Mesh motion » Six Degree of Freedom (DoF) » Solvers
#include <sixDoFSolver.H>
Public Member Functions
TypeName ("sixDoFSolver")
declareRunTimeSelectionTable (autoPtr, sixDoFSolver, dictionary,(const dictionary &dict, sixDoFRigidBodyMotion &body),(dict, body))
sixDoFSolver (const dictionary &dict, sixDoFRigidBodyMotion &body)
virtual autoPtr< sixDoFSolver > clone () const =0
virtual ~sixDoFSolver ()
virtual void solve (bool firstIter, const vector &fGlobal, const vector &tauGlobal, scalar deltaT, scalar deltaT0)=0
void write (Ostream &) const
Static Public Member Functions
static autoPtr< sixDoFSolver > New (const dictionary &dict, sixDoFRigidBodyMotion &body)
Protected Member Functions
point & centreOfRotation ()
tensor & Q ()
vector & v ()
vector & a ()
vector & pi ()
vector & tau ()
const point & centreOfRotation0 () const
const tensor & Q0 () const
const vector & v0 () const
const vector & a0 () const
const vector & pi0 () const
const vector & tau0 () const
scalar aDamp () const
tensor tConstraints () const
tensor rConstraints () const
Tuple2< tensor, vector > rotate (const tensor &Q0, const vector &pi, const scalar deltaT) const
void updateAcceleration (const vector &fGlobal, const vector &tauGlobal)
void updateConstraints ()
Protected Attributes
sixDoFRigidBodyMotion & body_
dictionary dict_
Detailed Description
Source files
sixDoFSolver.H
sixDoFSolver.C
newSixDoFSolver.C
Definition at line 51 of file sixDoFSolver.H.
Constructor & Destructor Documentation
sixDoFSolver()
sixDoFSolver (const dictionary & dict, sixDoFRigidBodyMotion & body)
Definition at line 35 of file sixDoFSolver.C.
~sixDoFSolver()
~sixDoFSolver () virtual
Definition at line 53 of file sixDoFSolver.C.
Member Function Documentation
centreOfRotation()
Foam::point & centreOfRotation () inline protected
Definition at line 24 of file sixDoFSolverI.H.
References sixDoFSolver::body_, and sixDoFRigidBodyMotionState::centreOfRotation().
Q()
Foam::tensor & Q () inline protected
Definition at line 29 of file sixDoFSolverI.H.
v()
Foam::vector & v () inline protected
Definition at line 34 of file sixDoFSolverI.H.
a()
Foam::vector & a () inline protected
Definition at line 39 of file sixDoFSolverI.H.
pi()
Foam::vector & pi () inline protected
Definition at line 44 of file sixDoFSolverI.H.
tau()
Foam::vector & tau () inline protected
Definition at line 49 of file sixDoFSolverI.H.
centreOfRotation0()
const Foam::point & centreOfRotation0 () const inline protected
Definition at line 55 of file sixDoFSolverI.H.
Q0()
const Foam::tensor & Q0 () const inline protected
Definition at line 60 of file sixDoFSolverI.H.
v0()
const Foam::vector & v0 () const inline protected
Definition at line 66 of file sixDoFSolverI.H.
a0()
const Foam::vector & a0 () const inline protected
Definition at line 72 of file sixDoFSolverI.H.
pi0()
const Foam::vector & pi0 () const inline protected
Definition at line 78 of file sixDoFSolverI.H.
tau0()
const Foam::vector & tau0 () const inline protected
Definition at line 84 of file sixDoFSolverI.H.
aDamp()
Foam::scalar aDamp () const inline protected
Definition at line 89 of file sixDoFSolverI.H.
tConstraints()
Foam::tensor tConstraints () const inline protected
Definition at line 94 of file sixDoFSolverI.H.
rConstraints()
Foam::tensor rConstraints () const inline protected
Definition at line 99 of file sixDoFSolverI.H.
rotate()
Foam::Tuple2< Foam::tensor, Foam::vector > rotate (const tensor & Q0, const vector & pi, const scalar deltaT) const inline protected
Definition at line 109 of file sixDoFSolverI.H.
updateAcceleration()
void updateAcceleration (const vector & fGlobal, const vector & tauGlobal) inline protected
Definition at line 122 of file sixDoFSolverI.H.
updateConstraints()
void updateConstraints () inline protected
Definition at line 131 of file sixDoFSolverI.H.
TypeName()
TypeName ("sixDoFSolver")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , sixDoFSolver , dictionary , (const dictionary &dict, sixDoFRigidBodyMotion &body) , (dict, body))
clone()
virtual autoPtr< sixDoFSolver > clone () const pure virtual
Implemented in CrankNicolson, Newmark, and symplectic.
New()
Foam::autoPtr< Foam::sixDoFSolver > New (const dictionary & dict, sixDoFRigidBodyMotion & body) static
Definition at line 26 of file sixDoFSolverNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
solve()
virtual void solve (bool firstIter, const vector & fGlobal, const vector & tauGlobal, scalar deltaT, scalar deltaT0) pure virtual
Implemented in CrankNicolson, Newmark, and symplectic.
write()
void write (Ostream & os) const
Definition at line 46 of file sixDoFSolver.C.
References os().
Member Data Documentation
body_
sixDoFRigidBodyMotion& body_ protected
Definition at line 58 of file sixDoFSolver.H.
Referenced by sixDoFSolver::centreOfRotation(), CrankNicolson::clone(), Newmark::clone(), and symplectic::clone().
dict_
dictionary dict_ protected
Definition at line 61 of file sixDoFSolver.H.
Referenced by CrankNicolson::clone(), Newmark::clone(), and symplectic::clone().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFSolvers/sixDoFSolver/sixDoFSolver.H
src/sixDoFRigidBodyMotion/sixDoFSolvers/sixDoFSolver/sixDoFSolver.C
src/sixDoFRigidBodyMotion/sixDoFSolvers/sixDoFSolver/sixDoFSolverI.H
src/sixDoFRigidBodyMotion/sixDoFSolvers/sixDoFSolver/sixDoFSolverNew.C