OpenFOAM: CorrectionLimitingMethod Class Reference
CorrectionLimitingMethod Class Reference abstract
Lagrangian particle models » Submodels » MP-PIC » Correction limiting
Base class for correction limiting methods.
#include <CorrectionLimitingMethod.H>
Public Member Functions
TypeName ("correctionLimitingMethod")
declareRunTimeSelectionTable (autoPtr, CorrectionLimitingMethod, dictionary,(const dictionary &dict),(dict))
CorrectionLimitingMethod (const dictionary &dict)
CorrectionLimitingMethod (const CorrectionLimitingMethod &cl)
virtual autoPtr< CorrectionLimitingMethod > clone () const =0
virtual ~CorrectionLimitingMethod ()
virtual vector limitedVelocity (const vector uP, const vector dU, const vector uMean) const =0
Static Public Member Functions
static autoPtr< CorrectionLimitingMethod > New (const dictionary &dict)
Detailed Description
Base class for correction limiting methods.
Source files
CorrectionLimitingMethod.H
CorrectionLimitingMethod.C
Definition at line 51 of file CorrectionLimitingMethod.H.
Constructor & Destructor Documentation
CorrectionLimitingMethod() [1/2]
CorrectionLimitingMethod (const dictionary & dict)
Definition at line 33 of file CorrectionLimitingMethod.C.
CorrectionLimitingMethod() [2/2]
CorrectionLimitingMethod (const CorrectionLimitingMethod & cl)
Definition at line 40 of file CorrectionLimitingMethod.C.
~CorrectionLimitingMethod()
~CorrectionLimitingMethod () virtual
Definition at line 78 of file CorrectionLimitingMethod.C.
Member Function Documentation
TypeName()
TypeName ("correctionLimitingMethod")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , CorrectionLimitingMethod , dictionary , (const dictionary &dict) , (dict))
clone()
virtual autoPtr< CorrectionLimitingMethod > clone () const pure virtual
Implemented in absolute, noCorrectionLimiting, and relative.
New()
Foam::autoPtr< Foam::CorrectionLimitingMethod > New (const dictionary & dict) static
Definition at line 50 of file CorrectionLimitingMethod.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
limitedVelocity()
virtual vector limitedVelocity (const vector uP, const vector dU, const vector uMean) const pure virtual
Implemented in absolute, noCorrectionLimiting, and relative.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/CorrectionLimitingMethods/CorrectionLimitingMethod/CorrectionLimitingMethod.H
src/lagrangian/intermediate/submodels/MPPIC/CorrectionLimitingMethods/CorrectionLimitingMethod/CorrectionLimitingMethod.C