OpenFOAM: LegendreMagnaudet Class Reference
LegendreMagnaudet Class Reference
Lift model of Legendre and Magnaudet.
#include <LegendreMagnaudet.H>
Public Member Functions
TypeName ("LegendreMagnaudet")
LegendreMagnaudet (const dictionary &dict, const phasePair &pair)
virtual ~LegendreMagnaudet ()
virtual tmp< volScalarField > Cl () const
TypeName ("LegendreMagnaudet")
LegendreMagnaudet (const dictionary &dict, const phasePair &pair)
virtual ~LegendreMagnaudet ()
virtual tmp< volScalarField > Cl () const
Public Member Functions inherited from liftModel
TypeName ("liftModel")
declareRunTimeSelectionTable (autoPtr, liftModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
liftModel (const dictionary &dict, const phasePair &pair)
virtual ~liftModel ()=default
virtual tmp< volVectorField > Fi () const
virtual tmp< volVectorField > F () const
virtual tmp< surfaceScalarField > Ff () const
TypeName ("liftModel")
declareRunTimeSelectionTable (autoPtr, liftModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
liftModel (const dictionary &dict, const phasePair &pair)
virtual ~liftModel ()=default
virtual tmp< volVectorField > Fi () const
virtual tmp< volVectorField > F () const
virtual tmp< surfaceScalarField > Ff () const
Additional Inherited Members
Static Public Member Functions inherited from liftModel
static autoPtr< liftModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< liftModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes inherited from liftModel
static const dimensionSet dimF
Protected Attributes inherited from liftModel
const phasePair & pair_
Detailed Description
Lift model of Legendre and Magnaudet.
References:
    Otromke, M. (2013).
    Implementation and Comparison of Correlations for interfacial Forces in
    a Gas-Liquid System within an Euler-Euler Framework.
    PhD Thesis.
    Legendre, D., & Magnaudet, J. (1998).
    The lift force on a spherical bubble in a viscous linear shear flow.
    Journal of Fluid Mechanics, 368, 81-126.
Source files
LegendreMagnaudet.H
LegendreMagnaudet.C
References:
    "Implementation and Comparison of Correlations for interfacial Forces
    in a Gas-Liquid System within an Euler-Euler Framework"
    Otromke, M.
    PhD Thesis
    April 2013
    "The lift force on a spherical bubble in a viscous linear shear flow"
    Legendre, D., Magnaudet, J.,
    Journal of Fluid Mechanics
    Volume 368, August 1998, pp. 81-126
Source files
LegendreMagnaudet.H
LegendreMagnaudet.C
Definition at line 65 of file LegendreMagnaudet.H.
Constructor & Destructor Documentation
LegendreMagnaudet() [1/2]
LegendreMagnaudet (const dictionary & dict, const phasePair & pair)
Definition at line 40 of file LegendreMagnaudet.C.
References Foam::dimless.
~LegendreMagnaudet() [1/2]
~LegendreMagnaudet () virtual
Definition at line 53 of file LegendreMagnaudet.C.
LegendreMagnaudet() [2/2]
LegendreMagnaudet (const dictionary & dict, const phasePair & pair)
~LegendreMagnaudet() [2/2]
virtual ~LegendreMagnaudet () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("LegendreMagnaudet")
Cl() [1/2]
Foam::tmp< Foam::volScalarField > Cl () const virtual
Implements liftModel.
Definition at line 59 of file LegendreMagnaudet.C.
References Foam::fvc::grad(), Foam::mag(), Foam::max(), Foam::constant::mathematical::pi(), Foam::pow3(), Foam::pow4(), Foam::Re(), Foam::sqr(), and Foam::sqrt().
TypeName() [2/2]
TypeName ("LegendreMagnaudet")
Cl() [2/2]
virtual tmp< volScalarField > Cl () const virtual
Implements liftModel.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/liftModels/LegendreMagnaudet/LegendreMagnaudet.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/liftModels/LegendreMagnaudet/LegendreMagnaudet.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/liftModels/LegendreMagnaudet/LegendreMagnaudet.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/liftModels/LegendreMagnaudet/LegendreMagnaudet.C