OpenFOAM: edgeMesh Class Reference
edgeMesh Class Reference
Mesh data needed to do the Finite Area discretisation.
#include <edgeFaMesh.H>
Public Member Functions
edgeMesh (const faMesh &mesh)
label size () const
const edgeVectorField & C () const
TypeName ("edgeMesh")
edgeMesh ()
edgeMesh (const edgeMesh &em)
edgeMesh (edgeMesh &&em)
edgeMesh (const pointField &points, const edgeList &edges)
edgeMesh (pointField &&pointLst, edgeList &&edgeLst)
edgeMesh (const fileName &name)
edgeMesh (const fileName &name, const word &fileType)
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()=default
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh, IOstreamOption streamOpt, const dictionary &options),(name, mesh, streamOpt, options))
void transfer (edgeMesh &mesh)
bool read (const fileName &name, const word &fileType)
virtual bool read (const fileName &name)
const pointField & points () const noexcept
const edgeList & edges () const noexcept
const labelListList & pointEdges () const
label regions (labelList &edgeRegion) const
virtual void clear ()
virtual void scalePoints (const scalar scaleFactor)
virtual void mergePoints (const scalar mergeDist)
virtual void mergeEdges ()
virtual void writeStats (Ostream &) const
virtual void write (const fileName &name, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
virtual void write (const fileName &name, const word &fileType, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
void operator= (const edgeMesh &rhs)
void operator= (edgeMesh &&rhs)
Public Member Functions inherited from GeoMesh< faMesh >
GeoMesh (const faMesh &mesh)
bool hasDb () const
const objectRegistry & thisDb () const
const faMesh & operator() () const
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()=default
virtual ~edgeMeshFormatsCore ()=default
Static Public Member Functions
static label size (const Mesh &mesh)
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static bool canReadType (const word &fileType, bool verbose=false)
static bool canWriteType (const word &fileType, bool verbose=false)
static bool canRead (const fileName &name, bool verbose=false)
static autoPtr< edgeMesh > New (const fileName &name, const word &fileType)
static autoPtr< edgeMesh > New (const fileName &name)
static void write (const fileName &name, const edgeMesh &mesh, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
static void write (const fileName &name, const word &fileType, const edgeMesh &mesh, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &fileType, const bool verbose=false, const char *functionName=nullptr)
Protected Member Functions
pointField & storedPoints () noexcept
edgeList & storedEdges () noexcept
Friends
Ostream & operator<< (Ostream &os, const edgeMesh &em)
Istream & operator>> (Istream &is, edgeMesh &em)
Additional Inherited Members
Public Types inherited from GeoMesh< faMesh >
typedef faMesh Mesh
typedef MESH::BoundaryMesh BoundaryMesh
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
Protected Attributes inherited from GeoMesh< faMesh >
const faMesh & mesh_
Detailed Description
Mesh data needed to do the Finite Area discretisation.
Points connected by edges.
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Can be read from fileName based on extension. Uses New factory method to select the reader and transfer the result.
Source files
edgeMesh.H
edgeMeshI.H
edgeMesh.C
edgeMeshIO.C
edgeMeshNew.C
Definition at line 47 of file edgeFaMesh.H.
Constructor & Destructor Documentation
edgeMesh() [1/8]
edgeMesh (const faMesh & mesh) inline explicit
Definition at line 56 of file edgeFaMesh.H.
edgeMesh() [2/8]
edgeMesh () inline
Definition at line 38 of file edgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
edgeMesh() [3/8]
edgeMesh (const edgeMesh & em) inline
Definition at line 47 of file edgeMeshI.H.
edgeMesh() [4/8]
edgeMesh (edgeMesh && em) inline
Definition at line 56 of file edgeMeshI.H.
References edgeMesh::transfer().
edgeMesh() [5/8]
edgeMesh (const pointField & points, const edgeList & edges) inline
Definition at line 64 of file edgeMeshI.H.
edgeMesh() [6/8]
edgeMesh (pointField && pointLst, edgeList && edgeLst) inline
Definition at line 77 of file edgeMeshI.H.
edgeMesh() [7/8]
edgeMesh (const fileName & name) explicit
Definition at line 42 of file edgeMeshIO.C.
References Foam::name(), and edgeMesh::read().
edgeMesh() [8/8]
edgeMesh (const fileName & name, const word & fileType)
Definition at line 28 of file edgeMeshIO.C.
References Foam::name(), and edgeMesh::read().
~edgeMesh()
virtual ~edgeMesh () virtual default
Member Function Documentation
size() [1/2]
static label size (const Mesh & mesh) inline static
Definition at line 64 of file edgeFaMesh.H.
References mesh.
size() [2/2]
label size () const inline
Definition at line 70 of file edgeFaMesh.H.
References GeoMesh< faMesh >::mesh_, and edgeMesh::size().
Referenced by edgeMesh::size().
C()
const edgeVectorField & C () const inline
Definition at line 76 of file edgeFaMesh.H.
References GeoMesh< faMesh >::mesh_.
storedPoints()
Foam::pointField & storedPoints () inline protected noexcept
Definition at line 24 of file edgeMeshI.H.
Referenced by extendedEdgeMesh::extendedEdgeMesh(), and extendedEdgeMesh::extendedEdgeMesh().
storedEdges()
Foam::edgeList & storedEdges () inline protected noexcept
Definition at line 30 of file edgeMeshI.H.
Referenced by extendedEdgeMesh::extendedEdgeMesh(), and extendedEdgeMesh::extendedEdgeMesh().
TypeName()
TypeName ("edgeMesh")
readTypes()
Foam::wordHashSet readTypes () static
Definition at line 42 of file edgeMesh.C.
writeTypes()
Foam::wordHashSet writeTypes () static
Definition at line 48 of file edgeMesh.C.
canReadType()
bool canReadType (const word & fileType, bool verbose = false) static
Definition at line 54 of file edgeMesh.C.
canWriteType()
bool canWriteType (const word & fileType, bool verbose = false) static
Definition at line 66 of file edgeMesh.C.
canRead()
bool canRead (const fileName & name, bool verbose = false) static
Definition at line 78 of file edgeMesh.C.
References word::ext(), word::has_ext(), and Foam::name().
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , edgeMesh , fileExtension , (const fileName &name) , (name))
New() [1/2]
Foam::autoPtr< Foam::edgeMesh > New (const fileName & name, const word & fileType) static
Definition at line 26 of file edgeMeshNew.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), Foam::name(), and Foam::nl.
New() [2/2]
Foam::autoPtr< Foam::edgeMesh > New (const fileName & name) static
Definition at line 48 of file edgeMeshNew.C.
References word::ext(), word::has_ext(), Foam::name(), and Foam::New().
declareMemberFunctionSelectionTable()
declareMemberFunctionSelectionTable (void , edgeMesh , write , fileExtension , (const fileName &name, const edgeMesh &mesh, IOstreamOption streamOpt, const dictionary &options) , (name, mesh, streamOpt, options))
write() [1/4]
void write (const fileName & name, const edgeMesh & mesh, IOstreamOption streamOpt = IOstreamOption(), const dictionary & options = dictionary::null) static
Definition at line 104 of file edgeMeshIO.C.
References word::ext(), mesh, Foam::name(), and write().
Referenced by extendedEdgeMesh::writeObj().
write() [2/4]
void write (const fileName & name, const word & fileType, const edgeMesh & mesh, IOstreamOption streamOpt = IOstreamOption(), const dictionary & options = dictionary::null) static
Definition at line 77 of file edgeMeshIO.C.
References DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInLookup, mesh, and Foam::name().
transfer()
void transfer (edgeMesh & mesh)
Definition at line 119 of file edgeMesh.C.
References mesh, and PtrList< T >::transfer().
Referenced by extendedEdgeMesh::add(), edgeMesh::edgeMesh(), extendedEdgeMesh::flipNormals(), extendedEdgeMesh::sortPointsAndEdges(), and extendedEdgeMesh::transfer().
read() [1/2]
bool read (const fileName & name, const word & fileType)
Definition at line 65 of file edgeMeshIO.C.
References Foam::name(), and Foam::New().
Referenced by edgeMesh::edgeMesh(), and edgeMesh::edgeMesh().
read() [2/2]
bool read (const fileName & name) virtual
Reimplemented in extendedEdgeMeshFormat, extendedFeatureEdgeMeshFormat, NASedgeFormat, edgeMeshFormat, OBJedgeFormat, STARCDedgeFormat, VTKedgeFormat, and extendedEdgeMesh.
Definition at line 54 of file edgeMeshIO.C.
References word::ext(), word::has_ext(), word::lessExt(), Foam::name(), and Foam::read().
points()
const Foam::pointField & points () const inline noexcept
Definition at line 92 of file edgeMeshI.H.
Referenced by extendedEdgeMesh::extendedEdgeMesh(), extendedEdgeMesh::extendedEdgeMesh(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), featureEdgeMesh::featureEdgeMesh(), and extendedEdgeMesh::sortPointsAndEdges().
edges()
const Foam::edgeList & edges () const inline noexcept
Definition at line 98 of file edgeMeshI.H.
Referenced by extendedEdgeMesh::extendedEdgeMesh(), extendedEdgeMesh::extendedEdgeMesh(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), and featureEdgeMesh::featureEdgeMesh().
pointEdges()
const Foam::labelListList & pointEdges () const inline
Definition at line 104 of file edgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
regions()
Foam::label regions (labelList & edgeRegion) const
Definition at line 132 of file edgeMesh.C.
References PtrList< T >::append(), e, forAll, PtrList< T >::setSize(), UPtrList< T >::size(), and PtrList< T >::transfer().
clear()
void clear () virtual
Reimplemented in extendedEdgeMesh.
Definition at line 111 of file edgeMesh.C.
References PtrList< T >::clear().
Referenced by extendedEdgeMesh::clear().
scalePoints()
void scalePoints (const scalar scaleFactor) virtual
Definition at line 198 of file edgeMesh.C.
References Foam::equal().
mergePoints()
void mergePoints (const scalar mergeDist) virtual
Definition at line 208 of file edgeMesh.C.
References e, and Foam::inplaceMergePoints().
mergeEdges()
void mergeEdges () virtual
Definition at line 235 of file edgeMesh.C.
References e, Foam::endl(), forAll, Foam::Info, PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), and UPtrList< T >::test().
writeStats()
void writeStats (Ostream & os) const virtual
Reimplemented in extendedEdgeMesh.
Definition at line 116 of file edgeMeshIO.C.
References Foam::endl(), Foam::indent(), Foam::nl, os(), points, and UPtrList< T >::size().
Referenced by extendedEdgeMesh::writeStats().
write() [3/4]
virtual void write (const fileName & name, IOstreamOption streamOpt = IOstreamOption(), const dictionary & options = dictionary::null) const inline virtual
Reimplemented in edgeMeshFormat, OBJedgeFormat, STARCDedgeFormat, and VTKedgeFormat.
Definition at line 266 of file edgeMesh.H.
References Foam::name(), and write().
write() [4/4]
virtual void write (const fileName & name, const word & fileType, IOstreamOption streamOpt = IOstreamOption(), const dictionary & options = dictionary::null) const inline virtual
Definition at line 278 of file edgeMesh.H.
References Foam::name(), and write().
operator=() [1/2]
void operator= (const edgeMesh & rhs) inline
Definition at line 116 of file edgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
operator=() [2/2]
void operator= (edgeMesh && rhs) inline
Definition at line 124 of file edgeMeshI.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const edgeMesh & em) friend
operator>>
Istream & operator>> (Istream & is, edgeMesh & em) friend
The documentation for this class was generated from the following files:
src/finiteArea/edgeMesh/edgeFaMesh.H
src/meshTools/edgeMesh/edgeMesh.H
src/meshTools/edgeMesh/edgeMesh.C
src/meshTools/edgeMesh/edgeMeshI.H
src/meshTools/edgeMesh/edgeMeshIO.C
src/meshTools/edgeMesh/edgeMeshNew.C