OpenFOAM: cuboid Class Reference
cuboid Class Reference
#include <cuboid.H>
Public Member Functions
TypeName ("cuboid")
cuboid (const word &name, const scalar m, const vector &c, const vector &L)
cuboid (const word &name, const dictionary &dict)
virtual autoPtr< rigidBody > clone () const
virtual ~cuboid ()
const vector & L () const
virtual void write (Ostream &) const
Public Member Functions inherited from rigidBody
TypeName ("rigidBody")
declareRunTimeSelectionTable (autoPtr, rigidBody, dictionary,(const word &name, const dictionary &dict),(name, dict))
rigidBody (const word &name, const scalar &m, const vector &c, const symmTensor &Ic)
rigidBody (const word &name, const rigidBodyInertia &rbi)
rigidBody (const word &name, const dictionary &dict)
virtual ~rigidBody ()
const word & name () const
virtual bool massless () const
void merge (const subBody &)
Public Member Functions inherited from rigidBodyInertia
rigidBodyInertia ()
rigidBodyInertia (const scalar m, const vector &c, const symmTensor &Ic)
rigidBodyInertia (const dictionary &dict)
rigidBodyInertia (const spatialTensor &st)
rigidBodyInertia (Istream &is)
scalar m () const
const vector & c () const
const symmTensor & Ic () const
symmTensor Ioc () const
symmTensor Icc (const vector &c) const
symmTensor Io () const
scalar kineticEnergy (const spatialVector &v)
operator spatialTensor () const
void operator+= (const rigidBodyInertia &)
Additional Inherited Members
Static Public Member Functions inherited from rigidBody
static autoPtr< rigidBody > New (const word &name, const scalar &m, const vector &c, const symmTensor &Ic)
static autoPtr< rigidBody > New (const word &name, const dictionary &dict)
Static Public Member Functions inherited from rigidBodyInertia
static symmTensor Ioc (const scalar m, const vector &c)
Detailed Description
Definition at line 53 of file cuboid.H.
Constructor & Destructor Documentation
cuboid() [1/2]
cuboid (const word & name, const scalar m, const vector & c, const vector & L) inline
Definition at line 45 of file cuboidI.H.
cuboid() [2/2]
cuboid (const word & name, const dictionary & dict) inline
Definition at line 58 of file cuboidI.H.
References rigidBodyInertia::c(), dict, Foam::I, and rigidBodyInertia::m().
~cuboid()
~cuboid () virtual
Definition at line 52 of file cuboid.C.
Member Function Documentation
TypeName()
TypeName ("cuboid")
clone()
Foam::autoPtr< Foam::RBD::rigidBody > clone () const virtual
Reimplemented from rigidBody.
Definition at line 44 of file cuboid.C.
L()
const Foam::vector & L () const inline
Definition at line 75 of file cuboidI.H.
write()
void write (Ostream & os) const virtual
Reimplemented from rigidBody.
Definition at line 58 of file cuboid.C.
References L, os(), and Foam::type().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/bodies/cuboid/cuboid.H
src/rigidBodyDynamics/bodies/cuboid/cuboid.C
src/rigidBodyDynamics/bodies/cuboid/cuboidI.H