OpenFOAM: cellCuts Class Reference
cellCuts Class Reference
Description of cuts across cells.
#include <cellCuts.H>
Public Member Functions
ClassName ("cellCuts")
cellCuts (const polyMesh &mesh, const labelList &cutCells, const labelList &meshVerts, const labelList &meshEdges, const scalarField &meshEdgeWeights, const bool verbose=true)
cellCuts (const polyMesh &mesh, const labelList &meshVerts, const labelList &meshEdges, const scalarField &meshEdgeWeights, const bool verbose=true)
cellCuts (const polyMesh &mesh, const labelList &cellLabels, const labelListList &cellLoops, const List< scalarField > &cellEdgeWeights, const bool verbose=true)
cellCuts (const polyMesh &mesh, const cellLooper &cellCutter, const List< refineCell > &refCells, const bool verbose=true)
cellCuts (const polyMesh &mesh, const cellLooper &cellCutter, const labelList &cellLabels, const List< plane > &cutPlanes, const bool verbose=true)
cellCuts (const polyMesh &mesh, const boolList &pointIsCut, const boolList &edgeIsCut, const scalarField &edgeWeight, const Map< edge > &faceSplitCut, const labelListList &cellLoops, const label nLoops, const labelListList &cellAnchorPoints, const bool verbose=true)
~cellCuts ()=default
void clearOut ()
const boolList & pointIsCut () const
const boolList & edgeIsCut () const
const scalarField & edgeWeight () const
const labelListList & faceCuts () const
const Map< edge > & faceSplitCut () const
const labelListList & cellLoops () const
label nLoops () const
const labelListList & cellAnchorPoints () const
pointField loopPoints (const label celli) const
labelList nonAnchorPoints (const labelList &cellPoints, const labelList &anchorPoints, const labelList &loop) const
void flip (const label celli)
void flipLoopOnly (const label celli)
void writeOBJ (Ostream &os, const pointField &loopPoints, label &vertI) const
void writeOBJ (Ostream &os) const
void writeCellOBJ (const fileName &dir, const label celli) const
Public Member Functions inherited from edgeVertex
edgeVertex (const polyMesh &mesh)
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Additional Inherited Members
Static Public Member Functions inherited from edgeVertex
static void updateLabels (const labelList &map, List< refineCell > &)
static void updateLabels (const labelList &map, Map< label > &)
static void updateLabels (const labelList &map, labelHashSet &)
static bool isEdge (const primitiveMesh &mesh, const label eVert)
static label getEdge (const primitiveMesh &mesh, const label eVert)
static label getVertex (const primitiveMesh &mesh, const label eVert)
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
static point coord (const primitiveMesh &, const label cut, const scalar weight)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Detailed Description
Description of cuts across cells.
Description of cut is given as list of vertices and list of edges to be cut (and position on edge).
Does some checking of correctness/non-overlapping of cuts. 2x2x2 refinement has to be done in three passes since cuts can not overlap (would make addressing too complicated)
Introduces concept of 'cut' which is either an existing vertex or a edge.
Input can either be
list of cut vertices and list of cut edges. Constructs cell circumference walks ('cellLoops').
list of cell circumference walks. Will filter them so they don't overlap.
cellWalker and list of cells to refine (refineCell). Constructs cellLoops and does B. cellWalker is class which can cut a single cell using a plane through the cell centre and in a certain normal direction
CellCuts constructed from cellLoops (B, C) can have multiple cut-edges and/or cut-point as long as there is per face only one (or none) cut across a face, i.e. a face can only be split into two faces.
The information available after construction:
pointIsCut, edgeIsCut.
faceSplitCut : the cross-cut of a face.
cellLoops : the loop which cuts across a cell
cellAnchorPoints : per cell the vertices on one side which are considered the anchor points.
AnchorPoints: connected loops have to be oriented in the same way to be able to grow new internal faces out of the same bottom faces. (limitation of the mapping procedure). The loop is cellLoop is oriented such that the normal of it points towards the anchorPoints. This is the only routine which uses geometric information.
Limitations:
cut description is very precise. Hard to get right.
do anchor points need to be unique per cell? Very inefficient.
is orientation guaranteed to be correct? Uses geometric info so can go wrong on highly distorted meshes.
is memory inefficient. Probably need to use Maps instead of labelLists.
Source files
cellCuts.H
cellCuts.C
Definition at line 106 of file cellCuts.H.
Constructor & Destructor Documentation
cellCuts() [1/6]
cellCuts (const polyMesh & mesh, const labelList & cutCells, const labelList & meshVerts, const labelList & meshEdges, const scalarField & meshEdgeWeights, const bool verbose = true)
Definition at line 2864 of file cellCuts.C.
References cellCuts::clearOut(), Foam::endl(), and Foam::Pout.
cellCuts() [2/6]
cellCuts (const polyMesh & mesh, const labelList & meshVerts, const labelList & meshEdges, const scalarField & meshEdgeWeights, const bool verbose = true)
Definition at line 2909 of file cellCuts.C.
References cellCuts::clearOut(), Foam::endl(), Foam::identity(), edgeVertex::mesh(), and Foam::Pout.
cellCuts() [3/6]
cellCuts (const polyMesh & mesh, const labelList & cellLabels, const labelListList & cellLoops, const List< scalarField > & cellEdgeWeights, const bool verbose = true)
Definition at line 2958 of file cellCuts.C.
References cellCuts::cellLoops(), cellCuts::clearOut(), Foam::endl(), and Foam::Pout.
cellCuts() [4/6]
cellCuts (const polyMesh & mesh, const cellLooper & cellCutter, const List< refineCell > & refCells, const bool verbose = true)
Definition at line 3006 of file cellCuts.C.
References cellCuts::clearOut(), Foam::endl(), and Foam::Pout.
cellCuts() [5/6]
cellCuts (const polyMesh & mesh, const cellLooper & cellCutter, const labelList & cellLabels, const List< plane > & cutPlanes, const bool verbose = true)
Definition at line 3053 of file cellCuts.C.
References cellCuts::clearOut(), Foam::endl(), and Foam::Pout.
cellCuts() [6/6]
cellCuts (const polyMesh & mesh, const boolList & pointIsCut, const boolList & edgeIsCut, const scalarField & edgeWeight, const Map< edge > & faceSplitCut, const labelListList & cellLoops, const label nLoops, const labelListList & cellAnchorPoints, const bool verbose = true)
Definition at line 3103 of file cellCuts.C.
References Foam::endl(), and Foam::Pout.
~cellCuts()
~cellCuts () default
Member Function Documentation
ClassName()
ClassName ("cellCuts")
clearOut()
void clearOut ()
Definition at line 3136 of file cellCuts.C.
Referenced by cellCuts::cellCuts(), cellCuts::cellCuts(), cellCuts::cellCuts(), cellCuts::cellCuts(), and cellCuts::cellCuts().
pointIsCut()
const boolList & pointIsCut () const inline
Definition at line 551 of file cellCuts.H.
edgeIsCut()
const boolList & edgeIsCut () const inline
Definition at line 557 of file cellCuts.H.
edgeWeight()
const scalarField & edgeWeight () const inline
Definition at line 563 of file cellCuts.H.
faceCuts()
const labelListList & faceCuts () const inline
Definition at line 570 of file cellCuts.H.
faceSplitCut()
const Map< edge > & faceSplitCut () const inline
Definition at line 580 of file cellCuts.H.
cellLoops()
const labelListList & cellLoops () const inline
Definition at line 586 of file cellCuts.H.
Referenced by cellCuts::cellCuts().
nLoops()
label nLoops () const inline
Definition at line 592 of file cellCuts.H.
cellAnchorPoints()
const labelListList & cellAnchorPoints () const inline
Definition at line 598 of file cellCuts.H.
loopPoints()
Foam::pointField loopPoints (const label celli) const
Definition at line 3142 of file cellCuts.C.
References forAll, Foam::getEdge(), and UList< T >::size().
nonAnchorPoints()
Foam::labelList nonAnchorPoints (const labelList & cellPoints, const labelList & anchorPoints, const labelList & loop) const
Definition at line 1322 of file cellCuts.C.
References forAll, UList< T >::found(), PtrList< T >::setSize(), and UList< T >::size().
flip()
void flip (const label celli)
Definition at line 3167 of file cellCuts.C.
References mesh, and Foam::reverse().
flipLoopOnly()
void flipLoopOnly (const label celli)
Definition at line 3184 of file cellCuts.C.
References Foam::reverse().
writeOBJ() [1/2]
void writeOBJ (Ostream & os, const pointField & loopPoints, label & vertI) const
Definition at line 3192 of file cellCuts.C.
References Foam::endl(), forAll, os(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
writeOBJ() [2/2]
void writeOBJ (Ostream & os) const
Definition at line 3219 of file cellCuts.C.
References forAll, and os().
writeCellOBJ()
void writeCellOBJ (const fileName & dir, const label celli) const
Definition at line 3233 of file cellCuts.C.
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/cellCuts/cellCuts.H
src/dynamicMesh/meshCut/cellCuts/cellCuts.C