OpenFOAM: StationaryPhaseModel< BasePhaseModel > Class Template Reference
StationaryPhaseModel< BasePhaseModel > Class Template Reference
Class which represents a stationary (and therefore probably solid) phase. Generates, but does not store, zero velocity and flux field and turbulent qauantities. Throws an error when non-const access is requested to the motion fields or when the momentum equation is requested. Usage must must protect against such calls.
#include <StationaryPhaseModel.H>
Public Member Functions
StationaryPhaseModel (const phaseSystem &fluid, const word &phaseName, const label index)
virtual ~StationaryPhaseModel ()
virtual bool stationary () const
virtual tmp< fvVectorMatrix > UEqn ()
virtual tmp< fvVectorMatrix > UfEqn ()
virtual tmp< volVectorField > U () const
virtual volVectorField & URef ()
virtual tmp< surfaceScalarField > phi () const
virtual surfaceScalarField & phiRef ()
virtual tmp< surfaceScalarField > alphaPhi () const
virtual surfaceScalarField & alphaPhiRef ()
virtual tmp< surfaceScalarField > alphaRhoPhi () const
virtual surfaceScalarField & alphaRhoPhiRef ()
virtual tmp< volVectorField > DUDt () const
virtual tmp< surfaceScalarField > DUDtf () const
virtual tmp< volScalarField > continuityError () const
virtual tmp< volScalarField > continuityErrorFlow () const
virtual tmp< volScalarField > continuityErrorSources () const
virtual tmp< volScalarField > K () const
virtual tmp< volScalarField > divU () const
virtual void divU (tmp< volScalarField > divU)
virtual tmp< volScalarField > mut () const
virtual tmp< volScalarField > muEff () const
virtual tmp< volScalarField > nut () const
virtual tmp< volScalarField > nuEff () const
virtual tmp< volScalarField > kappaEff () const
virtual tmp< scalarField > kappaEff (const label patchi) const
virtual tmp< volScalarField > alphaEff () const
virtual tmp< scalarField > alphaEff (const label patchi) const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > pPrime () const
template<class Type , template< class > class PatchField, class GeoMesh >
Foam::tmp< Foam::GeometricField< Type, PatchField, GeoMesh > > zeroField (const word &name, const dimensionSet &dims, const bool cache) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > zeroVolField (const word &name, const dimensionSet &dims, const bool cache) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > zeroSurfaceField (const word &name, const dimensionSet &dims, const bool cache) const
Detailed Description
template<class BasePhaseModel>
class Foam::StationaryPhaseModel< BasePhaseModel >
Class which represents a stationary (and therefore probably solid) phase. Generates, but does not store, zero velocity and flux field and turbulent qauantities. Throws an error when non-const access is requested to the motion fields or when the momentum equation is requested. Usage must must protect against such calls.
See also
MovingPhaseModel
Source files
StationaryPhaseModel.H
StationaryPhaseModel.C
Definition at line 54 of file StationaryPhaseModel.H.
Constructor & Destructor Documentation
StationaryPhaseModel()
template<class BasePhaseModel > StationaryPhaseModel (const phaseSystem & fluid, const word & phaseName, const label index)
Definition at line 83 of file StationaryPhaseModel.C.
~StationaryPhaseModel()
template<class BasePhaseModel > ~StationaryPhaseModel () virtual
Definition at line 97 of file StationaryPhaseModel.C.
Member Function Documentation
stationary()
template<class BasePhaseModel > bool stationary () const virtual
Definition at line 104 of file StationaryPhaseModel.C.
UEqn()
template<class BasePhaseModel > Foam::tmp< Foam::fvVectorMatrix > UEqn () virtual
Definition at line 112 of file StationaryPhaseModel.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
UfEqn()
template<class BasePhaseModel > Foam::tmp< Foam::fvVectorMatrix > UfEqn () virtual
Definition at line 124 of file StationaryPhaseModel.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
U()
template<class BasePhaseModel > Foam::tmp< Foam::volVectorField > U () const virtual
Definition at line 136 of file StationaryPhaseModel.C.
References Foam::dimVelocity.
URef()
template<class BasePhaseModel > Foam::volVectorField & URef () virtual
Definition at line 144 of file StationaryPhaseModel.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and GeometricField< vector, fvPatchField, volMesh >::null().
phi()
template<class BasePhaseModel > Foam::tmp< Foam::surfaceScalarField > phi () const virtual
Definition at line 156 of file StationaryPhaseModel.C.
References Foam::dimTime, and Foam::dimVolume.
phiRef()
template<class BasePhaseModel > Foam::surfaceScalarField & phiRef () virtual
Definition at line 164 of file StationaryPhaseModel.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and GeometricField< scalar, fvsPatchField, surfaceMesh >::null().
alphaPhi()
template<class BasePhaseModel > Foam::tmp< Foam::surfaceScalarField > alphaPhi () const virtual
Definition at line 176 of file StationaryPhaseModel.C.
References Foam::dimTime, and Foam::dimVolume.
alphaPhiRef()
template<class BasePhaseModel > Foam::surfaceScalarField & alphaPhiRef () virtual
Definition at line 184 of file StationaryPhaseModel.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and GeometricField< scalar, fvsPatchField, surfaceMesh >::null().
alphaRhoPhi()
template<class BasePhaseModel > Foam::tmp< Foam::surfaceScalarField > alphaRhoPhi () const virtual
Definition at line 196 of file StationaryPhaseModel.C.
References Foam::dimMass, and Foam::dimTime.
alphaRhoPhiRef()
template<class BasePhaseModel > Foam::surfaceScalarField & alphaRhoPhiRef () virtual
Definition at line 204 of file StationaryPhaseModel.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and GeometricField< scalar, fvsPatchField, surfaceMesh >::null().
DUDt()
template<class BasePhaseModel > Foam::tmp< Foam::volVectorField > DUDt () const virtual
Definition at line 216 of file StationaryPhaseModel.C.
References Foam::dimTime, and Foam::dimVelocity.
DUDtf()
template<class BasePhaseModel > Foam::tmp< Foam::surfaceScalarField > DUDtf () const virtual
Definition at line 224 of file StationaryPhaseModel.C.
References Foam::dimArea, Foam::dimTime, and Foam::dimVelocity.
continuityError()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > continuityError () const virtual
Definition at line 232 of file StationaryPhaseModel.C.
References Foam::dimDensity, and Foam::dimTime.
continuityErrorFlow()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > continuityErrorFlow () const virtual
Definition at line 240 of file StationaryPhaseModel.C.
References Foam::dimDensity, and Foam::dimTime.
continuityErrorSources()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > continuityErrorSources () const virtual
Definition at line 248 of file StationaryPhaseModel.C.
References Foam::dimDensity, and Foam::dimTime.
K()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > K () const virtual
Definition at line 256 of file StationaryPhaseModel.C.
References Foam::dimVelocity, and Foam::sqr().
divU() [1/2]
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > divU () const virtual
Definition at line 264 of file StationaryPhaseModel.C.
divU() [2/2]
template<class BasePhaseModel > void divU (tmp< volScalarField > divU) virtual
Definition at line 271 of file StationaryPhaseModel.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
mut()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > mut () const virtual
Definition at line 284 of file StationaryPhaseModel.C.
References Foam::dimDynamicViscosity.
muEff()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > muEff () const virtual
Definition at line 292 of file StationaryPhaseModel.C.
nut()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > nut () const virtual
Definition at line 300 of file StationaryPhaseModel.C.
References Foam::dimViscosity.
nuEff()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > nuEff () const virtual
Definition at line 308 of file StationaryPhaseModel.C.
kappaEff() [1/2]
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > kappaEff () const virtual
Definition at line 316 of file StationaryPhaseModel.C.
kappaEff() [2/2]
template<class BasePhaseModel > Foam::tmp< Foam::scalarField > kappaEff (const label patchi) const virtual
Definition at line 324 of file StationaryPhaseModel.C.
alphaEff() [1/2]
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > alphaEff () const virtual
Definition at line 332 of file StationaryPhaseModel.C.
alphaEff() [2/2]
template<class BasePhaseModel > Foam::tmp< Foam::scalarField > alphaEff (const label patchi) const virtual
Definition at line 340 of file StationaryPhaseModel.C.
k()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > k () const virtual
Definition at line 348 of file StationaryPhaseModel.C.
References Foam::dimVelocity, and Foam::sqr().
pPrime()
template<class BasePhaseModel > Foam::tmp< Foam::volScalarField > pPrime () const virtual
Definition at line 356 of file StationaryPhaseModel.C.
References Foam::dimPressure.
zeroField()
template<class BasePhaseModel > template<class Type , template< class > class PatchField, class GeoMesh > Foam::tmp< Foam::GeometricField< Type, PatchField, GeoMesh > > zeroField (const word & name, const dimensionSet & dims, const bool cache) const
Definition at line 28 of file StationaryPhaseModel.C.
References IOobject::groupName(), mesh, Foam::name(), PtrList< T >::PtrList(), timeName, and Foam::Zero.
zeroVolField()
template<class BasePhaseModel > template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > zeroVolField (const word & name, const dimensionSet & dims, const bool cache) const
Definition at line 55 of file StationaryPhaseModel.C.
References Foam::name().
zeroSurfaceField()
template<class BasePhaseModel > template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > zeroSurfaceField (const word & name, const dimensionSet & dims, const bool cache) const
Definition at line 69 of file StationaryPhaseModel.C.
References Foam::name().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/StationaryPhaseModel/StationaryPhaseModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/phaseModel/StationaryPhaseModel/StationaryPhaseModel.C