OpenFOAM: LList< LListBase, T >::const_iterator Class Reference
LList< LListBase, T >::const_iterator Class Reference
#include <LList.H>
Public Member Functions
const_iterator (const_base_iterator iter)
const_iterator (base_iterator iter)
const_reference operator* () const
const_pointer operator-> () const
const_reference operator() () const
const_iterator & operator++ ()
const_iterator & operator-- ()
Detailed Description
template<class LListBase, class T>
class Foam::LList< LListBase, T >::const_iterator
Definition at line 361 of file LList.H.
Constructor & Destructor Documentation
const_iterator() [1/2]
template<class LListBase , class T > const_iterator (const_base_iterator iter) inline
Definition at line 368 of file LList.H.
const_iterator() [2/2]
template<class LListBase , class T > const_iterator (base_iterator iter) inline
Definition at line 374 of file LList.H.
Member Function Documentation
operator*()
template<class LListBase , class T > const_reference operator* () const inline
Definition at line 379 of file LList.H.
References LList< LListBase, T >::link::ref().
Referenced by LList< LListBase, T >::const_iterator::operator()().
operator->()
template<class LListBase , class T > const_pointer operator-> () const inline
Definition at line 384 of file LList.H.
References LList< LListBase, T >::link::ptr().
operator()()
template<class LListBase , class T > const_reference operator() () const inline
Definition at line 389 of file LList.H.
References LList< LListBase, T >::const_iterator::operator*().
operator++()
template<class LListBase , class T > const_iterator & operator++ () inline
Definition at line 394 of file LList.H.
operator--()
template<class LListBase , class T > const_iterator & operator-- () inline
Definition at line 400 of file LList.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/containers/LinkedLists/accessTypes/LList/LList.H