OpenFOAM: equationInitialResidualCondition Class Reference
equationInitialResidualCondition Class Reference
Minimum or maximum initial residual run time condition.
#include <equationInitialResidualCondition.H>
Public Types
enum operatingMode { omMin , omMax }
Public Member Functions
TypeName ("equationInitialResidual")
equationInitialResidualCondition (const word &name, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state)
virtual ~equationInitialResidualCondition ()=default
virtual bool apply ()
virtual void write ()
virtual void reset ()
Public Member Functions inherited from runTimeCondition
TypeName ("runTimeCondition")
declareRunTimeSelectionTable (autoPtr, runTimeCondition, dictionary,(const word &name, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state),(name, obr, dict, state))
runTimeCondition (const word &name, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state)
virtual ~runTimeCondition ()=default
virtual const word & name () const
virtual bool active () const
virtual label groupID () const
Static Public Attributes
static const Enum< operatingMode > operatingModeNames
Protected Member Functions
template<class Type >
void setResidual (const fvMesh &mesh, const dictionary &dict, const word &fieldName, const label componenti, bool &canSet, scalar &residual) const
Protected Member Functions inherited from runTimeCondition
dictionary & setConditionDict ()
const dictionary & conditionDict () const
dictionary & conditionDict ()
Protected Attributes
solverFieldSelection fieldSelection_
const scalar value_
scalar timeStart_
operatingMode mode_
Protected Attributes inherited from runTimeCondition
word name_
const objectRegistry & obr_
stateFunctionObject & state_
bool active_
dictionary & conditionDict_
label groupID_
Additional Inherited Members
Static Public Member Functions inherited from runTimeCondition
static autoPtr< runTimeCondition > New (const word &conditionName, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state)
Public Attributes inherited from runTimeCondition
Switch log
Detailed Description
Minimum or maximum initial residual run time condition.
Source files
equationInitialResidualCondition.H
equationInitialResidualCondition.H
equationInitialResidualCondition.C
Definition at line 56 of file equationInitialResidualCondition.H.
Member Enumeration Documentation
operatingMode
enum operatingMode
Enumerator
omMin
Minimum.
omMax
Maximum.
Definition at line 62 of file equationInitialResidualCondition.H.
Constructor & Destructor Documentation
equationInitialResidualCondition()
equationInitialResidualCondition (const word & name, const objectRegistry & obr, const dictionary & dict, stateFunctionObject & state)
Definition at line 69 of file equationInitialResidualCondition.C.
References runTimeCondition::active_, dict, Foam::endl(), equationInitialResidualCondition::fieldSelection_, Foam::name(), fieldSelection::read(), UList< T >::size(), objectRegistry::time(), equationInitialResidualCondition::timeStart_, and WarningInFunction.
~equationInitialResidualCondition()
virtual ~equationInitialResidualCondition () virtual default
Member Function Documentation
setResidual()
template<class Type > void setResidual (const fvMesh & mesh, const dictionary & dict, const word & fieldName, const label componenti, bool & canSet, scalar & residual) const protected
Definition at line 24 of file equationInitialResidualConditionTemplates.C.
References Foam::cmptMax(), Foam::component(), dict, Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), and mesh.
TypeName()
TypeName ("equationInitialResidual")
apply()
bool apply () virtual
Implements runTimeCondition.
Definition at line 102 of file equationInitialResidualCondition.C.
References fieldInfo::component(), Foam::component(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, dictionary::found(), Log, mesh, fieldInfo::name(), Foam::nl, SetResidual, dictionary::sortedToc(), Foam::type(), and WarningInFunction.
write()
void write () virtual
Implements runTimeCondition.
Definition at line 219 of file equationInitialResidualCondition.C.
reset()
void reset () virtual
Implements runTimeCondition.
Definition at line 226 of file equationInitialResidualCondition.C.
Member Data Documentation
operatingModeNames
const Foam::Enum< Foam::functionObjects::runTimeControls::equationInitialResidualCondition::operatingMode > operatingModeNames static
Definition at line 68 of file equationInitialResidualCondition.H.
fieldSelection_
solverFieldSelection fieldSelection_ protected
Definition at line 76 of file equationInitialResidualCondition.H.
Referenced by equationInitialResidualCondition::equationInitialResidualCondition().
value_
const scalar value_ protected
Definition at line 79 of file equationInitialResidualCondition.H.
timeStart_
scalar timeStart_ protected
Definition at line 82 of file equationInitialResidualCondition.H.
Referenced by equationInitialResidualCondition::equationInitialResidualCondition().
mode_
operatingMode mode_ protected
Definition at line 85 of file equationInitialResidualCondition.H.
The documentation for this class was generated from the following files:
src/functionObjects/utilities/runTimeControl/runTimeCondition/equationInitialResidualCondition/equationInitialResidualCondition.H
src/functionObjects/utilities/runTimeControl/runTimeCondition/equationInitialResidualCondition/equationInitialResidualCondition.C
src/functionObjects/utilities/runTimeControl/runTimeCondition/equationInitialResidualCondition/equationInitialResidualConditionTemplates.C