OpenFOAM: vtuCells Class Reference
vtuCells Class Reference
A deep-copy description of an OpenFOAM volume mesh in data structures suitable for VTK UnstructuredGrid, including the possibility of decomposing polyhedral cells into primitive cell types.
#include <foamVtuCells.H>
Public Member Functions
vtuCells (const enum contentType output=contentType::XML, const bool decompose=false)
vtuCells (const polyMesh &mesh, const enum contentType output=contentType::XML, const bool decompose=false)
vtuCells (const vtk::outputOptions opts, const bool decompose=false)
vtuCells (const polyMesh &mesh, const vtk::outputOptions opts, const bool decompose=false)
enum contentType content () const noexcept
bool decomposeRequested () const noexcept
bool empty () const noexcept
label size () const noexcept
void clear ()
void reset (const polyMesh &mesh)
void reset (const polyMesh &mesh, const labelUList &subsetCellsIds)
void reset (const polyMesh &mesh, const enum contentType output, const bool decompose)
void resetShapes (const UList< cellShape > &shapes)
void renumberCells (const labelUList &mapping)
void renumberPoints (const labelUList &mapping)
void addPointCellLabels (const labelUList &cellIds)
const List< uint8_t > & cellTypes () const noexcept
const labelList & vertLabels () const noexcept
const labelList & vertOffsets () const noexcept
const labelList & faceLabels () const noexcept
const labelList & faceOffsets () const noexcept
const labelList & addPointCellLabels () const noexcept
const labelList & cellMap () const noexcept
Public Member Functions inherited from vtuSizing
vtuSizing () noexcept
vtuSizing (const polyMesh &mesh)
vtuSizing (const polyMesh &mesh, const bool decompose)
void reset (const polyMesh &mesh, const bool decompose=false)
void reset (const polyMesh &mesh, const labelUList &subsetCellsIds, const bool decompose=false)
void resetShapes (const UList< cellShape > &shapes)
void clear () noexcept
bool decompose () const noexcept
bool manifold () const noexcept
selectionModeType selectionMode () const noexcept
label nCells () const noexcept
label nPoints () const noexcept
label nVertLabels () const noexcept
label nFaceLabels () const noexcept
label nCellsPoly () const noexcept
label nVertPoly () const noexcept
label nAddCells () const noexcept
label nAddPoints () const noexcept
label nAddVerts () const noexcept
label nFieldCells () const noexcept
label nFieldPoints () const noexcept
void setNumPoints (label n) noexcept
void setNumAddPoints (label n) noexcept
label sizeOf (const enum contentType output, const enum slotType slot) const
label sizeLegacy () const
label sizeLegacy (const enum slotType slot) const
label sizeXml (const enum slotType slot) const
label sizeInternal1 (const enum slotType slot) const
label sizeInternal2 (const enum slotType slot) const
void populateLegacy (const polyMesh &mesh, UList< uint8_t > &cellTypes, labelUList &connectivity, foamVtkMeshMaps &maps) const
void populateXml (const polyMesh &mesh, UList< uint8_t > &cellTypes, labelUList &connectivity, labelUList &offsets, labelUList &faces, labelUList &facesOffsets, foamVtkMeshMaps &maps) const
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< int > &connectivity, UList< int > &offsets, UList< int > &faces, UList< int > &facesOffsets, foamVtkMeshMaps &maps, const enum contentType output) const
Populate lists for Internal VTK format.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< int > &connectivity, UList< int > &offsets, UList< int > &faces, UList< int > &facesOffsets, labelUList &cellMap, labelUList &addPointsIds, const enum contentType output) const
Populate lists for Internal VTK format.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< long > &connectivity, UList< long > &offsets, UList< long > &faces, UList< long > &facesOffsets, foamVtkMeshMaps &maps, const enum contentType output) const
Populate lists for Internal VTK format.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< long > &connectivity, UList< long > &offsets, UList< long > &faces, UList< long > &facesOffsets, labelUList &cellMap, labelUList &addPointsIds, const enum contentType output) const
Populate lists for Internal VTK format.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< long long > &connectivity, UList< long long > &offsets, UList< long long > &faces, UList< long long > &facesOffsets, foamVtkMeshMaps &maps, const enum contentType output) const
Populate lists for Internal VTK format.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< long long > &connectivity, UList< long long > &offsets, UList< long long > &faces, UList< long long > &facesOffsets, labelUList &cellMap, labelUList &addPointsIds, const enum contentType output) const
Populate lists for Internal VTK format.
void info (Ostream &os) const
bool operator== (const vtuSizing &rhs) const
bool operator!= (const vtuSizing &rhs) const
Additional Inherited Members
Public Types inherited from vtuSizing
enum contentType : char { LEGACY , XML , INTERNAL1 , INTERNAL2 }
enum slotType : char { CELLS , CELLS_OFFSETS , FACES , FACES_OFFSETS }
enum selectionModeType : char { FULL_MESH , SUBSET_MESH , SHAPE_MESH }
Static Public Member Functions inherited from vtuSizing
static labelList copyVertLabelsLegacy (const labelUList &connectivity, const label globalPointOffset)
static labelList copyVertLabelsXml (const labelUList &connectivity, const label globalPointOffset)
static labelList copyFaceLabelsXml (const labelUList &faceLabels, const label globalPointOffset)
static labelList copyFaceOffsetsXml (const labelUList &faceOffsets, const label prevOffset)
static void renumberVertLabelsLegacy (labelUList &connectivity, const label globalPointOffset)
static void renumberVertLabelsXml (labelUList &connectivity, const label globalPointOffset)
static void renumberFaceLabelsXml (labelUList &faceLabels, const label globalPointOffset)
static void renumberFaceOffsetsXml (labelUList &faceOffsets, const label prevOffset)
Protected Member Functions inherited from vtuSizing
void populateShapesLegacy (const UList< cellShape > &shapes, UList< uint8_t > &cellTypes, labelUList &connectivity, foamVtkMeshMaps &maps) const
void populateShapesXml (const UList< cellShape > &shapes, UList< uint8_t > &cellTypes, labelUList &connectivity, labelUList &offsets, labelUList &faces, labelUList &facesOffsets, foamVtkMeshMaps &maps) const
Detailed Description
A deep-copy description of an OpenFOAM volume mesh in data structures suitable for VTK UnstructuredGrid, including the possibility of decomposing polyhedral cells into primitive cell types.
Knowledge of the vtkUnstructuredGrid and the corresponding .vtu xml file-format aids in understanding this class. The class can be used for the VTK xml format, legacy format, as well as a VTK internal representation. The internal representation is somewhat related to the xml format, but not entirely.
See also
Foam::vtk::vtuSizing
Source files
foamVtuCells.H
foamVtuCells.C
foamVtuCellsI.H
Definition at line 66 of file foamVtuCells.H.
Constructor & Destructor Documentation
vtuCells() [1/4]
vtuCells (const enum contentType output = contentType::XML, const bool decompose = false) explicit
Definition at line 27 of file foamVtuCells.C.
vtuCells() [2/4]
vtuCells (const polyMesh & mesh, const enum contentType output = contentType::XML, const bool decompose = false) explicit
Definition at line 45 of file foamVtuCells.C.
References mesh, and vtuCells::reset().
vtuCells() [3/4]
vtuCells (const vtk::outputOptions opts, const bool decompose = false) explicit
Definition at line 58 of file foamVtuCells.C.
vtuCells() [4/4]
vtuCells (const polyMesh & mesh, const vtk::outputOptions opts, const bool decompose = false)
Definition at line 72 of file foamVtuCells.C.
References mesh, and vtuCells::reset().
Member Function Documentation
content()
enum Foam::vtk::vtuCells::contentType content () const inline noexcept
Definition at line 26 of file foamVtuCellsI.H.
decomposeRequested()
bool decomposeRequested () const inline noexcept
Definition at line 32 of file foamVtuCellsI.H.
empty()
bool empty () const inline noexcept
Definition at line 38 of file foamVtuCellsI.H.
References UPtrList< T >::empty().
size()
Foam::label size () const inline noexcept
Definition at line 44 of file foamVtuCellsI.H.
References UPtrList< T >::size().
clear()
void clear ()
Definition at line 212 of file foamVtuCells.C.
References vtuSizing::clear().
reset() [1/3]
void reset (const polyMesh & mesh)
Definition at line 225 of file foamVtuCells.C.
References mesh, and vtuSizing::reset().
Referenced by isoSurfaceTopo::isoSurfaceTopo(), vtuCells::vtuCells(), and vtuCells::vtuCells().
reset() [2/3]
void reset (const polyMesh & mesh, const labelUList & subsetCellsIds)
Definition at line 234 of file foamVtuCells.C.
References mesh, and vtuSizing::reset().
reset() [3/3]
void reset (const polyMesh & mesh, const enum contentType output, const bool decompose)
Definition at line 252 of file foamVtuCells.C.
References mesh, and Foam::output().
resetShapes()
void resetShapes (const UList< cellShape > & shapes)
Definition at line 266 of file foamVtuCells.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::identity(), vtuSizing::nCells(), Foam::nl, vtuSizing::resetShapes(), and WarningInFunction.
Referenced by isoSurfaceTopo::isoSurfaceTopo().
renumberCells()
void renumberCells (const labelUList & mapping)
Definition at line 335 of file foamVtuCells.C.
renumberPoints()
void renumberPoints (const labelUList & mapping)
Definition at line 341 of file foamVtuCells.C.
addPointCellLabels() [1/2]
void addPointCellLabels (const labelUList & cellIds)
Definition at line 328 of file foamVtuCells.C.
Referenced by isoSurfaceTopo::isoSurfaceTopo().
cellTypes()
const Foam::List< uint8_t > & cellTypes () const inline noexcept
Definition at line 51 of file foamVtuCellsI.H.
vertLabels()
const Foam::labelList & vertLabels () const inline noexcept
Definition at line 58 of file foamVtuCellsI.H.
vertOffsets()
const Foam::labelList & vertOffsets () const inline noexcept
Definition at line 65 of file foamVtuCellsI.H.
faceLabels()
const Foam::labelList & faceLabels () const inline noexcept
Definition at line 72 of file foamVtuCellsI.H.
faceOffsets()
const Foam::labelList & faceOffsets () const inline noexcept
Definition at line 79 of file foamVtuCellsI.H.
addPointCellLabels() [2/2]
const Foam::labelList & addPointCellLabels () const inline noexcept
Definition at line 86 of file foamVtuCellsI.H.
cellMap()
const Foam::labelList & cellMap () const inline noexcept
Definition at line 93 of file foamVtuCellsI.H.
The documentation for this class was generated from the following files:
src/fileFormats/vtk/part/foamVtuCells.H
src/fileFormats/vtk/part/foamVtuCells.C
src/fileFormats/vtk/part/foamVtuCellsI.H