OpenFOAM: PrimitivePatch< FaceList, PointField > Class Template Reference
PrimitivePatch< FaceList, PointField > Class Template Reference
A list of faces which address into the list of points.
#include <PrimitivePatch.H>
Public Types
enum surfaceTopo { MANIFOLD , OPEN , ILLEGAL }
typedef std::remove_reference< FaceList >::type::value_type face_type
typedef std::remove_reference< PointField >::type::value_type point_type
typedef FaceList FaceListType
typedef PointField PointFieldType
typedef face_type FaceType
Public Member Functions
PrimitivePatch (const FaceList &faces, const PointField &points)
PrimitivePatch (FaceList &&faces, const PointField &points)
PrimitivePatch (FaceList &faces, PointField &points, const bool reuse)
PrimitivePatch (const PrimitivePatch< FaceList, PointField > &pp)
virtual ~PrimitivePatch ()
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
const Field< point_type > & points () const noexcept
label nFaces () const noexcept
label nPoints () const
label nEdges () const
const edgeList & edges () const
const edgeList::subList internalEdges () const
const edgeList::subList boundaryEdges () const
label nInternalEdges () const
label nBoundaryEdges () const
bool isInternalEdge (const label edgei) const
const labelList & boundaryPoints () const
const labelListList & faceFaces () const
const labelListList & edgeFaces () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointFaces () const
const List< face_type > & localFaces () const
labelList boundaryFaces () const
labelList uniqBoundaryFaces () const
const labelList & meshPoints () const
const Map< label > & meshPointMap () const
const Field< point_type > & localPoints () const
const labelList & localPointOrder () const
label whichPoint (const label gp) const
edge meshEdge (const label edgei) const
edge meshEdge (const edge &e) const
label findEdge (const edge &e) const
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
label meshEdge (const label edgei, const edgeList &allEdges, const labelListList &pointEdges) const
labelList meshEdges (const labelUList &edgeLabels, const edgeList &allEdges, const labelListList &pointEdges) const
const Field< point_type > & faceCentres () const
const Field< point_type > & faceAreas () const
const Field< scalar > & magFaceAreas () const
const Field< point_type > & faceNormals () const
const Field< point_type > & pointNormals () const
Pair< point_type > box () const
scalar sphere (const label facei) const
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
bool hasBoundaryPoints () const
bool hasEdges () const
bool hasFaceFaces () const
bool hasEdgeFaces () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointFaces () const
bool hasMeshPoints () const
bool hasMeshPointMap () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
const labelListList & edgeLoops () const
surfaceTopo surfaceType (labelHashSet *badEdgesPtr=nullptr) const
bool checkTopology (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
bool checkPointManifold (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
virtual void movePoints (const Field< point_type > &)
void operator= (const PrimitivePatch< FaceList, PointField > &rhs)
void operator= (PrimitivePatch< FaceList, PointField > &&rhs)
label whichEdge (const edge &e) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Public Member Functions inherited from PrimitivePatchBase
ClassName ("PrimitivePatch")
PrimitivePatchBase ()=default
Detailed Description
template<class FaceList, class PointField>
class Foam::PrimitivePatch< FaceList, PointField >
A list of faces which address into the list of points.
The class is templated on the face type (e.g. triangle, polygon etc.) and on the list type of faces and points so that it can refer to existing lists using UList and const pointField& or hold the storage using List and pointField.
Source files
PrimitivePatch.H
PrimitivePatch.C
PrimitivePatchAddressing.C
PrimitivePatchBdryFaces.C
PrimitivePatchBdryPoints.C
PrimitivePatchCheck.C
PrimitivePatchClear.C
PrimitivePatchEdgeLoops.C
PrimitivePatchLocalPointOrder.C
PrimitivePatchMeshData.C
PrimitivePatchMeshEdges.C
PrimitivePatchPointAddressing.C
PrimitivePatchProjectPoints.C
Definition at line 78 of file PrimitivePatch.H.
Member Typedef Documentation
face_type
template<class FaceList , class PointField > typedef std::remove_reference<FaceList>::type::value_type face_type
Definition at line 89 of file PrimitivePatch.H.
point_type
template<class FaceList , class PointField > typedef std::remove_reference<PointField>::type::value_type point_type
Definition at line 93 of file PrimitivePatch.H.
FaceListType
template<class FaceList , class PointField > typedef FaceList FaceListType
Definition at line 96 of file PrimitivePatch.H.
PointFieldType
template<class FaceList , class PointField > typedef PointField PointFieldType
Definition at line 99 of file PrimitivePatch.H.
FaceType
template<class FaceList , class PointField > typedef face_type FaceType
Definition at line 103 of file PrimitivePatch.H.
Member Enumeration Documentation
surfaceTopo
template<class FaceList , class PointField > enum surfaceTopo
Enumerator
MANIFOLD
OPEN
ILLEGAL
Definition at line 110 of file PrimitivePatch.H.
Constructor & Destructor Documentation
PrimitivePatch() [1/4]
template<class FaceList , class PointField > PrimitivePatch (const FaceList & faces, const PointField & points)
Definition at line 27 of file PrimitivePatch.C.
PrimitivePatch() [2/4]
template<class FaceList , class PointField > PrimitivePatch (FaceList && faces, const PointField & points)
Definition at line 58 of file PrimitivePatch.C.
PrimitivePatch() [3/4]
template<class FaceList , class PointField > PrimitivePatch (FaceList & faces, PointField & points, const bool reuse)
Definition at line 89 of file PrimitivePatch.C.
PrimitivePatch() [4/4]
template<class FaceList , class PointField > PrimitivePatch (const PrimitivePatch< FaceList, PointField > & pp)
Definition at line 121 of file PrimitivePatch.C.
~PrimitivePatch()
template<class FaceList , class PointField > virtual ~PrimitivePatch () virtual
Member Function Documentation
clearOut()
template<class FaceList , class PointField > void clearOut ()
Definition at line 78 of file PrimitivePatchClear.C.
Referenced by processorPolyPatch::updateMesh().
clearGeom()
template<class FaceList , class PointField > void clearGeom ()
Definition at line 28 of file PrimitivePatchClear.C.
References DebugInFunction, and Foam::nl.
Referenced by polyPatch::clearGeom(), and polyPatch::updateMesh().
clearTopology()
template<class FaceList , class PointField > void clearTopology ()
Definition at line 43 of file PrimitivePatchClear.C.
References DebugInFunction, and Foam::nl.
Referenced by polyPatch::clearAddressing().
clearPatchMeshAddr()
template<class FaceList , class PointField > void clearPatchMeshAddr ()
Definition at line 66 of file PrimitivePatchClear.C.
References DebugInFunction, and Foam::nl.
Referenced by polyPatch::clearAddressing().
swap()
template<class FaceList , class PointField > void swap (PrimitivePatch< FaceList, PointField > &) delete
points()
template<class FaceList , class PointField > const Field< point_type > & points () const inline noexcept
Definition at line 299 of file PrimitivePatch.H.
Referenced by addPatchCellLayer::calcExtrudeInfo(), AMIInterpolation::calculate(), triSurfaceTools::curvatures(), Foam::drawHitProblem(), Foam::edgeMeshTools::featureProximity(), mappedPatchBase::findLocalSamples(), cyclicPolyPatch::initOrder(), processorPolyPatch::initOrder(), isoSurfaceTopo::isoSurfaceTopo(), momentOfInertia::massPropertiesPatch(), momentOfInertia::massPropertiesShell(), momentOfInertia::massPropertiesSolid(), offsetSurface::operator()(), triSurface::operator=(), cyclicPolyPatch::order(), oldCyclicPolyPatch::order(), processorPolyPatch::order(), orientedSurface::orientedSurface(), sampledCuttingSurface::points(), sampledFaceZone::points(), sampledMeshedSurface::points(), sampledNone::points(), sampledPatch::points(), sampledPlane::points(), sampledThresholdCellFaces::points(), addPatchCellLayer::setRefinement(), AMIInterpolation::srcPointFace(), triSurfaceTools::surfaceNormal(), triSurfaceTools::surfaceSide(), AMIInterpolation::tgtPointFace(), triSurfaceMeshPointSet::triSurfaceMeshPointSet(), triSurfaceTools::validTri(), triSurfaceTools::vertexNormals(), triSurfaceTools::vertexTriads(), cuttingSurfaceBase::walkCellCuts(), and surfaceNoise::writeSurfaceData().
nFaces()
template<class FaceList , class PointField > label nFaces () const inline noexcept
Definition at line 305 of file PrimitivePatch.H.
Referenced by surfaceNoise::initialise().
nPoints()
template<class FaceList , class PointField > label nPoints () const inline
Definition at line 316 of file PrimitivePatch.H.
References PrimitivePatch< FaceList, PointField >::meshPoints(), and UPtrList< T >::size().
Referenced by snappyLayerDriver::addLayers(), snappySnapDriver::calcNearestSurface(), snappySnapDriver::detectNearSurfaces(), snappySnapDriver::doSnap(), triSurfaceTools::greenRefine(), meshStructure::meshStructure(), medialAxisMeshMover::move(), addPatchCellLayer::setRefinement(), syncTools::syncPointMap(), and triSurfaceTools::vertexNormals().
nEdges()
template<class FaceList , class PointField > label nEdges () const inline
Definition at line 322 of file PrimitivePatch.H.
References PrimitivePatch< FaceList, PointField >::edges(), and UPtrList< T >::size().
Referenced by holeToFace::calcClosure(), addPatchCellLayer::calcExtrudeInfo(), triSurfaceTools::collapseEdges(), triSurfaceTools::collapseEdges(), edgeSurface::edgeSurface(), triSurfaceTools::greenRefine(), meshStructure::meshStructure(), polyBoundaryMesh::neighbourEdges(), addPatchCellLayer::setRefinement(), and syncTools::syncEdgeMap().
edges()
template<class FaceList , class PointField > const Foam::edgeList & edges () const
Definition at line 176 of file PrimitivePatch.C.
Referenced by meshRefinement::blockLeakFaces(), holeToFace::calcClosure(), addPatchCellLayer::calcExtrudeInfo(), snappySnapDriver::calcSnapDistance(), triSurfaceTools::collapseEdges(), triSurfaceTools::collapseEdges(), cyclicPolyPatch::coupledEdges(), edgeSurface::edgeSurface(), triSurfaceTools::getEdge(), triSurfaceTools::getVertexTriangles(), triSurfaceTools::getVertexVertices(), triSurfaceTools::greenRefine(), triSurfaceTools::maxEdge(), triSurfaceTools::minEdge(), edgeIntersections::minEdgeLength(), slidingInterface::modifyMotionPoints(), PrimitivePatch< FaceList, PointField >::nEdges(), polyBoundaryMesh::neighbourEdges(), triSurfaceTools::oppositeEdge(), triSurfaceTools::oppositeVertex(), triSurfaceTools::otherEdges(), addPatchCellLayer::setRefinement(), triSurfaceTools::surfaceSide(), and OBJstream::write().
internalEdges()
template<class FaceList , class PointField > const Foam::edgeList::subList internalEdges () const
Definition at line 189 of file PrimitivePatch.C.
boundaryEdges()
template<class FaceList , class PointField > const Foam::edgeList::subList boundaryEdges () const
Definition at line 198 of file PrimitivePatch.C.
nInternalEdges()
template<class FaceList , class PointField > Foam::label nInternalEdges () const
Definition at line 207 of file PrimitivePatch.C.
Referenced by holeToFace::calcClosure(), PrimitivePatch< FaceList, PointField >::isInternalEdge(), polyBoundaryMesh::neighbourEdges(), and addPatchCellLayer::setRefinement().
nBoundaryEdges()
template<class FaceList , class PointField > Foam::label nBoundaryEdges () const
Definition at line 220 of file PrimitivePatch.C.
References UPtrList< T >::size().
isInternalEdge()
template<class FaceList , class PointField > bool isInternalEdge (const label edgei) const inline
Definition at line 343 of file PrimitivePatch.H.
References PrimitivePatch< FaceList, PointField >::nInternalEdges().
boundaryPoints()
template<class FaceList , class PointField > const Foam::labelList & boundaryPoints () const
Definition at line 229 of file PrimitivePatch.C.
faceFaces()
template<class FaceList , class PointField > const Foam::labelListList & faceFaces () const
Definition at line 242 of file PrimitivePatch.C.
Referenced by triSurfaceTools::validTri().
edgeFaces()
template<class FaceList , class PointField > const Foam::labelListList & edgeFaces () const
Definition at line 255 of file PrimitivePatch.C.
Referenced by addPatchCellLayer::calcExtrudeInfo(), triSurfaceTools::collapseEdges(), meshRefinement::countEdgeFaces(), triSurfaceTools::edgeSide(), edgeSurface::edgeSurface(), extendedEdgeMesh::extendedEdgeMesh(), triSurfaceTools::getTriangle(), triSurfaceTools::getVertexTriangles(), addPatchCellLayer::globalEdgeFaces(), triSurfaceTools::greenRefine(), isoSurfaceTopo::isoSurfaceTopo(), triSurfaceTools::otherFace(), addPatchCellLayer::setRefinement(), and triSurfaceTools::surfaceNormal().
faceEdges()
template<class FaceList , class PointField > const Foam::labelListList & faceEdges () const
Definition at line 268 of file PrimitivePatch.C.
Referenced by cyclicPolyPatch::coupledEdges(), triSurfaceTools::getTriangle(), intersectedSurface::intersectedSurface(), isoSurfaceCell::isoSurfaceCell(), triSurfaceTools::oppositeEdge(), triSurfaceTools::otherEdges(), addPatchCellLayer::setRefinement(), triSurfaceTools::surfaceNormal(), and triSurfaceTools::surfaceSide().
pointEdges()
template<class FaceList , class PointField > const Foam::labelListList & pointEdges () const
Definition at line 281 of file PrimitivePatch.C.
Referenced by snappySnapDriver::calcSnapDistance(), triSurfaceTools::getEdge(), triSurfaceTools::getVertexVertices(), edgeIntersections::minEdgeLength(), and triSurfaceTools::surfaceSide().
pointFaces()
template<class FaceList , class PointField > const Foam::labelListList & pointFaces () const
Definition at line 294 of file PrimitivePatch.C.
Referenced by snappySnapDriver::avgCellCentres(), triSurfaceTools::getVertexTriangles(), oldCyclicPolyPatch::order(), and triSurfaceTools::vertexNormals().
localFaces()
template<class FaceList , class PointField > const Foam::List< typename Foam::PrimitivePatch< FaceList, PointField >::face_type > & localFaces () const
Definition at line 310 of file PrimitivePatch.C.
Referenced by triSurfaceTools::collapseEdges(), triSurfaceTools::greenRefine(), processorPolyPatch::initOrder(), processorCyclicPolyPatch::initOrder(), intersectedSurface::intersectedSurface(), triSurfaceTools::mergePoints(), triSurfaceTools::oppositeVertex(), oldCyclicPolyPatch::order(), processorPolyPatch::order(), triSurfaceTools::otherEdges(), triSurfaceTools::otherVertices(), boundaryMesh::readTriSurface(), snappySnapDriver::repatchToSurface(), addPatchCellLayer::setRefinement(), triSurfaceTools::surfaceNormal(), triSurfaceTools::surfaceSide(), cuttingSurfaceBase::walkCellCuts(), OBJstream::write(), lumpedPointMovement::writeVTP(), and lumpedPointMovement::writeZonesVTP().
boundaryFaces()
template<class FaceList , class PointField > Foam::labelList boundaryFaces () const
Definition at line 27 of file PrimitivePatchBdryFaces.C.
References forAll, PtrList< T >::PtrList(), and UPtrList< T >::size().
uniqBoundaryFaces()
template<class FaceList , class PointField > Foam::labelList uniqBoundaryFaces () const
Definition at line 51 of file PrimitivePatchBdryFaces.C.
References PtrList< T >::resize(), UPtrList< T >::size(), and Foam::sort().
meshPoints()
template<class FaceList , class PointField > const Foam::labelList & meshPoints () const
Definition at line 323 of file PrimitivePatch.C.
Referenced by snappyLayerDriver::addLayers(), snappySnapDriver::avgCellCentres(), meshRefinement::blockLeakFaces(), holeToFace::calcClosure(), addPatchCellLayer::calcExtrudeInfo(), snappySnapDriver::calcNearestSurface(), snappySnapDriver::calcSnapDistance(), cyclicPolyPatch::coupledEdges(), triSurfaceTools::curvatures(), snappySnapDriver::detectNearSurfaces(), mappedPatchBase::findLocalSamples(), globalPoints::globalPoints(), medialAxisMeshMover::move(), polyBoundaryMesh::neighbourEdges(), PrimitivePatch< FaceList, PointField >::nPoints(), orientedSurface::orientedSurface(), motionSmootherAlgo::setDisplacement(), addPatchCellLayer::setRefinement(), snappySnapDriver::smoothDisplacement(), and triSurfaceTools::vertexNormals().
meshPointMap()
template<class FaceList , class PointField > const Foam::Map< Foam::label > & meshPointMap () const
Definition at line 336 of file PrimitivePatch.C.
Referenced by snappyLayerDriver::addLayers(), triSurfaceTools::curvatures(), globalPoints::globalPoints(), PatchTools::pointNormals(), addPatchCellLayer::setRefinement(), and triSurfaceTools::vertexTriads().
localPoints()
template<class FaceList , class PointField > const Foam::Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > & localPoints () const
Definition at line 352 of file PrimitivePatch.C.
Referenced by snappyLayerDriver::addLayers(), snappySnapDriver::calcNearestSurface(), snappySnapDriver::calcSnapDistance(), triSurfaceTools::collapseEdges(), triSurfaceTools::collapseEdges(), cyclicPolyPatch::coupledEdges(), snappySnapDriver::detectNearSurfaces(), snappySnapDriver::doSnap(), edgeSurface::edgeSurface(), triSurfaceTools::greenRefine(), processorPolyPatch::initOrder(), processorCyclicPolyPatch::initOrder(), triSurfaceTools::maxEdge(), triSurfaceTools::mergePoints(), triSurfaceTools::minEdge(), edgeIntersections::minEdgeLength(), slidingInterface::modifyMotionPoints(), polyBoundaryMesh::neighbourEdges(), processorPolyPatch::order(), boundaryMesh::readTriSurface(), addPatchCellLayer::setRefinement(), snappySnapDriver::smoothDisplacement(), triSurfaceTools::surfaceSide(), OBJstream::write(), triSurfaceTools::writeOBJ(), and lumpedPointMovement::writeZonesVTP().
localPointOrder()
template<class FaceList , class PointField > const Foam::labelList & localPointOrder () const
Definition at line 365 of file PrimitivePatch.C.
whichPoint()
template<class FaceList , class PointField > Foam::label whichPoint (const label gp) const
Definition at line 378 of file PrimitivePatch.C.
Referenced by slidingInterface::modifyMotionPoints().
meshEdge() [1/3]
template<class FaceList , class PointField > Foam::edge meshEdge (const label edgei) const
Definition at line 28 of file PrimitivePatchMeshEdges.C.
meshEdge() [2/3]
template<class FaceList , class PointField > Foam::edge meshEdge (const edge & e) const
Definition at line 36 of file PrimitivePatchMeshEdges.C.
References e.
findEdge()
template<class FaceList , class PointField > Foam::label findEdge (const edge & e) const
Definition at line 175 of file PrimitivePatchMeshEdges.C.
References e, UList< T >::first(), and nPoints.
Referenced by PrimitivePatch< FaceList, PointField >::whichEdge().
meshEdges() [1/3]
template<class FaceList , class PointField > Foam::labelList meshEdges (const edgeList & allEdges, const labelListList & cellEdges, const labelList & faceCells) const
Definition at line 44 of file PrimitivePatchMeshEdges.C.
References DebugInFunction, forAll, found, and Foam::nl.
Referenced by addPatchCellLayer::calcExtrudeInfo(), addPatchCellLayer::globalEdgeFaces(), polyPatch::meshEdges(), and addPatchCellLayer::setRefinement().
meshEdges() [2/3]
template<class FaceList , class PointField > Foam::labelList meshEdges (const edgeList & allEdges, const labelListList & pointEdges) const
Definition at line 95 of file PrimitivePatchMeshEdges.C.
References DebugInFunction, forAll, and Foam::nl.
meshEdge() [3/3]
template<class FaceList , class PointField > Foam::label meshEdge (const label edgei, const edgeList & allEdges, const labelListList & pointEdges) const
Definition at line 129 of file PrimitivePatchMeshEdges.C.
meshEdges() [3/3]
template<class FaceList , class PointField > Foam::labelList meshEdges (const labelUList & edgeLabels, const edgeList & allEdges, const labelListList & pointEdges) const
Definition at line 154 of file PrimitivePatchMeshEdges.C.
References forAll, and UList< T >::size().
faceCentres()
template<class FaceList , class PointField > const Foam::Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > & faceCentres () const
Definition at line 393 of file PrimitivePatch.C.
Referenced by symmetryPlanePolyPatch::calcGeometry(), wedgePolyPatch::calcGeometry(), processorPolyPatch::initOrder(), processorPolyPatch::order(), movingWallVelocityFvPatchVectorField::Uwall(), and AMIInterpolation::writeFaceConnectivity().
faceAreas()
template<class FaceList , class PointField > const Foam::Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > & faceAreas () const
Definition at line 409 of file PrimitivePatch.C.
Referenced by cyclicACMIPolyPatch::scalePatchFaceAreas(), and dynamicMotionSolverFvMeshAMI::update().
magFaceAreas()
template<class FaceList , class PointField > const Foam::Field< Foam::scalar > & magFaceAreas () const
Definition at line 422 of file PrimitivePatch.C.
faceNormals()
template<class FaceList , class PointField > const Foam::Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > & faceNormals () const
Definition at line 438 of file PrimitivePatch.C.
Referenced by KinematicSurfaceFilm< CloudType >::absorbInteraction(), KinematicSurfaceFilm< CloudType >::bounceInteraction(), symmetryPlanePolyPatch::calcGeometry(), wedgePolyPatch::calcGeometry(), KinematicSurfaceFilm< CloudType >::drySplashInteraction(), triSurfaceTools::edgeSide(), processorPolyPatch::initOrder(), intersectedSurface::intersectedSurface(), processorPolyPatch::order(), sampledMeshedSurfaceNormal::sample(), KinematicSurfaceFilm< CloudType >::splashInteraction(), triSurfaceTools::surfaceNormal(), triSurfaceTools::surfaceSide(), and KinematicSurfaceFilm< CloudType >::wetSplashInteraction().
pointNormals()
template<class FaceList , class PointField > const Foam::Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > & pointNormals () const
Definition at line 454 of file PrimitivePatch.C.
Referenced by slidingInterface::modifyMotionPoints(), and triSurfaceTools::surfaceNormal().
box()
template<class FaceList , class PointField > Foam::Pair< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > box () const
Definition at line 122 of file PrimitivePatchBdryPoints.C.
References f(), UPtrList< T >::first(), Foam::max(), and Foam::min().
sphere()
template<class FaceList , class PointField > Foam::scalar sphere (const label facei) const
Definition at line 158 of file PrimitivePatchBdryPoints.C.
References Foam::magSqr().
hasFaceAreas()
template<class FaceList , class PointField > bool hasFaceAreas () const inline
Definition at line 472 of file PrimitivePatch.H.
hasFaceCentres()
template<class FaceList , class PointField > bool hasFaceCentres () const inline
Definition at line 473 of file PrimitivePatch.H.
hasFaceNormals()
template<class FaceList , class PointField > bool hasFaceNormals () const inline
Definition at line 474 of file PrimitivePatch.H.
hasPointNormals()
template<class FaceList , class PointField > bool hasPointNormals () const inline
Definition at line 475 of file PrimitivePatch.H.
hasBoundaryPoints()
template<class FaceList , class PointField > bool hasBoundaryPoints () const inline
Definition at line 477 of file PrimitivePatch.H.
hasEdges()
template<class FaceList , class PointField > bool hasEdges () const inline
Definition at line 482 of file PrimitivePatch.H.
hasFaceFaces()
template<class FaceList , class PointField > bool hasFaceFaces () const inline
Definition at line 483 of file PrimitivePatch.H.
hasEdgeFaces()
template<class FaceList , class PointField > bool hasEdgeFaces () const inline
Definition at line 484 of file PrimitivePatch.H.
hasFaceEdges()
template<class FaceList , class PointField > bool hasFaceEdges () const inline
Definition at line 485 of file PrimitivePatch.H.
hasPointEdges()
template<class FaceList , class PointField > bool hasPointEdges () const inline
Definition at line 487 of file PrimitivePatch.H.
hasPointFaces()
template<class FaceList , class PointField > bool hasPointFaces () const inline
Definition at line 488 of file PrimitivePatch.H.
hasMeshPoints()
template<class FaceList , class PointField > bool hasMeshPoints () const inline
Definition at line 490 of file PrimitivePatch.H.
hasMeshPointMap()
template<class FaceList , class PointField > bool hasMeshPointMap () const inline
Definition at line 491 of file PrimitivePatch.H.
projectPoints() [1/2]
template<class FaceList , class PointField > template<class ToPatch > List< objectHit > projectPoints (const ToPatch & targetPatch, const Field< point_type > & projectionDirection, const intersection::algorithm = intersection::FULL_RAY, const intersection::direction = intersection::VECTOR) const
projectFaceCentres() [1/2]
template<class FaceList , class PointField > template<class ToPatch > List< objectHit > projectFaceCentres (const ToPatch & targetPatch, const Field< point_type > & projectionDirection, const intersection::algorithm = intersection::FULL_RAY, const intersection::direction = intersection::VECTOR) const
edgeLoops()
template<class FaceList , class PointField > const Foam::labelListList & edgeLoops () const
Definition at line 127 of file PrimitivePatchEdgeLoops.C.
surfaceType()
template<class FaceList , class PointField > Foam::PrimitivePatch< FaceList, PointField >::surfaceTopo surfaceType (labelHashSet * badEdgesPtr = nullptr) const
Definition at line 96 of file PrimitivePatchCheck.C.
References badEdgesPtr, HashTable< T, Key, Hash >::clear(), forAll, foundError, HashSet< Key, Hash >::insert(), and UPtrList< T >::size().
checkTopology()
template<class FaceList , class PointField > bool checkTopology (const bool report = false, labelHashSet * pointSetPtr = nullptr) const
Definition at line 153 of file PrimitivePatchCheck.C.
References e, Foam::endl(), UList< T >::first(), forAll, foundError, Foam::Info, HashSet< Key, Hash >::insert(), pointSetPtr, and UPtrList< T >::size().
checkPointManifold()
template<class FaceList , class PointField > bool checkPointManifold (const bool report = false, labelHashSet * pointSetPtr = nullptr) const
Definition at line 195 of file PrimitivePatchCheck.C.
References Foam::endl(), forAll, foundError, Foam::Info, HashSet< Key, Hash >::insert(), Foam::nl, pFaces, pointSetPtr, and UPtrList< T >::size().
movePoints()
template<class FaceList , class PointField > void movePoints (const Field< point_type > &) virtual
Reimplemented in polyPatch.
Definition at line 163 of file PrimitivePatch.C.
References DebugInFunction, and Foam::endl().
Referenced by snappyLayerDriver::addLayers(), cyclicAMIPolyPatch::initMovePoints(), and polyPatch::movePoints().
operator=() [1/2]
template<class FaceList , class PointField > void operator= (const PrimitivePatch< FaceList, PointField > & rhs)
Definition at line 469 of file PrimitivePatch.C.
Referenced by polyPatch::operator=().
operator=() [2/2]
template<class FaceList , class PointField > void operator= (PrimitivePatch< FaceList, PointField > && rhs)
Definition at line 489 of file PrimitivePatch.C.
whichEdge()
template<class FaceList , class PointField > label whichEdge (const edge & e) const inline
Definition at line 573 of file PrimitivePatch.H.
References PrimitivePatch< FaceList, PointField >::findEdge().
Referenced by slidingInterface::modifyMotionPoints().
projectPoints() [2/2]
template<class FaceList , class PointField > template<class ToPatch > Foam::List< Foam::objectHit > projectPoints (const ToPatch & targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > & projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Definition at line 37 of file PrimitivePatchProjectPoints.C.
References Foam::abort(), Foam::average(), DebugInfo, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::magSqr(), Foam::nl, nPoints, points, PtrList< T >::PtrList(), and UPtrList< T >::size().
projectFaceCentres() [2/2]
template<class FaceList , class PointField > template<class ToPatch > Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch & targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > & projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Definition at line 267 of file PrimitivePatchProjectPoints.C.
References Foam::abort(), Foam::meshTools::bandCompression(), DebugInfo, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::magSqr(), Foam::nl, points, and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatch.H
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatch.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchAddressing.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchBdryFaces.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchBdryPoints.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchCheck.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchClear.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchEdgeLoops.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchLocalPointOrder.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchMeshData.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchMeshEdges.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchPointAddressing.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchProjectPoints.C