OpenFOAM: Constant< Type > Class Template Reference
Constant< Type > Class Template Reference
Templated function that returns a constant value.
#include <Constant.H>
Public Member Functions
TypeName ("constant")
void operator= (const Constant< Type > &)=delete
Constant (const word &entryName, const Type &value, const objectRegistry *obrPtr=nullptr)
Constant (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
Constant (const word &entryName, Istream &is)
Constant (const Constant< Type > &rhs)
virtual tmp< Function1< Type > > clone () const
virtual ~Constant ()=default
void reset (const Type &val)
virtual bool constant () const
virtual Type value (const scalar) const
virtual Type integrate (const scalar x1, const scalar x2) const
virtual tmp< Field< Type > > value (const scalarField &x) const
virtual void writeData (Ostream &os) const
Public Member Functions inherited from Function1< Type >
TypeName ("Function1") declareRunTimeSelectionTable(autoPtr
Function1 (const word &entryName, const objectRegistry *obrPtr=nullptr)
Function1 (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
Function1 (const Function1< Type > &rhs)
virtual ~Function1 ()=default
virtual bool good () const
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
virtual void writeEntries (Ostream &os) const
Public Member Functions inherited from function1Base
function1Base (const word &entryName, const objectRegistry *obrPtr=nullptr)
function1Base (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
function1Base (const function1Base &rhs)
virtual ~function1Base ()
const word & name () const noexcept
const objectRegistry * whichDb () const noexcept
void resetDb (const objectRegistry *obrPtr=nullptr) noexcept
void resetDb (const objectRegistry &db) noexcept
const objectRegistry & obr () const
bool isTime () const noexcept
const Time & time () const
template<class MeshType >
const MeshType & mesh (const word &regionName=word::null) const
virtual void userTimeToTime (const Time &t)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Public Types inherited from Function1< Type >
typedef Type returnType
Static Public Member Functions inherited from Function1< Type >
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict, const word &redirectType, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > NewCompat (const word &entryName, std::initializer_list< std::pair< const char *, int > > compat, const dictionary &dict, const word &redirectType=word::null, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
static autoPtr< Function1< Type > > NewIfPresent (const word &entryName, const dictionary &dict, const word &redirectType, const objectRegistry *obrPtr=nullptr)
static autoPtr< Function1< Type > > NewIfPresent (const word &entryName, const dictionary &dict, const objectRegistry *obrPtr=nullptr)
static refPtr< Function1< Type > > New (HashPtrTable< Function1< Type > > &cache, const word &entryName, const dictionary &dict, enum keyType::option matchOpt=keyType::LITERAL, const objectRegistry *obrPtr=nullptr, const bool mandatory=true)
Public Attributes inherited from Function1< Type >
Function1
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary const objectRegistry * obrPtr
const word const dictionary const objectRegistry entryName
const word const dictionary const objectRegistry dict
const word const dictionary const objectRegistry obrPtr
Protected Member Functions inherited from Function1< Type >
void operator= (const Function1< Type > &)=delete
Protected Member Functions inherited from function1Base
void operator= (const function1Base &)=delete
Protected Attributes inherited from function1Base
const word name_
const objectRegistry * obrPtr_
Detailed Description
template<class Type>
class Foam::Function1Types::Constant< Type >
Templated function that returns a constant value.
Usage - for entry <entryName> returning the value <value>, can be specified is different formats.
Inline specification:
    <entryName>  constant <value>
Dictionary format:
    <entryName>
    {
        type    constant;
        value   <value>;
    }
Source files
Constant.H
Constant.C
ConstantI.H
Definition at line 68 of file Constant.H.
Constructor & Destructor Documentation
Constant() [1/4]
template<class Type > Constant (const word & entryName, const Type & value, const objectRegistry * obrPtr = nullptr)
Definition at line 27 of file Constant.C.
Constant() [2/4]
template<class Type > Constant (const word & entryName, const dictionary & dict, const objectRegistry * obrPtr = nullptr)
Definition at line 40 of file Constant.C.
References Function1< Type >::dict, Function1< Type >::entryName, and keyType::LITERAL.
Constant() [3/4]
template<class Type > Constant (const word & entryName, Istream & is)
Definition at line 77 of file Constant.C.
Constant() [4/4]
template<class Type > Constant (const Constant< Type > & rhs) explicit
Definition at line 89 of file Constant.C.
~Constant()
template<class Type > virtual ~Constant () virtual default
Member Function Documentation
TypeName()
template<class Type > TypeName ("constant")
operator=()
template<class Type > void operator= (const Constant< Type > &) delete
clone()
template<class Type > virtual tmp< Function1< Type > > clone () const inline virtual
Implements Function1< Type >.
Reimplemented in Uniform< Type >.
Definition at line 117 of file Constant.H.
reset()
template<class Type > void reset (const Type & val) inline
Definition at line 27 of file ConstantI.H.
constant()
template<class Type > virtual bool constant () const inline virtual
Reimplemented from Function1< Type >.
Definition at line 133 of file Constant.H.
value() [1/2]
template<class Type > Type value (const scalar) const inline virtual
Reimplemented from Function1< Type >.
Definition at line 34 of file ConstantI.H.
integrate()
template<class Type > Type integrate (const scalar x1, const scalar x2) const inline virtual
Reimplemented from Function1< Type >.
Definition at line 41 of file ConstantI.H.
value() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > value (const scalarField & x) const virtual
Reimplemented from Function1< Type >.
Definition at line 99 of file Constant.C.
References Foam::New(), and x.
writeData()
template<class Type > void writeData (Ostream & os) const virtual
Reimplemented from Function1< Type >.
Definition at line 109 of file Constant.C.
References os(), token::SPACE, and Function1< Type >::writeData().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/Constant/Constant.H
src/OpenFOAM/primitives/functions/Function1/Constant/Constant.C
src/OpenFOAM/primitives/functions/Function1/Constant/ConstantI.H