OpenFOAM: inverseFaceDistanceDiffusivity Class Reference
inverseFaceDistanceDiffusivity Class Reference
Inverse distance to the given patches motion diffusivity.
#include <inverseFaceDistanceDiffusivity.H>
Public Member Functions
TypeName ("inverseFaceDistance")
inverseFaceDistanceDiffusivity (const fvMesh &mesh, Istream &mdData)
virtual ~inverseFaceDistanceDiffusivity ()
virtual void correct ()
Public Member Functions inherited from uniformDiffusivity
TypeName ("uniform")
uniformDiffusivity (const fvMesh &mesh, Istream &mdData)
virtual ~uniformDiffusivity ()
virtual tmp< surfaceScalarField > operator() () const
Public Member Functions inherited from motionDiffusivity
TypeName ("motionDiffusivity")
declareRunTimeSelectionTable (autoPtr, motionDiffusivity, Istream,(const fvMesh &mesh, Istream &mdData),(mesh, mdData))
motionDiffusivity (const fvMesh &mesh)
virtual ~motionDiffusivity ()
const fvMesh & mesh () const
Additional Inherited Members
Static Public Member Functions inherited from motionDiffusivity
static autoPtr< motionDiffusivity > New (const fvMesh &mesh, Istream &mdData)
Protected Attributes inherited from uniformDiffusivity
surfaceScalarField faceDiffusivity_
Detailed Description
Inverse distance to the given patches motion diffusivity.
Source files
inverseFaceDistanceDiffusivity.H
inverseFaceDistanceDiffusivity.C
Definition at line 46 of file inverseFaceDistanceDiffusivity.H.
Constructor & Destructor Documentation
inverseFaceDistanceDiffusivity()
inverseFaceDistanceDiffusivity (const fvMesh & mesh, Istream & mdData)
Definition at line 45 of file inverseFaceDistanceDiffusivity.C.
References inverseFaceDistanceDiffusivity::correct().
~inverseFaceDistanceDiffusivity()
~inverseFaceDistanceDiffusivity () virtual
Definition at line 60 of file inverseFaceDistanceDiffusivity.C.
Member Function Documentation
TypeName()
TypeName ("inverseFaceDistance")
correct()
void correct () virtual
Reimplemented from uniformDiffusivity.
Definition at line 66 of file inverseFaceDistanceDiffusivity.C.
References polyMesh::boundaryMesh(), forAll, HashTable< T, Key, Hash >::found(), HashSet< Key, Hash >::insert(), mesh, primitiveMesh::nInternalFaces(), PtrList< T >::setSize(), UPtrList< T >::size(), and Foam::sqrt().
Referenced by inverseFaceDistanceDiffusivity::inverseFaceDistanceDiffusivity().
The documentation for this class was generated from the following files:
src/fvMotionSolver/motionDiffusivity/inverseFaceDistance/inverseFaceDistanceDiffusivity.H
src/fvMotionSolver/motionDiffusivity/inverseFaceDistance/inverseFaceDistanceDiffusivity.C