OpenFOAM: rigidBodyMotion Class Reference
rigidBodyMotion Class Reference
Six degree of freedom motion for a rigid body.
#include <rigidBodyMotion.H>
Public Member Functions
rigidBodyMotion (const Time &time)
rigidBodyMotion (const Time &time, const dictionary &dict)
rigidBodyMotion (const Time &time, const dictionary &dict, const dictionary &stateDict)
~rigidBodyMotion ()
bool report () const
const rigidBodyModelState & state () const
rigidBodyModelState & state ()
spatialTransform X00 (const label bodyId) const
void newTime ()
void forwardDynamics (rigidBodyModelState &state, const scalarField &tau, const Field< spatialVector > &fx) const
void solve (const scalar t, const scalar deltaT, const scalarField &tau, const Field< spatialVector > &fx)
void status (const label bodyID) const
const vector vCofR (const label bodyID) const
const vector cCofR (const label bodyID) const
tmp< pointField > transformPoints (const label bodyID, const pointField &initialPoints) const
tmp< pointField > transformPoints (const label bodyID, const scalarField &weight, const pointField &initialPoints) const
tmp< pointField > transformPoints (const labelList &bodyIDs, const List< const scalarField * > &weights, const pointField &initialPoints) const
void write (Ostream &) const
bool read (const dictionary &dict)
Public Member Functions inherited from rigidBodyModel
TypeName ("rigidBodyModel")
rigidBodyModel (const Time &time)
rigidBodyModel (const Time &time, const dictionary &dict)
virtual ~rigidBodyModel ()
const Time & time () const
label nBodies () const
PtrList< rigidBody > bodies () const
const DynamicList< label > & lambda () const
const PtrList< joint > & joints () const
label nDoF () const
bool unitQuaternions () const
const vector & g () const
vector & g ()
const word & name (const label bodyID) const
const rigidBodyInertia & I (const label i) const
const spatialVector & v (const label i) const
const spatialVector & a (const label i) const
virtual label join (const label parentID, const spatialTransform &XT, autoPtr< joint > jointPtr, autoPtr< rigidBody > bodyPtr)
label join (const label parentID, const spatialTransform &XT, autoPtr< joints::composite > cJoint, autoPtr< rigidBody > bodyPtr)
label merge (const label parentID, const spatialTransform &X, autoPtr< rigidBody > bodyPtr)
bool merged (label bodyID) const
label master (label bodyID) const
label mergedBodyIndex (const label mergedBodyID) const
label mergedBodyID (const label mergedBodyIndex) const
const subBody & mergedBody (label mergedBodyID) const
label bodyID (const word &name) const
spatialTransform X0 (const label bodyId) const
vector masterPoint (const label bodyID, const vector &p) const
spatialVector v (const label bodyID, const vector &p) const
void applyRestraints (scalarField &tau, Field< spatialVector > &fx, const rigidBodyModelState &state) const
void forwardDynamics (rigidBodyModelState &state, const scalarField &tau, const Field< spatialVector > &fx) const
void forwardDynamicsCorrection (const rigidBodyModelState &state) const
bool read (const dictionary &dict)
Friends
class rigidBodySolver
Additional Inherited Members
Protected Member Functions inherited from rigidBodyModel
virtual label join_ (const label parentID, const spatialTransform &XT, autoPtr< joint > jointPtr, autoPtr< rigidBody > bodyPtr)
Protected Attributes inherited from rigidBodyModel
const Time & time_
PtrList< rigidBody > bodies_
PtrList< subBody > mergedBodies_
HashTable< label > bodyIDs_
DynamicList< label > lambda_
PtrList< joint > joints_
DynamicList< spatialTransform > XT_
label nDoF_
bool unitQuaternions_
PtrList< restraint > restraints_
vector g_
DynamicList< spatialTransform > Xlambda_
DynamicList< spatialTransform > X0_
DynamicList< spatialVector > v_
DynamicList< spatialVector > a_
DynamicList< spatialVector > c_
DynamicList< spatialTensor > IA_
DynamicList< spatialVector > pA_
DynamicList< compactSpatialTensor > S_
DynamicList< spatialVector > S1_
DynamicList< compactSpatialTensor > U_
DynamicList< spatialVector > U1_
DynamicList< tensor > Dinv_
DynamicList< vector > u_
Detailed Description
Six degree of freedom motion for a rigid body.
Angular momentum stored in body fixed reference frame. Reference orientation of the body (where Q = I) must align with the cartesian axes such that the Inertia tensor is in principle component form. Can add restraints (e.g. a spring) and constraints (e.g. motion may only be on a plane).
The time-integrator for the motion is run-time selectable with options for symplectic (explicit), Crank-Nicolson and Newmark schemes.
Source files
rigidBodyMotion.H
rigidBodyMotionI.H
rigidBodyMotion.C
rigidBodyMotionIO.C
Definition at line 71 of file rigidBodyMotion.H.
Constructor & Destructor Documentation
rigidBodyMotion() [1/3]
rigidBodyMotion (const Time & time)
Definition at line 41 of file rigidBodyMotion.C.
rigidBodyMotion() [2/3]
rigidBodyMotion (const Time & time, const dictionary & dict)
Definition at line 52 of file rigidBodyMotion.C.
References dict, rigidBodyModel::g(), and UPtrList< T >::get().
rigidBodyMotion() [3/3]
rigidBodyMotion (const Time & time, const dictionary & dict, const dictionary & stateDict)
Definition at line 85 of file rigidBodyMotion.C.
References dict, rigidBodyModel::g(), and UPtrList< T >::get().
~rigidBodyMotion()
~rigidBodyMotion ()
Definition at line 121 of file rigidBodyMotion.C.
Member Function Documentation
report()
bool report () const inline
Definition at line 23 of file rigidBodyMotionI.H.
state() [1/2]
const Foam::RBD::rigidBodyModelState & state () const inline
Definition at line 30 of file rigidBodyMotionI.H.
state() [2/2]
Foam::RBD::rigidBodyModelState & state () inline
Definition at line 37 of file rigidBodyMotionI.H.
X00()
Foam::spatialTransform X00 (const label bodyId) const
Definition at line 127 of file rigidBodyMotion.C.
newTime()
void newTime () inline
Definition at line 43 of file rigidBodyMotionI.H.
forwardDynamics()
void forwardDynamics (rigidBodyModelState & state, const scalarField & tau, const Field< spatialVector > & fx) const
Definition at line 144 of file rigidBodyMotion.C.
References rigidBodyModel::forwardDynamics(), and rigidBodyModelState::qDdot().
solve()
void solve (const scalar t, const scalar deltaT, const scalarField & tau, const Field< spatialVector > & fx)
Definition at line 164 of file rigidBodyMotion.C.
References Pstream::broadcast(), and UPstream::master().
status()
void status (const label bodyID) const
Definition at line 193 of file rigidBodyMotion.C.
References Foam::endl(), Foam::Info, SpatialVector< Cmpt >::l(), Foam::name(), Foam::nl, SpatialVector< Cmpt >::w(), X0(), and Foam::Zero.
vCofR()
const Foam::vector vCofR (const label bodyID) const
Definition at line 207 of file rigidBodyMotion.C.
References Foam::Zero.
cCofR()
const Foam::vector cCofR (const label bodyID) const
Definition at line 215 of file rigidBodyMotion.C.
References X0().
transformPoints() [1/3]
Foam::tmp< Foam::pointField > transformPoints (const label bodyID, const pointField & initialPoints) const
Definition at line 224 of file rigidBodyMotion.C.
References forAll, Foam::inv(), points, UList< T >::size(), spatialTransform::transformPoint(), and X0().
transformPoints() [2/3]
Foam::tmp< Foam::pointField > transformPoints (const label bodyID, const scalarField & weight, const pointField & initialPoints) const
Definition at line 246 of file rigidBodyMotion.C.
References forAll, septernion::I, Foam::inv(), points, s(), Foam::slerp(), spatialTransform::transformPoint(), and X0().
transformPoints() [3/3]
Foam::tmp< Foam::pointField > transformPoints (const labelList & bodyIDs, const List< const scalarField * > & weights, const pointField & initialPoints) const
Definition at line 288 of file rigidBodyMotion.C.
References Foam::average(), forAll, septernion::I, Foam::inv(), lambda(), points, UPtrList< T >::size(), and X0().
write()
void write (Ostream & os) const virtual
Reimplemented from rigidBodyModel.
Definition at line 49 of file rigidBodyMotionIO.C.
References os(), and rigidBodyModel::write().
read()
bool read (const dictionary & dict)
Definition at line 27 of file rigidBodyMotionIO.C.
References dict, Function1< Type >::NewIfPresent(), word::null, rigidBodyModel::read(), and rigidBodyModel::time().
Friends And Related Symbol Documentation
rigidBodySolver
friend class rigidBodySolver friend
Definition at line 75 of file rigidBodyMotion.H.
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/rigidBodyMotion/rigidBodyMotion.H
src/rigidBodyDynamics/rigidBodyMotion/rigidBodyMotion.C
src/rigidBodyDynamics/rigidBodyMotion/rigidBodyMotionI.H
src/rigidBodyDynamics/rigidBodyMotion/rigidBodyMotionIO.C