OpenFOAM: processorTopology Class Reference
processorTopology Class Reference
Determines/represents processor-processor connection. After instantiation contains the processor-processor connection table (globally synchronized on all processors).
#include <processorTopology.H>
Public Member Functions
processorTopology (const processorTopology &)=default
processorTopology (processorTopology &&)=default
processorTopology & operator= (const processorTopology &)=default
processorTopology & operator= (processorTopology &&)=default
processorTopology ()
label comm () const noexcept
const labelList & procNeighbours () const
const labelListList & procAdjacency () const
label procPatchLookup (const label proci) const
const lduSchedule & patchSchedule () const noexcept
template<class ProcPatch , class PatchListType >
Foam::processorTopology New (const PatchListType &patches, const label comm)
Static Public Member Functions
template<class ProcPatch , class PatchListType >
static processorTopology New (const PatchListType &patches, const label comm)
Detailed Description
Determines/represents processor-processor connection. After instantiation contains the processor-processor connection table (globally synchronized on all processors).
Note
A processorTopology is usually generated by using the New factory method, which has been wrapped into a separate header to minimize dependencies.
Warning
Does not currently correctly support multiple processor patches connecting two processors.
Source files
processorTopology.H
processorTopologyNew.H
Definition at line 61 of file processorTopology.H.
Constructor & Destructor Documentation
processorTopology() [1/3]
processorTopology (const processorTopology &) default
processorTopology() [2/3]
processorTopology (processorTopology &&) default
processorTopology() [3/3]
processorTopology ()
Definition at line 26 of file processorTopology.C.
Member Function Documentation
operator=() [1/2]
processorTopology & operator= (const processorTopology &) default
operator=() [2/2]
processorTopology & operator= (processorTopology &&) default
New() [1/2]
template<class ProcPatch , class PatchListType > static processorTopology New (const PatchListType & patches, const label comm) static
comm()
label comm () const inline noexcept
Definition at line 135 of file processorTopology.H.
Referenced by processorTopology::New().
procNeighbours()
const Foam::labelList & procNeighbours () const
Definition at line 35 of file processorTopology.C.
procAdjacency()
const Foam::labelListList & procAdjacency () const
Definition at line 95 of file processorTopology.C.
References Pstream::allGatherList(), UPtrList< T >::empty(), UPstream::msgType(), UPstream::myProcNo(), UPstream::nProcs(), UPstream::parRun(), and PtrList< T >::resize().
procPatchLookup()
label procPatchLookup (const label proci) const inline
Definition at line 149 of file processorTopology.H.
patchSchedule()
const lduSchedule & patchSchedule () const inline noexcept
Definition at line 156 of file processorTopology.H.
Referenced by faGlobalMeshData::patchSchedule(), and globalMeshData::patchSchedule().
New() [2/2]
template<class ProcPatch , class PatchListType > Foam::processorTopology New (const PatchListType & patches, const label comm)
Definition at line 47 of file processorTopologyNew.H.
References processorTopology::comm(), UPstream::defaultCommsType, UPtrList< T >::first(), forAll, UPstream::myProcNo(), UPstream::nProcs(), UPstream::parRun(), patches, PtrList< T >::push_back(), PtrList< T >::resize(), UPstream::scheduled, and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/parallel/processorTopology/processorTopology.H
src/OpenFOAM/parallel/processorTopology/processorTopology.C
src/OpenFOAM/parallel/processorTopology/processorTopologyNew.H