OpenFOAM: TDNBModel Class Reference
TDNBModel Class Reference abstract
Base class for departure from nucleation boiling models.
#include <TDNBModel.H>
Public Member Functions
TypeName ("TDNBModel")
declareRunTimeSelectionTable (autoPtr, TDNBModel, dictionary,(const dictionary &dict),(dict))
TDNBModel ()=default
virtual ~TDNBModel ()=default
virtual tmp< scalarField > TDNB (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const =0
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< TDNBModel > New (const dictionary &dict)
Detailed Description
Base class for departure from nucleation boiling models.
Source files
TDNBModel.H
TDNBModel.C
Definition at line 52 of file TDNBModel.H.
Constructor & Destructor Documentation
TDNBModel()
TDNBModel () default
~TDNBModel()
virtual ~TDNBModel () virtual default
Member Function Documentation
TypeName()
TypeName ("TDNBModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , TDNBModel , dictionary , (const dictionary &dict) , (dict))
New()
Foam::autoPtr< Foam::wallBoilingModels::TDNBModel > New (const dictionary & dict) static
Definition at line 38 of file TDNBModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, and Foam::Info.
Referenced by alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField().
TDNB()
virtual tmp< scalarField > TDNB (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const pure virtual
Implemented in Schroeder, and Shirai.
write()
void write (Ostream & os) const virtual
Reimplemented in Schroeder, and Shirai.
Definition at line 66 of file TDNBModel.C.
References os(), and Foam::type().
Referenced by Schroeder::write(), and Shirai::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/TDNBModels/TDNBModel/TDNBModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/TDNBModels/TDNBModel/TDNBModel.C