OpenFOAM: VTPsurfaceFormat< Face > Class Template Reference
VTPsurfaceFormat< Face > Class Template Reference
Write surfaces in VTP (xml) format. The default format is INLINE_BASE64.
#include <VTPsurfaceFormat.H>
Public Member Functions
VTPsurfaceFormat ()=default
virtual ~VTPsurfaceFormat ()=default
virtual void write (const fileName &name, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
Public Member Functions inherited from MeshedSurface< Face >
ClassName ("MeshedSurface")
MeshedSurface ()
MeshedSurface (const MeshedSurface &surf)
MeshedSurface (const UnsortedMeshedSurface< Face > &surf)
MeshedSurface (MeshedSurface &&surf)
MeshedSurface (UnsortedMeshedSurface< Face > &&surf)
MeshedSurface (const pointField &pointLst, const UList< Face > &faceLst, const UList< surfZone > &zoneLst)
MeshedSurface (pointField &&pointLst, List< Face > &&faceLst, const UList< surfZone > &zoneLst)
MeshedSurface (const pointField &pointLst, const UList< Face > &faceLst, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
MeshedSurface (pointField &&pointLst, List< Face > &&faceLst, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
MeshedSurface (const polyBoundaryMesh &bMesh, const bool globalPoints=false)
MeshedSurface (const surfMesh &mesh)
MeshedSurface (const fileName &name)
MeshedSurface (const fileName &name, const word &fileType)
MeshedSurface (Istream &is)
MeshedSurface (const Time &runTime)
MeshedSurface (const Time &runTime, const word &surfName)
MeshedSurface (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
declareRunTimeSelectionTable (autoPtr, MeshedSurface, fileExtension,(const fileName &name),(name))
virtual ~MeshedSurface ()
declareMemberFunctionSelectionTable (void, UnsortedMeshedSurface, write, fileExtension,(const fileName &name, const MeshedSurface< Face > &surf, IOstreamOption streamOpt, const dictionary &options),(name, surf, streamOpt, options))
label size () const
const List< Face > & surfFaces () const
const labelList & faceIds () const
const surfZoneList & surfZones () const
const vectorField & Sf () const
const scalarField & magSf () const
const vectorField & Cf () const
virtual void clear ()
virtual void addZones (const UList< surfZone > &, const bool cullEmpty=false)
virtual void addZones (const labelUList &sizes, const UList< word > &names, const bool cullEmpty=false)
virtual void addZones (const labelUList &sizes, const bool cullEmpty=false)
bool addZonesToFaces ()
virtual void removeZones ()
virtual void movePoints (const pointField &newPoints)
virtual void scalePoints (const scalar scaleFactor)
virtual void cleanup (const bool verbose)
virtual void compactPoints (labelList &pointMap=const_cast< labelList & >(labelList::null()))
virtual bool stitchFaces (const scalar tol=SMALL, const bool verbose=false)
virtual bool checkFaces (const bool verbose=false)
virtual label nTriangles () const
virtual label nTriangles (labelList &faceMap) const
virtual label triangulate ()
virtual label triangulate (labelList &faceMap)
template<class BoolListType >
void subsetMeshMap (const BoolListType &include, labelList &pointMap, labelList &faceMap) const
MeshedSurface subsetMesh (const UList< bool > &include, labelList &pointMap, labelList &faceMap) const
MeshedSurface subsetMesh (const bitSet &include, labelList &pointMap, labelList &faceMap) const
MeshedSurface subsetMesh (const UList< bool > &include) const
MeshedSurface subsetMesh (const bitSet &include) const
MeshedSurface subsetMesh (const wordRes &includeNames, const wordRes &excludeNames=wordRes()) const
void swap (MeshedSurface< Face > &surf)
void transfer (pointField &pointLst, List< Face > &faceLst)
void transfer (MeshedSurface< Face > &surf)
void transfer (UnsortedMeshedSurface< Face > &surf)
autoPtr< MeshedSurface< Face > > releaseGeom ()
void swapFaces (List< Face > &faces)
void swapPoints (pointField &points)
bool read (const fileName &name, const word &fileType)
virtual bool read (const fileName &name)
void writeStats (Ostream &os) const
virtual void write (const fileName &name, const word &fileType, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
void write (const Time &runTime, const word &surfName=word::null) const
void operator= (const MeshedSurface< Face > &surf)
void operator= (MeshedSurface< Face > &&surf)
operator MeshedSurfaceProxy< Face > () const
template<class Face >
MeshedSurface (const MeshedSurface< Face > &surf)
template<class Face >
MeshedSurface (MeshedSurface< Face > &&surf)
bool addZonesToFaces ()
bool addZonesToFaces ()
Public Member Functions inherited from PrimitivePatch<::Foam::List< Face >, pointField >
PrimitivePatch (const ::Foam::List< Face > &faces, const pointField &points)
PrimitivePatch (::Foam::List< Face > &&faces, const pointField &points)
PrimitivePatch (::Foam::List< Face > &faces, pointField &points, const bool reuse)
PrimitivePatch (const PrimitivePatch< ::Foam::List< Face >, pointField > &pp)
virtual ~PrimitivePatch ()
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
const Field< point_type > & points () const noexcept
label nFaces () const noexcept
label nPoints () const
label nEdges () const
const edgeList & edges () const
const edgeList::subList internalEdges () const
const edgeList::subList boundaryEdges () const
label nInternalEdges () const
label nBoundaryEdges () const
bool isInternalEdge (const label edgei) const
const labelList & boundaryPoints () const
const labelListList & faceFaces () const
const labelListList & edgeFaces () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointFaces () const
const List< face_type > & localFaces () const
labelList boundaryFaces () const
labelList uniqBoundaryFaces () const
const labelList & meshPoints () const
const Map< label > & meshPointMap () const
const Field< point_type > & localPoints () const
const labelList & localPointOrder () const
label whichPoint (const label gp) const
edge meshEdge (const label edgei) const
edge meshEdge (const edge &e) const
label meshEdge (const label edgei, const edgeList &allEdges, const labelListList &pointEdges) const
label findEdge (const edge &e) const
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
labelList meshEdges (const labelUList &edgeLabels, const edgeList &allEdges, const labelListList &pointEdges) const
const Field< point_type > & faceCentres () const
const Field< point_type > & faceAreas () const
const Field< scalar > & magFaceAreas () const
const Field< point_type > & faceNormals () const
const Field< point_type > & pointNormals () const
Pair< point_type > box () const
scalar sphere (const label facei) const
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
bool hasBoundaryPoints () const
bool hasEdges () const
bool hasFaceFaces () const
bool hasEdgeFaces () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointFaces () const
bool hasMeshPoints () const
bool hasMeshPointMap () const
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< ::Foam::List< Face >, pointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< ::Foam::List< Face >, pointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
const labelListList & edgeLoops () const
surfaceTopo surfaceType (labelHashSet *badEdgesPtr=nullptr) const
bool checkTopology (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
bool checkPointManifold (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
virtual void movePoints (const Field< point_type > &)
void operator= (const PrimitivePatch< ::Foam::List< Face >, pointField > &rhs)
void operator= (PrimitivePatch< ::Foam::List< Face >, pointField > &&rhs)
label whichEdge (const edge &e) const
Public Member Functions inherited from PrimitivePatchBase
ClassName ("PrimitivePatch")
PrimitivePatchBase ()=default
Public Member Functions inherited from List< Face >
constexpr List () noexcept
List (const label len)
List (const label len, const Face &val)
List (const label len, const Foam::zero)
List (const Foam::one, const Face &val)
List (const Foam::one, Face &&val)
List (const Foam::one, const Foam::zero)
List (const List< Face > &a)
List (const UList< Face > &a)
List (List< Face > &a, bool reuse)
List (const UList< Face > &list, const labelUList &indices)
List (const UList< Face > &list, const FixedList< label, N > &indices)
List (const FixedList< Face, N > &list)
List (const PtrList< Face > &list)
List (const SLList< Face > &list)
List (const IndirectListBase< Face, Addr > &list)
List (std::initializer_list< Face > list)
List (List< Face > &&list)
List (DynamicList< Face, SizeMin > &&list)
List (SLList< Face > &&list)
List (Istream &is)
autoPtr< List< Face > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const Face &val)
void resize (const label newLen)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const Face &val)
void transfer (List< Face > &list)
void transfer (DynamicList< Face, SizeMin > &list)
Face & newElmt (const label i)
Face & emplace_back (Args &&... args)
void push_back (const Face &val)
void push_back (Face &&val)
void push_back (const UList< Face > &list)
void push_back (const IndirectListBase< Face, Addr > &list)
label push_uniq (const Face &val)
void pop_back (label n=1)
void operator= (const UList< Face > &a)
void operator= (const List< Face > &list)
void operator= (const SLList< Face > &list)
void operator= (const IndirectListBase< Face, Addr > &list)
void operator= (const FixedList< Face, N > &list)
void operator= (std::initializer_list< Face > list)
void operator= (const Face &val)
void operator= (const Foam::zero)
void operator= (List< Face > &&list)
void operator= (DynamicList< Face, SizeMin > &&list)
void operator= (SLList< Face > &&list)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
void shallowCopy (const UList< Face > &)=delete
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const Face &val)
void append (Face &&val)
void append (const UList< Face > &list)
void append (const IndirectListBase< Face, Addr > &list)
label appendUniq (const Face &val)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Public Member Functions inherited from surfaceFormatsCore
surfaceFormatsCore ()=default
virtual ~surfaceFormatsCore ()=default
Static Public Member Functions
static void write (const fileName &filename, const MeshedSurfaceProxy< Face > &surf, IOstreamOption=IOstreamOption(), const dictionary &options=dictionary::null)
static void write (const fileName &filename, const UnsortedMeshedSurface< Face > &surf, IOstreamOption=IOstreamOption(), const dictionary &options=dictionary::null)
Static Public Member Functions inherited from MeshedSurface< Face >
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static bool canReadType (const word &fileType, bool verbose=false)
static bool canWriteType (const word &fileType, bool verbose=false)
static bool canRead (const fileName &name, bool verbose=false)
static autoPtr< MeshedSurface > New (const fileName &name, const word &fileType, bool mandatory=true)
static autoPtr< MeshedSurface > New (const fileName &name)
static void write (const fileName &name, const MeshedSurface< Face > &surf, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
static void write (const fileName &name, const word &fileType, const MeshedSurface< Face > &surf, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
Static Public Member Functions inherited from List< Face >
static const List< Face > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Static Public Member Functions inherited from surfaceFormatsCore
static bool checkSupport (const wordHashSet &available, const word &fileType, const bool verbose=false, const char *functionName=nullptr)
static fileName findFile (const IOobject &io, const bool isGlobal=true)
static fileName findFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
Additional Inherited Members
Public Types inherited from MeshedSurface< Face >
typedef Face face_type
typedef point point_type
Public Types inherited from PrimitivePatch<::Foam::List< Face >, pointField >
enum surfaceTopo
typedef std::remove_reference< ::Foam::List< Face > >::type::value_type face_type
typedef std::remove_reference< pointField >::type::value_type point_type
typedef ::Foam::List< Face > FaceListType
typedef pointField PointFieldType
typedef face_type FaceType
Public Types inherited from List< Face >
typedef SubList< Face > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Static Public Attributes inherited from surfaceFormatsCore
static word nativeExt
Protected Member Functions inherited from MeshedSurface< Face >
void transcribe (MeshedSurface< face > &surf)
void checkZones (const bool verbose=true)
pointField & storedPoints ()
List< Face > & storedFaces ()
labelList & storedFaceIds ()
surfZoneList & storedZones ()
void sortFacesAndStore (DynamicList< Face > &unsortedFaces, DynamicList< label > &zoneIds, DynamicList< label > &elemIds, bool sorted)
virtual void remapFaces (const labelUList &faceMapNewToOld)
void transcribe (MeshedSurface< face > &surf)
void transcribe (MeshedSurface< face > &surf)
void transcribe (MeshedSurface< face > &surf)
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Static Protected Member Functions inherited from surfaceFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
static labelList getSelectedPatches (const surfZoneList &patches, const wordRes &allow, const wordRes &deny=wordRes())
static fileName relativeFilePath (const IOobject &io, const fileName &f, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const bool isGlobal=true)
static fileName checkFile (const IOobject &io, const dictionary &dict, const bool isGlobal=true)
Static Protected Member Functions inherited from VTPsurfaceFormatCore
static vtk::outputOptions formatOptions (const dictionary &dict, vtk::outputOptions opts=vtk::formatType::INLINE_BASE64)
static void writeHeader (vtk::formatter &format, const UList< point > &pts, const label nFaces)
static void writeFooter (vtk::formatter &format)
static void writeCellData (vtk::formatter &format, const UList< surfZone > &zones)
static void writeCellData (vtk::formatter &format, const labelUList &zoneIds)
Detailed Description
template<class Face>
class Foam::fileFormats::VTPsurfaceFormat< Face >
Write surfaces in VTP (xml) format. The default format is INLINE_BASE64.
The output is never sorted by zone.
Output stream options: ignored (dictionary options only)
Format options
Property Description Required Default
format ascii or binary format no binary
precision Write precision in ascii no same as IOstream
Source files
VTPsurfaceFormat.H
VTPsurfaceFormat.C
Definition at line 79 of file VTPsurfaceFormat.H.
Constructor & Destructor Documentation
VTPsurfaceFormat()
template<class Face > VTPsurfaceFormat () default
~VTPsurfaceFormat()
template<class Face > virtual ~VTPsurfaceFormat () virtual default
Member Function Documentation
write() [1/3]
template<class Face > void write (const fileName & filename, const MeshedSurfaceProxy< Face > & surf, IOstreamOption = IOstreamOption(), const dictionary & options = dictionary::null) static
Definition at line 88 of file VTPsurfaceFormat.C.
References UPtrList< T >::empty(), f(), Foam::faceMap(), forAll, format(), formatOptions(), outputOptions::newFormatter(), os(), UPtrList< T >::size(), and UList< T >::size().
write() [2/3]
template<class Face > void write (const fileName & filename, const UnsortedMeshedSurface< Face > & surf, IOstreamOption = IOstreamOption(), const dictionary & options = dictionary::null) static
Definition at line 197 of file VTPsurfaceFormat.C.
References format(), formatOptions(), outputOptions::newFormatter(), os(), and UPtrList< T >::size().
write() [3/3]
template<class Face > virtual void write (const fileName & name, IOstreamOption streamOpt = IOstreamOption(), const dictionary & options = dictionary::null) const inline virtual
Reimplemented from MeshedSurface< Face >.
Definition at line 130 of file VTPsurfaceFormat.H.
References Foam::name(), and write().
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/vtp/VTPsurfaceFormat.H
src/surfMesh/surfaceFormats/vtp/VTPsurfaceFormat.C