OpenFOAM: UIListStreamAllocator Class Reference
UIListStreamAllocator Class Reference
#include <UIListStream.H>
Public Member Functions
const UList< char > list () const
UList< char > list ()
label size () const
std::streampos tellg () const
void rewind ()
Protected Types
typedef std::istream stream_type
Protected Member Functions
UIListStreamAllocator (char *buffer, size_t nbytes)
void reset (char *buffer, size_t nbytes)
void printBufInfo (Ostream &os) const
Protected Attributes
memorybuf::in buf_
stream_type stream_
Detailed Description
Definition at line 119 of file UIListStream.H.
Member Typedef Documentation
stream_type
typedef std::istream stream_type protected
Definition at line 125 of file UIListStream.H.
Constructor & Destructor Documentation
UIListStreamAllocator()
UIListStreamAllocator (char * buffer, size_t nbytes) inline protected
Definition at line 137 of file UIListStream.H.
Member Function Documentation
reset()
void reset (char * buffer, size_t nbytes) inline protected
Definition at line 147 of file UIListStream.H.
References UIListStreamAllocator::buf_, and memorybuf::in::resetg().
Referenced by IListStreamAllocator::reset_gbuffer().
printBufInfo()
void printBufInfo (Ostream & os) const inline protected
Definition at line 152 of file UIListStream.H.
References UIListStreamAllocator::buf_, os(), and memorybuf::in::printBufInfo().
Referenced by IListStream::print().
list() [1/2]
const UList< char > list () const inline
Definition at line 162 of file UIListStream.H.
References UIListStreamAllocator::buf_, and memorybuf::in::list().
Referenced by IListStreamAllocator::swap().
list() [2/2]
UList< char > list () inline
Definition at line 168 of file UIListStream.H.
References UIListStreamAllocator::buf_, and memorybuf::in::list().
size()
label size () const inline
Definition at line 174 of file UIListStream.H.
References UIListStreamAllocator::buf_, and memorybuf::in::capacity().
tellg()
std::streampos tellg () const inline
Definition at line 180 of file UIListStream.H.
References UIListStreamAllocator::buf_, and memorybuf::in::tellg().
Referenced by IListStream::pos(), and UIListStream::pos().
rewind()
void rewind () inline
Definition at line 186 of file UIListStream.H.
References UIListStreamAllocator::buf_, and UIListStreamAllocator::stream_.
Referenced by IListStream::rewind(), and UIListStream::rewind().
Member Data Documentation
buf_
memorybuf::in buf_ protected
Definition at line 128 of file UIListStream.H.
Referenced by UIListStreamAllocator::list(), UIListStreamAllocator::list(), UIListStreamAllocator::printBufInfo(), UIListStreamAllocator::reset(), UIListStreamAllocator::rewind(), UIListStreamAllocator::size(), and UIListStreamAllocator::tellg().
stream_
stream_type stream_ protected
Definition at line 131 of file UIListStream.H.
Referenced by UIListStreamAllocator::rewind().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/memory/UIListStream.H