OpenFOAM: faMeshTools Class Reference
faMeshTools Class Reference
A collection of tools for operating on an faMesh.
#include <faMeshTools.H>
Public Member Functions
template<class Type >
Foam::tmp< Foam::Field< Type > > flattenEdgeField (const GeometricField< Type, faePatchField, edgeMesh > &fld, const bool primitiveOrdering)
Static Public Member Functions
static void unregisterMesh (const faMesh &mesh)
static void forceDemandDriven (faMesh &mesh)
static autoPtr< faMesh > newMesh (const IOobject &io, const polyMesh &pMesh, const bool masterOnlyReading, const bool verbose=false)
static autoPtr< faMesh > loadOrCreateMesh (const IOobject &io, const polyMesh &pMesh, const bool decompose, const bool verbose=false)
static autoPtr< faMesh > loadOrCreateMesh (const IOobject &io, const polyMesh &pMesh, refPtr< fileOperation > &readHandler, const bool verbose=false)
static mapDistributePolyMesh readProcAddressing (const faMesh &mesh, const autoPtr< faMesh > &baseMeshPtr)
static void writeProcAddressing (const faMesh &mesh, const mapDistributePolyMesh &faDistMap, const bool decompose, refPtr< fileOperation > &writeHandler, const faMesh *procMesh=nullptr)
template<class Type >
static tmp< Field< Type > > flattenEdgeField (const GeometricField< Type, faePatchField, edgeMesh > &fld, const bool primitiveOrdering=false)
static void printMeshChecks (const faMesh &mesh, const int verbose=1)
Detailed Description
A collection of tools for operating on an faMesh.
Source files
faMeshTools.H
faMeshTools.C
faMeshToolsChecks.C
faMeshToolsProcAddr.C
faMeshToolsTemplates.C
Definition at line 57 of file faMeshTools.H.
Member Function Documentation
unregisterMesh()
void unregisterMesh (const faMesh & mesh) static
Definition at line 33 of file faMeshTools.C.
References objectRegistry::checkOut(), and mesh.
forceDemandDriven()
void forceDemandDriven (faMesh & mesh) static
Definition at line 45 of file faMeshTools.C.
References polyMesh::globalData(), and mesh.
newMesh()
Foam::autoPtr< Foam::faMesh > newMesh (const IOobject & io, const polyMesh & pMesh, const bool masterOnlyReading, const bool verbose = false) static
Definition at line 65 of file faMeshTools.C.
References fvMesh::boundary(), Pstream::broadcasts(), IOobject::db(), e, HashTable< T, Key, Hash >::empty(), UPtrList< T >::empty(), faceLabels(), IOobject::fileModificationChecking, forAll, UList< T >::get(), polyMesh::globalData(), dynamicFvMesh::init(), io(), Foam::isDir(), UPstream::master(), mesh, meshPtr, faMesh::meshSubDir, IOobjectOption::MUST_READ, Foam::name(), autoPtr< T >::New(), faPatch::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, nPatches, UPstream::parRun(), patches, IOobjectOption::READ_IF_PRESENT, polyMesh::regionName(), PtrList< T >::resize(), Foam::returnReduceOr(), PtrList< T >::set(), UPtrList< T >::size(), IOobject::time(), IOobject::timeStamp, Foam::type(), and UPstream::worldComm.
loadOrCreateMesh() [1/2]
Foam::autoPtr< Foam::faMesh > loadOrCreateMesh (const IOobject & io, const polyMesh & pMesh, const bool decompose, const bool verbose = false) static
Definition at line 579 of file faMeshTools.C.
References io().
loadOrCreateMesh() [2/2]
Foam::autoPtr< Foam::faMesh > loadOrCreateMesh (const IOobject & io, const polyMesh & pMesh, refPtr< fileOperation > & readHandler, const bool verbose = false) static
Parameters
readHandler Non-null reference if a mesh exists on given processor
Definition at line 599 of file faMeshTools.C.
References io().
readProcAddressing()
Foam::mapDistributePolyMesh readProcAddressing (const faMesh & mesh, const autoPtr< faMesh > & baseMeshPtr) static
Definition at line 220 of file faMeshToolsProcAddr.C.
References Foam::createReconstructMap(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, mesh, faMesh::meshSubDir, Foam::nl, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, IOobject::objectRelPath(), IOobjectOption::READ_IF_PRESENT, UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
writeProcAddressing()
void writeProcAddressing (const faMesh & mesh, const mapDistributePolyMesh & faDistMap, const bool decompose, refPtr< fileOperation > & writeHandler, const faMesh * procMesh = nullptr) static
Definition at line 300 of file faMeshToolsProcAddr.C.
References fvMesh::boundary(), mapDistributePolyMesh::cellMap(), mapDistributePolyMesh::distributePointData(), Foam::endl(), mapDistributePolyMesh::faceMap(), Foam::faceMap(), polyMesh::facesInstance(), fileOperation::fileHandler(), Foam::identity(), Foam::Info, UPstream::master(), mesh, faMesh::meshSubDir, primitiveMesh::nEdges(), primitiveMesh::nFaces(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, mapDistributePolyMesh::nOldCells(), mapDistributePolyMesh::nOldFaces(), mapDistributePolyMesh::nOldPoints(), UPstream::nonBlocking, primitiveMesh::nPoints(), IOobject::objectRelPath(), mapDistributePolyMesh::oldPatchSizes(), UPstream::parRun(), mapDistributePolyMesh::patchMap(), mapDistributePolyMesh::pointMap(), UPtrList< T >::size(), fvMesh::thisDb(), WarningInFunction, regIOobject::write(), and Foam::Zero.
flattenEdgeField() [1/2]
template<class Type > static tmp< Field< Type > > flattenEdgeField (const GeometricField< Type, faePatchField, edgeMesh > & fld, const bool primitiveOrdering = false) static
printMeshChecks()
void printMeshChecks (const faMesh & mesh, const int verbose = 1) static
Definition at line 28 of file faMeshToolsChecks.C.
References Foam::flatOutput(), Foam::gMinMax(), Foam::Info, Foam::limit(), UPstream::master(), mesh, Foam::minMax(), Foam::nl, nPatches, nPoints, p, UPstream::parRun(), patches, Foam::reduce(), Foam::returnReduce(), UPtrList< T >::size(), and Foam::sum().
flattenEdgeField() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > flattenEdgeField (const GeometricField< Type, faePatchField, edgeMesh > & fld, const bool primitiveOrdering)
Definition at line 26 of file faMeshToolsTemplates.C.
References fld(), forAll, mesh, faMesh::mesh(), Foam::New(), UPtrList< T >::size(), UList< T >::size(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/finiteArea/faMesh/faMeshTools/faMeshTools.H
src/finiteArea/faMesh/faMeshTools/faMeshTools.C
src/finiteArea/faMesh/faMeshTools/faMeshToolsChecks.C
src/finiteArea/faMesh/faMeshTools/faMeshToolsProcAddr.C
src/finiteArea/faMesh/faMeshTools/faMeshToolsTemplates.C