OpenFOAM: faceSetOption Class Reference
faceSetOption Class Reference
Intermediate abstract class for handling face-set options for the derived faOptions.
#include <faceSetOption.H>
Public Types
enum selectionModeType { smAll , smFaceSet , smFaceZone , smPatch }
Public Member Functions
TypeName ("faceSetOption")
faceSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
virtual ~faceSetOption ()=default
scalar timeStart () const noexcept
scalar duration () const noexcept
bool inTimeLimits (const scalar timeValue) const
bool useSubMesh () const noexcept
selectionModeType selectionMode () const noexcept
const wordRes & selectionNames () const noexcept
const wordRe & zoneName () const
scalar A () const noexcept
const labelList & faces () const noexcept
scalar timeStart (scalar val) noexcept
scalar duration (scalar val) noexcept
virtual bool isActive ()
virtual bool read (const dictionary &dict)
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
const word & regionName () const noexcept
const faMesh & regionMesh () const
const volSurfaceMapping & vsm () const
bool active (const bool on) noexcept
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (const areaScalarField &h, faMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, faMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const areaScalarField &h, const areaScalarField &rho, faMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (faMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (faMatrix< vector > &eqn, const label fieldi)
virtual void constrain (faMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (faMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (faMatrix< tensor > &eqn, const label fieldi)
virtual void correct (areaScalarField &field)
virtual void correct (areaVectorField &field)
virtual void correct (areaSphericalTensorField &field)
virtual void correct (areaSymmTensorField &field)
virtual void correct (areaTensorField &field)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
Static Public Attributes
static const Enum< selectionModeType > selectionModeTypeNames_
Protected Member Functions
void setSelection (const dictionary &dict)
void setFaceSelection ()
void setArea ()
template<class Type >
void subsetFilter (List< Type > &field) const
Protected Member Functions inherited from option
void resetApplied ()
Protected Attributes
scalar timeStart_
scalar duration_
selectionModeType selectionMode_
wordRes selectionNames_
labelList faces_
scalar A_
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
word regionName_
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Detailed Description
Intermediate abstract class for handling face-set options for the derived faOptions.
Usage
Minimal example by using constant/faOptions:
<userDefinedName1>
{
    // Mandatory/Optional (inherited) entries
    ...
    // Mandatory entries (unmodifiable)
    selectionMode   all;
    // Optional entries (runtime modifiable)
    timeStart       1.0;
    // Conditional mandatory entries (runtime modifiable)
    // when timeStart entry is present
    duration        1.4;
    // when selectionMode=faceZone
    faceZones       (<name> ...);
    //or: faceZone  <name>;
    // when selectionMode=patch
    patches         (<name> ...)
    //or: patch     <name>;
}
where the entries mean:
Property Description Type Reqd Dflt
selectionMode Mode of face selection - see below word yes -
timeStart Start time of faOption scalar no -1
duration
Duration of faOption execution
starting from timeStart
scalar cndtnl 0
faceSet Name of operand faceSet word cndtnl -
faceZone Name of operand faceZone(s) wordRe cndtnl -
faceZones Names of operand faceZones wordRes cndtnl -
patch Name of operand poly patch(s) wordRe cndtnl -
patches Names of operand poly patches wordRes cndtnl -
Options for the selectionMode entry:
      all       | Use all faces in the computational domain
      faceSet   | Use subset corresponding to specified (volume) faceSet
      faceZones | Use subset corresponding to specified (volume) faceZones
      faceZone  | Use subset corresponding to specified (volume) faceZones
      patch     | Use subset corresponding of specified volume patches
      patches   | Use subset corresponding of specified volume patches
The inherited entries are elaborated in:
faOption.H
Note
Source/sink options are to be added to the right-hand side of equations.
Source files
faceSetOption.H
faceSetOption.C
faceSetOptionI.H
Definition at line 168 of file faceSetOption.H.
Member Enumeration Documentation
selectionModeType
enum selectionModeType
Enumerator
smAll
"all" finite-area faces
smFaceSet
"faceSet" : subset with (volume) face set
smFaceZone
"faceZone" : subset with (volume) zone faces
smPatch
"patch" : subset with (volume) patches
Definition at line 177 of file faceSetOption.H.
Constructor & Destructor Documentation
faceSetOption()
faceSetOption (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 282 of file faceSetOption.C.
References option::coeffs_, Foam::decrIndent(), dict, Foam::incrIndent(), Foam::Info, faceSetOption::isActive(), faceSetOption::read(), faceSetOption::setArea(), faceSetOption::setFaceSelection(), and faceSetOption::setSelection().
~faceSetOption()
virtual ~faceSetOption () virtual default
Member Function Documentation
setSelection()
void setSelection (const dictionary & dict) protected
Definition at line 52 of file faceSetOption.C.
References List< T >::clear(), dict, UList< T >::empty(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::first(), List< T >::resize(), faceSetOption::selectionMode_, faceSetOption::selectionModeTypeNames_, faceSetOption::selectionNames_, faceSetOption::smAll, faceSetOption::smFaceSet, faceSetOption::smFaceZone, and faceSetOption::smPatch.
Referenced by faceSetOption::faceSetOption().
setFaceSelection()
void setFaceSelection () protected
Definition at line 135 of file faceSetOption.C.
References Foam::endl(), Foam::exit(), faceLabels(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), Foam::flatOutput(), forAll, Foam::identity(), Foam::indent(), Foam::Info, Foam::nl, patchIDs(), pbm, PtrList< T >::resize(), Foam::returnReduceAnd(), UPtrList< T >::size(), Foam::subset(), WarningInFunction, and zoneIDs.
Referenced by faceSetOption::faceSetOption().
setArea()
void setArea () protected
Definition at line 107 of file faceSetOption.C.
References IOstream::defaultPrecision(), Foam::endl(), Foam::indent(), Foam::Info, Foam::reduce(), Foam::returnReduce(), and Time::timeName().
Referenced by faceSetOption::faceSetOption().
subsetFilter()
template<class Type > void subsetFilter (List< Type > & field) const inline protected
Definition at line 24 of file faceSetOptionI.H.
References faceSetOption::faces_, field(), faceSetOption::selectionMode_, faceSetOption::smAll, UPtrList< T >::swap(), and Foam::Zero.
Referenced by externalHeatFluxSource::addSup(), and jouleHeatingSource::addSup().
TypeName()
TypeName ("faceSetOption")
timeStart() [1/2]
Foam::scalar timeStart () const inline noexcept
Definition at line 42 of file faceSetOptionI.H.
duration() [1/2]
Foam::scalar duration () const inline noexcept
Definition at line 48 of file faceSetOptionI.H.
inTimeLimits()
bool inTimeLimits (const scalar timeValue) const inline
Definition at line 54 of file faceSetOptionI.H.
useSubMesh()
bool useSubMesh () const inline noexcept
Definition at line 88 of file faceSetOptionI.H.
Referenced by externalHeatFluxSource::addSup(), limitHeight::correct(), and limitVelocity::correct().
selectionMode()
Foam::fa::faceSetOption::selectionModeType selectionMode () const inline noexcept
Definition at line 69 of file faceSetOptionI.H.
selectionNames()
const Foam::wordRes & selectionNames () const inline noexcept
Definition at line 76 of file faceSetOptionI.H.
zoneName()
const Foam::wordRe & zoneName () const inline
Definition at line 82 of file faceSetOptionI.H.
References wordRe::null.
A()
Foam::scalar A () const inline noexcept
Definition at line 94 of file faceSetOptionI.H.
Referenced by externalHeatFluxSource::addSup().
faces()
const Foam::labelList & faces () const inline noexcept
Definition at line 100 of file faceSetOptionI.H.
Referenced by externalHeatFluxSource::addSup().
timeStart() [2/2]
Foam::scalar timeStart (scalar val) inline noexcept
Definition at line 106 of file faceSetOptionI.H.
duration() [2/2]
Foam::scalar duration (scalar val) inline noexcept
Definition at line 114 of file faceSetOptionI.H.
isActive()
bool isActive () virtual
Reimplemented from option.
Definition at line 311 of file faceSetOption.C.
References option::isActive().
Referenced by faceSetOption::faceSetOption().
read()
bool read (const dictionary & dict) virtual
Reimplemented from option.
Reimplemented in limitHeight, limitVelocity, contactHeatFluxSource, externalFileSource, externalHeatFluxSource, and jouleHeatingSource.
Definition at line 336 of file faceSetOption.C.
References dict, and option::read().
Referenced by faceSetOption::faceSetOption(), limitHeight::read(), and limitVelocity::read().
Member Data Documentation
selectionModeTypeNames_
const Foam::Enum< Foam::fa::faceSetOption::selectionModeType > selectionModeTypeNames_ static
Definition at line 186 of file faceSetOption.H.
Referenced by faceSetOption::setSelection().
timeStart_
scalar timeStart_ protected
Definition at line 194 of file faceSetOption.H.
duration_
scalar duration_ protected
Definition at line 197 of file faceSetOption.H.
selectionMode_
selectionModeType selectionMode_ protected
Definition at line 200 of file faceSetOption.H.
Referenced by faceSetOption::setSelection(), and faceSetOption::subsetFilter().
selectionNames_
wordRes selectionNames_ protected
Definition at line 203 of file faceSetOption.H.
Referenced by faceSetOption::setSelection().
faces_
labelList faces_ protected
Definition at line 206 of file faceSetOption.H.
Referenced by faceSetOption::subsetFilter().
A_
scalar A_ protected
Definition at line 209 of file faceSetOption.H.
The documentation for this class was generated from the following files:
src/faOptions/faceSetOption/faceSetOption.H
src/faOptions/faceSetOption/faceSetOption.C
src/faOptions/faceSetOption/faceSetOptionI.H