OpenFOAM: fixedNormalInletOutletVelocityFvPatchVectorField Class Reference
fixedNormalInletOutletVelocityFvPatchVectorField Class Reference
Boundary conditions » Inlet | Boundary conditions » Outlet
This velocity inlet/outlet boundary condition combines a fixed normal component obtained from the "normalVelocity" patchField supplied with a fixed or zero-gradiented tangential component.
#include <fixedNormalInletOutletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("fixedNormalInletOutletVelocity")
fixedNormalInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
fixedNormalInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
fixedNormalInletOutletVelocityFvPatchVectorField (const fixedNormalInletOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
fixedNormalInletOutletVelocityFvPatchVectorField (const fixedNormalInletOutletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
fixedNormalInletOutletVelocityFvPatchVectorField (const fixedNormalInletOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual bool assignable () const
const word & phiName () const
word & phiName ()
Switch fixTangentialInflow () const
const fvPatchVectorField & normalVelocity () const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
virtual void operator= (const fvPatchField< vector > &pvf)
Protected Attributes
word phiName_
Switch fixTangentialInflow_
tmp< fvPatchVectorField > normalVelocity_
Detailed Description
This velocity inlet/outlet boundary condition combines a fixed normal component obtained from the "normalVelocity" patchField supplied with a fixed or zero-gradiented tangential component.
The tangential component is set depending on the direction of the flow and the setting of "fixTangentialInflow":
Outflow: apply zero-gradient condition to tangential components
Inflow:
fixTangentialInflow is true apply value provided by the normalVelocity patchField to the tangential components
fixTangentialInflow is false apply zero-gradient condition to tangential components.
Usage
Property Description Required Default value
phi flux field name no phi
fixTangentialInflow If true fix the tangential component for inflow yes
normalVelocity patchField providing the normal velocity field yes
Example of the boundary condition specification:
    <patchName>
    {
        type            fixedNormalInletOutletVelocity;
        fixTangentialInflow false;
        normalVelocity
        {
            type            uniformFixedValue;
            uniformValue    sine;
            uniformValueCoeffs
            {
                frequency 1;
                amplitude table
                (
                    (0  0)
                    (2  0.088)
                    (8  0.088)
                );
                scale     (0 1 0);
                level     (0 0 0);
            }
        }
        value           uniform (0 0 0);
    }
Source files
fixedNormalInletOutletVelocityFvPatchVectorField.H
fixedNormalInletOutletVelocityFvPatchVectorField.C
Definition at line 120 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
fixedNormalInletOutletVelocityFvPatchVectorField() [1/5]
fixedNormalInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 30 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
References Foam::New(), and Foam::Zero.
fixedNormalInletOutletVelocityFvPatchVectorField() [2/5]
fixedNormalInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 51 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
References dict, IOobjectOption::MUST_READ, fixedNormalInletOutletVelocityFvPatchVectorField::normalVelocity(), fvPatchFieldBase::readDict(), and Foam::Zero.
fixedNormalInletOutletVelocityFvPatchVectorField() [3/5]
fixedNormalInletOutletVelocityFvPatchVectorField (const fixedNormalInletOutletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 75 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
fixedNormalInletOutletVelocityFvPatchVectorField() [4/5]
fixedNormalInletOutletVelocityFvPatchVectorField (const fixedNormalInletOutletVelocityFvPatchVectorField & pivpvf)
Definition at line 94 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
fixedNormalInletOutletVelocityFvPatchVectorField() [5/5]
fixedNormalInletOutletVelocityFvPatchVectorField (const fixedNormalInletOutletVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 107 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("fixedNormalInletOutletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 178 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 194 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
assignable()
virtual bool assignable () const inline virtual
Definition at line 209 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
phiName() [1/2]
const word & phiName () const inline
Definition at line 215 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
References fixedNormalInletOutletVelocityFvPatchVectorField::phiName_.
phiName() [2/2]
word & phiName () inline
Definition at line 221 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
References fixedNormalInletOutletVelocityFvPatchVectorField::phiName_.
fixTangentialInflow()
Switch fixTangentialInflow () const inline
Definition at line 226 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
References fixedNormalInletOutletVelocityFvPatchVectorField::fixTangentialInflow_.
normalVelocity()
const fvPatchVectorField & normalVelocity () const inline
Definition at line 232 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
References fixedNormalInletOutletVelocityFvPatchVectorField::normalVelocity_.
Referenced by fixedNormalInletOutletVelocityFvPatchVectorField::fixedNormalInletOutletVelocityFvPatchVectorField().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 123 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Definition at line 133 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 148 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
References Foam::I, Foam::neg(), and Foam::sqr().
write()
void write (Ostream & os) const virtual
Definition at line 173 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), fvPatchField< Type >::write(), Ostream::writeEntry(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 193 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
References Foam::I, fvPatchField< Type >::operator=(), and Foam::transform().
Member Data Documentation
phiName_
word phiName_ protected
Definition at line 129 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
Referenced by fixedNormalInletOutletVelocityFvPatchVectorField::phiName(), and fixedNormalInletOutletVelocityFvPatchVectorField::phiName().
fixTangentialInflow_
Switch fixTangentialInflow_ protected
Definition at line 132 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
Referenced by fixedNormalInletOutletVelocityFvPatchVectorField::fixTangentialInflow().
normalVelocity_
tmp<fvPatchVectorField> normalVelocity_ protected
Definition at line 135 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
Referenced by fixedNormalInletOutletVelocityFvPatchVectorField::normalVelocity().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/fixedNormalInletOutletVelocity/fixedNormalInletOutletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/fixedNormalInletOutletVelocity/fixedNormalInletOutletVelocityFvPatchVectorField.C