OpenFOAM: sensitivitySurface Class Reference
sensitivitySurface Class Reference
Calculation of adjoint based sensitivities at wall faces.
#include <sensitivitySurfaceIncompressible.H>
Public Member Functions
TypeName ("surface")
sensitivitySurface (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~sensitivitySurface ()=default
void read ()
virtual bool readDict (const dictionary &dict)
void computeDerivativesSize ()
virtual void accumulateIntegrand (const scalar dt)
virtual void assembleSensitivities ()
virtual void clearSensitivities ()
autoPtr< adjointEikonalSolver > & getAdjointEikonalSolver ()
virtual void write (const word &baseName=word::null)
bool getIncludeObjective () const
bool getIncludeSurfaceArea () const
void setIncludeObjective (const bool includeObjective)
void setIncludeSurfaceArea (const bool includeSurfaceArea)
Public Member Functions inherited from adjointSensitivity
TypeName ("adjointSensitivity")
declareRunTimeSelectionTable (autoPtr, adjointSensitivity, dictionary,(const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver),(mesh, dict, adjointSolver))
adjointSensitivity (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
virtual ~adjointSensitivity ()=default
const incompressibleVars & primalVars () const
const incompressibleAdjointVars & adjointVars () const
const incompressibleAdjointSolver & adjointSolver () const
virtual const scalarField & calculateSensitivities ()
const scalarField & getSensitivities () const
tmp< volTensorField > computeGradDxDbMultiplier ()
tmp< volVectorField > adjointMeshMovementSource ()
Public Member Functions inherited from sensitivity
TypeName ("sensitivity")
sensitivity (const fvMesh &mesh, const dictionary &dict)
virtual ~sensitivity ()=default
const dictionary & dict () const
Protected Member Functions
void addGeometricSens ()
void setSuffixName ()
void smoothSensitivities ()
scalar computeRadius (const faMesh &aMesh)
Protected Attributes
bool includeSurfaceArea_
bool includePressureTerm_
bool includeGradStressTerm_
bool includeTransposeStresses_
bool useSnGradInTranposeStresses_
bool includeDivTerm_
bool includeDistance_
bool includeMeshMovement_
bool includeObjective_
bool writeGeometricInfo_
bool smoothSensitivities_
autoPtr< adjointEikonalSolver > eikonalSolver_
autoPtr< adjointMeshMovementSolver > meshMovementSolver_
autoPtr< volVectorField > nfOnPatchPtr_
autoPtr< volVectorField > SfOnPatchPtr_
autoPtr< volVectorField > CfOnPatchPtr_
Protected Attributes inherited from adjointSensitivity
scalarField derivatives_
incompressibleAdjointSolver & adjointSolver_
const incompressibleVars & primalVars_
incompressibleAdjointVars & adjointVars_
objectiveManager & objectiveManager_
Protected Attributes inherited from sensitivity
const fvMesh & mesh_
dictionary dict_
autoPtr< volScalarField > fieldSensPtr_
Additional Inherited Members
Static Public Member Functions inherited from adjointSensitivity
static autoPtr< adjointSensitivity > New (const fvMesh &mesh, const dictionary &dict, incompressibleAdjointSolver &adjointSolver)
Detailed Description
Calculation of adjoint based sensitivities at wall faces.
Reference:
    The computation of the sensitivity derivatives  follows the (E-)SI
    formulation of
        Kavvadias, I. S., Papoutsis-Kiachagias, E. M.,
        Giannakoglou, K. C. (2015).
        On the proper treatment of grid sensitivities in continuous adjoint
        methods for shape optimization.
        Journal of computational physics, 301, 1-18.
        https://doi.org/10.1016/j.jcp.2015.08.012
    whereas their smoothing based on the computation of the 'Sobolev
    gradient' is derived from
        Vassberg J. C., Jameson A. (2006).
        Aerodynamic Shape Optimization Part I: Theoretical Background.
        VKI Lecture Series, Introduction to Optimization and
        Multidisciplinary Design, Brussels, Belgium, 8 March, 2006.
Source files
sensitivitySurfaceIncompressible.H
sensitivitySurface.C
Definition at line 77 of file sensitivitySurfaceIncompressible.H.
Constructor & Destructor Documentation
sensitivitySurface()
sensitivitySurface (const fvMesh & mesh, const dictionary & dict, incompressibleAdjointSolver & adjointSolver)
Definition at line 398 of file sensitivitySurfaceIncompressible.C.
References IOobjectOption::AUTO_WRITE, sensitivitySurface::CfOnPatchPtr_, sensitivitySurface::computeDerivativesSize(), mesh, sensitivity::mesh_, sensitivitySurface::nfOnPatchPtr_, IOobjectOption::NO_READ, sensitivitySurface::read(), sensitivitySurface::setSuffixName(), sensitivitySurface::SfOnPatchPtr_, sensitivitySurface::writeGeometricInfo_, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
~sensitivitySurface()
virtual ~sensitivitySurface () virtual default
Member Function Documentation
addGeometricSens()
void addGeometricSens () protected
Definition at line 55 of file sensitivitySurfaceIncompressible.C.
References forAll, objectiveManager::getObjectiveFunctions(), Tensor< scalar >::I, sensitivitySurface::includeObjective_, sensitivity::mesh_, adjointSensitivity::objectiveManager_, p, UPtrList< T >::size(), syncTools::syncPointList(), Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
Referenced by sensitivitySurface::accumulateIntegrand().
setSuffixName()
void setSuffixName () protected
Definition at line 193 of file sensitivitySurfaceIncompressible.C.
References adjointSensitivity::adjointVars_, sensitivity::dict(), sensitivitySurface::includeMeshMovement_, word::null, shapeSensitivitiesBase::setSuffix(), and variablesSet::solverName().
Referenced by sensitivitySurface::sensitivitySurface(), and sensitivitySurface::write().
smoothSensitivities()
void smoothSensitivities () protected
Definition at line 214 of file sensitivitySurfaceIncompressible.C.
References aMesh(), sensitivitySurface::computeRadius(), DebugInfo, sensitivity::dict(), Foam::dimArea, Foam::dimless, Foam::endl(), faceLabels(), Foam::gMax(), Foam::Info, iters(), Foam::fam::laplacian(), Foam::mag(), sensitivity::mesh_, faMesh::meshSubDir, IOobjectOption::MUST_READ, Foam::nl, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, patchID, IOobjectOption::READ_IF_PRESENT, Foam::fam::Sp(), Foam::sqr(), Foam::sqrt(), vsm(), Foam::Zero, and faPatchFieldBase::zeroGradientType().
Referenced by sensitivitySurface::assembleSensitivities().
computeRadius()
scalar computeRadius (const faMesh & aMesh) protected
Definition at line 378 of file sensitivitySurfaceIncompressible.C.
References aMesh(), sensitivity::dict(), forAll, Foam::gAverage(), sensitivity::mesh_, Foam::pow(), and boundBox::span().
Referenced by sensitivitySurface::smoothSensitivities().
TypeName()
TypeName ("surface")
read()
void read ()
Definition at line 495 of file sensitivitySurfaceIncompressible.C.
References incompressibleAdjointVars::adjointTurbulence(), adjointSensitivity::adjointVars_, sensitivity::dict(), sensitivity::dict_, sensitivitySurface::eikonalSolver_, sensitivitySurface::includeDistance_, sensitivitySurface::includeDivTerm_, sensitivitySurface::includeGradStressTerm_, sensitivitySurface::includeMeshMovement_, sensitivitySurface::includeObjective_, sensitivitySurface::includePressureTerm_, sensitivitySurface::includeSurfaceArea_, sensitivitySurface::includeTransposeStresses_, sensitivity::mesh_, sensitivitySurface::meshMovementSolver_, adjointSensitivity::primalVars_, sensitivitySurface::smoothSensitivities_, sensitivitySurface::useSnGradInTranposeStresses_, and sensitivitySurface::writeGeometricInfo_.
Referenced by SIBase::read(), and sensitivitySurface::sensitivitySurface().
readDict()
bool readDict (const dictionary & dict) virtual
Reimplemented from sensitivity.
Definition at line 555 of file sensitivitySurfaceIncompressible.C.
References sensitivity::dict(), sensitivitySurface::eikonalSolver_, sensitivitySurface::meshMovementSolver_, and sensitivity::readDict().
Referenced by SIBase::readDict().
computeDerivativesSize()
void computeDerivativesSize () virtual
Reimplemented from sensitivity.
Definition at line 576 of file sensitivitySurfaceIncompressible.C.
References adjointSensitivity::derivatives_, sensitivity::mesh_, List< T >::setSize(), and UPtrList< T >::size().
Referenced by sensitivitySurface::sensitivitySurface().
accumulateIntegrand()
void accumulateIntegrand (const scalar dt) virtual
Implements adjointSensitivity.
Definition at line 587 of file sensitivitySurfaceIncompressible.C.
References sensitivitySurface::addGeometricSens(), incompressibleAdjointSolver::additionalSensitivityMapTerms(), adjointSensitivity::adjointSolver_, incompressibleAdjointVars::adjointTurbulence(), adjointSensitivity::adjointVars_, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), PtrList< T >::clear(), Field< Type >::component(), DebugInfo, Foam::dimVelocity, sensitivitySurface::eikonalSolver_, Foam::endl(), forAll, objectiveManager::getObjectiveFunctions(), Foam::fvc::grad(), sensitivitySurface::includeDistance_, sensitivitySurface::includeDivTerm_, sensitivitySurface::includeGradStressTerm_, sensitivitySurface::includeMeshMovement_, sensitivitySurface::includeObjective_, sensitivitySurface::includePressureTerm_, sensitivitySurface::includeTransposeStresses_, sensitivity::mesh_, sensitivitySurface::meshMovementSolver_, GeometricField< tensor, fvPatchField, volMesh >::New(), adjointSensitivity::objectiveManager_, p, incompressibleAdjointMeanFlowVars::pa(), adjointSensitivity::primalVars_, UPtrList< T >::size(), Foam::sqr(), Foam::twoSymm(), U, incompressibleAdjointMeanFlowVars::Ua(), Foam::unzipRow(), sensitivitySurface::useSnGradInTranposeStresses_, and Foam::Zero.
Referenced by SIBase::accumulateIntegrand().
assembleSensitivities()
void assembleSensitivities () virtual
Implements adjointSensitivity.
Definition at line 803 of file sensitivitySurfaceIncompressible.C.
References sensitivitySurface::CfOnPatchPtr_, adjointSensitivity::derivatives_, sensitivitySurface::eikonalSolver_, forAll, sensitivitySurface::includeDistance_, sensitivitySurface::includeMeshMovement_, sensitivitySurface::includeSurfaceArea_, sensitivity::mesh_, sensitivitySurface::meshMovementSolver_, sensitivitySurface::nfOnPatchPtr_, sensitivitySurface::SfOnPatchPtr_, UPtrList< T >::size(), sensitivitySurface::smoothSensitivities(), sensitivitySurface::smoothSensitivities_, and sensitivitySurface::writeGeometricInfo_.
Referenced by sensitivityBezier::assembleSensitivities(), and sensitivityVolBSplines::assembleSensitivities().
clearSensitivities()
void clearSensitivities () virtual
Reimplemented from adjointSensitivity.
Definition at line 896 of file sensitivitySurfaceIncompressible.C.
References adjointSensitivity::clearSensitivities(), shapeSensitivitiesBase::clearSensitivities(), sensitivitySurface::eikonalSolver_, sensitivitySurface::includeDistance_, sensitivitySurface::includeMeshMovement_, and sensitivitySurface::meshMovementSolver_.
Referenced by SIBase::clearSensitivities().
getAdjointEikonalSolver()
autoPtr< adjointEikonalSolver > & getAdjointEikonalSolver ()
Definition at line 913 of file sensitivitySurfaceIncompressible.C.
References sensitivitySurface::eikonalSolver_.
write()
void write (const word & baseName = word::null) virtual
Reimplemented from adjointSensitivity.
Definition at line 919 of file sensitivitySurfaceIncompressible.C.
References sensitivitySurface::CfOnPatchPtr_, sensitivitySurface::nfOnPatchPtr_, sensitivitySurface::setSuffixName(), sensitivitySurface::SfOnPatchPtr_, shapeSensitivitiesBase::write(), adjointSensitivity::write(), and sensitivitySurface::writeGeometricInfo_.
Referenced by SIBase::write().
getIncludeObjective()
bool getIncludeObjective () const inline
Definition at line 31 of file sensitivitySurfaceIncompressibleI.H.
References sensitivitySurface::includeObjective_.
Referenced by SIBase::read().
getIncludeSurfaceArea()
bool getIncludeSurfaceArea () const inline
Definition at line 37 of file sensitivitySurfaceIncompressibleI.H.
References sensitivitySurface::includeSurfaceArea_.
setIncludeObjective()
void setIncludeObjective (const bool includeObjective) inline
Definition at line 43 of file sensitivitySurfaceIncompressibleI.H.
References sensitivitySurface::includeObjective_.
Referenced by SIBase::read().
setIncludeSurfaceArea()
void setIncludeSurfaceArea (const bool includeSurfaceArea) inline
Definition at line 52 of file sensitivitySurfaceIncompressibleI.H.
References sensitivitySurface::includeSurfaceArea_.
Referenced by SIBase::read().
Member Data Documentation
includeSurfaceArea_
bool includeSurfaceArea_ protected
Definition at line 88 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::assembleSensitivities(), sensitivitySurface::getIncludeSurfaceArea(), sensitivitySurface::read(), and sensitivitySurface::setIncludeSurfaceArea().
includePressureTerm_
bool includePressureTerm_ protected
Definition at line 91 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::accumulateIntegrand(), and sensitivitySurface::read().
includeGradStressTerm_
bool includeGradStressTerm_ protected
Definition at line 94 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::accumulateIntegrand(), and sensitivitySurface::read().
includeTransposeStresses_
bool includeTransposeStresses_ protected
Definition at line 97 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::accumulateIntegrand(), and sensitivitySurface::read().
useSnGradInTranposeStresses_
bool useSnGradInTranposeStresses_ protected
Definition at line 100 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::accumulateIntegrand(), and sensitivitySurface::read().
includeDivTerm_
bool includeDivTerm_ protected
Definition at line 103 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::accumulateIntegrand(), and sensitivitySurface::read().
includeDistance_
bool includeDistance_ protected
Definition at line 106 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::accumulateIntegrand(), sensitivitySurface::assembleSensitivities(), sensitivitySurface::clearSensitivities(), and sensitivitySurface::read().
includeMeshMovement_
bool includeMeshMovement_ protected
Definition at line 109 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::accumulateIntegrand(), sensitivitySurface::assembleSensitivities(), sensitivitySurface::clearSensitivities(), sensitivitySurface::read(), and sensitivitySurface::setSuffixName().
includeObjective_
bool includeObjective_ protected
Definition at line 112 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::accumulateIntegrand(), sensitivitySurface::addGeometricSens(), sensitivitySurface::getIncludeObjective(), sensitivitySurface::read(), and sensitivitySurface::setIncludeObjective().
writeGeometricInfo_
bool writeGeometricInfo_ protected
Definition at line 115 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::assembleSensitivities(), sensitivitySurface::read(), sensitivitySurface::sensitivitySurface(), and sensitivitySurface::write().
smoothSensitivities_
bool smoothSensitivities_ protected
Definition at line 119 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::assembleSensitivities(), and sensitivitySurface::read().
eikonalSolver_
autoPtr<adjointEikonalSolver> eikonalSolver_ protected
Definition at line 121 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::accumulateIntegrand(), sensitivitySurface::assembleSensitivities(), sensitivitySurface::clearSensitivities(), sensitivitySurface::getAdjointEikonalSolver(), sensitivitySurface::read(), and sensitivitySurface::readDict().
meshMovementSolver_
autoPtr<adjointMeshMovementSolver> meshMovementSolver_ protected
Definition at line 123 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::accumulateIntegrand(), sensitivitySurface::assembleSensitivities(), sensitivitySurface::clearSensitivities(), sensitivitySurface::read(), and sensitivitySurface::readDict().
nfOnPatchPtr_
autoPtr<volVectorField> nfOnPatchPtr_ protected
Definition at line 126 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::assembleSensitivities(), sensitivitySurface::sensitivitySurface(), and sensitivitySurface::write().
SfOnPatchPtr_
autoPtr<volVectorField> SfOnPatchPtr_ protected
Definition at line 127 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::assembleSensitivities(), sensitivitySurface::sensitivitySurface(), and sensitivitySurface::write().
CfOnPatchPtr_
autoPtr<volVectorField> CfOnPatchPtr_ protected
Definition at line 128 of file sensitivitySurfaceIncompressible.H.
Referenced by sensitivitySurface::assembleSensitivities(), sensitivitySurface::sensitivitySurface(), and sensitivitySurface::write().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/sensitivitySurface/sensitivitySurfaceIncompressible.H
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/sensitivitySurface/sensitivitySurfaceIncompressible.C
src/optimisation/adjointOptimisation/adjoint/optimisation/adjointSensitivity/incompressible/sensitivitySurface/sensitivitySurfaceIncompressibleI.H