OpenFOAM: pressureDirectedInletOutletVelocityFvPatchVectorField Class Reference
pressureDirectedInletOutletVelocityFvPatchVectorField Class Reference
Boundary conditions » Inlet | Boundary conditions » Outlet
This velocity inlet/outlet boundary condition is applied to velocity boundaries where the pressure is specified. A zero-gradient condition is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with the specified inlet direction.
#include <pressureDirectedInletOutletVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("pressureDirectedInletOutletVelocity")
pressureDirectedInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
pressureDirectedInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
pressureDirectedInletOutletVelocityFvPatchVectorField (const pressureDirectedInletOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
pressureDirectedInletOutletVelocityFvPatchVectorField (const pressureDirectedInletOutletVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
pressureDirectedInletOutletVelocityFvPatchVectorField (const pressureDirectedInletOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual bool assignable () const
const word & rhoName () const
word & rhoName ()
const word & phiName () const
word & phiName ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This velocity inlet/outlet boundary condition is applied to velocity boundaries where the pressure is specified. A zero-gradient condition is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with the specified inlet direction.
Usage
Property Description Required Default value
phi flux field name no phi
rho density field name no rho
inletDirection inlet direction per patch face yes
Example of the boundary condition specification:
    <patchName>
    {
        type            pressureDirectedInletOutletVelocity;
        phi             phi;
        rho             rho;
        inletDirection  uniform (1 0 0);
        value           uniform 0;
    }
Note
Sign conventions:
positive flux (out of domain): apply zero-gradient condition
negative flux (into of domain): derive from the flux with specified direction
See also
Foam::mixedFvPatchVectorField
Source files
pressureDirectedInletOutletVelocityFvPatchVectorField.H
pressureDirectedInletOutletVelocityFvPatchVectorField.C
Definition at line 102 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
pressureDirectedInletOutletVelocityFvPatchVectorField() [1/5]
pressureDirectedInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 30 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
References Foam::Zero.
pressureDirectedInletOutletVelocityFvPatchVectorField() [2/5]
pressureDirectedInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 64 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
References dict, IOobjectOption::MUST_READ, fvPatchFieldBase::readDict(), and Foam::Zero.
pressureDirectedInletOutletVelocityFvPatchVectorField() [3/5]
pressureDirectedInletOutletVelocityFvPatchVectorField (const pressureDirectedInletOutletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 48 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
pressureDirectedInletOutletVelocityFvPatchVectorField() [4/5]
pressureDirectedInletOutletVelocityFvPatchVectorField (const pressureDirectedInletOutletVelocityFvPatchVectorField & pivpvf)
Definition at line 85 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
pressureDirectedInletOutletVelocityFvPatchVectorField() [5/5]
pressureDirectedInletOutletVelocityFvPatchVectorField (const pressureDirectedInletOutletVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 98 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("pressureDirectedInletOutletVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 159 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 178 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
assignable()
virtual bool assignable () const inline virtual
Definition at line 197 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
rhoName() [1/2]
const word & rhoName () const inline
Definition at line 203 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
rhoName() [2/2]
word & rhoName () inline
Definition at line 209 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
phiName() [1/2]
const word & phiName () const inline
Definition at line 215 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
phiName() [2/2]
word & phiName () inline
Definition at line 221 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 114 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Definition at line 124 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 140 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::exit(), Foam::FatalError, FatalErrorInFunction, n, and Foam::neg().
write()
void write (Ostream & os) const virtual
Definition at line 178 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntryIfDifferent(), and fvPatchField< Type >::writeValueEntry().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 193 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
References Foam::lerp().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/pressureDirectedInletOutletVelocity/pressureDirectedInletOutletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/pressureDirectedInletOutletVelocity/pressureDirectedInletOutletVelocityFvPatchVectorField.C