OpenFOAM: LduMatrix< Type, DType, LUType >::smoother Class Reference
LduMatrix< Type, DType, LUType >::smoother Class Reference abstract
#include <LduMatrix.H>
Public Member Functions
virtual const word & type () const =0
declareRunTimeSelectionTable (autoPtr, smoother, symMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix),(fieldName, matrix))
declareRunTimeSelectionTable (autoPtr, smoother, asymMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix),(fieldName, matrix))
smoother (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix)
virtual ~smoother ()=default
const word & fieldName () const noexcept
const LduMatrix< Type, DType, LUType > & matrix () const noexcept
virtual void smooth (Field< Type > &psi, const label nSweeps) const =0
Static Public Member Functions
static autoPtr< smoother > New (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &smootherDict)
Protected Attributes
word fieldName_
const LduMatrix< Type, DType, LUType > & matrix_
Detailed Description
template<class Type, class DType, class LUType>
class Foam::LduMatrix< Type, DType, LUType >::smoother
Definition at line 273 of file LduMatrix.H.
Constructor & Destructor Documentation
smoother()
template<class Type , class DType , class LUType > smoother (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix)
Definition at line 97 of file LduMatrixSmoother.C.
~smoother()
template<class Type , class DType , class LUType > virtual ~smoother () virtual default
Member Function Documentation
type()
template<class Type , class DType , class LUType > virtual const word & type () const pure virtual
declareRunTimeSelectionTable() [1/2]
template<class Type , class DType , class LUType > declareRunTimeSelectionTable (autoPtr , smoother , symMatrix , (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix) , (fieldName, matrix))
declareRunTimeSelectionTable() [2/2]
template<class Type , class DType , class LUType > declareRunTimeSelectionTable (autoPtr , smoother , asymMatrix , (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix) , (fieldName, matrix))
New()
template<class Type , class DType , class LUType > Foam::autoPtr< typename Foam::LduMatrix< Type, DType, LUType >::smoother > New (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix, const dictionary & smootherDict) static
Definition at line 28 of file LduMatrixSmoother.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, LduMatrix< Type, DType, LUType >::smoother::fieldName(), UPtrList< T >::get(), and LduMatrix< Type, DType, LUType >::smoother::matrix().
Referenced by SmoothSolver< Type, DType, LUType >::solve().
fieldName()
template<class Type , class DType , class LUType > const word & fieldName () const inline noexcept
Definition at line 349 of file LduMatrix.H.
References LduMatrix< Type, DType, LUType >::smoother::fieldName_.
Referenced by LduMatrix< Type, DType, LUType >::smoother::New().
matrix()
template<class Type , class DType , class LUType > const LduMatrix< Type, DType, LUType > & matrix () const inline noexcept
Definition at line 354 of file LduMatrix.H.
References LduMatrix< Type, DType, LUType >::smoother::matrix_.
Referenced by LduMatrix< Type, DType, LUType >::smoother::New(), and TGaussSeidelSmoother< Type, DType, LUType >::TGaussSeidelSmoother().
smooth()
template<class Type , class DType , class LUType > virtual void smooth (Field< Type > & psi, const label nSweeps) const pure virtual
Implemented in TGaussSeidelSmoother< Type, DType, LUType >.
Member Data Documentation
fieldName_
template<class Type , class DType , class LUType > word fieldName_ protected
Definition at line 279 of file LduMatrix.H.
Referenced by LduMatrix< Type, DType, LUType >::smoother::fieldName().
matrix_
template<class Type , class DType , class LUType > const LduMatrix<Type, DType, LUType>& matrix_ protected
Definition at line 280 of file LduMatrix.H.
Referenced by LduMatrix< Type, DType, LUType >::smoother::matrix().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrix.H
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrixSmoother.C