OpenFOAM: contactAngleForce Class Reference
contactAngleForce Class Reference abstract
Base-class for film contact angle force models.
#include <contactAngleForce.H>
Public Member Functions
TypeName ("contactAngle")
contactAngleForce (const word &typeName, liquidFilmBase &film, const dictionary &dict)
virtual ~contactAngleForce ()=default
virtual tmp< faVectorMatrix > correct (areaVectorField &U)
Public Member Functions inherited from force
TypeName ("force")
declareRunTimeSelectionTable (autoPtr, force, dictionary,(liquidFilmBase &film, const dictionary &dict),(film, dict))
force (liquidFilmBase &film)
force (const word &modelType, liquidFilmBase &film, const dictionary &dict)
virtual ~force ()
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (liquidFilmBase &film)
filmSubModelBase (liquidFilmBase &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
filmSubModelBase (const word &modelName, liquidFilmBase &film, const dictionary &dict, const word &baseName, const word &modelType)
virtual ~filmSubModelBase ()
virtual bool writeTime () const
const liquidFilmBase & film () const
liquidFilmBase & film ()
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
virtual void cacheFields (const bool store)
virtual fileName localPath () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
virtual void write (Ostream &os) const
Protected Member Functions
virtual tmp< areaScalarField > theta () const =0
Protected Member Functions inherited from subModelBase
bool inLine () const
Additional Inherited Members
Static Public Member Functions inherited from force
static autoPtr< force > New (liquidFilmBase &film, const dictionary &dict, const word &modelType)
Public Attributes inherited from subModelBase
bool log
Protected Attributes inherited from filmSubModelBase
liquidFilmBase & filmModel_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
Base-class for film contact angle force models.
The effect of the contact angle force can be ignored over a specified distance from patches.
The contact-angle force is implemented as follows:
with if :
where
= Contact-angle force [N/m^2/rho]
= Empirical constant [-]
= Liquid-air interfacial surface tension [kg/s^2]
= Contact angle [rad]
= Inverse width in direction normal to contact line [1/m]
= Direction normal to contact line [-]
= Film density [kg/m^3]
= Face-area vector [m^2]
= Contact-line movement force [N/m^2/rho]
= Film kinematic viscosity [m^2/s]
= Film velocity [m/s]
= Critical film height [m]
Reference:
        Governing equations (tag:MHDX):
            Meredith, K. V., Heather, A., De Vries, J., & Xin, Y. (2011).
            A numerical model for partially-wetted flow of thin liquid films.
            Computational Methods in Multiphase Flow VI, 70, 239.
        Contact line movement (tag:NDPC):
            Novk, M., Devaradja, R., Papper, J., & ern, M. (2020).
            Efficient CFD methods for assessment of water management.
            In 20. Internationales Stuttgarter Symposium (pp. 151-170).
            Springer Vieweg, Wiesbaden.
Usage
Minimal example:
{
    // Mandatory entries
    Ccf             <scalar>;
    // Optional entries
    hCrit           <scalar>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
Ccf Empirical coefficient scalar yes -
hCrit Critical film height [m] scalar no GREAT
The inherited entries are elaborated in:
force.H
Source files
contactAngleForce.H
contactAngleForce.C
Definition at line 188 of file contactAngleForce.H.
Constructor & Destructor Documentation
contactAngleForce()
contactAngleForce (const word & typeName, liquidFilmBase & film, const dictionary & dict)
Definition at line 42 of file contactAngleForce.C.
~contactAngleForce()
virtual ~contactAngleForce () virtual default
Member Function Documentation
theta()
virtual tmp< areaScalarField > theta () const protected pure virtual
Implemented in dynamicContactAngleForce.
Referenced by contactAngleForce::correct().
TypeName()
TypeName ("contactAngle")
correct()
tmp< faVectorMatrix > correct (areaVectorField & U) virtual
Implements force.
Definition at line 57 of file contactAngleForce.C.
References alpha, Foam::cos(), Foam::degToRad(), Foam::dimArea, Foam::dimDensity, Foam::dimForce, filmSubModelBase::film(), forAll, Foam::fac::grad(), mu, n, tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, Foam::normalised(), p, rhof(), IOobject::scopedName(), contactAngleForce::theta(), timeName, U, Uf, regIOobject::write(), filmSubModelBase::writeTime(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/regionFaModels/liquidFilm/subModels/kinematic/force/contactAngleForces/contactAngleForce/contactAngleForce.H
src/regionFaModels/liquidFilm/subModels/kinematic/force/contactAngleForces/contactAngleForce/contactAngleForce.C