OpenFOAM: NSRDSfunc2 Class Reference
NSRDSfunc2 Class Reference
NSRDS function number 102.
#include <NSRDSfunc2.H>
Public Member Functions
TypeName ("NSRDSfunc2")
NSRDSfunc2 (const scalar a, const scalar b, const scalar c, const scalar d)
NSRDSfunc2 (const dictionary &dict)
scalar f (scalar, scalar T) const
void writeData (Ostream &os) const
Public Member Functions inherited from thermophysicalFunction
TypeName ("thermophysicalFunction")
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, dictionary,(const dictionary &dict),(dict))
thermophysicalFunction ()
virtual ~thermophysicalFunction ()=default
Friends
Ostream & operator<< (Ostream &os, const NSRDSfunc2 &f)
Additional Inherited Members
Static Public Member Functions inherited from thermophysicalFunction
static autoPtr< thermophysicalFunction > New (Istream &is)
static autoPtr< thermophysicalFunction > New (const dictionary &dict)
Detailed Description
NSRDS function number 102.
Source:
                  NSRDS - AICHE
             Data Compilation Tables
                of Properties of
                 Pure Compounds
    Design Institute for Physical Property Data
      American Institute of Chemical Engineers
              345 East 47th Street
            New York, New York 10017
     National Standard Reference Data System
     American Institute of Chemical Engineers
      T.E. Daubert       -       R.P. Danner
        Department of Chemical Engineering
        The Pennsylvania State University
            University Park, PA 16802
Definition at line 63 of file NSRDSfunc2.H.
Constructor & Destructor Documentation
NSRDSfunc2() [1/2]
NSRDSfunc2 (const scalar a, const scalar b, const scalar c, const scalar d)
Definition at line 34 of file NSRDSfunc2.C.
NSRDSfunc2() [2/2]
NSRDSfunc2 (const dictionary & dict)
Definition at line 49 of file NSRDSfunc2.C.
Member Function Documentation
TypeName()
TypeName ("NSRDSfunc2")
f()
scalar f (scalar , scalar T) const inline virtual
Implements thermophysicalFunction.
Definition at line 97 of file NSRDSfunc2.H.
References Foam::pow(), Foam::sqr(), and T.
writeData()
void writeData (Ostream & os) const inline virtual
Implements thermophysicalFunction.
Definition at line 103 of file NSRDSfunc2.H.
References os(), and token::SPACE.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const NSRDSfunc2 & f) friend
Definition at line 114 of file NSRDSfunc2.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc2/NSRDSfunc2.H
src/thermophysicalModels/thermophysicalProperties/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc2/NSRDSfunc2.C