OpenFOAM: motionSmootherData Class Reference
motionSmootherData Class Reference
#include <motionSmootherData.H>
Public Member Functions
motionSmootherData (const pointMesh &pMesh)
motionSmootherData (const pointVectorField &displacement)
pointVectorField & displacement ()
const pointVectorField & displacement () const
const pointScalarField & scale () const
const pointField & oldPoints () const
Protected Attributes
pointVectorField displacement_
pointScalarField scale_
pointField oldPoints_
Detailed Description
Source files
motionSmootherData.H
motionSmootherData.C
Definition at line 45 of file motionSmootherData.H.
Constructor & Destructor Documentation
motionSmootherData() [1/2]
motionSmootherData (const pointMesh & pMesh) explicit
Definition at line 25 of file motionSmootherData.C.
References Foam::dimless.
motionSmootherData() [2/2]
motionSmootherData (const pointVectorField & displacement) explicit
Definition at line 59 of file motionSmootherData.C.
Member Function Documentation
displacement() [1/2]
Foam::pointVectorField & displacement ()
Definition at line 95 of file motionSmootherData.C.
Referenced by snappySnapDriver::doSnap(), snappySnapDriver::scaleMesh(), and snappySnapDriver::smoothDisplacement().
displacement() [2/2]
const Foam::pointVectorField & displacement () const
Definition at line 101 of file motionSmootherData.C.
scale()
const Foam::pointScalarField & scale () const
Definition at line 107 of file motionSmootherData.C.
oldPoints()
const Foam::pointField & oldPoints () const
Definition at line 113 of file motionSmootherData.C.
Member Data Documentation
displacement_
pointVectorField displacement_ protected
Definition at line 52 of file motionSmootherData.H.
scale_
pointScalarField scale_ protected
Definition at line 55 of file motionSmootherData.H.
oldPoints_
pointField oldPoints_ protected
Definition at line 58 of file motionSmootherData.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/motionSmoother/motionSmootherData.H
src/dynamicMesh/motionSmoother/motionSmootherData.C