OpenFOAM: Ostream Class Reference
Ostream Class Reference abstract
An Ostream is an abstract base class for all output systems (streams, files, token lists, etc).
#include <Ostream.H>
Public Member Functions
Ostream (const Ostream &)=default
virtual ~Ostream ()=default
Ostream (IOstreamOption streamOpt=IOstreamOption())
Ostream (IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual bool write (const token &tok)=0
virtual Ostream & write (const char c)=0
virtual Ostream & write (const char *str)=0
virtual Ostream & write (const word &str)=0
virtual Ostream & write (const keyType &kw)
virtual Ostream & write (const string &str)=0
virtual Ostream & writeQuoted (const std::string &str, const bool quoted=true)=0
virtual Ostream & write (const int32_t val)=0
virtual Ostream & write (const int64_t val)=0
virtual Ostream & write (const float val)=0
virtual Ostream & write (const double val)=0
virtual Ostream & write (const char *data, std::streamsize count)=0
virtual Ostream & writeRaw (const char *data, std::streamsize count)=0
virtual bool beginRawWrite (std::streamsize count)=0
virtual bool endRawWrite ()=0
virtual void indent ()=0
unsigned short indentSize () const noexcept
unsigned short indentSize (unsigned short val) noexcept
unsigned short indentLevel () const noexcept
unsigned short indentLevel (unsigned short val) noexcept
void incrIndent () noexcept
void decrIndent ()
virtual Ostream & writeKeyword (const keyType &kw)
virtual Ostream & beginBlock (const keyType &kw)
virtual Ostream & beginBlock ()
virtual Ostream & endBlock ()
virtual Ostream & endEntry ()
template<class T >
Ostream & writeEntry (const keyType &key, const T &value)
template<class T >
Ostream & writeEntryIfDifferent (const word &key, const T &value1, const T &value2)
virtual void flush ()=0
virtual void endl ()=0
virtual char fill () const =0
virtual char fill (const char fillch)=0
virtual int width () const =0
virtual int width (const int w)=0
virtual int precision () const =0
virtual int precision (const int p)=0
Ostream & operator() () const
unsigned short & indentLevel () noexcept
unsigned short & indentSize () noexcept
Public Member Functions inherited from IOstream
IOstream (const IOstream &)=default
virtual ~IOstream ()=default
IOstream (IOstreamOption streamOpt=IOstreamOption())
IOstream (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual const fileName & name () const
fileName relativeName () const
virtual bool check (const char *operation) const
bool fatalCheck (const char *operation) const
bool opened () const noexcept
bool closed () const noexcept
bool good () const noexcept
bool eof () const noexcept
bool fail () const noexcept
bool bad () const noexcept
operator bool () const noexcept
bool operator! () const noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void setLabelByteSize (unsigned nbytes) noexcept
void setScalarByteSize (unsigned nbytes) noexcept
template<class T = label>
std::enable_if< std::is_integral< T >::value, bool >::type checkLabelSize () const noexcept
template<class T = scalar>
std::enable_if< std::is_floating_point< T >::value, bool >::type checkScalarSize () const noexcept
label lineNumber () const noexcept
label & lineNumber () noexcept
label lineNumber (const label num) noexcept
virtual ios_base::fmtflags flags () const =0
void setEof () noexcept
void setFail () noexcept
void setBad ()
virtual ios_base::fmtflags flags (const ios_base::fmtflags f)=0
ios_base::fmtflags setf (const ios_base::fmtflags f)
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
void unsetf (const ios_base::fmtflags f)
virtual void print (Ostream &os) const
void print (Ostream &os, const int streamState) const
InfoProxy< IOstream > info () const noexcept
Public Member Functions inherited from IOstreamOption
constexpr IOstreamOption (streamFormat fmt=streamFormat::ASCII, compressionType comp=compressionType::UNCOMPRESSED) noexcept
constexpr IOstreamOption (streamFormat fmt, compressionType comp, versionNumber ver) noexcept
constexpr IOstreamOption (streamFormat fmt, versionNumber ver, compressionType comp=compressionType::UNCOMPRESSED) noexcept
IOstreamOption (const IOstreamOption &opt, streamFormat fmt) noexcept
streamFormat format () const noexcept
streamFormat format (const streamFormat fmt) noexcept
streamFormat format (const word &formatName)
compressionType compression () const noexcept
compressionType compression (const compressionType comp) noexcept
compressionType compression (const word &compName)
versionNumber version () const noexcept
versionNumber version (const versionNumber ver) noexcept
versionNumber version (const token &tok)
Protected Attributes
unsigned short indentSize_ = 4
unsigned short indentLevel_ = 0
Protected Attributes inherited from IOstream
std::ios_base::iostate ioState_
streamAccess openClosed_
unsigned char sizeofLabel_
unsigned char sizeofScalar_
label lineNumber_
Static Protected Attributes
static constexpr const unsigned short entryIndentation_ = 16
Static Protected Attributes inherited from IOstream
static fileName staticName_
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0 , OPENED }
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII = 0 , BINARY }
enum compressionType : char { UNCOMPRESSED = 0 , COMPRESSED }
enum appendType : char { NON_APPEND = 0 , APPEND }
enum atomicType : char { NON_ATOMIC = 0 , ATOMIC }
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision () noexcept
static unsigned int defaultPrecision (unsigned int prec) noexcept
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName, const streamFormat deflt=streamFormat::ASCII)
static streamFormat formatEnum (const word &key, const dictionary &dict, const streamFormat deflt=streamFormat::ASCII)
static compressionType compressionEnum (const word &compName, const compressionType deflt=compressionType::UNCOMPRESSED)
static compressionType compressionEnum (const word &key, const dictionary &dict, const compressionType deflt=compressionType::UNCOMPRESSED)
Static Public Attributes inherited from IOstream
static unsigned int precision_
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
static const versionNumber currentVersion
Protected Member Functions inherited from IOstream
void setOpened () noexcept
void setClosed () noexcept
void setState (std::ios_base::iostate state) noexcept
void setGood () noexcept
Detailed Description
An Ostream is an abstract base class for all output systems (streams, files, token lists, etc).
Source files
Ostream.H
Ostream.C
Definition at line 55 of file Ostream.H.
Constructor & Destructor Documentation
Ostream() [1/3]
Ostream (const Ostream &) default
~Ostream()
virtual ~Ostream () virtual default
Ostream() [2/3]
Ostream (IOstreamOption streamOpt = IOstreamOption()) inline explicit
Definition at line 88 of file Ostream.H.
Ostream() [3/3]
Ostream (IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp = IOstreamOption::UNCOMPRESSED) inline explicit
Definition at line 95 of file Ostream.H.
Member Function Documentation
write() [1/11]
virtual bool write (const token & tok) pure virtual
Implemented in ensightFile, UOPstreamBase, UOPstream, UOPBstream, OSstream, prefixOSstream, OTstream, and OBJstream.
Referenced by snappyLayerDriver::addLayers(), snappyLayerDriver::addLayers(), snappySnapDriver::doSnap(), if(), if(), interpolationTable< scalar >::interpolateValue(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), refinementIterator::setRefinement(), snappySnapDriver::smoothDisplacement(), ddt2::write(), extractEulerianParticles::write(), nearWallFields::write(), CelikEtaIndex::write(), CelikNuIndex::write(), PopeIndex::write(), forces::write(), dsmcFields::write(), electricPotential::write(), OBJstream::write(), cyclicAMIPolyPatch::write(), cyclicPolyPatch::write(), sixDoFRigidBodyMotion::write(), scene::write(), mappedPatchBase::write(), ReactionList< ThermoType >::write(), surfaceFieldValue::writeAll(), OBJstream::writeQuoted(), and vtkWriter::writeTemplate().
write() [2/11]
virtual Ostream & write (const char c) pure virtual
Implemented in OBJstream, UOPstreamBase, UOPstream, UOPBstream, OSstream, prefixOSstream, OTstream, OBJstream, and ensightFile.
write() [3/11]
virtual Ostream & write (const char * str) pure virtual
Implemented in ensightFile, OBJstream, UOPstreamBase, UOPstream, UOPBstream, OSstream, prefixOSstream, OTstream, and OBJstream.
write() [4/11]
virtual Ostream & write (const word & str) pure virtual
Implemented in ensightFile, OBJstream, UOPstreamBase, UOPstream, UOPBstream, OSstream, OTstream, OBJstream, and prefixOSstream.
write() [5/11]
Foam::Ostream & write (const keyType & kw) virtual
Reimplemented in OBJstream.
Definition at line 44 of file Ostream.C.
References writeQuoted().
write() [6/11]
virtual Ostream & write (const string & str) pure virtual
Implemented in ensightFile, OBJstream, OSHA1stream, UOPstreamBase, UOPstream, UOPBstream, OSstream, OTstream, OBJstream, and prefixOSstream.
writeQuoted()
virtual Ostream & writeQuoted (const std::string & str, const bool quoted = true) pure virtual
Implemented in OBJstream, UOPstreamBase, OSstream, OTstream, and prefixOSstream.
Referenced by Foam::operator<<().
write() [7/11]
virtual Ostream & write (const int32_t val) pure virtual
Implemented in ensightFile, UOPstreamBase, UOPstream, UOPBstream, OSstream, prefixOSstream, OTstream, and OBJstream.
write() [8/11]
virtual Ostream & write (const int64_t val) pure virtual
Implemented in ensightFile, UOPstreamBase, UOPstream, UOPBstream, OSstream, prefixOSstream, OTstream, and OBJstream.
write() [9/11]
virtual Ostream & write (const float val) pure virtual
Implemented in ensightFile, UOPstreamBase, UOPstream, UOPBstream, OSstream, prefixOSstream, OTstream, and OBJstream.
write() [10/11]
virtual Ostream & write (const double val) pure virtual
Implemented in ensightFile, UOPstreamBase, UOPstream, UOPBstream, OSstream, prefixOSstream, OTstream, and OBJstream.
write() [11/11]
virtual Ostream & write (const char * data, std::streamsize count) pure virtual
Implemented in ensightFile, prefixOSstream, UOPstreamBase, UOPstream, UOPBstream, OSstream, OTstream, and OBJstream.
writeRaw()
virtual Ostream & writeRaw (const char * data, std::streamsize count) pure virtual
Implemented in UOPstreamBase, OSstream, and OTstream.
beginRawWrite()
virtual bool beginRawWrite (std::streamsize count) pure virtual
Implemented in UOPstreamBase, OSstream, and OTstream.
endRawWrite()
virtual bool endRawWrite () pure virtual
Implemented in UOPstreamBase, OSstream, and OTstream.
indent()
virtual void indent () pure virtual
Implemented in UOPstreamBase, OSstream, prefixOSstream, and OTstream.
indentSize() [1/3]
unsigned short indentSize () const inline noexcept
Definition at line 172 of file Ostream.H.
References Ostream::indentSize_.
indentSize() [2/3]
unsigned short indentSize (unsigned short val) inline noexcept
Definition at line 178 of file Ostream.H.
References Ostream::indentSize_.
indentLevel() [1/3]
unsigned short indentLevel () const inline noexcept
Definition at line 186 of file Ostream.H.
References Ostream::indentLevel_.
indentLevel() [2/3]
unsigned short indentLevel (unsigned short val) inline noexcept
Definition at line 192 of file Ostream.H.
References Ostream::indentLevel_.
incrIndent()
void incrIndent () inline noexcept
Definition at line 200 of file Ostream.H.
References Ostream::indentLevel_.
Referenced by Foam::incrIndent().
decrIndent()
void decrIndent ()
Definition at line 30 of file Ostream.C.
References Ostream::indentLevel_.
Referenced by Foam::decrIndent().
writeKeyword()
Foam::Ostream & writeKeyword (const keyType & kw) virtual
Reimplemented in ensightFile, and ensightGeoFile.
Definition at line 50 of file Ostream.C.
References Foam::indent(), UPtrList< T >::size(), token::SPACE, write(), and writeQuoted().
Referenced by patchIdentifier::write(), zoneIdentifier::write(), JanevReactionRate::write(), LangmuirHinshelwoodReactionRate::write(), primitiveEntry::write(), UniformDimensionedField< Type >::writeData(), Function1< Type >::writeData(), ensightCells::writeDict(), ensightFaces::writeDict(), Ostream::writeEntry(), PackedList< Width >::writeEntry(), FixedList< T, N >::writeEntry(), UList< T >::writeEntry(), dimensioned< Type >::writeEntry(), Field< Type >::writeEntry(), and exprDriver::writeVariableStrings().
beginBlock() [1/2]
Foam::Ostream & beginBlock (const keyType & kw) virtual
Definition at line 80 of file Ostream.C.
References Foam::beginBlock(), Foam::indent(), write(), and writeQuoted().
Referenced by Foam::beginBlock(), Foam::operator<<(), Foam::RBD::operator<<(), Foam::operator<<(), Foam::printDOT(), fixedNormalInletOutletVelocityFvPatchVectorField::write(), freestreamFvPatchField< Type >::write(), outletMappedUniformInletFvPatchField< Type >::write(), scaledFixedValueFvPatchField< Type >::write(), sixDoFRigidBodyMotion::write(), surfZone::write(), surfacePatch::write(), polynomialSolidTransport< Thermo, PolySize >::write(), tabulatedAnIsoSolidTransport< Thermo >::write(), tabulatedSolidTransport< Thermo >::write(), adiabaticPerfectFluid< Specie >::write(), Boussinesq< Specie >::write(), icoTabulated< Specie >::write(), incompressiblePerfectGas< Specie >::write(), linear< Type >::write(), perfectFluid< Specie >::write(), rhoConst< Specie >::write(), rPolynomial< Specie >::write(), FallOffReactionRate< ReactionRate, FallOffFunction >::write(), NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::write(), ReactionList< ThermoType >::write(), specie::write(), eConstThermo< EquationOfState >::write(), hConstThermo< EquationOfState >::write(), hPolynomialThermo< EquationOfState, PolySize >::write(), hTabulatedThermo< EquationOfState >::write(), janafThermo< EquationOfState >::write(), logPolynomialTransport< Thermo, PolySize >::write(), polynomialTransport< Thermo, PolySize >::write(), sutherlandTransport< Thermo >::write(), tabulatedTransport< Thermo >::write(), WLFTransport< Thermo >::write(), profilingInformation::write(), dictionary::write(), mapDistributePolyMesh::writeCellMapEntries(), faBoundaryMesh::writeData(), MRFZone::writeData(), MappedFile< Type >::writeData(), profiling::writeData(), polyBoundaryMesh::writeData(), attachDetach::writeDict(), perfectInterface::writeDict(), setUpdater::writeDict(), slidingInterface::writeDict(), colourTable::writeDict(), cellZone::writeDict(), faceZone::writeDict(), pointZone::writeDict(), plane::writeDict(), ensightCells::writeDict(), ensightFaces::writeDict(), PDRblock::gridControl::writeDict(), GeometricBoundaryField< Type, PatchField, GeoMesh >::writeEntries(), mapDistribute::writeEntries(), mapDistributeBase::writeEntries(), dictionary::writeEntry(), GeometricBoundaryField< Type, PatchField, GeoMesh >::writeEntry(), coordinateSystem::writeEntry(), dictionary::writeEntry(), mapDistributePolyMesh::writeFaceMapEntries(), Foam::writeFuncsImpl(), IOobject::writeHeader(), decomposedBlockData::writeHeader(), decomposedBlockData::writeHeader(), mapDistributePolyMesh::writePatchMapEntries(), and mapDistributePolyMesh::writePointMapEntries().
beginBlock() [2/2]
Foam::Ostream & beginBlock () virtual
Definition at line 89 of file Ostream.C.
References token::BEGIN_BLOCK, Foam::incrIndent(), Foam::indent(), and write().
endBlock()
Foam::Ostream & endBlock () virtual
Definition at line 98 of file Ostream.C.
References Foam::decrIndent(), token::END_BLOCK, Foam::indent(), and write().
Referenced by Foam::endBlock(), Foam::operator<<(), Foam::operator<<(), Foam::printDOT(), fixedNormalInletOutletVelocityFvPatchVectorField::write(), freestreamFvPatchField< Type >::write(), outletMappedUniformInletFvPatchField< Type >::write(), scaledFixedValueFvPatchField< Type >::write(), rigidBodyModel::write(), sixDoFRigidBodyMotion::write(), surfZone::write(), surfacePatch::write(), polynomialSolidTransport< Thermo, PolySize >::write(), tabulatedAnIsoSolidTransport< Thermo >::write(), tabulatedSolidTransport< Thermo >::write(), adiabaticPerfectFluid< Specie >::write(), Boussinesq< Specie >::write(), icoTabulated< Specie >::write(), incompressiblePerfectGas< Specie >::write(), linear< Type >::write(), perfectFluid< Specie >::write(), rhoConst< Specie >::write(), rPolynomial< Specie >::write(), FallOffReactionRate< ReactionRate, FallOffFunction >::write(), NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::write(), ReactionList< ThermoType >::write(), specie::write(), eConstThermo< EquationOfState >::write(), hConstThermo< EquationOfState >::write(), hPolynomialThermo< EquationOfState, PolySize >::write(), hTabulatedThermo< EquationOfState >::write(), janafThermo< EquationOfState >::write(), logPolynomialTransport< Thermo, PolySize >::write(), polynomialTransport< Thermo, PolySize >::write(), sutherlandTransport< Thermo >::write(), tabulatedTransport< Thermo >::write(), WLFTransport< Thermo >::write(), profilingInformation::write(), dictionary::write(), mapDistributePolyMesh::writeCellMapEntries(), faBoundaryMesh::writeData(), MRFZone::writeData(), profiling::writeData(), polyBoundaryMesh::writeData(), attachDetach::writeDict(), perfectInterface::writeDict(), setUpdater::writeDict(), slidingInterface::writeDict(), colourTable::writeDict(), cellZone::writeDict(), faceZone::writeDict(), pointZone::writeDict(), plane::writeDict(), ensightCells::writeDict(), ensightFaces::writeDict(), PDRblock::gridControl::writeDict(), GeometricBoundaryField< Type, PatchField, GeoMesh >::writeEntries(), mapDistribute::writeEntries(), mapDistributeBase::writeEntries(), dictionary::writeEntry(), GeometricBoundaryField< Type, PatchField, GeoMesh >::writeEntry(), coordinateSystem::writeEntry(), dictionary::writeEntry(), mapDistributePolyMesh::writeFaceMapEntries(), Foam::writeFuncsImpl(), IOobject::writeHeader(), decomposedBlockData::writeHeader(), decomposedBlockData::writeHeader(), mapDistributePolyMesh::writePatchMapEntries(), and mapDistributePolyMesh::writePointMapEntries().
endEntry()
Foam::Ostream & endEntry () virtual
Definition at line 107 of file Ostream.C.
References token::END_STATEMENT, and write().
Referenced by Foam::endEntry(), Polynomial< Type >::writeData(), TableBase< Type >::writeData(), and Ostream::writeEntry().
writeEntry()
template<class T > Ostream & writeEntry (const keyType & key, const T & value) inline
Definition at line 234 of file Ostream.H.
References Ostream::endEntry(), and Ostream::writeKeyword().
Referenced by Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), faPatch::write(), SRFFreestreamVelocityFvPatchVectorField::write(), SRFVelocityFvPatchVectorField::write(), acousticWaveTransmissiveFvPatchField< Type >::write(), activeBaffleVelocityFvPatchVectorField::write(), activePressureForceBaffleVelocityFvPatchVectorField::write(), advectiveFvPatchField< Type >::write(), codedFixedValueFvPatchField< Type >::write(), codedMixedFvPatchField< Type >::write(), cylindricalInletVelocityFvPatchVectorField::write(), fixedJumpAMIFvPatchField< Type >::write(), fixedNormalInletOutletVelocityFvPatchVectorField::write(), fixedNormalSlipFvPatchField< Type >::write(), fixedProfileFvPatchField< Type >::write(), flowRateInletVelocityFvPatchVectorField::write(), inletOutletTotalTemperatureFvPatchScalarField::write(), mappedFlowRateFvPatchVectorField::write(), matchedFlowRateOutletVelocityFvPatchVectorField::write(), outletPhaseMeanVelocityFvPatchVectorField::write(), partialSlipFvPatchField< Type >::write(), phaseHydrostaticPressureFvPatchScalarField::write(), plenumPressureFvPatchScalarField::write(), pressureNormalInletOutletVelocityFvPatchVectorField::write(), pressurePIDControlInletVelocityFvPatchVectorField::write(), rotatingPressureInletOutletVelocityFvPatchVectorField::write(), rotatingWallVelocityFvPatchVectorField::write(), supersonicFreestreamFvPatchVectorField::write(), swirlFlowRateInletVelocityFvPatchVectorField::write(), swirlInletVelocityFvPatchVectorField::write(), syringePressureFvPatchScalarField::write(), totalPressureFvPatchScalarField::write(), totalTemperatureFvPatchScalarField::write(), turbulentDFSEMInletFvPatchVectorField::write(), turbulentInletFvPatchField< Type >::write(), turbulentIntensityKineticEnergyInletFvPatchScalarField::write(), uniformDensityHydrostaticPressureFvPatchScalarField::write(), uniformTotalPressureFvPatchScalarField::write(), variableHeightFlowRateFvPatchScalarField::write(), variableHeightFlowRateInletVelocityFvPatchVectorField::write(), waveTransmissiveFvPatchField< Type >::write(), fvPatchField< Type >::write(), surfaceDisplacementPointPatchVectorField::write(), surfaceSlipDisplacementPointPatchVectorField::write(), timeVaryingMappedFixedValuePointPatchField< Type >::write(), waveDisplacementPointPatchVectorField::write(), cyclicACMIPolyPatch::write(), cyclicAMIPolyPatch::write(), mappedVariableThicknessWallPolyPatch::write(), codedFixedValuePointPatchField< Type >::write(), fixedNormalSlipPointPatchField< Type >::write(), genericPolyPatch::write(), cyclicPolyPatch::write(), oldCyclicPolyPatch::write(), processorPolyPatch::write(), processorCyclicPolyPatch::write(), adjointFarFieldPressureFvPatchScalarField::write(), adjointFarFieldVelocityFvPatchVectorField::write(), adjointInletVelocityFvPatchVectorField::write(), adjointOutletPressureFvPatchScalarField::write(), adjointOutletVelocityFvPatchVectorField::write(), adjointOutletVelocityFluxFvPatchVectorField::write(), adjointRotatingWallVelocityFvPatchVectorField::write(), adjointWallVelocityFvPatchVectorField::write(), adjointWallVelocityLowReFvPatchVectorField::write(), kaqRWallFunctionFvPatchScalarField::write(), timeVaryingMassSorptionFvPatchScalarField::write(), copiedFixedValueFvPatchScalarField::write(), fixedMultiPhaseHeatFluxFvPatchScalarField::write(), JohnsonJacksonParticleSlipFvPatchVectorField::write(), JohnsonJacksonParticleThetaFvPatchScalarField::write(), sixDoFRigidBodyMotion::write(), enthalpySorptionFvPatchScalarField::write(), speciesSorptionFvPatchScalarField::write(), externalWallHeatFluxTemperatureFvPatchScalarField::write(), humidityTemperatureCoupledMixedFvPatchScalarField::write(), lumpedMassWallTemperatureFvPatchScalarField::write(), outletMappedUniformInletHeatAdditionFvPatchField::write(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::write(), constantAlphaContactAngleFvPatchScalarField::write(), dynamicAlphaContactAngleFvPatchScalarField::write(), timeVaryingAlphaContactAngleFvPatchScalarField::write(), fixedShearStressFvPatchVectorField::write(), porousBafflePressureFvPatchField::write(), waveAlphaFvPatchScalarField::write(), waveVelocityFvPatchVectorField::write(), waveMakerPointPatchVectorField::write(), interpolationLookUpTable< Type >::write(), boundaryPatch::write(), processorFaPatch::write(), faePatchField< Type >::write(), faPatchField< Type >::write(), fanFvPatchField< Type >::write(), fanPressureFvPatchScalarField::write(), mappedPatchFieldBase< Type >::write(), swirlFanVelocityFvPatchField::write(), fvsPatchField< Type >::write(), externalCoupledTemperatureMixedFvPatchScalarField::write(), CloudSubModelBase< CloudType >::write(), DispersionRASModel< CloudType >::write(), lumpedPointDisplacementPointPatchVectorField::write(), AMIInterpolation::write(), faceAreaWeightAMI::write(), mappedPatchBase::write(), pointPatchField< Type >::write(), profilingSysInfo::write(), interpolation2DTable< Type >::write(), csvTableReader< Type >::write(), coupleGroupIdentifier::write(), patchIdentifier::write(), geometricSurfacePatch::write(), surfZoneIdentifier::write(), zoneIdentifier::write(), coupledPolyPatch::write(), polyPatch::write(), cpuInfo::write(), memInfo::write(), oversetFvPatchField< Type >::write(), sixDoFRigidBodyMotionState::write(), surfZone::write(), surfacePatch::write(), solidArrheniusReactionRate::write(), solidIsothermalReactionRate::write(), solidReaction< ReactionThermo >::write(), polynomialSolidTransport< Thermo, PolySize >::write(), tabulatedSolidTransport< Thermo >::write(), adiabaticPerfectFluid< Specie >::write(), Boussinesq< Specie >::write(), icoTabulated< Specie >::write(), incompressiblePerfectGas< Specie >::write(), linear< Type >::write(), perfectFluid< Specie >::write(), rhoConst< Specie >::write(), rPolynomial< Specie >::write(), ArrheniusReactionRate::write(), SRIFallOffFunction::write(), TroeFallOffFunction::write(), LandauTellerReactionRate::write(), powerSeriesReactionRate::write(), thirdBodyEfficiencies::write(), Reaction< ReactionThermo >::write(), ReactionList< ThermoType >::write(), specie::write(), eConstThermo< EquationOfState >::write(), hConstThermo< EquationOfState >::write(), hPolynomialThermo< EquationOfState, PolySize >::write(), hTabulatedThermo< EquationOfState >::write(), janafThermo< EquationOfState >::write(), logPolynomialTransport< Thermo, PolySize >::write(), polynomialTransport< Thermo, PolySize >::write(), sutherlandTransport< Thermo >::write(), tabulatedTransport< Thermo >::write(), WLFTransport< Thermo >::write(), outletMachNumberPressureFvPatchScalarField::write(), temperatureCoupledBase::write(), alphaContactAngleTwoPhaseFvPatchScalarField::write(), profilingInformation::write(), mapDistributePolyMesh::writeCellMapEntries(), MRFZone::writeData(), profiling::writeData(), adjointSimple::writeData(), RASTurbulenceModel::writeData(), simple::writeData(), DimensionedField< Type, GeoMesh >::writeData(), attachDetach::writeDict(), perfectInterface::writeDict(), setUpdater::writeDict(), slidingInterface::writeDict(), colourTable::writeDict(), lumpedPointState::writeDict(), cellZone::writeDict(), faceZone::writeDict(), pointZone::writeDict(), plane::writeDict(), ensightCells::writeDict(), ensightFaces::writeDict(), wallFunctionBlenders::writeEntries(), mapDistribute::writeEntries(), mapDistributeBase::writeEntries(), coordinateSystem::writeEntry(), orientedType::writeEntry(), Ostream::writeEntryIfDifferent(), Foam::writeEntryIfPresent(), mapDistributePolyMesh::writeFaceMapEntries(), genericPatchFieldBase::writeGeneric(), nutUTabulatedWallFunctionFvPatchScalarField::writeLocalEntries(), Foam::writeMaps(), and mapDistributePolyMesh::writePointMapEntries().
writeEntryIfDifferent()
template<class T > Ostream & writeEntryIfDifferent (const word & key, const T & value1, const T & value2) inline
Definition at line 245 of file Ostream.H.
References Ostream::writeEntry().
Referenced by inletOutletFaPatchField< Type >::write(), outletInletFaPatchField< Type >::write(), activeBaffleVelocityFvPatchVectorField::write(), activePressureForceBaffleVelocityFvPatchVectorField::write(), advectiveFvPatchField< Type >::write(), electrostaticDepositionFvPatchScalarField::write(), fixedNormalInletOutletVelocityFvPatchVectorField::write(), fixedPressureCompressibleDensityFvPatchScalarField::write(), flowRateInletVelocityFvPatchVectorField::write(), flowRateOutletVelocityFvPatchVectorField::write(), fluxCorrectedVelocityFvPatchVectorField::write(), freestreamFvPatchField< Type >::write(), freestreamPressureFvPatchScalarField::write(), inletOutletFvPatchField< Type >::write(), inletOutletTotalTemperatureFvPatchScalarField::write(), interstitialInletVelocityFvPatchVectorField::write(), mappedMixedFieldFvPatchField< Type >::write(), mappedFlowRateFvPatchVectorField::write(), mappedMixedFvPatchField< Type >::write(), mappedVelocityFluxFixedValueFvPatchField::write(), matchedFlowRateOutletVelocityFvPatchVectorField::write(), outletInletFvPatchField< Type >::write(), outletMappedUniformInletFvPatchField< Type >::write(), phaseHydrostaticPressureFvPatchScalarField::write(), plenumPressureFvPatchScalarField::write(), pressureDirectedInletOutletVelocityFvPatchVectorField::write(), pressureDirectedInletVelocityFvPatchVectorField::write(), pressureInletOutletParSlipVelocityFvPatchVectorField::write(), pressureInletOutletVelocityFvPatchVectorField::write(), pressureInletVelocityFvPatchVectorField::write(), pressurePermeableAlphaInletOutletVelocityFvPatchVectorField::write(), pressurePIDControlInletVelocityFvPatchVectorField::write(), prghPermeableAlphaTotalPressureFvPatchScalarField::write(), prghPressureFvPatchScalarField::write(), prghTotalHydrostaticPressureFvPatchScalarField::write(), prghTotalPressureFvPatchScalarField::write(), supersonicFreestreamFvPatchVectorField::write(), swirlFlowRateInletVelocityFvPatchVectorField::write(), syringePressureFvPatchScalarField::write(), totalPressureFvPatchScalarField::write(), totalTemperatureFvPatchScalarField::write(), turbulentDFSEMInletFvPatchVectorField::write(), turbulentIntensityKineticEnergyInletFvPatchScalarField::write(), uniformInletOutletFvPatchField< Type >::write(), uniformTotalPressureFvPatchScalarField::write(), variableHeightFlowRateFvPatchScalarField::write(), waveSurfacePressureFvPatchScalarField::write(), waveTransmissiveFvPatchField< Type >::write(), surfaceDisplacementPointPatchVectorField::write(), surfaceSlipDisplacementPointPatchVectorField::write(), timeVaryingMappedFixedValuePointPatchField< Type >::write(), cyclicAMIPolyPatch::write(), cyclicPeriodicAMIPolyPatch::write(), processorCyclicPolyPatch::write(), timeVaryingMassSorptionFvPatchScalarField::write(), filmPyrolysisTemperatureCoupledFvPatchScalarField::write(), filmPyrolysisVelocityCoupledFvPatchVectorField::write(), filmHeightInletVelocityFvPatchVectorField::write(), inclinedFilmNusseltHeightFvPatchScalarField::write(), inclinedFilmNusseltInletVelocityFvPatchVectorField::write(), enthalpySorptionFvPatchScalarField::write(), speciesSorptionFvPatchScalarField::write(), humidityTemperatureCoupledMixedFvPatchScalarField::write(), outletMappedUniformInletHeatAdditionFvPatchField::write(), semiPermeableBaffleMassFractionFvPatchScalarField::write(), semiPermeableBaffleVelocityFvPatchVectorField::write(), temperatureDependentAlphaContactAngleFvPatchScalarField::write(), porousBafflePressureFvPatchField::write(), fanFvPatchField< Type >::write(), mappedPatchFieldBase< Type >::write(), swirlFanVelocityFvPatchField::write(), advancingFrontAMI::write(), faceAreaWeightAMI2D::write(), nearestFaceAMI::write(), mappedPatchBase::write(), tableReader< Type >::write(), cpuInfo::write(), oversetFvPatchField< Type >::write(), specie::write(), eConstThermo< EquationOfState >::write(), hConstThermo< EquationOfState >::write(), outletMachNumberPressureFvPatchScalarField::write(), profilingInformation::write(), wallFunctionCoefficients::writeEntries(), atmEpsilonWallFunctionFvPatchScalarField::writeLocalEntries(), atmNutkWallFunctionFvPatchScalarField::writeLocalEntries(), atmNutUWallFunctionFvPatchScalarField::writeLocalEntries(), atmNutWallFunctionFvPatchScalarField::writeLocalEntries(), epsilonWallFunctionFvPatchScalarField::writeLocalEntries(), nutUBlendedWallFunctionFvPatchScalarField::writeLocalEntries(), nutUSpaldingWallFunctionFvPatchScalarField::writeLocalEntries(), nutWallFunctionFvPatchScalarField::writeLocalEntries(), and omegaWallFunctionFvPatchScalarField::writeLocalEntries().
flush()
virtual void flush () pure virtual
Implemented in UOPstreamBase, OSstream, and OTstream.
endl()
virtual void endl () pure virtual
Implemented in UOPstreamBase, OSstream, and OTstream.
fill() [1/2]
virtual char fill () const pure virtual
Implemented in UOPstreamBase, OSstream, and OTstream.
Referenced by Foam::setfill().
fill() [2/2]
virtual char fill (const char fillch) pure virtual
Implemented in OSstream, UOPstreamBase, and OTstream.
width() [1/2]
virtual int width () const pure virtual
Implemented in UOPstreamBase, OSstream, and OTstream.
Referenced by Foam::setw().
width() [2/2]
virtual int width (const int w) pure virtual
Implemented in OSstream, UOPstreamBase, and OTstream.
precision() [1/2]
virtual int precision () const pure virtual
Implemented in UOPstreamBase, OSstream, and OTstream.
Referenced by Foam::setprecision().
precision() [2/2]
virtual int precision (const int p) pure virtual
Implemented in OSstream, UOPstreamBase, and OTstream.
operator()()
Ostream & operator() () const inline
Definition at line 293 of file Ostream.H.
indentLevel() [3/3]
unsigned short & indentLevel () inline noexcept
Definition at line 302 of file Ostream.H.
References Ostream::indentLevel_.
indentSize() [3/3]
unsigned short & indentSize () inline noexcept
Definition at line 308 of file Ostream.H.
References Ostream::indentSize_.
Member Data Documentation
entryIndentation_
constexpr const unsigned short entryIndentation_ = 16 static constexpr protected
Definition at line 64 of file Ostream.H.
indentSize_
unsigned short indentSize_ = 4 protected
Definition at line 67 of file Ostream.H.
Referenced by Ostream::indentSize(), Ostream::indentSize(), and Ostream::indentSize().
indentLevel_
unsigned short indentLevel_ = 0 protected
Definition at line 70 of file Ostream.H.
Referenced by Ostream::decrIndent(), Ostream::incrIndent(), Ostream::indentLevel(), Ostream::indentLevel(), and Ostream::indentLevel().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/IOstreams/Ostream.H
src/OpenFOAM/db/IOstreams/IOstreams/Ostream.C