OpenFOAM: graph::writer Class Reference
graph::writer Class Reference abstract
#include <graph.H>
Public Member Functions
TypeName ("writer")
declareRunTimeSelectionTable (autoPtr, writer, word,(),())
writer ()=default
virtual ~writer ()=default
virtual word ext () const =0
virtual void write (const graph &, Ostream &) const =0
Static Public Member Functions
static autoPtr< writer > New (const word &writeFormat)
Protected Member Functions
void writeXY (const scalarField &x, const scalarField &y, Ostream &) const
Detailed Description
Definition at line 179 of file graph.H.
Constructor & Destructor Documentation
writer()
writer () default
~writer()
virtual ~writer () virtual default
Member Function Documentation
writeXY()
void writeXY (const scalarField & x, const scalarField & y, Ostream & os) const protected
Definition at line 230 of file graph.C.
References Foam::endl(), forAll, os(), Foam::setw(), token::SPACE, x, and y.
Referenced by gnuplotWriter::write(), and xmgraceWriter::write().
TypeName()
TypeName ("writer")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , writer , word , () , ())
New()
Foam::autoPtr< Foam::graph::writer > New (const word & writeFormat) static
Definition at line 202 of file graph.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and FatalErrorInLookup.
ext()
virtual word ext () const pure virtual
Implemented in gnuplotWriter, rawWriter, and xmgraceWriter.
write()
virtual void write (const graph & , Ostream &) const pure virtual
Implemented in gnuplotWriter, rawWriter, and xmgraceWriter.
The documentation for this class was generated from the following files:
src/meshTools/graph/graph.H
src/meshTools/graph/graph.C