OpenFOAM: linearDamper Class Reference
linearDamper Class Reference
Mesh motion » Rigid body dynamics » Restraints
Linear damper restraint. Operates in the local frame of the body.
#include <linearDamper.H>
Public Member Functions
TypeName ("linearDamper")
linearDamper (const word &name, const dictionary &dict, const rigidBodyModel &model)
virtual autoPtr< restraint > clone () const
virtual ~linearDamper ()
virtual void restrain (scalarField &tau, Field< spatialVector > &fx, const rigidBodyModelState &state) const
virtual bool read (const dictionary &dict)
virtual void write (Ostream &) const
Public Member Functions inherited from restraint
TypeName ("restraint")
declareRunTimeSelectionTable (autoPtr, restraint, dictionary,(const word &name, const dictionary &dict, const rigidBodyModel &model),(name, dict, model))
restraint (const word &name, const dictionary &dict, const rigidBodyModel &model)
virtual ~restraint ()
const word & name () const
label bodyID () const
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from restraint
static autoPtr< restraint > New (const word &name, const dictionary &dict, const rigidBodyModel &model)
Protected Member Functions inherited from restraint
point bodyPoint (const point &p) const
spatialVector bodyPointVelocity (const point &p) const
Protected Attributes inherited from restraint
word name_
label bodyID_
label bodyIndex_
dictionary coeffs_
const rigidBodyModel & model_
Detailed Description
Linear damper restraint. Operates in the local frame of the body.
Source files
linearDamper.H
linearDamper.C
Definition at line 53 of file linearDamper.H.
Constructor & Destructor Documentation
linearDamper()
linearDamper (const word & name, const dictionary & dict, const rigidBodyModel & model)
Definition at line 48 of file linearDamper.C.
References dict, Foam::name(), and linearDamper::read().
~linearDamper()
~linearDamper () virtual
Definition at line 63 of file linearDamper.C.
Member Function Documentation
TypeName()
TypeName ("linearDamper")
clone()
virtual autoPtr< restraint > clone () const inline virtual
Implements restraint.
Definition at line 80 of file linearDamper.H.
restrain()
void restrain (scalarField & tau, Field< spatialVector > & fx, const rigidBodyModelState & state) const virtual
Implements restraint.
Definition at line 69 of file linearDamper.C.
References Foam::endl(), Foam::Info, and Foam::Zero.
read()
bool read (const dictionary & dict) virtual
Reimplemented from restraint.
Definition at line 88 of file linearDamper.C.
References dict, and restraint::read().
Referenced by linearDamper::linearDamper().
write()
void write (Ostream & os) const virtual
Implements restraint.
Definition at line 101 of file linearDamper.C.
References os(), and restraint::write().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/restraints/linearDamper/linearDamper.H
src/rigidBodyDynamics/restraints/linearDamper/linearDamper.C