OpenFOAM: VirtualMassForce< CloudType > Class Template Reference
VirtualMassForce< CloudType > Class Template Reference
Lagrangian particle models » Submodels » Kinematic » Forces
Calculates particle virtual mass force.
#include <VirtualMassForce.H>
Public Member Functions
TypeName ("virtualMass")
VirtualMassForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType=typeName)
VirtualMassForce (const VirtualMassForce &pgf)
virtual autoPtr< ParticleForce< CloudType > > clone () const
virtual ~VirtualMassForce ()
virtual void cacheFields (const bool store)
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
virtual scalar massAdd (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar mass) const
Public Member Functions inherited from PressureGradientForce< CloudType >
TypeName ("pressureGradient")
PressureGradientForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType=typeName)
PressureGradientForce (const PressureGradientForce &pgf)
virtual ~PressureGradientForce ()
const interpolation< vector > & DUcDtInterp () const
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
ParticleForce (const ParticleForce &pf)
virtual ~ParticleForce ()
const CloudType & owner () const
CloudType & owner ()
const fvMesh & mesh () const
const dictionary & coeffs () const
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Protected Attributes inherited from PressureGradientForce< CloudType >
const word UName_
autoPtr< interpolation< vector > > DUcDtInterpPtr_
Detailed Description
template<class CloudType>
class Foam::VirtualMassForce< CloudType >
Calculates particle virtual mass force.
Source files
VirtualMassForce.H
VirtualMassForce.C
Definition at line 50 of file VirtualMassForce.H.
Constructor & Destructor Documentation
VirtualMassForce() [1/2]
template<class CloudType > VirtualMassForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict, const word & forceType = typeName)
Definition at line 26 of file VirtualMassForce.C.
VirtualMassForce() [2/2]
template<class CloudType > VirtualMassForce (const VirtualMassForce< CloudType > & pgf)
Definition at line 40 of file VirtualMassForce.C.
~VirtualMassForce()
template<class CloudType > ~VirtualMassForce () virtual
Definition at line 53 of file VirtualMassForce.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("virtualMass")
clone()
template<class CloudType > virtual autoPtr< ParticleForce< CloudType > > clone () const inline virtual
Reimplemented from PressureGradientForce< CloudType >.
Definition at line 81 of file VirtualMassForce.H.
cacheFields()
template<class CloudType > void cacheFields (const bool store) virtual
Reimplemented from PressureGradientForce< CloudType >.
Definition at line 60 of file VirtualMassForce.C.
References PressureGradientForce< CloudType >::cacheFields().
calcCoupled()
template<class CloudType > Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const typename CloudType::parcelType::trackingData & td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Reimplemented from PressureGradientForce< CloudType >.
Definition at line 67 of file VirtualMassForce.C.
References PressureGradientForce< CloudType >::calcCoupled(), p, Foam::Re(), and forceSuSp::Su().
massAdd()
template<class CloudType > Foam::scalar massAdd (const typename CloudType::parcelType & p, const typename CloudType::parcelType::trackingData & td, const scalar mass) const virtual
Reimplemented from PressureGradientForce< CloudType >.
Definition at line 87 of file VirtualMassForce.C.
References p.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/VirtualMass/VirtualMassForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/VirtualMass/VirtualMassForce.C