OpenFOAM: procFacesGAMGProcAgglomeration Class Reference
procFacesGAMGProcAgglomeration Class Reference
Processor agglomeration of GAMGAgglomerations. Needs nAgglomeratingCells which is when to start agglomerating processors. Processors get agglomerated by constructing a single cell mesh for each processor with each processor interface a face. This then gets agglomerated using the pairGAMGAgglomeration algorithm with the number of faces on the original processor interface as face weight.
#include <procFacesGAMGProcAgglomeration.H>
Public Member Functions
TypeName ("procFaces")
procFacesGAMGProcAgglomeration (const procFacesGAMGProcAgglomeration &)=delete
void operator= (const procFacesGAMGProcAgglomeration &)=delete
procFacesGAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
virtual ~procFacesGAMGProcAgglomeration ()
virtual bool agglomerate ()
Public Member Functions inherited from GAMGProcAgglomeration
TypeName ("GAMGProcAgglomeration")
declareRunTimeSelectionTable (autoPtr, GAMGProcAgglomeration, GAMGAgglomeration,(GAMGAgglomeration &agglom, const dictionary &controlDict),(agglom, controlDict))
GAMGProcAgglomeration (const GAMGProcAgglomeration &)=delete
void operator= (const GAMGProcAgglomeration &)=delete
GAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
virtual ~GAMGProcAgglomeration ()
Additional Inherited Members
Static Public Member Functions inherited from GAMGProcAgglomeration
static autoPtr< GAMGProcAgglomeration > New (const word &type, GAMGAgglomeration &agglom, const dictionary &controlDict)
Protected Member Functions inherited from GAMGProcAgglomeration
void printStats (Ostream &os, GAMGAgglomeration &agglom) const
bool agglomerate (const label fineLevelIndex, const labelList &procAgglomMap, const labelList &masterProcs, const List< label > &agglomProcIDs, const label procAgglomComm)
void clearCommunicators ()
Static Protected Member Functions inherited from GAMGProcAgglomeration
static labelListList globalCellCells (const lduMesh &)
Protected Attributes inherited from GAMGProcAgglomeration
GAMGAgglomeration & agglom_
DynamicList< label > comms_
Detailed Description
Processor agglomeration of GAMGAgglomerations. Needs nAgglomeratingCells which is when to start agglomerating processors. Processors get agglomerated by constructing a single cell mesh for each processor with each processor interface a face. This then gets agglomerated using the pairGAMGAgglomeration algorithm with the number of faces on the original processor interface as face weight.
Source files
procFacesGAMGProcAgglomeration.H
procFacesGAMGProcAgglomeration.C
Definition at line 53 of file procFacesGAMGProcAgglomeration.H.
Constructor & Destructor Documentation
procFacesGAMGProcAgglomeration() [1/2]
procFacesGAMGProcAgglomeration (const procFacesGAMGProcAgglomeration &) delete
procFacesGAMGProcAgglomeration() [2/2]
procFacesGAMGProcAgglomeration (GAMGAgglomeration & agglom, const dictionary & controlDict)
Definition at line 212 of file procFacesGAMGProcAgglomeration.C.
~procFacesGAMGProcAgglomeration()
~procFacesGAMGProcAgglomeration () virtual
Definition at line 225 of file procFacesGAMGProcAgglomeration.C.
Member Function Documentation
TypeName()
TypeName ("procFaces")
operator=()
void operator= (const procFacesGAMGProcAgglomeration &) delete
agglomerate()
bool agglomerate () virtual
Implements GAMGProcAgglomeration.
Definition at line 231 of file procFacesGAMGProcAgglomeration.C.
References GAMGProcAgglomeration::agglomerate(), UPstream::allocateCommunicator(), UPtrList< T >::back(), GAMGAgglomeration::calculateRegionMaster(), Foam::endl(), Foam::nl, UPstream::nProcs(), Foam::Pout, rndGen, and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/procFacesGAMGProcAgglomeration/procFacesGAMGProcAgglomeration.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/procFacesGAMGProcAgglomeration/procFacesGAMGProcAgglomeration.C