OpenFOAM: BrownianMotionForce< CloudType > Class Template Reference
BrownianMotionForce< CloudType > Class Template Reference
Calculates particle Brownian motion force.
#include <BrownianMotionForce.H>
Public Member Functions
TypeName ("BrownianMotion")
BrownianMotionForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict)
BrownianMotionForce (const BrownianMotionForce &bmf)
virtual autoPtr< ParticleForce< CloudType > > clone () const
virtual ~BrownianMotionForce ()
scalar lambda () const
bool turbulence () const
virtual void cacheFields (const bool store)
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
ParticleForce (const ParticleForce &pf)
virtual ~ParticleForce ()
const CloudType & owner () const
CloudType & owner ()
const fvMesh & mesh () const
const dictionary & coeffs () const
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
virtual scalar massAdd (const typename CloudType::parcelType &p, const typename CloudType::parcelType::trackingData &td, const scalar mass) const
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Detailed Description
template<class CloudType>
class Foam::BrownianMotionForce< CloudType >
Calculates particle Brownian motion force.
Reference:
    Li, A., & Ahmadi, G. (1992).
    Dispersion and deposition of spherical particles from point sources
    in a turbulent channel flow.
    Aerosol science and technology,
    16(4), 209-226.
Source files
BrownianMotionForce.H
BrownianMotionForceI.H
BrownianMotionForce.C
Definition at line 59 of file BrownianMotionForce.H.
Constructor & Destructor Documentation
BrownianMotionForce() [1/2]
template<class CloudType > BrownianMotionForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict)
Definition at line 63 of file BrownianMotionForce.C.
BrownianMotionForce() [2/2]
template<class CloudType > BrownianMotionForce (const BrownianMotionForce< CloudType > & bmf)
Definition at line 80 of file BrownianMotionForce.C.
~BrownianMotionForce()
template<class CloudType > ~BrownianMotionForce () virtual
Definition at line 97 of file BrownianMotionForce.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("BrownianMotion")
clone()
template<class CloudType > virtual autoPtr< ParticleForce< CloudType > > clone () const inline virtual
Reimplemented from ParticleForce< CloudType >.
Definition at line 107 of file BrownianMotionForce.H.
lambda()
template<class CloudType > Foam::scalar lambda () const inline
Definition at line 24 of file BrownianMotionForceI.H.
turbulence()
template<class CloudType > bool turbulence () const inline
Definition at line 31 of file BrownianMotionForceI.H.
cacheFields()
template<class CloudType > void cacheFields (const bool store) virtual
Reimplemented from ParticleForce< CloudType >.
Definition at line 106 of file BrownianMotionForce.C.
References Foam::deleteDemandDrivenData().
calcCoupled()
template<class CloudType > Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const typename CloudType::parcelType::trackingData & td, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Reimplemented from ParticleForce< CloudType >.
Definition at line 138 of file BrownianMotionForce.C.
References alpha, Foam::cos(), Foam::exp(), f(), k, Foam::constant::physicoChemical::k, kb, Foam::mag(), p, Foam::constant::mathematical::pi(), Foam::pow5(), Foam::sin(), Foam::sqr(), Foam::sqrt(), forceSuSp::Su(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/lagrangian/turbulence/submodels/Thermodynamic/ParticleForces/BrownianMotion/BrownianMotionForce.H
src/lagrangian/turbulence/submodels/Thermodynamic/ParticleForces/BrownianMotion/BrownianMotionForce.C
src/lagrangian/turbulence/submodels/Thermodynamic/ParticleForces/BrownianMotion/BrownianMotionForceI.H