OpenFOAM: ensightCase::options Class Reference
ensightCase::options Class Reference
#include <ensightCase.H>
Public Member Functions
options (IOstreamOption::streamFormat fmt=IOstreamOption::BINARY)
IOstreamOption::streamFormat format () const noexcept
const word & mask () const noexcept
word padded (const label i) const
label width () const noexcept
bool overwrite () const noexcept
bool separateCloud () const noexcept
void width (const label i)
void overwrite (bool on) noexcept
void separateCloud (bool on) noexcept
bool nodeValues () const noexcept
void nodeValues (bool on) noexcept
Detailed Description
Definition at line 384 of file ensightCase.H.
Constructor & Destructor Documentation
options()
options (IOstreamOption::streamFormat fmt = IOstreamOption::BINARY)
Definition at line 25 of file ensightCaseOptions.C.
References ensightCase::options::width().
Member Function Documentation
format()
IOstreamOption::streamFormat format () const inline noexcept
Definition at line 423 of file ensightCase.H.
mask()
const word & mask () const inline noexcept
Definition at line 426 of file ensightCase.H.
padded()
Foam::word padded (const label i) const
Definition at line 41 of file ensightCaseOptions.C.
width() [1/2]
label width () const inline noexcept
Definition at line 432 of file ensightCase.H.
Referenced by ensightCase::options::options().
overwrite() [1/2]
bool overwrite () const inline noexcept
Definition at line 435 of file ensightCase.H.
separateCloud() [1/2]
bool separateCloud () const inline noexcept
Definition at line 438 of file ensightCase.H.
width() [2/2]
void width (const label i)
Definition at line 54 of file ensightCaseOptions.C.
References n, and PtrList< T >::resize().
overwrite() [2/2]
void overwrite (bool on) inline noexcept
Definition at line 448 of file ensightCase.H.
separateCloud() [2/2]
void separateCloud (bool on) inline noexcept
Definition at line 451 of file ensightCase.H.
nodeValues() [1/2]
bool nodeValues () const inline noexcept
Definition at line 457 of file ensightCase.H.
Referenced by ensightWrite::writeVolFieldsImpl().
nodeValues() [2/2]
void nodeValues (bool on) inline noexcept
Definition at line 463 of file ensightCase.H.
The documentation for this class was generated from the following files:
src/fileFormats/ensight/file/ensightCase.H
src/fileFormats/ensight/file/ensightCaseOptions.C