OpenFOAM: waveVelocityFvPatchVectorField Class Reference
waveVelocityFvPatchVectorField Class Reference
Example of the boundary condition specification:
#include <waveVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("waveVelocity")
waveVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
waveVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
waveVelocityFvPatchVectorField (const waveVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
waveVelocityFvPatchVectorField (const waveVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
waveVelocityFvPatchVectorField (const waveVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Example of the boundary condition specification:
inlet
{
    type            waveVelocity;
    value           uniform (0 0 0);
}
Usage
Property Description Required Default value
type type: waveVelocity yes
waveDict Dictionary specifying wave variables no waveProperties
Note
The value is positive inwards
May not work correctly for transonic inlets
Strange behaviour with potentialFoam since the U equation is not solved
Source files
waveVelocityFvPatchVectorField.H
waveVelocityFvPatchVectorField.C
Definition at line 80 of file waveVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
waveVelocityFvPatchVectorField() [1/5]
waveVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 29 of file waveVelocityFvPatchVectorField.C.
waveVelocityFvPatchVectorField() [2/5]
waveVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 53 of file waveVelocityFvPatchVectorField.C.
waveVelocityFvPatchVectorField() [3/5]
waveVelocityFvPatchVectorField (const waveVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 40 of file waveVelocityFvPatchVectorField.C.
waveVelocityFvPatchVectorField() [4/5]
waveVelocityFvPatchVectorField (const waveVelocityFvPatchVectorField & ptf)
Definition at line 65 of file waveVelocityFvPatchVectorField.C.
waveVelocityFvPatchVectorField() [5/5]
waveVelocityFvPatchVectorField (const waveVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 75 of file waveVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("waveVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 131 of file waveVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 147 of file waveVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 88 of file waveVelocityFvPatchVectorField.C.
References waveModel::correct(), waveModel::lookupOrCreate(), mesh, Foam::operator==(), waveModel::U(), and fvPatchField< Type >::updateCoeffs().
write()
void write (Ostream & os) const virtual
Definition at line 115 of file waveVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/waveModels/derivedFvPatchFields/waveVelocity/waveVelocityFvPatchVectorField.H
src/waveModels/derivedFvPatchFields/waveVelocity/waveVelocityFvPatchVectorField.C