OpenFOAM: nearWallFields Class Reference
nearWallFields Class Reference
FunctionObjects » Field function objects
Samples near-patch volume fields within an input distance range.
#include <nearWallFields.H>
Public Member Functions
TypeName ("nearWallFields")
nearWallFields (const word &name, const Time &runTime, const dictionary &dict)
nearWallFields (const nearWallFields &)=delete
void operator= (const nearWallFields &)=delete
virtual ~nearWallFields ()=default
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
virtual void movePoints (const polyMesh &mesh)
Protected Member Functions
void calcAddressing ()
template<class Type >
void createFields (PtrList< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class Type >
void sampleBoundaryField (const interpolationCellPoint< Type > &interpolator, GeometricField< Type, fvPatchField, volMesh > &fld) const
template<class Type >
void sampleFields (PtrList< GeometricField< Type, fvPatchField, volMesh > > &) const
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Attributes
List< Tuple2< word, word > > fieldSet_
labelHashSet patchSet_
scalar distance_
HashTable< word > fieldMap_
HashTable< word > reverseFieldMap_
labelListList cellToWalls_
List< List< point > > cellToSamples_
autoPtr< mapDistribute > getPatchDataMapPtr_
PtrList< volScalarField > vsf_
PtrList< volVectorField > vvf_
PtrList< volSphericalTensorField > vSpheretf_
PtrList< volSymmTensorField > vSymmtf_
PtrList< volTensorField > vtf_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Detailed Description
Samples near-patch volume fields within an input distance range.
Operands:
Operand Type Location
input vol<Type>Field $FOAM_CASE/<time>/<inpField>
output file - -
output field vol<Type>Field $FOAM_CASE/<time>/<outField>
where <Type>=Scalar/Vector/SphericalTensor/SymmTensor/Tensor.
Usage
Minimal example by using system/controlDict.functions:
nearWallFields1
{
    // Mandatory entries (unmodifiable)
    type            nearWallFields;
    libs            (fieldFunctionObjects);
    fields
    (
        (<field1> <outField1>)
        (<field2> <outField2>)
    );
    patches         (<patch1> <patch2> ... <patchN>);
    distance        0.01;
    // Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Req'd Dflt
type Type name: nearWallFields word yes -
libs Library name: fieldFunctionObjects word yes -
fields Names of input-output fields wordHashTable yes -
patches Names of patches to sample wordList yes -
distance Wall-normal distance from patch to sample scalar yes -
The inherited entries are elaborated in:
functionObject.H
Usage by the postProcess utility is not available.
See also
Foam::functionObject
Foam::functionObjects::fvMeshFunctionObject
ExtendedCodeGuide::functionObjects::field::nearWallFields
Source files
nearWallFields.H
nearWallFields.C
nearWallFieldsTemplates.C
Definition at line 159 of file nearWallFields.H.
Constructor & Destructor Documentation
nearWallFields() [1/2]
nearWallFields (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 238 of file nearWallFields.C.
References dict, and nearWallFields::read().
nearWallFields() [2/2]
nearWallFields (const nearWallFields &) delete
~nearWallFields()
virtual ~nearWallFields () virtual default
Member Function Documentation
calcAddressing()
void calcAddressing () protected
Definition at line 43 of file nearWallFields.C.
References nearWallFields::cellToSamples_, nearWallFields::cellToWalls_, tetrahedron< Point, PointRef >::centre(), functionObject::debug, DebugInFunction, cloud::defaultName, nearWallFields::distance_, e, functionObject::end(), UPtrList< T >::end(), Foam::endl(), f(), polyMesh::FACE_DIAG_TRIS, mappedPatchBase::facePoint(), forAll, nearWallFields::getPatchDataMapPtr_, InfoInFunction, fvMeshFunctionObject::mesh_, OFstream::name(), nearWallFields::patchSet_, List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), tetIndices::tet(), and OBJstream::writeLine().
createFields()
template<class Type > void createFields (PtrList< GeometricField< Type, fvPatchField, volMesh > > & sflds) const protected
Definition at line 27 of file nearWallFieldsTemplates.C.
References fvPatchFieldBase::calculatedType(), Foam::endl(), nearWallFields::fieldMap_, fld(), forAllConstIters, io(), Log, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, regionFunctionObject::obr_, nearWallFields::patchSet_, PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), HashTable< T, Key, Hash >::toc(), and WarningInFunction.
sampleBoundaryField()
template<class Type > void sampleBoundaryField (const interpolationCellPoint< Type > & interpolator, GeometricField< Type, fvPatchField, volMesh > & fld) const protected
Definition at line 84 of file nearWallFieldsTemplates.C.
References fld(), forAll, and UPtrList< T >::size().
sampleFields()
template<class Type > void sampleFields (PtrList< GeometricField< Type, fvPatchField, volMesh > > & sflds) const protected
Definition at line 132 of file nearWallFieldsTemplates.C.
References fld(), and forAll.
TypeName()
TypeName ("nearWallFields")
operator=()
void operator= (const nearWallFields &) delete
read()
bool read (const dictionary & dict) virtual
Reimplemented from regionFunctionObject.
Definition at line 254 of file nearWallFields.C.
References dict, Foam::endl(), UPtrList< T >::first(), forAll, Foam::Info, Foam::name(), functionObject::read(), and Foam::type().
Referenced by nearWallFields::nearWallFields().
execute()
bool execute () virtual
Implements functionObject.
Definition at line 302 of file nearWallFields.C.
References DebugInFunction, Foam::endl(), Log, Foam::name(), Foam::nl, and Foam::type().
write()
bool write () virtual
Implements functionObject.
Definition at line 343 of file nearWallFields.C.
References DebugInFunction, Foam::endl(), forAll, Log, and Ostream::write().
Member Data Documentation
fieldSet_
List<Tuple2<word, word> > fieldSet_ protected
Definition at line 170 of file nearWallFields.H.
patchSet_
labelHashSet patchSet_ protected
Definition at line 173 of file nearWallFields.H.
Referenced by nearWallFields::calcAddressing(), and nearWallFields::createFields().
distance_
scalar distance_ protected
Definition at line 176 of file nearWallFields.H.
Referenced by nearWallFields::calcAddressing().
fieldMap_
HashTable<word> fieldMap_ protected
Definition at line 179 of file nearWallFields.H.
Referenced by nearWallFields::createFields().
reverseFieldMap_
HashTable<word> reverseFieldMap_ protected
Definition at line 182 of file nearWallFields.H.
cellToWalls_
labelListList cellToWalls_ protected
Definition at line 188 of file nearWallFields.H.
Referenced by nearWallFields::calcAddressing().
cellToSamples_
List<List<point> > cellToSamples_ protected
Definition at line 191 of file nearWallFields.H.
Referenced by nearWallFields::calcAddressing().
getPatchDataMapPtr_
autoPtr<mapDistribute> getPatchDataMapPtr_ protected
Definition at line 194 of file nearWallFields.H.
Referenced by nearWallFields::calcAddressing().
vsf_
PtrList<volScalarField> vsf_ protected
Definition at line 199 of file nearWallFields.H.
vvf_
PtrList<volVectorField> vvf_ protected
Definition at line 200 of file nearWallFields.H.
vSpheretf_
PtrList<volSphericalTensorField> vSpheretf_ protected
Definition at line 201 of file nearWallFields.H.
vSymmtf_
PtrList<volSymmTensorField> vSymmtf_ protected
Definition at line 202 of file nearWallFields.H.
vtf_
PtrList<volTensorField> vtf_ protected
Definition at line 203 of file nearWallFields.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/nearWallFields/nearWallFields.H
src/functionObjects/field/nearWallFields/nearWallFields.C
src/functionObjects/field/nearWallFields/nearWallFieldsTemplates.C