OpenFOAM: MarshakRadiationFixedTemperatureFvPatchScalarField Class Reference
MarshakRadiationFixedTemperatureFvPatchScalarField Class Reference
#include <MarshakRadiationFixedTemperatureFvPatchScalarField.H>
Public Member Functions
TypeName ("MarshakRadiationFixedTemperature")
MarshakRadiationFixedTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
MarshakRadiationFixedTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
MarshakRadiationFixedTemperatureFvPatchScalarField (const MarshakRadiationFixedTemperatureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
MarshakRadiationFixedTemperatureFvPatchScalarField (const MarshakRadiationFixedTemperatureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
MarshakRadiationFixedTemperatureFvPatchScalarField (const MarshakRadiationFixedTemperatureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
const scalarField & Trad () const
scalarField & Trad ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Definition at line 84 of file MarshakRadiationFixedTemperatureFvPatchScalarField.H.
Constructor & Destructor Documentation
MarshakRadiationFixedTemperatureFvPatchScalarField() [1/5]
MarshakRadiationFixedTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 32 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
References Foam::Zero.
MarshakRadiationFixedTemperatureFvPatchScalarField() [2/5]
MarshakRadiationFixedTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 62 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
References fvPatchField< scalar >::operator=(), Foam::pow4(), Foam::constant::physicoChemical::sigma, and Foam::Zero.
MarshakRadiationFixedTemperatureFvPatchScalarField() [3/5]
MarshakRadiationFixedTemperatureFvPatchScalarField (const MarshakRadiationFixedTemperatureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 48 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
MarshakRadiationFixedTemperatureFvPatchScalarField() [4/5]
MarshakRadiationFixedTemperatureFvPatchScalarField (const MarshakRadiationFixedTemperatureFvPatchScalarField & ptf)
Definition at line 82 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
MarshakRadiationFixedTemperatureFvPatchScalarField() [5/5]
MarshakRadiationFixedTemperatureFvPatchScalarField (const MarshakRadiationFixedTemperatureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 93 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("MarshakRadiationFixedTemperature")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 136 of file MarshakRadiationFixedTemperatureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 152 of file MarshakRadiationFixedTemperatureFvPatchScalarField.H.
Trad() [1/2]
const scalarField & Trad () const inline
Definition at line 173 of file MarshakRadiationFixedTemperatureFvPatchScalarField.H.
Trad() [2/2]
scalarField & Trad () inline
Definition at line 180 of file MarshakRadiationFixedTemperatureFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 107 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 118 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 133 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
References gamma, mesh, UPstream::msgType(), MeshObject< fvMesh, Foam::GeometricMeshObject, boundaryRadiationProperties >::New(), Foam::pow4(), and Foam::constant::physicoChemical::sigma.
write()
void write (Ostream & os) const virtual
Definition at line 176 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
References os(), and mixedFvPatchField< Type >::write().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/derivedFvPatchFields/MarshakRadiationFixedTemperature/MarshakRadiationFixedTemperatureFvPatchScalarField.H
src/thermophysicalModels/radiation/derivedFvPatchFields/MarshakRadiationFixedTemperature/MarshakRadiationFixedTemperatureFvPatchScalarField.C