OpenFOAM: aspectRatioModel Class Reference
aspectRatioModel Class Reference abstract
#include <aspectRatioModel.H>
Public Member Functions
TypeName ("aspectRatioModel")
declareRunTimeSelectionTable (autoPtr, aspectRatioModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
aspectRatioModel (const dictionary &dict, const phasePair &pair)
virtual ~aspectRatioModel ()=default
virtual tmp< volScalarField > E () const =0
TypeName ("aspectRatioModel")
declareRunTimeSelectionTable (autoPtr, aspectRatioModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
aspectRatioModel (const dictionary &dict, const phasePair &pair)
virtual ~aspectRatioModel ()=default
virtual tmp< volScalarField > E () const =0
Static Public Member Functions
static autoPtr< aspectRatioModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< aspectRatioModel > New (const dictionary &dict, const phasePair &pair)
Protected Attributes
const phasePair & pair_
Detailed Description
Source files
aspectRatioModel.H
aspectRatioModel.C
Source files
aspectRatioModel.H
aspectRatioModel.C
Definition at line 51 of file aspectRatioModel.H.
Constructor & Destructor Documentation
aspectRatioModel() [1/2]
aspectRatioModel (const dictionary & dict, const phasePair & pair)
Definition at line 36 of file aspectRatioModel.C.
~aspectRatioModel() [1/2]
virtual ~aspectRatioModel () virtual default
aspectRatioModel() [2/2]
aspectRatioModel (const dictionary & dict, const phasePair & pair)
~aspectRatioModel() [2/2]
virtual ~aspectRatioModel () virtual default
Member Function Documentation
TypeName() [1/2]
TypeName ("aspectRatioModel")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , aspectRatioModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
New() [1/2]
Foam::autoPtr< Foam::aspectRatioModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 49 of file aspectRatioModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
Referenced by orderedPhasePair::orderedPhasePair().
E() [1/2]
virtual tmp< volScalarField > E () const pure virtual
Implemented in constantAspectRatio, TomiyamaAspectRatio, VakhrushevEfremov, Wellek, constantAspectRatio, TomiyamaAspectRatio, VakhrushevEfremov, and Wellek.
TypeName() [2/2]
TypeName ("aspectRatioModel")
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , aspectRatioModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
New() [2/2]
static autoPtr< aspectRatioModel > New (const dictionary & dict, const phasePair & pair) static
E() [2/2]
virtual tmp< volScalarField > E () const pure virtual
Implemented in constantAspectRatio, TomiyamaAspectRatio, VakhrushevEfremov, Wellek, constantAspectRatio, TomiyamaAspectRatio, VakhrushevEfremov, and Wellek.
Member Data Documentation
pair_
const phasePair & pair_ protected
Definition at line 58 of file aspectRatioModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/aspectRatioModels/aspectRatioModel/aspectRatioModel.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/aspectRatioModels/aspectRatioModel/aspectRatioModel.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/aspectRatioModels/aspectRatioModel/aspectRatioModel.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/aspectRatioModels/aspectRatioModel/aspectRatioModel.C