OpenFOAM: sigInt Class Reference
sigInt Class Reference
Signal handler for INT interrupt.
#include <sigInt.H>
Public Member Functions
sigInt ()
~sigInt ()
Static Public Member Functions
static void set (bool verbose=false)
static void unset (bool verbose=false)
Detailed Description
Signal handler for INT interrupt.
The standard interrupt handler is overridden to ensure that the runningJob file is removed.
Can be used either directly through the static member functions or through the scope of the object (constructor sets trapping; destructor restores original).
See also
Foam::JobInfo
Source files
sigInt.H
sigInt.C
Definition at line 55 of file sigInt.H.
Constructor & Destructor Documentation
sigInt()
sigInt ()
Definition at line 49 of file sigInt.C.
~sigInt()
~sigInt ()
Definition at line 57 of file sigInt.C.
Member Function Documentation
set()
void set (bool verbose = false) static
Definition at line 65 of file sigInt.C.
References Foam::setHandler().
Referenced by argList::parse().
unset()
void unset (bool verbose = false) static
Definition at line 77 of file sigInt.C.
References Foam::resetHandler().
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/signals/sigInt.H
src/OSspecific/POSIX/signals/sigInt.C