OpenFOAM: volBSplinesBase Class Reference
volBSplinesBase Class Reference
Class constructing a number of volumetric B-Splines boxes, read from dynamicMeshDict. Useful for various sensitivities and optMeshMovement classes.
#include <volBSplinesBase.H>
Public Member Functions
TypeName ("volBSplinesBase")
volBSplinesBase (const fvMesh &mesh)
virtual ~volBSplinesBase ()=default
const PtrList< NURBS3DVolume > & boxes () const
PtrList< NURBS3DVolume > & boxesRef ()
const NURBS3DVolume & box (const label boxI) const
NURBS3DVolume & boxRef (const label boxI)
const vectorField & getControlPoints (const label &iNURB) const
vectorField getAllControlPoints () const
label getTotalControlPointsNumber () const
label getNumberOfBoxes () const
labelList getStartCpID () const
label findBoxID (const label cpI) const
const labelList & getActiveDesignVariables () const
scalar computeMaxBoundaryDisplacement (const vectorField &controlPointsMovement, const labelList &patchesToBeMoved)
void boundControlPointMovement (vectorField &controlPointsMovement) const
void moveControlPoints (const vectorField &controlPointsMovement)
void writeControlPoints () const
virtual bool movePoints ()
virtual void updateMesh (const mapPolyMesh &)
Public Member Functions inherited from MeshObject< fvMesh, UpdateableMeshObject, volBSplinesBase >
MeshObject (const fvMesh &mesh)
MeshObject (const word &objName, const fvMesh &mesh)
virtual ~MeshObject ()=default
const fvMesh & mesh () const noexcept
virtual bool writeData (Ostream &os) const
Protected Attributes
PtrList< NURBS3DVolume > volume_
labelList activeDesignVariables_
Protected Attributes inherited from MeshObject< fvMesh, UpdateableMeshObject, volBSplinesBase >
const fvMesh & mesh_
Additional Inherited Members
Static Public Member Functions inherited from MeshObject< fvMesh, UpdateableMeshObject, volBSplinesBase >
static const volBSplinesBase & New (const fvMesh &mesh, Args &&... args)
static const volBSplinesBase & New (const word &objName, const fvMesh &mesh, Args &&... args)
static bool Delete (const word &objName, const fvMesh &mesh)
static bool Delete (const fvMesh &mesh)
Detailed Description
Class constructing a number of volumetric B-Splines boxes, read from dynamicMeshDict. Useful for various sensitivities and optMeshMovement classes.
Derives from MeshObject so that all instances know and update the same control points and parametric coordinates are computed only once
Source files
volBSplinesBase.H
volBSplinesBase.C
Definition at line 55 of file volBSplinesBase.H.
Constructor & Destructor Documentation
volBSplinesBase()
volBSplinesBase (const fvMesh & mesh)
Definition at line 36 of file volBSplinesBase.C.
References volBSplinesBase::activeDesignVariables_, forAll, volBSplinesBase::getStartCpID(), volBSplinesBase::getTotalControlPointsNumber(), MeshObject< fvMesh, UpdateableMeshObject, volBSplinesBase >::mesh(), IOobjectOption::MUST_READ_IF_MODIFIED, NURBS3DVolume::New(), IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, PtrList< T >::resize(), PtrList< T >::set(), List< T >::setSize(), UPtrList< T >::size(), dictionary::subDict(), and volBSplinesBase::volume_.
~volBSplinesBase()
virtual ~volBSplinesBase () virtual default
Member Function Documentation
TypeName()
TypeName ("volBSplinesBase")
boxes()
const PtrList< NURBS3DVolume > & boxes () const
Definition at line 103 of file volBSplinesBase.C.
References volBSplinesBase::volume_.
boxesRef()
PtrList< NURBS3DVolume > & boxesRef ()
Definition at line 109 of file volBSplinesBase.C.
References volBSplinesBase::volume_.
Referenced by sensitivityVolBSplines::assembleSensitivities(), sensitivityVolBSplinesFI::assembleSensitivities(), sensitivityVolBSplines::computeBCContributions(), optMeshMovementVolumetricBSplinesExternalMotionSolver::computeBoundaryMovement(), sensitivityVolBSplines::computeObjectiveContributions(), optMeshMovementVolumetricBSplines::optMeshMovementVolumetricBSplines(), sensitivityVolBSplines::write(), and sensitivityVolBSplinesFI::write().
box()
const NURBS3DVolume & box (const label boxI) const
Definition at line 115 of file volBSplinesBase.C.
References volBSplinesBase::volume_.
boxRef()
NURBS3DVolume & boxRef (const label boxI)
Definition at line 121 of file volBSplinesBase.C.
References volBSplinesBase::volume_.
getControlPoints()
const vectorField & getControlPoints (const label & iNURB) const
Definition at line 127 of file volBSplinesBase.C.
References volBSplinesBase::volume_.
Referenced by volBSplinesBase::getAllControlPoints().
getAllControlPoints()
vectorField getAllControlPoints () const
Definition at line 133 of file volBSplinesBase.C.
References PtrList< T >::append(), forAll, volBSplinesBase::getControlPoints(), and volBSplinesBase::volume_.
getTotalControlPointsNumber()
Foam::label getTotalControlPointsNumber () const
Definition at line 145 of file volBSplinesBase.C.
References forAll, and UPtrList< T >::size().
Referenced by optMeshMovementVolumetricBSplinesExternalMotionSolver::computeBoundaryMovement(), sensitivityVolBSplines::sensitivityVolBSplines(), sensitivityVolBSplinesFI::sensitivityVolBSplinesFI(), and volBSplinesBase::volBSplinesBase().
getNumberOfBoxes()
label getNumberOfBoxes () const
Definition at line 157 of file volBSplinesBase.C.
References UPtrList< T >::size().
Referenced by volBSplinesBase::getStartCpID().
getStartCpID()
labelList getStartCpID () const
Definition at line 163 of file volBSplinesBase.C.
References forAll, volBSplinesBase::getNumberOfBoxes(), UPtrList< T >::size(), and volBSplinesBase::volume_.
Referenced by volBSplinesBase::findBoxID(), and volBSplinesBase::volBSplinesBase().
findBoxID()
label findBoxID (const label cpI) const
Definition at line 178 of file volBSplinesBase.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, volBSplinesBase::getStartCpID(), and UPtrList< T >::size().
getActiveDesignVariables()
const Foam::labelList & getActiveDesignVariables () const
Definition at line 196 of file volBSplinesBase.C.
References volBSplinesBase::activeDesignVariables_.
computeMaxBoundaryDisplacement()
Foam::scalar computeMaxBoundaryDisplacement (const vectorField & controlPointsMovement, const labelList & patchesToBeMoved)
Definition at line 202 of file volBSplinesBase.C.
References forAll, Foam::max(), and Foam::Zero.
boundControlPointMovement()
void boundControlPointMovement (vectorField & controlPointsMovement) const
Definition at line 239 of file volBSplinesBase.C.
References forAll, and Foam::Zero.
Referenced by sensitivityVolBSplines::assembleSensitivities(), sensitivityVolBSplinesFI::assembleSensitivities(), sensitivityVolBSplines::computeBCContributions(), optMeshMovementVolumetricBSplinesExternalMotionSolver::computeBoundaryMovement(), and sensitivityVolBSplines::computeObjectiveContributions().
moveControlPoints()
void moveControlPoints (const vectorField & controlPointsMovement)
Definition at line 271 of file volBSplinesBase.C.
References forAll, and Foam::Zero.
writeControlPoints()
void writeControlPoints () const
Definition at line 302 of file volBSplinesBase.C.
movePoints()
bool movePoints () virtual
Definition at line 311 of file volBSplinesBase.C.
updateMesh()
void updateMesh (const mapPolyMesh &) virtual
Definition at line 318 of file volBSplinesBase.C.
Member Data Documentation
volume_
PtrList<NURBS3DVolume> volume_ protected
Definition at line 65 of file volBSplinesBase.H.
Referenced by volBSplinesBase::box(), volBSplinesBase::boxes(), volBSplinesBase::boxesRef(), volBSplinesBase::boxRef(), volBSplinesBase::getAllControlPoints(), volBSplinesBase::getControlPoints(), volBSplinesBase::getStartCpID(), and volBSplinesBase::volBSplinesBase().
activeDesignVariables_
labelList activeDesignVariables_ protected
Definition at line 68 of file volBSplinesBase.H.
Referenced by volBSplinesBase::getActiveDesignVariables(), and volBSplinesBase::volBSplinesBase().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBS3DVolume/volBSplinesBase/volBSplinesBase.H
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBS3DVolume/volBSplinesBase/volBSplinesBase.C