OpenFOAM: countstreambuf Class Reference
countstreambuf Class Reference
#include <OCountStream.H>
Public Member Functions
countstreambuf (std::streamsize precount=0)
std::streamsize tellp () const
void printBufInfo (Ostream &os) const
Protected Member Functions
virtual std::streampos seekoff (std::streamoff off, std::ios_base::seekdir way, std::ios_base::openmode which=std::ios_base::in|std::ios_base::out)
virtual std::streampos seekpos (std::streampos pos, std::ios_base::openmode which=std::ios_base::in|std::ios_base::out)
virtual int overflow (int c=EOF)
virtual std::streamsize xsputn (const char *s, std::streamsize n)
Detailed Description
Definition at line 45 of file OCountStream.H.
Constructor & Destructor Documentation
countstreambuf()
countstreambuf (std::streamsize precount = 0) inline explicit
Definition at line 118 of file OCountStream.H.
Member Function Documentation
seekoff()
virtual std::streampos seekoff (std::streamoff off, std::ios_base::seekdir way, std::ios_base::openmode which = std::ios_base::in|std::ios_base::out) inline protected virtual
Definition at line 55 of file OCountStream.H.
Referenced by countstreambuf::seekpos().
seekpos()
virtual std::streampos seekpos (std::streampos pos, std::ios_base::openmode which = std::ios_base::in|std::ios_base::out) inline protected virtual
Definition at line 86 of file OCountStream.H.
References Foam::pos(), and countstreambuf::seekoff().
overflow()
virtual int overflow (int c = EOF) inline protected virtual
Definition at line 97 of file OCountStream.H.
xsputn()
virtual std::streamsize xsputn (const char * s, std::streamsize n) inline protected virtual
Definition at line 108 of file OCountStream.H.
References n.
tellp()
std::streamsize tellp () const inline
Definition at line 124 of file OCountStream.H.
Referenced by ocountstream::size(), and OCountStreamAllocator::size().
printBufInfo()
void printBufInfo (Ostream & os) const inline
Definition at line 130 of file OCountStream.H.
References os().
Referenced by OCountStreamAllocator::printBufInfo().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/memory/OCountStream.H