OpenFOAM: boundaryDataSurfaceReader Class Reference
boundaryDataSurfaceReader Class Reference
A boundaryData format surface reader. However, the "surface" represented by boundaryData is actually only point data!
#include <boundaryDataSurfaceReader.H>
Public Member Functions
TypeName ("boundaryData")
boundaryDataSurfaceReader (const fileName &fName, const word &pointsName="points")
boundaryDataSurfaceReader (const fileName &fName, const dictionary &options, const word &pointsName="points")
virtual ~boundaryDataSurfaceReader ()=default
virtual const meshedSurface & geometry (const label timeIndex)
virtual instantList times () const
virtual wordList fieldNames (const label timeIndex) const
virtual tmp< Field< scalar > > field (const label timeIndex, const label fieldIndex, const scalar &refValue=pTraits< scalar >::zero) const
virtual tmp< Field< vector > > field (const label timeIndex, const label fieldIndex, const vector &refValue=pTraits< vector >::zero) const
virtual tmp< Field< sphericalTensor > > field (const label timeIndex, const label fieldIndex, const sphericalTensor &refValue=pTraits< sphericalTensor >::zero) const
virtual tmp< Field< symmTensor > > field (const label timeIndex, const label fieldIndex, const symmTensor &refValue=pTraits< symmTensor >::zero) const
virtual tmp< Field< tensor > > field (const label timeIndex, const label fieldIndex, const tensor &refValue=pTraits< tensor >::zero) const
template<class Type >
Foam::tmp< Foam::Field< Type > > readFieldTemplate (const label timeIndex, const label fieldIndex) const
template<class Type >
Foam::tmp< Foam::Field< Type > > readField (const Time &runTime, const fileName &baseDir, const instant &timeDir, const word &fieldName, Type &avg)
template<class Type >
Foam::tmp< Foam::Field< Type > > readField (const fileName &baseDir, const instant &timeDir, const word &fieldName, Type &avg)
Public Member Functions inherited from surfaceReader
TypeName ("surfaceReader")
declareRunTimeSelectionTable (autoPtr, surfaceReader, fileName,(const fileName &fName, const dictionary &options),(fName, options))
surfaceReader (const fileName &fName)
surfaceReader (const fileName &fName, const dictionary &options)
virtual ~surfaceReader ()=default
Static Public Member Functions
static pointField readPoints (const Time &runTime, const fileName &baseDir, const word &pointsName="points")
static pointField readPoints (const fileName &baseDir, const word &pointsName="points")
template<class Type >
static tmp< Field< Type > > readField (const Time &runTime, const fileName &baseDir, const instant &timeDir, const word &fieldName, Type &avg)
template<class Type >
static tmp< Field< Type > > readField (const fileName &baseDir, const instant &timeDir, const word &fieldName, Type &avg)
Static Public Member Functions inherited from surfaceReader
static dictionary formatOptions (const dictionary &dict, const word &formatName, const word &entryName="formatOptions")
static autoPtr< surfaceReader > New (const word &readType, const fileName &fName, const dictionary &options=dictionary())
Additional Inherited Members
Protected Attributes inherited from surfaceReader
fileName fileName_
Detailed Description
A boundaryData format surface reader. However, the "surface" represented by boundaryData is actually only point data!
Points <case>/constant/region0/"boundaryData"/patchName/points
Values <case>/constant/region0/"boundaryData"/patchName/TIME/field
readOptions
{
    boundaryData
    {
        points      points;
    }
}
Format options for boundaryData:
Property Description Required Default
points Name of the "points" file no points
Source files
boundaryDataSurfaceReader.H
boundaryDataSurfaceReader.C
boundaryDataSurfaceReaderTemplates.C
Definition at line 84 of file boundaryDataSurfaceReader.H.
Constructor & Destructor Documentation
boundaryDataSurfaceReader() [1/2]
boundaryDataSurfaceReader (const fileName & fName, const word & pointsName = "points") explicit
Definition at line 140 of file boundaryDataSurfaceReader.C.
boundaryDataSurfaceReader() [2/2]
boundaryDataSurfaceReader (const fileName & fName, const dictionary & options, const word & pointsName = "points")
Definition at line 150 of file boundaryDataSurfaceReader.C.
References DebugInFunction, Foam::endl(), Foam::Info, dictionary::readIfPresent(), and fileName::toAbsolute().
~boundaryDataSurfaceReader()
virtual ~boundaryDataSurfaceReader () virtual default
Member Function Documentation
TypeName()
TypeName ("boundaryData")
readPoints() [1/2]
Foam::pointField readPoints (const Time & runTime, const fileName & baseDir, const word & pointsName = "points") static
Definition at line 43 of file boundaryDataSurfaceReader.C.
References DebugInfo, UPtrList< T >::empty(), Foam::endl(), io(), IOobjectOption::MUST_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, points, and runTime.
readPoints() [2/2]
Foam::pointField readPoints (const fileName & baseDir, const word & pointsName = "points") static
Definition at line 82 of file boundaryDataSurfaceReader.C.
References argList::envGlobalPath(), and Time::New().
readField() [1/4]
template<class Type > static tmp< Field< Type > > readField (const Time & runTime, const fileName & baseDir, const instant & timeDir, const word & fieldName, Type & avg) static
readField() [2/4]
template<class Type > static tmp< Field< Type > > readField (const fileName & baseDir, const instant & timeDir, const word & fieldName, Type & avg) static
geometry()
const Foam::meshedSurface & geometry (const label timeIndex) virtual
Implements surfaceReader.
Definition at line 177 of file boundaryDataSurfaceReader.C.
References DebugInFunction, Foam::endl(), and timeIndex.
times()
Foam::instantList times () const virtual
Implements surfaceReader.
Definition at line 194 of file boundaryDataSurfaceReader.C.
fieldNames()
Foam::wordList fieldNames (const label timeIndex) const virtual
Implements surfaceReader.
Definition at line 200 of file boundaryDataSurfaceReader.C.
References UPtrList< T >::begin(), PtrList< T >::clear(), UPtrList< T >::end(), f(), Foam::fileHandler, Foam::name(), UPtrList< T >::size(), Foam::sort(), and timeIndex.
field() [1/5]
Foam::tmp< Foam::Field< Foam::scalar > > field (const label timeIndex, const label fieldIndex, const scalar & refValue = pTraits<scalar>::zero) const virtual
Implements surfaceReader.
Definition at line 230 of file boundaryDataSurfaceReader.C.
References timeIndex.
field() [2/5]
Foam::tmp< Foam::Field< Foam::vector > > field (const label timeIndex, const label fieldIndex, const vector & refValue = pTraits<vector>::zero) const virtual
Implements surfaceReader.
Definition at line 241 of file boundaryDataSurfaceReader.C.
References timeIndex.
field() [3/5]
Foam::tmp< Foam::Field< Foam::sphericalTensor > > field (const label timeIndex, const label fieldIndex, const sphericalTensor & refValue = pTraits<sphericalTensor>::zero) const virtual
Implements surfaceReader.
Definition at line 253 of file boundaryDataSurfaceReader.C.
References timeIndex.
field() [4/5]
Foam::tmp< Foam::Field< Foam::symmTensor > > field (const label timeIndex, const label fieldIndex, const symmTensor & refValue = pTraits<symmTensor>::zero) const virtual
Implements surfaceReader.
Definition at line 264 of file boundaryDataSurfaceReader.C.
References timeIndex.
field() [5/5]
Foam::tmp< Foam::Field< Foam::tensor > > field (const label timeIndex, const label fieldIndex, const tensor & refValue = pTraits<tensor>::zero) const virtual
Implements surfaceReader.
Definition at line 275 of file boundaryDataSurfaceReader.C.
References timeIndex.
readFieldTemplate()
template<class Type > Foam::tmp< Foam::Field< Type > > readFieldTemplate (const label timeIndex, const label fieldIndex) const
Definition at line 120 of file boundaryDataSurfaceReader.C.
References timeIndex.
readField() [3/4]
template<class Type > Foam::tmp< Foam::Field< Type > > readField (const Time & runTime, const fileName & baseDir, const instant & timeDir, const word & fieldName, Type & avg)
Definition at line 30 of file boundaryDataSurfaceReaderTemplates.C.
References DebugInfo, Foam::endl(), io(), IOobjectOption::MUST_READ, surfaceReader::New(), IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, IOobjectOption::READ_IF_PRESENT, runTime, and UPtrList< T >::size().
readField() [4/4]
template<class Type > Foam::tmp< Foam::Field< Type > > readField (const fileName & baseDir, const instant & timeDir, const word & fieldName, Type & avg)
Definition at line 74 of file boundaryDataSurfaceReaderTemplates.C.
References argList::envGlobalPath(), and Time::New().
The documentation for this class was generated from the following files:
src/surfMesh/readers/boundary/boundaryDataSurfaceReader.H
src/surfMesh/readers/boundary/boundaryDataSurfaceReader.C
src/surfMesh/readers/boundary/boundaryDataSurfaceReaderTemplates.C