OpenFOAM: temperatureCoupledBase Class Reference
temperatureCoupledBase Class Reference abstract
Common functions used in temperature coupled boundaries.
#include <temperatureCoupledBase.H>
Public Types
enum KMethodType {
mtFluidThermo , mtSolidThermo , mtDirectionalSolidThermo , mtLookup ,
mtFunction
}
Public Member Functions
temperatureCoupledBase (const fvPatch &patch, const KMethodType method=KMethodType::mtFluidThermo)
temperatureCoupledBase (const fvPatch &patch, const KMethodType method, const word &kappaName, const word &alphaName, const word &alphaAniName)
temperatureCoupledBase (const fvPatch &patch, const dictionary &dict)
temperatureCoupledBase (const fvPatch &patch, const temperatureCoupledBase &base)
temperatureCoupledBase (const temperatureCoupledBase &base)
virtual ~temperatureCoupledBase ()=default
word KMethod () const
const word & kappaName () const noexcept
const word & alphaName () const noexcept
virtual void autoMap (const fvPatchFieldMapper &)=0
virtual void rmap (const fvPatchField< scalar > &, const labelList &)=0
virtual tmp< scalarField > kappa (const scalarField &Tp) const
virtual tmp< scalarField > alpha (const scalarField &Tp) const
void write (Ostream &os) const
Protected Attributes
const fvPatch & patch_
const KMethodType method_
const word kappaName_
const word alphaName_
const word alphaAniName_
autoPtr< PatchFunction1< scalar > > kappaFunction1_
autoPtr< PatchFunction1< scalar > > alphaFunction1_
Static Protected Attributes
static const Enum< KMethodType > KMethodTypeNames_
Detailed Description
Common functions used in temperature coupled boundaries.
The thermal conductivity kappa may be obtained by the following methods:
'lookup' : lookup volScalarField (or volSymmTensorField) with name defined by 'kappa'
'fluidThermo' : use fluidThermo and default compressible::turbulenceModel to calculate kappa
'solidThermo' : use solidThermo kappa()
'directionalSolidThermo': uses look up for volSymmTensorField for transformed kappa vector. Field name definable in 'alphaAni', named 'Anialpha' in solid solver by default
'function' : kappa, alpha directly specified as Function1
'phaseSystem' : used for multiphase thermos
Keywords provided by this class:
Property Description Required Default
kappaMethod Thermal conductivity method yes
kappa Name of thermal conductivity field partly
alpha Name of thermal diffusivity field partly
alphaAni Name of non-isotropic alpha partly
kappaValue Function1 supplying kappa partly
alphaValue Function1 supplying alpha partly
Usage
nonIsotropicWall
{
    ...
    kappaMethod     directionalSolidThermo;
    alphaAni        Anialpha;
    ...
}
specifiedWall
{
    ...
    kappaMethod     function;
    kappaFunction   constant 1.0;
    alphaFunction   constant 100.0;
    ...
}
Source files
temperatureCoupledBase.H
temperatureCoupledBase.C
Definition at line 131 of file temperatureCoupledBase.H.
Member Enumeration Documentation
KMethodType
enum KMethodType
Enumerator
mtFluidThermo
mtSolidThermo
mtDirectionalSolidThermo
mtLookup
mtFunction
Definition at line 138 of file temperatureCoupledBase.H.
Constructor & Destructor Documentation
temperatureCoupledBase() [1/5]
temperatureCoupledBase (const fvPatch & patch, const KMethodType method = KMethodType::mtFluidThermo) explicit
Definition at line 47 of file temperatureCoupledBase.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, temperatureCoupledBase::KMethodTypeNames_, temperatureCoupledBase::method_, temperatureCoupledBase::mtDirectionalSolidThermo, temperatureCoupledBase::mtFunction, and temperatureCoupledBase::mtLookup.
temperatureCoupledBase() [2/5]
temperatureCoupledBase (const fvPatch & patch, const KMethodType method, const word & kappaName, const word & alphaName, const word & alphaAniName)
Definition at line 81 of file temperatureCoupledBase.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, temperatureCoupledBase::KMethodTypeNames_, temperatureCoupledBase::method_, and temperatureCoupledBase::mtFunction.
temperatureCoupledBase() [3/5]
temperatureCoupledBase (const fvPatch & patch, const dictionary & dict)
Definition at line 116 of file temperatureCoupledBase.C.
References temperatureCoupledBase::alphaFunction1_, dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, temperatureCoupledBase::kappaFunction1_, temperatureCoupledBase::KMethodTypeNames_, temperatureCoupledBase::method_, temperatureCoupledBase::mtDirectionalSolidThermo, temperatureCoupledBase::mtFunction, temperatureCoupledBase::mtLookup, Foam::nl, and temperatureCoupledBase::patch_.
temperatureCoupledBase() [4/5]
temperatureCoupledBase (const fvPatch & patch, const temperatureCoupledBase & base)
Definition at line 197 of file temperatureCoupledBase.C.
temperatureCoupledBase() [5/5]
temperatureCoupledBase (const temperatureCoupledBase & base)
Definition at line 188 of file temperatureCoupledBase.C.
~temperatureCoupledBase()
virtual ~temperatureCoupledBase () virtual default
Member Function Documentation
KMethod()
word KMethod () const inline
Definition at line 223 of file temperatureCoupledBase.H.
References temperatureCoupledBase::KMethodTypeNames_, and temperatureCoupledBase::method_.
kappaName()
const word & kappaName () const inline noexcept
Definition at line 229 of file temperatureCoupledBase.H.
References temperatureCoupledBase::kappaName_.
alphaName()
const word & alphaName () const inline noexcept
Definition at line 235 of file temperatureCoupledBase.H.
References temperatureCoupledBase::alphaName_.
autoMap()
void autoMap (const fvPatchFieldMapper & mapper) pure virtual
Implemented in filmPyrolysisRadiativeCoupledMixedFvPatchScalarField, externalWallHeatFluxTemperatureFvPatchScalarField, fixedIncidentRadiationFvPatchScalarField, humidityTemperatureCoupledMixedFvPatchScalarField, lumpedMassWallTemperatureFvPatchScalarField, turbulentTemperatureCoupledBaffleMixedFvPatchScalarField, and turbulentTemperatureRadCoupledMixedFvPatchScalarField.
Definition at line 215 of file temperatureCoupledBase.C.
Referenced by filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::autoMap(), externalWallHeatFluxTemperatureFvPatchScalarField::autoMap(), fixedIncidentRadiationFvPatchScalarField::autoMap(), humidityTemperatureCoupledMixedFvPatchScalarField::autoMap(), lumpedMassWallTemperatureFvPatchScalarField::autoMap(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::autoMap(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::autoMap().
rmap()
void rmap (const fvPatchField< scalar > & ptf, const labelList & addr) pure virtual
Implemented in filmPyrolysisRadiativeCoupledMixedFvPatchScalarField, lumpedMassWallTemperatureFvPatchScalarField, turbulentTemperatureCoupledBaffleMixedFvPatchScalarField, turbulentTemperatureRadCoupledMixedFvPatchScalarField, externalWallHeatFluxTemperatureFvPatchScalarField, fixedIncidentRadiationFvPatchScalarField, and humidityTemperatureCoupledMixedFvPatchScalarField.
Definition at line 231 of file temperatureCoupledBase.C.
Referenced by filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::rmap(), lumpedMassWallTemperatureFvPatchScalarField::rmap(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::rmap(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::rmap(), externalWallHeatFluxTemperatureFvPatchScalarField::rmap(), fixedIncidentRadiationFvPatchScalarField::rmap(), and humidityTemperatureCoupledMixedFvPatchScalarField::rmap().
kappa()
Foam::tmp< Foam::scalarField > kappa (const scalarField & Tp) const virtual
Reimplemented in turbulentTemperatureCoupledBaffleMixedFvPatchScalarField, and turbulentTemperatureRadCoupledMixedFvPatchScalarField.
Definition at line 253 of file temperatureCoupledBase.C.
References polyMesh::boundaryMesh(), objectRegistry::cfindObject(), basicThermo::dictName, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), basicThermo::kappa(), multiphaseInterSystem::kappaEff(), objectRegistry::lookupObject(), mesh, n, fvMesh::name(), Foam::nl, multiphaseInterSystem::phasePropertiesName, pp(), and turbulenceModel::propertiesName.
Referenced by turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::kappa(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::kappa(), and filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs().
alpha()
Foam::tmp< Foam::scalarField > alpha (const scalarField & Tp) const virtual
Definition at line 414 of file temperatureCoupledBase.C.
References basicThermo::alpha(), polyMesh::boundaryMesh(), objectRegistry::cfindObject(), basicThermo::dictName, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), objectRegistry::lookupObject(), mesh, n, fvMesh::name(), Foam::nl, and turbulenceModel::propertiesName.
write()
void write (Ostream & os) const
Definition at line 563 of file temperatureCoupledBase.C.
References os(), and Ostream::writeEntry().
Referenced by filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::write(), externalWallHeatFluxTemperatureFvPatchScalarField::write(), fixedIncidentRadiationFvPatchScalarField::write(), humidityTemperatureCoupledMixedFvPatchScalarField::write(), lumpedMassWallTemperatureFvPatchScalarField::write(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::write(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::write().
Member Data Documentation
KMethodTypeNames_
const Foam::Enum< Foam::temperatureCoupledBase::KMethodType > KMethodTypeNames_ static protected
Initial value:
{
    { KMethodType::mtFluidThermo, "fluidThermo" },
    { KMethodType::mtSolidThermo, "solidThermo" },
    { KMethodType::mtDirectionalSolidThermo, "directionalSolidThermo" },
    { KMethodType::mtLookup, "lookup" },
    { KMethodType::mtFunction, "function" }
}
Definition at line 35 of file temperatureCoupledBase.H.
Referenced by temperatureCoupledBase::KMethod(), temperatureCoupledBase::temperatureCoupledBase(), temperatureCoupledBase::temperatureCoupledBase(), and temperatureCoupledBase::temperatureCoupledBase().
patch_
const fvPatch& patch_ protected
Definition at line 155 of file temperatureCoupledBase.H.
Referenced by temperatureCoupledBase::temperatureCoupledBase().
method_
const KMethodType method_ protected
Definition at line 158 of file temperatureCoupledBase.H.
Referenced by temperatureCoupledBase::KMethod(), temperatureCoupledBase::temperatureCoupledBase(), temperatureCoupledBase::temperatureCoupledBase(), and temperatureCoupledBase::temperatureCoupledBase().
kappaName_
const word kappaName_ protected
Definition at line 161 of file temperatureCoupledBase.H.
Referenced by temperatureCoupledBase::kappaName().
alphaName_
const word alphaName_ protected
Definition at line 164 of file temperatureCoupledBase.H.
Referenced by temperatureCoupledBase::alphaName().
alphaAniName_
const word alphaAniName_ protected
Definition at line 167 of file temperatureCoupledBase.H.
kappaFunction1_
autoPtr<PatchFunction1<scalar> > kappaFunction1_ protected
Definition at line 170 of file temperatureCoupledBase.H.
Referenced by temperatureCoupledBase::temperatureCoupledBase().
alphaFunction1_
autoPtr<PatchFunction1<scalar> > alphaFunction1_ protected
Definition at line 173 of file temperatureCoupledBase.H.
Referenced by temperatureCoupledBase::temperatureCoupledBase().
The documentation for this class was generated from the following files:
src/thermoTools/derivedFvPatchFields/temperatureCoupledBase/temperatureCoupledBase.H
src/thermoTools/derivedFvPatchFields/temperatureCoupledBase/temperatureCoupledBase.C