OpenFOAM: fvMeshDistribute Class Reference
fvMeshDistribute Class Reference
Sends/receives parts of mesh+fvfields to neighbouring processors. Used in load balancing.
#include <fvMeshDistribute.H>
Public Member Functions
ClassName ("fvMeshDistribute")
fvMeshDistribute (fvMesh &mesh)
autoPtr< mapDistributePolyMesh > distribute (const labelList &dist)
Static Public Member Functions
static labelList countCells (const labelList &)
static void printCoupleInfo (const primitiveMesh &, const labelList &, const labelList &, const labelList &, const labelList &)
template<class GeoField >
static void printIntFieldInfo (const fvMesh &)
template<class GeoField >
static void printFieldInfo (const fvMesh &)
static void printMeshInfo (const fvMesh &)
static tmp< surfaceScalarField > generateTestField (const fvMesh &)
static void testField (const surfaceScalarField &)
Detailed Description
Sends/receives parts of mesh+fvfields to neighbouring processors. Used in load balancing.
Input is per local cell the processor it should move to. Moves meshes and volFields/surfaceFields and returns map which can be used to distribute other.
Notes:
does not handle cyclics. Will probably handle separated proc patches.
if all cells move off processor also all its processor patches will get deleted so comms might be screwed up (since e.g. globalMeshData expects procPatches on all)
initial mesh has to have procPatches last and all normal patches common to all processors and in the same order. This is checked.
Source files
fvMeshDistribute.H
fvMeshDistribute.C
fvMeshDistributeTemplates.C
Definition at line 66 of file fvMeshDistribute.H.
Constructor & Destructor Documentation
fvMeshDistribute()
fvMeshDistribute (fvMesh & mesh) explicit
Definition at line 1856 of file fvMeshDistribute.C.
Member Function Documentation
ClassName()
ClassName ("fvMeshDistribute")
countCells()
Foam::labelList countCells (const labelList & distribution) static
Definition at line 1864 of file fvMeshDistribute.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::nProcs(), and Foam::Zero.
distribute()
Foam::autoPtr< Foam::mapDistributePolyMesh > distribute (const labelList & dist)
Definition at line 1888 of file fvMeshDistribute.C.
References Foam::abort(), fvMeshAdder::add(), UPstream::allToAll(), fvMeshSubset::cellMap(), PtrList< T >::clear(), Foam::endl(), fvMeshSubset::faceFlipMap(), fvMeshSubset::faceMap(), Foam::faceMap(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), forAll, Foam::identity(), Foam::inplaceReorder(), meshes(), UPstream::myProcNo(), autoPtr< T >::New(), Foam::nl, UPstream::nonBlocking, UPstream::nProcs(), UPstream::parRun(), patches, fvMeshSubset::patchMap(), fvMeshSubset::pointMap(), Foam::Pout, Foam::renumber(), PtrList< T >::set(), List< T >::setSize(), PtrList< T >::setSize(), HashTable< T, Key, Hash >::size(), UPtrList< T >::size(), fvMeshSubset::subMesh(), List< T >::transfer(), PtrList< T >::transfer(), FieldBase::typeName, and Foam::Zero.
printCoupleInfo()
void printCoupleInfo (const primitiveMesh & mesh, const labelList & sourceFace, const labelList & sourceProc, const labelList & sourcePatch, const labelList & sourceNewNbrProc) static
Definition at line 277 of file fvMeshDistribute.C.
References Foam::endl(), primitiveMesh::faceCentres(), forAll, mesh, primitiveMesh::nInternalFaces(), Foam::nl, and Foam::Pout.
printIntFieldInfo()
template<class GeoField > void printIntFieldInfo (const fvMesh & mesh) static
Definition at line 74 of file fvMeshDistributeTemplates.C.
References Foam::endl(), fld(), forAllConstIters, mesh, Foam::Pout, and UPtrList< T >::size().
printFieldInfo()
template<class GeoField > void printFieldInfo (const fvMesh & mesh) static
Definition at line 102 of file fvMeshDistributeTemplates.C.
References Foam::endl(), fld(), forAllConstIters, mesh, Foam::nl, Foam::Pout, and UPtrList< T >::size().
printMeshInfo()
void printMeshInfo (const fvMesh & mesh) static
Definition at line 218 of file fvMeshDistribute.C.
References fvMesh::boundary(), polyMesh::cellZones(), Foam::endl(), polyMesh::faceZones(), forAll, mesh, zoneIdentifier::name(), primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, primitiveMesh::nPoints(), patches, polyMesh::points(), polyMesh::pointZones(), Foam::Pout, pp(), UPtrList< T >::size(), and UList< T >::size().
generateTestField()
Foam::tmp< Foam::surfaceScalarField > generateTestField (const fvMesh & mesh) static
Definition at line 397 of file fvMeshDistribute.C.
References Foam::dimless, fld(), forAll, fvMesh::magSf(), mesh, n, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::normalised(), VectorSpace< Form, Cmpt, Ncmpts >::one, fvMesh::Sf(), UPtrList< T >::size(), fvMesh::time(), and Foam::Zero.
testField()
void testField (const surfaceScalarField & fld) static
Definition at line 448 of file fvMeshDistribute.C.
References Foam::cos(), e, Foam::endl(), primitiveMesh::faceCentres(), fld(), forAll, Foam::mag(), fvMesh::magSf(), mesh, n, Foam::normalised(), VectorSpace< Form, Cmpt, Ncmpts >::one, fvMesh::Sf(), and WarningInFunction.
The documentation for this class was generated from the following files:
src/dynamicMesh/fvMeshDistribute/fvMeshDistribute.H
src/dynamicMesh/fvMeshDistribute/fvMeshDistribute.C
src/dynamicMesh/fvMeshDistribute/fvMeshDistributeTemplates.C