OpenFOAM: sutherlandTransport< Thermo > Class Template Reference
sutherlandTransport< Thermo > Class Template Reference
Thermophysical models » Specie » Transport
Transport package using Sutherland's formula.
#include <sutherlandTransport.H>
Public Member Functions
sutherlandTransport (const Thermo &t, const scalar As, const scalar Ts)
sutherlandTransport (const Thermo &t, const scalar mu1, const scalar T1, const scalar mu2, const scalar T2)
sutherlandTransport (const word &, const sutherlandTransport &)
sutherlandTransport (const dictionary &dict)
sutherlandTransport (const Thermo &t, const dictionary &dict)
autoPtr< sutherlandTransport > clone () const
scalar mu (const scalar p, const scalar T) const
scalar kappa (const scalar p, const scalar T) const
scalar alphah (const scalar p, const scalar T) const
void write (Ostream &os) const
void operator+= (const sutherlandTransport &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< sutherlandTransport > New (const dictionary &dict)
static word typeName ()
Friends
sutherlandTransport operator+ (const sutherlandTransport &, const sutherlandTransport &)
sutherlandTransport operator* (const scalar, const sutherlandTransport &)
Ostream & operator<< (Ostream &, const sutherlandTransport &)
Detailed Description
template<class Thermo>
class Foam::sutherlandTransport< Thermo >
Transport package using Sutherland's formula.
Templated into a given thermodynamics package (needed for thermal conductivity).
Dynamic viscosity [kg/m.s]
Source files
sutherlandTransport.H
sutherlandTransportI.H
sutherlandTransport.C
Definition at line 84 of file sutherlandTransport.H.
Constructor & Destructor Documentation
sutherlandTransport() [1/5]
template<class Thermo > sutherlandTransport (const Thermo & t, const scalar As, const scalar Ts) inline
Definition at line 45 of file sutherlandTransportI.H.
sutherlandTransport() [2/5]
template<class Thermo > sutherlandTransport (const Thermo & t, const scalar mu1, const scalar T1, const scalar mu2, const scalar T2) inline
Definition at line 59 of file sutherlandTransportI.H.
sutherlandTransport() [3/5]
template<class Thermo > sutherlandTransport (const word & name, const sutherlandTransport< Thermo > & st) inline
Definition at line 73 of file sutherlandTransportI.H.
sutherlandTransport() [4/5]
template<class Thermo > sutherlandTransport (const dictionary & dict) explicit
Definition at line 40 of file sutherlandTransport.C.
sutherlandTransport() [5/5]
template<class Thermo > sutherlandTransport (const Thermo & t, const dictionary & dict)
Definition at line 49 of file sutherlandTransport.C.
Member Function Documentation
clone()
template<class Thermo > Foam::autoPtr< Foam::sutherlandTransport< Thermo > > clone () const inline
Definition at line 87 of file sutherlandTransportI.H.
References Foam::New().
New()
template<class Thermo > Foam::autoPtr< Foam::sutherlandTransport< Thermo > > New (const dictionary & dict) inline static
Definition at line 95 of file sutherlandTransportI.H.
References dict, and Foam::New().
typeName()
template<class Thermo > static word typeName () inline static
Definition at line 150 of file sutherlandTransport.H.
mu()
template<class Thermo > Foam::scalar mu (const scalar p, const scalar T) const inline
Definition at line 107 of file sutherlandTransportI.H.
References Foam::sqrt(), and T.
kappa()
template<class Thermo > Foam::scalar kappa (const scalar p, const scalar T) const inline
Definition at line 118 of file sutherlandTransportI.H.
References Cv, mu, p, R, and T.
alphah()
template<class Thermo > Foam::scalar alphah (const scalar p, const scalar T) const inline
Definition at line 129 of file sutherlandTransportI.H.
References Cp, p, and T.
write()
template<class Thermo > void write (Ostream & os) const
Definition at line 64 of file sutherlandTransport.C.
References Ostream::beginBlock(), Ostream::endBlock(), specie::name(), os(), and Ostream::writeEntry().
operator+=()
template<class Thermo > void operator+= (const sutherlandTransport< Thermo > &) inline
Definition at line 143 of file sutherlandTransportI.H.
References Foam::mag(), and Y.
operator*=()
template<class Thermo > void operator*= (const scalar s) inline
Definition at line 164 of file sutherlandTransportI.H.
References s().
Friends And Related Symbol Documentation
operator+
template<class Thermo > sutherlandTransport operator+ (const sutherlandTransport< Thermo > & , const sutherlandTransport< Thermo > &) friend
operator*
template<class Thermo > sutherlandTransport operator* (const scalar , const sutherlandTransport< Thermo > &) friend
operator<<
template<class Thermo > Ostream & operator<< (Ostream & , const sutherlandTransport< Thermo > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/transport/sutherland/sutherlandTransport.H
src/thermophysicalModels/specie/transport/sutherland/sutherlandTransport.C
src/thermophysicalModels/specie/transport/sutherland/sutherlandTransportI.H