OpenFOAM: degenerateMatcher Class Reference
degenerateMatcher Class Reference
Collection of all hex degenerate matchers (hex, wedge, prism etc.)
#include <degenerateMatcher.H>
Static Public Member Functions
static cellShape match (const faceList &faces)
static cellShape match (const cellShape &shape)
static cellShape match (const primitiveMesh &mesh, const label celli)
Detailed Description
Collection of all hex degenerate matchers (hex, wedge, prism etc.)
Has static member function to match a shape.
See also
cellMatcher
Source files
degenerateMatcher.H
degenerateMatcher.C
Definition at line 56 of file degenerateMatcher.H.
Member Function Documentation
match() [1/3]
Foam::cellShape match (const faceList & faces) static
Definition at line 76 of file degenerateMatcher.C.
References Foam::identity(), UList< T >::size(), and Foam::Zero.
match() [2/3]
Foam::cellShape match (const cellShape & shape) static
Definition at line 90 of file degenerateMatcher.C.
References cellShape::collapsedFaces().
match() [3/3]
Foam::cellShape match (const primitiveMesh & mesh, const label celli) static
Definition at line 96 of file degenerateMatcher.C.
References primitiveMesh::cells(), polyMesh::faceOwner(), polyMesh::faces(), and mesh.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/cellMatcher/degenerateMatcher.H
src/OpenFOAM/meshes/meshShapes/cellMatcher/degenerateMatcher.C