OpenFOAM: blendingMethod Class Reference
blendingMethod Class Reference abstract
#include <blendingMethod.H>
Public Member Functions
TypeName ("blendingMethod")
declareRunTimeSelectionTable (autoPtr, blendingMethod, dictionary,(const dictionary &dict, const wordList &phaseNames),(dict, phaseNames))
blendingMethod (const dictionary &dict)
virtual ~blendingMethod ()=default
virtual tmp< volScalarField > f1 (const phaseModel &phase1, const phaseModel &phase2) const =0
virtual tmp< volScalarField > f2 (const phaseModel &phase1, const phaseModel &phase2) const =0
TypeName ("blendingMethod")
declareRunTimeSelectionTable (autoPtr, blendingMethod, dictionary,(const dictionary &dict, const wordList &phaseNames),(dict, phaseNames))
blendingMethod (const dictionary &dict)
virtual ~blendingMethod ()=default
virtual tmp< volScalarField > f1 (const phaseModel &phase1, const phaseModel &phase2) const =0
virtual tmp< volScalarField > f2 (const phaseModel &phase1, const phaseModel &phase2) const =0
Static Public Member Functions
static autoPtr< blendingMethod > New (const word &modelName, const dictionary &dict, const wordList &phaseNames)
static autoPtr< blendingMethod > New (const dictionary &dict, const wordList &phaseNames)
Detailed Description
Source files
blendingMethod.H
blendingMethod.C
Source files
blendingMethod.H
blendingMethod.C
Definition at line 48 of file blendingMethod.H.
Constructor & Destructor Documentation
blendingMethod() [1/2]
blendingMethod (const dictionary & dict) explicit
Definition at line 35 of file blendingMethod.C.
~blendingMethod() [1/2]
virtual ~blendingMethod () virtual default
blendingMethod() [2/2]
blendingMethod (const dictionary & dict) explicit
~blendingMethod() [2/2]
virtual ~blendingMethod () virtual default
Member Function Documentation
TypeName() [1/2]
TypeName ("blendingMethod")
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , blendingMethod , dictionary , (const dictionary &dict, const wordList &phaseNames) , (dict, phaseNames))
New() [1/2]
Foam::autoPtr< Foam::blendingMethod > New (const word & modelName, const dictionary & dict, const wordList & phaseNames) static
Definition at line 45 of file blendingMethod.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
Referenced by phaseSystem::phaseSystem(), and twoPhaseSystem::twoPhaseSystem().
f1() [1/2]
virtual tmp< volScalarField > f1 (const phaseModel & phase1, const phaseModel & phase2) const pure virtual
Implemented in hyperbolic, linear, noBlending, hyperbolic, linear, and noBlending.
f2() [1/2]
virtual tmp< volScalarField > f2 (const phaseModel & phase1, const phaseModel & phase2) const pure virtual
Implemented in hyperbolic, linear, noBlending, hyperbolic, linear, and noBlending.
TypeName() [2/2]
TypeName ("blendingMethod")
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , blendingMethod , dictionary , (const dictionary &dict, const wordList &phaseNames) , (dict, phaseNames))
New() [2/2]
Foam::autoPtr< Foam::blendingMethod > New (const dictionary & dict, const wordList & phaseNames) static
Definition at line 45 of file blendingMethod.C.
References dict, dictionary::dictName(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
f1() [2/2]
virtual tmp< volScalarField > f1 (const phaseModel & phase1, const phaseModel & phase2) const pure virtual
Implemented in hyperbolic, linear, noBlending, hyperbolic, linear, and noBlending.
f2() [2/2]
virtual tmp< volScalarField > f2 (const phaseModel & phase1, const phaseModel & phase2) const pure virtual
Implemented in hyperbolic, linear, noBlending, hyperbolic, linear, and noBlending.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/BlendedInterfacialModel/blendingMethods/blendingMethod/blendingMethod.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/BlendedInterfacialModel/blendingMethods/blendingMethod/blendingMethod.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/BlendedInterfacialModel/blendingMethods/blendingMethod/blendingMethod.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/BlendedInterfacialModel/blendingMethods/blendingMethod/blendingMethod.C