OpenFOAM: EulerImplicit< ChemistryModel > Class Template Reference
EulerImplicit< ChemistryModel > Class Template Reference
An Euler implicit solver for chemistry.
#include <EulerImplicit.H>
Public Member Functions
TypeName ("EulerImplicit")
EulerImplicit (typename ChemistryModel::reactionThermo &thermo)
virtual ~EulerImplicit ()
void updateRRInReactionI (const label index, const scalar pr, const scalar pf, const scalar corr, const label lRef, const label rRef, const scalar p, const scalar T, simpleMatrix< scalar > &RR) const
virtual void solve (scalarField &c, scalar &T, scalar &p, scalar &deltaT, scalar &subDeltaT) const
Public Member Functions inherited from chemistrySolver< ChemistryModel >
chemistrySolver (typename ChemistryModel::reactionThermo &thermo)
virtual ~chemistrySolver ()
Detailed Description
template<class ChemistryModel>
class Foam::EulerImplicit< ChemistryModel >
An Euler implicit solver for chemistry.
Source files
EulerImplicit.H
EulerImplicit.C
Definition at line 51 of file EulerImplicit.H.
Constructor & Destructor Documentation
EulerImplicit()
template<class ChemistryModel > EulerImplicit (typename ChemistryModel::reactionThermo & thermo)
Definition at line 30 of file EulerImplicit.C.
~EulerImplicit()
template<class ChemistryModel > ~EulerImplicit () virtual
Definition at line 46 of file EulerImplicit.C.
Member Function Documentation
TypeName()
template<class ChemistryModel > TypeName ("EulerImplicit< ChemistryModel >")
updateRRInReactionI()
template<class ChemistryModel > void updateRRInReactionI (const label index, const scalar pr, const scalar pf, const scalar corr, const label lRef, const label rRef, const scalar p, const scalar T, simpleMatrix< scalar > & RR) const
Definition at line 53 of file EulerImplicit.C.
References forAll, R, and s().
solve()
template<class ChemistryModel > void solve (scalarField & c, scalar & T, scalar & p, scalar & deltaT, scalar & subDeltaT) const virtual
Implements chemistrySolver< ChemistryModel >.
Definition at line 88 of file EulerImplicit.C.
References e, forAll, Foam::max(), Foam::min(), nSpecie, p, Foam::sum(), and T.
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistrySolver/EulerImplicit/EulerImplicit.H
src/thermophysicalModels/chemistryModel/chemistrySolver/EulerImplicit/EulerImplicit.C