OpenFOAM: SpatialVector< Cmpt > Class Template Reference
SpatialVector< Cmpt > Class Template Reference
Templated 3D spatial vector derived from VectorSpace used to represent the anglular and linear components of position, velocity and acceleration of rigid bodies.
#include <SpatialVector.H>
Classes
class dual
Public Types
enum components {
WX , WY , WZ , LX ,
LY , LZ
}
Public Types inherited from VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >
typedef VectorSpace< SpatialVector< Cmpt >, Cmpt, Ncmpts > vsType
typedef Cmpt cmptType
typedef Cmpt magType
typedef Cmpt * iterator
typedef const Cmpt * const_iterator
Public Member Functions
SpatialVector ()=default
SpatialVector (const Foam::zero)
SpatialVector (const typename SpatialVector::vsType &)
SpatialVector (const Vector< Cmpt > &w, const Vector< Cmpt > &l)
SpatialVector (const Cmpt &wx, const Cmpt &wy, const Cmpt &wz, const Cmpt &lx, const Cmpt &ly, const Cmpt &lz)
SpatialVector (Istream &)
const Cmpt & wx () const noexcept
const Cmpt & wy () const noexcept
const Cmpt & wz () const noexcept
const Cmpt & lx () const noexcept
const Cmpt & ly () const noexcept
const Cmpt & lz () const noexcept
Cmpt & wx () noexcept
Cmpt & wy () noexcept
Cmpt & wz () noexcept
Cmpt & lx () noexcept
Cmpt & ly () noexcept
Cmpt & lz () noexcept
Vector< Cmpt > w () const
Vector< Cmpt > l () const
dual operator* () const
Public Member Functions inherited from VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >
VectorSpace ()=default
VectorSpace (const Foam::zero)
VectorSpace (const VectorSpace< SpatialVector< Cmpt >, Cmpt, Ncmpts > &vs)
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
VectorSpace (Istream &is)
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Cmpt * data () noexcept
const ConstBlock< SubVector, BStart > block () const
const Foam::VectorSpace< SpatialVector< Cmpt >, Cmpt, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< SpatialVector< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< SpatialVector< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< SpatialVector< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >
static constexpr direction size () noexcept
static SpatialVector< Cmpt > uniform (const Cmpt &s)
Public Attributes inherited from VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >
Cmpt v_ [Ncmpts]
Static Public Attributes inherited from VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >
static constexpr direction dim
static constexpr direction nComponents
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const SpatialVector< Cmpt > zero
static const SpatialVector< Cmpt > one
static const SpatialVector< Cmpt > max
static const SpatialVector< Cmpt > min
static const SpatialVector< Cmpt > rootMax
static const SpatialVector< Cmpt > rootMin
Detailed Description
template<class Cmpt>
class Foam::SpatialVector< Cmpt >
Templated 3D spatial vector derived from VectorSpace used to represent the anglular and linear components of position, velocity and acceleration of rigid bodies.
Reference:
    Featherstone, R. (2008).
    Rigid body dynamics algorithms.
    Springer.
Source files
SpatialVector.H
SpatialVectorI.H
See also
Foam::VectorSpace Foam::Vector
Definition at line 61 of file SpatialVector.H.
Member Enumeration Documentation
components
template<class Cmpt > enum components
Enumerator
WX
WY
WZ
LX
LY
LZ
Definition at line 69 of file SpatialVector.H.
Constructor & Destructor Documentation
SpatialVector() [1/6]
template<class Cmpt > SpatialVector () default
SpatialVector() [2/6]
template<class Cmpt > SpatialVector (const Foam::zero) inline
Definition at line 24 of file SpatialVectorI.H.
SpatialVector() [3/6]
template<class Cmpt > SpatialVector (const typename SpatialVector< Cmpt >::vsType & vs) inline
Definition at line 31 of file SpatialVectorI.H.
SpatialVector() [4/6]
template<class Cmpt > SpatialVector (const Vector< Cmpt > & w, const Vector< Cmpt > & l) inline
Definition at line 41 of file SpatialVectorI.H.
SpatialVector() [5/6]
template<class Cmpt > SpatialVector (const Cmpt & wx, const Cmpt & wy, const Cmpt & wz, const Cmpt & lx, const Cmpt & ly, const Cmpt & lz) inline
Definition at line 57 of file SpatialVectorI.H.
SpatialVector() [6/6]
template<class Cmpt > SpatialVector (Istream & is) inline explicit
Definition at line 77 of file SpatialVectorI.H.
Member Function Documentation
wx() [1/2]
template<class Cmpt > const Cmpt & wx () const inline noexcept
Definition at line 124 of file SpatialVector.H.
References VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_, and SpatialVector< Cmpt >::WX.
Referenced by Rx::jcalc().
wy() [1/2]
template<class Cmpt > const Cmpt & wy () const inline noexcept
Definition at line 125 of file SpatialVector.H.
References VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_, and SpatialVector< Cmpt >::WY.
Referenced by Ry::jcalc().
wz() [1/2]
template<class Cmpt > const Cmpt & wz () const inline noexcept
Definition at line 126 of file SpatialVector.H.
References VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_, and SpatialVector< Cmpt >::WZ.
Referenced by Rz::jcalc().
lx() [1/2]
template<class Cmpt > const Cmpt & lx () const inline noexcept
Definition at line 128 of file SpatialVector.H.
References SpatialVector< Cmpt >::LX, and VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_.
ly() [1/2]
template<class Cmpt > const Cmpt & ly () const inline noexcept
Definition at line 129 of file SpatialVector.H.
References SpatialVector< Cmpt >::LY, and VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_.
lz() [1/2]
template<class Cmpt > const Cmpt & lz () const inline noexcept
Definition at line 130 of file SpatialVector.H.
References SpatialVector< Cmpt >::LZ, and VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_.
wx() [2/2]
template<class Cmpt > Cmpt & wx () inline noexcept
Definition at line 132 of file SpatialVector.H.
References VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_, and SpatialVector< Cmpt >::WX.
wy() [2/2]
template<class Cmpt > Cmpt & wy () inline noexcept
Definition at line 133 of file SpatialVector.H.
References VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_, and SpatialVector< Cmpt >::WY.
wz() [2/2]
template<class Cmpt > Cmpt & wz () inline noexcept
Definition at line 134 of file SpatialVector.H.
References VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_, and SpatialVector< Cmpt >::WZ.
lx() [2/2]
template<class Cmpt > Cmpt & lx () inline noexcept
Definition at line 136 of file SpatialVector.H.
References SpatialVector< Cmpt >::LX, and VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_.
ly() [2/2]
template<class Cmpt > Cmpt & ly () inline noexcept
Definition at line 137 of file SpatialVector.H.
References SpatialVector< Cmpt >::LY, and VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_.
lz() [2/2]
template<class Cmpt > Cmpt & lz () inline noexcept
Definition at line 138 of file SpatialVector.H.
References SpatialVector< Cmpt >::LZ, and VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_.
w()
template<class Cmpt > Foam::Vector< Cmpt > w () const inline
Definition at line 93 of file SpatialVectorI.H.
Referenced by rigidBodyMotion::status().
l()
template<class Cmpt > Foam::Vector< Cmpt > l () const inline
Definition at line 99 of file SpatialVectorI.H.
References SpatialVector< Cmpt >::LX, SpatialVector< Cmpt >::LY, SpatialVector< Cmpt >::LZ, and VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_.
Referenced by rigidBodyMotion::status().
operator*()
template<class Cmpt > Foam::SpatialVector< Cmpt >::dual operator* () const inline
Definition at line 116 of file SpatialVectorI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/spatialVectorAlgebra/SpatialVector/SpatialVector.H
src/OpenFOAM/primitives/spatialVectorAlgebra/SpatialVector/SpatialVectorI.H