OpenFOAM: DynamicList< T, SizeMin > Class Template Reference
DynamicList< T, SizeMin > Class Template Reference
A 1D vector of objects of type <T> that resizes itself as necessary to accept the new objects.
#include <DynamicList.H>
Inherits List< T >.
Public Member Functions
constexpr DynamicList () noexcept
DynamicList (const label len)
DynamicList (const label len, const T &val)
DynamicList (const label len, const Foam::zero)
DynamicList (const DynamicList< T, SizeMin > &lst)
template<int AnySizeMin>
DynamicList (const DynamicList< T, AnySizeMin > &lst)
DynamicList (const UList< T > &lst)
DynamicList (const UList< T > &list, const labelUList &indices)
template<unsigned N>
DynamicList (const FixedList< T, N > &lst)
DynamicList (std::initializer_list< T > lst)
template<class Addr >
DynamicList (const IndirectListBase< T, Addr > &lst)
DynamicList (DynamicList< T, SizeMin > &&lst)
template<int AnySizeMin>
DynamicList (DynamicList< T, AnySizeMin > &&lst)
DynamicList (List< T > &&lst)
DynamicList (Istream &is)
label capacity () const noexcept
std::streamsize capacity_bytes () const noexcept
void setCapacity (const label len)
void setCapacity_nocopy (const label len)
void setCapacity_unsafe (const label len) noexcept
void reserve (const label len)
void reserve_nocopy (const label len)
void resize (const label len)
void resize (const label len, const T &val)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const T &val)
void clear () noexcept
void clearStorage ()
label expandStorage () noexcept
void shrinkStorage ()
DynamicList< T, SizeMin > & shrink ()
template<int AnySizeMin>
void swap (DynamicList< T, AnySizeMin > &other)
void transfer (List< T > &list)
template<int AnySizeMin>
void transfer (DynamicList< T, AnySizeMin > &list)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (const T &val)
void push_back (T &&val)
void push_back (const UList< T > &list)
template<unsigned N>
void push_back (const FixedList< T, N > &list)
void push_back (std::initializer_list< T > list)
template<class Addr >
void push_back (const IndirectListBase< T, Addr > &lst)
void push_back (List< T > &&list)
template<int AnySizeMin>
void push_back (DynamicList< T, AnySizeMin > &&list)
label push_uniq (const T &val)
void pop_back (label n=1)
T remove ()
T remove (const label idx, const bool fast=false)
label remove (const labelRange &range)
label remove (std::initializer_list< label > start_size)
label subset (const labelRange &range)
label subset (std::initializer_list< label > start_size)
T & operator() (const label i)
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (const UList< T > &lst)
template<unsigned N>
void operator= (const FixedList< T, N > &lst)
void operator= (const DynamicList< T, SizeMin > &lst)
template<int AnySizeMin>
void operator= (const DynamicList< T, AnySizeMin > &lst)
void operator= (std::initializer_list< T > lst)
template<class Addr >
void operator= (const IndirectListBase< T, Addr > &lst)
void operator= (List< T > &&lst)
void operator= (DynamicList< T, SizeMin > &&lst)
template<int AnySizeMin>
void operator= (DynamicList< T, AnySizeMin > &&lst)
Istream & readList (Istream &is)
void append (const T &val)
void append (T &&val)
void append (const UList< T > &list)
template<unsigned N>
void append (const FixedList< T, N > &list)
void append (std::initializer_list< T > list)
template<class Addr >
void append (const IndirectListBase< T, Addr > &list)
void append (List< T > &&list)
template<int AnySizeMin>
void append (DynamicList< T, AnySizeMin > &&list)
label appendUniq (const T &val)
Public Member Functions inherited from List< T >
constexpr List () noexcept
List (const label len)
List (const label len, const T &val)
List (const label len, const Foam::zero)
List (const Foam::one, const T &val)
List (const Foam::one, T &&val)
List (const Foam::one, const Foam::zero)
List (const List< T > &a)
List (const UList< T > &a)
List (List< T > &a, bool reuse)
List (const UList< T > &list, const labelUList &indices)
template<unsigned N>
List (const UList< T > &list, const FixedList< label, N > &indices)
template<unsigned N>
List (const FixedList< T, N > &list)
List (const PtrList< T > &list)
List (const SLList< T > &list)
template<class Addr >
List (const IndirectListBase< T, Addr > &list)
List (std::initializer_list< T > list)
List (List< T > &&list)
template<int SizeMin>
List (DynamicList< T, SizeMin > &&list)
List (SLList< T > &&list)
List (Istream &is)
autoPtr< List< T > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const T &val)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const T &val)
void transfer (List< T > &list)
template<int SizeMin>
void transfer (DynamicList< T, SizeMin > &list)
T & newElmt (const label i)
template<class... Args>
T & emplace_back (Args &&... args)
void push_back (const T &val)
void push_back (T &&val)
void push_back (const UList< T > &list)
template<class Addr >
void push_back (const IndirectListBase< T, Addr > &list)
label push_uniq (const T &val)
void pop_back (label n=1)
void operator= (const UList< T > &a)
void operator= (const List< T > &list)
void operator= (const SLList< T > &list)
template<class Addr >
void operator= (const IndirectListBase< T, Addr > &list)
template<unsigned N>
void operator= (const FixedList< T, N > &list)
void operator= (std::initializer_list< T > list)
void operator= (const T &val)
void operator= (const Foam::zero)
void operator= (List< T > &&list)
template<int SizeMin>
void operator= (DynamicList< T, SizeMin > &&list)
void operator= (SLList< T > &&list)
Istream & readList (Istream &is)
void shallowCopy (const UList< T > &)=delete
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const T &val)
void append (T &&val)
void append (const UList< T > &list)
template<class Addr >
void append (const IndirectListBase< T, Addr > &list)
label appendUniq (const T &val)
Istream & readList (Istream &is)
void resize (const label newLen)
Istream & readList (Istream &is)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Static Public Member Functions
static constexpr label min_size () noexcept
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Friends
Istream & operator>> (Istream &is, DynamicList< T, SizeMin > &list)
Ostream & operator (Ostream &os, const DynamicList< T, SizeMin > &list)
Additional Inherited Members
Public Types inherited from List< T >
typedef SubList< T > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Detailed Description
template<class T, int SizeMin = 16>
class Foam::DynamicList< T, SizeMin >
A 1D vector of objects of type <T> that resizes itself as necessary to accept the new objects.
Internal storage is a compact array and the list can be shrunk to compact storage. The increase of list size uses a doubling strategy, with the SizeMin template parameter dictating a lower bound.
Source files
DynamicList.H
DynamicList.C
DynamicListI.H
DynamicListIO.C
Definition at line 65 of file DynamicList.H.
Constructor & Destructor Documentation
DynamicList() [1/15]
template<class T , int SizeMin> constexpr DynamicList () inline constexpr noexcept
Definition at line 131 of file DynamicListI.H.
DynamicList() [2/15]
template<class T , int SizeMin> DynamicList (const label len) inline explicit
Definition at line 139 of file DynamicListI.H.
DynamicList() [3/15]
template<class T , int SizeMin> DynamicList (const label len, const T & val) inline
Definition at line 149 of file DynamicListI.H.
DynamicList() [4/15]
template<class T , int SizeMin> DynamicList (const label len, const Foam::zero) inline
Definition at line 161 of file DynamicListI.H.
DynamicList() [5/15]
template<class T , int SizeMin> DynamicList (const DynamicList< T, SizeMin > & lst) inline
Definition at line 173 of file DynamicListI.H.
DynamicList() [6/15]
template<class T , int SizeMin> template<int AnySizeMin> DynamicList (const DynamicList< T, AnySizeMin > & lst) inline
Definition at line 185 of file DynamicListI.H.
DynamicList() [7/15]
template<class T , int SizeMin> DynamicList (const UList< T > & lst) inline explicit
Definition at line 196 of file DynamicListI.H.
DynamicList() [8/15]
template<class T , int SizeMin> DynamicList (const UList< T > & list, const labelUList & indices) inline
Definition at line 207 of file DynamicListI.H.
DynamicList() [9/15]
template<class T , int SizeMin> template<unsigned N> DynamicList (const FixedList< T, N > & lst) inline explicit
Definition at line 220 of file DynamicListI.H.
DynamicList() [10/15]
template<class T , int SizeMin> DynamicList (std::initializer_list< T > lst) inline explicit
Definition at line 231 of file DynamicListI.H.
DynamicList() [11/15]
template<class T , int SizeMin> template<class Addr > DynamicList (const IndirectListBase< T, Addr > & lst) inline explicit
Definition at line 243 of file DynamicListI.H.
DynamicList() [12/15]
template<class T , int SizeMin> DynamicList (DynamicList< T, SizeMin > && lst) inline
Definition at line 254 of file DynamicListI.H.
DynamicList() [13/15]
template<class T , int SizeMin> template<int AnySizeMin> DynamicList (DynamicList< T, AnySizeMin > && lst) inline
Definition at line 267 of file DynamicListI.H.
DynamicList() [14/15]
template<class T , int SizeMin> DynamicList (List< T > && lst) inline
Definition at line 279 of file DynamicListI.H.
DynamicList() [15/15]
template<class T , int SizeMin> DynamicList (Istream & is) explicit
Definition at line 30 of file DynamicListIO.C.
References DynamicList< T, SizeMin >::readList().
Member Function Documentation
min_size()
template<class T , int SizeMin = 16> static constexpr label min_size () inline static constexpr noexcept
Definition at line 164 of file DynamicList.H.
capacity()
template<class T , int SizeMin = 16> label capacity () const inline noexcept
Definition at line 167 of file DynamicList.H.
capacity_bytes()
template<class T , int SizeMin> std::streamsize capacity_bytes () const inline noexcept
Definition at line 293 of file DynamicListI.H.
setCapacity()
template<class T , int SizeMin> void setCapacity (const label len) inline
Definition at line 300 of file DynamicListI.H.
Referenced by fileMonitorWatcher::fileMonitorWatcher(), and Pstream::Pstream().
setCapacity_nocopy()
template<class T , int SizeMin> void setCapacity_nocopy (const label len) inline
Definition at line 310 of file DynamicListI.H.
setCapacity_unsafe()
template<class T , int SizeMin> void setCapacity_unsafe (const label len) inline noexcept
Definition at line 320 of file DynamicListI.H.
reserve()
template<class T , int SizeMin> void reserve (const label len) inline
Definition at line 330 of file DynamicListI.H.
reserve_nocopy()
template<class T , int SizeMin> void reserve_nocopy (const label len) inline
Definition at line 340 of file DynamicListI.H.
resize() [1/2]
template<class T , int SizeMin> void resize (const label len) inline
Definition at line 350 of file DynamicListI.H.
Referenced by DynamicList< T, SizeMin >::setSize(), and DynamicList< T, SizeMin >::setSize().
resize() [2/2]
template<class T , int SizeMin> void resize (const label len, const T & val) inline
Definition at line 370 of file DynamicListI.H.
References resize(), and UList< T >::size().
resize_nocopy()
template<class T , int SizeMin> void resize_nocopy (const label len) inline
Definition at line 360 of file DynamicListI.H.
setSize() [1/2]
template<class T , int SizeMin = 16> void setSize (const label n) inline
Definition at line 220 of file DynamicList.H.
References DynamicList< T, SizeMin >::resize().
setSize() [2/2]
template<class T , int SizeMin = 16> void setSize (const label n, const T & val) inline
Definition at line 223 of file DynamicList.H.
References DynamicList< T, SizeMin >::resize().
clear()
template<class T , int SizeMin> void clear () inline noexcept
Definition at line 389 of file DynamicListI.H.
References UList< T >::setAddressableSize().
Referenced by obstacleGrouping::clear(), ABAQUSCore::readHelper::clear(), foamVtkMeshMaps::clear(), and OTstream::rewind().
clearStorage()
template<class T , int SizeMin> void clearStorage () inline
Definition at line 396 of file DynamicListI.H.
References List< T >::clear().
expandStorage()
template<class T , int SizeMin> Foam::label expandStorage () inline noexcept
Definition at line 404 of file DynamicListI.H.
References UList< T >::setAddressableSize(), and UList< T >::size().
shrinkStorage()
template<class T , int SizeMin> void shrinkStorage () inline
Definition at line 416 of file DynamicListI.H.
References List< T >::resize(), UList< T >::setAddressableSize(), and UList< T >::size().
shrink()
template<class T , int SizeMin> Foam::DynamicList< T, SizeMin > & shrink () inline
Definition at line 432 of file DynamicListI.H.
Referenced by walkPatch::walkPatch().
swap()
template<class T , int SizeMin> template<int AnySizeMin> void swap (DynamicList< T, AnySizeMin > & other) inline
Definition at line 441 of file DynamicListI.H.
References UList< T >::swap().
transfer() [1/2]
template<class T , int SizeMin> void transfer (List< T > & list) inline
Definition at line 465 of file DynamicListI.H.
References UPtrList< T >::size(), and List< T >::transfer().
transfer() [2/2]
template<class T , int SizeMin> template<int AnySizeMin> void transfer (DynamicList< T, AnySizeMin > & list) inline
Definition at line 476 of file DynamicListI.H.
References List< T >::transfer().
emplace_back()
template<class T , int SizeMin> template<class... Args> T & emplace_back (Args &&... args) inline
Definition at line 501 of file DynamicListI.H.
References args, resize(), UList< T >::size(), and T.
push_back() [1/8]
template<class T , int SizeMin> void push_back (const T & val) inline
Definition at line 517 of file DynamicListI.H.
References resize(), and UList< T >::size().
Referenced by DynamicList< T, SizeMin >::append(), DynamicList< T, SizeMin >::append(), DynamicList< T, SizeMin >::append(), DynamicList< T, SizeMin >::append(), DynamicList< T, SizeMin >::append(), DynamicList< T, SizeMin >::append(), DynamicList< T, SizeMin >::append(), and DynamicList< T, SizeMin >::append().
push_back() [2/8]
template<class T , int SizeMin> void push_back (T && val) inline
Definition at line 530 of file DynamicListI.H.
References resize(), and UList< T >::size().
push_back() [3/8]
template<class T , int SizeMin> void push_back (const UList< T > & list) inline
Definition at line 543 of file DynamicListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, resize(), UList< T >::size(), UPtrList< T >::size(), and T.
push_back() [4/8]
template<class T , int SizeMin> template<unsigned N> void push_back (const FixedList< T, N > & list) inline
Definition at line 567 of file DynamicListI.H.
References resize(), UList< T >::size(), UPtrList< T >::size(), and T.
push_back() [5/8]
template<class T , int SizeMin> void push_back (std::initializer_list< T > list) inline
Definition at line 583 of file DynamicListI.H.
References resize(), UList< T >::size(), UPtrList< T >::size(), and T.
push_back() [6/8]
template<class T , int SizeMin> template<class Addr > void push_back (const IndirectListBase< T, Addr > & lst) inline
Definition at line 600 of file DynamicListI.H.
References n, resize(), UList< T >::size(), and UPtrList< T >::size().
push_back() [7/8]
template<class T , int SizeMin> void push_back (List< T > && list) inline
Definition at line 618 of file DynamicListI.H.
References Foam::abort(), PtrList< T >::clear(), Foam::FatalError, FatalErrorInFunction, resize(), UList< T >::size(), UPtrList< T >::size(), Foam::Swap(), and T.
push_back() [8/8]
template<class T , int SizeMin> template<int AnySizeMin> void push_back (DynamicList< T, AnySizeMin > && list) inline
Definition at line 644 of file DynamicListI.H.
push_uniq()
template<class T , int SizeMin> Foam::label push_uniq (const T & val) inline
Definition at line 655 of file DynamicListI.H.
Referenced by DynamicList< T, SizeMin >::appendUniq().
pop_back()
template<class T , int SizeMin> void pop_back (label n = 1) inline
Definition at line 670 of file DynamicListI.H.
References clear(), n, and resize().
remove() [1/4]
template<class T , int SizeMin> T remove () inline
Definition at line 684 of file DynamicListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, UList< T >::operator[](), UList< T >::setAddressableSize(), UList< T >::size(), and T.
remove() [2/4]
template<class T , int SizeMin> T remove (const label idx, const bool fast = false) inline
Definition at line 704 of file DynamicListI.H.
remove() [3/4]
template<class T , int SizeMin> Foam::label remove (const labelRange & range) inline
Definition at line 727 of file DynamicListI.H.
References range.
remove() [4/4]
template<class T , int SizeMin> Foam::label remove (std::initializer_list< label > start_size) inline
Definition at line 737 of file DynamicListI.H.
subset() [1/2]
template<class T , int SizeMin> Foam::label subset (const labelRange & range) inline
Definition at line 747 of file DynamicListI.H.
References range.
subset() [2/2]
template<class T , int SizeMin> Foam::label subset (std::initializer_list< label > start_size) inline
Definition at line 757 of file DynamicListI.H.
operator()()
template<class T , int SizeMin> T & operator() (const label i) inline
Definition at line 769 of file DynamicListI.H.
References resize().
operator=() [1/11]
template<class T , int SizeMin> void operator= (const T & val) inline
Definition at line 784 of file DynamicListI.H.
References UList< T >::operator=().
operator=() [2/11]
template<class T , int SizeMin> void operator= (const Foam::zero) inline
Definition at line 794 of file DynamicListI.H.
References UList< T >::operator=(), and Foam::Zero.
operator=() [3/11]
template<class T , int SizeMin> void operator= (const UList< T > & lst) inline
Definition at line 804 of file DynamicListI.H.
operator=() [4/11]
template<class T , int SizeMin> template<unsigned N> void operator= (const FixedList< T, N > & lst) inline
Definition at line 815 of file DynamicListI.H.
operator=() [5/11]
template<class T , int SizeMin> void operator= (const DynamicList< T, SizeMin > & lst) inline
Definition at line 825 of file DynamicListI.H.
operator=() [6/11]
template<class T , int SizeMin> template<int AnySizeMin> void operator= (const DynamicList< T, AnySizeMin > & lst) inline
Definition at line 841 of file DynamicListI.H.
operator=() [7/11]
template<class T , int SizeMin> void operator= (std::initializer_list< T > lst) inline
Definition at line 860 of file DynamicListI.H.
operator=() [8/11]
template<class T , int SizeMin> template<class Addr > void operator= (const IndirectListBase< T, Addr > & lst) inline
if (static_cast<const UList<T>*>(this) == static_cast<const UList<T>*>(&list.values()))
Definition at line 871 of file DynamicListI.H.
operator=() [9/11]
template<class T , int SizeMin> void operator= (List< T > && lst) inline
Definition at line 888 of file DynamicListI.H.
References clear().
operator=() [10/11]
template<class T , int SizeMin> void operator= (DynamicList< T, SizeMin > && lst) inline
Definition at line 899 of file DynamicListI.H.
References clear().
operator=() [11/11]
template<class T , int SizeMin> template<int AnySizeMin> void operator= (DynamicList< T, AnySizeMin > && lst) inline
Definition at line 916 of file DynamicListI.H.
References clear().
readList()
template<class T , int SizeMin> Foam::Istream & readList (Istream & is)
Definition at line 42 of file DynamicListIO.C.
References UPtrList< T >::size().
Referenced by DynamicList< T, SizeMin >::DynamicList().
append() [1/8]
template<class T , int SizeMin = 16> void append (const T & val) inline
Definition at line 399 of file DynamicList.H.
References DynamicList< T, SizeMin >::push_back().
Referenced by STLAsciiParse::beginSolid(), distributedDILUPreconditioner::distributedDILUPreconditioner(), wallBoundedStreamLineParticle::interpolateFields(), and listOp< N >::result::operator+().
append() [2/8]
template<class T , int SizeMin = 16> void append (T && val) inline
Definition at line 403 of file DynamicList.H.
References DynamicList< T, SizeMin >::push_back().
append() [3/8]
template<class T , int SizeMin = 16> void append (const UList< T > & list) inline
Definition at line 406 of file DynamicList.H.
References DynamicList< T, SizeMin >::push_back().
append() [4/8]
template<class T , int SizeMin = 16> template<unsigned N> void append (const FixedList< T, N > & list) inline
Definition at line 411 of file DynamicList.H.
References DynamicList< T, SizeMin >::push_back().
append() [5/8]
template<class T , int SizeMin = 16> void append (std::initializer_list< T > list) inline
Definition at line 415 of file DynamicList.H.
References DynamicList< T, SizeMin >::push_back().
append() [6/8]
template<class T , int SizeMin = 16> template<class Addr > void append (const IndirectListBase< T, Addr > & list) inline
Definition at line 419 of file DynamicList.H.
References DynamicList< T, SizeMin >::push_back().
append() [7/8]
template<class T , int SizeMin = 16> void append (List< T > && list) inline
Definition at line 426 of file DynamicList.H.
References DynamicList< T, SizeMin >::push_back().
append() [8/8]
template<class T , int SizeMin = 16> template<int AnySizeMin> void append (DynamicList< T, AnySizeMin > && list) inline
Definition at line 430 of file DynamicList.H.
References DynamicList< T, SizeMin >::push_back().
appendUniq()
template<class T , int SizeMin = 16> label appendUniq (const T & val) inline
Definition at line 437 of file DynamicList.H.
References DynamicList< T, SizeMin >::push_uniq().
Friends And Related Symbol Documentation
operator>>
template<class T , int SizeMin = 16> Istream & operator>> (Istream & is, DynamicList< T, SizeMin > & list) friend
Definition at line 447 of file DynamicList.H.
operator
template<class T , int SizeMin = 16> Ostream & operator (Ostream & os, const DynamicList< T, SizeMin > & list) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/DynamicList/DynamicList.H
src/OpenFOAM/containers/Lists/DynamicList/DynamicList.C
src/OpenFOAM/containers/Lists/DynamicList/DynamicListI.H
src/OpenFOAM/containers/Lists/DynamicList/DynamicListIO.C