OpenFOAM: OSstream Class Reference
OSstream Class Reference
Generic output stream using a standard (STL) stream.
#include <OSstream.H>
Public Member Functions
OSstream (const OSstream &)=default
void operator= (const OSstream &)=delete
OSstream (std::ostream &os, const string &streamName, IOstreamOption streamOpt=IOstreamOption())
OSstream (std::ostream &os, const string &streamName, IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
OSstream (std::ostream &os, const string &streamName, IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual const fileName & name () const
virtual const std::ostream & stdStream () const
virtual std::ostream & stdStream ()
virtual ios_base::fmtflags flags () const
virtual ios_base::fmtflags flags (const ios_base::fmtflags f)
void syncState ()
virtual bool write (const token &tok)
virtual Ostream & write (const char c)
virtual Ostream & write (const char *str)
virtual Ostream & write (const word &str)
virtual Ostream & write (const string &str)
virtual Ostream & writeQuoted (const std::string &str, const bool quoted=true)
virtual Ostream & write (const int32_t val)
virtual Ostream & write (const int64_t val)
virtual Ostream & write (const float val)
virtual Ostream & write (const double val)
virtual Ostream & write (const char *data, std::streamsize count)
virtual Ostream & writeRaw (const char *data, std::streamsize count)
virtual bool beginRawWrite (std::streamsize count)
virtual bool endRawWrite ()
virtual void indent ()
virtual void flush ()
virtual void endl ()
virtual char fill () const
virtual char fill (const char fillch)
virtual int width () const
virtual int width (const int w)
virtual int precision () const
virtual int precision (const int p)
virtual void print (Ostream &os) const
Public Member Functions inherited from Ostream
Ostream (const Ostream &)=default
virtual ~Ostream ()=default
Ostream (IOstreamOption streamOpt=IOstreamOption())
Ostream (IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
virtual Ostream & write (const keyType &kw)
unsigned short indentSize () const noexcept
unsigned short indentSize (unsigned short val) noexcept
unsigned short indentLevel () const noexcept
unsigned short indentLevel (unsigned short val) noexcept
void incrIndent () noexcept
void decrIndent ()
virtual Ostream & writeKeyword (const keyType &kw)
virtual Ostream & beginBlock (const keyType &kw)
virtual Ostream & beginBlock ()
virtual Ostream & endBlock ()
virtual Ostream & endEntry ()
template<class T >
Ostream & writeEntry (const keyType &key, const T &value)
template<class T >
Ostream & writeEntryIfDifferent (const word &key, const T &value1, const T &value2)
Ostream & operator() () const
unsigned short & indentLevel () noexcept
unsigned short & indentSize () noexcept
Public Member Functions inherited from IOstream
IOstream (const IOstream &)=default
virtual ~IOstream ()=default
IOstream (IOstreamOption streamOpt=IOstreamOption())
IOstream (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp=IOstreamOption::UNCOMPRESSED)
fileName relativeName () const
virtual bool check (const char *operation) const
bool fatalCheck (const char *operation) const
bool opened () const noexcept
bool closed () const noexcept
bool good () const noexcept
bool eof () const noexcept
bool fail () const noexcept
bool bad () const noexcept
operator bool () const noexcept
bool operator! () const noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void setLabelByteSize (unsigned nbytes) noexcept
void setScalarByteSize (unsigned nbytes) noexcept
template<class T = label>
std::enable_if< std::is_integral< T >::value, bool >::type checkLabelSize () const noexcept
template<class T = scalar>
std::enable_if< std::is_floating_point< T >::value, bool >::type checkScalarSize () const noexcept
label lineNumber () const noexcept
label & lineNumber () noexcept
label lineNumber (const label num) noexcept
void setEof () noexcept
void setFail () noexcept
void setBad ()
ios_base::fmtflags setf (const ios_base::fmtflags f)
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
void unsetf (const ios_base::fmtflags f)
void print (Ostream &os, const int streamState) const
InfoProxy< IOstream > info () const noexcept
Public Member Functions inherited from IOstreamOption
constexpr IOstreamOption (streamFormat fmt=streamFormat::ASCII, compressionType comp=compressionType::UNCOMPRESSED) noexcept
constexpr IOstreamOption (streamFormat fmt, compressionType comp, versionNumber ver) noexcept
constexpr IOstreamOption (streamFormat fmt, versionNumber ver, compressionType comp=compressionType::UNCOMPRESSED) noexcept
IOstreamOption (const IOstreamOption &opt, streamFormat fmt) noexcept
streamFormat format () const noexcept
streamFormat format (const streamFormat fmt) noexcept
streamFormat format (const word &formatName)
compressionType compression () const noexcept
compressionType compression (const compressionType comp) noexcept
compressionType compression (const word &compName)
versionNumber version () const noexcept
versionNumber version (const versionNumber ver) noexcept
versionNumber version (const token &tok)
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0 , OPENED }
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII = 0 , BINARY }
enum compressionType : char { UNCOMPRESSED = 0 , COMPRESSED }
enum appendType : char { NON_APPEND = 0 , APPEND }
enum atomicType : char { NON_ATOMIC = 0 , ATOMIC }
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision () noexcept
static unsigned int defaultPrecision (unsigned int prec) noexcept
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName, const streamFormat deflt=streamFormat::ASCII)
static streamFormat formatEnum (const word &key, const dictionary &dict, const streamFormat deflt=streamFormat::ASCII)
static compressionType compressionEnum (const word &compName, const compressionType deflt=compressionType::UNCOMPRESSED)
static compressionType compressionEnum (const word &key, const dictionary &dict, const compressionType deflt=compressionType::UNCOMPRESSED)
Static Public Attributes inherited from IOstream
static unsigned int precision_
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
static const versionNumber currentVersion
Protected Member Functions inherited from IOstream
void setOpened () noexcept
void setClosed () noexcept
void setState (std::ios_base::iostate state) noexcept
void setGood () noexcept
Protected Attributes inherited from Ostream
unsigned short indentSize_ = 4
unsigned short indentLevel_ = 0
Protected Attributes inherited from IOstream
std::ios_base::iostate ioState_
streamAccess openClosed_
unsigned char sizeofLabel_
unsigned char sizeofScalar_
label lineNumber_
Static Protected Attributes inherited from Ostream
static constexpr const unsigned short entryIndentation_ = 16
Static Protected Attributes inherited from IOstream
static fileName staticName_
Detailed Description
Generic output stream using a standard (STL) stream.
Source files
OSstream.H
OSstreamI.H
OSstream.C
Definition at line 50 of file OSstream.H.
Constructor & Destructor Documentation
OSstream() [1/4]
OSstream (const OSstream &) default
OSstream() [2/4]
OSstream (std::ostream & os, const string & streamName, IOstreamOption streamOpt = IOstreamOption()) inline
Definition at line 26 of file OSstreamI.H.
References IOstream::precision_, IOstream::setGood(), IOstream::setOpened(), and OSstream::syncState().
OSstream() [3/4]
OSstream (std::ostream & os, const string & streamName, IOstreamOption::streamFormat fmt, IOstreamOption::compressionType cmp = IOstreamOption::UNCOMPRESSED) inline
Definition at line 84 of file OSstream.H.
OSstream() [4/4]
OSstream (std::ostream & os, const string & streamName, IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp = IOstreamOption::UNCOMPRESSED) inline
Definition at line 96 of file OSstream.H.
Member Function Documentation
operator=()
void operator= (const OSstream &) delete
name()
virtual const fileName & name () const inline virtual
Reimplemented from IOstream.
Reimplemented in OFstream.
Definition at line 115 of file OSstream.H.
Referenced by collatedFileOperation::appendObject(), basicThermo::basicThermo(), meshObject::clear(), meshObject::clearUpto(), mappedPatchBase::collectSamples(), surfaceFieldValue::filterField(), masterUncollatedFileOperation::findInstance(), meshObject::movePoints(), masterUncollatedFileOperation::read(), masterUncollatedFileOperation::readStream(), voxelMeshSearch::update(), meshObject::updateMesh(), and collatedFileOperation::writeObject().
stdStream() [1/2]
virtual const std::ostream & stdStream () const inline virtual
Reimplemented in OFstream.
Definition at line 121 of file OSstream.H.
stdStream() [2/2]
virtual std::ostream & stdStream () inline virtual
Reimplemented in OFstream.
Definition at line 124 of file OSstream.H.
flags() [1/2]
virtual ios_base::fmtflags flags () const inline virtual
Implements IOstream.
Definition at line 130 of file OSstream.H.
Referenced by objective::write().
flags() [2/2]
virtual ios_base::fmtflags flags (const ios_base::fmtflags f) inline virtual
Implements IOstream.
Definition at line 136 of file OSstream.H.
References f().
syncState()
void syncState () inline
Definition at line 142 of file OSstream.H.
References IOstream::setState().
Referenced by OSstream::OSstream().
write() [1/10]
bool write (const token & tok) virtual
Implements Ostream.
Reimplemented in ensightFile, prefixOSstream, and OBJstream.
Definition at line 29 of file OSstream.C.
References token::BEGIN_BLOCK, token::DIRECTIVE, token::END_BLOCK, token::EXPRESSION, token::FLAG, token::HASH, token::VARIABLE, token::VERBATIM, write(), and OSstream::writeQuoted().
Referenced by prefixOSstream::write(), prefixOSstream::write(), prefixOSstream::write(), prefixOSstream::write(), prefixOSstream::write(), prefixOSstream::write(), prefixOSstream::write(), prefixOSstream::write(), prefixOSstream::write(), prefixOSstream::write(), and threadedCollatedOFstream::~threadedCollatedOFstream().
write() [2/10]
Foam::Ostream & write (const char c) virtual
Implements Ostream.
Reimplemented in OBJstream, prefixOSstream, OBJstream, and ensightFile.
Definition at line 82 of file OSstream.C.
References token::NL.
write() [3/10]
Foam::Ostream & write (const char * str) virtual
Implements Ostream.
Reimplemented in ensightFile, OBJstream, prefixOSstream, and OBJstream.
Definition at line 94 of file OSstream.C.
References Foam::stringOps::count(), and token::NL.
write() [4/10]
Foam::Ostream & write (const word & str) virtual
Implements Ostream.
Reimplemented in ensightFile, OBJstream, OBJstream, and prefixOSstream.
Definition at line 103 of file OSstream.C.
write() [5/10]
Foam::Ostream & write (const string & str) virtual
Implements Ostream.
Reimplemented in ensightFile, OBJstream, OSHA1stream, OBJstream, and prefixOSstream.
Definition at line 170 of file OSstream.C.
References writeQuoted().
writeQuoted()
Foam::Ostream & writeQuoted (const std::string & str, const bool quoted = true) virtual
Implements Ostream.
Reimplemented in OBJstream, and prefixOSstream.
Definition at line 111 of file OSstream.C.
References Foam::stringOps::count(), token::DQUOTE, and token::NL.
Referenced by OSHA1stream::write(), OSstream::write(), and prefixOSstream::writeQuoted().
write() [6/10]
Foam::Ostream & write (const int32_t val) virtual
Implements Ostream.
Reimplemented in ensightFile, prefixOSstream, and OBJstream.
Definition at line 176 of file OSstream.C.
write() [7/10]
Foam::Ostream & write (const int64_t val) virtual
Implements Ostream.
Reimplemented in ensightFile, prefixOSstream, and OBJstream.
Definition at line 184 of file OSstream.C.
write() [8/10]
Foam::Ostream & write (const float val) virtual
Implements Ostream.
Reimplemented in ensightFile, prefixOSstream, and OBJstream.
Definition at line 192 of file OSstream.C.
write() [9/10]
Foam::Ostream & write (const double val) virtual
Implements Ostream.
Reimplemented in ensightFile, prefixOSstream, and OBJstream.
Definition at line 200 of file OSstream.C.
write() [10/10]
Foam::Ostream & write (const char * data, std::streamsize count) virtual
Implements Ostream.
Reimplemented in ensightFile, prefixOSstream, and OBJstream.
Definition at line 208 of file OSstream.C.
writeRaw()
Foam::Ostream & writeRaw (const char * data, std::streamsize count) virtual
Implements Ostream.
Definition at line 241 of file OSstream.C.
Referenced by decomposedBlockData::writeData(), and CircularBuffer< T >::writeList().
beginRawWrite()
bool beginRawWrite (std::streamsize count) virtual
Implements Ostream.
Definition at line 218 of file OSstream.C.
References Foam::abort(), token::BEGIN_LIST, Foam::FatalIOError, FatalIOErrorInFunction, and format().
Referenced by CircularBuffer< T >::writeList().
endRawWrite()
bool endRawWrite () virtual
Implements Ostream.
Definition at line 233 of file OSstream.C.
References token::END_LIST.
Referenced by CircularBuffer< T >::writeList().
indent()
void indent () virtual
Implements Ostream.
Reimplemented in prefixOSstream.
Definition at line 256 of file OSstream.C.
Referenced by prefixOSstream::indent(), Foam::indent(), Foam::printDOT(), and Foam::writeHeaderEntry().
flush()
void flush () virtual
Implements Ostream.
Definition at line 266 of file OSstream.C.
Referenced by Foam::flush().
endl()
void endl () virtual
Implements Ostream.
Definition at line 272 of file OSstream.C.
References write().
Referenced by Foam::endl().
fill() [1/2]
char fill () const virtual
Implements Ostream.
Definition at line 281 of file OSstream.C.
fill() [2/2]
char fill (const char fillch) virtual
Implements Ostream.
Definition at line 287 of file OSstream.C.
width() [1/2]
int width () const virtual
Implements Ostream.
Definition at line 293 of file OSstream.C.
Referenced by snappyVoxelMeshDriver::snappyVoxelMeshDriver().
width() [2/2]
int width (const int w) virtual
Implements Ostream.
Definition at line 299 of file OSstream.C.
precision() [1/2]
int precision () const virtual
Implements Ostream.
Definition at line 305 of file OSstream.C.
Referenced by Foam::entryToString(), GAMGAgglomeration::printLevels(), Time::readDict(), ITstream::toString(), dimensionSet::write(), and PDRblock::writeBlockMeshDict().
precision() [2/2]
int precision (const int p) virtual
Implements Ostream.
Definition at line 311 of file OSstream.C.
References p.
print()
void print (Ostream & os) const virtual
Reimplemented from IOstream.
Reimplemented in OFstream, OCountStream, OListStream, UOListStream, prefixOSstream, and OStringStream.
Definition at line 39 of file SstreamsPrint.C.
References Foam::name(), os(), and IOstream::print().
Referenced by OFstream::print(), prefixOSstream::print(), and OStringStream::print().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Sstreams/OSstream.H
src/OpenFOAM/db/IOstreams/Sstreams/OSstream.C
src/OpenFOAM/db/IOstreams/Sstreams/OSstreamI.H
src/OpenFOAM/db/IOstreams/Sstreams/SstreamsPrint.C