OpenFOAM: filmTurbulenceModel Class Reference
filmTurbulenceModel Class Reference abstract
Base class for film turbulence models.
#include <filmTurbulenceModel.H>
Public Types
enum frictionMethodType { mquadraticProfile , mlinearProfile , mDarcyWeisbach , mManningStrickler }
enum shearMethodType { msimple , mwallFunction }
Public Member Functions
TypeName ("filmTurbulenceModel")
declareRunTimeSelectionTable (autoPtr, filmTurbulenceModel, dictionary,(liquidFilmBase &film, const dictionary &dict),(film, dict))
filmTurbulenceModel (const word &modelType, liquidFilmBase &film, const dictionary &dict)
virtual ~filmTurbulenceModel ()=default
const liquidFilmBase & film () const
tmp< volSymmTensorField > devRhoReff () const
tmp< faVectorMatrix > primaryRegionFriction (areaVectorField &U) const
tmp< volScalarField > rho () const
virtual tmp< areaScalarField > Cw () const
virtual tmp< areaScalarField > mut () const =0
virtual void correct ()=0
virtual tmp< faVectorMatrix > Su (areaVectorField &U) const =0
Static Public Member Functions
static autoPtr< filmTurbulenceModel > New (liquidFilmBase &film, const dictionary &dict)
Protected Attributes
const liquidFilmBase & film_
const dictionary dict_
const frictionMethodType method_
const shearMethodType shearMethod_
word rhoName_
scalar rhoRef_
Static Protected Attributes
static const Enum< frictionMethodType > frictionMethodTypeNames_
static const Enum< shearMethodType > shearMethodTypeNames_
Detailed Description
Base class for film turbulence models.
Source files
filmTurbulenceModel.H
filmTurbulenceModel.C
filmTurbulenceModelNew.C
Definition at line 56 of file filmTurbulenceModel.H.
Member Enumeration Documentation
frictionMethodType
enum frictionMethodType
Enumerator
mquadraticProfile
mlinearProfile
mDarcyWeisbach
mManningStrickler
Definition at line 72 of file filmTurbulenceModel.H.
shearMethodType
enum shearMethodType
Enumerator
msimple
mwallFunction
Definition at line 81 of file filmTurbulenceModel.H.
Constructor & Destructor Documentation
filmTurbulenceModel()
filmTurbulenceModel (const word & modelType, liquidFilmBase & film, const dictionary & dict)
Definition at line 67 of file filmTurbulenceModel.C.
References filmTurbulenceModel::dict_, UPtrList< T >::get(), filmTurbulenceModel::rhoName_, and filmTurbulenceModel::rhoRef_.
~filmTurbulenceModel()
virtual ~filmTurbulenceModel () virtual default
Member Function Documentation
TypeName()
TypeName ("filmTurbulenceModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , filmTurbulenceModel , dictionary , (liquidFilmBase &film, const dictionary &dict) , (film, dict))
New()
autoPtr< filmTurbulenceModel > New (liquidFilmBase & film, const dictionary & dict) static
Definition at line 34 of file filmTurbulenceModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
film()
const liquidFilmBase & film () const
Definition at line 90 of file filmTurbulenceModel.C.
References filmTurbulenceModel::film_.
Referenced by laminar::mut().
devRhoReff()
tmp< Foam::volSymmTensorField > devRhoReff () const
Definition at line 296 of file filmTurbulenceModel.C.
References Foam::devTwoSymm(), basicThermo::dictName, Foam::dimViscosity, Foam::exit(), Foam::FatalError, FatalErrorInFunction, filmTurbulenceModel::film_, objectRegistry::foundObject(), Foam::fvc::grad(), objectRegistry::lookupObject(), nu, GeometricField< symmTensor, fvPatchField, volMesh >::null(), filmTurbulenceModel::rho(), transportProperties(), turb, and U.
Referenced by filmTurbulenceModel::primaryRegionFriction().
primaryRegionFriction()
tmp< faVectorMatrix > primaryRegionFriction (areaVectorField & U) const
Definition at line 186 of file filmTurbulenceModel.C.
References filmTurbulenceModel::devRhoReff(), filmTurbulenceModel::dict_, Foam::dimLength, Foam::dimVelocity, filmTurbulenceModel::film_, UPtrList< T >::first(), forAll, UPtrList< T >::get(), filmTurbulenceModel::msimple, filmTurbulenceModel::mwallFunction, tmp< T >::New(), patchIds, PtrList< T >::set(), filmTurbulenceModel::shearMethod_, UPtrList< T >::size(), UList< T >::size(), Foam::fam::Sp(), Foam::sqr(), U, and Foam::Zero.
Referenced by laminar::Su().
rho()
tmp< Foam::volScalarField > rho () const
Definition at line 353 of file filmTurbulenceModel.C.
References Foam::dimDensity, filmTurbulenceModel::film_, objectRegistry::lookupObject(), tmp< T >::New(), filmTurbulenceModel::rhoName_, filmTurbulenceModel::rhoRef_, and fvMesh::time().
Referenced by filmTurbulenceModel::Cw(), and filmTurbulenceModel::devRhoReff().
Cw()
tmp< areaScalarField > Cw () const virtual
Definition at line 96 of file filmTurbulenceModel.C.
References Foam::cbrt(), filmTurbulenceModel::Cw(), filmTurbulenceModel::dict_, Foam::dimVelocity, Foam::exit(), Foam::FatalError, FatalErrorInFunction, filmTurbulenceModel::film_, Foam::flatOutput(), filmTurbulenceModel::frictionMethodTypeNames_, g, UPtrList< T >::get(), h, h0, Foam::mag(), filmTurbulenceModel::mDarcyWeisbach, filmTurbulenceModel::method_, filmTurbulenceModel::mlinearProfile, filmTurbulenceModel::mManningStrickler, filmTurbulenceModel::mquadraticProfile, mu, n, tmp< T >::New(), gravity::New(), Foam::nl, filmTurbulenceModel::rho(), Foam::sqr(), and Uf.
Referenced by filmTurbulenceModel::Cw(), and laminar::wallFriction().
mut()
virtual tmp< areaScalarField > mut () const pure virtual
Implemented in laminar.
correct()
virtual void correct () pure virtual
Implemented in laminar.
Su()
virtual tmp< faVectorMatrix > Su (areaVectorField & U) const pure virtual
Implemented in laminar.
Member Data Documentation
film_
const liquidFilmBase& film_ protected
Definition at line 93 of file filmTurbulenceModel.H.
Referenced by filmTurbulenceModel::Cw(), filmTurbulenceModel::devRhoReff(), filmTurbulenceModel::film(), filmTurbulenceModel::primaryRegionFriction(), filmTurbulenceModel::rho(), and laminar::wallFriction().
frictionMethodTypeNames_
const Enum< filmTurbulenceModel::frictionMethodType > frictionMethodTypeNames_ static protected
Initial value:
{
    { frictionMethodType::mquadraticProfile, "quadraticProfile" },
    { frictionMethodType::mlinearProfile, "linearProfile" },
    { frictionMethodType::mDarcyWeisbach, "DarcyWeisbach" },
    { frictionMethodType::mManningStrickler, "ManningStrickler" }
}
Definition at line 96 of file filmTurbulenceModel.H.
Referenced by filmTurbulenceModel::Cw().
shearMethodTypeNames_
const Enum< filmTurbulenceModel::shearMethodType > shearMethodTypeNames_ static protected
Initial value:
{
    { shearMethodType::msimple, "simple" },
    { shearMethodType::mwallFunction, "wallFunction" }
}
Definition at line 99 of file filmTurbulenceModel.H.
dict_
const dictionary dict_ protected
Definition at line 102 of file filmTurbulenceModel.H.
Referenced by filmTurbulenceModel::Cw(), filmTurbulenceModel::filmTurbulenceModel(), and filmTurbulenceModel::primaryRegionFriction().
method_
const frictionMethodType method_ protected
Definition at line 105 of file filmTurbulenceModel.H.
Referenced by filmTurbulenceModel::Cw().
shearMethod_
const shearMethodType shearMethod_ protected
Definition at line 108 of file filmTurbulenceModel.H.
Referenced by filmTurbulenceModel::primaryRegionFriction().
rhoName_
word rhoName_ protected
Definition at line 111 of file filmTurbulenceModel.H.
Referenced by filmTurbulenceModel::filmTurbulenceModel(), and filmTurbulenceModel::rho().
rhoRef_
scalar rhoRef_ protected
Definition at line 114 of file filmTurbulenceModel.H.
Referenced by filmTurbulenceModel::filmTurbulenceModel(), and filmTurbulenceModel::rho().
The documentation for this class was generated from the following files:
src/regionFaModels/liquidFilm/subModels/kinematic/filmTurbulenceModel/filmTurbulenceModel/filmTurbulenceModel.H
src/regionFaModels/liquidFilm/subModels/kinematic/filmTurbulenceModel/filmTurbulenceModel/filmTurbulenceModel.C
src/regionFaModels/liquidFilm/subModels/kinematic/filmTurbulenceModel/filmTurbulenceModel/filmTurbulenceModelNew.C