OpenFOAM: UPtrList< T > Class Template Reference
UPtrList< T > Class Template Reference
A list of pointers to objects of type <T>, without allocation/deallocation management of the pointers - this is to be done elsewhere. The operator[] returns a reference to the object (not the pointer).
#include <UPtrList.H>
Inherited by PtrList< CloudFunctionObject< CloudType > >, PtrList< Field< Type > >, PtrList< PatchField< Type > >, PtrList< InjectionModel< CloudType > >, PtrList< fvPatchField< symmTensor > >, PtrList< fvPatchField< scalar > >, PtrList< MRFZone >, PtrList< pointPatchField< Type > >, PtrList< ParticleForce< CloudType > >, PtrList< joint >, PtrList< ZoneType >, PtrList< block >, PtrList< coalCloud >, PtrList< coordinateSystem >, PtrList< fa::option >, PtrList< entry >, PtrList< faPatchMapper >, PtrList< functionObject >, PtrList< fv::option >, PtrList< fvPatchMapper >, PtrList< pairPotential >, PtrList< pointPatchMapper >, PtrList< polyMeshModifier >, PtrList< porosityModel >, PtrList< profileModel >, PtrList< Reaction< ThermoType > >, PtrList< extendedFeatureEdgeMesh >, PtrList< force >, PtrList< injectionModel >, PtrList< pyrolysisModel >, PtrList< regionModelFunctionObject >, PtrList< transferModel >, PtrList< sampledSet >, PtrList< sampledSurface >, PtrList< searchableSurface >, PtrList< tetherPotential >, PtrList< fvPatchField< vector > >, PtrList< fvPatchField< tensor > >, PtrList< Foam::GeometricField >, PtrList< Foam::fvPatchField< scalar > >, PtrList< Foam::fvPatchField< Foam::Vector > >, PtrList< Foam::pointPatchField< Foam::Vector > >, PtrList< Field< Foam::Vector > >, PtrList< Field< scalar > >, PtrList< Foam::OFstream >, PtrList< Foam::Field >, PtrList< Foam::List >, PtrList< Foam::lduPrimitiveMesh >, PtrList< Foam::lduMatrix >, PtrList< Foam::PtrList< Foam::lduInterfaceField > >, PtrList< Foam::lduInterfaceField >, PtrList< Foam::UPtrList >, PtrList< Foam::FieldField< Foam::Field, scalar > >, PtrList< Foam::Field< scalar > >, PtrList< Foam::distributionModels::general >, PtrList< ParticleForce< KinematicCloud< Foam::DSMCCloud > > >, PtrList< CloudFunctionObject< KinematicCloud< Foam::DSMCCloud > > >, PtrList< InjectionModel< Foam::KinematicCloud< Foam::DSMCCloud > > >, PtrList< ParticleForce< KinematicCloud< CloudType > > >, PtrList< CloudFunctionObject< KinematicCloud< CloudType > > >, PtrList< Foam::Field< LUType > >, PtrList< fvsPatchField< scalar > >, PtrList< Foam::PatchInteractionModel< Foam::DSMCCloud > >, PtrList< Foam::List< char > >, PtrList< boundaryEntry >, PtrList< Foam::diameterModels::populationBalanceModel >, PtrList< Foam::RBD::rigidBody >, PtrList< Foam::RBD::subBody >, PtrList< Foam::RBD::joint >, PtrList< Foam::RBD::restraint >, PtrList< Foam::DimensionedField >, PtrList< Foam::patchInjectionBase >, PtrList< Foam::Reaction< ThermoType > >, PtrList< ThermoType >, PtrList< Foam::adjointSolver >, PtrList< Foam::Function1< scalar > >, PtrList< blockVertex >, PtrList< blockEdge >, PtrList< blockFace >, PtrList< Foam::entry >, PtrList< Foam::boundaryPatch >, PtrList< Foam::fvMeshSubset >, PtrList< Foam::cellModel >, PtrList< Foam::cellSizeAndAlignmentControl >, PtrList< pointPatchField< scalar > >, PtrList< Foam::extendedFeatureEdgeMesh >, PtrList< Foam::surfaceZonesInfo >, PtrList< Foam::dictionary >, PtrList< Foam::Field< label > >, PtrList< Foam::Field< Foam::Vector > >, PtrList< Foam::Field< Foam::SphericalTensor > >, PtrList< Foam::Field< Foam::SymmTensor > >, PtrList< Foam::Field< Foam::Tensor > >, PtrList< Foam::Function1< Type > >, PtrList< Foam::topoSetFaceSource >, PtrList< Foam::decompositionConstraint >, PtrList< Foam::diameterModels::IATEsource >, PtrList< Foam::PtrList< Foam::dimensioned > >, PtrList< Foam::dimensioned >, PtrList< Foam::diameterModels::coalescenceModel >, PtrList< Foam::diameterModels::breakupModel >, PtrList< Foam::diameterModels::binaryBreakupModel >, PtrList< Foam::diameterModels::driftModel >, PtrList< Foam::diameterModels::nucleationModel >, PtrList< Foam::diameterModels::sizeGroup >, PtrList< pointPatchField< vector > >, PtrList< Foam::Field< solveScalar > >, PtrList< Foam::FieldField< Foam::Field, solveScalar > >, PtrList< Foam::motionSolver >, PtrList< Foam::indexedOctree< Foam::treeDataEdge > >, PtrList< temperatureCoupling >, PtrList< Foam::PatchFunction1Types::MappedFile< scalar > >, PtrList< faPatchField< scalar > >, PtrList< Foam::faFieldDecomposer::patchFieldDecomposer >, PtrList< Foam::faFieldDecomposer::processorAreaPatchFieldDecomposer >, PtrList< Foam::faFieldDecomposer::processorEdgePatchFieldDecomposer >, PtrList< Foam::GeometricField< scalar, Foam::faPatchField, Foam::areaMesh > >, PtrList< Foam::faPatchField< scalar > >, PtrList< Foam::GeometricField< scalar, Foam::faePatchField, Foam::edgeMesh > >, PtrList< Foam::faePatchField< scalar > >, PtrList< Foam::GeometricField< Foam::Vector, Foam::faPatchField, Foam::areaMesh > >, PtrList< Foam::faPatchField< Foam::Vector > >, PtrList< Foam::GeometricField< Foam::Vector, Foam::faePatchField, Foam::edgeMesh > >, PtrList< Foam::faePatchField< Foam::Vector > >, PtrList< Foam::GeometricField< Foam::SphericalTensor, Foam::faPatchField, Foam::areaMesh > >, PtrList< Foam::faPatchField< Foam::SphericalTensor > >, PtrList< Foam::GeometricField< Foam::SphericalTensor, Foam::faePatchField, Foam::edgeMesh > >, PtrList< Foam::faePatchField< Foam::SphericalTensor > >, PtrList< Foam::GeometricField< Foam::SymmTensor, Foam::faPatchField, Foam::areaMesh > >, PtrList< Foam::faPatchField< Foam::SymmTensor > >, PtrList< Foam::GeometricField< Foam::SymmTensor, Foam::faePatchField, Foam::edgeMesh > >, PtrList< Foam::faePatchField< Foam::SymmTensor > >, PtrList< Foam::GeometricField< Foam::Tensor, Foam::faPatchField, Foam::areaMesh > >, PtrList< Foam::faPatchField< Foam::Tensor > >, PtrList< Foam::GeometricField< Foam::Tensor, Foam::faePatchField, Foam::edgeMesh > >, PtrList< Foam::faePatchField< Foam::Tensor > >, PtrList< Foam::faMesh >, PtrList< Foam::IOList >, PtrList< Foam::Field< Type > >, PtrList< Foam::mapDistributeBase >, PtrList< Foam::functionObject >, PtrList< ParticleForce< KinematicCloud< Cloud< basicKinematicCollidingParcel > > > >, PtrList< CloudFunctionObject< KinematicCloud< Cloud< basicKinematicCollidingParcel > > > >, PtrList< Foam::functionObjects::runTimeControls::runTimeCondition >, PtrList< Foam::vtk::vtuCells >, PtrList< Foam::fvFieldDecomposer::patchFieldDecomposer >, PtrList< Foam::fvFieldDecomposer::processorVolPatchFieldDecomposer >, PtrList< Foam::fvFieldDecomposer::processorSurfacePatchFieldDecomposer >, PtrList< Foam::DimensionedField< scalar, Foam::volMesh > >, PtrList< Foam::GeometricField< scalar, Foam::fvPatchField, Foam::volMesh > >, PtrList< Foam::GeometricField< scalar, Foam::fvsPatchField, Foam::surfaceMesh > >, PtrList< Foam::fvsPatchField< scalar > >, PtrList< Foam::DimensionedField< Foam::Vector, Foam::volMesh > >, PtrList< Foam::GeometricField< Foam::Vector, Foam::fvPatchField, Foam::volMesh > >, PtrList< Foam::GeometricField< Foam::Vector, Foam::fvsPatchField, Foam::surfaceMesh > >, PtrList< Foam::fvsPatchField< Foam::Vector > >, PtrList< Foam::DimensionedField< Foam::SphericalTensor, Foam::volMesh > >, PtrList< Foam::GeometricField< Foam::SphericalTensor, Foam::fvPatchField, Foam::volMesh > >, PtrList< Foam::fvPatchField< Foam::SphericalTensor > >, PtrList< Foam::GeometricField< Foam::SphericalTensor, Foam::fvsPatchField, Foam::surfaceMesh > >, PtrList< Foam::fvsPatchField< Foam::SphericalTensor > >, PtrList< Foam::DimensionedField< Foam::SymmTensor, Foam::volMesh > >, PtrList< Foam::GeometricField< Foam::SymmTensor, Foam::fvPatchField, Foam::volMesh > >, PtrList< Foam::fvPatchField< Foam::SymmTensor > >, PtrList< Foam::GeometricField< Foam::SymmTensor, Foam::fvsPatchField, Foam::surfaceMesh > >, PtrList< Foam::fvsPatchField< Foam::SymmTensor > >, PtrList< Foam::DimensionedField< Foam::Tensor, Foam::volMesh > >, PtrList< Foam::GeometricField< Foam::Tensor, Foam::fvPatchField, Foam::volMesh > >, PtrList< Foam::fvPatchField< Foam::Tensor > >, PtrList< Foam::GeometricField< Foam::Tensor, Foam::fvsPatchField, Foam::surfaceMesh > >, PtrList< Foam::fvsPatchField< Foam::Tensor > >, PtrList< Foam::fvMesh >, PtrList< Foam::fvMatrix< Type > >, PtrList< Foam::ignitionSite >, PtrList< Foam::implicitFunction >, PtrList< Foam::adjointSolverManager >, PtrList< Foam::incompressible::adjointSensitivity >, PtrList< Foam::fvPatchField< Type > >, PtrList< Foam::pointPatchField< Type > >, PtrList< Foam::fvsPatchField< Type > >, PtrList< Foam::PtrList< Foam::IOField< label > > >, PtrList< Foam::IOField< label > >, PtrList< Foam::PtrList< Foam::CompactIOField< Foam::Field< label >, label > > >, PtrList< Foam::CompactIOField< Foam::Field< label >, label > >, PtrList< Foam::PtrList< Foam::IOField< scalar > > >, PtrList< Foam::IOField< scalar > >, PtrList< Foam::PtrList< Foam::CompactIOField< Foam::Field< scalar >, scalar > > >, PtrList< Foam::CompactIOField< Foam::Field< scalar >, scalar > >, PtrList< Foam::PtrList< Foam::IOField< Foam::Vector > > >, PtrList< Foam::IOField< Foam::Vector > >, PtrList< Foam::PtrList< Foam::CompactIOField< Foam::Field< Foam::Vector >, Foam::Vector > > >, PtrList< Foam::CompactIOField< Foam::Field< Foam::Vector >, Foam::Vector > >, PtrList< Foam::PtrList< Foam::IOField< Foam::SphericalTensor > > >, PtrList< Foam::IOField< Foam::SphericalTensor > >, PtrList< Foam::PtrList< Foam::CompactIOField< Foam::Field< Foam::SphericalTensor >, Foam::SphericalTensor > > >, PtrList< Foam::CompactIOField< Foam::Field< Foam::SphericalTensor >, Foam::SphericalTensor > >, PtrList< Foam::PtrList< Foam::IOField< Foam::SymmTensor > > >, PtrList< Foam::IOField< Foam::SymmTensor > >, PtrList< Foam::PtrList< Foam::CompactIOField< Foam::Field< Foam::SymmTensor >, Foam::SymmTensor > > >, PtrList< Foam::CompactIOField< Foam::Field< Foam::SymmTensor >, Foam::SymmTensor > >, PtrList< Foam::PtrList< Foam::IOField< Foam::Tensor > > >, PtrList< Foam::IOField< Foam::Tensor > >, PtrList< Foam::PtrList< Foam::CompactIOField< Foam::Field< Foam::Tensor >, Foam::Tensor > > >, PtrList< Foam::CompactIOField< Foam::Field< Foam::Tensor >, Foam::Tensor > >, PtrList< const Foam::lduInterface >, PtrList< fvsPatchField< vector > >, PtrList< Foam::liquidProperties >, PtrList< Foam::AMIInterpolation >, PtrList< Foam::decompositionMethod >, PtrList< Foam::solidBodyMotionFunction >, PtrList< Foam::objective >, PtrList< Foam::primalSolver >, PtrList< const Foam::lduPrimitiveProcessorInterface >, PtrList< Foam::PrimitivePatch >, PtrList< phaseModel >, PtrList< Foam::pointFieldDecomposer::patchFieldDecomposer >, PtrList< Foam::GeometricField< scalar, Foam::pointPatchField, Foam::pointMesh > >, PtrList< Foam::pointPatchField< scalar > >, PtrList< Foam::GeometricField< Foam::Vector, Foam::pointPatchField, Foam::pointMesh > >, PtrList< Foam::GeometricField< Foam::SphericalTensor, Foam::pointPatchField, Foam::pointMesh > >, PtrList< Foam::pointPatchField< Foam::SphericalTensor > >, PtrList< Foam::GeometricField< Foam::SymmTensor, Foam::pointPatchField, Foam::pointMesh > >, PtrList< Foam::pointPatchField< Foam::SymmTensor > >, PtrList< Foam::GeometricField< Foam::Tensor, Foam::pointPatchField, Foam::pointMesh > >, PtrList< Foam::pointPatchField< Foam::Tensor > >, PtrList< Foam::pointMesh >, PtrList< Foam::PrimitivePatchInterpolation >, PtrList< pointZone >, PtrList< faceZone >, PtrList< cellZone >, PtrList< Foam::procLduInterface >, PtrList< Foam::Time >, PtrList< Foam::profilingInformation >, PtrList< GasThermo >, PtrList< Foam::radiation::boundaryRadiationPropertiesPatch >, PtrList< Foam::radiation::radiativeIntensityRay >, PtrList< Foam::indexedOctree< Foam::treeDataPoint > >, PtrList< faPatchField< tensor > >, PtrList< faPatchField< vector > >, PtrList< faePatchField< scalar > >, PtrList< Foam::PtrList< Foam::AMIInterpolation > >, PtrList< bodyMesh >, PtrList< Foam::mappedPatchBase >, PtrList< Foam::coordSetWriter >, PtrList< Foam::coordSet >, PtrList< Foam::surfaceWriter >, PtrList< Foam::coordSystem::cartesian >, PtrList< Foam::cellSizeFunction >, PtrList< Foam::sixDoFRigidBodyMotionRestraint >, PtrList< Foam::sixDoFRigidBodyMotionConstraint >, PtrList< Foam::Reaction< SolidThermo > >, PtrList< SolidThermo >, PtrList< Foam::solidProperties >, PtrList< Foam::dimensionSet >, PtrList< Foam::interpolation< scalar > >, PtrList< Foam::interpolation< Foam::Vector > >, PtrList< Foam::triSurfaceMesh >, PtrList< Foam::indexedOctree >, PtrList< Foam::Function1< Foam::Vector > >, PtrList< Foam::Function1< Foam::SymmTensor > >, PtrList< Foam::Function1< TypeR > >, PtrList< Foam::NURBS3DVolume >, and PtrList< T >.
Classes
class const_iterator
struct greater
class Iterator
class iterator
struct less
struct value_compare
Public Types
typedef T value_type
typedef T & reference
typedef const T & const_reference
Public Member Functions
constexpr UPtrList () noexcept
UPtrList (const label len)
UPtrList (const UPtrList< T > &list)
UPtrList (UPtrList< T > &&list)
UPtrList (UPtrList< T > &list, bool reuse)
UPtrList (PtrList< T > &list)
UPtrList (const UList< T * > &list)
UPtrList (UList< T > &list)
bool empty () const noexcept
label size () const noexcept
label count () const noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
const T * test (const label i) const
const T * get (const label i) const
T * get (const label i)
const T * set (const label i) const
void clear ()
void free ()
void resize (const label newLen)
label squeezeNull ()
void trimTrailingNull ()
void push_back (T *ptr)
void push_back (UPtrList< T > &&other)
void swap (UPtrList< T > &list)
void transfer (UPtrList< T > &list)
T * set (const label i, T *ptr)
void reorder (const labelUList &oldToNew, const bool check=false)
void sortOrder (const labelUList &order, const bool check=false)
void checkNonNull () const
const T & at (const label i) const
T & at (const label i)
const T & operator[] (const label i) const
T & operator[] (const label i)
FOAM_DEPRECATED_FOR (2022-09, "get(), set() or test() methods") const T *operator()(const label i) const
void operator= (const UPtrList< T > &list)
void operator= (UPtrList< T > &&list)
T ** begin_ptr () noexcept
T ** end_ptr () noexcept
iterator begin ()
iterator end () noexcept
const_iterator cbegin () const
const_iterator cend () const noexcept
const_iterator begin () const
const_iterator end () const noexcept
void setSize (const label n)
T & first ()
const T & first () const
T & last ()
const T & last () const
void append (T *ptr)
void append (UPtrList< T > &&other)
Protected Member Functions
void setAddressableSize (const label n) noexcept
label find_next (label pos) const
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Protected Attributes
Detail::PtrListDetail< T > ptrs_
Friends
class Iterator< true >
class Iterator< false >
Ostream & operator<< (Ostream &os, const UPtrList< T > &list)
Detailed Description
template<class T>
class Foam::UPtrList< T >
A list of pointers to objects of type <T>, without allocation/deallocation management of the pointers - this is to be done elsewhere. The operator[] returns a reference to the object (not the pointer).
The iterators are similar to bitSet in that they skip nullptr entries, and also return a value (like the list operator[] does).
When traversing lists, it possible to test the validity directly:
forAll(interfaces, i)
{
    if (interfaces.test(i))
    {
        // Interface is set, do something
        const auto& intf = interfaces[i];
        ...
    }
}
The lists can also be traversed with a for-range (in OpenFOAM-v2212 and earlier this would have failed on nullptr entries):
for (const auto& intf : interfaces)
{
    // Do something
    ...
}
It is also possible to traverse with non-null entries and use key/val access (like HashTable naming):
forAllConstIters(interfaces, iter)
{
    Info<< "entry " << iter.key() << " : " << iter.val() << nl;
}
Note
The class definition is such that it contains a list of pointers, but itself does not inherit from a list of pointers since this would wreak havoc later with inheritance resolution.
See also
Foam::PtrList Foam::PtrDynList
Source files
UPtrList.H
UPtrListI.H
UPtrList.C
Definition at line 100 of file UPtrList.H.
Member Typedef Documentation
value_type
template<class T > typedef T value_type
Definition at line 130 of file UPtrList.H.
reference
template<class T > typedef T& reference
Definition at line 133 of file UPtrList.H.
const_reference
template<class T > typedef const T& const_reference
Definition at line 136 of file UPtrList.H.
Constructor & Destructor Documentation
UPtrList() [1/9]
template<class T > UPtrList (Detail::PtrListDetail< T > && ptrs) inline explicit protected
Definition at line 55 of file UPtrListI.H.
UPtrList() [2/9]
template<class T > constexpr UPtrList () inline constexpr noexcept
Definition at line 41 of file UPtrListI.H.
UPtrList() [3/9]
template<class T > UPtrList (const label len) inline explicit
Definition at line 48 of file UPtrListI.H.
UPtrList() [4/9]
template<class T > UPtrList (const UPtrList< T > & list) inline
Definition at line 62 of file UPtrListI.H.
UPtrList() [5/9]
template<class T > UPtrList (UPtrList< T > && list) inline
Definition at line 69 of file UPtrListI.H.
UPtrList() [6/9]
template<class T > UPtrList (UPtrList< T > & list, bool reuse) inline
Definition at line 76 of file UPtrListI.H.
UPtrList() [7/9]
template<class T > UPtrList (PtrList< T > & list) explicit
Definition at line 29 of file UPtrList.C.
UPtrList() [8/9]
template<class T > UPtrList (const UList< T * > & list) inline explicit
Definition at line 83 of file UPtrListI.H.
UPtrList() [9/9]
template<class T > UPtrList (UList< T > & list) inline explicit
Definition at line 90 of file UPtrListI.H.
References UPtrList< T >::ptrs_, and UPtrList< T >::size().
Member Function Documentation
setAddressableSize()
template<class T > void setAddressableSize (const label n) inline protected noexcept
Definition at line 25 of file UPtrListI.H.
References n, and UPtrList< T >::setAddressableSize().
Referenced by PtrDynList< Foam::Field< label > >::pop_back(), UPtrList< T >::setAddressableSize(), PtrDynList< Foam::Field< label > >::transfer(), and UPtrList< T >::trimTrailingNull().
find_next()
template<class T > Foam::label find_next (label pos) const inline protected
Definition at line 32 of file UPtrListI.H.
References UPtrList< T >::find_next(), Foam::pos(), and UPtrList< T >::ptrs_.
Referenced by UPtrList< T >::find_next(), UPtrList< T >::Iterator< Const >::increment(), faceAreaWeightAMI::setNextFaces(), and Foam::ListOps::setValue().
empty()
template<class T > bool empty () const inline noexcept
Definition at line 106 of file UPtrListI.H.
References UPtrList< T >::empty().
Referenced by AABBTree< Type >::AABBTree(), ABAQUSCore::abaqusToFoamFaceAddr(), labelRanges::add(), cyclicAMIPolyPatch::addAMIFaces(), exprResultGlobals::addValue(), exprDriver::addVariables(), singleCellFvMesh::agglomPatchFieldMapper::agglomPatchFieldMapper(), adjointSolverManager::aggregateSensitivities(), dlLibraryTable::append(), directMethod::appendToDirectSeeds(), rigidBodyModel::applyRestraints(), argList::argList(), Foam::meshTools::bandCompression(), dynamicIndexedOctree< Type >::bb(), indexedOctree< Type >::bb(), STLAsciiParse::beginSolid(), Foam::blankElementMasks(), fileOperation::broadcastCopy(), holeToFace::calcClosure(), Foam::calcElementMasks(), fieldExtents::calcFieldExtents(), forces::calcForcesMoments(), createShellMesh::calcPointRegions(), surfaceNoise::calculate(), waveMethod::calculate(), faceAreaWeightAMI::calculate(), faceAreaWeightAMI2D::calculate(), cellVolumeWeightMethod::calculateAddressing(), correctedCellVolumeWeightMethod::calculateAddressing(), cellMapper::cellMapper(), cuttingSurfaceBase::cellSelection(), dictionary::cfindScopedDict(), triSurface::checkEdges(), fvMatrix< Type >::checkImplicit(), argList::checkRootCase(), chemkinReader::chemkinReader(), dlLibraryTable::close(), ofstreamPointer::close(), cellTable::combine(), Foam::combineFormatOptions(), IOstreamOption::compressionEnum(), ConstantRateDevolatilisation< CloudType >::ConstantRateDevolatilisation(), boundBox::contains(), boundBox::containsAny(), Foam::debug::controlDict(), dictionaryContent::copyDict(), dictionaryContent::copyDict(), dynamicCode::copyOrCreateFiles(), ensightMesh::correct(), fvMeshSubsetProxy::correct(), injectionModelList::correct(), decompositionMethod::decompose(), metisLikeDecomp::decomposeGeneral(), directoryIterator::directoryIterator(), argList::displayDoc(), faMeshDistributor::distributeAreaFields(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), distributedWeightedFvPatchFieldMapper::distributedWeightedFvPatchFieldMapper(), faMeshDistributor::distributeEdgeFields(), faMeshDistributor::distributeField(), faMeshBoundaryHalo::distributeSparse(), Foam::dlSymFind(), PatchTools::edgeNormals(), edgeSurface::edgeSurface(), lumpedPointState::empty(), coordSetWriter::empty(), globalIndex::empty(), fvFieldDecomposer::empty(), pointFieldDecomposer::empty(), faFieldDecomposer::empty(), surfaceWriter::empty(), List< Type >::empty(), seriesWriter::empty(), vtuCells::empty(), multiWorldConnections::empty(), dynamicTreeDataPoint::empty(), CircularBuffer< T >::empty(), IndirectListBase< T, Addr >::empty(), UPtrList< T >::empty(), Enum< EnumType >::empty(), wordRes::matcher::empty(), lagrangianFieldDecomposer::fieldsCache::privateCache::empty(), vtmWriter::endBlock(), formatter::endTag(), FilterField::evaluate(), fvExprDriver::evaluateVariableRemote(), Pstream::exchange(), Pstream::exchange(), Foam::PstreamDetail::exchangeBuf(), Foam::PstreamDetail::exchangeConsensus(), Foam::PstreamDetail::exchangeConsensus(), Foam::PstreamDetail::exchangeContainer(), Foam::PstreamDetail::exchangeContainer(), masterUncollatedFileOperation::exists(), fileOperation::exists(), Foam::expandLeading(), string::ext(), Foam::extractValues(), Foam::extractValues(), faAreaMapper::faAreaMapper(), faceMapper::faceMapper(), polyTopoChange::faceRemoved(), fileOperation::fileHandler(), exprDriver::fillFunctionValues(), Foam::filteredName(), regExpCxx::find(), regExpPosix::find(), searchableSurfacesQueries::findAllIntersections(), functionObjectList::findDict(), Foam::findEtcFile(), faBoundaryMesh::findIndex(), polyBoundaryMesh::findIndex(), ZoneMesh< ZoneType, MeshType >::findIndex(), coordinateSystems::findIndex(), fileOperation::findInstance(), masterUncollatedFileOperation::findInstance(), dlLibraryTable::findLibrary(), mapNearestMethod::findMappedSrcCell(), triSurfaceRegionSearch::findNearest(), distributedTriSurfaceMesh::findNearest(), searchableSurfacesQueries::findNearest(), mapNearestMethod::findNearestCell(), refinementFeatures::findNearestEdge(), refinementFeatures::findNearestPoint(), fileOperation::findTimes(), IOstreamOption::formatEnum(), dlLibraryTable::fullname(), fvMeshSubsetter::fvMeshSubset(), globalIndex::gather(), globalIndex::gather(), coordSet::gatherSort(), Foam::getCommPattern(), zoneDistribute::getDatafromOtherProc(), Foam::getEnv(), exprDriver::getFunctionValue(), fileOperation::getGlobalIORanks(), sampledSurface::getRegistrySurface(), FaceCellWave< Type, TrackingData >::handleProcPatches(), string::has_ext(), coordSetWriter::hasCoords(), Foam::hasEnv(), sampledMeshedSurface::hasFaceIds(), IOobject::hasHeaderClass(), lumpedPointMovement::hasMapping(), IFstream::IFstream(), Distribution< Type >::index(), coordinateSystems::indices(), faBoundaryMesh::indices(), polyBoundaryMesh::indices(), ZoneMesh< ZoneType, MeshType >::indices(), faBoundaryMesh::indices(), polyBoundaryMesh::indices(), ZoneMesh< ZoneType, MeshType >::indices(), dynamicMultiMotionSolverFvMesh::init(), expressionEntry::inplaceExpand(), Foam::stringOps::inplaceReplaceVar(), faAreaMapper::insertedObjects(), interfaceDefinitions::interfaceName(), intersectedSurface::intersectedSurface(), fileName::isAbsolute(), fileName::isBackup(), JobInfo::JobInfo(), Reaction< ThermoType >::kf(), UPstream::listScatterValues(), Foam::ln(), triSurfaceLoader::load(), dlLibraryTable::loaded(), fileOperation::lookupAndCacheProcessorsPath(), dictionary::makeScopedDict(), volSurfaceMapping::mapInternalToSurface(), Foam::MapVolFields(), triSurface::markZone(), PatchTools::markZone(), regExpCxx::match(), Foam::max(), Foam::min(), Foam::mkDir(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel(), Foam::mv(), coordinateSystems::names(), faPatchField< Type >::New(), triSurface::New(), MeshedSurface< Face >::New(), UnsortedMeshedSurface< Face >::New(), fvsPatchField< Type >::New(), fvPatchField< Type >::New(), chemistryReductionMethod< CompType, ThermoType >::New(), chemistryTabulationMethod< CompType, ThermoType >::New(), pointPatchField< Type >::New(), fileOperation::New(), fileOperation::New(), LESdelta::New(), faPatchField< Type >::New(), faePatchField< Type >::New(), fvsPatchField< Type >::New(), fvPatchField< Type >::New(), pointPatchField< Type >::New(), masterUncollatedFileOperation::NewIFstream(), fvMeshTools::newMesh(), faMeshTools::newMesh(), Distribution< Type >::normalised(), objectiveManager::objectiveManager(), OFstream::OFstream(), dlLibraryTable::open(), emptyOp< T >::operator()(), Foam::functionObjects::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::functionObjects::operator>>(), outletMappedUniformInletFvPatchField< Type >::outletMappedUniformInletFvPatchField(), dynamicIndexedOctree< Type >::overlaps(), indexedOctree< Type >::overlaps(), dynamicIndexedOctree< Type >::overlaps(), indexedOctree< Type >::overlaps(), argList::parse(), ParticleErosion< CloudType >::ParticleErosion(), patchInteractionDataList::patchInteractionDataList(), polyBoundaryMesh::patchSet(), pimpleControl::pimpleControl(), Foam::MatrixTools::pinv(), plane::plane(), pointMapper::pointMapper(), PatchTools::pointNormals(), polyMesh::polyMesh(), CodedField< Type >::prepare(), CodedFunction1< Type >::prepare(), probes::prepare(), ITstream::print(), argList::printMan(), Foam::printMaps(), Foam::printRange(), Foam::printTable(), processorTopology::procAdjacency(), genericPatchFieldBase::processEntry(), faceAreaWeightAMI::processSourceFace(), Foam::stringOps::quotemeta(), Distribution< Type >::raw(), binModel::read(), areaWrite::read(), ABAQUSsurfaceFormat< Face >::read(), masterUncollatedFileOperation::read(), ABAQUSCore::readHelper::read(), masterUncollatedFileOperation::readAndSend(), Foam::readLagrangian(), fileOperation::readObjects(), masterUncollatedFileOperation::readObjects(), uncollatedFileOperation::readObjects(), boundaryDataSurfaceReader::readPoints(), masterUncollatedFileOperation::readStream(), uncollatedFileOperation::readStream(), faFieldReconstructor::reconstructAreaFields(), faFieldReconstructor::reconstructEdgeFields(), lagrangianReconstructor::reconstructFieldFields(), lagrangianReconstructor::reconstructFields(), fvFieldReconstructor::reconstructInternalFields(), Foam::reconstructLagrangian(), pointFieldReconstructor::reconstructPointFields(), fvFieldReconstructor::reconstructSurfaceFields(), fvFieldReconstructor::reconstructVolumeFields(), Foam::redistributeLagrangian(), DAC< CompType, ThermoType >::reduceMechanism(), DRG< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), cuttingSurfaceBase::remapFaces(), UnsortedMeshedSurface< Face >::remapFaces(), reader::remapMeshInfo(), labelRanges::remove(), edgeIntersections::removeDegenerates(), dynamicIndexedOctree< Type >::removeIndex(), seriesWriter::removeNewer(), boundaryRegion::rename(), fvMeshSubsetProxy::resetZones(), Foam::resolveLabel(), dynamicCode::resolveTemplates(), HashTable< T, Key, Hash >::retain(), mappedPatchBase::sameWorld(), sampledMeshedSurface::sampledMeshedSurface(), motionSmootherAlgo::scaleMesh(), globalIndex::scatter(), IOobject::scopedName(), regExpCxx::search(), regExpPosix::search(), IOobject::selectIO(), Foam::selectPatchFaces(), binModel::setCoordinateSystem(), forces::setCoordinateSystem(), Foam::setEnv(), fvExpressionField::setField(), box::setRefineFlags(), addPatchCellLayer::setRefinement(), masterUncollatedFileOperation::setTime(), zoneDistribute::setUpCommforZone(), simpleControl::simpleControl(), ensightCells::sort(), ensightFaces::sort(), fileOperation::sortTimes(), Foam::stringOps::split(), Foam::stringOps::split(), Foam::stringOps::splitAny(), Foam::stringOps::splitFixed(), sampledSurface::storeRegistrySurface(), exprResultDelayed::storeValue(), fileOperation::subRanks(), topoBitSet::subset(), topoBoolSet::subset(), Foam::subsetSubset(), coordSetWriter::suffix(), coordSetWriter::suffix(), globalMeshData::syncData(), globalMeshData::syncData(), syncTools::syncEdgeMap(), syncTools::syncPointMap(), Foam::system(), Foam::system(), Foam::system(), coordSetWriter::timeValue(), surfaceWriter::timeValue(), dictionary::topDict(), globalIndexAndTransform::transformIndicesForPatches(), treeBoundBox::treeBoundBox(), treeBoundBox::treeBoundBox(), treeBoundBox::treeBoundBox(), triSurfaceMesh::triSurfaceMesh(), triSurfaceMesh::triSurfaceMesh(), fieldEntry::units(), writerCaching::update(), outletMappedUniformInletFvPatchField< Type >::updateCoeffs(), optimisationType::updateGradientsAndValues(), ZoneMesh< ZoneType, MeshType >::updateMetaData(), Foam::expressions::valueTypeCodeOf(), cuttingSurfaceBase::walkCellCuts(), processorColour::walkFront(), walkPatch::walkPatch(), surfaceFieldValue::write(), volFieldValue::write(), dataCloud::write(), vtkCloud::write(), vtkWrite::write(), ABAQUSsurfaceFormat< Face >::write(), NASsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), STARCDsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), X3DsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), VTPsurfaceFormat< Face >::write(), triSurface::write(), MeshedSurface< Face >::write(), MeshedSurfaceProxy< Face >::write(), UnsortedMeshedSurface< Face >::write(), FLMAsurfaceFormat< Face >::write(), Foam::writeAllPointFields(), Foam::writeAllVolFields(), STLsurfaceFormat< Face >::writeAscii(), Foam::writeEntryIfPresent(), decomposedBlockData::writeExtraHeaderContent(), Foam::writeFuncsImpl(), decomposedBlockData::writeHeader(), decomposedBlockData::writeHeader(), IOobject::writeHeaderContent(), IOobject::writeHeaderContent(), CircularBuffer< T >::writeList(), Foam::writeMaps(), ensightOutputSurface::writePointData(), Foam::writePointField(), Foam::ensightOutput::writePointField(), Foam::writePointFields(), writer::writeSolution(), abaqusWriter::writeTemplate(), nastranWriter::writeTemplate(), streamLineBase::writeToFile(), Foam::writeTrackField(), volFieldValue::writeValues(), Foam::ensightOutput::writeVolField(), Foam::writeVolFields(), and Foam::writeVolFields().
size()
template<class T > Foam::label size () const inline noexcept
Definition at line 113 of file UPtrListI.H.
Referenced by AABBTree< Type >::AABBTree(), sensitivitySurface::accumulateIntegrand(), sensitivitySurfacePoints::accumulateIntegrand(), oversetFvMeshBase::active(), isoSurfacePoint::adaptPatchFields(), extendedEdgeMesh::add(), polyMeshAdder::add(), fvMeshAdder::add(), preserveBaffles::add(), singleProcessorFaceSets::add(), boundBox::add(), boundBox::add(), polyMeshAdder::add(), fvMeshAdder::add(), polyMeshAdder::add(), fvMeshPrimitiveLduAddressing::addAddressing(), cyclicAMIPolyPatch::addAMIFaces(), argList::addArgument(), polyTopoChange::addCell(), surfaceZonesInfo::addCellZone(), cellTable::addCellZones(), surfaceZonesInfo::addCellZonesToMesh(), scene::addColourToMesh(), sixDoFRigidBodyMotion::addConstraints(), object::addData(), object::addData(), polyTopoChange::addFace(), surfaceZonesInfo::addFaceZone(), snappyRefineDriver::addFaceZones(), surfaceZonesInfo::addFaceZonesToMesh(), scene::addField(), sensitivitySurface::addGeometricSens(), oversetFvMeshBase::addInterpolation(), edgeSurface::addIntersectionEdges(), snappyLayerDriver::addLayers(), snappyLayerDriver::addLayers(), columnFvMeshInfo::addLocalPatches(), polyTopoChange::addMesh(), scene::addMesh(), ABAQUSCore::readHelper::addNewElset(), boundaryMesh::addPatch(), meshRefinement::addPatch(), fvMeshTools::addPatch(), polyTopoChange::addPoint(), meshRefinement::addPointZone(), sixDoFRigidBodyMotion::addRestraints(), SemiImplicitSource< Type >::addSup(), interRegionExplicitPorositySource::addSup(), interRegionExplicitPorositySource::addSup(), scene::addToAnimation(), faMatrix< Type >::addToInternalField(), fvMatrix< Type >::addToInternalField(), pointPatchField< Type >::addToInternalField(), pointPatchField< Type >::addToInternalField(), polyTopoChanger::addTopologyModifiers(), globalIndexAndTransform::addToTransformIndex(), animation::addTranslation(), unwatchedIOdictionary::addWatch(), regIOobject::addWatch(), fileMonitor::addWatch(), polyMesh::addZones(), adjointSolverManager::adjointSolverManager(), boundaryAdjointContribution::adjointTMVariable1Source(), boundaryAdjointContribution::adjointTMVariable2Source(), oversetFvPatchField< Type >::adjustPsi(), polyMeshTetDecomposition::adjustTetBasePtIs(), primitiveMeshGeometry::affectedCells(), polyMeshGeometry::affectedCells(), eagerGAMGProcAgglomeration::agglomerate(), manualGAMGProcAgglomeration::agglomerate(), masterCoarsestGAMGProcAgglomeration::agglomerate(), procFacesGAMGProcAgglomeration::agglomerate(), AMIInterpolation::agglomerate(), GAMGProcAgglomeration::agglomerate(), MGridGenGAMGAgglomeration::agglomerate(), pairGAMGAgglomeration::agglomerate(), GAMGInterface::agglomerateCoeffs(), GAMGAgglomeration::agglomerateLduAddressing(), adjointSolverManager::aggregateSensitivities(), extendedEdgeMesh::allNearestFeatureEdges(), extendedEdgeMesh::allNearestFeaturePoints(), UPstream::allocateInterHostCommunicator(), UPstream::allocateIntraHostCommunicator(), Foam::PstreamDetail::allToAll(), Foam::PstreamDetail::allToAllConsensus(), Foam::PstreamDetail::allToAllConsensus(), Foam::PstreamDetail::allToAllv(), AMIInterpolation::AMIInterpolation(), LduMatrix< Type, DType, LUType >::Amul(), Matrix< Form, Type >::AmulImpl(), AMIInterpolation::append(), Foam::appendCsvLabels(), meshRefinement::appendPatch(), windowModel::apply(), singleProcessorFaceSets::apply(), Foam::applyPermutation(), setToCellZone::applyToSet(), normalToFace::applyToSet(), cellToFaceZone::applyToSet(), faceZoneToFaceZone::applyToSet(), searchableSurfaceToFaceZone::applyToSet(), setAndNormalToFaceZone::applyToSet(), setsToFaceZone::applyToSet(), setToFaceZone::applyToSet(), setToPointZone::applyToSet(), face::areaInContact(), sensitivitySurface::assembleSensitivities(), sensitivitySurfacePoints::assembleSensitivities(), sensitivityVolBSplines::assembleSensitivities(), assemblyFaceAreaPairGAMGAgglomeration::assemblyFaceAreaPairGAMGAgglomeration(), Field< T >::assign(), Foam::FieldOps::assign(), Foam::FieldOps::assign(), Foam::FieldOps::assign(), Foam::FieldOps::assign(), attachPolyTopoChanger::attach(), fvPatchField< Type >::autoMap(), FreeStream< CloudType >::autoMap(), extendedEdgeMesh::autoMap(), Foam::average(), Foam::average(), Foam::average(), AveragingMethod< Type >::AveragingMethod(), snappySnapDriver::avgCellCentres(), distributedDILUPreconditioner::backwardInternal(), binaryTree< CompType, ThermoType >::balance(), meshRefinement::balance(), meshRefinement::balance(), Foam::meshTools::bandCompression(), vtmWriter::beginBlock(), patchMeshWriter::beginPiece(), binaryTree< CompType, ThermoType >::binaryTreeSearch(), binned::binned(), bitSet::bitSet(), bitSet::bitSet(), bitSet::bitSet(), Foam::blankElementMasks(), isoSurfaceBase::blockCells(), meshRefinement::blockLeakFaces(), PDRblock::blockMeshDict(), booleanSurface::booleanSurface(), booleanSurface::booleanSurface(), PrimitivePatch< FaceList, PointField >::boundaryFaces(), faMesh::boundaryProcSizes(), faPatch::boundaryProcSizes(), box::box(), treeDataEdge::boxes(), Foam::boxesImpl(), Foam::boxesImpl(), bufferedAccumulator< Type >::bufferLength(), pairPotentialList::buildPotentials(), tetherPotentialList::buildPotentials(), SurfaceFilmModel< CloudType >::cacheFilmFields(), valueAverageBase::calc(), ReactingHeterogeneousParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), ReactingParcel< ParcelType >::calc(), nearWallFields::calcAddressing(), faceAreaWeightAMI::calcAddressing(), mappedPatchBase::calcAMI(), PatchTools::calcBounds(), decompositionMethod::calcCellCells(), decompositionMethod::calcCellCells(), primitiveMesh::calcCells(), holeToFace::calcClosure(), curvatureSeparation::calcCosAngle(), Foam::calcElementMasks(), enrichedPatch::calcEnrichedFaces(), addPatchCellLayer::calcExtrudeInfo(), faceCoupleInfo::calcFacePointAverages(), cellToFaceStencil::calcFaceStencil(), coupledPolyPatch::calcFaceTol(), polyDualMesh::calcFeatures(), cutCell::calcGeomDataCutFace(), cellLimitedGrad< Type, Limiter >::calcGrad(), faceLimitedGrad< Type >::calcGrad(), triSurfaceTools::calcInterpolationWeights(), TDILUPreconditioner< Type, DType, LUType >::calcInvD(), globalIndex::calcListOffsets(), cellMatcher::calcLocalFaces(), mappedPatchBase::calcMapping(), fieldMinMax::calcMinMaxFieldType(), snappySnapDriver::calcNearestSurface(), globalIndex::calcOffsets(), polyLine::calcParam(), phaseSystem::calcPhi(), faPatch::calcPointEdges(), faPatch::calcPointLabels(), createShellMesh::calcPointRegions(), Foam::calcProximityOfFeatureEdges(), Foam::calcProximityOfFeaturePoints(), globalIndex::calcRanges(), distributedDILUPreconditioner::calcReciprocalD(), cutFace::calcSubFace(), cutFace::calcSubFace(), cutFace::calcSubFace(), cutFace::calcSubFaceCentreAndArea(), cyclicAMIPolyPatch::calcTransforms(), cyclicPolyPatch::calcTransforms(), coupledPolyPatch::calcTransformTensors(), surfaceNoise::calculate(), viewFactor::calculate(), waveMethod::calculate(), faceAreaWeightAMI::calculate(), faceAreaWeightAMI2D::calculate(), valueAverageBase::calculate(), waveMethod::calculate(), correctedCellVolumeWeightMethod::calculate(), extractEulerianParticles::calculateAddressing(), mapNearestMethod::calculateAddressing(), correlationFunction< Type >::calculateCorrelationFunction(), calculatedProcessorGAMGInterface::calculatedProcessorGAMGInterface(), meshRefinement::calculateEdgeWeights(), parcelSelection::calculateFilter(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::calculateMassFractions(), singleStepReactingMixture< ThermoType >::calculateMaxProducts(), GAMGAgglomeration::calculateRegionMaster(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), pointMVCWeight::calcWeights(), LiquidEvaporation< CloudType >::calcXc(), LiquidEvaporationBoil< CloudType >::calcXc(), MeshedSurface< face >::canRead(), PackedList< Width >::capacity(), CircularBuffer< T >::capacity(), deltaBoundary::cellCenters_d(), processorColour::cellColour(), primitiveMesh::cellEdges(), multiComponentMixture< ThermoType >::cellMixture(), fvMotionSolver::cellMotionBoundaryTypes(), primitiveMesh::cellPoints(), polyMeshTetDecomposition::cellTetIndices(), dynamicRefineFvMesh::cellToPoint(), multiComponentMixture< ThermoType >::cellVolMixture(), ReynoldsAnalogy::Cf(), ZoneMesh< ZoneType, MeshType >::cfindZone(), repatchPolyTopoChanger::changeAnchorPoint(), boundaryMesh::changeFaces(), polyTopoChange::changeMesh(), polyTopoChange::changeMesh(), repatchPolyTopoChanger::changePatchID(), boundaryMesh::changePatchType(), layerAdditionRemoval::changeTopology(), argList::check(), Foam::checkAllHits(), objectRegistry::checkCacheTemporaryObjects(), objectiveIncompressible::checkCellZonesSize(), primitiveMesh::checkClosedBoundary(), primitiveMesh::checkCommonOrder(), Foam::PstreamGlobals::checkCommunicator(), polyBoundaryMesh::checkDefinition(), coordSet::checkDimensions(), primitiveMesh::checkDuplicateFaces(), primitiveMesh::checkEdgeLength(), triSurface::checkEdges(), primitiveMeshGeometry::checkFaceDotProduct(), primitiveMesh::checkFaceOrthogonality(), MeshedSurface< Face >::checkFaces(), Foam::checkFaceSizeMatch(), Foam::checkFaceSizeMatch(), primitiveMesh::checkFaceVertices(), extractEulerianParticles::checkFaceZone(), Cloud< ParcelType >::checkFieldIOobject(), Cloud< ParticleType >::checkFieldIOobject(), Foam::checkFireEdges(), Foam::checkFireEdges(), surfaceFeatures::checkFlatRegionEdge(), searchableSurfaces::checkIntersection(), entry::checkITstream(), dictionary::checkITstream(), hexRef8::checkMesh(), motionSmootherAlgo::checkMesh(), motionSmootherAlgo::checkMesh(), edgeCollapser::checkMeshQuality(), searchableSurfaces::checkNormalOrientation(), PatchTools::checkOrientation(), faBoundaryMesh::checkParallelSync(), polyBoundaryMesh::checkParallelSync(), ZoneMesh< ZoneType, MeshType >::checkParallelSync(), PrimitivePatch< FaceList, PointField >::checkPointManifold(), primitiveMesh::checkPointNearness(), hexRef8::checkRefinementLevels(), GAMGAgglomeration::checkRestriction(), ReactingCloud< CloudType >::checkSuppliedComposition(), PrimitivePatch< FaceList, PointField >::checkTopology(), triSurface::checkTriangles(), primitiveMesh::checkUpperTriangular(), MeshedSurface< Face >::checkZones(), surfMesh::checkZones(), chemkinReader::chemkinReader(), Foam::clamp(), Foam::clamp(), ensightFaces::classify(), ensightFaces::classify(), ensightFaces::classify(), extendedEdgeMesh::classifyEdge(), extendedEdgeMesh::classifyFeaturePoint(), GAMGAgglomeration::clearLevel(), refinementHistory::clone(), dlLibraryTable::close(), Cloud< ParticleType >::Cloud(), Foam::cmptAv(), Foam::cmptMag(), Foam::cmptMagSqr(), Foam::cmptMax(), Foam::cmptMin(), coalCloudList::coalCloudList(), cellShape::collapsedFaces(), triSurfaceTools::collapseEdges(), meshRefinement::collectAndPrint(), extendedCellToFaceStencil::collectData(), extendedFaceToCellStencil::collectData(), wallDistAddressing::collectPatchFields(), ORourkeCollision< CloudType >::collide(), CollisionRecordList< PairType, WallType >::CollisionRecordList(), cellTable::combine(), Foam::ListListOps::combine(), holeToFace::combine(), Foam::ListListOps::combineOffset(), PrecisionAdaptor< Type, InputType, Container >::commit(), commSchedule::commSchedule(), refinementHistory::compact(), CompactListList< T >::CompactListList(), CompactListList< T >::CompactListList(), triSurface::compactPoints(), removeFaces::compatibleRemoves(), EigenMatrix< cmptType >::complexEVecs(), Foam::ComplexField(), Foam::ComplexField(), Foam::ComplexField(), Foam::ComplexField(), Foam::ComplexField(), Foam::ComplexField(), fileName::component(), fileName::components(), externalCoupled::compositeName(), sensitivityVolBSplines::computeBCContributions(), optMeshMovementVolumetricBSplinesExternalMotionSolver::computeBoundaryMovement(), constraintProjection::computeCorrection(), sensitivitySurface::computeDerivativesSize(), optimisationType::computeDirection(), multiDimPolyFitter< T >::computeMatrixSource(), multiDimPolyFitter< T >::computeMatrixSource(), optimisationType::computeMeritFunction(), sensitivityVolBSplines::computeObjectiveContributions(), adjointSimple::computeObjectiveSensitivities(), polyLine::concat(), ConeInjection< CloudType >::ConeInjection(), NURBS3DVolume::confineControlPoint(), NURBS3DVolume::confineControlPoint(), NURBS3DVolume::confineControlPointsDirections(), edgeCollapser::consistentCollapse(), hexRef8::consistentSlowRefinement(), hexRef8::consistentSlowRefinement2(), ConstantField< Type >::ConstantField(), DSMCCloud< ParcelType >::constProps(), faPatch::constraintTypes(), fvPatch::constraintTypes(), polyPatch::constraintTypes(), Foam::containerSizes(), boundBox::contains(), boundBox::contains(), boundBox::containsAny(), boundBox::containsAny(), optMeshMovementVolumetricBSplines::controlPointMovement(), vtuAdaptor::convertField(), IntegralScaleBox< Type >::convolve(), NURBS3DVolume::coordinates(), Foam::ensightOutput::Detail::copyComponent(), IndirectListBase< T, Addr >::copyList(), dynamicCode::copyOrCreateFiles(), polySurface::copySurface(), surfMesh::copySurface(), polySurface::copySurface(), surfMesh::copySurface(), diffusionMulticomponent< ReactionThermo, ThermoType >::correct(), pointPatchDist::correct(), ensightMesh::correct(), nearWallDist::correct(), wallDistData< TransferType >::correct(), inverseFaceDistanceDiffusivity::correct(), inversePointDistanceDiffusivity::correct(), transferModel::correct(), injectionModelList::correct(), limitVelocity::correct(), directionalPressureGradientExplicitSource::correct(), particle< Type >::correctAfterParallelTransfer(), pointLinear< Type >::correction(), ReactingParcel< ParcelType >::correctSurfaceValues(), regionProperties::count(), PtrListDetail< CloudFunctionObject< CloudType > >::count(), cyclicACMIFvsPatchField< Type >::coupled(), cyclicPolyPatch::coupledEdges(), globalMeshData::coupledPatchMeshEdgeMap(), cyclicPolyPatch::coupledPoints(), ReynoldsAnalogy::Cp(), heThermo< BasicThermo, MixtureType >::Cp(), heThermo< BasicThermo, MixtureType >::Cp(), heThermo< BasicThermo, MixtureType >::CpByCpv(), heThermo< BasicPsiThermo, MixtureType >::Cpv(), heThermo< BasicThermo, MixtureType >::Cpv(), profiling::create(), List< Type >::create(), profiling::create(), scene::createAnimation(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), meshRefinement::createBaffles(), AABBTree< Type >::createBoxes(), nearWallFields::createFields(), distanceSurface::createGeometry(), box::createMap(), Foam::createReconstructMap(), Foam::createReconstructMap(), createShellMesh::createShellMesh(), inverseDistance::createStencil(), Foam::createTree(), Foam::createZeroBoundaryPointFieldPtr(), Foam::createZeroBoundaryPtr(), meshRefinement::createZoneBaffles(), wallBoundedParticle::crossEdgeConnectedFace(), STARCDMeshReader::cullPoints(), motionSmootherAlgo::curPoints(), displacementInterpolationMotionSolver::curPoints(), volumetricBSplinesMotionSolver::curPoints(), wallBoundedParticle::currentEdge(), triSurfaceTools::curvatures(), curvatureSeparation::curvatureSeparation(), geomCellLooper::cut(), extendedEdgeMesh::cut(), topoCellLooper::cut(), Foam::meshTools::cutDirToEdge(), cutFaceAdvect::cutPoints(), cutFaceAdvect::cutPoints(), heThermo< BasicThermo, MixtureType >::Cv(), cyclicACMIGAMGInterface::cyclicACMIGAMGInterface(), cyclicAMIGAMGInterface::cyclicAMIGAMGInterface(), cyclicFvPatchField< scalar >::cyclicFvPatchField(), cyclicGAMGInterface::cyclicGAMGInterface(), fvMatrix< Type >::DD(), decompositionMethod::decompose(), multiLevelDecomp::decompose(), hierarchGeomDecomp::decompose(), hierarchGeomDecomp::decompose(), randomDecomp::decompose(), simpleGeomDecomp::decompose(), randomDecomp::decompose(), simpleGeomDecomp::decompose(), metisLikeDecomp::decompose(), decompositionMethod::decompose(), decompositionMethod::decompose(), manualDecomp::decompose(), noDecomp::decompose(), decompositionMethod::decompose(), metisLikeDecomp::decompose(), multiLevelDecomp::decompose(), structuredDecomp::decompose(), decompositionMethod::decompose(), faFieldDecomposer::decomposeField(), pointFieldDecomposer::decomposeField(), metisLikeDecomp::decomposeGeneral(), faMeshDecomposition::decomposeMesh(), UList< T >::deepCopy(), UList< T >::deepCopy(), triSurfaceTools::delaunay2D(), boundaryMesh::deletePatch(), cyclicFaPatch::delta(), cyclicFvPatch::delta(), cyclicACMIFvPatch::delta(), cyclicAMIFvPatch::delta(), TDACChemistryModel< ReactionThermo, ThermoType >::derivatives(), TDACChemistryModel< CompType, ThermoType >::derivatives(), NURBS3DVolume::determineActiveDesignVariablesAndPoints(), solarCalculator::diffuseSolarRad(), adjointRASModel::diffusionCoeffVar1(), adjointSpalartAllmaras::diffusionCoeffVar1(), adjointRASModel::diffusionCoeffVar2(), dimensionSets::dimensionSets(), meshRefinement::directionalRefine(), directions::directions(), adjointSpalartAllmaras::distanceSensitivities(), faMeshDistributor::distribute(), fvMeshDistribute::distribute(), distributedTriSurfaceMesh::distribute(), refinementHistory::distribute(), mapDistributeBase::distribute(), mapDistributeBase::distribute(), mapDistribute::distribute(), mapDistributeBase::distribute(), distributedDILUPreconditioner::distributedDILUPreconditioner(), faMeshDistributor::distributeField(), faMeshBoundaryHalo::distributeSparse(), boundaryAdjointContribution::dJdGradU(), boundaryAdjointContribution::dJdnut(), Foam::dlLoaded(), NURBS3DVolume::dndbBasedSensitivities(), Bezier::dndbBasedSensitivities(), Bezier::dndbBasedSensitivities(), snappyLayerDriver::doLayers(), snappyRefineDriver::doRefine(), snappyVoxelMeshDriver::doRefine(), box::doRefineBoxes(), meshRefinement::doRemovePoints(), meshRefinement::doRestorePoints(), snappySnapDriver::doSnap(), dummyAgglomeration::dummyAgglomeration(), meshRefinement::dumpIntersections(), Foam::duplicateOrder(), Bezier::dxdbFace(), Bezier::dxdbFace(), dynamicIndexedOctree< Type >::dynamicIndexedOctree(), extendedEdgeMesh::edgeBaffles(), faBoundaryMesh::edgeFaces(), primitiveMesh::edgeFaces(), faBoundaryMesh::edgeLabels(), extendedEdgeMesh::edgeNormals(), PatchTools::edgeOwner(), face::edges(), triSurfaceTools::edgeSide(), edgeSurface::edgeSurface(), triSurfaceMesh::edgeTree(), treeDataPrimitivePatch< PatchType >::empty(), globalIndexAndTransform::encode(), globalIndexAndTransform::encodeTransformIndex(), energyTransport::energyTransport(), PackedList< Width >::equal(), equationMaxIterCondition::equationMaxIterCondition(), HashTable< T, Key, Hash >::erase(), dynamicRefineFvMesh::error(), Foam::etcDirs(), edgeInterpolationScheme< scalar >::euclidianInterpolate(), FilterField::evaluate(), fieldAverageItem::evolve(), Pstream::exchange(), Pstream::exchange(), mapDistributeBase::exchangeAddressing(), mapDistributeBase::exchangeAddressing(), Foam::PstreamDetail::exchangeChunkedBuf(), Foam::PstreamDetail::exchangeConsensus(), Pstream::exchangeConsensus(), Foam::PstreamDetail::exchangeConsensus(), mapDistributeBase::exchangeMasks(), Pstream::exchangeSizes(), Pstream::exchangeSizes(), Pstream::exchangeSizes(), ddt2::execute(), extractEulerianParticles::execute(), limitFields::execute(), setFlow::execute(), surfaceDistance::execute(), zeroGradient::execute(), includeEntry::execute(), includeEtcEntry::execute(), includeEntry::execute(), includeEtcEntry::execute(), functionObjectList::execute(), ifeqEntry::execute(), Foam::expandLeading(), Foam::expandString(), string::ext(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), wallDistAddressing::extract(), Foam::extractValues(), Foam::extractValues(), extrudePatchMesh::extrudePatchMesh(), fvBoundaryMesh::faceCells(), polyBoundaryMesh::faceCells(), faceCoupleInfo::faceCoupleInfo(), ABAQUSCore::faceDecomposition(), NASCore::faceDecomposition(), primitiveMesh::faceEdges(), LduMatrix< Type, DType, LUType >::faceH(), lduMatrix::faceH(), FaceInteraction< CloudType >::FaceInteraction(), PatchToPatchInterpolation< FromPatch, ToPatch >::faceInterpolate(), Bezier::facePoints_d(), Bezier::facePoints_d(), FacePostProcessing< CloudType >::FacePostProcessing(), Foam::vtk::Tools::Faces(), prismMatcher::faceSizeMatch(), tetWedgeMatcher::faceSizeMatch(), wedgeMatcher::faceSizeMatch(), OppositeFaceCellWave< Type, TrackingData >::faceToCell(), PrimitivePatchInterpolation< Patch >::faceToEdgeInterpolate(), PrimitivePatchInterpolation< Patch >::faceToPointInterpolate(), faMatrix< Type >::faMatrix(), IndirectListBase< T, Addr >::fcIndex(), FDICPreconditioner::FDICPreconditioner(), FDICSmoother::FDICSmoother(), featureEdgeMesh::featureEdgeMesh(), extendedEdgeMesh::featurePointNormals(), fft::fftRenumberRecurse(), boundaryDataSurfaceReader::fieldNames(), IOobject::fileNameComponents(), uncollatedFileOperation::filePathInfo(), masterUncollatedFileOperation::filePathInfo(), exprDriver::fillFunctionValues(), cellClassification::fillRegionEdges(), distanceSurface::filterFaceProximity(), distanceSurface::filterKeepLargestRegion(), distanceSurface::filterKeepNearestRegions(), distanceSurface::filterRegionProximity(), pointNoise::filterTimeData(), sensitivitySurfacePoints::finalisePointSensitivities(), CircularBuffer< T >::find(), IndirectListBase< T, Addr >::find(), refinementSurfaces::findAllIntersections(), refinementSurfaces::findAllIntersections(), searchableSurfacesQueries::findAllIntersections(), volBSplinesBase::findBoxID(), refinementParameters::findCells(), NURBS3DSurface::findClosestSurfacePoint(), TimePaths::findClosestTime(), TimePaths::findClosestTimeIndex(), localPointRegion::findDuplicateFacePairs(), localPointRegion::findDuplicateFaces(), patchProbes::findElements(), polyMeshTetDecomposition::findFaceBasePts(), refinementSurfaces::findHigherIntersection(), cellVolumeWeightMethod::findInitialSeeds(), directMethod::findInitialSeeds(), mapNearestMethod::findInitialSeeds(), fileOperation::findInstance(), masterUncollatedFileOperation::findInstance(), searchableSurfaceWithGaps::findLine(), distributedTriSurfaceMesh::findLineAll(), distributedTriSurfaceMesh::findNearest(), distributedTriSurfaceMesh::findNearest(), searchableSurfacesQueries::findNearest(), searchableSurfacesQueries::findNearest(), searchableSurfacesQueries::findNearest(), refinementSurfaces::findNearestRegion(), refinementSurfaces::findNearestRegion(), refinementSurfaces::findNearestRegion(), wallBoundedStreamLine::findNearestTet(), searchableExtrudedCircle::findParametricNearest(), instant::findRange(), mappedPatchBase::findSamples(), polyMeshAdder::findSharedPoints(), instant::findStart(), ZoneMesh< ZoneType, MeshType >::findZoneID(), PstreamBuffers::finishedSends(), multiDimPolyFitter< T >::fitData(), multiDimPolyFitter< T >::fitData(), multiDimPolyFitter< T >::fitData(), multiDimPolyFitter< T >::fitData(), fixedFluxPressureFvPatchScalarField::fixedFluxPressureFvPatchScalarField(), FixedList< T, N >::FixedList(), volPointInterpolation::flatBoundaryField(), faMeshTools::flattenEdgeField(), mapDistributeBase::flipAndCombine(), forceList::forceList(), forceList::forceList(), rigidBodyModel::forwardDynamics(), distributedDICPreconditioner::forwardInternal(), distributedDILUPreconditioner::forwardInternal(), distributedDICPreconditioner::forwardInternalDiag(), distributedDILUPreconditioner::forwardInternalDiag(), PtrListDetail< T >::free(), FreeStream< CloudType >::FreeStream(), interfaceTrackingFvMesh::freeSurfaceSnGradU(), faceCorrectedSnGrad< Type >::fullGradCorrection(), fvFieldReconstructor::fvFieldReconstructor(), GAMGAgglomeration::GAMGAgglomeration(), GAMGSolver::GAMGSolver(), populationBalanceModel::gamma(), heThermo< BasicThermo, MixtureType >::gamma(), lduPrimitiveMesh::gather(), globalIndex::gather(), globalIndex::gather(), globalIndex::gather(), externalCoupled::gatherAndCombine(), PatchTools::gatherAndMerge(), globalIndex::gatherInplaceOp(), Pstream::gatherList(), globalIndex::gatherOp(), globalIndex::gatherOp(), Foam::PstreamDetail::gatherv(), globalIndex::gatherValues(), meshRefinement::gAverage(), Foam::gAverage(), particleDistribution::generateDistribution(), fvMeshDistribute::generateTestField(), geometric::geometric(), GeometricBoundaryField< Type, PatchField, GeoMesh >::GeometricBoundaryField(), globalIndex::get(), Foam::getAcceptableFunctionKeys(), surfaceZonesInfo::getAllClosedNamedSurfaces(), coupledPolyPatch::getAnchorPoints(), Foam::getBoundedColours(), surfaceZonesInfo::getClosedNamedSurfaces(), Foam::getCommPattern(), zoneDistribute::getDatafromOtherProc(), Foam::getEdge(), GenericPatchGeoFieldsWriter< PatchType >::getFaceField(), Foam::ensightOutput::Detail::getFaceSizes(), Foam::ensightOutput::Detail::getFaceSizes(), searchableSurfaceCollection::getField(), triSurfaceMesh::getField(), distributedTriSurfaceMesh::getField(), parseDriver::getField(), zoneDistribute::getFields(), fileOperation::getGlobalHostIORanks(), fileOperation::getGlobalIORanks(), surfaceSets::getHangingCells(), Foam::getHostGroupIds(), Foam::getIdentifier(), surfaceZonesInfo::getInsidePointNamedSurfaces(), combineFaces::getMergeSets(), surfaceZonesInfo::getNamedSurfaces(), boundaryMesh::getNearest(), searchableBox::getNormal(), searchableCone::getNormal(), searchableCylinder::getNormal(), searchableExtrudedCircle::getNormal(), searchablePlane::getNormal(), searchablePlate::getNormal(), searchableSphere::getNormal(), searchableSurfaceCollection::getNormal(), triSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getNormal(), searchableDisk::getNormal(), volBSplinesBase::getNumberOfBoxes(), fvExprDriver::getOrReadFieldImpl(), combineFaces::getOutsideFace(), cellDistFuncs::getPatchIDs(), cellDistFuncs::getPointNeighbours(), weightedPosition::getPoints(), Foam::ensightOutput::Detail::getPolysFacePoints(), Foam::ensightOutput::Detail::getPolysNFaces(), triSurfaceMeshPointSet::getRefPoint(), searchableBox::getRegion(), searchableCone::getRegion(), searchableCylinder::getRegion(), searchableDisk::getRegion(), searchableExtrudedCircle::getRegion(), searchablePlane::getRegion(), searchablePlate::getRegion(), searchableRotatedBox::getRegion(), searchableSphere::getRegion(), searchableSurfaceCollection::getRegion(), triSurfaceMesh::getRegion(), distributedTriSurfaceMesh::getRegion(), hexRef8::getSplitPoints(), surfaceZonesInfo::getStandaloneNamedSurfaces(), volBSplinesBase::getStartCpID(), volBSplinesBase::getTotalControlPointsNumber(), surfaceZonesInfo::getUnclosedNamedSurfaces(), surfaceZonesInfo::getUnnamedSurfaces(), removePoints::getUnrefimentSet(), wallDistAddressing::getValues(), fvExprDriver::getVariable(), parseDriver::getVariableIfAvailable(), cellLooper::getVertEdgesNonFace(), triSurfaceTools::getVertexTriangles(), cellLooper::getVertFacesNonEdge(), distributedTriSurfaceMesh::getVolumeType(), searchableBox::getVolumeType(), searchableCone::getVolumeType(), searchableCylinder::getVolumeType(), searchableSphere::getVolumeType(), triSurfaceMesh::getVolumeType(), meshRefinement::getZoneFaces(), meshRefinement::getZones(), cellCellStencil::globalCellCells(), GAMGProcAgglomeration::globalCellCells(), lduPrimitiveMesh::globalCellCells(), addPatchCellLayer::globalEdgeFaces(), globalIndex::globalIndex(), globalIndex::globalIndex(), globalIndex::globalIndex(), globalIndexAndTransform::globalIndexAndTransform(), transformFaPatchField< Type >::gradientInternalCoeffs(), chemPointISAT< CompType, ThermoType >::grow(), fvMatrix< Type >::H1(), faMeshBoundaryHalo::haloSize(), FaceCellWave< Type, TrackingData >::handleAMICyclicPatches(), FaceCellWave< Type, TrackingData >::handleCyclicPatches(), FaceCellWave< Type, TrackingData >::handleProcPatches(), string::has_ext(), HashTable< T * >::HashTable(), coordSetWriter::hasTime(), surfaceWriter::hasTime(), basicThermo::heBoundaryBaseTypes(), Henry< Thermo, OtherThermo >::Henry(), hexRef8::hexRef8(), hexRef8::hexRef8(), hexRef8Data::hexRef8Data(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Hs(), if(), if(), if(), Foam::Im(), Foam::Im(), Distribution< Type >::index(), indexedOctree< Type >::indexedOctree(), FreeStream< CloudType >::inflow(), KinematicCloud< CloudType >::info(), MPPICCloud< CloudType >::info(), LocalInteraction< CloudType >::info(), RecycleInteraction< CloudType >::info(), StandardWallInteraction< CloudType >::info(), injectionModelList::info(), transferModelList::info(), irregularMultiDirectional::info(), dynamicMultiMotionSolverFvMesh::init(), dynamicRefineFvMesh::init(), calculatedProcessorFvPatchField< Type >::initEvaluate(), heatExchangerModel::initialise(), interRegionExplicitPorositySource::initialise(), InjectedParticleDistributionInjection< CloudType >::initialise(), InjectedParticleInjection< CloudType >::initialise(), viewFactor::initialise(), surfaceNoise::initialise(), extractEulerianParticles::initialiseBins(), fluxSummary::initialiseCellZoneAndDirection(), fluxSummary::initialiseFaceZone(), fluxSummary::initialiseFaceZoneAndDirection(), fluxSummary::initialiseSurfaceAndDirection(), advancingFrontAMI::initialiseWalk(), objectivePtLosses::initialize(), objectiveUniformityPatch::initialize(), calculatedProcessorFvPatchField< Type >::initInterfaceMatrixUpdate(), lduCalculatedProcessorField< Type >::initInterfaceMatrixUpdate(), streamLineBase::initInterpolations(), LduMatrix< Type, DType, LUType >::initMatrixInterfaces(), lduMatrix::initMatrixInterfaces(), processorPolyPatch::initOrder(), InjectionModelList< CloudType >::InjectionModelList(), injectionModelList::injectionModelList(), injectionModelList::injectionModelList(), expressionEntry::inplaceExpand(), Foam::stringOps::inplaceExpand(), Foam::inplaceRenumber(), Foam::inplaceReorder(), Foam::inplaceReverseList(), Foam::inplaceRotateList(), Foam::inplaceSubset(), Foam::inplaceSubset(), Foam::inplaceSubsetList(), Foam::inplaceSubsetMatchingStrings(), Foam::input(), dynamicIndexedOctree< Type >::insertIndex(), NURBSbasis::insertKnot(), NURBS3DCurve::insertKnot(), distribution::insertMissingKeys(), correlationFunction< Type >::integral(), TableBase< Type >::integrate(), FieldFunction1< Function1Type >::integrate(), linearInterpolationWeights::integrationWeights(), faBoundaryMesh::interfaces(), fvBoundaryMesh::interfaces(), vtuAdaptor::internal(), cyclicACMIGAMGInterface::internalFieldTransfer(), cyclicAMIGAMGInterface::internalFieldTransfer(), AssemblyFvPatch< CyclicType >::internalFieldTransfer(), cyclicAMIPolyPatch::interpolate(), pointToPointPlanarInterpolation::interpolate(), faMeshSubset::interpolate(), leastSquaresEdgeInterpolation< Type >::interpolate(), edgeInterpolationScheme< Type >::interpolate(), faMeshSubset::interpolate(), singleCellFvMesh::interpolate(), fvMeshSubset::interpolate(), fvMeshSubset::interpolate(), fvMeshSubset::interpolate(), interpolationCellPointFace< Type >::interpolate(), patchTransformedInterpolation::interpolate(), cellCellStencil::interpolate(), volPointInterpolation::interpolateDimensionedInternalField(), surfaceInterpolate::interpolateFields(), wallBoundedStreamLineParticle::interpolateFields(), meshToMesh0::interpolateInternalField(), Foam::interpolatePointToCell(), Foam::interpolateSplineXY(), AMIInterpolation::interpolateToSource(), AMIInterpolation::interpolateToTarget(), interpolationTable< Type >::interpolateValue(), interpolationTable< Type >::interpolateValues(), Foam::interpolateXY(), Foam::interpolateXY(), regionModel::interRegionAMI(), intersectedSurface::intersectedSurface(), gradingDescriptors::inv(), Foam::inv(), Foam::inv(), Foam::inv(), topoSet::invert(), Foam::invTransform(), ISAT< CompType, ThermoType >::ISAT(), fvExprDriver::isGlobalVariable(), exprDriver::isLocalVariable(), isoSurfaceCell::isoSurfaceCell(), isoSurfacePoint::isoSurfacePoint(), isoSurfaceTopo::isoSurfaceTopo(), triSurfaceMesh::isSurfaceClosed(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::jacobian(), rigidBodyModel::join(), labelRange::join(), rigidBodyModel::join_(), Foam::kShellMean(), cell::labels(), boundaryAdjointContributionIncompressible::laminarDiffusivity(), lduPrimitiveMesh::lduPrimitiveMesh(), lduPrimitiveMesh::lduPrimitiveMesh(), Foam::levelSetFraction(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), Foam::MULES::limitSum(), Foam::MULES::limitSum(), Foam::MULES::limitSum(), Foam::MULES::limitSum(), lineDivide::lineDivide(), CircularBuffer< T >::list(), IndirectListBase< T, Addr >::list(), UPstream::listScatterValues(), triSurfaceLoader::load(), distributedTriSurfaceMesh::localQueries(), cylindrical::localToGlobal(), face::longestEdge(), hashedWordList::lookup(), fileOperation::lookupAndCacheProcessorsPath(), zone::lookupMap(), Foam::lumpedPointTools::lumpedPointStates(), LUscalarMatrix::LUscalarMatrix(), cell::mag(), Foam::mag(), Foam::magSqr(), deltaBoundary::makeCellCentres_d(), cyclicFaPatch::makeDeltaCoeffs(), meshRefinement::makeDisplacementField(), stabilisedFvGeometryScheme::makeFaceCentresAndAreas(), primitiveMeshTools::makeFaceCentresAndAreas(), deltaBoundary::makeFaceCentresAndAreas_d(), deltaBoundary::makeFaceCentresAndAreas_d(), Foam::makeIdentity(), faceCoupleInfo::makeMap(), faceCoupleInfo::makeMap(), polyTopoChange::makeMesh(), polyTopoChange::makeMesh(), averageNeighbourFvGeometryScheme::makeNonOrthoWeights(), cyclicFaPatch::makeWeights(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), coordinateSystem::manyTimesImpl(), Field< T >::map(), Field< Type >::map(), cyclicACMIPolyPatch::mapCollocatedFaces(), mappedPolyPatch::mapCollocatedFaces(), mappedWallPolyPatch::mapCollocatedFaces(), fvMeshAdder::MapDimField(), fvMeshAdder::MapDimFields(), mapDistribute::mapDistribute(), mapDistribute::mapDistribute(), mapDistributeBase::mapDistributeBase(), mapDistribute::mapDistributeBase(), fvMesh::mapFields(), Foam::MapLagrangianFields(), Foam::MapLagrangianFields(), mappedPatchBase::mappedPatchBase(), mapPolyMesh::mapPolyMesh(), mapPolyMesh::mapPolyMesh(), mapPolyMesh::mapPolyMesh(), meshToMesh::mapSrcToTgt(), meshToMesh::mapSrcToTgt(), meshToMesh::mapSrcToTgt(), meshToMesh::mapSrcToTgt(), fvMeshAdder::MapSurfaceField(), fvMeshAdder::MapSurfaceFields(), meshToMesh::mapTgtToSrc(), meshToMesh::mapTgtToSrc(), meshToMesh::mapTgtToSrc(), meshToMesh::mapTgtToSrc(), fvMeshAdder::MapVolField(), fvMeshAdder::MapVolFields(), inverseDistance::markDonors(), trackingInverseDistance::markDonors(), edgeCollapser::markMergeEdges(), triSurface::markZone(), PatchTools::markZone(), triSurface::markZones(), masterUncollatedFileOperation::masterOp(), masterUncollatedFileOperation::masterOp(), polyBoundaryMesh::matchGroups(), scalars::matching(), wordRes::matching(), Foam::matchPoints(), Foam::matchPoints(), Foam::max(), Foam::maxMagSqr(), cellDistFuncs::maxPatchSize(), propellerInfo::meanSampleDiskField(), correlationFunction< Type >::measurandFieldSize(), distribution::median(), Distribution< Type >::median(), edgeIntersections::merge(), cellToCellStencil::merge(), cellToFaceStencil::merge(), cellToCellStencil::merge(), cellToFaceStencil::merge(), zoneCellStencils::merge(), meshRefinement::mergeBaffles(), edgeMesh::mergeEdges(), meshRefinement::mergeEdgesUndo(), debugWriter::mergeField(), surfaceWriter::mergeFieldTemplate(), meshRefinement::mergeFreeStandingBaffles(), meshRefinement::mergePatchFaces(), meshRefinement::mergePatchFacesUndo(), globalMeshData::mergePoints(), globalMeshData::mergePoints(), extendedEdgeMesh::mergePointsAndSort(), fileOperation::mergeTimes(), meshRefinement::mergeZoneBaffles(), blockMesh::mesh(), cellShape::meshEdges(), MeshedSurface< face >::MeshedSurface(), MeshedSurface< Face >::MeshedSurface(), momentOfInertia::meshInertia(), meshToMesh0::meshToMesh0(), Foam::min(), Foam::minMagSqr(), SVD::minNonZeroS(), polyMeshTetDecomposition::minQuality(), Foam::mkDir(), attachDetach::modifyMotionPoints(), polyTopoChange::modifyPoint(), regionModel1D::moveMesh(), solidBodyFvGeometryScheme::movePoints(), polyMesh::movePoints(), polyTopoChange::movePoints(), globalIndex::mpiGather(), globalIndex::mpiGatherOp(), multiBandZoneAbsorptionEmission::multiBandZoneAbsorptionEmission(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::MultiComponentPhaseModel(), multiDirRefinement::multiDirRefinement(), multiDirRefinement::multiDirRefinement(), phaseProperties::name(), rigidBodyModel::nBodies(), PrimitivePatch< FaceList, PointField >::nBoundaryEdges(), regionModel::nbrCoupledPatchID(), bufferedAccumulator< Type >::nBuffers(), PDRmeshArrays::nCells(), UPstream::nComms(), adjointSolverManager::nConstraints(), joint::nDoF(), surfaceFeatures::nearestEdges(), extendedEdgeMesh::nearestFeatureEdgeByType(), meshRefinement::nearestIntersection(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), primitiveMesh::nEdges(), PrimitivePatch< FaceList, PointField >::nEdges(), cellModel::nEdges(), polyBoundaryMesh::neighbourEdges(), reuseTmp< TypeR, Type1 >::New(), chemistryReductionMethod< CompType, ThermoType >::New(), chemistryTabulationMethod< CompType, ThermoType >::New(), processorTopology::New(), profiling::New(), combustionModel::New(), masterUncollatedFileOperation::NewIFstream(), mappedPolyPatch::newInternalProcFaces(), mappedWallPolyPatch::newInternalProcFaces(), cyclicPolyPatch::newInternalProcFaces(), fvMeshTools::newMesh(), faMeshTools::newMesh(), ensightCase::nextTime(), PDRmeshArrays::nFaces(), surfMesh::nFaces(), cellModel::nFaces(), faPatch::ngbPolyPatchPointNormals(), globalIndexAndTransform::nIndependentTransforms(), surfaceFeatures::nInternalEdges(), indexedOctree< Type >::nLeafs(), adjointSolverManager::nObjectives(), nonBlockingGaussSeidelSmoother::nonBlockingGaussSeidelSmoother(), lduPrimitiveMesh::nonBlockingSchedule(), zoneCellStencils::nonEmptyFacesPatch(), cyclicACMIPolyPatch::nonOverlapPatchID(), surfaceLocation::normal(), distribution::normalisedShifted(), AMIInterpolation::normaliseWeights(), potential::nPairPotentials(), faMeshLduAddressing::nPatches(), CompositionModel< CloudType >::nPhase(), polySurface::nPointData(), faPatch::nPoints(), PrimitivePatch< FaceList, PointField >::nPoints(), polySurface::nPoints(), surfMesh::nPoints(), UPstream::nProcs(), polyLine::nSegments(), molecule::constantProperties::nSites(), MeshedSurface< Face >::nTriangles(), coordSetWriter::numPoints(), coordSetWriter::numTracks(), blockMesh::numZonedBlocks(), objectiveManager::objectiveManager(), noiseFFT::octaveBandInfo(), noiseFFT::octaves(), noiseModel::octaves(), offsetSurface::offsetSurface(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), StandardChemistryModel< CompType, ThermoType >::omega(), coordinateSystem::oneToOneImpl(), surfaceFormatsCore::oneZone(), dlLibraryTable::open(), dlLibraryTable::open(), dlLibraryTable::open(), mapDistribute::transformPosition::operator()(), csvTableReader< Type >::operator()(), PackedList< Width >::hasher::operator()(), interpolation2DTable< Type >::operator()(), sizeOp< T >::operator()(), MapInternalField< Type, MeshMapper, surfaceMesh >::operator()(), MapInternalField< Type, MeshMapper, volMesh >::operator()(), MapInternalField< Type, MeshMapper, areaMesh >::operator()(), MapInternalField< Type, MeshMapper, edgeMesh >::operator()(), MapInternalField< Type, MeshMapper, pointMesh >::operator()(), listPlusEqOp< T >::operator()(), appendEqOp< T >::operator()(), globalMeshData::ListPlusEqOp< T >::operator()(), janafThermo< EquationOfState >::operator+=(), polynomialFunction::operator+=(), polynomialFunction::operator-=(), fileName::operator/=(), Foam::operator<(), Foam::operator<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), CircularBuffer< T >::operator=(), HashSet< Key, Hash >::operator=(), IjkField< scalar >::operator=(), List< T >::operator=(), cellTable::operator=(), PtrDynList< T, SizeMin >::operator=(), PtrDynList< T, SizeMin >::operator=(), PtrDynList< T, SizeMin >::operator=(), PtrList< T >::operator=(), FixedList< T, N >::operator=(), List< T >::operator=(), HashSet< Key, Hash >::operator=(), BiIndirectList< T >::operator=(), FixedList< T, N >::operator=(), MeshedSurface< face >::operator=(), List< T >::operator=(), List< T >::operator=(), Foam::operator==(), Foam::operator==(), Foam::operator==(), HashSet< Key, Hash >::operator==(), interpolationTable< Type >::operator[](), Foam::operator^(), cell::opposingFaceLabel(), optimisationManager::optimisationManager(), processorPolyPatch::order(), orientedSurface::orient(), orientedSurface::orient(), triSurfaceTools::otherFace(), Foam::outer(), outletMappedUniformInletFvPatchField< Type >::outletMappedUniformInletFvPatchField(), Foam::output(), distributedTriSurfaceMesh::overlappingSurface(), voxelMeshSearch::overlaps(), labelRange::overlaps(), oversetGAMGInterface::oversetGAMGInterface(), PackedList< Width >::PackedList(), PackedList< Width >::PackedList(), PackedList< Width >::PackedList(), CompactListList< T >::packImpl(), CellZoneInjection< CloudType >::parcelsToInject(), FieldActivatedInjection< CloudType >::parcelsToInject(), InflationInjection< CloudType >::parcelsToInject(), ManualInjection< CloudType >::parcelsToInject(), argList::parse(), scalarRanges::parse(), scalarRange::parse(), ParticleCollector< CloudType >::ParticleCollector(), ParticleZoneInfo< CloudType >::ParticleZoneInfo(), blockMesh::patchDicts(), NURBS3DVolume::patchDxDbFace(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::PatchEdgeFaceWave(), multiComponentMixture< ThermoType >::patchFaceMixture(), polyMeshAdder::patchFacePairs(), multiComponentMixture< ThermoType >::patchFaceVolMixture(), pointFieldDecomposer::patchFieldDecomposer::patchFieldDecomposer(), polyBoundaryMesh::patchID(), sampledPatch::patchIDs(), lumpedPointDisplacementPointPatchVectorField::patchIds(), boundaryMesh::patchify(), patchInjection::patchInjection(), pointPatchField< Type >::patchInternalField(), calculatedProcessorFvPatchField< Type >::patchNeighbourField(), faBoundaryMesh::patchRanges(), faBoundaryMesh::patchStarts(), adjointEikonalSolver::patchTypes(), patchZones::patchZones(), formatter::PDataArray(), PstreamBuffers::peekRecvData(), noiseFFT::Pf(), phaseModel::phaseModel(), phaseModel::phaseModel(), phasePropertiesList::phasePropertiesList(), Foam::MatrixTools::pinv(), primitiveMesh::pointCells(), pointFieldReconstructor::pointFieldReconstructor(), PatchToPatchInterpolation< FromPatch, ToPatch >::pointInterpolate(), pointMapper::pointMapper(), PatchTools::pointNormals(), primitiveMesh::pointPoints(), vtuAdaptor::points(), vtuAdaptor::points(), Foam::vtk::Tools::Points(), PrimitivePatchInterpolation< Patch >::pointToFaceInterpolate(), polyBoundaryMesh::polyBoundaryMesh(), polyline::polyline(), polyMesh::polyMesh(), polyMesh::polyMesh(), Foam::polyMeshZipUpCells(), Polynomial< PolySize >::Polynomial(), populationBalanceModel::populationBalanceModel(), bezier::position(), projectCurveEdge::position(), projectEdge::position(), blockEdge::position(), polyline::positionAndDirection(), HeatTransferCoeff< CloudType >::postEvolve(), KinematicReynoldsNumber< CloudType >::postEvolve(), NusseltNumber< CloudType >::postEvolve(), ParticleDose< CloudType >::postEvolve(), ThermoReynoldsNumber< CloudType >::postEvolve(), WeberNumberReacting< CloudType >::postEvolve(), Foam::pow(), powerLawLopesdaCostaZone::powerLawLopesdaCostaZone(), DiagonalPreconditioner< Type, DType, LUType >::precondition(), TDILUPreconditioner< Type, DType, LUType >::precondition(), distributedDILUPreconditioner::precondition(), diagonalPreconditioner::precondition(), DICPreconditioner::precondition(), DILUPreconditioner::precondition(), FDICPreconditioner::precondition(), GAMGPreconditioner::precondition(), noPreconditioner::precondition(), TDILUPreconditioner< Type, DType, LUType >::preconditionT(), DILUPreconditioner::preconditionT(), Foam::prependList(), pressureInletOutletVelocityFvPatchVectorField::pressureInletOutletVelocityFvPatchVectorField(), filmTurbulenceModel::primaryRegionFriction(), foamToVtkReportFields::print(), seriesWriter::print(), seriesWriter::print(), sampledCuttingPlane::print(), sampledFaceZone::print(), sampledMeshedSurface::print(), sampledPatch::print(), sampledPatchInternalField::print(), sampledPlane::print(), distanceSurface::print(), collatedFileOperation::printBanner(), PackedList< Width >::printBits(), fvMeshDistribute::printFieldInfo(), reader::printInfo(), fvMeshDistribute::printIntFieldInfo(), GAMGAgglomeration::printLevels(), argList::printMan(), Foam::printManOption(), Foam::printMaps(), faMeshTools::printMeshChecks(), fvMeshDistribute::printMeshInfo(), Foam::printOption(), fileOperation::printRanks(), Foam::printRootsSubscription(), GAMGProcAgglomeration::printStats(), basicThermo::printThermoNames(), argList::printUsage(), GAMGAgglomeration::procAgglomerateRestrictAddressing(), particleDistribution::processField(), globalIndexAndTransform::processor(), faFieldDecomposer::processorAreaPatchFieldDecomposer::processorAreaPatchFieldDecomposer(), processorGAMGInterface::processorGAMGInterface(), collatedFileOperation::processorsDir(), fvFieldDecomposer::processorVolPatchFieldDecomposer::processorVolPatchFieldDecomposer(), faceAreaWeightAMI::processSourceFace(), polyMeshAdder::procPatchPairs(), particle< Type >::procTetPt(), PrimitivePatch< FaceList, PointField >::projectFaceCentres(), PrimitivePatch< FaceList, PointField >::projectPoints(), AMIInterpolation::projectPointsToSurface(), noiseFFT::PSDf(), cellModel::ptr(), cellModel::ptr(), PtrList< T >::PtrList(), PtrList< T >::PtrList(), PtrListDictionary< T >::PtrListDictionary(), pureZoneMixture< ThermoType >::pureZoneMixture(), DynamicList< T, SizeMin >::push_back(), CircularBuffer< T >::push_back(), List< T >::push_back(), DynamicList< T, SizeMin >::push_back(), CircularBuffer< T >::push_back(), DynamicList< T, SizeMin >::push_back(), DynamicField< T, SizeMin >::push_back(), ITstream::push_back(), DynamicList< T, SizeMin >::push_back(), ITstream::push_back(), PtrDynList< Foam::Field< label > >::push_back(), PtrDynList< T, SizeMin >::push_back(), PtrDynList< T, SizeMin >::push_back(), Enum< EnumType >::push_back(), DynamicList< T, SizeMin >::push_back(), Foam::PstreamGlobals::push_request(), FIRECore::putFireLabels(), heatTransferCoeffModel::q(), multiphaseInterHtcModel::q(), reactingEulerHtcModel::q(), cutFaceAdvect::quadAreaCoeffs(), Foam::stringOps::quotemeta(), interpolationTable< Type >::rateOfChange(), face::rcEdges(), Foam::Re(), Foam::Re(), Reaction< ReactionThermo >::reactionStr(), cloudSolution::read(), functionObjectList::read(), regIOobject::read(), runTimeControl::read(), tabulated6DoFAcceleration::read(), MRFZone::read(), binModel::read(), derivedFields::read(), externalCoupled::read(), fluxSummary::read(), unequalBinWidth::read(), multiFieldValue::read(), multiRegion::read(), FixedValueConstraint< Type >::read(), sampledSurfaces::read(), tabulated6DoFMotion::read(), NASedgeFormat::read(), ABAQUSsurfaceFormat< Face >::read(), AC3DsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OBJsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), STLsurfaceFormat< Face >::read(), TRIsurfaceFormat< Face >::read(), VTKsurfaceFormat< Face >::read(), OBJedgeFormat::read(), STARCDedgeFormat::read(), VTKedgeFormat::read(), boundaryMesh::read(), masterUncollatedFileOperation::read(), dimensionSet::read(), ITstream::read(), masterUncollatedFileOperation::readAndSend(), STARCDMeshReader::readBoundary(), ensightSurfaceReader::readCase(), STARCDMeshReader::readCells(), dynamicRefineFvMesh::readDict(), Time::readDict(), Foam::readDir(), ABAQUSCore::readHelper::readElements(), GeometricBoundaryField< Type, PatchField, GeoMesh >::readField(), ensightSurfaceReader::readField(), boundaryDataSurfaceReader::readField(), lagrangianFieldDecomposer::readFieldFields(), DSMCParcel< ParcelType >::readFields(), injectedParticle::readFields(), molecule::readFields(), solidParticle::readFields(), streamLineParticle::readFields(), wallBoundedStreamLineParticle::readFields(), CollidingParcel< ParcelType >::readFields(), KinematicParcel< ParcelType >::readFields(), MPPICParcel< ParcelType >::readFields(), ThermoParcel< ParcelType >::readFields(), ReactingHeterogeneousParcel< ParcelType >::readFields(), ReactingMultiphaseParcel< ParcelType >::readFields(), ReactingParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::readFields(), lagrangianFieldDecomposer::readFields(), fieldsDistributor::readFields(), fieldsDistributor::readFields(), wallBoundedParticle::readFields(), particle< Type >::readFields(), fixedGradientFaPatchField< Type >::readGradientEntry(), fixedGradientFvPatchField< Type >::readGradientEntry(), Foam::readLagrangian(), CircularBuffer< T >::readList(), DynamicList< T, SizeMin >::readList(), UList< T >::readList(), mixedFaPatchField< Type >::readMixedEntries(), mixedFvPatchField< Type >::readMixedEntries(), injectedParticle::readObjects(), ReactingMultiphaseParcel< ParcelType >::readObjects(), ReactingParcel< ParcelType >::readObjects(), SprayParcel< ParcelType >::readObjects(), particle< Type >::readObjects(), CollidingParcel< ParcelType >::readObjects(), KinematicParcel< ParcelType >::readObjects(), MPPICParcel< ParcelType >::readObjects(), ThermoParcel< ParcelType >::readObjects(), Foam::readObjVertices(), ABAQUSCore::readHelper::readPoints(), faMeshTools::readProcAddressing(), fvMeshTools::readProcAddressing(), regIOobject::readStream(), surfaceNoise::readSurfaceData(), ABAQUSCore::readHelper::readSurfaceElements(), boundaryMesh::readTriSurface(), polyMesh::readUpdate(), surfMesh::readUpdate(), faePatchField< Type >::readValueEntry(), faPatchField< Type >::readValueEntry(), fvPatchField< Type >::readValueEntry(), fvsPatchField< Type >::readValueEntry(), valuePointPatchField< Type >::readValueEntry(), realSize(), fft::realTransform1D(), mapDistributeBase::receive(), mapDistributeBase::receive(), faFieldReconstructor::reconstructField(), faFieldReconstructor::reconstructField(), fvFieldReconstructor::reconstructField(), fvFieldReconstructor::reconstructField(), pointFieldReconstructor::reconstructField(), lagrangianReconstructor::reconstructField(), lagrangianReconstructor::reconstructFieldField(), processorMeshes::reconstructPoints(), lagrangianReconstructor::reconstructPositions(), Foam::recursiveExpand(), DAC< CompType, ThermoType >::reduceMechanism(), DRG< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), box::refineBox(), box::refineBox(), meshRefinement::refineCandidates(), refinementHistory::refinementHistory(), refinementHistory::refinementHistory(), refinementHistory::refinementHistory(), refinementHistory::refinementHistory(), refinementHistory::refinementHistory(), refinementHistory::refinementHistory(), refinementParameters::refinementParameters(), refinementSurfaces::refinementSurfaces(), regionProperties::regionProperties(), searchableSurfaceCollection::regions(), edgeMesh::regions(), regionSplit2D::regionSplit2D(), Foam::ReImSum(), Foam::ReImSum(), faMatrix< Type >::relax(), fvMatrix< Type >::relax(), cuttingSurfaceBase::remapFaces(), UnsortedMeshedSurface< Face >::remapFaces(), lumpedPointController::remapPointLabels(), cyclicAMIPolyPatch::removeAMIFaces(), polyTopoChange::removeCell(), edgeIntersections::removeDegenerates(), fvMeshTools::removeEmptyPatches(), polyTopoChange::removeFace(), meshRefinement::removeGapCells(), dynamicIndexedOctree< Type >::removeIndex(), seriesWriter::removeNewer(), RemoveParcels< CloudType >::RemoveParcels(), polyTopoChange::removePoint(), undoableMeshCutter::removeSplitFaces(), SloanRenumber::renumber(), Foam::renumber(), randomRenumber::renumber(), renumberMethod::renumber(), manualRenumber::renumber(), structuredRenumber::renumber(), zoltanRenumber::renumber(), springRenumber::renumberImpl(), UPtrList< T >::reorder(), Foam::reorder(), FIREMeshReader::reorganize(), string::replace(), profilingPstream::report(), cyclicACMIPolyPatch::reportCoverage(), AMIWeights::reportPatch(), PtrDynList< T, SizeMin >::reserve(), PackedList< Width >::reserve(), fvMeshSubset::reset(), faFieldDecomposer::reset(), faMeshBoundaryHalo::reset(), faMeshSubset::reset(), fvMeshSubset::reset(), fvFieldDecomposer::reset(), faFieldDecomposer::reset(), globalIndex::reset(), fvFieldDecomposer::reset(), pointFieldDecomposer::reset(), vtuSizing::reset(), cyclicACMIPolyPatch::resetAMI(), cyclicAMIPolyPatch::resetAMI(), fieldSelection::resetFieldFilters(), multiDimPolyFitter< T >::resetMatrix(), polyMesh::resetPrimitives(), vtuSizing::resetShapes(), LduMatrix< Type, DType, LUType >::residual(), lduMatrix::residual(), LduMatrix< Type, DType, LUType >::residual(), lduMatrix::residual(), refinementHistory::resize(), CompactListList< T >::resize(), GAMGAgglomeration::restrictFaceField(), pairPatchAgglomeration::restrictField(), GAMGAgglomeration::restrictField(), Foam::reverse(), face::reverseFace(), Foam::reverseList(), Foam::rewritePatchLabels(), IndirectListBase< T, Addr >::rfind(), ReynoldsAnalogy::rho(), CompositionModel< CloudType >::rho(), heThermo< BasicThermo, MixtureType >::rhoEoS(), updateMethod::rightMult(), MappedFile< Type >::rmap(), noiseFFT::RMSmeanPf(), Foam::rotateList(), Foam::safeLog10(), binned::sample(), multiNormal::sample(), nearWallFields::sampleBoundaryField(), sampledPatchInternalField::sampleOnFaces(), sampledSurface::sampleOnFaces(), sampledPatchInternalField::sampleOnPoints(), sampledSurface::sampleOnPoints(), mappedPatchBase::sampleSize(), FPCG::scalarSolve(), PBiCGStab::scalarSolve(), PCG::scalarSolve(), PPCG::scalarSolveCG(), motionSmootherAlgo::scaleMesh(), cyclicACMIPolyPatch::scalePatchFaceAreas(), globalIndex::scatter(), Pstream::scatterList(), Foam::PstreamDetail::scatterv(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaces::searchableSurfaces(), ConstPrecisionAdaptor< Type, InputType, Container >::select(), extendedEdgeMesh::select(), triSurfaceLoader::select(), triSurfaceLoader::selectAll(), surfaceFeatures::selectFeatureEdges(), Foam::selectPatchFaces(), dynamicRefineFvMesh::selectRefineCells(), dynamicRefineFvMesh::selectUnrefinePoints(), mapDistributeBase::send(), PstreamBuffers::sendDataCount(), distributedDILUPreconditioner::sendGlobal(), accessor::set(), UPtrList< CloudFunctionObject< CloudType > >::setAddressableSize(), cyclicAMIPolyPatch::setAMIFaces(), extractEulerianParticles::setBlockedFaces(), Foam::setBlockFaceCorrespondence(), fvMatrix< Type >::setBounAndInterCoeffs(), NURBS3DVolume::setControlPoints(), volumetricBSplinesMotionSolver::setControlPointsMovement(), Time::setControls(), refinementSurfaces::setCurvatureMinLevelFields(), noiseFFT::setData(), faceSetOption::setFaceSelection(), repatchPolyTopoChanger::setFaceZone(), boundaryMesh::setFeatureEdges(), fvExpressionField::setField(), faBoundaryMesh::setGroup(), polyBoundaryMesh::setGroup(), ZoneMesh< ZoneType, MeshType >::setGroup(), pointPatchField< Type >::setInInternalField(), globalIndex::setLocalSize(), CompactListList< T >::setLocalSize(), fvGeometryScheme::setMeshPhi(), refinementSurfaces::setMinLevelFields(), cellVolumeWeightMethod::setNextCells(), mapNearestMethod::setNextNearestCells(), noiseModel::setOctaveBands(), weightedPosition::setPoints(), patchInjectionBase::setPositionAndCell(), ConeInjection< CloudType >::setPositionAndCell(), ReactingLookupTableInjection< CloudType >::setPositionAndCell(), ReactingMultiphaseLookupTableInjection< CloudType >::setPositionAndCell(), ThermoLookupTableInjection< CloudType >::setPositionAndCell(), ConeInjection< CloudType >::setProperties(), ReactingLookupTableInjection< CloudType >::setProperties(), ReactingMultiphaseLookupTableInjection< CloudType >::setProperties(), ThermoLookupTableInjection< CloudType >::setProperties(), box::setRefineFlags(), removeCells::setRefinement(), removePoints::setRefinement(), meshCutter::setRefinement(), addPatchCellLayer::setRefinement(), perfectInterface::setRefinement(), meshCutAndRemove::setRefinement(), hexRef8::setRefinement(), faceCollapser::setRefinement(), removeFaces::setRefinement(), combineFaces::setRefinement(), edgeCollapser::setRefinement(), refinementIterator::setRefinement(), duplicatePoints::setRefinement(), boundaryCutter::setRefinement(), createShellMesh::setRefinement(), UnsortedMeshedSurface< Face >::setSize(), masterUncollatedFileOperation::setTime(), coordSetWriter::setTracks(), coordSetWriter::setTrackTimes(), removePoints::setUnrefinement(), hexRef8::setUnrefinement(), Foam::ListOps::setValue(), Foam::ListOps::setValue(), Foam::ListOps::setValue(), Foam::ListOps::setValue(), UnsortedMeshedSurface< Face >::setZones(), shellSurfaces::shellSurfaces(), PackedList< Width >::shrink(), Foam::shuffle(), electrostaticDepositionFvPatchScalarField::sigma(), singleCellFvMesh::singleCellFvMesh(), singleStepReactingMixture< ThermoType >::singleStepReactingMixture(), ISAT< CompType, ThermoType >::size(), faAreaMapper::size(), parseDriver::size(), pairPatchAgglomeration::size(), phasePropertiesList::size(), lumpedPointMovement::size(), lumpedPointState::size(), treeDataPrimitivePatch< PatchType >::size(), patchFunction1Base::size(), searchableExtrudedCircle::size(), searchableSurfaceWithGaps::size(), pointPatchField< Type >::size(), GAMGAgglomeration::size(), pointMapper::size(), facePointPatch::size(), cellMapper::size(), distributedWeightedFvPatchFieldMapper::size(), MeshedSurfaceProxy< Face >::size(), UnsortedMeshedSurface< Face >::size(), surfaceWriter::size(), liquidMixtureProperties::size(), solidMixtureProperties::size(), List< Type >::size(), seriesWriter::size(), vtuCells::size(), multiWorldConnections::size(), dynamicTreeDataPoint::size(), IndirectListBase< T, Addr >::size(), argList::size(), profiling::size(), Enum< EnumType >::size(), lagrangianFieldDecomposer::fieldsCache::privateCache::size(), parseDriver::size(), triSurfaceGeoMesh::size(), triSurfacePointGeoMesh::size(), ITstream::skip(), SLGThermo::SLGThermo(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), nonBlockingGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), symGaussSeidelSmoother::smooth(), DICSmoother::smooth(), DILUSmoother::smooth(), FDICSmoother::smooth(), Foam::fvc::smooth(), basicSymmetryFaPatchField< Type >::snGrad(), wedgeFaPatchField< Type >::snGrad(), basicSymmetryFvPatchField< Type >::snGrad(), symmetryPlaneFvPatchField< Type >::snGrad(), wedgeFvPatchField< Type >::snGrad(), rigidBodyMeshMotionSolver::solve(), TDACChemistryModel< ReactionThermo, ThermoType >::solve(), LLTMatrix< Type >::solve(), LLTMatrix< Type >::solve(), PBiCCCG< Type, DType, LUType >::solve(), PBiCICG< Type, DType, LUType >::solve(), PCICG< Type, DType, LUType >::solve(), SmoothSolver< Type, DType, LUType >::solve(), LUscalarMatrix::solve(), GAMGSolver::solve(), PBiCG::solve(), smoothSolver::solve(), oversetFvMeshBase::solveOverset(), tolerances::solverRelativeTolerances(), fvMatrix< Type >::solveSegregated(), reactingOneDim::solveSpeciesMass(), ParSortableList< Type >::sort(), SortList< T >::sort(), PatchTools::sortedEdgeFaces(), extendedEdgeMesh::sortedOrder(), Foam::sortedOrder(), Foam::sortedOrder(), PatchTools::sortedPointEdges(), triSurface::sortedZones(), UnsortedMeshedSurface< Face >::sortedZones(), MeshedSurface< Face >::sortFacesAndStore(), extendedEdgeMesh::sortPointsAndEdges(), fileOperation::sortTimes(), splineInterpolationWeights::splineInterpolationWeights(), Foam::stringOps::split(), Foam::stringOps::split(), meshRefinement::splitFacesUndo(), Foam::stringOps::splitFixed(), Foam::stringOps::splitFunctionArgs(), meshRefinement::splitMeshRegions(), Foam::splitStringToList(), basicThermo::splitThermoName(), Foam::fvc::spread(), Foam::sqr(), Foam::stabilise(), cellVolumeWeight::stencilWeights(), inverseDistance::stencilWeights(), leastSquares::stencilWeights(), Foam::stepBackwardsToNextPoint(), Foam::stepForwardsToNextPoint(), MeshedSurface< Face >::stitchFaces(), hexRef8::storeData(), fvMesh::storeOldVol(), streamLineParticle::streamLineParticle(), string::string_printf(), fileOperation::subRanks(), refinementHistory::subset(), meshRefinement::subsetBaffles(), Foam::subsetMatchingStrings(), Foam::ListListOps::subSizes(), faMatrix< Type >::subtractFromInternalField(), fvMatrix< Type >::subtractFromInternalField(), faceZoneSet::subtractSet(), Foam::sum(), LduMatrix< Type, DType, LUType >::sumA(), lduMatrix::sumA(), Foam::sumCmptMag(), Foam::sumCmptProd(), boundaryAdjointContributionIncompressible::sumContributions(), Foam::sumMag(), cellDistFuncs::sumPatchSize(), Foam::sumProd(), Foam::sumProd(), Foam::sumProd(), Foam::sumProd(), Foam::sumSqr(), reconstructionSchemes::surface(), surfaceFeatures::surfaceFeatures(), surfaceIntersection::surfaceIntersection(), PrimitivePatch< FaceList, PointField >::surfaceType(), surfaceZonesInfo::surfaceZonesInfo(), surfZoneIOList::surfZoneIOList(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), Foam::fvc::sweep(), Foam::symmOuter(), faceZoneSet::sync(), syncTools::syncBoundaryFaceList(), globalMeshData::syncData(), globalMeshData::syncData(), syncTools::syncEdgeList(), syncTools::syncEdgeList(), syncTools::syncEdgeList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), globalMeshData::syncPointData(), syncTools::syncPointList(), syncTools::syncPointList(), syncTools::syncPointList(), syncTools::syncPointMap(), weightedPosition::syncPoints(), weightedPosition::syncPoints(), pointConstraints::syncUntransformedData(), pointToPointPlanarInterpolation::targetSize(), StandardChemistryModel< ReactionThermo, ThermoType >::tc(), Foam::FieldOps::ternary(), Foam::FieldOps::ternary(), Foam::FieldOps::ternarySelect(), Foam::FieldOps::ternarySelect(), Foam::FieldOps::ternarySelect(), meshRefinement::testSyncBoundaryFaceList(), meshRefinement::testSyncPointList(), meshRefinement::testSyncPointList(), TGaussSeidelSmoother< Type, DType, LUType >::TGaussSeidelSmoother(), boundaryAdjointContributionIncompressible::thermalDiffusion(), thermoSingleLayer::thermoSingleLayer(), thirdBodyEfficiencies::thirdBodyEfficiencies(), thirdBodyEfficiencies::thirdBodyEfficiencies(), cutFaceAdvect::timeIntegratedArea(), LduMatrix< Type, DType, LUType >::Tmul(), lduMatrix::Tmul(), Matrix< Form, Type >::TmulImpl(), boundaryAdjointContribution::TMVariable1(), boundaryAdjointContribution::TMVariable1Diffusion(), boundaryAdjointContribution::TMVariable2(), boundaryAdjointContribution::TMVariable2Diffusion(), blockMesh::topology(), surfaceFeatures::toStatus(), ITstream::toString(), streamLine::track(), wallBoundedStreamLine::track(), MeshedSurface< Face >::transcribe(), DynamicList< T, SizeMin >::transfer(), DynamicField< T, SizeMin >::transfer(), MeshedSurface< Face >::transfer(), fvMatrix< Type >::transferFvMatrixCoeffs(), transferModelList::transferModelList(), KinematicSurfaceFilm< CloudType >::transferParcel(), fft::transform(), FaceCellWave< Type, TrackingData >::transform(), Foam::transform(), Foam::transform(), multiMotion::transformation(), globalIndexAndTransform::transformIndex(), Foam::transformList(), Foam::transformList(), Foam::transformList(), Foam::transformList(), globalIndexAndTransform::transformPatches(), coordinateSystem::transformPointImpl(), rigidBodyMotion::transformPoints(), cyclicAMIPolyPatch::transformPosition(), cyclicPolyPatch::transformPosition(), triSurfaceSearch::tree(), faceAreaIntersect::triangleFan(), face::triangles(), triSurfaceTools::triangulate(), triSurfaceTools::triangulate(), MeshedSurface< Face >::triangulate(), triSurfaceTools::triangulateFaceCentre(), advancingFrontAMI::triangulatePatch(), extendedEdgeMesh::trim(), surfaceFeatures::trimFeatures(), streamLineBase::trimToBox(), streamLineBase::trimToBox(), triSurface::triSurfInstance(), GeometricBoundaryField< Type, PatchField, GeoMesh >::types(), pointConstraint::unconstrainedDirections(), mapDistributeBase::unionCombineMasks(), wordRes::uniq(), wordRes::uniq(), PrimitivePatch< FaceList, PointField >::uniqBoundaryFaces(), ensightFaces::uniqueMeshPoints(), Foam::unitSet(), PackedList< Width >::unpack(), CompactListList< T >::unpack(), PackedList< Width >::unpack(), dynamicRefineFvMesh::unrefine(), Foam::unzip(), Foam::unzip(), Foam::unzip(), Foam::unzip(), Foam::unzip(), Foam::unzip(), Foam::unzipCol(), Foam::unzipCols(), Foam::unzipDiag(), Foam::unzipDiag(), Foam::unzipRow(), Foam::unzipRow(), Foam::unzipRows(), Foam::unzipRows(), liquidFilmBase::Up(), dynamicMotionSolverListFvMesh::update(), cellVolumeWeight::update(), inverseDistance::update(), trackingInverseDistance::update(), sampledFaceZone::update(), lduPrimitiveMeshAssembly::update(), oversetFvMeshBase::updateAddressing(), turbulentDFSEMInletFvPatchVectorField::updateCoeffs(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), lumpedPointDisplacementPointPatchVectorField::updateCoeffs(), fixedMultiPhaseHeatFluxFvPatchScalarField::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), ReactingHeterogeneousParcel< ParcelType >::updatedDeltaVolume(), ReactingParcel< ParcelType >::updatedDeltaVolume(), ReactingMultiphaseParcel< ParcelType >::updatedDeltaVolume(), patchEdgeFaceRegions::updateEdge(), patchEdgeFaceRegions::updateEdge(), primitiveMeshTools::updateFaceCentresAndAreas(), polyMesh::updateGeomPoints(), optimisationType::updateGradientsAndValues(), jumpCyclicFvPatchField< Type >::updateInterfaceMatrix(), meshRefinement::updateIntersections(), edgeVertex::updateLabels(), edgeVertex::updateLabels(), meshRefinement::updateList(), lduPrimitiveMeshAssembly::updateMaps(), LduMatrix< Type, DType, LUType >::updateMatrixInterfaces(), lduMatrix::updateMatrixInterfaces(), faGlobalMeshData::updateMesh(), CellZoneInjection< CloudType >::updateMesh(), componentDisplacementMotionSolver::updateMesh(), points0MotionSolver::updateMesh(), refinementHistory::updateMesh(), removePoints::updateMesh(), faMesh::updateMesh(), meshRefinement::updateMesh(), addPatchCellLayer::updateMesh(), hexRef8::updateMesh(), fvMesh::updateMesh(), patchInjectionBase::updateMesh(), processorFaPatch::updateMesh(), fileFieldSelection::updateSelection(), solverFieldSelection::updateSelection(), volFieldSelection::updateSelection(), fvExprDriver::updateSet(), fileMonitor::updateStates(), dynamicRefineFvMesh::updateTopology(), UPtrList< T >::UPtrList(), MeshedSurfaceProxy< Face >::useFaceIds(), MeshedSurfaceProxy< Face >::useFaceMap(), ensightMesh::options::useFaceZones(), liquidFilmBase::Uw(), wallPoints::valid(), patchEdgeFaceRegions::valid(), UList< T >::validateRange(), triSurfaceTools::validTri(), triSurfaceTools::validTri(), colourTable::value(), Sampled< Type >::value(), TableBase< Type >::value(), clampedPlateFaPatchField< Type >::valueInternalCoeffs(), transformFvPatchField< Type >::valueInternalCoeffs(), Foam::HashTableOps::values(), splineInterpolationWeights::valueWeights(), triSurfaceTools::vertexTriads(), Foam::vertices(), Foam::vtk::Tools::Vertices(), surfaceIteratorIso::vofCutCell(), surfaceIteratorPLIC::vofCutCell(), volBSplinesBase::volBSplinesBase(), FieldActivatedInjection< CloudType >::volumeToInject(), cuttingSurfaceBase::walkCellCuts(), cellCellStencil::walkFront(), wallBoundedStreamLineParticle::wallBoundedStreamLineParticle(), wallLayerCells::wallLayerCells(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), streamLineBase::wallPatch(), adjointSpalartAllmaras::wallShapeSensitivities(), reader::warnDuplicates(), interpolationWeights::weightedSum(), meshRefinement::weightedSum(), surfaceFieldValue::weightingFactor(), boundaryMesh::whichPatch(), polyBoundaryMesh::whichPatchFace(), surfaceFieldValue::write(), momentum::write(), multiFieldValue::write(), particleDistribution::write(), regionSizeDistribution::write(), areaWrite::write(), vtkWrite::write(), FaceInteraction< CloudType >::write(), ParticleCollector< CloudType >::write(), ParticlePostProcessing< CloudType >::write(), ParticleZoneInfo< CloudType >::write(), debugWriter::write(), vtkWriter::write(), UOPstreamBase::write(), OTstream::write(), STARCDedgeFormat::write(), OBJedgeFormat::write(), GTSsurfaceFormat< Face >::write(), ABAQUSsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), NASsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), OFFsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), STARCDsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), VTPsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), GTSsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), VTPsurfaceFormat< Face >::write(), patchWriter::write(), patchWriter::write(), MeshedSurfaceProxy< Face >::write(), OBJstream::write(), sensitivityVolBSplines::write(), sensitivityVolBSplinesFI::write(), OFstreamCollator::write(), ensightFaces::write(), voxelMeshSearch::write(), FLMAsurfaceFormat< Face >::write(), oversetFvMeshBase::write(), scene::write(), functionEntry::write(), oversetFvMeshBase::writeAgglomeration(), STLsurfaceFormat< Face >::writeAscii(), fileWriter::writeBasicField(), STLsurfaceFormat< Face >::writeBinary(), decomposedBlockData::writeBlocks(), box::writeBoxes(), coordSetWriter::writeBufferContents(), STARCDedgeFormat::writeCase(), STARCDsurfaceFormatCore::writeCase(), VTKsurfaceFormatCore::writeCellData(), VTPsurfaceFormatCore::writeCellData(), Foam::vtk::writeCellSetFaces(), triSurfaceTools::writeCloseness(), Foam::ensightOutput::writeCloudPositions(), faBoundaryMesh::writeData(), profiling::writeData(), polyBoundaryMesh::writeData(), faMeshDecomposition::writeDecomposition(), UList< T >::writeEntry(), Foam::ensightOutput::Detail::writeFaceLocalField(), Foam::ensightOutput::Detail::writeFaceSubField(), Foam::ensightOutput::writeField(), Foam::ensightOutput::writeField(), Foam::ensightOutput::Detail::writeFieldComponents(), DSMCParcel< ParcelType >::writeFields(), injectedParticle::writeFields(), molecule::writeFields(), solidParticle::writeFields(), streamLineParticle::writeFields(), wallBoundedStreamLineParticle::writeFields(), CollidingParcel< ParcelType >::writeFields(), KinematicParcel< ParcelType >::writeFields(), MPPICParcel< ParcelType >::writeFields(), ThermoParcel< ParcelType >::writeFields(), ReactingHeterogeneousParcel< ParcelType >::writeFields(), ReactingMultiphaseParcel< ParcelType >::writeFields(), ReactingParcel< ParcelType >::writeFields(), SprayParcel< ParcelType >::writeFields(), wallBoundedParticle::writeFields(), particle< Type >::writeFields(), lumpedPointMovement::writeForcesAndMomentsVTP(), lagrangianWriter::writeGeometry(), externalCoupled::writeGeometry(), AC3DsurfaceFormatCore::writeHeader(), Foam::writeHeaderEntry(), advancingFrontAMI::writeIntersectionOBJ(), Ostream::writeKeyword(), PackedList< Width >::writeList(), CircularBuffer< T >::writeList(), IndirectListBase< T, Addr >::writeList(), UILList< LListBase, T >::writeList(), UList< T >::writeList(), UList< T >::writeList(), Foam::vtk::writeListParallel(), Foam::vtk::writeListParallel(), Foam::vtk::writeListsParallel(), Foam::vtk::writeListsParallel(), Matrix< Form, Type >::writeMatrix(), patchMeshWriter::writeNeighIDs(), faceAreaWeightAMI2D::writeNoMatch(), coupledPolyPatch::writeOBJ(), triSurfaceTools::writeOBJ(), extendedEdgeMesh::writeObj(), surfaceFeatures::writeObj(), AABBTreeBase::writeOBJ(), indexedOctreeBase::writeOBJ(), Foam::meshTools::writeOBJ(), cellZoneSet::writeObject(), faceZoneSet::writeObject(), pointZoneSet::writeObject(), oversetFvMeshBase::writeObject(), injectedParticle::writeObjects(), ReactingHeterogeneousParcel< ParcelType >::writeObjects(), ReactingMultiphaseParcel< ParcelType >::writeObjects(), ReactingParcel< ParcelType >::writeObjects(), SprayParcel< ParcelType >::writeObjects(), particle< Type >::writeObjects(), CollidingParcel< ParcelType >::writeObjects(), KinematicParcel< ParcelType >::writeObjects(), MPPICParcel< ParcelType >::writeObjects(), ThermoParcel< ParcelType >::writeObjects(), patchMeshWriter::writePatchIDs(), coordSetWriter::writePointData(), patchMeshWriter::writePoints(), Foam::vtk::writePointSet(), patchMeshWriter::writePolys(), Foam::ensightOutput::writePolysPoints(), Foam::ensightOutput::writePolysPoints(), faMeshTools::writeProcAddressing(), fvMeshTools::writeProcAddressing(), lumpedPointMovement::writeStateVTP(), edgeMesh::writeStats(), extendedEdgeMesh::writeStats(), surfaceFeatures::writeStats(), MeshedSurface< Face >::writeStats(), triSurface::writeStats(), Foam::edgeMeshTools::writeStats(), extendedCellToFaceStencil::writeStencilStats(), surfaceNoise::writeSurfaceData(), abaqusWriter::writeTemplate(), debugWriter::writeTemplate(), nastranWriter::writeTemplate(), starcdWriter::writeTemplate(), x3dWriter::writeTemplate(), csvWriter::writeTemplate(), gltfWriter::writeTemplate(), gnuplotWriter::writeTemplate(), rawWriter::writeTemplate(), vtkWriter::writeTemplate(), xmgraceWriter::writeTemplate(), gltfWriter::writeTemplate_animate(), streamLineBase::writeToFile(), dynamicIndexedOctree< Type >::writeTreeInfo(), Foam::ensightOutput::writeVolField(), Foam::writeVolFields(), vtkWrite::writeVolFieldsImpl(), interfaceTrackingFvMesh::writeVTKControlPoints(), lumpedPointMovement::writeVTP(), lumpedPointState::writeVTP(), Foam::stringOps::writeWrapped(), Foam::writeZone(), liquidMixtureProperties::X(), interpolation2DTable< Type >::Xi(), liquidMixtureProperties::Xs(), Foam::XstepForwardsToNextPoint(), phaseProperties::Y(), zeroATCcells::zeroATCcells(), MRFZoneList::zeroFilter(), Foam::zip(), Foam::zip(), Foam::zip(), Foam::zip(), Foam::zip(), Foam::zip(), Foam::zip(), Foam::zip(), Foam::zip(), Foam::zip(), Foam::zip(), Foam::zipCols(), Foam::zipRows(), Foam::zipRows(), refinementParameters::zonePoints(), boundaryRadiationProperties::zoneTransmissivity(), meshRefinement::zonify(), PstreamBuffers::~PstreamBuffers(), UOPBstream::~UOPBstream(), and UOPstream::~UOPstream().
count()
template<class T > Foam::label count () const inline noexcept
Definition at line 120 of file UPtrListI.H.
Referenced by AABBTree< Type >::AABBTree(), AMIInterpolation::calcDistribution(), CloudFunctionObjectList< CloudType >::CloudFunctionObjectList(), hexRef8::consistentSlowRefinement(), mapDistributeBase::countUnmapped(), polyMeshFilter::filterEdges(), InjectionModelList< CloudType >::InjectionModelList(), isoSurfaceCell::isoSurfaceCell(), isoSurfaceTopo::isoSurfaceTopo(), dynamicRefineFvMesh::mapFields(), ParticleForceList< CloudType >::ParticleForceList(), meshRefinement::printMeshInfo(), clockValue::seconds(), dynamicRefineFvMesh::selectRefineCells(), dynamicRefineFvMesh::selectUnrefinePoints(), faceAreaWeightAMI::setNextFaces(), addPatchCellLayer::setRefinement(), clockValue::str(), refinementData::updateCell(), refinementData::updateFace(), refinementData::updateFace(), meshRefinement::updateIntersections(), cellCellStencil::walkFront(), UList< T >::writeEntry(), and triSurface::writeStats().
front() [1/2]
template<class T > T & front () inline
Definition at line 223 of file UPtrListI.H.
Referenced by Foam::meshTools::bandCompression(), box::box(), fileName::concat(), face::edges(), OppositeFaceCellWave< Type, TrackingData >::faceToCell(), UPtrList< T >::first(), UPtrList< T >::first(), fileOperation::getGlobalIORanks(), Foam::invTransform(), face::longestEdge(), Foam::operator/(), Foam::polyMeshZipUpCells(), ITstream::print(), face::rcEdges(), functionObjectList::read(), primitiveEntry::read(), forceCoeffs::selectCoeffs(), exprResultDelayed::storeValue(), ITstream::toString(), Foam::transform(), Foam::transform(), Foam::transformList(), Foam::transformList(), Foam::transformList(), zoneToCell::zones(), zoneToFace::zones(), zoneToPoint::zones(), faceZoneToCell::zones(), zoneToCell::zones(), zoneToFace::zones(), and zoneToPoint::zones().
front() [2/2]
template<class T > const T & front () const inline
Definition at line 230 of file UPtrListI.H.
back() [1/2]
template<class T > T & back () inline
Definition at line 237 of file UPtrListI.H.
Referenced by fileMonitor::addWatch(), eagerGAMGProcAgglomeration::agglomerate(), masterCoarsestGAMGProcAgglomeration::agglomerate(), procFacesGAMGProcAgglomeration::agglomerate(), directMethod::appendToDirectSeeds(), cellVolumeWeightMethod::calculateAddressing(), correctedCellVolumeWeightMethod::calculateAddressing(), MeshedSurface< Face >::checkZones(), surfMesh::checkZones(), fileName::concat(), wallDistAddressing::correct(), profiling::create(), face::edges(), globalIndex::empty(), vtmWriter::endBlock(), profiling::endTimer(), ifeqEntry::execute(), mapNearestMethod::findMappedSrcCell(), mapNearestMethod::findNearestCell(), fileName::isBackup(), UPtrList< T >::last(), UPtrList< T >::last(), face::longestEdge(), Reaction< ThermoType >::New(), Foam::operator/(), fileName::operator/=(), Foam::polyMeshZipUpCells(), ITstream::print(), faceAreaWeightAMI::processSourceFace(), face::rcEdges(), dimensionSet::read(), ITstream::read(), ensightSurfaceReader::readCase(), distributedDILUPreconditioner::receive(), distributedDILUPreconditioner::send(), exprResultDelayed::storeValue(), streamLineBase::trimToBox(), and profiling::writeData().
back() [2/2]
template<class T > const T & back () const inline
Definition at line 244 of file UPtrListI.H.
test()
template<class T > const T * test (const label i) const inline
Definition at line 127 of file UPtrListI.H.
References UPtrList< T >::get().
Referenced by polyMeshTetDecomposition::adjustTetBasePtIs(), extendedEdgeMesh::autoMap(), Foam::meshTools::bandCompression(), Foam::calcElementMasks(), Foam::calcNormalDistance_filtered(), dynamicRefineFvMesh::calculateProtectedCells(), primitiveMeshTools::cellDeterminant(), coordinateSystems::cfind(), ensightFaces::classify(), edgeCollapser::consistentCollapse(), hexRef8::consistentSlowRefinement2(), hexRef8::consistentUnrefinement(), meshRefinement::countHits(), faMeshDistributor::distributeField(), snappyLayerDriver::doLayers(), dynamicRefineFvMesh::extendMarkedCells(), boundaryRadiationProperties::faceZoneIds(), distanceSurface::filterKeepLargestRegion(), distanceSurface::filterKeepNearestRegions(), distanceSurface::filterPrepareRegionSplit(), meshRefinement::findRegions(), topoBitSet::found(), topoBoolSet::found(), meshRefinement::gAverage(), Foam::getSelectedProcs(), dynamicRefineFvMesh::init(), meshRefinement::intersectedPoints(), isoSurfaceTopo::isoSurfaceTopo(), FaceCellWave< Type, int >::leaveDomain(), edgeCollapser::markSmallEdges(), edgeMesh::mergeEdges(), cell::opposingFace(), plicRDF::reconstruct(), distanceSurface::refineBlockedCells(), regionSplit::regionSplit(), regionSplit2D::regionSplit2D(), snappySnapDriver::repatchToSurface(), dynamicRefineFvMesh::selectRefineCells(), dynamicRefineFvMesh::selectUnrefinePoints(), motionSmootherAlgo::setDisplacement(), faceAreaWeightAMI::setNextFaces(), hexRef8::setRefinement(), edgeCollapser::setRefinement(), fieldSmoother::smoothLambdaMuDisplacement(), fieldSmoother::smoothNormals(), extendedEdgeMesh::sortPointsAndEdges(), triSurface::subsetMesh(), meshRefinement::updateIntersections(), cellCellStencil::walkFront(), meshRefinement::weightedSum(), and meshRefinement::zonify().
get() [1/2]
template<class T > const T * get (const label i) const inline
Definition at line 134 of file UPtrListI.H.
References UPtrList< T >::get().
Referenced by lookup::a(), fvMeshAdder::add(), geometric::add(), refinementHistory::add(), columnFvMeshInfo::addLocalPatches(), exprResultGlobals::addValue(), refinementHistory::apply(), coordinateSystem::assign(), UPtrList< T >::at(), UPtrList< T >::at(), Cloud< ParcelType >::autoMap(), PDRarrays::block(), fixedCoeff::calcForce(), parcelSelection::calculateFilter(), genericRagelLemonDriver::cbegin(), ZoneMesh< ZoneType, MeshType >::cfindZone(), axisAligned::computeControlPoints(), hexRef8::consistentUnrefinement(), genericRagelLemonDriver::content(), Foam::cp(), rotorDiskSource::createCoordinateSystem(), filmTurbulenceModel::Cw(), DAC< CompType, ThermoType >::DAC(), Cloud< ParcelType >::deleteLostParticles(), dynamicCodeContext::dict(), Foam::dimensionedConstant(), directions::directions(), argList::displayDoc(), parseDriver::dupZeroField(), lookup::e(), stringEntry::evaluate(), KirchhoffShell::evolveRegion(), thermalShell::evolveRegion(), externalCoupledTemperatureMixedFvPatchScalarField::externalCoupledTemperatureMixedFvPatchScalarField(), fileOperation::fileHandler(), fileOperation::fileHandler(), filmTurbulenceModel::filmTurbulenceModel(), regIOobject::findMetaData(), UPtrList< T >::FOAM_DEPRECATED_FOR(), FreeStream< CloudType >::FreeStream(), UPtrList< T >::const_iterator::get(), ifstreamPointer::get(), ofstreamPointer::get(), ifstreamPointer::get(), ofstreamPointer::get(), UPtrList< T >::get(), UPtrList< T >::get(), exprDriver::getFunction1Ptr(), decomposedBlockData::getNumBlocks(), Foam::getOrAdd(), Enum< injectionMethod >::getOrDefault(), exprResult::getValue(), if(), movingConeTopoFvMesh::init(), HashPtrTable< T, Key, Hash >::insert(), wallBoundedStreamLineParticle::interpolateFields(), ISAT< CompType, ThermoType >::ISAT(), layerParameters::layerParameters(), Foam::MULES::limiterCorr(), fvExprDriver::lookupGlobal(), volSurfaceMapping::mapToSurface(), volSurfaceMapping::mapToSurface(), medialAxisMeshMover::move(), decompositionMethod::New(), absorptionEmissionModel::New(), objectiveIncompressible::New(), adjointSensitivity::New(), chemistryReductionMethod< CompType, ThermoType >::New(), chemistryTabulationMethod< CompType, ThermoType >::New(), laminarFlameSpeed::New(), LduMatrix< Type, DType, LUType >::preconditioner::New(), waveModel::New(), lduMatrix::solver::New(), LduMatrix< Type, DType, LUType >::smoother::New(), porosityModel::New(), fieldValue::New(), displacementMethod::New(), Function1< Type >::New(), PatchFunction1< Type >::New(), basicSolidChemistryModel::New(), filmThermoModel::New(), filmTurbulenceModel::New(), filmRadiationModel::New(), heatTransferModel::New(), phaseChangeModel::New(), filmViscosityModel::New(), coordSetWriter::numPoints(), objective::objective(), objectiveIncompressible::objectiveIncompressible(), objectiveManager::objectiveManager(), offsetSurface::offsetSurface(), refPtr< Field< InputType > >::operator tmp< Field< InputType > >(), UPtrList< T >::less::operator()(), UPtrList< T >::greater::operator()(), ifstreamPointer::operator->(), ofstreamPointer::operator->(), ifstreamPointer::operator->(), ofstreamPointer::operator->(), Foam::functionObjects::operator>>(), PackedList< Width >::PackedList(), PackedList< Width >::PackedList(), PackedList< Width >::PackedList(), parProfilingSolver::parProfilingSolver(), IOobject::parseHeader(), fvExpressionField::performAction(), RecycleInteraction< CloudType >::postEvolve(), pressureControl::pressureControl(), filmTurbulenceModel::primaryRegionFriction(), solutionControl::read(), Curle::read(), fieldAverage::read(), fieldExtents::read(), norm::read(), propellerInfo::read(), externalHeatFluxSource::read(), jouleHeatingSource::read(), MRFZone::read(), singleDirectionUniformBin::read(), uniformBin::read(), externalCoupled::read(), surfaceFieldValue::read(), equalBinWidth::read(), unequalBinWidth::read(), limitFields::read(), multiFieldValue::read(), hydrostaticPressure::read(), rotorDiskSource::read(), targetCoeffTrim::read(), SemiImplicitSource< Type >::read(), valueAverageBase::read(), surfaceNoise::read(), Enum< injectionMethod >::read(), dynamicRefineFvMesh::readDict(), fieldsDistributor::readFields(), fieldsDistributor::readFields(), conjugateGradient::readFromDict(), functionObjectList::readFunctionObject(), Foam::ReadHex(), Foam::readToNewline(), Foam::readUntilBalancedDelimiter(), Foam::readVariable(), Foam::readVerbatim(), refinementSurfaces::refinementSurfaces(), tolerances::relaxationFactor(), zoltanRenumber::renumber(), rigidBodyModel::rigidBodyModel(), rigidBodyMotion::rigidBodyMotion(), rigidBodyMotion::rigidBodyMotion(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaces::searchableSurfaces(), cellBitSet::select(), UPtrList< T >::set(), PrecisionAdaptor< Type, InputType, Container >::set(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::setCdSigma(), propellerInfo::setCoordinateSystem(), motionSmootherAlgo::setErrorReduction(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::setPorosityCoefficient(), coordSetWriter::setTracks(), shapeOptimisation::shapeOptimisation(), shellSurfaces::shellSurfaces(), Foam::skipComments(), multiphaseSystem::solve(), populationBalanceModel::solve(), twoPhaseSystem::solve(), tolerances::solverRelativeTolerance(), tolerances::solverTolerance(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi(), regIOobject::store(), regIOobject::store(), surfaceZonesInfo::surfaceZonesInfo(), UPtrList< T >::test(), HashPtrTable< IOobject >::test(), thirdBodyEfficiencies::thirdBodyEfficiencies(), uniformInterpolationTable< Type >::uniformInterpolationTable(), lduPrimitiveMeshAssembly::update(), LduMatrix< Type, DType, LUType >::updateMatrixInterfaces(), lduMatrix::updateMatrixInterfaces(), dynamicRefineFvMesh::updateTopology(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), vtkWriter::write(), and PackedList< Width >::writeList().
get() [2/2]
template<class T > T * get (const label i) inline
Definition at line 141 of file UPtrListI.H.
References UPtrList< T >::get().
set() [1/2]
template<class T > const T * set (const label i) const inline
Definition at line 285 of file UPtrList.H.
References UPtrList< T >::get().
Referenced by GAMGAgglomeration::agglomerateLduAddressing(), lduPrimitiveMesh::gather(), GAMGProcAgglomeration::globalCellCells(), lduPrimitiveMesh::globalCellCells(), lduMatrix::initMatrixInterfaces(), faBoundaryMesh::interfaces(), fvBoundaryMesh::interfaces(), lduPrimitiveMesh::lduPrimitiveMesh(), lduPrimitiveMesh::lduPrimitiveMesh(), multiphaseSystem::multiphaseSystem(), Foam::operator<<(), phaseSystem::phaseSystem(), GAMGAgglomeration::printLevels(), procLduMatrix::procLduMatrix(), GeometricBoundaryField< Type, PatchField, GeoMesh >::scalarInterfaces(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaceWithGaps::searchableSurfaceWithGaps(), PtrList< T >::set(), fvMatrix< Type >::setInterfaces(), lduMatrix::sumA(), oversetFvMeshBase::updateAddressing(), lduMatrix::updateMatrixInterfaces(), and oversetFvMeshBase::write().
clear()
template<class T > void clear () inline
Definition at line 195 of file UPtrListI.H.
References PtrList< T >::clear().
Referenced by PtrList< CloudFunctionObject< CloudType > >::PtrList().
free()
template<class T > void free () inline
Definition at line 202 of file UPtrListI.H.
resize()
template<class T > void resize (const label newLen) inline
Definition at line 251 of file UPtrListI.H.
Referenced by phaseSystem::phaseSystem(), and UPtrList< T >::setSize().
squeezeNull()
template<class T > Foam::label squeezeNull ()
Definition at line 38 of file UPtrList.C.
References T.
trimTrailingNull()
template<class T > void trimTrailingNull ()
Definition at line 62 of file UPtrList.C.
References UPtrList< T >::setAddressableSize().
push_back() [1/2]
template<class T > void push_back (T * ptr) inline
Definition at line 258 of file UPtrListI.H.
Referenced by UPtrList< T >::append(), UPtrList< T >::append(), PtrList< CloudFunctionObject< CloudType > >::PtrList(), PtrList< T >::push_back(), PtrList< T >::push_back(), PtrList< T >::push_back(), and PtrList< T >::push_back().
push_back() [2/2]
template<class T > void push_back (UPtrList< T > && other) inline
Definition at line 265 of file UPtrListI.H.
swap()
template<class T > void swap (UPtrList< T > & list) inline
Definition at line 209 of file UPtrListI.H.
References UPtrList< T >::ptrs_, and UPtrList< T >::swap().
Referenced by FilterField::evaluate(), fileOperation::fileHandler(), fileOperation::fileHandler(), DynamicField< T, SizeMin >::readList(), Matrix< Form, Type >::release(), faceSetOption::subsetFilter(), Foam::Swap(), CircularBuffer< T >::swap(), CompactListList< T >::swap(), OListStreamAllocator::swap(), Foam::Swap(), Foam::Swap(), OListStreamAllocator::swap(), MeshedSurface< Face >::swap(), PackedList< Width >::swap(), Foam::Swap(), regExpCxx::swap(), Foam::Swap(), triSurface::swap(), Foam::Swap(), UnsortedMeshedSurface< Face >::swap(), UPtrList< T >::swap(), MeshedSurface< Face >::transfer(), triSurfaceTools::writeCloseness(), triSurfaceTools::writeCurvature(), and Foam::edgeMeshTools::writeFeatureProximity().
transfer()
template<class T > void transfer (UPtrList< T > & list) inline
Definition at line 216 of file UPtrListI.H.
Referenced by PtrList< T >::transfer().
set() [2/2]
template<class T > T * set (const label i, T * ptr) inline
Definition at line 182 of file UPtrListI.H.
References T.
reorder()
template<class T > void reorder (const labelUList & oldToNew, const bool check = false)
Definition at line 79 of file UPtrList.C.
References Foam::abort(), Foam::check(), UPtrList< T >::checkNonNull(), Foam::FatalError, FatalErrorInFunction, Foam::name(), Foam::nl, UPtrList< T >::size(), T, and PtrList< T >::transfer().
Referenced by meshRefinement::addPatch(), fvMeshTools::addPatch(), phasePropertiesList::phasePropertiesList(), LBFGS::pivotFields(), PtrDynList< T, SizeMin >::reorder(), polyBoundaryMesh::reorder(), and fvMeshTools::reorderPatches().
sortOrder()
template<class T > void sortOrder (const labelUList & order, const bool check = false)
Definition at line 128 of file UPtrList.C.
References Foam::abort(), Foam::check(), UPtrList< T >::checkNonNull(), Foam::FatalError, FatalErrorInFunction, Foam::name(), Foam::nl, UList< T >::size(), T, and PtrList< T >::transfer().
Referenced by Foam::shuffle().
checkNonNull()
template<class T > void checkNonNull () const inline
Definition at line 273 of file UPtrListI.H.
Referenced by UPtrList< T >::reorder(), and UPtrList< T >::sortOrder().
at() [1/2]
template<class T > const T & at (const label i) const inline
Definition at line 148 of file UPtrListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::get(), and T.
Referenced by pointLinear< Type >::correction(), UPtrList< T >::iterator::val(), and UPtrList< T >::const_iterator::val().
at() [2/2]
template<class T > T & at (const label i) inline
Definition at line 165 of file UPtrListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::get(), and T.
operator[]() [1/2]
template<class T > const T & operator[] (const label i) const inline
Definition at line 282 of file UPtrListI.H.
Referenced by singleStepReactingMixture< ThermoType >::calculateqFuel(), forceList::correct(), injectionModelList::correct(), transferModelList::correct(), transferModelList::correct(), forceList::correct(), pyrolysisModelCollection::evolve(), pyrolysisModelCollection::evolveRegion(), pyrolysisModelCollection::info(), injectionModelList::info(), transferModelList::info(), FieldField< Field, Type >::negate(), FieldField< Field, Type >::normalise(), FieldField< Field, Type >::operator=(), FieldField< Field, Type >::operator=(), FieldField< Field, Type >::operator=(), FieldField< Field, Type >::operator[](), FieldField< Field, Type >::operator[](), pyrolysisModelCollection::preEvolveRegion(), FieldField< Field, Type >::replace(), FieldField< Field, Type >::replace(), coalCloudList::UTrans(), and MRFZoneList::zeroFilter().
operator[]() [2/2]
template<class T > T & operator[] (const label i) inline
Definition at line 289 of file UPtrListI.H.
FOAM_DEPRECATED_FOR()
template<class T > FOAM_DEPRECATED_FOR (2022- 09, " get(), set() or test() methods") const inline
Definition at line 363 of file UPtrList.H.
References UPtrList< T >::get().
operator=() [1/2]
template<class T > void operator= (const UPtrList< T > & list) inline
Definition at line 458 of file UPtrListI.H.
References UPtrList< T >::ptrs_.
operator=() [2/2]
template<class T > void operator= (UPtrList< T > && list) inline
Definition at line 465 of file UPtrListI.H.
References PtrList< T >::transfer().
begin_ptr()
template<class T > T ** begin_ptr () inline noexcept
Definition at line 586 of file UPtrList.H.
References UPtrList< T >::begin(), and UPtrList< T >::ptrs_.
Referenced by Foam::sort(), and Foam::sort().
end_ptr()
template<class T > T ** end_ptr () inline noexcept
Definition at line 589 of file UPtrList.H.
References UPtrList< T >::end(), and UPtrList< T >::ptrs_.
Referenced by Foam::sort(), and Foam::sort().
begin() [1/2]
template<class T > Foam::UPtrList< T >::iterator begin () inline
Definition at line 409 of file UPtrListI.H.
Referenced by DictionaryBase< IDLListType, T >::addEntries(), distributedDILUPreconditioner::addInterface(), UPstream::allocateCommunicator(), multiphaseInterSystem::alphahe(), multiphaseInterSystem::alphahe(), LduMatrix< Type, DType, LUType >::Amul(), lduMatrix::Amul(), Foam::FieldOps::assign(), Foam::FieldOps::assign(), distributedDILUPreconditioner::backwardInternal(), HashSet< Key, Hash >::begin(), HashSet< Key, Hash >::begin(), stdFoam::begin(), stdFoam::begin(), UPtrList< T >::begin_ptr(), bitSet::bitSet(), bitSet::bitSet(), bitSet::bitSet(), bitSet::bitSet(), bitSet::bitSet(), bitSet::bitSet(), Foam::HashSetOps::bitset(), bitSet::bitSet(), Foam::HashSetOps::bools(), treeDataEdge::boxes(), treeDataPrimitivePatch< PatchType >::boxes(), Foam::boxesImpl(), Foam::boxesImpl(), TDILUPreconditioner< Type, DType, LUType >::calcInvD(), DICPreconditioner::calcReciprocalD(), DILUPreconditioner::calcReciprocalD(), distributedDILUPreconditioner::calcReciprocalD(), stdFoam::cbegin(), treeDataEdge::centres(), ZoneMesh< ZoneType, MeshType >::cfindZone(), dictionary::changeKeyword(), Foam::clamp(), Foam::clamp(), Foam::ListListOps::combine(), Foam::ListListOps::combineOffset(), PrecisionAdaptor< Type, InputType, Container >::commit(), EigenMatrix< cmptType >::complexEVecs(), Foam::ensightOutput::Detail::copyComponent(), faMeshDecomposition::decomposeMesh(), UList< CloudFunctionObject< CloudType > * >::deepCopy(), triSurfaceTools::delaunay2D(), diagonalPreconditioner::diagonalPreconditioner(), DiagonalPreconditioner< Type, DType, LUType >::DiagonalPreconditioner(), DICPreconditioner::DICPreconditioner(), DICSmoother::DICSmoother(), DILUPreconditioner::DILUPreconditioner(), DILUSmoother::DILUSmoother(), multiphaseSystem::dragCoeff(), Foam::eigenValues(), edge::erase(), objectRegistry::erase(), Pstream::exchange(), ABAQUSCore::faceDecomposition(), NASCore::faceDecomposition(), FDICPreconditioner::FDICPreconditioner(), FDICSmoother::FDICSmoother(), boundaryDataSurfaceReader::fieldNames(), IndirectListBase< T, Addr >::find(), Foam::findFirstCommonElementFromSortedLists(), distributedDICPreconditioner::forwardInternal(), distributedDILUPreconditioner::forwardInternal(), distributedDICPreconditioner::forwardInternalDiag(), distributedDILUPreconditioner::forwardInternalDiag(), GenericPatchGeoFieldsWriter< PatchType >::getFaceField(), fileOperation::getGlobalIORanks(), LduMatrix< Type, DType, LUType >::H(), lduMatrix::H(), lduMatrix::H1(), HashSet< Key, Hash >::HashSet(), HashSet< labelPairPair >::HashSet(), HashSet< Key, Hash >::HashSet(), HashSet< Key, Hash >::HashSet(), STDMD::initialise(), PDRblock::innerMesh(), Foam::inplaceMapKey(), HashSet< Key, Hash >::insert(), edge::insert(), Foam::inv(), Foam::kShellIntegration(), labelRange::labels(), sliceRange::labels(), Foam::makeIdentity(), HashSet< labelPairPair >::merge(), HashTable< T, Key, Hash >::merge(), Foam::operator*(), Foam::operator*(), Foam::operator+(), Foam::operator+(), Foam::operator-(), Foam::operator-(), Foam::operator-(), Foam::operator-(), Foam::operator/(), Foam::operator/(), HashSet< Key, Hash >::operator=(), FixedList< T, N >::operator=(), HashSet< Key, Hash >::operator=(), CompactListList< T >::packImpl(), SortableList< T >::partialReverseSort(), SortableListEFA< Type >::partialSort(), SortableList< T >::partialSort(), primitiveMesh::pointCells(), DiagonalPreconditioner< Type, DType, LUType >::precondition(), TDILUPreconditioner< Type, DType, LUType >::precondition(), distributedDILUPreconditioner::precondition(), diagonalPreconditioner::precondition(), DICPreconditioner::precondition(), DILUPreconditioner::precondition(), FDICPreconditioner::precondition(), noPreconditioner::precondition(), TDILUPreconditioner< Type, DType, LUType >::preconditionT(), DILUPreconditioner::preconditionT(), dictionary::remove(), zoltanRenumber::renumber(), vtuSizing::renumberFaceLabelsXml(), fvMeshSubset::reset(), LduMatrix< Type, DType, LUType >::residual(), lduMatrix::residual(), IndirectListBase< T, Addr >::rfind(), FPCG::scalarSolve(), PBiCGStab::scalarSolve(), PCG::scalarSolve(), ConstPrecisionAdaptor< Type, InputType, Container >::select(), bitSet::set(), bitSet::set(), bitSet::set(), Foam::BitOps::set(), Foam::shuffle(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), nonBlockingGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), symGaussSeidelSmoother::smooth(), DICSmoother::smooth(), DILUSmoother::smooth(), FDICSmoother::smooth(), PBiCCCG< Type, DType, LUType >::solve(), PBiCICG< Type, DType, LUType >::solve(), PCICG< Type, DType, LUType >::solve(), PBiCG::solve(), SortList< T >::sort(), Foam::sort(), split(), basicThermo::splitThermoName(), Foam::stableSort(), Foam::stableSort(), string::stripInvalid(), Foam::ListListOps::subSizes(), LduMatrix< Type, DType, LUType >::sumA(), lduMatrix::sumA(), TGaussSeidelSmoother< Type, DType, LUType >::TGaussSeidelSmoother(), LduMatrix< Type, DType, LUType >::Tmul(), lduMatrix::Tmul(), fft::transform(), CompactListList< T >::unpack(), HashSet< Key, Hash >::unset(), bitSet::unset(), HashSet< Key, Hash >::unset(), bitSet::unset(), bitSet::unset(), cuttingSurfaceBase::walkCellCuts(), processorColour::walkFront(), Foam::ensightOutput::writeCloudPositions(), and fvExprDriver::writeCommon().
end() [1/2]
template<class T > Foam::UPtrList< T >::iterator end () inline noexcept
Definition at line 433 of file UPtrListI.H.
Referenced by DictionaryBase< IDLListType, T >::addEntries(), multiphaseInterSystem::alphahe(), multiphaseInterSystem::alphahe(), bitSet::bitSet(), bitSet::bitSet(), bitSet::bitSet(), bitSet::bitSet(), bitSet::bitSet(), bitSet::bitSet(), Foam::HashSetOps::bitset(), bitSet::bitSet(), Foam::HashSetOps::bools(), nearWallFields::calcAddressing(), distributedDILUPreconditioner::calcReciprocalD(), viewFactor::calculate(), stdFoam::cend(), ZoneMesh< ZoneType, MeshType >::cfindZone(), Foam::checkFireEdges(), MassTransferPhaseSystem< BasePhaseSystem >::correctMassSources(), UList< CloudFunctionObject< CloudType > * >::deepCopy(), DICPreconditioner::DICPreconditioner(), DICSmoother::DICSmoother(), DILUPreconditioner::DILUPreconditioner(), DILUSmoother::DILUSmoother(), edgeSurface::edgeSurface(), Foam::meshTools::edgeToCutDir(), directionInfo::edgeToFaceIndex(), Foam::eigenValues(), functionObjectList::end(), timeControl::end(), steadyOptimisation::end(), stdFoam::end(), stdFoam::end(), UPtrList< T >::end_ptr(), edge::erase(), objectRegistry::erase(), Pstream::exchange(), FDICPreconditioner::FDICPreconditioner(), FDICSmoother::FDICSmoother(), boundaryDataSurfaceReader::fieldNames(), Foam::findFirstCommonElementFromSortedLists(), fileOperation::getGlobalIORanks(), Foam::meshTools::getParallelEdges(), HashSet< Key, Hash >::HashSet(), HashSet< labelPairPair >::HashSet(), HashSet< Key, Hash >::HashSet(), HashSet< Key, Hash >::HashSet(), MassTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), if(), viewFactor::initialise(), Foam::inplaceMapKey(), HashSet< Key, Hash >::insert(), edge::insert(), leastSquaresEdgeInterpolation< Type >::interpolate(), treeBoundBox::intersects(), cellFeatures::isFeaturePoint(), labelRange::labels(), sliceRange::labels(), Foam::makeIdentity(), HashSet< labelPairPair >::merge(), HashTable< T, Key, Hash >::merge(), slidingInterface::modifyMotionPoints(), line< Point, PointRef >::nearestDist(), triangle< Point, PointRef >::nearestPoint(), Foam::operator-(), Foam::operator-(), Foam::operator/(), HashSet< Key, Hash >::operator=(), HashSet< Key, Hash >::operator=(), SortableList< T >::partialReverseSort(), SortableListDRGEP< Type >::partialSort(), SortableListEFA< Type >::partialSort(), SortableList< T >::partialSort(), primitiveMesh::pointCells(), Foam::polyMeshZipUpCells(), bitSet::set(), bitSet::set(), bitSet::set(), Foam::BitOps::set(), tetDecomposer::setRefinement(), duplicatePoints::setRefinement(), Foam::shuffle(), SortList< T >::sort(), Foam::sort(), extendedEdgeMesh::sortPointsAndEdges(), split(), Foam::stableSort(), Foam::stableSort(), HashSet< Key, Hash >::unset(), bitSet::unset(), HashSet< Key, Hash >::unset(), bitSet::unset(), and bitSet::unset().
cbegin()
template<class T > Foam::UPtrList< T >::const_iterator cbegin () const inline
Definition at line 425 of file UPtrListI.H.
Referenced by Foam::PstreamDetail::allToAllConsensus(), multiphaseInterSystem::alphaEff(), multiphaseInterSystem::alphaEff(), Foam::FieldOps::assign(), Foam::FieldOps::assign(), IndirectListBase< T, Addr >::begin(), treeDataEdge::boxes(), Foam::boxesImpl(), Foam::boxesImpl(), valueAverageBase::calc(), fieldAverageItem::calculateMeanField(), fieldAverageItem::calculatePrime2MeanField(), HashSet< Key, Hash >::cbegin(), IndirectListBase< T, Addr >::cbegin(), Foam::clamp(), Foam::clamp(), PrecisionAdaptor< Type, InputType, Container >::commit(), multiphaseInterSystem::Cp(), multiphaseInterSystem::Cp(), multiphaseInterSystem::CpByCpv(), multiphaseInterSystem::CpByCpv(), multiphaseInterSystem::Cpv(), multiphaseInterSystem::Cpv(), dictionary::csearch(), multiphaseInterSystem::Cv(), multiphaseInterSystem::Cv(), faMeshDecomposition::decomposeMesh(), functionObjectList::end(), HashTable< T, Key, Hash >::erase(), functionObjectList::execute(), Foam::extractValues(), Foam::extractValues(), multiphaseInterSystem::gamma(), multiphaseInterSystem::generatePhi(), HashSet< Key, Hash >::HashSet(), HashTable< T * >::HashTable(), multiphaseInterSystem::hc(), Foam::Im(), Foam::Im(), multiphaseInterSystem::kappa(), multiphaseInterSystem::kappa(), cell::labels(), Pstream::mapCombineGather(), Foam::max(), multiphaseSystem::maxDiffNo(), Foam::min(), multiphaseInterSystem::mu(), multiphaseInterSystem::mu(), multivariateScheme< Type, Scheme >::multivariateScheme(), multivariateSelectionScheme< Type >::multivariateSelectionScheme(), multiphaseSystem::nu(), multiphaseInterSystem::nu(), multiphaseSystem::nu(), multiphaseInterSystem::nu(), Foam::operator*(), Foam::operator+(), Foam::operator+(), Matrix< Form, Type >::operator+=(), Foam::operator-(), Foam::operator-(), Foam::operator-(), Foam::operator-(), Matrix< Form, Type >::operator-=(), Foam::operator/(), UList< T >::operator<(), Foam::operator<<(), LPtrList< LListBase, T >::operator=(), Matrix< Form, Type >::operator=(), UILList< LListBase, T >::operator=(), HashSet< Key, Hash >::operator==(), UILList< LListBase, T >::operator==(), Foam::MatrixTools::pinv(), PtrList< T >::PtrList(), Foam::Re(), Foam::Re(), Foam::ReImSum(), Foam::ReImSum(), multiphaseSystem::rho(), multiphaseInterSystem::rho(), phaseSystem::rho(), multiphaseSystem::rho(), multiphaseInterSystem::rho(), ConstPrecisionAdaptor< Type, InputType, Container >::select(), Foam::stringOps::split(), Foam::stringOps::split(), Foam::stringOps::splitAny(), Foam::stringOps::splitFixed(), exprResultGlobals::Table::Table(), phaseSystem::U(), UILList< LListBase, T >::UILList(), exprResultDelayed::updateReadValue(), regionSizeDistribution::write(), and Matrix< RectangularMatrix< Type >, Type >::~Matrix().
cend()
template<class T > Foam::UPtrList< T >::const_iterator cend () const inline noexcept
Definition at line 449 of file UPtrListI.H.
Referenced by multiphaseInterSystem::addInterfacePorosity(), Foam::PstreamDetail::allToAllConsensus(), Foam::FieldOps::assign(), Foam::FieldOps::assign(), treeDataEdge::boxes(), Foam::boxesImpl(), Foam::boxesImpl(), genericRagelLemonDriver::cbegin(), IndirectListBase< T, Addr >::cend(), genericRagelLemonDriver::cend(), PrecisionAdaptor< Type, InputType, Container >::commit(), IndirectListBase< T, Addr >::end(), HashTable< T, Key, Hash >::erase(), multiphaseInterSystem::generatePhi(), HashSet< Key, Hash >::HashSet(), HashTable< T * >::HashTable(), Foam::Im(), Foam::Im(), cell::labels(), Pstream::mapCombineGather(), Foam::max(), Foam::min(), multiphaseInterSystem::nearInterface(), Foam::operator*(), Foam::operator+(), Foam::operator+(), Foam::operator-(), Foam::operator-(), UList< T >::operator<(), Foam::operator<<(), LPtrList< LListBase, T >::operator=(), Matrix< Form, Type >::operator=(), UILList< LListBase, T >::operator=(), HashSet< Key, Hash >::operator==(), Foam::MatrixTools::pinv(), PtrList< T >::PtrList(), Foam::Re(), Foam::Re(), Foam::ReImSum(), Foam::ReImSum(), phaseSystem::rho(), ConstPrecisionAdaptor< Type, InputType, Container >::select(), Foam::stringOps::split(), Foam::stringOps::split(), Foam::stringOps::splitAny(), Foam::stringOps::splitFixed(), multiphaseInterSystem::surfaceTensionForce(), exprResultGlobals::Table::Table(), phaseSystem::U(), UILList< LListBase, T >::UILList(), and Matrix< RectangularMatrix< Type >, Type >::~Matrix().
begin() [2/2]
template<class T > Foam::UPtrList< T >::const_iterator begin () const inline
Definition at line 417 of file UPtrListI.H.
end() [2/2]
template<class T > Foam::UPtrList< T >::const_iterator end () const inline noexcept
Definition at line 441 of file UPtrListI.H.
setSize()
template<class T > void setSize (const label n) inline
Definition at line 614 of file UPtrList.H.
References UPtrList< T >::resize().
Referenced by lduPrimitiveMesh::lduPrimitiveMesh(), lduPrimitiveMesh::lduPrimitiveMesh(), multiphaseSystem::multiphaseSystem(), searchableSurfaceCollection::searchableSurfaceCollection(), fvMatrix< Type >::setInterfaces(), and oversetFvMeshBase::updateAddressing().
first() [1/2]
template<class T > T & first () inline
Definition at line 618 of file UPtrList.H.
References UPtrList< T >::front().
Referenced by boundBox::add(), snappyLayerDriver::addLayers(), snappyLayerDriver::addLayersSinglePass(), argList::addOptionCompat(), globalIndexAndTransform::addToTransformIndex(), manualGAMGProcAgglomeration::agglomerate(), SubStrings< StringType >::append(), equationMaxIterCondition::apply(), preserveBaffles::apply(), snappySnapDriver::avgCellCentres(), meshRefinement::balance(), PDRblock::blockMeshDict(), faMesh::boundaryProcs(), faPatch::boundaryProcs(), faMesh::boundaryProcSizes(), faPatch::boundaryProcSizes(), PrimitivePatch< FaceList, PointField >::box(), cell::box(), face::box(), Foam::broadcastFile_single(), SurfaceFilmModel< CloudType >::cacheFilmFields(), valueAverageBase::calc(), curvatureSeparation::calcInvR1(), fieldMinMax::calcMinMaxFieldType(), DarcyForchheimer::calcTransformModelData(), correctedCellVolumeWeightMethod::calculateAddressing(), parcelSelection::calculateFilter(), fieldAverageItem::calculateMeanField(), interpolation2DTable< Type >::check(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFaceSkewness(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceWeights(), objectRegistry::checkIn(), TableBase< Type >::checkMaxBounds(), TableBase< Type >::checkMinBounds(), polyMeshGeometry::checkVolRatio(), commSchedule::commSchedule(), Pair< T >::compare(), faPatchData::comparePatchPair(), polyLine::concat(), ConstantRateDevolatilisation< CloudType >::ConstantRateDevolatilisation(), constantNucleation::correct(), wallBoiling::correct(), injectionModelList::correct(), multiWorldConnections::createComms(), pimpleControl::criteriaSatisfied(), simpleControl::criteriaSatisfied(), dictionary::csearchCompat(), Distribution< Type >::cumulativeNormalised(), Distribution< Type >::cumulativeRaw(), decompositionMethod::decompose(), snappyRefineDriver::doRefine(), face::edges(), triFace::edges(), pairPotential::energyTable(), Foam::stringOps::evaluate(), Foam::PstreamDetail::exchangeBuf(), Foam::PstreamDetail::exchangeChunkedBuf(), Foam::PstreamDetail::exchangeConsensus(), Foam::PstreamDetail::exchangeConsensus(), masterUncollatedFileOperation::exists(), FaceInteraction< CloudType >::FaceInteraction(), Foam::faceNij(), fileOperation::filePath(), uncollatedFileOperation::filePathInfo(), masterUncollatedFileOperation::filePathInfo(), distanceSurface::filterKeepNearestRegions(), TimePaths::findClosestTime(), shellSurfaces::findDirectionalLevel(), patchProbes::findElements(), mappedPatchBase::findLocalSamples(), distributedTriSurfaceMesh::findNearest(), instant::findRange(), mappedPatchBase::findSamples(), fileOperation::findTimes(), pairPotential::forceTable(), multiphaseInterSystem::generatePairs(), phaseSystem::generatePairs(), phaseSystem::generatePairsAndSubModels(), multiphaseInterSystem::generatePairsTable(), Foam::getCommPattern(), weightedPosition::getPoints(), triSurfaceMeshPointSet::getRefPoint(), globalIndexAndTransform::globalIndexAndTransform(), FaceCellWave< Type, TrackingData >::handleExplicitConnections(), HashTable< T, Key, Hash >::HashTable(), if(), if(), argList::ignoreOptionCompat(), globalIndexAndTransform::index(), RecycleInteraction< CloudType >::info(), TableBase< Type >::initialise(), SurfaceFilmModel< CloudType >::injectParticles(), linearInterpolationWeights::integrationWeights(), surfaceInterpolate::interpolateFields(), isoSurfaceTopo::interpolateTemplate(), interpolationTable< Type >::interpolateValue(), interpolationTable< scalar >::interpolationTable(), TableBase< Type >::interpolator(), meshToMeshMethod::interVolAndCentroid(), isoSurfaceTopo::isoSurfaceTopo(), LangmuirHinshelwoodReactionRate::LangmuirHinshelwoodReactionRate(), triSurfaceLoader::load(), fileOperation::lookupAndCacheProcessorsPath(), volSurfaceMapping::mapToSurface(), volSurfaceMapping::mapToSurface(), volSurfaceMapping::mapToSurface(), volSurfaceMapping::mapToSurface(), volSurfaceMapping::mapToVolume(), volSurfaceMapping::mapToVolumePatch(), faPatchData::matchPatchPair(), solutionControl::maxTypeResidual(), distribution::median(), Distribution< Type >::median(), meshRefinement::mergeBaffles(), slidingInterface::modifyMotionPoints(), nastranWriter::nastranWriter(), processorTopology::New(), distribution::normalised(), Distribution< Type >::normalised(), distribution::normalisedShifted(), scalars::operation(), weightedPosition::operator()(), Pair< T >::symmHasher::operator()(), minFirstOp< T1 >::operator()(), maxFirstOp< T1 >::operator()(), interpolation2DTable< Type >::operator()(), Hash< std::pair< T1, T2 > >::operator()(), minFirstOp< T1 >::operator()(), maxFirstOp< T1 >::operator()(), Hash< Tuple2< T1, T2 > >::operator()(), mappedPatchBase::nearestWorldEqOp::operator()(), Foam::operator*(), Foam::operator+(), forceSuSp::operator+=(), forceSuSp::operator-=(), Foam::operator<(), Foam::operator<(), Foam::operator<<(), Foam::operator<<(), HashTable< T, Key, Hash >::operator=(), Foam::operator==(), Foam::operator==(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Pair< T >::Pair(), Pair< T >::Pair(), argList::parse(), ParticleCollector< CloudType >::ParticleCollector(), weightedPosition::plusEqOp(), PopulationBalancePhaseSystem< BasePhaseSystem >::PopulationBalancePhaseSystem(), BSpline::position(), CatmullRomSpline::position(), BSpline::position(), CatmullRomSpline::position(), filmTurbulenceModel::primaryRegionFriction(), argList::printCompat(), Foam::printDOT(), Foam::printTable(), particleDistribution::processField(), collatedFileOperation::processorsDir(), projectFace::project(), noiseModel::PSDf(), noiseFFT::PSDf(), distribution::raw(), Distribution< Type >::raw(), face::rcEdges(), triFace::rcEdges(), cloudSolution::read(), timeActivatedFileUpdate::read(), patchProbes::read(), tabulated6DoFAcceleration::read(), surfaceFieldValue::read(), fluxSummary::read(), nearWallFields::read(), dataCloud::read(), vtkCloud::read(), velocityDampingConstraint::read(), acousticDampingSource::read(), explicitPorositySource::read(), multiphaseMangrovesSource::read(), tabulated6DoFMotion::read(), dynamicRefineFvMesh::readDict(), ensightSurfaceReader::readField(), functionObjectList::readFunctionObject(), ensightSurfaceReader::readGeometry(), ensightSurfaceReader::readGeometryHeader(), functionEntry::readStringList(), RectangularMatrix< scalar >::RectangularMatrix(), RecycleInteraction< CloudType >::RecycleInteraction(), refinementParameters::refinementParameters(), searchableDisk::regions(), searchablePlate::regions(), searchableSphere::regions(), profilingPstream::report(), faMeshBoundaryHalo::reset(), objectRegistry::resetCacheTemporaryObject(), Foam::reverse(), MappedFile< Type >::rmap(), timeVaryingMappedFixedValuePointPatchField< Type >::rmap(), triSurfaceLoader::select(), cloudSolution::semiImplicit(), Foam::setBlockFaceCorrespondence(), Time::setControls(), faceSetOption::setFaceSelection(), weightedPosition::setPoints(), InflationInjection< CloudType >::setProperties(), equationInitialResidualCondition::setResidual(), shellSurfaces::shellSurfaces(), CrankNicolson::solve(), Newmark::solve(), symplectic::solve(), meshRefinement::splitFacesUndo(), Foam::stringOps::splitFunctionArgs(), SquareMatrix< scalar >::SquareMatrix(), SquareMatrix< scalar >::SquareMatrix(), thirdBodyEfficiencies::thirdBodyEfficiencies(), wallBoundedStreamLine::track(), globalIndexAndTransform::transformIndicesForPatches(), outletMappedUniformInletFvPatchField< Type >::updateCoeffs(), timeVaryingMappedFixedValuePointPatchField< Type >::updateCoeffs(), exprResultDelayed::updateReadValue(), solverInfo::updateSolverInfo(), Polynomial< Type >::userTimeToTime(), TableBase< Type >::userTimeToTime(), Distribution< Type >::validLimits(), colourTable::value(), TableBase< Type >::value(), MappedFile< Type >::value(), cuttingSurfaceBase::walkCellCuts(), distribution::write(), ABAQUSsurfaceFormat< Face >::write(), Distribution< Type >::write(), OBJstream::write(), OBJstream::write(), mesh::write(), LangmuirHinshelwoodReactionRate::write(), thirdBodyEfficiencies::write(), pairPotential::writeEnergyAndForceTables(), RecycleInteraction< CloudType >::writeFileHeader(), noiseModel::writeFileHeader(), AABBTree< Type >::writeOBJ(), TableBase< Type >::x(), and meshRefinement::zonify().
first() [2/2]
template<class T > const T & first () const inline
Definition at line 622 of file UPtrList.H.
References UPtrList< T >::front().
last() [1/2]
template<class T > T & last () inline
Definition at line 626 of file UPtrList.H.
References UPtrList< T >::back().
Referenced by tabulated6DoFAcceleration::acceleration(), columnFvMeshInfo::addLocalPatches(), HashSet< Key, Hash >::assignMany(), TableBase< Type >::checkMaxBounds(), TableBase< Type >::checkMinBounds(), fileName::component(), hexRef8::consistentSlowRefinement(), wallBoiling::correct(), List< Type >::create(), pimpleControl::criteriaSatisfied(), metisLikeDecomp::decomposeGeneral(), faMeshDistributor::distribute(), edgeSurface::edgeSurface(), TimePaths::findClosestTime(), searchableBox::findLineAll(), searchableRotatedBox::findLineAll(), searchableExtrudedCircle::findParametricNearest(), FreeStream< CloudType >::inflow(), distribution::insertMissingKeys(), linearInterpolationWeights::integrationWeights(), wallBoundedStreamLineParticle::interpolateFields(), interpolationTable< Type >::interpolateValue(), isoSurfaceTopo::isoSurfaceTopo(), volSurfaceMapping::mapInternalToSurface(), CollisionRecordList< PairType, WallType >::matchPairRecord(), CollisionRecordList< PairType, WallType >::matchWallRecord(), solutionControl::maxTypeResidual(), sampledSet::iNewCapture::operator()(), sampledSurface::iNewCapture::operator()(), SprayCloud< CloudType >::penetration(), polyline::polyline(), Foam::polyMeshZipUpCells(), BSpline::position(), CatmullRomSpline::position(), BSpline::position(), CatmullRomSpline::position(), projectCurveEdge::position(), projectEdge::position(), GAMGAgglomeration::procAgglomerateRestrictAddressing(), collatedFileOperation::processorsDir(), projectFace::project(), noiseModel::PSDf(), noiseFFT::PSDf(), regIOobject::readIfModified(), particle< Type >::readObjects(), Time::setControls(), fvMatrix< Type >::setInterfaces(), patchInjectionBase::setPositionAndCell(), addPatchCellLayer::setRefinement(), createShellMesh::setRefinement(), masterUncollatedFileOperation::setTime(), searchableSurfaceCollection::size(), exprResultDelayed::storeValue(), tabulated6DoFMotion::transformation(), cuttingSurfaceBase::walkCellCuts(), propellerInfo::writeAxialWake(), and propellerInfo::writeWake().
last() [2/2]
template<class T > const T & last () const inline
Definition at line 630 of file UPtrList.H.
References UPtrList< T >::back().
append() [1/2]
template<class T > void append (T * ptr) inline
Definition at line 634 of file UPtrList.H.
References UPtrList< T >::push_back().
Referenced by AveragingMethod< Type >::AveragingMethod().
append() [2/2]
template<class T > void append (UPtrList< T > && other) inline
Definition at line 638 of file UPtrList.H.
References UPtrList< T >::push_back().
Friends And Related Symbol Documentation
Iterator< true >
template<class T > friend class Iterator< true > friend
Definition at line 376 of file UPtrList.H.
Iterator< false >
template<class T > friend class Iterator< false > friend
Definition at line 376 of file UPtrList.H.
operator<<
template<class T > Ostream & operator<< (Ostream & os, const UPtrList< T > & list) friend
Member Data Documentation
ptrs_
template<class T > Detail::PtrListDetail<T> ptrs_ protected
Definition at line 107 of file UPtrList.H.
Referenced by UPtrList< CloudFunctionObject< CloudType > >::back(), UPtrList< T >::begin_ptr(), PtrList< T >::clone(), UPtrList< T >::end_ptr(), UPtrList< T >::find_next(), UPtrList< T >::operator=(), PtrList< T >::PtrList(), PtrList< T >::PtrList(), UPtrList< T >::swap(), UPtrList< CloudFunctionObject< CloudType > >::UPtrList(), and UPtrList< T >::UPtrList().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashTable/HashTable.H
src/OpenFOAM/containers/PtrLists/UPtrList/UPtrList.H
src/OpenFOAM/containers/PtrLists/UPtrList/UPtrList.C
src/OpenFOAM/containers/PtrLists/UPtrList/UPtrListI.H