OpenFOAM: mappedVariableThicknessWallPolyPatch Class Reference
mappedVariableThicknessWallPolyPatch Class Reference
Foam::mappedVariableThicknessWallPolyPatch.
#include <mappedVariableThicknessWallPolyPatch.H>
Public Member Functions
TypeName ("mappedWallVariableThickness")
mappedVariableThicknessWallPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
mappedVariableThicknessWallPolyPatch (const word &name, const label size, const label start, const label index, const word &sampleRegion, const mappedPatchBase::sampleMode mode, const word &samplePatch, const vectorField &offset, const polyBoundaryMesh &bm)
mappedVariableThicknessWallPolyPatch (const word &name, const label size, const label start, const label index, const word &sampleRegion, const mappedPatchBase::sampleMode mode, const word &samplePatch, const vector &offset, const polyBoundaryMesh &bm)
mappedVariableThicknessWallPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
mappedVariableThicknessWallPolyPatch (const mappedVariableThicknessWallPolyPatch &, const polyBoundaryMesh &)
mappedVariableThicknessWallPolyPatch (const mappedVariableThicknessWallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
mappedVariableThicknessWallPolyPatch (const mappedVariableThicknessWallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
virtual ~mappedVariableThicknessWallPolyPatch ()=default
scalarField & thickness () noexcept
const scalarField & thickness () const noexcept
void write (Ostream &) const
Public Member Functions inherited from mappedWallPolyPatch
TypeName ("mappedWall")
mappedWallPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
mappedWallPolyPatch (const word &name, const label size, const label start, const label index, const word &sampleRegion, const mappedPatchBase::sampleMode mode, const word &samplePatch, const vectorField &offset, const polyBoundaryMesh &bm)
mappedWallPolyPatch (const word &name, const label size, const label start, const label index, const word &sampleRegion, const mappedPatchBase::sampleMode mode, const word &samplePatch, const vector &offset, const polyBoundaryMesh &bm)
mappedWallPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
mappedWallPolyPatch (const mappedWallPolyPatch &, const polyBoundaryMesh &)
mappedWallPolyPatch (const mappedWallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
mappedWallPolyPatch (const mappedWallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
virtual void newInternalProcFaces (label &iFaces, label &pFaces) const
virtual const labelUList & nbrCells () const
virtual label neighbPolyPatchID () const
virtual refPtr< labelListList > mapCollocatedFaces () const
virtual bool masterImplicit () const
virtual word neighbRegionID () const
virtual ~mappedWallPolyPatch ()
Public Member Functions inherited from wallPolyPatch
TypeName ("wall")
wallPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
wallPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
wallPolyPatch (const wallPolyPatch &, const polyBoundaryMesh &)
wallPolyPatch (const wallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
wallPolyPatch (const wallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Public Member Functions inherited from polyPatch
TypeName ("patch")
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &physicalType, const wordList &inGroups)
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
polyPatch (const polyPatch &, const polyBoundaryMesh &)
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
polyPatch (const polyPatch &p)
polyPatch (const polyPatch &p, const labelList &faceCells)
virtual autoPtr< polyPatch > clone (const labelList &faceCells) const
virtual ~polyPatch ()
label offset () const noexcept
label start () const noexcept
labelRange range () const
const polyBoundaryMesh & boundaryMesh () const noexcept
virtual bool coupled () const
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
template<class T >
const List< T >::subList patchSlice (const UList< T > &values) const
template<class T >
const List< T >::subList boundarySlice (const List< T > &values) const
template<class T >
const Field< T >::subField patchSlice (const Field< T > &values) const
const vectorField::subField faceCentres () const
const vectorField::subField faceAreas () const
tmp< vectorField > faceCellCentres () const
tmp< scalarField > areaFraction () const
const labelUList & faceCells () const
const labelList & meshEdges () const
virtual void clearAddressing ()
label whichFace (const label facei) const noexcept
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
virtual bool changeTopology () const
virtual bool setTopology (polyTopoChange &)
void operator= (const polyPatch &)
Public Member Functions inherited from patchIdentifier
patchIdentifier (const patchIdentifier &)=default
patchIdentifier & operator= (const patchIdentifier &)=default
virtual ~patchIdentifier ()=default
patchIdentifier ()
patchIdentifier (const word &name, const label index)
patchIdentifier (const word &name, const label index, const word &physicalType, const wordList &inGroups=wordList())
patchIdentifier (const word &name, const dictionary &dict, const label index)
patchIdentifier (const patchIdentifier &ident, const label index)
const word & name () const noexcept
word & name () noexcept
label index () const noexcept
label & index () noexcept
const word & physicalType () const noexcept
word & physicalType () noexcept
const wordList & inGroups () const noexcept
wordList & inGroups () noexcept
bool inGroup (const word &name) const
void write (Ostream &os) const
Public Member Functions inherited from PrimitivePatch< FaceList, PointField >
PrimitivePatch (const FaceList &faces, const PointField &points)
PrimitivePatch (FaceList &&faces, const PointField &points)
PrimitivePatch (FaceList &faces, PointField &points, const bool reuse)
PrimitivePatch (const PrimitivePatch< FaceList, PointField > &pp)
virtual ~PrimitivePatch ()
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
const Field< point_type > & points () const noexcept
label nFaces () const noexcept
label nPoints () const
label nEdges () const
const edgeList & edges () const
const edgeList::subList internalEdges () const
const edgeList::subList boundaryEdges () const
label nInternalEdges () const
label nBoundaryEdges () const
bool isInternalEdge (const label edgei) const
const labelList & boundaryPoints () const
const labelListList & faceFaces () const
const labelListList & edgeFaces () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointFaces () const
const List< face_type > & localFaces () const
labelList boundaryFaces () const
labelList uniqBoundaryFaces () const
const labelList & meshPoints () const
const Map< label > & meshPointMap () const
const Field< point_type > & localPoints () const
const labelList & localPointOrder () const
label whichPoint (const label gp) const
edge meshEdge (const label edgei) const
edge meshEdge (const edge &e) const
label findEdge (const edge &e) const
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
label meshEdge (const label edgei, const edgeList &allEdges, const labelListList &pointEdges) const
labelList meshEdges (const labelUList &edgeLabels, const edgeList &allEdges, const labelListList &pointEdges) const
const Field< point_type > & faceCentres () const
const Field< point_type > & faceAreas () const
const Field< scalar > & magFaceAreas () const
const Field< point_type > & faceNormals () const
const Field< point_type > & pointNormals () const
Pair< point_type > box () const
scalar sphere (const label facei) const
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
bool hasBoundaryPoints () const
bool hasEdges () const
bool hasFaceFaces () const
bool hasEdgeFaces () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointFaces () const
bool hasMeshPoints () const
bool hasMeshPointMap () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
const labelListList & edgeLoops () const
surfaceTopo surfaceType (labelHashSet *badEdgesPtr=nullptr) const
bool checkTopology (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
bool checkPointManifold (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
void operator= (const PrimitivePatch< FaceList, PointField > &rhs)
void operator= (PrimitivePatch< FaceList, PointField > &&rhs)
label whichEdge (const edge &e) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Public Member Functions inherited from PrimitivePatchBase
ClassName ("PrimitivePatch")
PrimitivePatchBase ()=default
Public Member Functions inherited from mappedPatchBase
TypeName ("mappedPatchBase")
mappedPatchBase (const polyPatch &)
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vectorField &offsets)
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vector &uniformOffset)
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const scalar normalDistance)
mappedPatchBase (const polyPatch &, const dictionary &)
mappedPatchBase (const polyPatch &, const sampleMode, const dictionary &)
mappedPatchBase (const polyPatch &, const mappedPatchBase &)
mappedPatchBase (const polyPatch &, const mappedPatchBase &, const labelUList &mapAddressing)
virtual ~mappedPatchBase ()
void clearOut ()
void setOffset (const scalar normalDist)
void setOffset (const vector &uniformOffset)
void setOffset (const vectorField &offsets)
sampleMode mode () const noexcept
const word & sampleWorld () const noexcept
const word & sampleRegion () const
const word & samplePatch () const
const word & coupleGroup () const
label sampleSize () const
const vector & offset () const noexcept
const vectorField & offsets () const noexcept
label getCommunicator () const
label comm () const
bool sameWorld () const
bool masterWorld () const
bool sameRegion () const noexcept
uniformDimensionedScalarField & updateSampleMeshTime () const
uniformDimensionedScalarField & updateMeshTime () const
bool upToDate () const
const mapDistribute & map () const
const AMIPatchToPatchInterpolation & AMI (const bool forceUpdate=false) const
bool owner () const
const autoPtr< Foam::searchableSurface > & surfPtr () const
const polyMesh & sampleMesh () const
const polyPatch & samplePolyPatch () const
tmp< pointField > samplePoints () const
const fileName & sampleDatabasePath () const
bool sampleDatabase () const
virtual fileName sendPath (const label proci) const
virtual fileName receivePath (const label proci) const
template<class Type >
void distribute (List< Type > &lst) const
template<class Type , class CombineOp >
void distribute (List< Type > &lst, const CombineOp &cop) const
template<class Type >
void reverseDistribute (List< Type > &lst) const
template<class Type , class CombineOp >
void reverseDistribute (List< Type > &lst, const CombineOp &cop) const
Additional Inherited Members
Public Types inherited from PrimitivePatch< FaceList, PointField >
enum surfaceTopo { MANIFOLD , OPEN , ILLEGAL }
typedef std::remove_reference< FaceList >::type::value_type face_type
typedef std::remove_reference< PointField >::type::value_type point_type
typedef FaceList FaceListType
typedef PointField PointFieldType
typedef face_type FaceType
Public Types inherited from mappedPatchBase
enum sampleMode {
NEARESTCELL , NEARESTPATCHFACE , NEARESTPATCHFACEAMI , NEARESTPATCHPOINT ,
NEARESTFACE , NEARESTONLYCELL
}
enum offsetMode { UNIFORM , NONUNIFORM , NORMAL }
typedef Tuple2< pointIndexHit, Tuple2< scalar, label > > nearInfo
typedef Tuple2< nearInfo, label > nearInfoWorld
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
static bool constraintType (const word &patchType)
static wordList constraintTypes ()
Static Public Member Functions inherited from patchIdentifier
static word defaultName (const label n=-1)
Static Public Member Functions inherited from mappedPatchBase
static pointIndexHit facePoint (const polyMesh &, const label facei, const polyMesh::cellDecomposition)
static fileName sendPath (const fileName &root, const label proci)
static fileName receivePath (const fileName &root, const label proci)
static const objectRegistry & subRegistry (const objectRegistry &obr, const fileName &path)
template<class Type >
static void storeField (objectRegistry &obr, const word &fieldName, const Field< Type > &values)
static void writeDict (const objectRegistry &obr, dictionary &dict)
static void readDict (const dictionary &d, objectRegistry &obr)
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Static Public Attributes inherited from mappedPatchBase
static const Enum< sampleMode > sampleModeNames_
static const Enum< offsetMode > offsetModeNames_
Protected Member Functions inherited from mappedWallPolyPatch
virtual void initGeometry (PstreamBuffers &)
virtual void calcGeometry (PstreamBuffers &)
virtual void initMovePoints (PstreamBuffers &, const pointField &)
virtual void movePoints (PstreamBuffers &, const pointField &)
virtual void initUpdateMesh (PstreamBuffers &)
virtual void updateMesh (PstreamBuffers &)
Protected Member Functions inherited from polyPatch
virtual void clearGeom ()
virtual void movePoints (const Field< point_type > &)
Protected Member Functions inherited from mappedPatchBase
bool addWorldConnection ()
label getWorldCommunicator () const
const polyMesh & lookupMesh (const word &region) const
const polyPatch & lookupPatch (const word &sampleRegion, const word &samplePatch) const
tmp< pointField > facePoints (const polyPatch &) const
void collectSamples (const label mySampleWorld, const pointField &facePoints, pointField &samples, labelList &patchFaceWorlds, labelList &patchFaceProcs, labelList &patchFaces, pointField &patchFc) const
void findLocalSamples (const sampleMode mode, const label sampleWorld, const word &sampleRegion, const word &samplePatch, const pointField &samplePoints, List< nearInfoWorld > &nearest) const
void findSamples (const sampleMode mode, const label myWorldIndex, const pointField &, const labelList &wantedWorlds, const labelList &origProcs, labelList &sampleProcs, labelList &sampleIndices, pointField &sampleLocations) const
tmp< pointField > samplePoints (const pointField &) const
void calcMapping () const
void calcAMI () const
Static Protected Member Functions inherited from mappedPatchBase
static autoPtr< fileName > readDatabase (const dictionary &dict)
static const objectRegistry & subRegistry (const objectRegistry &obr, const wordList &names, const label index)
template<class Type >
static bool writeIOField (const regIOobject &obj, dictionary &dict)
template<class Type >
static bool constructIOField (const word &name, token &tok, Istream &is, objectRegistry &obr)
Protected Attributes inherited from mappedPatchBase
const polyPatch & patch_
word sampleWorld_
word sampleRegion_
const sampleMode mode_
word samplePatch_
const coupleGroupIdentifier coupleGroup_
const autoPtr< fileName > sampleDatabasePtr_
offsetMode offsetMode_
vector offset_
vectorField offsets_
scalar distance_
label communicator_
bool sameRegion_
autoPtr< mapDistribute > mapPtr_
const bool AMIReverse_
autoPtr< AMIPatchToPatchInterpolation > AMIPtr_
autoPtr< searchableSurface > surfPtr_
dictionary surfDict_
autoPtr< uniformDimensionedScalarField > updateMeshTimePtr_
autoPtr< uniformDimensionedScalarField > updateSampleMeshTimePtr_
Detailed Description
Foam::mappedVariableThicknessWallPolyPatch.
Source files
mappedVariableThicknessWallPolyPatch.H
mappedVariableThicknessWallPolyPatch.C
Definition at line 48 of file mappedVariableThicknessWallPolyPatch.H.
Constructor & Destructor Documentation
mappedVariableThicknessWallPolyPatch() [1/7]
mappedVariableThicknessWallPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType)
Definition at line 48 of file mappedVariableThicknessWallPolyPatch.C.
References Foam::name().
mappedVariableThicknessWallPolyPatch() [2/7]
mappedVariableThicknessWallPolyPatch (const word & name, const label size, const label start, const label index, const word & sampleRegion, const mappedPatchBase::sampleMode mode, const word & samplePatch, const vectorField & offset, const polyBoundaryMesh & bm)
Definition at line 63 of file mappedVariableThicknessWallPolyPatch.C.
mappedVariableThicknessWallPolyPatch() [3/7]
mappedVariableThicknessWallPolyPatch (const word & name, const label size, const label start, const label index, const word & sampleRegion, const mappedPatchBase::sampleMode mode, const word & samplePatch, const vector & offset, const polyBoundaryMesh & bm)
Definition at line 81 of file mappedVariableThicknessWallPolyPatch.C.
mappedVariableThicknessWallPolyPatch() [4/7]
mappedVariableThicknessWallPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Definition at line 99 of file mappedVariableThicknessWallPolyPatch.C.
mappedVariableThicknessWallPolyPatch() [5/7]
mappedVariableThicknessWallPolyPatch (const mappedVariableThicknessWallPolyPatch & pp, const polyBoundaryMesh & bm)
Definition at line 113 of file mappedVariableThicknessWallPolyPatch.C.
mappedVariableThicknessWallPolyPatch() [6/7]
mappedVariableThicknessWallPolyPatch (const mappedVariableThicknessWallPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart)
Definition at line 125 of file mappedVariableThicknessWallPolyPatch.C.
mappedVariableThicknessWallPolyPatch() [7/7]
mappedVariableThicknessWallPolyPatch (const mappedVariableThicknessWallPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Definition at line 139 of file mappedVariableThicknessWallPolyPatch.C.
~mappedVariableThicknessWallPolyPatch()
virtual ~mappedVariableThicknessWallPolyPatch () virtual default
Member Function Documentation
TypeName()
TypeName ("mappedWallVariableThickness")
clone() [1/3]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm) const inline virtual
Reimplemented from mappedWallPolyPatch.
Definition at line 145 of file mappedVariableThicknessWallPolyPatch.H.
clone() [2/3]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Reimplemented from mappedWallPolyPatch.
Definition at line 155 of file mappedVariableThicknessWallPolyPatch.H.
References patchIdentifier::index().
clone() [3/3]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Reimplemented from mappedWallPolyPatch.
Definition at line 178 of file mappedVariableThicknessWallPolyPatch.H.
References patchIdentifier::index().
thickness() [1/2]
scalarField & thickness () inline noexcept
Definition at line 207 of file mappedVariableThicknessWallPolyPatch.H.
thickness() [2/2]
const scalarField & thickness () const inline noexcept
Definition at line 210 of file mappedVariableThicknessWallPolyPatch.H.
write()
void write (Foam::Ostream & os) const virtual
Reimplemented from mappedWallPolyPatch.
Definition at line 155 of file mappedVariableThicknessWallPolyPatch.C.
References os(), and Ostream::writeEntry().
The documentation for this class was generated from the following files:
src/meshTools/mappedPatches/mappedPolyPatch/mappedVariableThicknessWallPolyPatch.H
src/meshTools/mappedPatches/mappedPolyPatch/mappedVariableThicknessWallPolyPatch.C