OpenFOAM: block Class Reference
block Class Reference
Creates a single block of cells from point coordinates, numbers of cells in each direction and an expansion ratio.
#include <block.H>
Classes
class iNew
Public Member Functions
TypeName ("block")
declareRunTimeSelectionTable (autoPtr, block, Istream,(const dictionary &dict, const label index, const pointField &vertices, const blockEdgeList &edges, const blockFaceList &faces, Istream &is),(dict, index, vertices, edges, faces, is))
block (const cellShape &bshape, const pointField &vertices, const blockEdgeList &edges, const blockFaceList &faces, const labelVector &density, const UList< gradingDescriptors > &expand=UList< gradingDescriptors >::null(), const word &zoneName="")
block (const dictionary &dict, const label index, const pointField &vertices, const blockEdgeList &edges, const blockFaceList &faces, Istream &is)
block (const blockDescriptor &blockDesc)
autoPtr< block > clone () const
virtual ~block ()=default
const pointField & points () const noexcept
const List< hexCell > & cells () const
const FixedList< List< FixedList< label, 4 > >, 6 > & boundaryPatches () const noexcept
cellShapeList shapes () const
Public Member Functions inherited from blockDescriptor
blockDescriptor (const blockDescriptor &)=default
void operator= (const blockDescriptor &)=delete
blockDescriptor (const cellShape &bshape, const pointField &vertices, const blockEdgeList &edges, const blockFaceList &faces, const labelVector &density, const UList< gradingDescriptors > &expand=UList< gradingDescriptors >::null(), const word &zoneName=word::null)
blockDescriptor (const dictionary &dict, const label blockIndex, const pointField &vertices, const blockEdgeList &edges, const blockFaceList &faces, Istream &is)
const pointField & vertices () const noexcept
const blockFaceList & blockFaces () const noexcept
const cellShape & blockShape () const noexcept
const labelVector & density () const noexcept
const List< gradingDescriptors > & grading () const noexcept
const word & zoneName () const noexcept
const FixedList< label, 6 > & curvedFaces () const noexcept
label nCurvedFaces () const noexcept
const point & blockPoint (const label i) const
label facePointLabel (const direction facei, const label i, const label j) const
bool vertex (const label i, const label j, const label k) const
bool edge (const label i, const label j, const label k) const
int edgesPointsWeights (pointField(&edgesPoints)[12], scalarList(&edgesWeights)[12]) const
bool edgePointsWeights (const label edgei, pointField &edgePoints, scalarList &edgeWeights, const label nDiv, const gradingDescriptors &gd=gradingDescriptors()) const
bool edgePointsWeights (const label edgei, pointField &edgePoints, scalarList &edgeWeights) const
bool flatFaceOrEdge (const label i, const label j, const label k) const
FixedList< pointField, 6 > facePoints (const pointField &points) const
void correctFacePoints (FixedList< pointField, 6 > &) const
InfoProxy< blockDescriptor > info () const noexcept
Public Member Functions inherited from ijkMesh
ijkMesh ()
ijkMesh (const labelVector &ijk)
ijkMesh (const label nx, const label ny, const label nz)
label nPoints () const
label nCells () const
label nFaces () const
label nInternalFaces () const
label nBoundaryFaces () const
label nBoundaryFaces (const direction shapeFacei) const
label cellLabel (const label i, const label j, const label k) const
label cellLabel (const labelVector &ijk) const
label pointLabel (const label i, const label j, const label k) const
label pointLabel (const labelVector &ijk) const
hexCell vertLabels (const label i, const label j, const label k) const
hexCell vertLabels (const labelVector &ijk) const
Public Member Functions inherited from ijkAddressing
ijkAddressing ()
ijkAddressing (const labelVector &ijk)
ijkAddressing (const label ni, const label nj, const label nk)
bool empty () const
const labelVector & sizes () const
labelVector & sizes ()
label size () const
const label & size (const vector::components cmpt) const
void clear ()
void reset (const label ni, const label nj, const label nk)
void reset (const labelVector &newSizes)
label index (const label i, const label j, const label k) const
label index (const labelVector &ijk) const
labelVector index (const label idx) const
void checkIndex (const label i, const label j, const label k, const bool allowExtra=false) const
void checkIndex (const labelVector &ijk, const bool allowExtra=false) const
void checkSizes () const
void checkSizes (const labelVector &other) const
void checkSizes (const label nTotal) const
Static Public Member Functions
static autoPtr< block > New (const dictionary &dict, const label index, const pointField &points, const blockEdgeList &edges, const blockFaceList &faces, Istream &)
Static Public Member Functions inherited from blockDescriptor
static void write (Ostream &, const label blocki, const dictionary &)
Detailed Description
Creates a single block of cells from point coordinates, numbers of cells in each direction and an expansion ratio.
Note
The cells for filling the block are demand-driven.
Source files
block.H
block.C
blockCreate.C
Definition at line 54 of file block.H.
Constructor & Destructor Documentation
block() [1/3]
block (const cellShape & bshape, const pointField & vertices, const blockEdgeList & edges, const blockFaceList & faces, const labelVector & density, const UList< gradingDescriptors > & expand = UList<gradingDescriptors>::null(), const word & zoneName = "")
Definition at line 34 of file block.C.
References Foam::vertices().
block() [2/3]
block (const dictionary & dict, const label index, const pointField & vertices, const blockEdgeList & edges, const blockFaceList & faces, Istream & is)
Definition at line 56 of file block.C.
block() [3/3]
block (const blockDescriptor & blockDesc)
Definition at line 77 of file block.C.
~block()
virtual ~block () virtual default
Member Function Documentation
TypeName()
TypeName ("block")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , block , Istream , (const dictionary &dict, const label index, const pointField &vertices, const blockEdgeList &edges, const blockFaceList &faces, Istream &is) , (dict, index, vertices, edges, faces, is))
clone()
autoPtr< block > clone () const inline
Definition at line 153 of file block.H.
References NotImplemented.
New()
Foam::autoPtr< Foam::block > New (const dictionary & dict, const label index, const pointField & points, const blockEdgeList & edges, const blockFaceList & faces, Istream & is) static
Definition at line 92 of file block.C.
References DebugInFunction, dict, Foam::endl(), autoPtr< T >::New(), and points.
Referenced by block::iNew::operator()().
points()
const Foam::pointField & points () const inline noexcept
Definition at line 24 of file blockI.H.
cells()
const Foam::List< Foam::hexCell > & cells () const inline
Definition at line 30 of file blockI.H.
boundaryPatches()
const Foam::FixedList< Foam::List< Foam::FixedList< Foam::label, 4 > >, 6 > & boundaryPatches () const inline noexcept
Definition at line 42 of file blockI.H.
shapes()
Foam::cellShapeList shapes () const
Definition at line 549 of file blockCreate.C.
References k.
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blocks/block/block.H
src/mesh/blockMesh/blocks/block/block.C
src/mesh/blockMesh/blocks/block/blockCreate.C
src/mesh/blockMesh/blocks/block/blockI.H