OpenFOAM: LehrMilliesMewes Class Reference
LehrMilliesMewes Class Reference
Model of Lehr et al. (2002). The breakup rate is calculated by.
#include <LehrMilliesMewes.H>
Public Member Functions
TypeName ("LehrMilliesMewes")
LehrMilliesMewes (const populationBalanceModel &popBal, const dictionary &dict)
virtual ~LehrMilliesMewes ()=default
virtual void addToBinaryBreakupRate (volScalarField &binaryBreakupRate, const label i, const label j)
Public Member Functions inherited from binaryBreakupModel
TypeName ("binaryBreakupModel")
declareRunTimeSelectionTable (autoPtr, binaryBreakupModel, dictionary,(const populationBalanceModel &popBal, const dictionary &dict),(popBal, dict))
binaryBreakupModel (const populationBalanceModel &popBal, const dictionary &dict)
autoPtr< binaryBreakupModel > clone () const
virtual ~binaryBreakupModel ()=default
virtual void correct ()
Additional Inherited Members
Static Public Member Functions inherited from binaryBreakupModel
static autoPtr< binaryBreakupModel > New (const word &type, const populationBalanceModel &popBal, const dictionary &dict)
Protected Attributes inherited from binaryBreakupModel
const populationBalanceModel & popBal_
Detailed Description
Model of Lehr et al. (2002). The breakup rate is calculated by.
with the time scale
the dimensionless diameter
and the length scale
= Density of continuous phase [kg/m3]
= Surface tension [N/m]
= Continuous phase turbulent dissipation rate [m2/s3]
= Diameter of daughter bubble i [m]
= Diameter of mother bubble j [m]
References:
        Lehr, F., Millies, M., & Mewes, D. (2002).
        Bubble‐size distributions and flow fields in bubble columns.
        AIChE Journal, 48(11), 2426-2443.
        Eq. 12-16, p. 2429-2430.
Source files
LehrMilliesMewes.H
LehrMilliesMewes.C
Definition at line 121 of file LehrMilliesMewes.H.
Constructor & Destructor Documentation
LehrMilliesMewes()
LehrMilliesMewes (const populationBalanceModel & popBal, const dictionary & dict)
Definition at line 49 of file LehrMilliesMewes.C.
~LehrMilliesMewes()
virtual ~LehrMilliesMewes () virtual default
Member Function Documentation
TypeName()
TypeName ("LehrMilliesMewes")
addToBinaryBreakupRate()
void addToBinaryBreakupRate (volScalarField & binaryBreakupRate, const label i, const label j) virtual
Implements binaryBreakupModel.
Definition at line 61 of file LehrMilliesMewes.C.
References Foam::dimLength, Foam::erf(), Foam::exp(), L, Foam::log(), Foam::max(), Foam::pow(), Foam::pow3(), phaseModel::rho(), Foam::sqr(), Foam::sqrt(), and T.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/binaryBreakupModels/LehrMilliesMewes/LehrMilliesMewes.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/populationBalanceModel/binaryBreakupModels/LehrMilliesMewes/LehrMilliesMewes.C