OpenFOAM: fieldAverageItem Class Reference
fieldAverageItem Class Reference
Helper class to describe what form of averaging to apply. A set will be applied to each base field in Foam::fieldAverage, of the following form.
#include <fieldAverageItem.H>
Public Types
enum class baseType { ITER , TIME }
enum class windowType { NONE , APPROXIMATE , EXACT }
Public Member Functions
fieldAverageItem ()
fieldAverageItem (Istream &)
fieldAverageItem (const fieldAverageItem &)
~fieldAverageItem ()
bool active () const
bool & active ()
const word & fieldName () const
bool mean () const
bool & mean ()
const word & meanFieldName () const
void setMeanFieldName (const word &name)
bool prime2Mean () const
bool & prime2Mean ()
const word & prime2MeanFieldName () const
void setPrime2MeanFieldName (const word &name)
const word & base () const
label totalIter () const
scalar totalTime () const
scalar window () const
const word & windowName () const
const FIFOStack< scalar > & windowTimes () const
const FIFOStack< word > & windowFieldNames () const
bool allowRestart () const
scalar dt (const scalar deltaT) const
scalar Dt () const
word windowFieldName (const word &prefix) const
bool inWindow (const scalar t) const
bool storeWindowFields () const
bool writeWindowFields () const
void addToWindow (const word &fieldName, const scalar deltaT)
void evolve (const objectRegistry &obr)
void clear (const objectRegistry &obr, const bool fullClean)
bool readState (const dictionary &dict)
void writeState (dictionary &dict) const
template<class Type >
bool calculateMeanField (const objectRegistry &obr) const
template<class Type1 , class Type2 >
bool calculatePrime2MeanField (const objectRegistry &obr) const
void operator= (const fieldAverageItem &)
Static Public Attributes
static const word EXT_MEAN
static const word EXT_PRIME2MEAN
Friends
bool operator== (const fieldAverageItem &a, const fieldAverageItem &b)
bool operator!= (const fieldAverageItem &a, const fieldAverageItem &b)
Istream & operator>> (Istream &, fieldAverageItem &)
Ostream & operator<< (Ostream &, const fieldAverageItem &)
Detailed Description
Helper class to describe what form of averaging to apply. A set will be applied to each base field in Foam::fieldAverage, of the following form.
Usage
<field1>
{
    mean            on;
    prime2Mean      on;
    base            time; // iteration
    window          200;  // optional averaging window
    windowName      w1;   // optional window name (default = "")
    windowType      approximate; // window type
    allowRestart    yes;  // optional, used for windowType 'exact'
}
where the entries mean:
Property Description Type Req'd Dflt
mean Flag to calculate average bool yes -
prime2Mean Flag to calculate prime-square average bool yes -
base Type of averaging interval word yes -
window Averaging window scalar no
windowName Name of the averaging window word no ""
windowType Type of averaging window word no
allowRestart Flag to allow restart for windowType=exact bool no
Options for the base entry:
      time | Averaging interval is based on time
      iter | Averaging interval is based on iterations
Options for the windowType entry:
      none  | no windowing
      exact | allow additional files will be stored and written
      approximate | disallow additional files will be stored and written
Note
To employ the prime2Mean option, the mean option must be enabled.
Source files
fieldAverageItem.H
fieldAverageItem.C
fieldAverageItemIO.C
Definition at line 153 of file fieldAverageItem.H.
Member Enumeration Documentation
baseType
enum class baseType strong
Enumerator
ITER
TIME
Definition at line 169 of file fieldAverageItem.H.
windowType
enum class windowType strong
Enumerator
NONE
APPROXIMATE
EXACT
Definition at line 176 of file fieldAverageItem.H.
Constructor & Destructor Documentation
fieldAverageItem() [1/3]
fieldAverageItem ()
Definition at line 63 of file fieldAverageItem.C.
fieldAverageItem() [2/3]
fieldAverageItem (Istream & is)
Definition at line 28 of file fieldAverageItemIO.C.
fieldAverageItem() [3/3]
fieldAverageItem (const fieldAverageItem & faItem)
Definition at line 84 of file fieldAverageItem.C.
~fieldAverageItem()
~fieldAverageItem ()
Definition at line 110 of file fieldAverageItem.C.
Member Function Documentation
active() [1/2]
bool active () const inline
Definition at line 23 of file fieldAverageItemI.H.
active() [2/2]
bool & active () inline
Definition at line 29 of file fieldAverageItemI.H.
fieldName()
const Foam::word & fieldName () const inline
Definition at line 35 of file fieldAverageItemI.H.
Referenced by fieldAverageItem::calculateMeanField().
mean() [1/2]
bool mean () const inline
Definition at line 41 of file fieldAverageItemI.H.
mean() [2/2]
bool & mean () inline
Definition at line 47 of file fieldAverageItemI.H.
meanFieldName()
const Foam::word & meanFieldName () const inline
Definition at line 54 of file fieldAverageItemI.H.
setMeanFieldName()
void setMeanFieldName (const word & name) inline
Definition at line 60 of file fieldAverageItemI.H.
References Foam::name().
prime2Mean() [1/2]
bool prime2Mean () const inline
Definition at line 69 of file fieldAverageItemI.H.
prime2Mean() [2/2]
bool & prime2Mean () inline
Definition at line 75 of file fieldAverageItemI.H.
prime2MeanFieldName()
const Foam::word & prime2MeanFieldName () const inline
Definition at line 82 of file fieldAverageItemI.H.
setPrime2MeanFieldName()
void setPrime2MeanFieldName (const word & name) inline
Definition at line 88 of file fieldAverageItemI.H.
References Foam::name().
base()
const Foam::word & base () const inline
Definition at line 97 of file fieldAverageItemI.H.
totalIter()
Foam::label totalIter () const inline
Definition at line 103 of file fieldAverageItemI.H.
totalTime()
Foam::scalar totalTime () const inline
Definition at line 109 of file fieldAverageItemI.H.
window()
Foam::scalar window () const inline
Definition at line 115 of file fieldAverageItemI.H.
windowName()
const Foam::word & windowName () const inline
Definition at line 121 of file fieldAverageItemI.H.
windowTimes()
const Foam::FIFOStack< Foam::scalar > & windowTimes () const inline
Definition at line 128 of file fieldAverageItemI.H.
windowFieldNames()
const Foam::FIFOStack< Foam::word > & windowFieldNames () const inline
Definition at line 135 of file fieldAverageItemI.H.
allowRestart()
bool allowRestart () const inline
Definition at line 141 of file fieldAverageItemI.H.
dt()
Foam::scalar dt (const scalar deltaT) const inline
Definition at line 147 of file fieldAverageItemI.H.
References Foam::FatalError, and FatalErrorInFunction.
Referenced by fieldAverageItem::calculateMeanField().
Dt()
Foam::scalar Dt () const inline
Definition at line 174 of file fieldAverageItemI.H.
References Foam::FatalError, and FatalErrorInFunction.
Referenced by fieldAverageItem::calculateMeanField().
windowFieldName()
Foam::word windowFieldName (const word & prefix) const inline
Definition at line 198 of file fieldAverageItemI.H.
References Foam::name().
inWindow()
bool inWindow (const scalar t) const inline
Definition at line 207 of file fieldAverageItemI.H.
References Foam::FatalError, and FatalErrorInFunction.
storeWindowFields()
bool storeWindowFields () const inline
Definition at line 232 of file fieldAverageItemI.H.
writeWindowFields()
bool writeWindowFields () const inline
Definition at line 238 of file fieldAverageItemI.H.
addToWindow()
void addToWindow (const word & fieldName, const scalar deltaT)
Definition at line 116 of file fieldAverageItem.C.
evolve()
void evolve (const objectRegistry & obr)
Definition at line 127 of file fieldAverageItem.C.
References objectRegistry::checkOut(), forAllIters, UPtrList< T >::size(), and objectRegistry::time().
clear()
void clear (const objectRegistry & obr, const bool fullClean)
Definition at line 155 of file fieldAverageItem.C.
References objectRegistry::checkOut(), and PtrList< T >::clear().
readState()
bool readState (const dictionary & dict)
Definition at line 186 of file fieldAverageItem.C.
References dict.
writeState()
void writeState (dictionary & dict) const
Definition at line 201 of file fieldAverageItem.C.
References dict.
calculateMeanField()
template<class Type > bool calculateMeanField (const objectRegistry & obr) const
Definition at line 25 of file fieldAverageItemTemplates.C.
References fieldAverageItem::APPROXIMATE, beta(), LList< LListBase, T >::cbegin(), UPtrList< T >::cbegin(), fieldAverageItem::Dt(), fieldAverageItem::dt(), fieldAverageItem::EXACT, Foam::FatalError, FatalErrorInFunction, fieldAverageItem::fieldName(), objectRegistry::findObject(), LList< LListBase, T >::first(), UPtrList< T >::first(), objectRegistry::lookupObject(), objectRegistry::lookupObjectRef(), n, fieldAverageItem::NONE, and objectRegistry::time().
calculatePrime2MeanField()
template<class Type1 , class Type2 > bool calculatePrime2MeanField (const objectRegistry & obr) const
Definition at line 160 of file fieldAverageItemTemplates.C.
References beta(), UPtrList< T >::cbegin(), Foam::FatalError, FatalErrorInFunction, objectRegistry::findObject(), objectRegistry::lookupObject(), objectRegistry::lookupObjectRef(), Foam::sqr(), and objectRegistry::time().
operator=()
void operator= (const fieldAverageItem & rhs)
Definition at line 219 of file fieldAverageItem.C.
Friends And Related Symbol Documentation
operator==
bool operator== (const fieldAverageItem & a, const fieldAverageItem & b) friend
Definition at line 368 of file fieldAverageItem.H.
operator!=
bool operator!= (const fieldAverageItem & a, const fieldAverageItem & b) friend
Definition at line 390 of file fieldAverageItem.H.
operator>>
Istream & operator>> (Istream & , fieldAverageItem &) friend
operator<<
Ostream & operator<< (Ostream & , const fieldAverageItem &) friend
Member Data Documentation
EXT_MEAN
const Foam::word EXT_MEAN static
Definition at line 162 of file fieldAverageItem.H.
Referenced by Foam::functionObjects::operator>>().
EXT_PRIME2MEAN
const Foam::word EXT_PRIME2MEAN static
Definition at line 165 of file fieldAverageItem.H.
Referenced by Foam::functionObjects::operator>>().
The documentation for this class was generated from the following files:
src/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItem.H
src/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItem.C
src/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItemI.H
src/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItemIO.C
src/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItemTemplates.C