OpenFOAM: iterativeGaussGrad< Type > Class Template Reference
iterativeGaussGrad< Type > Class Template Reference
A second-order gradient scheme using face-interpolation, Gauss' theorem and iterative skew correction.
#include <iterativeGaussGrad.H>
Public Member Functions
TypeName ("iterativeGauss")
iterativeGaussGrad (const fvMesh &mesh)
iterativeGaussGrad (const fvMesh &mesh, Istream &schemeData)
virtual tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > calcGrad (const GeometricField< Type, fvPatchField, volMesh > &vsf, const word &name) const
Public Member Functions inherited from gaussGrad< Type >
TypeName ("Gauss")
gaussGrad (const fvMesh &mesh)
gaussGrad (const fvMesh &mesh, Istream &is)
Public Member Functions inherited from gradScheme< Type >
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, gradScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
gradScheme (const fvMesh &mesh)
virtual ~gradScheme ()=default
const fvMesh & mesh () const
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name) const
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from gaussGrad< Type >
static tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > gradf (const GeometricField< Type, fvsPatchField, surfaceMesh > &, const word &name)
static void correctBoundaryConditions (const GeometricField< Type, fvPatchField, volMesh > &, GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > &)
Static Public Member Functions inherited from gradScheme< Type >
static tmp< gradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Detailed Description
template<class Type>
class Foam::fv::iterativeGaussGrad< Type >
A second-order gradient scheme using face-interpolation, Gauss' theorem and iterative skew correction.
Usage
Minimal example by using system/fvSchemes:
gradSchemes
{
    grad(<term>)   iterativeGauss <interpolation scheme> <number of iters>;
}
and by using system/fvSolution:
relaxationFactors
{
    fields
    {
        grad(<term>)    <relaxation factor>;
    }
}
Source files
iterativeGaussGrad.H
iterativeGaussGrad.C
Definition at line 73 of file iterativeGaussGrad.H.
Constructor & Destructor Documentation
iterativeGaussGrad() [1/2]
template<class Type > iterativeGaussGrad (const fvMesh & mesh) inline
Definition at line 101 of file iterativeGaussGrad.H.
iterativeGaussGrad() [2/2]
template<class Type > iterativeGaussGrad (const fvMesh & mesh, Istream & schemeData) inline
Definition at line 108 of file iterativeGaussGrad.H.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
Member Function Documentation
TypeName()
template<class Type > TypeName ("iterativeGauss")
calcGrad()
template<class Type > Foam::tmp< Foam::GeometricField< typename Foam::outerProduct< Foam::vector, Type >::type, Foam::fvPatchField, Foam::volMesh > > calcGrad (const GeometricField< Type, fvPatchField, volMesh > & vsf, const word & name) const virtual
Reimplemented from gaussGrad< Type >.
Definition at line 36 of file iterativeGaussGrad.C.
References Foam::linearInterpolate(), Foam::name(), and relax().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/gradSchemes/iterativeGaussGrad/iterativeGaussGrad.H
src/finiteVolume/finiteVolume/gradSchemes/iterativeGaussGrad/iterativeGaussGrad.C