OpenFOAM: polyAddPoint Class Reference
polyAddPoint Class Reference
Class containing data for point addition.
#include <polyAddPoint.H>
Public Member Functions
TypeName ("addPoint")
polyAddPoint ()
polyAddPoint (const point &p, const label masterPointID, const label zoneID, const bool inCell)
virtual autoPtr< topoAction > clone () const
const point & newPoint () const
label masterPointID () const
bool appended () const
bool isInZone () const
label zoneID () const
bool inCell () const
Public Member Functions inherited from topoAction
TypeName ("topoAction")
topoAction ()
virtual ~topoAction ()=default
Detailed Description
Class containing data for point addition.
Definition at line 43 of file polyAddPoint.H.
Constructor & Destructor Documentation
polyAddPoint() [1/2]
polyAddPoint () inline
Definition at line 73 of file polyAddPoint.H.
Referenced by polyAddPoint::clone().
polyAddPoint() [2/2]
polyAddPoint (const point & p, const label masterPointID, const label zoneID, const bool inCell) inline
Definition at line 82 of file polyAddPoint.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, polyAddPoint::inCell(), and p.
Member Function Documentation
TypeName()
TypeName ("addPoint")
clone()
virtual autoPtr< topoAction > clone () const inline virtual
Implements topoAction.
Definition at line 108 of file polyAddPoint.H.
References polyAddPoint::polyAddPoint().
newPoint()
const point & newPoint () const inline
Definition at line 120 of file polyAddPoint.H.
masterPointID()
label masterPointID () const inline
Definition at line 126 of file polyAddPoint.H.
appended()
bool appended () const inline
Definition at line 132 of file polyAddPoint.H.
isInZone()
bool isInZone () const inline
Definition at line 138 of file polyAddPoint.H.
zoneID()
label zoneID () const inline
Definition at line 144 of file polyAddPoint.H.
inCell()
bool inCell () const inline
Definition at line 150 of file polyAddPoint.H.
Referenced by polyAddPoint::polyAddPoint().
The documentation for this class was generated from the following file:
src/meshTools/polyTopoChange/addObject/polyAddPoint.H