OpenFOAM: polyMeshFilter Class Reference
polyMeshFilter Class Reference
Remove the edges and faces of a polyMesh whilst satisfying the given mesh quality criteria.
#include <polyMeshFilter.H>
Public Member Functions
ClassName ("polyMeshFilter")
polyMeshFilter (const fvMesh &mesh)
polyMeshFilter (const fvMesh &mesh, const labelList &pointPriority)
polyMeshFilter (const fvMesh &mesh, const labelList &pointPriority, const dictionary &dict)
~polyMeshFilter ()=default
const autoPtr< fvMesh > & filteredMesh () const
const autoPtr< labelList > & pointPriority () const
label filter (const label nOriginalBadFaces)
label filter (const faceSet &fSet)
label filterEdges (const label nOriginalBadFaces)
Static Public Member Functions
static autoPtr< fvMesh > copyMesh (const fvMesh &mesh)
static void copySets (const polyMesh &oldMesh, const polyMesh &newMesh)
static void updateSets (const mapPolyMesh &map)
Detailed Description
Remove the edges and faces of a polyMesh whilst satisfying the given mesh quality criteria.
Works on a copy of the mesh.
Source files
polyMeshFilter.H
polyMeshFilter.C
polyMeshFilterTemplates.C
Definition at line 61 of file polyMeshFilter.H.
Constructor & Destructor Documentation
polyMeshFilter() [1/3]
polyMeshFilter (const fvMesh & mesh) explicit
Definition at line 888 of file polyMeshFilter.C.
References Foam::Info, and polyMeshFilterSettings::writeSettings().
polyMeshFilter() [2/3]
polyMeshFilter (const fvMesh & mesh, const labelList & pointPriority)
Definition at line 915 of file polyMeshFilter.C.
References Foam::Info, and polyMeshFilterSettings::writeSettings().
polyMeshFilter() [3/3]
polyMeshFilter (const fvMesh & mesh, const labelList & pointPriority, const dictionary & dict)
Definition at line 945 of file polyMeshFilter.C.
References Foam::Info, and polyMeshFilterSettings::writeSettings().
~polyMeshFilter()
~polyMeshFilter () default
Member Function Documentation
ClassName()
ClassName ("polyMeshFilter")
filteredMesh()
const Foam::autoPtr< Foam::fvMesh > & filteredMesh () const
Definition at line 1115 of file polyMeshFilter.C.
pointPriority()
const Foam::autoPtr< Foam::labelList > & pointPriority () const
Definition at line 1122 of file polyMeshFilter.C.
copyMesh()
Foam::autoPtr< Foam::fvMesh > copyMesh (const fvMesh & mesh) static
Definition at line 63 of file polyMeshFilter.C.
References mapPolyMesh::hasMotionPoints(), mesh, fvMesh::name(), IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, mapPolyMesh::preMotionPoints(), IOobjectOption::READ_IF_PRESENT, and fvMesh::time().
copySets()
void copySets (const polyMesh & oldMesh, const polyMesh & newMesh) static
Definition at line 51 of file polyMeshFilter.C.
updateSets()
void updateSets (const mapPolyMesh & map) static
Definition at line 43 of file polyMeshFilter.C.
filter() [1/2]
Foam::label filter (const label nOriginalBadFaces)
Definition at line 966 of file polyMeshFilter.C.
References PtrList< T >::resize().
filter() [2/2]
Foam::label filter (const faceSet & fSet)
Definition at line 975 of file polyMeshFilter.C.
References forAll, and PtrList< T >::resize().
filterEdges()
Foam::label filterEdges (const label nOriginalBadFaces)
Definition at line 992 of file polyMeshFilter.C.
References edgeCollapser::checkMeshQuality(), UPtrList< T >::count(), Foam::decrIndent(), Foam::endl(), Foam::identity(), Foam::incrIndent(), Foam::indent(), Foam::Info, Foam::labelMax, Foam::nl, primitiveMesh::nPoints(), PtrList< T >::resize(), Foam::returnReduce(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/dynamicMesh/polyMeshFilter/polyMeshFilter.H
src/dynamicMesh/polyMeshFilter/polyMeshFilter.C
src/dynamicMesh/polyMeshFilter/polyMeshFilterTemplates.C