OpenFOAM: memorybuf::in Class Reference
memorybuf::in Class Reference
#include <memoryStreamBuffer.H>
Public Member Functions
in (char *s, std::streamsize n)
void resetg (char *s, std::streamsize n)
std::streamsize capacity () const
const UList< char > list () const
UList< char > list ()
void printBufInfo (Ostream &os) const
std::streamsize tellg () const
Protected Member Functions
in ()=default
virtual std::streamsize xsgetn (char *s, std::streamsize n)
Protected Member Functions inherited from memorybuf
virtual std::streampos seekoff (std::streamoff off, std::ios_base::seekdir way, std::ios_base::openmode which=std::ios_base::in|std::ios_base::out)
virtual std::streampos seekpos (std::streampos pos, std::ios_base::openmode which=std::ios_base::in|std::ios_base::out)
std::streamsize tellg () const
std::streamsize tellp () const
Detailed Description
Definition at line 154 of file memoryStreamBuffer.H.
Constructor & Destructor Documentation
in() [1/2]
in () protected default
in() [2/2]
in (char * s, std::streamsize n) inline
Definition at line 181 of file memoryStreamBuffer.H.
References n, memorybuf::in::resetg(), and s().
Member Function Documentation
xsgetn()
virtual std::streamsize xsgetn (char * s, std::streamsize n) inline protected virtual
Definition at line 164 of file memoryStreamBuffer.H.
References n, and s().
resetg()
void resetg (char * s, std::streamsize n) inline
Definition at line 188 of file memoryStreamBuffer.H.
References n, and s().
Referenced by memorybuf::in::in(), uiliststream::reset(), and UIListStreamAllocator::reset().
capacity()
std::streamsize capacity () const inline
Definition at line 204 of file memoryStreamBuffer.H.
Referenced by UIListStreamAllocator::size().
list() [1/2]
const UList< char > list () const inline
Definition at line 210 of file memoryStreamBuffer.H.
Referenced by UIListStreamAllocator::list(), and UIListStreamAllocator::list().
list() [2/2]
UList< char > list () inline
Definition at line 216 of file memoryStreamBuffer.H.
printBufInfo()
void printBufInfo (Ostream & os) const inline
Definition at line 222 of file memoryStreamBuffer.H.
References os().
Referenced by UIListStreamAllocator::printBufInfo().
tellg()
std::streamsize tellg () const inline
Definition at line 127 of file memoryStreamBuffer.H.
Referenced by UIListStreamAllocator::tellg().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/memory/memoryStreamBuffer.H