OpenFOAM: lduCalculatedProcessorField< Type > Class Template Reference
lduCalculatedProcessorField< Type > Class Template Reference
Boundary conditions » Generic
A lduProcessorField type bypassing coupledFvPatchField.
#include <lduCalculatedProcessorField.H>
Public Member Functions
ClassName ("lduCalculatedProcessorField")
lduCalculatedProcessorField (const lduInterface &interface)
lduCalculatedProcessorField (const lduCalculatedProcessorField< Type > &)
virtual ~lduCalculatedProcessorField ()=default
virtual bool ready () const
virtual void initInterfaceMatrixUpdate (solveScalarField &result, const bool add, const lduAddressing &lduAddr, const label patchId, const solveScalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const
virtual void updateInterfaceMatrix (solveScalarField &result, const bool add, const lduAddressing &lduAddr, const label patchId, const solveScalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const
virtual void initInterfaceMatrixUpdate (Field< scalar > &result, const bool add, const lduAddressing &lduAddr, const label patchId, const Field< scalar > &psiInternal, const scalarField &coeffs, const Pstream::commsTypes commsType) const
virtual void updateInterfaceMatrix (Field< scalar > &result, const bool add, const lduAddressing &lduAddr, const label patchId, const Field< scalar > &psiInternal, const scalarField &coeffs, const Pstream::commsTypes commsType) const
virtual label comm () const
virtual int myProcNo () const
virtual int neighbProcNo () const
virtual bool doTransform () const
virtual const tensorField & forwardT () const
virtual int rank () const
Public Member Functions inherited from LduInterfaceField< Type >
TypeName ("LduInterfaceField")
LduInterfaceField (const lduInterface &patch)
virtual ~LduInterfaceField ()=default
virtual void initInterfaceMatrixUpdate (Field< Type > &, const bool add, const lduAddressing &, const label interfacei, const Field< Type > &, const scalarField &, const Pstream::commsTypes commsType) const
virtual void updateInterfaceMatrix (Field< Type > &, const bool add, const lduAddressing &, const label interfacei, const Field< Type > &, const scalarField &, const Pstream::commsTypes commsType) const =0
virtual void initInterfaceMatrixUpdate (solveScalarField &result, const bool add, const lduAddressing &, const label interfacei, const solveScalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const
virtual void updateInterfaceMatrix (solveScalarField &result, const bool add, const lduAddressing &, const label interfacei, const solveScalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const=0
Public Member Functions inherited from lduInterfaceField
TypeName ("lduInterfaceField")
lduInterfaceField (const lduInterfaceField &)=delete
void operator= (const lduInterfaceField &)=delete
lduInterfaceField (const lduInterface &patch)
virtual ~lduInterfaceField ()=default
const lduInterface & interface () const noexcept
virtual const word & interfaceFieldType () const
bool updatedMatrix () const noexcept
bool updatedMatrix (bool flag) const noexcept
template<class Type >
void addToInternalField (Field< Type > &result, const bool add, const labelUList &faceCells, const scalarField &coeffs, const Field< Type > &vals) const
bool & updatedMatrix () noexcept
Public Member Functions inherited from processorLduInterfaceField
TypeName ("processorLduInterfaceField")
processorLduInterfaceField ()=default
virtual ~processorLduInterfaceField ()=default
template<class Type >
void transformCoupleField (Field< Type > &f) const
void transformCoupleField (solveScalarField &f, const direction cmpt) const
Protected Member Functions
void addToInternalField (solveScalarField &result, const bool add, const scalarField &coeffs, const solveScalarField &vals) const
virtual bool all_ready () const
Protected Attributes
const lduPrimitiveProcessorInterface & procInterface_
label sendRequest_
label recvRequest_
Field< Type > sendBuf_
Field< Type > recvBuf_
solveScalarField scalarSendBuf_
solveScalarField scalarRecvBuf_
Detailed Description
template<class Type>
class Foam::lduCalculatedProcessorField< Type >
A lduProcessorField type bypassing coupledFvPatchField.
Used to add updateInterfaceMatrix capabilities to a lduMatrix which is fully uncoupled from the fvMesh.
Its functionality is purely to init and update the processor interfaces.
Source files
lduCalculatedProcessorField.H
lduCalculatedProcessorField.C
Definition at line 57 of file lduCalculatedProcessorField.H.
Constructor & Destructor Documentation
lduCalculatedProcessorField() [1/2]
template<class Type > lduCalculatedProcessorField (const lduInterface & interface) explicit
Definition at line 26 of file lduCalculatedProcessorField.C.
References Foam::refCast().
lduCalculatedProcessorField() [2/2]
template<class Type > lduCalculatedProcessorField (const lduCalculatedProcessorField< Type > & ptf)
Definition at line 39 of file lduCalculatedProcessorField.C.
~lduCalculatedProcessorField()
template<class Type > virtual ~lduCalculatedProcessorField () virtual default
Member Function Documentation
addToInternalField()
template<class Type > void addToInternalField (solveScalarField & result, const bool add, const scalarField & coeffs, const solveScalarField & vals) const protected
Definition at line 132 of file lduCalculatedProcessorField.C.
References Foam::add(), and forAll.
all_ready()
template<class Type > bool all_ready () const protected virtual
Definition at line 54 of file lduCalculatedProcessorField.C.
References UPstream::finishedRequestPair().
ClassName()
template<class Type > ClassName ("lduCalculatedProcessorField< Type >")
ready()
template<class Type > bool ready () const virtual
Reimplemented from lduInterfaceField.
Definition at line 61 of file lduCalculatedProcessorField.C.
References UPstream::finishedRequest().
initInterfaceMatrixUpdate() [1/2]
template<class Type > void initInterfaceMatrixUpdate (solveScalarField & result, const bool add, const lduAddressing & lduAddr, const label patchId, const solveScalarField & psiInternal, const scalarField & coeffs, const direction cmpt, const Pstream::commsTypes commsType) const virtual
Reimplemented from lduInterfaceField.
Definition at line 74 of file lduCalculatedProcessorField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::nonBlocking, UPstream::nRequests(), lduAddressing::patchAddr(), patchId(), UIPstream::read(), UPtrList< T >::size(), and UOPstream::write().
updateInterfaceMatrix() [1/2]
template<class Type > void updateInterfaceMatrix (solveScalarField & result, const bool add, const lduAddressing & lduAddr, const label patchId, const solveScalarField & psiInternal, const scalarField & coeffs, const direction cmpt, const Pstream::commsTypes commsType) const virtual
Implements lduInterfaceField.
Definition at line 160 of file lduCalculatedProcessorField.C.
References Foam::add(), UPstream::finishedRequest(), and UPstream::waitRequest().
initInterfaceMatrixUpdate() [2/2]
template<class Type > virtual void initInterfaceMatrixUpdate (Field< scalar > & result, const bool add, const lduAddressing & lduAddr, const label patchId, const Field< scalar > & psiInternal, const scalarField & coeffs, const Pstream::commsTypes commsType) const inline virtual
Definition at line 164 of file lduCalculatedProcessorField.H.
References NotImplemented.
updateInterfaceMatrix() [2/2]
template<class Type > virtual void updateInterfaceMatrix (Field< scalar > & result, const bool add, const lduAddressing & lduAddr, const label patchId, const Field< scalar > & psiInternal, const scalarField & coeffs, const Pstream::commsTypes commsType) const inline virtual
Definition at line 179 of file lduCalculatedProcessorField.H.
References NotImplemented.
comm()
template<class Type > virtual label comm () const inline virtual
Implements processorLduInterfaceField.
Definition at line 197 of file lduCalculatedProcessorField.H.
References lduCalculatedProcessorField< Type >::procInterface_.
myProcNo()
template<class Type > virtual int myProcNo () const inline virtual
Implements processorLduInterfaceField.
Definition at line 203 of file lduCalculatedProcessorField.H.
References lduCalculatedProcessorField< Type >::procInterface_.
neighbProcNo()
template<class Type > virtual int neighbProcNo () const inline virtual
Implements processorLduInterfaceField.
Definition at line 209 of file lduCalculatedProcessorField.H.
References lduCalculatedProcessorField< Type >::procInterface_.
doTransform()
template<class Type > virtual bool doTransform () const inline virtual
Implements processorLduInterfaceField.
Definition at line 215 of file lduCalculatedProcessorField.H.
forwardT()
template<class Type > virtual const tensorField & forwardT () const inline virtual
Implements processorLduInterfaceField.
Definition at line 221 of file lduCalculatedProcessorField.H.
References lduCalculatedProcessorField< Type >::procInterface_.
rank()
template<class Type > virtual int rank () const inline virtual
Implements processorLduInterfaceField.
Definition at line 227 of file lduCalculatedProcessorField.H.
Member Data Documentation
procInterface_
template<class Type > const lduPrimitiveProcessorInterface& procInterface_ protected
Definition at line 67 of file lduCalculatedProcessorField.H.
Referenced by lduCalculatedProcessorField< Type >::comm(), lduCalculatedProcessorField< Type >::forwardT(), lduCalculatedProcessorField< Type >::myProcNo(), and lduCalculatedProcessorField< Type >::neighbProcNo().
sendRequest_
template<class Type > label sendRequest_ mutable protected
Definition at line 73 of file lduCalculatedProcessorField.H.
recvRequest_
template<class Type > label recvRequest_ mutable protected
Definition at line 76 of file lduCalculatedProcessorField.H.
sendBuf_
template<class Type > Field<Type> sendBuf_ mutable protected
Definition at line 79 of file lduCalculatedProcessorField.H.
recvBuf_
template<class Type > Field<Type> recvBuf_ mutable protected
Definition at line 82 of file lduCalculatedProcessorField.H.
scalarSendBuf_
template<class Type > solveScalarField scalarSendBuf_ mutable protected
Definition at line 85 of file lduCalculatedProcessorField.H.
scalarRecvBuf_
template<class Type > solveScalarField scalarRecvBuf_ mutable protected
Definition at line 88 of file lduCalculatedProcessorField.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterface/lduCalculatedProcessorField/lduCalculatedProcessorField.H
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterface/lduCalculatedProcessorField/lduCalculatedProcessorField.C