OpenFOAM: timeVaryingAlphaContactAngleFvPatchScalarField Class Reference
timeVaryingAlphaContactAngleFvPatchScalarField Class Reference
A time-varying alphaContactAngle scalar boundary condition (alphaContactAngleTwoPhaseFvPatchScalarField)
#include <timeVaryingAlphaContactAngleFvPatchScalarField.H>
Public Member Functions
TypeName ("timeVaryingAlphaContactAngle")
timeVaryingAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
timeVaryingAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
timeVaryingAlphaContactAngleFvPatchScalarField (const timeVaryingAlphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
virtual tmp< fvPatchScalarField > clone () const
timeVaryingAlphaContactAngleFvPatchScalarField (const timeVaryingAlphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual tmp< scalarField > theta (const fvPatchVectorField &Up, const fvsPatchVectorField &nHat) const
virtual void write (Ostream &) const
Public Member Functions inherited from alphaContactAngleTwoPhaseFvPatchScalarField
alphaContactAngleTwoPhaseFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
alphaContactAngleTwoPhaseFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField &)
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
Additional Inherited Members
Public Types inherited from alphaContactAngleTwoPhaseFvPatchScalarField
enum limitControls { lcNone , lcGradient , lcZeroGradient , lcAlpha }
Public Attributes inherited from alphaContactAngleTwoPhaseFvPatchScalarField
limitControls limit_
Static Public Attributes inherited from alphaContactAngleTwoPhaseFvPatchScalarField
static const Enum< limitControls > limitControlNames_
Detailed Description
A time-varying alphaContactAngle scalar boundary condition (alphaContactAngleTwoPhaseFvPatchScalarField)
Source files
timeVaryingAlphaContactAngleFvPatchScalarField.H
timeVaryingAlphaContactAngleFvPatchScalarField.C
Definition at line 48 of file timeVaryingAlphaContactAngleFvPatchScalarField.H.
Constructor & Destructor Documentation
timeVaryingAlphaContactAngleFvPatchScalarField() [1/4]
timeVaryingAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 30 of file timeVaryingAlphaContactAngleFvPatchScalarField.C.
timeVaryingAlphaContactAngleFvPatchScalarField() [2/4]
timeVaryingAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 62 of file timeVaryingAlphaContactAngleFvPatchScalarField.C.
References alphaContactAngleTwoPhaseFvPatchScalarField::evaluate().
timeVaryingAlphaContactAngleFvPatchScalarField() [3/4]
timeVaryingAlphaContactAngleFvPatchScalarField (const timeVaryingAlphaContactAngleFvPatchScalarField & gcpsf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 45 of file timeVaryingAlphaContactAngleFvPatchScalarField.C.
timeVaryingAlphaContactAngleFvPatchScalarField() [4/4]
timeVaryingAlphaContactAngleFvPatchScalarField (const timeVaryingAlphaContactAngleFvPatchScalarField & gcpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 80 of file timeVaryingAlphaContactAngleFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("timeVaryingAlphaContactAngle")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 95 of file timeVaryingAlphaContactAngleFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 111 of file timeVaryingAlphaContactAngleFvPatchScalarField.H.
theta()
Foam::tmp< Foam::scalarField > theta (const fvPatchVectorField & Up, const fvsPatchVectorField & nHat) const virtual
Implements alphaContactAngleTwoPhaseFvPatchScalarField.
Definition at line 98 of file timeVaryingAlphaContactAngleFvPatchScalarField.C.
References tmp< T >::New().
write()
void write (Ostream & os) const virtual
Reimplemented from alphaContactAngleTwoPhaseFvPatchScalarField.
Definition at line 124 of file timeVaryingAlphaContactAngleFvPatchScalarField.C.
References os(), alphaContactAngleTwoPhaseFvPatchScalarField::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/transportModels/twoPhaseProperties/alphaContactAngle/timeVaryingAlphaContactAngle/timeVaryingAlphaContactAngleFvPatchScalarField.H
src/transportModels/twoPhaseProperties/alphaContactAngle/timeVaryingAlphaContactAngle/timeVaryingAlphaContactAngleFvPatchScalarField.C