OpenFOAM: isotropic Class Reference
isotropic Class Reference
Lagrangian particle models » Submodels » MP-PIC » Time scale
Model for the time scale over which the velocity field of a dispersed phase tends towards an isotropic distribution.
#include <isotropic.H>
Public Member Functions
TypeName ("isotropic")
isotropic (const dictionary &dict)
isotropic (const isotropic &hc)
virtual autoPtr< TimeScaleModel > clone () const
virtual ~isotropic ()
tmp< FieldField< Field, scalar > > oneByTau (const FieldField< Field, scalar > &alpha, const FieldField< Field, scalar > &r32, const FieldField< Field, scalar > &uSqr, const FieldField< Field, scalar > &f) const
Public Member Functions inherited from TimeScaleModel
TypeName ("timeScaleModel")
declareRunTimeSelectionTable (autoPtr, TimeScaleModel, dictionary,(const dictionary &dict),(dict))
TimeScaleModel (const dictionary &dict)
TimeScaleModel (const TimeScaleModel &sm)
virtual ~TimeScaleModel ()
Additional Inherited Members
Static Public Member Functions inherited from TimeScaleModel
static autoPtr< TimeScaleModel > New (const dictionary &dict)
Protected Attributes inherited from TimeScaleModel
scalar alphaPacked_
scalar e_
Detailed Description
Model for the time scale over which the velocity field of a dispersed phase tends towards an isotropic distribution.
Reference:
    "Inclusion of collisional return-to-isotropy in the MP-PIC method"
    P O'Rourke and D Snider
    Chemical Engineering Science
    Volume 80, Issue 0, Pages 39-54, December 2012
Source files
isotropic.H
isotropic.C
Definition at line 60 of file isotropic.H.
Constructor & Destructor Documentation
isotropic() [1/2]
isotropic (const dictionary & dict)
Definition at line 44 of file isotropic.C.
isotropic() [2/2]
isotropic (const isotropic & hc)
Definition at line 53 of file isotropic.C.
~isotropic()
~isotropic () virtual
Definition at line 64 of file isotropic.C.
Member Function Documentation
TypeName()
TypeName ("isotropic")
clone()
virtual autoPtr< TimeScaleModel > clone () const inline virtual
Implements TimeScaleModel.
Definition at line 79 of file isotropic.H.
oneByTau()
Foam::tmp< Foam::FieldField< Foam::Field, Foam::scalar > > oneByTau (const FieldField< Field, scalar > & alpha, const FieldField< Field, scalar > & r32, const FieldField< Field, scalar > & uSqr, const FieldField< Field, scalar > & f) const virtual
Implements TimeScaleModel.
Definition at line 71 of file isotropic.C.
References alpha, f(), Foam::max(), Foam::constant::mathematical::pi(), and Foam::sqrt().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/TimeScaleModels/isotropic/isotropic.H
src/lagrangian/intermediate/submodels/MPPIC/TimeScaleModels/isotropic/isotropic.C