OpenFOAM: triangle2D Class Reference
triangle2D Class Reference
2-D triangle and queries
#include <triangle2D.H>
Public Member Functions
triangle2D (const vector2D &a, const vector2D &b, const vector2D &c, const bool orient=false)
triangle2D (const vector &a3d, const vector &b3d, const vector &c3d, const vector &axis1, const vector &axis2, const bool orient=false)
label order () const
label snapClosePoints (const triangle2D &triB)
void interArea (const triangle2D &triB, vector2D &centre, scalar &area) const
scalar interArea (const triangle2D &triB) const
bool overlaps (const triangle2D &triB) const
scalar area () const noexcept
vector2D centre () const
bool contains (const triangle2D &tri) const
bool isSame (const triangle2D &triB) const
bool pointInside (const vector2D &p) const
Public Member Functions inherited from FixedList< vector2D, 3 >
void writeEntry (const word &keyword, Ostream &os) const
FixedList ()=default
FixedList (const vector2D &val)
FixedList (const Foam::zero)
FixedList (const vector2D list[N])
FixedList (const FixedList< vector2D, N > &list)
FixedList (FixedList< vector2D, N > &&list)
FixedList (std::initializer_list< vector2D > list)
FixedList (const UList< vector2D > &list)
FixedList (const FixedList< vector2D, AnyNum > &list, const FixedList< label, N > &indices)
FixedList (const UList< vector2D > &list, const FixedList< label, N > &indices)
FixedList (const SLList< vector2D > &list)
FixedList (Istream &is)
autoPtr< FixedList< vector2D, N > > clone () const
const vector2D * cdata () const noexcept
vector2D * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
vector2D & get () noexcept
const vector2D & get () const noexcept
vector2D & front () noexcept
const vector2D & front () const noexcept
vector2D & back () noexcept
const vector2D & back () const noexcept
label fcIndex (const label i) const
const vector2D & fcValue (const label i) const
vector2D & fcValue (const label i)
label rcIndex (const label i) const
const vector2D & rcValue (const label i) const
vector2D & rcValue (const label i)
void checkStart (const label start) const
void checkSize (const label size) const
void checkIndex (const label i) const
bool uniform () const
label find (const vector2D &val, label pos=0) const
label rfind (const vector2D &val, label pos=-1) const
bool contains (const vector2D &val, label pos=0) const
void resize (const label n)
void resize_nocopy (const label n)
void setSize (const label n)
void fill (const vector2D &val)
void fill (const Foam::zero)
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void transfer (FixedList< vector2D, N > &list)
vector2D & operator[] (const label i)
const vector2D & operator[] (const label i) const
void operator= (const vector2D list[N])
void operator= (const UList< vector2D > &list)
void operator= (const SLList< vector2D > &list)
void operator= (std::initializer_list< vector2D > list)
void operator= (const vector2D &val)
void operator= (const Foam::zero)
void operator= (const FixedList< vector2D, N > &list)
void operator= (FixedList< vector2D, N > &&list)
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
void swap (FixedList< vector2D, N > &other)
bool operator== (const FixedList< vector2D, N > &list) const
bool operator!= (const FixedList< vector2D, N > &list) const
bool operator< (const FixedList< vector2D, N > &list) const
bool operator> (const FixedList< vector2D, N > &list) const
bool operator<= (const FixedList< vector2D, N > &list) const
bool operator>= (const FixedList< vector2D, N > &list) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label shortLen=0) const
vector2D & first () noexcept
const vector2D & first () const noexcept
vector2D & last () noexcept
const vector2D & last () const noexcept
bool found (const vector2D &val, label pos=0) const
Static Public Member Functions
static void writeOBJ (Ostream &os, const triangle2D &tri, label offset)
static label nClosePoints (const triangle2D &triA, const triangle2D &triB)
static scalar area (const vector2D &a, const vector2D &b, const vector2D &c)
static bool lineSegmentIntersectionPoint (const vector2D &lp1, const vector2D &lp2, const vector2D &sp1, const vector2D &sp2, vector2D &intersection)
static bool lineIntersectionPoint (const vector2D &a, const vector2D &b, const vector2D &c, const vector2D &d, vector2D &intersection)
static bool lineIntersects (const vector2D &a, const vector2D &b, const vector2D &c, const vector2D &d)
Static Public Member Functions inherited from FixedList< vector2D, 3 >
static const FixedList< vector2D, N > & null ()
static std::streamsize size_bytes () noexcept
static std::streamsize byteSize ()
static constexpr bool empty () noexcept
static constexpr label size () noexcept
static constexpr unsigned max_size () noexcept
Static Public Attributes
static int debug = 0
static scalar relTol = 1e-8
static scalar absTol = 1e-10
Additional Inherited Members
Public Types inherited from FixedList< vector2D, 3 >
typedef vector2D value_type
typedef vector2D * pointer
typedef const vector2D * const_pointer
typedef vector2D & reference
typedef const vector2D & const_reference
typedef vector2D * iterator
typedef const vector2D * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Protected Member Functions inherited from FixedList< vector2D, 3 >
void writeEntry (Ostream &os) const
Detailed Description
2-D triangle and queries
Source files
triangle2D.H
triangle2DI.H
triangle2D.C
Definition at line 48 of file triangle2D.H.
Constructor & Destructor Documentation
triangle2D() [1/2]
triangle2D (const vector2D & a, const vector2D & b, const vector2D & c, const bool orient = false)
Definition at line 40 of file triangle2D.C.
References b.
triangle2D() [2/2]
triangle2D (const vector & a3d, const vector & b3d, const vector & c3d, const vector & axis1, const vector & axis2, const bool orient = false)
Definition at line 64 of file triangle2D.C.
Member Function Documentation
order()
Foam::label order () const inline
Definition at line 192 of file triangle2DI.H.
References Foam::mag(), and Foam::sign().
Referenced by triangle2D::interArea().
writeOBJ()
void writeOBJ (Ostream & os, const triangle2D & tri, label offset) inline static
Definition at line 25 of file triangle2DI.H.
References Foam::endl(), Foam::nl, and os().
nClosePoints()
Foam::label nClosePoints (const triangle2D & triA, const triangle2D & triB) inline static
Definition at line 44 of file triangle2DI.H.
References forAll.
area() [1/2]
Foam::scalar area (const vector2D & a, const vector2D & b, const vector2D & c) inline static
Definition at line 71 of file triangle2DI.H.
References b, and Vector2D< Cmpt >::perp().
lineSegmentIntersectionPoint()
bool lineSegmentIntersectionPoint (const vector2D & lp1, const vector2D & lp2, const vector2D & sp1, const vector2D & sp2, vector2D & intersection) inline static
Definition at line 93 of file triangle2DI.H.
References Foam::endl(), Foam::mag(), Foam::nl, os(), Vector2D< Cmpt >::perp(), and s().
lineIntersectionPoint()
bool lineIntersectionPoint (const vector2D & a, const vector2D & b, const vector2D & c, const vector2D & d, vector2D & intersection) inline static
Definition at line 149 of file triangle2DI.H.
References b.
lineIntersects()
bool lineIntersects (const vector2D & a, const vector2D & b, const vector2D & c, const vector2D & d) inline static
Definition at line 162 of file triangle2DI.H.
References b, DebugInfo, and Foam::endl().
snapClosePoints()
Foam::label snapClosePoints (const triangle2D & triB)
Definition at line 86 of file triangle2D.C.
References forAll.
Referenced by faceAreaWeightAMI2D::storeInterArea().
interArea() [1/2]
void interArea (const triangle2D & triB, vector2D & centre, scalar & area) const
Definition at line 111 of file triangle2D.C.
References Foam::endl(), Foam::Info, n, OFstream::name(), Foam::name(), Foam::nl, triangle2D::order(), os(), p0, Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
interArea() [2/2]
Foam::scalar interArea (const triangle2D & triB) const
Definition at line 258 of file triangle2D.C.
References Foam::Zero.
overlaps()
bool overlaps (const triangle2D & triB) const
Definition at line 269 of file triangle2D.C.
References Foam::j1().
area() [2/2]
Foam::scalar area () const inline noexcept
Definition at line 186 of file triangle2DI.H.
centre()
Foam::vector2D centre () const inline
Definition at line 85 of file triangle2DI.H.
contains()
bool contains (const triangle2D & tri) const inline
Definition at line 198 of file triangle2DI.H.
isSame()
bool isSame (const triangle2D & triB) const inline
Definition at line 207 of file triangle2DI.H.
pointInside()
bool pointInside (const vector2D & p) const inline
Definition at line 218 of file triangle2DI.H.
References p.
Member Data Documentation
debug
int debug = 0 static
Definition at line 63 of file triangle2D.H.
relTol
Foam::scalar relTol = 1e-8 static
Definition at line 66 of file triangle2D.H.
Referenced by faceAreaWeightAMI2D::storeInterArea().
absTol
Foam::scalar absTol = 1e-10 static
Definition at line 69 of file triangle2D.H.
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/triangle2D/triangle2D.H
src/meshTools/AMIInterpolation/triangle2D/triangle2D.C
src/meshTools/AMIInterpolation/triangle2D/triangle2DI.H