OpenFOAM: SubList< T > Class Template Reference
SubList< T > Class Template Reference
A List obtained as a section of another List.
#include <SubList.H>
Public Member Functions
SubList () noexcept=default
SubList (const SubList &) noexcept=default
SubList (const UList< T > &list)
template<unsigned N>
SubList (const FixedList< T, N > &list)
SubList (const UList< T > &list, const label subSize)
SubList (const UList< T > &list, const label subSize, const label startIndex)
SubList (const UList< T > &list, const labelRange &range)
SubList (const labelRange &range, const UList< T > &list)
operator const Foam::List< T > & () const
void operator= (const SubList< T > &list)
void operator= (const UList< T > &list)
template<class Addr >
void operator= (const IndirectListBase< T, Addr > &list)
void operator= (const T &val)
void operator= (const Foam::zero)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Static Public Member Functions
static const SubList< T > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Additional Inherited Members
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Detailed Description
template<class T>
class Foam::SubList< T >
A List obtained as a section of another List.
Since the SubList is itself unallocated, no storage is allocated or de-allocated during its use. To achieve this behaviour, SubList is derived from UList rather than List.
Source files
SubList.H
SubListI.H
Definition at line 63 of file SubList.H.
Constructor & Destructor Documentation
SubList() [1/8]
template<class T > SubList () default noexcept
SubList() [2/8]
template<class T > SubList (const SubList< T > &) default noexcept
SubList() [3/8]
template<class T > SubList (const UList< T > & list) inline explicit
Definition at line 27 of file SubListI.H.
SubList() [4/8]
template<class T > template<unsigned N> SubList (const FixedList< T, N > & list) inline explicit
Definition at line 38 of file SubListI.H.
SubList() [5/8]
template<class T > SubList (const UList< T > & list, const label subSize) inline
Definition at line 48 of file SubListI.H.
SubList() [6/8]
template<class T > SubList (const UList< T > & list, const label subSize, const label startIndex) inline
Definition at line 63 of file SubListI.H.
SubList() [7/8]
template<class T > SubList (const UList< T > & list, const labelRange & range) inline
Definition at line 79 of file SubListI.H.
SubList() [8/8]
template<class T > SubList (const labelRange & range, const UList< T > & list) inline
Definition at line 96 of file SubListI.H.
Member Function Documentation
null()
template<class T > const Foam::SubList< T > & null () inline static
Definition at line 109 of file SubListI.H.
operator const Foam::List< T > &()
template<class T > operator const Foam::List< T > & () const inline
Definition at line 118 of file SubListI.H.
operator=() [1/5]
template<class T > void operator= (const SubList< T > & list) inline
Definition at line 125 of file SubListI.H.
References UList< T >::deepCopy().
Referenced by SubField< Type >::operator=(), SubField< Type >::operator=(), SubField< Type >::operator=(), and SubField< Type >::operator=().
operator=() [2/5]
template<class T > void operator= (const UList< T > & list) inline
Definition at line 132 of file SubListI.H.
References UList< T >::deepCopy().
operator=() [3/5]
template<class T > template<class Addr > void operator= (const IndirectListBase< T, Addr > & list) inline
Definition at line 140 of file SubListI.H.
operator=() [4/5]
template<class T > void operator= (const T & val) inline
Definition at line 147 of file SubListI.H.
References UList< T >::operator=().
operator=() [5/5]
template<class T > void operator= (const Foam::zero) inline
Definition at line 154 of file SubListI.H.
References UList< T >::operator=(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/List/SubList.H
src/OpenFOAM/containers/Lists/List/SubListI.H