OpenFOAM: absorptionEmissionModel Class Reference
absorptionEmissionModel Class Reference
Model to supply absorption and emission coefficients for radiation modelling.
#include <absorptionEmissionModel.H>
Public Member Functions
TypeName ("absorptionEmissionModel")
declareRunTimeSelectionTable (autoPtr, absorptionEmissionModel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
absorptionEmissionModel (const dictionary &dict, const fvMesh &mesh)
virtual ~absorptionEmissionModel ()
const fvMesh & mesh () const
const dictionary & dict () const
virtual tmp< volScalarField > a (const label bandI=0) const
virtual tmp< volScalarField > aCont (const label bandI=0) const
virtual tmp< volScalarField > aDisp (const label bandI=0) const
virtual tmp< volScalarField > e (const label bandI=0) const
virtual tmp< volScalarField > eCont (const label bandI=0) const
virtual tmp< volScalarField > eDisp (const label bandI=0) const
virtual tmp< volScalarField > E (const label bandI=0) const
virtual tmp< volScalarField > ECont (const label bandI=0) const
virtual tmp< volScalarField > EDisp (const label bandI=0) const
virtual label nBands () const
virtual const Vector2D< scalar > & bands (const label n) const
virtual bool isGrey () const
virtual void correct (volScalarField &a, PtrList< volScalarField > &aj) const
Static Public Member Functions
static autoPtr< absorptionEmissionModel > New (const dictionary &dict, const fvMesh &mesh)
Protected Attributes
const dictionary dict_
const fvMesh & mesh_
Detailed Description
Model to supply absorption and emission coefficients for radiation modelling.
Definition at line 48 of file absorptionEmissionModel.H.
Constructor & Destructor Documentation
absorptionEmissionModel()
absorptionEmissionModel (const dictionary & dict, const fvMesh & mesh)
Definition at line 36 of file absorptionEmissionModel.C.
~absorptionEmissionModel()
~absorptionEmissionModel () virtual
Definition at line 49 of file absorptionEmissionModel.C.
Member Function Documentation
TypeName()
TypeName ("absorptionEmissionModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , absorptionEmissionModel , dictionary , (const dictionary &dict, const fvMesh &mesh) , (dict, mesh))
New()
Foam::autoPtr< Foam::radiation::absorptionEmissionModel > New (const dictionary & dict, const fvMesh & mesh) static
Definition at line 28 of file absorptionEmissionModelNew.C.
References absorptionEmissionModel::dict(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, UPtrList< T >::get(), Foam::Info, and absorptionEmissionModel::mesh().
mesh()
const fvMesh & mesh () const inline
Definition at line 109 of file absorptionEmissionModel.H.
References absorptionEmissionModel::mesh_.
Referenced by greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), multiBandZoneAbsorptionEmission::multiBandZoneAbsorptionEmission(), absorptionEmissionModel::New(), and wideBandAbsorptionEmission::wideBandAbsorptionEmission().
dict()
const dictionary & dict () const inline
Definition at line 115 of file absorptionEmissionModel.H.
References absorptionEmissionModel::dict_.
Referenced by greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), greyMeanSolidAbsorptionEmission::greyMeanSolidAbsorptionEmission(), absorptionEmissionModel::New(), and wideBandAbsorptionEmission::wideBandAbsorptionEmission().
a()
Foam::tmp< Foam::volScalarField > a (const label bandI = 0) const virtual
Definition at line 56 of file absorptionEmissionModel.C.
aCont()
Foam::tmp< Foam::volScalarField > aCont (const label bandI = 0) const virtual
Reimplemented in multiBandAbsorptionEmission, multiBandZoneAbsorptionEmission, localDensityAbsorptionEmission, binaryAbsorptionEmission, constantAbsorptionEmission, greyMeanAbsorptionEmission, greyMeanSolidAbsorptionEmission, and wideBandAbsorptionEmission.
Definition at line 63 of file absorptionEmissionModel.C.
References Foam::dimLength, Foam::dimless, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and Foam::Zero.
aDisp()
Foam::tmp< Foam::volScalarField > aDisp (const label bandI = 0) const virtual
Reimplemented in cloudAbsorptionEmission, and binaryAbsorptionEmission.
Definition at line 86 of file absorptionEmissionModel.C.
References Foam::dimLength, Foam::dimless, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and Foam::Zero.
e()
Foam::tmp< Foam::volScalarField > e (const label bandI = 0) const virtual
Definition at line 109 of file absorptionEmissionModel.C.
eCont()
Foam::tmp< Foam::volScalarField > eCont (const label bandI = 0) const virtual
Reimplemented in multiBandAbsorptionEmission, multiBandZoneAbsorptionEmission, localDensityAbsorptionEmission, binaryAbsorptionEmission, constantAbsorptionEmission, greyMeanAbsorptionEmission, greyMeanSolidAbsorptionEmission, and wideBandAbsorptionEmission.
Definition at line 116 of file absorptionEmissionModel.C.
References Foam::dimLength, Foam::dimless, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and Foam::Zero.
eDisp()
Foam::tmp< Foam::volScalarField > eDisp (const label bandI = 0) const virtual
Reimplemented in cloudAbsorptionEmission, and binaryAbsorptionEmission.
Definition at line 139 of file absorptionEmissionModel.C.
References Foam::dimLength, Foam::dimless, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, and Foam::Zero.
E()
Foam::tmp< Foam::volScalarField > E (const label bandI = 0) const virtual
Definition at line 162 of file absorptionEmissionModel.C.
ECont()
Foam::tmp< Foam::volScalarField > ECont (const label bandI = 0) const virtual
Reimplemented in multiBandAbsorptionEmission, multiBandZoneAbsorptionEmission, localDensityAbsorptionEmission, binaryAbsorptionEmission, constantAbsorptionEmission, greyMeanAbsorptionEmission, and wideBandAbsorptionEmission.
Definition at line 169 of file absorptionEmissionModel.C.
References Foam::dimLength, Foam::dimMass, Foam::dimTime, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, Foam::pow3(), and Foam::Zero.
EDisp()
Foam::tmp< Foam::volScalarField > EDisp (const label bandI = 0) const virtual
Reimplemented in cloudAbsorptionEmission, and binaryAbsorptionEmission.
Definition at line 192 of file absorptionEmissionModel.C.
References Foam::dimLength, Foam::dimMass, Foam::dimTime, IOobjectOption::NO_READ, IOobjectOption::NO_REGISTER, IOobjectOption::NO_WRITE, Foam::pow3(), and Foam::Zero.
nBands()
Foam::label nBands () const virtual
Reimplemented in multiBandAbsorptionEmission, multiBandZoneAbsorptionEmission, and wideBandAbsorptionEmission.
Definition at line 214 of file absorptionEmissionModel.C.
bands()
const Foam::Vector2D< Foam::scalar > & bands (const label n) const virtual
Reimplemented in wideBandAbsorptionEmission.
Definition at line 221 of file absorptionEmissionModel.C.
isGrey()
bool isGrey () const virtual
Reimplemented in localDensityAbsorptionEmission, constantAbsorptionEmission, greyMeanAbsorptionEmission, greyMeanSolidAbsorptionEmission, multiBandAbsorptionEmission, multiBandZoneAbsorptionEmission, and wideBandAbsorptionEmission.
Definition at line 227 of file absorptionEmissionModel.C.
correct()
void correct (volScalarField & a, PtrList< volScalarField > & aj) const virtual
Reimplemented in wideBandAbsorptionEmission.
Definition at line 233 of file absorptionEmissionModel.C.
Member Data Documentation
dict_
const dictionary dict_ protected
Definition at line 56 of file absorptionEmissionModel.H.
Referenced by absorptionEmissionModel::dict().
mesh_
const fvMesh& mesh_ protected
Definition at line 59 of file absorptionEmissionModel.H.
Referenced by absorptionEmissionModel::mesh().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/absorptionEmissionModel/absorptionEmissionModel.H
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/absorptionEmissionModel/absorptionEmissionModel.C
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/absorptionEmissionModel/absorptionEmissionModelNew.C