OpenFOAM: patchWriter Class Reference
patchWriter Class Reference
Write OpenFOAM patches and patch fields in VTP or legacy vtk format.
#include <foamVtkPatchWriter.H>
Public Member Functions
patchWriter (const polyMesh &mesh, const labelList &patchIDs, const vtk::outputOptions opts=vtk::formatType::INLINE_BASE64, const bool useNearCellValue=false)
patchWriter (const polyMesh &mesh, const labelList &patchIDs, const fileName &file, bool parallel=Pstream::parRun())
patchWriter (const polyMesh &mesh, const labelList &patchIDs, const vtk::outputOptions opts, const fileName &file, bool parallel=Pstream::parRun())
patchWriter (const polyMesh &mesh, const labelList &patchIDs, const vtk::outputOptions opts, const bool useNearCellValue, const fileName &file, bool parallel=Pstream::parRun())
virtual ~patchWriter ()=default
template<class Type , template< class > class PatchField>
void write (const GeometricField< Type, PatchField, pointMesh > &field)
template<class Type , template< class > class PatchField>
void write (const GeometricField< Type, PatchField, volMesh > &field)
template<class Type >
void write (const GeometricField< Type, fvPatchField, volMesh > &field, const PrimitivePatchInterpolation< primitivePatch > &pInterp)
template<class Type >
void write (const GeometricField< Type, fvPatchField, volMesh > &field, const PrimitivePatchInterpolation< primitivePatch > *pInterp)
Public Member Functions inherited from patchMeshWriter
patchMeshWriter (const polyMesh &mesh, const labelList &patchIDs, const vtk::outputOptions opts=vtk::formatType::INLINE_BASE64)
patchMeshWriter (const polyMesh &mesh, const labelList &patchIDs, const fileName &file, bool parallel=Pstream::parRun())
patchMeshWriter (const polyMesh &mesh, const labelList &patchIDs, const vtk::outputOptions opts, const fileName &file, bool parallel=Pstream::parRun())
virtual ~patchMeshWriter ()=default
const labelList & patchIDs () const noexcept
virtual bool beginFile (std::string title="")
virtual bool writeGeometry ()
virtual bool beginCellData (label nFields=0)
virtual bool beginPointData (label nFields=0)
void writePatchIDs ()
bool writeProcIDs ()
bool writeNeighIDs ()
template<class Type >
void writeUniform (const word &fieldName, const Type &val)
Public Member Functions inherited from fileWriter
fileWriter (const vtk::fileTag contentType, const vtk::outputOptions opts)
virtual ~fileWriter ()
vtk::fileTag contentType () const noexcept
vtk::outputOptions opts () const noexcept
word ext () const
bool legacy () const noexcept
bool parallel () const noexcept
const word & state () const
const fileName & output () const noexcept
virtual bool open (const fileName &file, bool parallel=UPstream::parRun())
void close ()
bool beginFieldData (label nFields=0)
bool isCellData () const noexcept
bool isPointData () const noexcept
label nCellData () const noexcept
label nPointData () const noexcept
bool endFieldData ()
bool endCellData ()
bool endPointData ()
void writeTimeValue (scalar timeValue)
Additional Inherited Members
Static Public Member Functions inherited from patchMeshWriter
static word ext (vtk::outputOptions opts)
Protected Types inherited from fileWriter
enum outputState : uint8_t {
CLOSED = 0 , OPENED , DECLARED , FIELD_DATA ,
PIECE , CELL_DATA , POINT_DATA
}
Protected Member Functions inherited from patchMeshWriter
void beginPiece ()
void writePoints ()
void writePolysLegacy (const label pointOffset)
void writePolys (const label pointOffset)
patchMeshWriter (const patchMeshWriter &)=delete
void operator= (const patchMeshWriter &)=delete
Protected Member Functions inherited from fileWriter
void checkFormatterValidity () const
Ostream & reportBadState (Ostream &, outputState expected) const
Ostream & reportBadState (Ostream &, outputState, outputState) const
std::ofstream & os () noexcept
vtk::formatter & format ()
bool isState (outputState test) const noexcept
bool notState (outputState test) const noexcept
template<class Type >
void beginDataArray (const word &fieldName, const label nValues)
void endDataArray ()
void beginPoints (const label nPoints)
void endPoints ()
bool enter_Piece ()
bool endPiece ()
bool enter_CellData (label nEntries, label nFields)
bool enter_PointData (label nEntries, label nFields)
bool exit_File ()
template<class Type >
void writeUniform (const word &fieldName, const Type &val, const label nValues)
template<class Type >
void writeBasicField (const word &fieldName, const UList< Type > &field)
bool writeProcIDs (const label nValues)
fileWriter (const fileWriter &)=delete
void operator= (const fileWriter &)=delete
Protected Attributes inherited from patchMeshWriter
label numberOfPoints_
label numberOfCells_
label nLocalPoints_
label nLocalPolys_
label nLocalPolyConn_
const polyMesh & mesh_
labelList patchIDs_
Protected Attributes inherited from fileWriter
outputState state_
vtk::fileTag contentType_
bool parallel_
vtk::outputOptions opts_
label nCellData_
label nPointData_
fileName outputFile_
autoPtr< vtk::formatter > format_
std::ofstream os_
Static Protected Attributes inherited from fileWriter
static const Enum< outputState > stateNames
Detailed Description
Write OpenFOAM patches and patch fields in VTP or legacy vtk format.
The file output states are managed by the Foam::vtk::fileWriter class. FieldData (eg, TimeValue) must appear before any geometry pieces.
Note
Parallel output is combined into a single Piece without point merging, which is similar to using multi-piece data sets, but allows more convenient creation as a streaming process. In the future, the duplicate points at processor connections may be addressed using ghost points.
See also
Foam::vtk::patchMeshWriter
Source files
foamVtkPatchWriter.H
foamVtkPatchWriterTemplates.C
Definition at line 64 of file foamVtkPatchWriter.H.
Constructor & Destructor Documentation
patchWriter() [1/4]
patchWriter (const polyMesh & mesh, const labelList & patchIDs, const vtk::outputOptions opts = vtk::formatType::INLINE_BASE64, const bool useNearCellValue = false) inline
Definition at line 90 of file foamVtkPatchWriter.H.
patchWriter() [2/4]
patchWriter (const polyMesh & mesh, const labelList & patchIDs, const fileName & file, bool parallel = Pstream::parRun()) inline
Definition at line 105 of file foamVtkPatchWriter.H.
patchWriter() [3/4]
patchWriter (const polyMesh & mesh, const labelList & patchIDs, const vtk::outputOptions opts, const fileName & file, bool parallel = Pstream::parRun()) inline
Definition at line 120 of file foamVtkPatchWriter.H.
patchWriter() [4/4]
patchWriter (const polyMesh & mesh, const labelList & patchIDs, const vtk::outputOptions opts, const bool useNearCellValue, const fileName & file, bool parallel = Pstream::parRun()) inline
Definition at line 137 of file foamVtkPatchWriter.H.
~patchWriter()
virtual ~patchWriter () virtual default
Member Function Documentation
write() [1/4]
template<class Type , template< class > class PatchField> void write (const GeometricField< Type, PatchField, pointMesh > & field)
Definition at line 27 of file foamVtkPatchWriterTemplates.C.
References UPstream::blocking, fileWriter::endDataArray(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, field(), fileWriter::format(), fileWriter::isState(), UPstream::master(), UPstream::masterNo(), IOstream::name(), Foam::nl, patchMeshWriter::nLocalPoints_, nPatches, fileWriter::nPointData_, nPoints, fileWriter::parallel_, patchId(), patchMeshWriter::patchIDs_, fileWriter::POINT_DATA, Foam::reduce(), fileWriter::reportBadState(), UList< T >::size(), UPstream::subProcs(), and Foam::vtk::writeList().
write() [2/4]
template<class Type , template< class > class PatchField> void write (const GeometricField< Type, PatchField, volMesh > & field)
Definition at line 129 of file foamVtkPatchWriterTemplates.C.
References UPstream::blocking, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, field(), format(), UPstream::master(), UPstream::masterNo(), Foam::nl, nPatches, patchId(), Foam::reduce(), UPtrList< T >::size(), UPstream::subProcs(), and Foam::vtk::writeList().
write() [3/4]
template<class Type > void write (const GeometricField< Type, fvPatchField, volMesh > & field, const PrimitivePatchInterpolation< primitivePatch > & pInterp)
Definition at line 225 of file foamVtkPatchWriterTemplates.C.
References UPstream::blocking, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, field(), format(), UPstream::master(), UPstream::masterNo(), Foam::nl, nPatches, nPoints, patchId(), Foam::reduce(), UPtrList< T >::size(), UPstream::subProcs(), and Foam::vtk::writeList().
write() [4/4]
template<class Type > void write (const GeometricField< Type, fvPatchField, volMesh > & field, const PrimitivePatchInterpolation< primitivePatch > * pInterp)
The documentation for this class was generated from the following files:
src/conversion/vtk/output/foamVtkPatchWriter.H
src/conversion/vtk/output/foamVtkPatchWriterTemplates.C