OpenFOAM: DSMCParcel< ParcelType >::constantProperties Class Reference
DSMCParcel< ParcelType >::constantProperties Class Reference
#include <DSMCParcel.H>
Public Member Functions
constantProperties ()
constantProperties (const dictionary &dict)
scalar mass () const
scalar d () const
scalar sigmaT () const
direction internalDegreesOfFreedom () const
scalar omega () const
Detailed Description
template<class ParcelType>
class Foam::DSMCParcel< ParcelType >::constantProperties
Definition at line 77 of file DSMCParcel.H.
Constructor & Destructor Documentation
constantProperties() [1/2]
template<class ParcelType > constantProperties () inline
Definition at line 26 of file DSMCParcelI.H.
constantProperties() [2/2]
template<class ParcelType > constantProperties (const dictionary & dict) inline
Definition at line 34 of file DSMCParcelI.H.
Member Function Documentation
mass()
template<class ParcelType > Foam::scalar mass () const inline
Definition at line 88 of file DSMCParcelI.H.
Referenced by DSMCParcel< ParcelType >::hitWallPatch().
d()
template<class ParcelType > Foam::scalar d () const inline
Definition at line 95 of file DSMCParcelI.H.
sigmaT()
template<class ParcelType > Foam::scalar sigmaT () const inline
Definition at line 103 of file DSMCParcelI.H.
References Foam::constant::mathematical::pi().
internalDegreesOfFreedom()
template<class ParcelType > Foam::direction internalDegreesOfFreedom () const inline
Definition at line 111 of file DSMCParcelI.H.
Referenced by DSMCParcel< ParcelType >::hitWallPatch().
omega()
template<class ParcelType > Foam::scalar omega () const inline
Definition at line 120 of file DSMCParcelI.H.
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/parcels/Templates/DSMCParcel/DSMCParcel.H
src/lagrangian/DSMC/parcels/Templates/DSMCParcel/DSMCParcelI.H