OpenFOAM: uniformNormalFixedValueFvPatchVectorField Class Reference
uniformNormalFixedValueFvPatchVectorField Class Reference
Boundary conditions » Generic | Boundary conditions » Inlet
This boundary condition provides a uniform surface-normal vector boundary condition by its magnitude.
#include <uniformNormalFixedValueFvPatchVectorField.H>
Public Member Functions
TypeName ("uniformNormalFixedValue")
uniformNormalFixedValueFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
uniformNormalFixedValueFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
uniformNormalFixedValueFvPatchVectorField (const uniformNormalFixedValueFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
uniformNormalFixedValueFvPatchVectorField (const uniformNormalFixedValueFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
uniformNormalFixedValueFvPatchVectorField (const uniformNormalFixedValueFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &os) const
Detailed Description
This boundary condition provides a uniform surface-normal vector boundary condition by its magnitude.
Usage
Property Description Required Default
uniformValue uniform value yes
ramp time-based ramping no
Example of the boundary condition specification:
    <patchName>
    {
        type            uniformNormalFixedValue;
        uniformValue    constant -10;          // 10 INTO the domain
    }
Note
Sign conventions:
the value is positive for outward-pointing vectors
See also
Foam::Function1Types Foam::fixedValueFvPatchField Foam::surfaceNormalFixedValueFvPatchVectorField Foam::uniformFixedValueFvPatchVectorField
Source files
uniformNormalFixedValueFvPatchVectorField.H
uniformNormalFixedValueFvPatchVectorField.C
Definition at line 93 of file uniformNormalFixedValueFvPatchVectorField.H.
Constructor & Destructor Documentation
uniformNormalFixedValueFvPatchVectorField() [1/5]
uniformNormalFixedValueFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 28 of file uniformNormalFixedValueFvPatchVectorField.C.
uniformNormalFixedValueFvPatchVectorField() [2/5]
uniformNormalFixedValueFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 41 of file uniformNormalFixedValueFvPatchVectorField.C.
References dict.
uniformNormalFixedValueFvPatchVectorField() [3/5]
uniformNormalFixedValueFvPatchVectorField (const uniformNormalFixedValueFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 60 of file uniformNormalFixedValueFvPatchVectorField.C.
References FieldMapper::direct(), and FieldMapper::hasUnmapped().
uniformNormalFixedValueFvPatchVectorField() [4/5]
uniformNormalFixedValueFvPatchVectorField (const uniformNormalFixedValueFvPatchVectorField & ptf)
Definition at line 86 of file uniformNormalFixedValueFvPatchVectorField.C.
uniformNormalFixedValueFvPatchVectorField() [5/5]
uniformNormalFixedValueFvPatchVectorField (const uniformNormalFixedValueFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Definition at line 98 of file uniformNormalFixedValueFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("uniformNormalFixedValue")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 147 of file uniformNormalFixedValueFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 163 of file uniformNormalFixedValueFvPatchVectorField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & mapper) virtual
Definition at line 113 of file uniformNormalFixedValueFvPatchVectorField.C.
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Definition at line 129 of file uniformNormalFixedValueFvPatchVectorField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 144 of file uniformNormalFixedValueFvPatchVectorField.C.
References fvPatchField< vector >::operator=(), and fvPatchField< vector >::updateCoeffs().
write()
void write (Ostream & os) const virtual
Definition at line 165 of file uniformNormalFixedValueFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/uniformNormalFixedValue/uniformNormalFixedValueFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/uniformNormalFixedValue/uniformNormalFixedValueFvPatchVectorField.C