OpenFOAM: Bromley Class Reference
Bromley Class Reference
A correlation for boiling film modelling based on Bromley (1950) for boiling flows.
#include <Bromley.H>
Public Member Functions
TypeName ("Bromley")
Bromley (const dictionary &dict)
virtual ~Bromley ()=default
virtual tmp< scalarField > htcFilmBoil (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const
virtual void write (Ostream &os) const
Public Member Functions inherited from filmBoilingModel
TypeName ("filmBoilingModel")
declareRunTimeSelectionTable (autoPtr, filmBoilingModel, dictionary,(const dictionary &dict),(dict))
filmBoilingModel ()=default
virtual ~filmBoilingModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from filmBoilingModel
static autoPtr< filmBoilingModel > New (const dictionary &dict)
Detailed Description
A correlation for boiling film modelling based on Bromley (1950) for boiling flows.
Reference:
    Bromley, L. A. (1950).
    Heat transfer in stable film boiling.
    Chemical Engineering Progress, 46, 221-227.
Usage
Example of the model specification:
filmBoilingModel
{
    // Mandatory entries
    type            Bromley;
    L               <scalar>;
    // Optional entries
    Cn              <scalar>;
    emissivity      <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: Bromley word yes -
L Characteristic length scale scalar yes -
Cn Coefficient for nucleation site density scalar no 0.62
emissivity Wall emissivity scalar no 1.0
Source files
Bromley.H
Bromley.C
Definition at line 112 of file Bromley.H.
Constructor & Destructor Documentation
Bromley()
Bromley (const dictionary & dict)
Definition at line 50 of file Bromley.C.
~Bromley()
virtual ~Bromley () virtual default
Member Function Documentation
TypeName()
TypeName ("Bromley")
htcFilmBoil()
Foam::tmp< Foam::scalarField > htcFilmBoil (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const virtual
Implements filmBoilingModel.
Definition at line 65 of file Bromley.C.
References cells, e, g, L, Foam::mag(), Foam::max(), Foam::pow025(), Foam::pow3(), Foam::pow4(), Foam::constant::physicoChemical::sigma, and tCp.
write()
void write (Ostream & os) const virtual
Reimplemented from filmBoilingModel.
Definition at line 115 of file Bromley.C.
References os(), and filmBoilingModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/filmBoilingModels/Bromley/Bromley.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/filmBoilingModels/Bromley/Bromley.C