OpenFOAM: pointConstraints Class Reference
pointConstraints Class Reference
Application of (multi-)patch point constraints.
#include <pointConstraints.H>
Public Member Functions
ClassName ("pointConstraints")
pointConstraints (const pointMesh &)
~pointConstraints ()
const labelList & patchPatchPointConstraintPoints () const
const tensorField & patchPatchPointConstraintTensors () const
const List< pointConstraint > & patchPatchPointConstraints () const
void updateMesh (const mapPolyMesh &)
bool movePoints ()
template<class Type >
void constrainCorners (GeometricField< Type, pointPatchField, pointMesh > &pf) const
template<class Type >
void constrain (GeometricField< Type, pointPatchField, pointMesh > &pf, const bool overrideValue=false) const
void constrainDisplacement (pointVectorField &displacement, const bool overrideValue=false) const
template<>
void constrainCorners (GeometricField< scalar, pointPatchField, pointMesh > &pf) const
template<>
void constrainCorners (GeometricField< label, pointPatchField, pointMesh > &pf) const
Public Member Functions inherited from MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >
MeshObject (const pointMesh &mesh)
MeshObject (const word &objName, const pointMesh &mesh)
virtual ~MeshObject ()=default
const pointMesh & mesh () const noexcept
virtual bool writeData (Ostream &os) const
Static Public Member Functions
template<class Type , class CombineOp >
static void syncUntransformedData (const polyMesh &mesh, List< Type > &pointData, const CombineOp &cop)
template<class Type >
static void setPatchFields (GeometricField< Type, pointPatchField, pointMesh > &)
Static Public Member Functions inherited from MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >
static const pointConstraints & New (const pointMesh &mesh, Args &&... args)
static const pointConstraints & New (const word &objName, const pointMesh &mesh, Args &&... args)
static bool Delete (const word &objName, const pointMesh &mesh)
static bool Delete (const pointMesh &mesh)
Additional Inherited Members
Protected Attributes inherited from MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >
const pointMesh & mesh_
Detailed Description
Application of (multi-)patch point constraints.
Note: includes all points which are on the boundary of a patch with a constraint. It includes them (even though the constraint will already be implemented through the patch evaluation) since these points might be coupled to points which are not on any constraint patch and we don't want to get inconsistency between the two points.
Source files
pointConstraints.H
pointConstraints.C
pointConstraintsTemplates.C
Definition at line 60 of file pointConstraints.H.
Constructor & Destructor Documentation
pointConstraints()
pointConstraints (const pointMesh & pm) explicit
Definition at line 332 of file pointConstraints.C.
References Foam::endl(), and Foam::Pout.
~pointConstraints()
~pointConstraints ()
Definition at line 349 of file pointConstraints.C.
References Foam::endl(), and Foam::Pout.
Member Function Documentation
ClassName()
ClassName ("pointConstraints")
patchPatchPointConstraintPoints()
const labelList & patchPatchPointConstraintPoints () const inline
Definition at line 109 of file pointConstraints.H.
patchPatchPointConstraintTensors()
const tensorField & patchPatchPointConstraintTensors () const inline
Definition at line 115 of file pointConstraints.H.
patchPatchPointConstraints()
const List< pointConstraint > & patchPatchPointConstraints () const inline
Definition at line 121 of file pointConstraints.H.
updateMesh()
void updateMesh (const mapPolyMesh &)
Definition at line 360 of file pointConstraints.C.
movePoints()
bool movePoints ()
Definition at line 366 of file pointConstraints.C.
syncUntransformedData()
template<class Type , class CombineOp > void syncUntransformedData (const polyMesh & mesh, List< Type > & pointData, const CombineOp & cop) static
Definition at line 28 of file pointConstraintsTemplates.C.
References forAll, MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >::mesh(), and UPtrList< T >::size().
Referenced by volPointInterpolation::interpolateBoundaryField(), and volPointInterpolation::interpolateDimensionedInternalField().
setPatchFields()
template<class Type > void setPatchFields (GeometricField< Type, pointPatchField, pointMesh > & pf) static
Definition at line 84 of file pointConstraintsTemplates.C.
References forAll, and Foam::isA().
constrainCorners() [1/3]
template<class Type > void constrainCorners (GeometricField< Type, pointPatchField, pointMesh > & pf) const
Definition at line 106 of file pointConstraintsTemplates.C.
References forAll, and Foam::transform().
constrain()
template<class Type > void constrain (GeometricField< Type, pointPatchField, pointMesh > & pf, const bool overrideValue = false) const
Definition at line 123 of file pointConstraintsTemplates.C.
References mesh.
constrainDisplacement()
void constrainDisplacement (pointVectorField & displacement, const bool overrideValue = false) const
Definition at line 372 of file pointConstraints.C.
References mesh, MeshObject< polyMesh, UpdateableMeshObject, twoDPointCorrector >::New(), and points.
constrainCorners() [2/3]
template<> void constrainCorners (GeometricField< scalar, pointPatchField, pointMesh > & pf) const
constrainCorners() [3/3]
template<> void constrainCorners (GeometricField< label, pointPatchField, pointMesh > & pf) const
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/volPointInterpolation/pointConstraints.H
src/finiteVolume/interpolation/volPointInterpolation/pointConstraints.C
src/finiteVolume/interpolation/volPointInterpolation/pointConstraintsTemplates.C