OpenFOAM: mapDistribute Class Reference
mapDistribute Class Reference
Class containing processor-to-processor mapping information.
#include <mapDistribute.H>
Classes
class transform
class transformPosition
Public Member Functions
ClassName ("mapDistribute")
mapDistribute ()
mapDistribute (const label comm)
mapDistribute (mapDistributeBase &&map)
mapDistribute (const mapDistribute &map)
mapDistribute (mapDistribute &&map)
mapDistribute (const dictionary &dict, const label comm=UPstream::worldComm)
mapDistribute (const label constructSize, labelListList &&subMap, labelListList &&constructMap, labelListList &&transformElements, labelList &&transformStart, const bool subHasFlip=false, const bool constructHasFlip=false, const label comm=UPstream::worldComm)
mapDistribute (const globalIndex &, labelList &untransformedElements, const globalIndexAndTransform &, const labelPairList &transformedElements, labelList &transformedIndices, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistribute (const globalIndex &, labelListList &cellCells, const globalIndexAndTransform &, const List< labelPairList > &transformedElements, labelListList &transformedIndices, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistribute (Istream &is)
autoPtr< mapDistribute > clone () const
virtual ~mapDistribute ()=default
const labelListList & transformElements () const noexcept
const labelList & transformStart () const noexcept
label whichTransform (const label index) const
void clear ()
void transfer (mapDistribute &map)
template<class T >
void distribute (List< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void distribute (List< T > &fld, const NegateOp &negOp, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
template<class T >
void distribute (DynamicList< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const label constructSize, List< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const label constructSize, const T &nullValue, List< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
template<class T , class TransformOp >
void distribute (const globalIndexAndTransform &, List< T > &fld, const TransformOp &top, const int tag=UPstream::msgType()) const
template<class T , class TransformOp >
void reverseDistribute (const globalIndexAndTransform &, const label constructSize, List< T > &fld, const TransformOp &top, const int tag=UPstream::msgType()) const
template<class T , class TransformOp >
void reverseDistribute (const globalIndexAndTransform &, const label constructSize, const T &nullValue, List< T > &fld, const TransformOp &top, const int tag=UPstream::msgType()) const
void printLayout (Ostream &os) const
void operator= (const mapDistribute &rhs)
void operator= (mapDistribute &&rhs)
void readDict (const dictionary &dict)
void writeEntries (Ostream &os) const
void updateMesh (const mapPolyMesh &)
mapDistributeBase ()
mapDistributeBase (const label comm)
mapDistributeBase (const mapDistributeBase &map)
mapDistributeBase (mapDistributeBase &&map)
mapDistributeBase (const dictionary &dict, const label comm=UPstream::worldComm)
mapDistributeBase (const label constructSize, labelListList &&subMap, labelListList &&constructMap, const bool subHasFlip=false, const bool constructHasFlip=false, const label comm=UPstream::worldComm)
mapDistributeBase (const labelUList &sendProcs, const labelUList &recvProcs, const label comm=UPstream::worldComm)
mapDistributeBase (const globalIndex &, labelList &elements, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistributeBase (const globalIndex &, labelListList &cellCells, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistributeBase (labelListList &&subMap, const bool subHasFlip=false, const bool constructHasFlip=false, const label comm=UPstream::worldComm)
mapDistributeBase (Istream &is)
Public Member Functions inherited from mapDistributeBase
ClassName ("mapDistributeBase")
mapDistributeBase ()
mapDistributeBase (const label comm)
mapDistributeBase (const mapDistributeBase &map)
mapDistributeBase (mapDistributeBase &&map)
mapDistributeBase (const dictionary &dict, const label comm=UPstream::worldComm)
mapDistributeBase (const label constructSize, labelListList &&subMap, labelListList &&constructMap, const bool subHasFlip=false, const bool constructHasFlip=false, const label comm=UPstream::worldComm)
mapDistributeBase (const labelUList &sendProcs, const labelUList &recvProcs, const label comm=UPstream::worldComm)
mapDistributeBase (const globalIndex &, labelList &elements, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistributeBase (const globalIndex &, labelListList &cellCells, List< Map< label > > &compactMap, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
mapDistributeBase (labelListList &&subMap, const bool subHasFlip=false, const bool constructHasFlip=false, const label comm=UPstream::worldComm)
mapDistributeBase (Istream &is)
label constructSize () const noexcept
label & constructSize () noexcept
const labelListList & subMap () const noexcept
labelListList & subMap () noexcept
const labelListList & constructMap () const noexcept
labelListList & constructMap () noexcept
bool subHasFlip () const noexcept
bool & subHasFlip () noexcept
bool constructHasFlip () const noexcept
bool & constructHasFlip () noexcept
label comm () const noexcept
label nMaps () const noexcept
labelList subMapSizes () const
labelList constructMapSizes () const
const List< labelPair > & schedule () const
const List< labelPair > & whichSchedule (const UPstream::commsTypes commsType) const
void clear ()
void transfer (mapDistributeBase &rhs)
void compactLocalData (const bitSet &allowedLocalElems, const int tag=UPstream::msgType(), const bool doRenumber=false)
void compactRemoteData (const bitSet &allowedRemoteElems, const int tag=UPstream::msgType(), const bool doRenumber=false)
void compactLocalData (const bitSet &allowedLocalElems, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactRemoteData (const bitSet &allowedRemoteElems, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactData (const labelUList &localElements, const labelUList &remoteElements, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactLocalData (const labelUList &localElements, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
void compactRemoteData (const labelUList &remoteElements, labelList &oldToNewSub, labelList &oldToNewConstruct, const label localSize=-1, const int tag=UPstream::msgType())
template<class T >
void distribute (List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void distribute (DynamicList< T > &values, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void distribute (List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void distribute (const Pstream::commsTypes commsType, List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void distribute (const Pstream::commsTypes commsType, const T &nullValue, List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const label constructSize, List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const label constructSize, const T &nullValue, List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const Pstream::commsTypes commsType, const label constructSize, List< T > &values, const int tag=UPstream::msgType()) const
template<class T , class NegateOp >
void reverseDistribute (const Pstream::commsTypes commsType, const label constructSize, List< T > &values, const NegateOp &negOp, const int tag=UPstream::msgType()) const
template<class T >
void reverseDistribute (const Pstream::commsTypes commsType, const label constructSize, const T &nullValue, List< T > &values, const int tag=UPstream::msgType()) const
template<class T >
void send (PstreamBuffers &pBufs, const List< T > &field) const
template<class T >
void receive (PstreamBuffers &pBufs, List< T > &field) const
template<class T >
void send (const UList< T > &field, labelRange &requests, PtrList< List< T > > &sendFields, PtrList< List< T > > &recvFields, const int tag=UPstream::msgType()) const
template<class T >
void receive (const labelRange &requests, const UPtrList< List< T > > &sendFields, const UPtrList< List< T > > &recvFields, List< T > &field, const int tag=UPstream::msgType()) const
void printLayout (Ostream &os) const
void operator= (const mapDistributeBase &rhs)
void operator= (mapDistributeBase &&rhs)
InfoProxy< mapDistributeBase > info () const noexcept
void readDict (const dictionary &dict)
void writeEntries (Ostream &os) const
void updateMesh (const mapPolyMesh &)
void compact (const boolList &remoteElemUsed, const int tag=UPstream::msgType())
void compact (const boolList &remoteElemUsed, const label localSize, labelList &oldToNewSub, labelList &oldToNewConstruct, const int tag=UPstream::msgType())
template<class T , class NegateOp >
Foam::List< T > accessAndFlip (const UList< T > &values, const labelUList &indices, const bool hasFlip, const NegateOp &negOp)
Friends
Istream & operator>> (Istream &, mapDistribute &)
Ostream & operator<< (Ostream &, const mapDistribute &)
Additional Inherited Members
Static Public Member Functions inherited from mapDistributeBase
static bool hasFlipAddressing (const labelUList &map)
static bool hasFlipAddressing (const labelListList &maps)
static label countUnmapped (const labelUList &elements, const labelListList &maps, const bool hasFlip)
static List< labelPair > schedule (const labelListList &subMap, const labelListList &constructMap, const int tag, const label comm=UPstream::worldComm)
static label renumber (const globalIndex &, const List< Map< label > > &compactMap, const label globalElement)
static label renumberMap (labelListList &mapElements, const labelUList &oldToNew, const bool hasFlip)
template<class T , class NegateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &field, const NegateOp &negOp, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T , class CombineOp , class NegateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &field, const T &nullValue, const CombineOp &cop, const NegateOp &negOp, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm)
template<class T , class negateOp >
static void send (const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, const UList< T > &field, labelRange &requests, PtrList< List< T > > &sendFields, PtrList< List< T > > &recvFields, const negateOp &negOp, const int tag, const label comm)
template<class T , class CombineOp , class negateOp >
static void receive (const label constructSize, const labelListList &constructMap, const bool constructHasFlip, const UPtrList< List< T > > &sendFields, const UPtrList< List< T > > &recvFields, const labelRange &requests, List< T > &field, const CombineOp &cop, const negateOp &negOp, const int tag, const label comm)
Protected Member Functions inherited from mapDistributeBase
void calcCompactAddressing (const globalIndex &globalNumbering, const labelUList &elements, List< Map< label > > &compactMap) const
void calcCompactAddressing (const globalIndex &globalNumbering, const labelListList &elements, List< Map< label > > &compactMap) const
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelList &elements, List< Map< label > > &compactMap, labelList &compactStart)
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelListList &elements, List< Map< label > > &compactMap, labelList &compactStart)
Static Protected Member Functions inherited from mapDistributeBase
static void checkReceivedSize (const label proci, const label expectedSize, const label receivedSize)
static label getMappedSize (const labelListList &maps, const bool hasFlip)
static void exchangeMasks (const UList< bitSet > &sendMasks, UList< bitSet > &recvMasks, const int tag, const label comm)
static void unionCombineMasks (UList< bitSet > &sendMasks, UList< bitSet > &recvMasks, const int tag, const label comm)
template<class T , class CombineOp , class NegateOp >
static void flipAndCombine (const labelUList &map, const bool hasFlip, const UList< T > &rhs, const CombineOp &cop, const NegateOp &negOp, List< T > &lhs)
template<class T , class NegateOp >
static T accessAndFlip (const UList< T > &values, const label index, const bool hasFlip, const NegateOp &negOp)
template<class T , class NegateOp >
static List< T > accessAndFlip (const UList< T > &values, const labelUList &indices, const bool hasFlip, const NegateOp &negOp)
Detailed Description
Class containing processor-to-processor mapping information.
We store mapping from the bits-to-send to the complete starting list (subXXXMap) and from the received bits to their location in the new list (constructXXXMap).
Note: Schedule is a list of processor pairs (one send, one receive. One of them will be myself) which forms a scheduled (i.e. non-buffered) exchange. See distribute on how to use it. Note2: number of items sent on one processor have to equal the number of items received on the other processor.
To aid constructing these maps there are the constructors from global numbering, either with or without transforms.
without transforms: Constructors using compact numbering: layout is
all my own elements first (whether used or not)
followed by used-only remote elements sorted by remote processor. So e.g 4 procs and on proc 1 the compact table will first have all globalIndex.localSize() elements from proc1 followed by used-only elements of proc0, proc2, proc3. The constructed mapDistribute sends the local elements from and receives the remote elements into their compact position. compactMap[proci] is the position of elements from proci in the compact map. compactMap[myProcNo()] is empty since trivial addressing.
It rewrites the input global indices into indices into the constructed data.
with transforms: This requires the precalculated set of possible transforms (globalIndexAndTransform). These are given as permutations (+, -, or none) of up to 3 independent transforms. The layout of the data is
all my own elements first (whether used or not)
followed by used-only remote elements sorted by remote processor.
followed by - for each transformation index - the set of local or remote elements with that transformation. The inputs for the constructor are
the set of untransformed local or remote indices in globalIndex numbering. These get rewritten to be indices into the layout of the data.
the set of transformed local or remote indices in globalIndexAndTransform encoding. These are labelPairs.
Any distribute with transforms is now done as: 1. exchange data with other processors and receive these into the slots for that processor 2. for all transformations transform a subset of the data according to transformElements_[transformI] and store this starting from transformStart_[transformI]
In the same way a reverse distribute will 1. apply the inverse transform to the data starting at transformStart_[transformI] and copy the result back into the transformElements_[transformI]. These might be local or remote slots. 2. the data in the remote slots will now be sent back to the correct location in the originating processor.
E.g. a map to handle
mesh points on a mesh with
1 cyclic so 3 permutations (+,-,none) will have layout
on e.g. processor 1 out of 2:
+——+ <- transformStart[2] | | | | <- transform2 applied to data in local or remote slots | | +——+ <- transformStart[1] | | | | <- transform1 applied to data in local or remote slots | | +——+ <- transformStart[1] | | | | <- transform0 applied to data in local or remote slots | | +——+ <- transformStart[0] | | | | <- data from proc2 | | +——+ | | | | <- data from proc0 | | +——+ <- mesh.nPoints() | | | | | | +——+ 0
When constructing from components optionally a 'flip' on the maps can be specified. This will interpret the map values as index+flip, similar to e.g. faceProcAddressing. The flip will only be applied to fieldTypes (scalar, vector, .. triad)
Source files
mapDistribute.H
mapDistribute.C
mapDistributeIO.C
mapDistributeTemplates.C
Definition at line 156 of file mapDistribute.H.
Constructor & Destructor Documentation
mapDistribute() [1/10]
mapDistribute ()
Definition at line 144 of file mapDistribute.C.
mapDistribute() [2/10]
mapDistribute (const label comm) explicit
Definition at line 150 of file mapDistribute.C.
mapDistribute() [3/10]
mapDistribute (mapDistributeBase && map) explicit
Definition at line 156 of file mapDistribute.C.
mapDistribute() [4/10]
mapDistribute (const mapDistribute & map) explicit
Definition at line 162 of file mapDistribute.C.
mapDistribute() [5/10]
mapDistribute (mapDistribute && map) explicit
Definition at line 170 of file mapDistribute.C.
References mapDistribute::transfer().
mapDistribute() [6/10]
mapDistribute (const dictionary & dict, const label comm = UPstream::worldComm) explicit
Definition at line 26 of file mapDistributeIO.C.
References dict, and mapDistribute::readDict().
mapDistribute() [7/10]
mapDistribute (const label constructSize, labelListList && subMap, labelListList && constructMap, labelListList && transformElements, labelList && transformStart, const bool subHasFlip = false, const bool constructHasFlip = false, const label comm = UPstream::worldComm)
Definition at line 178 of file mapDistribute.C.
mapDistribute() [8/10]
mapDistribute (const globalIndex & globalNumbering, labelList & untransformedElements, const globalIndexAndTransform & globalTransforms, const labelPairList & transformedElements, labelList & transformedIndices, List< Map< label > > & compactMap, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm)
Definition at line 204 of file mapDistribute.C.
References mapDistributeBase::calcCompactAddressing(), mapDistributeBase::comm(), mapDistributeBase::constructSize(), mapDistributeBase::exchangeAddressing(), forAll, globalIndexAndTransform::index(), UPstream::myProcNo(), n, Foam::Pout, mapDistribute::printLayout(), globalIndexAndTransform::processor(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), globalIndexAndTransform::transformIndex(), globalIndexAndTransform::transformPermutations(), and Foam::Zero.
mapDistribute() [9/10]
mapDistribute (const globalIndex & globalNumbering, labelListList & cellCells, const globalIndexAndTransform & globalTransforms, const List< labelPairList > & transformedElements, labelListList & transformedIndices, List< Map< label > > & compactMap, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm)
Definition at line 312 of file mapDistribute.C.
References mapDistributeBase::calcCompactAddressing(), mapDistributeBase::comm(), mapDistributeBase::constructSize(), mapDistributeBase::exchangeAddressing(), forAll, globalIndexAndTransform::index(), UPstream::myProcNo(), n, Foam::Pout, mapDistribute::printLayout(), globalIndexAndTransform::processor(), List< T >::setSize(), PtrList< T >::setSize(), UPtrList< T >::size(), globalIndexAndTransform::transformIndex(), globalIndexAndTransform::transformPermutations(), and Foam::Zero.
mapDistribute() [10/10]
mapDistribute (Istream & is) explicit
Definition at line 34 of file mapDistributeIO.C.
~mapDistribute()
virtual ~mapDistribute () virtual default
Member Function Documentation
ClassName()
ClassName ("mapDistribute")
clone()
Foam::autoPtr< Foam::mapDistribute > clone () const
Definition at line 433 of file mapDistribute.C.
References autoPtr< T >::New().
transformElements()
const labelListList & transformElements () const inline noexcept
Definition at line 408 of file mapDistribute.H.
transformStart()
const labelList & transformStart () const inline noexcept
Definition at line 414 of file mapDistribute.H.
whichTransform()
Foam::label whichTransform (const label index) const
Definition at line 441 of file mapDistribute.C.
References Foam::findLower().
clear()
void clear ()
Definition at line 447 of file mapDistribute.C.
References mapDistributeBase::clear().
transfer()
void transfer (mapDistribute & map)
Definition at line 455 of file mapDistribute.C.
References mapDistributeBase::transfer().
Referenced by IOmapDistribute::IOmapDistribute(), and mapDistribute::mapDistribute().
distribute() [1/4]
template<class T > void distribute (List< T > & fld, const bool dummyTransform = true, const int tag = UPstream::msgType()) const
Definition at line 142 of file mapDistributeTemplates.C.
References fld().
Referenced by AMIInterpolation::agglomerate(), extendedCellToFaceStencil::collectData(), extendedFaceToCellStencil::collectData(), mapDistributePolyMesh::distributeCellData(), mapDistributePolyMesh::distributeFaceData(), mapDistributeLagrangian::distributeLagrangianData(), mapDistributePolyMesh::distributePatchData(), mapDistributePolyMesh::distributePointData(), cellVolumeWeight::findHoles(), inverseDistance::findHoles(), distributedTriSurfaceMesh::findNearest(), distributedTriSurfaceMesh::getVolumeType(), AMIInterpolation::interpolateToSource(), AMIInterpolation::interpolateToTarget(), oversetFvPatchField< Type >::manipulateMatrix(), meshToMesh::mapSrcToTgt(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), meshToMesh::mapTgtToSrc(), PatchTools::pointNormals(), cellVolumeWeight::update(), inverseDistance::update(), and trackingInverseDistance::update().
distribute() [2/4]
template<class T , class NegateOp > void distribute (List< T > & fld, const NegateOp & negOp, const bool dummyTransform = true, const int tag = UPstream::msgType()) const
Definition at line 123 of file mapDistributeTemplates.C.
References mapDistributeBase::distribute(), and fld().
distribute() [3/4]
template<class T > void distribute (DynamicList< T > & fld, const bool dummyTransform = true, const int tag = UPstream::msgType()) const
Definition at line 154 of file mapDistributeTemplates.C.
References fld(), and UPtrList< T >::size().
reverseDistribute() [1/4]
template<class T > void reverseDistribute (const label constructSize, List< T > & fld, const bool dummyTransform = true, const int tag = UPstream::msgType()) const
Definition at line 172 of file mapDistributeTemplates.C.
References fld(), and mapDistributeBase::reverseDistribute().
Referenced by distributedTriSurfaceMesh::findNearest(), distributedTriSurfaceMesh::getField(), distributedTriSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getRegion(), and PatchTools::pointNormals().
reverseDistribute() [2/4]
template<class T > void reverseDistribute (const label constructSize, const T & nullValue, List< T > & fld, const bool dummyTransform = true, const int tag = UPstream::msgType()) const
Definition at line 190 of file mapDistributeTemplates.C.
References fld(), and mapDistributeBase::reverseDistribute().
distribute() [4/4]
template<class T , class TransformOp > void distribute (const globalIndexAndTransform & git, List< T > & fld, const TransformOp & top, const int tag = UPstream::msgType()) const
Definition at line 209 of file mapDistributeTemplates.C.
References fld().
reverseDistribute() [3/4]
template<class T , class TransformOp > void reverseDistribute (const globalIndexAndTransform & git, const label constructSize, List< T > & fld, const TransformOp & top, const int tag = UPstream::msgType()) const
Definition at line 226 of file mapDistributeTemplates.C.
References fld().
reverseDistribute() [4/4]
template<class T , class TransformOp > void reverseDistribute (const globalIndexAndTransform & git, const label constructSize, const T & nullValue, List< T > & fld, const TransformOp & top, const int tag = UPstream::msgType()) const
Definition at line 246 of file mapDistributeTemplates.C.
References fld().
printLayout()
void printLayout (Ostream & os) const
Definition at line 126 of file mapDistribute.C.
References Foam::endl(), forAll, Foam::nl, os(), mapDistributeBase::printLayout(), and UList< T >::size().
Referenced by mapDistribute::mapDistribute(), and mapDistribute::mapDistribute().
operator=() [1/2]
void operator= (const mapDistribute & rhs)
Definition at line 470 of file mapDistribute.C.
References mapDistributeBase::operator=().
Referenced by IOmapDistribute::IOmapDistribute().
operator=() [2/2]
void operator= (mapDistribute && rhs)
Definition at line 483 of file mapDistribute.C.
readDict()
void readDict (const dictionary & dict)
Definition at line 42 of file mapDistributeIO.C.
References PtrList< T >::clear(), dict, dictionary::findDict(), and mapDistributeBase::readDict().
Referenced by mapDistribute::mapDistribute().
writeEntries()
void writeEntries (Ostream & os) const
Definition at line 62 of file mapDistributeIO.C.
References Ostream::beginBlock(), Ostream::endBlock(), Foam::nl, os(), mapDistributeBase::writeEntries(), and Ostream::writeEntry().
updateMesh()
void updateMesh (const mapPolyMesh &) inline
Definition at line 547 of file mapDistribute.H.
References NotImplemented.
mapDistributeBase() [1/11]
mapDistributeBase ()
Definition at line 361 of file mapDistributeBase.C.
References FatalErrorInFunction.
mapDistributeBase() [2/11]
mapDistributeBase (const label comm) explicit
Definition at line 364 of file mapDistributeBase.C.
mapDistributeBase() [3/11]
mapDistributeBase (const mapDistributeBase & map)
Definition at line 367 of file mapDistributeBase.C.
mapDistributeBase() [4/11]
mapDistributeBase (mapDistributeBase && map)
Definition at line 370 of file mapDistributeBase.C.
mapDistributeBase() [5/11]
mapDistributeBase (const dictionary & dict, const label comm = UPstream::worldComm) explicit
Definition at line 373 of file mapDistributeBaseIO.C.
mapDistributeBase() [6/11]
mapDistributeBase (const label constructSize, labelListList && subMap, labelListList && constructMap, const bool subHasFlip = false, const bool constructHasFlip = false, const label comm = UPstream::worldComm)
Definition at line 380 of file mapDistributeBase.C.
mapDistributeBase() [7/11]
mapDistributeBase (const labelUList & sendProcs, const labelUList & recvProcs, const label comm = UPstream::worldComm)
Definition at line 394 of file mapDistributeBase.C.
References globalIndex::isLocal(), and globalIndex::whichProcID().
mapDistributeBase() [8/11]
mapDistributeBase (const globalIndex & globalNumbering, labelList & elements, List< Map< label > > & compactMap, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm)
Definition at line 407 of file mapDistributeBase.C.
References PtrList< T >::resize().
mapDistributeBase() [9/11]
mapDistributeBase (const globalIndex & globalNumbering, labelListList & cellCells, List< Map< label > > & compactMap, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm)
Definition at line 421 of file mapDistributeBase.C.
mapDistributeBase() [10/11]
mapDistributeBase (labelListList && subMap, const bool subHasFlip = false, const bool constructHasFlip = false, const label comm = UPstream::worldComm) explicit
Definition at line 433 of file mapDistributeBase.C.
References PtrList< T >::clear(), forAll, globalIndex::isLocal(), UPstream::myProcNo(), UPstream::nProcs(), PtrList< T >::resize(), UPtrList< T >::size(), globalIndex::toLocal(), globalIndex::whichProcID(), and Foam::Zero.
mapDistributeBase() [11/11]
mapDistributeBase (Istream & is) explicit
Definition at line 442 of file mapDistributeBaseIO.C.
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & , mapDistribute &) friend
operator<<
Ostream & operator<< (Ostream & , const mapDistribute &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.C
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributeIO.C
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributeTemplates.C