OpenFOAM: PairSpringSliderDashpot< CloudType > Class Template Reference
PairSpringSliderDashpot< CloudType > Class Template Reference
Pair forces between particles colliding with a spring, slider, damper model.
#include <PairSpringSliderDashpot.H>
Public Member Functions
TypeName ("pairSpringSliderDashpot")
PairSpringSliderDashpot (const dictionary &dict, CloudType &cloud)
virtual ~PairSpringSliderDashpot ()=default
scalar volumeFactor () const
scalar overlapArea (scalar rA, scalar rB, scalar rAB) const
virtual bool controlsTimestep () const
virtual label nSubCycles () const
virtual void evaluatePair (typename CloudType::parcelType &pA, typename CloudType::parcelType &pB) const
Public Member Functions inherited from PairModel< CloudType >
TypeName ("pairModel")
declareRunTimeSelectionTable (autoPtr, PairModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
PairModel (CloudType &owner)
PairModel (const dictionary &dict, CloudType &owner, const word &type)
virtual ~PairModel ()
const CloudType & owner () const
const dictionary & dict () const
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from PairModel< CloudType >
static autoPtr< PairModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Protected Member Functions inherited from PairModel< CloudType >
scalar forceCoeff (typename CloudType::parcelType &pA, typename CloudType::parcelType &pB) const
Detailed Description
template<class CloudType>
class Foam::PairSpringSliderDashpot< CloudType >
Pair forces between particles colliding with a spring, slider, damper model.
Reference:
    "Lagrangian numerical simulation of plug flow of cohesionless
     particles in a horizontal pipe"
    Tsuji, Y., Tanaka, T., Ishida, T.,
    Powder Technology
    Volume 73, Issue 3, September 1992, pp. 239-250
Definition at line 53 of file PairSpringSliderDashpot.H.
Constructor & Destructor Documentation
PairSpringSliderDashpot()
template<class CloudType > PairSpringSliderDashpot (const dictionary & dict, CloudType & cloud)
Definition at line 77 of file PairSpringSliderDashpot.C.
References PairModel< CloudType >::coeffDict(), Foam::mag(), nu, PairModel< CloudType >::owner(), and Foam::sqr().
~PairSpringSliderDashpot()
template<class CloudType > virtual ~PairSpringSliderDashpot () virtual default
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("pairSpringSliderDashpot")
volumeFactor()
template<class CloudType > scalar volumeFactor () const inline
Definition at line 139 of file PairSpringSliderDashpot.H.
overlapArea()
template<class CloudType > scalar overlapArea (scalar rA, scalar rB, scalar rAB) const inline
Definition at line 146 of file PairSpringSliderDashpot.H.
References Foam::sqr().
controlsTimestep()
template<class CloudType > bool controlsTimestep () const virtual
Implements PairModel< CloudType >.
Definition at line 123 of file PairSpringSliderDashpot.C.
nSubCycles()
template<class CloudType > Foam::label nSubCycles () const virtual
Implements PairModel< CloudType >.
Definition at line 130 of file PairSpringSliderDashpot.C.
References Foam::pow(), rhoMax, and Foam::sqrt().
evaluatePair()
template<class CloudType > void evaluatePair (typename CloudType::parcelType & pA, typename CloudType::parcelType & pB) const virtual
Implements PairModel< CloudType >.
Definition at line 155 of file PairSpringSliderDashpot.C.
References Foam::cbrt(), M, Foam::mag(), Foam::pow(), Foam::pow025(), R, Foam::sqrt(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/PairModel/PairSpringSliderDashpot/PairSpringSliderDashpot.H
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/PairModel/PairSpringSliderDashpot/PairSpringSliderDashpot.C