OpenFOAM: radialActuationDiskSource Class Reference
radialActuationDiskSource Class Reference
Numerics » Finite volume Options » Sources
Applies sources on velocity field (i.e. U) within a specified region to enable actuator disk models with radial thrust distribution for aero/hydro thrust loading of horizontal axis turbines on surrounding flow field in terms of energy conversion processes.
#include <radialActuationDiskSource.H>
Public Member Functions
TypeName ("radialActuationDiskSource")
radialActuationDiskSource (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
radialActuationDiskSource (const radialActuationDiskSource &)=delete
void operator= (const radialActuationDiskSource &)=delete
virtual ~radialActuationDiskSource ()=default
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual bool read (const dictionary &dict)
Public Member Functions inherited from actuationDiskSource
TypeName ("actuationDiskSource")
actuationDiskSource ()=delete
actuationDiskSource (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
actuationDiskSource (const actuationDiskSource &)=delete
void operator= (const actuationDiskSource &)=delete
virtual ~actuationDiskSource ()=default
const vector & diskDir () const
scalar diskArea () const
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
Public Member Functions inherited from cellSetOption
TypeName ("cellSetOption")
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
virtual ~cellSetOption ()=default
scalar timeStart () const noexcept
scalar duration () const noexcept
bool inTimeLimits (const scalar timeValue) const
bool useSubMesh () const noexcept
selectionModeType selectionMode () const noexcept
const wordRes & selectionNames () const noexcept
const wordRe & zoneName () const
scalar V () const noexcept
const labelList & cells () const noexcept
scalar timeStart (scalar val) noexcept
scalar duration (scalar val) noexcept
virtual bool isActive ()
const word & cellSetName () const
Public Member Functions inherited from option
TypeName ("option")
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
autoPtr< option > clone () const
virtual ~option ()=default
const word & name () const noexcept
const fvMesh & mesh () const noexcept
const dictionary & coeffs () const noexcept
bool active () const noexcept
void setApplied (const label fieldi)
bool active (const bool on) noexcept
virtual label applyToField (const word &fieldName) const
virtual void checkApplied () const
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void postProcessSens (scalarField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (vectorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void postProcessSens (tensorField &sensField, const word &fieldName=word::null, const word &designVariablesName=word::null)
virtual void writeHeader (Ostream &) const
virtual void writeFooter (Ostream &) const
virtual void writeData (Ostream &) const
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Additional Inherited Members
Public Types inherited from cellSetOption
enum selectionModeType {
smAll , smCellSet , smCellZone , smPoints ,
smGeometric , smCellType
}
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Public Attributes inherited from option
bool log
Static Public Attributes inherited from cellSetOption
static const Enum< selectionModeType > selectionModeTypeNames_
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Types inherited from actuationDiskSource
enum forceMethodType { FROUDE , VARIABLE_SCALING }
enum monitorMethodType { POINTS , CELLSET }
Protected Member Functions inherited from actuationDiskSource
virtual void writeFileHeader (Ostream &os)
Protected Member Functions inherited from cellSetOption
void setSelection (const dictionary &dict)
void setCellSelection ()
void setVol ()
Protected Member Functions inherited from option
void resetApplied ()
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes inherited from actuationDiskSource
enum forceMethodType forceMethod_
enum monitorMethodType monitorMethod_
label sink_
scalar writeFileStart_
scalar writeFileEnd_
scalar diskArea_
vector diskDir_
autoPtr< Function1< scalar > > UvsCpPtr_
autoPtr< Function1< scalar > > UvsCtPtr_
labelList monitorCells_
Protected Attributes inherited from cellSetOption
scalar timeStart_
scalar duration_
selectionModeType selectionMode_
wordRes selectionNames_
List< point > points_
dictionary geometricSelection_
labelList cells_
scalar V_
Protected Attributes inherited from option
const word name_
const word modelType_
const fvMesh & mesh_
dictionary dict_
dictionary coeffs_
wordList fieldNames_
List< bool > applied_
bool active_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Static Protected Attributes inherited from actuationDiskSource
static const Enum< forceMethodType > forceMethodTypeNames
static const Enum< monitorMethodType > monitorMethodTypeNames
Detailed Description
Applies sources on velocity field (i.e. U) within a specified region to enable actuator disk models with radial thrust distribution for aero/hydro thrust loading of horizontal axis turbines on surrounding flow field in terms of energy conversion processes.
Sources applied to:
  U         | Velocity    [m/s]
Required fields:
  U         | Velocity    [m/s]
Thrust, which is computed by actuationDiskSource.H is distributed as a function of actuator disk radius through a given forth order polynomial function:
where
= Thrust magnitude computed by actuationDiskSource setup
= Thrust magnitude as a function of "r"
= Local actuator disk radius
= Polynomial coefficients
Usage
Minimal example by using constant/fvOptions:
radialActuationDiskSource1
{
    // Mandatory entries (unmodifiable)
    type            radialActuationDiskSource;
    // Mandatory entries (runtime modifiable)
    coeffs          (0.1 0.5 0.01);
    // Mandatory/Optional (inherited) entries
    ...
}
where the entries mean:
Property Description Type Reqd Dflt
type Type name: radialActuationDiskSource word yes -
coeffs Radial distribution function coefficients vector yes -
The inherited entries are elaborated in:
fvOption.H
cellSetOption.H
writeFile.H
Function1.H
actuationDiskSource.H
Note
radialActuationDiskSource computes only Froude force computation method of actuationDiskSource.
Source files
radialActuationDiskSource.H
radialActuationDiskSource.C
radialActuationDiskSourceTemplates.C
Definition at line 150 of file radialActuationDiskSource.H.
Constructor & Destructor Documentation
radialActuationDiskSource() [1/2]
radialActuationDiskSource (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Definition at line 39 of file radialActuationDiskSource.C.
References Foam::endl(), Foam::Info, Foam::name(), and option::name_.
radialActuationDiskSource() [2/2]
radialActuationDiskSource (const radialActuationDiskSource &) delete
~radialActuationDiskSource()
virtual ~radialActuationDiskSource () virtual default
Member Function Documentation
TypeName()
TypeName ("radialActuationDiskSource")
operator=()
void operator= (const radialActuationDiskSource &) delete
addSup() [1/2]
void addSup (fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented from actuationDiskSource.
Definition at line 56 of file radialActuationDiskSource.C.
References U.
addSup() [2/2]
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented from actuationDiskSource.
Definition at line 80 of file radialActuationDiskSource.C.
References rho, and U.
read()
bool read (const dictionary & dict) virtual
Reimplemented from actuationDiskSource.
Definition at line 105 of file radialActuationDiskSource.C.
References dict, and actuationDiskSource::read().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/radialActuationDiskSource/radialActuationDiskSource.H
src/fvOptions/sources/derived/radialActuationDiskSource/radialActuationDiskSource.C
src/fvOptions/sources/derived/radialActuationDiskSource/radialActuationDiskSourceTemplates.C