OpenFOAM: sorptionWallFunctionFvPatchScalarField Class Reference
sorptionWallFunctionFvPatchScalarField Class Reference
Turbulence models » Boundary conditions » Wall functions
The sorptionWallFunction is a wall boundary condition to specify scalar/concentration gradient for turbulent and laminar flows.
#include <sorptionWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("sorptionWallFunction")
sorptionWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
sorptionWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
sorptionWallFunctionFvPatchScalarField (const sorptionWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
sorptionWallFunctionFvPatchScalarField (const sorptionWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
sorptionWallFunctionFvPatchScalarField (const sorptionWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
The sorptionWallFunction is a wall boundary condition to specify scalar/concentration gradient for turbulent and laminar flows.
The governing equation of the boundary condition is:
with
and with the mass-transfer coefficient is calculated for turbulent flows
or for laminar-flow and molecular-diffusion-only states
where
= Gradient of concentration
= Wall-adjacent concentration
= Near-wall cell concentration
= First-cell centre wall distance
= Flux of concentration
= Mass-transfer coefficient
= Wall-surface concentration
= Adsorption or absorption/permeation coefficient
= Empirical model coefficient
= Turbulent kinetic energy in near-wall cell
= Non-dimensional blended near-wall cell height
= Molecular-diffusion coefficient
= First-cell centre wall distance
Required fields:
      x    | Arbitrary scalar field, e.g. species, passive scalars etc.
Reference:
        Standard model for exponential blending (tag:FDC):
            Foat, T., Drodge, J., Charleson, A., Whatmore, B.,
            Pownall, S., Glover, P., ... & Marr, A. (2022).
            Predicting vapour transport from semi-volatile organic
            compounds concealed within permeable packaging.
            International Journal of Heat and Mass Transfer, 183, 122012.
            DOI:10.1016/j.ijheatmasstransfer.2021.122012
        Standard model for stepwise blending (tag:F):
            Foat, T. (2021).
            Modelling vapour transport in indoor environments for
            improved detection of explosives using dogs.
            Doctoral dissertation. University of Southampton.
            URI:http://eprints.soton.ac.uk/id/eprint/456709
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            sorptionWallFunction;
    Sc              <scalar>;
    Sct             <scalar>;
    kAbs            <PatchFunction1<scalar>>;
    // Optional entries
    laminar         <bool>;
    D               <scalar>;
    kName           <word>;
    nuName          <word>;
    // Inherited entries
    Cmu             <scalar>;
    kappa           <scalar>;
    E               <scalar>;
    blending        <word>;
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: sorptionWallFunction word yes -
Sc Schmidt number scalar yes -
Sct Turbulent Schmidt number scalar yes -
kAbs
Adsorption or absorption/permeation coefficient
PatchFunction1<scalar> yes -
laminar
Flag to calculate mass-transfer coefficient under the
laminar-flow or molecular-diffusion-only states
bool no false
kName Name of operand turbulent kinetic energy field word no k
nuName Name of operand kinematic viscosity field word no nu
The inherited entries are elaborated in:
fixedGradientFvPatchField.H
wallFunctionCoefficients.H
wallFunctionBlenders.H
PatchFunction1.H
Source files
sorptionWallFunctionFvPatchScalarField.H
sorptionWallFunctionFvPatchScalarField.C
Definition at line 271 of file sorptionWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
sorptionWallFunctionFvPatchScalarField() [1/5]
sorptionWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 225 of file sorptionWallFunctionFvPatchScalarField.C.
sorptionWallFunctionFvPatchScalarField() [2/5]
sorptionWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 265 of file sorptionWallFunctionFvPatchScalarField.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::Zero.
sorptionWallFunctionFvPatchScalarField() [3/5]
sorptionWallFunctionFvPatchScalarField (const sorptionWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 244 of file sorptionWallFunctionFvPatchScalarField.C.
sorptionWallFunctionFvPatchScalarField() [4/5]
sorptionWallFunctionFvPatchScalarField (const sorptionWallFunctionFvPatchScalarField & swfpsf)
Definition at line 309 of file sorptionWallFunctionFvPatchScalarField.C.
sorptionWallFunctionFvPatchScalarField() [5/5]
sorptionWallFunctionFvPatchScalarField (const sorptionWallFunctionFvPatchScalarField & swfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 327 of file sorptionWallFunctionFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("sorptionWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 356 of file sorptionWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 372 of file sorptionWallFunctionFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & mapper) virtual
Definition at line 348 of file sorptionWallFunctionFvPatchScalarField.C.
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Definition at line 362 of file sorptionWallFunctionFvPatchScalarField.C.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 380 of file sorptionWallFunctionFvPatchScalarField.C.
write()
void write (Ostream & os) const virtual
Definition at line 393 of file sorptionWallFunctionFvPatchScalarField.C.
References os(), fixedGradientFvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/thermoTools/derivedFvPatchFields/wallFunctions/sorptionWallFunction/sorptionWallFunctionFvPatchScalarField.H
src/thermoTools/derivedFvPatchFields/wallFunctions/sorptionWallFunction/sorptionWallFunctionFvPatchScalarField.C