OpenFOAM: UPstream::communicator Class Reference
UPstream::communicator Class Reference
#include <UPstream.H>
Public Member Functions
communicator (const communicator &)=delete
void operator= (const communicator &)=delete
communicator () noexcept
communicator (communicator &&c)
communicator (const label parentComm, const labelRange &subRanks)
communicator (const label parentComm, const labelUList &subRanks)
~communicator ()
bool good () const noexcept
label comm () const noexcept
void reset ()
void reset (label parent, const labelRange &subRanks)
void reset (label parent, const labelUList &subRanks)
void reset (communicator &&c)
void operator= (communicator &&c)
operator label () const noexcept
Detailed Description
Definition at line 425 of file UPstream.H.
Constructor & Destructor Documentation
communicator() [1/5]
communicator (const communicator &) delete
communicator() [2/5]
communicator () inline noexcept
Definition at line 438 of file UPstream.H.
communicator() [3/5]
communicator (communicator && c) inline
Definition at line 441 of file UPstream.H.
communicator() [4/5]
communicator (const label parentComm, const labelRange & subRanks) inline
Parameters
parentComm The parent communicator
subRanks The contiguous sub-ranks of parent to use
Definition at line 444 of file UPstream.H.
communicator() [5/5]
communicator (const label parentComm, const labelUList & subRanks) inline
Parameters
parentComm The parent communicator
subRanks The sub-ranks of parent to use (negative values ignored)
Definition at line 457 of file UPstream.H.
~communicator()
~communicator () inline
Definition at line 470 of file UPstream.H.
References UPstream::freeCommunicator().
Member Function Documentation
operator=() [1/2]
void operator= (const communicator &) delete
good()
bool good () const inline noexcept
Definition at line 473 of file UPstream.H.
comm()
label comm () const inline noexcept
Definition at line 476 of file UPstream.H.
reset() [1/4]
void reset () inline
Definition at line 479 of file UPstream.H.
References UPstream::freeCommunicator().
Referenced by UPstream::communicator::operator=().
reset() [2/4]
void reset (label parent, const labelRange & subRanks) inline
Definition at line 482 of file UPstream.H.
References UPstream::allocateCommunicator(), UPstream::freeCommunicator(), and UPstream::parent().
reset() [3/4]
void reset (label parent, const labelUList & subRanks) inline
Definition at line 489 of file UPstream.H.
References UPstream::allocateCommunicator(), UPstream::freeCommunicator(), and UPstream::parent().
reset() [4/4]
void reset (communicator && c) inline
Definition at line 496 of file UPstream.H.
References UPstream::freeCommunicator().
operator=() [2/2]
void operator= (communicator && c) inline
Definition at line 504 of file UPstream.H.
References UPstream::communicator::reset().
operator label()
operator label () const inline noexcept
Definition at line 507 of file UPstream.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/Pstreams/UPstream.H