OpenFOAM: IOstreamOption Class Reference
IOstreamOption Class Reference
A simple container for options an IOstream can normally have.
#include <IOstreamOption.H>
Classes
class versionNumber
Public Types
enum streamFormat : char { ASCII = 0 , BINARY }
enum compressionType : char { UNCOMPRESSED = 0 , COMPRESSED }
enum appendType : char { NON_APPEND = 0 , APPEND }
enum atomicType : char { NON_ATOMIC = 0 , ATOMIC }
Public Member Functions
constexpr IOstreamOption (streamFormat fmt=streamFormat::ASCII, compressionType comp=compressionType::UNCOMPRESSED) noexcept
constexpr IOstreamOption (streamFormat fmt, compressionType comp, versionNumber ver) noexcept
constexpr IOstreamOption (streamFormat fmt, versionNumber ver, compressionType comp=compressionType::UNCOMPRESSED) noexcept
IOstreamOption (const IOstreamOption &opt, streamFormat fmt) noexcept
streamFormat format () const noexcept
streamFormat format (const streamFormat fmt) noexcept
streamFormat format (const word &formatName)
compressionType compression () const noexcept
compressionType compression (const compressionType comp) noexcept
compressionType compression (const word &compName)
versionNumber version () const noexcept
versionNumber version (const versionNumber ver) noexcept
versionNumber version (const token &tok)
Static Public Member Functions
static streamFormat formatEnum (const word &formatName, const streamFormat deflt=streamFormat::ASCII)
static streamFormat formatEnum (const word &key, const dictionary &dict, const streamFormat deflt=streamFormat::ASCII)
static compressionType compressionEnum (const word &compName, const compressionType deflt=compressionType::UNCOMPRESSED)
static compressionType compressionEnum (const word &key, const dictionary &dict, const compressionType deflt=compressionType::UNCOMPRESSED)
Static Public Attributes
static const Enum< streamFormat > formatNames
static const versionNumber currentVersion
Detailed Description
A simple container for options an IOstream can normally have.
The format (ASCII | BINARY) is typically controlled by enumerated names (ascii, binary).
The compression (UNCOMPRESSED | COMPRESSED) is typically controlled by switch values (true/false, on/off, ...).
Additionally, some enumerations are defined (APPEND, NON_APPEND, ...) that are useful, verbose alternatives to bool values.
Source files
IOstreamOption.H
IOstreamOption.C
Definition at line 61 of file IOstreamOption.H.
Member Enumeration Documentation
streamFormat
enum streamFormat : char
Enumerator
ASCII
"ascii" (normal default)
BINARY
"binary"
Definition at line 68 of file IOstreamOption.H.
compressionType
enum compressionType : char
Enumerator
UNCOMPRESSED
compression = false
COMPRESSED
compression = true
Definition at line 75 of file IOstreamOption.H.
appendType
enum appendType : char
Enumerator
NON_APPEND
append = false
APPEND
append = true
Definition at line 82 of file IOstreamOption.H.
atomicType
enum atomicType : char
Enumerator
NON_ATOMIC
atomic = false
ATOMIC
atomic = true
Definition at line 89 of file IOstreamOption.H.
Constructor & Destructor Documentation
IOstreamOption() [1/4]
constexpr IOstreamOption (streamFormat fmt = streamFormat::ASCII, compressionType comp = compressionType::UNCOMPRESSED) inline constexpr noexcept
Definition at line 204 of file IOstreamOption.H.
IOstreamOption() [2/4]
constexpr IOstreamOption (streamFormat fmt, compressionType comp, versionNumber ver) inline constexpr noexcept
Definition at line 216 of file IOstreamOption.H.
IOstreamOption() [3/4]
constexpr IOstreamOption (streamFormat fmt, versionNumber ver, compressionType comp = compressionType::UNCOMPRESSED) inline constexpr noexcept
Definition at line 229 of file IOstreamOption.H.
IOstreamOption() [4/4]
IOstreamOption (const IOstreamOption & opt, streamFormat fmt) inline noexcept
Definition at line 242 of file IOstreamOption.H.
Member Function Documentation
formatEnum() [1/2]
Foam::IOstreamOption::streamFormat formatEnum (const word & formatName, const streamFormat deflt = streamFormat::ASCII) static
Definition at line 45 of file IOstreamOption.C.
References UPtrList< T >::empty(), IOstreamOption::formatNames, and WarningInFunction.
Referenced by IOstreamOption::format(), VTPsurfaceFormatCore::formatOptions(), VTKsurfaceFormatCore::formatOptions(), vtkCloud::read(), vtkWrite::read(), and vtkWriter::vtkWriter().
formatEnum() [2/2]
Foam::IOstreamOption::streamFormat formatEnum (const word & key, const dictionary & dict, const streamFormat deflt = streamFormat::ASCII) static
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
Definition at line 72 of file IOstreamOption.C.
References dict.
compressionEnum() [1/2]
Foam::IOstreamOption::compressionType compressionEnum (const word & compName, const compressionType deflt = compressionType::UNCOMPRESSED) static
Definition at line 84 of file IOstreamOption.C.
References UPtrList< T >::empty(), Switch::find(), Foam::nl, and WarningInFunction.
Referenced by IOstreamOption::compression().
compressionEnum() [2/2]
Foam::IOstreamOption::compressionType compressionEnum (const word & key, const dictionary & dict, const compressionType deflt = compressionType::UNCOMPRESSED) static
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
Definition at line 119 of file IOstreamOption.C.
References dict.
format() [1/3]
streamFormat format () const inline noexcept
Definition at line 298 of file IOstreamOption.H.
Referenced by Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::printMaps(), Time::readDict(), Foam::setformat(), csvTableReader< Type >::write(), dimensionSet::write(), Foam::writeChars(), particle< Type >::writeCoordinates(), Time::writeFormat(), IOobject::writeHeaderContent(), PackedList< Width >::writeList(), CircularBuffer< T >::writeList(), FixedList< T, N >::writeList(), UList< T >::writeList(), Foam::writeMaps(), Matrix< Form, Type >::writeMatrix(), injectedParticle::writePosition(), and particle< Type >::writePosition().
format() [2/3]
streamFormat format (const streamFormat fmt) inline noexcept
Definition at line 302 of file IOstreamOption.H.
format() [3/3]
streamFormat format (const word & formatName) inline
Definition at line 313 of file IOstreamOption.H.
References IOstreamOption::formatEnum().
compression() [1/3]
compressionType compression () const inline noexcept
Definition at line 321 of file IOstreamOption.H.
Referenced by IFstream::IFstream(), Time::readDict(), and Time::writeCompression().
compression() [2/3]
compressionType compression (const compressionType comp) inline noexcept
Definition at line 325 of file IOstreamOption.H.
compression() [3/3]
compressionType compression (const word & compName) inline
Definition at line 336 of file IOstreamOption.H.
References IOstreamOption::compressionEnum().
version() [1/3]
versionNumber version () const inline noexcept
Definition at line 344 of file IOstreamOption.H.
Referenced by Time::readDict(), Foam::setversion(), IOobject::writeHeaderContent(), and Time::writeVersion().
version() [2/3]
versionNumber version (const versionNumber ver) inline noexcept
Definition at line 348 of file IOstreamOption.H.
version() [3/3]
versionNumber version (const token & tok) inline
Definition at line 357 of file IOstreamOption.H.
Member Data Documentation
formatNames
const Foam::Enum< Foam::IOstreamOption::streamFormat > formatNames static
Definition at line 174 of file IOstreamOption.H.
Referenced by IOstreamOption::formatEnum(), Foam::operator<<(), ensightSurfaceReader::readGeometry(), exprResult::writeDict(), exprResult::writeField(), and exprResult::writeValue().
currentVersion
const Foam::IOstreamOption::versionNumber currentVersion static
Definition at line 177 of file IOstreamOption.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/options/IOstreamOption.H
src/OpenFOAM/db/options/IOstreamOption.C