OpenFOAM: chemkinReader Class Reference
chemkinReader Class Reference
Thermophysical models » Reaction thermophysical models » Chemistry readers
Foam::chemkinReader.
#include <chemkinReader.H>
Public Types
enum phase { solid , liquid , gas }
Public Types inherited from chemistryReader< gasHThermoPhysics >
typedef gasHThermoPhysics thermoType
Public Member Functions
TypeName ("chemkinReader")
chemkinReader (speciesTable &species, const fileName &CHEMKINFileName, const fileName &transportFileName, const fileName &thermoFileName=fileName::null, const bool newFormat=false)
chemkinReader (const dictionary &thermoDict, speciesTable &species)
virtual ~chemkinReader ()=default
const wordList & elementNames () const
const HashTable< label > & elementIndices () const
const HashTable< scalar > & isotopeAtomicWts () const
const speciesTable & species () const
const speciesCompositionTable & specieComposition () const
const HashTable< phase > & speciePhase () const
const ReactionTable< gasHThermoPhysics > & speciesThermo () const
const ReactionList< gasHThermoPhysics > & reactions () const
Public Member Functions inherited from chemistryReader< gasHThermoPhysics >
TypeName ("chemistryReader")
chemistryReader ()
declareRunTimeSelectionTable (autoPtr, chemistryReader, dictionary,(const dictionary &thermoDict, speciesTable &species),(thermoDict, species))
virtual ~chemistryReader ()=default
Additional Inherited Members
Static Public Member Functions inherited from chemistryReader< gasHThermoPhysics >
static autoPtr< chemistryReader > New (const dictionary &thermoDict, speciesTable &species)
Detailed Description
Foam::chemkinReader.
Source files
chemkinReader.H
chemkinReader.C
chemkinLexer.C
Definition at line 60 of file chemkinReader.H.
Member Enumeration Documentation
phase
enum phase
Enumerator
solid
liquid
gas
Definition at line 69 of file chemkinReader.H.
Constructor & Destructor Documentation
chemkinReader() [1/2]
chemkinReader (speciesTable & species, const fileName & CHEMKINFileName, const fileName & transportFileName, const fileName & thermoFileName = fileName::null, const bool newFormat = false)
Definition at line 826 of file chemkinReader.C.
chemkinReader() [2/2]
chemkinReader (const dictionary & thermoDict, speciesTable & species)
Definition at line 846 of file chemkinReader.C.
References UPtrList< T >::empty(), Foam::endl(), Foam::Info, UPtrList< T >::size(), and thermoDict.
~chemkinReader()
virtual ~chemkinReader () virtual default
Member Function Documentation
TypeName()
TypeName ("chemkinReader")
elementNames()
const wordList & elementNames () const inline
Definition at line 317 of file chemkinReader.H.
elementIndices()
const HashTable< label > & elementIndices () const inline
Definition at line 323 of file chemkinReader.H.
isotopeAtomicWts()
const HashTable< scalar > & isotopeAtomicWts () const inline
Definition at line 329 of file chemkinReader.H.
species()
const speciesTable & species () const inline virtual
Implements chemistryReader< gasHThermoPhysics >.
Definition at line 335 of file chemkinReader.H.
specieComposition()
const speciesCompositionTable & specieComposition () const inline virtual
Implements chemistryReader< gasHThermoPhysics >.
Definition at line 341 of file chemkinReader.H.
speciePhase()
const HashTable< phase > & speciePhase () const inline
Definition at line 347 of file chemkinReader.H.
speciesThermo()
const ReactionTable< gasHThermoPhysics > & speciesThermo () const inline virtual
Implements chemistryReader< gasHThermoPhysics >.
Definition at line 353 of file chemkinReader.H.
reactions()
const ReactionList< gasHThermoPhysics > & reactions () const inline virtual
Implements chemistryReader< gasHThermoPhysics >.
Definition at line 359 of file chemkinReader.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/chemistryReaders/chemkinReader/chemkinReader.H
src/thermophysicalModels/reactionThermo/chemistryReaders/chemkinReader/chemkinReader.C