OpenFOAM: cyclicAMIGAMGInterface Class Reference
cyclicAMIGAMGInterface Class Reference
GAMG agglomerated cyclic AMI interface.
#include <cyclicAMIGAMGInterface.H>
Public Member Functions
TypeName ("cyclicAMI")
cyclicAMIGAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &restrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
virtual ~cyclicAMIGAMGInterface ()
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
virtual label neighbPatchID () const
virtual bool owner () const
virtual const cyclicAMIGAMGInterface & neighbPatch () const
virtual const AMIPatchToPatchInterpolation & AMI () const
virtual const tensorField & forwardT () const
virtual const tensorField & reverseT () const
virtual void write (Ostream &) const
Public Member Functions inherited from GAMGInterface
TypeName ("GAMGInterface")
declareRunTimeSelectionTable (autoPtr, GAMGInterface, lduInterface,(const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm),(index, coarseInterfaces, fineInterface, localRestrictAddressing, neighbourRestrictAddressing, fineLevelIndex, coarseComm))
declareRunTimeSelectionTable (autoPtr, GAMGInterface, Istream,(const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is),(index, coarseInterfaces, is))
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces)
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const labelUList &faceCells, const labelUList &faceRestrictAddressing)
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
virtual label size () const
virtual label index () const
virtual const lduInterfacePtrsList & coarseInterfaces () const
virtual const labelUList & faceCells () const
virtual const labelList & faceRestrictAddressing () const
virtual labelList & faceRestrictAddressing ()
template<class Type >
tmp< Field< Type > > interfaceInternalField (const UList< Type > &internalData) const
template<class Type >
tmp< Field< Type > > interfaceInternalField (const UList< Type > &internalData, const labelUList &faceCells) const
template<class Type >
void interfaceInternalField (const UList< Type > &internalData, List< Type > &) const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData, const labelUList &faceCells) const
void combine (const GAMGInterface &)
virtual tmp< scalarField > agglomerateCoeffs (const scalarField &fineCoeffs) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interfaceInternalField (const UList< Type > &iF) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interfaceInternalField (const UList< Type > &iF, const labelUList &faceCells) const
Public Member Functions inherited from lduInterface
TypeNameNoDebug ("lduInterface")
lduInterface () noexcept=default
virtual ~lduInterface ()=default
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF, const labelUList &faceCells) const
Public Member Functions inherited from cyclicAMILduInterface
TypeNameNoDebug ("cyclicAMILduInterface")
cyclicAMILduInterface () noexcept=default
virtual ~cyclicAMILduInterface ()=default
Additional Inherited Members
Static Public Member Functions inherited from GAMGInterface
static autoPtr< GAMGInterface > New (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
static autoPtr< GAMGInterface > New (const word &coupleType, const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
Protected Member Functions inherited from GAMGInterface
GAMGInterface (const GAMGInterface &)=delete
void operator= (const GAMGInterface &)=delete
Protected Attributes inherited from GAMGInterface
const label index_
const lduInterfacePtrsList & coarseInterfaces_
labelList faceCells_
labelList faceRestrictAddressing_
Detailed Description
GAMG agglomerated cyclic AMI interface.
Source files
cyclicAMIGAMGInterface.H
cyclicAMIGAMGInterface.C
Definition at line 47 of file cyclicAMIGAMGInterface.H.
Constructor & Destructor Documentation
cyclicAMIGAMGInterface()
cyclicAMIGAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, const lduInterface & fineInterface, const labelField & restrictAddressing, const labelField & neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
Definition at line 43 of file cyclicAMIGAMGInterface.C.
References PtrList< T >::append(), GAMGInterface::faceCells_, GAMGInterface::faceRestrictAddressing_, Foam::refCast(), UPtrList< T >::size(), List< T >::transfer(), and PtrList< T >::transfer().
~cyclicAMIGAMGInterface()
~cyclicAMIGAMGInterface () virtual
Definition at line 155 of file cyclicAMIGAMGInterface.C.
Member Function Documentation
TypeName()
TypeName ("cyclicAMI")
internalFieldTransfer()
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const virtual
Implements lduInterface.
Definition at line 161 of file cyclicAMIGAMGInterface.C.
References forAll, and UPtrList< T >::size().
neighbPatchID()
virtual label neighbPatchID () const inline virtual
Implements cyclicAMILduInterface.
Definition at line 112 of file cyclicAMIGAMGInterface.H.
References cyclicAMILduInterface::neighbPatchID().
Referenced by cyclicAMIGAMGInterface::neighbPatch().
owner()
virtual bool owner () const inline virtual
Implements cyclicAMILduInterface.
Definition at line 117 of file cyclicAMIGAMGInterface.H.
References cyclicAMILduInterface::owner().
neighbPatch()
virtual const cyclicAMIGAMGInterface & neighbPatch () const inline virtual
Implements cyclicAMILduInterface.
Definition at line 122 of file cyclicAMIGAMGInterface.H.
References GAMGInterface::coarseInterfaces_, and cyclicAMIGAMGInterface::neighbPatchID().
AMI()
virtual const AMIPatchToPatchInterpolation & AMI () const inline virtual
Implements cyclicAMILduInterface.
Definition at line 130 of file cyclicAMIGAMGInterface.H.
forwardT()
virtual const tensorField & forwardT () const inline virtual
Implements cyclicAMILduInterface.
Definition at line 136 of file cyclicAMIGAMGInterface.H.
References cyclicAMILduInterface::forwardT().
Referenced by cyclicAMIGAMGInterfaceField::forwardT().
reverseT()
virtual const tensorField & reverseT () const inline virtual
Implements cyclicAMILduInterface.
Definition at line 142 of file cyclicAMIGAMGInterface.H.
References cyclicAMILduInterface::reverseT().
Referenced by cyclicAMIGAMGInterfaceField::reverseT().
write()
virtual void write (Ostream &) const inline virtual
Implements GAMGInterface.
Definition at line 151 of file cyclicAMIGAMGInterface.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/GAMG/interfaces/cyclicAMIGAMGInterface/cyclicAMIGAMGInterface.H
src/meshTools/AMIInterpolation/GAMG/interfaces/cyclicAMIGAMGInterface/cyclicAMIGAMGInterface.C