OpenFOAM: volPointInterpolation Class Reference
volPointInterpolation Class Reference
Interpolate from cell centres to points (vertices) using inverse distance weighting.
#include <volPointInterpolation.H>
Public Member Functions
ClassName ("volPointInterpolation")
volPointInterpolation (const fvMesh &)
~volPointInterpolation ()
void updateMesh (const mapPolyMesh &)
bool movePoints ()
template<class Type >
tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
template<class Type >
tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class Type >
tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const wordList &patchFieldTypes) const
template<class Type >
tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &, const wordList &patchFieldTypes) const
template<class Type >
tmp< DimensionedField< Type, pointMesh > > interpolate (const DimensionedField< Type, volMesh > &) const
template<class Type >
tmp< DimensionedField< Type, pointMesh > > interpolate (const tmp< DimensionedField< Type, volMesh > > &) const
template<class Type >
void interpolateInternalField (const GeometricField< Type, fvPatchField, volMesh > &, GeometricField< Type, pointPatchField, pointMesh > &) const
template<class Type >
void interpolateBoundaryField (const GeometricField< Type, fvPatchField, volMesh > &vf, GeometricField< Type, pointPatchField, pointMesh > &pf) const
template<class Type >
void interpolateBoundaryField (const GeometricField< Type, fvPatchField, volMesh > &vf, GeometricField< Type, pointPatchField, pointMesh > &pf, const bool overrideFixedValue) const
template<class Type >
void interpolate (const GeometricField< Type, fvPatchField, volMesh > &, GeometricField< Type, pointPatchField, pointMesh > &) const
template<class Type >
tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const word &name, const bool cache) const
template<class Type >
void interpolateDimensionedInternalField (const DimensionedField< Type, volMesh > &vf, DimensionedField< Type, pointMesh > &pf) const
template<class Type >
tmp< DimensionedField< Type, pointMesh > > interpolate (const DimensionedField< Type, volMesh > &, const word &name, const bool cache) const
void interpolateDisplacement (const volVectorField &, pointVectorField &) const
template<class Type >
Foam::tmp< Foam::Field< Type > > flatBoundaryField (const GeometricField< Type, fvPatchField, volMesh > &vf) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, const wordList &patchFieldTypes) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const wordList &patchFieldTypes) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name, const bool cache) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf) const
template<class Type >
Foam::tmp< Foam::DimensionedField< Type, Foam::pointMesh > > interpolate (const DimensionedField< Type, volMesh > &vf, const word &name, const bool cache) const
template<class Type >
Foam::tmp< Foam::DimensionedField< Type, Foam::pointMesh > > interpolate (const DimensionedField< Type, volMesh > &vf) const
template<class Type >
Foam::tmp< Foam::DimensionedField< Type, Foam::pointMesh > > interpolate (const tmp< DimensionedField< Type, volMesh > > &tvf) const
Public Member Functions inherited from MeshObject< fvMesh, UpdateableMeshObject, volPointInterpolation >
MeshObject (const fvMesh &mesh)
MeshObject (const word &objName, const fvMesh &mesh)
virtual ~MeshObject ()=default
const fvMesh & mesh () const noexcept
virtual bool writeData (Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from MeshObject< fvMesh, UpdateableMeshObject, volPointInterpolation >
static const volPointInterpolation & New (const fvMesh &mesh, Args &&... args)
static const volPointInterpolation & New (const word &objName, const fvMesh &mesh, Args &&... args)
static bool Delete (const word &objName, const fvMesh &mesh)
static bool Delete (const fvMesh &mesh)
Protected Attributes inherited from MeshObject< fvMesh, UpdateableMeshObject, volPointInterpolation >
const fvMesh & mesh_
Detailed Description
Interpolate from cell centres to points (vertices) using inverse distance weighting.
Source files
volPointInterpolation.H
volPointInterpolation.C
volPointInterpolate.C
Definition at line 55 of file volPointInterpolation.H.
Constructor & Destructor Documentation
volPointInterpolation()
volPointInterpolation (const fvMesh & vm) explicit
Definition at line 467 of file volPointInterpolation.C.
~volPointInterpolation()
~volPointInterpolation ()
Definition at line 478 of file volPointInterpolation.C.
Member Function Documentation
ClassName()
ClassName ("volPointInterpolation")
updateMesh()
void updateMesh (const mapPolyMesh &)
Definition at line 484 of file volPointInterpolation.C.
References mesh, and MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New().
movePoints()
bool movePoints ()
Definition at line 493 of file volPointInterpolation.C.
interpolate() [1/17]
template<class Type > tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Referenced by parseDriver::cellToPoint().
interpolate() [2/17]
template<class Type > tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
interpolate() [3/17]
template<class Type > tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & , const wordList & patchFieldTypes) const
interpolate() [4/17]
template<class Type > tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & , const wordList & patchFieldTypes) const
interpolate() [5/17]
template<class Type > tmp< DimensionedField< Type, pointMesh > > interpolate (const DimensionedField< Type, volMesh > &) const
interpolate() [6/17]
template<class Type > tmp< DimensionedField< Type, pointMesh > > interpolate (const tmp< DimensionedField< Type, volMesh > > &) const
interpolateInternalField()
template<class Type > void interpolateInternalField (const GeometricField< Type, fvPatchField, volMesh > & vf, GeometricField< Type, pointPatchField, pointMesh > & pf) const
Definition at line 123 of file volPointInterpolate.C.
References Foam::endl(), forAll, Foam::Pout, and Foam::Zero.
interpolateBoundaryField() [1/2]
template<class Type > void interpolateBoundaryField (const GeometricField< Type, fvPatchField, volMesh > & vf, GeometricField< Type, pointPatchField, pointMesh > & pf) const
Definition at line 267 of file volPointInterpolate.C.
References boundary, forAll, mesh, pFaces, pointConstraints::syncUntransformedData(), and Foam::Zero.
interpolateBoundaryField() [2/2]
template<class Type > void interpolateBoundaryField (const GeometricField< Type, fvPatchField, volMesh > & vf, GeometricField< Type, pointPatchField, pointMesh > & pf, const bool overrideFixedValue) const
Definition at line 334 of file volPointInterpolate.C.
References MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >::New().
interpolate() [7/17]
template<class Type > void interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, GeometricField< Type, pointPatchField, pointMesh > & pf) const
Definition at line 351 of file volPointInterpolate.C.
References Foam::endl(), and Foam::Pout.
interpolate() [8/17]
template<class Type > tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & , const word & name, const bool cache) const
interpolateDimensionedInternalField()
template<class Type > void interpolateDimensionedInternalField (const DimensionedField< Type, volMesh > & vf, DimensionedField< Type, pointMesh > & pf) const
Definition at line 160 of file volPointInterpolate.C.
References primitiveMesh::cellCentres(), Foam::endl(), forAll, Foam::mag(), mesh, primitiveMesh::pointCells(), points, polyMesh::points(), Foam::Pout, s(), UPtrList< T >::size(), pointConstraints::syncUntransformedData(), and Foam::Zero.
interpolate() [9/17]
template<class Type > tmp< DimensionedField< Type, pointMesh > > interpolate (const DimensionedField< Type, volMesh > & , const word & name, const bool cache) const
interpolateDisplacement()
void interpolateDisplacement (const volVectorField & vf, pointVectorField & pf) const
Definition at line 501 of file volPointInterpolation.C.
References MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >::New().
flatBoundaryField()
template<class Type > Foam::tmp< Foam::Field< Type > > flatBoundaryField (const GeometricField< Type, fvPatchField, volMesh > & vf) const
Definition at line 220 of file volPointInterpolate.C.
References fvMesh::boundary(), forAll, mesh, primitiveMesh::nBoundaryFaces(), primitiveMesh::nInternalFaces(), pp(), UPtrList< T >::size(), and Foam::Zero.
interpolate() [10/17]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const wordList & patchFieldTypes) const
Definition at line 375 of file volPointInterpolate.C.
References MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), and Foam::New().
interpolate() [11/17]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const wordList & patchFieldTypes) const
Definition at line 408 of file volPointInterpolate.C.
References PtrList< T >::clear(), and Foam::interpolate().
interpolate() [12/17]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name, const bool cache) const
Definition at line 424 of file volPointInterpolate.C.
References solution::cachePrintMessage(), Foam::interpolate(), Foam::name(), MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), Foam::New(), and regIOobject::store().
interpolate() [13/17]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf) const
Definition at line 494 of file volPointInterpolate.C.
References Foam::interpolate().
interpolate() [14/17]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf) const
Definition at line 505 of file volPointInterpolate.C.
References PtrList< T >::clear(), and Foam::interpolate().
interpolate() [15/17]
template<class Type > Foam::tmp< Foam::DimensionedField< Type, Foam::pointMesh > > interpolate (const DimensionedField< Type, volMesh > & vf, const word & name, const bool cache) const
Definition at line 520 of file volPointInterpolate.C.
References solution::cachePrintMessage(), Foam::interpolate(), Foam::name(), MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), Foam::New(), and regIOobject::store().
interpolate() [16/17]
template<class Type > Foam::tmp< Foam::DimensionedField< Type, Foam::pointMesh > > interpolate (const DimensionedField< Type, volMesh > & vf) const
Definition at line 591 of file volPointInterpolate.C.
References Foam::interpolate().
interpolate() [17/17]
template<class Type > Foam::tmp< Foam::DimensionedField< Type, Foam::pointMesh > > interpolate (const tmp< DimensionedField< Type, volMesh > > & tvf) const
Definition at line 602 of file volPointInterpolate.C.
References PtrList< T >::clear(), and Foam::interpolate().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/volPointInterpolation/volPointInterpolation.H
src/finiteVolume/interpolation/volPointInterpolation/volPointInterpolate.C
src/finiteVolume/interpolation/volPointInterpolation/volPointInterpolation.C