OpenFOAM: localReferenceTemperature Class Reference
localReferenceTemperature Class Reference
Heat transfer coefficient calculation that employs the patch internal field as the reference temperature.
#include <localReferenceTemperature.H>
Public Member Functions
TypeName ("localReferenceTemperature")
localReferenceTemperature (const dictionary &dict, const fvMesh &mesh, const word &TName)
virtual ~localReferenceTemperature ()=default
virtual bool read (const dictionary &dict)
Public Member Functions inherited from heatTransferCoeffModel
TypeName ("heatTransferCoeffModel")
declareRunTimeSelectionTable (autoPtr, heatTransferCoeffModel, dictionary,(const dictionary &dict, const fvMesh &mesh, const word &TName),(dict, mesh, TName))
heatTransferCoeffModel (const dictionary &dict, const fvMesh &mesh, const word &TName)
heatTransferCoeffModel (const heatTransferCoeffModel &)=delete
void operator= (const heatTransferCoeffModel &)=delete
virtual ~heatTransferCoeffModel ()=default
const fvMesh & mesh () const noexcept
const labelHashSet & patchSet () const noexcept
const word & TName () const noexcept
const word & qrName () const noexcept
tmp< FieldField< Field, scalar > > q () const
virtual bool calc (volScalarField &result, const FieldField< Field, scalar > &q)
Protected Member Functions
virtual void htc (volScalarField &htc, const FieldField< Field, scalar > &q)
localReferenceTemperature (const localReferenceTemperature &)=delete
void operator= (const localReferenceTemperature &)=delete
Additional Inherited Members
Static Public Member Functions inherited from heatTransferCoeffModel
static autoPtr< heatTransferCoeffModel > New (const dictionary &dict, const fvMesh &mesh, const word &TName)
Protected Attributes inherited from heatTransferCoeffModel
const fvMesh & mesh_
labelHashSet patchSet_
const word TName_
word qrName_
Detailed Description
Heat transfer coefficient calculation that employs the patch internal field as the reference temperature.
The heat transfer coefficient is calculated by:
where
= Heat transfer coefficient [W/m^2/K]
= Heat flux [W/m^2]
= Patch internal temperature field [K]
= Patch temperature [K]
Usage
Minimal example by using system/controlDict.functions:
heatTransferCoeff1
{
    // Inherited entries
    ...
    // Mandatory entries
    htcModel        localReferenceTemperature;
}
where the entries mean:
Property Description Type Reqd Deflt
type Model name: localReferenceTemperature word yes -
Source files
localReferenceTemperature.H
localReferenceTemperature.C
Definition at line 110 of file localReferenceTemperature.H.
Constructor & Destructor Documentation
localReferenceTemperature() [1/2]
localReferenceTemperature (const localReferenceTemperature &) protected delete
localReferenceTemperature() [2/2]
localReferenceTemperature (const dictionary & dict, const fvMesh & mesh, const word & TName)
Definition at line 65 of file localReferenceTemperature.C.
References dict, and localReferenceTemperature::read().
~localReferenceTemperature()
virtual ~localReferenceTemperature () virtual default
Member Function Documentation
htc()
void htc (volScalarField & htc, const FieldField< Field, scalar > & q) protected virtual
Implements heatTransferCoeffModel.
Definition at line 43 of file localReferenceTemperature.C.
References localReferenceTemperature::htc(), heatTransferCoeffModel::mesh_, heatTransferCoeffModel::patchSet_, heatTransferCoeffModel::q(), T, and heatTransferCoeffModel::TName_.
Referenced by localReferenceTemperature::htc().
operator=()
void operator= (const localReferenceTemperature &) protected delete
TypeName()
TypeName ("localReferenceTemperature")
read()
bool read (const dictionary & dict) virtual
Reimplemented from heatTransferCoeffModel.
Definition at line 81 of file localReferenceTemperature.C.
References dict, and heatTransferCoeffModel::read().
Referenced by localReferenceTemperature::localReferenceTemperature().
The documentation for this class was generated from the following files:
src/functionObjects/field/heatTransferCoeff/heatTransferCoeffModels/localReferenceTemperature/localReferenceTemperature.H
src/functionObjects/field/heatTransferCoeff/heatTransferCoeffModels/localReferenceTemperature/localReferenceTemperature.C