OpenFOAM: PointData< DataType > Class Template Reference
PointData< DataType > Class Template Reference
Variant of pointEdgePoint with some transported additional data. Templated on the transported data type.
#include <PointData.H>
Public Member Functions
PointData ()=default
PointData (const point &origin, const scalar distSqr, const DataType &data)
const DataType & data () const noexcept
DataType & data () noexcept
bool operator== (const PointData< DataType > &) const
bool operator!= (const PointData< DataType > &) const
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointI, const label edgeI, const PointData< DataType > &edgeInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointI, const PointData< DataType > &newPointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updatePoint (const PointData< DataType > &newPointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointI, const PointData< DataType > &pointInfo, const scalar tol, TrackingData &td)
Public Member Functions inherited from pointEdgePoint
pointEdgePoint ()
pointEdgePoint (const point &origin, const scalar distSqr)
const point & origin () const noexcept
point & origin () noexcept
scalar distSqr () const noexcept
scalar & distSqr () noexcept
bool operator== (const pointEdgePoint &) const
bool operator!= (const pointEdgePoint &) const
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
bool sameGeometry (const pointEdgePoint &, const scalar tol, TrackingData &td) const
template<class TrackingData >
void leaveDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
template<class TrackingData >
void enterDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const label edgeI, const pointEdgePoint &edgeInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const pointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updatePoint (const pointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointi, const pointEdgePoint &pointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const pointEdgePoint &, TrackingData &td) const
Friends
Ostream & operator<< (Ostream &, const PointData< DataType > &)
Istream & operator>> (Istream &, PointData< DataType > &)
Detailed Description
template<class DataType>
class Foam::PointData< DataType >
Variant of pointEdgePoint with some transported additional data. Templated on the transported data type.
Source files
PointData.H
PointDataI.H
PointData.C
Definition at line 58 of file PointData.H.
Constructor & Destructor Documentation
PointData() [1/2]
template<class DataType > PointData () default
PointData() [2/2]
template<class DataType > PointData (const point & origin, const scalar distSqr, const DataType & data) inline
Definition at line 28 of file PointDataI.H.
Member Function Documentation
data() [1/2]
template<class DataType > const DataType & data () const inline noexcept
Definition at line 88 of file PointData.H.
data() [2/2]
template<class DataType > DataType & data () inline noexcept
Definition at line 90 of file PointData.H.
operator==()
template<class DataType > bool operator== (const PointData< DataType > & rhs) const inline
Definition at line 179 of file PointDataI.H.
References pointEdgePoint::operator==().
operator!=()
template<class DataType > bool operator!= (const PointData< DataType > & rhs) const inline
Definition at line 189 of file PointDataI.H.
transform()
template<class DataType > template<class TrackingData > void transform (const tensor & rotTensor, TrackingData & td) inline
Definition at line 44 of file PointDataI.H.
References Foam::transform(), and pointEdgePoint::transform().
updatePoint() [1/3]
template<class DataType > template<class TrackingData > bool updatePoint (const polyMesh & mesh, const label pointI, const label edgeI, const PointData< DataType > & edgeInfo, const scalar tol, TrackingData & td) inline
Definition at line 57 of file PointDataI.H.
References mesh, and pointEdgePoint::updatePoint().
updatePoint() [2/3]
template<class DataType > template<class TrackingData > bool updatePoint (const polyMesh & mesh, const label pointI, const PointData< DataType > & newPointInfo, const scalar tol, TrackingData & td) inline
Definition at line 91 of file PointDataI.H.
References mesh, and pointEdgePoint::updatePoint().
updatePoint() [3/3]
template<class DataType > template<class TrackingData > bool updatePoint (const PointData< DataType > & newPointInfo, const scalar tol, TrackingData & td) inline
Definition at line 123 of file PointDataI.H.
References pointEdgePoint::updatePoint().
updateEdge()
template<class DataType > template<class TrackingData > bool updateEdge (const polyMesh & mesh, const label edgeI, const label pointI, const PointData< DataType > & pointInfo, const scalar tol, TrackingData & td) inline
Definition at line 143 of file PointDataI.H.
References mesh, and pointEdgePoint::updateEdge().
Friends And Related Symbol Documentation
operator<<
template<class DataType > Ostream & operator<< (Ostream & , const PointData< DataType > &) friend
operator>>
template<class DataType > Istream & operator>> (Istream & , PointData< DataType > &) friend
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/externalDisplacementMeshMover/medialAxisMeshMover.H
src/meshTools/algorithms/PointEdgeWave/PointData.H
src/meshTools/algorithms/PointEdgeWave/PointDataI.H