OpenFOAM: fieldEntry Class Reference
fieldEntry Class Reference
#include <ccmSolutionTable.H>
Public Member Functions
fieldEntry (const word &shortName, const string &fullName, const char *units=nullptr)
const word & name () const
const string & fullName () const
const string & units () const
label maxCellId () const
label maxFaceId () const
void units (const std::string &units)
void maxCellId (const int newMax)
void maxFaceId (const int newMax)
Friends
Ostream & operator<< (Ostream &os, const fieldEntry &entry)
Detailed Description
Definition at line 136 of file ccmSolutionTable.H.
Constructor & Destructor Documentation
fieldEntry()
fieldEntry (const word & shortName, const string & fullName, const char * units = nullptr) inline
Definition at line 160 of file ccmSolutionTable.H.
References fieldEntry::units().
Member Function Documentation
name()
const word & name () const inline
Definition at line 183 of file ccmSolutionTable.H.
fullName()
const string & fullName () const inline
Definition at line 189 of file ccmSolutionTable.H.
units() [1/2]
const string & units () const inline
Definition at line 195 of file ccmSolutionTable.H.
Referenced by fieldEntry::fieldEntry(), and fieldEntry::units().
maxCellId() [1/2]
label maxCellId () const inline
Definition at line 201 of file ccmSolutionTable.H.
maxFaceId() [1/2]
label maxFaceId () const inline
Definition at line 207 of file ccmSolutionTable.H.
units() [2/2]
void units (const std::string & units) inline
Definition at line 216 of file ccmSolutionTable.H.
References UPtrList< T >::empty(), and fieldEntry::units().
maxCellId() [2/2]
void maxCellId (const int newMax) inline
Definition at line 225 of file ccmSolutionTable.H.
maxFaceId() [2/2]
void maxFaceId (const int newMax) inline
Definition at line 235 of file ccmSolutionTable.H.
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const fieldEntry & entry) friend
Definition at line 246 of file ccmSolutionTable.H.
The documentation for this class was generated from the following file:
src/conversion/ccm/reader/ccmSolutionTable.H