OpenFOAM: sigmoid Class Reference
sigmoid Class Reference
#include <sigmoid.H>
Public Member Functions
TypeName ("sigmoid")
sigmoid (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
~sigmoid ()
void scaleEnergy (scalar &e, const scalar r) const
bool read (const dictionary &energyScalingFunctionProperties)
Public Member Functions inherited from energyScalingFunction
TypeName ("energyScalingFunction")
declareRunTimeSelectionTable (autoPtr, energyScalingFunction, dictionary,(const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot),(name, energyScalingFunctionProperties, pairPot))
energyScalingFunction (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
virtual ~energyScalingFunction ()=default
const dictionary & energyScalingFunctionProperties () const
Additional Inherited Members
Static Public Member Functions inherited from energyScalingFunction
static autoPtr< energyScalingFunction > New (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
Protected Member Functions inherited from energyScalingFunction
energyScalingFunction (const energyScalingFunction &)=delete
void operator= (const energyScalingFunction &)=delete
Protected Attributes inherited from energyScalingFunction
word name_
dictionary energyScalingFunctionProperties_
const pairPotential & pairPot_
Detailed Description
Source files
sigmoid.H
sigmoid.C
Definition at line 48 of file sigmoid.H.
Constructor & Destructor Documentation
sigmoid()
sigmoid (const word & name, const dictionary & energyScalingFunctionProperties, const pairPotential & pairPot)
Definition at line 58 of file sigmoid.C.
~sigmoid()
~sigmoid () inline
Definition at line 88 of file sigmoid.H.
Member Function Documentation
TypeName()
TypeName ("sigmoid")
scaleEnergy()
void scaleEnergy (scalar & e, const scalar r) const virtual
Implements energyScalingFunction.
Definition at line 77 of file sigmoid.C.
References e.
read()
bool read (const dictionary & energyScalingFunctionProperties) virtual
Implements energyScalingFunction.
Definition at line 83 of file sigmoid.C.
References energyScalingFunction::energyScalingFunctionProperties(), energyScalingFunction::read(), and dictionary::readEntry().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/energyScalingFunction/derived/sigmoid/sigmoid.H
src/lagrangian/molecularDynamics/potential/energyScalingFunction/derived/sigmoid/sigmoid.C