OpenFOAM: nutWallFunctionFvPatchScalarField Class Reference
nutWallFunctionFvPatchScalarField Class Reference abstract
Turbulence models » Boundary conditions » Wall functions
The class nutWallFunction is an abstract base class that hosts calculation methods and common functions for nut wall-function boundary conditions.
#include <nutWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("nutWallFunction")
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< scalarField > yPlus () const =0
const wallFunctionCoefficients & wallCoeffs () const noexcept
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Static Public Member Functions
static const nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel &turbModel, const label patchi)
Protected Member Functions
virtual const volVectorField & U (const turbulenceModel &turb) const
virtual void checkType ()
virtual tmp< scalarField > calcNut () const =0
void writeLocalEntries (Ostream &) const
Protected Attributes
word UName_
wallFunctionCoefficients wallCoeffs_
Detailed Description
The class nutWallFunction is an abstract base class that hosts calculation methods and common functions for nut wall-function boundary conditions.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Top-level entries
    ...
    // Optional entries
    U             U;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
U Name of operand velocity field word no U
The inherited entries are elaborated in:
fixedValueFvPatchFields.H
wallFunctionCoefficients.H
Source files
nutWallFunctionFvPatchScalarField.H
nutWallFunctionFvPatchScalarField.C
Definition at line 93 of file nutWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutWallFunctionFvPatchScalarField() [1/5]
nutWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 78 of file nutWallFunctionFvPatchScalarField.C.
References nutWallFunctionFvPatchScalarField::checkType().
nutWallFunctionFvPatchScalarField() [2/5]
nutWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 108 of file nutWallFunctionFvPatchScalarField.C.
References nutWallFunctionFvPatchScalarField::checkType().
nutWallFunctionFvPatchScalarField() [3/5]
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 92 of file nutWallFunctionFvPatchScalarField.C.
References nutWallFunctionFvPatchScalarField::checkType().
nutWallFunctionFvPatchScalarField() [4/5]
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField & wfpsf)
Definition at line 123 of file nutWallFunctionFvPatchScalarField.C.
References nutWallFunctionFvPatchScalarField::checkType().
nutWallFunctionFvPatchScalarField() [5/5]
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 136 of file nutWallFunctionFvPatchScalarField.C.
References nutWallFunctionFvPatchScalarField::checkType().
Member Function Documentation
U()
const Foam::volVectorField & U (const turbulenceModel & turb) const protected virtual
Definition at line 52 of file nutWallFunctionFvPatchScalarField.C.
References word::null, and turb.
checkType()
void checkType () protected virtual
Definition at line 38 of file nutWallFunctionFvPatchScalarField.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
Referenced by nutWallFunctionFvPatchScalarField::nutWallFunctionFvPatchScalarField(), nutWallFunctionFvPatchScalarField::nutWallFunctionFvPatchScalarField(), nutWallFunctionFvPatchScalarField::nutWallFunctionFvPatchScalarField(), nutWallFunctionFvPatchScalarField::nutWallFunctionFvPatchScalarField(), and nutWallFunctionFvPatchScalarField::nutWallFunctionFvPatchScalarField().
calcNut()
virtual tmp< scalarField > calcNut () const protected pure virtual
Implemented in atmNutkWallFunctionFvPatchScalarField, atmNutUWallFunctionFvPatchScalarField, atmNutWallFunctionFvPatchScalarField, nutkFilmWallFunctionFvPatchScalarField, nutkRoughWallFunctionFvPatchScalarField, nutkWallFunctionFvPatchScalarField, nutLowReWallFunctionFvPatchScalarField, nutUBlendedWallFunctionFvPatchScalarField, nutUSpaldingWallFunctionFvPatchScalarField, nutUTabulatedWallFunctionFvPatchScalarField, and nutUWallFunctionFvPatchScalarField.
writeLocalEntries()
void writeLocalEntries (Ostream & os) const protected
Definition at line 66 of file nutWallFunctionFvPatchScalarField.C.
References word::null, os(), and Ostream::writeEntryIfDifferent().
TypeName()
TypeName ("nutWallFunction")
nutw()
const Foam::nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel & turbModel, const label patchi) static
Definition at line 153 of file nutWallFunctionFvPatchScalarField.C.
Referenced by atmNutkWallFunctionFvPatchScalarField::calcNut(), atmNutUWallFunctionFvPatchScalarField::calcNut(), atmNutWallFunctionFvPatchScalarField::calcNut(), nutkWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), and nutUWallFunctionFvPatchScalarField::calcNut().
yPlus()
virtual tmp< scalarField > yPlus () const pure virtual
Implemented in nutkFilmWallFunctionFvPatchScalarField, nutkWallFunctionFvPatchScalarField, nutLowReWallFunctionFvPatchScalarField, nutUBlendedWallFunctionFvPatchScalarField, nutURoughWallFunctionFvPatchScalarField, nutUSpaldingWallFunctionFvPatchScalarField, nutUTabulatedWallFunctionFvPatchScalarField, and nutUWallFunctionFvPatchScalarField.
wallCoeffs()
const wallFunctionCoefficients & wallCoeffs () const inline noexcept
Definition at line 190 of file nutWallFunctionFvPatchScalarField.H.
References nutWallFunctionFvPatchScalarField::wallCoeffs_.
Referenced by adjointkOmegaSST::adjointMeanFlowSource().
updateCoeffs()
void updateCoeffs () virtual
Definition at line 168 of file nutWallFunctionFvPatchScalarField.C.
References Foam::operator==().
write()
void write (Ostream & os) const virtual
Reimplemented in atmNutkWallFunctionFvPatchScalarField, atmNutUWallFunctionFvPatchScalarField, atmNutWallFunctionFvPatchScalarField, nutkRoughWallFunctionFvPatchScalarField, nutkWallFunctionFvPatchScalarField, nutLowReWallFunctionFvPatchScalarField, nutkFilmWallFunctionFvPatchScalarField, nutUBlendedWallFunctionFvPatchScalarField, nutURoughWallFunctionFvPatchScalarField, nutUSpaldingWallFunctionFvPatchScalarField, nutUTabulatedWallFunctionFvPatchScalarField, and nutUWallFunctionFvPatchScalarField.
Definition at line 181 of file nutWallFunctionFvPatchScalarField.C.
References os(), and fvPatchField< Type >::write().
Referenced by atmNutkWallFunctionFvPatchScalarField::write(), atmNutUWallFunctionFvPatchScalarField::write(), atmNutWallFunctionFvPatchScalarField::write(), nutkRoughWallFunctionFvPatchScalarField::write(), nutkWallFunctionFvPatchScalarField::write(), nutLowReWallFunctionFvPatchScalarField::write(), nutkFilmWallFunctionFvPatchScalarField::write(), nutUBlendedWallFunctionFvPatchScalarField::write(), nutURoughWallFunctionFvPatchScalarField::write(), nutUSpaldingWallFunctionFvPatchScalarField::write(), nutUTabulatedWallFunctionFvPatchScalarField::write(), and nutUWallFunctionFvPatchScalarField::write().
Member Data Documentation
UName_
word UName_ protected
Definition at line 104 of file nutWallFunctionFvPatchScalarField.H.
wallCoeffs_
wallFunctionCoefficients wallCoeffs_ protected
Definition at line 107 of file nutWallFunctionFvPatchScalarField.H.
Referenced by atmNutkWallFunctionFvPatchScalarField::calcNut(), atmNutUWallFunctionFvPatchScalarField::calcNut(), atmNutWallFunctionFvPatchScalarField::calcNut(), nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), and nutWallFunctionFvPatchScalarField::wallCoeffs().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutWallFunction/nutWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutWallFunction/nutWallFunctionFvPatchScalarField.C