OpenFOAM: EulerFaD2dt2Scheme< Type > Class Template Reference
EulerFaD2dt2Scheme< Type > Class Template Reference
First-order Euler implicit d2dt2 using the current and two previous time-step values.
#include <EulerFaD2dt2Scheme.H>
Public Member Functions
TypeName ("Euler")
EulerFaD2dt2Scheme (const faMesh &mesh)
EulerFaD2dt2Scheme (const faMesh &mesh, Istream &is)
const faMesh & mesh () const
tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const dimensioned< Type >)
tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const GeometricField< Type, faPatchField, areaMesh > &)
tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const dimensionedScalar &, const GeometricField< Type, faPatchField, areaMesh > &)
tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)
tmp< faMatrix< Type > > famD2dt2 (const GeometricField< Type, faPatchField, areaMesh > &)
tmp< faMatrix< Type > > famD2dt2 (const dimensionedScalar &, const GeometricField< Type, faPatchField, areaMesh > &)
tmp< faMatrix< Type > > famD2dt2 (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)
Public Member Functions inherited from faD2dt2Scheme< Type >
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, faD2dt2Scheme, Istream,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
faD2dt2Scheme (const faMesh &mesh)
faD2dt2Scheme (const faMesh &mesh, Istream &)
virtual ~faD2dt2Scheme ()
const faMesh & mesh () const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from faD2dt2Scheme< Type >
static tmp< faD2dt2Scheme< Type > > New (const faMesh &mesh, Istream &schemeData)
Protected Member Functions inherited from faD2dt2Scheme< Type >
faD2dt2Scheme (const faD2dt2Scheme &)=delete
void operator= (const faD2dt2Scheme &)=delete
Protected Attributes inherited from faD2dt2Scheme< Type >
const faMesh & mesh_
Detailed Description
template<class Type>
class Foam::fa::EulerFaD2dt2Scheme< Type >
First-order Euler implicit d2dt2 using the current and two previous time-step values.
Source files
EulerFaD2dt2Scheme.H
EulerFaD2dt2Scheme.C
Definition at line 53 of file EulerFaD2dt2Scheme.H.
Constructor & Destructor Documentation
EulerFaD2dt2Scheme() [1/2]
template<class Type > EulerFaD2dt2Scheme (const faMesh & mesh) inline
Definition at line 81 of file EulerFaD2dt2Scheme.H.
EulerFaD2dt2Scheme() [2/2]
template<class Type > EulerFaD2dt2Scheme (const faMesh & mesh, Istream & is) inline
Definition at line 87 of file EulerFaD2dt2Scheme.H.
Member Function Documentation
TypeName()
template<class Type > TypeName ("Euler")
mesh()
template<class Type > const faMesh & mesh () const inline
Definition at line 96 of file EulerFaD2dt2Scheme.H.
References faD2dt2Scheme< Type >::mesh().
facD2dt2() [1/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const dimensioned< Type > dt) virtual
Implements faD2dt2Scheme< Type >.
Definition at line 53 of file EulerFaD2dt2Scheme.C.
References faPatchFieldBase::calculatedType(), Foam::dimTime, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::sqr(), timeName, and Foam::Zero.
facD2dt2() [2/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faD2dt2Scheme< Type >.
Definition at line 119 of file EulerFaD2dt2Scheme.C.
References mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::sqr(), and timeName.
facD2dt2() [3/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faD2dt2Scheme< Type >.
Definition at line 196 of file EulerFaD2dt2Scheme.C.
References mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, rho, Foam::sqr(), and timeName.
facD2dt2() [4/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > facD2dt2 (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faD2dt2Scheme< Type >.
Definition at line 281 of file EulerFaD2dt2Scheme.C.
References mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, rho, Foam::sqr(), and timeName.
famD2dt2() [1/3]
template<class Type > tmp< faMatrix< Type > > famD2dt2 (const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faD2dt2Scheme< Type >.
Definition at line 396 of file EulerFaD2dt2Scheme.C.
References Foam::dimArea, Foam::dimTime, mesh, and Foam::sqr().
famD2dt2() [2/3]
template<class Type > tmp< faMatrix< Type > > famD2dt2 (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faD2dt2Scheme< Type >.
Definition at line 455 of file EulerFaD2dt2Scheme.C.
References Foam::dimArea, Foam::dimTime, mesh, rho, and Foam::sqr().
famD2dt2() [3/3]
template<class Type > tmp< faMatrix< Type > > famD2dt2 (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faD2dt2Scheme< Type >.
Definition at line 516 of file EulerFaD2dt2Scheme.C.
References Foam::dimArea, Foam::dimTime, mesh, rho, and Foam::sqr().
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/d2dt2Schemes/EulerFaD2dt2Scheme/EulerFaD2dt2Scheme.H
src/finiteArea/finiteArea/d2dt2Schemes/EulerFaD2dt2Scheme/EulerFaD2dt2Scheme.C