OpenFOAM: chemistryReader< ThermoType > Class Template Reference
chemistryReader< ThermoType > Class Template Reference abstract
Thermophysical models » Reaction thermophysical models » Chemistry readers
Abstract class for reading chemistry.
#include <chemistryReader.H>
Public Types
typedef ThermoType thermoType
Public Member Functions
TypeName ("chemistryReader")
chemistryReader ()
declareRunTimeSelectionTable (autoPtr, chemistryReader, dictionary,(const dictionary &thermoDict, speciesTable &species),(thermoDict, species))
virtual ~chemistryReader ()=default
virtual const speciesTable & species () const =0
virtual const speciesCompositionTable & specieComposition () const =0
virtual const ReactionTable< ThermoType > & speciesThermo () const =0
virtual const ReactionList< ThermoType > & reactions () const =0
Static Public Member Functions
static autoPtr< chemistryReader > New (const dictionary &thermoDict, speciesTable &species)
Detailed Description
template<class ThermoType>
class Foam::chemistryReader< ThermoType >
Abstract class for reading chemistry.
Source files
chemistryReader.H
chemistryReader.C
Definition at line 57 of file chemistryReader.H.
Member Typedef Documentation
thermoType
template<class ThermoType > typedef ThermoType thermoType
Definition at line 65 of file chemistryReader.H.
Constructor & Destructor Documentation
chemistryReader()
template<class ThermoType > chemistryReader () inline
Definition at line 71 of file chemistryReader.H.
~chemistryReader()
template<class ThermoType > virtual ~chemistryReader () virtual default
Member Function Documentation
TypeName()
template<class ThermoType > TypeName ("chemistryReader< ThermoType >")
declareRunTimeSelectionTable()
template<class ThermoType > declareRunTimeSelectionTable (autoPtr , chemistryReader< ThermoType > , dictionary , (const dictionary &thermoDict, speciesTable &species) , (thermoDict, species))
New()
template<class ThermoType > Foam::autoPtr< Foam::chemistryReader< ThermoType > > New (const dictionary & thermoDict, speciesTable & species) static
Definition at line 28 of file chemistryReader.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, PtrList< T >::PtrList(), and thermoDict.
species()
template<class ThermoType > virtual const speciesTable & species () const pure virtual
Implemented in chemkinReader, and foamChemistryReader< ThermoType >.
specieComposition()
template<class ThermoType > virtual const speciesCompositionTable & specieComposition () const pure virtual
Implemented in chemkinReader, and foamChemistryReader< ThermoType >.
speciesThermo()
template<class ThermoType > virtual const ReactionTable< ThermoType > & speciesThermo () const pure virtual
Implemented in chemkinReader, and foamChemistryReader< ThermoType >.
reactions()
template<class ThermoType > virtual const ReactionList< ThermoType > & reactions () const pure virtual
Implemented in chemkinReader, and foamChemistryReader< ThermoType >.
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/chemistryReaders/chemistryReader/chemistryReader.H
src/thermophysicalModels/reactionThermo/chemistryReaders/chemistryReader/chemistryReader.C