OpenFOAM: motionInterpolation Class Reference
motionInterpolation Class Reference
Base class for interpolation of cell displacement fields, generated by fvMotionSolvers, to the points. This base class implements the default method which applies volPointInterpolation only.
#include <motionInterpolation.H>
Public Member Functions
TypeName ("motionInterpolation")
declareRunTimeSelectionTable (autoPtr, motionInterpolation, Istream,(const fvMesh &mesh, Istream &entry),(mesh, entry))
motionInterpolation (const fvMesh &mesh)
motionInterpolation (const fvMesh &mesh, Istream &entry)
virtual ~motionInterpolation ()
const fvMesh & mesh () const
virtual void interpolate (const volScalarField &, pointScalarField &) const
virtual void interpolate (const volVectorField &, pointVectorField &) const
Static Public Member Functions
static autoPtr< motionInterpolation > New (const fvMesh &mesh)
static autoPtr< motionInterpolation > New (const fvMesh &mesh, Istream &entry)
Detailed Description
Base class for interpolation of cell displacement fields, generated by fvMotionSolvers, to the points. This base class implements the default method which applies volPointInterpolation only.
Source files
motionInterpolation.H
motionInterpolation.C
Definition at line 48 of file motionInterpolation.H.
Constructor & Destructor Documentation
motionInterpolation() [1/2]
motionInterpolation (const fvMesh & mesh)
Definition at line 37 of file motionInterpolation.C.
motionInterpolation() [2/2]
motionInterpolation (const fvMesh & mesh, Istream & entry)
Definition at line 46 of file motionInterpolation.C.
~motionInterpolation()
~motionInterpolation () virtual
Definition at line 91 of file motionInterpolation.C.
Member Function Documentation
TypeName()
TypeName ("motionInterpolation")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , motionInterpolation , Istream , (const fvMesh &mesh, Istream &entry) , (mesh, entry))
New() [1/2]
Foam::autoPtr< Foam::motionInterpolation > New (const fvMesh & mesh) static
Definition at line 59 of file motionInterpolation.C.
References mesh, and autoPtr< T >::New().
New() [2/2]
Foam::autoPtr< Foam::motionInterpolation > New (const fvMesh & mesh, Istream & entry) static
Definition at line 66 of file motionInterpolation.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, and mesh.
mesh()
const fvMesh & mesh () const inline
Definition at line 115 of file motionInterpolation.H.
interpolate() [1/2]
void interpolate (const volScalarField & cellDisplacement, pointScalarField & pointDisplacement) const virtual
Reimplemented in patchCorrectedInterpolation, and patchTransformedInterpolation.
Definition at line 97 of file motionInterpolation.C.
References mesh, and MeshObject< fvMesh, UpdateableMeshObject, volPointInterpolation >::New().
interpolate() [2/2]
void interpolate (const volVectorField & cellDisplacement, pointVectorField & pointDisplacement) const virtual
Reimplemented in patchCorrectedInterpolation, and patchTransformedInterpolation.
Definition at line 111 of file motionInterpolation.C.
References mesh, and MeshObject< fvMesh, UpdateableMeshObject, volPointInterpolation >::New().
The documentation for this class was generated from the following files:
src/fvMotionSolver/motionInterpolation/motionInterpolation/motionInterpolation.H
src/fvMotionSolver/motionInterpolation/motionInterpolation/motionInterpolation.C