OpenFOAM: distributedWeightedFvPatchFieldMapper Class Reference
distributedWeightedFvPatchFieldMapper Class Reference
FieldMapper with weighted mapping from (optionally remote) quantities.
#include <distributedWeightedFvPatchFieldMapper.H>
Public Member Functions
distributedWeightedFvPatchFieldMapper (const label singlePatchProc, const mapDistributeBase *distMapPtr, const labelListList &addressing, const scalarListList &weights)
virtual ~distributedWeightedFvPatchFieldMapper ()=default
virtual label size () const
virtual bool direct () const
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
virtual bool hasUnmapped () const
virtual const labelListList & addressing () const
virtual const scalarListList & weights () const
Public Member Functions inherited from fvPatchFieldMapper
fvPatchFieldMapper ()=default
Public Member Functions inherited from FieldMapper
FieldMapper ()=default
virtual ~FieldMapper ()=default
virtual const labelUList & directAddressing () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &fld) const
Detailed Description
FieldMapper with weighted mapping from (optionally remote) quantities.
Definition at line 43 of file distributedWeightedFvPatchFieldMapper.H.
Constructor & Destructor Documentation
distributedWeightedFvPatchFieldMapper()
distributedWeightedFvPatchFieldMapper (const label singlePatchProc, const mapDistributeBase * distMapPtr, const labelListList & addressing, const scalarListList & weights) inline
Definition at line 62 of file distributedWeightedFvPatchFieldMapper.H.
References distributedWeightedFvPatchFieldMapper::addressing(), UPtrList< T >::empty(), Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
~distributedWeightedFvPatchFieldMapper()
virtual ~distributedWeightedFvPatchFieldMapper () virtual default
Member Function Documentation
size()
virtual label size () const inline virtual
Implements FieldMapper.
Definition at line 102 of file distributedWeightedFvPatchFieldMapper.H.
References distributedWeightedFvPatchFieldMapper::addressing(), distributedWeightedFvPatchFieldMapper::distributed(), distributedWeightedFvPatchFieldMapper::distributeMap(), and UPtrList< T >::size().
direct()
virtual bool direct () const inline virtual
Implements FieldMapper.
Definition at line 114 of file distributedWeightedFvPatchFieldMapper.H.
distributed()
virtual bool distributed () const inline virtual
Reimplemented from FieldMapper.
Definition at line 119 of file distributedWeightedFvPatchFieldMapper.H.
Referenced by distributedWeightedFvPatchFieldMapper::size().
distributeMap()
virtual const mapDistributeBase & distributeMap () const inline virtual
Reimplemented from FieldMapper.
Definition at line 124 of file distributedWeightedFvPatchFieldMapper.H.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
Referenced by distributedWeightedFvPatchFieldMapper::size().
hasUnmapped()
virtual bool hasUnmapped () const inline virtual
Implements FieldMapper.
Definition at line 135 of file distributedWeightedFvPatchFieldMapper.H.
addressing()
virtual const labelListList & addressing () const inline virtual
Reimplemented from FieldMapper.
Definition at line 140 of file distributedWeightedFvPatchFieldMapper.H.
Referenced by distributedWeightedFvPatchFieldMapper::distributedWeightedFvPatchFieldMapper(), and distributedWeightedFvPatchFieldMapper::size().
weights()
virtual const scalarListList & weights () const inline virtual
Reimplemented from FieldMapper.
Definition at line 145 of file distributedWeightedFvPatchFieldMapper.H.
The documentation for this class was generated from the following file:
src/sampling/meshToMesh/distributedWeightedFvPatchFieldMapper.H