OpenFOAM: ofstreamPointer Class Reference
ofstreamPointer Class Reference
A wrapped std::ofstream with possible compression handling (ogzstream) that behaves much like a std::unique_ptr.
#include <fstreamPointer.H>
Public Member Functions
ofstreamPointer (const ofstreamPointer &)=delete
ofstreamPointer (ofstreamPointer &&)=default
void operator= (const ofstreamPointer &)=delete
ofstreamPointer & operator= (ofstreamPointer &&)=default
~ofstreamPointer ()=default
ofstreamPointer () noexcept
ofstreamPointer (std::nullptr_t)
ofstreamPointer (const fileName &pathname, IOstreamOption::compressionType comp=IOstreamOption::UNCOMPRESSED, const bool append=false, const bool atomic=false)
std::ostream * get () noexcept
const std::ostream * get () const noexcept
IOstreamOption::compressionType whichCompression () const
std::ostream * release () noexcept
void reset (std::ostream *ptr) noexcept
std::ostream & operator* ()
const std::ostream & operator* () const
std::ostream * operator-> () noexcept
const std::ostream * operator-> () const noexcept
Static Public Member Functions
static bool supports_gz ()
Protected Member Functions
void reopen (const std::string &pathname)
void close (const std::string &pathname)
Detailed Description
A wrapped std::ofstream with possible compression handling (ogzstream) that behaves much like a std::unique_ptr.
Note
No operator bool to avoid inheritance ambiguity with std::ios::operator bool.
Source files
fstreamPointer.H
fstreamPointers.C
Definition at line 164 of file fstreamPointer.H.
Constructor & Destructor Documentation
ofstreamPointer() [1/5]
ofstreamPointer (const ofstreamPointer &) delete
ofstreamPointer() [2/5]
ofstreamPointer (ofstreamPointer &&) default
~ofstreamPointer()
~ofstreamPointer () default
ofstreamPointer() [3/5]
ofstreamPointer () noexcept
Definition at line 106 of file fstreamPointers.C.
ofstreamPointer() [4/5]
ofstreamPointer (std::nullptr_t) explicit
Definition at line 113 of file fstreamPointers.C.
ofstreamPointer() [5/5]
ofstreamPointer (const fileName & pathname, IOstreamOption::compressionType comp = IOstreamOption::UNCOMPRESSED, const bool append = false, const bool atomic = false) explicit
Definition at line 120 of file fstreamPointers.C.
References append(), IOstreamOption::COMPRESSED, Foam::endl(), fileName::FILE, Foam::mode(), Foam::nl, Foam::rm(), fileName::SYMLINK, Foam::type(), IOstreamOption::UNCOMPRESSED, fileName::UNDEFINED, and Foam::Warning.
Member Function Documentation
reopen()
void reopen (const std::string & pathname) protected
Definition at line 253 of file fstreamPointers.C.
References PtrList< T >::clear().
Referenced by OFstream::rewind().
close()
void close (const std::string & pathname) protected
Definition at line 318 of file fstreamPointers.C.
References PtrList< T >::clear(), and UPtrList< T >::empty().
Referenced by OFstream::~OFstream().
operator=() [1/2]
void operator= (const ofstreamPointer &) delete
operator=() [2/2]
ofstreamPointer & operator= (ofstreamPointer &&) default
supports_gz()
bool supports_gz () static
Definition at line 46 of file fstreamPointers.C.
Referenced by Time::readDict().
get() [1/2]
std::ostream * get () inline noexcept
Definition at line 239 of file fstreamPointer.H.
References UPtrList< T >::get().
Referenced by OFstream::OFstream(), OFstream::OFstream(), OFstream::rewind(), OFstream::stdStream(), and OFstream::stdStream().
get() [2/2]
const std::ostream * get () const inline noexcept
Definition at line 242 of file fstreamPointer.H.
References UPtrList< T >::get().
whichCompression()
Foam::IOstreamOption::compressionType whichCompression () const
Definition at line 375 of file fstreamPointers.C.
References IOstreamOption::COMPRESSED, and IOstreamOption::UNCOMPRESSED.
release()
std::ostream * release () inline noexcept
Definition at line 251 of file fstreamPointer.H.
References PtrList< T >::release().
reset()
void reset (std::ostream * ptr) inline noexcept
Definition at line 254 of file fstreamPointer.H.
operator*() [1/2]
std::ostream & operator* () inline
Definition at line 260 of file fstreamPointer.H.
operator*() [2/2]
const std::ostream & operator* () const inline
Definition at line 263 of file fstreamPointer.H.
operator->() [1/2]
std::ostream * operator-> () inline noexcept
Definition at line 266 of file fstreamPointer.H.
References UPtrList< T >::get().
operator->() [2/2]
const std::ostream * operator-> () const inline noexcept
Definition at line 269 of file fstreamPointer.H.
References UPtrList< T >::get().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Fstreams/fstreamPointer.H
src/OpenFOAM/db/IOstreams/Fstreams/fstreamPointers.C