OpenFOAM: removeCells Class Reference
removeCells Class Reference
Given list of cells to remove, insert all the topology changes.
#include <removeCells.H>
Public Member Functions
ClassName ("removeCells")
removeCells (const polyMesh &mesh, const bool syncPar=true)
~removeCells ()=default
labelList getExposedFaces (const bitSet &removedCell) const
labelList getExposedFaces (const labelUList &cellsToRemove) const
void setRefinement (const bitSet &removedCell, const labelUList &facesToExpose, const labelUList &patchIDs, polyTopoChange &) const
void setRefinement (const labelUList &cellsToRemove, const labelUList &facesToExpose, const labelUList &patchIDs, polyTopoChange &) const
void updateMesh (const mapPolyMesh &)
Detailed Description
Given list of cells to remove, insert all the topology changes.
Works in two passes:
get faces that will become boundary faces
given these faces and the patches they have to go into make the changes.
Source files
removeCells.H
removeCells.C
Definition at line 59 of file removeCells.H.
Constructor & Destructor Documentation
removeCells()
removeCells (const polyMesh & mesh, const bool syncPar = true) explicit
Definition at line 67 of file removeCells.C.
~removeCells()
~removeCells () default
Member Function Documentation
ClassName()
ClassName ("removeCells")
getExposedFaces() [1/2]
Foam::labelList getExposedFaces (const bitSet & removedCell) const
Definition at line 76 of file removeCells.C.
References PtrList< T >::append(), forAll, patches, pp(), syncTools::syncBoundaryFaceList(), and Foam::Zero.
Referenced by fvMeshSubsetter::getExposedFaces(), and fvMeshSubsetter::getExposedFaces().
getExposedFaces() [2/2]
Foam::labelList getExposedFaces (const labelUList & cellsToRemove) const
Definition at line 472 of file removeCells.C.
setRefinement() [1/2]
void setRefinement (const bitSet & removedCell, const labelUList & facesToExpose, const labelUList & patchIDs, polyTopoChange & meshMod) const
Definition at line 180 of file removeCells.C.
References Foam::abort(), coupled(), Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, patches, pp(), polyTopoChange::setAction(), UPtrList< T >::size(), WarningInFunction, ZoneMesh< ZoneType, MeshType >::whichZone(), and Foam::Zero.
setRefinement() [2/2]
void setRefinement (const labelUList & cellsToRemove, const labelUList & facesToExpose, const labelUList & patchIDs, polyTopoChange & meshMod) const
Definition at line 483 of file removeCells.C.
updateMesh()
void updateMesh (const mapPolyMesh &) inline
Definition at line 125 of file removeCells.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/removeCells.H
src/dynamicMesh/polyTopoChange/polyTopoChange/removeCells.C