OpenFOAM: incompressibleAdjointMeanFlowVars Class Reference
incompressibleAdjointMeanFlowVars Class Reference
Manages the adjoint mean flow fields and their mean values.
#include <incompressibleAdjointMeanFlowVars.H>
Public Member Functions
TypeName ("incompressibleAdjointMeanFlowVars")
incompressibleAdjointMeanFlowVars (fvMesh &mesh, solverControl &SolverControl, incompressibleVars &primalVars)
virtual ~incompressibleAdjointMeanFlowVars ()=default
const incompressibleVars & primalVars () const
const volScalarField & pa () const
volScalarField & pa ()
const volVectorField & Ua () const
volVectorField & Ua ()
const surfaceScalarField & phia () const
surfaceScalarField & phia ()
const volScalarField & paInst () const
volScalarField & paInst ()
const volVectorField & UaInst () const
volVectorField & UaInst ()
const surfaceScalarField & phiaInst () const
surfaceScalarField & phiaInst ()
bool computeMeanFields () const
const solverControl & getSolverControl () const
virtual void nullify ()
Public Member Functions inherited from variablesSet
TypeName ("variablesSet")
variablesSet (fvMesh &mesh, const dictionary &dict)
virtual autoPtr< variablesSet > clone () const
virtual ~variablesSet ()=default
const word & solverName () const
bool useSolverNameForFields () const
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > allocateField (const fvMesh &mesh, const word &baseName, const word &solverName, const bool useSolverNameForFields)
template<class Type >
void renameTurbulenceField (GeometricField< Type, fvPatchField, volMesh > &baseField, const word &solverName)
tmp< surfaceScalarField > allocateFluxField (const fvMesh &mesh, const volVectorField &velocity, const word &baseName, const word &solverName, const bool useSolverNameForFields)
virtual void transfer (variablesSet &vars)
Protected Member Functions
void setFields ()
void setMeanFields ()
Protected Member Functions inherited from variablesSet
template<class Type , template< class > class PatchField, class GeoMesh >
autoPtr< GeometricField< Type, PatchField, GeoMesh > > allocateRenamedField (const autoPtr< GeometricField< Type, PatchField, GeoMesh > > &bf)
template<class Type , template< class > class PatchField, class GeoMesh >
void swapAndRename (autoPtr< GeometricField< Type, PatchField, GeoMesh > > &p1, autoPtr< GeometricField< Type, PatchField, GeoMesh > > &p2)
Protected Attributes
solverControl & solverControl_
incompressibleVars & primalVars_
autoPtr< volScalarField > paPtr_
autoPtr< volVectorField > UaPtr_
autoPtr< surfaceScalarField > phiaPtr_
autoPtr< volScalarField > paMeanPtr_
autoPtr< volVectorField > UaMeanPtr_
autoPtr< surfaceScalarField > phiaMeanPtr_
Protected Attributes inherited from variablesSet
fvMesh & mesh_
word solverName_
bool useSolverNameForFields_
Additional Inherited Members
Static Public Member Functions inherited from variablesSet
template<class Type >
static void setField (autoPtr< GeometricField< Type, fvPatchField, volMesh > > &fieldPtr, const fvMesh &mesh, const word &baseName, const word &solverName, const bool useSolverNameForFields)
static void setFluxField (autoPtr< surfaceScalarField > &fieldPtr, const fvMesh &mesh, const volVectorField &velocity, const word &baseName, const word &solverName, const bool useSolverNameForFields)
static tmp< volVectorField > autoCreateMeshMovementField (const fvMesh &mesh, const word &name, const dimensionSet &dims)
template<class Type , template< class > class PatchField, class GeoMesh >
static void nullifyField (GeometricField< Type, PatchField, GeoMesh > &fieldPtr)
Detailed Description
Manages the adjoint mean flow fields and their mean values.
Definition at line 45 of file incompressibleAdjointMeanFlowVars.H.
Constructor & Destructor Documentation
incompressibleAdjointMeanFlowVars()
incompressibleAdjointMeanFlowVars (fvMesh & mesh, solverControl & SolverControl, incompressibleVars & primalVars)
Definition at line 111 of file incompressibleAdjointMeanFlowVars.C.
References incompressibleAdjointMeanFlowVars::setFields(), and incompressibleAdjointMeanFlowVars::setMeanFields().
~incompressibleAdjointMeanFlowVars()
virtual ~incompressibleAdjointMeanFlowVars () virtual default
Member Function Documentation
setFields()
void setFields () protected
Definition at line 36 of file incompressibleAdjointMeanFlowVars.C.
References variablesSet::mesh_, incompressibleAdjointMeanFlowVars::paPtr_, incompressibleAdjointMeanFlowVars::phiaPtr_, variablesSet::setField(), variablesSet::setFluxField(), schemesLookup::setFluxRequired(), variablesSet::solverName_, incompressibleAdjointMeanFlowVars::UaInst(), incompressibleAdjointMeanFlowVars::UaPtr_, and variablesSet::useSolverNameForFields_.
Referenced by incompressibleAdjointMeanFlowVars::incompressibleAdjointMeanFlowVars().
setMeanFields()
void setMeanFields () protected
Definition at line 53 of file incompressibleAdjointMeanFlowVars.C.
References IOobjectOption::AUTO_WRITE, solverControl::average(), Foam::endl(), Foam::Info, variablesSet::mesh_, Foam::name(), incompressibleAdjointMeanFlowVars::paInst(), incompressibleAdjointMeanFlowVars::paMeanPtr_, incompressibleAdjointMeanFlowVars::phiaInst(), incompressibleAdjointMeanFlowVars::phiaMeanPtr_, IOobjectOption::READ_IF_PRESENT, incompressibleAdjointMeanFlowVars::solverControl_, fvMesh::time(), incompressibleAdjointMeanFlowVars::UaInst(), and incompressibleAdjointMeanFlowVars::UaMeanPtr_.
Referenced by incompressibleAdjointMeanFlowVars::incompressibleAdjointMeanFlowVars().
TypeName()
TypeName ("incompressibleAdjointMeanFlowVars")
primalVars()
const incompressibleVars & primalVars () const
Definition at line 135 of file incompressibleAdjointMeanFlowVars.C.
References incompressibleAdjointMeanFlowVars::primalVars_.
pa() [1/2]
const volScalarField & pa () const
Definition at line 140 of file incompressibleAdjointMeanFlowVars.C.
References incompressibleAdjointMeanFlowVars::paMeanPtr_, incompressibleAdjointMeanFlowVars::paPtr_, incompressibleAdjointMeanFlowVars::solverControl_, and solverControl::useAveragedFields().
Referenced by sensitivitySurface::accumulateIntegrand(), sensitivitySurfacePoints::accumulateIntegrand(), and shapeSensitivities::dvdbMult().
pa() [2/2]
volScalarField & pa ()
Definition at line 153 of file incompressibleAdjointMeanFlowVars.C.
References incompressibleAdjointMeanFlowVars::paMeanPtr_, incompressibleAdjointMeanFlowVars::paPtr_, incompressibleAdjointMeanFlowVars::solverControl_, and solverControl::useAveragedFields().
Ua() [1/2]
const volVectorField & Ua () const
Definition at line 166 of file incompressibleAdjointMeanFlowVars.C.
References incompressibleAdjointMeanFlowVars::solverControl_, incompressibleAdjointMeanFlowVars::UaMeanPtr_, incompressibleAdjointMeanFlowVars::UaPtr_, and solverControl::useAveragedFields().
Referenced by shapeSensitivities::accumulateBCSensitivityIntegrand(), sensitivitySurface::accumulateIntegrand(), sensitivitySurfacePoints::accumulateIntegrand(), adjointLaminar::devReff(), adjointSpalartAllmaras::distanceSensitivities(), and shapeSensitivities::dvdbMult().
Ua() [2/2]
volVectorField & Ua ()
Definition at line 179 of file incompressibleAdjointMeanFlowVars.C.
References incompressibleAdjointMeanFlowVars::solverControl_, incompressibleAdjointMeanFlowVars::UaMeanPtr_, incompressibleAdjointMeanFlowVars::UaPtr_, and solverControl::useAveragedFields().
phia() [1/2]
const surfaceScalarField & phia () const
Definition at line 192 of file incompressibleAdjointMeanFlowVars.C.
References incompressibleAdjointMeanFlowVars::phiaMeanPtr_, incompressibleAdjointMeanFlowVars::phiaPtr_, incompressibleAdjointMeanFlowVars::solverControl_, and solverControl::useAveragedFields().
phia() [2/2]
surfaceScalarField & phia ()
Definition at line 205 of file incompressibleAdjointMeanFlowVars.C.
References incompressibleAdjointMeanFlowVars::phiaMeanPtr_, incompressibleAdjointMeanFlowVars::phiaPtr_, incompressibleAdjointMeanFlowVars::solverControl_, and solverControl::useAveragedFields().
paInst() [1/2]
const Foam::volScalarField & paInst () const inline
Definition at line 25 of file incompressibleAdjointMeanFlowVarsI.H.
References incompressibleAdjointMeanFlowVars::paPtr_.
Referenced by adjointSimple::adjointSimple(), and incompressibleAdjointMeanFlowVars::setMeanFields().
paInst() [2/2]
Foam::volScalarField & paInst () inline
Definition at line 31 of file incompressibleAdjointMeanFlowVarsI.H.
UaInst() [1/2]
const Foam::volVectorField & UaInst () const inline
Definition at line 38 of file incompressibleAdjointMeanFlowVarsI.H.
Referenced by adjointkOmegaSST::adjointMeanFlowSource(), adjointSpalartAllmaras::correct(), adjointkOmegaSST::devReff(), adjointSpalartAllmaras::devReff(), adjointkOmegaSST::dR_dnut(), incompressibleAdjointMeanFlowVars::setFields(), and incompressibleAdjointMeanFlowVars::setMeanFields().
UaInst() [2/2]
Foam::volVectorField & UaInst () inline
Definition at line 44 of file incompressibleAdjointMeanFlowVarsI.H.
phiaInst() [1/2]
const Foam::surfaceScalarField & phiaInst () const inline
Definition at line 51 of file incompressibleAdjointMeanFlowVarsI.H.
Referenced by incompressibleAdjointMeanFlowVars::setMeanFields().
phiaInst() [2/2]
Foam::surfaceScalarField & phiaInst () inline
Definition at line 58 of file incompressibleAdjointMeanFlowVarsI.H.
computeMeanFields()
bool computeMeanFields () const
Definition at line 218 of file incompressibleAdjointMeanFlowVars.C.
References solverControl::average(), and incompressibleAdjointMeanFlowVars::solverControl_.
getSolverControl()
const solverControl & getSolverControl () const
Definition at line 224 of file incompressibleAdjointMeanFlowVars.C.
References incompressibleAdjointMeanFlowVars::solverControl_.
Referenced by adjointRASModel::computeMeanFields(), adjointkOmegaSST::correct(), adjointSpalartAllmaras::correct(), adjointRASModel::getAdjointTMVariable1(), adjointRASModel::getAdjointTMVariable2(), adjointRASModel::resetMeanFields(), and adjointRASModel::setMeanFields().
nullify()
void nullify () virtual
Reimplemented in incompressibleAdjointVars.
Definition at line 230 of file incompressibleAdjointMeanFlowVars.C.
References variablesSet::nullifyField(), incompressibleAdjointMeanFlowVars::paPtr_, incompressibleAdjointMeanFlowVars::phiaPtr_, and incompressibleAdjointMeanFlowVars::UaPtr_.
Referenced by incompressibleAdjointVars::nullify().
Member Data Documentation
solverControl_
solverControl& solverControl_ protected
Definition at line 68 of file incompressibleAdjointMeanFlowVars.H.
Referenced by incompressibleAdjointVars::computeMeanFields(), incompressibleAdjointMeanFlowVars::computeMeanFields(), incompressibleAdjointMeanFlowVars::getSolverControl(), incompressibleAdjointMeanFlowVars::pa(), incompressibleAdjointMeanFlowVars::pa(), incompressibleAdjointMeanFlowVars::phia(), incompressibleAdjointMeanFlowVars::phia(), incompressibleAdjointVars::resetMeanFields(), incompressibleAdjointMeanFlowVars::setMeanFields(), incompressibleAdjointMeanFlowVars::Ua(), and incompressibleAdjointMeanFlowVars::Ua().
primalVars_
incompressibleVars& primalVars_ protected
Definition at line 71 of file incompressibleAdjointMeanFlowVars.H.
Referenced by incompressibleAdjointMeanFlowVars::primalVars().
paPtr_
autoPtr<volScalarField> paPtr_ protected
Definition at line 75 of file incompressibleAdjointMeanFlowVars.H.
Referenced by incompressibleAdjointVars::computeMeanFields(), incompressibleAdjointMeanFlowVars::nullify(), incompressibleAdjointMeanFlowVars::pa(), incompressibleAdjointMeanFlowVars::pa(), incompressibleAdjointMeanFlowVars::paInst(), incompressibleAdjointVars::resetMeanFields(), and incompressibleAdjointMeanFlowVars::setFields().
UaPtr_
autoPtr<volVectorField> UaPtr_ protected
Definition at line 76 of file incompressibleAdjointMeanFlowVars.H.
Referenced by incompressibleAdjointVars::computeMeanFields(), incompressibleAdjointMeanFlowVars::nullify(), incompressibleAdjointVars::resetMeanFields(), incompressibleAdjointMeanFlowVars::setFields(), incompressibleAdjointMeanFlowVars::Ua(), and incompressibleAdjointMeanFlowVars::Ua().
phiaPtr_
autoPtr<surfaceScalarField> phiaPtr_ protected
Definition at line 77 of file incompressibleAdjointMeanFlowVars.H.
Referenced by incompressibleAdjointVars::computeMeanFields(), incompressibleAdjointMeanFlowVars::nullify(), incompressibleAdjointMeanFlowVars::phia(), incompressibleAdjointMeanFlowVars::phia(), incompressibleAdjointVars::resetMeanFields(), and incompressibleAdjointMeanFlowVars::setFields().
paMeanPtr_
autoPtr<volScalarField> paMeanPtr_ protected
Definition at line 82 of file incompressibleAdjointMeanFlowVars.H.
Referenced by incompressibleAdjointVars::computeMeanFields(), incompressibleAdjointMeanFlowVars::pa(), incompressibleAdjointMeanFlowVars::pa(), incompressibleAdjointVars::resetMeanFields(), and incompressibleAdjointMeanFlowVars::setMeanFields().
UaMeanPtr_
autoPtr<volVectorField> UaMeanPtr_ protected
Definition at line 83 of file incompressibleAdjointMeanFlowVars.H.
Referenced by incompressibleAdjointVars::computeMeanFields(), incompressibleAdjointVars::resetMeanFields(), incompressibleAdjointMeanFlowVars::setMeanFields(), incompressibleAdjointMeanFlowVars::Ua(), and incompressibleAdjointMeanFlowVars::Ua().
phiaMeanPtr_
autoPtr<surfaceScalarField> phiaMeanPtr_ protected
Definition at line 84 of file incompressibleAdjointMeanFlowVars.H.
Referenced by incompressibleAdjointVars::computeMeanFields(), incompressibleAdjointMeanFlowVars::phia(), incompressibleAdjointMeanFlowVars::phia(), incompressibleAdjointVars::resetMeanFields(), and incompressibleAdjointMeanFlowVars::setMeanFields().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/solvers/variablesSet/incompressibleAdjointMeanFlow/incompressibleAdjointMeanFlowVars.H
src/optimisation/adjointOptimisation/adjoint/solvers/variablesSet/incompressibleAdjointMeanFlow/incompressibleAdjointMeanFlowVars.C
src/optimisation/adjointOptimisation/adjoint/solvers/variablesSet/incompressibleAdjointMeanFlow/incompressibleAdjointMeanFlowVarsI.H