OpenFOAM: interpolationCellPoint< Type > Class Template Reference
interpolationCellPoint< Type > Class Template Reference
Given cell centre values and point (vertex) values decompose into tetrahedra and linear interpolate within them.
#include <interpolationCellPoint.H>
Public Member Functions
TypeName ("cellPoint")
interpolationCellPoint (const GeometricField< Type, fvPatchField, volMesh > &psi)
Type interpolate (const cellPointWeight &cpw) const
Type interpolate (const vector &position, const label celli, const label facei=-1) const
Type interpolate (const barycentric &coordinates, const tetIndices &tetIs, const label facei=-1) const
Public Member Functions inherited from interpolation< Type >
virtual const word & type () const =0
declareRunTimeSelectionTable (autoPtr, interpolation, dictionary,(const GeometricField< Type, fvPatchField, volMesh > &psi),(psi))
interpolation (const GeometricField< Type, fvPatchField, volMesh > &psi)
virtual ~interpolation ()=default
const GeometricField< Type, fvPatchField, volMesh > & psi () const noexcept
Protected Attributes
const GeometricField< Type, pointPatchField, pointMesh > psip_
Protected Attributes inherited from interpolation< Type >
const GeometricField< Type, fvPatchField, volMesh > & psi_
const polyMesh & pMesh_
const vectorField & pMeshPoints_
const faceList & pMeshFaces_
const vectorField & pMeshFaceCentres_
const vectorField & pMeshFaceAreas_
Additional Inherited Members
Static Public Member Functions inherited from interpolation< Type >
static autoPtr< interpolation< Type > > New (const word &interpolationType, const GeometricField< Type, fvPatchField, volMesh > &psi)
static autoPtr< interpolation< Type > > New (const dictionary &interpolationSchemes, const GeometricField< Type, fvPatchField, volMesh > &psi)
Detailed Description
template<class Type>
class Foam::interpolationCellPoint< Type >
Given cell centre values and point (vertex) values decompose into tetrahedra and linear interpolate within them.
Definition at line 44 of file interpolationCellPoint.H.
Constructor & Destructor Documentation
interpolationCellPoint()
template<class Type > interpolationCellPoint (const GeometricField< Type, fvPatchField, volMesh > & psi) explicit
Definition at line 27 of file interpolationCellPoint.C.
References Foam::name(), Foam::New(), and interpolation< Type >::psi().
Member Function Documentation
TypeName()
template<class Type > TypeName ("cellPoint")
interpolate() [1/3]
template<class Type > Type interpolate (const cellPointWeight & cpw) const inline
Definition at line 24 of file interpolationCellPointI.H.
Referenced by interpolationCellPointWallModified< Type >::interpolate(), interpolationCellPointWallModified< Type >::interpolate(), and interpolationCellPointWallModified< Type >::interpolate().
interpolate() [2/3]
template<class Type > Type interpolate (const vector & position, const label celli, const label facei = -1) const inline virtual
Implements interpolation< Type >.
Reimplemented in interpolationCellPointWallModified< Type >.
Definition at line 42 of file interpolationCellPointI.H.
References Foam::interpolate().
interpolate() [3/3]
template<class Type > Type interpolate (const barycentric & coordinates, const tetIndices & tetIs, const label facei = -1) const inline virtual
Reimplemented from interpolation< Type >.
Reimplemented in interpolationCellPointWallModified< Type >.
Definition at line 54 of file interpolationCellPointI.H.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
Member Data Documentation
psip_
template<class Type > const GeometricField<Type, pointPatchField, pointMesh> psip_ protected
Definition at line 53 of file interpolationCellPoint.H.
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/interpolation/interpolationCellPoint/interpolationCellPoint.H
src/finiteVolume/interpolation/interpolation/interpolationCellPoint/interpolationCellPoint.C
src/finiteVolume/interpolation/interpolation/interpolationCellPoint/interpolationCellPointI.H