OpenFOAM: engineValve Class Reference
engineValve Class Reference
Foam::engineValve.
#include <engineValve.H>
Public Member Functions
engineValve (const word &name, const polyMesh &mesh, const autoPtr< coordinateSystem > &valveCS, const word &bottomPatchName, const word &poppetPatchName, const word &stemPatchName, const word &curtainInPortPatchName, const word &curtainInCylinderPatchName, const word &detachInCylinderPatchName, const word &detachInPortPatchName, const labelList &detachFaces, const graph &liftProfile, const scalar minLift, const scalar minTopLayer, const scalar maxTopLayer, const scalar minBottomLayer, const scalar maxBottomLayer, const scalar diameter)
engineValve (const word &name, const polyMesh &mesh, const dictionary &dict)
~engineValve ()=default
const word & name () const
const coordinateSystem & cs () const
const graph & liftProfile () const
scalar diameter () const
const polyPatchID & bottomPatchID () const
const polyPatchID & poppetPatchID () const
const polyPatchID & stemPatchID () const
const polyPatchID & curtainInCylinderPatchID () const
const polyPatchID & curtainInPortPatchID () const
const polyPatchID & detachInCylinderPatchID () const
const polyPatchID & detachInPortPatchID () const
const labelList & detachFaces () const
scalar minTopLayer () const
scalar maxTopLayer () const
scalar minBottomLayer () const
scalar maxBottomLayer () const
scalar lift (const scalar theta) const
bool isOpen () const
scalar curLift () const
scalar curVelocity () const
labelList movingPatchIDs () const
void writeDict (Ostream &os) const
Detailed Description
Foam::engineValve.
Source files
engineValve.H
engineValve.C
Definition at line 53 of file engineValve.H.
Constructor & Destructor Documentation
engineValve() [1/2]
engineValve (const word & name, const polyMesh & mesh, const autoPtr< coordinateSystem > & valveCS, const word & bottomPatchName, const word & poppetPatchName, const word & stemPatchName, const word & curtainInPortPatchName, const word & curtainInCylinderPatchName, const word & detachInCylinderPatchName, const word & detachInPortPatchName, const labelList & detachFaces, const graph & liftProfile, const scalar minLift, const scalar minTopLayer, const scalar maxTopLayer, const scalar minBottomLayer, const scalar maxBottomLayer, const scalar diameter)
Definition at line 62 of file engineValve.C.
engineValve() [2/2]
engineValve (const word & name, const polyMesh & mesh, const dictionary & dict)
Definition at line 108 of file engineValve.C.
~engineValve()
~engineValve () default
Member Function Documentation
name()
const word & name () const inline
Definition at line 186 of file engineValve.H.
cs()
const coordinateSystem & cs () const inline
Definition at line 192 of file engineValve.H.
liftProfile()
const graph & liftProfile () const inline
Definition at line 198 of file engineValve.H.
diameter()
scalar diameter () const inline
Definition at line 204 of file engineValve.H.
bottomPatchID()
const polyPatchID & bottomPatchID () const inline
Definition at line 213 of file engineValve.H.
poppetPatchID()
const polyPatchID & poppetPatchID () const inline
Definition at line 219 of file engineValve.H.
stemPatchID()
const polyPatchID & stemPatchID () const inline
Definition at line 225 of file engineValve.H.
curtainInCylinderPatchID()
const polyPatchID & curtainInCylinderPatchID () const inline
Definition at line 231 of file engineValve.H.
curtainInPortPatchID()
const polyPatchID & curtainInPortPatchID () const inline
Definition at line 237 of file engineValve.H.
detachInCylinderPatchID()
const polyPatchID & detachInCylinderPatchID () const inline
Definition at line 244 of file engineValve.H.
detachInPortPatchID()
const polyPatchID & detachInPortPatchID () const inline
Definition at line 250 of file engineValve.H.
detachFaces()
const labelList & detachFaces () const inline
Definition at line 256 of file engineValve.H.
minTopLayer()
scalar minTopLayer () const inline
Definition at line 264 of file engineValve.H.
maxTopLayer()
scalar maxTopLayer () const inline
Definition at line 269 of file engineValve.H.
minBottomLayer()
scalar minBottomLayer () const inline
Definition at line 274 of file engineValve.H.
maxBottomLayer()
scalar maxBottomLayer () const inline
Definition at line 279 of file engineValve.H.
lift()
Foam::scalar lift (const scalar theta) const
Definition at line 172 of file engineValve.C.
References Foam::interpolateXY().
isOpen()
bool isOpen () const
Definition at line 183 of file engineValve.C.
curLift()
Foam::scalar curLift () const
Definition at line 189 of file engineValve.C.
References Foam::max().
curVelocity()
Foam::scalar curVelocity () const
Definition at line 199 of file engineValve.C.
References Foam::max().
movingPatchIDs()
Foam::labelList movingPatchIDs () const
Definition at line 213 of file engineValve.C.
References PtrList< T >::setSize().
writeDict()
void writeDict (Ostream & os) const
Definition at line 236 of file engineValve.C.
References token::BEGIN_BLOCK, token::END_BLOCK, token::END_STATEMENT, Foam::endl(), OFstream::name(), Foam::name(), Foam::nl, and os().
The documentation for this class was generated from the following files:
src/engine/engineValve/engineValve.H
src/engine/engineValve/engineValve.C