OpenFOAM: faNVDscheme< Type, NVDweight > Class Template Reference
faNVDscheme< Type, NVDweight > Class Template Reference
Class to create the weighting-factors based on the NVD (Normalised Variable Diagram).
#include <faNVDscheme.H>
Public Types
typedef NVDweight Weight
Public Member Functions
TypeName ("faNVDscheme")
faNVDscheme (const faMesh &mesh, const edgeScalarField &edgeFlux, const NVDweight &weight)
faNVDscheme (const faMesh &mesh, Istream &is)
faNVDscheme (const faMesh &mesh, const edgeScalarField &edgeFlux, Istream &is)
virtual tmp< edgeScalarField > weights (const GeometricField< Type, faPatchField, areaMesh > &) const
Public Member Functions inherited from edgeInterpolationScheme< Type >
declareRunTimeSelectionTable (tmp, edgeInterpolationScheme, Mesh,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, edgeInterpolationScheme, MeshFlux,(const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
edgeInterpolationScheme (const faMesh &mesh)
virtual ~edgeInterpolationScheme ()
const faMesh & mesh () const
virtual bool corrected () const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > correction (const GeometricField< Type, faPatchField, areaMesh > &) const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &) const
virtual tmp< GeometricField< Type, faePatchField, edgeMesh > > euclidianInterpolate (const GeometricField< Type, faPatchField, areaMesh > &) const
tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh > > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Protected Member Functions
faNVDscheme (const faNVDscheme &)=delete
void operator= (const faNVDscheme &)=delete
Protected Attributes
const edgeScalarField & edgeFlux_
Additional Inherited Members
Static Public Member Functions inherited from edgeInterpolationScheme< Type >
static tmp< edgeInterpolationScheme< Type > > New (const faMesh &mesh, Istream &schemeData)
static tmp< edgeInterpolationScheme< Type > > New (const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &, const tmp< edgeScalarField > &, const tmp< edgeScalarField > &)
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &, const tmp< edgeScalarField > &)
static tmp< GeometricField< Type, faePatchField, edgeMesh > > euclidianInterpolate (const GeometricField< Type, faPatchField, areaMesh > &, const tmp< edgeScalarField > &)
Detailed Description
template<class Type, class NVDweight>
class Foam::faNVDscheme< Type, NVDweight >
Class to create the weighting-factors based on the NVD (Normalised Variable Diagram).
The particular differencing scheme class is supplied as a template argument, the weight function of which is called by the weight function of this class for the internal edges as well as edges of coupled patches (e.g. processor-processor patches). The weight function is supplied the central-differencing weighting factor, the edge-flux, the cell and edge gradients (from which the normalised variable distribution may be created) and the cell centre distance.
This code organisation is both neat and efficient, allowing for convenient implementation of new schemes to run on parallelised cases.
Source files
faNVDscheme.H
faNVDscheme.C
Definition at line 59 of file faNVDscheme.H.
Member Typedef Documentation
Weight
template<class Type , class NVDweight > typedef NVDweight Weight
Definition at line 82 of file faNVDscheme.H.
Constructor & Destructor Documentation
faNVDscheme() [1/4]
template<class Type , class NVDweight > faNVDscheme (const faNVDscheme< Type, NVDweight > &) protected delete
faNVDscheme() [2/4]
template<class Type , class NVDweight > faNVDscheme (const faMesh & mesh, const edgeScalarField & edgeFlux, const NVDweight & weight) inline
Definition at line 92 of file faNVDscheme.H.
faNVDscheme() [3/4]
template<class Type , class NVDweight > faNVDscheme (const faMesh & mesh, Istream & is) inline
Definition at line 107 of file faNVDscheme.H.
faNVDscheme() [4/4]
template<class Type , class NVDweight > faNVDscheme (const faMesh & mesh, const edgeScalarField & edgeFlux, Istream & is) inline
Definition at line 125 of file faNVDscheme.H.
Member Function Documentation
operator=()
template<class Type , class NVDweight > void operator= (const faNVDscheme< Type, NVDweight > &) protected delete
TypeName()
template<class Type , class NVDweight > TypeName ("faNVDscheme< Type, NVDweight >")
weights()
template<class Type , class NVDweight > Foam::tmp< Foam::edgeScalarField > weights (const GeometricField< Type, faPatchField, areaMesh > & phi) const virtual
Implements edgeInterpolationScheme< Type >.
Definition at line 51 of file faNVDscheme.C.
References coupled(), forAll, Foam::fac::grad(), Foam::limiter(), Vector< Cmpt >::magSqr(), mesh, n, Vector< Cmpt >::normalise(), phi, PtrList< T >::PtrList(), Vector< Cmpt >::removeCollinear(), and VectorSpace< Form, Cmpt, Ncmpts >::uniform().
Member Data Documentation
edgeFlux_
template<class Type , class NVDweight > const edgeScalarField& edgeFlux_ protected
Definition at line 68 of file faNVDscheme.H.
The documentation for this class was generated from the following files:
src/finiteArea/interpolation/edgeInterpolation/schemes/NVDscheme/faNVDscheme.H
src/finiteArea/interpolation/edgeInterpolation/schemes/NVDscheme/faNVDscheme.C