OpenFOAM: ensightCells Class Reference
ensightCells Class Reference
Sorting/classification of cells (3D) into corresponding ensight element types.
#include <ensightCells.H>
Public Types
enum elemType {
TETRA4 = 0 , PYRAMID5 , PENTA6 , HEXA8 ,
NFACED
}
Public Member Functions
TypeName ("ensightCells")
ensightCells ()
ensightCells (const string &description)
virtual ~ensightCells ()=default
bool manifold () const noexcept
label size (const elemType etype) const
labelRange range (const elemType etype) const
label totalSize () const noexcept
label total () const noexcept
label total (const elemType etype) const
const FixedList< label, nTypes > & totals () const
FixedList< label, nTypes > sizes () const
const labelList & cellIds () const
const labelUList cellIds (const elemType etype) const
Map< label > meshPointMap (const polyMesh &mesh) const
void classify (const polyMesh &mesh)
void classify (const polyMesh &mesh, const labelUList &cellIds)
void classify (const polyMesh &mesh, const bitSet &selection)
void clearOut ()
void clear ()
void reduce ()
void sort ()
void incrCellIds (const label off)
void decrCellIds (const label off)
InfoProxy< ensightCells > info () const noexcept
label uniqueMeshPoints (const polyMesh &mesh, labelList &uniqueMeshPointLabels, bool parallel) const
virtual void writeDict (Ostream &os, const bool full=false) const
virtual void write (ensightGeoFile &os, const polyMesh &mesh, bool parallel) const
label size () const noexcept
Public Member Functions inherited from ensightPart
TypeNameNoDebug ("ensightPart")
ensightPart ()
ensightPart (const string &description)
virtual ~ensightPart ()=default
label index () const noexcept
label & index () noexcept
label identifier () const noexcept
label & identifier () noexcept
bool empty () const noexcept
label size () const noexcept
const string & name () const noexcept
void rename (const string &value)
void rename (string &&value)
label operator[] (const label i) const
Static Public Member Functions
static const char * key (const elemType etype) noexcept
Static Public Attributes
static constexpr int nTypes = 5
static const char * elemNames [nTypes]
Additional Inherited Members
Protected Member Functions inherited from ensightPart
const labelList & addressing () const noexcept
labelList & addressing () noexcept
void clear ()
void incrAddressing (const label off)
void decrAddressing (const label off)
Detailed Description
Sorting/classification of cells (3D) into corresponding ensight element types.
Definition at line 49 of file ensightCells.H.
Member Enumeration Documentation
elemType
enum elemType
Enumerator
TETRA4
"tetra4"
PYRAMID5
"pyramid5"
PENTA6
"penta6"
HEXA8
"hexa8"
NFACED
"nfaced"
Definition at line 59 of file ensightCells.H.
Constructor & Destructor Documentation
ensightCells() [1/2]
ensightCells ()
Definition at line 72 of file ensightCells.C.
ensightCells() [2/2]
ensightCells (const string & description) explicit
Definition at line 81 of file ensightCells.C.
References ensightPart::rename().
~ensightCells()
virtual ~ensightCells () virtual default
Member Function Documentation
key()
const char * key (const elemType etype) inline static noexcept
Definition at line 42 of file ensightCellsI.H.
Referenced by ensightCells::writeDict().
TypeName()
TypeName ("ensightCells")
manifold()
bool manifold () const inline noexcept
Definition at line 36 of file ensightCellsI.H.
size() [1/2]
Foam::label size (const elemType etype) const inline
Definition at line 60 of file ensightCellsI.H.
Referenced by Foam::ensightOutput::writeField().
range()
Foam::labelRange range (const elemType etype) const inline
Definition at line 66 of file ensightCellsI.H.
totalSize()
Foam::label totalSize () const noexcept
Definition at line 104 of file ensightCells.C.
References n.
Referenced by ensightCells::total().
total() [1/2]
label total () const inline noexcept
Definition at line 182 of file ensightCells.H.
References ensightCells::totalSize().
Referenced by Foam::ensightOutput::writeField().
total() [2/2]
Foam::label total (const elemType etype) const inline
Definition at line 54 of file ensightCellsI.H.
totals()
const Foam::FixedList< Foam::label, 5 > & totals () const inline
Definition at line 48 of file ensightCellsI.H.
sizes()
Foam::FixedList< Foam::label, 5 > sizes () const
Definition at line 91 of file ensightCells.C.
cellIds() [1/2]
const Foam::labelList & cellIds () const inline
Definition at line 72 of file ensightCellsI.H.
Referenced by ensightCells::meshPointMap(), and Foam::ensightOutput::writeField().
cellIds() [2/2]
const Foam::labelUList cellIds (const elemType etype) const inline
Definition at line 79 of file ensightCellsI.H.
References range.
meshPointMap()
Foam::Map< Foam::label > meshPointMap (const polyMesh & mesh) const
const cellList& meshCells = mesh.cells();
Definition at line 31 of file ensightCellsAddr.C.
References ensightCells::cellIds(), mesh, MeshObject< polyMesh, UpdateableMeshObject, manifoldCellsMeshObject >::New(), nPoints, and ensightCells::size().
classify() [1/3]
void classify (const polyMesh & mesh)
Definition at line 235 of file ensightCells.C.
References mesh, and primitiveMesh::nCells().
Referenced by ensightMesh::correct().
classify() [2/3]
void classify (const polyMesh & mesh, const labelUList & cellIds)
Definition at line 242 of file ensightCells.C.
References mesh.
classify() [3/3]
void classify (const polyMesh & mesh, const bitSet & selection)
Definition at line 252 of file ensightCells.C.
References mesh.
clearOut()
void clearOut ()
Definition at line 127 of file ensightCells.C.
clear()
void clear ()
Definition at line 115 of file ensightCells.C.
References ensightPart::clear(), and Foam::Zero.
Referenced by ensightMesh::correct().
reduce()
void reduce ()
Definition at line 131 of file ensightCells.C.
References Foam::reduce().
Referenced by ensightMesh::correct().
sort()
void sort ()
Definition at line 141 of file ensightCells.C.
References UPtrList< T >::empty(), range, and Foam::sort().
incrCellIds()
void incrCellIds (const label off) inline
Definition at line 85 of file ensightCellsI.H.
decrCellIds()
void decrCellIds (const label off) inline
Definition at line 91 of file ensightCellsI.H.
info()
InfoProxy< ensightCells > info () const inline noexcept
Definition at line 252 of file ensightCells.H.
Referenced by ensightMesh::correct().
uniqueMeshPoints()
Foam::label uniqueMeshPoints (const polyMesh & mesh, labelList & uniqueMeshPointLabels, bool parallel) const
Definition at line 220 of file ensightCellsAddr.C.
References mesh, and List< label >::null().
Referenced by Foam::ensightOutput::writePointField().
writeDict()
void writeDict (Ostream & os, const bool full = false) const virtual
Reimplemented from ensightPart.
Definition at line 262 of file ensightCells.C.
References Ostream::beginBlock(), Ostream::endBlock(), Foam::endEntry(), ensightCells::key(), Foam::name(), ensightCells::nTypes, os(), Foam::type(), Ostream::writeEntry(), and Ostream::writeKeyword().
write()
void write (ensightGeoFile & os, const polyMesh & mesh, bool parallel) const virtual
< Collective write?
Definition at line 259 of file ensightCellsIO.C.
References ensightPart::index(), mesh, ensightPart::name(), ensightCells::NFACED, nPoints, ensightCells::nTypes, os(), UPstream::parRun(), polyMesh::points(), and Foam::ensightOutput::Detail::writeCoordinates().
size() [2/2]
label size () const inline noexcept
Definition at line 150 of file ensightPart.H.
Referenced by ensightCells::meshPointMap().
Member Data Documentation
nTypes
constexpr int nTypes = 5 static constexpr
Definition at line 69 of file ensightCells.H.
Referenced by Foam::operator<<(), ensightCells::write(), and ensightCells::writeDict().
elemNames
const char * elemNames static
Initial value:
=
{
    "tetra4", "pyramid5", "penta6", "hexa8", "nfaced"
}
Definition at line 35 of file ensightCells.H.
Referenced by Foam::operator<<().
The documentation for this class was generated from the following files:
src/fileFormats/ensight/part/cells/ensightCells.H
src/fileFormats/ensight/part/cells/ensightCells.C
src/fileFormats/ensight/part/cells/ensightCellsAddr.C
src/fileFormats/ensight/part/cells/ensightCellsI.H
src/fileFormats/ensight/part/cells/ensightCellsIO.C