OpenFOAM: vectorTensorTransform Class Reference
vectorTensorTransform Class Reference
Vector-tensor class used to perform translations and rotations in 3D space.
#include <vectorTensorTransform.H>
Public Member Functions
vectorTensorTransform (const vectorTensorTransform &)=default
vectorTensorTransform & operator= (const vectorTensorTransform &)=default
vectorTensorTransform ()
vectorTensorTransform (const vector &t, const tensor &R, bool hasR=true)
vectorTensorTransform (const vector &t)
vectorTensorTransform (const tensor &R)
vectorTensorTransform (Istream &)
const vector & t () const
const tensor & R () const
bool hasR () const
vector & t ()
tensor & R ()
vector transformPosition (const vector &v) const
pointField transformPosition (const pointField &pts) const
vector invTransformPosition (const vector &v) const
pointField invTransformPosition (const pointField &pts) const
template<class Type >
tmp< Field< Type > > transform (const Field< Type > &) const
void operator&= (const vectorTensorTransform &)
void operator= (const vector &)
void operator+= (const vector &)
void operator-= (const vector &)
void operator= (const tensor &)
void operator&= (const tensor &)
template<>
Foam::tmp< Foam::Field< bool > > transform (const Field< bool > &fld) const
template<>
Foam::tmp< Foam::Field< Foam::label > > transform (const Field< label > &fld) const
template<>
Foam::tmp< Foam::Field< Foam::scalar > > transform (const Field< scalar > &fld) const
template<>
tmp< Field< bool > > transform (const Field< bool > &) const
template<>
tmp< Field< label > > transform (const Field< label > &) const
template<>
tmp< Field< scalar > > transform (const Field< scalar > &) const
template<class Type >
Foam::tmp< Foam::Field< Type > > transform (const Field< Type > &fld) const
Static Public Attributes
static const char *const typeName
static const vectorTensorTransform zero
static const vectorTensorTransform I
Friends
Istream & operator>> (Istream &is, vectorTensorTransform &)
Ostream & operator<< (Ostream &os, const vectorTensorTransform &)
Detailed Description
Vector-tensor class used to perform translations and rotations in 3D space.
Source files
vectorTensorTransform.H
vectorTensorTransformI.H
vectorTensorTransform.C
vectorTensorTransformTemplates.C
Definition at line 59 of file vectorTensorTransform.H.
Constructor & Destructor Documentation
vectorTensorTransform() [1/6]
vectorTensorTransform (const vectorTensorTransform &) default
vectorTensorTransform() [2/6]
vectorTensorTransform () inline
Definition at line 23 of file vectorTensorTransformI.H.
vectorTensorTransform() [3/6]
vectorTensorTransform (const vector & t, const tensor & R, bool hasR = true) inline
Definition at line 31 of file vectorTensorTransformI.H.
vectorTensorTransform() [4/6]
vectorTensorTransform (const vector & t) inline explicit
Definition at line 44 of file vectorTensorTransformI.H.
vectorTensorTransform() [5/6]
vectorTensorTransform (const tensor & R) inline explicit
Definition at line 52 of file vectorTensorTransformI.H.
vectorTensorTransform() [6/6]
vectorTensorTransform (Istream & is) explicit
Definition at line 48 of file vectorTensorTransform.C.
Member Function Documentation
operator=() [1/3]
vectorTensorTransform & operator= (const vectorTensorTransform &) default
t() [1/2]
const Foam::vector & t () const inline
Definition at line 62 of file vectorTensorTransformI.H.
R() [1/2]
const Foam::tensor & R () const inline
Definition at line 68 of file vectorTensorTransformI.H.
Referenced by vectorTensorTransform::transform().
hasR()
bool hasR () const inline
Definition at line 74 of file vectorTensorTransformI.H.
t() [2/2]
Foam::vector & t () inline
Definition at line 80 of file vectorTensorTransformI.H.
R() [2/2]
Foam::tensor & R () inline
Definition at line 86 of file vectorTensorTransformI.H.
transformPosition() [1/2]
Foam::vector transformPosition (const vector & v) const inline
Definition at line 97 of file vectorTensorTransformI.H.
References R.
transformPosition() [2/2]
Foam::pointField transformPosition (const pointField & pts) const inline
Definition at line 113 of file vectorTensorTransformI.H.
References pts, and R.
invTransformPosition() [1/2]
Foam::vector invTransformPosition (const vector & v) const inline
Definition at line 132 of file vectorTensorTransformI.H.
References R, and T.
invTransformPosition() [2/2]
Foam::pointField invTransformPosition (const pointField & pts) const inline
Definition at line 148 of file vectorTensorTransformI.H.
References pts, and R.
transform() [1/8]
template<class Type > tmp< Field< Type > > transform (const Field< Type > &) const
operator&=() [1/2]
void operator&= (const vectorTensorTransform & tr) inline
Definition at line 169 of file vectorTensorTransformI.H.
References Foam::tr().
operator=() [2/3]
void operator= (const vector & t) inline
Definition at line 183 of file vectorTensorTransformI.H.
operator+=()
void operator+= (const vector & t) inline
Definition at line 189 of file vectorTensorTransformI.H.
operator-=()
void operator-= (const vector & t) inline
Definition at line 195 of file vectorTensorTransformI.H.
operator=() [3/3]
void operator= (const tensor & R) inline
Definition at line 201 of file vectorTensorTransformI.H.
References R.
operator&=() [2/2]
void operator&= (const tensor & R) inline
Definition at line 209 of file vectorTensorTransformI.H.
References R.
transform() [2/8]
template<> Foam::tmp< Foam::Field< bool > > transform (const Field< bool > & fld) const
Definition at line 67 of file vectorTensorTransform.C.
References fld().
transform() [3/8]
template<> Foam::tmp< Foam::Field< Foam::label > > transform (const Field< label > & fld) const
Definition at line 75 of file vectorTensorTransform.C.
References fld().
transform() [4/8]
template<> Foam::tmp< Foam::Field< Foam::scalar > > transform (const Field< scalar > & fld) const
Definition at line 83 of file vectorTensorTransform.C.
References fld().
transform() [5/8]
template<> tmp< Field< bool > > transform (const Field< bool > &) const
transform() [6/8]
template<> tmp< Field< label > > transform (const Field< label > &) const
transform() [7/8]
template<> tmp< Field< scalar > > transform (const Field< scalar > &) const
transform() [8/8]
template<class Type > Foam::tmp< Foam::Field< Type > > transform (const Field< Type > & fld) const
Definition at line 24 of file vectorTensorTransformTemplates.C.
References fld(), and vectorTensorTransform::R().
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & is, vectorTensorTransform &) friend
operator<<
Ostream & operator<< (Ostream & os, const vectorTensorTransform &) friend
Member Data Documentation
typeName
const char *const typeName static
Initial value:
=
    "vectorTensorTransform"
Definition at line 79 of file vectorTensorTransform.H.
zero
const Foam::vectorTensorTransform zero static
Definition at line 81 of file vectorTensorTransform.H.
I
const Foam::vectorTensorTransform I static
Definition at line 83 of file vectorTensorTransform.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/globalIndexAndTransform/vectorTensorTransform/vectorTensorTransform.H
src/OpenFOAM/primitives/globalIndexAndTransform/vectorTensorTransform/vectorTensorTransform.C
src/OpenFOAM/primitives/globalIndexAndTransform/vectorTensorTransform/vectorTensorTransformI.H
src/OpenFOAM/primitives/globalIndexAndTransform/vectorTensorTransform/vectorTensorTransformTemplates.C