OpenFOAM: cyclicACMIPolyPatch Class Reference
cyclicACMIPolyPatch Class Reference
Cyclic patch for Arbitrarily Coupled Mesh Interface (ACMI).
#include <cyclicACMIPolyPatch.H>
Public Member Functions
TypeName ("cyclicACMI")
cyclicACMIPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform=UNKNOWN, const word &defaultAMIMethod=faceAreaWeightAMI::typeName)
cyclicACMIPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType, const word &defaultAMIMethod=faceAreaWeightAMI::typeName)
cyclicACMIPolyPatch (const cyclicACMIPolyPatch &, const polyBoundaryMesh &)
cyclicACMIPolyPatch (const cyclicACMIPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart, const word &nbrPatchName, const word &nonOverlapPatchName)
cyclicACMIPolyPatch (const cyclicACMIPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
virtual ~cyclicACMIPolyPatch ()=default
virtual void newInternalProcFaces (label &, label &) const
virtual refPtr< labelListList > mapCollocatedFaces () const
virtual const cyclicACMIPolyPatch & neighbPatch () const
const word & nonOverlapPatchName () const
virtual label nonOverlapPatchID () const
const polyPatch & nonOverlapPatch () const
polyPatch & nonOverlapPatch ()
const scalarField & mask () const
virtual const scalarField & srcMask () const
virtual const scalarField & tgtMask () const
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
virtual void write (Ostream &) const
virtual bool updateAreas () const
bool upToDate (const regIOobject &) const
void setUpToDate (regIOobject &) const
Public Member Functions inherited from cyclicAMIPolyPatch
TypeName ("cyclicAMI")
cyclicAMIPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform=UNKNOWN, const word &defaultAMIMethod=faceAreaWeightAMI::typeName)
cyclicAMIPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType, const word &defaultAMIMethod=faceAreaWeightAMI::typeName)
cyclicAMIPolyPatch (const cyclicAMIPolyPatch &, const polyBoundaryMesh &)
cyclicAMIPolyPatch (const cyclicAMIPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart, const word &nbrPatchName)
cyclicAMIPolyPatch (const cyclicAMIPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
virtual ~cyclicAMIPolyPatch ()=default
virtual const labelUList & nbrCells () const
virtual label neighbPolyPatchID () const
virtual bool masterImplicit () const
bool canResetAMI () const
bool createAMIFaces () const
bool updatingAMI () const
virtual bool changeTopology () const
virtual bool setTopology (polyTopoChange &topoChange)
virtual bool coupled () const
const word & neighbPatchName () const
virtual label neighbPatchID () const
scalar fraction () const
virtual bool owner () const
label periodicPatchID () const
const AMIPatchToPatchInterpolation & AMI () const
const scalarListList & weights () const
const scalarField & weightsSum () const
bool applyLowWeightCorrection () const
vectorField & faceAreas0 () const
vectorField & faceCentres0 () const
const vector & rotationAxis () const
const point & rotationCentre () const
const vector & separationVector () const
virtual void transformPosition (pointField &) const
virtual void transformPosition (point &l, const label facei) const
virtual void reverseTransformPosition (point &l, const label facei) const
virtual void reverseTransformDirection (vector &d, const label facei) const
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >()) const
template<class Type >
tmp< Field< Type > > interpolate (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues=UList< Type >()) const
template<class Type >
tmp< Field< Type > > interpolateUntransformed (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
void interpolate (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >()) const
virtual void calcGeometry (const primitivePatch &referPatch, const pointField &thisCtrs, const vectorField &thisAreas, const pointField &thisCc, const pointField &nbrCtrs, const vectorField &nbrAreas, const pointField &nbrCc)
label pointFace (const label facei, const vector &n, point &p) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateUntransformed (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues) const
Public Member Functions inherited from coupledPolyPatch
TypeName ("coupled")
coupledPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform)
coupledPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
coupledPolyPatch (const coupledPolyPatch &, const polyBoundaryMesh &bm)
coupledPolyPatch (const coupledPolyPatch &, const labelList &faceCells)
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
virtual ~coupledPolyPatch ()
virtual bool neighbour () const
virtual transformType transform () const
virtual transformType & transform ()
virtual bool separated () const
virtual const vectorField & separation () const
virtual bool parallel () const
virtual const tensorField & forwardT () const
virtual const tensorField & reverseT () const
virtual const boolList & collocated () const
scalar matchTolerance () const
Public Member Functions inherited from polyPatch
TypeName ("patch")
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &physicalType, const wordList &inGroups)
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
polyPatch (const polyPatch &, const polyBoundaryMesh &)
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
polyPatch (const polyPatch &p)
polyPatch (const polyPatch &p, const labelList &faceCells)
virtual autoPtr< polyPatch > clone (const labelList &faceCells) const
virtual ~polyPatch ()
virtual word neighbRegionID () const
label offset () const noexcept
label start () const noexcept
labelRange range () const
const polyBoundaryMesh & boundaryMesh () const noexcept
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
template<class T >
const List< T >::subList patchSlice (const UList< T > &values) const
template<class T >
const List< T >::subList boundarySlice (const List< T > &values) const
template<class T >
const Field< T >::subField patchSlice (const Field< T > &values) const
const vectorField::subField faceCentres () const
const vectorField::subField faceAreas () const
tmp< vectorField > faceCellCentres () const
tmp< scalarField > areaFraction () const
const labelUList & faceCells () const
const labelList & meshEdges () const
virtual void clearAddressing ()
label whichFace (const label facei) const noexcept
void operator= (const polyPatch &)
Public Member Functions inherited from patchIdentifier
patchIdentifier (const patchIdentifier &)=default
patchIdentifier & operator= (const patchIdentifier &)=default
virtual ~patchIdentifier ()=default
patchIdentifier ()
patchIdentifier (const word &name, const label index)
patchIdentifier (const word &name, const label index, const word &physicalType, const wordList &inGroups=wordList())
patchIdentifier (const word &name, const dictionary &dict, const label index)
patchIdentifier (const patchIdentifier &ident, const label index)
const word & name () const noexcept
word & name () noexcept
label index () const noexcept
label & index () noexcept
const word & physicalType () const noexcept
word & physicalType () noexcept
const wordList & inGroups () const noexcept
wordList & inGroups () noexcept
bool inGroup (const word &name) const
void write (Ostream &os) const
Public Member Functions inherited from PrimitivePatch< FaceList, PointField >
PrimitivePatch (const FaceList &faces, const PointField &points)
PrimitivePatch (FaceList &&faces, const PointField &points)
PrimitivePatch (FaceList &faces, PointField &points, const bool reuse)
PrimitivePatch (const PrimitivePatch< FaceList, PointField > &pp)
virtual ~PrimitivePatch ()
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
const Field< point_type > & points () const noexcept
label nFaces () const noexcept
label nPoints () const
label nEdges () const
const edgeList & edges () const
const edgeList::subList internalEdges () const
const edgeList::subList boundaryEdges () const
label nInternalEdges () const
label nBoundaryEdges () const
bool isInternalEdge (const label edgei) const
const labelList & boundaryPoints () const
const labelListList & faceFaces () const
const labelListList & edgeFaces () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointFaces () const
const List< face_type > & localFaces () const
labelList boundaryFaces () const
labelList uniqBoundaryFaces () const
const labelList & meshPoints () const
const Map< label > & meshPointMap () const
const Field< point_type > & localPoints () const
const labelList & localPointOrder () const
label whichPoint (const label gp) const
edge meshEdge (const label edgei) const
edge meshEdge (const edge &e) const
label findEdge (const edge &e) const
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
label meshEdge (const label edgei, const edgeList &allEdges, const labelListList &pointEdges) const
labelList meshEdges (const labelUList &edgeLabels, const edgeList &allEdges, const labelListList &pointEdges) const
const Field< point_type > & faceCentres () const
const Field< point_type > & faceAreas () const
const Field< scalar > & magFaceAreas () const
const Field< point_type > & faceNormals () const
const Field< point_type > & pointNormals () const
Pair< point_type > box () const
scalar sphere (const label facei) const
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
bool hasBoundaryPoints () const
bool hasEdges () const
bool hasFaceFaces () const
bool hasEdgeFaces () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointFaces () const
bool hasMeshPoints () const
bool hasMeshPointMap () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point_type > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
const labelListList & edgeLoops () const
surfaceTopo surfaceType (labelHashSet *badEdgesPtr=nullptr) const
bool checkTopology (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
bool checkPointManifold (const bool report=false, labelHashSet *pointSetPtr=nullptr) const
void operator= (const PrimitivePatch< FaceList, PointField > &rhs)
void operator= (PrimitivePatch< FaceList, PointField > &&rhs)
label whichEdge (const edge &e) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< typename Foam::PrimitivePatch< FaceList, PointField >::point_type > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Public Member Functions inherited from PrimitivePatchBase
ClassName ("PrimitivePatch")
PrimitivePatchBase ()=default
Static Public Member Functions
static scalar tolerance ()
Static Public Member Functions inherited from coupledPolyPatch
static scalarField calcFaceTol (const UList< face > &faces, const pointField &points, const pointField &faceCentres)
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
static bool constraintType (const word &patchType)
static wordList constraintTypes ()
Static Public Member Functions inherited from patchIdentifier
static word defaultName (const label n=-1)
Protected Member Functions
void reportCoverage (const word &name, const scalarField &weightSum) const
virtual void resetAMI (const UList< point > &points) const
virtual void resetAMI () const
virtual void scalePatchFaceAreas ()
virtual void scalePatchFaceAreas (const cyclicACMIPolyPatch &acmipp, const scalarField &mask, const vectorList &faceArea, const vectorList &noFaceArea)
virtual void initGeometry (PstreamBuffers &)
virtual void calcGeometry (PstreamBuffers &)
virtual void initMovePoints (PstreamBuffers &pBufs, const pointField &)
virtual void movePoints (PstreamBuffers &pBufs, const pointField &)
virtual void initUpdateMesh (PstreamBuffers &)
virtual void updateMesh (PstreamBuffers &)
virtual void clearGeom ()
Protected Member Functions inherited from cyclicAMIPolyPatch
virtual bool removeAMIFaces (polyTopoChange &topoChange)
virtual bool addAMIFaces (polyTopoChange &topoChange)
virtual void setAMIFaces ()
virtual void restoreScaledGeometry ()
const autoPtr< searchableSurface > & surfPtr () const
autoPtr< coordSystem::cylindrical > cylindricalCS () const
virtual void calcTransforms ()
Protected Member Functions inherited from coupledPolyPatch
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr, const scalarField &smallDist, const scalar absTol, const transformType=UNKNOWN) const
Protected Member Functions inherited from polyPatch
virtual void movePoints (const Field< point_type > &)
Additional Inherited Members
Public Types inherited from coupledPolyPatch
enum transformType {
UNKNOWN , ROTATIONAL , TRANSLATIONAL , COINCIDENTFULLMATCH ,
NOORDERING
}
Public Types inherited from PrimitivePatch< FaceList, PointField >
enum surfaceTopo { MANIFOLD , OPEN , ILLEGAL }
typedef std::remove_reference< FaceList >::type::value_type face_type
typedef std::remove_reference< PointField >::type::value_type point_type
typedef FaceList FaceListType
typedef PointField PointFieldType
typedef face_type FaceType
Static Public Attributes inherited from cyclicAMIPolyPatch
static const scalar tolerance_ = 1e-10
Static Public Attributes inherited from coupledPolyPatch
static const Enum< transformType > transformTypeNames
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Static Protected Member Functions inherited from coupledPolyPatch
static void writeOBJ (Ostream &os, const point &pt)
static void writeOBJ (Ostream &, const pointField &, const labelList &)
static void writeOBJ (const fileName &, const UList< face > &, const pointField &)
static void writeOBJ (Ostream &os, const point &p0, const point &p1, label &vertI)
static pointField getAnchorPoints (const UList< face > &, const pointField &, const transformType)
static label getRotation (const pointField &points, const face &f, const point &anchor, const scalar tol)
Protected Attributes inherited from cyclicAMIPolyPatch
word nbrPatchName_
const coupleGroupIdentifier coupleGroup_
label nbrPatchID_
const scalar fraction_
vector rotationAxis_
point rotationCentre_
bool rotationAngleDefined_
scalar rotationAngle_
vector separationVector_
word periodicPatchName_
label periodicPatchID_
autoPtr< AMIPatchToPatchInterpolation > AMIPtr_
const dictionary surfDict_
autoPtr< searchableSurface > surfPtr_
bool createAMIFaces_
bool moveFaceCentres_
bool updatingAMI_
labelListList srcFaceIDs_
labelListList tgtFaceIDs_
vectorField faceAreas0_
vectorField faceCentres0_
Detailed Description
Cyclic patch for Arbitrarily Coupled Mesh Interface (ACMI).
Mixes cyclicAMI behaviour with non-coupled patch behaviour using the overlap area fraction. The non-coupled patch is specified through the nonOverlapPatch keyword.
Usage
Example of the patch specification:
type cyclicACMI; neighbourPatch ACMI2_couple; // cyclicAMI neighbour patch nonOverlapPatch ACMI1_blockage; // patch for uncoupled faces
Optional time-dependent scaling (PatchFunction1) scale table ((0.00 1.0) (0.02 1.0) (0.0201 0.0));
See also
cyclicAMIPolyPatch.C
Source files
cyclicACMIPolyPatch.H
cyclicACMIPolyPatch.C
Definition at line 74 of file cyclicACMIPolyPatch.H.
Constructor & Destructor Documentation
cyclicACMIPolyPatch() [1/5]
cyclicACMIPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType, const transformType transform = UNKNOWN, const word & defaultAMIMethod = faceAreaWeightAMI::typeName)
Definition at line 535 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::AMIPtr_.
cyclicACMIPolyPatch() [2/5]
cyclicACMIPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType, const word & defaultAMIMethod = faceAreaWeightAMI::typeName)
Definition at line 584 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::AMIPtr_, dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and patchIdentifier::name().
cyclicACMIPolyPatch() [3/5]
cyclicACMIPolyPatch (const cyclicACMIPolyPatch & pp, const polyBoundaryMesh & bm)
Definition at line 630 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::AMIPtr_.
cyclicACMIPolyPatch() [4/5]
cyclicACMIPolyPatch (const cyclicACMIPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart, const word & nbrPatchName, const word & nonOverlapPatchName)
Definition at line 664 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::AMIPtr_, Foam::exit(), Foam::FatalError, FatalErrorInFunction, and patchIdentifier::name().
cyclicACMIPolyPatch() [5/5]
cyclicACMIPolyPatch (const cyclicACMIPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Definition at line 711 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::AMIPtr_.
~cyclicACMIPolyPatch()
virtual ~cyclicACMIPolyPatch () virtual default
Member Function Documentation
reportCoverage()
void reportCoverage (const word & name, const scalarField & weightSum) const protected
Definition at line 151 of file cyclicACMIPolyPatch.C.
References Foam::endl(), Foam::Info, Foam::name(), Foam::reduce(), Foam::returnReduce(), UPtrList< T >::size(), and Foam::sum().
resetAMI() [1/2]
void resetAMI (const UList< point > & points) const protected virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 281 of file cyclicACMIPolyPatch.C.
References Foam::abort(), Foam::clamp(), DebugPout, Foam::endl(), Foam::FatalError, FatalErrorInFunction, primitiveMesh::hasFaceAreas(), mesh, boundaryMesh::mesh(), patchIdentifier::name(), Foam::name(), points, Foam::Pout, cyclicAMIPolyPatch::resetAMI(), UPtrList< T >::size(), AMIInterpolation::srcWeightsSum(), and AMIInterpolation::tgtWeightsSum().
resetAMI() [2/2]
void resetAMI () const protected virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 275 of file cyclicACMIPolyPatch.C.
References mesh, and points.
scalePatchFaceAreas() [1/2]
void scalePatchFaceAreas () protected virtual
Definition at line 346 of file cyclicACMIPolyPatch.C.
References primitiveMesh::cellVolumes(), Foam::endl(), polyPatch::faceAreas(), PrimitivePatch< FaceList, PointField >::faceAreas(), polyPatch::faceCells(), Foam::Info, mesh, boundaryMesh::mesh(), patchIdentifier::name(), Foam::nl, and Foam::sum().
scalePatchFaceAreas() [2/2]
void scalePatchFaceAreas (const cyclicACMIPolyPatch & acmipp, const scalarField & mask, const vectorList & faceArea, const vectorList & noFaceArea) protected virtual
Definition at line 180 of file cyclicACMIPolyPatch.C.
References primitiveMesh::cellCentres(), primitiveMesh::cells(), primitiveMesh::cellVolumes(), DebugPout, Foam::endl(), polyPatch::faceAreas(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), forAll, Foam::max(), mesh, boundaryMesh::mesh(), Foam::min(), patchIdentifier::name(), Foam::nl, UPtrList< T >::size(), UList< T >::size(), Foam::sum(), Foam::uniqueSort(), primitiveMeshTools::updateCellCentresAndVols(), and WarningInFunction.
initGeometry()
void initGeometry (PstreamBuffers & pBufs) protected virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 418 of file cyclicACMIPolyPatch.C.
References DebugPout, Foam::endl(), cyclicAMIPolyPatch::initGeometry(), and Foam::name().
calcGeometry()
void calcGeometry (PstreamBuffers & pBufs) protected virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 436 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::calcGeometry(), DebugPout, Foam::endl(), and Foam::name().
initMovePoints()
void initMovePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 444 of file cyclicACMIPolyPatch.C.
References DebugPout, Foam::endl(), cyclicAMIPolyPatch::initMovePoints(), Foam::name(), and p.
movePoints()
void movePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 464 of file cyclicACMIPolyPatch.C.
References DebugPout, Foam::endl(), cyclicAMIPolyPatch::movePoints(), Foam::name(), and p.
initUpdateMesh()
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 477 of file cyclicACMIPolyPatch.C.
References DebugPout, Foam::endl(), cyclicAMIPolyPatch::initUpdateMesh(), and Foam::name().
updateMesh()
void updateMesh (PstreamBuffers & pBufs) protected virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 485 of file cyclicACMIPolyPatch.C.
References DebugPout, Foam::endl(), Foam::name(), and cyclicAMIPolyPatch::updateMesh().
clearGeom()
void clearGeom () protected virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 493 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::clearGeom(), DebugPout, Foam::endl(), and Foam::name().
TypeName()
TypeName ("cyclicACMI")
clone() [1/3]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm) const inline virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 240 of file cyclicACMIPolyPatch.H.
clone() [2/3]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 247 of file cyclicACMIPolyPatch.H.
References patchIdentifier::index(), and cyclicAMIPolyPatch::neighbPatchName().
clone() [3/3]
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 272 of file cyclicACMIPolyPatch.H.
References patchIdentifier::index().
newInternalProcFaces()
void newInternalProcFaces (label & newFaces, label & newProcFaces) const virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 747 of file cyclicACMIPolyPatch.C.
References forAll.
mapCollocatedFaces()
Foam::refPtr< Foam::labelListList > mapCollocatedFaces () const virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 784 of file cyclicACMIPolyPatch.C.
References forAll, PtrList< T >::setSize(), and UPtrList< T >::size().
neighbPatch()
const Foam::cyclicACMIPolyPatch & neighbPatch () const virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 807 of file cyclicACMIPolyPatch.C.
References Foam::endl(), Foam::name(), pp(), and WarningInFunction.
Referenced by cyclicACMIPolyPatch::updateAreas().
nonOverlapPatchName()
const Foam::word & nonOverlapPatchName () const inline
Definition at line 23 of file cyclicACMIPolyPatchI.H.
nonOverlapPatchID()
Foam::label nonOverlapPatchID () const virtual
Definition at line 825 of file cyclicACMIPolyPatch.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), Foam::name(), Foam::nl, UPtrList< T >::size(), and Foam::type().
Referenced by cyclicACMIFvPatch::nonOverlapPatchID().
nonOverlapPatch() [1/2]
const Foam::polyPatch & nonOverlapPatch () const inline
Definition at line 29 of file cyclicACMIPolyPatchI.H.
Referenced by cyclicACMIPolyPatch::updateAreas().
nonOverlapPatch() [2/2]
Foam::polyPatch & nonOverlapPatch () inline
Definition at line 38 of file cyclicACMIPolyPatchI.H.
mask()
const Foam::scalarField & mask () const inline
Definition at line 47 of file cyclicACMIPolyPatchI.H.
srcMask()
const Foam::scalarField & srcMask () const virtual
Definition at line 501 of file cyclicACMIPolyPatch.C.
tgtMask()
const Foam::scalarField & tgtMask () const virtual
Definition at line 517 of file cyclicACMIPolyPatch.C.
tolerance()
Foam::scalar tolerance () inline static
Definition at line 58 of file cyclicACMIPolyPatchI.H.
Referenced by cyclicACMIFvPatch::makeWeights().
initOrder()
void initOrder (PstreamBuffers & pBufs, const primitivePatch & pp) const virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 891 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::initOrder(), and pp().
order()
bool order (PstreamBuffers & pBufs, const primitivePatch & pp, labelList & faceMap, labelList & rotation) const virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 901 of file cyclicACMIPolyPatch.C.
References Foam::faceMap(), cyclicAMIPolyPatch::order(), and pp().
write()
void write (Ostream & os) const virtual
Reimplemented from cyclicAMIPolyPatch.
Definition at line 913 of file cyclicACMIPolyPatch.C.
References os(), cyclicAMIPolyPatch::write(), and Ostream::writeEntry().
updateAreas()
bool updateAreas () const virtual
Definition at line 40 of file cyclicACMIPolyPatch.C.
References PtrList< T >::clone(), cyclicAMIPolyPatch::createAMIFaces_, Foam::endl(), regIOobject::eventNo(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::gAverage(), Foam::max(), mesh, boundaryMesh::mesh(), Foam::min(), patchIdentifier::name(), cyclicACMIPolyPatch::neighbPatch(), cyclicACMIPolyPatch::nonOverlapPatch(), cyclicAMIPolyPatch::owner(), Foam::Pout, regIOobject::setUpToDate(), cyclicAMIPolyPatch::tolerance_, and WarningInFunction.
upToDate()
bool upToDate (const regIOobject & io) const
Definition at line 136 of file cyclicACMIPolyPatch.C.
References io().
setUpToDate()
void setUpToDate (regIOobject & io) const
Definition at line 145 of file cyclicACMIPolyPatch.C.
References io().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/patches/cyclicACMI/cyclicACMIPolyPatch/cyclicACMIPolyPatch.H
src/meshTools/AMIInterpolation/patches/cyclicACMI/cyclicACMIPolyPatch/cyclicACMIPolyPatch.C
src/meshTools/AMIInterpolation/patches/cyclicACMI/cyclicACMIPolyPatch/cyclicACMIPolyPatchI.H