OpenFOAM: Rosenbrock23 Class Reference
Rosenbrock23 Class Reference
Numerics » Ordinary Differential Equation (ODE) solvers
L-stable embedded Rosenbrock ODE solver of order (2)3.
#include <Rosenbrock23.H>
Public Member Functions
TypeName ("Rosenbrock23")
Rosenbrock23 (const ODESystem &ode, const dictionary &dict)
virtual ~Rosenbrock23 ()=default
virtual bool resize ()
virtual scalar solve (const scalar x0, const scalarField &y0, const scalarField &dydx0, const scalar dx, scalarField &y) const
virtual void solve (scalar &x, scalarField &y, scalar &dxTry) const
virtual void solve (scalar &x, scalarField &y, scalar &dxTry) const
virtual void solve (scalar &x, scalarField &y, stepState &step) const
virtual void solve (const scalar xStart, const scalar xEnd, scalarField &y, scalar &dxEst) const
Public Member Functions inherited from ODESolver
TypeName ("ODESolver")
declareRunTimeSelectionTable (autoPtr, ODESolver, dictionary,(const ODESystem &ode, const dictionary &dict),(ode, dict))
ODESolver (const ODESystem &ode, const dictionary &dict)
ODESolver (const ODESystem &ode, const scalarField &absTol, const scalarField &relTol)
virtual ~ODESolver ()=default
label nEqns () const
scalarField & absTol ()
scalarField & relTol ()
template<class Type >
void resizeField (UList< Type > &f) const
void resizeMatrix (scalarSquareMatrix &m) const
Public Member Functions inherited from adaptiveSolver
adaptiveSolver (const ODESystem &ode, const dictionary &dict)
virtual ~adaptiveSolver ()=default
bool resize (const label n)
void solve (const ODESystem &ode, scalar &x, scalarField &y, scalar &dxTry) const
Additional Inherited Members
Static Public Member Functions inherited from ODESolver
static autoPtr< ODESolver > New (const ODESystem &ode, const dictionary &dict)
template<class Type >
static void resizeField (UList< Type > &f, const label n)
Protected Member Functions inherited from ODESolver
scalar normalizeError (const scalarField &y0, const scalarField &y, const scalarField &err) const
ODESolver (const ODESolver &)=delete
void operator= (const ODESolver &)=delete
Protected Attributes inherited from ODESolver
const ODESystem & odes_
const label maxN_
label n_
scalarField absTol_
scalarField relTol_
label maxSteps_
Detailed Description
L-stable embedded Rosenbrock ODE solver of order (2)3.
References:
    Sandu, A., Verwer, J. G., Blom, J. G., Spee, E. J., Carmichael, G. R.,
    & Potra, F. A. (1997).
    Benchmarking stiff ODE solvers for atmospheric chemistry problems II:
    Rosenbrock solvers.
    Atmospheric environment, 31(20), 3459-3472.
Source files
Rosenbrock23.H
Rosenbrock23.C
Definition at line 60 of file Rosenbrock23.H.
Constructor & Destructor Documentation
Rosenbrock23()
Rosenbrock23 (const ODESystem & ode, const dictionary & dict)
Definition at line 60 of file Rosenbrock23.C.
~Rosenbrock23()
virtual ~Rosenbrock23 () virtual default
Member Function Documentation
TypeName()
TypeName ("Rosenbrock23")
resize()
bool resize () virtual
Implements ODESolver.
Definition at line 78 of file Rosenbrock23.C.
References ODESolver::resize(), and adaptiveSolver::resize().
solve() [1/5]
Foam::scalar solve (const scalar x0, const scalarField & y0, const scalarField & dydx0, const scalar dx, scalarField & y) const virtual
Implements adaptiveSolver.
Definition at line 101 of file Rosenbrock23.C.
References forAll, gamma, Foam::LUBacksubstitute(), Foam::LUDecompose(), y, and Foam::y0().
solve() [2/5]
void solve (scalar & x, scalarField & y, scalar & dxTry) const virtual
Reimplemented from ODESolver.
Definition at line 167 of file Rosenbrock23.C.
References adaptiveSolver::solve(), x, and y.
solve() [3/5]
void solve (scalar & x, scalarField & y, scalar & dxTry) const virtual
Reimplemented from ODESolver.
Definition at line 193 of file ODESolver.C.
solve() [4/5]
void solve (scalar & x, scalarField & y, stepState & step) const virtual
Reimplemented from ODESolver.
Definition at line 204 of file ODESolver.C.
solve() [5/5]
void solve (const scalar xStart, const scalar xEnd, scalarField & y, scalar & dxEst) const virtual
Reimplemented from ODESolver.
Definition at line 213 of file ODESolver.C.
The documentation for this class was generated from the following files:
src/ODE/ODESolvers/Rosenbrock23/Rosenbrock23.H
src/ODE/ODESolvers/Rosenbrock23/Rosenbrock23.C