OpenFOAM: velocityGroup Class Reference
velocityGroup Class Reference
This diameterModel is intended for use with a populationBalanceModel in order to simulate polydispersed bubbly or particulate flows. It can hold any number of sizeGroups from which the Sauter mean diameter is calculated. It can also be used as a diameterModel without a populationBalance and would then behave like a constantDiameter model. In this case, some arbitrary name must be entered for the populationBalance keyword.
#include <velocityGroup.H>
Public Member Functions
TypeName ("velocityGroup")
velocityGroup (const dictionary &diameterProperties, const phaseModel &phase)
virtual ~velocityGroup ()
const word & popBalName () const
const volScalarField & f () const
const dimensionedScalar & formFactor () const
const PtrList< sizeGroup > & sizeGroups () const
const tmp< fv::convectionScheme< scalar > > & mvConvection () const
const volScalarField & dmdt () const
volScalarField & dmdtRef ()
void preSolve ()
void postSolve ()
virtual bool read (const dictionary &diameterProperties)
virtual tmp< volScalarField > d () const
Public Member Functions inherited from diameterModel
TypeName ("diameterModel")
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &dict, const phaseModel &phase),(dict, phase))
diameterModel (const dictionary &dict, const phaseModel &phase)
virtual ~diameterModel ()=default
const dictionary & diameterProperties () const
const phaseModel & phase () const
virtual void correct ()
TypeName ("diameterModel")
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &dict, const phaseModel &phase),(dict, phase))
diameterModel (const dictionary &dict, const phaseModel &phase)
virtual ~diameterModel ()=default
const dictionary & diameterProperties () const
const phaseModel & phase () const
virtual void correct ()
Additional Inherited Members
Static Public Member Functions inherited from diameterModel
static autoPtr< diameterModel > New (const dictionary &diameterProperties, const phaseModel &phase)
static autoPtr< diameterModel > New (const dictionary &dict, const phaseModel &phase)
Protected Attributes inherited from diameterModel
dictionary diameterProperties_
const phaseModel & phase_
Detailed Description
This diameterModel is intended for use with a populationBalanceModel in order to simulate polydispersed bubbly or particulate flows. It can hold any number of sizeGroups from which the Sauter mean diameter is calculated. It can also be used as a diameterModel without a populationBalance and would then behave like a constantDiameter model. In this case, some arbitrary name must be entered for the populationBalance keyword.
Usage
Property Description
populationBalance Name of the corresponding populationBalance
formFactor Form factor for converting diameter into volume
sizeGroups List of sizeGroups
Example
    diameterModel   velocityGroup;
    velocityGroupCoeffs
    {
        populationBalance    bubbles;
        formFactor      0.5235987756;
        sizeGroups
        (
            f0{d  1.00e-3; value 0;}
            f1{d  1.08e-3; value 0;}
            f2{d  1.16e-3; value 0.25;}
            f3{d  1.25e-3; value 0.5;}
            f4{d  1.36e-3; value 0.25;}
            f5{d  1.46e-3; value 0;}
            ...
        );
    }
See also
Foam::diameterModels::sizeGroup Foam::diameterModels::populationBalanceModel
Source files
velocityGroup.H
velocityGroup.C
Definition at line 103 of file velocityGroup.H.
Constructor & Destructor Documentation
velocityGroup()
velocityGroup (const dictionary & diameterProperties, const phaseModel & phase)
Definition at line 139 of file velocityGroup.C.
References e, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), Foam::max(), DimensionedField< Type, GeoMesh >::mesh(), Foam::min(), Foam::nl, diameterModel::phase(), diameterModel::phase_, and DimensionedField< Type, GeoMesh >::weightedAverage().
~velocityGroup()
~velocityGroup () virtual
Definition at line 270 of file velocityGroup.C.
Member Function Documentation
TypeName()
TypeName ("velocityGroup")
popBalName()
const Foam::word & popBalName () const inline
Definition at line 24 of file velocityGroupI.H.
f()
const Foam::volScalarField & f () const inline
Definition at line 31 of file velocityGroupI.H.
formFactor()
const Foam::dimensionedScalar & formFactor () const inline
Definition at line 38 of file velocityGroupI.H.
sizeGroups()
const Foam::PtrList< Foam::diameterModels::sizeGroup > & sizeGroups () const inline
Definition at line 45 of file velocityGroupI.H.
mvConvection()
const Foam::tmp< Foam::fv::convectionScheme< Foam::scalar > > & mvConvection () const inline
Definition at line 52 of file velocityGroupI.H.
dmdt()
const Foam::volScalarField & dmdt () const inline
Definition at line 58 of file velocityGroupI.H.
dmdtRef()
Foam::volScalarField & dmdtRef () inline
Definition at line 65 of file velocityGroupI.H.
preSolve()
void preSolve ()
Definition at line 277 of file velocityGroup.C.
postSolve()
void postSolve ()
Definition at line 283 of file velocityGroup.C.
References Foam::endl(), Foam::Info, Foam::max(), Foam::min(), and phase::name().
read()
bool read (const dictionary & diameterProperties) virtual
Implements diameterModel.
Definition at line 315 of file velocityGroup.C.
References diameterModel::read().
d()
Foam::tmp< Foam::volScalarField > d () const virtual
Implements diameterModel.
Definition at line 325 of file velocityGroup.C.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/diameterModels/velocityGroup/velocityGroup.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/diameterModels/velocityGroup/velocityGroup.C
src/phaseSystemModels/reactingEuler/multiphaseSystem/diameterModels/velocityGroup/velocityGroupI.H