OpenFOAM: Arrhenius< ViscousModel > Class Template Reference
Arrhenius< ViscousModel > Class Template Reference
Arrhenius type of dependency on a given scalar field name. Most likely temperature. The expression is as follow:
#include <Arrhenius.H>
Public Member Functions
TypeName ("Arrhenius")
Arrhenius (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
virtual ~Arrhenius ()=default
virtual void correct ()
virtual bool read (const dictionary &viscosityProperties)
Detailed Description
template<class ViscousModel>
class Foam::viscosityModels::Arrhenius< ViscousModel >
Arrhenius type of dependency on a given scalar field name. Most likely temperature. The expression is as follow:
    mu = exp(-alpha_*(T - Talpha_))
Source files
Arrhenius.H
Arrhenius.C
Definition at line 55 of file Arrhenius.H.
Constructor & Destructor Documentation
Arrhenius()
template<class ViscousModel > Arrhenius (const word & name, const dictionary & viscosityProperties, const volVectorField & U, const surfaceScalarField & phi)
Definition at line 40 of file Arrhenius.C.
References Foam::dimTemperature, Foam::inv(), and Foam::name().
~Arrhenius()
template<class ViscousModel > virtual ~Arrhenius () virtual default
Member Function Documentation
TypeName()
template<class ViscousModel > TypeName ("Arrhenius< ViscousModel >")
correct()
template<class ViscousModel > virtual void correct () inline virtual
Definition at line 108 of file Arrhenius.H.
References objectRegistry::findObject().
read()
template<class ViscousModel > bool read (const dictionary & viscosityProperties) virtual
Definition at line 70 of file Arrhenius.C.
References dictionary::optionalSubDict(), and viscosityModel::read().
The documentation for this class was generated from the following files:
src/transportModels/incompressible/viscosityModels/Arrhenius/Arrhenius.H
src/transportModels/incompressible/viscosityModels/Arrhenius/Arrhenius.C