OpenFOAM: gradingDescriptor Class Reference
gradingDescriptor Class Reference
Handles the specification for grading within a section of a block.
#include <gradingDescriptor.H>
Public Member Functions
gradingDescriptor ()
gradingDescriptor (const scalar blockFraction, const scalar nDivFraction, const scalar expansionRatio)
gradingDescriptor (const scalar expansionRatio)
gradingDescriptor (Istream &is)
~gradingDescriptor ()=default
scalar blockFraction () const
scalar nDivFraction () const
scalar expansionRatio () const
void correct ()
gradingDescriptor inv () const
bool operator== (const gradingDescriptor &) const
bool operator!= (const gradingDescriptor &) const
Friends
class gradingDescriptors
Istream & operator>> (Istream &, gradingDescriptor &)
Ostream & operator<< (Ostream &, const gradingDescriptor &)
Detailed Description
Handles the specification for grading within a section of a block.
The grading specification is handled is controlled by three parameters:
blockFraction: the fraction of the block the section occupies
nDivFraction: the fraction of the divisions of the block allocated to the section
expansionRatio: the expansion ratio for the grading with the section of block defined as the ratio of end-size / start-size for the section. A negative value is trapped and treated as its inverse.
Source files
gradingDescriptor.H
gradingDescriptor.C
Definition at line 66 of file gradingDescriptor.H.
Constructor & Destructor Documentation
gradingDescriptor() [1/4]
gradingDescriptor ()
Definition at line 28 of file gradingDescriptor.C.
gradingDescriptor() [2/4]
gradingDescriptor (const scalar blockFraction, const scalar nDivFraction, const scalar expansionRatio)
Definition at line 36 of file gradingDescriptor.C.
References gradingDescriptor::correct().
gradingDescriptor() [3/4]
gradingDescriptor (const scalar expansionRatio) explicit
Definition at line 51 of file gradingDescriptor.C.
References gradingDescriptor::correct().
gradingDescriptor() [4/4]
gradingDescriptor (Istream & is) explicit
Definition at line 64 of file gradingDescriptor.C.
~gradingDescriptor()
~gradingDescriptor () default
Member Function Documentation
blockFraction()
scalar blockFraction () const inline
Definition at line 107 of file gradingDescriptor.H.
nDivFraction()
scalar nDivFraction () const inline
Definition at line 112 of file gradingDescriptor.H.
expansionRatio()
scalar expansionRatio () const inline
Definition at line 117 of file gradingDescriptor.H.
correct()
void correct ()
Definition at line 72 of file gradingDescriptor.C.
Referenced by gradingDescriptor::gradingDescriptor(), and gradingDescriptor::gradingDescriptor().
inv()
Foam::gradingDescriptor inv () const
Definition at line 81 of file gradingDescriptor.C.
operator==()
bool operator== (const gradingDescriptor & gd) const
Definition at line 94 of file gradingDescriptor.C.
References Foam::equal().
operator!=()
bool operator!= (const gradingDescriptor & gd) const
Definition at line 103 of file gradingDescriptor.C.
References Foam::operator==().
Friends And Related Symbol Documentation
gradingDescriptors
friend class gradingDescriptors friend
Definition at line 78 of file gradingDescriptor.H.
operator>>
Istream & operator>> (Istream & , gradingDescriptor &) friend
operator<<
Ostream & operator<< (Ostream & , const gradingDescriptor &) friend
The documentation for this class was generated from the following files:
src/mesh/blockMesh/gradingDescriptor/gradingDescriptor.H
src/mesh/blockMesh/gradingDescriptor/gradingDescriptor.C