OpenFOAM: mappedPatchFieldBase< Type > Class Template Reference
mappedPatchFieldBase< Type > Class Template Reference
Functionality for sampling fields using mappedPatchBase. Every call to mappedField() returns a sampled field, optionally scaled to maintain an area-weighted average.
#include <mappedPatchFieldBase.H>
Public Member Functions
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< Type > &patchField, const word &fieldName, const bool setAverage, const Type average, const word &interpolationScheme)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< Type > &patchField, const dictionary &dict)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< Type > &patchField, const dictionary &dict, const Field< Type > &fld)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< Type > &patchField)
mappedPatchFieldBase (const mappedPatchFieldBase< Type > &mapper)
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< Type > &patchField, const mappedPatchFieldBase< Type > &base)
virtual ~mappedPatchFieldBase ()=default
template<class T >
const GeometricField< T, fvPatchField, volMesh > & sampleField (const word &fieldName) const
const GeometricField< Type, fvPatchField, volMesh > & sampleField () const
virtual tmp< Field< Type > > mappedField () const
virtual tmp< Field< Type > > mappedInternalField () const
virtual tmp< scalarField > mappedWeightField () const
virtual void mappedWeightField (const word &weightFieldName, tmp< scalarField > &thisWeights, tmp< scalarField > &nbrWeights) const
virtual void write (Ostream &os) const
template<class T >
void distribute (const word &fieldName, Field< T > &newValues) const
template<class Type2 >
const Foam::GeometricField< Type2, Foam::fvPatchField, Foam::volMesh > & sampleField (const word &fieldName) const
Static Public Member Functions
static const mappedPatchBase & mapper (const fvPatch &p, const DimensionedField< Type, volMesh > &iF)
Protected Member Functions
template<class T >
void initRetrieveField (const objectRegistry &obr, const word &region, const word &patch, const labelListList &map, const word &fieldName, const Field< T > &fld) const
template<class T >
bool storeAndRetrieveField (const word &fieldName, const label myComm, const labelListList &subMap, const label constructSize, const labelListList &constructMap, const labelListList &address, const scalarListList &weights, Field< T > &fld) const
template<class T >
void initRetrieveField (const word &fieldName, const Field< T > &fld) const
template<class T >
void storeField (const objectRegistry &obr, const word &region, const word &patch, const label myComm, const labelListList &procToMap, const word &fieldName, const Field< T > &fld) const
template<class T >
bool retrieveField (const bool allowUnset, const objectRegistry &obr, const word &region, const word &patch, const label myComm, const labelListList &procToMap, const word &fieldName, Field< T > &fld) const
Protected Attributes
const mappedPatchBase & mapper_
const fvPatchField< Type > & patchField_
word fieldName_
const bool setAverage_
const Type average_
word interpolationScheme_
Detailed Description
template<class Type>
class Foam::mappedPatchFieldBase< Type >
Functionality for sampling fields using mappedPatchBase. Every call to mappedField() returns a sampled field, optionally scaled to maintain an area-weighted average.
Example usage:
{
    field               T;          // default is same as fvPatchField
    setAverage          false;
    average             1.0;        // only if setAverage=true
    interpolationScheme cellPoint;  // default is cell
}
Property Description Required Default
field name of field to be mapped no this field name
setAverage use average value no false
average average value to apply if setAverage = yes partly
interpolationScheme interpolation scheme partly cell
Source files
mappedPatchFieldBase.H
mappedPatchFieldBase.C
Definition at line 101 of file mappedPatchFieldBase.H.
Constructor & Destructor Documentation
mappedPatchFieldBase() [1/6]
template<class Type > mappedPatchFieldBase (const mappedPatchBase & mapper, const fvPatchField< Type > & patchField, const word & fieldName, const bool setAverage, const Type average, const word & interpolationScheme)
Definition at line 313 of file mappedPatchFieldBase.C.
mappedPatchFieldBase() [2/6]
template<class Type > mappedPatchFieldBase (const mappedPatchBase & mapper, const fvPatchField< Type > & patchField, const dictionary & dict)
Definition at line 333 of file mappedPatchFieldBase.C.
References dict, Foam::exit(), Foam::FatalError, FatalErrorInFunction, mappedPatchFieldBase< Type >::interpolationScheme_, mappedPatchFieldBase< Type >::mapper_, mappedPatchBase::NEARESTCELL, mappedPatchBase::NEARESTPATCHFACE, mappedPatchBase::NEARESTPATCHFACEAMI, and mappedPatchBase::sampleModeNames_.
mappedPatchFieldBase() [3/6]
template<class Type > mappedPatchFieldBase (const mappedPatchBase & mapper, const fvPatchField< Type > & patchField, const dictionary & dict, const Field< Type > & fld)
Definition at line 389 of file mappedPatchFieldBase.C.
References mappedPatchFieldBase< Type >::initRetrieveField(), mappedPatchFieldBase< Type >::mapper_, mappedPatchBase::NEARESTPATCHFACE, mappedPatchBase::NEARESTPATCHFACEAMI, and mappedPatchFieldBase< Type >::patchField_.
mappedPatchFieldBase() [4/6]
template<class Type > mappedPatchFieldBase (const mappedPatchBase & mapper, const fvPatchField< Type > & patchField)
Definition at line 427 of file mappedPatchFieldBase.C.
mappedPatchFieldBase() [5/6]
template<class Type > mappedPatchFieldBase (const mappedPatchFieldBase< Type > & mapper) explicit
Definition at line 443 of file mappedPatchFieldBase.C.
mappedPatchFieldBase() [6/6]
template<class Type > mappedPatchFieldBase (const mappedPatchBase & mapper, const fvPatchField< Type > & patchField, const mappedPatchFieldBase< Type > & base)
Definition at line 458 of file mappedPatchFieldBase.C.
~mappedPatchFieldBase()
template<class Type > virtual ~mappedPatchFieldBase () virtual default
Member Function Documentation
initRetrieveField() [1/2]
template<class Type > template<class T > void initRetrieveField (const objectRegistry & obr, const word & region, const word & patch, const labelListList & map, const word & fieldName, const Field< T > & fld) const protected
Definition at line 193 of file mappedPatchFieldBase.C.
References UPstream::nProcs().
Referenced by mappedPatchFieldBase< Type >::mappedPatchFieldBase().
storeAndRetrieveField()
template<class Type > template<class T > bool storeAndRetrieveField (const word & fieldName, const label myComm, const labelListList & subMap, const label constructSize, const labelListList & constructMap, const labelListList & address, const scalarListList & weights, Field< T > & fld) const protected
Definition at line 244 of file mappedPatchFieldBase.C.
initRetrieveField() [2/2]
template<class Type > template<class T > void initRetrieveField (const word & fieldName, const Field< T > & fld) const protected
Definition at line 969 of file mappedPatchFieldBase.C.
References fld(), and mappedPatchBase::NEARESTPATCHFACE.
storeField()
template<class Type > template<class T > void storeField (const objectRegistry & obr, const word & region, const word & patch, const label myComm, const labelListList & procToMap, const word & fieldName, const Field< T > & fld) const protected
Definition at line 46 of file mappedPatchFieldBase.C.
References Foam::endl(), Foam::flatOutput(), fld(), forAll, Foam::Pout, UPstream::procID(), UList< T >::size(), mappedPatchBase::storeField(), and mappedPatchBase::subRegistry().
retrieveField()
template<class Type > template<class T > bool retrieveField (const bool allowUnset, const objectRegistry & obr, const word & region, const word & patch, const label myComm, const labelListList & procToMap, const word & fieldName, Field< T > & fld) const protected
Definition at line 97 of file mappedPatchFieldBase.C.
References forAll, UPstream::procID(), UList< T >::size(), and mappedPatchBase::subRegistry().
sampleField() [1/3]
template<class Type > template<class T > const GeometricField< T, fvPatchField, volMesh > & sampleField (const word & fieldName) const
sampleField() [2/3]
template<class Type > const Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > & sampleField () const
Definition at line 508 of file mappedPatchFieldBase.C.
mappedField()
template<class Type > Foam::tmp< Foam::Field< Type > > mappedField () const virtual
Definition at line 606 of file mappedPatchFieldBase.C.
References Foam::abort(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld(), forAll, Foam::gSum(), Foam::mag(), VectorSpace< Form, Cmpt, Ncmpts >::max, UPstream::msgType(), mappedPatchBase::NEARESTCELL, mappedPatchBase::NEARESTFACE, mappedPatchBase::NEARESTPATCHFACE, mappedPatchBase::NEARESTPATCHFACEAMI, Foam::New(), interpolation< Type >::New(), Foam::nl, samples(), PtrList< T >::setSize(), UList< T >::size(), PtrList< T >::transfer(), and Foam::Zero.
mappedInternalField()
template<class Type > Foam::tmp< Foam::Field< Type > > mappedInternalField () const virtual
Definition at line 816 of file mappedPatchFieldBase.C.
References UPstream::msgType().
mappedWeightField() [1/2]
template<class Type > Foam::tmp< Foam::scalarField > mappedWeightField () const virtual
Definition at line 852 of file mappedPatchFieldBase.C.
References UPstream::msgType().
mappedWeightField() [2/2]
template<class Type > void mappedWeightField (const word & weightFieldName, tmp< scalarField > & thisWeights, tmp< scalarField > & nbrWeights) const virtual
Definition at line 889 of file mappedPatchFieldBase.C.
References UPstream::msgType().
write()
template<class Type > void write (Ostream & os) const virtual
Reimplemented in mappedFieldFvPatchField< Type >, mappedMixedFieldFvPatchField< Type >, mappedFixedPushedInternalValueFvPatchField< Type >, mappedFixedValueFvPatchField< Type >, mappedMixedFvPatchField< Type >, thermalBaffleFvPatchScalarField, mappedFixedInternalValueFvPatchField< Type >, turbulentTemperatureCoupledBaffleMixedFvPatchScalarField, and turbulentTemperatureRadCoupledMixedFvPatchScalarField.
Definition at line 996 of file mappedPatchFieldBase.C.
References mappedPatchBase::NEARESTCELL, os(), Ostream::writeEntry(), and Ostream::writeEntryIfDifferent().
Referenced by mappedFieldFvPatchField< Type >::write(), mappedMixedFieldFvPatchField< Type >::write(), mappedFixedValueFvPatchField< Type >::write(), mappedMixedFvPatchField< Type >::write(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::write(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::write().
mapper()
template<class Type > const Foam::mappedPatchBase & mapper (const fvPatch & p, const DimensionedField< Type, volMesh > & iF) static
Definition at line 947 of file mappedPatchFieldBase.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOobject::name(), Foam::nl, and p.
Referenced by turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs().
distribute()
template<class Type > template<class T > void distribute (const word & fieldName, Field< T > & newValues) const
Definition at line 516 of file mappedPatchFieldBase.C.
References fld(), mappedPatchBase::NEARESTPATCHFACEAMI, PtrList< T >::setSize(), AMIInterpolation::srcAddress(), AMIInterpolation::srcMap(), AMIInterpolation::srcWeights(), AMIInterpolation::tgtAddress(), AMIInterpolation::tgtMap(), and AMIInterpolation::tgtWeights().
sampleField() [3/3]
template<class Type > template<class Type2 > const Foam::GeometricField< Type2, Foam::fvPatchField, Foam::volMesh > & sampleField (const word & fieldName) const
Definition at line 479 of file mappedPatchFieldBase.C.
Member Data Documentation
mapper_
template<class Type > const mappedPatchBase& mapper_ protected
Definition at line 114 of file mappedPatchFieldBase.H.
Referenced by mappedPatchFieldBase< Type >::mappedPatchFieldBase(), and mappedPatchFieldBase< Type >::mappedPatchFieldBase().
patchField_
template<class Type > const fvPatchField<Type>& patchField_ protected
Definition at line 117 of file mappedPatchFieldBase.H.
Referenced by mappedPatchFieldBase< Type >::mappedPatchFieldBase().
fieldName_
template<class Type > word fieldName_ protected
Definition at line 120 of file mappedPatchFieldBase.H.
setAverage_
template<class Type > const bool setAverage_ protected
Definition at line 123 of file mappedPatchFieldBase.H.
average_
template<class Type > const Type average_ protected
Definition at line 127 of file mappedPatchFieldBase.H.
interpolationScheme_
template<class Type > word interpolationScheme_ protected
Definition at line 130 of file mappedPatchFieldBase.H.
Referenced by mappedPatchFieldBase< Type >::mappedPatchFieldBase().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/mappedField/mappedPatchFieldBase.H
src/finiteVolume/fields/fvPatchFields/derived/mappedField/mappedPatchFieldBase.C