OpenFOAM: centredCPCCellToFaceStencilObject Class Reference
centredCPCCellToFaceStencilObject Class Reference
#include <centredCPCCellToFaceStencilObject.H>
Public Member Functions
TypeName ("centredCPCCellToFaceStencil")
centredCPCCellToFaceStencilObject (const fvMesh &mesh)
virtual ~centredCPCCellToFaceStencilObject ()=default
Public Member Functions inherited from MeshObject< fvMesh, TopologicalMeshObject, centredCPCCellToFaceStencilObject >
MeshObject (const fvMesh &mesh)
MeshObject (const word &objName, const fvMesh &mesh)
virtual ~MeshObject ()=default
const fvMesh & mesh () const noexcept
virtual bool writeData (Ostream &os) const
Public Member Functions inherited from extendedCentredCellToFaceStencil
extendedCentredCellToFaceStencil (const cellToFaceStencil &)
const mapDistribute & map () const
const labelListList & stencil () const
void compact ()
template<class T >
void collectData (const GeometricField< T, fvPatchField, volMesh > &fld, List< List< T > > &stencilFld) const
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &stencilWeights) const
Public Member Functions inherited from extendedCellToFaceStencil
ClassName ("extendedCellToFaceStencil")
extendedCellToFaceStencil (const polyMesh &)
template<class Type >
void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, List< List< Type > > &stencilFld)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &stencilWeights)
Additional Inherited Members
Static Public Member Functions inherited from MeshObject< fvMesh, TopologicalMeshObject, centredCPCCellToFaceStencilObject >
static const centredCPCCellToFaceStencilObject & New (const fvMesh &mesh, Args &&... args)
static const centredCPCCellToFaceStencilObject & New (const word &objName, const fvMesh &mesh, Args &&... args)
static bool Delete (const word &objName, const fvMesh &mesh)
static bool Delete (const fvMesh &mesh)
Static Public Member Functions inherited from extendedCellToFaceStencil
template<class T >
static void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< T, fvPatchField, volMesh > &fld, List< List< T > > &stencilFld)
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &stencilWeights)
Static Protected Member Functions inherited from extendedCellToFaceStencil
static void writeStencilStats (Ostream &os, const labelListList &stencil, const mapDistribute &map)
Protected Attributes inherited from MeshObject< fvMesh, TopologicalMeshObject, centredCPCCellToFaceStencilObject >
const fvMesh & mesh_
Protected Attributes inherited from extendedCellToFaceStencil
const polyMesh & mesh_
Detailed Description
Source files
centredCPCCellToFaceStencilObject.H
Definition at line 47 of file centredCPCCellToFaceStencilObject.H.
Constructor & Destructor Documentation
centredCPCCellToFaceStencilObject()
centredCPCCellToFaceStencilObject (const fvMesh & mesh) inline explicit
Definition at line 65 of file centredCPCCellToFaceStencilObject.H.
References Foam::endl(), Foam::Info, extendedCentredCellToFaceStencil::map(), Foam::nl, extendedCentredCellToFaceStencil::stencil(), Foam::type(), and extendedCellToFaceStencil::writeStencilStats().
~centredCPCCellToFaceStencilObject()
virtual ~centredCPCCellToFaceStencilObject () virtual default
Member Function Documentation
TypeName()
TypeName ("centredCPCCellToFaceStencil")
The documentation for this class was generated from the following file:
src/finiteVolume/fvMesh/extendedStencil/cellToFace/MeshObjects/centredCPCCellToFaceStencilObject.H