OpenFOAM: exponential Class Reference
exponential Class Reference
Nucleate flux sub-cooling correlation.
#include <exponential.H>
Public Member Functions
TypeName ("exponential")
exponential (const dictionary &dict)
virtual ~exponential ()=default
virtual tmp< scalarField > qNucleate (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const
virtual void write (Ostream &os) const
Public Member Functions inherited from nucleateFluxModel
TypeName ("nucleateFluxModel")
declareRunTimeSelectionTable (autoPtr, nucleateFluxModel, dictionary,(const dictionary &dict),(dict))
nucleateFluxModel ()=default
virtual ~nucleateFluxModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from nucleateFluxModel
static autoPtr< nucleateFluxModel > New (const dictionary &dict)
Detailed Description
Nucleate flux sub-cooling correlation.
References:
    Frost W. & Dzakowic G. S. (1967)
    An extension of the methods of predicting incipient
    boiling on commercially finished surfaces.
    ASME AIChE Heat Transfer Conf 67-HT-61, Seattle.
    Shirai, Y., Tatsumoto, H., Shiotsu, M., Hata, K.,
    Kobayashi, H., Naruo, Y., & Inatani, Y. (2010).
    Boiling heat transfer from a horizontal flat
    plate in a pool of liquid hydrogen.
    Cryogenics, 50(6-7), 410-416.
    DOI:10.1016/j.cryogenics.2010.04.001
Usage
Example of the model specification:
nucleateFluxModel
{
    // Mandatory entries
    type            exponential;
    // Optional entries
    a               <scalar>;
    b               <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: exponential word yes -
a Pre-factor coefficient scalar no 6309
b Exponent coefficient scalar no 2.52
Source files
exponential.H
exponential.C
Definition at line 111 of file exponential.H.
Constructor & Destructor Documentation
exponential()
exponential (const dictionary & dict)
Definition at line 48 of file exponential.C.
~exponential()
virtual ~exponential () virtual default
Member Function Documentation
TypeName()
TypeName ("exponential")
qNucleate()
Foam::tmp< Foam::scalarField > qNucleate (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const virtual
Implements nucleateFluxModel.
Definition at line 62 of file exponential.C.
References Foam::max(), and Foam::pow().
write()
void write (Ostream & os) const virtual
Reimplemented from nucleateFluxModel.
Definition at line 79 of file exponential.C.
References os(), and nucleateFluxModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/nucleateFluxModels/exponential/exponential.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/nucleateFluxModels/exponential/exponential.C