OpenFOAM: pressureControl Class Reference
pressureControl Class Reference
Provides controls for the pressure reference is closed-volume simulations and a general method for limiting the pressure during the startup of steady-state simulations.
#include <pressureControl.H>
Public Member Functions
pressureControl (const volScalarField &p, const volScalarField &rho, const dictionary &dict, const bool pRefRequired=true)
label refCell () const
scalar refValue () const
bool limit (volScalarField &p) const
Detailed Description
Provides controls for the pressure reference is closed-volume simulations and a general method for limiting the pressure during the startup of steady-state simulations.
Source files
pressureControl.H
pressureControlI.H
pressureControl.C
Definition at line 50 of file pressureControl.H.
Constructor & Destructor Documentation
pressureControl()
pressureControl (const volScalarField & p, const volScalarField & rho, const dictionary & dict, const bool pRefRequired = true)
Definition at line 26 of file pressureControl.C.
References dict, Foam::dimDensity, Foam::dimPressure, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, forAll, UPtrList< T >::get(), Foam::Info, IOWarningInFunction, Foam::max(), Foam::min(), Foam::nl, p, pMin, Foam::reduce(), rho, rhoMax, rhoMin, Foam::setRefCell(), and dimensioned< Type >::value().
Member Function Documentation
refCell()
Foam::label refCell () const inline
Definition at line 23 of file pressureControlI.H.
refValue()
Foam::scalar refValue () const inline
Definition at line 29 of file pressureControlI.H.
limit()
bool limit (volScalarField & p) const
Definition at line 224 of file pressureControl.C.
References Foam::endl(), Foam::Info, Foam::max(), Foam::min(), p, and pMin.
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/pressureControl/pressureControl.H
src/finiteVolume/cfdTools/general/pressureControl/pressureControl.C
src/finiteVolume/cfdTools/general/pressureControl/pressureControlI.H