OpenFOAM: externalWallHeatFluxTemperatureFvPatchScalarField Class Reference
externalWallHeatFluxTemperatureFvPatchScalarField Class Reference
Boundary conditions » Thermophysical | Boundary conditions » Wall
This boundary condition applies a heat flux condition to temperature on an external wall in one of three modes:
#include <externalWallHeatFluxTemperatureFvPatchScalarField.H>
Public Types
enum operationMode { fixedPower , fixedHeatFlux , fixedHeatTransferCoeff }
Public Types inherited from temperatureCoupledBase
enum KMethodType {
mtFluidThermo , mtSolidThermo , mtDirectionalSolidThermo , mtLookup ,
mtFunction
}
Public Member Functions
TypeName ("externalWallHeatFluxTemperature")
externalWallHeatFluxTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
externalWallHeatFluxTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
externalWallHeatFluxTemperatureFvPatchScalarField (const externalWallHeatFluxTemperatureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
externalWallHeatFluxTemperatureFvPatchScalarField (const externalWallHeatFluxTemperatureFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
externalWallHeatFluxTemperatureFvPatchScalarField (const externalWallHeatFluxTemperatureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual bool fixesValue () const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchScalarField &, const labelList &)
virtual void updateCoeffs ()
void write (Ostream &) const
Public Member Functions inherited from temperatureCoupledBase
temperatureCoupledBase (const fvPatch &patch, const KMethodType method=KMethodType::mtFluidThermo)
temperatureCoupledBase (const fvPatch &patch, const KMethodType method, const word &kappaName, const word &alphaName, const word &alphaAniName)
temperatureCoupledBase (const fvPatch &patch, const dictionary &dict)
temperatureCoupledBase (const fvPatch &patch, const temperatureCoupledBase &base)
temperatureCoupledBase (const temperatureCoupledBase &base)
virtual ~temperatureCoupledBase ()=default
word KMethod () const
const word & kappaName () const noexcept
const word & alphaName () const noexcept
virtual tmp< scalarField > kappa (const scalarField &Tp) const
virtual tmp< scalarField > alpha (const scalarField &Tp) const
void write (Ostream &os) const
Static Public Attributes
static const Enum< operationMode > operationModeNames
Additional Inherited Members
Protected Attributes inherited from temperatureCoupledBase
const fvPatch & patch_
const KMethodType method_
const word kappaName_
const word alphaName_
const word alphaAniName_
autoPtr< PatchFunction1< scalar > > kappaFunction1_
autoPtr< PatchFunction1< scalar > > alphaFunction1_
Static Protected Attributes inherited from temperatureCoupledBase
static const Enum< KMethodType > KMethodTypeNames_
Detailed Description
This boundary condition applies a heat flux condition to temperature on an external wall in one of three modes:
fixed power: supply Q
fixed heat flux: supply q
fixed heat transfer coefficient: supply h and Ta
where:
= Power [W]
= Heat flux [W/m^2]
= Heat transfer coefficient [W/m^2/K]
= Ambient temperature [K]
For heat transfer coefficient mode optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries.
The thermal conductivity kappa can either be retrieved from various possible sources, as detailed in the class temperatureCoupledBase.
The ambient temperature Ta is specified as a Foam::Function1 of time but uniform in space.
Usage
Property Description Required Default
mode 'power', 'flux' or 'coefficient' yes
Q Power [W] for mode 'power'
q Heat flux [W/m^2] for mode 'flux'
h Heat transfer coefficient [W/m^2/K] for mode 'coefficient'
Ta Ambient temperature [K] for mode 'coefficient'
thicknessLayers Layer thicknesses [m] no
kappaLayers Layer thermal conductivities [W/m/K] no
relaxation Relaxation for the wall temperature no 1
emissivity Surface emissivity for radiative flux to ambient no 0
qr Name of the radiative field no none
qrRelaxation Relaxation factor for radiative field no 1
kappaMethod Inherited from temperatureCoupledBase inherited
kappa Inherited from temperatureCoupledBase inherited
Example of the boundary condition specification:
    <patchName>
    {
        type            externalWallHeatFluxTemperature;
        mode            coefficient;
        Ta              constant 300.0;
        h               constant 10.0;
        thicknessLayers (0.1 0.2 0.3 0.4);
        kappaLayers     (1 2 3 4);
        kappaMethod     fluidThermo;
        value           $internalField;
    }
Note
Quantities that are considered "global" (eg, power, ambient temperature) can be specified as Function1 types. Quantities that may have local variations (eg, htc, heat-flux) can be specified as PatchFunction1 types.
See also
Foam::temperatureCoupledBase Foam::mixedFvPatchScalarField
Source files
externalWallHeatFluxTemperatureFvPatchScalarField.H
externalWallHeatFluxTemperatureFvPatchScalarField.C
Definition at line 207 of file externalWallHeatFluxTemperatureFvPatchScalarField.H.
Member Enumeration Documentation
operationMode
enum operationMode
Enumerator
fixedPower
Heat power [W].
fixedHeatFlux
Heat flux [W/m2].
fixedHeatTransferCoeff
Heat transfer coefficient [W/m^2/K].
Definition at line 217 of file externalWallHeatFluxTemperatureFvPatchScalarField.H.
Constructor & Destructor Documentation
externalWallHeatFluxTemperatureFvPatchScalarField() [1/5]
externalWallHeatFluxTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 46 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
externalWallHeatFluxTemperatureFvPatchScalarField() [2/5]
externalWallHeatFluxTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 73 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, externalWallHeatFluxTemperatureFvPatchScalarField::fixedHeatFlux, externalWallHeatFluxTemperatureFvPatchScalarField::fixedHeatTransferCoeff, externalWallHeatFluxTemperatureFvPatchScalarField::fixedPower, IOobjectOption::MUST_READ, p, List< T >::resize(), UList< T >::size(), and Foam::Zero.
externalWallHeatFluxTemperatureFvPatchScalarField() [3/5]
externalWallHeatFluxTemperatureFvPatchScalarField (const externalWallHeatFluxTemperatureFvPatchScalarField & rhs, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 160 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
References Field< Type >::map(), List< T >::resize(), and FieldMapper::size().
externalWallHeatFluxTemperatureFvPatchScalarField() [4/5]
externalWallHeatFluxTemperatureFvPatchScalarField (const externalWallHeatFluxTemperatureFvPatchScalarField & rhs)
Definition at line 192 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
externalWallHeatFluxTemperatureFvPatchScalarField() [5/5]
externalWallHeatFluxTemperatureFvPatchScalarField (const externalWallHeatFluxTemperatureFvPatchScalarField & rhs, const DimensionedField< scalar, volMesh > & iF)
Definition at line 215 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("externalWallHeatFluxTemperature")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 309 of file externalWallHeatFluxTemperatureFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 325 of file externalWallHeatFluxTemperatureFvPatchScalarField.H.
fixesValue()
virtual bool fixesValue () const inline virtual
Definition at line 342 of file externalWallHeatFluxTemperatureFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & mapper) virtual
Implements temperatureCoupledBase.
Definition at line 241 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
References temperatureCoupledBase::autoMap().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Implements temperatureCoupledBase.
Definition at line 265 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
References temperatureCoupledBase::rmap().
updateCoeffs()
void updateCoeffs () virtual
Definition at line 295 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
References DebugInfo, forAll, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::gSum(), Foam::lerp(), Foam::mag(), Foam::nl, Foam::pow3(), UList< T >::size(), and Foam::Zero.
write()
void write (Ostream & os) const
Definition at line 464 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
References os(), fvPatchField< Type >::write(), temperatureCoupledBase::write(), Ostream::writeEntry(), and fvPatchField< Type >::writeValueEntry().
Member Data Documentation
operationModeNames
const Foam::Enum< Foam::externalWallHeatFluxTemperatureFvPatchScalarField::operationMode > operationModeNames static
Definition at line 224 of file externalWallHeatFluxTemperatureFvPatchScalarField.H.
The documentation for this class was generated from the following files:
src/thermoTools/derivedFvPatchFields/externalWallHeatFluxTemperature/externalWallHeatFluxTemperatureFvPatchScalarField.H
src/thermoTools/derivedFvPatchFields/externalWallHeatFluxTemperature/externalWallHeatFluxTemperatureFvPatchScalarField.C