OpenFOAM: GammaLimiter< LimiterFunc > Class Template Reference
GammaLimiter< LimiterFunc > Class Template Reference
Numerics » Finite volume numerical schemes » Surface interpolation schemes » Limited interpolation schemes
Class with limiter function which returns the limiter for the Gamma differencing scheme based on phict obtained from the LimiterFunc class.
#include <Gamma.H>
Public Member Functions
GammaLimiter (Istream &is)
scalar limiter (const scalar cdWeight, const scalar faceFlux, const typename LimiterFunc::phiType &phiP, const typename LimiterFunc::phiType &phiN, const typename LimiterFunc::gradPhiType &gradcP, const typename LimiterFunc::gradPhiType &gradcN, const vector &d) const
Detailed Description
template<class LimiterFunc>
class Foam::GammaLimiter< LimiterFunc >
Class with limiter function which returns the limiter for the Gamma differencing scheme based on phict obtained from the LimiterFunc class.
Used in conjunction with the template class LimitedScheme.
Source files
Gamma.H
Gamma.C
Definition at line 54 of file Gamma.H.
Constructor & Destructor Documentation
GammaLimiter()
template<class LimiterFunc > GammaLimiter (Istream & is) inline
Definition at line 62 of file Gamma.H.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::max().
Member Function Documentation
limiter()
template<class LimiterFunc > scalar limiter (const scalar cdWeight, const scalar faceFlux, const typename LimiterFunc::phiType & phiP, const typename LimiterFunc::phiType & phiN, const typename LimiterFunc::gradPhiType & gradcP, const typename LimiterFunc::gradPhiType & gradcN, const vector & d) const inline
Definition at line 79 of file Gamma.H.
References Foam::clamp().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/Gamma/Gamma.H