OpenFOAM: Explicit< CloudType > Class Template Reference
Explicit< CloudType > Class Template Reference
Lagrangian particle models » Submodels » MP-PIC » Packing
Explicit model for applying an inter-particle stress to the particles.
#include <Explicit.H>
Public Member Functions
TypeName ("explicit")
Explicit (const dictionary &dict, CloudType &owner)
Explicit (const Explicit< CloudType > &cm)
virtual autoPtr< PackingModel< CloudType > > clone () const
virtual ~Explicit ()
virtual void cacheFields (const bool store)
virtual vector velocityCorrection (typename CloudType::parcelType &p, const scalar deltaT) const
Public Member Functions inherited from PackingModel< CloudType >
TypeName ("packingModel")
declareRunTimeSelectionTable (autoPtr, PackingModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
PackingModel (CloudType &owner)
PackingModel (const dictionary &dict, CloudType &owner, const word &type)
PackingModel (const PackingModel< CloudType > &cm)
virtual ~PackingModel ()
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
virtual ~CloudSubModelBase ()=default
const CloudType & owner () const
virtual bool writeTime () const
virtual fileName localPath () const
CloudType & owner ()
virtual void info ()
virtual void write (Ostream &os) const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
subModelBase (const subModelBase &smb)
virtual ~subModelBase ()=default
const word & modelName () const
const dictionary & dict () const
const word & baseName () const
const word & modelType () const
const dictionary & coeffDict () const
const dictionary & properties () const
virtual bool defaultCoeffs (const bool printMsg) const
virtual bool active () const
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
bool getModelDict (const word &entryName, dictionary &dict) const
template<class Type >
bool getModelProperty (const word &entryName, Type &value) const
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Static Public Member Functions inherited from PackingModel< CloudType >
static autoPtr< PackingModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Public Attributes inherited from subModelBase
bool log
Protected Member Functions inherited from subModelBase
bool inLine () const
Protected Attributes inherited from PackingModel< CloudType >
autoPtr< ParticleStressModel > particleStressModel_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Protected Attributes inherited from subModelBase
const word modelName_
dictionary & properties_
const dictionary dict_
const word baseName_
const word modelType_
const dictionary coeffDict_
Detailed Description
template<class CloudType>
class Foam::PackingModels::Explicit< CloudType >
Explicit model for applying an inter-particle stress to the particles.
The inter-particle stress is calculated using current particle locations. This force is then applied only to the particles that are moving towards regions of close pack. The resulting velocity change is limited using an abtracted correction velocity limiter.
Reference:
    "An Incompressible Three-Dimensional Multiphase Particle-in-Cell Model
    for Dense Particle Flows"
    D Snider
    Journal of Computational Physics
    Volume 170, Issue 2, Pages 523-549, July 2001
Source files
Explicit.H
Explicit.C
Definition at line 66 of file Explicit.H.
Constructor & Destructor Documentation
Explicit() [1/2]
template<class CloudType > Explicit (const dictionary & dict, CloudType & owner)
Definition at line 27 of file Explicit.C.
References Foam::New().
Explicit() [2/2]
template<class CloudType > Explicit (const Explicit< CloudType > & cm)
Definition at line 46 of file Explicit.C.
~Explicit()
template<class CloudType > ~Explicit () virtual
Definition at line 63 of file Explicit.C.
Member Function Documentation
TypeName()
template<class CloudType > TypeName ("explicit")
clone()
template<class CloudType > virtual autoPtr< PackingModel< CloudType > > clone () const inline virtual
Implements PackingModel< CloudType >.
Definition at line 101 of file Explicit.H.
cacheFields()
template<class CloudType > void cacheFields (const bool store) virtual
Reimplemented from subModelBase.
Definition at line 70 of file Explicit.C.
References subModelBase::cacheFields(), PtrList< T >::clear(), cloudName(), and mesh.
velocityCorrection()
template<class CloudType > Foam::vector velocityCorrection (typename CloudType::parcelType & p, const scalar deltaT) const virtual
Implements PackingModel< CloudType >.
Definition at line 136 of file Explicit.C.
References alpha, p, and Foam::Zero.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/PackingModels/Explicit/Explicit.H
src/lagrangian/intermediate/submodels/MPPIC/PackingModels/Explicit/Explicit.C