OpenFOAM: snappyRefineDriver Class Reference
snappyRefineDriver Class Reference
#include <snappyRefineDriver.H>
Public Member Functions
ClassName ("snappyRefineDriver")
snappyRefineDriver (meshRefinement &meshRefiner, decompositionMethod &decomposer, fvMeshDistribute &distributor, const labelUList &globalToMasterPatch, const labelUList &globalToSlavePatch, coordSetWriter &setFormatter, const bool dryRun=false)
void doRefine (const dictionary &refineDict, const refinementParameters &refineParams, const snapParameters &snapParams, const bool prepareForSnapping, const meshRefinement::FaceMergeType mergeType, const dictionary &motionDict)
Static Public Member Functions
static void addFaceZones (meshRefinement &meshRefiner, const refinementParameters &refineParams, const HashTable< Pair< word > > &faceZoneToPatches)
Detailed Description
Source files
snappyRefineDriver.H
snappyRefineDriver.C
Definition at line 61 of file snappyRefineDriver.H.
Constructor & Destructor Documentation
snappyRefineDriver()
snappyRefineDriver (meshRefinement & meshRefiner, decompositionMethod & decomposer, fvMeshDistribute & distributor, const labelUList & globalToMasterPatch, const labelUList & globalToSlavePatch, coordSetWriter & setFormatter, const bool dryRun = false)
Definition at line 56 of file snappyRefineDriver.C.
Member Function Documentation
ClassName()
ClassName ("snappyRefineDriver")
doRefine()
void doRefine (const dictionary & refineDict, const refinementParameters & refineParams, const snapParameters & snapParams, const bool prepareForSnapping, const meshRefinement::FaceMergeType mergeType, const dictionary & motionDict)
Definition at line 3291 of file snappyRefineDriver.C.
References addProfiling, Foam::endl(), UPtrList< T >::first(), forAll, surfaceZonesInfo::getUnnamedSurfaces(), Foam::Info, Foam::labelMax, Foam::max(), mesh, primitiveMesh::nCells(), Foam::nl, UPstream::parRun(), patches, and UPtrList< T >::size().
addFaceZones()
void addFaceZones (meshRefinement & meshRefiner, const refinementParameters & refineParams, const HashTable< Pair< word > > & faceZoneToPatches) static
Definition at line 3015 of file snappyRefineDriver.C.
References polyMesh::boundaryMesh(), Foam::endl(), surfaceZonesInfo::faceZoneTypeNames, forAllConstIters, Foam::Info, mesh, Foam::nl, patchNames(), Foam::setf(), Foam::setw(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappyRefineDriver.H
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappyRefineDriver.C