OpenFOAM: kOmega< BasicTurbulenceModel > Class Template Reference
kOmega< BasicTurbulenceModel > Class Template Reference
Turbulence models » RAS turbulence
Standard high Reynolds-number k-omega turbulence model for incompressible and compressible flows.
#include <kOmega.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kOmega")
kOmega (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~kOmega ()=default
virtual bool read ()
tmp< volScalarField > DkEff () const
tmp< volScalarField > DomegaEff () const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > omega () const
virtual void correct ()
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
virtual void correctNut ()
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar beta_
dimensionedScalar gamma_
dimensionedScalar alphaK_
dimensionedScalar alphaOmega_
volScalarField k_
volScalarField omega_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::kOmega< BasicTurbulenceModel >
Standard high Reynolds-number k-omega turbulence model for incompressible and compressible flows.
References:
    Wilcox, D. C. (1988).
    Reassessment of the scale-determining
    equation for advanced turbulence models.
    AIAA Journal, 26(11), 1299-1310.
    DOI:10.2514/3.10041
The default model coefficients are
    kOmegaCoeffs
    {
        Cmu         0.09;  // Equivalent to betaStar
        alpha       0.52;
        beta        0.072;
        alphak      0.5;
        alphaOmega  0.5;
    }
Source files
kOmega.H
kOmega.C
Definition at line 76 of file kOmega.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 107 of file kOmega.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 108 of file kOmega.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 109 of file kOmega.H.
Constructor & Destructor Documentation
kOmega()
template<class BasicTurbulenceModel > kOmega (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 49 of file kOmega.C.
References Foam::bound(), kOmega< BasicTurbulenceModel >::k_, kOmega< BasicTurbulenceModel >::omega_, and Foam::type().
~kOmega()
template<class BasicTurbulenceModel > virtual ~kOmega () virtual default
Member Function Documentation
correctNut()
template<class BasicTurbulenceModel > void correctNut () protected virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 36 of file kOmega.C.
References options::New().
TypeName()
template<class BasicTurbulenceModel > TypeName ("kOmega< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 157 of file kOmega.C.
References Foam::read().
DkEff()
template<class BasicTurbulenceModel > tmp< volScalarField > DkEff () const inline
Definition at line 142 of file kOmega.H.
References kOmega< BasicTurbulenceModel >::alphaK_, nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
DomegaEff()
template<class BasicTurbulenceModel > tmp< volScalarField > DomegaEff () const inline
Definition at line 155 of file kOmega.H.
References kOmega< BasicTurbulenceModel >::alphaOmega_, nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
k()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > k () const inline virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 168 of file kOmega.H.
References kOmega< BasicTurbulenceModel >::k_.
omega()
template<class BasicTurbulenceModel > virtual tmp< volScalarField > omega () const inline virtual
Definition at line 174 of file kOmega.H.
References kOmega< BasicTurbulenceModel >::omega_.
correct()
template<class BasicTurbulenceModel > void correct () virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 175 of file kOmega.C.
References Foam::fvc::absolute(), alpha, Foam::bound(), PtrList< T >::clear(), correct(), Foam::fvm::ddt(), Foam::devTwoSymm(), Foam::fvc::div(), Foam::fvm::div(), divU, fvOptions, Foam::fvc::grad(), Foam::fvm::laplacian(), options::New(), nut, phi, rho, solve(), Foam::fvm::Sp(), Foam::fvm::SuSp(), and U.
Member Data Documentation
Cmu_
template<class BasicTurbulenceModel > dimensionedScalar Cmu_ protected
Definition at line 87 of file kOmega.H.
beta_
template<class BasicTurbulenceModel > dimensionedScalar beta_ protected
Definition at line 88 of file kOmega.H.
gamma_
template<class BasicTurbulenceModel > dimensionedScalar gamma_ protected
Definition at line 89 of file kOmega.H.
alphaK_
template<class BasicTurbulenceModel > dimensionedScalar alphaK_ protected
Definition at line 90 of file kOmega.H.
Referenced by kOmega< BasicTurbulenceModel >::DkEff().
alphaOmega_
template<class BasicTurbulenceModel > dimensionedScalar alphaOmega_ protected
Definition at line 91 of file kOmega.H.
Referenced by kOmega< BasicTurbulenceModel >::DomegaEff().
k_
template<class BasicTurbulenceModel > volScalarField k_ protected
Definition at line 96 of file kOmega.H.
Referenced by kOmega< BasicTurbulenceModel >::k(), and kOmega< BasicTurbulenceModel >::kOmega().
omega_
template<class BasicTurbulenceModel > volScalarField omega_ protected
Definition at line 97 of file kOmega.H.
Referenced by kOmega< BasicTurbulenceModel >::kOmega(), and kOmega< BasicTurbulenceModel >::omega().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/kOmega/kOmega.H
src/TurbulenceModels/turbulenceModels/RAS/kOmega/kOmega.C