OpenFOAM: gzstreambase Class Reference
gzstreambase Class Reference
#include <gzstream.h>
Public Member Functions
gzstreambase ()
gzstreambase (const char *_name, int _open_mode)
~gzstreambase ()
void open (const char *_name, int _open_mode)
void close ()
gzstreambuf * rdbuf ()
Protected Attributes
gzstreambuf buf
Detailed Description
Definition at line 113 of file gzstream.h.
Constructor & Destructor Documentation
gzstreambase() [1/2]
gzstreambase () inline
Definition at line 126 of file gzstream.h.
gzstreambase() [2/2]
gzstreambase (const char * _name, int _open_mode)
~gzstreambase()
~gzstreambase ()
Member Function Documentation
open()
void open (const char * _name, int _open_mode)
Referenced by igzstream::open(), ogzstream::open(), igzstream::open(), and ogzstream::open().
close()
void close ()
rdbuf()
gzstreambuf * rdbuf () inline
Definition at line 137 of file gzstream.h.
Referenced by igzstream::rdbuf(), and ogzstream::rdbuf().
Member Data Documentation
buf
gzstreambuf buf protected
Definition at line 120 of file gzstream.h.
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/gzstream/gzstream.h