OpenFOAM: refinementParameters Class Reference
refinementParameters Class Reference
Simple container to keep together refinement specific information.
#include <refinementParameters.H>
Public Member Functions
refinementParameters (const dictionary &dict, const bool dryRun=false)
label maxGlobalCells () const
label maxLocalCells () const
label minRefineCells () const
scalar curvature () const
scalar planarAngle () const
label nBufferLayers () const
const pointField & locationsInMesh () const
const wordList & zonesInMesh () const
const pointField & locationsOutsideMesh () const
bool useLeakClosure () const
bool allowFreeStandingZoneFaces () const
bool useTopologicalSnapDetection () const
scalar maxLoadUnbalance () const
label maxCellUnbalance () const
bool handleSnapProblems () const
bool interfaceRefine () const
label nErodeCellZone () const
label nFilterIter () const
scalar minCellFraction () const
label nMinCells () const
bool balanceAtEnd () const
dictionary getZoneInfo (const word &fzName, surfaceZonesInfo::faceZoneType &faceType) const
labelList addCellZonesToMesh (polyMesh &) const
Static Public Member Functions
static labelList findCells (const bool checkInsideMesh, const polyMesh &, const pointField &locations)
static labelList zonedLocations (const wordList &zonesInMesh)
static labelList unzonedLocations (const wordList &zonesInMesh)
static List< pointField > zonePoints (const pointField &locationsInMesh, const wordList &zonesInMesh, const pointField &locationsOutsideMesh)
Detailed Description
Simple container to keep together refinement specific information.
Source files
refinementParameters.H
refinementParameters.C
Definition at line 54 of file refinementParameters.H.
Constructor & Destructor Documentation
refinementParameters()
refinementParameters (const dictionary & dict, const bool dryRun = false)
Definition at line 32 of file refinementParameters.C.
References List< T >::append(), Foam::cos(), Foam::degToRad(), dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, UPtrList< T >::first(), forAll, IOWarningInFunction, word::null, List< T >::setSize(), UPtrList< T >::size(), and UList< T >::size().
Member Function Documentation
maxGlobalCells()
label maxGlobalCells () const inline
Definition at line 149 of file refinementParameters.H.
maxLocalCells()
label maxLocalCells () const inline
Definition at line 155 of file refinementParameters.H.
minRefineCells()
label minRefineCells () const inline
Definition at line 161 of file refinementParameters.H.
curvature()
scalar curvature () const inline
Definition at line 167 of file refinementParameters.H.
planarAngle()
scalar planarAngle () const inline
Definition at line 173 of file refinementParameters.H.
nBufferLayers()
label nBufferLayers () const inline
Definition at line 179 of file refinementParameters.H.
locationsInMesh()
const pointField & locationsInMesh () const inline
Definition at line 185 of file refinementParameters.H.
zonesInMesh()
const wordList & zonesInMesh () const inline
Definition at line 191 of file refinementParameters.H.
locationsOutsideMesh()
const pointField & locationsOutsideMesh () const inline
Definition at line 197 of file refinementParameters.H.
useLeakClosure()
bool useLeakClosure () const inline
Definition at line 207 of file refinementParameters.H.
allowFreeStandingZoneFaces()
bool allowFreeStandingZoneFaces () const inline
Definition at line 214 of file refinementParameters.H.
useTopologicalSnapDetection()
bool useTopologicalSnapDetection () const inline
Definition at line 221 of file refinementParameters.H.
maxLoadUnbalance()
scalar maxLoadUnbalance () const inline
Definition at line 227 of file refinementParameters.H.
maxCellUnbalance()
label maxCellUnbalance () const inline
Definition at line 233 of file refinementParameters.H.
handleSnapProblems()
bool handleSnapProblems () const inline
Definition at line 238 of file refinementParameters.H.
interfaceRefine()
bool interfaceRefine () const inline
Definition at line 244 of file refinementParameters.H.
nErodeCellZone()
label nErodeCellZone () const inline
Definition at line 250 of file refinementParameters.H.
nFilterIter()
label nFilterIter () const inline
Definition at line 257 of file refinementParameters.H.
minCellFraction()
scalar minCellFraction () const inline
Definition at line 264 of file refinementParameters.H.
nMinCells()
label nMinCells () const inline
Definition at line 271 of file refinementParameters.H.
balanceAtEnd()
bool balanceAtEnd () const inline
Definition at line 277 of file refinementParameters.H.
getZoneInfo()
Foam::dictionary getZoneInfo (const word & fzName, surfaceZonesInfo::faceZoneType & faceType) const
Definition at line 158 of file refinementParameters.C.
References dictionary::add(), surfaceZonesInfo::faceZoneTypeNames, and surfaceZonesInfo::INTERNAL.
addCellZonesToMesh()
Foam::labelList addCellZonesToMesh (polyMesh & mesh) const
Definition at line 187 of file refinementParameters.C.
References surfaceZonesInfo::addCellZone(), forAll, mesh, word::null, and zoneIDs.
findCells()
Foam::labelList findCells (const bool checkInsideMesh, const polyMesh & mesh, const pointField & locations) static
Definition at line 209 of file refinementParameters.C.
References polyMesh::bounds(), Foam::endl(), Foam::exit(), polyMesh::FACE_DIAG_TRIS, Foam::FatalError, FatalErrorInFunction, polyMesh::findCell(), forAll, Foam::Info, mesh, primitiveMesh::nCells(), Foam::nl, Foam::reduce(), UPtrList< T >::size(), and polyMesh::tetBasePtIs().
zonedLocations()
Foam::labelList zonedLocations (const wordList & zonesInMesh) static
Definition at line 269 of file refinementParameters.C.
References PtrList< T >::append(), forAll, word::null, and UList< T >::size().
unzonedLocations()
Foam::labelList unzonedLocations (const wordList & zonesInMesh) static
Definition at line 291 of file refinementParameters.C.
References PtrList< T >::append(), forAll, and word::null.
zonePoints()
Foam::List< Foam::pointField > zonePoints (const pointField & locationsInMesh, const wordList & zonesInMesh, const pointField & locationsOutsideMesh) static
Definition at line 313 of file refinementParameters.C.
References PtrList< T >::append(), forAll, Foam::name(), UPtrList< T >::size(), and UList< T >::size().
Referenced by meshRefinement::blockLeakFaces().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/snappyHexMeshDriver/refinementParameters/refinementParameters.H
src/mesh/snappyHexMesh/snappyHexMeshDriver/refinementParameters/refinementParameters.C