OpenFOAM: LESfilter Class Reference
LESfilter Class Reference abstract
Abstract class for LES filters.
#include <LESfilter.H>
Public Member Functions
TypeName ("LESfilter")
declareRunTimeSelectionTable (autoPtr, LESfilter, dictionary,(const fvMesh &mesh, const dictionary &LESfilterDict),(mesh, LESfilterDict))
LESfilter (const fvMesh &mesh)
virtual ~LESfilter ()=default
const fvMesh & mesh () const
virtual void read (const dictionary &)=0
virtual tmp< volScalarField > operator() (const tmp< volScalarField > &) const =0
virtual tmp< volVectorField > operator() (const tmp< volVectorField > &) const =0
virtual tmp< volSymmTensorField > operator() (const tmp< volSymmTensorField > &) const =0
virtual tmp< volTensorField > operator() (const tmp< volTensorField > &) const =0
Static Public Member Functions
static autoPtr< LESfilter > New (const fvMesh &, const dictionary &, const word &filterDictName="filter")
Protected Member Functions
template<class GeoFieldType >
void correctBoundaryConditions (const tmp< GeoFieldType > &tgf) const
Detailed Description
Abstract class for LES filters.
Source files
LESfilter.H
LESfilter.C
newFilter.C
Definition at line 53 of file LESfilter.H.
Constructor & Destructor Documentation
LESfilter()
LESfilter (const fvMesh & mesh) inline
Definition at line 110 of file LESfilter.H.
~LESfilter()
virtual ~LESfilter () virtual default
Member Function Documentation
correctBoundaryConditions()
template<class GeoFieldType > void correctBoundaryConditions (const tmp< GeoFieldType > & tgf) const inline protected
Definition at line 80 of file LESfilter.H.
TypeName()
TypeName ("LESfilter")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , LESfilter , dictionary , (const fvMesh &mesh, const dictionary &LESfilterDict) , (mesh, LESfilterDict))
New()
Foam::autoPtr< Foam::LESfilter > New (const fvMesh & mesh, const dictionary & dict, const word & filterDictName = "filter") static
Definition at line 36 of file LESfilter.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and LESfilter::mesh().
mesh()
const fvMesh & mesh () const inline
Definition at line 134 of file LESfilter.H.
Referenced by anisotropicFilter::anisotropicFilter(), anisotropicFilter::anisotropicFilter(), laplaceFilter::laplaceFilter(), laplaceFilter::laplaceFilter(), and LESfilter::New().
read()
virtual void read (const dictionary &) pure virtual
Implemented in anisotropicFilter, laplaceFilter, and simpleFilter.
operator()() [1/4]
virtual tmp< volScalarField > operator() (const tmp< volScalarField > &) const pure virtual
Implemented in anisotropicFilter, laplaceFilter, and simpleFilter.
operator()() [2/4]
virtual tmp< volVectorField > operator() (const tmp< volVectorField > &) const pure virtual
Implemented in anisotropicFilter, laplaceFilter, and simpleFilter.
operator()() [3/4]
virtual tmp< volSymmTensorField > operator() (const tmp< volSymmTensorField > &) const pure virtual
Implemented in anisotropicFilter, laplaceFilter, and simpleFilter.
operator()() [4/4]
virtual tmp< volTensorField > operator() (const tmp< volTensorField > &) const pure virtual
Implemented in anisotropicFilter, laplaceFilter, and simpleFilter.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESfilters/LESfilter/LESfilter.H
src/TurbulenceModels/turbulenceModels/LES/LESfilters/LESfilter/LESfilter.C