OpenFOAM: PhiLimiter Class Reference
PhiLimiter Class Reference
Numerics » Finite volume numerical schemes » Surface interpolation schemes » Limited interpolation schemes
Class with limiter function which returns the limiter for the Phi differencing scheme.
#include <Phi.H>
Public Member Functions
PhiLimiter (Istream &is)
scalar limiter (const scalar cdWeight, const scalar faceFlux, const vector &PhiP, const vector &PhiN, const vector &Sf, const scalar &) const
Detailed Description
Class with limiter function which returns the limiter for the Phi differencing scheme.
Used in conjunction with the template class PhiScheme.
Source files
Phi.H
Phi.C
Definition at line 52 of file Phi.H.
Constructor & Destructor Documentation
PhiLimiter()
PhiLimiter (Istream & is) inline
Definition at line 58 of file Phi.H.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
Member Function Documentation
limiter()
scalar limiter (const scalar cdWeight, const scalar faceFlux, const vector & PhiP, const vector & PhiN, const vector & Sf, const scalar &) const inline
Definition at line 71 of file Phi.H.
References Foam::clamp(), and Foam::stabilise().
Referenced by PhiScheme< Type, PhiLimiter >::limiter().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/Phi/Phi.H