OpenFOAM: treeDataPrimitivePatch< PatchType > Class Template Reference
treeDataPrimitivePatch< PatchType > Class Template Reference
Encapsulation of data needed to search on PrimitivePatches.
#include <treeDataPrimitivePatch.H>
Classes
class findAllIntersectOp
class findIntersectOp
class findNearestOp
class findSelfIntersectOp
Public Member Functions
treeDataPrimitivePatch (const bool cacheBb, const PatchType &patch, const scalar planarTol)
treeDataPrimitivePatch (const PatchType &patch, const scalar planarTol)
int nDim () const noexcept
treeBoundBox bounds (const labelUList &indices) const
const PatchType & patch () const noexcept
bool useSubset () const noexcept
const labelList& faceLabels() const noexcept { labelList::null(); }
bool empty () const
label size () const
label objectIndex (const label index) const noexcept
const point & centre (const label index) const
tmp< pointField > centres () const
volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< PatchType > > &, const point &) const
bool overlaps (const label index, const treeBoundBox &searchBox) const
bool overlaps (const label index, const point &centre, const scalar radiusSqr) const
void findNearest (const labelUList &indices, const point &sample, scalar &nearestDistSqr, label &nearestIndex, point &nearestPoint) const
Foam::volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< triSurface > > &oc, const point &sample) const
volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< triSurface > > &oc, const point &sample) const
Static Public Member Functions
static treeBoundBoxList boxes (const PatchType &patch)
static bool findIntersection (const indexedOctree< treeDataPrimitivePatch< PatchType > > &tree, const label index, const point &start, const point &end, point &intersectionPoint)
Detailed Description
template<class PatchType>
class Foam::treeDataPrimitivePatch< PatchType >
Encapsulation of data needed to search on PrimitivePatches.
Source files
treeDataPrimitivePatch.H
treeDataPrimitivePatch.C
Definition at line 59 of file treeDataPrimitivePatch.H.
Constructor & Destructor Documentation
treeDataPrimitivePatch() [1/2]
template<class PatchType > treeDataPrimitivePatch (const bool cacheBb, const PatchType & patch, const scalar planarTol)
Definition at line 78 of file treeDataPrimitivePatch.C.
treeDataPrimitivePatch() [2/2]
template<class PatchType > treeDataPrimitivePatch (const PatchType & patch, const scalar planarTol) inline
Definition at line 210 of file treeDataPrimitivePatch.H.
Member Function Documentation
boxes()
template<class PatchType > Foam::treeBoundBoxList boxes (const PatchType & patch) static
Definition at line 32 of file treeDataPrimitivePatch.C.
References UPtrList< T >::begin(), f(), points, pp(), and PtrList< T >::PtrList().
nDim()
template<class PatchType > int nDim () const inline noexcept
Definition at line 225 of file treeDataPrimitivePatch.H.
bounds()
template<class PatchType > Foam::treeBoundBox bounds (const labelUList & indices) const
Definition at line 142 of file treeDataPrimitivePatch.C.
References boundBox::add().
patch()
template<class PatchType > const PatchType & patch () const inline noexcept
Definition at line 234 of file treeDataPrimitivePatch.H.
Referenced by treeDataPrimitivePatch< PatchType >::findIntersection(), and treeDataPrimitivePatch< PatchType >::findSelfIntersectOp::operator()().
useSubset()
template<class PatchType > bool useSubset () const inline noexcept
const labelList& faceLabels() const noexcept { labelList::null(); }
Definition at line 240 of file treeDataPrimitivePatch.H.
empty()
template<class PatchType > bool empty () const inline
Definition at line 243 of file treeDataPrimitivePatch.H.
References UPtrList< T >::size().
size()
template<class PatchType > label size () const inline
Definition at line 246 of file treeDataPrimitivePatch.H.
References UPtrList< T >::size().
objectIndex()
template<class PatchType > label objectIndex (const label index) const inline noexcept
Definition at line 249 of file treeDataPrimitivePatch.H.
centre()
template<class PatchType > const point & centre (const label index) const inline
const typename PatchType::face_type& operator[](label index) const { return patch_[index]; }
Definition at line 256 of file treeDataPrimitivePatch.H.
Referenced by treeDataPrimitivePatch< PatchType >::overlaps().
centres()
template<class PatchType > tmp< pointField > centres () const inline
Definition at line 263 of file treeDataPrimitivePatch.H.
getVolumeType() [1/3]
template<class PatchType > Foam::volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< PatchType > > & oc, const point & sample) const
Definition at line 159 of file treeDataPrimitivePatch.C.
References Foam::abort(), e, Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, forAll, indexedOctree< Type >::getSide(), PointIndexHit< PointType >::index(), Foam::mag(), Foam::magSqr(), Foam::normalised(), points, Foam::Pout, Foam::sqr(), volumeType::UNKNOWN, and Foam::Zero.
overlaps() [1/2]
template<class PatchType > bool overlaps (const label index, const treeBoundBox & searchBox) const
Definition at line 388 of file treeDataPrimitivePatch.C.
References f(), forAll, and points.
Referenced by treeDataPrimitivePatch< PatchType >::overlaps().
overlaps() [2/2]
template<class PatchType > bool overlaps (const label index, const point & centre, const scalar radiusSqr) const
Definition at line 447 of file treeDataPrimitivePatch.C.
References treeDataPrimitivePatch< PatchType >::centre(), f(), treeBoundBox::overlaps(), treeDataPrimitivePatch< PatchType >::overlaps(), points, and Foam::sqr().
findIntersection()
template<class PatchType > bool findIntersection (const indexedOctree< treeDataPrimitivePatch< PatchType > > & tree, const label index, const point & start, const point & end, point & intersectionPoint) static
Definition at line 615 of file treeDataPrimitivePatch.C.
References f(), intersection::HALF_RAY, treeDataPrimitivePatch< PatchType >::patch(), points, and tree().
Referenced by treeDataPrimitivePatch< PatchType >::findIntersectOp::operator()(), treeDataPrimitivePatch< PatchType >::findAllIntersectOp::operator()(), and treeDataPrimitivePatch< PatchType >::findSelfIntersectOp::operator()().
findNearest()
template<class PatchType > void findNearest (const labelUList & indices, const point & sample, scalar & nearestDistSqr, label & nearestIndex, point & nearestPoint) const
Definition at line 484 of file treeDataPrimitivePatch.C.
References f(), points, and Foam::sqr().
Referenced by treeDataPrimitivePatch< PatchType >::findNearestOp::operator()().
getVolumeType() [2/3]
Foam::volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< triSurface > > & oc, const point & sample) const
Definition at line 28 of file treeDataTriSurface.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, PointIndexHit< PointType >::index(), triSurfaceTools::INSIDE, volumeType::INSIDE, triSurfaceTools::OUTSIDE, volumeType::OUTSIDE, Foam::sqr(), triSurfaceTools::surfaceSide(), triSurfaceTools::UNKNOWN, and volumeType::UNKNOWN.
getVolumeType() [3/3]
volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< triSurface > > & oc, const point & sample) const
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataPrimitivePatch.H
src/meshTools/indexedOctree/treeDataPrimitivePatch.C