OpenFOAM: foamVtkMeshMaps Class Reference
foamVtkMeshMaps Class Reference
Bookkeeping for mesh subsetting and/or polyhedral cell decomposition. Although the main use case is for handling vtk meshes, it is not specific to VTK alone.
#include <foamVtkMeshMaps.H>
Public Member Functions
foamVtkMeshMaps ()=default
const labelList & cellMap () const noexcept
DynamicList< label > & cellMap () noexcept
const labelList & pointMap () const noexcept
DynamicList< label > & pointMap () noexcept
const labelList & additionalIds () const noexcept
DynamicList< label > & additionalIds () noexcept
void clear ()
void renumberCells (const labelUList &mapping)
void renumberPoints (const labelUList &mapping)
Detailed Description
Bookkeeping for mesh subsetting and/or polyhedral cell decomposition. Although the main use case is for handling vtk meshes, it is not specific to VTK alone.
The cellMap is a local-to-global lookup for normal and decomposed cells. The pointMap is an optional local-to-global lookup for point ids. The additional ids is typically used to store the cell-centre labels for additional points of decomposed cells
Source files
foamVtkMeshMaps.H
foamVtkMeshMaps.C
foamVtkMeshMapsI.H
Definition at line 54 of file foamVtkMeshMaps.H.
Constructor & Destructor Documentation
foamVtkMeshMaps()
foamVtkMeshMaps () default
Member Function Documentation
cellMap() [1/2]
const Foam::labelList & cellMap () const inline noexcept
Definition at line 34 of file foamVtkMeshMapsI.H.
Referenced by vtuAdaptor::convertField().
cellMap() [2/2]
Foam::DynamicList< Foam::label > & cellMap () inline noexcept
Definition at line 41 of file foamVtkMeshMapsI.H.
pointMap() [1/2]
const Foam::labelList & pointMap () const inline noexcept
Definition at line 48 of file foamVtkMeshMapsI.H.
pointMap() [2/2]
Foam::DynamicList< Foam::label > & pointMap () inline noexcept
Definition at line 55 of file foamVtkMeshMapsI.H.
additionalIds() [1/2]
const Foam::labelList & additionalIds () const inline noexcept
Definition at line 62 of file foamVtkMeshMapsI.H.
Referenced by vtuAdaptor::points().
additionalIds() [2/2]
Foam::DynamicList< Foam::label > & additionalIds () inline noexcept
Definition at line 69 of file foamVtkMeshMapsI.H.
clear()
void clear () inline
Definition at line 25 of file foamVtkMeshMapsI.H.
References DynamicList< T, SizeMin >::clear().
renumberCells()
void renumberCells (const labelUList & mapping)
Definition at line 26 of file foamVtkMeshMaps.C.
References Foam::inplaceRenumber().
renumberPoints()
void renumberPoints (const labelUList & mapping)
Definition at line 33 of file foamVtkMeshMaps.C.
References Foam::inplaceRenumber().
The documentation for this class was generated from the following files:
src/fileFormats/vtk/part/foamVtkMeshMaps.H
src/fileFormats/vtk/part/foamVtkMeshMaps.C
src/fileFormats/vtk/part/foamVtkMeshMapsI.H