OpenFOAM: ReactingHeterogeneousCloud< CloudType > Class Template Reference
ReactingHeterogeneousCloud< CloudType > Class Template Reference
Lagrangian particle models » Clouds
Templated base class for reacting heterogeneous cloud.
#include <ReactingHeterogeneousCloud.H>
Public Types
typedef CloudType cloudType
typedef CloudType::particleType parcelType
typedef ReactingHeterogeneousCloud< CloudType > reactingHeterogeneousCloudType
Public Types inherited from DSMCCloud< ParcelType >
typedef ParcelType parcelType
Public Types inherited from Cloud< ParcelType >
typedef ParcelType particleType
typedef ParcelType parcelType
Public Types inherited from cloud
enum class geometryType { COORDINATES , POSITIONS }
Public Types inherited from IOobject
enum objectState : char { GOOD , BAD }
enum fileCheckTypes : char { timeStamp , timeStampMaster , inotify , inotifyMaster }
Public Types inherited from IOobjectOption
enum readOption : unsigned char {
NO_READ = 0 , MUST_READ = 0x1 , READ_MODIFIED = 0x3 , MUST_READ_IF_MODIFIED = 0x3 ,
LAZY_READ = 0x4 , READ_IF_PRESENT = 0x4
}
enum writeOption : unsigned char { NO_WRITE = 0 , AUTO_WRITE = 0x10 }
enum registerOption : unsigned char { NO_REGISTER = 0 , REGISTER = 1 }
Public Types inherited from HashTable< regIOobject * >
typedef HashTable< regIOobject *, word, Foam::Hash< word > > this_type
typedef std::conditional< std::is_same< Foam::zero, typenamestd::remove_cv< regIOobject * >::type >::value, Detail::HashTableSingle< word >, Detail::HashTablePair< word, regIOobject * > >::type node_type
typedef word key_type
typedef regIOobject * mapped_type
typedef regIOobject * value_type
typedef Foam::Hash< word > hasher
typedef regIOobject * * pointer
typedef regIOobject * & reference
typedef const regIOobject * * const_pointer
typedef const regIOobject * & const_reference
typedef label difference_type
typedef label size_type
using key_iterator = key_iterator_base< iterator >
using const_key_iterator = key_iterator_base< const_iterator >
Public Types inherited from UILList< LListBase, T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef label size_type
typedef label difference_type
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Public Member Functions
ReactingHeterogeneousCloud (const word &cloudName, const volScalarField &rho, const volVectorField &U, const dimensionedVector &g, const SLGThermo &thermo, bool readFields=true)
ReactingHeterogeneousCloud (ReactingHeterogeneousCloud< CloudType > &c, const word &name)
ReactingHeterogeneousCloud (const fvMesh &mesh, const word &name, const ReactingHeterogeneousCloud< CloudType > &c)
virtual autoPtr< Cloud< parcelType > > clone (const word &name)
virtual autoPtr< Cloud< parcelType > > cloneBare (const word &name) const
virtual ~ReactingHeterogeneousCloud ()=default
const ReactingHeterogeneousCloud & cloudCopy () const
label nF () const
const HeterogeneousReactingModel< ReactingHeterogeneousCloud< CloudType > > & heterogeneousReaction () const
HeterogeneousReactingModel< ReactingHeterogeneousCloud< CloudType > > & heterogeneousReaction ()
void setParcelThermoProperties (parcelType &parcel, const scalar lagrangianDt)
void checkParcelProperties (parcelType &parcel, const scalar lagrangianDt, const bool fullyDescribed)
void storeState ()
void restoreState ()
void evolve ()
virtual void autoMap (const mapPolyMesh &)
void info ()
virtual void readObjects (const objectRegistry &obr)
virtual void writeFields () const
virtual void writeObjects (objectRegistry &obr) const
Public Member Functions inherited from DSMCCloud< ParcelType >
DSMCCloud (const word &cloudName, const fvMesh &mesh, bool readFields=true)
DSMCCloud (const word &cloudName, const fvMesh &mesh, const IOdictionary &dsmcInitialiseDict)
virtual ~DSMCCloud ()
const word & cloudName () const
const fvMesh & mesh () const
const IOdictionary & particleProperties () const
const List< word > & typeIdList () const
scalar nParticle () const
const List< DynamicList< ParcelType * > > & cellOccupancy () const
volScalarField & sigmaTcRMax ()
scalarField & collisionSelectionRemainder ()
const List< typename ParcelType::constantProperties > & constProps () const
const ParcelType::constantProperties & constProps (label typeId) const
Random & rndGen ()
volScalarField::Boundary & qBF ()
volVectorField::Boundary & fDBF ()
volScalarField::Boundary & rhoNBF ()
volScalarField::Boundary & rhoMBF ()
volScalarField::Boundary & linearKEBF ()
volScalarField::Boundary & internalEBF ()
volScalarField::Boundary & iDofBF ()
volVectorField::Boundary & momentumBF ()
const volScalarField & boundaryT () const
const volVectorField & boundaryU () const
const volScalarField & q () const
const volVectorField & fD () const
const volScalarField & rhoN () const
const volScalarField & rhoM () const
const volScalarField & dsmcRhoN () const
const volScalarField & linearKE () const
const volScalarField & internalE () const
const volScalarField & iDof () const
const volVectorField & momentum () const
vector equipartitionLinearVelocity (scalar temperature, scalar mass)
scalar equipartitionInternalEnergy (scalar temperature, direction internalDegreesOfFreedom)
scalar maxwellianAverageSpeed (scalar temperature, scalar mass) const
scalarField maxwellianAverageSpeed (scalarField temperature, scalar mass) const
scalar maxwellianRMSSpeed (scalar temperature, scalar mass) const
scalarField maxwellianRMSSpeed (scalarField temperature, scalar mass) const
scalar maxwellianMostProbableSpeed (scalar temperature, scalar mass) const
scalarField maxwellianMostProbableSpeed (scalarField temperature, scalar mass) const
const BinaryCollisionModel< DSMCCloud< ParcelType > > & binaryCollision () const
BinaryCollisionModel< DSMCCloud< ParcelType > > & binaryCollision ()
const WallInteractionModel< DSMCCloud< ParcelType > > & wallInteraction () const
WallInteractionModel< DSMCCloud< ParcelType > > & wallInteraction ()
const InflowBoundaryModel< DSMCCloud< ParcelType > > & inflowBoundary () const
InflowBoundaryModel< DSMCCloud< ParcelType > > & inflowBoundary ()
scalar massInSystem () const
vector linearMomentumOfSystem () const
scalar linearKineticEnergyOfSystem () const
scalar internalEnergyOfSystem () const
void info () const
void dumpParticlePositions () const
void addNewParcel (const vector &position, const label celli, const vector &U, const scalar Ei, const label typeId)
void evolve ()
void clear ()
Public Member Functions inherited from Cloud< ParcelType >
TypeName ("Cloud")
Cloud (const polyMesh &mesh, const word &cloudName, const IDLList< ParcelType > &particles)
Cloud (const polyMesh &pMesh, const word &cloudName, const bool checkClass=true)
const polyMesh & pMesh () const
virtual label nParcels () const
DynamicList< label > & labels () const
void addParticle (ParcelType *pPtr)
void deleteParticle (ParcelType &p)
void deleteLostParticles ()
void cloudReset (const Cloud< ParcelType > &c)
void move (TrackCloudType &cloud, typename ParticleType::trackingData &td, const scalar trackTime)
IOobject fieldIOobject (const word &fieldName, IOobjectOption::readOption rOpt=IOobjectOption::NO_READ) const
void checkFieldIOobject (const Cloud< ParcelType > &c, const IOField< DataType > &data) const
void checkFieldFieldIOobject (const Cloud< ParcelType > &c, const CompactIOField< Field< DataType >, DataType > &data) const
bool readStoreFile (const IOobject &io, const IOobject &ioNew) const
void readFromFiles (objectRegistry &obr, const wordRes &selectFields, const wordRes &excludeFields=wordRes::null()) const
virtual bool writeObject (IOstreamOption streamOpt, const bool writeOnProc) const
void writePositions () const
void storeGlobalPositions () const
Public Member Functions inherited from cloud
TypeName ("cloud")
cloud (const objectRegistry &obr)
cloud (const objectRegistry &obr, const word &cloudName)
virtual ~cloud ()=default
template<class Type >
Foam::IOField< Type > & createIOField (const word &fieldName, const label nParticle, objectRegistry &obr)
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
objectRegistry (const Time &db, const label nObjects=128)
objectRegistry (const IOobject &io, const label nObjects=128)
virtual ~objectRegistry ()
const objectRegistry & thisDb () const noexcept
const objectRegistry & parent () const noexcept
const Time & time () const noexcept
bool isTimeDb () const noexcept
virtual const fileName & dbDir () const
HashTable< wordHashSet > classes () const
template<class MatchPredicate >
HashTable< wordHashSet > classes (const MatchPredicate &matchName) const
UPtrList< const regIOobject > csorted () const
UPtrList< const regIOobject > sorted () const
UPtrList< regIOobject > sorted ()
template<class Type >
UPtrList< const Type > csorted () const
template<class Type >
UPtrList< const Type > sorted () const
template<class Type >
UPtrList< Type > sorted ()
template<class Type , class MatchPredicate >
UPtrList< const Type > csorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
UPtrList< const Type > sorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
UPtrList< Type > sorted (const MatchPredicate &matchName)
label count (const char *clsName) const
template<class MatchPredicate >
label count (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
label count (const bool strict=false) const
template<class Type , class MatchPredicate >
label count (const MatchPredicate &matchName) const
wordList names () const
wordList names (const char *clsName) const
template<class MatchPredicate >
wordList names (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
wordList names () const
template<class Type , class MatchPredicate >
wordList names (const MatchPredicate &matchName) const
wordList sortedNames () const
wordList sortedNames (const char *clsName) const
template<class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
wordList sortedNames () const
template<class Type , class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchName) const
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false, const bool recursive=false) const
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
const regIOobject * cfindIOobject (const word &name, const bool recursive=false) const
bool contains (const word &name, const bool recursive=false) const
template<class Type >
bool foundObject (const word &name, const bool recursive=false) const
template<class Type >
const Type * cfindObject (const word &name, const bool recursive=false) const
template<class Type >
const Type * findObject (const word &name, const bool recursive=false) const
template<class Type >
Type * findObject (const word &name, const bool recursive=false)
template<class Type >
Type * getObjectPtr (const word &name, const bool recursive=false) const
template<class Type >
const Type & lookupObject (const word &name, const bool recursive=false) const
template<class Type >
Type & lookupObjectRef (const word &name, const bool recursive=false) const
label getEvent () const
bool checkIn (regIOobject *io) const
bool checkIn (regIOobject &io) const
bool checkOut (regIOobject *io) const
bool checkOut (regIOobject &io) const
bool checkOut (const word &key) const
void clear ()
void clearStorage ()
bool erase (const iterator &iter)
bool erase (const word &key)
label erase (std::initializer_list< word > keys)
label erase (const UList< word > &keys)
virtual void rename (const word &newName)
bool cacheTemporaryObject (const word &name) const
template<class Type >
bool cacheTemporaryObject (Type &obj) const
void resetCacheTemporaryObject (const regIOobject *io) const
void resetCacheTemporaryObject (const regIOobject &io) const
bool checkCacheTemporaryObjects () const
virtual bool modified () const
void readModifiedObjects ()
virtual bool readIfModified ()
virtual bool writeData (Ostream &) const
bool found (const word &name, bool recursive=false) const
template<class Type >
const Type * lookupObjectPtr (const word &name, bool recursive=false) const
template<class Type >
Type * lookupObjectRefPtr (const word &name, bool recursive=false) const
template<class MatchPredicate >
Foam::HashTable< Foam::wordHashSet > classesImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label countImpl (const objectRegistry &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName)
template<class Type , class MatchPredicate >
Foam::label countTypeImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList namesImpl (const objectRegistry &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool doSort)
template<class Type , class MatchPredicate >
Foam::wordList namesTypeImpl (const objectRegistry &list, const MatchPredicate &matchName, const bool doSort)
template<class Type , class MatchPredicate >
Foam::UPtrList< Type > objectsTypeImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate >
Foam::HashTable< Foam::wordHashSet > classes (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::label count (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type , class MatchPredicate >
Foam::label count (const MatchPredicate &matchName) const
template<class Type >
Foam::label count (const bool strict) const
template<class Type >
Foam::UPtrList< const Type > csorted () const
template<class Type >
Foam::UPtrList< const Type > sorted () const
template<class Type >
Foam::UPtrList< Type > sorted ()
template<class Type , class MatchPredicate >
Foam::UPtrList< const Type > csorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
Foam::UPtrList< const Type > sorted (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
Foam::UPtrList< Type > sorted (const MatchPredicate &matchName)
template<class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
Foam::wordList names () const
template<class Type , class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
Foam::wordList sortedNames () const
template<class Type , class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchName) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
regIOobject (const IOobject &io, const bool isTimeObject=false)
regIOobject (const regIOobject &rio)
regIOobject (const regIOobject &rio, bool registerCopy)
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
regIOobject (const IOobject &io, const regIOobject &rio)
virtual ~regIOobject ()
bool checkIn ()
bool checkOut ()
virtual void addWatch ()
bool registered () const noexcept
bool ownedByRegistry () const noexcept
bool store ()
void release (const bool unregister=false) noexcept
label eventNo () const noexcept
label & eventNo () noexcept
bool upToDate (const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
void setUpToDate ()
const dictionary * findMetaData () const noexcept
dictionary & getMetaData () noexcept
void removeMetaData ()
virtual void updateMetaData ()
virtual fileName filePath () const
bool headerOk ()
Istream & readStream (const word &, const bool readOnProc=true)
void close ()
virtual bool readData (Istream &)
virtual bool read ()
virtual label addWatch (const fileName &)
const labelList & watchIndices () const noexcept
labelList & watchIndices () noexcept
virtual bool write (const bool writeOnProc=true) const
virtual bool global () const
void operator= (const IOobject &io)
virtual bool writeObject (IOstreamOption::streamFormat fmt, IOstreamOption::versionNumber ver, IOstreamOption::compressionType cmp, const bool writeOnProc) const
Public Member Functions inherited from IOobject
TypeName ("IOobject")
IOobject (const IOobject &)=default
virtual ~IOobject ()=default
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption ioOpt=IOobjectOption())
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const fileName &path, const objectRegistry &registry, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt=IOobjectOption::NO_WRITE, bool registerObject=true, bool globalObject=false)
IOobject (const IOobject &io, const objectRegistry &registry)
IOobject (const IOobject &io, const word &name)
IOobject (const IOobject &io, const word &name, const fileName &local)
IOobject (const IOobject &io, IOobjectOption::readOption rOpt, IOobjectOption::writeOption wOpt)
IOobject (const IOobject &io, IOobjectOption::registerOption regOpt)
autoPtr< IOobject > clone () const
autoPtr< IOobject > clone (const objectRegistry &registry) const
const objectRegistry & db () const noexcept
const Time & time () const noexcept
const word & name () const noexcept
const word & headerClassName () const noexcept
word & headerClassName () noexcept
const string & note () const noexcept
string & note () noexcept
unsigned labelByteSize () const noexcept
unsigned scalarByteSize () const noexcept
void resetHeader (const word &newName=word::null)
bool hasHeaderClass () const noexcept
template<class Type >
bool isHeaderClass () const
template<class Type >
bool isHeaderClassName () const
word group () const
word member () const
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const noexcept
fileName & instance () noexcept
const fileName & local () const noexcept
fileName path () const
fileName path (const word &instance, const fileName &local=fileName::null) const
fileName objectPath () const
fileName objectRelPath () const
fileName localFilePath (const word &typeName, const bool search=true) const
fileName globalFilePath (const word &typeName, const bool search=true) const
IOstreamOption parseHeader (const dictionary &headerDict)
bool readHeader (Istream &is)
bool readHeader (dictionary &headerDict, Istream &is)
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
template<class Type >
void warnNoRereading () const
bool writeHeader (Ostream &os) const
bool writeHeader (Ostream &os, const word &objectType) const
void writeHeader (dictionary &dict, IOstreamOption streamOpt) const
void writeHeader (dictionary &dict, const word &objectType, IOstreamOption streamOpt) const
bool good () const noexcept
bool bad () const noexcept
InfoProxy< IOobject > info () const noexcept
void operator= (const IOobject &io)
template<>
bool isHeaderClass () const
template<class StringType >
Foam::word groupName (StringType base, const word &group)
Public Member Functions inherited from IOobjectOption
constexpr IOobjectOption (readOption rOpt=readOption::NO_READ, writeOption wOpt=writeOption::NO_WRITE, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (writeOption wOpt, registerOption registerObject=registerOption::REGISTER, bool globalObject=false) noexcept
constexpr IOobjectOption (registerOption registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (readOption rOpt, writeOption wOpt, bool registerObject, bool globalObject=false) noexcept
constexpr IOobjectOption (bool registerObject, bool globalObject=false) noexcept
readOption readOpt () const noexcept
readOption readOpt (readOption opt) noexcept
writeOption writeOpt () const noexcept
writeOption writeOpt (writeOption opt) noexcept
bool registerObject () const noexcept
bool registerObject (bool on) noexcept
bool globalObject () const noexcept
bool globalObject (bool on) noexcept
bool isAnyRead () const noexcept
bool isReadRequired () const noexcept
bool isReadOptional () const noexcept
readOption & readOpt () noexcept
writeOption & writeOpt () noexcept
bool & registerObject () noexcept
bool & globalObject () noexcept
Public Member Functions inherited from HashTable< regIOobject * >
HashTable ()
HashTable (const label size)
HashTable (Istream &is, const label size=128)
HashTable (const this_type &ht)
HashTable (this_type &&rhs)
HashTable (std::initializer_list< std::pair< word, regIOobject * > > list)
~HashTable ()
bool empty () const noexcept
label size () const noexcept
label capacity () const noexcept
regIOobject * & at (const word &key)
const regIOobject * & at (const word &key) const
bool contains (const word &key) const
iterator find (const word &key)
const_iterator find (const word &key) const
const_iterator cfind (const word &key) const
const regIOobject * & lookup (const word &key, const regIOobject * &deflt) const
List< word > toc () const
List< word > sortedToc () const
List< word > sortedToc (const Compare &comp) const
Foam::List< word > sortedToc (const Compare &comp) const
List< word > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
Foam::List< word > tocKeys (const UnaryPredicate &pred, const bool invert) const
List< word > tocValues (const UnaryPredicate &pred, const bool invert=false) const
Foam::List< word > tocValues (const UnaryPredicate &pred, const bool invert) const
List< word > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
Foam::List< word > tocEntries (const BinaryPredicate &pred, const bool invert) const
UPtrList< const node_type > csorted () const
UPtrList< const node_type > sorted () const
UPtrList< node_type > sorted ()
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
Foam::label countKeys (const UnaryPredicate &pred, const bool invert) const
label countValues (const UnaryPredicate &pred, const bool invert=false) const
Foam::label countValues (const UnaryPredicate &pred, const bool invert) const
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
Foam::label countEntries (const BinaryPredicate &pred, const bool invert) const
bool emplace (const word &key, Args &&... args)
bool emplace_set (const word &key, Args &&... args)
bool insert (const word &key, const regIOobject * &obj)
bool insert (const word &key, regIOobject * &&obj)
bool set (const word &key, const regIOobject * &obj)
bool set (const word &key, regIOobject * &&obj)
bool erase (const iterator &iter)
bool erase (const word &key)
label erase (const HashTable< AnyType, word, AnyHash > &other)
label erase (std::initializer_list< word > keys)
label erase (InputIter first, InputIter last)
label erase (const FixedList< word, N > &keys)
label erase (const UList< word > &keys)
Foam::label erase (InputIter first, InputIter last)
Foam::label erase (const FixedList< word, N > &keys)
Foam::label erase (const HashTable< AnyType, word, AnyHash > &other)
label retain (const HashTable< AnyType, word, AnyHash > &other)
Foam::label retain (const HashTable< AnyType, word, AnyHash > &other)
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
Foam::label filterKeys (const UnaryPredicate &pred, const bool pruning)
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
Foam::label filterValues (const UnaryPredicate &pred, const bool pruning)
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
Foam::label filterEntries (const BinaryPredicate &pred, const bool pruning)
void resize (const label sz)
void clear ()
void clearStorage ()
void swap (HashTable< regIOobject *, word, Foam::Hash< word > > &rhs)
void transfer (HashTable< regIOobject *, word, Foam::Hash< word > > &rhs)
void merge (HashTable< regIOobject *, word, Foam::Hash< word > > &source)
void merge (HashTable< regIOobject *, word, Foam::Hash< word > > &&source)
regIOobject * & operator[] (const word &key)
const regIOobject * & operator[] (const word &key) const
regIOobject * & operator() (const word &key)
regIOobject * & operator() (const word &key, const regIOobject * &deflt)
void operator= (const this_type &rhs)
void operator= (std::initializer_list< std::pair< word, regIOobject * > > rhs)
void operator= (this_type &&rhs)
bool operator== (const this_type &rhs) const
bool operator!= (const this_type &rhs) const
this_type & operator+= (const this_type &rhs)
const_iterator_pair< const_key_iterator, this_type > keys () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end () noexcept
const_iterator end () const noexcept
constexpr const_iterator cend () const noexcept
Ostream & printInfo (Ostream &os) const
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
bool found (const word &key) const
Public Member Functions inherited from HashTableCore
ClassName ("HashTable")
HashTableCore () noexcept=default
Public Member Functions inherited from ILList< LListBase, T >
ILList ()=default
ILList (T *item)
ILList (Istream &is)
ILList (const ILList< LListBase, T > &lst)
ILList (ILList< LListBase, T > &&lst)
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
template<class INew >
ILList (Istream &is, const INew &inew)
~ILList ()
void clear ()
void pop_front (label n=1)
bool erase (T *item)
void transfer (ILList< LListBase, T > &lst)
void operator= (const ILList< LListBase, T > &lst)
void operator= (ILList< LListBase, T > &&lst)
Public Member Functions inherited from UILList< LListBase, T >
UILList ()=default
UILList (T *item)
UILList (const UILList< LListBase, T > &list)
T * front ()
const T * front () const
T * back ()
const T * back () const
T * removeHead ()
T * remove (T *item)
T * remove (iterator &iter)
void operator= (const UILList< LListBase, T > &lst)
bool operator== (const UILList< LListBase, T > &lst) const
bool operator!= (const UILList< LListBase, T > &lst) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
iterator begin ()
const_iterator cbegin () const
reverse_iterator rbegin ()
const_reverse_iterator crbegin () const
const_iterator begin () const
const_reverse_iterator rbegin () const
const iterator & end ()
const const_iterator & cend () const
const reverse_iterator & rend ()
const const_reverse_iterator & crend () const
const const_iterator & end () const
const const_reverse_iterator & rend () const
T * first ()
const T * first () const
T * last ()
const T * last () const
Public Member Functions inherited from DSMCBaseCloud
TypeName ("DSMCBaseCloud")
DSMCBaseCloud ()=default
virtual ~DSMCBaseCloud ()=default
Public Member Functions inherited from reactingHeterogeneousCloud
TypeName ("reactingHeterogeneousCloud")
reactingHeterogeneousCloud ()=default
virtual ~reactingHeterogeneousCloud ()=default
Protected Member Functions
void setModels ()
void cloudReset (ReactingHeterogeneousCloud< CloudType > &c)
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstreamOption::streamFormat fmt, const word &typeName)
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Protected Attributes
autoPtr< HeterogeneousReactingModel< ReactingHeterogeneousCloud< CloudType > > > heterogeneousReactionModel_
Protected Attributes inherited from Cloud< ParcelType >
cloud::geometryType geometryType_
Additional Inherited Members
Static Public Member Functions inherited from cloud
template<class Type >
static IOField< Type > & createIOField (const word &fieldName, const label nParticle, objectRegistry &obr)
template<class Type >
static const IOField< Type > * findIOField (const word &fieldName, const objectRegistry &obr)
static const IOField< point > * findIOPosition (const objectRegistry &obr)
template<class Type >
static const IOField< Type > & lookupIOField (const word &fieldName, const objectRegistry &obr)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
template<class Type >
static Type & store (autoPtr< Type > &ptr)
template<class Type >
static Type & store (autoPtr< Type > &&ptr)
template<class Type >
static Type & store (refPtr< Type > &ptr)
template<class Type >
static Type & store (refPtr< Type > &&ptr)
template<class Type >
static Type & store (tmp< Type > &ptr)
template<class Type >
static Type & store (tmp< Type > &&ptr)
Static Public Member Functions inherited from IOobject
static bool bannerEnabled () noexcept
static bool bannerEnabled (bool on) noexcept
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
template<class StringType >
static word groupName (StringType base, const word &group)
static word group (const word &name)
static word member (const word &name)
static word scopedName (const std::string &scope, const word &name)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
static Ostream & writeBanner (Ostream &os, const bool noSyntaxHint=false)
static Ostream & writeDivider (Ostream &os)
static Ostream & writeEndDivider (Ostream &os)
Static Public Member Functions inherited from IOobjectOption
static bool isAnyRead (readOption opt) noexcept
static bool isReadRequired (readOption opt) noexcept
static bool isReadOptional (readOption opt) noexcept
static readOption lazierRead (readOption opt) noexcept
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Static Public Attributes inherited from Cloud< ParcelType >
static word cloudPropertiesName
Static Public Attributes inherited from cloud
static const Enum< geometryType > geometryTypeNames
static const word prefix
static word defaultName
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
static char scopeSeparator
static fileCheckTypes fileModificationChecking
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Static Protected Member Functions inherited from IOobject
static void writeHeaderContent (Ostream &os, const IOobject &io, const word &objectType, const dictionary *metaDataDict=nullptr)
static void writeHeaderContent (dictionary &dict, const IOobject &io, const word &objectType, IOstreamOption streamOpt, const dictionary *metaDataDict=nullptr)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
Detailed Description
template<class CloudType>
class Foam::ReactingHeterogeneousCloud< CloudType >
Templated base class for reacting heterogeneous cloud.
Adds to reacting cloud:
Heterogeneous reaction model
Source files
ReactingHeterogeneousCloud.H
ReactingHeterogeneousCloudI.H
ReactingHeterogeneousCloud.C
Definition at line 59 of file ReactingHeterogeneousCloud.H.
Member Typedef Documentation
cloudType
template<class CloudType > typedef CloudType cloudType
Definition at line 69 of file ReactingHeterogeneousCloud.H.
parcelType
template<class CloudType > typedef CloudType::particleType parcelType
Definition at line 72 of file ReactingHeterogeneousCloud.H.
reactingHeterogeneousCloudType
template<class CloudType > typedef ReactingHeterogeneousCloud<CloudType> reactingHeterogeneousCloudType
Definition at line 76 of file ReactingHeterogeneousCloud.H.
Constructor & Destructor Documentation
ReactingHeterogeneousCloud() [1/3]
template<class CloudType > ReactingHeterogeneousCloud (const word & cloudName, const volScalarField & rho, const volVectorField & U, const dimensionedVector & g, const SLGThermo & thermo, bool readFields = true)
Definition at line 54 of file ReactingHeterogeneousCloud.C.
References composition, Cloud< ParcelType >::deleteLostParticles(), Foam::readFields(), and ReactingHeterogeneousCloud< CloudType >::setModels().
ReactingHeterogeneousCloud() [2/3]
template<class CloudType > ReactingHeterogeneousCloud (ReactingHeterogeneousCloud< CloudType > & c, const word & name)
Definition at line 83 of file ReactingHeterogeneousCloud.C.
ReactingHeterogeneousCloud() [3/3]
template<class CloudType > ReactingHeterogeneousCloud (const fvMesh & mesh, const word & name, const ReactingHeterogeneousCloud< CloudType > & c)
Definition at line 97 of file ReactingHeterogeneousCloud.C.
~ReactingHeterogeneousCloud()
template<class CloudType > virtual ~ReactingHeterogeneousCloud () virtual default
Member Function Documentation
setModels()
template<class CloudType > void setModels () protected
Definition at line 27 of file ReactingHeterogeneousCloud.C.
References Foam::New().
Referenced by ReactingHeterogeneousCloud< CloudType >::ReactingHeterogeneousCloud().
cloudReset()
template<class CloudType > void cloudReset (ReactingHeterogeneousCloud< CloudType > & c) protected
Definition at line 41 of file ReactingHeterogeneousCloud.C.
References Cloud< ParcelType >::cloudReset().
clone()
template<class CloudType > virtual autoPtr< Cloud< parcelType > > clone (const word & name) inline virtual
Definition at line 156 of file ReactingHeterogeneousCloud.H.
References IOobject::name().
cloneBare()
template<class CloudType > virtual autoPtr< Cloud< parcelType > > cloneBare (const word & name) const inline virtual
Definition at line 165 of file ReactingHeterogeneousCloud.H.
References DSMCCloud< ParcelType >::mesh().
cloudCopy()
template<class CloudType > const Foam::ReactingHeterogeneousCloud< CloudType > & cloudCopy () const inline
Definition at line 25 of file ReactingHeterogeneousCloudI.H.
nF()
template<class CloudType > Foam::label nF () const inline
Definition at line 50 of file ReactingHeterogeneousCloudI.H.
heterogeneousReaction() [1/2]
template<class CloudType > const Foam::HeterogeneousReactingModel< Foam::ReactingHeterogeneousCloud< CloudType > > & heterogeneousReaction () const inline
Definition at line 34 of file ReactingHeterogeneousCloudI.H.
heterogeneousReaction() [2/2]
template<class CloudType > Foam::HeterogeneousReactingModel< Foam::ReactingHeterogeneousCloud< CloudType > > & heterogeneousReaction () inline
Definition at line 43 of file ReactingHeterogeneousCloudI.H.
setParcelThermoProperties()
template<class CloudType > void setParcelThermoProperties (parcelType & parcel, const scalar lagrangianDt)
Definition at line 114 of file ReactingHeterogeneousCloud.C.
checkParcelProperties()
template<class CloudType > void checkParcelProperties (parcelType & parcel, const scalar lagrangianDt, const bool fullyDescribed)
Definition at line 155 of file ReactingHeterogeneousCloud.C.
References Foam::abort(), composition, Foam::FatalError, FatalErrorInFunction, and Foam::nl.
storeState()
template<class CloudType > void storeState ()
Definition at line 195 of file ReactingHeterogeneousCloud.C.
References Foam::name().
restoreState()
template<class CloudType > void restoreState ()
Definition at line 208 of file ReactingHeterogeneousCloud.C.
evolve()
template<class CloudType > void evolve ()
Definition at line 216 of file ReactingHeterogeneousCloud.C.
autoMap()
template<class CloudType > void autoMap (const mapPolyMesh & mapper) virtual
Reimplemented from DSMCCloud< ParcelType >.
Definition at line 228 of file ReactingHeterogeneousCloud.C.
References Cloud< ParticleType >::autoMap().
info()
template<class CloudType > void info ()
Definition at line 240 of file ReactingHeterogeneousCloud.C.
readObjects()
template<class CloudType > void readObjects (const objectRegistry & obr) virtual
Reimplemented from cloud.
Definition at line 256 of file ReactingHeterogeneousCloud.C.
References composition, and cloud::readObjects().
writeFields()
template<class CloudType > void writeFields () const virtual
Reimplemented from Cloud< ParcelType >.
Definition at line 249 of file ReactingHeterogeneousCloud.C.
writeObjects()
template<class CloudType > void writeObjects (objectRegistry & obr) const virtual
Reimplemented from cloud.
Definition at line 264 of file ReactingHeterogeneousCloud.C.
References composition, and cloud::writeObjects().
Member Data Documentation
heterogeneousReactionModel_
template<class CloudType > autoPtr< HeterogeneousReactingModel < ReactingHeterogeneousCloud<CloudType> > > heterogeneousReactionModel_ protected
Definition at line 109 of file ReactingHeterogeneousCloud.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/ReactingHeterogeneousCloud/ReactingHeterogeneousCloud.H
src/lagrangian/intermediate/clouds/Templates/ReactingHeterogeneousCloud/ReactingHeterogeneousCloud.C
src/lagrangian/intermediate/clouds/Templates/ReactingHeterogeneousCloud/ReactingHeterogeneousCloudI.H