OpenFOAM: linear Class Reference
linear Class Reference
#include <linear.H>
Public Member Functions
TypeName ("linear")
linear (const dictionary &dict, const wordList &phaseNames)
~linear ()=default
virtual tmp< volScalarField > f1 (const phaseModel &phase1, const phaseModel &phase2) const
virtual tmp< volScalarField > f2 (const phaseModel &phase1, const phaseModel &phase2) const
TypeName ("linear")
linear (const dictionary &dict, const wordList &phaseNames)
~linear ()=default
virtual tmp< volScalarField > f1 (const phaseModel &phase1, const phaseModel &phase2) const
virtual tmp< volScalarField > f2 (const phaseModel &phase1, const phaseModel &phase2) const
Public Member Functions inherited from blendingMethod
TypeName ("blendingMethod")
declareRunTimeSelectionTable (autoPtr, blendingMethod, dictionary,(const dictionary &dict, const wordList &phaseNames),(dict, phaseNames))
blendingMethod (const dictionary &dict)
virtual ~blendingMethod ()=default
TypeName ("blendingMethod")
declareRunTimeSelectionTable (autoPtr, blendingMethod, dictionary,(const dictionary &dict, const wordList &phaseNames),(dict, phaseNames))
blendingMethod (const dictionary &dict)
virtual ~blendingMethod ()=default
Additional Inherited Members
Static Public Member Functions inherited from blendingMethod
static autoPtr< blendingMethod > New (const word &modelName, const dictionary &dict, const wordList &phaseNames)
static autoPtr< blendingMethod > New (const dictionary &dict, const wordList &phaseNames)
Detailed Description
Source files
linear.H
linear.C
Definition at line 47 of file linear.H.
Constructor & Destructor Documentation
linear() [1/2]
linear (const dictionary & dict, const wordList & phaseNames)
Definition at line 43 of file linear.C.
References dict, Foam::dimless, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and IOobject::groupName().
~linear() [1/2]
~linear () default
linear() [2/2]
linear (const dictionary & dict, const wordList & phaseNames)
~linear() [2/2]
~linear () default
Member Function Documentation
TypeName() [1/2]
TypeName ("linear")
f1() [1/2]
Foam::tmp< Foam::volScalarField > f1 (const phaseModel & phase1, const phaseModel & phase2) const virtual
Implements blendingMethod.
Definition at line 93 of file linear.C.
References Foam::max(), Foam::min(), and phase2.
f2() [1/2]
Foam::tmp< Foam::volScalarField > f2 (const phaseModel & phase1, const phaseModel & phase2) const virtual
Implements blendingMethod.
Definition at line 118 of file linear.C.
References Foam::max(), Foam::min(), and phase1.
TypeName() [2/2]
TypeName ("linear")
f1() [2/2]
virtual tmp< volScalarField > f1 (const phaseModel & phase1, const phaseModel & phase2) const virtual
Implements blendingMethod.
f2() [2/2]
virtual tmp< volScalarField > f2 (const phaseModel & phase1, const phaseModel & phase2) const virtual
Implements blendingMethod.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/BlendedInterfacialModel/blendingMethods/linear/linear.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/BlendedInterfacialModel/blendingMethods/linear/linear.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/BlendedInterfacialModel/blendingMethods/linear/linear.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/BlendedInterfacialModel/blendingMethods/linear/linear.C