OpenFOAM: averageNeighbourFvGeometryScheme Class Reference
averageNeighbourFvGeometryScheme Class Reference
Geometry calculation scheme to minimise non-orthogonality/.
#include <averageNeighbourFvGeometryScheme.H>
Public Member Functions
TypeName ("averageNeighbour")
averageNeighbourFvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~averageNeighbourFvGeometryScheme ()=default
virtual void movePoints ()
Public Member Functions inherited from highAspectRatioFvGeometryScheme
TypeName ("highAspectRatio")
highAspectRatioFvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~highAspectRatioFvGeometryScheme ()=default
Public Member Functions inherited from basicFvGeometryScheme
TypeName ("basic")
basicFvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~basicFvGeometryScheme ()=default
virtual tmp< surfaceScalarField > weights () const
virtual tmp< surfaceScalarField > deltaCoeffs () const
virtual tmp< surfaceScalarField > nonOrthDeltaCoeffs () const
virtual tmp< surfaceVectorField > nonOrthCorrectionVectors () const
Public Member Functions inherited from fvGeometryScheme
TypeName ("fvGeometryScheme")
declareRunTimeSelectionTable (tmp, fvGeometryScheme, dict,(const fvMesh &mesh, const dictionary &dict),(mesh, dict))
fvGeometryScheme (const fvMesh &mesh, const dictionary &dict)
virtual ~fvGeometryScheme ()=default
const fvMesh & mesh () const
virtual void updateMesh (const mapPolyMesh &mpm)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Protected Member Functions
label clipFaceTet (const scalar minRatio, const vectorField &faceCentres, const vectorField &faceNormals, vectorField &faceCorrection) const
void makePyrHeights (const pointField &cellCentres, const vectorField &faceCentres, const vectorField &faceNormals, scalarField &ownHeight, scalarField &neiHeight) const
label clipPyramids (const pointField &cellCentres, const vectorField &faceCentres, const vectorField &faceNormals, const scalarField &minOwnHeight, const scalarField &minNeiHeight, vectorField &correction) const
tmp< pointField > averageNeighbourCentres (const pointField &cellCentres, const vectorField &faceNormals, const scalarField &faceWeights) const
tmp< pointField > averageCentres (const pointField &cellCentres, const pointField &faceCentres, const vectorField &faceNormals) const
void makeNonOrthoWeights (const pointField &cellCentres, const vectorField &faceNormals, scalarField &cosAngles, scalarField &faceWeights) const
Protected Member Functions inherited from highAspectRatioFvGeometryScheme
void calcAspectRatioWeights (scalarField &cellWeight, scalarField &faceWeight) const
Protected Member Functions inherited from fvGeometryScheme
bool setMeshPhi () const
Protected Attributes
const label nIters_
const scalar relax_
const scalar minRatio_
Protected Attributes inherited from highAspectRatioFvGeometryScheme
const scalar minAspect_
const scalar maxAspect_
Protected Attributes inherited from fvGeometryScheme
const fvMesh & mesh_
Additional Inherited Members
Static Public Member Functions inherited from fvGeometryScheme
static tmp< fvGeometryScheme > New (const fvMesh &mesh, const dictionary &dict, const word &defaultScheme)
Static Protected Member Functions inherited from highAspectRatioFvGeometryScheme
static void makeAverageCentres (const polyMesh &mesh, const pointField &points, const pointField &faceAreas, const scalarField &magFaceAreas, pointField &faceCentres, pointField &cellCentres)
Detailed Description
Geometry calculation scheme to minimise non-orthogonality/.
Source files
averageNeighbourFvGeometryScheme.H
averageNeighbourFvGeometryScheme.C
Definition at line 48 of file averageNeighbourFvGeometryScheme.H.
Constructor & Destructor Documentation
averageNeighbourFvGeometryScheme()
averageNeighbourFvGeometryScheme (const fvMesh & mesh, const dictionary & dict)
Definition at line 544 of file averageNeighbourFvGeometryScheme.C.
~averageNeighbourFvGeometryScheme()
virtual ~averageNeighbourFvGeometryScheme () virtual default
Member Function Documentation
clipFaceTet()
Foam::label clipFaceTet (const scalar minRatio, const vectorField & faceCentres, const vectorField & faceNormals, vectorField & faceCorrection) const protected
Definition at line 47 of file averageNeighbourFvGeometryScheme.C.
References f(), forAll, Foam::mag(), fvGeometryScheme::mesh_, n, nCorr, p, Foam::returnReduce(), and VectorSpace< Form, Cmpt, Ncmpts >::zero.
makePyrHeights()
void makePyrHeights (const pointField & cellCentres, const vectorField & faceCentres, const vectorField & faceNormals, scalarField & ownHeight, scalarField & neiHeight) const protected
Definition at line 123 of file averageNeighbourFvGeometryScheme.C.
References n, and PtrList< T >::setSize().
clipPyramids()
Foam::label clipPyramids (const pointField & cellCentres, const vectorField & faceCentres, const vectorField & faceNormals, const scalarField & minOwnHeight, const scalarField & minNeiHeight, vectorField & correction) const protected
Definition at line 161 of file averageNeighbourFvGeometryScheme.C.
References Foam::correction(), n, Foam::returnReduce(), and VectorSpace< Form, Cmpt, Ncmpts >::zero.
averageNeighbourCentres()
Foam::tmp< Foam::pointField > averageNeighbourCentres (const pointField & cellCentres, const vectorField & faceNormals, const scalarField & faceWeights) const protected
Definition at line 257 of file averageNeighbourFvGeometryScheme.C.
References forAll, n, pbm, pp(), syncTools::swapBoundaryCellPositions(), and Foam::Zero.
averageCentres()
Foam::tmp< Foam::pointField > averageCentres (const pointField & cellCentres, const pointField & faceCentres, const vectorField & faceNormals) const protected
Definition at line 366 of file averageNeighbourFvGeometryScheme.C.
References f(), forAll, n, pbm, pp(), and syncTools::swapBoundaryCellPositions().
makeNonOrthoWeights()
void makeNonOrthoWeights (const pointField & cellCentres, const vectorField & faceNormals, scalarField & cosAngles, scalarField & faceWeights) const protected
Definition at line 499 of file averageNeighbourFvGeometryScheme.C.
References Foam::clamp(), Foam::cos(), Foam::degToRad(), polyMeshTools::faceOrthogonality(), forAll, List< T >::setSize(), and UPtrList< T >::size().
TypeName()
TypeName ("averageNeighbour")
movePoints()
void movePoints () virtual
Reimplemented from highAspectRatioFvGeometryScheme.
Definition at line 593 of file averageNeighbourFvGeometryScheme.C.
References Foam::acos(), fileName::clean(), Foam::correction(), Foam::cos(), Foam::degToRad(), Foam::endl(), polyMeshTools::faceOrthogonality(), forAll, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::mag(), Foam::min(), Foam::mkDir(), highAspectRatioFvGeometryScheme::movePoints(), OFstream::name(), surfaceWriter::New(), functionObject::outputPrefix, Foam::Pout, Foam::radToDeg(), primitiveMesh::resetGeometry(), and OBJstream::writeLine().
Member Data Documentation
nIters_
const label nIters_ protected
Definition at line 67 of file averageNeighbourFvGeometryScheme.H.
relax_
const scalar relax_ protected
Definition at line 70 of file averageNeighbourFvGeometryScheme.H.
minRatio_
const scalar minRatio_ protected
Definition at line 74 of file averageNeighbourFvGeometryScheme.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvGeometryScheme/averageNeighbour/averageNeighbourFvGeometryScheme.H
src/finiteVolume/fvMesh/fvGeometryScheme/averageNeighbour/averageNeighbourFvGeometryScheme.C