OpenFOAM: nutkWallFunctionFvPatchScalarField Class Reference
nutkWallFunctionFvPatchScalarField Class Reference
Turbulence models » Boundary conditions » Wall functions
This boundary condition provides a wall function for the turbulent viscosity (i.e. nut) based on the turbulent kinetic energy, (i.e. k) for for low- and high-Reynolds number applications.
#include <nutkWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("nutkWallFunction")
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual tmp< scalarField > yPlus () const
virtual void write (Ostream &) const
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
const wallFunctionCoefficients & wallCoeffs () const noexcept
virtual void updateCoeffs ()
Protected Member Functions
virtual tmp< scalarField > calcNut () const
void writeLocalEntries (Ostream &) const
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual const volVectorField & U (const turbulenceModel &turb) const
virtual void checkType ()
void writeLocalEntries (Ostream &) const
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static const nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel &turbModel, const label patchi)
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
word UName_
wallFunctionCoefficients wallCoeffs_
Detailed Description
This boundary condition provides a wall function for the turbulent viscosity (i.e. nut) based on the turbulent kinetic energy, (i.e. k) for for low- and high-Reynolds number applications.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            nutkWallFunction;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: nutkWallFunction word yes -
The inherited entries are elaborated in:
nutWallFunctionFvPatchScalarField.H
wallFunctionBlenders.H
Source files
nutkWallFunctionFvPatchScalarField.H
nutkWallFunctionFvPatchScalarField.C
Definition at line 88 of file nutkWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutkWallFunctionFvPatchScalarField() [1/5]
nutkWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 147 of file nutkWallFunctionFvPatchScalarField.C.
nutkWallFunctionFvPatchScalarField() [2/5]
nutkWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 171 of file nutkWallFunctionFvPatchScalarField.C.
nutkWallFunctionFvPatchScalarField() [3/5]
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 158 of file nutkWallFunctionFvPatchScalarField.C.
nutkWallFunctionFvPatchScalarField() [4/5]
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField & wfpsf)
Definition at line 183 of file nutkWallFunctionFvPatchScalarField.C.
nutkWallFunctionFvPatchScalarField() [5/5]
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 193 of file nutkWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcNut()
Foam::tmp< Foam::scalarField > calcNut () const protected virtual
Implements nutWallFunctionFvPatchScalarField.
Reimplemented in atmNutkWallFunctionFvPatchScalarField, atmNutWallFunctionFvPatchScalarField, nutkFilmWallFunctionFvPatchScalarField, and nutkRoughWallFunctionFvPatchScalarField.
Definition at line 31 of file nutkWallFunctionFvPatchScalarField.C.
References wallFunctionBlenders::blender_, wallFunctionCoefficients::Cmu(), e, wallFunctionCoefficients::E(), Foam::exp(), forAll, IOobject::groupName(), k, wallFunctionCoefficients::kappa(), Foam::log(), Foam::max(), wallFunctionBlenders::n_, tmp< T >::New(), nutWallFunctionFvPatchScalarField::nutw(), Foam::pow(), Foam::pow025(), Foam::pow4(), turbulenceModel::propertiesName, Foam::sqrt(), Foam::tanh(), nutWallFunctionFvPatchScalarField::wallCoeffs_, y, nutkWallFunctionFvPatchScalarField::yPlus(), wallFunctionCoefficients::yPlusLam(), and Foam::Zero.
writeLocalEntries()
void writeLocalEntries (Ostream & os) const protected
Definition at line 136 of file nutkWallFunctionFvPatchScalarField.C.
References os(), and wallFunctionBlenders::writeEntries().
TypeName()
TypeName ("nutkWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Reimplemented in atmNutkWallFunctionFvPatchScalarField, atmNutWallFunctionFvPatchScalarField, nutkFilmWallFunctionFvPatchScalarField, and nutkRoughWallFunctionFvPatchScalarField.
Definition at line 145 of file nutkWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Reimplemented in atmNutkWallFunctionFvPatchScalarField, atmNutWallFunctionFvPatchScalarField, nutkFilmWallFunctionFvPatchScalarField, and nutkRoughWallFunctionFvPatchScalarField.
Definition at line 161 of file nutkWallFunctionFvPatchScalarField.H.
yPlus()
Foam::tmp< Foam::scalarField > yPlus () const virtual
Implements nutWallFunctionFvPatchScalarField.
Reimplemented in nutkFilmWallFunctionFvPatchScalarField.
Definition at line 206 of file nutkWallFunctionFvPatchScalarField.C.
References forAll, IOobject::groupName(), k, Foam::mag(), tmp< T >::New(), Foam::pow025(), turbulenceModel::propertiesName, fvPatchField< Type >::snGrad(), Foam::sqrt(), U, y, yPlus, and Foam::Zero.
Referenced by atmNutkWallFunctionFvPatchScalarField::calcNut(), and nutkWallFunctionFvPatchScalarField::calcNut().
write()
void write (Ostream & os) const virtual
Reimplemented from nutWallFunctionFvPatchScalarField.
Reimplemented in atmNutkWallFunctionFvPatchScalarField, atmNutWallFunctionFvPatchScalarField, nutkRoughWallFunctionFvPatchScalarField, and nutkFilmWallFunctionFvPatchScalarField.
Definition at line 259 of file nutkWallFunctionFvPatchScalarField.C.
References os(), nutWallFunctionFvPatchScalarField::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutkWallFunction/nutkWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutkWallFunction/nutkWallFunctionFvPatchScalarField.C