OpenFOAM: gaussConvectionScheme< Type > Class Template Reference
gaussConvectionScheme< Type > Class Template Reference
Numerics » Finite volume numerical schemes » Convection schemes
Basic second-order convection using face-gradients and Gauss' theorem.
#include <gaussConvectionScheme.H>
Public Member Functions
TypeName ("Gauss")
gaussConvectionScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux, const tmp< surfaceInterpolationScheme< Type > > &scheme)
gaussConvectionScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
const surfaceInterpolationScheme< Type > & interpScheme () const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< fvMatrix< Type > > fvmDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
Public Member Functions inherited from convectionScheme< Type >
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, convectionScheme, Istream,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
declareRunTimeSelectionTable (tmp, convectionScheme, Multivariate,(const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, fields, faceFlux, schemeData))
convectionScheme (const convectionScheme &)
convectionScheme (const fvMesh &mesh, const surfaceScalarField &)
virtual ~convectionScheme ()
const fvMesh & mesh () const
void operator= (const convectionScheme< Type > &)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from convectionScheme< Type >
static tmp< convectionScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
static tmp< convectionScheme< Type > > New (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Detailed Description
template<class Type>
class Foam::fv::gaussConvectionScheme< Type >
Basic second-order convection using face-gradients and Gauss' theorem.
Source files
gaussConvectionScheme.H
gaussConvectionScheme.C
Definition at line 55 of file gaussConvectionScheme.H.
Constructor & Destructor Documentation
gaussConvectionScheme() [1/2]
template<class Type > gaussConvectionScheme (const fvMesh & mesh, const surfaceScalarField & faceFlux, const tmp< surfaceInterpolationScheme< Type > > & scheme) inline
Definition at line 82 of file gaussConvectionScheme.H.
gaussConvectionScheme() [2/2]
template<class Type > gaussConvectionScheme (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Definition at line 94 of file gaussConvectionScheme.H.
Member Function Documentation
TypeName()
template<class Type > TypeName ("Gauss")
interpScheme()
template<class Type > const surfaceInterpolationScheme< Type > & interpScheme () const
Definition at line 39 of file gaussConvectionScheme.C.
interpolate()
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const surfaceScalarField & , const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 47 of file gaussConvectionScheme.C.
flux()
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 59 of file gaussConvectionScheme.C.
References Foam::interpolate().
fvmDiv()
template<class Type > tmp< fvMatrix< Type > > fvmDiv (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 71 of file gaussConvectionScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::correction(), forAll, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and Foam::fvc::surfaceIntegrate().
fvcDiv()
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDiv (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 115 of file gaussConvectionScheme.C.
References Foam::fvc::surfaceIntegrate().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/convectionSchemes/gaussConvectionScheme/gaussConvectionScheme.H
src/finiteVolume/finiteVolume/convectionSchemes/gaussConvectionScheme/gaussConvectionScheme.C