OpenFOAM: restraint Class Reference
restraint Class Reference abstract
Base class for defining restraints for rigid-body dynamics.
#include <rigidBodyRestraint.H>
Public Member Functions
TypeName ("restraint")
declareRunTimeSelectionTable (autoPtr, restraint, dictionary,(const word &name, const dictionary &dict, const rigidBodyModel &model),(name, dict, model))
restraint (const word &name, const dictionary &dict, const rigidBodyModel &model)
virtual autoPtr< restraint > clone () const =0
virtual ~restraint ()
const word & name () const
label bodyID () const
virtual void restrain (scalarField &tau, Field< spatialVector > &fx, const rigidBodyModelState &state) const =0
virtual bool read (const dictionary &dict)
const dictionary & coeffDict () const
virtual void write (Ostream &) const =0
Static Public Member Functions
static autoPtr< restraint > New (const word &name, const dictionary &dict, const rigidBodyModel &model)
Protected Member Functions
point bodyPoint (const point &p) const
spatialVector bodyPointVelocity (const point &p) const
Protected Attributes
word name_
label bodyID_
label bodyIndex_
dictionary coeffs_
const rigidBodyModel & model_
Detailed Description
Base class for defining restraints for rigid-body dynamics.
Source files
rigidBodyRestraint.H
rigidBodyRestraint.C
rigidBodyRestraintNew.C
Definition at line 65 of file rigidBodyRestraint.H.
Constructor & Destructor Documentation
restraint()
restraint (const word & name, const dictionary & dict, const rigidBodyModel & model)
Definition at line 38 of file rigidBodyRestraint.C.
References Foam::name().
~restraint()
~restraint () virtual
Definition at line 55 of file rigidBodyRestraint.C.
Member Function Documentation
bodyPoint()
Foam::point bodyPoint (const point & p) const inline protected
Definition at line 25 of file rigidBodyRestraintI.H.
References restraint::bodyID_, restraint::model_, p, and Foam::Zero.
bodyPointVelocity()
Foam::spatialVector bodyPointVelocity (const point & p) const inline protected
Definition at line 34 of file rigidBodyRestraintI.H.
References p.
TypeName()
TypeName ("restraint")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , restraint , dictionary , (const word &name, const dictionary &dict, const rigidBodyModel &model) , (name, dict, model))
clone()
virtual autoPtr< restraint > clone () const pure virtual
Implemented in externalForce, linearAxialAngularSpring, linearDamper, linearSpring, prescribedRotation, softWall, and sphericalAngularDamper.
New()
Foam::autoPtr< Foam::RBD::restraint > New (const word & name, const dictionary & dict, const rigidBodyModel & model) static
Definition at line 27 of file rigidBodyRestraintNew.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and restraint::name().
name()
const word & name () const inline
Definition at line 149 of file rigidBodyRestraint.H.
References restraint::name_.
Referenced by restraint::New().
bodyID()
label bodyID () const inline
Definition at line 154 of file rigidBodyRestraint.H.
References restraint::bodyID_.
restrain()
virtual void restrain (scalarField & tau, Field< spatialVector > & fx, const rigidBodyModelState & state) const pure virtual
Implemented in externalForce, linearAxialAngularSpring, linearDamper, linearSpring, prescribedRotation, softWall, and sphericalAngularDamper.
read()
bool read (const dictionary & dict) virtual
Reimplemented in externalForce, linearAxialAngularSpring, linearDamper, linearSpring, prescribedRotation, softWall, and sphericalAngularDamper.
Definition at line 67 of file rigidBodyRestraint.C.
References dict.
Referenced by externalForce::read(), linearAxialAngularSpring::read(), linearDamper::read(), linearSpring::read(), prescribedRotation::read(), softWall::read(), and sphericalAngularDamper::read().
coeffDict()
const Foam::dictionary & coeffDict () const
Definition at line 61 of file rigidBodyRestraint.C.
write()
void write (Ostream & os) const pure virtual
Implemented in externalForce, linearAxialAngularSpring, linearDamper, linearSpring, prescribedRotation, softWall, and sphericalAngularDamper.
Definition at line 74 of file rigidBodyRestraint.C.
References os(), and Foam::type().
Referenced by externalForce::write(), linearAxialAngularSpring::write(), linearDamper::write(), linearSpring::write(), prescribedRotation::write(), softWall::write(), and sphericalAngularDamper::write().
Member Data Documentation
name_
word name_ protected
Definition at line 73 of file rigidBodyRestraint.H.
Referenced by restraint::name().
bodyID_
label bodyID_ protected
Definition at line 76 of file rigidBodyRestraint.H.
Referenced by restraint::bodyID(), and restraint::bodyPoint().
bodyIndex_
label bodyIndex_ protected
Definition at line 79 of file rigidBodyRestraint.H.
coeffs_
dictionary coeffs_ protected
Definition at line 82 of file rigidBodyRestraint.H.
model_
const rigidBodyModel& model_ protected
Definition at line 85 of file rigidBodyRestraint.H.
Referenced by restraint::bodyPoint().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/restraints/restraint/rigidBodyRestraint.H
src/rigidBodyDynamics/restraints/restraint/rigidBodyRestraint.C
src/rigidBodyDynamics/restraints/restraint/rigidBodyRestraintI.H
src/rigidBodyDynamics/restraints/restraint/rigidBodyRestraintNew.C