OpenFOAM: alphatFilmWallFunctionFvPatchScalarField Class Reference
alphatFilmWallFunctionFvPatchScalarField Class Reference
Boundary conditions » Region boundary conditions » Surface film boundary conditions | Turbulence models » Compressible turbulence » Boundary conditions » Wall functions
This boundary condition provides a turbulent thermal diffusivity condition when using wall functions, for use with surface film models. This condition varies from the standard wall function by taking into account any mass released from the film model.
#include <alphatFilmWallFunctionFvPatchScalarField.H>
Public Member Functions
TypeName ("alphatFilmWallFunction")
alphatFilmWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
alphatFilmWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
alphatFilmWallFunctionFvPatchScalarField (const alphatFilmWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
alphatFilmWallFunctionFvPatchScalarField (const alphatFilmWallFunctionFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
alphatFilmWallFunctionFvPatchScalarField (const alphatFilmWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Protected Attributes
word filmRegionName_
scalar B_
scalar yPlusCrit_
scalar Cmu_
scalar kappa_
scalar Prt_
Detailed Description
This boundary condition provides a turbulent thermal diffusivity condition when using wall functions, for use with surface film models. This condition varies from the standard wall function by taking into account any mass released from the film model.
Usage
Example of the boundary condition specification:
<patchName>
{
    // Mandatory entries
    type            alphatFilmWallFunction;
    // Optional entries
    filmRegion      <word>;
    B               <scalar>;
    yPlusCrit       <scalar>;
    Cmu             <scalar>;
    kappa           <scalar>;
    Prt             <scalar>;
    // Inherited entries
    ...
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: alphatFilmWallFunction word yes -
filmRegion Name of film region word no surfaceFilmProperties
B Model coefficient scalar no 5.5
yPlusCrit Critical y+ for transition to turbulence scalar no 11.5
Cmu Empirical model coefficient scalar no 0.09
Prt Turbulent Prandtl number scalar no 0.85
kappa von Karman constant scalar no 0.41
The inherited entries are elaborated in:
fixedValueFvPatchFields.H
Source files
alphatFilmWallFunctionFvPatchScalarField.H
alphatFilmWallFunctionFvPatchScalarField.C
Definition at line 141 of file alphatFilmWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
alphatFilmWallFunctionFvPatchScalarField() [1/5]
alphatFilmWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 42 of file alphatFilmWallFunctionFvPatchScalarField.C.
alphatFilmWallFunctionFvPatchScalarField() [2/5]
alphatFilmWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 78 of file alphatFilmWallFunctionFvPatchScalarField.C.
alphatFilmWallFunctionFvPatchScalarField() [3/5]
alphatFilmWallFunctionFvPatchScalarField (const alphatFilmWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 59 of file alphatFilmWallFunctionFvPatchScalarField.C.
alphatFilmWallFunctionFvPatchScalarField() [4/5]
alphatFilmWallFunctionFvPatchScalarField (const alphatFilmWallFunctionFvPatchScalarField & fwfpsf)
Definition at line 99 of file alphatFilmWallFunctionFvPatchScalarField.C.
alphatFilmWallFunctionFvPatchScalarField() [5/5]
alphatFilmWallFunctionFvPatchScalarField (const alphatFilmWallFunctionFvPatchScalarField & fwfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 115 of file alphatFilmWallFunctionFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("alphatFilmWallFunction")
clone() [1/2]
virtual tmp< fvPatchScalarField > clone () const inline virtual
Definition at line 209 of file alphatFilmWallFunctionFvPatchScalarField.H.
clone() [2/2]
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 225 of file alphatFilmWallFunctionFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 134 of file alphatFilmWallFunctionFvPatchScalarField.C.
References alphaEff(), alphatFilmWallFunctionFvPatchScalarField::Cmu_, Foam::exp(), alphatFilmWallFunctionFvPatchScalarField::filmRegionName_, forAll, IOobject::groupName(), k, alphatFilmWallFunctionFvPatchScalarField::kappa_, Foam::max(), Foam::min(), UPstream::msgType(), Foam::pow(), Foam::pow025(), Pr(), turbulenceModel::propertiesName, alphatFilmWallFunctionFvPatchScalarField::Prt_, Foam::sqrt(), uTau, y, yPlus, and alphatFilmWallFunctionFvPatchScalarField::yPlusCrit_.
write()
void write (Ostream & os) const virtual
Definition at line 239 of file alphatFilmWallFunctionFvPatchScalarField.C.
References alphatFilmWallFunctionFvPatchScalarField::B_, alphatFilmWallFunctionFvPatchScalarField::Cmu_, alphatFilmWallFunctionFvPatchScalarField::filmRegionName_, alphatFilmWallFunctionFvPatchScalarField::kappa_, os(), alphatFilmWallFunctionFvPatchScalarField::Prt_, fvPatchField< Type >::write(), fvPatchField< Type >::writeValueEntry(), and alphatFilmWallFunctionFvPatchScalarField::yPlusCrit_.
Member Data Documentation
filmRegionName_
word filmRegionName_ protected
Definition at line 150 of file alphatFilmWallFunctionFvPatchScalarField.H.
Referenced by alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatFilmWallFunctionFvPatchScalarField::write().
B_
scalar B_ protected
Definition at line 153 of file alphatFilmWallFunctionFvPatchScalarField.H.
Referenced by alphatFilmWallFunctionFvPatchScalarField::write().
yPlusCrit_
scalar yPlusCrit_ protected
Definition at line 156 of file alphatFilmWallFunctionFvPatchScalarField.H.
Referenced by alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatFilmWallFunctionFvPatchScalarField::write().
Cmu_
scalar Cmu_ protected
Definition at line 159 of file alphatFilmWallFunctionFvPatchScalarField.H.
Referenced by alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatFilmWallFunctionFvPatchScalarField::write().
kappa_
scalar kappa_ protected
Definition at line 162 of file alphatFilmWallFunctionFvPatchScalarField.H.
Referenced by alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatFilmWallFunctionFvPatchScalarField::write().
Prt_
scalar Prt_ protected
Definition at line 165 of file alphatFilmWallFunctionFvPatchScalarField.H.
Referenced by alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatFilmWallFunctionFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/derivedFvPatchFields/wallFunctions/alphatFilmWallFunction/alphatFilmWallFunctionFvPatchScalarField.H
src/regionModels/surfaceFilmModels/derivedFvPatchFields/wallFunctions/alphatFilmWallFunction/alphatFilmWallFunctionFvPatchScalarField.C