OpenFOAM: kOmegaSSTSAS< BasicTurbulenceModel > Class Template Reference
kOmegaSSTSAS< BasicTurbulenceModel > Class Template Reference
Turbulence models » LES turbulence
Scale-adaptive URAS model based on the k-omega-SST RAS model.
#include <kOmegaSSTSAS.H>
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kOmegaSST< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >
typedef BasicEddyViscosityModel::alphaField alphaField
typedef BasicEddyViscosityModel::rhoField rhoField
typedef BasicEddyViscosityModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kOmegaSSTSAS")
kOmegaSSTSAS (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~kOmegaSSTSAS ()=default
virtual bool read ()
const volScalarField & delta () const
Public Member Functions inherited from kOmegaSST< BasicTurbulenceModel >
TypeName ("kOmegaSST")
kOmegaSST (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~kOmegaSST ()=default
Public Member Functions inherited from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >
kOmegaSSTBase (const kOmegaSSTBase &)=delete
kOmegaSSTBase (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
void operator= (const kOmegaSSTBase &)=delete
virtual ~kOmegaSSTBase ()=default
tmp< volScalarField > DkEff (const volScalarField &F1) const
tmp< volScalarField > DomegaEff (const volScalarField &F1) const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > omega () const
virtual void correct ()
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~eddyViscosity ()=default
virtual tmp< volScalarField > nut () const
virtual tmp< scalarField > nut (const label patchi) const
virtual tmp< volSymmTensorField > R () const
virtual void validate ()
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
virtual ~linearViscousStress ()=default
virtual tmp< volSymmTensorField > devRhoReff () const
virtual tmp< volSymmTensorField > devRhoReff (const volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Protected Member Functions
virtual tmp< fvScalarMatrix > Qsas (const volScalarField::Internal &S2, const volScalarField::Internal &gamma, const volScalarField::Internal &beta) const
Protected Member Functions inherited from kOmegaSST< BasicTurbulenceModel >
virtual void correctNut (const volScalarField &S2)
virtual void correctNut ()
Protected Member Functions inherited from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >
void setDecayControl (const dictionary &dict)
virtual tmp< volScalarField > F1 (const volScalarField &CDkOmega) const
virtual tmp< volScalarField > F2 () const
virtual tmp< volScalarField > F3 () const
virtual tmp< volScalarField > F23 () const
tmp< volScalarField > blend (const volScalarField &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField::Internal > blend (const volScalarField::Internal &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField > alphaK (const volScalarField &F1) const
tmp< volScalarField > alphaOmega (const volScalarField &F1) const
tmp< volScalarField::Internal > beta (const volScalarField::Internal &F1) const
tmp< volScalarField::Internal > gamma (const volScalarField::Internal &F1) const
virtual tmp< volScalarField > S2 (const volTensorField &gradU) const
virtual tmp< volScalarField::Internal > Pk (const volScalarField::Internal &G) const
virtual tmp< volScalarField::Internal > epsilonByk (const volScalarField &F1, const volTensorField &gradU) const
virtual tmp< volScalarField::Internal > GbyNu0 (const volTensorField &gradU, const volScalarField &S2) const
virtual tmp< volScalarField::Internal > GbyNu (const volScalarField::Internal &GbyNu0, const volScalarField::Internal &F2, const volScalarField::Internal &S2) const
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > omegaSource () const
Protected Attributes
dimensionedScalar Cs_
dimensionedScalar kappa_
dimensionedScalar zeta2_
dimensionedScalar sigmaPhi_
dimensionedScalar C_
autoPtr< Foam::LESdelta > delta_
Protected Attributes inherited from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >
dimensionedScalar alphaK1_
dimensionedScalar alphaK2_
dimensionedScalar alphaOmega1_
dimensionedScalar alphaOmega2_
dimensionedScalar gamma1_
dimensionedScalar gamma2_
dimensionedScalar beta1_
dimensionedScalar beta2_
dimensionedScalar betaStar_
dimensionedScalar a1_
dimensionedScalar b1_
dimensionedScalar c1_
Switch F3_
const volScalarField & y_
volScalarField k_
volScalarField omega_
Switch decayControl_
dimensionedScalar kInf_
dimensionedScalar omegaInf_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::kOmegaSSTSAS< BasicTurbulenceModel >
Scale-adaptive URAS model based on the k-omega-SST RAS model.
References:
    Egorov, Y., & Menter F.R. (2008).
    Development and Application of SST-SAS Model in the DESIDER Project.
    Advances in Hybrid RANS-LES Modelling,
    Notes on Num. Fluid Mech. And Multidisciplinary Design,
    Volume 97, 261-270.
The model coefficients are
    kOmegaSSTSASCoeffs
    {
        // Default SST coefficients
        alphaK1     0.85;
        alphaK2     1.0;
        alphaOmega1 0.5;
        alphaOmega2 0.856;
        beta1       0.075;
        beta2       0.0828;
        betaStar    0.09;
        gamma1      5/9;
        gamma2      0.44;
        a1          0.31;
        b1          1.0;
        c1          10.0;
        F3          no;
        // Default SAS coefficients
        Cs          0.11;
        kappa       0.41;
        zeta2       3.51;
        sigmaPhi    2.0/3.0;
        C           2;
        // Delta must be specified for SAS e.g.
        delta cubeRootVol;
        cubeRootVolCoeffs
        {}
    }
Source files
kOmegaSSTSAS.H
kOmegaSSTSAS.C
Definition at line 97 of file kOmegaSSTSAS.H.
Member Typedef Documentation
alphaField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 142 of file kOmegaSSTSAS.H.
rhoField
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 143 of file kOmegaSSTSAS.H.
transportModel
template<class BasicTurbulenceModel > typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 144 of file kOmegaSSTSAS.H.
Constructor & Destructor Documentation
kOmegaSSTSAS()
template<class BasicTurbulenceModel > kOmegaSSTSAS (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 92 of file kOmegaSSTSAS.C.
References kOmegaSST< BasicTurbulenceModel >::correctNut(), and Foam::type().
~kOmegaSSTSAS()
template<class BasicTurbulenceModel > virtual ~kOmegaSSTSAS () virtual default
Member Function Documentation
Qsas()
template<class BasicTurbulenceModel > tmp< fvScalarMatrix > Qsas (const volScalarField::Internal & S2, const volScalarField::Internal & gamma, const volScalarField::Internal & beta) const protected virtual
Reimplemented from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >.
Definition at line 34 of file kOmegaSSTSAS.C.
References beta(), delta, gamma, Foam::fvc::grad(), L, Foam::fvc::laplacian(), Foam::mag(), Foam::magSqr(), Foam::max(), Foam::min(), Foam::pow025(), Foam::sqr(), Foam::sqrt(), Foam::fvm::Su(), and Foam::Zero.
TypeName()
template<class BasicTurbulenceModel > TypeName ("kOmegaSSTSAS< BasicTurbulenceModel >")
read()
template<class BasicTurbulenceModel > bool read () virtual
Reimplemented from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >.
Definition at line 183 of file kOmegaSSTSAS.C.
delta()
template<class BasicTurbulenceModel > const volScalarField & delta () const inline
Definition at line 177 of file kOmegaSSTSAS.H.
References kOmegaSSTSAS< BasicTurbulenceModel >::delta_.
Member Data Documentation
Cs_
template<class BasicTurbulenceModel > dimensionedScalar Cs_ protected
Definition at line 116 of file kOmegaSSTSAS.H.
kappa_
template<class BasicTurbulenceModel > dimensionedScalar kappa_ protected
Definition at line 117 of file kOmegaSSTSAS.H.
zeta2_
template<class BasicTurbulenceModel > dimensionedScalar zeta2_ protected
Definition at line 118 of file kOmegaSSTSAS.H.
sigmaPhi_
template<class BasicTurbulenceModel > dimensionedScalar sigmaPhi_ protected
Definition at line 119 of file kOmegaSSTSAS.H.
C_
template<class BasicTurbulenceModel > dimensionedScalar C_ protected
Definition at line 120 of file kOmegaSSTSAS.H.
delta_
template<class BasicTurbulenceModel > autoPtr<Foam::LESdelta> delta_ protected
Definition at line 126 of file kOmegaSSTSAS.H.
Referenced by kOmegaSSTSAS< BasicTurbulenceModel >::delta().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/kOmegaSSTSAS/kOmegaSSTSAS.H
src/TurbulenceModels/turbulenceModels/RAS/kOmegaSSTSAS/kOmegaSSTSAS.C