OpenFOAM: collector Class Reference
collector Class Reference
Implementation of template-invariant tools for various function objects such as Foam::ParticleHistogram.
#include <cloudFunctionObjectTools.H>
Public Member Functions
collector (const dictionary &dict, const polyMesh &mesh)
collector (const collector &phc)
void operator= (const collector &)=delete
virtual ~collector ()=default
bool isPatch () const noexcept
label size () const noexcept
const labelList & IDs () const noexcept
const wordList & names () const noexcept
const List< boundBox > & BBs () const noexcept
Detailed Description
Implementation of template-invariant tools for various function objects such as Foam::ParticleHistogram.
Source files
cloudFunctionObjectTools.H
cloudFunctionObjectTools.C
Definition at line 55 of file cloudFunctionObjectTools.H.
Constructor & Destructor Documentation
collector() [1/2]
collector (const dictionary & dict, const polyMesh & mesh)
Definition at line 25 of file cloudFunctionObjectTools.C.
References dict, UList< T >::empty(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::flatOutput(), mesh, Foam::nl, points, List< T >::resize(), PtrList< T >::resize(), and UList< T >::size().
collector() [2/2]
collector (const collector & phc)
Definition at line 94 of file cloudFunctionObjectTools.C.
~collector()
virtual ~collector () virtual default
Member Function Documentation
operator=()
void operator= (const collector &) delete
isPatch()
bool isPatch () const inline noexcept
Definition at line 99 of file cloudFunctionObjectTools.H.
size()
label size () const inline noexcept
Definition at line 102 of file cloudFunctionObjectTools.H.
References UList< T >::size().
Referenced by ParticleHistogram< CloudType >::ParticleHistogram(), and ParticlePostProcessing< CloudType >::ParticlePostProcessing().
IDs()
const labelList & IDs () const inline noexcept
Definition at line 105 of file cloudFunctionObjectTools.H.
names()
const wordList & names () const inline noexcept
Definition at line 108 of file cloudFunctionObjectTools.H.
BBs()
const List< boundBox > & BBs () const inline noexcept
Definition at line 111 of file cloudFunctionObjectTools.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/CloudFunctionObjects/CloudFunctionObject/cloudFunctionObjectTools.H
src/lagrangian/intermediate/submodels/CloudFunctionObjects/CloudFunctionObject/cloudFunctionObjectTools.C