OpenFOAM: refPtr< T > Class Template Reference
refPtr< T > Class Template Reference
A class for managing references or pointers (no reference counting)
#include <refPtr.H>
Public Types
typedef T element_type
typedef T * pointer
typedef Foam::refCount::zero refCount
Public Member Functions
constexpr refPtr () noexcept
constexpr refPtr (std::nullptr_t) noexcept
constexpr refPtr (T *p) noexcept
constexpr refPtr (const T &obj) noexcept
refPtr (refPtr< T > &&rhs) noexcept
refPtr (const refPtr< T > &rhs)
refPtr (const refPtr< T > &rhs, bool reuse)
refPtr (std::unique_ptr< T > &&rhs) noexcept
refPtr (const autoPtr< T > &)=delete
refPtr (autoPtr< T > &&rhs) noexcept
refPtr (const tmp< T > &rhs, bool reuse)
refPtr (const tmp< T > &rhs)
refPtr (tmp< T > &&rhs)
~refPtr () noexcept
bool good () const noexcept
bool is_const () const noexcept
bool is_pointer () const noexcept
bool is_reference () const noexcept
bool movable () const noexcept
T * get () noexcept
const T * get () const noexcept
const T & cref () const
T & ref () const
T & constCast () const
refPtr< T > shallowClone () const noexcept
T * release () noexcept
T * ptr () const
void clear () const noexcept
void reset (T *p=nullptr) noexcept
void reset (refPtr< T > &&other) noexcept
void reset (const autoPtr< T > &)=delete
void reset (autoPtr< T > &&other) noexcept
void reset (std::unique_ptr< T > &&other)
void reset (tmp< T > &rhs, bool reuse)
void cref (const refPtr< T > &other) noexcept
void cref (const T &obj) noexcept
void cref (const T *p) noexcept
void cref (const autoPtr< T > &)=delete
void cref (const tmp< T > &)=delete
void ref (T &obj) noexcept
void ref (T *p) noexcept
void ref (const autoPtr< T > &)=delete
void ref (const tmp< T > &)=delete
void swap (refPtr< T > &other) noexcept
const T & operator* () const
T & operator* ()
const T * operator-> () const
T * operator-> ()
const T & operator() () const
operator bool () const noexcept
operator const T & () const
void operator= (const refPtr< T > &other)
void operator= (refPtr< T > &&other) noexcept
void operator= (T *p)=delete
void operator= (std::nullptr_t) noexcept
void operator= (const autoPtr< T > &)=delete
void operator= (autoPtr< T > &&other) noexcept
void operator= (std::unique_ptr< T > &&other)
void operator= (const tmp< T > &)=delete
void operator= (tmp< T > &&other)
operator tmp< T > ()
bool valid () const noexcept
bool empty () const noexcept
Static Public Member Functions
template<class... Args>
static refPtr< T > New (Args &&... args)
template<class U , class... Args>
static refPtr< T > NewFrom (Args &&... args)
static word typeName ()
Detailed Description
template<class T>
class Foam::refPtr< T >
A class for managing references or pointers (no reference counting)
Source files
refPtr.H
refPtrI.H
See also
Foam::autoPtr Foam::tmp
Definition at line 53 of file refPtr.H.
Member Typedef Documentation
element_type
template<class T > typedef T element_type
Definition at line 78 of file refPtr.H.
pointer
template<class T > typedef T* pointer
Definition at line 81 of file refPtr.H.
refCount
template<class T > typedef Foam::refCount::zero refCount
Definition at line 85 of file refPtr.H.
Constructor & Destructor Documentation
refPtr() [1/13]
template<class T > constexpr refPtr () inline constexpr noexcept
Definition at line 37 of file refPtrI.H.
refPtr() [2/13]
template<class T > constexpr refPtr (std::nullptr_t) inline constexpr noexcept
Definition at line 45 of file refPtrI.H.
refPtr() [3/13]
template<class T > constexpr refPtr (T * p) inline explicit constexpr noexcept
Definition at line 53 of file refPtrI.H.
refPtr() [4/13]
template<class T > constexpr refPtr (const T & obj) inline constexpr noexcept
Definition at line 61 of file refPtrI.H.
refPtr() [5/13]
template<class T > refPtr (refPtr< T > && rhs) inline noexcept
Definition at line 69 of file refPtrI.H.
refPtr() [6/13]
template<class T > refPtr (const refPtr< T > & rhs) inline
Definition at line 80 of file refPtrI.H.
References refPtr< T >::is_pointer().
refPtr() [7/13]
template<class T > refPtr (const refPtr< T > & rhs, bool reuse) inline
Definition at line 103 of file refPtrI.H.
refPtr() [8/13]
template<class T > refPtr (std::unique_ptr< T > && rhs) inline explicit noexcept
Definition at line 134 of file refPtrI.H.
refPtr() [9/13]
template<class T > refPtr (const autoPtr< T > &) delete
refPtr() [10/13]
template<class T > refPtr (autoPtr< T > && rhs) inline explicit noexcept
Definition at line 141 of file refPtrI.H.
refPtr() [11/13]
template<class T > refPtr (const tmp< T > & rhs, bool reuse) inline
Definition at line 148 of file refPtrI.H.
References refPtr< T >::reset().
refPtr() [12/13]
template<class T > refPtr (const tmp< T > & rhs) inline explicit
Definition at line 157 of file refPtrI.H.
References refPtr< T >::reset().
refPtr() [13/13]
template<class T > refPtr (tmp< T > && rhs) inline explicit
Definition at line 166 of file refPtrI.H.
References refPtr< T >::reset().
~refPtr()
template<class T > ~refPtr () inline noexcept
Definition at line 177 of file refPtrI.H.
Member Function Documentation
New()
template<class T > template<class... Args> static refPtr< T > New (Args &&... args) inline static
Definition at line 144 of file refPtr.H.
References args, and T.
Referenced by AMIInterpolation::calculate(), RASModelVariables::cloneRefPtr(), fileOperation::lookupAndCacheProcessorsPath(), and blockMesh::topology().
NewFrom()
template<class T > template<class U , class... Args> static refPtr< T > NewFrom (Args &&... args) inline static
Definition at line 156 of file refPtr.H.
References args, and U.
typeName()
template<class T > Foam::word typeName () inline static
Definition at line 28 of file refPtrI.H.
References Foam::name(), and T.
good()
template<class T > bool good () const inline noexcept
Definition at line 171 of file refPtr.H.
Referenced by ConstPrecisionAdaptor< Type, InputType, Container >::active(), and PrecisionAdaptor< Type, InputType, Container >::active().
is_const()
template<class T > bool is_const () const inline noexcept
Definition at line 186 of file refPtrI.H.
is_pointer()
template<class T > bool is_pointer () const inline noexcept
Definition at line 193 of file refPtrI.H.
Referenced by ConstPrecisionAdaptor< Type, InputType, Container >::active(), PrecisionAdaptor< Type, InputType, Container >::active(), and refPtr< T >::refPtr().
is_reference()
template<class T > bool is_reference () const inline noexcept
Definition at line 201 of file refPtrI.H.
movable()
template<class T > bool movable () const inline noexcept
Definition at line 209 of file refPtrI.H.
get() [1/2]
template<class T > T * get () inline noexcept
Definition at line 189 of file refPtr.H.
get() [2/2]
template<class T > const T * get () const inline noexcept
Definition at line 192 of file refPtr.H.
cref() [1/6]
template<class T > const T & cref () const inline
Definition at line 216 of file refPtrI.H.
Referenced by PrecisionAdaptor< Type, InputType, Container >::commit(), refPtr< T >::constCast(), refPtr< Field< InputType > >::operator const Field< InputType > &(), and refPtr< T >::operator()().
ref() [1/5]
template<class T > T & ref () const inline
Definition at line 230 of file refPtrI.H.
constCast()
template<class T > T & constCast () const inline
Definition at line 207 of file refPtr.H.
References refPtr< T >::cref(), and T.
shallowClone()
template<class T > Foam::refPtr< T > shallowClone () const inline noexcept
Definition at line 251 of file refPtrI.H.
release()
template<class T > T * release () inline noexcept
Definition at line 266 of file refPtrI.H.
ptr()
template<class T > T * ptr () const inline
Definition at line 280 of file refPtrI.H.
clear()
template<class T > void clear () const inline noexcept
Definition at line 303 of file refPtrI.H.
Referenced by PrecisionAdaptor< Type, InputType, Container >::~PrecisionAdaptor().
reset() [1/6]
template<class T > void reset (T * p = nullptr) inline noexcept
Definition at line 314 of file refPtrI.H.
Referenced by refPtr< T >::operator=(), refPtr< T >::operator=(), refPtr< T >::operator=(), refPtr< T >::operator=(), refPtr< T >::refPtr(), refPtr< T >::refPtr(), and refPtr< T >::refPtr().
reset() [2/6]
template<class T > void reset (refPtr< T > && other) inline noexcept
Definition at line 323 of file refPtrI.H.
References clear().
reset() [3/6]
template<class T > void reset (const autoPtr< T > &) delete
reset() [4/6]
template<class T > void reset (autoPtr< T > && other) inline noexcept
Definition at line 239 of file refPtr.H.
References refPtr< T >::reset().
Referenced by refPtr< T >::reset().
reset() [5/6]
template<class T > void reset (std::unique_ptr< T > && other) inline
Definition at line 242 of file refPtr.H.
References refPtr< T >::reset().
Referenced by refPtr< T >::reset().
reset() [6/6]
template<class T > void reset (tmp< T > & rhs, bool reuse) inline
Definition at line 341 of file refPtrI.H.
cref() [2/6]
template<class T > void cref (const refPtr< T > & other) inline noexcept
Definition at line 368 of file refPtrI.H.
References clear().
cref() [3/6]
template<class T > void cref (const T & obj) inline noexcept
Definition at line 383 of file refPtrI.H.
References clear(), and T.
cref() [4/6]
template<class T > void cref (const T * p) inline noexcept
Definition at line 392 of file refPtrI.H.
References clear(), p, and T.
cref() [5/6]
template<class T > void cref (const autoPtr< T > &) delete
cref() [6/6]
template<class T > void cref (const tmp< T > &) delete
ref() [2/5]
template<class T > void ref (T & obj) inline noexcept
Definition at line 401 of file refPtrI.H.
References clear().
ref() [3/5]
template<class T > void ref (T * p) inline noexcept
Definition at line 410 of file refPtrI.H.
References clear(), and p.
ref() [4/5]
template<class T > void ref (const autoPtr< T > &) delete
ref() [5/5]
template<class T > void ref (const tmp< T > &) delete
swap()
template<class T > void swap (refPtr< T > & other) inline noexcept
Definition at line 419 of file refPtrI.H.
References p, and T.
operator*() [1/2]
template<class T > const T & operator* () const inline
Definition at line 436 of file refPtrI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator*() [2/2]
template<class T > T & operator* () inline
Definition at line 449 of file refPtrI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator->() [1/2]
template<class T > const T * operator-> () const inline
Definition at line 470 of file refPtrI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator->() [2/2]
template<class T > T * operator-> () inline
Definition at line 484 of file refPtrI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator()()
template<class T > const T & operator() () const inline
Definition at line 299 of file refPtr.H.
References refPtr< T >::cref().
operator bool()
template<class T > operator bool () const inline explicit noexcept
Definition at line 305 of file refPtr.H.
operator const T &()
template<class T > operator const T & () const inline
Definition at line 308 of file refPtr.H.
operator=() [1/9]
template<class T > void operator= (const refPtr< T > & other) inline
Definition at line 505 of file refPtrI.H.
References Foam::abort(), clear(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and T.
operator=() [2/9]
template<class T > void operator= (refPtr< T > && other) inline noexcept
Definition at line 318 of file refPtr.H.
References refPtr< T >::reset().
operator=() [3/9]
template<class T > void operator= (T * p) delete
operator=() [4/9]
template<class T > void operator= (std::nullptr_t) inline noexcept
Definition at line 324 of file refPtr.H.
References refPtr< T >::reset().
operator=() [5/9]
template<class T > void operator= (const autoPtr< T > &) delete
operator=() [6/9]
template<class T > void operator= (autoPtr< T > && other) inline noexcept
Definition at line 330 of file refPtr.H.
References refPtr< T >::reset().
operator=() [7/9]
template<class T > void operator= (std::unique_ptr< T > && other) inline
Definition at line 333 of file refPtr.H.
References refPtr< T >::reset().
operator=() [8/9]
template<class T > void operator= (const tmp< T > &) delete
operator=() [9/9]
template<class T > void operator= (tmp< T > && other) inline
Definition at line 542 of file refPtrI.H.
operator tmp< T >()
template<class T > operator tmp< T > () inline
Definition at line 549 of file refPtrI.H.
valid()
template<class T > bool valid () const inline noexcept
Definition at line 349 of file refPtr.H.
empty()
template<class T > bool empty () const inline noexcept
Definition at line 355 of file refPtr.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashPtrTable/HashPtrTable.H
src/OpenFOAM/memory/refPtr/refPtr.H
src/OpenFOAM/memory/refPtr/refPtrI.H