OpenFOAM: profileModel Class Reference
profileModel Class Reference abstract
Base class for profile models for handling aerofoil lift and drag polar diagrams.
#include <profileModel.H>
Public Member Functions
TypeName ("profileModel")
declareRunTimeSelectionTable (autoPtr, profileModel, dictionary,(const dictionary &dict, const word &modelName),(dict, modelName))
profileModel (const dictionary &dict, const word &modelName)
virtual ~profileModel ()=default
const word & name () const
virtual void Cdl (const scalar alpha, scalar &Cd, scalar &Cl) const =0
Static Public Member Functions
static autoPtr< profileModel > New (const dictionary &dict)
Protected Member Functions
bool readFromFile () const
Protected Attributes
const dictionary dict_
const word name_
fileName fName_
Detailed Description
Base class for profile models for handling aerofoil lift and drag polar diagrams.
Usage
Minimal example by using constant/fvOptions: rotorDiskSource1 { Mandatory/Optional (inherited) entries ...
Mandatory entries (runtime modifiable) profiles { Mandatory entries (runtime modifiable) <profile1> { type <profileModel>;
Mandatory/Optional (inherited) entries ... } ... <profileN> { ... }
Optional entries (runtime modifiable) file <fileName>; } }
where the entries mean:
Property Description Type Reqd Dflt
type Profile model - see below word yes -
file Name of file containing profile characteristics word no -
Options for the type entry:
      lookup    | Polar data is linearly interpolated based on angle of attack
      series    | Polar data is computed as sum of cosine series
See also
Foam::fv::rotorDiskSource
Foam::lookupProfile
Foam::seriesProfile
Source files
profileModel.H
profileModel.C
profileModelList.C
Definition at line 116 of file profileModel.H.
Constructor & Destructor Documentation
profileModel()
profileModel (const dictionary & dict, const word & modelName)
Definition at line 44 of file profileModel.C.
~profileModel()
virtual ~profileModel () virtual default
Member Function Documentation
readFromFile()
bool readFromFile () const protected
Definition at line 36 of file profileModel.C.
References profileModel::fName_.
Referenced by lookupProfile::lookupProfile(), and seriesProfile::seriesProfile().
TypeName()
TypeName ("profileModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , profileModel , dictionary , (const dictionary &dict, const word &modelName) , (dict, modelName))
New()
Foam::autoPtr< Foam::profileModel > New (const dictionary & dict) static
Definition at line 60 of file profileModel.C.
References dict, dictionary::dictName(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
Referenced by profileModelList::profileModelList().
name()
const Foam::word & name () const
Definition at line 54 of file profileModel.C.
Cdl()
virtual void Cdl (const scalar alpha, scalar & Cd, scalar & Cl) const pure virtual
Implemented in lookupProfile, and seriesProfile.
Member Data Documentation
dict_
const dictionary dict_ protected
Definition at line 123 of file profileModel.H.
name_
const word name_ protected
Definition at line 126 of file profileModel.H.
fName_
fileName fName_ protected
Definition at line 129 of file profileModel.H.
Referenced by lookupProfile::lookupProfile(), profileModel::readFromFile(), and seriesProfile::seriesProfile().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/rotorDiskSource/profileModel/profileModel.H
src/fvOptions/sources/derived/rotorDiskSource/profileModel/profileModel.C