OpenFOAM: surfZoneIdentifier Class Reference
surfZoneIdentifier Class Reference
Identifies a surface patch/zone by name and index, with optional geometric type.
#include <surfZoneIdentifier.H>
Public Member Functions
surfZoneIdentifier (const surfZoneIdentifier &)=default
surfZoneIdentifier & operator= (const surfZoneIdentifier &)=default
surfZoneIdentifier ()
surfZoneIdentifier (const label index)
surfZoneIdentifier (const word &name, const label index)
surfZoneIdentifier (const word &name, const label index, const word &geometricType)
surfZoneIdentifier (const word &name, const dictionary &dict, const label index)
surfZoneIdentifier (const surfZoneIdentifier &ident, const label index)
const word & name () const
word & name ()
const word & geometricType () const
word & geometricType ()
label index () const
label & index ()
void write (Ostream &os) const
Static Public Member Functions
static word defaultName (const label n=-1)
Static Public Attributes
static constexpr const char *const emptyType = "empty"
Detailed Description
Identifies a surface patch/zone by name and index, with optional geometric type.
See also
patchIdentifier
Source files
surfZoneIdentifier.H
surfZoneIdentifier.C
Definition at line 55 of file surfZoneIdentifier.H.
Constructor & Destructor Documentation
surfZoneIdentifier() [1/7]
surfZoneIdentifier (const surfZoneIdentifier &) default
surfZoneIdentifier() [2/7]
surfZoneIdentifier ()
Definition at line 27 of file surfZoneIdentifier.C.
surfZoneIdentifier() [3/7]
surfZoneIdentifier (const label index) explicit
Definition at line 33 of file surfZoneIdentifier.C.
surfZoneIdentifier() [4/7]
surfZoneIdentifier (const word & name, const label index)
Definition at line 41 of file surfZoneIdentifier.C.
surfZoneIdentifier() [5/7]
surfZoneIdentifier (const word & name, const label index, const word & geometricType)
Definition at line 53 of file surfZoneIdentifier.C.
surfZoneIdentifier() [6/7]
surfZoneIdentifier (const word & name, const dictionary & dict, const label index)
Definition at line 66 of file surfZoneIdentifier.C.
References dict.
surfZoneIdentifier() [7/7]
surfZoneIdentifier (const surfZoneIdentifier & ident, const label index)
Definition at line 81 of file surfZoneIdentifier.C.
Member Function Documentation
defaultName()
static word defaultName (const label n = -1) inline static
Definition at line 79 of file surfZoneIdentifier.H.
References n.
Referenced by MeshedSurface< Face >::addZones(), UnsortedMeshedSurface< Face >::setZones(), and UnsortedMeshedSurface< Face >::sortedZones().
operator=()
surfZoneIdentifier & operator= (const surfZoneIdentifier &) default
name() [1/2]
const word & name () const inline
Definition at line 137 of file surfZoneIdentifier.H.
Referenced by surfZone::New(), and Foam::operator==().
name() [2/2]
word & name () inline
Definition at line 143 of file surfZoneIdentifier.H.
geometricType() [1/2]
const word & geometricType () const inline
Definition at line 149 of file surfZoneIdentifier.H.
Referenced by Foam::operator==(), and Foam::operator==().
geometricType() [2/2]
word & geometricType () inline
Definition at line 155 of file surfZoneIdentifier.H.
index() [1/2]
label index () const inline
Definition at line 161 of file surfZoneIdentifier.H.
Referenced by Foam::operator==(), and surfZone::surfZone().
index() [2/2]
label & index () inline
Definition at line 167 of file surfZoneIdentifier.H.
write()
void write (Ostream & os) const
Definition at line 95 of file surfZoneIdentifier.C.
References os(), and Ostream::writeEntry().
Referenced by surfZone::write().
Member Data Documentation
emptyType
constexpr const char* const emptyType = "empty" static constexpr
Definition at line 73 of file surfZoneIdentifier.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/Identifiers/surface/surfZoneIdentifier.H
src/OpenFOAM/meshes/Identifiers/surface/surfZoneIdentifier.C