OpenFOAM: HashTable< T, Key, Hash >::const_iterator Class Reference
HashTable< T, Key, Hash >::const_iterator Class Reference
#include <HashTable.H>
Public Types
using iterator_category = std::forward_iterator_tag
using difference_type = this_type::difference_type
using node_type = this_type::node_type
using key_type = this_type::key_type
using mapped_type = const this_type::mapped_type
using value_type = const this_type::value_type
using pointer = this_type::const_pointer
using reference = this_type::const_reference
Public Types inherited from HashTable< T, Key, Hash >::Iterator< true >
using iterator_category = std::forward_iterator_tag
using difference_type = this_type::difference_type
using table_type = typename std::conditional< Const, const this_type, this_type >::type
using node_type = typename std::conditional< Const, const this_type::node_type, this_type::node_type >::type
using key_type = this_type::key_type
using mapped_type = typename std::conditional< Const, const this_type::mapped_type, this_type::mapped_type >::type
Public Member Functions
const_iterator ()=default
const_iterator (const const_iterator &)=default
const_iterator & operator= (const const_iterator &)=default
template<bool Any>
const_iterator (const Iterator< Any > &iter)
const_iterator (const iterator &iter)
const node_type * node () const noexcept
reference val () const
reference operator* () const
reference operator() () const
const_iterator & operator++ ()
const_iterator operator++ (int)
const_iterator & operator= (const iterator &iter)
Public Member Functions inherited from HashTable< T, Key, Hash >::Iterator< true >
bool good () const noexcept
bool found () const noexcept
const Key & key () const
Ostream & print (Ostream &os) const
operator bool () const noexcept
bool operator== (const Iterator< Any > &iter) const noexcept
bool operator!= (const Iterator< Any > &iter) const noexcept
Additional Inherited Members
Protected Member Functions inherited from HashTable< T, Key, Hash >::Iterator< true >
constexpr Iterator () noexcept
Iterator (table_type *tbl)
Iterator (table_type *tbl, const Key &key)
void increment ()
operator const Iterator< Any > & () const
Protected Attributes inherited from HashTable< T, Key, Hash >::Iterator< true >
node_type * entry_
table_type * container_
label index_
Detailed Description
template<class T, class Key = word, class Hash = Foam::Hash<Key>>
class Foam::HashTable< T, Key, Hash >::const_iterator
Definition at line 810 of file HashTable.H.
Member Typedef Documentation
iterator_category
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using iterator_category = std::forward_iterator_tag
Definition at line 817 of file HashTable.H.
difference_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using difference_type = this_type::difference_type
Definition at line 818 of file HashTable.H.
node_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using node_type = this_type::node_type
Definition at line 820 of file HashTable.H.
key_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using key_type = this_type::key_type
Definition at line 821 of file HashTable.H.
mapped_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using mapped_type = const this_type::mapped_type
Definition at line 822 of file HashTable.H.
value_type
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using value_type = const this_type::value_type
Definition at line 823 of file HashTable.H.
pointer
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using pointer = this_type::const_pointer
Definition at line 824 of file HashTable.H.
reference
template<class T , class Key = word, class Hash = Foam::Hash<Key>> using reference = this_type::const_reference
Definition at line 825 of file HashTable.H.
Constructor & Destructor Documentation
const_iterator() [1/4]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> const_iterator () default
const_iterator() [2/4]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> const_iterator (const const_iterator &) default
const_iterator() [3/4]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> template<bool Any> const_iterator (const Iterator< Any > & iter) inline
Definition at line 844 of file HashTable.H.
const_iterator() [4/4]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> const_iterator (const iterator & iter) inline
Definition at line 850 of file HashTable.H.
Member Function Documentation
operator=() [1/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> const_iterator & operator= (const const_iterator &) default
node()
template<class T , class Key = word, class Hash = Foam::Hash<Key>> const node_type * node () const inline noexcept
Definition at line 859 of file HashTable.H.
val()
template<class T , class Key = word, class Hash = Foam::Hash<Key>> reference val () const inline
Definition at line 865 of file HashTable.H.
Referenced by HashTable< T, Key, Hash >::at(), IOobjectList::cfindObject(), HashTable< T, Key, Hash >::lookup(), HashTable< T, Key, Hash >::const_iterator::operator()(), HashTable< T, Key, Hash >::const_iterator::operator*(), and HashTable< T, Key, Hash >::operator==().
operator*()
template<class T , class Key = word, class Hash = Foam::Hash<Key>> reference operator* () const inline
Definition at line 871 of file HashTable.H.
References HashTable< T, Key, Hash >::const_iterator::val().
operator()()
template<class T , class Key = word, class Hash = Foam::Hash<Key>> reference operator() () const inline
Definition at line 872 of file HashTable.H.
References HashTable< T, Key, Hash >::const_iterator::val().
operator++() [1/2]
template<class T , class Key , class Hash > Foam::HashTable< T, Key, Hash >::const_iterator & operator++ () inline
Definition at line 146 of file HashTableIterI.H.
operator++() [2/2]
template<class T , class Key , class Hash > Foam::HashTable< T, Key, Hash >::const_iterator operator++ (int) inline
Definition at line 155 of file HashTableIterI.H.
operator=() [2/2]
template<class T , class Key = word, class Hash = Foam::Hash<Key>> const_iterator & operator= (const iterator & iter) inline
Definition at line 881 of file HashTable.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashTable/HashTable.H
src/OpenFOAM/containers/HashTables/HashTable/HashTableIterI.H