OpenFOAM: Frank Class Reference
Frank Class Reference
Wall lubrication model of Frank.
#include <Frank.H>
Public Member Functions
TypeName ("Frank")
Frank (const dictionary &dict, const phasePair &pair)
virtual ~Frank ()
tmp< volVectorField > Fi () const
TypeName ("Frank")
Frank (const dictionary &dict, const phasePair &pair)
virtual ~Frank ()
tmp< volVectorField > Fi () const
Public Member Functions inherited from wallLubricationModel
TypeName ("wallLubricationModel")
declareRunTimeSelectionTable (autoPtr, wallLubricationModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
wallLubricationModel (const dictionary &dict, const phasePair &pair)
virtual ~wallLubricationModel ()=default
virtual tmp< volVectorField > F () const
virtual tmp< surfaceScalarField > Ff () const
TypeName ("wallLubricationModel")
declareRunTimeSelectionTable (autoPtr, wallLubricationModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
wallLubricationModel (const dictionary &dict, const phasePair &pair)
virtual ~wallLubricationModel ()=default
virtual tmp< volVectorField > F () const
virtual tmp< surfaceScalarField > Ff () const
Public Member Functions inherited from wallDependentModel
wallDependentModel (const fvMesh &mesh)
virtual ~wallDependentModel ()
const volScalarField & yWall () const
const volVectorField & nWall () const
wallDependentModel (const fvMesh &mesh)
virtual ~wallDependentModel ()
const volScalarField & yWall () const
const volVectorField & nWall () const
Additional Inherited Members
Static Public Member Functions inherited from wallLubricationModel
static autoPtr< wallLubricationModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< wallLubricationModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes inherited from wallLubricationModel
static const dimensionSet dimF
Protected Member Functions inherited from wallLubricationModel
tmp< volVectorField > zeroGradWalls (tmp< volVectorField >) const
Protected Attributes inherited from wallLubricationModel
const phasePair & pair_
Detailed Description
Wall lubrication model of Frank.
References:
    Otromke, M. (2013).
    Implementation and Comparison of Correlations for interfacial Forces in
    a Gas-Liquid System within an Euler-Euler Framework.
    PhD Thesis.
    Frank, T. (2005, April).
    Advances in computational fluid dynamics (CFD) of 3-dimensional
    gas-liquid multiphase flows.
    In NAFEMS Seminar: Simulation of Complex Flows (CFD)-Applications and
    Trends, Wiesbaden, Germany (pp. 1-18).
Source files
Frank.H
Frank.C
References:
    "Implementation and Comparison of Correlations for interfacial Forces
     in a Gas-Liquid System within an Euler-Euler Framework"
    Otromke, M.
    PhD Thesis
    April 2013
    "Advances in Computational Fluid Dynamics (CFD) of 3-dimensional Gas-
     Liquid Multiphase Flows"
    Frank, T.
    NAFEMS Seminar: Simulation of Complex Flows (CFD), April 2005, pp. 1-18
Source files
Frank.H
Frank.C
Definition at line 67 of file Frank.H.
Constructor & Destructor Documentation
Frank() [1/2]
Frank (const dictionary & dict, const phasePair & pair)
Definition at line 45 of file Frank.C.
References Foam::dimless.
~Frank() [1/2]
~Frank () virtual
Definition at line 60 of file Frank.C.
Frank() [2/2]
Frank (const dictionary & dict, const phasePair & pair)
~Frank() [2/2]
virtual ~Frank () virtual
Member Function Documentation
TypeName() [1/2]
TypeName ("Frank")
Fi() [1/2]
Foam::tmp< Foam::volVectorField > Fi () const virtual
Implements wallLubricationModel.
Definition at line 66 of file Frank.C.
References Foam::dimLength, Foam::dimless, Foam::exp(), Foam::magSqr(), Foam::max(), n, Foam::neg(), Foam::pos0(), Foam::pow(), and y.
TypeName() [2/2]
TypeName ("Frank")
Fi() [2/2]
tmp< volVectorField > Fi () const virtual
Implements wallLubricationModel.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/wallLubricationModels/Frank/Frank.H
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/wallLubricationModels/Frank/Frank.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/interfacialModels/wallLubricationModels/Frank/Frank.C
src/phaseSystemModels/twoPhaseEuler/twoPhaseSystem/interfacialModels/wallLubricationModels/Frank/Frank.C