OpenFOAM: FIREMeshReader Class Reference
FIREMeshReader Class Reference
Read AVL/FIRE fpma, fpmb files.
#include <FIREMeshReader.H>
Public Member Functions
FIREMeshReader (const fileName &, const scalar scaleFactor=1.0)
virtual ~FIREMeshReader ()=default
virtual autoPtr< polyMesh > mesh (const objectRegistry &)
Public Member Functions inherited from meshReader
meshReader (const fileName &, const scalar scaling=1.0)
virtual ~meshReader ()=default
void writeAux (const objectRegistry &) const
void writeMesh (const polyMesh &, IOstreamOption streamOpt=IOstreamOption(IOstreamOption::BINARY)) const
Protected Member Functions
FIREMeshReader (const FIREMeshReader &)=delete
void operator= (const FIREMeshReader &)=delete
virtual bool readGeometry (const scalar scaleFactor=1.0)
void readPoints (ISstream &, const scalar scaleFactor=1.0)
void readFaces (ISstream &)
void readCells (ISstream &)
void readSelections (ISstream &)
void reorganize ()
void addPatches (polyMesh &) const
Protected Member Functions inherited from FIRECore
FIRECore ()=default
Protected Attributes
labelList owner_
labelList neigh_
labelList faceZoneId_
wordList faceNames_
Protected Attributes inherited from meshReader
fileName geometryFile_
scalar scaleFactor_
pointField points_
labelList origCellId_
List< List< cellFaceIdentifier > > boundaryIds_
wordList patchTypes_
wordList patchNames_
wordList patchPhysicalTypes_
labelList patchStarts_
labelList patchSizes_
label nInternalFaces_
faceList meshFaces_
faceListList cellFaces_
faceList baffleFaces_
labelList cellTableId_
cellTable cellTable_
Additional Inherited Members
Public Types inherited from FIRECore
enum selectionType { cellSelection = 2 , faceSelection = 3 }
enum shapeType {
fireLine = 1 , fireTri = 2 , fireQuad = 3 , fireTet = 4 ,
fireHex = 5 , firePyr = 6 , firePrism = 8
}
enum fileExt3d { POLY_ASCII , POLY_BINARY , POLY_ASCII_Z , POLY_BINARY_Z }
typedef int32_t fireInt_t
typedef double fireReal_t
Static Public Member Functions inherited from meshReader
static void warnDuplicates (const word &context, const wordList &)
Static Public Member Functions inherited from FIRECore
static fileName fireFileName (const fileName &baseName, const enum fileExt3d)
static label getFireLabel (ISstream &)
static point getFirePoint (ISstream &)
static std::string getFireString (ISstream &)
static void putFireLabel (OSstream &, const label)
static void putFireLabels (OSstream &, const labelUList &)
static void putFireLabels (OSstream &, const label count, const label start)
static void putFirePoint (OSstream &, const point &)
static void putFireString (OSstream &, const std::string &)
Static Protected Member Functions inherited from FIRECore
static label readPoints (ISstream &, pointField &)
Static Protected Attributes inherited from FIRECore
static const Enum< fileExt3d > file3dExtensions
Detailed Description
Read AVL/FIRE fpma, fpmb files.
Note
Does not handle compressed versions (fpmaz, fpmbz) of these files.
Source files
FIREMeshReader.H
FIREMeshReader.C
Definition at line 57 of file FIREMeshReader.H.
Constructor & Destructor Documentation
FIREMeshReader() [1/2]
FIREMeshReader (const FIREMeshReader &) protected delete
FIREMeshReader() [2/2]
FIREMeshReader (const fileName & name, const scalar scaleFactor = 1.0)
Definition at line 458 of file FIREMeshReader.C.
~FIREMeshReader()
virtual ~FIREMeshReader () virtual default
Member Function Documentation
operator=()
void operator= (const FIREMeshReader &) protected delete
readGeometry()
bool readGeometry (const scalar scaleFactor = 1.0) protected virtual
Implements meshReader.
Definition at line 374 of file FIREMeshReader.C.
References Foam::abort(), IOstreamOption::ASCII, IOstreamOption::BINARY, Foam::FatalError, FatalErrorInFunction, FIRECore::file3dExtensions, Foam::nl, FIRECore::POLY_ASCII, and FIRECore::POLY_BINARY.
readPoints()
void readPoints (ISstream & is, const scalar scaleFactor = 1.0) protected
Definition at line 29 of file FIREMeshReader.C.
References Foam::endl(), Foam::Info, n, meshReader::points_, and FIRECore::readPoints().
readFaces()
void readFaces (ISstream & is) protected
Definition at line 46 of file FIREMeshReader.C.
References Foam::abort(), Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, and List< T >::setSize().
readCells()
void readCells (ISstream & is) protected
Definition at line 78 of file FIREMeshReader.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::Info, and Foam::Warning.
readSelections()
void readSelections (ISstream & is) protected
Definition at line 129 of file FIREMeshReader.C.
References PtrList< T >::append(), cellId, FIRECore::cellSelection, Foam::endl(), faceId(), FIRECore::faceSelection, Foam::Info, Foam::name(), PtrList< T >::setSize(), PtrList< T >::transfer(), and word::validate().
reorganize()
void reorganize () protected
Definition at line 196 of file FIREMeshReader.C.
References PtrList< T >::clear(), Foam::endl(), forAll, Foam::Info, Foam::inplaceReorder(), nPatches, Foam::pos(), PtrList< T >::setSize(), and UPtrList< T >::size().
addPatches()
void addPatches (polyMesh & mesh) const protected
Definition at line 336 of file FIREMeshReader.C.
References Foam::endl(), forAll, Foam::Info, mesh, word::null, and PtrList< T >::set().
mesh()
Foam::autoPtr< Foam::polyMesh > mesh (const objectRegistry & registry) virtual
Reimplemented from meshReader.
Definition at line 419 of file FIREMeshReader.C.
References IOobjectOption::AUTO_WRITE, polyMesh::defaultRegion, Foam::endl(), Foam::Info, mesh, meshPtr, autoPtr< T >::New(), and IOobjectOption::NO_READ.
Member Data Documentation
owner_
labelList owner_ protected
Definition at line 67 of file FIREMeshReader.H.
neigh_
labelList neigh_ protected
Definition at line 68 of file FIREMeshReader.H.
faceZoneId_
labelList faceZoneId_ protected
Definition at line 70 of file FIREMeshReader.H.
faceNames_
wordList faceNames_ protected
Definition at line 71 of file FIREMeshReader.H.
The documentation for this class was generated from the following files:
src/conversion/fire/FIREMeshReader.H
src/conversion/fire/FIREMeshReader.C