OpenFOAM: eConstThermo< EquationOfState > Class Template Reference
eConstThermo< EquationOfState > Class Template Reference
Thermophysical models » Specie » Thermodynamics
Constant properties thermodynamics package templated on an equation of state.
#include <eConstThermo.H>
Public Member Functions
eConstThermo (const dictionary &dict)
eConstThermo (const word &, const eConstThermo &)
autoPtr< eConstThermo > clone () const
scalar limit (const scalar T) const
scalar Cv (const scalar p, const scalar T) const
scalar Es (const scalar p, const scalar T) const
scalar Ea (const scalar p, const scalar T) const
scalar Hc () const
scalar S (const scalar p, const scalar T) const
scalar Gstd (const scalar T) const
scalar dCpdT (const scalar p, const scalar T) const
void write (Ostream &os) const
void operator+= (const eConstThermo &)
Static Public Member Functions
static autoPtr< eConstThermo > New (const dictionary &dict)
static word typeName ()
Friends
eConstThermo operator+ (const eConstThermo &, const eConstThermo &)
eConstThermo operator* (const scalar, const eConstThermo &)
eConstThermo operator== (const eConstThermo &, const eConstThermo &)
Ostream & operator<< (Ostream &, const eConstThermo &)
Detailed Description
template<class EquationOfState>
class Foam::eConstThermo< EquationOfState >
Constant properties thermodynamics package templated on an equation of state.
Source files
eConstThermo.H
eConstThermoI.H
eConstThermo.C
Definition at line 86 of file eConstThermo.H.
Constructor & Destructor Documentation
eConstThermo() [1/2]
template<class EquationOfState > eConstThermo (const dictionary & dict)
Definition at line 28 of file eConstThermo.C.
eConstThermo() [2/2]
template<class EquationOfState > eConstThermo (const word & , const eConstThermo< EquationOfState > &) inline
Member Function Documentation
clone()
template<class EquationOfState > Foam::autoPtr< Foam::eConstThermo< EquationOfState > > clone () const inline
Definition at line 60 of file eConstThermoI.H.
References Foam::New().
New()
template<class EquationOfState > Foam::autoPtr< Foam::eConstThermo< EquationOfState > > New (const dictionary & dict) inline static
Definition at line 68 of file eConstThermoI.H.
References dict, and Foam::New().
typeName()
template<class EquationOfState > static word typeName () inline static
Definition at line 140 of file eConstThermo.H.
limit()
template<class EquationOfState > Foam::scalar limit (const scalar T) const inline
Definition at line 77 of file eConstThermoI.H.
References T.
Cv()
template<class EquationOfState > Foam::scalar Cv (const scalar p, const scalar T) const inline
Definition at line 87 of file eConstThermoI.H.
References p, and T.
Es()
template<class EquationOfState > Foam::scalar Es (const scalar p, const scalar T) const inline
Definition at line 98 of file eConstThermoI.H.
References p, and T.
Ea()
template<class EquationOfState > Foam::scalar Ea (const scalar p, const scalar T) const inline
Definition at line 109 of file eConstThermoI.H.
References Es(), p, and T.
Hc()
template<class EquationOfState > Foam::scalar Hc () const inline
Definition at line 120 of file eConstThermoI.H.
S()
template<class EquationOfState > Foam::scalar S (const scalar p, const scalar T) const inline
Definition at line 127 of file eConstThermoI.H.
References Cp, Foam::log(), p, and T.
Gstd()
template<class EquationOfState > Foam::scalar Gstd (const scalar T) const inline
Definition at line 138 of file eConstThermoI.H.
References T.
dCpdT()
template<class EquationOfState > Foam::scalar dCpdT (const scalar p, const scalar T) const inline
Definition at line 150 of file eConstThermoI.H.
References NotImplemented.
write()
template<class EquationOfState > void write (Ostream & os) const
Definition at line 41 of file eConstThermo.C.
References Ostream::beginBlock(), Ostream::endBlock(), os(), Ostream::writeEntry(), and Ostream::writeEntryIfDifferent().
operator+=()
template<class EquationOfState > void operator+= (const eConstThermo< EquationOfState > &) inline
Definition at line 163 of file eConstThermoI.H.
References Foam::mag(), and Y.
Friends And Related Symbol Documentation
operator+
template<class EquationOfState > eConstThermo operator+ (const eConstThermo< EquationOfState > & , const eConstThermo< EquationOfState > &) friend
operator*
template<class EquationOfState > eConstThermo operator* (const scalar , const eConstThermo< EquationOfState > &) friend
operator==
template<class EquationOfState > eConstThermo operator== (const eConstThermo< EquationOfState > & , const eConstThermo< EquationOfState > &) friend
operator<<
template<class EquationOfState > Ostream & operator<< (Ostream & , const eConstThermo< EquationOfState > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/eConst/eConstThermo.H
src/thermophysicalModels/specie/thermo/eConst/eConstThermo.C
src/thermophysicalModels/specie/thermo/eConst/eConstThermoI.H