OpenFOAM: boundaryAdjointContribution Class Reference
boundaryAdjointContribution Class Reference abstract
Abstract base class for computing contributions of the objective functions to the adjoint boundary conditions.
#include <boundaryAdjointContribution.H>
Public Member Functions
TypeName ("boundaryAdjointContribution")
declareRunTimeSelectionTable (autoPtr, boundaryAdjointContribution, dictionary,(const word &managerName, const word &adjointSolverName, const word &simulationType, const fvPatch &patch),(managerName, adjointSolverName, simulationType, patch))
boundaryAdjointContribution (const word &managerName, const word &adjointSolverName, const word &simulationType, const fvPatch &patch)
virtual ~boundaryAdjointContribution ()=default
virtual tmp< scalarField > pressureSource ()=0
virtual tmp< vectorField > velocitySource ()=0
virtual tmp< vectorField > tangentVelocitySource ()=0
virtual tmp< vectorField > normalVelocitySource ()=0
virtual tmp< scalarField > adjointTMVariable1Source ()
virtual tmp< scalarField > adjointTMVariable2Source ()
virtual tmp< scalarField > dJdnut ()
virtual tmp< tensorField > dJdGradU ()
virtual tmp< scalarField > energySource ()=0
virtual tmp< scalarField > momentumDiffusion ()=0
virtual tmp< scalarField > laminarDiffusivity ()=0
virtual tmp< scalarField > thermalDiffusion ()=0
virtual tmp< scalarField > wallDistance ()=0
virtual tmp< scalarField > TMVariable1Diffusion ()
virtual tmp< scalarField > TMVariable2Diffusion ()
virtual tmp< scalarField > TMVariable1 ()
virtual tmp< scalarField > TMVariable2 ()
virtual const fvPatchVectorField & Ub () const =0
virtual const fvPatchScalarField & pb () const =0
virtual const fvsPatchScalarField & phib () const =0
virtual const fvPatchScalarField & turbulentDiffusivity () const =0
virtual const fvPatchVectorField & Uab () const =0
virtual const fvPatchScalarField & pab () const =0
virtual const fvsPatchScalarField & phiab () const =0
virtual const word primalSolverName () const =0
virtual const word adjointSolverName () const =0
Static Public Member Functions
static autoPtr< boundaryAdjointContribution > New (const word &managerName, const word &adjointSolverName, const word &simulationType, const fvPatch &patch)
Protected Attributes
const fvPatch & patch_
Detailed Description
Abstract base class for computing contributions of the objective functions to the adjoint boundary conditions.
Source files
boundaryAdjointContribution.H
boundaryAdjointContribution.C
Definition at line 54 of file boundaryAdjointContribution.H.
Constructor & Destructor Documentation
boundaryAdjointContribution()
boundaryAdjointContribution (const word & managerName, const word & adjointSolverName, const word & simulationType, const fvPatch & patch)
Definition at line 37 of file boundaryAdjointContribution.C.
~boundaryAdjointContribution()
virtual ~boundaryAdjointContribution () virtual default
Member Function Documentation
TypeName()
TypeName ("boundaryAdjointContribution")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , boundaryAdjointContribution , dictionary , (const word &managerName, const word &adjointSolverName, const word &simulationType, const fvPatch &patch) , (managerName, adjointSolverName, simulationType, patch))
New()
autoPtr< boundaryAdjointContribution > New (const word & managerName, const word & adjointSolverName, const word & simulationType, const fvPatch & patch) static
Definition at line 51 of file boundaryAdjointContribution.C.
References boundaryAdjointContribution::adjointSolverName(), Foam::exit(), Foam::FatalError, and FatalErrorInLookup.
Referenced by adjointSpalartAllmaras::distanceSensitivities(), adjointBoundaryCondition< Type >::setBoundaryContributionPtr(), and boundaryAdjointContributionIncompressible::sumContributions().
pressureSource()
virtual tmp< scalarField > pressureSource () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
velocitySource()
virtual tmp< vectorField > velocitySource () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
tangentVelocitySource()
virtual tmp< vectorField > tangentVelocitySource () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
normalVelocitySource()
virtual tmp< vectorField > normalVelocitySource () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
adjointTMVariable1Source()
tmp< scalarField > adjointTMVariable1Source () virtual
Reimplemented in boundaryAdjointContributionIncompressible.
Definition at line 87 of file boundaryAdjointContribution.C.
References tmp< T >::New(), boundaryAdjointContribution::patch_, UPtrList< T >::size(), and Foam::Zero.
adjointTMVariable2Source()
tmp< scalarField > adjointTMVariable2Source () virtual
Reimplemented in boundaryAdjointContributionIncompressible.
Definition at line 93 of file boundaryAdjointContribution.C.
References tmp< T >::New(), boundaryAdjointContribution::patch_, UPtrList< T >::size(), and Foam::Zero.
dJdnut()
tmp< scalarField > dJdnut () virtual
Reimplemented in boundaryAdjointContributionIncompressible.
Definition at line 99 of file boundaryAdjointContribution.C.
References tmp< T >::New(), boundaryAdjointContribution::patch_, UPtrList< T >::size(), and Foam::Zero.
dJdGradU()
tmp< tensorField > dJdGradU () virtual
Reimplemented in boundaryAdjointContributionIncompressible.
Definition at line 105 of file boundaryAdjointContribution.C.
References tmp< T >::New(), boundaryAdjointContribution::patch_, UPtrList< T >::size(), and Foam::Zero.
energySource()
virtual tmp< scalarField > energySource () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
momentumDiffusion()
virtual tmp< scalarField > momentumDiffusion () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
laminarDiffusivity()
virtual tmp< scalarField > laminarDiffusivity () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
thermalDiffusion()
virtual tmp< scalarField > thermalDiffusion () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
wallDistance()
virtual tmp< scalarField > wallDistance () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
TMVariable1Diffusion()
tmp< scalarField > TMVariable1Diffusion () virtual
Reimplemented in boundaryAdjointContributionIncompressible.
Definition at line 111 of file boundaryAdjointContribution.C.
References tmp< T >::New(), boundaryAdjointContribution::patch_, UPtrList< T >::size(), and Foam::Zero.
TMVariable2Diffusion()
tmp< scalarField > TMVariable2Diffusion () virtual
Reimplemented in boundaryAdjointContributionIncompressible.
Definition at line 117 of file boundaryAdjointContribution.C.
References tmp< T >::New(), boundaryAdjointContribution::patch_, UPtrList< T >::size(), and Foam::Zero.
TMVariable1()
tmp< scalarField > TMVariable1 () virtual
Reimplemented in boundaryAdjointContributionIncompressible.
Definition at line 123 of file boundaryAdjointContribution.C.
References tmp< T >::New(), boundaryAdjointContribution::patch_, UPtrList< T >::size(), and Foam::Zero.
TMVariable2()
tmp< scalarField > TMVariable2 () virtual
Reimplemented in boundaryAdjointContributionIncompressible.
Definition at line 129 of file boundaryAdjointContribution.C.
References tmp< T >::New(), boundaryAdjointContribution::patch_, UPtrList< T >::size(), and Foam::Zero.
Ub()
virtual const fvPatchVectorField & Ub () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
pb()
virtual const fvPatchScalarField & pb () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
phib()
virtual const fvsPatchScalarField & phib () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
turbulentDiffusivity()
virtual const fvPatchScalarField & turbulentDiffusivity () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
Uab()
virtual const fvPatchVectorField & Uab () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
pab()
virtual const fvPatchScalarField & pab () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
phiab()
virtual const fvsPatchScalarField & phiab () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
primalSolverName()
virtual const word primalSolverName () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
adjointSolverName()
virtual const word adjointSolverName () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
Referenced by boundaryAdjointContribution::New().
Member Data Documentation
patch_
const fvPatch& patch_ protected
Definition at line 74 of file boundaryAdjointContribution.H.
Referenced by boundaryAdjointContribution::adjointTMVariable1Source(), boundaryAdjointContribution::adjointTMVariable2Source(), boundaryAdjointContribution::dJdGradU(), boundaryAdjointContribution::dJdnut(), boundaryAdjointContributionIncompressible::laminarDiffusivity(), boundaryAdjointContributionIncompressible::momentumDiffusion(), boundaryAdjointContributionIncompressible::pab(), boundaryAdjointContributionIncompressible::pb(), boundaryAdjointContributionIncompressible::phiab(), boundaryAdjointContributionIncompressible::phib(), boundaryAdjointContributionIncompressible::pressureSource(), boundaryAdjointContributionIncompressible::sumContributions(), boundaryAdjointContributionIncompressible::tangentVelocitySource(), boundaryAdjointContributionIncompressible::thermalDiffusion(), boundaryAdjointContribution::TMVariable1(), boundaryAdjointContributionIncompressible::TMVariable1(), boundaryAdjointContribution::TMVariable1Diffusion(), boundaryAdjointContributionIncompressible::TMVariable1Diffusion(), boundaryAdjointContribution::TMVariable2(), boundaryAdjointContributionIncompressible::TMVariable2(), boundaryAdjointContribution::TMVariable2Diffusion(), boundaryAdjointContributionIncompressible::TMVariable2Diffusion(), boundaryAdjointContributionIncompressible::turbulentDiffusivity(), boundaryAdjointContributionIncompressible::Uab(), boundaryAdjointContributionIncompressible::Ub(), boundaryAdjointContributionIncompressible::velocitySource(), and boundaryAdjointContributionIncompressible::wallDistance().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/boundaryAdjointContributions/boundaryAdjointContribution/boundaryAdjointContribution.H
src/optimisation/adjointOptimisation/adjoint/boundaryAdjointContributions/boundaryAdjointContribution/boundaryAdjointContribution.C