OpenFOAM: cylindrical Class Reference
cylindrical Class Reference
A cylindrical coordinate system (r-theta-z). The coordinate system angle theta is always in radians.
#include <cylindricalCS.H>
Public Member Functions
TypeNameNoDebug ("cylindrical")
cylindrical ()=default
cylindrical (const cylindrical &csys)=default
cylindrical (cylindrical &&csys)=default
cylindrical (const coordinateSystem &csys)
cylindrical (coordinateSystem &&csys)
cylindrical (autoPtr< coordinateSystem > &&csys)
cylindrical (const coordinateRotation &crot)
cylindrical (const point &origin, const coordinateRotation &crot)
cylindrical (const point &origin, const vector &axis)
cylindrical (const word &name, const point &origin, const vector &axis)
cylindrical (const point &origin, const vector &axis, const vector &dirn)
cylindrical (const word &name, const point &origin, const vector &axis, const vector &dirn)
cylindrical (const dictionary &dict, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
cylindrical (const dictionary &dict, const word &dictName, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
virtual autoPtr< coordinateSystem > clone () const
virtual ~cylindrical ()=default
virtual bool uniform () const
virtual tensor R (const point &global) const
cylindrical & operator= (const cylindrical &)=default
cylindrical & operator= (cylindrical &&)=default
virtual const tensor & R () const
virtual tensor R (const point &global) const
virtual tmp< tensorField > R (const UList< point > &global) const
virtual tmp< tensorField > R (const pointUIndList &global) const
Public Member Functions inherited from coordinateSystem
TypeName ("coordinateSystem")
coordinateSystem ()
coordinateSystem (const coordinateRotation &crot)
coordinateSystem (coordinateRotation &&crot)
coordinateSystem (const coordinateSystem &csys)
coordinateSystem (coordinateSystem &&csys)
coordinateSystem (autoPtr< coordinateSystem > &&csys)
coordinateSystem (const word &name, const coordinateSystem &csys)
coordinateSystem (const point &origin, const coordinateRotation &crot)
coordinateSystem (const point &origin, const vector &axis, const vector &dirn)
coordinateSystem (const word &name, const point &origin, const coordinateRotation &crot)
coordinateSystem (const word &name, const point &origin, const vector &axis, const vector &dirn)
coordinateSystem (const dictionary &dict, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
coordinateSystem (const dictionary &dict, const word &dictName, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
declareRunTimeSelectionTable (autoPtr, coordinateSystem, dictionary,(const dictionary &dict, IOobjectOption::readOption readOrigin),(dict, readOrigin))
declareRunTimeSelectionTable (autoPtr, coordinateSystem, registry,(const objectRegistry &obr, const dictionary &dict, IOobjectOption::readOption readOrigin),(obr, dict, readOrigin))
virtual ~coordinateSystem ()=default
virtual bool valid () const
virtual const point & origin () const
virtual const coordinateRotation & rotation () const
virtual const word & name () const
virtual const string & note () const
virtual const vector e1 () const
virtual const vector e2 () const
virtual const vector e3 () const
virtual void rename (const word &newName)
virtual string & note ()
virtual point & origin ()
virtual void clear ()
virtual void rotation (autoPtr< coordinateRotation > &&crot)
virtual void write (Ostream &os) const
virtual void writeEntry (Ostream &os) const
virtual void writeEntry (const word &keyword, Ostream &os) const
void operator= (const coordinateSystem &csys)
void operator= (coordinateSystem &&csys)
void operator= (const autoPtr< coordinateSystem > &csys)
void operator= (autoPtr< coordinateSystem > &&csys)
point transformPoint (const point &localCart) const
tmp< pointField > transformPoint (const UList< point > &localCart) const
tmp< pointField > transformPoint (const pointUIndList &localCart) const
point invTransformPoint (const point &global) const
tmp< pointField > invTransformPoint (const UList< point > &global) const
tmp< pointField > invTransformPoint (const pointUIndList &global) const
point globalPosition (const point &local) const
tmp< pointField > globalPosition (const pointField &local) const
point localPosition (const point &global) const
tmp< pointField > localPosition (const pointField &global) const
vector globalVector (const vector &local) const
tmp< vectorField > globalVector (const vectorField &local) const
vector localVector (const vector &global) const
tmp< vectorField > localVector (const vectorField &global) const
virtual symmTensor transformPrincipal (const vector &input) const
With constant rotation tensor.
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< vector > &input) const
With constant rotation tensor.
virtual symmTensor transformPrincipal (const point &global, const vector &input) const
With rotation tensor at given global position.
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< point > &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transformPrincipal (const pointUIndList &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< point > &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transformPrincipal (const pointUIndList &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual scalar transform (const scalar &input) const
With constant rotation tensor.
virtual tmp< Field< scalar > > transform (const UList< scalar > &input) const
With constant rotation tensor.
virtual scalar transform (const point &global, const scalar &input) const
With rotation tensor at given global position.
virtual tmp< Field< scalar > > transform (const UList< point > &global, const scalar &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > transform (const pointUIndList &global, const scalar &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > transform (const UList< point > &global, const UList< scalar > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > transform (const pointUIndList &global, const UList< scalar > &input) const
With rotation tensors at given global positions.
virtual vector transform (const vector &input) const
With constant rotation tensor.
virtual tmp< Field< vector > > transform (const UList< vector > &input) const
With constant rotation tensor.
virtual vector transform (const point &global, const vector &input) const
With rotation tensor at given global position.
virtual tmp< Field< vector > > transform (const UList< point > &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > transform (const pointUIndList &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > transform (const UList< point > &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > transform (const pointUIndList &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual sphericalTensor transform (const sphericalTensor &input) const
With constant rotation tensor.
virtual tmp< Field< sphericalTensor > > transform (const UList< sphericalTensor > &input) const
With constant rotation tensor.
virtual sphericalTensor transform (const point &global, const sphericalTensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< sphericalTensor > > transform (const UList< point > &global, const sphericalTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > transform (const pointUIndList &global, const sphericalTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > transform (const UList< point > &global, const UList< sphericalTensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > transform (const pointUIndList &global, const UList< sphericalTensor > &input) const
With rotation tensors at given global positions.
virtual symmTensor transform (const symmTensor &input) const
With constant rotation tensor.
virtual tmp< Field< symmTensor > > transform (const UList< symmTensor > &input) const
With constant rotation tensor.
virtual symmTensor transform (const point &global, const symmTensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< symmTensor > > transform (const UList< point > &global, const symmTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transform (const pointUIndList &global, const symmTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transform (const UList< point > &global, const UList< symmTensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > transform (const pointUIndList &global, const UList< symmTensor > &input) const
With rotation tensors at given global positions.
virtual tensor transform (const tensor &input) const
With constant rotation tensor.
virtual tmp< Field< tensor > > transform (const UList< tensor > &input) const
With constant rotation tensor.
virtual tensor transform (const point &global, const tensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< tensor > > transform (const UList< point > &global, const tensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > transform (const pointUIndList &global, const tensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > transform (const UList< point > &global, const UList< tensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > transform (const pointUIndList &global, const UList< tensor > &input) const
With rotation tensors at given global positions.
virtual scalar invTransform (const scalar &input) const
With constant rotation tensor.
virtual tmp< Field< scalar > > invTransform (const UList< scalar > &input) const
With constant rotation tensor.
virtual scalar invTransform (const point &global, const scalar &input) const
With rotation tensor at given global position.
virtual tmp< Field< scalar > > invTransform (const UList< point > &global, const scalar &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > invTransform (const pointUIndList &global, const scalar &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > invTransform (const UList< point > &global, const UList< scalar > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< scalar > > invTransform (const pointUIndList &global, const UList< scalar > &input) const
With rotation tensors at given global positions.
virtual vector invTransform (const vector &input) const
With constant rotation tensor.
virtual tmp< Field< vector > > invTransform (const UList< vector > &input) const
With constant rotation tensor.
virtual vector invTransform (const point &global, const vector &input) const
With rotation tensor at given global position.
virtual tmp< Field< vector > > invTransform (const UList< point > &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > invTransform (const pointUIndList &global, const vector &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > invTransform (const UList< point > &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< vector > > invTransform (const pointUIndList &global, const UList< vector > &input) const
With rotation tensors at given global positions.
virtual sphericalTensor invTransform (const sphericalTensor &input) const
With constant rotation tensor.
virtual tmp< Field< sphericalTensor > > invTransform (const UList< sphericalTensor > &input) const
With constant rotation tensor.
virtual sphericalTensor invTransform (const point &global, const sphericalTensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< sphericalTensor > > invTransform (const UList< point > &global, const sphericalTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > invTransform (const pointUIndList &global, const sphericalTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > invTransform (const UList< point > &global, const UList< sphericalTensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< sphericalTensor > > invTransform (const pointUIndList &global, const UList< sphericalTensor > &input) const
With rotation tensors at given global positions.
virtual symmTensor invTransform (const symmTensor &input) const
With constant rotation tensor.
virtual tmp< Field< symmTensor > > invTransform (const UList< symmTensor > &input) const
With constant rotation tensor.
virtual symmTensor invTransform (const point &global, const symmTensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< symmTensor > > invTransform (const UList< point > &global, const symmTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > invTransform (const pointUIndList &global, const symmTensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > invTransform (const UList< point > &global, const UList< symmTensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< symmTensor > > invTransform (const pointUIndList &global, const UList< symmTensor > &input) const
With rotation tensors at given global positions.
virtual tensor invTransform (const tensor &input) const
With constant rotation tensor.
virtual tmp< Field< tensor > > invTransform (const UList< tensor > &input) const
With constant rotation tensor.
virtual tensor invTransform (const point &global, const tensor &input) const
With rotation tensor at given global position.
virtual tmp< Field< tensor > > invTransform (const UList< point > &global, const tensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > invTransform (const pointUIndList &global, const tensor &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > invTransform (const UList< point > &global, const UList< tensor > &input) const
With rotation tensors at given global positions.
virtual tmp< Field< tensor > > invTransform (const pointUIndList &global, const UList< tensor > &input) const
With rotation tensors at given global positions.
template<class PointField >
Foam::tmp< Foam::tensorField > rotationsImpl (const PointField &global) const
template<class PointField >
Foam::tmp< Foam::pointField > transformPointImpl (const PointField &localCart) const
template<class PointField >
Foam::tmp< Foam::pointField > invTransformPointImpl (const PointField &global) const
template<class RetType , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > manyTimesImpl (const tensor &tt, const UList< Type > &input, const BinaryOp &bop)
template<class RetType , class PointField , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > oneToOneImpl (const PointField &global, const UList< Type > &input, const BinaryOp &bop) const
template<class RetType , class PointField , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > oneToManyImpl (const PointField &global, const Type &input, const BinaryOp &bop) const
Static Public Attributes
static const cylindrical null
Protected Member Functions
virtual vector localToGlobal (const vector &local, bool translate) const
virtual tmp< vectorField > localToGlobal (const vectorField &local, bool translate) const
virtual vector globalToLocal (const vector &global, bool translate) const
virtual tmp< vectorField > globalToLocal (const vectorField &global, bool translate) const
Protected Member Functions inherited from coordinateSystem
template<class PointField >
tmp< tensorField > rotationsImpl (const PointField &global) const
template<class PointField >
tmp< pointField > transformPointImpl (const PointField &localCart) const
template<class PointField >
tmp< pointField > invTransformPointImpl (const PointField &global) const
template<class RetType , class PointField , class Type , class BinaryOp >
tmp< Field< RetType > > oneToOneImpl (const PointField &global, const UList< Type > &input, const BinaryOp &bop) const
template<class RetType , class PointField , class Type , class BinaryOp >
tmp< Field< RetType > > oneToManyImpl (const PointField &global, const Type &input, const BinaryOp &bop) const
void assign (const dictionary &dict, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
coordinateSystem (std::nullptr_t)
Additional Inherited Members
Static Public Member Functions inherited from coordinateSystem
static autoPtr< coordinateSystem > New (const word &modelType, const objectRegistry &obr, const dictionary &dict, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
static autoPtr< coordinateSystem > New (const word &modelType, const dictionary &dict, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
static autoPtr< coordinateSystem > New (const objectRegistry &obr, const dictionary &dict, const word &dictName=word::null, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
static autoPtr< coordinateSystem > New (const dictionary &dict, const word &dictName=word::null, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
static autoPtr< coordinateSystem > New (Istream &is, IOobjectOption::readOption readOrigin=IOobjectOption::MUST_READ)
static autoPtr< coordinateSystem > NewIfPresent (const objectRegistry &obr, const dictionary &dict, const word &dictName=coordinateSystem::typeName)
static autoPtr< coordinateSystem > NewIfPresent (const dictionary &dict, const word &dictName=coordinateSystem::typeName)
Static Protected Member Functions inherited from coordinateSystem
template<class RetType , class Type , class BinaryOp >
static tmp< Field< RetType > > manyTimesImpl (const tensor &tt, const UList< Type > &input, const BinaryOp &bop)
Protected Attributes inherited from coordinateSystem
autoPtr< coordinateRotation > spec_
point origin_
tensor rot_
word name_
string note_
Static Protected Attributes inherited from coordinateSystem
static coordinateSystem dummy_
Detailed Description
A cylindrical coordinate system (r-theta-z). The coordinate system angle theta is always in radians.
Dictionary entries
Property Description Required Default
type type name: cylindrical yes
Source files
cylindricalCS.H
cylindricalCS.C
cylindricalCSTransform.C
Definition at line 67 of file cylindricalCS.H.
Constructor & Destructor Documentation
cylindrical() [1/14]
cylindrical () default
cylindrical() [2/14]
cylindrical (const cylindrical & csys) default
cylindrical() [3/14]
cylindrical (cylindrical && csys) default
cylindrical() [4/14]
cylindrical (const coordinateSystem & csys) explicit
Definition at line 84 of file cylindricalCS.C.
cylindrical() [5/14]
cylindrical (coordinateSystem && csys) explicit
Definition at line 90 of file cylindricalCS.C.
cylindrical() [6/14]
cylindrical (autoPtr< coordinateSystem > && csys) explicit
Definition at line 96 of file cylindricalCS.C.
cylindrical() [7/14]
cylindrical (const coordinateRotation & crot) explicit
Definition at line 102 of file cylindricalCS.C.
cylindrical() [8/14]
cylindrical (const point & origin, const coordinateRotation & crot)
Definition at line 108 of file cylindricalCS.C.
cylindrical() [9/14]
cylindrical (const point & origin, const vector & axis)
Definition at line 118 of file cylindricalCS.C.
cylindrical() [10/14]
cylindrical (const word & name, const point & origin, const vector & axis)
Definition at line 128 of file cylindricalCS.C.
cylindrical() [11/14]
cylindrical (const point & origin, const vector & axis, const vector & dirn)
Definition at line 144 of file cylindricalCS.C.
cylindrical() [12/14]
cylindrical (const word & name, const point & origin, const vector & axis, const vector & dirn)
Definition at line 155 of file cylindricalCS.C.
cylindrical() [13/14]
cylindrical (const dictionary & dict, IOobjectOption::readOption readOrigin = IOobjectOption::MUST_READ) explicit
Definition at line 167 of file cylindricalCS.C.
References dict, and Foam::warnCompatDegrees().
cylindrical() [14/14]
cylindrical (const dictionary & dict, const word & dictName, IOobjectOption::readOption readOrigin = IOobjectOption::MUST_READ)
Definition at line 179 of file cylindricalCS.C.
References dict, dictName(), and Foam::warnCompatDegrees().
~cylindrical()
virtual ~cylindrical () virtual default
Member Function Documentation
localToGlobal() [1/2]
Foam::vector localToGlobal (const vector & local, bool translate) const protected virtual
Reimplemented from coordinateSystem.
Definition at line 234 of file cylindricalCS.C.
References local, coordinateSystem::localToGlobal(), and Foam::toCartesian().
localToGlobal() [2/2]
Foam::tmp< Foam::vectorField > localToGlobal (const vectorField & local, bool translate) const protected virtual
Reimplemented from coordinateSystem.
Definition at line 248 of file cylindricalCS.C.
References local, coordinateSystem::localToGlobal(), tmp< T >::New(), UPtrList< T >::size(), and Foam::toCartesian().
globalToLocal() [1/2]
Foam::vector globalToLocal (const vector & global, bool translate) const protected virtual
Reimplemented from coordinateSystem.
Definition at line 273 of file cylindricalCS.C.
References Foam::fromCartesian(), and coordinateSystem::globalToLocal().
globalToLocal() [2/2]
Foam::tmp< Foam::vectorField > globalToLocal (const vectorField & global, bool translate) const protected virtual
Reimplemented from coordinateSystem.
Definition at line 286 of file cylindricalCS.C.
References Foam::fromCartesian(), coordinateSystem::globalToLocal(), and UList< T >::size().
TypeNameNoDebug()
TypeNameNoDebug ("cylindrical")
clone()
virtual autoPtr< coordinateSystem > clone () const inline virtual
Reimplemented from coordinateSystem.
Definition at line 197 of file cylindricalCS.H.
uniform()
virtual bool uniform () const inline virtual
Reimplemented from coordinateSystem.
Definition at line 210 of file cylindricalCS.H.
R() [1/5]
Foam::tensor R (const point & global) const virtual
Reimplemented from coordinateSystem.
Definition at line 201 of file cylindricalCS.C.
References Foam::mag().
Referenced by rotorDiskSource::calculate().
operator=() [1/2]
cylindrical & operator= (const cylindrical &) default
operator=() [2/2]
cylindrical & operator= (cylindrical &&) default
R() [2/5]
virtual const tensor & R () const inline virtual
Reimplemented from coordinateSystem.
Definition at line 597 of file coordinateSystem.H.
R() [3/5]
Foam::tensor R (const point & global) const virtual
Reimplemented from coordinateSystem.
Definition at line 680 of file coordinateSystem.C.
R() [4/5]
Foam::tmp< Foam::tensorField > R (const UList< point > & global) const virtual
Reimplemented from coordinateSystem.
Definition at line 684 of file coordinateSystem.C.
R() [5/5]
Foam::tmp< Foam::tensorField > R (const pointUIndList & global) const virtual
Reimplemented from coordinateSystem.
Definition at line 688 of file coordinateSystem.C.
Member Data Documentation
null
const Foam::coordSystem::cylindrical null static
Definition at line 117 of file cylindricalCS.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/coordinate/systems/cylindricalCS.H
src/OpenFOAM/primitives/coordinate/systems/cylindricalCS.C