OpenFOAM: Sampled< Type > Class Template Reference
Sampled< Type > Class Template Reference
PatchFunction1 to sample an existing field.
#include <Sampled.H>
Public Member Functions
TypeName ("sampled")
void operator= (const Sampled< Type > &)=delete
Sampled (const polyPatch &pp, const word &redirectType, const word &entryName, const dictionary &dict, const bool faceValues=true)
Sampled (const Sampled< Type > &rhs)
Sampled (const Sampled< Type > &rhs, const polyPatch &pp)
virtual tmp< PatchFunction1< Type > > clone () const
virtual tmp< PatchFunction1< Type > > clone (const polyPatch &pp) const
virtual ~Sampled ()=default
const GeometricField< Type, fvPatchField, volMesh > & sampleField () const
virtual tmp< Field< Type > > value (const scalar x) const
virtual bool constant () const
virtual bool uniform () const
virtual tmp< Field< Type > > integrate (const scalar x1, const scalar x2) const
virtual void writeData (Ostream &os) const
Public Member Functions inherited from PatchFunction1< Type >
TypeName ("PatchFunction1") declareRunTimeSelectionTable(autoPtr
PatchFunction1 (const polyPatch &pp, const word &entryName, const bool faceValues=true)
PatchFunction1 (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true)
PatchFunction1 (const PatchFunction1< Type > &rhs)
PatchFunction1 (const PatchFunction1< Type > &rhs, const polyPatch &pp)
virtual ~PatchFunction1 ()=default
virtual bool good () const
virtual tmp< pointField > localPosition (const pointField &globalPos) const
virtual tmp< Field< Type > > transform (const Field< Type > &fld) const
virtual tmp< Field< Type > > transform (const tmp< Field< Type > > &tfld) const
virtual void autoMap (const FieldMapper &mapper)
virtual void rmap (const PatchFunction1< Type > &rhs, const labelList &addr)
Public Member Functions inherited from patchFunction1Base
patchFunction1Base (const polyPatch &pp, const word &entryName, const bool faceValues=true)
patchFunction1Base (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true)
patchFunction1Base (const patchFunction1Base &rhs)
patchFunction1Base (const patchFunction1Base &rhs, const polyPatch &pp)
virtual ~patchFunction1Base ()=default
const word & name () const noexcept
const polyPatch & patch () const noexcept
bool faceValues () const noexcept
label size () const
const objectRegistry * whichDb () const
const objectRegistry & obr () const
const Time & time () const
virtual void userTimeToTime (const Time &t)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from mappedPatchBase
TypeName ("mappedPatchBase")
mappedPatchBase (const polyPatch &)
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vectorField &offsets)
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vector &uniformOffset)
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const scalar normalDistance)
mappedPatchBase (const polyPatch &, const dictionary &)
mappedPatchBase (const polyPatch &, const sampleMode, const dictionary &)
mappedPatchBase (const polyPatch &, const mappedPatchBase &)
mappedPatchBase (const polyPatch &, const mappedPatchBase &, const labelUList &mapAddressing)
virtual ~mappedPatchBase ()
void clearOut ()
void setOffset (const scalar normalDist)
void setOffset (const vector &uniformOffset)
void setOffset (const vectorField &offsets)
sampleMode mode () const noexcept
const word & sampleWorld () const noexcept
const word & sampleRegion () const
const word & samplePatch () const
const word & coupleGroup () const
label sampleSize () const
const vector & offset () const noexcept
const vectorField & offsets () const noexcept
label getCommunicator () const
label comm () const
bool sameWorld () const
bool masterWorld () const
bool sameRegion () const noexcept
uniformDimensionedScalarField & updateSampleMeshTime () const
uniformDimensionedScalarField & updateMeshTime () const
bool upToDate () const
const mapDistribute & map () const
const AMIPatchToPatchInterpolation & AMI (const bool forceUpdate=false) const
bool owner () const
const autoPtr< Foam::searchableSurface > & surfPtr () const
const polyMesh & sampleMesh () const
const polyPatch & samplePolyPatch () const
tmp< pointField > samplePoints () const
const fileName & sampleDatabasePath () const
bool sampleDatabase () const
virtual fileName sendPath (const label proci) const
virtual fileName receivePath (const label proci) const
template<class Type >
void distribute (List< Type > &lst) const
template<class Type , class CombineOp >
void distribute (List< Type > &lst, const CombineOp &cop) const
template<class Type >
void reverseDistribute (List< Type > &lst) const
template<class Type , class CombineOp >
void reverseDistribute (List< Type > &lst, const CombineOp &cop) const
virtual void write (Ostream &os) const
Protected Member Functions
bool haveSampleField () const
Protected Member Functions inherited from PatchFunction1< Type >
void operator= (const PatchFunction1< Type > &)=delete
Protected Member Functions inherited from patchFunction1Base
void operator= (const patchFunction1Base &)=delete
Protected Member Functions inherited from mappedPatchBase
bool addWorldConnection ()
label getWorldCommunicator () const
const polyMesh & lookupMesh (const word &region) const
const polyPatch & lookupPatch (const word &sampleRegion, const word &samplePatch) const
tmp< pointField > facePoints (const polyPatch &) const
void collectSamples (const label mySampleWorld, const pointField &facePoints, pointField &samples, labelList &patchFaceWorlds, labelList &patchFaceProcs, labelList &patchFaces, pointField &patchFc) const
void findLocalSamples (const sampleMode mode, const label sampleWorld, const word &sampleRegion, const word &samplePatch, const pointField &samplePoints, List< nearInfoWorld > &nearest) const
void findSamples (const sampleMode mode, const label myWorldIndex, const pointField &, const labelList &wantedWorlds, const labelList &origProcs, labelList &sampleProcs, labelList &sampleIndices, pointField &sampleLocations) const
tmp< pointField > samplePoints (const pointField &) const
void calcMapping () const
void calcAMI () const
Protected Attributes
word fieldName_
const bool setAverage_
const Type average_
word interpolationScheme_
Protected Attributes inherited from PatchFunction1< Type >
coordinateScaling< Type > coordSys_
Protected Attributes inherited from patchFunction1Base
const word name_
const polyPatch & patch_
const bool faceValues_
Protected Attributes inherited from mappedPatchBase
const polyPatch & patch_
word sampleWorld_
word sampleRegion_
const sampleMode mode_
word samplePatch_
const coupleGroupIdentifier coupleGroup_
const autoPtr< fileName > sampleDatabasePtr_
offsetMode offsetMode_
vector offset_
vectorField offsets_
scalar distance_
label communicator_
bool sameRegion_
autoPtr< mapDistribute > mapPtr_
const bool AMIReverse_
autoPtr< AMIPatchToPatchInterpolation > AMIPtr_
autoPtr< searchableSurface > surfPtr_
dictionary surfDict_
autoPtr< uniformDimensionedScalarField > updateMeshTimePtr_
autoPtr< uniformDimensionedScalarField > updateSampleMeshTimePtr_
Additional Inherited Members
Public Types inherited from PatchFunction1< Type >
typedef Field< Type > returnType
Public Types inherited from mappedPatchBase
enum sampleMode {
NEARESTCELL , NEARESTPATCHFACE , NEARESTPATCHFACEAMI , NEARESTPATCHPOINT ,
NEARESTFACE , NEARESTONLYCELL
}
enum offsetMode { UNIFORM , NONUNIFORM , NORMAL }
typedef Tuple2< pointIndexHit, Tuple2< scalar, label > > nearInfo
typedef Tuple2< nearInfo, label > nearInfoWorld
Static Public Member Functions inherited from PatchFunction1< Type >
static autoPtr< PatchFunction1< Type > > New (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true, const bool mandatory=true)
static autoPtr< PatchFunction1< Type > > NewCompat (const polyPatch &pp, const word &entryName, std::initializer_list< std::pair< const char *, int > > compat, const dictionary &dict, const bool faceValues=true, const bool mandatory=true)
static autoPtr< PatchFunction1< Type > > NewIfPresent (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true)
static refPtr< PatchFunction1< Type > > New (HashPtrTable< PatchFunction1< Type > > &cache, const polyPatch &pp, const word &entryName, const dictionary &dict, enum keyType::option matchOpt=keyType::LITERAL, const bool faceValues=true, const bool mandatory=true)
Static Public Member Functions inherited from mappedPatchBase
static pointIndexHit facePoint (const polyMesh &, const label facei, const polyMesh::cellDecomposition)
static fileName sendPath (const fileName &root, const label proci)
static fileName receivePath (const fileName &root, const label proci)
static const objectRegistry & subRegistry (const objectRegistry &obr, const fileName &path)
template<class Type >
static void storeField (objectRegistry &obr, const word &fieldName, const Field< Type > &values)
static void writeDict (const objectRegistry &obr, dictionary &dict)
static void readDict (const dictionary &d, objectRegistry &obr)
Public Attributes inherited from PatchFunction1< Type >
PatchFunction1
dictionary
const polyPatch & pp
const polyPatch const word & type
const polyPatch const word const word & entryName
const polyPatch const word const word const dictionary & dict
const polyPatch const word const word const dictionary const bool faceValues
const polyPatch const word const word const dictionary const bool pp
const polyPatch const word const word const dictionary const bool type
const polyPatch const word const word const dictionary const bool entryName
const polyPatch const word const word const dictionary const bool dict
Static Public Attributes inherited from mappedPatchBase
static const Enum< sampleMode > sampleModeNames_
static const Enum< offsetMode > offsetModeNames_
Static Protected Member Functions inherited from mappedPatchBase
static autoPtr< fileName > readDatabase (const dictionary &dict)
static const objectRegistry & subRegistry (const objectRegistry &obr, const wordList &names, const label index)
template<class Type >
static bool writeIOField (const regIOobject &obj, dictionary &dict)
template<class Type >
static bool constructIOField (const word &name, token &tok, Istream &is, objectRegistry &obr)
Detailed Description
template<class Type>
class Foam::PatchFunction1Types::Sampled< Type >
PatchFunction1 to sample an existing field.
It is the exact functionality from mappedField boundary condition with the following differences:
the field name is specified. So any derived fields will have the same field name to sample.
if used with uniformFixedValue boundary condition there is the problem that that re-evaluates instead of reading/mapping.
Usage
Property Description Required Default value
field Field name yes
sampleMode how to obtain samples yes
sampleRegion mesh to sample no ""
samplePatch patch to sample no ""
offsetMode how to offset samples no uniform
offset uniform offset vector no (0 0 0)
interpolationScheme interpolation method yes cell
setAverage optional average adjustment no false
average optional average value no
Example of the boundary condition specification:
    <patchName>
    {
        // Field to sample
        field           U;
        // Geometric/mapping info (equivalent of 'mappedPatch' patch type)
        sampleMode      nearestCell;
        offset          (0 -0.001 0);
        // Field specific info (equivalent of 'mappedField' patch field type)
        interpolationScheme cell;
    }
Source files
Sampled.H
Sampled.C
Definition at line 138 of file Sampled.H.
Constructor & Destructor Documentation
Sampled() [1/3]
template<class Type > Sampled (const polyPatch & pp, const word & redirectType, const word & entryName, const dictionary & dict, const bool faceValues = true)
Definition at line 46 of file Sampled.C.
References Sampled< Type >::interpolationScheme_, mappedPatchBase::mode(), mappedPatchBase::NEARESTCELL, and dictionary::readEntry().
Sampled() [2/3]
template<class Type > Sampled (const Sampled< Type > & rhs) explicit
Definition at line 70 of file Sampled.C.
Sampled() [3/3]
template<class Type > Sampled (const Sampled< Type > & rhs, const polyPatch & pp) explicit
Definition at line 80 of file Sampled.C.
~Sampled()
template<class Type > virtual ~Sampled () virtual default
Member Function Documentation
haveSampleField()
template<class Type > bool haveSampleField () const protected
Definition at line 118 of file Sampled.C.
References mappedPatchBase::patch_.
TypeName()
template<class Type > TypeName ("sampled")
operator=()
template<class Type > void operator= (const Sampled< Type > &) delete
clone() [1/2]
template<class Type > virtual tmp< PatchFunction1< Type > > clone () const inline virtual
Implements PatchFunction1< Type >.
Definition at line 208 of file Sampled.H.
clone() [2/2]
template<class Type > virtual tmp< PatchFunction1< Type > > clone (const polyPatch & pp) const inline virtual
Implements PatchFunction1< Type >.
Definition at line 217 of file Sampled.H.
References PatchFunction1< Type >::pp.
sampleField()
template<class Type > const Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > & sampleField () const
Definition at line 99 of file Sampled.C.
References mappedPatchBase::patch_.
value()
template<class Type > Foam::tmp< Foam::Field< Type > > value (const scalar x) const virtual
Reimplemented from PatchFunction1< Type >.
Definition at line 138 of file Sampled.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::gAverage(), Foam::gSum(), Foam::mag(), VectorSpace< Form, Cmpt, Ncmpts >::max, mesh, Foam::mode(), UPstream::msgType(), mappedPatchBase::NEARESTCELL, mappedPatchBase::NEARESTFACE, mappedPatchBase::NEARESTPATCHFACE, mappedPatchBase::NEARESTPATCHFACEAMI, Foam::New(), interpolation< Type >::New(), Foam::nl, mappedPatchBase::patch_, Foam::returnReduceOr(), samples(), PtrList< T >::setSize(), UPtrList< T >::size(), PtrList< T >::transfer(), Foam::transform(), and Foam::Zero.
constant()
template<class Type > virtual bool constant () const inline virtual
Reimplemented from PatchFunction1< Type >.
Definition at line 241 of file Sampled.H.
uniform()
template<class Type > virtual bool uniform () const inline virtual
Implements PatchFunction1< Type >.
Definition at line 247 of file Sampled.H.
integrate()
template<class Type > Foam::tmp< Foam::Field< Type > > integrate (const scalar x1, const scalar x2) const virtual
Reimplemented from PatchFunction1< Type >.
Definition at line 309 of file Sampled.C.
References NotImplemented.
writeData()
template<class Type > void writeData (Ostream & os) const virtual
Reimplemented from PatchFunction1< Type >.
Definition at line 321 of file Sampled.C.
References Foam::name(), os(), Foam::type(), mappedPatchBase::write(), and PatchFunction1< Type >::writeData().
Member Data Documentation
fieldName_
template<class Type > word fieldName_ protected
Definition at line 154 of file Sampled.H.
setAverage_
template<class Type > const bool setAverage_ protected
Definition at line 157 of file Sampled.H.
average_
template<class Type > const Type average_ protected
Definition at line 161 of file Sampled.H.
interpolationScheme_
template<class Type > word interpolationScheme_ protected
Definition at line 164 of file Sampled.H.
Referenced by Sampled< Type >::Sampled().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/mappedField/Sampled/Sampled.H
src/finiteVolume/fields/fvPatchFields/derived/mappedField/Sampled/Sampled.C