OpenFOAM: UpwindFitScheme< Type, Polynomial, Stencil > Class Template Reference
UpwindFitScheme< Type, Polynomial, Stencil > Class Template Reference
Numerics » Finite volume numerical schemes » Surface interpolation schemes
Upwind biased fit surface interpolation scheme that applies an explicit correction to linear.
#include <UpwindFitScheme.H>
Public Member Functions
TypeName ("UpwindFitScheme")
UpwindFitScheme (const fvMesh &mesh, Istream &is)
UpwindFitScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
virtual bool corrected () const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Public Member Functions inherited from linear< Type >
TypeName ("linear")
linear (const fvMesh &mesh)
linear (const fvMesh &mesh, Istream &)
linear (const fvMesh &mesh, const surfaceScalarField &, Istream &)
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
linear (const Specie &sp, const scalar psi, const scalar rho0)
linear (const dictionary &dict)
linear (const word &name, const linear &)
autoPtr< linear > clone () const
scalar rho (scalar p, scalar T) const
scalar H (const scalar p, const scalar T) const
scalar Cp (scalar p, scalar T) const
scalar E (const scalar p, const scalar T) const
scalar Cv (scalar p, scalar T) const
scalar S (const scalar p, const scalar T) const
scalar psi (scalar p, scalar T) const
scalar Z (scalar p, scalar T) const
scalar CpMCv (scalar p, scalar T) const
void write (Ostream &os) const
void operator+= (const linear &)
void operator*= (const scalar)
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
virtual ~surfaceInterpolationScheme ()=default
const fvMesh & mesh () const
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class SFType >
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< typename SFType::value_type, Type >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
tmp< GeometricField< typename innerProduct< vector, scalar >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Foam::tmp< Foam::GeometricField< typename Foam::innerProduct< Foam::vector, Foam::scalar >::type, Foam::fvsPatchField, Foam::surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< scalar, fvPatchField, volMesh > &) const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Additional Inherited Members
Static Public Member Functions inherited from linear< Type >
static autoPtr< linear > New (const dictionary &dict)
static word typeName ()
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Static Public Attributes inherited from linear< Type >
static const bool incompressible = false
static const bool isochoric = false
Detailed Description
template<class Type, class Polynomial, class Stencil>
class Foam::UpwindFitScheme< Type, Polynomial, Stencil >
Upwind biased fit surface interpolation scheme that applies an explicit correction to linear.
Definition at line 47 of file UpwindFitScheme.H.
Constructor & Destructor Documentation
UpwindFitScheme() [1/2]
template<class Type , class Polynomial , class Stencil > UpwindFitScheme (const fvMesh & mesh, Istream & is) inline
Definition at line 85 of file UpwindFitScheme.H.
UpwindFitScheme() [2/2]
template<class Type , class Polynomial , class Stencil > UpwindFitScheme (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Definition at line 95 of file UpwindFitScheme.H.
Member Function Documentation
TypeName()
template<class Type , class Polynomial , class Stencil > TypeName ("UpwindFitScheme< Type, Polynomial, Stencil >")
corrected()
template<class Type , class Polynomial , class Stencil > virtual bool corrected () const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 112 of file UpwindFitScheme.H.
correction()
template<class Type , class Polynomial , class Stencil > virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 119 of file UpwindFitScheme.H.
References surfaceInterpolationScheme< Type >::mesh(), MeshObject< Mesh, MeshObjectType, Type >::New(), and extendedUpwindCellToFaceStencil::weightedSum().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/UpwindFitScheme/UpwindFitScheme.H