OpenFOAM: propellerInfo Class Reference
propellerInfo Class Reference
FunctionObjects » Forces function objects
Calculates propeller performance and wake field properties.
#include <propellerInfo.H>
Public Types
enum class rotationMode { SPECIFIED , MRF }
Public Member Functions
TypeName ("propellerInfo")
propellerInfo (const word &name, const Time &runTime, const dictionary &dict, const bool readFields=true)
propellerInfo (const word &name, const objectRegistry &obr, const dictionary &dict, const bool readFields=true)
virtual ~propellerInfo ()=default
virtual bool read (const dictionary &)
virtual bool execute ()
virtual bool write ()
void UpdateMesh (const mapPolyMesh &mpm)
void movePoints (const polyMesh &mesh)
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &psi, const Type &defaultValue) const
Public Member Functions inherited from forces
TypeName ("forces")
forces (const word &name, const Time &runTime, const dictionary &dict, const bool readFields=true)
forces (const word &name, const objectRegistry &obr, const dictionary &dict, const bool readFields=true)
forces (const forces &)=delete
void operator= (const forces &)=delete
virtual ~forces ()=default
virtual void calcForcesMoments ()
virtual vector forceEff () const
virtual vector momentEff () const
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~fvMeshFunctionObject ()=default
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
virtual ~regionFunctionObject ()=default
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
virtual ~stateFunctionObject ()=default
dictionary & propertyDict ()
bool foundProperty (const word &entryName) const
void clearTrigger ()
label getTrigger () const
bool setTrigger (const label triggeri)
bool getDict (const word &entryName, dictionary &dict) const
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getProperty (const word &entryName, Type &value) const
template<class Type >
void setProperty (const word &entryName, const Type &value)
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
template<class Type >
void setResult (const word &entryName, const Type &value)
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
word resultType (const word &entryName) const
word objectResultType (const word &objectName, const word &entryName) const
wordList objectResultEntries () const
wordList objectResultEntries (const word &objectName) const
void writeResultEntries (Ostream &os) const
void writeResultEntries (const word &objectName, Ostream &os) const
void writeAllResultEntries (Ostream &os) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
virtual ~timeFunctionObject ()=default
const Time & time () const
objectRegistry & storedObjects ()
const objectRegistry & storedObjects () const
Public Member Functions inherited from functionObject
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name, const bool withNamePrefix=defaultUseNamePrefix)
autoPtr< functionObject > clone () const
virtual ~functionObject ()=default
virtual const word & type () const =0
const word & name () const noexcept
bool useNamePrefix () const noexcept
bool useNamePrefix (bool on) noexcept
virtual bool execute (const label subIndex)
virtual bool end ()
virtual bool adjustTimeStep ()
virtual bool filesModified () const
virtual void updateMesh (const mapPolyMesh &mpm)
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
writeFile (const writeFile &wf)
virtual ~writeFile ()=default
virtual OFstream & file ()
virtual bool writeToFile () const
virtual bool canWriteToFile () const
virtual bool canResetFile () const
virtual bool canWriteHeader () const
virtual label charWidth () const
virtual void writeCommented (Ostream &os, const string &str) const
virtual void writeTabbed (Ostream &os, const string &str) const
virtual void writeHeader (Ostream &os, const string &str) const
virtual void writeCurrentTime (Ostream &os) const
virtual void writeBreak (Ostream &os) const
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
template<class Type >
void writeValue (Ostream &os, const Type &val) const
Static Public Attributes
static const Enum< rotationMode > rotationModeNames_
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
static bool defaultUseNamePrefix
static word outputPrefix
Static Public Attributes inherited from writeFile
static label addChars = 8
Protected Member Functions
void setCoordinateSystem (const dictionary &dict)
void setRotationalSpeed ()
void createFiles ()
const volVectorField & U () const
void writePropellerPerformance ()
void writeWake (const vectorField &U, const scalar URef)
void writeAxialWake (const vectorField &U, const scalar URef)
void writeWakeFields (const scalar URef)
void setSampleDiskGeometry (const coordinateSystem &coordSys, const scalar r1, const scalar r2, const scalar nTheta, const label nRadius, faceList &faces, pointField &points) const
void setSampleDiskSurface (const dictionary &dict)
void updateSampleDiskCells ()
scalar meanSampleDiskField (const scalarField &field) const
void writeSampleDiskSurface (const vectorField &U, const vectorField &Ur, const scalar URef)
template<class Type >
tmp< Field< Type > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &psi, const Type &defaultValue) const
propellerInfo (const propellerInfo &)=delete
void operator= (const propellerInfo &)=delete
Protected Member Functions inherited from forces
void setCoordinateSystem (const dictionary &dict, const word &e3Name=word::null, const word &e1Name=word::null)
volVectorField & force ()
volVectorField & moment ()
void initialise ()
void reset ()
tmp< symmTensorField > devRhoReff (const tensorField &gradUp, const label patchi) const
tmp< volScalarField > mu () const
tmp< volScalarField > rho () const
tmp< scalarField > rho (const label patchi) const
scalar rho (const volScalarField &p) const
void addToPatchFields (const label patchi, const vectorField &Md, const vectorField &fP, const vectorField &fV)
void addToInternalField (const labelList &cellIDs, const vectorField &Md, const vectorField &f)
void createIntegratedDataFiles ()
void writeIntegratedDataFileHeader (const word &header, OFstream &os) const
void writeIntegratedDataFiles ()
void writeIntegratedDataFile (const vector &pres, const vector &vis, const vector &internal, OFstream &os) const
void logIntegratedData (const string &descriptor, const vector &pres, const vector &vis, const vector &internal) const
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
void operator= (const fvMeshFunctionObject &)=delete
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
template<class ObjectType >
bool foundObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
template<class ObjectType >
bool storeInDb (const word &fieldName, const tmp< ObjectType > &tfield, const objectRegistry &obr)
bool writeObject (const word &fieldName)
bool clearObject (const word &fieldName)
void clearObjects (const wordList &objNames)
regionFunctionObject (const regionFunctionObject &)=delete
void operator= (const regionFunctionObject &)=delete
Protected Member Functions inherited from stateFunctionObject
const functionObjects::properties & stateDict () const
functionObjects::properties & stateDict ()
stateFunctionObject (const stateFunctionObject &)=delete
void operator= (const stateFunctionObject &)=delete
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
timeFunctionObject (const timeFunctionObject &)=delete
void operator= (const timeFunctionObject &)=delete
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Protected Member Functions inherited from writeFile
void initStream (Ostream &os) const
fileName baseFileDir () const
fileName baseTimeDir () const
fileName filePath (const fileName &fName) const
virtual autoPtr< OFstream > newFile (const fileName &fName) const
virtual autoPtr< OFstream > newFileAtTime (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > newFileAtStartTime (const word &name) const
virtual void resetFile (const word &name)
Omanip< int > valueWidth (const label offset=0) const
void operator= (const writeFile &)=delete
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
virtual autoPtr< OFstream > createFile (const word &name) const
Protected Attributes
scalar radius_
autoPtr< Function1< scalar > > URefPtr_
rotationMode rotationMode_
word MRFName_
scalar n_
bool writePropellerPerformance_
autoPtr< OFstream > propellerPerformanceFilePtr_
bool writeWakeFields_
autoPtr< surfaceWriter > surfaceWriterPtr_
label nTheta_
label nRadial_
pointField points_
bool errorOnPointNotFound_
faceList faces_
labelList cellIds_
boolList pointMask_
word interpolationScheme_
autoPtr< OFstream > wakeFilePtr_
autoPtr< OFstream > axialWakeFilePtr_
scalar nanValue_
Protected Attributes inherited from forces
vector sumPatchForcesP_
vector sumPatchForcesV_
vector sumPatchMomentsP_
vector sumPatchMomentsV_
vector sumInternalForces_
vector sumInternalMoments_
autoPtr< OFstream > forceFilePtr_
autoPtr< OFstream > momentFilePtr_
autoPtr< coordinateSystem > coordSysPtr_
labelHashSet patchSet_
scalar rhoRef_
scalar pRef_
word pName_
word UName_
word rhoName_
word fDName_
bool directForceDensity_
bool porosity_
bool writeFields_
bool initialised_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
const objectRegistry & obr_
const objectRegistry * obrPtr_
Protected Attributes inherited from timeFunctionObject
const Time & time_
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
const fileName prefix_
word fileName_
autoPtr< OFstream > filePtr_
label writePrecision_
bool writeToFile_
bool updateHeader_
bool writtenHeader_
bool useUserTime_
scalar startTime_
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Public Attributes inherited from functionObject
bool log
Detailed Description
Calculates propeller performance and wake field properties.
Controlled by executeControl:
Propeller performance
Thrust coefficient, Kt
Torque coefficient, 10*Kq
Advance coefficient, J
Open water efficiency, etaO
Written to postProcessing/<name>/<time>/propellerPerformance.dat
Controlled by writeControl:
Wake field text file
Wake: 1 - UzMean/URef
Velocity in cylindrical coordinates at xyz locations
Written to postProcessing/<name>/<time>/wake.dat
Axial wake field text file
1 - Uz/URef at r/R and angle
Written to postProcessing/<name>/<time>/axialWake.dat
Velocity surface
Written to postProcessing/<name>/surfaces/<time>/disk.<fileType>
Usage
Example of function object specification:
propellerInfo1
{
    type            propellerInfo;
    libs            (forces);
    writeControl    writeTime;
    patches         ("propeller.*");
    URef            5; // Function1 type; 'constant' form shown here
    rho             rhoInf; // incompressible
    rhoInf          1.2;
    // Optionally write propeller performance data
    writePropellerPerformance yes;
    // Propeller data:
    // Radius
    radius          0.1;
    rotationMode    specified; // specified | MRF
    // rotationMode = specified:
    origin          (0 -0.1 0);
    n               25.15;
    axis            (0 1 0);
    // Optional reference direction for angle (alpha) = 0
    alphaAxis       (1 0 0);
    //// rotationMode = mrf
    //// MRF             MRFZoneName;
    //// (origin, n and axis retrieved from MRF model)
    // Optionally write wake text files
    // Note: controlled by writeControl
    writeWakeFields yes;
    // Sample plane (disk) properties
    // Note: controlled by writeControl
    sampleDisk
    {
        surfaceWriter   vtk;
        r1              0.05;
        r2              0.2;
        nTheta          36;
        nRadial         10;
        interpolationScheme cellPoint;
        errorOnPointNotFound false;
    }
}
Where the entries comprise:
Property Description Required Deflt value
type Type name: propellerInfo yes
log Write to standard output no no
patches Patches included in the forces calculation yes
p Pressure field name no p
U Velocity field name no U
rho Density field name no rho
URef Reference velocity yes
rotationMode Rotation mode (see below) yes
origin Sample disk centre no*
n Revolutions per second no*
axis Propeller axis no*
alphaAxis Axis that defines alpha=0 dir no
MRF Name of MRF zone no*
originOffset Origin offset for MRF mode no (0 0 0)
writePropellerPerformance Write propeller performance text file yes
writeWakeFields Write wake field text files yes
surfaceWriter Sample disk surface writer no*
r1 Sample disk inner radius no 0
r2 Sample disk outer radius no*
nTheta Divisions in theta direction no*
nRadial Divisions in radial direction no*
interpolationScheme Sampling interpolation scheme no* cell
Note
URef is a scalar Function1 type, i.e. supports constant, table, lookup values
rotationMode is used to set the origin, axis and revolutions per second
if set to 'specified' all 3 entries are required
note: origin is the sample disk origin
if set to 'MRF' only the MRF entry is required
to move the sample disk away from the MRF origin, use the originOffset
if writePropellerPerformance is set to on|true:
propellerPerformance text file will be written
if writeWakeFields is set to on|true:
wake and axialWake text files will be written
if the surfaceWriter entry is set, the sample disk surface will be written
extents set according to the r1 and r2 entries
discretised according to the nTheta and nRadial entries
See also
Foam::functionObject::forces Foam::Function1
Source files
propellerInfo.H
propellerInfo.C
Definition at line 298 of file propellerInfo.H.
Member Enumeration Documentation
rotationMode
enum class rotationMode strong
Enumerator
SPECIFIED
MRF
Definition at line 305 of file propellerInfo.H.
Constructor & Destructor Documentation
propellerInfo() [1/3]
propellerInfo (const propellerInfo &) protected delete
propellerInfo() [2/3]
propellerInfo (const word & name, const Time & runTime, const dictionary & dict, const bool readFields = true)
Definition at line 795 of file propellerInfo.C.
References dict, Foam::endl(), Log, and propellerInfo::read().
propellerInfo() [3/3]
propellerInfo (const word & name, const objectRegistry & obr, const dictionary & dict, const bool readFields = true)
Definition at line 833 of file propellerInfo.C.
~propellerInfo()
virtual ~propellerInfo () virtual default
Member Function Documentation
setCoordinateSystem()
void setCoordinateSystem (const dictionary & dict) protected
Definition at line 53 of file propellerInfo.C.
References forces::coordSysPtr_, dict, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::FatalIOError, FatalIOErrorInFunction, UPtrList< T >::get(), fvMeshFunctionObject::mesh_, propellerInfo::MRF, propellerInfo::MRFName_, propellerInfo::n_, Vector< Cmpt >::normalise(), propellerInfo::rotationMode_, propellerInfo::rotationModeNames_, propellerInfo::SPECIFIED, Foam::constant::mathematical::twoPi(), Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
setRotationalSpeed()
void setRotationalSpeed () protected
Definition at line 130 of file propellerInfo.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::constant::mathematical::twoPi().
createFiles()
void createFiles () protected
Definition at line 168 of file propellerInfo.C.
References Foam::nl, os(), and Foam::writeHeader().
U()
const Foam::volVectorField & U () const protected
Definition at line 207 of file propellerInfo.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
writePropellerPerformance()
void writePropellerPerformance () protected
Definition at line 554 of file propellerInfo.C.
References Log, Foam::name(), Foam::nl, os(), Foam::pow4(), Foam::sign(), Foam::sqr(), Foam::tab, Foam::constant::mathematical::twoPi(), and Foam::type().
writeWake()
void writeWake (const vectorField & U, const scalar URef) protected
Definition at line 612 of file propellerInfo.C.
References Foam::endl(), UPtrList< T >::last(), UPstream::master(), Foam::nl, os(), Foam::tab, U, and Foam::writeHeader().
writeAxialWake()
void writeAxialWake (const vectorField & U, const scalar URef) protected
Definition at line 671 of file propellerInfo.C.
References Foam::endl(), UPtrList< T >::last(), UPstream::master(), Foam::nl, os(), Foam::tab, and U.
writeWakeFields()
void writeWakeFields (const scalar URef) protected
Definition at line 731 of file propellerInfo.C.
References Foam::endl(), Foam::interpolate(), U, VectorSpace< Form, Cmpt, Ncmpts >::uniform(), and WarningInFunction.
setSampleDiskGeometry()
void setSampleDiskGeometry (const coordinateSystem & coordSys, const scalar r1, const scalar r2, const scalar nTheta, const label nRadius, faceList & faces, pointField & points) const protected
Definition at line 224 of file propellerInfo.C.
References PtrList< T >::append(), PtrList< T >::clear(), coordinateSystem::globalPosition(), Foam::identity(), coordinateSystem::origin(), p, points, List< T >::setSize(), PtrList< T >::setSize(), and Foam::constant::mathematical::twoPi().
setSampleDiskSurface()
void setSampleDiskSurface (const dictionary & dict) protected
Definition at line 327 of file propellerInfo.C.
References dict, surfaceWriter::formatOptions(), and surfaceWriter::New().
updateSampleDiskCells()
void updateSampleDiskCells () protected
Definition at line 378 of file propellerInfo.C.
References PtrList< T >::append(), polyMesh::CELL_TETS, treeBoundBox::contains(), DebugInfo, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, found, boundBox::inflate(), Pstream::listCombineReduce(), UPstream::myProcNo(), Foam::pos(), Foam::reduce(), and tree().
meanSampleDiskField()
Foam::scalar meanSampleDiskField (const scalarField & field) const protected
Definition at line 476 of file propellerInfo.C.
References f(), Foam::FatalError, FatalErrorInFunction, field(), forAll, and UPtrList< T >::size().
writeSampleDiskSurface()
void writeSampleDiskSurface (const vectorField & U, const vectorField & Ur, const scalar URef) protected
Definition at line 520 of file propellerInfo.C.
References PtrList< T >::clear(), Foam::name(), and U.
interpolate() [1/2]
template<class Type > tmp< Field< Type > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & psi, const Type & defaultValue) const protected
operator=()
void operator= (const propellerInfo &) protected delete
TypeName()
TypeName ("propellerInfo")
read()
bool read (const dictionary & dict) virtual
Reimplemented from forces.
Definition at line 847 of file propellerInfo.C.
References dict, UPtrList< T >::get(), and forces::read().
Referenced by propellerInfo::propellerInfo().
execute()
bool execute () virtual
Reimplemented from forces.
Definition at line 878 of file propellerInfo.C.
References Foam::interpolate(), U, and VectorSpace< Form, Cmpt, Ncmpts >::uniform().
write()
bool write () virtual
Reimplemented from forces.
Definition at line 912 of file propellerInfo.C.
UpdateMesh()
void UpdateMesh (const mapPolyMesh & mpm)
Definition at line 921 of file propellerInfo.C.
movePoints()
void movePoints (const polyMesh & mesh) virtual
Reimplemented from functionObject.
Definition at line 927 of file propellerInfo.C.
interpolate() [2/2]
template<class Type > Foam::tmp< Foam::Field< Type > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & psi, const Type & defaultValue) const
Definition at line 762 of file propellerInfo.C.
References field(), forAll, Pstream::listCombineReduce(), Foam::New(), and psi.
Member Data Documentation
rotationModeNames_
const Foam::Enum< Foam::functionObjects::propellerInfo::rotationMode > rotationModeNames_ static
Definition at line 311 of file propellerInfo.H.
Referenced by propellerInfo::setCoordinateSystem().
radius_
scalar radius_ protected
Definition at line 319 of file propellerInfo.H.
URefPtr_
autoPtr<Function1<scalar> > URefPtr_ protected
Definition at line 322 of file propellerInfo.H.
rotationMode_
rotationMode rotationMode_ protected
Definition at line 325 of file propellerInfo.H.
Referenced by propellerInfo::setCoordinateSystem().
MRFName_
word MRFName_ protected
Definition at line 328 of file propellerInfo.H.
Referenced by propellerInfo::setCoordinateSystem().
n_
scalar n_ protected
Definition at line 331 of file propellerInfo.H.
Referenced by propellerInfo::setCoordinateSystem().
writePropellerPerformance_
bool writePropellerPerformance_ protected
Definition at line 334 of file propellerInfo.H.
propellerPerformanceFilePtr_
autoPtr<OFstream> propellerPerformanceFilePtr_ protected
Definition at line 337 of file propellerInfo.H.
writeWakeFields_
bool writeWakeFields_ protected
Definition at line 340 of file propellerInfo.H.
surfaceWriterPtr_
autoPtr<surfaceWriter> surfaceWriterPtr_ protected
Definition at line 346 of file propellerInfo.H.
nTheta_
label nTheta_ protected
Definition at line 349 of file propellerInfo.H.
nRadial_
label nRadial_ protected
Definition at line 352 of file propellerInfo.H.
points_
pointField points_ protected
Definition at line 355 of file propellerInfo.H.
errorOnPointNotFound_
bool errorOnPointNotFound_ protected
Definition at line 360 of file propellerInfo.H.
faces_
faceList faces_ protected
Definition at line 363 of file propellerInfo.H.
cellIds_
labelList cellIds_ protected
Definition at line 366 of file propellerInfo.H.
pointMask_
boolList pointMask_ protected
Definition at line 369 of file propellerInfo.H.
interpolationScheme_
word interpolationScheme_ protected
Definition at line 372 of file propellerInfo.H.
wakeFilePtr_
autoPtr<OFstream> wakeFilePtr_ protected
Definition at line 375 of file propellerInfo.H.
axialWakeFilePtr_
autoPtr<OFstream> axialWakeFilePtr_ protected
Definition at line 378 of file propellerInfo.H.
nanValue_
scalar nanValue_ protected
Definition at line 382 of file propellerInfo.H.
The documentation for this class was generated from the following files:
src/functionObjects/forces/propellerInfo/propellerInfo.H
src/functionObjects/forces/propellerInfo/propellerInfo.C