OpenFOAM: Poisson Class Reference
Poisson Class Reference
Calculation of approximate distance to nearest patch for all cells and boundary by solving Poisson's equation.
#include <PoissonPatchDistMethod.H>
Public Member Functions
TypeName ("Poisson")
Poisson (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs)
Poisson (const fvMesh &mesh, const labelHashSet &patchIDs)
virtual bool correct (volScalarField &y)
virtual bool correct (volScalarField &y, volVectorField &n)
Public Member Functions inherited from patchDistMethod
TypeName ("patchDistMethod")
declareRunTimeSelectionTable (autoPtr, patchDistMethod, dictionary,(const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs),(dict, mesh, patchIDs))
patchDistMethod (const fvMesh &mesh, const labelHashSet &patchIDs)
virtual ~patchDistMethod ()
const labelHashSet & patchIDs () const
virtual bool movePoints ()
virtual void updateMesh (const mapPolyMesh &)
template<class Type >
Foam::wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Additional Inherited Members
Static Public Member Functions inherited from patchDistMethod
static autoPtr< patchDistMethod > New (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs, const word &defaultPatchDistMethod=word::null)
template<class Type >
static wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Protected Member Functions inherited from patchDistMethod
patchDistMethod (const patchDistMethod &)=delete
void operator= (const patchDistMethod &)=delete
Protected Attributes inherited from patchDistMethod
const fvMesh & mesh_
const labelHashSet patchIDs_
Detailed Description
Calculation of approximate distance to nearest patch for all cells and boundary by solving Poisson's equation.
References:
    D.B. Spalding,
    "Calculation of turbulent heat transfer in cluttered spaces",
    Proc. 10th Int. Heat Transfer Conference, Brighton, UK, (1994).
    E. Fares and W. Schroder,
    "Differential Equation for Approximate Wall Distance",
    Int.J.Numer.Meth., 39:743-762, (2002).
    P.G. Tucker,
    "Differential equation based wall distance computation for DES and
     RANS",
    J.Comp.Phys., Vol. 190, Issue 1, 1 st September, pp. 229-248 (2003)
Example of the wallDist specification in fvSchemes:
    laplacianSchemes
    {
        .
        .
        laplacian(yPsi) Gauss linear corrected;
        .
        .
    }
    wallDist
    {
        method Poisson;
        // Optional entry enabling the calculation
        // of the normal-to-wall field
        nRequired false;
    }
Also the solver specification for yPsi is required in fvSolution, e.g. for simple cases:
    yPsi
    {
        solver          PCG;
        preconditioner  DIC;
        tolerance       1e-5;
        relTol          0;
    }
or for more complex cases:
    yPsi
    {
        solver          GAMG;
        smoother        GaussSeidel;
        cacheAgglomeration true;
        nCellsInCoarsestLevel 10;
        agglomerator    faceAreaPair;
        mergeLevels     1;
        tolerance       1e-5;
        relTol          0;
    }
See also
Foam::patchDistMethod::meshWave Foam::wallDist
Source files
PoissonPatchDistMethod.H
PoissonPatchDistMethod.C
Definition at line 115 of file PoissonPatchDistMethod.H.
Constructor & Destructor Documentation
Poisson() [1/2]
Poisson (const dictionary & dict, const fvMesh & mesh, const labelHashSet & patchIDs)
Definition at line 40 of file PoissonPatchDistMethod.C.
Poisson() [2/2]
Poisson (const fvMesh & mesh, const labelHashSet & patchIDs)
Definition at line 51 of file PoissonPatchDistMethod.C.
Member Function Documentation
TypeName()
TypeName ("Poisson")
correct() [1/2]
bool correct (volScalarField & y) virtual
Implements patchDistMethod.
Definition at line 63 of file PoissonPatchDistMethod.C.
References correct(), GeometricField< vector, fvPatchField, volMesh >::null(), and y.
correct() [2/2]
bool correct (volScalarField & y, volVectorField & n) virtual
Implements patchDistMethod.
Definition at line 69 of file PoissonPatchDistMethod.C.
References Foam::dimLength, Foam::dimless, Foam::fvc::grad(), Foam::fvm::laplacian(), Foam::mag(), Foam::magSqr(), Foam::max(), n, Foam::notNull(), solve(), Foam::sqr(), Foam::sqrt(), y, and Foam::Zero.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/patchDistMethods/Poisson/PoissonPatchDistMethod.H
src/finiteVolume/fvMesh/wallDist/patchDistMethods/Poisson/PoissonPatchDistMethod.C