OpenFOAM: multiBandTransmissivity Class Reference
multiBandTransmissivity Class Reference
multiBandTransmissivity radiation transmissivity for solids.
#include <multiBandTransmissivity.H>
Public Member Functions
TypeName ("multiBandTransmissivity")
multiBandTransmissivity (const dictionary &dict, const polyPatch &p)
virtual ~multiBandTransmissivity ()=default
tmp< scalarField > t (const label bandI=0, vectorField *incomingDirection=nullptr, scalarField *T=nullptr) const
scalar t (const label faceI, const label bandI=0, const vector dir=Zero, const scalar T=0) const
bool isGrey () const
label nBands () const
Public Member Functions inherited from wallTransmissivityModel
TypeName ("wallTransmissivityModel")
declareRunTimeSelectionTable (autoPtr, wallTransmissivityModel, dictionary,(const dictionary &dict, const polyPatch &pp),(dict, pp))
wallTransmissivityModel (const dictionary &dict, const polyPatch &pp)
virtual ~wallTransmissivityModel ()=default
Static Public Attributes
static const label maxBands_ = 5
Additional Inherited Members
Static Public Member Functions inherited from wallTransmissivityModel
static autoPtr< wallTransmissivityModel > New (const dictionary &dict, const polyPatch &pp)
Protected Attributes inherited from wallTransmissivityModel
const polyPatch & pp_
Detailed Description
multiBandTransmissivity radiation transmissivity for solids.
Usage
    wallTransmissivityModel
    {
        type            multiBandTransmissivity;
        transmissivity  (0.3 0.7);
    };
Source files
multiBandTransmissivity.H
multiBandTransmissivity.C
Definition at line 62 of file multiBandTransmissivity.H.
Constructor & Destructor Documentation
multiBandTransmissivity()
multiBandTransmissivity (const dictionary & dict, const polyPatch & p)
Definition at line 44 of file multiBandTransmissivity.C.
References dictionary::readEntry(), and UList< T >::size().
~multiBandTransmissivity()
virtual ~multiBandTransmissivity () virtual default
Member Function Documentation
TypeName()
TypeName ("multiBandTransmissivity")
t() [1/2]
Foam::tmp< Foam::scalarField > t (const label bandI = 0, vectorField * incomingDirection = nullptr, scalarField * T = nullptr) const virtual
Implements wallTransmissivityModel.
Definition at line 63 of file multiBandTransmissivity.C.
References tmp< T >::New().
t() [2/2]
Foam::scalar t (const label faceI, const label bandI = 0, const vector dir = Zero, const scalar T = 0) const virtual
Implements wallTransmissivityModel.
Definition at line 74 of file multiBandTransmissivity.C.
isGrey()
bool isGrey () const inline virtual
Implements wallTransmissivityModel.
Definition at line 130 of file multiBandTransmissivity.H.
nBands()
label nBands () const inline virtual
Implements wallTransmissivityModel.
Definition at line 136 of file multiBandTransmissivity.H.
Member Data Documentation
maxBands_
const label maxBands_ = 5 static
Definition at line 71 of file multiBandTransmissivity.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/wallTransmissivityModel/multiBandTransmissivity/multiBandTransmissivity.H
src/thermophysicalModels/radiation/submodels/wallTransmissivityModel/multiBandTransmissivity/multiBandTransmissivity.C