OpenFOAM: MassTransferPhaseSystem< BasePhaseSystem > Class Template Reference
MassTransferPhaseSystem< BasePhaseSystem > Class Template Reference
Class for mass transfer between phases.
#include <MassTransferPhaseSystem.H>
Public Types
typedef HashTable< autoPtr< interfaceCompositionModel >, phasePairKey, phasePairKey::hash > massTransferModelTable
typedef HashTable< volScalarField::Internal > SuSpTable
Public Member Functions
MassTransferPhaseSystem (const fvMesh &)
virtual ~MassTransferPhaseSystem ()=default
tmp< volScalarField > dmdt (const phasePairKey &key) const
virtual tmp< fvScalarMatrix > heatTransfer (const volScalarField &T)
virtual tmp< fvScalarMatrix > volTransfer (const volScalarField &p)
virtual void correctMassSources (const volScalarField &T)
virtual void alphaTransfer (SuSpTable &Su, SuSpTable &Sp)
virtual void massSpeciesTransfer (const Foam::phaseModel &phase, volScalarField::Internal &Su, volScalarField::Internal &Sp, const word speciesName)
virtual bool includeVolChange ()
Protected Types
typedef HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > dmdtTable
Protected Member Functions
tmp< volScalarField > calculateL (const volScalarField &dmdtNetki, const phasePairKey &keyik, const phasePairKey &keyki, const volScalarField &T) const
Protected Attributes
dmdtTable dmdt_
massTransferModelTable massTransferModels_
Detailed Description
template<class BasePhaseSystem>
class Foam::MassTransferPhaseSystem< BasePhaseSystem >
Class for mass transfer between phases.
Source files
MassTransferPhaseSystem.H
MassTransferPhaseSystem.C
Definition at line 51 of file MassTransferPhaseSystem.H.
Member Typedef Documentation
massTransferModelTable
template<class BasePhaseSystem > typedef HashTable< autoPtr<interfaceCompositionModel>, phasePairKey, phasePairKey::hash > massTransferModelTable
Definition at line 66 of file MassTransferPhaseSystem.H.
SuSpTable
template<class BasePhaseSystem > typedef HashTable<volScalarField::Internal> SuSpTable
Definition at line 69 of file MassTransferPhaseSystem.H.
dmdtTable
template<class BasePhaseSystem > typedef HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > dmdtTable protected
Definition at line 82 of file MassTransferPhaseSystem.H.
Constructor & Destructor Documentation
MassTransferPhaseSystem()
template<class BasePhaseSystem > MassTransferPhaseSystem (const fvMesh & mesh) explicit
Definition at line 34 of file MassTransferPhaseSystem.C.
References IOobjectOption::AUTO_WRITE, Foam::dimDensity, Foam::dimTime, MassTransferPhaseSystem< BasePhaseSystem >::dmdt_, forAllConstIters, HashTable< T, Key, Hash >::found(), IOobject::groupName(), MassTransferPhaseSystem< BasePhaseSystem >::massTransferModels_, mesh, Foam::name(), IOobjectOption::NO_READ, HashPtrTable< T, Key, Hash >::set(), timeName, and Foam::Zero.
~MassTransferPhaseSystem()
template<class BasePhaseSystem > virtual ~MassTransferPhaseSystem () virtual default
Member Function Documentation
calculateL()
template<class BasePhaseSystem > Foam::tmp< Foam::volScalarField > calculateL (const volScalarField & dmdtNetki, const phasePairKey & keyik, const phasePairKey & keyki, const volScalarField & T) const protected
Definition at line 73 of file MassTransferPhaseSystem.C.
References Foam::dimEnergy, Foam::dimMass, L, mesh, Foam::neg(), tmp< T >::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, Foam::pos(), T, timeName, and Foam::Zero.
dmdt()
template<class BasePhaseSystem > Foam::tmp< Foam::volScalarField > dmdt (const phasePairKey & key) const
Definition at line 128 of file MassTransferPhaseSystem.C.
References Foam::dimDensity, Foam::dimTime, mesh, tmp< T >::New(), timeName, and Foam::Zero.
heatTransfer()
template<class BasePhaseSystem > Foam::tmp< Foam::fvScalarMatrix > heatTransfer (const volScalarField & T) virtual
Definition at line 157 of file MassTransferPhaseSystem.C.
References Foam::dimDensity, Foam::dimEnergy, Foam::dimTemperature, Foam::dimTime, UPtrList< T >::end(), forAllConstIters, L, mesh, Foam::name(), tmp< T >::New(), phasei, Sp, Foam::fvm::Sp(), Su, T, interfaceCompositionModel::T, timeName, and Foam::Zero.
volTransfer()
template<class BasePhaseSystem > Foam::tmp< Foam::fvScalarMatrix > volTransfer (const volScalarField & p) virtual
Definition at line 299 of file MassTransferPhaseSystem.C.
References Foam::dimless, Foam::dimPressure, Foam::dimTime, Foam::dimVolume, forAllConstIters, mesh, phaseModel::name(), tmp< T >::New(), p, interfaceCompositionModel::P, phase1, phasePair::phase1(), phase2, phasePair::phase2(), Sp, Foam::fvm::Sp(), Su, timeName, and Foam::Zero.
correctMassSources()
template<class BasePhaseSystem > void correctMassSources (const volScalarField & T) virtual
Definition at line 448 of file MassTransferPhaseSystem.C.
References UPtrList< T >::end(), forAllConstIters, Foam::name(), phasei, and T.
alphaTransfer()
template<class BasePhaseSystem > void alphaTransfer (SuSpTable & Su, SuSpTable & Sp) virtual
Definition at line 499 of file MassTransferPhaseSystem.C.
References interfaceCompositionModel::alpha, alpha1, alpha2, Foam::clamp(), Foam::fvc::div(), forAll, forAllConstIters, Foam::gMax(), Foam::max(), phaseModel::name(), phase1, phasePair::phase1(), phase2, phasePair::phase2(), phi, Sp, and Su.
massSpeciesTransfer()
template<class BasePhaseSystem > void massSpeciesTransfer (const Foam::phaseModel & phase, volScalarField::Internal & Su, volScalarField::Internal & Sp, const word speciesName) virtual
Definition at line 700 of file MassTransferPhaseSystem.C.
References forAllConstIters, phaseModel::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), Sp, and Su.
includeVolChange()
template<class BasePhaseSystem > bool includeVolChange () virtual
Definition at line 723 of file MassTransferPhaseSystem.C.
References forAllIters.
Member Data Documentation
dmdt_
template<class BasePhaseSystem > dmdtTable dmdt_ protected
Definition at line 88 of file MassTransferPhaseSystem.H.
Referenced by MassTransferPhaseSystem< BasePhaseSystem >::MassTransferPhaseSystem().
massTransferModels_
template<class BasePhaseSystem > massTransferModelTable massTransferModels_ protected
Definition at line 91 of file MassTransferPhaseSystem.H.
Referenced by MassTransferPhaseSystem< BasePhaseSystem >::MassTransferPhaseSystem().
The documentation for this class was generated from the following files:
src/phaseSystemModels/multiphaseInter/phasesSystem/MassTransferPhaseSystem/MassTransferPhaseSystem.H
src/phaseSystemModels/multiphaseInter/phasesSystem/MassTransferPhaseSystem/MassTransferPhaseSystem.C