OpenFOAM: patchTransformedInterpolation Class Reference
patchTransformedInterpolation Class Reference
Interpolation of cell-based displacements to the points with additional correction of patch-adjacent cells.
#include <patchTransformedInterpolation.H>
Public Member Functions
TypeName ("patchTransformed")
patchTransformedInterpolation (const fvMesh &mesh, Istream &entry)
virtual ~patchTransformedInterpolation ()
virtual void interpolate (const volScalarField &, pointScalarField &) const
virtual void interpolate (const volVectorField &, pointVectorField &) const
Public Member Functions inherited from motionInterpolation
TypeName ("motionInterpolation")
declareRunTimeSelectionTable (autoPtr, motionInterpolation, Istream,(const fvMesh &mesh, Istream &entry),(mesh, entry))
motionInterpolation (const fvMesh &mesh)
motionInterpolation (const fvMesh &mesh, Istream &entry)
virtual ~motionInterpolation ()
const fvMesh & mesh () const
Additional Inherited Members
Static Public Member Functions inherited from motionInterpolation
static autoPtr< motionInterpolation > New (const fvMesh &mesh)
static autoPtr< motionInterpolation > New (const fvMesh &mesh, Istream &entry)
Detailed Description
Interpolation of cell-based displacements to the points with additional correction of patch-adjacent cells.
Snappy meshes often have moderately non-orthogonal faces next to patches. If these partches are moved, these already quite distorted faces quickly violate the quality criteria.
This method corrects patch-adjacent cells are by calculating the average translation, rotation and expansion of points connected to the patch. This transformation is then applied to all the points in the cell that are not on the patch. This does a better job of preserving the cell shape on the patch than pure interpolation, though it can simply move the problem into the next layer of cells.
The user needs only to specify the patches on which this correction is performed:
    interpolation patchTransformed (movingPatch1 movingPatch2);
Note that this method is not defined for scalar displacement fields.
Source files
patchTransformedInterpolation.H
patchTransformedInterpolation.C
Definition at line 67 of file patchTransformedInterpolation.H.
Constructor & Destructor Documentation
patchTransformedInterpolation()
patchTransformedInterpolation (const fvMesh & mesh, Istream & entry)
Definition at line 76 of file patchTransformedInterpolation.C.
~patchTransformedInterpolation()
~patchTransformedInterpolation () virtual
Definition at line 89 of file patchTransformedInterpolation.C.
Member Function Documentation
TypeName()
TypeName ("patchTransformed")
interpolate() [1/2]
void interpolate (const volScalarField & , pointScalarField &) const virtual
Reimplemented from motionInterpolation.
Definition at line 95 of file patchTransformedInterpolation.C.
References NotImplemented.
interpolate() [2/2]
void interpolate (const volVectorField & cellDisplacement, pointVectorField & pointDisplacement) const virtual
Reimplemented from motionInterpolation.
Definition at line 105 of file patchTransformedInterpolation.C.
References cells, GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), f(), forAll, Foam::magSqr(), mesh, MeshObject< fvMesh, UpdateableMeshObject, volPointInterpolation >::New(), nPoints, points, UPtrList< T >::size(), syncTools::syncPointList(), x, Foam::Zero, and VectorSpace< Form, Cmpt, Ncmpts >::zero.
The documentation for this class was generated from the following files:
src/fvMotionSolver/motionInterpolation/patchTransformed/patchTransformedInterpolation.H
src/fvMotionSolver/motionInterpolation/patchTransformed/patchTransformedInterpolation.C