OpenFOAM: ensightFaces Class Reference
ensightFaces Class Reference
Sorting/classification of faces (2D) into corresponding ensight types.
#include <ensightFaces.H>
Public Types
enum elemType { TRIA3 = 0 , QUAD4 , NSIDED }
Public Member Functions
TypeName ("ensightFaces")
ensightFaces ()
ensightFaces (const string &description)
virtual ~ensightFaces ()=default
label size (const elemType etype) const
labelRange range (const elemType etype) const
label totalSize () const noexcept
label total () const noexcept
label total (const elemType etype) const
const FixedList< label, nTypes > & totals () const
FixedList< label, nTypes > sizes () const
const labelList & faceIds () const noexcept
const labelUList faceIds (const elemType etype) const
const boolList & flipMap () const
bool usesFlipMap () const
const labelList & faceOrder () const noexcept
const labelUList faceOrder (const elemType etype) const
void classify (const UList< face > &faces)
void classify (const UList< face > &faces, const labelRange &range)
void classify (const UList< face > &faces, const labelUList &addr, const boolList &flipMap=boolList(), const bitSet &exclude=bitSet())
void clearOut ()
void clear ()
void reduce ()
void sort ()
void incrFaceIds (const label off)
void decrFaceIds (const label off)
InfoProxy< ensightFaces > info () const noexcept
label uniqueMeshPoints (const polyMesh &mesh, labelList &uniqueMeshPointLabels, bool parallel) const
virtual void writeDict (Ostream &os, const bool full=false) const
virtual void write (ensightGeoFile &os, const polyMesh &mesh, bool parallel) const
label size () const noexcept
Public Member Functions inherited from ensightPart
TypeNameNoDebug ("ensightPart")
ensightPart ()
ensightPart (const string &description)
virtual ~ensightPart ()=default
label index () const noexcept
label & index () noexcept
label identifier () const noexcept
label & identifier () noexcept
bool empty () const noexcept
label size () const noexcept
const string & name () const noexcept
void rename (const string &value)
void rename (string &&value)
label operator[] (const label i) const
Static Public Member Functions
static const char * key (const elemType etype) noexcept
Static Public Attributes
static constexpr int nTypes = 3
static const char * elemNames [nTypes]
Additional Inherited Members
Protected Member Functions inherited from ensightPart
const labelList & addressing () const noexcept
labelList & addressing () noexcept
void clear ()
void incrAddressing (const label off)
void decrAddressing (const label off)
Detailed Description
Sorting/classification of faces (2D) into corresponding ensight types.
Some caution may be required when handling face addressing into a boundaryField. Since the face addressing is absolute, it will be necessary to work on a copy with local ids. For example,
// Operate on a copy
ensightFaces localPart(part);
// Change from global faceIds to patch-local faceIds
localPart.decrFaceIds(patchStart);
// Can now address into boundaryField
Additionally, for some uses (eg, finiteArea), the ordered list of faces can be used for a direct local lookup into the field instead of via the overall mesh face addressing.
Definition at line 66 of file ensightFaces.H.
Member Enumeration Documentation
elemType
enum elemType
Enumerator
TRIA3
"tria3"
QUAD4
"quad4"
NSIDED
"nsided"
Definition at line 76 of file ensightFaces.H.
Constructor & Destructor Documentation
ensightFaces() [1/2]
ensightFaces ()
Definition at line 96 of file ensightFaces.C.
ensightFaces() [2/2]
ensightFaces (const string & description) explicit
Definition at line 106 of file ensightFaces.C.
References ensightPart::rename().
~ensightFaces()
virtual ~ensightFaces () virtual default
Member Function Documentation
key()
const char * key (const elemType etype) inline static noexcept
Definition at line 42 of file ensightFacesI.H.
Referenced by ensightFaces::writeDict().
TypeName()
TypeName ("ensightFaces")
size() [1/2]
Foam::label size (const elemType etype) const inline
Definition at line 60 of file ensightFacesI.H.
Referenced by Foam::ensightOutput::Detail::writeFaceLocalField(), Foam::ensightOutput::Detail::writeFaceSubField(), Foam::ensightOutput::writeField(), and Foam::ensightOutput::writeVolField().
range()
Foam::labelRange range (const elemType etype) const inline
Definition at line 66 of file ensightFacesI.H.
Referenced by Foam::ensightOutput::writeFaceConnectivityPresorted(), and Foam::ensightOutput::Detail::writeFaceSubField().
totalSize()
Foam::label totalSize () const noexcept
Definition at line 129 of file ensightFaces.C.
References n.
Referenced by ensightFaces::total().
total() [1/2]
label total () const inline noexcept
Definition at line 161 of file ensightFaces.H.
References ensightFaces::totalSize().
Referenced by ensightMesh::correct(), Foam::ensightOutput::writeFaceConnectivity(), Foam::ensightOutput::writeFaceConnectivityPresorted(), Foam::ensightOutput::Detail::writeFaceLocalField(), Foam::ensightOutput::Detail::writeFaceSubField(), and Foam::ensightOutput::writeField().
total() [2/2]
Foam::label total (const elemType etype) const inline
Definition at line 54 of file ensightFacesI.H.
totals()
const Foam::FixedList< Foam::label, 3 > & totals () const inline
Definition at line 48 of file ensightFacesI.H.
sizes()
Foam::FixedList< Foam::label, 3 > sizes () const
Definition at line 116 of file ensightFaces.C.
faceIds() [1/2]
const Foam::labelList & faceIds () const inline noexcept
Definition at line 72 of file ensightFacesI.H.
Referenced by ensightFaces::uniqueMeshPoints(), ensightFaces::write(), Foam::ensightOutput::writeFaceConnectivity(), Foam::ensightOutput::writeField(), and Foam::ensightOutput::writeVolField().
faceIds() [2/2]
const Foam::labelUList faceIds (const elemType etype) const inline
Definition at line 79 of file ensightFacesI.H.
References range.
flipMap()
const Foam::boolList & flipMap () const inline
Definition at line 85 of file ensightFacesI.H.
Referenced by ensightFaces::write().
usesFlipMap()
bool usesFlipMap () const inline
Definition at line 91 of file ensightFacesI.H.
Referenced by ensightFaces::write().
faceOrder() [1/2]
const Foam::labelList & faceOrder () const inline noexcept
Definition at line 98 of file ensightFacesI.H.
Referenced by Foam::ensightOutput::Detail::writeFaceLocalField().
faceOrder() [2/2]
const Foam::labelUList faceOrder (const elemType etype) const inline
Definition at line 105 of file ensightFacesI.H.
References range.
classify() [1/3]
void classify (const UList< face > & faces)
Definition at line 211 of file ensightFaces.C.
References Foam::add(), UPtrList< T >::size(), and Foam::Zero.
Referenced by ensightMesh::correct(), ensightFaMesh::correct(), and ensightOutputSurface::ensightOutputSurface().
classify() [2/3]
void classify (const UList< face > & faces, const labelRange & range)
Definition at line 239 of file ensightFaces.C.
References range, UPtrList< T >::size(), and IntRange< IntType >::start().
classify() [3/3]
void classify (const UList< face > & faces, const labelUList & addr, const boolList & flipMap = boolList(), const bitSet & exclude = bitSet())
Definition at line 255 of file ensightFaces.C.
References Foam::add(), faceId(), PtrList< T >::resize(), UPtrList< T >::size(), UList< T >::size(), UList< T >::test(), UPtrList< T >::test(), and Foam::Zero.
clearOut()
void clearOut ()
Definition at line 153 of file ensightFaces.C.
clear()
void clear ()
Definition at line 140 of file ensightFaces.C.
References ensightPart::clear(), and Foam::Zero.
Referenced by ensightMesh::correct(), and ensightFaMesh::correct().
reduce()
void reduce ()
Definition at line 157 of file ensightFaces.C.
References Foam::reduce().
Referenced by ensightMesh::correct(), and ensightFaMesh::correct().
sort()
void sort ()
Definition at line 167 of file ensightFaces.C.
References PtrList< T >::clear(), UPtrList< T >::empty(), range, and Foam::sortedOrder().
incrFaceIds()
void incrFaceIds (const label off) inline
Definition at line 111 of file ensightFacesI.H.
decrFaceIds()
void decrFaceIds (const label off) inline
Definition at line 117 of file ensightFacesI.H.
info()
InfoProxy< ensightFaces > info () const inline noexcept
Definition at line 245 of file ensightFaces.H.
Referenced by ensightMesh::correct(), and ensightFaMesh::correct().
uniqueMeshPoints()
Foam::label uniqueMeshPoints (const polyMesh & mesh, labelList & uniqueMeshPointLabels, bool parallel) const
Definition at line 31 of file ensightFacesAddr.C.
References ensightFaces::faceIds(), mesh, nPoints, UPstream::parRun(), points, pp(), and UPtrList< T >::size().
Referenced by Foam::ensightOutput::writePointField().
writeDict()
void writeDict (Ostream & os, const bool full = false) const virtual
Reimplemented from ensightPart.
Definition at line 317 of file ensightFaces.C.
References Ostream::beginBlock(), Ostream::endBlock(), Foam::endEntry(), ensightFaces::key(), Foam::name(), ensightFaces::nTypes, os(), Foam::type(), Ostream::writeEntry(), and Ostream::writeKeyword().
write()
void write (ensightGeoFile & os, const polyMesh & mesh, bool parallel) const virtual
< Collective write?
< Collective write?
Reimplemented in ensightOutputSurface.
Definition at line 31 of file ensightFacesIO.C.
References f(), ensightFaces::faceIds(), ensightFaces::flipMap(), forAll, Foam::ListOps::identity(), ensightPart::index(), Foam::ListListOps::inplaceRenumber(), mesh, ensightPart::name(), nPoints, os(), UPstream::parRun(), points, pp(), PtrList< T >::resize(), UPtrList< T >::size(), ensightFaces::usesFlipMap(), Foam::ensightOutput::Detail::writeCoordinates(), and Foam::ensightOutput::writeFaceConnectivityPresorted().
size() [2/2]
label size () const inline noexcept
Definition at line 150 of file ensightPart.H.
Member Data Documentation
nTypes
constexpr int nTypes = 3 static constexpr
Definition at line 84 of file ensightFaces.H.
Referenced by Foam::operator<<(), and ensightFaces::writeDict().
elemNames
const char * elemNames static
Initial value:
=
{
    "tria3", "quad4", "nsided"
}
Definition at line 32 of file ensightFaces.H.
Referenced by Foam::operator<<(), ensightSurfaceReader::readField(), and ensightSurfaceReader::readGeometry().
The documentation for this class was generated from the following files:
src/fileFormats/ensight/part/faces/ensightFaces.H
src/fileFormats/ensight/part/faces/ensightFaces.C
src/fileFormats/ensight/part/faces/ensightFacesAddr.C
src/fileFormats/ensight/part/faces/ensightFacesI.H
src/fileFormats/ensight/part/faces/ensightFacesIO.C