OpenFOAM: freestreamVelocityFvPatchVectorField Class Reference
freestreamVelocityFvPatchVectorField Class Reference
Boundary conditions » Inlet | Boundary conditions » Outlet
This boundary condition provides a free-stream condition for velocity.
#include <freestreamVelocityFvPatchVectorField.H>
Public Member Functions
TypeName ("freestreamVelocity")
freestreamVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
freestreamVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
freestreamVelocityFvPatchVectorField (const freestreamVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
freestreamVelocityFvPatchVectorField (const freestreamVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
freestreamVelocityFvPatchVectorField (const freestreamVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
const vectorField & freestreamValue () const
vectorField & freestreamValue ()
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
This boundary condition provides a free-stream condition for velocity.
It is an inlet-outlet condition that uses the velocity orientation to continuously blend between fixed value for normal inlet and zero gradient for normal outlet flow.
Usage
Property Description Required Default value
freestreamValue freestream velocity yes
Example of the boundary condition specification:
    <patchName>
    {
        type            freestreamVelocity;
        freestreamValue uniform (300 0 0);
    }
Note
This condition is designed to operate with the freestreamPressure condition
See also
Foam::mixedFvPatchField Foam::freestreamFvPatchField
Source files
freestreamVelocityFvPatchVectorField.H
freestreamVelocityFvPatchVectorField.C
Definition at line 86 of file freestreamVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
freestreamVelocityFvPatchVectorField() [1/5]
freestreamVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 26 of file freestreamVelocityFvPatchVectorField.C.
freestreamVelocityFvPatchVectorField() [2/5]
freestreamVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 36 of file freestreamVelocityFvPatchVectorField.C.
References dict, freestreamVelocityFvPatchVectorField::freestreamValue(), fvPatchField< vector >::operator=(), p, and Foam::Zero.
freestreamVelocityFvPatchVectorField() [3/5]
freestreamVelocityFvPatchVectorField (const freestreamVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 57 of file freestreamVelocityFvPatchVectorField.C.
freestreamVelocityFvPatchVectorField() [4/5]
freestreamVelocityFvPatchVectorField (const freestreamVelocityFvPatchVectorField & wbppsf)
Definition at line 69 of file freestreamVelocityFvPatchVectorField.C.
freestreamVelocityFvPatchVectorField() [5/5]
freestreamVelocityFvPatchVectorField (const freestreamVelocityFvPatchVectorField & wbppsf, const DimensionedField< vector, volMesh > & iF)
Definition at line 78 of file freestreamVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("freestreamVelocity")
clone() [1/2]
virtual tmp< fvPatchVectorField > clone () const inline virtual
Definition at line 131 of file freestreamVelocityFvPatchVectorField.H.
clone() [2/2]
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 147 of file freestreamVelocityFvPatchVectorField.H.
freestreamValue() [1/2]
const vectorField & freestreamValue () const inline
Definition at line 162 of file freestreamVelocityFvPatchVectorField.H.
Referenced by freestreamVelocityFvPatchVectorField::freestreamVelocityFvPatchVectorField().
freestreamValue() [2/2]
vectorField & freestreamValue () inline
Definition at line 165 of file freestreamVelocityFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Definition at line 90 of file freestreamVelocityFvPatchVectorField.C.
References Foam::mag(), and fvPatchField< Type >::updateCoeffs().
write()
void write (Ostream & os) const virtual
Definition at line 105 of file freestreamVelocityFvPatchVectorField.C.
References os(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeValueEntry().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/freestreamVelocity/freestreamVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/freestreamVelocity/freestreamVelocityFvPatchVectorField.C