OpenFOAM: WallCollisionRecord< Type > Class Template Reference
WallCollisionRecord< Type > Class Template Reference
Record of a collision between the particle holding the record and a wall face at the position relative to the centre of the particle.
#include <WallCollisionRecord.H>
Public Member Functions
WallCollisionRecord ()
WallCollisionRecord (bool accessed, const vector &pRel, const Type &data=Type(Zero))
WallCollisionRecord (Istream &)
WallCollisionRecord (const WallCollisionRecord &)
~WallCollisionRecord ()
const vector & pRel () const
const Type & collisionData () const
Type & collisionData ()
bool match (const vector &pRel, scalar radius)
bool accessed () const
void setAccessed ()
void setUnaccessed ()
void operator= (const WallCollisionRecord &)
Static Public Attributes
static const scalar errorCosAngle
Friends
bool operator== (const WallCollisionRecord< Type > &, const WallCollisionRecord< Type > &)
bool operator!= (const WallCollisionRecord< Type > &, const WallCollisionRecord< Type > &)
Istream & operator>> (Istream &, WallCollisionRecord< Type > &)
Ostream & operator<< (Ostream &, const WallCollisionRecord< Type > &)
Detailed Description
template<class Type>
class Foam::WallCollisionRecord< Type >
Record of a collision between the particle holding the record and a wall face at the position relative to the centre of the particle.
Source files
WallCollisionRecord.H
WallCollisionRecordI.H
WallCollisionRecord.C
WallCollisionRecordIO.C
Definition at line 75 of file WallCollisionRecord.H.
Constructor & Destructor Documentation
WallCollisionRecord() [1/4]
template<class Type > WallCollisionRecord ()
Definition at line 33 of file WallCollisionRecord.C.
WallCollisionRecord() [2/4]
template<class Type > WallCollisionRecord (bool accessed, const vector & pRel, const Type & data = Type(Zero))
Definition at line 42 of file WallCollisionRecord.C.
WallCollisionRecord() [3/4]
template<class Type > WallCollisionRecord (Istream & is)
Definition at line 27 of file WallCollisionRecordIO.C.
References FUNCTION_NAME.
WallCollisionRecord() [4/4]
template<class Type > WallCollisionRecord (const WallCollisionRecord< Type > &)
~WallCollisionRecord()
template<class Type > ~WallCollisionRecord ()
Definition at line 70 of file WallCollisionRecord.C.
Member Function Documentation
pRel()
template<class Type > const Foam::vector & pRel () const inline
Definition at line 68 of file WallCollisionRecordI.H.
collisionData() [1/2]
template<class Type > const Type & collisionData () const inline
Definition at line 76 of file WallCollisionRecordI.H.
collisionData() [2/2]
template<class Type > Type & collisionData () inline
Definition at line 83 of file WallCollisionRecordI.H.
match()
template<class Type > bool match (const vector & pRel, scalar radius) inline
Definition at line 24 of file WallCollisionRecordI.H.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::Info, Foam::mag(), Foam::nl, and PtrList< T >::PtrList().
accessed()
template<class Type > bool accessed () const inline
Definition at line 90 of file WallCollisionRecordI.H.
setAccessed()
template<class Type > void setAccessed () inline
Definition at line 97 of file WallCollisionRecordI.H.
setUnaccessed()
template<class Type > void setUnaccessed () inline
Definition at line 104 of file WallCollisionRecordI.H.
operator=()
template<class Type > void operator= (const WallCollisionRecord< Type > &)
Definition at line 77 of file WallCollisionRecord.C.
Friends And Related Symbol Documentation
operator==
template<class Type > bool operator== (const WallCollisionRecord< Type > & , const WallCollisionRecord< Type > &) friend
operator!=
template<class Type > bool operator!= (const WallCollisionRecord< Type > & , const WallCollisionRecord< Type > &) friend
operator>>
template<class Type > Istream & operator>> (Istream & , WallCollisionRecord< Type > &) friend
operator<<
template<class Type > Ostream & operator<< (Ostream & , const WallCollisionRecord< Type > &) friend
Member Data Documentation
errorCosAngle
template<class Type > const Foam::scalar errorCosAngle static
Definition at line 95 of file WallCollisionRecord.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/WallCollisionRecord/WallCollisionRecord.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/WallCollisionRecord/WallCollisionRecord.C
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/WallCollisionRecord/WallCollisionRecordI.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/WallCollisionRecord/WallCollisionRecordIO.C