OpenFOAM: variablesSet Class Reference
variablesSet Class Reference
Base class for creating a set of variables.
#include <variablesSet.H>
Public Member Functions
TypeName ("variablesSet")
variablesSet (fvMesh &mesh, const dictionary &dict)
virtual autoPtr< variablesSet > clone () const
virtual ~variablesSet ()=default
const word & solverName () const
bool useSolverNameForFields () const
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > allocateField (const fvMesh &mesh, const word &baseName, const word &solverName, const bool useSolverNameForFields)
template<class Type >
void renameTurbulenceField (GeometricField< Type, fvPatchField, volMesh > &baseField, const word &solverName)
tmp< surfaceScalarField > allocateFluxField (const fvMesh &mesh, const volVectorField &velocity, const word &baseName, const word &solverName, const bool useSolverNameForFields)
virtual void transfer (variablesSet &vars)
Static Public Member Functions
template<class Type >
static void setField (autoPtr< GeometricField< Type, fvPatchField, volMesh > > &fieldPtr, const fvMesh &mesh, const word &baseName, const word &solverName, const bool useSolverNameForFields)
static void setFluxField (autoPtr< surfaceScalarField > &fieldPtr, const fvMesh &mesh, const volVectorField &velocity, const word &baseName, const word &solverName, const bool useSolverNameForFields)
static tmp< volVectorField > autoCreateMeshMovementField (const fvMesh &mesh, const word &name, const dimensionSet &dims)
template<class Type , template< class > class PatchField, class GeoMesh >
static void nullifyField (GeometricField< Type, PatchField, GeoMesh > &fieldPtr)
Protected Member Functions
template<class Type , template< class > class PatchField, class GeoMesh >
autoPtr< GeometricField< Type, PatchField, GeoMesh > > allocateRenamedField (const autoPtr< GeometricField< Type, PatchField, GeoMesh > > &bf)
template<class Type , template< class > class PatchField, class GeoMesh >
void swapAndRename (autoPtr< GeometricField< Type, PatchField, GeoMesh > > &p1, autoPtr< GeometricField< Type, PatchField, GeoMesh > > &p2)
Protected Attributes
fvMesh & mesh_
word solverName_
bool useSolverNameForFields_
Detailed Description
Base class for creating a set of variables.
Definition at line 43 of file variablesSet.H.
Constructor & Destructor Documentation
variablesSet()
variablesSet (fvMesh & mesh, const dictionary & dict)
Definition at line 53 of file variablesSet.C.
~variablesSet()
virtual ~variablesSet () virtual default
Member Function Documentation
allocateRenamedField()
template<class Type , template< class > class PatchField, class GeoMesh > autoPtr< GeometricField< Type, PatchField, GeoMesh > > allocateRenamedField (const autoPtr< GeometricField< Type, PatchField, GeoMesh > > & bf) protected
Definition at line 159 of file variablesSetTemplates.C.
References Foam::name(), and timeName.
swapAndRename()
template<class Type , template< class > class PatchField, class GeoMesh > void swapAndRename (autoPtr< GeometricField< Type, PatchField, GeoMesh > > & p1, autoPtr< GeometricField< Type, PatchField, GeoMesh > > & p2) protected
Definition at line 183 of file variablesSetTemplates.C.
Referenced by incompressibleVars::transfer().
TypeName()
TypeName ("variablesSet")
clone()
autoPtr< variablesSet > clone () const virtual
Reimplemented in incompressibleVars.
Definition at line 68 of file variablesSet.C.
References NotImplemented.
Referenced by variablesSet::renameTurbulenceField().
solverName()
const word & solverName () const
Definition at line 77 of file variablesSet.C.
References variablesSet::solverName_.
Referenced by FIBase::accumulateIntegrand(), adjointkOmegaSST::adjointkOmegaSST(), adjointSensitivity::adjointMeshMovementSource(), adjointRASModel::adjointSolverName(), adjointSpalartAllmaras::adjointSpalartAllmaras(), variablesSet::allocateField(), variablesSet::allocateFluxField(), adjointRASModel::primalSolverName(), variablesSet::renameTurbulenceField(), variablesSet::setField(), variablesSet::setFluxField(), sensitivitySurface::setSuffixName(), sensitivitySurfacePoints::setSuffixName(), sensitivityBezier::write(), sensitivityBezierFI::write(), sensitivityVolBSplines::write(), and sensitivityVolBSplinesFI::write().
useSolverNameForFields()
bool useSolverNameForFields () const
Definition at line 83 of file variablesSet.C.
References variablesSet::useSolverNameForFields_.
Referenced by adjointkOmegaSST::adjointkOmegaSST(), adjointSpalartAllmaras::adjointSpalartAllmaras(), variablesSet::allocateField(), variablesSet::allocateFluxField(), variablesSet::setField(), and variablesSet::setFluxField().
setField()
template<class Type > void setField (autoPtr< GeometricField< Type, fvPatchField, volMesh > > & fieldPtr, const fvMesh & mesh, const word & baseName, const word & solverName, const bool useSolverNameForFields) static
Definition at line 214 of file variablesSetTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, variablesSet::solverName(), and variablesSet::useSolverNameForFields().
Referenced by adjointkOmegaSST::adjointkOmegaSST(), adjointSpalartAllmaras::adjointSpalartAllmaras(), variablesSet::allocateField(), incompressibleVars::setFields(), and incompressibleAdjointMeanFlowVars::setFields().
allocateField()
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > allocateField (const fvMesh & mesh, const word & baseName, const word & solverName, const bool useSolverNameForFields)
Definition at line 249 of file variablesSetTemplates.C.
References mesh, variablesSet::setField(), variablesSet::solverName(), and variablesSet::useSolverNameForFields().
renameTurbulenceField()
template<class Type > void renameTurbulenceField (GeometricField< Type, fvPatchField, volMesh > & baseField, const word & solverName)
Definition at line 267 of file variablesSetTemplates.C.
References IOobjectOption::AUTO_WRITE, variablesSet::clone(), Foam::endl(), forAll, Foam::Info, mesh, IOobjectOption::MUST_READ, Foam::nl, IOobjectOption::NO_REGISTER, PtrList< T >::set(), and variablesSet::solverName().
Referenced by incompressibleVars::renameTurbulenceFields().
setFluxField()
void setFluxField (autoPtr< surfaceScalarField > & fieldPtr, const fvMesh & mesh, const volVectorField & velocity, const word & baseName, const word & solverName, const bool useSolverNameForFields) static
Definition at line 89 of file variablesSet.C.
References IOobjectOption::AUTO_WRITE, Foam::linearInterpolate(), mesh, IOobjectOption::READ_IF_PRESENT, variablesSet::solverName(), and variablesSet::useSolverNameForFields().
Referenced by variablesSet::allocateFluxField(), incompressibleVars::setFields(), and incompressibleAdjointMeanFlowVars::setFields().
allocateFluxField()
tmp< surfaceScalarField > allocateFluxField (const fvMesh & mesh, const volVectorField & velocity, const word & baseName, const word & solverName, const bool useSolverNameForFields)
Definition at line 141 of file variablesSet.C.
References mesh, variablesSet::setFluxField(), variablesSet::solverName(), and variablesSet::useSolverNameForFields().
autoCreateMeshMovementField()
tmp< volVectorField > autoCreateMeshMovementField (const fvMesh & mesh, const word & name, const dimensionSet & dims) static
Definition at line 165 of file variablesSet.C.
References mesh, tmp< T >::New(), IOobjectOption::NO_WRITE, IOobjectOption::READ_IF_PRESENT, and Foam::Zero.
nullifyField()
template<class Type , template< class > class PatchField, class GeoMesh > void nullifyField (GeometricField< Type, PatchField, GeoMesh > & fieldPtr) static
Definition at line 339 of file variablesSetTemplates.C.
References field(), variablesSet::nullifyField(), oldTime(), and Foam::Zero.
Referenced by incompressibleAdjointMeanFlowVars::nullify(), adjointkOmegaSST::nullify(), adjointSpalartAllmaras::nullify(), and variablesSet::nullifyField().
transfer()
void transfer (variablesSet & vars) virtual
Reimplemented in incompressibleVars.
Definition at line 189 of file variablesSet.C.
Member Data Documentation
mesh_
fvMesh& mesh_ protected
Definition at line 86 of file variablesSet.H.
Referenced by incompressibleVars::setFields(), incompressibleAdjointMeanFlowVars::setFields(), incompressibleVars::setMeanFields(), incompressibleAdjointMeanFlowVars::setMeanFields(), and incompressibleVars::write().
solverName_
word solverName_ protected
Definition at line 89 of file variablesSet.H.
Referenced by incompressibleVars::renameTurbulenceFields(), incompressibleVars::setFields(), incompressibleAdjointMeanFlowVars::setFields(), and variablesSet::solverName().
useSolverNameForFields_
bool useSolverNameForFields_ protected
Definition at line 92 of file variablesSet.H.
Referenced by incompressibleVars::renameTurbulenceFields(), incompressibleVars::setFields(), incompressibleAdjointMeanFlowVars::setFields(), variablesSet::useSolverNameForFields(), and incompressibleVars::write().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/solvers/variablesSet/variablesSet/variablesSet.H
src/optimisation/adjointOptimisation/adjoint/solvers/variablesSet/variablesSet/variablesSet.C
src/optimisation/adjointOptimisation/adjoint/solvers/variablesSet/variablesSet/variablesSetTemplates.C