OpenFOAM: EulerDdtScheme< Type > Class Template Reference
EulerDdtScheme< Type > Class Template Reference
Numerics » Finite volume numerical schemes » Time schemes
Basic first-order Euler implicit/explicit ddt using only the current and previous time-step values.
#include <EulerDdtScheme.H>
Public Types
typedef ddtScheme< Type >::fluxFieldType fluxFieldType
Public Types inherited from ddtScheme< Type >
typedef GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > fluxFieldType
Public Member Functions
TypeName ("Euler")
EulerDdtScheme (const fvMesh &mesh)
EulerDdtScheme (const fvMesh &mesh, Istream &is)
const fvMesh & mesh () const
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > fvcDdt (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< fluxFieldType > fvcDdtUfCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > &U, const GeometricField< scalar, fvsPatchField, surfaceMesh > &Uf)
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &U, const surfaceScalarField &phi)
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &Uf)
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &phi)
Public Member Functions inherited from ddtScheme< Type >
virtual const word & type () const =0
declareRunTimeSelectionTable (tmp, ddtScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
ddtScheme (const fvMesh &mesh)
ddtScheme (const fvMesh &mesh, Istream &is)
virtual ~ddtScheme ()=default
const fvMesh & mesh () const
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeffExperimental (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr, const volScalarField &rho)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &rhoU, const fluxFieldType &phi, const volScalarField &rho)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from ddtSchemeBase
ddtSchemeBase ()
ddtSchemeBase ()
Additional Inherited Members
Static Public Member Functions inherited from ddtScheme< Type >
static tmp< ddtScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Static Public Attributes inherited from ddtSchemeBase
static bool experimentalDdtCorr
Protected Member Functions inherited from ddtScheme< Type >
ddtScheme (const ddtScheme &)=delete
void operator= (const ddtScheme &)=delete
Protected Attributes inherited from ddtScheme< Type >
const fvMesh & mesh_
scalar ddtPhiCoeff_
Detailed Description
template<class Type>
class Foam::fv::EulerDdtScheme< Type >
Basic first-order Euler implicit/explicit ddt using only the current and previous time-step values.
Source files
EulerDdtScheme.H
EulerDdtScheme.C
Definition at line 56 of file EulerDdtScheme.H.
Member Typedef Documentation
fluxFieldType
template<class Type > typedef ddtScheme<Type>::fluxFieldType fluxFieldType
Definition at line 156 of file EulerDdtScheme.H.
Constructor & Destructor Documentation
EulerDdtScheme() [1/2]
template<class Type > EulerDdtScheme (const fvMesh & mesh) inline
Definition at line 78 of file EulerDdtScheme.H.
EulerDdtScheme() [2/2]
template<class Type > EulerDdtScheme (const fvMesh & mesh, Istream & is) inline
Definition at line 84 of file EulerDdtScheme.H.
Member Function Documentation
TypeName()
template<class Type > TypeName ("Euler")
mesh()
template<class Type > const fvMesh & mesh () const inline
Definition at line 93 of file EulerDdtScheme.H.
References ddtScheme< Type >::mesh().
fvcDdt() [1/6]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > & dt) virtual
Implements ddtScheme< Type >.
Definition at line 41 of file EulerDdtScheme.C.
References fvPatchFieldBase::calculatedType(), Foam::dimTime, mesh, Foam::New(), timeName, and Foam::Zero.
fvcDdt() [2/6]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 85 of file EulerDdtScheme.C.
References mesh, and timeName.
fvcDdt() [3/6]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 141 of file EulerDdtScheme.C.
References mesh, rho, and timeName.
fvcDdt() [4/6]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 198 of file EulerDdtScheme.C.
References mesh, rho, and timeName.
fvcDdt() [5/6]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 258 of file EulerDdtScheme.C.
References alpha, mesh, rho, and timeName.
fvcDdt() [6/6]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > fvcDdt (const GeometricField< Type, fvsPatchField, surfaceMesh > & sf) virtual
Reimplemented from ddtScheme< Type >.
Definition at line 331 of file EulerDdtScheme.C.
References mesh, and timeName.
fvmDdt() [1/4]
template<class Type > tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 358 of file EulerDdtScheme.C.
References Foam::dimTime, Foam::dimVol, and mesh.
fvmDdt() [2/4]
template<class Type > tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 393 of file EulerDdtScheme.C.
References Foam::dimTime, Foam::dimVol, mesh, and rho.
fvmDdt() [3/4]
template<class Type > tmp< fvMatrix< Type > > fvmDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 430 of file EulerDdtScheme.C.
References Foam::dimTime, Foam::dimVol, mesh, and rho.
fvmDdt() [4/4]
template<class Type > tmp< fvMatrix< Type > > fvmDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 469 of file EulerDdtScheme.C.
References alpha, Foam::dimTime, Foam::dimVol, mesh, and rho.
fvcDdtUfCorr() [1/4]
template<class Type > tmp< typename EulerDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 512 of file EulerDdtScheme.C.
References Foam::fvc::dotInterpolate(), mesh, timeName, U, and Uf.
fvcDdtPhiCorr() [1/4]
template<class Type > tmp< typename EulerDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 545 of file EulerDdtScheme.C.
References Foam::fvc::dotInterpolate(), mesh, phi, timeName, and U.
fvcDdtUfCorr() [2/4]
template<class Type > tmp< typename EulerDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 577 of file EulerDdtScheme.C.
References Foam::abort(), Foam::dimVelocity, Foam::fvc::dotInterpolate(), Foam::FatalError, FatalErrorInFunction, mesh, rho, timeName, U, and Uf.
fvcDdtPhiCorr() [2/4]
template<class Type > tmp< typename EulerDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 662 of file EulerDdtScheme.C.
References Foam::abort(), Foam::dimArea, Foam::dimVelocity, Foam::fvc::dotInterpolate(), Foam::FatalError, FatalErrorInFunction, mesh, phi, rho, timeName, and U.
meshPhi()
template<class Type > tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &) virtual
Implements ddtScheme< Type >.
Definition at line 752 of file EulerDdtScheme.C.
References mesh.
fvcDdtUfCorr() [3/4]
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > & U, const GeometricField< scalar, fvsPatchField, surfaceMesh > & Uf)
fvcDdtPhiCorr() [3/4]
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & U, const surfaceScalarField & phi)
fvcDdtUfCorr() [4/4]
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & Uf)
fvcDdtPhiCorr() [4/4]
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & phi)
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/ddtSchemes/EulerDdtScheme/EulerDdtScheme.H
src/finiteVolume/finiteVolume/ddtSchemes/EulerDdtScheme/EulerDdtScheme.C