OpenFOAM: phasePropertiesList Class Reference
phasePropertiesList Class Reference
Simple container for a list of phase properties.
#include <phasePropertiesList.H>
Public Member Functions
phasePropertiesList ()
phasePropertiesList (Istream &is, const wordList &gasNames, const wordList &liquidNames, const wordList &solidNames)
~phasePropertiesList ()
const List< phaseProperties > & props () const
const wordList & phaseTypes () const
const wordList & stateLabels () const
label size () const
const phaseProperties & operator[] (const label) const
Detailed Description
Simple container for a list of phase properties.
Source files
phasePropertiesList.H
phasePropertiesList.C
Definition at line 49 of file phasePropertiesList.H.
Constructor & Destructor Documentation
phasePropertiesList() [1/2]
phasePropertiesList ()
Definition at line 25 of file phasePropertiesList.C.
phasePropertiesList() [2/2]
phasePropertiesList (Istream & is, const wordList & gasNames, const wordList & liquidNames, const wordList & solidNames)
Definition at line 33 of file phasePropertiesList.C.
References forAll, UPtrList< T >::reorder(), List< T >::setSize(), UPtrList< T >::size(), and solidNames().
~phasePropertiesList()
~phasePropertiesList ()
Definition at line 62 of file phasePropertiesList.C.
Member Function Documentation
props()
const Foam::List< Foam::phaseProperties > & props () const
Definition at line 69 of file phasePropertiesList.C.
phaseTypes()
const Foam::wordList & phaseTypes () const
Definition at line 75 of file phasePropertiesList.C.
stateLabels()
const Foam::wordList & stateLabels () const
Definition at line 81 of file phasePropertiesList.C.
size()
Foam::label size () const
Definition at line 87 of file phasePropertiesList.C.
References UPtrList< T >::size().
operator[]()
const Foam::phaseProperties & operator[] (const label phaseI) const
Definition at line 94 of file phasePropertiesList.C.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/phaseProperties/phasePropertiesList/phasePropertiesList.H
src/lagrangian/intermediate/phaseProperties/phasePropertiesList/phasePropertiesList.C