OpenFOAM: meshToMesh0 Class Reference
meshToMesh0 Class Reference
Serial mesh to mesh interpolation class.
#include <meshToMesh0.H>
Classes
class patchFieldInterpolator
Public Types
enum order { MAP , INTERPOLATE , CELL_POINT_INTERPOLATE , CELL_VOLUME_WEIGHT }
Public Member Functions
ClassName ("meshToMesh0")
meshToMesh0 (const fvMesh &fromMesh, const fvMesh &toMesh, const HashTable< word > &patchMap, const wordList &cuttingPatchNames)
meshToMesh0 (const fvMesh &fromMesh, const fvMesh &toMesh)
~meshToMesh0 ()=default
const fvMesh & fromMesh () const
const fvMesh & toMesh () const
const labelList & cellAddressing () const
scalar V () const
template<class Type , class CombineOp >
void mapField (Field< Type > &, const Field< Type > &, const labelList &adr, const CombineOp &cop) const
template<class Type , class CombineOp >
void interpolateField (Field< Type > &, const VolumeField< Type > &, const labelList &adr, const scalarListList &weights, const CombineOp &cop) const
template<class Type , class CombineOp >
void interpolateField (Field< Type > &, const VolumeField< Type > &, const labelListList &adr, const scalarListList &weights, const CombineOp &cop) const
template<class Type , class CombineOp >
void interpolateField (Field< Type > &, const VolumeField< Type > &, const labelList &adr, const vectorField &centres, const CombineOp &cop) const
template<class Type , class CombineOp >
void interpolateInternalField (Field< Type > &, const VolumeField< Type > &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
template<class Type , class CombineOp >
void interpolateInternalField (Field< Type > &, const tmp< VolumeField< Type > > &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
template<class Type , class CombineOp >
void interpolate (VolumeField< Type > &, const VolumeField< Type > &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
template<class Type , class CombineOp >
void interpolate (VolumeField< Type > &, const tmp< VolumeField< Type > > &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
template<class Type , class CombineOp >
tmp< VolumeField< Type > > interpolate (const VolumeField< Type > &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
template<class Type , class CombineOp >
tmp< VolumeField< Type > > interpolate (const tmp< VolumeField< Type > > &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
template<class Type , class CombineOp >
Foam::tmp< Foam::VolumeField< Type > > interpolate (const VolumeField< Type > &fromVf, meshToMesh0::order ord, const CombineOp &cop) const
template<class Type , class CombineOp >
Foam::tmp< Foam::VolumeField< Type > > interpolate (const tmp< VolumeField< Type > > &tfromVf, meshToMesh0::order ord, const CombineOp &cop) const
Detailed Description
Serial mesh to mesh interpolation class.
Note
This class is due to be deprecated in favour of meshToMesh
Source files
meshToMesh0.H
meshToMesh0.C
calculateMeshToMesh0Addressing.C
calculateMeshToMesh0Weights.C
meshToMesh0Templates.C
Definition at line 61 of file meshToMesh0.H.
Member Enumeration Documentation
order
enum order
Enumerator
MAP
INTERPOLATE
CELL_POINT_INTERPOLATE
CELL_VOLUME_WEIGHT
Definition at line 143 of file meshToMesh0.H.
Constructor & Destructor Documentation
meshToMesh0() [1/2]
meshToMesh0 (const fvMesh & fromMesh, const fvMesh & toMesh, const HashTable< word > & patchMap, const wordList & cuttingPatchNames)
Definition at line 37 of file meshToMesh0.C.
References Foam::endl(), HashTable< T, Key, Hash >::find(), forAll, HashTable< T, Key, Hash >::found(), HashTable< T, Key, Hash >::insert(), and WarningInFunction.
meshToMesh0() [2/2]
meshToMesh0 (const fvMesh & fromMesh, const fvMesh & toMesh)
Definition at line 108 of file meshToMesh0.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, HashTable< T, Key, Hash >::insert(), and UPtrList< T >::size().
~meshToMesh0()
~meshToMesh0 () default
Member Function Documentation
ClassName()
ClassName ("meshToMesh0")
fromMesh()
const fvMesh & fromMesh () const inline
Definition at line 229 of file meshToMesh0.H.
toMesh()
const fvMesh & toMesh () const inline
Definition at line 234 of file meshToMesh0.H.
cellAddressing()
const labelList & cellAddressing () const inline
Definition at line 240 of file meshToMesh0.H.
V()
scalar V () const inline
Definition at line 246 of file meshToMesh0.H.
mapField()
template<class Type , class CombineOp > void mapField (Field< Type > & toF, const Field< Type > & fromVf, const labelList & adr, const CombineOp & cop) const
Definition at line 31 of file meshToMesh0Templates.C.
References forAll.
interpolateField() [1/3]
template<class Type , class CombineOp > void interpolateField (Field< Type > & toF, const VolumeField< Type > & fromVf, const labelList & adr, const scalarListList & weights, const CombineOp & cop) const
Definition at line 81 of file meshToMesh0Templates.C.
References f(), forAll, and UList< T >::size().
interpolateField() [2/3]
template<class Type , class CombineOp > void interpolateField (Field< Type > & toF, const VolumeField< Type > & fromVf, const labelListList & adr, const scalarListList & weights, const CombineOp & cop) const
Definition at line 54 of file meshToMesh0Templates.C.
References f(), forAll, and Foam::Zero.
interpolateField() [3/3]
template<class Type , class CombineOp > void interpolateField (Field< Type > & toF, const VolumeField< Type > & fromVf, const labelList & adr, const vectorField & centres, const CombineOp & cop) const
Definition at line 116 of file meshToMesh0Templates.C.
References forAll.
interpolateInternalField() [1/2]
template<class Type , class CombineOp > void interpolateInternalField (Field< Type > & toF, const VolumeField< Type > & fromVf, meshToMesh0::order ord = INTERPOLATE, const CombineOp & cop = eqOp<Type>()) const
Definition at line 147 of file meshToMesh0Templates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and UPtrList< T >::size().
interpolateInternalField() [2/2]
template<class Type , class CombineOp > void interpolateInternalField (Field< Type > & toF, const tmp< VolumeField< Type > > & tfromVf, meshToMesh0::order ord = INTERPOLATE, const CombineOp & cop = eqOp<Type>()) const
Definition at line 228 of file meshToMesh0Templates.C.
References PtrList< T >::clear().
interpolate() [1/6]
template<class Type , class CombineOp > void interpolate (VolumeField< Type > & toVf, const VolumeField< Type > & fromVf, meshToMesh0::order ord = INTERPOLATE, const CombineOp & cop = eqOp<Type>()) const
Definition at line 242 of file meshToMesh0Templates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, and Foam::isA().
interpolate() [2/6]
template<class Type , class CombineOp > void interpolate (VolumeField< Type > & toVf, const tmp< VolumeField< Type > > & tfromVf, meshToMesh0::order ord = INTERPOLATE, const CombineOp & cop = eqOp<Type>()) const
Definition at line 340 of file meshToMesh0Templates.C.
References PtrList< T >::clear(), and Foam::interpolate().
interpolate() [3/6]
template<class Type , class CombineOp > tmp< VolumeField< Type > > interpolate (const VolumeField< Type > & , order = INTERPOLATE, const CombineOp & cop = eqOp< Type >()) const
interpolate() [4/6]
template<class Type , class CombineOp > tmp< VolumeField< Type > > interpolate (const tmp< VolumeField< Type > > & , order = INTERPOLATE, const CombineOp & cop = eqOp< Type >()) const
interpolate() [5/6]
template<class Type , class CombineOp > Foam::tmp< Foam::VolumeField< Type > > interpolate (const VolumeField< Type > & fromVf, meshToMesh0::order ord, const CombineOp & cop) const
Definition at line 355 of file meshToMesh0Templates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::New(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and PtrList< T >::set().
interpolate() [6/6]
template<class Type , class CombineOp > Foam::tmp< Foam::VolumeField< Type > > interpolate (const tmp< VolumeField< Type > > & tfromVf, meshToMesh0::order ord, const CombineOp & cop) const
Definition at line 423 of file meshToMesh0Templates.C.
References PtrList< T >::clear(), and Foam::interpolate().
The documentation for this class was generated from the following files:
src/sampling/meshToMesh0/meshToMesh0.H
src/sampling/meshToMesh0/calculateMeshToMesh0Addressing.C
src/sampling/meshToMesh0/calculateMeshToMesh0Weights.C
src/sampling/meshToMesh0/meshToMesh0.C
src/sampling/meshToMesh0/meshToMesh0Templates.C