OpenFOAM: polyMeshFilterSettings Class Reference
polyMeshFilterSettings Class Reference
Class to store the settings for the polyMeshFilter class.
#include <polyMeshFilterSettings.H>
Public Member Functions
polyMeshFilterSettings (const dictionary &dict)
~polyMeshFilterSettings ()=default
const dictionary & collapseEdgesCoeffDict () const
const dictionary & collapseFacesCoeffDict () const
const dictionary & meshQualityCoeffDict () const
Switch controlMeshQuality () const
const scalar & minLen () const
const scalar & maxCos () const
const scalar & edgeReductionFactor () const
const label & maxIterations () const
const label & maxSmoothIters () const
const scalar & initialFaceLengthFactor () const
const scalar & faceReductionFactor () const
const label & maxPointErrorCount () const
void writeSettings (Ostream &os) const
Detailed Description
Class to store the settings for the polyMeshFilter class.
Source files
polyMeshFilterSettings.H
polyMeshFilterSettings.C
polyMeshFilterSettingsI.H
Definition at line 51 of file polyMeshFilterSettings.H.
Constructor & Destructor Documentation
polyMeshFilterSettings()
polyMeshFilterSettings (const dictionary & dict) explicit
Definition at line 27 of file polyMeshFilterSettings.C.
References Foam::cos(), and Foam::degToRad().
~polyMeshFilterSettings()
~polyMeshFilterSettings () default
Member Function Documentation
collapseEdgesCoeffDict()
const Foam::dictionary & collapseEdgesCoeffDict () const inline
Definition at line 25 of file polyMeshFilterSettingsI.H.
collapseFacesCoeffDict()
const Foam::dictionary & collapseFacesCoeffDict () const inline
Definition at line 31 of file polyMeshFilterSettingsI.H.
meshQualityCoeffDict()
const Foam::dictionary & meshQualityCoeffDict () const inline
Definition at line 37 of file polyMeshFilterSettingsI.H.
controlMeshQuality()
Foam::Switch controlMeshQuality () const inline
Definition at line 43 of file polyMeshFilterSettingsI.H.
minLen()
const Foam::scalar & minLen () const inline
Definition at line 48 of file polyMeshFilterSettingsI.H.
maxCos()
const Foam::scalar & maxCos () const inline
Definition at line 53 of file polyMeshFilterSettingsI.H.
edgeReductionFactor()
const Foam::scalar & edgeReductionFactor () const inline
Definition at line 59 of file polyMeshFilterSettingsI.H.
maxIterations()
const Foam::label & maxIterations () const inline
Definition at line 64 of file polyMeshFilterSettingsI.H.
maxSmoothIters()
const Foam::label & maxSmoothIters () const inline
Definition at line 69 of file polyMeshFilterSettingsI.H.
initialFaceLengthFactor()
const Foam::scalar & initialFaceLengthFactor () const inline
Definition at line 75 of file polyMeshFilterSettingsI.H.
faceReductionFactor()
const Foam::scalar & faceReductionFactor () const inline
Definition at line 81 of file polyMeshFilterSettingsI.H.
maxPointErrorCount()
const Foam::label & maxPointErrorCount () const inline
Definition at line 87 of file polyMeshFilterSettingsI.H.
writeSettings()
void writeSettings (Ostream & os) const
Definition at line 77 of file polyMeshFilterSettings.C.
References Foam::acos(), Foam::endl(), Foam::nl, os(), and Foam::radToDeg().
Referenced by polyMeshFilter::polyMeshFilter(), polyMeshFilter::polyMeshFilter(), and polyMeshFilter::polyMeshFilter().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyMeshFilter/polyMeshFilterSettings.H
src/dynamicMesh/polyMeshFilter/polyMeshFilterSettings.C
src/dynamicMesh/polyMeshFilter/polyMeshFilterSettingsI.H