OpenFOAM: ensightOutputSurface Class Reference
ensightOutputSurface Class Reference
A variant of ensightFaces that holds references to contiguous points/faces with its own encapsulated write methods. The surface is assumed to have been merged prior, thus the output is serial-only.
#include <ensightOutputSurface.H>
Public Member Functions
ensightOutputSurface (const pointField &points, const faceList &faces, const string &description="surface")
virtual ~ensightOutputSurface ()=default
void write (ensightGeoFile &os) const
template<class Type >
void writeData (ensightFile &os, const Field< Type > &fld, const bool isPointData=false) const
template<class Type >
void writeFaceData (ensightFile &os, const Field< Type > &fld) const
template<class Type >
void writePointData (ensightFile &os, const Field< Type > &fld) const
virtual void write (ensightGeoFile &, const polyMesh &, bool) const
Public Member Functions inherited from ensightFaces
TypeName ("ensightFaces")
ensightFaces ()
ensightFaces (const string &description)
virtual ~ensightFaces ()=default
label size (const elemType etype) const
labelRange range (const elemType etype) const
label totalSize () const noexcept
label total () const noexcept
label total (const elemType etype) const
const FixedList< label, nTypes > & totals () const
FixedList< label, nTypes > sizes () const
const labelList & faceIds () const noexcept
const labelUList faceIds (const elemType etype) const
const boolList & flipMap () const
bool usesFlipMap () const
const labelList & faceOrder () const noexcept
const labelUList faceOrder (const elemType etype) const
void classify (const UList< face > &faces)
void classify (const UList< face > &faces, const labelRange &range)
void classify (const UList< face > &faces, const labelUList &addr, const boolList &flipMap=boolList(), const bitSet &exclude=bitSet())
void clearOut ()
void clear ()
void reduce ()
void sort ()
void incrFaceIds (const label off)
void decrFaceIds (const label off)
InfoProxy< ensightFaces > info () const noexcept
label uniqueMeshPoints (const polyMesh &mesh, labelList &uniqueMeshPointLabels, bool parallel) const
virtual void writeDict (Ostream &os, const bool full=false) const
label size () const noexcept
Public Member Functions inherited from ensightPart
TypeNameNoDebug ("ensightPart")
ensightPart ()
ensightPart (const string &description)
virtual ~ensightPart ()=default
label index () const noexcept
label & index () noexcept
label identifier () const noexcept
label & identifier () noexcept
bool empty () const noexcept
label size () const noexcept
const string & name () const noexcept
void rename (const string &value)
void rename (string &&value)
label operator[] (const label i) const
Additional Inherited Members
Public Types inherited from ensightFaces
enum elemType { TRIA3 = 0 , QUAD4 , NSIDED }
Static Public Member Functions inherited from ensightFaces
static const char * key (const elemType etype) noexcept
Static Public Attributes inherited from ensightFaces
static constexpr int nTypes = 3
static const char * elemNames [nTypes]
Protected Member Functions inherited from ensightPart
const labelList & addressing () const noexcept
labelList & addressing () noexcept
void clear ()
void incrAddressing (const label off)
void decrAddressing (const label off)
Detailed Description
A variant of ensightFaces that holds references to contiguous points/faces with its own encapsulated write methods. The surface is assumed to have been merged prior, thus the output is serial-only.
Note
The primary use is for the Foam::surfaceWriters::ensightWriter but can be used independently as well.
Source files
ensightOutputSurface.H
ensightOutputSurface.C
ensightOutputSurfaceTemplates.C
Definition at line 54 of file ensightOutputSurface.H.
Constructor & Destructor Documentation
ensightOutputSurface()
ensightOutputSurface (const pointField & points, const faceList & faces, const string & description = "surface")
Definition at line 26 of file ensightOutputSurface.C.
References ensightFaces::classify().
~ensightOutputSurface()
virtual ~ensightOutputSurface () virtual default
Member Function Documentation
write() [1/2]
void write (ensightGeoFile & os) const
Definition at line 44 of file ensightOutputSurface.C.
References Foam::name(), os(), Foam::ensightOutput::Detail::writeCoordinates(), and Foam::ensightOutput::writeFaceConnectivity().
Referenced by ensightWriter::writeCollated(), and ensightWriter::writeUncollated().
writeData()
template<class Type > void writeData (ensightFile & os, const Field< Type > & fld, const bool isPointData = false) const
Definition at line 27 of file ensightOutputSurfaceTemplates.C.
References fld(), ensightOutputSurface::writeFaceData(), and ensightOutputSurface::writePointData().
Referenced by ensightWriter::writeCollated(), and ensightWriter::writeUncollated().
writeFaceData()
template<class Type > void writeFaceData (ensightFile & os, const Field< Type > & fld) const
Definition at line 46 of file ensightOutputSurfaceTemplates.C.
References fld(), os(), and Foam::ensightOutput::writeField().
Referenced by ensightOutputSurface::writeData().
writePointData()
template<class Type > void writePointData (ensightFile & os, const Field< Type > & fld) const
Definition at line 63 of file ensightOutputSurfaceTemplates.C.
References ensightFile::coordinates, ensightPart::empty(), UPtrList< T >::empty(), fld(), ensightPart::index(), os(), and Foam::ensightOutput::Detail::writeFieldComponents().
Referenced by ensightOutputSurface::writeData().
write() [2/2]
virtual void write (ensightGeoFile & , const polyMesh & , bool) const inline virtual
Reimplemented from ensightFaces.
Definition at line 120 of file ensightOutputSurface.H.
The documentation for this class was generated from the following files:
src/fileFormats/ensight/part/surface/ensightOutputSurface.H
src/fileFormats/ensight/part/surface/ensightOutputSurface.C
src/fileFormats/ensight/part/surface/ensightOutputSurfaceTemplates.C