OpenFOAM: endian Class Reference
endian Class Reference
#include <endian.H>
Static Public Member Functions
static bool isBig () noexcept
static bool isLittle () noexcept
static uint32_t swap32 (uint32_t)
static uint64_t swap64 (uint64_t)
Detailed Description
Definition at line 67 of file endian.H.
Member Function Documentation
isBig()
bool isBig () inline static noexcept
Definition at line 36 of file endianI.H.
isLittle()
bool isLittle () inline static noexcept
Definition at line 45 of file endianI.H.
swap32()
uint32_t swap32 (uint32_t u) inline static
Definition at line 54 of file endianI.H.
Referenced by legacyRawFormatter::write(), and legacyRawFormatter::write().
swap64()
uint64_t swap64 (uint64_t u) inline static
Definition at line 76 of file endianI.H.
Referenced by legacyRawFormatter::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/endian/endian.H
src/OpenFOAM/primitives/endian/endianI.H