OpenFOAM: PointIntegrateData< DataType > Class Template Reference
PointIntegrateData< DataType > Class Template Reference
Integrate along selected edges using PointEdgeWave.
#include <PointIntegrateData.H>
Classes
class trackingData
Public Member Functions
PointIntegrateData ()
PointIntegrateData (const DataType &data)
const DataType & data () const
DataType & data ()
template<class TrackingData >
bool valid (TrackingData &td) const
template<class TrackingData >
bool sameGeometry (const PointIntegrateData< DataType > &, const scalar tol, TrackingData &td) const
template<class TrackingData >
void leaveDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
template<class TrackingData >
void enterDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointI, const label edgeI, const PointIntegrateData< DataType > &edgeInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointI, const PointIntegrateData< DataType > &newPointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updatePoint (const PointIntegrateData< DataType > &newPointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointI, const PointIntegrateData< DataType > &pointInfo, const scalar tol, TrackingData &td)
template<class TrackingData >
bool equal (const PointIntegrateData< DataType > &, TrackingData &td) const
bool operator== (const PointIntegrateData< DataType > &) const
bool operator!= (const PointIntegrateData< DataType > &) const
Friends
Ostream & operator<< (Ostream &, const PointIntegrateData< DataType > &)
Istream & operator>> (Istream &, PointIntegrateData< DataType > &)
Detailed Description
template<class DataType>
class Foam::PointIntegrateData< DataType >
Integrate along selected edges using PointEdgeWave.
Source files
PointIntegrateData.H
PointIntegrateDataI.H
Definition at line 55 of file PointIntegrateData.H.
Constructor & Destructor Documentation
PointIntegrateData() [1/2]
template<class DataType > PointIntegrateData () inline
Definition at line 27 of file PointIntegrateDataI.H.
PointIntegrateData() [2/2]
template<class DataType > PointIntegrateData (const DataType & data) inline
Definition at line 34 of file PointIntegrateDataI.H.
Member Function Documentation
data() [1/2]
template<class DataType > const DataType & data () const inline
Definition at line 95 of file PointIntegrateData.H.
data() [2/2]
template<class DataType > DataType & data () inline
Definition at line 99 of file PointIntegrateData.H.
valid()
template<class DataType > template<class TrackingData > bool valid (TrackingData & td) const inline
Definition at line 48 of file PointIntegrateDataI.H.
sameGeometry()
template<class DataType > template<class TrackingData > bool sameGeometry (const PointIntegrateData< DataType > & , const scalar tol, TrackingData & td) const inline
Definition at line 56 of file PointIntegrateDataI.H.
leaveDomain()
template<class DataType > template<class TrackingData > void leaveDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Definition at line 69 of file PointIntegrateDataI.H.
enterDomain()
template<class DataType > template<class TrackingData > void enterDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Definition at line 81 of file PointIntegrateDataI.H.
transform()
template<class DataType > template<class TrackingData > void transform (const tensor & rotTensor, TrackingData & td) inline
Definition at line 93 of file PointIntegrateDataI.H.
References Foam::transform().
updatePoint() [1/3]
template<class DataType > template<class TrackingData > bool updatePoint (const polyMesh & mesh, const label pointI, const label edgeI, const PointIntegrateData< DataType > & edgeInfo, const scalar tol, TrackingData & td) inline
Definition at line 105 of file PointIntegrateDataI.H.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
updatePoint() [2/3]
template<class DataType > template<class TrackingData > bool updatePoint (const polyMesh & mesh, const label pointI, const PointIntegrateData< DataType > & newPointInfo, const scalar tol, TrackingData & td) inline
Definition at line 132 of file PointIntegrateDataI.H.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
updatePoint() [3/3]
template<class DataType > template<class TrackingData > bool updatePoint (const PointIntegrateData< DataType > & newPointInfo, const scalar tol, TrackingData & td) inline
Definition at line 159 of file PointIntegrateDataI.H.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
updateEdge()
template<class DataType > template<class TrackingData > bool updateEdge (const polyMesh & mesh, const label edgeI, const label pointI, const PointIntegrateData< DataType > & pointInfo, const scalar tol, TrackingData & td) inline
Definition at line 183 of file PointIntegrateDataI.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, and polyMesh::points().
equal()
template<class DataType > template<class TrackingData > bool equal (const PointIntegrateData< DataType > & pi, TrackingData & td) const inline
Definition at line 213 of file PointIntegrateDataI.H.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
operator==()
template<class DataType > bool operator== (const PointIntegrateData< DataType > & rhs) const inline
Definition at line 239 of file PointIntegrateDataI.H.
operator!=()
template<class DataType > bool operator!= (const PointIntegrateData< DataType > & rhs) const inline
Definition at line 249 of file PointIntegrateDataI.H.
Friends And Related Symbol Documentation
operator<<
template<class DataType > Ostream & operator<< (Ostream & , const PointIntegrateData< DataType > &) friend
operator>>
template<class DataType > Istream & operator>> (Istream & , PointIntegrateData< DataType > &) friend
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/snappyHexMeshDriver/PointIntegrateData/PointIntegrateData.H
src/mesh/snappyHexMesh/snappyHexMeshDriver/PointIntegrateData/PointIntegrateDataI.H