OpenFOAM: processorFaPatch Class Reference
processorFaPatch Class Reference
Processor patch.
#include <processorFaPatch.H>
Public Member Functions
TypeName ("processor")
processorFaPatch (const labelUList &edgeLabels, const label index, const faBoundaryMesh &bm, const label nbrPolyPatchi, const label myProcNo, const label neighbProcNo, const word &patchType=typeName)
processorFaPatch (const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm, const word &patchType=typeName)
virtual ~processorFaPatch ()
virtual label interfaceSize () const noexcept
int myProcNo () const noexcept
int neighbProcNo () const noexcept
virtual bool coupled () const
virtual bool owner () const noexcept
virtual int tag () const
virtual label comm () const
virtual const tensorField & forwardT () const
virtual tmp< vectorField > delta () const
const vectorField & neighbEdgeCentres () const noexcept
const vectorField & neighbEdgeLengths () const noexcept
tmp< vectorField > neighbEdgeNormals () const
const vectorField & neighbEdgeFaceCentres () const noexcept
const labelList & neighbPoints () const
const labelList & nonGlobalPatchPoints () const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData, const labelUList &edgeFaces) const
virtual void initTransfer (const Pstream::commsTypes commsType, const labelUList &interfaceData) const
virtual tmp< labelField > transfer (const Pstream::commsTypes commsType, const labelUList &interfaceData) const
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &internalData) const
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &internalData) const
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &internalData, const labelUList &edgeCells) const
virtual void write (Ostream &os) const
Public Member Functions inherited from coupledFaPatch
TypeNameNoDebug ("coupled")
coupledFaPatch (const word &name, const labelList &edgeLabels, const label index, const faBoundaryMesh &bm, const label nbrPolyPatchIndex, const word &patchType)
coupledFaPatch (const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm, const word &patchType)
virtual ~coupledFaPatch ()=default
virtual bool neighbour () const
bool separated () const
const vectorField & separation () const
const tensorField & forwardT () const
const tensorField & reverseT () const
bool parallel () const
virtual const labelUList & faceCells () const
Public Member Functions inherited from lduInterface
TypeNameNoDebug ("lduInterface")
lduInterface () noexcept=default
virtual ~lduInterface ()=default
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF, const labelUList &faceCells) const
Public Member Functions inherited from faPatch
TypeName ("patch")
declareRunTimeSelectionTable (autoPtr, faPatch, dictionary,(const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
faPatch (const word &name, const labelUList &edgeLabels, const label index, const faBoundaryMesh &bm, const label nbrPolyPatchi, const word &patchType)
faPatch (const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm, const word &patchType)
faPatch (const faPatch &p, const faBoundaryMesh &bm)
faPatch (const faPatch &p, const faBoundaryMesh &bm, const label index, const labelUList &edgeLabels, const label nbrPolyPatchi)
virtual autoPtr< faPatch > clone (const faBoundaryMesh &bm) const
virtual autoPtr< faPatch > clone (const faBoundaryMesh &bm, const labelUList &edgeLabels, const label index, const label nbrPolyPatchi) const
virtual ~faPatch ()
const labelList & edgeLabels () const noexcept
label nPoints () const
label nEdges () const noexcept
label ngbPolyPatchIndex () const noexcept
const faBoundaryMesh & boundaryMesh () const noexcept
label offset () const
label start () const
virtual label size () const
label whichEdge (const label edgei) const
template<class T >
const List< T >::subList patchSlice (const List< T > &values) const
template<class T >
const List< T >::subList boundarySlice (const List< T > &values) const
List< labelPair > boundaryConnections () const
labelList boundaryProcs () const
List< labelPair > boundaryProcSizes () const
const labelList & pointLabels () const
const labelListList & pointEdges () const
tmp< vectorField > ngbPolyPatchFaceNormals () const
tmp< vectorField > ngbPolyPatchPointNormals () const
const labelUList & edgeFaces () const
const vectorField & edgeCentres () const
const vectorField & edgeLengths () const
const scalarField & magEdgeLengths () const
tmp< vectorField > edgeNormals () const
tmp< vectorField > edgeFaceCentres () const
const scalarField & weights () const
void makeCorrectionVectors (vectorField &) const
const scalarField & deltaCoeffs () const
void resetEdges (const labelUList &newEdges)
void resetEdges (labelList &&newEdges)
template<class Type >
void patchInternalField (const UList< Type > &internalData, const labelUList &addressing, Field< Type > &pfld) const
template<class Type >
void patchInternalField (const UList< Type > &internalData, Field< Type > &pfld) const
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &internalData) const
template<class GeometricField , class AnyType = bool>
const GeometricField::Patch & patchField (const GeometricField &gf) const
template<class GeometricField , class AnyType = bool>
const GeometricField::Patch & lookupPatchField (const word &name, const GeometricField *=nullptr, const AnyType *=nullptr) const
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &internalData) const
Public Member Functions inherited from patchIdentifier
patchIdentifier (const patchIdentifier &)=default
patchIdentifier & operator= (const patchIdentifier &)=default
virtual ~patchIdentifier ()=default
patchIdentifier ()
patchIdentifier (const word &name, const label index)
patchIdentifier (const word &name, const label index, const word &physicalType, const wordList &inGroups=wordList())
patchIdentifier (const word &name, const dictionary &dict, const label index)
patchIdentifier (const patchIdentifier &ident, const label index)
const word & name () const noexcept
word & name () noexcept
label index () const noexcept
label & index () noexcept
const word & physicalType () const noexcept
word & physicalType () noexcept
const wordList & inGroups () const noexcept
wordList & inGroups () noexcept
bool inGroup (const word &name) const
void write (Ostream &os) const
Public Member Functions inherited from List< label >
constexpr List () noexcept
List (const label len)
List (const label len, const label &val)
List (const label len, const Foam::zero)
List (const Foam::one, const label &val)
List (const Foam::one, label &&val)
List (const Foam::one, const Foam::zero)
List (const List< label > &a)
List (const UList< label > &a)
List (List< label > &a, bool reuse)
List (const UList< label > &list, const labelUList &indices)
List (const UList< label > &list, const FixedList< label, N > &indices)
List (const FixedList< label, N > &list)
List (const PtrList< label > &list)
List (const SLList< label > &list)
List (const IndirectListBase< label, Addr > &list)
List (std::initializer_list< label > list)
List (List< label > &&list)
List (DynamicList< label, SizeMin > &&list)
List (SLList< label > &&list)
List (Istream &is)
autoPtr< List< label > > clone () const
~List ()
void clear ()
void resize (const label len)
void resize (const label len, const label &val)
void resize (const label newLen)
void resize_nocopy (const label len)
void setSize (const label n)
void setSize (const label n, const label &val)
void transfer (List< label > &list)
void transfer (DynamicList< label, SizeMin > &list)
label & newElmt (const label i)
label & emplace_back (Args &&... args)
void push_back (const label &val)
void push_back (label &&val)
void push_back (const UList< label > &list)
void push_back (const IndirectListBase< label, Addr > &list)
label push_uniq (const label &val)
void pop_back (label n=1)
void operator= (const UList< label > &a)
void operator= (const List< label > &list)
void operator= (const SLList< label > &list)
void operator= (const IndirectListBase< label, Addr > &list)
void operator= (const FixedList< label, N > &list)
void operator= (std::initializer_list< label > list)
void operator= (const label &val)
void operator= (const Foam::zero)
void operator= (List< label > &&list)
void operator= (DynamicList< label, SizeMin > &&list)
void operator= (SLList< label > &&list)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
Istream & readList (Istream &is)
void shallowCopy (const UList< label > &)=delete
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type set (const label i, bool val=true)
void append (const label &val)
void append (label &&val)
void append (const UList< label > &list)
void append (const IndirectListBase< label, Addr > &list)
label appendUniq (const label &val)
Public Member Functions inherited from UList< T >
UList (const UList< T > &)=default
constexpr UList () noexcept
UList (T *__restrict__ v, const label len) noexcept
label fcIndex (const label i) const noexcept
label rcIndex (const label i) const noexcept
const T & fcValue (const label i) const
T & fcValue (const label i)
const T & rcValue (const label i) const
T & rcValue (const label i)
const T * cdata () const noexcept
T * data () noexcept
const char * cdata_bytes () const noexcept
char * data_bytes () noexcept
T & front ()
const T & front () const
T & back ()
const T & back () const
std::streamsize size_bytes () const noexcept
std::streamsize byteSize () const
void checkStart (const label start) const
void checkSize (const label size) const
void checkRange (const label start, const label len) const
void checkIndex (const label i) const
bool uniform () const
label find (const T &val, label pos=0) const
label rfind (const T &val, label pos=-1) const
bool contains (const T &val, label pos=0) const
void moveFirst (const label i)
void moveLast (const label i)
void swapFirst (const label i)
void swapLast (const label i)
void shallowCopy (const UList< T > &list)
void deepCopy (const UList< T > &list)
template<class Addr >
void deepCopy (const IndirectListBase< T, Addr > &list)
SubList< T > slice (const label pos, label len=-1)
const SubList< T > slice (const label pos, label len=-1) const
SubList< T > slice (const labelRange &range)
const SubList< T > slice (const labelRange &range) const
T & operator[] (const label i)
const T & operator[] (const label i) const
operator const Foam::List< T > & () const
void operator= (const T &val)
void operator= (const Foam::zero)
iterator begin () noexcept
iterator end () noexcept
iterator begin (const label i) noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin (const label i) const noexcept
const_iterator begin (const label i) const noexcept
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const noexcept
label size () const noexcept
void swap (UList< T > &list)
bool operator== (const UList< T > &a) const
bool operator!= (const UList< T > &a) const
bool operator< (const UList< T > &list) const
bool operator> (const UList< T > &a) const
bool operator<= (const UList< T > &a) const
bool operator>= (const UList< T > &a) const
Istream & readList (Istream &is)
void writeEntry (const word &keyword, Ostream &os) const
Ostream & writeList (Ostream &os, const label shortLen=0) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type test (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type get (const label i) const
template<class TypeT = T>
std::enable_if< std::is_same< bool, TypeT >::value, bool >::type unset (const label i)
T & first ()
const T & first () const
T & last ()
const T & last () const
bool found (const T &val, label pos=0) const
Istream & readList (Istream &is)
Ostream & writeList (Ostream &os, const label) const
const bool & operator[] (const label i) const
UPstream::commsStruct & operator[] (const label procID)
const UPstream::commsStruct & operator[] (const label procID) const
Foam::UPstream::commsStruct & operator[] (const label procID)
const Foam::UPstream::commsStruct & operator[] (const label procID) const
Ostream & writeList (Ostream &os, const label) const
Istream & readList (Istream &is)
Public Member Functions inherited from processorLduInterface
TypeNameNoDebug ("processorLduInterface")
processorLduInterface () noexcept=default
virtual ~processorLduInterface ()=default
template<class Type >
void send (const UPstream::commsTypes commsType, const UList< Type > &f) const
template<class Type >
void receive (const UPstream::commsTypes commsType, UList< Type > &f) const
template<class Type >
tmp< Field< Type > > receive (const UPstream::commsTypes commsType, const label size) const
template<class Type >
void compressedSend (const UPstream::commsTypes commsType, const UList< Type > &f) const
template<class Type >
void compressedReceive (const UPstream::commsTypes commsType, UList< Type > &f) const
template<class Type >
tmp< Field< Type > > compressedReceive (const UPstream::commsTypes commsType, const label size) const
template<class Type >
Foam::tmp< Foam::Field< Type > > receive (const UPstream::commsTypes commsType, const label size) const
template<class Type >
Foam::tmp< Foam::Field< Type > > compressedReceive (const UPstream::commsTypes commsType, const label size) const
Protected Member Functions
processorFaPatch (const word &name, const labelUList &edgeLabels, const label index, const faBoundaryMesh &bm, const label nbrPolyPatchi, const label myProcNo, const label neighbProcNo, const word &patchType=typeName)
void makeWeights (scalarField &) const
void makeDeltaCoeffs (scalarField &) const
void makeNonGlobalPatchPoints () const
void initGeometry (PstreamBuffers &)
void calcGeometry (PstreamBuffers &)
void initMovePoints (PstreamBuffers &, const pointField &)
void movePoints (PstreamBuffers &, const pointField &)
virtual void initUpdateMesh (PstreamBuffers &)
virtual void updateMesh (PstreamBuffers &)
Protected Member Functions inherited from coupledFaPatch
void calcTransformTensors (const vector &Cf, const vector &Cr, const vector &nf, const vector &nr) const
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr) const
Protected Member Functions inherited from faPatch
void calcPointLabels () const
void calcPointEdges () const
Protected Member Functions inherited from UList< T >
void setAddressableSize (const label n) noexcept
void size (const label n)
void writeEntry (Ostream &os) const
labelRange validateRange (const labelRange &requestedRange) const
UList< T > & operator= (const UList< T > &)=delete
void writeEntry (Ostream &os) const
void writeEntry (Ostream &os) const
Additional Inherited Members
Public Types inherited from faPatch
typedef faBoundaryMesh BoundaryMesh
Public Types inherited from List< label >
typedef SubList< label > subList
Public Types inherited from UList< T >
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T * iterator
typedef const T * const_iterator
typedef label size_type
typedef label difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Static Public Member Functions inherited from faPatch
static autoPtr< faPatch > New (const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm)
static autoPtr< faPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm)
static bool constraintType (const word &patchType)
static wordList constraintTypes ()
Static Public Member Functions inherited from patchIdentifier
static word defaultName (const label n=-1)
Static Public Member Functions inherited from List< label >
static const List< label > & null ()
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
static constexpr label max_size () noexcept
Detailed Description
Processor patch.
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Source files
processorFaPatch.H
processorFaPatch.C
Definition at line 52 of file processorFaPatch.H.
Constructor & Destructor Documentation
processorFaPatch() [1/3]
processorFaPatch (const word & name, const labelUList & edgeLabels, const label index, const faBoundaryMesh & bm, const label nbrPolyPatchi, const label myProcNo, const label neighbProcNo, const word & patchType = typeName) protected
Definition at line 49 of file processorFaPatch.C.
processorFaPatch() [2/3]
processorFaPatch (const labelUList & edgeLabels, const label index, const faBoundaryMesh & bm, const label nbrPolyPatchi, const label myProcNo, const label neighbProcNo, const word & patchType = typeName)
Definition at line 72 of file processorFaPatch.C.
processorFaPatch() [3/3]
processorFaPatch (const word & name, const dictionary & dict, const label index, const faBoundaryMesh & bm, const word & patchType = typeName)
Definition at line 97 of file processorFaPatch.C.
~processorFaPatch()
~processorFaPatch () virtual
Definition at line 40 of file processorFaPatch.C.
References PtrList< T >::clear().
Member Function Documentation
makeWeights()
void makeWeights (scalarField & w) const protected virtual
Implements coupledFaPatch.
Definition at line 391 of file processorFaPatch.C.
References coupledFaPatch::delta(), and UPstream::parRun().
makeDeltaCoeffs()
void makeDeltaCoeffs (scalarField & dc) const protected virtual
Implements coupledFaPatch.
Definition at line 415 of file processorFaPatch.C.
References coupledFaPatch::delta(), and UPstream::parRun().
makeNonGlobalPatchPoints()
void makeNonGlobalPatchPoints () const protected
Definition at line 125 of file processorFaPatch.C.
References forAll, UList< T >::found(), Foam::identity(), boundaryMesh::mesh(), nPoints, UPstream::parRun(), pointLabels(), and PtrList< T >::resize().
initGeometry()
void initGeometry (PstreamBuffers & pBufs) protected virtual
Implements coupledFaPatch.
Definition at line 170 of file processorFaPatch.C.
References edgeCentres(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::name(), Foam::nl, and UPstream::parRun().
calcGeometry()
void calcGeometry (PstreamBuffers & pBufs) protected virtual
Implements coupledFaPatch.
Definition at line 194 of file processorFaPatch.C.
References e, edgeCentres(), forAll, Foam::mag(), Foam::nl, UPstream::parRun(), and WarningInFunction.
Referenced by processorFaPatch::movePoints().
initMovePoints()
void initMovePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Implements coupledFaPatch.
Definition at line 237 of file processorFaPatch.C.
References faPatch::movePoints(), and p.
movePoints()
void movePoints (PstreamBuffers & pBufs, const pointField &) protected virtual
Implements coupledFaPatch.
Definition at line 248 of file processorFaPatch.C.
References processorFaPatch::calcGeometry().
initUpdateMesh()
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Reimplemented from faPatch.
Definition at line 258 of file processorFaPatch.C.
References e, Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::find(), faPatch::initUpdateMesh(), mesh, Foam::name(), Foam::nl, nPoints, UPstream::parRun(), and pointLabels().
updateMesh()
void updateMesh (PstreamBuffers & pBufs) protected virtual
Reimplemented from faPatch.
Definition at line 306 of file processorFaPatch.C.
References e, UList< T >::find(), forAll, mesh, nPoints, UPstream::parRun(), pointLabels(), UPtrList< T >::size(), and faPatch::updateMesh().
TypeName()
TypeName ("processor")
interfaceSize()
virtual label interfaceSize () const inline virtual noexcept
Definition at line 169 of file processorFaPatch.H.
References faPatch::size().
myProcNo()
int myProcNo () const inline virtual noexcept
Implements processorLduInterface.
Definition at line 175 of file processorFaPatch.H.
Referenced by processorFaPatchField< Type >::myProcNo().
neighbProcNo()
int neighbProcNo () const inline virtual noexcept
Implements processorLduInterface.
Definition at line 181 of file processorFaPatch.H.
Referenced by processorFaPatchField< Type >::neighbProcNo().
coupled()
virtual bool coupled () const inline virtual
Reimplemented from coupledFaPatch.
Definition at line 187 of file processorFaPatch.H.
References UPstream::parRun().
owner()
virtual bool owner () const inline virtual noexcept
Implements coupledFaPatch.
Definition at line 193 of file processorFaPatch.H.
tag()
virtual int tag () const inline virtual
Implements processorLduInterface.
Definition at line 200 of file processorFaPatch.H.
References UPstream::msgType().
comm()
Foam::label comm () const virtual
Implements processorLduInterface.
Definition at line 119 of file processorFaPatch.C.
References boundaryMesh::mesh().
Referenced by processorFaPatchField< Type >::comm().
forwardT()
virtual const tensorField & forwardT () const inline virtual
Implements processorLduInterface.
Definition at line 210 of file processorFaPatch.H.
References coupledFaPatch::forwardT().
Referenced by processorFaPatchField< Type >::forwardT().
delta()
Foam::tmp< Foam::vectorField > delta () const virtual
Implements coupledFaPatch.
Definition at line 430 of file processorFaPatch.C.
References coupledFaPatch::delta(), UPstream::parRun(), and Foam::transform().
neighbEdgeCentres()
const vectorField & neighbEdgeCentres () const inline noexcept
Definition at line 220 of file processorFaPatch.H.
neighbEdgeLengths()
const vectorField & neighbEdgeLengths () const inline noexcept
Definition at line 226 of file processorFaPatch.H.
neighbEdgeNormals()
Foam::tmp< Foam::vectorField > neighbEdgeNormals () const
Definition at line 360 of file processorFaPatch.C.
References tmp< T >::New().
neighbEdgeFaceCentres()
const vectorField & neighbEdgeFaceCentres () const inline noexcept
Definition at line 235 of file processorFaPatch.H.
neighbPoints()
const Foam::labelList & neighbPoints () const
Definition at line 368 of file processorFaPatch.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and Foam::nl.
nonGlobalPatchPoints()
const Foam::labelList & nonGlobalPatchPoints () const
Definition at line 465 of file processorFaPatch.C.
interfaceInternalField() [1/2]
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData) const virtual
Implements coupledFaPatch.
Definition at line 476 of file processorFaPatch.C.
interfaceInternalField() [2/2]
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData, const labelUList & edgeFaces) const virtual
Implements lduInterface.
Definition at line 485 of file processorFaPatch.C.
References tmp< T >::New().
initTransfer()
void initTransfer (const Pstream::commsTypes commsType, const labelUList & interfaceData) const virtual
Reimplemented from coupledFaPatch.
Definition at line 497 of file processorFaPatch.C.
transfer()
Foam::tmp< Foam::labelField > transfer (const Pstream::commsTypes commsType, const labelUList & interfaceData) const virtual
Implements coupledFaPatch.
Definition at line 507 of file processorFaPatch.C.
initInternalFieldTransfer()
void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & internalData) const virtual
Reimplemented from coupledFaPatch.
Definition at line 517 of file processorFaPatch.C.
internalFieldTransfer() [1/2]
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & internalData) const virtual
Implements coupledFaPatch.
Definition at line 527 of file processorFaPatch.C.
internalFieldTransfer() [2/2]
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & internalData, const labelUList & edgeCells) const virtual
Definition at line 537 of file processorFaPatch.C.
write()
void write (Ostream & os) const virtual
Reimplemented from faPatch.
Definition at line 548 of file processorFaPatch.C.
References os(), faPatch::write(), and Ostream::writeEntry().
The documentation for this class was generated from the following files:
src/finiteArea/faMesh/faPatches/constraint/processor/processorFaPatch.H
src/finiteArea/faMesh/faPatches/constraint/processor/processorFaPatch.C