OpenFOAM: fvMatrix< Type > Class Template Reference
fvMatrix< Type > Class Template Reference
A special matrix type and solver, designed for finite volume solutions of scalar equations. Face addressing is used to make all matrix assembly and solution loops vectorise.
#include <fvMatrix.H>
Classes
class fvSolver
Public Types
typedef GeometricField< Type, fvPatchField, volMesh > psiFieldType
typedef GeometricField< Type, fvsPatchField, surfaceMesh > faceFluxFieldType
typedef GeometricField< Type, fvsPatchField, surfaceMesh > * faceFluxFieldPtrType
Public Types inherited from lduMatrix
enum class normTypes : char { NO_NORM , DEFAULT_NORM , L1_SCALED_NORM }
Public Member Functions
ClassName ("fvMatrix")
fvMatrix (const GeometricField< Type, fvPatchField, volMesh > &psi, const dimensionSet &ds)
fvMatrix (const fvMatrix< Type > &)
fvMatrix (const tmp< fvMatrix< Type > > &)
fvMatrix (const GeometricField< Type, fvPatchField, volMesh > &psi, Istream &is)
tmp< fvMatrix< Type > > clone () const
virtual ~fvMatrix ()
label nMatrices () const
const fvMatrix< Type > & matrix (const label i) const
fvMatrix< Type > & matrix (const label i)
label globalPatchID (const label fieldi, const label patchi) const
void transferFvMatrixCoeffs ()
void createOrUpdateLduPrimitiveAssembly ()
lduPrimitiveMeshAssembly * lduMeshPtr ()
const lduPrimitiveMeshAssembly * lduMeshPtr () const
void manipulateMatrix (direction cmp)
void setBounAndInterCoeffs ()
void setInterfaces (lduInterfaceFieldPtrsList &, PtrDynList< lduInterfaceField > &newInterfaces)
void mapContributions (label fieldi, const FieldField< Field, Type > &fluxContrib, FieldField< Field, Type > &contrib, bool internal) const
const lduPrimitiveMeshAssembly & lduMeshAssembly ()
const GeometricField< Type, fvPatchField, volMesh > & psi (const label i=0) const
GeometricField< Type, fvPatchField, volMesh > & psi (const label i=0)
void clear ()
const dimensionSet & dimensions () const noexcept
Field< Type > & source () noexcept
const Field< Type > & source () const noexcept
const FieldField< Field, Type > & internalCoeffs () const noexcept
FieldField< Field, Type > & internalCoeffs () noexcept
const FieldField< Field, Type > & boundaryCoeffs () const noexcept
FieldField< Field, Type > & boundaryCoeffs () noexcept
faceFluxFieldPtrType & faceFluxCorrectionPtr ()
bool hasFaceFluxCorrection () const noexcept
void setValues (const labelUList &cellLabels, const Type &value)
void setValues (const labelUList &cellLabels, const UList< Type > &values)
void setValues (const labelUList &cellLabels, const UIndirectList< Type > &values)
void setReference (const label celli, const Type &value, const bool forceReference=false)
void setReferences (const labelUList &cellLabels, const Type &value, const bool forceReference=false)
void setReferences (const labelUList &cellLabels, const UList< Type > &values, const bool forceReference=false)
void setComponentReference (const label patchi, const label facei, const direction cmpt, const scalar value)
void addFvMatrix (fvMatrix< Type > &matrix)
void relax (const scalar alpha)
void relax ()
void boundaryManipulate (typename GeometricField< Type, fvPatchField, volMesh >::Boundary &values)
autoPtr< fvSolver > solver (const dictionary &)
autoPtr< fvSolver > solver ()
SolverPerformance< Type > solveSegregatedOrCoupled (const dictionary &)
SolverPerformance< Type > solveSegregated (const dictionary &)
SolverPerformance< Type > solveCoupled (const dictionary &)
SolverPerformance< Type > solve (const dictionary &)
SolverPerformance< Type > solve ()
tmp< Field< Type > > residual () const
tmp< scalarField > D () const
tmp< Field< Type > > DD () const
tmp< volScalarField > A () const
tmp< GeometricField< Type, fvPatchField, volMesh > > H () const
tmp< volScalarField > H1 () const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux () const
const dictionary & solverDict () const
void operator= (const fvMatrix< Type > &)
void operator= (const tmp< fvMatrix< Type > > &)
void negate ()
void operator+= (const fvMatrix< Type > &)
void operator+= (const tmp< fvMatrix< Type > > &)
void operator-= (const fvMatrix< Type > &)
void operator-= (const tmp< fvMatrix< Type > > &)
void operator+= (const DimensionedField< Type, volMesh > &)
void operator+= (const tmp< DimensionedField< Type, volMesh > > &)
void operator+= (const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
void operator-= (const DimensionedField< Type, volMesh > &)
void operator-= (const tmp< DimensionedField< Type, volMesh > > &)
void operator-= (const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator+= (const Foam::zero)
void operator-= (const Foam::zero)
void operator*= (const volScalarField::Internal &)
void operator*= (const tmp< volScalarField::Internal > &)
void operator*= (const tmp< volScalarField > &)
void operator*= (const dimensioned< scalar > &)
void setComponentReference (const label patchi, const label facei, const direction, const scalar value)
Foam::autoPtr< Foam::fvMatrix< Foam::scalar >::fvSolver > solver (const dictionary &solverControls)
Foam::solverPerformance solveSegregated (const dictionary &solverControls)
Foam::tmp< Foam::scalarField > residual () const
Foam::tmp< Foam::volScalarField > H () const
Foam::tmp< Foam::volScalarField > H1 () const
void setComponentReference (const label patchi, const label facei, const direction, const scalar value)
autoPtr< fvMatrix< scalar >::fvSolver > solver (const dictionary &)
solverPerformance solveSegregated (const dictionary &)
tmp< scalarField > residual () const
tmp< volScalarField > H () const
tmp< volScalarField > H1 () const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
int use_count () const noexcept
bool unique () const noexcept
void operator++ () noexcept
void operator++ (int) noexcept
void operator-- () noexcept
void operator-- (int) noexcept
Public Member Functions inherited from lduMatrix
ClassName ("lduMatrix")
lduMatrix (const lduMesh &)
lduMatrix (const lduMatrix &)
lduMatrix (lduMatrix &, bool reuse)
lduMatrix (const lduMesh &, Istream &)
~lduMatrix ()
const lduMesh & mesh () const noexcept
void setLduMesh (const lduMesh &m)
const lduAddressing & lduAddr () const
const lduSchedule & patchSchedule () const
scalarField & lower ()
scalarField & diag ()
scalarField & upper ()
scalarField & lower (const label size)
scalarField & diag (const label nCoeffs)
scalarField & upper (const label nCoeffs)
const scalarField & lower () const
const scalarField & diag () const
const scalarField & upper () const
bool hasDiag () const noexcept
bool hasUpper () const noexcept
bool hasLower () const noexcept
bool diagonal () const noexcept
bool symmetric () const noexcept
bool asymmetric () const noexcept
void sumDiag ()
void negSumDiag ()
void sumMagOffDiag (scalarField &sumOff) const
void Amul (solveScalarField &, const tmp< solveScalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
void Tmul (solveScalarField &, const tmp< solveScalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
void sumA (solveScalarField &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &) const
void residual (solveScalarField &rA, const solveScalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
tmp< solveScalarField > residual (const solveScalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
void initMatrixInterfaces (const bool add, const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const solveScalarField &psiif, solveScalarField &result, const direction cmpt) const
void updateMatrixInterfaces (const bool add, const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const solveScalarField &psiif, solveScalarField &result, const direction cmpt, const label startRequest) const
void setResidualField (const scalarField &residual, const word &fieldName, const bool initial) const
template<class Type >
tmp< Field< Type > > H (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > H (const tmp< Field< Type > > &) const
tmp< scalarField > H1 () const
template<class Type >
tmp< Field< Type > > faceH (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > faceH (const tmp< Field< Type > > &) const
InfoProxy< lduMatrix > info () const noexcept
void operator= (const lduMatrix &)
void negate ()
void operator+= (const lduMatrix &)
void operator-= (const lduMatrix &)
void operator*= (const scalarField &)
void operator*= (scalar)
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const tmp< Field< Type > > &tpsi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const tmp< Field< Type > > &tpsi) const
Protected Member Functions
template<class Type2 >
void addToInternalField (const labelUList &addr, const Field< Type2 > &pf, Field< Type2 > &intf) const
template<class Type2 >
void addToInternalField (const labelUList &addr, const tmp< Field< Type2 > > &tpf, Field< Type2 > &intf) const
template<class Type2 >
void subtractFromInternalField (const labelUList &addr, const Field< Type2 > &pf, Field< Type2 > &intf) const
template<class Type2 >
void subtractFromInternalField (const labelUList &addr, const tmp< Field< Type2 > > &tpf, Field< Type2 > &intf) const
bool checkImplicit (const label fieldi=0)
void addBoundaryDiag (scalarField &diag, const direction cmpt) const
void addCmptAvBoundaryDiag (scalarField &diag) const
void addBoundarySource (Field< Type > &source, const bool couples=true) const
template<template< class > class ListType>
void setValuesFromList (const labelUList &cellLabels, const ListType< Type > &values)
Friends
class fvSolver
tmp< GeometricField< Type, fvPatchField, volMesh > > operator& (const fvMatrix< Type > &, const DimensionedField< Type, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > operator& (const fvMatrix< Type > &, const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > operator& (const tmp< fvMatrix< Type > > &, const DimensionedField< Type, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > operator& (const tmp< fvMatrix< Type > > &, const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
Ostream & operator<< (Ostream &, const fvMatrix< Type > &)
Additional Inherited Members
Static Public Attributes inherited from lduMatrix
static const Enum< normTypes > normTypesNames_
static constexpr const label defaultMaxIter = 1000
static const scalar defaultTolerance = 1e-6
Detailed Description
template<class Type>
class Foam::fvMatrix< Type >
A special matrix type and solver, designed for finite volume solutions of scalar equations. Face addressing is used to make all matrix assembly and solution loops vectorise.
Source files
fvMatrix.H
fvMatrix.C
fvMatrixSolve.C
fvScalarMatrix.C
Definition at line 112 of file fvMatrix.H.
Member Typedef Documentation
psiFieldType
template<class Type > typedef GeometricField<Type, fvPatchField, volMesh> psiFieldType
Definition at line 124 of file fvMatrix.H.
faceFluxFieldType
template<class Type > typedef GeometricField<Type, fvsPatchField, surfaceMesh> faceFluxFieldType
Definition at line 129 of file fvMatrix.H.
faceFluxFieldPtrType
template<class Type > typedef GeometricField<Type, fvsPatchField, surfaceMesh>* faceFluxFieldPtrType
Definition at line 493 of file fvMatrix.H.
Constructor & Destructor Documentation
fvMatrix() [1/4]
template<class Type > fvMatrix (const GeometricField< Type, fvPatchField, volMesh > & psi, const dimensionSet & ds)
Definition at line 351 of file fvMatrix.C.
References fvMatrix< Type >::checkImplicit(), DebugInFunction, Foam::endl(), forAll, psi, PtrList< T >::set(), and Foam::Zero.
fvMatrix() [2/4]
template<class Type > fvMatrix (const fvMatrix< Type > & fvm)
Definition at line 396 of file fvMatrix.C.
References DebugInFunction, and Foam::endl().
fvMatrix() [3/4]
template<class Type > fvMatrix (const tmp< fvMatrix< Type > > & tmat)
Definition at line 424 of file fvMatrix.C.
References PtrList< T >::clear(), DebugInFunction, and Foam::endl().
fvMatrix() [4/4]
template<class Type > fvMatrix (const GeometricField< Type, fvPatchField, volMesh > & psi, Istream & is) inline
Definition at line 308 of file fvMatrix.H.
~fvMatrix()
template<class Type > ~fvMatrix () virtual
Definition at line 464 of file fvMatrix.C.
References DebugInFunction, Foam::deleteDemandDrivenData(), and Foam::endl().
Member Function Documentation
addToInternalField() [1/2]
template<class Type > template<class Type2 > void addToInternalField (const labelUList & addr, const Field< Type2 > & pf, Field< Type2 > & intf) const protected
Definition at line 41 of file fvMatrix.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, and UPtrList< T >::size().
addToInternalField() [2/2]
template<class Type > template<class Type2 > void addToInternalField (const labelUList & addr, const tmp< Field< Type2 > > & tpf, Field< Type2 > & intf) const protected
Definition at line 65 of file fvMatrix.C.
References PtrList< T >::clear().
subtractFromInternalField() [1/2]
template<class Type > template<class Type2 > void subtractFromInternalField (const labelUList & addr, const Field< Type2 > & pf, Field< Type2 > & intf) const protected
Definition at line 79 of file fvMatrix.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, and UPtrList< T >::size().
subtractFromInternalField() [2/2]
template<class Type > template<class Type2 > void subtractFromInternalField (const labelUList & addr, const tmp< Field< Type2 > > & tpf, Field< Type2 > & intf) const protected
Definition at line 103 of file fvMatrix.C.
References PtrList< T >::clear().
checkImplicit()
template<class Type > bool checkImplicit (const label fieldi = 0) protected
Definition at line 315 of file fvMatrix.C.
References UPtrList< T >::empty(), Foam::endl(), forAll, Foam::name(), Foam::Pout, and psi.
Referenced by fvMatrix< Type >::fvMatrix().
addBoundaryDiag()
template<class Type > void addBoundaryDiag (scalarField & diag, const direction cmpt) const protected
Definition at line 116 of file fvMatrix.C.
References Foam::component(), Foam::diag(), forAll, and psi.
addCmptAvBoundaryDiag()
template<class Type > void addCmptAvBoundaryDiag (scalarField & diag) const protected
Definition at line 145 of file fvMatrix.C.
References Foam::cmptAv(), Foam::diag(), forAll, and psi.
addBoundarySource()
template<class Type > void addBoundarySource (Field< Type > & source, const bool couples = true) const protected
Definition at line 169 of file fvMatrix.C.
References Foam::cmptMultiply(), forAll, and psi.
setValuesFromList()
template<class Type > template<template< class > class ListType> void setValuesFromList (const labelUList & cellLabels, const ListType< Type > & values) protected
Definition at line 219 of file fvMatrix.C.
References polyMesh::boundaryMesh(), cells, primitiveMesh::cells(), Foam::diag(), forAll, primitiveMesh::isInternalFace(), mesh, fvMesh::neighbour(), fvMesh::owner(), primitiveFieldRef(), psi, and Foam::Zero.
ClassName()
template<class Type > ClassName ("fvMatrix< Type >")
clone()
template<class Type > tmp< fvMatrix< Type > > clone () const inline
Definition at line 318 of file fvMatrix.H.
References Foam::New().
Referenced by fvMatrix< Type >::addFvMatrix().
nMatrices()
template<class Type > label nMatrices () const inline
Definition at line 334 of file fvMatrix.H.
matrix() [1/2]
template<class Type > const fvMatrix< Type > & matrix (const label i) const inline
Definition at line 339 of file fvMatrix.H.
Referenced by fvMatrix< Type >::psi(), and fvMatrix< Type >::psi().
matrix() [2/2]
template<class Type > fvMatrix< Type > & matrix (const label i) inline
Definition at line 344 of file fvMatrix.H.
globalPatchID()
template<class Type > label globalPatchID (const label fieldi, const label patchi) const inline
Definition at line 349 of file fvMatrix.H.
References fvMatrix< Type >::lduMeshPtr(), and lduPrimitiveMeshAssembly::patchMap().
transferFvMatrixCoeffs()
template<class Type > void transferFvMatrixCoeffs ()
Definition at line 821 of file fvMatrix.C.
References Foam::diag(), Foam::faceMap(), forAll, PtrList< T >::setSize(), UPtrList< T >::size(), and Foam::Zero.
createOrUpdateLduPrimitiveAssembly()
template<class Type > void createOrUpdateLduPrimitiveAssembly ()
Definition at line 914 of file fvMatrix.C.
References Foam::endl(), Foam::Info, io(), lduPrimitiveMesh::lduAddr(), IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, psi, IOobjectOption::REGISTER, PtrList< T >::set(), and lduPrimitiveMeshAssembly::update().
lduMeshPtr() [1/2]
template<class Type > Foam::lduPrimitiveMeshAssembly * lduMeshPtr ()
Definition at line 888 of file fvMatrix.C.
Referenced by fvMatrix< Type >::globalPatchID(), and fvMatrix< Type >::lduMeshAssembly().
lduMeshPtr() [2/2]
template<class Type > const Foam::lduPrimitiveMeshAssembly * lduMeshPtr () const
Definition at line 901 of file fvMatrix.C.
manipulateMatrix()
template<class Type > void manipulateMatrix (direction cmp)
Definition at line 798 of file fvMatrix.C.
References forAll, and psi.
setBounAndInterCoeffs()
template<class Type > void setBounAndInterCoeffs ()
Definition at line 668 of file fvMatrix.C.
References boundary, forAll, psi, PtrList< T >::set(), List< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), and Foam::Zero.
setInterfaces()
template<class Type > void setInterfaces (lduInterfaceFieldPtrsList & interfaces, PtrDynList< lduInterfaceField > & newInterfaces)
Definition at line 477 of file fvMatrix.C.
References PtrList< T >::append(), forAll, UPtrList< T >::last(), psi, PtrList< T >::set(), UPtrList< T >::set(), and UPtrList< T >::setSize().
mapContributions()
template<class Type > void mapContributions (label fieldi, const FieldField< Field, Type > & fluxContrib, FieldField< Field, Type > & contrib, bool internal) const
Definition at line 555 of file fvMatrix.C.
References lduPrimitiveMeshAssembly::cellBoundMap(), cellId, Foam::cmptMultiply(), coupled(), faceId(), lduPrimitiveMeshAssembly::facePatchFaceMap(), forAll, lduPrimitiveMeshAssembly::patchLocalToGlobalMap(), lduPrimitiveMeshAssembly::patchMap(), pp(), psi, and PtrList< T >::setSize().
lduMeshAssembly()
template<class Type > const lduPrimitiveMeshAssembly & lduMeshAssembly () inline
Definition at line 400 of file fvMatrix.H.
References fvMatrix< Type >::lduMeshPtr().
psi() [1/2]
template<class Type > const GeometricField< Type, fvPatchField, volMesh > & psi (const label i = 0) const inline
Definition at line 406 of file fvMatrix.H.
References fvMatrix< Type >::matrix().
Referenced by MRFZone::addCoriolis(), MRFZone::addCoriolis(), and Foam::oversetPatchPhiErr().
psi() [2/2]
template<class Type > GeometricField< Type, fvPatchField, volMesh > & psi (const label i = 0) inline
Definition at line 418 of file fvMatrix.H.
References fvMatrix< Type >::matrix().
clear()
template<class Type > void clear () inline
Definition at line 441 of file fvMatrix.H.
References PtrList< T >::clear().
dimensions()
template<class Type > const dimensionSet & dimensions () const inline noexcept
Definition at line 448 of file fvMatrix.H.
Referenced by fvMatrix< Type >::addFvMatrix().
source() [1/2]
template<class Type > Field< Type > & source () inline noexcept
Definition at line 453 of file fvMatrix.H.
Referenced by MRFZone::addCoriolis(), MRFZone::addCoriolis(), and ReactingCloud< CloudType >::SYi().
source() [2/2]
template<class Type > const Field< Type > & source () const inline noexcept
Definition at line 458 of file fvMatrix.H.
internalCoeffs() [1/2]
template<class Type > const FieldField< Field, Type > & internalCoeffs () const inline noexcept
Definition at line 465 of file fvMatrix.H.
internalCoeffs() [2/2]
template<class Type > FieldField< Field, Type > & internalCoeffs () inline noexcept
Definition at line 472 of file fvMatrix.H.
boundaryCoeffs() [1/2]
template<class Type > const FieldField< Field, Type > & boundaryCoeffs () const inline noexcept
Definition at line 479 of file fvMatrix.H.
boundaryCoeffs() [2/2]
template<class Type > FieldField< Field, Type > & boundaryCoeffs () inline noexcept
Definition at line 486 of file fvMatrix.H.
faceFluxCorrectionPtr()
template<class Type > faceFluxFieldPtrType & faceFluxCorrectionPtr () inline
Definition at line 496 of file fvMatrix.H.
hasFaceFluxCorrection()
template<class Type > bool hasFaceFluxCorrection () const inline noexcept
Definition at line 502 of file fvMatrix.H.
setValues() [1/3]
template<class Type > void setValues (const labelUList & cellLabels, const Type & value)
Definition at line 977 of file fvMatrix.C.
setValues() [2/3]
template<class Type > void setValues (const labelUList & cellLabels, const UList< Type > & values)
Definition at line 988 of file fvMatrix.C.
setValues() [3/3]
template<class Type > void setValues (const labelUList & cellLabels, const UIndirectList< Type > & values)
Definition at line 999 of file fvMatrix.C.
setReference()
template<class Type > void setReference (const label celli, const Type & value, const bool forceReference = false)
Definition at line 1010 of file fvMatrix.C.
References Foam::diag().
Referenced by adjointSimple::mainIter().
setReferences() [1/2]
template<class Type > void setReferences (const labelUList & cellLabels, const Type & value, const bool forceReference = false)
Definition at line 1026 of file fvMatrix.C.
References cellId, Foam::diag(), and forAll.
setReferences() [2/2]
template<class Type > void setReferences (const labelUList & cellLabels, const UList< Type > & values, const bool forceReference = false)
Definition at line 1049 of file fvMatrix.C.
References cellId, Foam::diag(), and forAll.
setComponentReference() [1/3]
template<class Type > void setComponentReference (const label patchi, const label facei, const direction cmpt, const scalar value)
Definition at line 30 of file fvMatrixSolve.C.
References Foam::diag(), and UPstream::master().
addFvMatrix()
template<class Type > void addFvMatrix (fvMatrix< Type > & matrix)
Definition at line 1072 of file fvMatrix.C.
References Foam::abort(), PtrList< T >::append(), fvMatrix< Type >::clone(), fvMatrix< Type >::dimensions(), Foam::endl(), Foam::FatalError, and FatalErrorInFunction.
relax() [1/2]
template<class Type > void relax (const scalar alpha)
Definition at line 1101 of file fvMatrix.C.
References alpha, Foam::cmptMag(), Foam::cmptMax(), Foam::cmptMin(), Foam::component(), D, DebugInFunction, Foam::diag(), Foam::endl(), forAll, InfoInFunction, Foam::mag(), Foam::max(), UPstream::msgType(), Foam::nl, Foam::reduce(), Foam::returnReduce(), UPtrList< T >::size(), and Foam::Zero.
Referenced by incompressiblePrimalSolver::correctBoundaryConditions(), simple::mainIter(), thermalShell::solveEnergy(), and kinematicSingleLayer::solveMomentum().
relax() [2/2]
template<class Type > void relax ()
Definition at line 1249 of file fvMatrix.C.
References Foam::name(), and relax().
boundaryManipulate()
template<class Type > void boundaryManipulate (typename GeometricField< Type, fvPatchField, volMesh >::Boundary & values)
Definition at line 1265 of file fvMatrix.C.
References forAll.
Referenced by adjointSimple::mainIter().
solver() [1/4]
template<class Type > autoPtr< fvSolver > solver (const dictionary &)
solver() [2/4]
template<class Type > Foam::autoPtr< typename Foam::fvMatrix< Type >::fvSolver > solver ()
Definition at line 322 of file fvMatrixSolve.C.
solveSegregatedOrCoupled()
template<class Type > Foam::SolverPerformance< Type > solveSegregatedOrCoupled (const dictionary & solverControls)
Definition at line 54 of file fvMatrixSolve.C.
References addProfiling, polyMesh::defaultRegion, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::Info, messageStream::masterStream(), mesh, regionName, solve(), and Foam::type().
Referenced by displacementComponentLaplacianFvMotionSolver::solve(), velocityComponentLaplacianFvMotionSolver::solve(), displacementLaplacianFvMotionSolver::solve(), displacementSBRStressFvMotionSolver::solve(), solidBodyDisplacementLaplacianFvMotionSolver::solve(), and velocityLaplacianFvMotionSolver::solve().
solveSegregated() [1/3]
template<class Type > Foam::SolverPerformance< Type > solveSegregated (const dictionary & solverControls)
Definition at line 104 of file fvMatrixSolve.C.
References Foam::diag(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, messageStream::masterStream(), mesh, lduMatrix::solver::New(), UPstream::nRequests(), and psi.
solveCoupled()
template<class Type > Foam::SolverPerformance< Type > solveCoupled (const dictionary & solverControls)
Definition at line 244 of file fvMatrixSolve.C.
References Foam::diag(), Foam::endl(), Foam::Info, messageStream::masterStream(), mesh, and psi.
solve() [1/2]
template<class Type > Foam::SolverPerformance< Type > solve (const dictionary & solverControls)
Definition at line 311 of file fvMatrixSolve.C.
Referenced by adjointSimple::mainIter(), thermalShell::solveEnergy(), reactingOneDim::solveSpeciesMass(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi().
solve() [2/2]
template<class Type > Foam::SolverPerformance< Type > solve ()
Definition at line 336 of file fvMatrixSolve.C.
References solve().
residual() [1/3]
template<class Type > Foam::tmp< Foam::Field< Type > > residual () const
Definition at line 343 of file fvMatrixSolve.C.
References lduMatrix::residual(), and Foam::Zero.
D()
template<class Type > Foam::tmp< Foam::scalarField > D () const
Definition at line 1279 of file fvMatrix.C.
References Foam::diag(), and tmp< T >::New().
DD()
template<class Type > Foam::tmp< Foam::Field< Type > > DD () const
Definition at line 1288 of file fvMatrix.C.
References Foam::diag(), forAll, and UPtrList< T >::size().
A()
template<class Type > Foam::tmp< Foam::volScalarField > A () const
Definition at line 1312 of file fvMatrix.C.
References D, Foam::dimVol, fvPatchFieldBase::extrapolatedCalculatedType(), and GeometricField< scalar, fvPatchField, volMesh >::New().
Referenced by incompressiblePrimalSolver::correctBoundaryConditions(), and simple::mainIter().
H() [1/3]
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > H () const
Definition at line 1331 of file fvMatrix.C.
References Foam::dimVol, fvPatchFieldBase::extrapolatedCalculatedType(), lduMatrix::H(), GeometricField< Type, PatchField, GeoMesh >::New(), and Foam::Zero.
Referenced by incompressiblePrimalSolver::correctBoundaryConditions(), and simple::mainIter().
H1() [1/3]
template<class Type > Foam::tmp< Foam::volScalarField > H1 () const
Definition at line 1383 of file fvMatrix.C.
References Foam::component(), Foam::dimVol, fvPatchFieldBase::extrapolatedCalculatedType(), forAll, lduMatrix::H1(), GeometricField< scalar, fvPatchField, volMesh >::New(), and UPtrList< T >::size().
Referenced by simple::mainIter().
flux()
template<class Type > Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > flux () const
Definition at line 1420 of file fvMatrix.C.
References Foam::abort(), Foam::cmptMultiply(), lduMatrix::faceH(), Foam::FatalError, FatalErrorInFunction, forAll, and GeometricField< Type, PatchField, GeoMesh >::New().
Referenced by adjointSimple::mainIter(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi().
solverDict()
template<class Type > const Foam::dictionary & solverDict () const
Definition at line 1524 of file fvMatrix.C.
Referenced by displacementComponentLaplacianFvMotionSolver::solve(), velocityComponentLaplacianFvMotionSolver::solve(), displacementLaplacianFvMotionSolver::solve(), displacementSBRStressFvMotionSolver::solve(), solidBodyDisplacementLaplacianFvMotionSolver::solve(), and velocityLaplacianFvMotionSolver::solve().
operator=() [1/2]
template<class Type > void operator= (const fvMatrix< Type > & fvmv)
Definition at line 1540 of file fvMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and lduMatrix::operator=().
operator=() [2/2]
template<class Type > void operator= (const tmp< fvMatrix< Type > > & tfvmv)
Definition at line 1577 of file fvMatrix.C.
References PtrList< T >::clear().
negate()
template<class Type > void negate ()
Definition at line 1585 of file fvMatrix.C.
References lduMatrix::negate().
operator+=() [1/7]
template<class Type > void operator+= (const fvMatrix< Type > & fvmv)
Definition at line 1600 of file fvMatrix.C.
References Foam::checkMethod(), and lduMatrix::operator+=().
operator+=() [2/7]
template<class Type > void operator+= (const tmp< fvMatrix< Type > > & tfvmv)
Definition at line 1630 of file fvMatrix.C.
References PtrList< T >::clear().
operator-=() [1/7]
template<class Type > void operator-= (const fvMatrix< Type > & fvmv)
Definition at line 1638 of file fvMatrix.C.
References Foam::checkMethod(), and lduMatrix::operator-=().
operator-=() [2/7]
template<class Type > void operator-= (const tmp< fvMatrix< Type > > & tfvmv)
Definition at line 1666 of file fvMatrix.C.
References PtrList< T >::clear().
operator+=() [3/7]
template<class Type > void operator+= (const DimensionedField< Type, volMesh > & su)
Definition at line 1674 of file fvMatrix.C.
References Foam::checkMethod().
operator+=() [4/7]
template<class Type > void operator+= (const tmp< DimensionedField< Type, volMesh > > & tsu)
Definition at line 1685 of file fvMatrix.C.
References PtrList< T >::clear().
operator+=() [5/7]
template<class Type > void operator+= (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tsu)
Definition at line 1696 of file fvMatrix.C.
References PtrList< T >::clear().
operator-=() [3/7]
template<class Type > void operator-= (const DimensionedField< Type, volMesh > & su)
Definition at line 1707 of file fvMatrix.C.
References Foam::checkMethod().
operator-=() [4/7]
template<class Type > void operator-= (const tmp< DimensionedField< Type, volMesh > > & tsu)
Definition at line 1718 of file fvMatrix.C.
References PtrList< T >::clear().
operator-=() [5/7]
template<class Type > void operator-= (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tsu)
Definition at line 1729 of file fvMatrix.C.
References PtrList< T >::clear().
operator+=() [6/7]
template<class Type > void operator+= (const dimensioned< Type > & su)
Definition at line 1740 of file fvMatrix.C.
References psi.
operator-=() [6/7]
template<class Type > void operator-= (const dimensioned< Type > & su)
Definition at line 1750 of file fvMatrix.C.
References psi.
operator+=() [7/7]
template<class Type > void operator+= (const Foam::zero)
Definition at line 1760 of file fvMatrix.C.
operator-=() [7/7]
template<class Type > void operator-= (const Foam::zero)
Definition at line 1765 of file fvMatrix.C.
operator*=() [1/4]
template<class Type > void operator*= (const volScalarField::Internal & dsf)
Definition at line 1770 of file fvMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, and lduMatrix::operator*=().
operator*=() [2/4]
template<class Type > void operator*= (const tmp< volScalarField::Internal > & tfld)
Definition at line 1800 of file fvMatrix.C.
References PtrList< T >::clear().
operator*=() [3/4]
template<class Type > void operator*= (const tmp< volScalarField > & tfld)
Definition at line 1811 of file fvMatrix.C.
References PtrList< T >::clear().
operator*=() [4/4]
template<class Type > void operator*= (const dimensioned< scalar > & ds)
Definition at line 1822 of file fvMatrix.C.
References lduMatrix::operator*=().
setComponentReference() [2/3]
void setComponentReference (const label patchi, const label facei, const direction , const scalar value)
Definition at line 33 of file fvScalarMatrix.C.
References Foam::diag(), and UPstream::master().
solver() [3/4]
Foam::autoPtr< Foam::fvMatrix< Foam::scalar >::fvSolver > solver (const dictionary & solverControls)
Definition at line 58 of file fvScalarMatrix.C.
References addProfiling, polyMesh::defaultRegion, Foam::diag(), Foam::endl(), Foam::Info, messageStream::masterStream(), mesh, lduMatrix::solver::New(), regionName, and solve().
solveSegregated() [2/3]
Foam::solverPerformance solveSegregated (const dictionary & solverControls)
Definition at line 158 of file fvScalarMatrix.C.
References Foam::diag(), Foam::endl(), forAll, Foam::Info, messageStream::masterStream(), mesh, Foam::name(), tmp< T >::New(), lduMatrix::solver::New(), primitiveFieldRef(), psi, UPtrList< T >::size(), and Foam::Zero.
residual() [2/3]
Foam::tmp< Foam::scalarField > residual () const
Definition at line 321 of file fvScalarMatrix.C.
References psi, lduMatrix::residual(), and Foam::Zero.
H() [2/3]
Foam::tmp< Foam::volScalarField > H () const
Definition at line 350 of file fvScalarMatrix.C.
References Foam::dimVol, fvPatchFieldBase::extrapolatedCalculatedType(), lduMatrix::H(), and GeometricField< scalar, fvPatchField, volMesh >::New().
H1() [2/3]
Foam::tmp< Foam::volScalarField > H1 () const
Definition at line 372 of file fvScalarMatrix.C.
References Foam::dimVol, fvPatchFieldBase::extrapolatedCalculatedType(), lduMatrix::H1(), and GeometricField< scalar, fvPatchField, volMesh >::New().
setComponentReference() [3/3]
void setComponentReference (const label patchi, const label facei, const direction , const scalar value)
solver() [4/4]
autoPtr< fvMatrix< scalar >::fvSolver > solver (const dictionary &)
solveSegregated() [3/3]
solverPerformance solveSegregated (const dictionary &)
residual() [3/3]
tmp< scalarField > residual () const
H() [3/3]
tmp< volScalarField > H () const
H1() [3/3]
tmp< volScalarField > H1 () const
Friends And Related Symbol Documentation
fvSolver
template<class Type > friend class fvSolver friend
Definition at line 176 of file fvMatrix.H.
operator& [1/4]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > operator& (const fvMatrix< Type > & , const DimensionedField< Type, volMesh > &) friend
operator& [2/4]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > operator& (const fvMatrix< Type > & , const tmp< GeometricField< Type, fvPatchField, volMesh > > &) friend
operator& [3/4]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > operator& (const tmp< fvMatrix< Type > > & , const DimensionedField< Type, volMesh > &) friend
operator& [4/4]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > operator& (const tmp< fvMatrix< Type > > & , const tmp< GeometricField< Type, fvPatchField, volMesh > > &) friend
operator<<
template<class Type > Ostream & operator<< (Ostream & , const fvMatrix< Type > &) friend
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/fvPatchField/fvPatchField.H
src/finiteVolume/fvMatrices/fvMatrix/fvMatrix.H
src/finiteVolume/fvMatrices/fvMatrix/fvMatrix.C
src/finiteVolume/fvMatrices/fvMatrix/fvMatrixSolve.C