OpenFOAM: tetIndices Class Reference
tetIndices Class Reference
Storage and named access for the indices of a tet which is part of the decomposition of a cell.
#include <tetIndices.H>
Public Member Functions
constexpr tetIndices () noexcept
constexpr tetIndices (label celli, label facei, label tetPointi) noexcept
~tetIndices ()=default
label cell () const noexcept
label & cell () noexcept
label face () const noexcept
label & face () noexcept
label tetPt () const noexcept
label & tetPt () noexcept
triFace faceTriIs (const polyMesh &mesh, const bool warn=true) const
triFace triIs (const polyMesh &mesh, const bool warn=true) const
tetPointRef tet (const polyMesh &mesh) const
tetPointRef oldTet (const polyMesh &mesh) const
triPointRef faceTri (const polyMesh &mesh) const
triPointRef oldFaceTri (const polyMesh &mesh) const
point barycentricToPoint (const polyMesh &mesh, const barycentric &bary) const
Static Public Member Functions
static label compare (const tetIndices &a, const tetIndices &b) noexcept
Friends
Istream & operator>> (Istream &, tetIndices &)
Ostream & operator<< (Ostream &, const tetIndices &)
Detailed Description
Storage and named access for the indices of a tet which is part of the decomposition of a cell.
Tets are designated by
cell (of course)
face on cell
three points on face (faceBasePt, facePtA, facePtB) When constructing from a mesh and index in the face (tetPtI):
faceBasePt is the mesh.tetBasePtIs() base point
facePtA is tetPtI away from faceBasePt
facePtB is next one after/before facePtA e.g.:
+—+ |2 /| | / | |/ 1| <- tetPt (so 1 for first triangle, 2 for second) +—+ ^ faceBasePt
Source files
tetIndices.H
tetIndicesI.H
tetIndices.C
Definition at line 78 of file tetIndices.H.
Constructor & Destructor Documentation
tetIndices() [1/2]
constexpr tetIndices () inline constexpr noexcept
Definition at line 24 of file tetIndicesI.H.
tetIndices() [2/2]
constexpr tetIndices (label celli, label facei, label tetPointi) inline constexpr noexcept
Definition at line 32 of file tetIndicesI.H.
~tetIndices()
~tetIndices () default
Member Function Documentation
cell() [1/2]
label cell () const inline noexcept
Definition at line 128 of file tetIndices.H.
Referenced by interpolationCell< Type >::interpolate(), Foam::operator<<(), and Foam::operator>>().
cell() [2/2]
label & cell () inline noexcept
Definition at line 131 of file tetIndices.H.
face() [1/2]
label face () const inline noexcept
Definition at line 134 of file tetIndices.H.
Referenced by polyMesh::findTetFacePt(), Foam::operator<<(), and Foam::operator>>().
face() [2/2]
label & face () inline noexcept
Definition at line 137 of file tetIndices.H.
tetPt() [1/2]
label tetPt () const inline noexcept
Definition at line 140 of file tetIndices.H.
Referenced by polyMesh::findTetFacePt(), Foam::operator<<(), and Foam::operator>>().
tetPt() [2/2]
label & tetPt () inline noexcept
Definition at line 143 of file tetIndices.H.
faceTriIs()
Foam::triFace faceTriIs (const polyMesh & mesh, const bool warn = true) const inline
Definition at line 47 of file tetIndicesI.H.
References Foam::endl(), f(), polyMesh::faceOwner(), polyMesh::faces(), UList< T >::fcIndex(), mesh, UList< T >::size(), polyMesh::tetBasePtIs(), Foam::Warning, and WarningInFunction.
triIs()
Foam::triFace triIs (const polyMesh & mesh, const bool warn = true) const inline
Definition at line 88 of file tetIndicesI.H.
References Foam::endl(), f(), polyMesh::faceOwner(), polyMesh::faces(), UList< T >::fcIndex(), mesh, UList< T >::size(), polyMesh::tetBasePtIs(), Foam::Warning, and WarningInFunction.
tet()
Foam::tetPointRef tet (const polyMesh & mesh) const inline
Definition at line 129 of file tetIndicesI.H.
References primitiveMesh::cellCentres(), mesh, polyMesh::points(), and pts.
Referenced by nearWallFields::calcAddressing().
oldTet()
Foam::tetPointRef oldTet (const polyMesh & mesh) const inline
Definition at line 144 of file tetIndicesI.H.
References mesh, polyMesh::oldCellCentres(), polyMesh::oldPoints(), and pts.
faceTri()
Foam::triPointRef faceTri (const polyMesh & mesh) const inline
Definition at line 182 of file tetIndicesI.H.
References mesh, and polyMesh::points().
oldFaceTri()
Foam::triPointRef oldFaceTri (const polyMesh & mesh) const inline
Definition at line 188 of file tetIndicesI.H.
References mesh, and polyMesh::oldPoints().
barycentricToPoint()
Foam::point barycentricToPoint (const polyMesh & mesh, const barycentric & bary) const inline
Definition at line 159 of file tetIndicesI.H.
References b, primitiveMesh::cellCentres(), mesh, polyMesh::points(), pts, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
compare()
Foam::label compare (const tetIndices & a, const tetIndices & b) inline static noexcept
Definition at line 197 of file tetIndicesI.H.
References b, and Foam::diff().
Referenced by Foam::operator<(), Foam::operator<=(), Foam::operator>(), and Foam::operator>=().
Friends And Related Symbol Documentation
operator>>
Istream & operator>> (Istream & , tetIndices &) friend
operator<<
Ostream & operator<< (Ostream & , const tetIndices &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyMeshTetDecomposition/tetIndices.H
src/OpenFOAM/meshes/polyMesh/polyMeshTetDecomposition/tetIndices.C
src/OpenFOAM/meshes/polyMesh/polyMeshTetDecomposition/tetIndicesI.H