OpenFOAM: basicMultiComponentMixture Class Reference
basicMultiComponentMixture Class Reference
Thermophysical models » Reaction thermophysical models » Mixtures
Multi-component mixture.
#include <basicMultiComponentMixture.H>
Public Types
typedef basicMultiComponentMixture basicMixtureType
Public Types inherited from basicMixture
typedef basicMixture basicMixtureType
Public Member Functions
TypeName ("basicMultiComponentMixture")
basicMultiComponentMixture (const dictionary &thermoDict, const wordList &specieNames, const fvMesh &mesh, const word &phaseName)
virtual ~basicMultiComponentMixture ()=default
const speciesTable & species () const
bool contains (const word &specieName) const
bool active (label speciei) const
const List< bool > & active () const
void setActive (label speciei)
void setInactive (label speciei)
PtrList< volScalarField > & Y ()
const PtrList< volScalarField > & Y () const
volScalarField & Y (const label i)
const volScalarField & Y (const label i) const
volScalarField & Y (const word &specieName)
const volScalarField & Y (const word &specieName) const
Public Member Functions inherited from basicMixture
basicMixture (const dictionary &, const fvMesh &, const word &)
Protected Attributes
speciesTable species_
List< bool > active_
PtrList< volScalarField > Y_
Detailed Description
Multi-component mixture.
Provides a list of mass fraction fields and helper functions to query mixture composition.
Source files
basicMultiComponentMixture.H
basicMultiComponentMixture.C
Definition at line 56 of file basicMultiComponentMixture.H.
Member Typedef Documentation
basicMixtureType
typedef basicMultiComponentMixture basicMixtureType
Definition at line 82 of file basicMultiComponentMixture.H.
Constructor & Destructor Documentation
basicMultiComponentMixture()
basicMultiComponentMixture (const dictionary & thermoDict, const wordList & specieNames, const fvMesh & mesh, const word & phaseName)
Definition at line 32 of file basicMultiComponentMixture.C.
References IOobjectOption::AUTO_WRITE, DebugInfo, Foam::endl(), forAll, IOobject::groupName(), mesh, IOobjectOption::MUST_READ, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, PtrList< T >::set(), basicMultiComponentMixture::species_, Time::timeName(), IOobject::typeHeaderOk(), and basicMultiComponentMixture::Y_.
~basicMultiComponentMixture()
virtual ~basicMultiComponentMixture () virtual default
Member Function Documentation
TypeName()
TypeName ("basicMultiComponentMixture")
species()
const Foam::speciesTable & species () const inline
Definition at line 22 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::species_.
Referenced by ReactingHeterogeneousParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), ReactingParcel< ParcelType >::calc(), and singleStepReactingMixture< ThermoType >::singleStepReactingMixture().
contains()
bool contains (const word & specieName) const inline
Definition at line 28 of file basicMultiComponentMixtureI.H.
active() [1/2]
bool active (label speciei) const inline
Definition at line 37 of file basicMultiComponentMixtureI.H.
Referenced by TDACChemistryModel< ReactionThermo, ThermoType >::solve().
active() [2/2]
const Foam::List< bool > & active () const inline
Definition at line 43 of file basicMultiComponentMixtureI.H.
setActive()
void setActive (label speciei) inline
Definition at line 49 of file basicMultiComponentMixtureI.H.
Referenced by TDACChemistryModel< ReactionThermo, ThermoType >::solve().
setInactive()
void setInactive (label speciei) inline
Definition at line 55 of file basicMultiComponentMixtureI.H.
Y() [1/6]
Foam::PtrList< Foam::volScalarField > & Y () inline
Definition at line 62 of file basicMultiComponentMixtureI.H.
Referenced by semiPermeableBaffleVelocityFvPatchVectorField::updateCoeffs().
Y() [2/6]
const Foam::PtrList< Foam::volScalarField > & Y () const inline
Definition at line 69 of file basicMultiComponentMixtureI.H.
Y() [3/6]
Foam::volScalarField & Y (const label i) inline
Definition at line 75 of file basicMultiComponentMixtureI.H.
Y() [4/6]
const Foam::volScalarField & Y (const label i) const inline
Definition at line 81 of file basicMultiComponentMixtureI.H.
Y() [5/6]
Foam::volScalarField & Y (const word & specieName) inline
Definition at line 90 of file basicMultiComponentMixtureI.H.
Y() [6/6]
const Foam::volScalarField & Y (const word & specieName) const inline
Definition at line 99 of file basicMultiComponentMixtureI.H.
Member Data Documentation
species_
speciesTable species_ protected
Definition at line 66 of file basicMultiComponentMixture.H.
Referenced by basicMultiComponentMixture::basicMultiComponentMixture(), multiComponentMixture< ThermoType >::multiComponentMixture(), and basicMultiComponentMixture::species().
active_
List<bool> active_ protected
Definition at line 69 of file basicMultiComponentMixture.H.
Y_
PtrList<volScalarField> Y_ protected
Definition at line 72 of file basicMultiComponentMixture.H.
Referenced by basicMultiComponentMixture::basicMultiComponentMixture().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/basicMultiComponentMixture/basicMultiComponentMixture.H
src/thermophysicalModels/reactionThermo/mixtures/basicMultiComponentMixture/basicMultiComponentMixture.C
src/thermophysicalModels/reactionThermo/mixtures/basicMultiComponentMixture/basicMultiComponentMixtureI.H