OpenFOAM: Newmark Class Reference
Newmark Class Reference
Mesh motion » Six Degree of Freedom (DoF) » Solvers
Newmark 2nd-order time-integrator for 6DoF solid-body motion.
#include <Newmark.H>
Public Member Functions
TypeName ("Newmark")
Newmark (const dictionary &dict, sixDoFRigidBodyMotion &body)
virtual autoPtr< sixDoFSolver > clone () const
virtual ~Newmark ()
virtual void solve (bool firstIter, const vector &fGlobal, const vector &tauGlobal, scalar deltaT, scalar deltaT0)
Public Member Functions inherited from sixDoFSolver
TypeName ("sixDoFSolver")
declareRunTimeSelectionTable (autoPtr, sixDoFSolver, dictionary,(const dictionary &dict, sixDoFRigidBodyMotion &body),(dict, body))
sixDoFSolver (const dictionary &dict, sixDoFRigidBodyMotion &body)
virtual ~sixDoFSolver ()
void write (Ostream &) const
Additional Inherited Members
Static Public Member Functions inherited from sixDoFSolver
static autoPtr< sixDoFSolver > New (const dictionary &dict, sixDoFRigidBodyMotion &body)
Protected Member Functions inherited from sixDoFSolver
point & centreOfRotation ()
tensor & Q ()
vector & v ()
vector & a ()
vector & pi ()
vector & tau ()
const point & centreOfRotation0 () const
const tensor & Q0 () const
const vector & v0 () const
const vector & a0 () const
const vector & pi0 () const
const vector & tau0 () const
scalar aDamp () const
tensor tConstraints () const
tensor rConstraints () const
Tuple2< tensor, vector > rotate (const tensor &Q0, const vector &pi, const scalar deltaT) const
void updateAcceleration (const vector &fGlobal, const vector &tauGlobal)
void updateConstraints ()
Protected Attributes inherited from sixDoFSolver
sixDoFRigidBodyMotion & body_
dictionary dict_
Detailed Description
Newmark 2nd-order time-integrator for 6DoF solid-body motion.
Reference:
    Newmark, N. M. (1959).
    A method of computation for structural dynamics.
    Journal of the Engineering Mechanics Division, 85(3), 67-94.
Example specification in dynamicMeshDict:
solver
{
    type    Newmark;
    gamma   0.5;    // Velocity integration coefficient
    beta    0.25;   // Position integration coefficient
}
Source files
Newmark.H
Newmark.C
Definition at line 68 of file Newmark.H.
Constructor & Destructor Documentation
Newmark()
Newmark (const dictionary & dict, sixDoFRigidBodyMotion & body)
Definition at line 39 of file Newmark.C.
References Foam::max(), and Foam::sqr().
~Newmark()
~Newmark () virtual
Definition at line 60 of file Newmark.C.
Member Function Documentation
TypeName()
TypeName ("Newmark")
clone()
virtual autoPtr< sixDoFSolver > clone () const inline virtual
Implements sixDoFSolver.
Definition at line 97 of file Newmark.H.
References sixDoFSolver::body_, and sixDoFSolver::dict_.
solve()
void solve (bool firstIter, const vector & fGlobal, const vector & tauGlobal, scalar deltaT, scalar deltaT0) virtual
Implements sixDoFSolver.
Definition at line 66 of file Newmark.C.
References UPtrList< T >::first(), and Foam::sqr().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFSolvers/Newmark/Newmark.H
src/sixDoFRigidBodyMotion/sixDoFSolvers/Newmark/Newmark.C