OpenFOAM: Zuber Class Reference
Zuber Class Reference
A critical heat flux (CHF) correlation model based on Zuber (1958) for boiling flows.
#include <Zuber.H>
Public Member Functions
TypeName ("Zuber")
Zuber (const dictionary &dict)
virtual ~Zuber ()=default
virtual tmp< scalarField > CHF (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const
virtual void write (Ostream &os) const
Public Member Functions inherited from CHFModel
TypeName ("CHFModel")
declareRunTimeSelectionTable (autoPtr, CHFModel, dictionary,(const dictionary &dict),(dict))
CHFModel ()=default
virtual ~CHFModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from CHFModel
static autoPtr< CHFModel > New (const dictionary &dict)
Detailed Description
A critical heat flux (CHF) correlation model based on Zuber (1958) for boiling flows.
Reference:
    Zuber, N. (1958).
    On the stability of boiling heat transfer.
    Trans. Am. Soc. Mech. Engrs., 80.
    URL:https://www.osti.gov/biblio/4326542
Usage
Example of the model specification:
CHFModel
{
    // Mandatory entries
    type            Zuber;
    // Optional entries
    Cn              <scalar>;
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name: Zuber word yes -
Cn Model coefficient scalar no 0.131
Source files
Zuber.H
Zuber.C
Definition at line 97 of file Zuber.H.
Constructor & Destructor Documentation
Zuber()
Zuber (const dictionary & dict)
Definition at line 49 of file Zuber.C.
~Zuber()
virtual ~Zuber () virtual default
Member Function Documentation
TypeName()
TypeName ("Zuber")
CHF()
Foam::tmp< Foam::scalarField > CHF (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const virtual
Implements CHFModel.
Definition at line 62 of file Zuber.C.
References cells, g, L, Foam::mag(), Foam::max(), Foam::pow(), liquid::sigma(), Foam::sqr(), and Foam::Zero.
write()
void write (Ostream & os) const virtual
Reimplemented from CHFModel.
Definition at line 99 of file Zuber.C.
References os(), and CHFModel::write().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/CHFModels/Zuber/Zuber.H
src/phaseSystemModels/reactingEuler/multiphaseSystem/derivedFvPatchFields/wallBoilingSubModels/CHFModels/Zuber/Zuber.C