OpenFOAM: NASedgeFormat Class Reference
NASedgeFormat Class Reference
Nastran edge reader.
#include <NASedgeFormat.H>
Public Member Functions
NASedgeFormat (const fileName &filename)
virtual ~NASedgeFormat ()=default
virtual bool read (const fileName &filename)
Public Member Functions inherited from edgeMesh
edgeMesh (const faMesh &mesh)
label size () const
const edgeVectorField & C () const
TypeName ("edgeMesh")
edgeMesh ()
edgeMesh (const edgeMesh &em)
edgeMesh (edgeMesh &&em)
edgeMesh (const pointField &points, const edgeList &edges)
edgeMesh (pointField &&pointLst, edgeList &&edgeLst)
edgeMesh (const fileName &name)
edgeMesh (const fileName &name, const word &fileType)
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()=default
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh, IOstreamOption streamOpt, const dictionary &options),(name, mesh, streamOpt, options))
void transfer (edgeMesh &mesh)
bool read (const fileName &name, const word &fileType)
const pointField & points () const noexcept
const edgeList & edges () const noexcept
const labelListList & pointEdges () const
label regions (labelList &edgeRegion) const
virtual void clear ()
virtual void scalePoints (const scalar scaleFactor)
virtual void mergePoints (const scalar mergeDist)
virtual void mergeEdges ()
virtual void writeStats (Ostream &) const
virtual void write (const fileName &name, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
virtual void write (const fileName &name, const word &fileType, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null) const
void operator= (const edgeMesh &rhs)
void operator= (edgeMesh &&rhs)
Public Member Functions inherited from GeoMesh< faMesh >
GeoMesh (const faMesh &mesh)
bool hasDb () const
const objectRegistry & thisDb () const
const faMesh & operator() () const
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()=default
virtual ~edgeMeshFormatsCore ()=default
Public Member Functions inherited from NASCore
NASCore ()=default
Static Public Member Functions
static autoPtr< edgeMesh > New (const fileName &name)
Static Public Member Functions inherited from edgeMesh
static label size (const Mesh &mesh)
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static bool canReadType (const word &fileType, bool verbose=false)
static bool canWriteType (const word &fileType, bool verbose=false)
static bool canRead (const fileName &name, bool verbose=false)
static autoPtr< edgeMesh > New (const fileName &name, const word &fileType)
static autoPtr< edgeMesh > New (const fileName &name)
static void write (const fileName &name, const edgeMesh &mesh, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
static void write (const fileName &name, const word &fileType, const edgeMesh &mesh, IOstreamOption streamOpt=IOstreamOption(), const dictionary &options=dictionary::null)
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &fileType, const bool verbose=false, const char *functionName=nullptr)
Static Public Member Functions inherited from NASCore
static scalar readNasScalar (const std::string &str)
static std::string nextNasField (const std::string &str, std::string::size_type &pos, std::string::size_type len)
static void setPrecision (Ostream &os, const fieldFormat format)
static Ostream & writeKeyword (Ostream &os, const word &keyword, const fieldFormat format)
static void writeCoord (Ostream &os, const point &p, const label pointId, const fieldFormat format)
static label faceDecomposition (const UList< point > &points, const UList< face > &faces, labelList &decompOffsets, DynamicList< face > &decompFaces)
Additional Inherited Members
Public Types inherited from GeoMesh< faMesh >
typedef faMesh Mesh
typedef MESH::BoundaryMesh BoundaryMesh
Public Types inherited from NASCore
enum fieldFormat { SHORT , LONG , FREE }
enum loadFormat { PLOAD2 , PLOAD4 }
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
Static Public Attributes inherited from NASCore
static const Enum< fieldFormat > fieldFormatNames
static const Enum< loadFormat > loadFormatNames
Protected Member Functions inherited from edgeMesh
pointField & storedPoints () noexcept
edgeList & storedEdges () noexcept
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
Protected Attributes inherited from GeoMesh< faMesh >
const faMesh & mesh_
Detailed Description
Nastran edge reader.
Interprets "CBEAM", "CROD" and "PLOTEL" entries as edges.
Handles Nastran short, long formats and comma-separated free format.
Properly handles the Nastran compact floating point notation:
    GRID          28        10.20269-.030265-2.358-8
Source files
NASedgeFormat.H
NASedgeFormat.C
Definition at line 57 of file NASedgeFormat.H.
Constructor & Destructor Documentation
NASedgeFormat()
NASedgeFormat (const fileName & filename) explicit
Definition at line 29 of file NASedgeFormat.C.
References NASedgeFormat::read().
~NASedgeFormat()
virtual ~NASedgeFormat () virtual default
Member Function Documentation
New()
static autoPtr< edgeMesh > New (const fileName & name) inline static
Definition at line 81 of file NASedgeFormat.H.
References Foam::name().
read()
bool read (const fileName & filename) virtual
Reimplemented from edgeMesh.
Definition at line 37 of file NASedgeFormat.C.
References PtrList< T >::append(), b, clear(), PtrList< T >::clear(), e, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, points, pts, Foam::readLabel(), PtrList< T >::resize(), PtrList< T >::set(), UPtrList< T >::size(), PtrList< T >::transfer(), word::validate(), x, and y.
Referenced by NASedgeFormat::NASedgeFormat().
The documentation for this class was generated from the following files:
src/meshTools/edgeMesh/edgeFormats/nastran/NASedgeFormat.H
src/meshTools/edgeMesh/edgeFormats/nastran/NASedgeFormat.C