OpenFOAM: scalarRange Class Reference
scalarRange Class Reference
Scalar bounds to be used as a unary predicate.
#include <scalarRange.H>
Public Types
typedef scalar value_type
Public Member Functions
constexpr scalarRange () noexcept
constexpr scalarRange (const scalar val) noexcept
scalarRange (const scalar minVal, const scalar maxVal) noexcept
scalarRange (const MinMax< label > &range) noexcept
scalarRange (const MinMax< scalar > &range) noexcept
void clear () noexcept
bool empty () const noexcept
bool good () const noexcept
bool single () const noexcept
scalar min () const noexcept
scalar max () const noexcept
scalar value () const
bool contains (const scalar val) const
bool match (const scalar value) const
bool operator() (const scalar value) const
constexpr bool operator== (const scalarRange &rhs) const noexcept
constexpr bool operator!= (const scalarRange &rhs) const noexcept
bool valid () const noexcept
Static Public Member Functions
static bool parse (const std::string &str, scalarRange &range)
static scalarRange parse (const std::string &str)
static constexpr scalarRange ge (const scalar minVal) noexcept
static constexpr scalarRange gt (const scalar minVal) noexcept
static constexpr scalarRange ge0 () noexcept
static constexpr scalarRange gt0 () noexcept
static constexpr scalarRange le (const scalar maxVal) noexcept
static constexpr scalarRange lt (const scalar maxVal) noexcept
static constexpr scalarRange zero_one () noexcept
Static Public Attributes
static const scalarRange always
Friends
Ostream & operator<< (Ostream &os, const scalarRange &range)
Detailed Description
Scalar bounds to be used as a unary predicate.
The bound can be specified as an "MIN:MAX" range, as a "MIN:" or ":MAX" bound or simply as a single "VALUE".
When defined via the parse() method, the special string "none" can be used to define an empty (inverse) range.
See also
Foam::MinMax Foam::predicates::scalars
Source files
scalarRange.H
scalarRange.C
Definition at line 63 of file scalarRange.H.
Member Typedef Documentation
value_type
typedef scalar value_type
Definition at line 104 of file scalarRange.H.
Constructor & Destructor Documentation
scalarRange() [1/5]
constexpr scalarRange () inline constexpr noexcept
Definition at line 36 of file scalarRangeI.H.
Referenced by scalarRange::parse().
scalarRange() [2/5]
constexpr scalarRange (const scalar val) inline explicit constexpr noexcept
Definition at line 42 of file scalarRangeI.H.
scalarRange() [3/5]
scalarRange (const scalar minVal, const scalar maxVal) inline noexcept
Definition at line 48 of file scalarRangeI.H.
References clear(), and Foam::equal().
scalarRange() [4/5]
scalarRange (const MinMax< label > & range) explicit noexcept
Definition at line 131 of file scalarRange.C.
scalarRange() [5/5]
scalarRange (const MinMax< scalar > & range) explicit noexcept
Definition at line 139 of file scalarRange.C.
Member Function Documentation
parse() [1/2]
bool parse (const std::string & str, scalarRange & range) static
Definition at line 39 of file scalarRange.C.
References scalarRange::always, PtrList< T >::clear(), Switch::find(), scalarRange::ge(), scalarRange::le(), range, scalarRange::scalarRange(), and UPtrList< T >::size().
Referenced by scalarRanges::parse().
parse() [2/2]
Foam::scalarRange parse (const std::string & str) static
Definition at line 116 of file scalarRange.C.
References Foam::endl(), Foam::Info, and range.
ge()
constexpr Foam::scalarRange ge (const scalar minVal) inline static constexpr noexcept
Definition at line 68 of file scalarRangeI.H.
Referenced by scalarRange::parse().
gt()
constexpr Foam::scalarRange gt (const scalar minVal) inline static constexpr noexcept
Definition at line 75 of file scalarRangeI.H.
ge0()
constexpr Foam::scalarRange ge0 () inline static constexpr noexcept
Definition at line 82 of file scalarRangeI.H.
gt0()
constexpr Foam::scalarRange gt0 () inline static constexpr noexcept
Definition at line 89 of file scalarRangeI.H.
le()
constexpr Foam::scalarRange le (const scalar maxVal) inline static constexpr noexcept
Definition at line 96 of file scalarRangeI.H.
Referenced by scalarRange::parse().
lt()
constexpr Foam::scalarRange lt (const scalar maxVal) inline static constexpr noexcept
Definition at line 102 of file scalarRangeI.H.
zero_one()
constexpr Foam::scalarRange zero_one () inline static constexpr noexcept
Definition at line 109 of file scalarRangeI.H.
clear()
void clear () inline noexcept
Definition at line 117 of file scalarRangeI.H.
empty()
bool empty () const inline noexcept
Definition at line 125 of file scalarRangeI.H.
good()
bool good () const inline noexcept
Definition at line 131 of file scalarRangeI.H.
Referenced by scalarRange::valid().
single()
bool single () const inline noexcept
Definition at line 137 of file scalarRangeI.H.
min()
scalar min () const inline noexcept
Definition at line 190 of file scalarRange.H.
max()
scalar max () const inline noexcept
Definition at line 193 of file scalarRange.H.
value()
Foam::scalar value () const inline
Definition at line 143 of file scalarRangeI.H.
Referenced by scalarRange::match(), and scalarRange::operator()().
contains()
bool contains (const scalar val) const inline
Definition at line 166 of file scalarRangeI.H.
References Foam::equal().
Referenced by scalarRange::match(), and scalarRange::operator()().
match()
bool match (const scalar value) const inline
Definition at line 204 of file scalarRange.H.
References scalarRange::contains(), and scalarRange::value().
operator()()
bool operator() (const scalar value) const inline
Definition at line 210 of file scalarRange.H.
References scalarRange::contains(), and scalarRange::value().
operator==()
constexpr bool operator== (const scalarRange & rhs) const inline constexpr noexcept
Definition at line 185 of file scalarRangeI.H.
operator!=()
constexpr bool operator!= (const scalarRange & rhs) const inline constexpr noexcept
Definition at line 192 of file scalarRangeI.H.
valid()
bool valid () const inline noexcept
Definition at line 225 of file scalarRange.H.
References scalarRange::good().
Friends And Related Symbol Documentation
operator<<
Ostream & operator<< (Ostream & os, const scalarRange & range) friend
Member Data Documentation
always
const Foam::scalarRange always static
Definition at line 110 of file scalarRange.H.
Referenced by scalarRange::parse().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/ranges/scalarRange/scalarRange.H
src/OpenFOAM/primitives/ranges/scalarRange/scalarRange.C
src/OpenFOAM/primitives/ranges/scalarRange/scalarRangeI.H