OpenFOAM: opaqueDiffusive Class Reference
opaqueDiffusive Class Reference
Radiation boundary model for opaque diffusive walls. It requires to specify a wallAbsorptionEmissionModel in boundaryRadiationProperties file.
#include <opaqueDiffusive.H>
Public Member Functions
TypeName ("opaqueDiffusive")
opaqueDiffusive (const dictionary &dict, const polyPatch &pp)
virtual ~opaqueDiffusive ()=default
virtual tmp< scalarField > e (const label bandI, vectorField *incomingDirection, scalarField *T) const
virtual scalar e (const label faceI, const label bandI, const vector &dir, const scalar T) const
virtual tmp< scalarField > a (const label bandI, vectorField *incomingDirection, scalarField *T) const
virtual scalar a (const label faceI, const label bandI, const vector &dir, const scalar T) const
virtual tmp< scalarField > t (const label bandI, vectorField *incomingDirection, scalarField *T) const
virtual scalar t (const label faceI, const label bandI, const vector &dir, const scalar T) const
virtual tmp< scalarField > rSpec (const label bandI, vectorField *incomingDirection, scalarField *T) const
virtual scalar rSpec (const label faceI, const label bandI, const vector &dir, const scalar T) const
virtual tmp< scalarField > rDiff (const label bandI, vectorField *incomingDirection, scalarField *T) const
virtual scalar rDiff (const label faceI, const label bandI, const vector &dir, const scalar T) const
virtual bool isGrey () const
virtual label nBands () const
Public Member Functions inherited from boundaryRadiationPropertiesPatch
TypeName ("boundaryRadiationPropertiesPatch")
declareRunTimeSelectionTable (autoPtr, boundaryRadiationPropertiesPatch, dictionary,(const dictionary &dict, const polyPatch &pp),(dict, pp))
boundaryRadiationPropertiesPatch (const dictionary &, const polyPatch &)
virtual ~boundaryRadiationPropertiesPatch ()=default
const wallAbsorptionEmissionModel & absorptionEmission () const
const wallTransmissivityModel & transmissiveModel () const
virtual void write (Ostream &) const
Protected Attributes
const polyPatch & pp_
Protected Attributes inherited from boundaryRadiationPropertiesPatch
autoPtr< wallAbsorptionEmissionModel > absorptionEmission_
autoPtr< wallTransmissivityModel > transmissivity_
Additional Inherited Members
Static Public Member Functions inherited from boundaryRadiationPropertiesPatch
static autoPtr< boundaryRadiationPropertiesPatch > New (const dictionary &dict, const polyPatch &pp)
Detailed Description
Radiation boundary model for opaque diffusive walls. It requires to specify a wallAbsorptionEmissionModel in boundaryRadiationProperties file.
Usage
    type       opaqueDiffusive;
    wallAbsorptionEmissionModel
    {
        type            multiBandAbsorption;
        absorptivity    (0.3 0.7);
        emissivity      (0.3 0.7);
    };
Definition at line 58 of file opaqueDiffusive.H.
Constructor & Destructor Documentation
opaqueDiffusive()
opaqueDiffusive (const dictionary & dict, const polyPatch & pp)
Definition at line 43 of file opaqueDiffusive.C.
References boundaryRadiationPropertiesPatch::absorptionEmission_, dict, wallAbsorptionEmissionModel::New(), and pp().
~opaqueDiffusive()
virtual ~opaqueDiffusive () virtual default
Member Function Documentation
TypeName()
TypeName ("opaqueDiffusive")
e() [1/2]
Foam::tmp< Foam::scalarField > e (const label bandI, vectorField * incomingDirection, scalarField * T) const virtual
Implements boundaryRadiationPropertiesPatch.
Definition at line 64 of file opaqueDiffusive.C.
References T.
e() [2/2]
Foam::scalar e (const label faceI, const label bandI, const vector & dir, const scalar T) const virtual
Implements boundaryRadiationPropertiesPatch.
Definition at line 75 of file opaqueDiffusive.C.
References T.
a() [1/2]
Foam::tmp< Foam::scalarField > a (const label bandI, vectorField * incomingDirection, scalarField * T) const virtual
Implements boundaryRadiationPropertiesPatch.
Definition at line 88 of file opaqueDiffusive.C.
References T.
a() [2/2]
Foam::scalar a (const label faceI, const label bandI, const vector & dir, const scalar T) const virtual
Implements boundaryRadiationPropertiesPatch.
Definition at line 99 of file opaqueDiffusive.C.
References T.
t() [1/2]
Foam::tmp< Foam::scalarField > t (const label bandI, vectorField * incomingDirection, scalarField * T) const virtual
Implements boundaryRadiationPropertiesPatch.
Definition at line 111 of file opaqueDiffusive.C.
References tmp< T >::New().
t() [2/2]
Foam::scalar t (const label faceI, const label bandI, const vector & dir, const scalar T) const virtual
Implements boundaryRadiationPropertiesPatch.
Definition at line 122 of file opaqueDiffusive.C.
rSpec() [1/2]
Foam::tmp< Foam::scalarField > rSpec (const label bandI, vectorField * incomingDirection, scalarField * T) const virtual
Implements boundaryRadiationPropertiesPatch.
Definition at line 135 of file opaqueDiffusive.C.
References tmp< T >::New(), and Foam::Zero.
rSpec() [2/2]
Foam::scalar rSpec (const label faceI, const label bandI, const vector & dir, const scalar T) const virtual
Implements boundaryRadiationPropertiesPatch.
Definition at line 146 of file opaqueDiffusive.C.
References Foam::Zero.
rDiff() [1/2]
Foam::tmp< Foam::scalarField > rDiff (const label bandI, vectorField * incomingDirection, scalarField * T) const virtual
Implements boundaryRadiationPropertiesPatch.
Definition at line 158 of file opaqueDiffusive.C.
References tmp< T >::New(), and Foam::Zero.
rDiff() [2/2]
Foam::scalar rDiff (const label faceI, const label bandI, const vector & dir, const scalar T) const virtual
Implements boundaryRadiationPropertiesPatch.
Definition at line 169 of file opaqueDiffusive.C.
References Foam::Zero.
isGrey()
bool isGrey () const virtual
Implements boundaryRadiationPropertiesPatch.
Definition at line 181 of file opaqueDiffusive.C.
nBands()
Foam::label nBands () const virtual
Implements boundaryRadiationPropertiesPatch.
Definition at line 187 of file opaqueDiffusive.C.
Member Data Documentation
pp_
const polyPatch& pp_ protected
Definition at line 68 of file opaqueDiffusive.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/boundaryRadiationProperties/opaqueDiffusive/opaqueDiffusive.H
src/thermophysicalModels/radiation/submodels/boundaryRadiationProperties/opaqueDiffusive/opaqueDiffusive.C