OpenFOAM: applications/utilities/surface/surfaceClean/collapseEdge.H File Reference
collapseEdge.H File Reference
Routines to collapse small edges.
Functions
label collapseEdge (triSurface &surf, const scalar minLen)
Detailed Description
Routines to collapse small edges.
Original source file collapseEdge.H
InClass Foam::collapseEdge
Source files
collapseEdge.H
collapseEdge.C
Definition in file collapseEdge.H.
Function Documentation
collapseEdge()
label collapseEdge (triSurface & surf, const scalar minLen)
Referenced by edgeCollapser::consistentCollapse(), edgeCollapser::markFaceZoneEdges(), edgeCollapser::markMergeEdges(), edgeCollapser::markSmallEdges(), and edgeCollapser::markSmallSliverFaces().