OpenFOAM: applications/utilities/postProcessing/miscellaneous/postChannel/collapse.H File Reference
collapse.H File Reference
Functions
fileName path (UMean.rootPath()/UMean.caseName()/"graphs"/UMean.instance())
mkDir (path)
scalarField UMeanXvalues (channelIndexing.collapse(UMean.component(vector::X)()))
scalarField UMeanYvalues (channelIndexing.collapse(UMean.component(vector::Y)()))
scalarField UMeanZvalues (channelIndexing.collapse(UMean.component(vector::Z)()))
scalarField RxxValues (channelIndexing.collapse(Rxx))
scalarField RyyValues (channelIndexing.collapse(Ryy))
scalarField RzzValues (channelIndexing.collapse(Rzz))
scalarField RxyValues (channelIndexing.collapse(Rxy, true))
scalarField pPrime2MeanValues (channelIndexing.collapse(pPrime2Mean))
scalarField urmsValues (sqrt(mag(RxxValues)))
scalarField vrmsValues (sqrt(mag(RyyValues)))
scalarField wrmsValues (sqrt(mag(RzzValues)))
scalarField kValues (0.5 *(sqr(urmsValues)+sqr(vrmsValues)+sqr(wrmsValues)))
makeGraph (y, UMeanXvalues, "Uf", path, gFormat)
makeGraph (y, urmsValues, "u", path, gFormat)
makeGraph (y, vrmsValues, "v", path, gFormat)
makeGraph (y, wrmsValues, "w", path, gFormat)
makeGraph (y, RxyValues, "uv", path, gFormat)
makeGraph (y, kValues, "k", path, gFormat)
makeGraph (y, pPrime2MeanValues, "pPrime2Mean", path, gFormat)
Variables
const scalarField & y = channelIndexing.y()
Function Documentation
path()
fileName path (UMean. rootPath)/UMean.caseName()/"graphs"/UMean.instance()
Referenced by processorPolyPatch::calcGeometry(), Time::caseName(), dictionary::cfindScopedDict(), argList::checkRootCase(), TimePaths::constantPath(), cyclicPolyPatch::coupledEdges(), cyclicPolyPatch::coupledPoints(), Foam::cwd_P(), fileOperation::detectProcessorPath(), distributedTriSurfaceMesh::distribute(), DSMCCloud< ParcelType >::dumpParticlePositions(), fileOperation::filePath(), uncollatedFileOperation::filePathInfo(), TimePaths::findClosestTime(), Time::findInstancePath(), Time::findInstancePath(), processorPolyPatch::initOrder(), TDACChemistryModel< ReactionThermo, ThermoType >::logFile(), fileOperation::lookupAndCacheProcessorsPath(), Foam::makeGraph(), Foam::makeGraph(), dictionary::makeScopedDict(), writeFile::newFile(), ensightCase::newGeometry(), IOobject::objectPath(), cyclicPolyPatch::order(), oldCyclicPolyPatch::order(), processorPolyPatch::order(), functionObjectList::readFunctionObject(), fileOperation::readObjects(), masterUncollatedFileOperation::readStream(), uncollatedFileOperation::readStream(), Foam::rmDir(), seriesWriter::scan(), Foam::search(), Time::setControls(), fileOperation::splitProcessorPath(), mappedPatchBase::subRegistry(), masterUncollatedFileOperation::sync(), TimePaths::times(), wallBoundedParticle::trackToEdge(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), graph::write(), csvWriter::writeBuffered(), gnuplotWriter::writeBuffered(), rawWriter::writeBuffered(), Foam::writeCellGraph(), collatedFileOperation::writeObject(), Cloud< ParticleType >::writePositions(), csvWriter::writeTemplate(), gnuplotWriter::writeTemplate(), nastranWriter::writeTemplate(), rawWriter::writeTemplate(), xmgraceWriter::writeTemplate(), nastranWriter::writeTemplate(), gltfWriter::writeTemplate(), gltfWriter::writeTemplate_animate(), and regIOobject::~regIOobject().
mkDir()
mkDir (path)
UMeanXvalues()
scalarField UMeanXvalues (channelIndexing. collapseUMean.component(vector::X)())
UMeanYvalues()
scalarField UMeanYvalues (channelIndexing. collapseUMean.component(vector::Y)())
UMeanZvalues()
scalarField UMeanZvalues (channelIndexing. collapseUMean.component(vector::Z)())
RxxValues()
scalarField RxxValues (channelIndexing. collapseRxx)
RyyValues()
scalarField RyyValues (channelIndexing. collapseRyy)
RzzValues()
scalarField RzzValues (channelIndexing. collapseRzz)
RxyValues()
scalarField RxyValues (channelIndexing. collapseRxy, true)
pPrime2MeanValues()
scalarField pPrime2MeanValues (channelIndexing. collapsepPrime2Mean)
urmsValues()
scalarField urmsValues (sqrt(mag(RxxValues)))
vrmsValues()
scalarField vrmsValues (sqrt(mag(RyyValues)))
wrmsValues()
scalarField wrmsValues (sqrt(mag(RzzValues)))
kValues()
scalarField kValues (0.5 * sqr(urmsValues)+sqr(vrmsValues)+sqr(wrmsValues))
makeGraph() [1/7]
makeGraph (y , UMeanXvalues , "Uf" , path , gFormat)
Referenced by Foam::makeGraph(), and Foam::makeGraph().
makeGraph() [2/7]
makeGraph (y , urmsValues , "u" , path , gFormat)
makeGraph() [3/7]
makeGraph (y , vrmsValues , "v" , path , gFormat)
makeGraph() [4/7]
makeGraph (y , wrmsValues , "w" , path , gFormat)
makeGraph() [5/7]
makeGraph (y , RxyValues , "uv" , path , gFormat)
makeGraph() [6/7]
makeGraph (y , kValues , "k" , path , gFormat)
makeGraph() [7/7]
makeGraph (y , pPrime2MeanValues , "pPrime2Mean" , path , gFormat)
Variable Documentation
y
const scalarField& y = channelIndexing.y()
Definition at line 46 of file collapse.H.