OpenFOAM: applications/solvers/combustion/chemFoam/createFieldRefs.H File Reference
createFieldRefs.H File Reference
Variables
BasicChemistryModel< psiReactionThermo > & chemistry = pChemistry()
scalar dtChem
basicSpecieMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
volScalarField & p = thermo.p()
Variable Documentation
chemistry
BasicChemistryModel<psiReactionThermo>& chemistry = pChemistry()
Definition at line 1 of file createFieldRefs.H.
Referenced by DAC< CompType, ThermoType >::DAC(), DRG< CompType, ThermoType >::DRG(), DRGEP< CompType, ThermoType >::DRGEP(), reactionsSensitivityAnalysis< chemistryType >::execute(), ISAT< CompType, ThermoType >::ISAT(), PFA< CompType, ThermoType >::PFA(), and reactionsSensitivityAnalysis< chemistryType >::reactionsSensitivityAnalysis().
dtChem
scalar dtChem
Initial value:
= refCast<const BasicChemistryModel<psiReactionThermo>>
(
    chemistry
).deltaTChem()[0]
Definition at line 2 of file createFieldRefs.H.
Referenced by if().
composition
basicSpecieMixture& composition = thermo.composition()
Definition at line 6 of file createFieldRefs.H.
Referenced by ReactingHeterogeneousParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), ReactingParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), ReactingParcel< ParcelType >::calcPhaseChange(), MUCSheterogeneousRate< CloudType >::calculate(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::calculateMassFractions(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::calculateVolumeFractions(), ReactingCloud< CloudType >::checkParcelProperties(), ReactingHeterogeneousCloud< CloudType >::checkParcelProperties(), SprayParcel< ParcelType >::chi(), diffusion< ReactionThermo, ThermoType >::correct(), infinitelyFastChemistry< ReactionThermo, ThermoType >::correct(), forAll(), forAll(), if(), if(), enthalpySorptionFvPatchScalarField::patchSource(), ReactingHeterogeneousCloud< CloudType >::ReactingHeterogeneousCloud(), ReactingHeterogeneousCloud< Foam::DSMCCloud >::ReactingHeterogeneousCloud(), ReactingMultiphaseCloud< Foam::DSMCCloud >::ReactingMultiphaseCloud(), ReactingMultiphaseCloud< CloudType >::ReactingMultiphaseCloud(), ReactingHeterogeneousCloud< CloudType >::readObjects(), ReactingHeterogeneousCloud< Foam::DSMCCloud >::setModels(), ReactingCloud< CloudType >::setParcelThermoProperties(), ReactingMultiphaseCloud< CloudType >::setParcelThermoProperties(), SprayCloud< CloudType >::setParcelThermoProperties(), TDACChemistryModel< ReactionThermo, ThermoType >::solve(), SprayCloud< CloudType >::SprayCloud(), TDACChemistryModel< ReactionThermo, ThermoType >::TDACChemistryModel(), semiPermeableBaffleVelocityFvPatchVectorField::updateCoeffs(), ReactingHeterogeneousParcel< ParcelType >::updatedDeltaVolume(), ReactingParcel< ParcelType >::updatedDeltaVolume(), ReactingCloud< CloudType >::writeFields(), ReactingMultiphaseCloud< Foam::DSMCCloud >::writeFields(), ReactingCloud< CloudType >::writeObjects(), and ReactingHeterogeneousCloud< CloudType >::writeObjects().
Y
PtrList<volScalarField>& Y = composition.Y()
Definition at line 7 of file createFieldRefs.H.
Referenced by ReactingParcel< ParcelType >::calcPhaseChange(), LiquidEvaporationBoil< CloudType >::calculate(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::calculateMassFractions(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::calculateVolumeFractions(), LiquidEvapFuchsKnudsen< CloudType >::calcXc(), LiquidEvaporation< CloudType >::calcXc(), LiquidEvaporationBoil< CloudType >::calcXc(), ReactingParcel< ParcelType >::cellValueSourceCorrection(), ReactingCloud< CloudType >::checkSuppliedComposition(), CompositionModel< CloudType >::Cp(), solidMixtureProperties::Cp(), solarCalculator::diffuseSolarRad(), thermo< Thermo, Type >::dKcdTbyKc(), forAll(), forAll(), forAll(), singleStepReactingMixture< ThermoType >::fresCorrect(), CompositionModel< CloudType >::H(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Hc(), CompositionModel< CloudType >::Hc(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Hs(), CompositionModel< CloudType >::Hs(), if(), if(), thermo< Thermo, Type >::K(), thermo< Thermo, Type >::Kc(), thermo< Thermo, Type >::Kn(), thermo< Thermo, Type >::Kx(), CompositionModel< CloudType >::L(), moleFractions< ThermoType >::moleFractions(), adiabaticPerfectFluid< Specie >::operator+=(), Boussinesq< Specie >::operator+=(), constAnIsoSolidTransport< Thermo >::operator+=(), constIsoSolidTransport< Thermo >::operator+=(), constTransport< Thermo >::operator+=(), eConstThermo< EquationOfState >::operator+=(), exponentialSolidTransport< Thermo >::operator+=(), hConstThermo< EquationOfState >::operator+=(), hPolynomialThermo< EquationOfState, PolySize >::operator+=(), hPowerThermo< EquationOfState >::operator+=(), icoPolynomial< Specie, PolySize >::operator+=(), incompressiblePerfectGas< Specie >::operator+=(), janafThermo< EquationOfState >::operator+=(), linear< Type >::operator+=(), logPolynomialTransport< Thermo, PolySize >::operator+=(), PengRobinsonGas< Specie >::operator+=(), perfectFluid< Specie >::operator+=(), polynomialSolidTransport< Thermo, PolySize >::operator+=(), polynomialTransport< Thermo, PolySize >::operator+=(), rhoConst< Specie >::operator+=(), rPolynomial< Specie >::operator+=(), sutherlandTransport< Thermo >::operator+=(), WLFTransport< Thermo >::operator+=(), diffusionMulticomponent< ReactionThermo, ThermoType >::R(), EDC< ReactionThermo >::R(), laminar< ReactionThermo >::R(), noCombustion< ReactionThermo >::R(), PaSR< ReactionThermo >::R(), singleStepCombustion< ReactionThermo, ThermoType >::R(), zoneCombustion< ReactionThermo >::R(), BilgerMixtureFraction::read(), ReactingHeterogeneousParcel< ParcelType >::readFields(), ReactingParcel< ParcelType >::readFields(), ReactingParcel< ParcelType >::readObjects(), solidMixtureProperties::rho(), RowVector< Cmpt >::RowVector(), SprayCloud< CloudType >::setParcelThermoProperties(), TDACChemistryModel< ReactionThermo, ThermoType >::solve(), semiPermeableBaffleVelocityFvPatchVectorField::updateCoeffs(), ReactingParcel< ParcelType >::updateMassFraction(), Vector< Cmpt >::Vector(), Vector2D< Cmpt >::Vector2D(), ReactingHeterogeneousParcel< ParcelType >::writeFields(), ReactingParcel< ParcelType >::writeFields(), ReactingHeterogeneousParcel< ParcelType >::writeObjects(), ReactingParcel< ParcelType >::writeObjects(), liquidMixtureProperties::X(), and liquidMixtureProperties::Y().
p
volScalarField& p = thermo.p()
Definition at line 8 of file createFieldRefs.H.
Referenced by SpecieMixture< MixtureType >::A(), thermo< Thermo, Type >::A(), KinematicSurfaceFilm< CloudType >::absorbInteraction(), sensitivitySurface::accumulateIntegrand(), sensitivitySurfacePoints::accumulateIntegrand(), extractEulerianParticles::accumulateParticleInfo(), greyMeanAbsorptionEmission::aCont(), wideBandAbsorptionEmission::aCont(), activePressureForceBaffleVelocityFvPatchVectorField::activePressureForceBaffleVelocityFvPatchVectorField(), boundBox::add(), preserveBaffles::add(), boundBox::add(), faMesh::addFaPatches(), fvMesh::addFvPatches(), sensitivitySurface::addGeometricSens(), snappyLayerDriver::addLayers(), polyMesh::addPatches(), Foam::adjustPhi(), oversetFvPatchField< Type >::adjustPsi(), masterCoarsestGAMGProcAgglomeration::agglomerate(), SpecieMixture< MixtureType >::alphah(), exponentialSolidTransport< Thermo >::alphah(), polynomialSolidTransport< Thermo, PolySize >::alphah(), tabulatedAnIsoSolidTransport< Thermo >::alphah(), tabulatedSolidTransport< Thermo >::alphah(), constTransport< Thermo >::alphah(), logPolynomialTransport< Thermo, PolySize >::alphah(), polynomialTransport< Thermo, PolySize >::alphah(), sutherlandTransport< Thermo >::alphah(), tabulatedTransport< Thermo >::alphah(), WLFTransport< Thermo >::alphah(), liquidProperties::alphah(), thermophysicalPropertiesSelector< ThermophysicalProperties >::alphah(), alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField(), angularOscillatingDisplacementPointPatchVectorField::angularOscillatingDisplacementPointPatchVectorField(), angularOscillatingVelocityPointPatchVectorField::angularOscillatingVelocityPointPatchVectorField(), PDRblock::gridControl::append(), blockEdge::appendEndPoints(), Foam::applyOctant(), Foam::applyPermutation(), DiagonalMatrix< cmptType >::applyPermutation(), SquareMatrix< Type >::applyPermutation(), Foam::applyPermutation(), arcEdge::arcEdge(), face::areaNormal(), attachPolyTopoChanger::attach(), Cloud< ParticleType >::autoMap(), Cloud< ParcelType >::autoMap(), FreeStream< CloudType >::autoMap(), aC10H7CH3::B(), Ar::B(), bC10H7CH3::B(), C10H22::B(), C12H26::B(), C13H28::B(), C14H30::B(), C16H34::B(), C2H5OH::B(), C2H6::B(), C2H6O::B(), C3H6O::B(), C3H8::B(), C4H10O::B(), C6H14::B(), C6H6::B(), C7H16::B(), C7H8::B(), C8H10::B(), C8H18::B(), C9H20::B(), CH3OH::B(), CH4N2O::B(), H2O::B(), iC3H8O::B(), IC8H18::B(), IDEA::B(), MB::B(), N2::B(), nC3H8O::B(), restraint::bodyPoint(), restraint::bodyPointVelocity(), KinematicSurfaceFilm< CloudType >::bounceInteraction(), primitiveMeshTools::boundaryFaceSkewness(), primitiveMeshTools::boundaryFaceSkewness(), cell::box(), KinematicCloud< CloudType >::buildCellOccupancy(), Foam::calc_pTotal(), PatchTools::calcBounds(), SprayParcel< ParcelType >::calcBreakup(), DistortedSphereDragForce< CloudType >::calcCoupled(), ErgunWenYuDragForce< CloudType >::calcCoupled(), NonSphereDragForce< CloudType >::calcCoupled(), PlessisMasliyahDragForce< CloudType >::calcCoupled(), SphereDragForce< CloudType >::calcCoupled(), WenYuDragForce< CloudType >::calcCoupled(), LiftForce< CloudType >::calcCoupled(), PressureGradientForce< CloudType >::calcCoupled(), VirtualMassForce< CloudType >::calcCoupled(), BrownianMotionForce< CloudType >::calcCoupled(), CentredFitSnGradData< Polynomial >::calcFit(), forces::calcForcesMoments(), cutCell::calcGeomDataCutFace(), fourthGrad< Type >::calcGrad(), triSurfaceTools::calcInterpolationWeights(), cutCell::calcIsoFacePointsFromEdges(), momentumError::calcMomentError(), ParticleForceList< CloudType >::calcNonCoupled(), CoulombForce< CloudType >::calcNonCoupled(), GravityForce< CloudType >::calcNonCoupled(), InterfaceForce< CloudType >::calcNonCoupled(), NonInertialFrameForce< CloudType >::calcNonCoupled(), ParamagneticForce< CloudType >::calcNonCoupled(), SRFForce< CloudType >::calcNonCoupled(), cutFace::calcSubFace(), cutFace::calcSubFace(), cutFace::calcSubFace(), KinematicParcel< ParcelType >::calcUCorrection(), Stochastic< CloudType >::calculate(), surfaceNoise::calculate(), StandardChemistryModel< ReactionThermo, ThermoType >::calculate(), hydrostaticPressure::calculateAndWrite(), calculatedProcessorGAMGInterfaceField::calculatedProcessorGAMGInterfaceField(), StandardChemistryModel< ReactionThermo, ThermoType >::calculateRR(), KinematicParcel< ParcelType >::calcVelocity(), multiComponentMixture< ThermoType >::cellVolMixture(), polyMeshGeometry::checkFaceAngles(), primitiveMeshGeometry::checkFaceAngles(), polyMeshGeometry::checkFaceAngles(), primitiveMeshGeometry::checkFaceAngles(), polyMeshGeometry::checkFaceFlatness(), polyMeshGeometry::checkFaceFlatness(), polyMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceTets(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), primitiveMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceTwist(), primitiveMeshGeometry::checkFaceTwist(), PatchTools::checkOrientation(), polyMeshGeometry::checkTriangleTwist(), polyMeshGeometry::checkTriangleTwist(), chemPointISAT< CompType, ThermoType >::chemPointISAT(), triangle< Point, PointRef >::classify(), polyBoundaryMesh::clearAddressing(), polyBoundaryMesh::clearGeom(), averageNeighbourFvGeometryScheme::clipFaceTet(), extractEulerianParticles::collectParticle(), SuppressionCollision< CloudType >::collide(), ORourkeCollision< CloudType >::collide(), incompressibleAdjointSolver::computeGradDxDbMultiplier(), molecule::constantProperties::constantProperties(), Foam::constrainHbyA(), Foam::constrainPressure(), Foam::constrainPressure(), Foam::constrainPressure(), Foam::constrainPressure(), reconstructedDistanceFunction::constructRDF(), face::contactSphereDiameter(), PDRblock::location::contains(), boundBox::contains(), boundBox::containsAny(), IntegralScaleBox< Type >::convolve(), ensightMesh::correct(), isothermal::correct(), contactAngleForce::correct(), polyMeshGeometry::correct(), primitiveMeshGeometry::correct(), ArrheniusViscosity::correct(), function1Viscosity::correct(), waxSolventViscosity::correct(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), SpecularReflection< CloudType >::correct(), LocalInteraction< CloudType >::correct(), MultiInteraction< CloudType >::correct(), Rebound< CloudType >::correct(), RecycleInteraction< CloudType >::correct(), StandardWallInteraction< CloudType >::correct(), incompressiblePrimalSolver::correctBoundaryConditions(), twoDPointCorrector::correctDisplacement(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), Foam::CorrectPhi(), Foam::CorrectPhi(), twoDPointCorrector::correctPoints(), IsothermalPhaseModel< BasePhaseModel >::correctThermo(), PointEdgeWave< Type, TrackingData >::countPatchType(), liquidFilmThermo::Cp(), CompositionModel< CloudType >::Cp(), SpecieMixture< MixtureType >::Cp(), liquidFilmThermo::Cp(), hConstThermo< EquationOfState >::Cp(), hPolynomialThermo< EquationOfState, PolySize >::Cp(), hPowerThermo< EquationOfState >::Cp(), hTabulatedThermo< EquationOfState >::Cp(), janafThermo< EquationOfState >::Cp(), Cp(), thermophysicalPropertiesSelector< ThermophysicalProperties >::Cp(), liquidMixtureProperties::Cp(), multiphaseInterSystem::Cp(), phaseModel::Cp(), heThermo< BasicThermo, MixtureType >::Cp(), heThermo< BasicThermo, MixtureType >::Cp(), PengRobinsonGas< Specie >::Cp(), aC10H7CH3::Cp(), Ar::Cp(), bC10H7CH3::Cp(), C10H22::Cp(), C12H26::Cp(), C13H28::Cp(), C14H30::Cp(), C16H34::Cp(), C2H5OH::Cp(), C2H6::Cp(), C2H6O::Cp(), C3H6O::Cp(), C3H8::Cp(), C4H10O::Cp(), C6H14::Cp(), C6H6::Cp(), C7H16::Cp(), C7H8::Cp(), C8H10::Cp(), C8H18::Cp(), C9H20::Cp(), CH3OH::Cp(), CH4N2O::Cp(), H2O::Cp(), iC3H8O::Cp(), IC8H18::Cp(), IDEA::Cp(), MB::Cp(), N2::Cp(), nC3H8O::Cp(), thermo< Thermo, Type >::CpByCpv(), multiphaseInterSystem::CpByCpv(), phaseModel::CpByCpv(), heThermo< BasicThermo, MixtureType >::CpByCpv(), absoluteInternalEnergy< Thermo >::CpByCpv(), sensibleInternalEnergy< Thermo >::CpByCpv(), ReactingMultiphaseParcel< ParcelType >::CpEff(), ReactingHeterogeneousParcel< ParcelType >::CpEff(), aC10H7CH3::Cpg(), Ar::Cpg(), bC10H7CH3::Cpg(), C10H22::Cpg(), C12H26::Cpg(), C13H28::Cpg(), C14H30::Cpg(), C16H34::Cpg(), C2H5OH::Cpg(), C2H6::Cpg(), C2H6O::Cpg(), C3H6O::Cpg(), C3H8::Cpg(), C4H10O::Cpg(), C6H14::Cpg(), C6H6::Cpg(), C7H16::Cpg(), C7H8::Cpg(), C8H10::Cpg(), C8H18::Cpg(), C9H20::Cpg(), CH3OH::Cpg(), CH4N2O::Cpg(), H2O::Cpg(), iC3H8O::Cpg(), IC8H18::Cpg(), IDEA::Cpg(), MB::Cpg(), N2::Cpg(), nC3H8O::Cpg(), PengRobinsonGas< Specie >::CpMCv(), perfectFluid< Specie >::CpMCv(), thermophysicalPropertiesSelector< ThermophysicalProperties >::CpMCv(), thermo< Thermo, Type >::Cpv(), multiphaseInterSystem::Cpv(), phaseModel::Cpv(), heThermo< BasicPsiThermo, MixtureType >::Cpv(), heThermo< BasicThermo, MixtureType >::Cpv(), absoluteEnthalpy< Thermo >::Cpv(), absoluteInternalEnergy< Thermo >::Cpv(), sensibleEnthalpy< Thermo >::Cpv(), sensibleInternalEnergy< Thermo >::Cpv(), refPtr< T >::cref(), tmp< T >::cref(), SpecieMixture< MixtureType >::Cv(), eConstThermo< EquationOfState >::Cv(), Cv(), thermophysicalPropertiesSelector< ThermophysicalProperties >::Cv(), multiphaseInterSystem::Cv(), phaseModel::Cv(), heThermo< BasicThermo, MixtureType >::Cv(), PengRobinsonGas< Specie >::Cv(), cyclicACMIFvPatchField< Type >::cyclicACMIFvPatchField(), cyclicACMIFvPatchField< Type >::cyclicACMIFvPatchField(), cyclicACMIFvsPatchField< Type >::cyclicACMIFvsPatchField(), cyclicACMIGAMGInterfaceField::cyclicACMIGAMGInterfaceField(), cyclicACMIPointPatchField< Type >::cyclicACMIPointPatchField(), cyclicAMIFvPatchField< Type >::cyclicAMIFvPatchField(), cyclicAMIFvPatchField< Type >::cyclicAMIFvPatchField(), cyclicAMIFvsPatchField< Type >::cyclicAMIFvsPatchField(), cyclicAMIGAMGInterfaceField::cyclicAMIGAMGInterfaceField(), cyclicAMIPointPatchField< Type >::cyclicAMIPointPatchField(), cyclicFaePatchField< Type >::cyclicFaePatchField(), cyclicFaPatchField< Type >::cyclicFaPatchField(), cyclicFaPatchField< Type >::cyclicFaPatchField(), cyclicFvPatchField< Type >::cyclicFvPatchField(), cyclicFvPatchField< Type >::cyclicFvPatchField(), cyclicFvsPatchField< Type >::cyclicFvsPatchField(), cyclicGAMGInterfaceField::cyclicGAMGInterfaceField(), cyclicPointPatchField< Type >::cyclicPointPatchField(), isothermal::d(), liquidFilmThermo::D(), liquidMixtureProperties::D(), InterfaceCompositionModel< Thermo, OtherThermo >::D(), aC10H7CH3::D(), Ar::D(), bC10H7CH3::D(), C10H22::D(), C12H26::D(), C13H28::D(), C14H30::D(), C16H34::D(), C2H5OH::D(), C2H6::D(), C2H6O::D(), C3H6O::D(), C3H8::D(), C4H10O::D(), C6H14::D(), C6H6::D(), C7H16::D(), C7H8::D(), C8H10::D(), C8H18::D(), C9H20::D(), CH3OH::D(), CH4N2O::D(), H2O::D(), iC3H8O::D(), IC8H18::D(), IDEA::D(), MB::D(), N2::D(), nC3H8O::D(), aC10H7CH3::D(), Ar::D(), bC10H7CH3::D(), C10H22::D(), C12H26::D(), C13H28::D(), C14H30::D(), C16H34::D(), C2H5OH::D(), C2H6::D(), C2H6O::D(), C3H6O::D(), C3H8::D(), C4H10O::D(), C6H14::D(), C6H6::D(), C7H16::D(), C7H8::D(), C8H10::D(), C8H18::D(), C9H20::D(), CH3OH::D(), CH4N2O::D(), H2O::D(), iC3H8O::D(), IC8H18::D(), IDEA::D(), MB::D(), N2::D(), nC3H8O::D(), d2vec_permute(), hTabulatedThermo< EquationOfState >::dCpdT(), thermo< Thermo, Type >::dcpdT(), faFieldDecomposer::decomposeField(), fvFieldDecomposer::decomposeField(), Cloud< ParticleType >::deleteLostParticles(), Cloud< ParticleType >::deleteParticle(), basicFvGeometryScheme::deltaCoeffs(), StandardChemistryModel< ReactionThermo, ThermoType >::derivatives(), TDACChemistryModel< ReactionThermo, ThermoType >::derivatives(), TDACChemistryModel< CompType, ThermoType >::derivatives(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::derivatives(), InterfaceCompositionModel< Thermo, OtherThermo >::Dfrom(), LiquidEvapFuchsKnudsen< CloudType >::dh(), LiquidEvaporation< CloudType >::dh(), LiquidEvaporationBoil< CloudType >::dh(), directionMixedFvPatchField< Type >::directionMixedFvPatchField(), plane::distance(), cylinderImplicitFunction::distanceToSurfaces(), planeImplicitFunction::distanceToSurfaces(), sphereImplicitFunction::distanceToSurfaces(), KinematicCloud< Foam::DSMCCloud >::Dmax(), Foam::domainName(), snappySnapDriver::doSnap(), KinematicSurfaceFilm< CloudType >::drySplashInteraction(), InterfaceCompositionModel< Thermo, OtherThermo >::Dto(), DSMCCloud< ParcelType >::dumpParticlePositions(), Foam::dynamicCast(), Foam::dynamicCast(), PengRobinsonGas< Specie >::E(), eConstThermo< EquationOfState >::Ea(), Ea(), thermophysicalPropertiesSelector< ThermophysicalProperties >::Ea(), PatchTools::edgeNormals(), PatchTools::edgeOwner(), emptyFaePatchField< Type >::emptyFaePatchField(), emptyFaPatchField< Type >::emptyFaPatchField(), emptyFaPatchField< Type >::emptyFaPatchField(), emptyFvPatchField< Type >::emptyFvPatchField(), emptyFvPatchField< Type >::emptyFvPatchField(), emptyFvsPatchField< Type >::emptyFvsPatchField(), emptyPointPatchField< Type >::emptyPointPatchField(), pitchForkRing::energy(), SpecieMixture< MixtureType >::Es(), eConstThermo< EquationOfState >::Es(), Es(), thermophysicalPropertiesSelector< ThermophysicalProperties >::Es(), WallLocalSpringSliderDashpot< CloudType >::evaluateWall(), WallSpringSliderDashpot< CloudType >::evaluateWall(), Curle::execute(), STLAsciiParseManual::execute(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), APIdiffCoefFunc::f(), APIdiffCoefFunc::f(), Patch::faceCentres(), primitiveMeshTools::faceConcavity(), primitiveMeshTools::faceFlatness(), Patch::faceNormals(), mappedPatchBase::facePoint(), Patch::faces(), polyMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::filmPyrolysisRadiativeCoupledMixedFvPatchScalarField(), pointNoise::filterTimeData(), sensitivitySurfacePoints::finalisePointSensitivities(), voxelMeshSearch::findCell(), polyMesh::findCell(), meshRefinement::findCell(), PDRblock::location::findCell(), polyMesh::findCellFacePt(), PDRblock::location::findIndex(), meshRefinement::findRegion(), polyMesh::findTetFacePt(), fixedGradientFvPatchField< Type >::fixedGradientFvPatchField(), fixedJumpAMIFvPatchField< Type >::fixedJumpAMIFvPatchField(), fixedJumpFvPatchField< Type >::fixedJumpFvPatchField(), fixedValueFvPatchField< Type >::fixedValueFvPatchField(), face::FOAM_DEPRECATED_FOR(), for(), forAll(), forAll(), pitchForkRing::force(), FreeStream< CloudType >::FreeStream(), freestreamFvPatchField< Type >::freestreamFvPatchField(), freestreamFvPatchField< Type >::freestreamFvPatchField(), freestreamPressureFvPatchScalarField::freestreamPressureFvPatchScalarField(), freestreamVelocityFvPatchVectorField::freestreamVelocityFvPatchVectorField(), SpecieMixture< MixtureType >::G(), thermo< Thermo, Type >::G(), thermo< Thermo, Type >::g(), thermo< Thermo, Type >::gamma(), phaseModel::gamma(), heThermo< BasicThermo, MixtureType >::gamma(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::gasHs(), get_geom_list(), coordSetWriter::getBufferLine(), Foam::getOctant(), searchableSphere::getVolumeType(), cylinderImplicitFunction::grad(), ellipsoidImplicitFunction::grad(), sphereImplicitFunction::grad(), CompositionModel< CloudType >::H(), icoTabulated< Specie >::H(), PengRobinsonGas< Specie >::H(), aC10H7CH3::h(), Ar::h(), bC10H7CH3::h(), C10H22::h(), C12H26::h(), C13H28::h(), C14H30::h(), C16H34::h(), C2H5OH::h(), C2H6::h(), C2H6O::h(), C3H6O::h(), C3H8::h(), C4H10O::h(), C6H14::h(), C6H6::h(), C7H16::h(), C7H8::h(), C8H10::h(), C8H18::h(), C9H20::h(), CH3OH::h(), CH4N2O::h(), H2O::h(), iC3H8O::h(), IC8H18::h(), IDEA::h(), MB::h(), N2::h(), nC3H8O::h(), SpecieMixture< MixtureType >::Ha(), hConstThermo< EquationOfState >::Ha(), hPolynomialThermo< EquationOfState, PolySize >::Ha(), hPowerThermo< EquationOfState >::Ha(), hTabulatedThermo< EquationOfState >::Ha(), janafThermo< EquationOfState >::Ha(), Ha(), liquidProperties::Ha(), thermophysicalPropertiesSelector< ThermophysicalProperties >::Ha(), FaceCellWave< Type, TrackingData >::hasPatch(), CompositionModel< CloudType >::Hc(), SpecieMixture< MixtureType >::HE(), thermo< Thermo, Type >::HE(), thermo< Thermo, Type >::he(), thermalBaffle::he(), absoluteEnthalpy< Thermo >::HE(), absoluteInternalEnergy< Thermo >::HE(), sensibleEnthalpy< Thermo >::HE(), sensibleInternalEnergy< Thermo >::HE(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), heheuPsiThermo< BasicPsiThermo, MixtureType >::heu(), heheuPsiThermo< BasicPsiThermo, MixtureType >::heu(), particle< Type >::hitBoundaryFace(), KinematicParcel< ParcelType >::hitPatch(), PointHit< PointType >::hitPoint(), PointIndexHit< PointType >::hitPoint(), PointIndexHit< PointType >::hitPoint(), liquidFilmThermo::hl(), liquidMixtureProperties::hl(), aC10H7CH3::hl(), Ar::hl(), bC10H7CH3::hl(), C10H22::hl(), C12H26::hl(), C13H28::hl(), C14H30::hl(), C16H34::hl(), C2H5OH::hl(), C2H6::hl(), C2H6O::hl(), C3H6O::hl(), C3H8::hl(), C4H10O::hl(), C6H14::hl(), C6H6::hl(), C7H16::hl(), C7H8::hl(), C8H10::hl(), C8H18::hl(), C9H20::hl(), CH3OH::hl(), CH4N2O::hl(), H2O::hl(), iC3H8O::hl(), IC8H18::hl(), IDEA::hl(), MB::hl(), N2::hl(), nC3H8O::hl(), CompositionModel< CloudType >::Hs(), SpecieMixture< MixtureType >::Hs(), hConstThermo< EquationOfState >::Hs(), hPolynomialThermo< EquationOfState, PolySize >::Hs(), hPowerThermo< EquationOfState >::Hs(), hTabulatedThermo< EquationOfState >::Hs(), janafThermo< EquationOfState >::Hs(), Hs(), liquidProperties::Hs(), thermophysicalPropertiesSelector< ThermophysicalProperties >::Hs(), ReactingMultiphaseParcel< ParcelType >::HsEff(), ReactingHeterogeneousParcel< ParcelType >::HsEff(), humidityTemperatureCoupledMixedFvPatchScalarField::humidityTemperatureCoupledMixedFvPatchScalarField(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), face::inertia(), FreeStream< CloudType >::inflow(), InjectedParticleDistributionInjection< CloudType >::initialise(), InjectedParticleInjection< CloudType >::initialise(), cyclicFaPatch::initMovePoints(), processorFaPatch::initMovePoints(), mappedPolyPatch::initMovePoints(), mappedWallPolyPatch::initMovePoints(), cyclicPolyPatch::initMovePoints(), oldCyclicPolyPatch::initMovePoints(), processorPolyPatch::initMovePoints(), cyclicACMIPolyPatch::initMovePoints(), cyclicAMIPolyPatch::initMovePoints(), inletOutletFaPatchField< Type >::inletOutletFaPatchField(), inletOutletFvPatchField< Type >::inletOutletFvPatchField(), blockMesh::inplacePointTransforms(), tetrahedron< Point, PointRef >::inside(), DSMCCloud< ParcelType >::internalEnergyOfSystem(), regionModel::interRegionAMI(), face::intersection(), triFace::intersection(), triFace::intersection(), Foam::isA(), meshSearch::isInside(), particleInfo::isOlderThan(), token::isPunctuation(), objectiveForce::J(), objectiveMoment::J(), objectivePtLosses::J(), StandardChemistryModel< ReactionThermo, ThermoType >::jacobian(), TDACChemistryModel< ReactionThermo, ThermoType >::jacobian(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::jacobian(), TDACChemistryModel< ReactionThermo, ThermoType >::jacobian(), liquidFilmThermo::kappa(), SpecieMixture< MixtureType >::kappa(), liquidFilmThermo::kappa(), tabulatedSolidTransport< Thermo >::kappa(), tabulatedSolidTransport< Thermo >::Kappa(), constTransport< Thermo >::kappa(), sutherlandTransport< Thermo >::kappa(), tabulatedTransport< Thermo >::kappa(), WLFTransport< Thermo >::kappa(), liquidMixtureProperties::kappa(), aC10H7CH3::kappa(), Ar::kappa(), bC10H7CH3::kappa(), C10H22::kappa(), C12H26::kappa(), C13H28::kappa(), C14H30::kappa(), C16H34::kappa(), C2H5OH::kappa(), C2H6::kappa(), C2H6O::kappa(), C3H6O::kappa(), C3H8::kappa(), C4H10O::kappa(), C6H14::kappa(), C6H6::kappa(), C7H16::kappa(), C7H8::kappa(), C8H10::kappa(), C8H18::kappa(), C9H20::kappa(), CH3OH::kappa(), CH4N2O::kappa(), H2O::kappa(), iC3H8O::kappa(), IC8H18::kappa(), IDEA::kappa(), MB::kappa(), N2::kappa(), nC3H8O::kappa(), thermophysicalPropertiesSelector< ThermophysicalProperties >::kappa(), aC10H7CH3::kappag(), Ar::kappag(), bC10H7CH3::kappag(), C10H22::kappag(), C12H26::kappag(), C13H28::kappag(), C14H30::kappag(), C16H34::kappag(), C2H5OH::kappag(), C2H6::kappag(), C2H6O::kappag(), C3H6O::kappag(), C3H8::kappag(), C4H10O::kappag(), C6H14::kappag(), C6H6::kappag(), C7H16::kappag(), C7H8::kappag(), C8H10::kappag(), C8H18::kappag(), C9H20::kappag(), CH3OH::kappag(), CH4N2O::kappag(), H2O::kappag(), iC3H8O::kappag(), IC8H18::kappag(), IDEA::kappag(), MB::kappag(), N2::kappag(), nC3H8O::kappag(), thermo< Thermo, Type >::Kc(), IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kf(), NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kf(), ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kf(), thermo< Thermo, Type >::Kn(), thermo< Thermo, Type >::Kp(), NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kr(), ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kr(), NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kr(), ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kr(), thermo< Thermo, Type >::Kx(), CompositionModel< CloudType >::L(), InterfaceCompositionModel< Thermo, OtherThermo >::L(), ReactingMultiphaseParcel< ParcelType >::LEff(), ReactingHeterogeneousParcel< ParcelType >::LEff(), pressureControl::limit(), DSMCCloud< ParcelType >::linearKineticEnergyOfSystem(), KinematicCloud< CloudType >::linearKineticEnergyOfSystem(), DSMCCloud< ParcelType >::linearMomentumOfSystem(), KinematicCloud< CloudType >::linearMomentumOfSystem(), Foam::linearWeight(), triSurfaceLoader::load(), loadLibrary(), fvPatch::lookupPatch(), face::mag(), simple::mainIter(), highAspectRatioFvGeometryScheme::makeAverageCentres(), stabilisedFvGeometryScheme::makeFaceCentresAndAreas(), primitiveMeshTools::makeFaceCentresAndAreas(), primitiveMeshTools::makeFaceCentresAndAreas(), deltaBoundary::makeFaceCentresAndAreas_d(), deltaBoundary::makeFaceCentresAndAreas_d(), mappedVelocityFluxFixedValueFvPatchField::mappedVelocityFluxFixedValueFvPatchField(), mappedVelocityFluxFixedValueFvPatchField::mappedVelocityFluxFixedValueFvPatchField(), mappedPatchFieldBase< Type >::mapper(), regionModel::mapRegionPatchField(), regionModel::mapRegionPatchInternalField(), Foam::markupBoundaryPoints(), PatchTools::markZone(), PatchTools::markZones(), VirtualMassForce< CloudType >::massAdd(), ParticleForceList< KinematicCloud< Foam::DSMCCloud > >::massEff(), ParticleForceList< CloudType >::massEff(), DSMCCloud< ParcelType >::massInSystem(), KinematicCloud< CloudType >::massInSystem(), rigidBodyModel::masterPoint(), noiseModel::meanPf(), Patch::mesh(), plane::mirror(), polyTopoChanger::modifyMotionPoints(), layeredEngineMesh::move(), wallBoundedStreamLineParticle::move(), DSMCParcel< ParcelType >::move(), CollidingParcel< ParcelType >::move(), KinematicParcel< ParcelType >::move(), MPPICParcel< ParcelType >::move(), Cloud< ParcelType >::move(), Cloud< ParticleType >::move(), fvBoundaryMesh::movePoints(), solidBodyFvGeometryScheme::movePoints(), FitData< CentredFitData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::movePoints(), velocityDisplacementMotionSolver::movePoints(), faBoundaryMesh::movePoints(), fvMesh::movePoints(), displacementMeshMoverMotionSolver::movePoints(), displacementMotionSolverMeshMover::movePoints(), medialAxisMeshMover::movePoints(), pointBoundaryMesh::movePoints(), polyBoundaryMesh::movePoints(), cyclicFaPatch::movePoints(), mappedPolyPatch::movePoints(), mappedWallPolyPatch::movePoints(), cyclicPolyPatch::movePoints(), oldCyclicPolyPatch::movePoints(), polyPatch::movePoints(), cyclicACMIPolyPatch::movePoints(), liquidFilmThermo::mu(), SpecieMixture< MixtureType >::mu(), liquidFilmThermo::mu(), tabulatedTransport< Thermo >::mu(), liquidMixtureProperties::mu(), aC10H7CH3::mu(), Ar::mu(), bC10H7CH3::mu(), C10H22::mu(), C12H26::mu(), C13H28::mu(), C14H30::mu(), C16H34::mu(), C2H5OH::mu(), C2H6::mu(), C2H6O::mu(), C3H6O::mu(), C3H8::mu(), C4H10O::mu(), C6H14::mu(), C6H6::mu(), C7H16::mu(), C7H8::mu(), C8H10::mu(), C8H18::mu(), C9H20::mu(), CH3OH::mu(), CH4N2O::mu(), H2O::mu(), iC3H8O::mu(), IC8H18::mu(), IDEA::mu(), MB::mu(), N2::mu(), nC3H8O::mu(), thermophysicalPropertiesSelector< ThermophysicalProperties >::mu(), aC10H7CH3::mug(), Ar::mug(), bC10H7CH3::mug(), C10H22::mug(), C12H26::mug(), C13H28::mug(), C14H30::mug(), C16H34::mug(), C2H5OH::mug(), C2H6::mug(), C2H6O::mug(), C3H6O::mug(), C3H8::mug(), C4H10O::mug(), C6H14::mug(), C6H6::mug(), C7H16::mug(), C7H8::mug(), C8H10::mug(), C8H18::mug(), C9H20::mug(), CH3OH::mug(), CH4N2O::mug(), H2O::mug(), iC3H8O::mug(), IC8H18::mug(), IDEA::mug(), MB::mug(), N2::mug(), nC3H8O::mug(), regionModel::nbrCoupledPatchID(), line< Point, PointRef >::nearestDist(), plane::nearestPoint(), tetrahedron< Point, PointRef >::nearestPoint(), triangle< Point, PointRef >::nearestPoint(), face::nearestPoint(), triFace::nearestPoint(), face::nearestPointClassify(), triFace::nearestPointClassify(), triangle< Point, PointRef >::nearestPointClassify(), faePatchField< Type >::New(), faPatchField< Type >::New(), faePatchField< Type >::New(), faPatchField< Type >::New(), fvsPatchField< Type >::New(), fvPatchField< Type >::New(), fvPatchField< Type >::New(), fvsPatchField< Type >::New(), pointPatchField< Type >::New(), pointPatchField< Type >::New(), faPatchField< Type >::New(), faePatchField< Type >::New(), fvsPatchField< Type >::New(), fvPatchField< Type >::New(), pointPatchField< Type >::New(), faPatchField< Type >::New(), faePatchField< Type >::New(), fvsPatchField< Type >::New(), fvPatchField< Type >::New(), pointPatchField< Type >::New(), fvPatchField< Type >::NewCalculatedType(), fvsPatchField< Type >::NewCalculatedType(), faBoundaryMesh::nNonProcessor(), polyBoundaryMesh::nNonProcessor(), basicFvGeometryScheme::nonOrthCorrectionVectors(), basicFvGeometryScheme::nonOrthDeltaCoeffs(), faBoundaryMesh::nProcessorPatches(), polyBoundaryMesh::nProcessorPatches(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), StandardChemistryModel< CompType, ThermoType >::omega(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), StandardChemistryModel< ReactionThermo, ThermoType >::omega(), StandardChemistryModel< ReactionThermo, ThermoType >::omegaI(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omegaI(), token::operator!=(), RaviPetersen::operator()(), sumParticleOp< VOFParticle >::operator()(), areaOp::operator()(), areaIntegrateOp< Type >::operator()(), volumeOp::operator()(), volumeIntegrateOp< Type >::operator()(), listOp< N >::operator()(), polyline::operator()(), sigmaRadial::operator()(), ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::operator()(), FallOffReactionRate< ReactionRate, FallOffFunction >::operator()(), thirdBodyArrheniusReactionRate::operator()(), Foam::operator*(), Foam::operator*(), particleInfo::operator+=(), lumpedPointState::operator+=(), Foam::operator/(), Foam::operator/(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), polyPatch::operator=(), token::operator=(), refPtr< Field< Type > >::operator=(), tmp< T >::operator=(), token::operator==(), Foam::operator>>(), oscillatingVelocityPointPatchVectorField::oscillatingVelocityPointPatchVectorField(), outletInletFaPatchField< Type >::outletInletFaPatchField(), outletInletFvPatchField< Type >::outletInletFvPatchField(), KinematicCloud< Foam::DSMCCloud >::outputProperties(), partialSlipFvPatchField< Type >::partialSlipFvPatchField(), KinematicCloud< CloudType >::patchData(), multiComponentMixture< ThermoType >::patchFaceVolMixture(), wallBoundedParticle::patchInteraction(), polyBoundaryMesh::patchRanges(), faBoundaryMesh::patchSizes(), polyBoundaryMesh::patchSizes(), polyBoundaryMesh::patchStarts(), SprayCloud< CloudType >::penetration(), perm_check(), perm_inv(), noiseModel::Pf(), polyBoundaryMesh::physicalTypes(), cyclicAMIPolyPatch::pointFace(), sampledSet::pointInCell(), primitiveMesh::pointInCell(), polyMesh::pointInCell(), primitiveMesh::pointInCellBB(), triangle2D::pointInside(), PatchTools::pointNormals(), vtuAdaptor::points(), Patch::points(), face::points(), triFace::points(), points_delaunay_naive_2d(), polyAddPoint::polyAddPoint(), ILList< LListBase, T >::pop_front(), LList< LListBase, T >::pop_front(), LPtrList< LListBase, T >::pop_front(), polyline::positionAndDirection(), RecycleInteraction< CloudType >::postEvolve(), HeatTransferCoeff< CloudType >::postEvolve(), KinematicReynoldsNumber< CloudType >::postEvolve(), NusseltNumber< CloudType >::postEvolve(), ParticleDose< CloudType >::postEvolve(), ParticleZoneInfo< CloudType >::postEvolve(), ThermoReynoldsNumber< CloudType >::postEvolve(), WeberNumberReacting< CloudType >::postEvolve(), CloudFunctionObjectList< CloudType >::postFace(), FaceInteraction< CloudType >::postFace(), FacePostProcessing< CloudType >::postFace(), ParticleHistogram< CloudType >::postFace(), ParticlePostProcessing< CloudType >::postFace(), ParticleTracks< CloudType >::postFace(), RemoveParcels< CloudType >::postFace(), ParticleCollector< CloudType >::postMove(), ParticleTrap< CloudType >::postMove(), ParticleZoneInfo< CloudType >::postMove(), VoidFraction< CloudType >::postMove(), CloudFunctionObjectList< CloudType >::postPatch(), ParticleErosion< CloudType >::postPatch(), ParticleHistogram< CloudType >::postPatch(), ParticlePostProcessing< CloudType >::postPatch(), PatchCollisionDensity< CloudType >::postPatch(), PatchInteractionFields< CloudType >::postPatch(), Foam::pow(), Foam::pow(), OSstream::precision(), WallLocalSpringSliderDashpot< CloudType >::pREff(), WallSpringSliderDashpot< CloudType >::pREff(), PDRblock::gridControl::prepend(), pressureControl::pressureControl(), pressureInletOutletVelocityFvPatchVectorField::pressureInletOutletVelocityFvPatchVectorField(), faMeshTools::printMeshChecks(), Foam::printPatchEdges(), Foam::prismOp(), pointNoise::processData(), processorCyclicFvPatchField< Type >::processorCyclicFvPatchField(), processorCyclicFvPatchField< Type >::processorCyclicFvPatchField(), processorCyclicFvsPatchField< Type >::processorCyclicFvsPatchField(), processorFaePatchField< Type >::processorFaePatchField(), processorFaPatchField< Type >::processorFaPatchField(), processorFaPatchField< Type >::processorFaPatchField(), processorFvPatchField< Type >::processorFvPatchField(), processorFvPatchField< Type >::processorFvPatchField(), processorFvsPatchField< Type >::processorFvsPatchField(), processorGAMGInterfaceField::processorGAMGInterfaceField(), FaceInteraction< CloudType >::processParticle(), noiseModel::PSDf(), adiabaticPerfectFluid< Specie >::psi(), PengRobinsonGas< Specie >::psi(), rPolynomial< Specie >::psi(), thermophysicalPropertiesSelector< ThermophysicalProperties >::psi(), colourTable::ptr(), liquidFilmThermo::pv(), liquidMixtureProperties::pv(), aC10H7CH3::pv(), Ar::pv(), bC10H7CH3::pv(), C10H22::pv(), C12H26::pv(), C13H28::pv(), C14H30::pv(), C16H34::pv(), C2H5OH::pv(), C2H6::pv(), C2H6O::pv(), C3H6O::pv(), C3H8::pv(), C4H10O::pv(), C6H14::pv(), C6H6::pv(), C7H16::pv(), C7H8::pv(), C8H10::pv(), C8H18::pv(), C9H20::pv(), CH3OH::pv(), CH4N2O::pv(), H2O::pv(), iC3H8O::pv(), IC8H18::pv(), IDEA::pv(), MB::pv(), N2::pv(), nC3H8O::pv(), liquidMixtureProperties::pvInvert(), liquidProperties::pvInvert(), Kutadeladze::qNucleate(), Foam::quadOp(), Foam::quadraticWeight(), face::ray(), triangle< Point, PointRef >::ray(), triFace::ray(), contactHeatFluxSource::read(), externalFileSource::read(), particle< Type >::readData(), DSMCParcel< ParcelType >::readFields(), injectedParticle::readFields(), solidParticle::readFields(), streamLineParticle::readFields(), wallBoundedStreamLineParticle::readFields(), CollidingParcel< ParcelType >::readFields(), KinematicParcel< ParcelType >::readFields(), MPPICParcel< ParcelType >::readFields(), ThermoParcel< ParcelType >::readFields(), ReactingHeterogeneousParcel< ParcelType >::readFields(), ReactingMultiphaseParcel< ParcelType >::readFields(), ReactingParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::readFields(), wallBoundedParticle::readFields(), particle< Type >::readFields(), ensightSurfaceReader::readGeometry(), fixedGradientFaPatchField< Type >::readGradientEntry(), fixedGradientFvPatchField< Type >::readGradientEntry(), PtrList< T >::readIstream(), PtrList< CloudFunctionObject< CloudType > >::readIstream(), mixedFaPatchField< Type >::readMixedEntries(), mixedFvPatchField< scalar >::readMixedEntries(), mixedFvPatchField< Type >::readMixedEntries(), injectedParticle::readObjects(), ReactingParcel< ParcelType >::readObjects(), SprayParcel< ParcelType >::readObjects(), particle< Type >::readObjects(), CollidingParcel< ParcelType >::readObjects(), KinematicParcel< ParcelType >::readObjects(), MPPICParcel< ParcelType >::readObjects(), ThermoParcel< ParcelType >::readObjects(), ABAQUSCore::readHelper::readPoints(), faePatchField< Type >::readValueEntry(), faPatchField< Type >::readValueEntry(), fvPatchField< Type >::readValueEntry(), fvsPatchField< Type >::readValueEntry(), valuePointPatchField< Type >::readValueEntry(), InteractionLists< ParticleType >::receiveReferredData(), DAC< CompType, ThermoType >::reduceMechanism(), DRG< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), EFA< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), cellModel::ref(), cellModel::ref(), cellModel::ref(), colourTable::ref(), refPtr< Field< Type > >::ref(), refPtr< T >::ref(), tmp< T >::ref(), Foam::refCast(), Foam::refCast(), Foam::refCast(), relax(), autoPtr< T >::release(), SLListBase::remove(), LList< LListBase, T >::link::remove(), tmp< T >::reset(), autoPtr< T >::reset(), tmp< T >::reset(), softWall::restrain(), Foam::Detail::reusable(), Foam::reverse(), liquidFilmThermo::rho(), SpecieMixture< MixtureType >::rho(), liquidFilmThermo::rho(), liquidMixtureProperties::rho(), CompositionModel< CloudType >::rho(), forces::rho(), adiabaticPerfectFluid< Specie >::rho(), icoTabulated< Specie >::rho(), linear< Type >::rho(), PengRobinsonGas< Specie >::rho(), perfectFluid< Specie >::rho(), perfectGas< Specie >::rho(), rPolynomial< Specie >::rho(), aC10H7CH3::rho(), Ar::rho(), bC10H7CH3::rho(), C10H22::rho(), C12H26::rho(), C13H28::rho(), C14H30::rho(), C16H34::rho(), C2H5OH::rho(), C2H6::rho(), C2H6O::rho(), C3H6O::rho(), C3H8::rho(), C4H10O::rho(), C6H14::rho(), C6H6::rho(), C7H16::rho(), C7H8::rho(), C8H10::rho(), C8H18::rho(), C9H20::rho(), CH3OH::rho(), CH4N2O::rho(), H2O::rho(), iC3H8O::rho(), IC8H18::rho(), IDEA::rho(), MB::rho(), N2::rho(), nC3H8O::rho(), thermophysicalPropertiesSelector< ThermophysicalProperties >::rho(), KinematicCloud< CloudType >::rhoEff(), KinematicCloud< Foam::DSMCCloud >::rhoEff(), heThermo< BasicThermo, MixtureType >::rhoEoS(), heThermo< BasicPsiThermo, MixtureType >::rhoEoS(), noiseModel::RMSmeanPf(), cubicEqn::roots(), CollidingCloud< CloudType >::rotationalKineticEnergyOfSystem(), solidChemistryModel< CompType, SolidThermo >::RRsHs(), SpecieMixture< MixtureType >::S(), adiabaticPerfectFluid< Specie >::S(), linear< Type >::S(), PengRobinsonGas< Specie >::S(), perfectFluid< Specie >::S(), perfectGas< Specie >::S(), eConstThermo< EquationOfState >::S(), hConstThermo< EquationOfState >::S(), hPolynomialThermo< EquationOfState, PolySize >::S(), hPowerThermo< EquationOfState >::S(), hTabulatedThermo< EquationOfState >::S(), janafThermo< EquationOfState >::S(), thermo< Thermo, Type >::s(), thermophysicalPropertiesSelector< ThermophysicalProperties >::S(), general::sample(), normal::sample(), multiNormal::sample(), PPCG::scalarSolveCG(), Foam::serializeProjectPoints(), autoPtr< T >::set(), cellSetOption::setCellSelection(), noiseFFT::setData(), noiseFFT::setData(), lumpedPointDisplacementPointPatchVectorField::setInterpolators(), KinematicSurfaceFilm< CloudType >::setParcelProperties(), SurfaceFilmModel< CloudType >::setParcelProperties(), ThermoSurfaceFilm< CloudType >::setParcelProperties(), SprayCloud< CloudType >::setParcelThermoProperties(), lumpedPointDisplacementPointPatchVectorField::setPatchControls(), fvMesh::setPhi(), PointHit< PointType >::setPoint(), PointIndexHit< PointType >::setPoint(), propellerInfo::setSampleDiskGeometry(), plane::sideOfPlane(), liquidFilmThermo::sigma(), liquidFilmThermo::sigma(), liquidMixtureProperties::sigma(), aC10H7CH3::sigma(), Ar::sigma(), bC10H7CH3::sigma(), C10H22::sigma(), C12H26::sigma(), C13H28::sigma(), C14H30::sigma(), C16H34::sigma(), C2H5OH::sigma(), C2H6::sigma(), C2H6O::sigma(), C3H6O::sigma(), C3H8::sigma(), C4H10O::sigma(), C6H14::sigma(), C6H6::sigma(), C7H16::sigma(), C7H8::sigma(), C8H10::sigma(), C8H18::sigma(), C9H20::sigma(), CH3OH::sigma(), CH4N2O::sigma(), H2O::sigma(), iC3H8O::sigma(), IC8H18::sigma(), IDEA::sigma(), MB::sigma(), N2::sigma(), nC3H8O::sigma(), plane::sign(), triangle< Point, PointRef >::sign(), face::sign(), triFace::sign(), plane::signedDistance(), sixDoFRigidBodyDisplacementPointPatchVectorField::sixDoFRigidBodyDisplacementPointPatchVectorField(), slicedFaePatchField< Type >::slicedFaePatchField(), slicedFaPatchField< Type >::slicedFaPatchField(), slicedFvPatchField< Type >::slicedFvPatchField(), slicedFvsPatchField< Type >::slicedFvsPatchField(), cellDistFuncs::smallestDist(), StandardChemistryModel< ReactionThermo, ThermoType >::solve(), TDACChemistryModel< ReactionThermo, ThermoType >::solve(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), EulerImplicit< ChemistryModel >::solve(), ode< ChemistryModel >::solve(), plane::somePointInPlane(), PatchTools::sortedEdgeFaces(), PatchTools::sortedPointEdges(), DiagonalMatrix< Type >::sortPermutation(), SquareMatrix< Type >::sortPermutation(), specularRadiationMixedFvPatchScalarField::specularRadiationMixedFvPatchScalarField(), KinematicSurfaceFilm< CloudType >::splashInteraction(), regIOobject::store(), regIOobject::store(), regIOobject::store(), oversetFvPatchField< Type >::storeFringeCoefficients(), Cloud< ParticleType >::storeGlobalPositions(), meshRefinement::subsetBaffles(), PatchTools::subsetMap(), autoPtr< T >::swap(), refPtr< T >::swap(), tmp< T >::swap(), symmetryFaePatchField< Type >::symmetryFaePatchField(), symmetryFaPatchField< Type >::symmetryFaPatchField(), symmetryFaPatchField< Type >::symmetryFaPatchField(), symmetryFvPatchField< Type >::symmetryFvPatchField(), symmetryFvPatchField< Type >::symmetryFvPatchField(), symmetryFvsPatchField< Type >::symmetryFvsPatchField(), symmetryPlaneFvPatchField< Type >::symmetryPlaneFvPatchField(), symmetryPlaneFvPatchField< Type >::symmetryPlaneFvPatchField(), symmetryPlaneFvsPatchField< Type >::symmetryPlaneFvsPatchField(), symmetryPlanePointPatchField< Type >::symmetryPlanePointPatchField(), symmetryPointPatchField< Type >::symmetryPointPatchField(), liquidFilmThermo::Tb(), StandardChemistryModel< ReactionThermo, ThermoType >::tc(), thermo< Thermo, Type >::TEa(), thermo< Thermo, Type >::TEs(), Foam::tetCutPrism0(), Foam::tetCutPrism01(), Foam::tetCutPrism23(), Foam::tetCutTet(), thermo< Thermo, Type >::THa(), thermo< Thermo, Type >::THE(), heThermo< BasicThermo, MixtureType >::THE(), heThermo< BasicThermo, MixtureType >::THE(), absoluteInternalEnergy< Thermo >::THE(), sensibleInternalEnergy< Thermo >::THE(), absoluteEnthalpy< Thermo >::THE(), sensibleEnthalpy< Thermo >::THE(), thermo< Thermo, Type >::THs(), ThermoCloud< CloudType >::Tmax(), LiquidEvapFuchsKnudsen< CloudType >::TMax(), LiquidEvaporation< CloudType >::TMax(), LiquidEvaporationBoil< CloudType >::TMax(), ThermoCloud< CloudType >::Tmin(), token::token(), dictionary::topDict(), Foam::toPoint(), CV2D::toPoint(), CV2D::toPoint2D(), CV2D::toPoint2D(), CV2D::toPoint3D(), KinematicCloud< CloudType >::totalParticlePerParcel(), KinematicSurfaceFilm< CloudType >::transferParcel(), ThermoSurfaceFilm< CloudType >::transferParcel(), spatialTransform::transformPoint(), Foam::triCutQuad(), Foam::triCutTri(), Antoine::Tsat(), constantSaturationConditions::Tsat(), function1::Tsat(), polynomial::Tsat(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::turbulentTemperatureRadCoupledMixedFvPatchScalarField(), motionSolver::twoDCorrectPoints(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField(), uniformMixedFvPatchField< Type >::uniformMixedFvPatchField(), face::unitNormal(), SHF< CloudType >::update(), objectivePtLosses::update_boundarydJdv(), objectivePtLosses::update_boundarydJdvn(), objectiveForce::update_dSdbMultiplier(), objectiveMoment::update_dSdbMultiplier(), objectiveMoment::update_dxdbDirectMultiplier(), objectiveForce::update_dxdbMultiplier(), objectiveMoment::update_dxdbMultiplier(), KinematicParcel< ParcelType >::trackingData::updateAverages(), MPPICParcel< ParcelType >::trackingData::updateAverages(), activeBaffleVelocityFvPatchVectorField::updateCoeffs(), activePressureForceBaffleVelocityFvPatchVectorField::updateCoeffs(), outletMappedUniformInletFvPatchField< Type >::updateCoeffs(), plenumPressureFvPatchScalarField::updateCoeffs(), cellMotionFvPatchField< Type >::updateCoeffs(), angularOscillatingVelocityPointPatchVectorField::updateCoeffs(), oscillatingVelocityPointPatchVectorField::updateCoeffs(), outletMachNumberPressureFvPatchScalarField::updateCoeffs(), ReactingParcel< ParcelType >::updatedDeltaVolume(), ReactingMultiphaseParcel< ParcelType >::updatedDeltaVolume(), primitiveMeshTools::updateFaceCentresAndAreas(), prghPermeableAlphaTotalPressureFvPatchScalarField::updateSnGrad(), movingWallVelocityFvPatchVectorField::Uwall(), rigidBodyModel::v(), noiseModel::validateBounds(), cylinderImplicitFunction::value(), ellipsoidImplicitFunction::value(), paraboloidImplicitFunction::value(), planeImplicitFunction::value(), sinImplicitFunction::value(), sphereImplicitFunction::value(), Relaxation< CloudType >::velocityCorrection(), Explicit< CloudType >::velocityCorrection(), Implicit< CloudType >::velocityCorrection(), triSurfaceTools::vertexTriads(), MassTransferPhaseSystem< BasePhaseSystem >::volTransfer(), Foam::vtkWritePatchEdges(), wedgeFaePatchField< Type >::wedgeFaePatchField(), wedgeFaPatchField< Type >::wedgeFaPatchField(), wedgeFvPatchField< Type >::wedgeFvPatchField(), wedgeFvPatchField< Type >::wedgeFvPatchField(), wedgeFvsPatchField< Type >::wedgeFvsPatchField(), wedgePointPatchField< Type >::wedgePointPatchField(), KinematicSurfaceFilm< CloudType >::wetSplashInteraction(), polyBoundaryMesh::whichPatchFace(), plane::whichSide(), while(), while(), while(), while(), while(), momentum::write(), regionSizeDistribution::write(), dsmcFields::write(), ParticleZoneInfo< CloudType >::write(), equalBinWidth::write(), OBJedgeFormat::write(), OBJstream::write(), OBJstream::write(), OBJstream::write(), coordSet::write(), eddy::writeCentreOBJ(), Foam::ensightOutput::writeCloudPositions(), meshToMeshMethod::writeConnectivity(), NASCore::writeCoord(), faBoundaryMesh::writeData(), DSMCParcel< ParcelType >::writeFields(), injectedParticle::writeFields(), solidParticle::writeFields(), streamLineParticle::writeFields(), wallBoundedStreamLineParticle::writeFields(), CollidingParcel< ParcelType >::writeFields(), KinematicParcel< ParcelType >::writeFields(), MPPICParcel< ParcelType >::writeFields(), ThermoParcel< ParcelType >::writeFields(), ReactingHeterogeneousParcel< ParcelType >::writeFields(), ReactingParcel< ParcelType >::writeFields(), SprayParcel< ParcelType >::writeFields(), wallBoundedParticle::writeFields(), particle< Type >::writeFields(), externalCoupled::writeGeometry(), Foam::writeMeasured_ascii(), Foam::writeMeasured_binary(), faceAreaWeightAMI2D::writeNoMatch(), AABBTreeBase::writeOBJ(), indexedOctreeBase::writeOBJ(), injectedParticle::writeObjects(), ReactingParcel< ParcelType >::writeObjects(), SprayParcel< ParcelType >::writeObjects(), particle< Type >::writeObjects(), CollidingParcel< ParcelType >::writeObjects(), KinematicParcel< ParcelType >::writeObjects(), MPPICParcel< ParcelType >::writeObjects(), ThermoParcel< ParcelType >::writeObjects(), Foam::writeObjEdges(), lumpedPointState::writePlain(), Foam::writePoint(), ABAQUSCore::writePoints(), STARCDCore::writePoints(), X3DsurfaceFormatCore::writePoints(), injectedParticle::writePosition(), particle< Type >::writePosition(), passivePositionParticle::writePosition(), Cloud< ParticleType >::writePositions(), eddy::writeSurfaceOBJ(), coordSetWriter::writeTable(), interfaceTrackingFvMesh::writeVTKControlPoints(), liquidMixtureProperties::Xs(), PengRobinsonGas< Specie >::Z(), ILList< ParticleType >::~ILList(), and TDACChemistryModel< CompType, ThermoType >::~TDACChemistryModel().