OpenFOAM: applications/solvers/combustion/PDRFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
volVectorField HbyA (constrainHbyA(invA &UEqn.H(), U, p))
if (pimple.transonic())
while (pimple.correctNonOrthogonal())
U correctBoundaryConditions ()
fvOptions correct (U)
if (thermo.dpdt())
Variables
rho = thermo.rho()
else
U = HbyA - (invA & (betav*fvc::grad(p)))
K = 0.5*magSqr(U)
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
HbyA()
volVectorField HbyA (constrainHbyA(invA &UEqn.H(), U, p))
if() [1/2]
if (pimple. transonic())
Definition at line 6 of file pEqn.H.
References betav, fvOptions, HbyA, invA(), mesh, p, phi, phid(), pimple, psi, rAU, rho, and U.
while()
while (pimple. correctNonOrthogonal())
Definition at line 49 of file pEqn.H.
References betav, fvOptions, invA(), mesh, p, phi, phiHbyA, pimple, psi, and rho.
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
if() [2/2]
if (thermo. dpdt())
Definition at line 77 of file pEqn.H.
References dpdt, and p.
Variable Documentation
rho
rho = thermo.rho()
Definition at line 1 of file pEqn.H.
else
else
Initial value:
{
    surfaceScalarField phiHbyA
    (
        "phiHbyA",
        (
            fvc::flux(rho*HbyA)
          + fvc::interpolate(rho*rAU)*fvc::ddtCorr(rho, U, phi)
        )
    )
Definition at line 38 of file pEqn.H.
U
U = HbyA - (invA & (betav*fvc::grad(p)))
Definition at line 72 of file pEqn.H.
Referenced by Foam::fvc::absolute(), Foam::fvc::absolute(), sensitivitySurface::accumulateIntegrand(), sensitivitySurfacePoints::accumulateIntegrand(), extractEulerianParticles::accumulateParticleInfo(), MRFZoneList::addAcceleration(), ATCstandard::addATC(), ATCUaGradU::addATC(), MRFZone::addCoriolis(), MRFZone::addCoriolis(), MRFZone::addCoriolis(), velocityDampingConstraint::addDamping(), DSMCCloud< ParcelType >::addNewParcel(), atmCoriolisUSource::addSup(), atmPlantCanopyUSource::addSup(), acousticDampingSource::addSup(), buoyancyEnergy::addSup(), heatExchangerSource::addSup(), viscousDissipation::addSup(), multiphaseMangrovesTurbulenceModel::addSup(), atmCoriolisUSource::addSup(), atmPlantCanopyUSource::addSup(), acousticDampingSource::addSup(), radialActuationDiskSource::addSup(), interRegionExplicitPorositySource::addSup(), multiphaseMangrovesSource::addSup(), multiphaseMangrovesTurbulenceModel::addSup(), atmCoriolisUSource::addSup(), atmPlantCanopyUSource::addSup(), acousticDampingSource::addSup(), radialActuationDiskSource::addSup(), interRegionExplicitPorositySource::addSup(), multiphaseMangrovesSource::addSup(), adjointkOmegaSST::adjointMeanFlowSource(), Foam::adjustPhi(), Foam::fvc::alphaCorr(), atmBoundaryLayerInletVelocityFvPatchVectorField::atmBoundaryLayerInletVelocityFvPatchVectorField(), Implicit< CloudType >::cacheFields(), Foam::calc_pTotal(), Foam::calc_rhoU(), energySpectrum::calcAndWriteSpectrum(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), targetCoeffTrim::calcCoeffs(), curvatureSeparation::calcCosAngle(), Foam::calcEk(), powerLawLopesdaCosta::calcForce(), DarcyForchheimer::calcForce(), fixedCoeff::calcForce(), powerLaw::calcForce(), solidification::calcForce(), forces::calcForcesMoments(), curvatureSeparation::calcInvR1(), curvatureSeparation::calcInvR1(), momentumError::calcMomentError(), atmNutUWallFunctionFvPatchScalarField::calcNut(), nutUBlendedWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), ObukhovLength::calcOL(), rotorDiskSource::calculate(), hydrostaticPressure::calculateAndWrite(), tabulatedHeatTransfer::calculateHtc(), tabulatedNTUHeatTransfer::calculateHtc(), nutUBlendedWallFunctionFvPatchScalarField::calcUTau(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), ReynoldsAnalogy::Cf(), coalCloudList::coalCloudList(), extractEulerianParticles::collectParticle(), kOmegaSST::computeG(), incompressibleAdjointSolver::computeGradDxDbMultiplier(), Foam::constrainHbyA(), Foam::constrainPressure(), Foam::constrainPressure(), Foam::constrainPressure(), Foam::constrainPressure(), adjointkOmegaSST::convectionMeanFlowSource(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), kL< BasicTurbulenceModel >::correct(), adjointkOmegaSST::correct(), kineticTheoryModel::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), SpalartAllmarasBase< BasicEddyViscosityModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), EBRSM< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::correct(), limitVelocity::correct(), contactAngleForce::correct(), forceList::correct(), powerLawLopesdaCosta::correct(), DarcyForchheimer::correct(), fixedCoeff::correct(), powerLaw::correct(), solidification::correct(), targetCoeffTrim::correct(), thixotropicViscosity::correct(), targetCoeffTrim::correct(), powerLawLopesdaCosta::correct(), DarcyForchheimer::correct(), fixedCoeff::correct(), powerLaw::correct(), solidification::correct(), powerLawLopesdaCosta::correct(), DarcyForchheimer::correct(), fixedCoeff::correct(), powerLaw::correct(), solidification::correct(), curvatureSeparation::correct(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), SpecularReflection< CloudType >::correct(), LocalInteraction< CloudType >::correct(), Rebound< CloudType >::correct(), StandardWallInteraction< CloudType >::correct(), multiphaseStabilizedTurbulence::correct(), limitVelocity::correct(), directionalPressureGradientExplicitSource::correct(), meanVelocityForce::correct(), contactAngleForce::correct(), forceList::correct(), thermocapillaryForce::correct(), incompressiblePrimalSolver::correctBoundaryConditions(), kOmegaSST::correctBoundaryConditions(), MRFZoneList::correctBoundaryFlux(), MRFZone::correctBoundaryVelocity(), MRFZoneList::correctBoundaryVelocity(), MovingPhaseModel< BasePhaseModel >::correctKinematics(), Foam::CorrectPhi(), Foam::CorrectPhi(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), Foam::fvc::correctRhoUf(), targetCoeffTrim::correctTrim(), Foam::fvc::correctUf(), Foam::correctUphiBCs(), Foam::correctUphiBCs(), interfaceTrackingFvMesh::correctUsBoundaryConditions(), MRFZoneList::DDt(), MRFZoneList::DDt(), Foam::fvc::ddtCorr(), Foam::fvc::ddtCorr(), Foam::fvc::ddtCorr(), Foam::fvc::ddtCorr(), Foam::fvc::ddtCorr(), Foam::fvc::ddtCorr(), ReynoldsAnalogy::devReff(), RASModelVariables::devReff(), adjointkOmegaSST::devReff(), adjointLaminar::devReff(), adjointSpalartAllmaras::devReff(), IncompressibleTurbulenceModel< TransportModel >::devReff(), PhaseIncompressibleTurbulenceModel< TransportModel >::devReff(), filmTurbulenceModel::devRhoReff(), kineticTheoryModel::devRhoReff(), phasePressureModel::devRhoReff(), Maxwell< BasicTurbulenceModel >::devRhoReff(), nonlinearEddyViscosity< BasicTurbulenceModel >::devRhoReff(), ReynoldsStress< BasicTurbulenceModel >::devRhoReff(), adjointkOmegaSST::diffusionNutMeanFlowMult(), adjointSpalartAllmaras::distanceSensitivities(), adjointLaminar::divDevReff(), IncompressibleTurbulenceModel< TransportModel >::divDevReff(), PhaseIncompressibleTurbulenceModel< TransportModel >::divDevReff(), momentumError::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::DivDevRhoReff(), incompressibleInterPhaseTransportModel< Mixture >::divDevRhoReff(), IncompressibleTurbulenceModel< TransportModel >::divDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), nonlinearEddyViscosity< BasicTurbulenceModel >::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), kineticTheoryModel::divDevRhoReff(), phasePressureModel::divDevRhoReff(), IncompressibleTurbulenceModel< TransportModel >::divDevRhoReff(), PhaseIncompressibleTurbulenceModel< TransportModel >::divDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), adjointkOmegaSST::divUMeanFlowSource(), adjointkOmegaSST::dNutdbMult(), adjointkOmegaSST::dR_dF1(), adjointkOmegaSST::dR_dnut(), multiphaseMangrovesSource::dragCoeff(), Foam::dynamicCast(), Foam::dynamicCast(), effectivenessTable::energyDensity(), KinematicParcel< ParcelType >::Eo(), multiphaseMangrovesTurbulenceModel::epsilonCoeff(), DispersionRASModel< CloudType >::epsilonModel(), PopeIndex::execute(), setFlow::execute(), propellerInfo::execute(), adjointkOmegaSST::FISensitivityTerm(), adjointSpalartAllmaras::FISensitivityTerm(), for(), for(), for(), forAll(), forAll(), ddtScheme< Type >::fvcDdtPhiCoeff(), ddtScheme< Type >::fvcDdtPhiCoeff(), ddtScheme< Type >::fvcDdtPhiCoeff(), ddtScheme< Type >::fvcDdtPhiCoeffExperimental(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), boundedDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), steadyStateDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), boundedDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), steadyStateDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), boundedDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), steadyStateDdtScheme< Type >::fvcDdtUfCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), boundedDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), steadyStateDdtScheme< Type >::fvcDdtUfCorr(), NURBS3DCurve::genEquidistant(), NURBS3DSurface::genEquidistant(), ATCstandard::getFISensitivityTerm(), ATCUaGradU::getFISensitivityTerm(), adjointkOmegaSST::GMeanFlowSource(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), incompressibleInterPhaseTransportModel< Mixture >::incompressibleInterPhaseTransportModel(), FreeStream< CloudType >::inflow(), rotorDiskSource::inflowVelocity(), InjectedParticleDistributionInjection< CloudType >::initialise(), InjectedParticleInjection< CloudType >::initialise(), wallBoundedStreamLineParticle::interpolateFields(), Foam::isA(), objectiveFlowRate::J(), objectiveFlowRatePartition::J(), objectivePowerDissipation::J(), objectivePtLosses::J(), objectiveUniformityCellZone::J(), objectiveUniformityPatch::J(), MovingPhaseModel< BasePhaseModel >::K(), multiphaseMangrovesTurbulenceModel::kCoeff(), DispersionRASModel< CloudType >::kModel(), kOmegaSSTDES< BasicTurbulenceModel >::LESRegion(), continuousGasKEqn< BasicTurbulenceModel >::liquidTurbulence(), continuousGasKEpsilon< BasicTurbulenceModel >::liquidTurbulence(), meanVelocityForce::magUbarAve(), patchMeanVelocityForce::magUbarAve(), phasePair::magUr(), simple::mainIter(), Foam::fvc::makeAbsolute(), Foam::fvc::makeAbsolute(), Foam::fvc::makeAbsolute(), MRFZone::makeAbsolute(), MRFZoneList::makeAbsolute(), Foam::fvc::makeRelative(), Foam::fvc::makeRelative(), Foam::fvc::makeRelative(), MRFZone::makeRelative(), MRFZoneList::makeRelative(), MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransfer(), MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransferf(), fvMotionSolverEngineMesh::move(), layeredEngineMesh::move(), solidParticleCloud::move(), streamLineParticle::move(), wallBoundedStreamLineParticle::move(), MPPICParcel< ParcelType >::move(), laminarModel< BasicTurbulenceModel >::New(), LESModel< BasicTurbulenceModel >::New(), RASModel< BasicTurbulenceModel >::New(), TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >::New(), PhaseIncompressibleTurbulenceModel< TransportModel >::New(), Foam::incompressible::New(), CompressibleTurbulenceModel< TransportModel >::New(), ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::New(), Foam::compressible::New(), IncompressibleTurbulenceModel< TransportModel >::New(), Foam::incompressible::New(), viscosityModel::New(), reconstructionSchemes::New(), autoPtr< T >::NewFrom(), refPtr< T >::NewFrom(), tmp< T >::NewFrom(), JohnsonJacksonSchaeffer::nu(), Schaeffer::nu(), adjointkOmegaSST::nutJacobianTMVar1(), adjointkOmegaSST::nutJacobianTMVar2(), adjointkOmegaSST::nutJacobianU(), adjointkOmegaSST::nutMeanFlowSource(), Foam::oversetAdjustPhi(), KinematicCloud< Foam::DSMCCloud >::packingModel(), particle< Type >::patchData(), PhaseCompressibleTurbulenceModel< phaseModel >::PhaseCompressibleTurbulenceModel(), continuousGasKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), NicenoKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), continuousGasKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), LaheyKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), ParticleErosion< CloudType >::postPatch(), filmTurbulenceModel::primaryRegionFriction(), KinematicParcel< ParcelType >::Re(), DSMCParcel< ParcelType >::readFields(), injectedParticle::readFields(), solidParticle::readFields(), KinematicParcel< ParcelType >::readFields(), injectedParticle::readObjects(), KinematicParcel< ParcelType >::readObjects(), Foam::refCast(), Foam::refCast(), Foam::refCast(), Foam::fvc::relative(), Foam::fvc::relative(), NullMRF::relative(), NullMRF::relative(), relax(), wallBoundedStreamLineParticle::sample(), PatchInjection< CloudType >::setProperties(), shallowWaterAbsorption::setVelocity(), generalizedNewtonian< BasicMomentumTransportModel >::strainRate(), laminar::Su(), coalCloudList::SU(), laminar::Su(), ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::ThermalDiffusivity(), dynamicContactAngleForce::theta(), phaseSystem::U(), SRFModel::Uabs(), interfaceTrackingFvMesh::update(), rawTopoChangerFvMesh::update(), GradientDispersionRAS< CloudType >::update(), StochasticDispersionRAS< CloudType >::update(), ReitzKHRT< CloudType >::update(), objectiveForce::update_boundarydJdnut(), objectiveMoment::update_boundarydJdnut(), objectivePtLosses::update_boundarydJdp(), objectivePtLosses::update_boundarydJdv(), objectiveUniformityPatch::update_boundarydJdv(), objectivePtLosses::update_boundarydJdvn(), objectiveUniformityPatch::update_boundarydJdvn(), objectivePtLosses::update_boundarydJdvt(), objectiveUniformityPatch::update_boundarydJdvt(), objectivePowerDissipation::update_divDxDbMultiplier(), objectiveUniformityCellZone::update_divDxDbMultiplier(), objectivePowerDissipation::update_dJdTMvar1(), objectivePowerDissipation::update_dJdTMvar2(), objectivePowerDissipation::update_dJdv(), objectiveUniformityCellZone::update_dJdv(), objectiveForce::update_dSdbMultiplier(), objectiveForce::update_dxdbMultiplier(), objectiveMoment::update_dxdbMultiplier(), objectivePowerDissipation::update_gradDxDbMultiplier(), objectiveMoment::update_meanValues(), atmBoundaryLayerInletVelocityFvPatchVectorField::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), plenumPressureFvPatchScalarField::updateCoeffs(), supersonicFreestreamFvPatchVectorField::updateCoeffs(), translatingWallVelocityFvPatchVectorField::updateCoeffs(), turbulentDFSEMInletFvPatchVectorField::updateCoeffs(), JohnsonJacksonParticleThetaFvPatchScalarField::updateCoeffs(), outletMachNumberPressureFvPatchScalarField::updateCoeffs(), reconstructedDistanceFunction::updateContactAngle(), ATCstandard::updatePrimalBasedQuantities(), adjointkOmegaSST::updatePrimalRelatedFields(), adjointSpalartAllmaras::updatePrimalRelatedFields(), interfaceTrackingFvMesh::updateUs(), movingWallVelocityFvPatchVectorField::Uwall(), Implicit< CloudType >::velocityCorrection(), laminar::wallFriction(), KinematicParcel< ParcelType >::We(), KinematicSurfaceFilm< CloudType >::wetSplashInteraction(), while(), while(), while(), energySpectrum::write(), eulerianParticle::write(), propellerInfo::writeAxialWake(), eulerianParticle::writeDict(), DSMCParcel< ParcelType >::writeFields(), injectedParticle::writeFields(), solidParticle::writeFields(), KinematicParcel< ParcelType >::writeFields(), injectedParticle::writeObjects(), KinematicParcel< ParcelType >::writeObjects(), propellerInfo::writeSampleDiskSurface(), propellerInfo::writeWake(), propellerInfo::writeWakeFields(), nutkWallFunctionFvPatchScalarField::yPlus(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutUBlendedWallFunctionFvPatchScalarField::yPlus(), nutURoughWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), nutUTabulatedWallFunctionFvPatchScalarField::yPlus(), and nutUWallFunctionFvPatchScalarField::yPlus().
K
K = 0.5*magSqr(U)
Definition at line 75 of file pEqn.H.