OpenFOAM: applications/solvers/combustion/coldEngineFoam/createFieldRefs.H File Reference
createFieldRefs.H File Reference
Variables
const volScalarField & psi = thermo.psi()
const volScalarField & T = thermo.T()
Variable Documentation
psi
const volScalarField& psi = thermo.psi()
Definition at line 1 of file createFieldRefs.H.
Referenced by fvMatrix< Type >::addBoundaryDiag(), fvMatrix< Type >::addBoundarySource(), fvMatrix< Type >::addCmptAvBoundaryDiag(), solver::addOptimisationTypeSource(), PhaseLimitStabilization< Type >::addSup(), patchCellsSource::addSup(), SemiImplicitSource< Type >::addSup(), oversetFvPatchField< Type >::adjustPsi(), LduMatrix< Type, DType, LUType >::Amul(), lduMatrix::Amul(), fvMatrix< Type >::checkImplicit(), rotorDiskSource::constructGeometry(), Foam::MULES::correct(), Foam::MULES::correct(), Foam::MULES::correct(), Foam::MULES::correct(), Foam::MULES::correct(), cellCellStencil::correctBoundaryConditions(), Foam::CorrectPhi(), cellCellStencil::createField(), fvMatrix< Type >::createOrUpdateLduPrimitiveAssembly(), Foam::fvc::DDt(), Foam::fvc::DDt(), SpalartAllmarasIDDES< BasicTurbulenceModel >::dTilda(), Foam::MULES::explicitSolve(), Foam::MULES::explicitSolve(), Foam::MULES::explicitSolve(), Foam::MULES::explicitSolve(), Foam::MULES::explicitSolve(), LduMatrix< Type, DType, LUType >::faceH(), lduMatrix::faceH(), oversetFvPatchField< Type >::fringeFlux(), fvMatrix< Type >::fvMatrix(), LduMatrix< Type, DType, LUType >::H(), lduMatrix::H(), if(), if(), if(), if(), if(), cellCellStencil::interpolate(), propellerInfo::interpolate(), cellCellStencil::interpolate(), cellCellStencil::interpolate(), dynamicOversetFvMesh::interpolate(), staticOversetFvMesh::interpolate(), dynamicOversetFvMesh::interpolate(), staticOversetFvMesh::interpolate(), dynamicOversetFvMesh::interpolate(), staticOversetFvMesh::interpolate(), dynamicOversetFvMesh::interpolate(), staticOversetFvMesh::interpolate(), dynamicOversetFvMesh::interpolate(), staticOversetFvMesh::interpolate(), dynamicOversetFvMesh::interpolate(), staticOversetFvMesh::interpolate(), dynamicOversetFvMesh::interpolate(), staticOversetFvMesh::interpolate(), dynamicOversetFvMesh::interpolate(), staticOversetFvMesh::interpolate(), dynamicOversetFvMesh::interpolate(), staticOversetFvMesh::interpolate(), dynamicOversetFvMesh::interpolate(), staticOversetFvMesh::interpolate(), SpalartAllmarasDES< BasicTurbulenceModel >::lengthScaleLES(), Foam::MULES::limit(), Foam::MULES::limit(), Foam::MULES::limitCorr(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), fvMatrix< Type >::manipulateMatrix(), fvMatrix< Type >::mapContributions(), PhaseTransferPhaseSystem< BasePhaseSystem >::massTransfer(), PopulationBalancePhaseSystem< BasePhaseSystem >::massTransfer(), interpolation< Type >::New(), interpolation< Type >::New(), LduMatrix< Type, DType, LUType >::solver::normFactor(), lduMatrix::solver::normFactor(), faMatrix< Type >::operator+=(), fvMatrix< Type >::operator+=(), faMatrix< Type >::operator-=(), fvMatrix< Type >::operator-=(), Foam::operator<<(), SpalartAllmarasDES< BasicTurbulenceModel >::psi(), fixedTrim::read(), faMatrix< Type >::residual(), fvMatrix< Type >::residual(), LduMatrix< Type, DType, LUType >::residual(), lduMatrix::residual(), LduMatrix< Type, DType, LUType >::residual(), lduMatrix::residual(), DICSmoother::scalarSmooth(), DICGaussSeidelSmoother::scalarSmooth(), DILUSmoother::scalarSmooth(), DILUGaussSeidelSmoother::scalarSmooth(), FDICSmoother::scalarSmooth(), GaussSeidelSmoother::scalarSmooth(), nonBlockingGaussSeidelSmoother::scalarSmooth(), symGaussSeidelSmoother::scalarSmooth(), lduMatrix::solver::scalarSolve(), FPCG::scalarSolve(), PBiCGStab::scalarSolve(), PCG::scalarSolve(), PPCG::scalarSolveCG(), distributedDILUPreconditioner::sendGlobal(), fvMatrix< Type >::setBounAndInterCoeffs(), fvMatrix< Type >::setInterfaces(), fvMatrix< Type >::setValuesFromList(), faMatrix< Type >::setValuesFromList(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), nonBlockingGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), symGaussSeidelSmoother::smooth(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), DICSmoother::smooth(), DICGaussSeidelSmoother::smooth(), DILUSmoother::smooth(), DILUGaussSeidelSmoother::smooth(), FDICSmoother::smooth(), GaussSeidelSmoother::smooth(), nonBlockingGaussSeidelSmoother::smooth(), symGaussSeidelSmoother::smooth(), faMatrix< Type >::solve(), faMatrix< Type >::solve(), faMatrix< Type >::solve(), fvMatrix< Type >::fvSolver::solve(), DiagonalSolver< Type, DType, LUType >::solve(), PBiCCCG< Type, DType, LUType >::solve(), PBiCICG< Type, DType, LUType >::solve(), PCICG< Type, DType, LUType >::solve(), SmoothSolver< Type, DType, LUType >::solve(), Foam::solve(), diagonalSolver::solve(), GAMGSolver::solve(), PBiCG::solve(), smoothSolver::solve(), fvMatrix< Type >::solveCoupled(), oversetFvMeshBase::solveOverset(), fvMatrix< Type >::solveSegregated(), fvMatrix< Type >::solveSegregated(), targetCoeffTrim::thetag(), LduMatrix< Type, DType, LUType >::Tmul(), lduMatrix::Tmul(), oversetFvPatchField< Type >::updateInterfaceMatrix(), while(), and while().
T
const volScalarField& T = thermo.T()
Definition at line 2 of file createFieldRefs.H.
Referenced by opaqueDiffusive::a(), opaqueReflective::a(), transparent::a(), opaqueDiffusive::a(), opaqueReflective::a(), transparent::a(), SpecieMixture< MixtureType >::A(), thermo< Thermo, Type >::A(), thermo< Thermo, Type >::a(), boundaryRadiationProperties::absorptivity(), FIBase::accumulateIntegrand(), greyMeanAbsorptionEmission::aCont(), wideBandAbsorptionEmission::aCont(), MinMax< T >::add(), ATCstandard::addATC(), ATCUaGradU::addATC(), interRegionHeatTransferModel::addSup(), LehrMilliesMewes::addToBinaryBreakupRate(), Pstream::allGatherList(), UPstream::allGatherValues(), SpecieMixture< MixtureType >::alphah(), constAnIsoSolidTransport< Thermo >::alphah(), constIsoSolidTransport< Thermo >::alphah(), exponentialSolidTransport< Thermo >::alphah(), polynomialSolidTransport< Thermo, PolySize >::alphah(), tabulatedAnIsoSolidTransport< Thermo >::alphah(), tabulatedSolidTransport< Thermo >::alphah(), constTransport< Thermo >::alphah(), logPolynomialTransport< Thermo, PolySize >::alphah(), polynomialTransport< Thermo, PolySize >::alphah(), sutherlandTransport< Thermo >::alphah(), tabulatedTransport< Thermo >::alphah(), WLFTransport< Thermo >::alphah(), liquidProperties::alphah(), thermophysicalPropertiesSelector< ThermophysicalProperties >::alphah(), sensitivityBezierFI::assembleSensitivities(), sensitivityVolBSplinesFI::assembleSensitivities(), UPtrList< T >::at(), UPtrList< T >::at(), aC10H7CH3::B(), Ar::B(), bC10H7CH3::B(), C10H22::B(), C12H26::B(), C13H28::B(), C14H30::B(), C16H34::B(), C2H5OH::B(), C2H6::B(), C2H6O::B(), C3H6O::B(), C3H8::B(), C4H10O::B(), C6H14::B(), C6H6::B(), C7H16::B(), C7H8::B(), C8H10::B(), C8H18::B(), C9H20::B(), CH3OH::B(), CH4N2O::B(), H2O::B(), iC3H8O::B(), IC8H18::B(), IDEA::B(), liquid::B(), MB::B(), N2::B(), nC3H8O::B(), UILList< LListBase, T >::back(), UILList< LListBase, T >::back(), blackBodyEmission::blackBodyEmission(), SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), ReactingHeterogeneousParcel< ParcelType >::calcHeterogeneousReactions(), ObukhovLength::calcOL(), ReactingParcel< ParcelType >::calcPhaseChange(), ReactingMultiphaseParcel< ParcelType >::calcSurfaceReactions(), ThermoParcel< ParcelType >::calcSurfaceValues(), StandardChemistryModel< ReactionThermo, ThermoType >::calculate(), LiquidEvaporation< CloudType >::calculate(), LiquidEvaporationBoil< CloudType >::calculate(), LiquidEvapFuchsKnudsen< CloudType >::calculate(), SingleKineticRateDevolatilisation< CloudType >::calculate(), COxidationDiffusionLimitedRate< CloudType >::calculate(), COxidationHurtMitchell< CloudType >::calculate(), COxidationIntrinsicRate< CloudType >::calculate(), COxidationKineticDiffusionLimitedRate< CloudType >::calculate(), COxidationMurphyShaddix< CloudType >::calculate(), MUCSheterogeneousRate< CloudType >::calculate(), MassTransferPhaseSystem< BasePhaseSystem >::calculateL(), StandardChemistryModel< ReactionThermo, ThermoType >::calculateRR(), DynamicField< T, SizeMin >::capacity_bytes(), multiComponentMixture< ThermoType >::cellVolMixture(), IOstream::checkLabelSize(), IOstream::checkScalarSize(), SprayParcel< ParcelType >::chi(), PtrList< T >::clone(), absorptionCoeffs::coeffs(), Foam::ListListOps::combine(), Pstream::combineGather(), Foam::ListListOps::combineOffset(), Pstream::combineScatter(), incompressibleAdjointSolver::computeGradDxDbMultiplier(), refPtr< T >::constCast(), tmp< T >::constCast(), fixedTemperatureConstraint::constrain(), kL< BasicTurbulenceModel >::correct(), ArrheniusViscosity::correct(), function1Viscosity::correct(), waxSolventViscosity::correct(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), limitTemperature::correct(), particle< Type >::correctAfterInteractionListReferral(), particle< Type >::correctAfterParallelTransfer(), MassTransferPhaseSystem< BasePhaseSystem >::correctMassSources(), solidification::correctModel(), standardPhaseChange::correctModel(), waxSolventEvaporation::correctModel(), ReactingParcel< ParcelType >::correctSurfaceValues(), IsothermalPhaseModel< BasePhaseModel >::correctThermo(), PtrListDetail< T >::count(), liquidFilmThermo::Cp(), CompositionModel< CloudType >::Cp(), SpecieMixture< MixtureType >::Cp(), liquidFilmThermo::Cp(), hConstThermo< EquationOfState >::Cp(), hPolynomialThermo< EquationOfState, PolySize >::Cp(), hPowerThermo< EquationOfState >::Cp(), hTabulatedThermo< EquationOfState >::Cp(), janafThermo< EquationOfState >::Cp(), Cp(), thermo< Thermo, Type >::cp(), thermophysicalPropertiesSelector< ThermophysicalProperties >::Cp(), liquidMixtureProperties::Cp(), multiphaseInterSystem::Cp(), phaseModel::Cp(), heThermo< BasicThermo, MixtureType >::Cp(), heThermo< BasicThermo, MixtureType >::Cp(), PengRobinsonGas< Specie >::Cp(), aC10H7CH3::Cp(), Ar::Cp(), bC10H7CH3::Cp(), C10H22::Cp(), C12H26::Cp(), C13H28::Cp(), C14H30::Cp(), C16H34::Cp(), C2H5OH::Cp(), C2H6::Cp(), C2H6O::Cp(), C3H6O::Cp(), C3H8::Cp(), C4H10O::Cp(), C6H14::Cp(), C6H6::Cp(), C7H16::Cp(), C7H8::Cp(), C8H10::Cp(), C8H18::Cp(), C9H20::Cp(), CH3OH::Cp(), CH4N2O::Cp(), H2O::Cp(), iC3H8O::Cp(), IC8H18::Cp(), IDEA::Cp(), liquid::Cp(), MB::Cp(), N2::Cp(), nC3H8O::Cp(), thermo< Thermo, Type >::CpByCpv(), multiphaseInterSystem::CpByCpv(), phaseModel::CpByCpv(), heThermo< BasicThermo, MixtureType >::CpByCpv(), absoluteInternalEnergy< Thermo >::CpByCpv(), sensibleInternalEnergy< Thermo >::CpByCpv(), ReactingMultiphaseParcel< ParcelType >::CpEff(), ReactingHeterogeneousParcel< ParcelType >::CpEff(), aC10H7CH3::Cpg(), Ar::Cpg(), bC10H7CH3::Cpg(), C10H22::Cpg(), C12H26::Cpg(), C13H28::Cpg(), C14H30::Cpg(), C16H34::Cpg(), C2H5OH::Cpg(), C2H6::Cpg(), C2H6O::Cpg(), C3H6O::Cpg(), C3H8::Cpg(), C4H10O::Cpg(), C6H14::Cpg(), C6H6::Cpg(), C7H16::Cpg(), C7H8::Cpg(), C8H10::Cpg(), C8H18::Cpg(), C9H20::Cpg(), CH3OH::Cpg(), CH4N2O::Cpg(), H2O::Cpg(), iC3H8O::Cpg(), IC8H18::Cpg(), IDEA::Cpg(), liquid::Cpg(), MB::Cpg(), N2::Cpg(), nC3H8O::Cpg(), PengRobinsonGas< Specie >::CpMCv(), perfectFluid< Specie >::CpMCv(), thermophysicalPropertiesSelector< ThermophysicalProperties >::CpMCv(), thermo< Thermo, Type >::Cpv(), multiphaseInterSystem::Cpv(), phaseModel::Cpv(), heThermo< BasicThermo, MixtureType >::Cpv(), heThermo< BasicPsiThermo, MixtureType >::Cpv(), absoluteEnthalpy< Thermo >::Cpv(), absoluteInternalEnergy< Thermo >::Cpv(), sensibleEnthalpy< Thermo >::Cpv(), sensibleInternalEnergy< Thermo >::Cpv(), refPtr< T >::cref(), tmp< T >::cref(), refPtr< T >::cref(), tmp< T >::cref(), triSurfaceTools::curvatures(), SpecieMixture< MixtureType >::Cv(), eConstThermo< EquationOfState >::Cv(), Cv(), thermo< Thermo, Type >::cv(), thermophysicalPropertiesSelector< ThermophysicalProperties >::Cv(), multiphaseInterSystem::Cv(), phaseModel::Cv(), heThermo< BasicThermo, MixtureType >::Cv(), PengRobinsonGas< Specie >::Cv(), liquidFilmThermo::D(), liquidMixtureProperties::D(), InterfaceCompositionModel< Thermo, OtherThermo >::D(), aC10H7CH3::D(), Ar::D(), bC10H7CH3::D(), C10H22::D(), C12H26::D(), C13H28::D(), C14H30::D(), C16H34::D(), C2H5OH::D(), C2H6::D(), C2H6O::D(), C3H6O::D(), C3H8::D(), C4H10O::D(), C6H14::D(), C6H6::D(), C7H16::D(), C7H8::D(), C8H10::D(), C8H18::D(), C9H20::D(), CH3OH::D(), CH4N2O::D(), H2O::D(), iC3H8O::D(), IC8H18::D(), IDEA::D(), liquid::D(), MB::D(), N2::D(), nC3H8O::D(), aC10H7CH3::D(), Ar::D(), bC10H7CH3::D(), C10H22::D(), C12H26::D(), C13H28::D(), C14H30::D(), C16H34::D(), C2H5OH::D(), C2H6::D(), C2H6O::D(), C3H6O::D(), C3H8::D(), C4H10O::D(), C6H14::D(), C6H6::D(), C7H16::D(), C7H8::D(), C8H10::D(), C8H18::D(), C9H20::D(), CH3OH::D(), CH4N2O::D(), H2O::D(), iC3H8O::D(), IC8H18::D(), IDEA::D(), liquid::D(), MB::D(), N2::D(), nC3H8O::D(), hPolynomialThermo< EquationOfState, PolySize >::dCpdT(), hTabulatedThermo< EquationOfState >::dCpdT(), janafThermo< EquationOfState >::dCpdT(), thermo< Thermo, Type >::dcpdT(), UList< T >::deepCopy(), blackBodyEmission::deltaLambdaT(), StandardChemistryModel< ReactionThermo, ThermoType >::derivatives(), TDACChemistryModel< ReactionThermo, ThermoType >::derivatives(), TDACChemistryModel< CompType, ThermoType >::derivatives(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::derivatives(), InterfaceCompositionModel< Thermo, OtherThermo >::Dfrom(), LiquidEvapFuchsKnudsen< CloudType >::dh(), LiquidEvaporation< CloudType >::dh(), LiquidEvaporationBoil< CloudType >::dh(), boundaryRadiationProperties::diffReflectivity(), Foam::dimensionedConstant(), adjointkOmegaSST::divDevReff(), adjointLaminar::divDevReff(), adjointSpalartAllmaras::divDevReff(), momentumError::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::DivDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), kineticTheoryModel::divDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), thermo< Thermo, Type >::dKcdTbyKc(), InterfaceCompositionModel< Thermo, OtherThermo >::Dto(), opaqueDiffusive::e(), opaqueReflective::e(), transparent::e(), opaqueDiffusive::e(), opaqueReflective::e(), transparent::e(), PengRobinsonGas< Specie >::E(), eConstThermo< EquationOfState >::Ea(), Ea(), thermo< Thermo, Type >::ea(), thermophysicalPropertiesSelector< ThermophysicalProperties >::Ea(), blackBodyEmission::EbDeltaLambdaT(), blackBodyEmission::EblambdaT(), Foam::eigenValues(), Foam::eigenValues(), Foam::eigenValues(), Foam::eigenVector(), Foam::eigenVector(), Foam::eigenVector(), Foam::eigenVector(), Foam::eigenVectors(), Foam::eigenVectors(), Foam::eigenVectors(), Foam::eigenVectors(), Foam::eigenVectors(), Foam::eigenVectors(), Foam::eigenVectors(), boundaryRadiationProperties::emissivity(), HashPtrTable< T, Key, Hash >::emplace(), PtrDynList< T, SizeMin >::emplace(), PtrList< T >::emplace(), DynamicList< T, SizeMin >::emplace_back(), List< T >::emplace_back(), PtrDynList< T, SizeMin >::emplace_back(), DynamicField< T, SizeMin >::emplace_back(), PtrList< T >::emplace_set(), effectivenessTable::energyDensity(), Dictionary< T >::erase(), HashPtrTable< T, Key, Hash >::erase(), SpecieMixture< MixtureType >::Es(), eConstThermo< EquationOfState >::Es(), Es(), thermo< Thermo, Type >::es(), thermophysicalPropertiesSelector< ThermophysicalProperties >::Es(), comfort::execute(), APIdiffCoefFunc::f(), APIdiffCoefFunc::f(), NSRDSfunc0::f(), NSRDSfunc1::f(), NSRDSfunc14::f(), NSRDSfunc2::f(), NSRDSfunc3::f(), NSRDSfunc4::f(), NSRDSfunc5::f(), NSRDSfunc6::f(), NSRDSfunc7::f(), boundaryRadiationProperties::faceAbsorptivity(), boundaryRadiationProperties::faceDiffReflectivity(), boundaryRadiationProperties::faceEmissivity(), boundaryRadiationProperties::faceSpecReflectivity(), boundaryRadiationProperties::faceTransmissivity(), IndirectListBase< T, Addr >::find(), FixedList< T, N >::find(), UList< T >::find(), adjointkOmegaSST::FISensitivityTerm(), adjointSpalartAllmaras::FISensitivityTerm(), for(), forAll(), forAll(), rigidBodyModel::forwardDynamics(), UILList< LListBase, T >::front(), UILList< LListBase, T >::front(), fvDOM::fvDOM(), fvDOM::fvDOM(), SpecieMixture< MixtureType >::G(), thermo< Thermo, Type >::G(), thermo< Thermo, Type >::g(), thermo< Thermo, Type >::gamma(), phaseModel::gamma(), heThermo< BasicThermo, MixtureType >::gamma(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::gasHs(), Pstream::gather(), meshRefinement::gAverage(), UILList< LListBase, T >::iterator::get(), UILList< LListBase, T >::const_iterator::get(), UILList< LListBase, T >::reverse_iterator::get(), UILList< LListBase, T >::const_reverse_iterator::get(), entry::get(), argList::get(), dictionary::get(), argList::get(), entry::getCheck(), dictionary::getCheck(), argList::getCheck(), dictionary::getCheckOrAdd(), dictionary::getCheckOrDefault(), argList::getCheckOrDefault(), dictionary::getCompat(), Foam::getLazyPair(), dictionary::getOrAdd(), Foam::getOrAdd(), dictionary::getOrDefault(), dictionary::getOrDefaultCompat(), fvExprDriver::getTopoSet(), eConstThermo< EquationOfState >::Gstd(), hConstThermo< EquationOfState >::Gstd(), hPolynomialThermo< EquationOfState, PolySize >::Gstd(), hPowerThermo< EquationOfState >::Gstd(), hTabulatedThermo< EquationOfState >::Gstd(), janafThermo< EquationOfState >::Gstd(), CompositionModel< CloudType >::H(), icoTabulated< Specie >::H(), PengRobinsonGas< Specie >::H(), aC10H7CH3::h(), Ar::h(), bC10H7CH3::h(), C10H22::h(), C12H26::h(), C13H28::h(), C14H30::h(), C16H34::h(), C2H5OH::h(), C2H6::h(), C2H6O::h(), C3H6O::h(), C3H8::h(), C4H10O::h(), C6H14::h(), C6H6::h(), C7H16::h(), C7H8::h(), C8H10::h(), C8H18::h(), C9H20::h(), CH3OH::h(), CH4N2O::h(), H2O::h(), iC3H8O::h(), IC8H18::h(), IDEA::h(), liquid::h(), MB::h(), N2::h(), nC3H8O::h(), SpecieMixture< MixtureType >::Ha(), hConstThermo< EquationOfState >::Ha(), hPolynomialThermo< EquationOfState, PolySize >::Ha(), hPowerThermo< EquationOfState >::Ha(), hTabulatedThermo< EquationOfState >::Ha(), janafThermo< EquationOfState >::Ha(), Ha(), thermo< Thermo, Type >::ha(), liquidProperties::Ha(), thermophysicalPropertiesSelector< ThermophysicalProperties >::Ha(), HashPtrTable< IOobject >::HashPtrTable(), SpecieMixture< MixtureType >::HE(), thermo< Thermo, Type >::HE(), thermo< Thermo, Type >::he(), absoluteEnthalpy< Thermo >::HE(), absoluteInternalEnergy< Thermo >::HE(), sensibleEnthalpy< Thermo >::HE(), sensibleInternalEnergy< Thermo >::HE(), MassTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), liquidFilmThermo::hl(), liquidMixtureProperties::hl(), aC10H7CH3::hl(), Ar::hl(), bC10H7CH3::hl(), C10H22::hl(), C12H26::hl(), C13H28::hl(), C14H30::hl(), C16H34::hl(), C2H5OH::hl(), C2H6::hl(), C2H6O::hl(), C3H6O::hl(), C3H8::hl(), C4H10O::hl(), C6H14::hl(), C6H6::hl(), C7H16::hl(), C7H8::hl(), C8H10::hl(), C8H18::hl(), C9H20::hl(), CH3OH::hl(), CH4N2O::hl(), H2O::hl(), iC3H8O::hl(), IC8H18::hl(), IDEA::hl(), liquid::hl(), MB::hl(), N2::hl(), nC3H8O::hl(), CompositionModel< CloudType >::Hs(), SpecieMixture< MixtureType >::Hs(), hConstThermo< EquationOfState >::Hs(), hPolynomialThermo< EquationOfState, PolySize >::Hs(), hPowerThermo< EquationOfState >::Hs(), hTabulatedThermo< EquationOfState >::Hs(), janafThermo< EquationOfState >::Hs(), Hs(), thermo< Thermo, Type >::hs(), liquidProperties::Hs(), thermophysicalPropertiesSelector< ThermophysicalProperties >::Hs(), solidProperties::Hs(), ReactingMultiphaseParcel< ParcelType >::HsEff(), ReactingHeterogeneousParcel< ParcelType >::HsEff(), fixedReferenceTemperature::htc(), localReferenceTemperature::htc(), if(), cyclicAMIPolyPatch::interpolate(), cellCellStencil::interpolate(), Dual< Type >::interpolateGrad(), vectorTensorTransform::invTransformPosition(), StandardChemistryModel< ReactionThermo, ThermoType >::jacobian(), TDACChemistryModel< ReactionThermo, ThermoType >::jacobian(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::jacobian(), TDACChemistryModel< ReactionThermo, ThermoType >::jacobian(), thermo< Thermo, Type >::K(), liquidFilmThermo::kappa(), SpecieMixture< MixtureType >::kappa(), liquidFilmThermo::kappa(), exponentialSolidTransport< Thermo >::kappa(), exponentialSolidTransport< Thermo >::Kappa(), polynomialSolidTransport< Thermo, PolySize >::kappa(), polynomialSolidTransport< Thermo, PolySize >::Kappa(), tabulatedAnIsoSolidTransport< Thermo >::kappa(), tabulatedAnIsoSolidTransport< Thermo >::Kappa(), tabulatedSolidTransport< Thermo >::kappa(), tabulatedSolidTransport< Thermo >::Kappa(), constTransport< Thermo >::kappa(), logPolynomialTransport< Thermo, PolySize >::kappa(), polynomialTransport< Thermo, PolySize >::kappa(), sutherlandTransport< Thermo >::kappa(), tabulatedTransport< Thermo >::kappa(), WLFTransport< Thermo >::kappa(), liquidMixtureProperties::kappa(), aC10H7CH3::kappa(), Ar::kappa(), bC10H7CH3::kappa(), C10H22::kappa(), C12H26::kappa(), C13H28::kappa(), C14H30::kappa(), C16H34::kappa(), C2H5OH::kappa(), C2H6::kappa(), C2H6O::kappa(), C3H6O::kappa(), C3H8::kappa(), C4H10O::kappa(), C6H14::kappa(), C6H6::kappa(), C7H16::kappa(), C7H8::kappa(), C8H10::kappa(), C8H18::kappa(), C9H20::kappa(), CH3OH::kappa(), CH4N2O::kappa(), H2O::kappa(), iC3H8O::kappa(), IC8H18::kappa(), IDEA::kappa(), liquid::kappa(), MB::kappa(), N2::kappa(), nC3H8O::kappa(), thermophysicalPropertiesSelector< ThermophysicalProperties >::kappa(), aC10H7CH3::kappag(), Ar::kappag(), bC10H7CH3::kappag(), C10H22::kappag(), C12H26::kappag(), C13H28::kappag(), C14H30::kappag(), C16H34::kappag(), C2H5OH::kappag(), C2H6::kappag(), C2H6O::kappag(), C3H6O::kappag(), C3H8::kappag(), C4H10O::kappag(), C6H14::kappag(), C6H6::kappag(), C7H16::kappag(), C7H8::kappag(), C8H10::kappag(), C8H18::kappag(), C9H20::kappag(), CH3OH::kappag(), CH4N2O::kappag(), H2O::kappag(), iC3H8O::kappag(), IC8H18::kappag(), IDEA::kappag(), liquid::kappag(), MB::kappag(), N2::kappag(), nC3H8O::kappag(), thermo< Thermo, Type >::Kc(), diffusionGasEvaporation< Thermo, OtherThermo >::Kexp(), interfaceHeatResistance< Thermo, OtherThermo >::Kexp(), interfaceOxideRate< Thermo, OtherThermo >::Kexp(), kineticGasEvaporation< Thermo, OtherThermo >::Kexp(), IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kf(), NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kf(), ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kf(), thermo< Thermo, Type >::Kn(), thermo< Thermo, Type >::Kp(), NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kr(), ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kr(), NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kr(), ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kr(), thermo< Thermo, Type >::Kx(), CompositionModel< CloudType >::L(), ReactingMultiphaseParcel< ParcelType >::LEff(), ReactingHeterogeneousParcel< ParcelType >::LEff(), eConstThermo< EquationOfState >::limit(), hConstThermo< EquationOfState >::limit(), hPowerThermo< EquationOfState >::limit(), hTabulatedThermo< EquationOfState >::limit(), janafThermo< EquationOfState >::limit(), liquidProperties::limit(), thermophysicalProperties::limit(), thermophysicalPropertiesSelector< ThermophysicalProperties >::limit(), hPolynomialThermo< EquationOfState, PolySize >::limit(), List< T >::List(), List< T >::List(), UPstream::listGatherValues(), UPstream::listScatterValues(), LList< LListBase, T >::LList(), LList< LListBase, T >::LList(), Antoine::lnPSat(), AntoineExtended::lnPSat(), ArdenBuck::lnPSat(), constantSaturationConditions::lnPSat(), dynamicRefineFvMesh::mapNewInternalFaces(), Foam::minMaxMag(), liquidFilmThermo::mu(), SpecieMixture< MixtureType >::mu(), liquidFilmThermo::mu(), logPolynomialTransport< Thermo, PolySize >::mu(), polynomialTransport< Thermo, PolySize >::mu(), sutherlandTransport< Thermo >::mu(), tabulatedTransport< Thermo >::mu(), WLFTransport< Thermo >::mu(), liquidMixtureProperties::mu(), aC10H7CH3::mu(), Ar::mu(), bC10H7CH3::mu(), C10H22::mu(), C12H26::mu(), C13H28::mu(), C14H30::mu(), C16H34::mu(), C2H5OH::mu(), C2H6::mu(), C2H6O::mu(), C3H6O::mu(), C3H8::mu(), C4H10O::mu(), C6H14::mu(), C6H6::mu(), C7H16::mu(), C7H8::mu(), C8H10::mu(), C8H18::mu(), C9H20::mu(), CH3OH::mu(), CH4N2O::mu(), H2O::mu(), iC3H8O::mu(), IC8H18::mu(), IDEA::mu(), liquid::mu(), MB::mu(), N2::mu(), nC3H8O::mu(), thermophysicalPropertiesSelector< ThermophysicalProperties >::mu(), aC10H7CH3::mug(), Ar::mug(), bC10H7CH3::mug(), C10H22::mug(), C12H26::mug(), C13H28::mug(), C14H30::mug(), C16H34::mug(), C2H5OH::mug(), C2H6::mug(), C2H6O::mug(), C3H6O::mug(), C3H8::mug(), C4H10O::mug(), C6H14::mug(), C6H6::mug(), C7H16::mug(), C7H8::mug(), C8H10::mug(), C8H18::mug(), C9H20::mug(), CH3OH::mug(), CH4N2O::mug(), H2O::mug(), iC3H8O::mug(), IC8H18::mug(), IDEA::mug(), liquid::mug(), MB::mug(), N2::mug(), nC3H8O::mug(), autoPtr< T >::New(), refPtr< T >::New(), tmp< T >::New(), radiationModel::New(), radiationModel::New(), tmp< T >::NewImmovable(), Foam::NullObjectPtr(), Foam::NullObjectRef(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), StandardChemistryModel< CompType, ThermoType >::omega(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), StandardChemistryModel< ReactionThermo, ThermoType >::omega(), StandardChemistryModel< ReactionThermo, ThermoType >::omegaI(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omegaI(), Foam::operator&(), FixedList< T, N >::hasher::operator()(), UPtrList< T >::less::operator()(), UPtrList< T >::greater::operator()(), solidArrheniusReactionRate::operator()(), solidIsothermalReactionRate::operator()(), ArrheniusReactionRate::operator()(), ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::operator()(), FallOffReactionRate< ReactionRate, FallOffFunction >::operator()(), JanevReactionRate::operator()(), LandauTellerReactionRate::operator()(), LangmuirHinshelwoodReactionRate::operator()(), powerSeriesReactionRate::operator()(), thirdBodyArrheniusReactionRate::operator()(), SRIFallOffFunction::operator()(), TroeFallOffFunction::operator()(), Hash< T >::operator()(), UList< T >::hasher::operator()(), mapDistribute::transform::operator()(), appendEqOp< T >::operator()(), uniqueEqOp< T >::operator()(), minMaxMagEqOp< T >::operator()(), isNotEqOp< T >::operator()(), autoPtr< T >::operator*(), autoPtr< T >::operator->(), FixedList< T, N >::operator<(), CircularBuffer< T >::operator=(), List< T >::operator=(), UList< T >::operator=(), List< T >::operator=(), LList< LListBase, T >::operator=(), refPtr< T >::operator=(), List< T >::operator=(), UList< T >::operator=(), tmp< T >::operator=(), List< T >::operator=(), List< CloudFunctionObject< CloudType > * >::operator=(), List< T >::operator=(), List< CloudFunctionObject< CloudType > * >::operator=(), List< T >::operator=(), LList< LListBase, T >::operator=(), FixedList< T, N >::operator==(), LabelledItem< T >::operator==(), UList< T >::operator==(), PtrDictionary< T >::operator[](), PtrListDictionary< T >::operator[](), PtrDictionary< T >::operator[](), PtrListDictionary< T >::operator[](), Foam::outputIndent(), P1::P1(), P1::P1(), multiComponentMixture< ThermoType >::patchFaceVolMixture(), DynamicList< label >::pop_back(), ILList< LListBase, T >::pop_front(), LPtrList< LListBase, T >::pop_front(), Antoine::pSat(), AntoineExtended::pSat(), ArdenBuck::pSat(), constantSaturationConditions::pSat(), Antoine::pSatPrime(), AntoineExtended::pSatPrime(), ArdenBuck::pSatPrime(), constantSaturationConditions::pSatPrime(), PengRobinsonGas< Specie >::psi(), perfectFluid< Specie >::psi(), perfectGas< Specie >::psi(), rPolynomial< Specie >::psi(), thermophysicalPropertiesSelector< ThermophysicalProperties >::psi(), PtrList< CloudFunctionObject< CloudType > >::PtrList(), PtrList< CloudFunctionObject< CloudType > >::PtrList(), PtrList< T >::PtrList(), PtrListDictionary< phaseModel >::PtrListDictionary(), DynamicList< T, SizeMin >::push_back(), DynamicList< T, SizeMin >::push_back(), DynamicField< T, SizeMin >::push_back(), DynamicList< T, SizeMin >::push_back(), DynamicList< T, SizeMin >::push_back(), liquidFilmThermo::pv(), liquidMixtureProperties::pv(), aC10H7CH3::pv(), Ar::pv(), bC10H7CH3::pv(), C10H22::pv(), C12H26::pv(), C13H28::pv(), C14H30::pv(), C16H34::pv(), C2H5OH::pv(), C2H6::pv(), C2H6O::pv(), C3H6O::pv(), C3H8::pv(), C4H10O::pv(), C6H14::pv(), C6H6::pv(), C7H16::pv(), C7H8::pv(), C8H10::pv(), C8H18::pv(), C9H20::pv(), CH3OH::pv(), CH4N2O::pv(), H2O::pv(), iC3H8O::pv(), IC8H18::pv(), IDEA::pv(), liquid::pv(), MB::pv(), N2::pv(), nC3H8O::pv(), liquidMixtureProperties::pvInvert(), liquidProperties::pvInvert(), heatTransferCoeffModel::q(), multiphaseInterHtcModel::q(), reactingEulerHtcModel::q(), opaqueReflective::rDiff(), opaqueReflective::rDiff(), Foam::blockMeshTools::read(), Foam::readBlock(), ThermoParcel< ParcelType >::readFields(), Foam::ReadHex(), PtrList< T >::readIstream(), LList< LListBase, T >::readList(), List< T >::readList(), UList< T >::readList(), ThermoParcel< ParcelType >::readObjects(), DAC< CompType, ThermoType >::reduceMechanism(), DRG< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), EFA< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), refPtr< Field< Type > >::ref(), autoPtr< T >::release(), DynamicList< T, SizeMin >::remove(), DictionaryBase< IDLListType, T >::remove(), UILList< LListBase, T >::remove(), UILList< LListBase, T >::remove(), LList< LListBase, T >::link::remove(), UILList< LListBase, T >::removeHead(), UPtrList< T >::reorder(), List< T >::resize(), PtrListDetail< T >::resize(), Foam::returnReduce(), cyclicAMIPolyPatch::reverseTransformDirection(), cyclicAMIPolyPatch::reverseTransformPosition(), IndirectListBase< T, Addr >::rfind(), FixedList< T, N >::rfind(), UList< T >::rfind(), liquidFilmThermo::rho(), SpecieMixture< MixtureType >::rho(), liquidFilmThermo::rho(), liquidMixtureProperties::rho(), CompositionModel< CloudType >::rho(), Boussinesq< Specie >::rho(), icoPolynomial< Specie, PolySize >::rho(), icoTabulated< Specie >::rho(), incompressiblePerfectGas< Specie >::rho(), PengRobinsonGas< Specie >::rho(), perfectFluid< Specie >::rho(), perfectGas< Specie >::rho(), rPolynomial< Specie >::rho(), aC10H7CH3::rho(), Ar::rho(), bC10H7CH3::rho(), C10H22::rho(), C12H26::rho(), C13H28::rho(), C14H30::rho(), C16H34::rho(), C2H5OH::rho(), C2H6::rho(), C2H6O::rho(), C3H6O::rho(), C3H8::rho(), C4H10O::rho(), C6H14::rho(), C6H6::rho(), C7H16::rho(), C7H8::rho(), C8H10::rho(), C8H18::rho(), C9H20::rho(), CH3OH::rho(), CH4N2O::rho(), H2O::rho(), iC3H8O::rho(), IC8H18::rho(), IDEA::rho(), liquid::rho(), MB::rho(), N2::rho(), nC3H8O::rho(), thermophysicalPropertiesSelector< ThermophysicalProperties >::rho(), heThermo< BasicPsiThermo, MixtureType >::rhoEoS(), heThermo< BasicThermo, MixtureType >::rhoEoS(), solidChemistryModel< CompType, SolidThermo >::RRsHs(), opaqueReflective::rSpec(), opaqueReflective::rSpec(), SpecieMixture< MixtureType >::S(), adiabaticPerfectFluid< Specie >::S(), linear< Type >::S(), PengRobinsonGas< Specie >::S(), eConstThermo< EquationOfState >::S(), hConstThermo< EquationOfState >::S(), hPolynomialThermo< EquationOfState, PolySize >::S(), hPowerThermo< EquationOfState >::S(), hTabulatedThermo< EquationOfState >::S(), janafThermo< EquationOfState >::S(), thermo< Thermo, Type >::s(), thermophysicalPropertiesSelector< ThermophysicalProperties >::S(), Pstream::scatter(), HashPtrTable< T, Key, Hash >::set(), PtrListDictionary< phaseModel >::set(), PtrListDictionary< T >::set(), UPtrList< T >::set(), PtrListDetail< CloudFunctionObject< CloudType > >::setNull(), ThermoCloud< Foam::DSMCCloud >::setParcelThermoProperties(), liquidFilmThermo::sigma(), temperatureDependent::sigma(), liquidFilmThermo::sigma(), liquidMixtureProperties::sigma(), aC10H7CH3::sigma(), Ar::sigma(), bC10H7CH3::sigma(), C10H22::sigma(), C12H26::sigma(), C13H28::sigma(), C14H30::sigma(), C16H34::sigma(), C2H5OH::sigma(), C2H6::sigma(), C2H6O::sigma(), C3H6O::sigma(), C3H8::sigma(), C4H10O::sigma(), C6H14::sigma(), C6H6::sigma(), C7H16::sigma(), C7H8::sigma(), C8H10::sigma(), C8H18::sigma(), C9H20::sigma(), CH3OH::sigma(), CH4N2O::sigma(), H2O::sigma(), iC3H8O::sigma(), IC8H18::sigma(), IDEA::sigma(), liquid::sigma(), MB::sigma(), N2::sigma(), nC3H8O::sigma(), FixedList< T, N >::size_bytes(), solarLoad::solarLoad(), solarLoad::solarLoad(), elasticityMotionSolver::solve(), adjointMeshMovementSolver::solve(), StandardChemistryModel< ReactionThermo, ThermoType >::solve(), TDACChemistryModel< ReactionThermo, ThermoType >::solve(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), EulerImplicit< ChemistryModel >::solve(), ode< ChemistryModel >::solve(), Foam::sort(), UPtrList< T >::sortOrder(), boundaryRadiationProperties::specReflectivity(), UPtrList< T >::squeezeNull(), radiationModel::ST(), radiationModel::ST(), radiationModel::ST(), Foam::ListListOps::subSizes(), autoPtr< T >::swap(), refPtr< T >::swap(), tmp< T >::swap(), Foam::T(), Foam::T(), Foam::T(), StandardChemistryModel< ReactionThermo, ThermoType >::tc(), thermo< Thermo, Type >::TEa(), thermo< Thermo, Type >::TEs(), meshRefinement::testSyncBoundaryFaceList(), thermo< Thermo, Type >::THa(), heThermo< BasicThermo, MixtureType >::THE(), heThermo< BasicThermo, MixtureType >::THE(), ThermoCloud< CloudType >::ThermoCloud(), ThermoCloud< CloudType >::ThermoCloud(), dynamicContactAngleForce::theta(), perturbedTemperatureDependentContactAngleForce::theta(), temperatureDependentContactAngleForce::theta(), thermo< Thermo, Type >::THs(), particle< Type >::trackToMovingTri(), particle< Type >::trackToStationaryTri(), sixDoFRigidBodyMotion::transform(), FaceCellWave< Type, TrackingData >::transform(), SDA::transformation(), Foam::transformList(), Foam::transformList(), cyclicPolyPatch::transformPosition(), cyclicAMIPolyPatch::transformPosition(), DSMCParcel< ParcelType >::transformProperties(), CollidingParcel< ParcelType >::transformProperties(), KinematicParcel< ParcelType >::transformProperties(), molecule::transformProperties(), solidParticle::transformProperties(), boundaryRadiationProperties::transmissivity(), refPtr< T >::typeName(), tmp< T >::typeName(), IndirectListBase< T, Addr >::uniform(), fixedMultiPhaseHeatFluxFvPatchScalarField::updateCoeffs(), humidityTemperatureCoupledMixedFvPatchScalarField::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), ReactingParcel< ParcelType >::updatedDeltaVolume(), ReactingMultiphaseParcel< ParcelType >::updatedDeltaVolume(), fvExprDriver::updateSet(), jouleHeatingSource::updateSigma(), rigidBodyModel::v(), viewFactor::viewFactor(), viewFactor::viewFactor(), waveMakerPointPatchVectorField::waveLength(), irregularMultiDirectional::waveLength(), StokesI::waveLength(), HashPtrTable< T, Key, Hash >::write(), PtrListDetail< T >::write(), ThermoParcel< ParcelType >::writeFields(), CircularBuffer< T >::writeList(), IndirectListBase< T, Addr >::writeList(), LList< LListBase, T >::writeList(), UILList< LListBase, T >::writeList(), ThermoParcel< ParcelType >::writeObjects(), PengRobinsonGas< Specie >::Z(), boundaryRadiationProperties::zoneTransmissivity(), ILList< ParticleType >::~ILList(), and TDACChemistryModel< CompType, ThermoType >::~TDACChemistryModel().