OpenFOAM: applications/solvers/combustion/chemFoam/readControls.H File Reference
readControls.H File Reference
Functions
runTime controlDict ().readEntry("adjustTimeStep"
Variables
runTime adjustTimeStep
runTime maxDeltaT
Function Documentation
controlDict()
runTime controlDict ()
Referenced by Foam::listSwitches(), masterCoarsestGAMGProcAgglomeration::masterCoarsestGAMGProcAgglomeration(), functionObjectList::New(), GAMGAgglomeration::New(), GAMGAgglomeration::New(), GAMGAgglomeration::New(), GAMGProcAgglomeration::New(), and Foam::debug::switchSet().
Variable Documentation
adjustTimeStep
runTime adjustTimeStep
Definition at line 1 of file readControls.H.
maxDeltaT
runTime maxDeltaT
Definition at line 3 of file readControls.H.