OpenFOAM: applications/solvers/combustion/reactingFoam/pcEqn.H File Reference
pcEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
volScalarField rAtU (1.0/(1.0/rAU - UEqn.H1()))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
if (pimple.nCorrPISO()<=1)
if (pimple.transonic())
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
volScalarField rhorAtU ("rhorAtU", rho *rAtU)
constrainPressure (p, rho, U, phiHbyA, rhorAtU, MRF)
while (pimple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
if (pressureControl.limit(p))
if (thermo.dpdt())
Variables
rho = thermo.rho()
else
phiHbyA = fvc::interpolate(rho*(rAtU - rAU))*fvc::snGrad(p)*mesh.magSf()
HbyA = (rAU - rAtU)*fvc::grad(p)
U = HbyA - rAtU*fvc::grad(p)
K = 0.5*magSqr(U)
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
rAtU()
volScalarField rAtU (1.0/ 1.0/rAU - UEqn.H1())
Referenced by if(), if(), and simple::mainIter().
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
if() [1/4]
if (pimple.nCorrPISO()<= 1)
Definition at line 7 of file pcEqn.H.
References tUEqn().
if() [2/4]
if (pimple. transonic())
Definition at line 12 of file pcEqn.H.
References fvOptions, HbyA, mesh, MRF, p, phi, phic(), phid(), pimple, psi, rAtU(), rAU, rho, rhorAtU(), and U.
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
rhorAtU()
volScalarField rhorAtU ("rhorAtU" , rho * rAtU)
Referenced by if(), if(), while(), and while().
constrainPressure()
constrainPressure (p , rho , U , phiHbyA , rhorAtU , MRF)
while()
while (pimple. correctNonOrthogonal())
Definition at line 81 of file pcEqn.H.
References fvOptions, mesh, p, phi, phiHbyA, pimple, psi, rho, and rhorAtU().
relax()
p relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
if() [3/4]
if (pressureControl. limitp)
Definition at line 112 of file pcEqn.H.
References p, and rho.
if() [4/4]
if (thermo. dpdt())
Definition at line 118 of file pcEqn.H.
References dpdt, and p.
Variable Documentation
rho
rho = thermo.rho()
Definition at line 1 of file pcEqn.H.
Referenced by if(), if(), if(), if(), if(), if(), while(), and while().
else
else
Initial value:
{
    surfaceScalarField phiHbyA
    (
        "phiHbyA",
        (
            fvc::flux(rho*HbyA)
          + MRF.zeroFilter(fvc::interpolate(rho*rAU)*fvc::ddtCorr(rho, U, phi))
        )
    )
Definition at line 60 of file pcEqn.H.
phiHbyA
phiHbyA = fvc::interpolate(rho*(rAtU - rAU))*fvc::snGrad(p)*mesh.magSf()
Definition at line 73 of file pcEqn.H.
Referenced by Foam::constrainPressure(), Foam::constrainPressure(), Foam::constrainPressure(), Foam::constrainPressure(), incompressiblePrimalSolver::correctBoundaryConditions(), for(), if(), if(), if(), if(), if(), if(), if(), if(), if(), simple::mainIter(), while(), while(), while(), and while().
HbyA
HbyA = (rAU - rAtU)*fvc::grad(p)
Definition at line 74 of file pcEqn.H.
Referenced by incompressiblePrimalSolver::correctBoundaryConditions(), for(), if(), if(), if(), if(), simple::mainIter(), relax(), while(), and while().
U
U = HbyA - rAtU*fvc::grad(p)
Definition at line 107 of file pcEqn.H.
Referenced by if(), and if().
K
K = 0.5*magSqr(U)
Definition at line 110 of file pcEqn.H.