OpenFOAM: applications/solvers/combustion/fireFoam/UEqn.H File Reference
UEqn.H File Reference
Functions
MRF correctBoundaryVelocity (U)
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U)==parcels.SU(U)+fvOptions(rho, U))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple.momentumPredictor())
Function Documentation
correctBoundaryVelocity()
MRF correctBoundaryVelocity (U)
UEqn()
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U) = =parcels.SU(U)+fvOptions(rho, U))
relax()
E2Eqn relax ()
Initial value:
{
        U2Eqn =
        (
            phase2.UEqn()
         ==
           *momentumTransfer[phase2.name()]
          + fvOptions(alpha2, rho2, U2)
        )
Referenced by iterativeGaussGrad< Type >::calcGrad(), relaxedSnGrad< Type >::correction(), relaxedNonOrthoGaussLaplacianScheme< Type, GType >::fvmLaplacian(), faMatrix< Type >::relax(), fvMatrix< Type >::relax(), GeometricField< Type, PatchField, GeoMesh >::relax(), KinematicCloud< CloudType >::relaxSources(), ThermoCloud< CloudType >::relaxSources(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), and porousBafflePressureFvPatchField::updateCoeffs().
constrain()
fvOptions constrain (UEqn)
if()
if (pimple. momentumPredictor())
Definition at line 17 of file UEqn.H.
References fvOptions, ghf, mesh, p_rgh, rho, solve(), U, and UEqn.