OpenFOAM: applications/solvers/combustion/reactingFoam/setRDeltaT.H File Reference
setRDeltaT.H File Reference
Functions
scalar maxCo (pimpleDict.get< scalar >("maxCo"))
scalar maxDeltaT (pimpleDict.getOrDefault< scalar >("maxDeltaT", GREAT))
scalar rDeltaTSmoothingCoeff (pimpleDict.getOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.1))
scalar rDeltaTDampingCoeff (pimpleDict.getOrDefault< scalar >("rDeltaTDampingCoeff", 1.0))
scalar alphaTemp (pimpleDict.getOrDefault< scalar >("alphaTemp", 0.05))
scalar alphaY (pimpleDict.getOrDefault< scalar >("alphaY", 1.0))
Info<< "Time scales min/max:"<< endl;volScalarField rDeltaT0("rDeltaT0", rDeltaT);{ rDeltaT.ref()=(fvc::surfaceSum(mag(phi))()()/((2 *maxCo) *mesh.V() *rho()));rDeltaT.max(1/maxDeltaT);Info<< " Flow = "<< 1/gMax(rDeltaT.primitiveField())<< ", "<< 1/gMin(rDeltaT.primitiveField())<< endl;} if(alphaTemp< 1) { volScalarField::Internal rDeltaTT(mag(Qdot)/(alphaTemp *rho *thermo.Cp() *T));Info<< " Temperature = "<< 1/(gMax(rDeltaTT.field())+VSMALL)<< ", "<< 1/(gMin(rDeltaTT.field())+VSMALL)<< endl;rDeltaT.ref()=max(rDeltaT(), rDeltaTT);} if(alphaY< 1) { dictionary Yref(pimpleDict.subDict("Yref"));volScalarField::Internal rDeltaTY(IOobject("rDeltaTY", runTime.timeName(), mesh), mesh, dimensionedScalar(rDeltaT.dimensions(), Zero));bool foundY=false;forAll(Y, i) { if(i !=inertIndex &&composition.active(i)) { volScalarField &Yi=Y[i];if(Yref.found(Yi.name())) { foundY=true;const scalar Yrefi=Yref.get< scalar > (Yi.name())
rDeltaTY field ()
if (foundY)
rDeltaT correctBoundaryConditions ()
if (rDeltaTSmoothingCoeff< 1)
if (rDeltaTDampingCoeff< 1 &&runTime.timeIndex() > runTime.startTimeIndex()+1)
Variables
const dictionary & pimpleDict = pimple.dict()
else
Detailed Description
Original source file setRDeltaT.H
Definition in file setRDeltaT.H.
Function Documentation
maxCo()
scalar maxCo (pimpleDict.get< scalar > "maxCo")
maxDeltaT()
scalar maxDeltaT (pimpleDict.getOrDefault< scalar > "maxDeltaT", GREAT)
rDeltaTSmoothingCoeff()
scalar rDeltaTSmoothingCoeff (pimpleDict.getOrDefault< scalar > "rDeltaTSmoothingCoeff", 0.1)
Referenced by correctBoundaryConditions(), and if().
rDeltaTDampingCoeff()
scalar rDeltaTDampingCoeff (pimpleDict.getOrDefault< scalar > "rDeltaTDampingCoeff", 1.0)
Referenced by if().
alphaTemp()
scalar alphaTemp (pimpleDict.getOrDefault< scalar > "alphaTemp", 0.05)
alphaY()
scalar alphaY (pimpleDict.getOrDefault< scalar > "alphaY", 1.0)
Info<< "Time scales min/max:"<< endl;volScalarField rDeltaT0("rDeltaT0", rDeltaT);{ rDeltaT.ref()=(fvc::surfaceSum(mag(phi))()()/((2 *maxCo) *mesh.V() *rho()));rDeltaT.max(1/maxDeltaT);Info<< " Flow = "<< 1/gMax(rDeltaT.primitiveField())<< ", "<< 1/gMin(rDeltaT.primitiveField())<< endl;} if(alphaTemp< 1) { volScalarField::Internal rDeltaTT(mag(Qdot)/(alphaTemp *rho *thermo.Cp() *T));Info<< " Temperature = "<< 1/(gMax(rDeltaTT.field())+VSMALL)<< ", "<< 1/(gMin(rDeltaTT.field())+VSMALL)<< endl;rDeltaT.ref()=max(rDeltaT(), rDeltaTT);} if(alphaY< 1) { dictionary Yref(pimpleDict.subDict("Yref"));volScalarField::Internal rDeltaTY(IOobject("rDeltaTY", runTime.timeName(), mesh), mesh, dimensionedScalar(rDeltaT.dimensions(), Zero));bool foundY=false;forAll(Y, i) { if(i !=inertIndex &&composition.active(i)) { volScalarField &Yi=Y[i];if(Yref.found(Yi.name())) { foundY=true;const scalar Yrefi=Yref.get< scalar >()
Info<< "Time scales min/max:"<< endl;volScalarField rDeltaT0("rDeltaT0", rDeltaT);{ rDeltaT.ref()=(fvc::surfaceSum(mag(phi))()()/((2 *maxCo) *mesh.V() *rho()));rDeltaT.max(1/maxDeltaT);Info<< " Flow = "<< 1/gMax(rDeltaT.primitiveField())<< ", "<< 1/gMin(rDeltaT.primitiveField())<< endl;} if(alphaTemp< 1) { volScalarField::Internal rDeltaTT(mag(Qdot)/(alphaTemp *rho *thermo.Cp() *T));Info<< " Temperature = "<< 1/(gMax(rDeltaTT.field())+VSMALL)<< ", "<< 1/(gMin(rDeltaTT.field())+VSMALL)<< endl;rDeltaT.ref()=max(rDeltaT(), rDeltaTT);} if(alphaY< 1) { dictionary Yref(pimpleDict.subDict("Yref"));volScalarField::Internal rDeltaTY(IOobject("rDeltaTY", runTime.timeName(), mesh), mesh, dimensionedScalar(rDeltaT.dimensions(), Zero));bool foundY=false;forAll(Y, i) { if(i !=inertIndex &&composition.active(i)) { volScalarField &Yi=Y[i];if(Yref.found(Yi.name())) { foundY=true;const scalar Yrefi=Yref.get< scalar > (Yi. name())
field()
rDeltaTY field ()
Referenced by phaseSystem::addField(), phaseSystem::addField(), phaseSystem::addField(), phaseSystem::addField(), NURBS3DSurface::buildSurface(), fieldExtents::calcMask(), fieldExtents::calcMask(), fieldMinMax::calcMinMaxFields(), fieldMinMax::calcMinMaxFieldType(), norm::calcNormType(), parseDriver::cellToFace(), parseDriver::cellToPoint(), fieldValue::combineFields(), sizeDistribution::combineFields(), fieldValue::combineFields(), adjointBoundaryCondition< Type >::computePatchGrad(), kinematicSingleLayer::constrainFilmField(), optionList::correct(), CodedSource< Type >::correct(), optionList::correct(), atmNutSource::correct(), multiphaseStabilizedTurbulence::correct(), optionList::d2dt2(), optionList::d2dt2(), optionList::d2dt2(), optionList::d2dt2(), dimFieldDecomposer::decomposeField(), fvFieldDecomposer::decomposeField(), faFieldDecomposer::decomposeField(), faFieldDecomposer::decomposeField(), fvFieldDecomposer::decomposeField(), fvFieldDecomposer::decomposeField(), pointFieldDecomposer::decomposeField(), lagrangianFieldDecomposer::decomposeField(), lagrangianFieldDecomposer::decomposeFieldField(), mapDistributeBase::distribute(), mapDistributeBase::distribute(), Foam::doCorrectBoundaryConditions(), Foam::doCorrectBoundaryConditions(), Foam::MULES::explicitSolve(), parseDriver::faceToPoint(), extractEulerianParticles::faceValue(), exprDriver::fill_random(), volFieldValue::filterField(), surfaceFieldValue::filterField(), surfaceFieldValue::filterField(), sizeDistribution::filterField(), forAll(), particleDistribution::generateDistribution(), GeometricBoundaryField< Type, PatchField, GeoMesh >::GeometricBoundaryField(), GeometricBoundaryField< Type, PatchField, GeoMesh >::GeometricBoundaryField(), GeometricBoundaryField< Type, PatchField, GeoMesh >::GeometricBoundaryField(), GeometricBoundaryField< Type, PatchField, GeoMesh >::GeometricBoundaryField(), GeometricBoundaryField< Type, PatchField, GeoMesh >::GeometricBoundaryField(), Foam::getAnimationColour(), Foam::getBoundedColours(), Foam::getData(), externalDisplacementMeshMover::getFixedValueBCs(), Foam::getRefCellValue(), updateMethod::globalSum(), ensightFile::hasUndef(), ensightFile::hasUndef(), ensightFile::hasUndef(), ensightFile::hasUndef(), liquidFilmModel::info(), interRegionHeatTransferModel::interpolate(), interRegionHeatTransferModel::interpolate(), propellerInfo::interpolate(), interRegionHeatTransferModel::interpolate(), interRegionHeatTransferModel::interpolate(), limitFields::limitField(), limitFields::limitScalarField(), Foam::MapDimensionedFields(), Foam::MapGeometricFields(), meshToMesh::mapInternalSrcToTgt(), meshToMesh::mapInternalSrcToTgt(), meshToMesh::mapInternalSrcToTgt(), meshToMesh::mapInternalSrcToTgt(), meshToMesh::mapInternalSrcToTgt(), meshToMesh::mapInternalSrcToTgt(), meshToMesh::mapInternalTgtToSrc(), meshToMesh::mapInternalTgtToSrc(), meshToMesh::mapInternalTgtToSrc(), meshToMesh::mapInternalTgtToSrc(), meshToMesh::mapInternalTgtToSrc(), meshToMesh::mapInternalTgtToSrc(), meshToMesh::mapSrcToTgt(), meshToMesh::mapSrcToTgt(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), meshToMesh::mapTgtToSrc(), meshToMesh::mapTgtToSrc(), propellerInfo::meanSampleDiskField(), fieldSmoother::minSmoothField(), objective::nullify(), variablesSet::nullifyField(), optionList::operator()(), optionList::operator()(), optionList::operator()(), optionList::operator()(), optionList::operator()(), multivariateIndependentScheme< Type >::operator()(), multivariateScheme< Type, Scheme >::operator()(), multivariateSelectionScheme< Type >::operator()(), multivariateUpwind< Type >::operator()(), optionList::operator()(), optionList::operator()(), optionList::operator()(), optionList::operator()(), optionList::operator()(), optionList::operator()(), optionList::operator()(), MapInternalField< Type, MeshMapper, surfaceMesh >::operator()(), MapInternalField< Type, MeshMapper, volMesh >::operator()(), MapInternalField< Type, MeshMapper, areaMesh >::operator()(), MapInternalField< Type, MeshMapper, edgeMesh >::operator()(), MapInternalField< Type, MeshMapper, pointMesh >::operator()(), optionList::operator()(), optionList::operator()(), parseDriver::pointToCell(), parseDriver::pointToFace(), liquidFilmModel::preEvolveRegion(), particleDistribution::processField(), GeometricBoundaryField< Type, PatchField, GeoMesh >::readField(), ensightSurfaceReader::readField(), Foam::ensightOutput::readWriteCloudField(), fft::realTransform1D(), mapDistributeBase::receive(), mapDistributeBase::receive(), mapDistributeBase::receive(), lagrangianReconstructor::reconstructField(), lagrangianReconstructor::reconstructFieldField(), KinematicCloud< CloudType >::relax(), coordSetWriter::repackageFields(), KinematicCloud< CloudType >::scale(), mapDistributeBase::send(), mapDistributeBase::send(), mapDistributeBase::send(), Foam::setRefCell(), Foam::setRefCell(), Foam::fvc::smooth(), optionList::source(), optionList::source(), Foam::fvc::spread(), faceSetOption::subsetFilter(), Foam::sumNeighbours(), Foam::fvc::sweep(), thresholdCellFaces::thresholdCellFaces(), fft::transform(), Foam::transformList(), Foam::transformList(), Foam::transformList(), Foam::transformList(), Foam::transformList(), Foam::transformList(), advectiveFvPatchField< Type >::updateCoeffs(), speciesSorptionFvPatchScalarField::updateCoeffs(), equalBinWidth::write(), unequalBinWidth::write(), internalWriter::write(), NURBS3DCurve::write(), GenericPatchGeoFieldsWriter< PatchType >::write(), patchWriter::write(), GenericPatchGeoFieldsWriter< PatchType >::write(), internalWriter::write(), patchWriter::write(), internalWriter::write(), patchWriter::write(), lagrangianWriter::write(), surfaceFieldWriter::write(), polyWriter::write(), NURBS3DCurve::write(), Foam::writeAreaField(), fileWriter::writeBasicField(), polyWriter::writeCellData(), internalMeshWriter::writeCellData(), Foam::ensightOutput::writeCloudField(), rotorDiskSource::writeField(), lagrangianWriter::writeFields(), ensightFile::writeList(), ensightFile::writeList(), ensightFile::writeList(), ensightFile::writeList(), ensightFile::writeList(), polyWriter::writePointData(), internalMeshWriter::writePointData(), coordSetWriter::writePointData(), Foam::writePointField(), Foam::writePointField(), writer::writeSolution(), gltfWriter::writeTemplate(), gltfWriter::writeTemplate_animate(), Foam::writeVolField(), vtkWrite::writeVolFieldsImpl(), vtkWrite::writeVolFieldsImpl(), ensightWrite::writeVolFieldsImpl(), NURBS3DCurve::writeWParses(), and NURBS3DCurve::writeWParses().
if() [1/3]
if (foundY)
Definition at line 132 of file setRDeltaT.H.
correctBoundaryConditions()
rDeltaT correctBoundaryConditions ()
if() [2/3]
if ()
Definition at line 152 of file setRDeltaT.H.
References rDeltaTSmoothingCoeff().
if() [3/3]
if (rDeltaTDampingCoeff< 1 &&runTime.timeIndex() > runTime.startTimeIndex()+ 1)
Definition at line 160 of file setRDeltaT.H.
References rDeltaT0(), and rDeltaTDampingCoeff().
Variable Documentation
pimpleDict
const dictionary& pimpleDict = pimple.dict()
Definition at line 25 of file setRDeltaT.H.
else
else
Initial value:
{
            IOWarningIn(args.executable().c_str(), Yref)
                << "Cannot find any active species in Yref " << Yref
                << endl
Definition at line 140 of file setRDeltaT.H.