OpenFOAM: applications/solvers/combustion/reactingFoam/UEqn.H File Reference
UEqn.H File Reference
Functions
MRF correctBoundaryVelocity (U)
tmp< fvVectorMatrix > tUEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U)==fvOptions(rho, U))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple.momentumPredictor())
Variables
fvVectorMatrix & UEqn = tUEqn.ref()
Function Documentation
correctBoundaryVelocity()
MRF correctBoundaryVelocity (U)
tUEqn()
tmp< fvVectorMatrix > tUEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U) = =fvOptions(rho, U))
Referenced by incompressiblePrimalSolver::correctBoundaryConditions(), kinematicSingleLayer::evolveRegion(), thermoSingleLayer::evolveRegion(), if(), simple::mainIter(), and kinematicSingleLayer::solveMomentum().
relax()
UEqn relax ()
constrain()
fvOptions constrain (UEqn)
if()
if (pimple. momentumPredictor())
Definition at line 19 of file UEqn.H.
References fvOptions, p, solve(), U, and UEqn.
Variable Documentation
UEqn
fvVectorMatrix& UEqn = tUEqn.ref()
Definition at line 13 of file UEqn.H.
Referenced by MRFZoneList::addAcceleration(), MRFZoneList::addAcceleration(), MRFZone::addCoriolis(), MRFZone::addCoriolis(), multiphaseInterSystem::addInterfacePorosity(), porosityModelList::addResistance(), porosityModelList::addResistance(), porosityModelList::addResistance(), powerLawLopesdaCosta::correct(), DarcyForchheimer::correct(), fixedCoeff::correct(), powerLaw::correct(), solidification::correct(), powerLawLopesdaCosta::correct(), DarcyForchheimer::correct(), fixedCoeff::correct(), powerLaw::correct(), solidification::correct(), powerLawLopesdaCosta::correct(), DarcyForchheimer::correct(), fixedCoeff::correct(), powerLaw::correct(), solidification::correct(), incompressiblePrimalSolver::correctBoundaryConditions(), kinematicSingleLayer::evolveRegion(), thermoSingleLayer::evolveRegion(), if(), if(), if(), if(), if(), if(), if(), simple::mainIter(), velocityLaplacianFvMotionSolver::solve(), kinematicSingleLayer::solveMomentum(), and kinematicSingleLayer::solveThickness().