OpenFOAM: applications/solvers/combustion/chemFoam/hEqn.H File Reference
hEqn.H File Reference
Functions
if (constProp=="volume")
thermo correct ()
Variables
else
Function Documentation
if()
if (constProp = = "volume")
Definition at line 4 of file hEqn.H.
References h, integratedHeat, p, rho, and u0.
correct()
radiation correct ()
Referenced by porosityModel::addResistance(), porosityModel::addResistance(), porosityModel::addResistance(), interRegionHeatTransferModel::addSup(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), kL< BasicTurbulenceModel >::correct(), motionDirectionalDiffusivity::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), EBRSM< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::correct(), Foam::MULES::correct(), Foam::MULES::correct(), Foam::MULES::correct(), Foam::MULES::correct(), advectionDiffusion::correct(), directionalMeshWave::correct(), meshWaveAddressing::correct(), Poisson::correct(), exact::correct(), fvMeshSubsetProxy::fvMeshSubsetProxy(), fvMeshSubsetProxy::fvMeshSubsetProxy(), fvMeshSubsetProxy::fvMeshSubsetProxy(), meshStructure::meshStructure(), meshStructure::meshStructure(), wallDistAddressing::movePoints(), sampledSets::movePoints(), fvMeshSubsetProxy::readUpdate(), sampledSets::readUpdate(), fvMeshSubsetProxy::resetZones(), rotorDiskSource::setFaceArea(), populationBalanceModel::solve(), and sampledSets::updateMesh().
Variable Documentation
else
else
Initial value:
{
        h[0] = h0 + integratedHeat
Definition at line 8 of file hEqn.H.