OpenFOAM: applications/solvers/compressible/rhoSimpleFoam/rhoPorousSimpleFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
if (pressureImplicitPorosity)
tUEqn clear ()
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(rho *HbyA))
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
while (simple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
pressureControl limit (p)
if (closedVolume)
Variables
tmp< volVectorField > tHbyA
else
volVectorField & HbyA = tHbyA.ref()
bool closedVolume = false
rho = thermo.rho()
Function Documentation
if() [1/2]
if (pressureImplicitPorosity)
Definition at line 5 of file pEqn.H.
References p, tHbyA, trTU, U, and UEqn.
clear()
tUEqn clear ()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(rho *HbyA))
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
while()
while (simple. correctNonOrthogonal())
Definition at line 24 of file pEqn.H.
References fvOptions, p, phi, phiHbyA, pressureControl, pressureImplicitPorosity(), psi, rho, simple, trAU, and trTU.
relax()
p relax ()
References HbyA, p, trTU, and U.
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
limit()
pressureControl limit (p)
Referenced by Foam::MULES::explicitSolve(), and Foam::MULES::limit().
if() [2/2]
if (closedVolume)
Definition at line 86 of file pEqn.H.
References initialMass, p, and psi.
Variable Documentation
tHbyA
tmp<volVectorField> tHbyA
Initial value:
{
    const volScalarField& psi = thermo.psi()
Definition at line 4 of file pEqn.H.
Referenced by Foam::constrainHbyA(), and if().
else
else
Initial value:
{
        tHbyA = constrainHbyA(trAU()*UEqn.H(), U, p)
Definition at line 9 of file pEqn.H.
HbyA
volVectorField& HbyA = tHbyA.ref()
Definition at line 13 of file pEqn.H.
closedVolume
closedVolume = false
Definition at line 17 of file pEqn.H.
rho
rho = thermo.rho()
Definition at line 92 of file pEqn.H.