OpenFOAM: applications/solvers/compressible/rhoPimpleFoam/pcEqn.H File Reference
pcEqn.H File Reference
Functions
if (!pimple.SIMPLErho())
const volScalarField psip0 (psi *p)
volScalarField rAU (1.0/UEqn.A())
volScalarField rAtU (1.0/(1.0/rAU - UEqn.H1()))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
if (pimple.nCorrPISO()<=1)
surfaceScalarField phiHbyA ("phiHbyA",(fvc::interpolate(rho) *fvc::flux(HbyA)+MRF.zeroFilter(fvc::interpolate(rho *rAU) *fvc::ddtCorr(rho, U, phi, rhoUf))))
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
volScalarField rhorAtU ("rhorAtU", rho *rAtU)
constrainPressure (p, rho, U, phiHbyA, rhorAtU, MRF)
if (pimple.transonic())
fvScalarMatrix pDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p))+fvc::div(phiHbyA)==fvOptions(psi, p, rho.name()))
while (pimple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
if (pressureControl.limit(p))
thermo correctRho (psi *p - psip0, rhoMin, rhoMax)
if (thermo.dpdt())
Variables
else
HbyA = (rAU - rAtU)*fvc::grad(p)
U = HbyA - rAtU*fvc::grad(p)
K = 0.5*magSqr(U)
rho = thermo.rho()
Function Documentation
if() [1/5]
if (!pimple. SIMPLErho())
Definition at line 1 of file pcEqn.H.
References rho.
psip0()
const volScalarField psip0 (psi * p)
rAU()
volScalarField rAU (1.0/UEqn. A())
rAtU()
volScalarField rAtU (1.0/ 1.0/rAU - UEqn.H1())
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
if() [2/5]
if (pimple.nCorrPISO()<= 1)
Definition at line 14 of file pcEqn.H.
References tUEqn().
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::interpolate(rho) *fvc::flux(HbyA)+MRF.zeroFilter(fvc::interpolate(rho *rAU) *fvc::ddtCorr(rho, U, phi, rhoUf))))
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
rhorAtU()
volScalarField rhorAtU ("rhorAtU" , rho * rAtU)
constrainPressure()
constrainPressure (p , rho , U , phiHbyA , rhorAtU , MRF)
if() [3/5]
if (pimple. transonic())
Definition at line 39 of file pcEqn.H.
References fvOptions, HbyA, mesh, p, pDDtEqn(), phi, phid(), phiHbyA, pimple, psi, rAtU(), rAU, rho, and rhorAtU().
pDDtEqn()
fvScalarMatrix pDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p))+fvc::div(phiHbyA) = =fvOptions(psi, p, rho.name()))
Referenced by if(), and while().
while()
while (pimple. correctNonOrthogonal())
Definition at line 89 of file pcEqn.H.
References mesh, p, pDDtEqn(), phi, phiHbyA, pimple, and rhorAtU().
relax()
p relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
if() [4/5]
if (pressureControl. limitp)
Definition at line 113 of file pcEqn.H.
References p.
correctRho()
thermo correctRho (psi *p - psip0, rhoMin , rhoMax)
if() [5/5]
if (thermo. dpdt())
Definition at line 124 of file pcEqn.H.
References dpdt, mesh, p, rho, and U.
Variable Documentation
else
else
Initial value:
{
    phiHbyA += fvc::interpolate(rho*(rAtU - rAU))*fvc::snGrad(p)*mesh.magSf()
Definition at line 76 of file pcEqn.H.
HbyA
HbyA = (rAU - rAtU)*fvc::grad(p)
Definition at line 79 of file pcEqn.H.
U
U = HbyA - rAtU*fvc::grad(p)
Definition at line 108 of file pcEqn.H.
K
K = 0.5*magSqr(U)
Definition at line 111 of file pcEqn.H.
rho
rho = thermo.rho()
Definition at line 119 of file pcEqn.H.