OpenFOAM: applications/solvers/multiphase/compressibleInterFoam/compressibleAlphaEqnSubCycle.H File Reference
compressibleAlphaEqnSubCycle.H File Reference
Functions
tmp< surfaceScalarField > talphaPhi1 (alphaPhi10)
if (nAlphaSubCycles > 1)
surfaceScalarField alphaPhi2 ("alphaPhi2", phi - alphaPhi1)
volScalarField::Internal contErr ((fvc::ddt(rho)+fvc::div(rhoPhi) -(fvOptions(alpha1, mixture.thermo1().rho())&rho1) -(fvOptions(alpha2, mixture.thermo2().rho())&rho2))())
Variables
else
const surfaceScalarField & alphaPhi1 = talphaPhi1()
Function Documentation
talphaPhi1()
tmp< surfaceScalarField > talphaPhi1 (alphaPhi10)
Referenced by if().
if()
if (nAlphaSubCycles , 1)
Definition at line 3 of file compressibleAlphaEqnSubCycle.H.
References alpha1, alphaPhi10, LTS, mesh, nAlphaSubCycles(), rhoPhi, runTime, and talphaPhi1().
alphaPhi2()
surfaceScalarField alphaPhi2 ("alphaPhi2" , phi - alphaPhi1)
contErr()
volScalarField::Internal contErr ((fvc::ddt(rho)+fvc::div(rhoPhi) -(fvOptions(alpha1, mixture.thermo1().rho())&rho1) -(fvOptions(alpha2, mixture.thermo2().rho())&rho2))())
Referenced by adjointSimple::continuityErrors(), simple::continuityErrors(), and AnisothermalPhaseModel< BasePhaseModel >::heEqn().
Variable Documentation
else
else
Initial value:
{
}
rho == alpha1*rho1 + alpha2*rho2
Definition at line 52 of file compressibleAlphaEqnSubCycle.H.
alphaPhi1
const surfaceScalarField& alphaPhi1 = talphaPhi1()
Definition at line 59 of file compressibleAlphaEqnSubCycle.H.