OpenFOAM: applications/solvers/compressible/rhoSimpleFoam/overRhoSimpleFoam/createUpdatedDynamicFvMesh.H File Reference
createUpdatedDynamicFvMesh.H File Reference
Required Variables.
Functions
mesh update ()
Variables
Foam::autoPtr< Foam::dynamicFvMesh > meshPtr
dynamicFvMesh & mesh = meshPtr()
Detailed Description
Required Variables.
Original source file createUpdatedDynamicFvMesh.H
Provided Variables
Definition in file createUpdatedDynamicFvMesh.H.
Function Documentation
update()
mesh update ()
Referenced by solidificationMeltingSource::addSup(), polyTopoChanger::changeMesh(), steadyOptimisation::checkEndOfLoopAndUpdate(), fvExprDriver::clearVariables(), BFGS::computeCorrection(), DBFGS::computeCorrection(), LBFGS::computeCorrection(), SR1::computeCorrection(), dynamicFvMesh::controlledUpdate(), medialAxisMeshMover::medialAxisMeshMover(), cellCellStencil::New(), sampledMeshedSurface::update(), sampledMeshedSurface::update(), cellInfo::updateCell(), smoothDelta::deltaData::updateCell(), refinementDistanceData::updateCell(), smoothData::updateCell(), sweepData::updateCell(), wallNormalInfo::updateCell(), wallPoint::updateCell(), wallPoints::updateCell(), directionalWallPointData< Type >::updateCell(), transportData::updateCell(), wallPointAddressing::updateCell(), wallPointData< scalar >::updateCell(), patchEdgeFaceRegion::updateEdge(), patchEdgeFaceRegion::updateEdge(), externalPointEdgePoint::updateEdge(), pointEdgeCollapse::updateEdge(), pointEdgePoint::updateEdge(), pointEdgeStructuredWalk::updateEdge(), patchEdgeFaceInfo::updateEdge(), patchEdgeFaceInfo::updateEdge(), cellInfo::updateFace(), smoothDelta::deltaData::updateFace(), cellInfo::updateFace(), smoothDelta::deltaData::updateFace(), refinementDistanceData::updateFace(), smoothData::updateFace(), sweepData::updateFace(), wallNormalInfo::updateFace(), wallPoint::updateFace(), wallPoints::updateFace(), refinementDistanceData::updateFace(), smoothData::updateFace(), sweepData::updateFace(), wallNormalInfo::updateFace(), wallPoint::updateFace(), wallPoints::updateFace(), patchEdgeFaceRegion::updateFace(), directionalWallPointData< Type >::updateFace(), directionalWallPointData< Type >::updateFace(), transportData::updateFace(), wallPointAddressing::updateFace(), transportData::updateFace(), wallPointAddressing::updateFace(), wallPointData< scalar >::updateFace(), patchEdgeFaceInfo::updateFace(), externalPointEdgePoint::updatePoint(), pointEdgeCollapse::updatePoint(), pointEdgePoint::updatePoint(), pointEdgeStructuredWalk::updatePoint(), externalPointEdgePoint::updatePoint(), externalPointEdgePoint::updatePoint(), pointEdgeCollapse::updatePoint(), pointEdgePoint::updatePoint(), pointEdgeStructuredWalk::updatePoint(), pointEdgeCollapse::updatePoint(), pointEdgePoint::updatePoint(), pointEdgeStructuredWalk::updatePoint(), fvExprDriver::updateSpecialVariables(), wallPointData< scalar >::wallPointData(), surfaceFieldValue::write(), fluxSummary::write(), ensightWrite::write(), and vtkWrite::write().
Variable Documentation
meshPtr
meshPtr
Initial value:
= dynamicFvMesh::New
    (
        IOobject
        (
            polyMesh::defaultRegion,
            runTime.timeName(),
            runTime,
            IOobject::MUST_READ
        )
    )
Definition at line 25 of file createUpdatedDynamicFvMesh.H.
mesh
dynamicFvMesh& mesh = meshPtr()
Definition at line 44 of file createUpdatedDynamicFvMesh.H.