OpenFOAM: applications/solvers/multiphase/compressibleInterFoam/compressibleInterIsoFoam/alphaEqn.H File Reference
alphaEqn.H File Reference
Functions
advector advect (Sp,(Su+divU *min(alpha1(), scalar(1)))())
Variables
rhoPhi = advector.getRhoPhi(rho1, rho2)
alphaPhi10 = advector.alphaPhi()
alpha2 = 1.0 - alpha1
Function Documentation
advect()
advector advect (Sp , (Su+divU *min(alpha1(), scalar(1)))())
Variable Documentation
rhoPhi
rhoPhi = advector.getRhoPhi(rho1, rho2)
Definition at line 6 of file alphaEqn.H.
Referenced by for(), if(), if(), and if().
alphaPhi10
alphaPhi10 = advector.alphaPhi()
Definition at line 7 of file alphaEqn.H.
Referenced by for(), if(), if(), if(), if(), if(), and twoPhaseSystem::solve().
alpha2
alpha2 = 1.0 - alpha1
Definition at line 9 of file alphaEqn.H.
Referenced by for(), for(), and if().