OpenFOAM: applications/solvers/compressible/rhoPimpleFoam/overRhoPimpleDyMFoam/correctPhi.H File Reference
correctPhi.H File Reference
Functions
if (mesh.changing())
wordList pcorrTypes (p.boundaryField().size(), fvPatchFieldBase::zeroGradientType())
forAll (p.boundaryField(), patchi)
volScalarField pcorr (IOobject("pcorr", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar(p.dimensions(), Zero), pcorrTypes)
mesh setFluxRequired (pcorr.name())
while (pimple.correctNonOrthogonal())
Function Documentation
if()
if (mesh. changing())
Definition at line 1 of file correctPhi.H.
References forAll, mesh, phi, rho, and U.
pcorrTypes()
wordList pcorrTypes (p. boundaryField).size(, fvPatchFieldBase::zeroGradientType())
Referenced by Foam::CorrectPhi(), Foam::CorrectPhi(), for(), and forAll().
forAll()
forAll (p. boundaryField(), patchi)
Definition at line 36 of file correctPhi.H.
References p, and pcorrTypes().
pcorr()
volScalarField pcorr (IOobject("pcorr", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedScalar(p.dimensions(), Zero) , pcorrTypes)
Referenced by Foam::CorrectPhi(), Foam::CorrectPhi(), if(), and while().
setFluxRequired()
mesh setFluxRequired (pcorr. name())
References rAUf().
while()
while (pimple. correctNonOrthogonal())
Definition at line 64 of file correctPhi.H.
References mesh, pcorr(), phi, pimple, psi, and rAUf().