OpenFOAM: applications/solvers/compressible/rhoCentralFoam/createFieldRefs.H File Reference
createFieldRefs.H File Reference
Functions
bool inviscid (true)
if (max(mu.primitiveField()) > 0.0)
Variables
volScalarField & p = thermo.p()
const volScalarField & T = thermo.T()
const volScalarField & psi = thermo.psi()
const volScalarField & mu = thermo.mu()
Function Documentation
inviscid()
bool inviscid (true)
Referenced by if().
if()
if (max(mu.primitiveField()) , 0. 0)
Definition at line 7 of file createFieldRefs.H.
References inviscid().
Variable Documentation
p
volScalarField& p = thermo.p()
Definition at line 1 of file createFieldRefs.H.
T
const volScalarField& T = thermo.T()
Definition at line 2 of file createFieldRefs.H.
psi
const volScalarField& psi = thermo.psi()
Definition at line 3 of file createFieldRefs.H.
mu
const volScalarField& mu = thermo.mu()
Definition at line 4 of file createFieldRefs.H.
Referenced by porosityModel::addResistance(), porosityModelList::addResistance(), interRegionExplicitPorositySource::addSup(), constTransport< Thermo >::alphah(), WLFTransport< Thermo >::alphah(), DarcyForchheimer::calcForce(), forces::calcForcesMoments(), KinematicParcel< ParcelType >::calcVelocity(), tetrahedron< Point, PointRef >::circumCentre(), tetrahedron< Point, PointRef >::circumRadius(), EDC< ReactionThermo >::correct(), contactAngleForce::correct(), DarcyForchheimer::correct(), DarcyForchheimer::correct(), DarcyForchheimer::correct(), directionalPressureGradientExplicitSource::correct(), filmTurbulenceModel::Cw(), KinematicSurfaceFilm< CloudType >::drySplashInteraction(), kOmegaSSTBase< BasicEddyViscosityModel >::F1(), kOmegaSSTBase< BasicEddyViscosityModel >::F2(), kOmegaSSTBase< BasicEddyViscosityModel >::F3(), Foam::interpolateSplineXY(), constTransport< Thermo >::kappa(), sutherlandTransport< Thermo >::kappa(), WLFTransport< Thermo >::kappa(), multiphaseInterSystem::mu(), multiphaseInterSystem::mu(), incompressibleTwoPhaseMixture::mu(), liquidMixtureProperties::mu(), filmViscosityModel::New(), multiphaseSystem::nu(), fluidThermo::nu(), multiphaseSystem::nu(), fluidThermo::nu(), BSpline::position(), CatmullRomSpline::position(), polyLine::position(), BSpline::position(), CatmullRomSpline::position(), BSplineEdge::position(), polyLine::position(), splineEdge::position(), SprayParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::readObjects(), multiNormal::sample(), fieldSmoother::smoothLambdaMuDisplacement(), surfaceAlignedSBRStressFvMotionSolver::solve(), laminar::Su(), particle< Type >::trackToMovingTri(), particle< Type >::trackToStationaryTri(), KinematicSurfaceFilm< CloudType >::transferParcel(), ThermoSurfaceFilm< CloudType >::transferParcel(), ETAB< CloudType >::update(), PilchErdman< CloudType >::update(), ReitzKHRT< CloudType >::update(), SHF< CloudType >::update(), TAB< CloudType >::update(), LISAAtomization< CloudType >::update(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), splineInterpolationWeights::valueWeights(), KinematicSurfaceFilm< CloudType >::wetSplashInteraction(), SprayParcel< ParcelType >::writeFields(), and SprayParcel< ParcelType >::writeObjects().