OpenFOAM: applications/solvers/compressible/rhoCentralFoam/setRDeltaT.H File Reference
setRDeltaT.H File Reference
Functions
scalar rDeltaTSmoothingCoeff (runTime.controlDict().getOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.02))
rDeltaT ref () = pos(alpha2)
rDeltaT correctBoundaryConditions ()
Function Documentation
rDeltaTSmoothingCoeff()
scalar rDeltaTSmoothingCoeff (runTime. controlDict).getOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.02)
ref()
p_rghEqnComp2 ref () = pos(alpha2)
Referenced by polyTopoChanger::changeMesh(), adjointkOmegaSST::correct(), objectRegistry::lookupObjectRef(), refPtr< Field< InputType > >::operator tmp< Field< InputType > >(), colourTable::ref(), perfectInterface::setRefinement(), attachDetach::setRefinement(), layerAdditionRemoval::setRefinement(), perfectInterface::setRefinement(), slidingInterface::setRefinement(), and polyTopoChanger::topoChangeRequest().
correctBoundaryConditions()
rDeltaT correctBoundaryConditions ()