OpenFOAM: applications/solvers/compressible/rhoPimpleAdiabaticFoam/EEqn.H File Reference
EEqn.H File Reference
Functions
if (mag(gamma - min(Cp/Cv).value()) > VSMALL)
if (!local)
thermo correct ()
rho relax ()
rho writeMinMax (Info)
Variables
const tmp< volScalarField > & tCp = thermo.Cp()
const tmp< volScalarField > & tCv = thermo.Cv()
const volScalarField & Cp = tCp()
const volScalarField & Cv = tCv()
const scalar gamma = max(Cp/Cv).value()
const dictionary & thermoDict = thermo.subDict("mixture")
const dictionary & eosDict = thermoDict.subDict("equationOfState")
bool local = eosDict.getOrDefault("local", false)
else
const volScalarField & p0 = p.oldTime()
he = thermo.he(p, pow(p/p0, (gamma - scalar(1))/gamma)*T0)
psi = 1.0/((Cp - Cv)*T)
rho = thermo.rho()
Function Documentation
if() [1/2]
if (mag(gamma - min(Cp/Cv).value()) , VSMALL)
Definition at line 11 of file EEqn.H.
References notImplemented.
if() [2/2]
if (! local)
Definition at line 26 of file EEqn.H.
References eosDict, gamma, he, p, p0, and T0.
correct()
thermo correct ()
relax()
rho relax ()
writeMinMax()
rho writeMinMax (Info)
Variable Documentation
tCp
const tmp<volScalarField>& tCp = thermo.Cp()
Definition at line 4 of file EEqn.H.
Referenced by HuaXu::CHFSubCool(), Tatsumoto::CHFSubCool(), constantFilmThermo::Cp(), liquidFilmThermo::Cp(), heThermo< BasicThermo, MixtureType >::Cp(), heThermo< BasicThermo, MixtureType >::Cp(), heThermo< BasicThermo, MixtureType >::Cp(), BreenWestwater::htcFilmBoil(), Bromley::htcFilmBoil(), and alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs().
tCv
const tmp<volScalarField>& tCv = thermo.Cv()
Definition at line 5 of file EEqn.H.
Referenced by heThermo< BasicThermo, MixtureType >::Cv(), and heThermo< BasicThermo, MixtureType >::Cv().
Cp
const volScalarField& Cp = tCp()
Definition at line 7 of file EEqn.H.
Referenced by solidificationMeltingSource::addSup(), constAnIsoSolidTransport< Thermo >::alphah(), constIsoSolidTransport< Thermo >::alphah(), exponentialSolidTransport< Thermo >::alphah(), polynomialSolidTransport< Thermo, PolySize >::alphah(), tabulatedAnIsoSolidTransport< Thermo >::alphah(), tabulatedSolidTransport< Thermo >::alphah(), logPolynomialTransport< Thermo, PolySize >::alphah(), polynomialTransport< Thermo, PolySize >::alphah(), sutherlandTransport< Thermo >::alphah(), tabulatedTransport< Thermo >::alphah(), liquidProperties::alphah(), SprayParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), ReactingParcel< ParcelType >::calcPhaseChange(), tabulatedNTUHeatTransfer::calculateHtc(), HuaXu::CHFSubCool(), Tatsumoto::CHFSubCool(), ThermoCloud< Foam::DSMCCloud >::constProps(), standardPhaseChange::correctModel(), multiphaseInterSystem::Cp(), thermo< Thermo, Type >::cp(), liquidMixtureProperties::Cp(), multiphaseInterSystem::Cp(), phaseModel::Cp(), heThermo< BasicThermo, MixtureType >::Cp(), solidMixtureProperties::Cp(), Cv(), setFlow::execute(), energyTransport::execute(), multiphaseInterSystem::gamma(), thermo< Thermo, Type >::gamma(), ReynoldsAnalogy::htc(), waveMakerPointPatchVectorField::initialiseGeometry(), waveModel::initialiseGeometry(), heThermo< BasicThermo, MixtureType >::kappa(), heThermo< BasicThermo, MixtureType >::kappa(), constTransport< Thermo >::kappa(), WLFTransport< Thermo >::kappa(), multiphaseInterSystem::kappaEff(), multiphaseInterSystem::kappaEff(), heThermo< BasicThermo, MixtureType >::kappaEff(), heThermo< BasicThermo, MixtureType >::kappaEff(), ThermoParcel< ParcelType >::readFields(), ThermoParcel< ParcelType >::readObjects(), eConstThermo< EquationOfState >::S(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), energySpectrum::write(), ThermoParcel< ParcelType >::writeFields(), and ThermoParcel< ParcelType >::writeObjects().
Cv
const volScalarField& Cv = tCv()
Definition at line 8 of file EEqn.H.
Referenced by Cp(), multiphaseInterSystem::Cv(), heThermo< BasicThermo, MixtureType >::Cv(), thermo< Thermo, Type >::cv(), multiphaseInterSystem::Cv(), multiphaseInterSystem::gamma(), and sutherlandTransport< Thermo >::kappa().
gamma
const scalar gamma = max(Cp/Cv).value()
Definition at line 9 of file EEqn.H.
Referenced by P1::calculate(), LiquidEvapFuchsKnudsen< CloudType >::calculate(), ORourkeCollision< CloudType >::collideSorted(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), absoluteInternalEnergy< Thermo >::CpByCpv(), sensibleInternalEnergy< Thermo >::CpByCpv(), laplacianScheme< Type >::facLaplacian(), gaussLaplacianScheme< Type >::facLaplacian(), laplacianScheme< Type >::famLaplacian(), gaussLaplacianScheme< Type >::famLaplacian(), laplacianScheme< Type, GType >::fvcLaplacian(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), relaxedNonOrthoGaussLaplacianScheme< Type, GType >::fvcLaplacian(), laplacianScheme< Type, GType >::fvmLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), relaxedNonOrthoGaussLaplacianScheme< Type, GType >::fvmLaplacian(), heThermo< BasicThermo, MixtureType >::gamma(), multiphaseInterSystem::gamma(), heThermo< BasicThermo, MixtureType >::gamma(), chemPointISAT< CompType, ThermoType >::grow(), if(), Foam::fac::laplacian(), Foam::fam::laplacian(), Foam::fac::laplacian(), Foam::fam::laplacian(), Foam::fac::laplacian(), Foam::fac::laplacian(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), Foam::fvc::laplacian(), Foam::fvc::laplacian(), Foam::fac::laplacian(), Foam::fam::laplacian(), Foam::fac::laplacian(), Foam::fam::laplacian(), Foam::fac::laplacian(), Foam::fac::laplacian(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), Foam::fvc::laplacian(), Foam::fvc::laplacian(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), Foam::fvc::laplacian(), Foam::fvc::laplacian(), LBFGS::LBFGSUpdate(), barotropicCompressibilityModel::New(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), PPCG::scalarSolveCG(), rodas23::solve(), rodas34::solve(), Rosenbrock12::solve(), Rosenbrock23::solve(), Rosenbrock34::solve(), MarshakRadiationFvPatchScalarField::updateCoeffs(), MarshakRadiationFixedTemperatureFvPatchScalarField::updateCoeffs(), outletMachNumberPressureFvPatchScalarField::updateCoeffs(), and adjointkOmegaSST::updatePrimalRelatedFields().
thermoDict
const dictionary& thermoDict = thermo.subDict("mixture")
Definition at line 16 of file EEqn.H.
Referenced by chemkinReader::chemkinReader(), chemistryReader< ThermoType >::New(), basicThermo::New(), basicThermo::New(), basicSolidChemistryModel::New(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel(), pureMixture< ThermoType >::read(), pureZoneMixture< ThermoType >::read(), egrMixture< ThermoType >::read(), homogeneousMixture< ThermoType >::read(), inhomogeneousMixture< ThermoType >::read(), multiComponentMixture< ThermoType >::read(), singleComponentMixture< ThermoType >::read(), and veryInhomogeneousMixture< ThermoType >::read().
eosDict
const dictionary& eosDict = thermoDict.subDict("equationOfState")
Definition at line 18 of file EEqn.H.
Referenced by if().
local
bool local = eosDict.getOrDefault("local", false)
Definition at line 20 of file EEqn.H.
Referenced by coordinateScaling< scalar >::coordinateScaling(), fileOperation::detectProcessorPath(), fileOperation::filePath(), coordinateSystem::globalPosition(), coordinateSystem::globalPosition(), coordinateSystem::globalVector(), coordinateSystem::globalVector(), IOobjectList::IOobjectList(), cylindrical::localToGlobal(), indirect::localToGlobal(), cylindrical::localToGlobal(), indirect::localToGlobal(), fileOperation::lookupAndCacheProcessorsPath(), DimensionedField< Type, GeoMesh >::New(), GeometricField< Type, PatchField, GeoMesh >::New(), GeometricField< Type, PatchField, GeoMesh >::New(), GeometricField< Type, PatchField, GeoMesh >::New(), IOobject::objectRelPath(), IOobject::path(), IOobject::path(), PatchTools::pointNormals(), fileOperation::readObjects(), masterUncollatedFileOperation::readObjects(), uncollatedFileOperation::readObjects(), masterUncollatedFileOperation::readStream(), uncollatedFileOperation::readStream(), fileOperation::splitProcessorPath(), masterUncollatedFileOperation::sync(), coordinateScaling< Type >::transform(), continuityError::write(), and decomposedBlockData::writeData().
else
else
Initial value:
{
        const volScalarField& T0 = T.oldTime()
Definition at line 33 of file EEqn.H.
p0
const volScalarField& p0 = p.oldTime()
Definition at line 36 of file EEqn.H.
Referenced by triangle< Point, PointRef >::areaNormal(), line< Point, PointRef >::box(), triangle< Point, PointRef >::box(), tetrahedron< Point, PointRef >::box(), FitData< FitDataType, ExtendedStencil, Polynomial >::calcFit(), CentredFitSnGradData< Polynomial >::calcFit(), triSurfaceTools::calcInterpolationWeights(), triangle< Point, PointRef >::centre(), PatchTools::checkOrientation(), SprayParcel< ParcelType >::chi(), polyLine::concat(), coordinateScaling< scalar >::coordinateScaling(), noiseFFT::dbToPa(), noiseFFT::dbToPa(), pointNoise::filterTimeData(), searchableSurfacesQueries::findAnyIntersection(), InjectionModel< CloudType >::findCellAtPosition(), refinementSurfaces::findHigherIntersection(), searchableExtrudedCircle::findParametricNearest(), Foam::getTetCutIndex(), if(), triangle2D::interArea(), triangleFuncs::intersectBb(), Foam::linearWeight(), FitData< CentredFitData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::movePoints(), sumParticleOp< VOFParticle >::operator()(), BSpline::position(), CatmullRomSpline::position(), polyLine::position(), InjectionModel< Foam::KinematicCloud< Foam::DSMCCloud > >::prepareForNextTimeStep(), noiseFFT::PSD(), noiseFFT::PSD(), Foam::quadraticWeight(), ReactingMultiphaseCloud< Foam::DSMCCloud >::ReactingMultiphaseCloud(), ReactingMultiphaseParcel< ParcelType >::readObjects(), ConeNozzleInjection< CloudType >::setProperties(), tetDecomposer::setRefinement(), noiseFFT::SPL(), surfaceFeatures::subsetPlane(), tetCell::tetCell(), tetPoints::tetPoints(), triFace::triFace(), triPoints::triPoints(), triangle< Point, PointRef >::unitNormal(), fanPressureFvPatchScalarField::updateCoeffs(), rotatingTotalPressureFvPatchScalarField::updateCoeffs(), totalPressureFvPatchScalarField::updateCoeffs(), uniformTotalPressureFvPatchScalarField::updateCoeffs(), cuttingSurfaceBase::walkCellCuts(), STLtriangle::write(), STLtriangle::write(), ReactingHeterogeneousParcel< ParcelType >::writeFields(), ReactingMultiphaseParcel< ParcelType >::writeFields(), OBJstream::writeLine(), coupledPolyPatch::writeOBJ(), ReactingHeterogeneousParcel< ParcelType >::writeObjects(), and ReactingMultiphaseParcel< ParcelType >::writeObjects().
he
he = thermo.he(p, pow(p/p0, (gamma - scalar(1))/gamma)*T0)
Definition at line 38 of file EEqn.H.
psi
psi = 1.0/((Cp - Cv)*T)
Definition at line 43 of file EEqn.H.
rho
rho = thermo.rho()
Definition at line 45 of file EEqn.H.