OpenFOAM: applications/solvers/compressible/rhoPimpleAdiabaticFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volVectorField HbyA ("HbyA", U)
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho)/fvc::interpolate(UEqn.A()))
surfaceVectorField rhoHbyAf ("rhoHbyAf", fvc::interpolate(rho) *fvc::interpolate(U)+rhorAUf *fvc::interpolate(fvc::grad(p)))
if (pimple.nCorrPISO()<=1)
if (pimple.transonic())
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
while (pimple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
Variables
HbyA = rAU*UEqn.H()
else
phiByRho = phi/fvc::interpolate(rho)
U = HbyA - rAU*fvc::grad(p)
rho = thermo.rho()
Function Documentation
HbyA()
volVectorField HbyA ("HbyA" , U)
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho)/fvc::interpolate(UEqn.A()))
rhoHbyAf()
surfaceVectorField rhoHbyAf ("rhoHbyAf" , fvc::interpolate(rho) *fvc::interpolate(U)+rhorAUf *fvc::interpolate(fvc::grad(p)))
if() [1/2]
if (pimple.nCorrPISO()<= 1)
Definition at line 26 of file pEqn.H.
References tUEqn().
if() [2/2]
if (pimple. transonic())
Definition at line 31 of file pEqn.H.
References args, and argList::executable().
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
while()
while (pimple. correctNonOrthogonal())
Definition at line 54 of file pEqn.H.
References fvOptions, mesh, p, phi, phiHbyA, pimple, psi, rho, and rhorAUf().
relax()
p relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
Variable Documentation
HbyA
HbyA = rAU*UEqn.H()
Definition at line 4 of file pEqn.H.
else
else
Initial value:
{
        surfaceScalarField phiHbyA
        (
            "phiHbyA",
            (
                (rhoHbyAf & mesh.Sf())
              + rhorAUf*fvc::interpolate(rho)*fvc::ddtCorr(U, phiByRho)
              + fvc::interpolate(rho)
              * fvc::alphaCorr(U, phiByRho, pimple.finalInnerIter())
            )
        )
Definition at line 37 of file pEqn.H.
phiByRho
phiByRho = phi/fvc::interpolate(rho)
Definition at line 76 of file pEqn.H.
U
U = HbyA - rAU*fvc::grad(p)
Definition at line 84 of file pEqn.H.
rho
rho = thermo.rho()
Definition at line 89 of file pEqn.H.