OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToVTK/convertSurfaceFields.H File Reference
convertSurfaceFields.H File Reference
Functions
if (doSurfaceFields)
if (!selectedFaceZones.empty() &&!mesh.faceZones().empty())
Variables
label nSurfaceScalarField = -1
label nSurfaceVectorField = -1
PtrList< const surfaceScalarField > sScalars
PtrList< const surfaceVectorField > sVectors
Detailed Description
Original source file convertSurfaceFields.H
Definition in file convertSurfaceFields.H.
Function Documentation
if() [1/2]
if (doSurfaceFields)
Definition at line 32 of file convertSurfaceFields.H.
References args, fld(), mesh, nSurfaceScalarField, nSurfaceVectorField, outputName(), regionDir, argList::relativePath(), regIOobject::rename(), PtrList< T >::set(), sScalars, sVectors, and writer().
if() [2/2]
if (!selectedFaceZones. empty) &&!mesh.faceZones().empty()
Definition at line 134 of file convertSurfaceFields.H.
References args, fld(), mesh, nSurfaceScalarField, nSurfaceVectorField, outputName(), pp(), regionDir, argList::relativePath(), sScalars, sVectors, and writer().
Variable Documentation
nSurfaceScalarField
label nSurfaceScalarField = -1
Definition at line 25 of file convertSurfaceFields.H.
Referenced by if(), and if().
nSurfaceVectorField
label nSurfaceVectorField = -1
Definition at line 26 of file convertSurfaceFields.H.
Referenced by if(), and if().
sScalars
PtrList<const surfaceScalarField> sScalars
Definition at line 28 of file convertSurfaceFields.H.
Referenced by if(), and if().
sVectors
PtrList<const surfaceVectorField> sVectors
Definition at line 29 of file convertSurfaceFields.H.
Referenced by if(), and if().