OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToVTK/convertProcessorPatches.H File Reference
convertProcessorPatches.H File Reference
Functions
fileName vtmOutputBase (outputDir/regionDir/vtkName+timeDesc)
forAll (patchIds, i)
patchWriters resize (patchIds.size())
List< wordList > procPatchNames (UPstream::nProcs())
for (const label patchId :patchIds)
patchWriters resize (nPatchWriters)
if (internalWriter)
for (vtk::patchWriter &writer :patchWriters)
patchWriters clear ()
if (UPstream::master() &&nProcPatches)
Variables
const label nVolFields
const auto subDirNaming
autoPtr< vtk::internalWriter > internalWriter
PtrList< vtk::patchWriter > patchWriters
const polyBoundaryMesh & patches = mesh.boundaryMesh()
labelList patchIds
label nPatchWriters = 0
const label nProcPatches = returnReduce(nPatchWriters, sumOp<label>())
Detailed Description
Original source file convertProcessorPatches.H
Definition in file convertProcessorPatches.H.
Function Documentation
vtmOutputBase()
fileName vtmOutputBase (outputDir/regionDir/vtkName+ timeDesc)
Referenced by for(), if(), and vtkWrite::write().
forAll()
forAll (patchIds , i)
Definition at line 63 of file convertProcessorPatches.H.
References patches, and patchIds.
resize() [1/2]
patchWriters resize (patchIds. size())
Referenced by bitSet::andEq(), bitSet::assign(), HashTable< T, Key, Hash >::clearStorage(), List< CloudFunctionObject< CloudType > * >::clone(), DynamicList< T, SizeMin >::emplace_back(), List< T >::emplace_back(), DynamicField< T, SizeMin >::emplace_back(), HashTable< T * >::erase(), Field< T >::Field(), topoSet::invert(), List< T >::newElmt(), DynamicList< T, SizeMin >::operator()(), DynamicField< T, SizeMin >::operator()(), PtrList< T >::operator=(), HashTable< T, Key, Hash >::operator=(), bitSet::orEq(), PackedList< Width >::pop_back(), DynamicList< T, SizeMin >::pop_back(), PtrDynList< T, SizeMin >::pop_back(), DynamicField< T, SizeMin >::pop_back(), DynamicList< T, SizeMin >::push_back(), List< T >::push_back(), DynamicList< T, SizeMin >::push_back(), DynamicList< T, SizeMin >::push_back(), DynamicField< T, SizeMin >::push_back(), DynamicList< T, SizeMin >::push_back(), DynamicField< T, SizeMin >::push_back(), DynamicList< T, SizeMin >::push_back(), PtrDynList< T, SizeMin >::push_back(), PtrDynList< T, SizeMin >::push_back(), DynamicList< T, SizeMin >::push_back(), DynamicList< T, SizeMin >::push_back(), DynamicField< T, SizeMin >::push_back(), PtrDynList< T, SizeMin >::push_back(), List< CloudFunctionObject< CloudType > * >::push_uniq(), PackedList< Width >::remove(), optionList::reset(), MRFZoneList::reset(), porosityModelList::reset(), DynamicList< T, SizeMin >::resize(), DynamicField< T, SizeMin >::resize(), SquareMatrix< Type >::resize(), SquareMatrix< Type >::resize(), IjkField< Type >::resize(), PtrDynList< T, SizeMin >::set(), PackedList< Width >::set(), bitSet::set(), SquareMatrix< Type >::setSize(), Matrix< Form, Type >::setSize(), CompactListList< T >::setSize(), CompactListList< T >::setSize(), CompactListList< T >::setSize(), CompactListList< T >::setSize(), HashTable< T * >::sorted(), PackedList< 1 >::transfer(), bitSet::unset(), and bitSet::xorEq().
procPatchNames()
List< wordList > procPatchNames (UPstream::nProcs())
Referenced by for(), and if().
for() [1/2]
for (const label patchId :patchIds)
Definition at line 79 of file convertProcessorPatches.H.
References nPatchWriters, patches, patchId(), patchWriters, pp(), procPatchNames(), subDirNaming, vtmOutputBase(), and writer().
resize() [2/2]
patchWriters resize (nPatchWriters)
if() [1/2]
if (internalWriter)
Definition at line 145 of file convertProcessorPatches.H.
References internalWriter.
for() [2/2]
for (vtk::patchWriter &writer :patchWriters)
Definition at line 150 of file convertProcessorPatches.H.
References writer().
clear()
patchInterps clear ()
Referenced by exprDriver::addVariables(), exprDriver::addVariables(), faPatchData::assign(), bitSet::assign(), faPatchData::assign_coupled(), HashTable< T, Key, Hash >::clearStorage(), ensightMesh::correct(), ensightFaMesh::correct(), refPtr< T >::cref(), refPtr< T >::cref(), tmp< T >::cref(), refPtr< T >::cref(), tmp< T >::cref(), tmp< T >::cref(), fieldExpression::execute(), fieldsExpression::execute(), ensightMesh::expire(), exprResult::getResult(), topoSet::invert(), refPtr< Field< Type > >::is_pointer(), seriesWriter::load(), mergedSurf::merge(), CircularBuffer< T >::operator=(), dictionary::operator=(), exprResult::operator=(), ILList< LListBase, T >::operator=(), LList< LListBase, T >::operator=(), LPtrList< LListBase, T >::operator=(), Matrix< Form, Type >::operator=(), MeshedSurface< Face >::operator=(), refPtr< Field< Type > >::operator=(), refPtr< T >::operator=(), tmp< T >::operator=(), UnsortedMeshedSurface< Face >::operator=(), DynamicList< T, SizeMin >::operator=(), DynamicList< T, SizeMin >::operator=(), exprResult::operator=(), ILList< LListBase, T >::operator=(), keyType::operator=(), DynamicList< T, SizeMin >::operator=(), LList< LListBase, T >::operator=(), regExpCxx::operator=(), regExpPosix::operator=(), SortableList< T >::operator=(), HashTable< T, Key, Hash >::operator=(), LList< LListBase, T >::operator=(), tmp< T >::operator=(), wordRe::operator=(), PackedList< Width >::pop_back(), DynamicList< T, SizeMin >::pop_back(), PtrDynList< T, SizeMin >::pop_back(), DynamicField< T, SizeMin >::pop_back(), ILList< ParticleType >::pop_front(), List< CloudFunctionObject< CloudType > * >::push_back(), schemesLookup::read(), extendedEdgeMeshFormat::read(), extendedFeatureEdgeMeshFormat::read(), NASedgeFormat::read(), ABAQUSsurfaceFormat< Face >::read(), AC3DsurfaceFormat< Face >::read(), GTSsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OBJsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), STLsurfaceFormat< Face >::read(), TRIsurfaceFormat< Face >::read(), VTKsurfaceFormat< Face >::read(), edgeMeshFormat::read(), OBJedgeFormat::read(), STARCDedgeFormat::read(), MeshedSurface< Face >::read(), UnsortedMeshedSurface< Face >::read(), MeshedSurface< Face >::read(), UnsortedMeshedSurface< Face >::read(), ABAQUSCore::readHelper::read(), boundaryRegion::readDict(), cellTable::readDict(), exprString::readEntry(), Matrix< Form, Type >::readMatrix(), fvBoundaryMesh::readUpdate(), refPtr< T >::ref(), tmp< T >::ref(), refPtr< T >::ref(), tmp< T >::ref(), Matrix< Form, Type >::release(), faMeshSubset::reset(), fvMeshSubset::reset(), fvMeshSubset::reset(), fvMeshSubset::reset(), dynamicCode::reset(), faFieldDecomposer::reset(), faMeshSubset::reset(), fvMeshSubset::reset(), fvFieldDecomposer::reset(), faFieldDecomposer::reset(), fvFieldDecomposer::reset(), pointFieldDecomposer::reset(), refPtr< T >::reset(), tmp< T >::reset(), exprResult::resetImpl(), CompactListList< T >::resize(), HashTable< T, Key, Hash >::retain(), ocountstream::rewind(), scalarRange::scalarRange(), seriesWriter::scan(), SHA1Digest::SHA1Digest(), SHA1Digest::SHA1Digest(), SHA1Digest::SHA1Digest(), HashTable< T, Key, Hash >::transfer(), List< T >::transfer(), LList< LListBase, T >::transfer(), LPtrList< LListBase, T >::transfer(), Matrix< Form, Type >::transfer(), UnsortedMeshedSurface< Face >::transfer(), MeshedSurface< Face >::transfer(), UnsortedMeshedSurface< Face >::transfer(), memInfo::update(), vtuSizing::vtuSizing(), vtuSizing::vtuSizing(), JobInfo::write(), CStringList::~CStringList(), HashTable< T, Key, Hash >::~HashTable(), ILList< LListBase, T >::~ILList(), LList< LListBase, T >::~LList(), MeshedSurface< Face >::~MeshedSurface(), MeshedSurfaceIOAllocator::~MeshedSurfaceIOAllocator(), regExpPosix::~regExpPosix(), and tmp< T >::~tmp().
if() [2/2]
if (UPstream::master() && nProcPatches)
Definition at line 162 of file convertProcessorPatches.H.
References forAll, n, Foam::name(), nProcPatches, outputName(), procPatchNames(), subDirNaming, vtmBoundaries, and vtmOutputBase().
Variable Documentation
nVolFields
const label nVolFields
Initial value:
=
    (
        objects.count(stringListOps::foundOp<word>(fieldTypes::volume))
    )
Definition at line 28 of file convertProcessorPatches.H.
Referenced by vtkWrite::write().
subDirNaming
const auto subDirNaming
Initial value:
=
        [](const label i) -> fileName
        { return "processor" / ("processor" + Foam::name(i)); }
Definition at line 43 of file convertProcessorPatches.H.
Referenced by for(), and if().
internalWriter
autoPtr<vtk::internalWriter> internalWriter
Definition at line 49 of file convertProcessorPatches.H.
Referenced by if(), vtkWrite::write(), Foam::writeAllDimFields(), Foam::writeAllDimFields(), Foam::writeAllPointFields(), Foam::writeAllVolFields(), Foam::writeDimFields(), Foam::writeDimFields(), Foam::writePointField(), Foam::writePointFields(), Foam::writeVolFields(), Foam::writeVolFields(), vtkWrite::writeVolFieldsImpl(), and vtkWrite::writeVolFieldsImpl().
patchWriters
PtrList<vtk::patchWriter> patchWriters
Definition at line 52 of file convertProcessorPatches.H.
Referenced by for(), vtkWrite::write(), Foam::writeAllPointFields(), Foam::writeAllVolFields(), Foam::writePointField(), Foam::writePointFields(), Foam::writeVolFields(), Foam::writeVolFields(), vtkWrite::writeVolFieldsImpl(), and vtkWrite::writeVolFieldsImpl().
patches
const polyBoundaryMesh& patches = mesh.boundaryMesh()
Definition at line 54 of file convertProcessorPatches.H.
Referenced by isoSurfacePoint::adaptPatchFields(), fvMeshAdder::add(), columnFvMeshInfo::addLocalPatches(), polyTopoChange::addMesh(), cellToCellStencil::allCoupledFacesPatch(), cellToFaceStencil::allCoupledFacesPatch(), zoneCellStencils::allCoupledFacesPatch(), assemblyFaceAreaPairGAMGAgglomeration::assemblyFaceAreaPairGAMGAgglomeration(), patchMeshWriter::beginPiece(), meshRefinement::blockLeakFaces(), decompositionMethod::calcCellCells(), decompositionMethod::calcCellCells(), addPatchCellLayer::calcExtrudeInfo(), cellToFaceStencil::calcFaceStencil(), polyDualMesh::calcFeatures(), solarLoad::calculate(), processorColour::cellColour(), repatchPolyTopoChanger::changePatches(), repatchPolyTopoChanger::changePatches(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceSkewness(), polyMeshGeometry::checkFaceTets(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), hexRef8::checkMesh(), polyMeshGeometry::checkVolRatio(), polyBoundaryMesh::clearAddressing(), polyBoundaryMesh::clearGeom(), processorColour::colour(), adjointEikonalSolver::computeYPhi(), LRR< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::correct(), directionalMeshWave::correct(), advectionDiffusion::correct(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), ReynoldsStress< BasicTurbulenceModel >::correctWallShearStress(), decompositionMethod::decompose(), faMeshDecomposition::decomposeMesh(), fvMeshDistribute::distribute(), distributedTriSurfaceMesh::distribute(), snappyRefineDriver::doRefine(), faBoundaryMesh::edgeFaces(), faBoundaryMesh::edgeLabels(), wallHeatFlux::execute(), yPlus::execute(), extendedCellToCellStencil::extendedCellToCellStencil(), extendedCellToFaceStencil::extendedCellToFaceStencil(), extendedFaceToCellStencil::extendedFaceToCellStencil(), faBoundaryMeshMapper::faBoundaryMeshMapper(), fvBoundaryMesh::faceCells(), polyBoundaryMesh::faceCells(), faMeshMapper::faMeshMapper(), localPointRegion::findDuplicateFacePairs(), polyMeshTetDecomposition::findFaceBasePts(), fvBoundaryMesh::findPatchID(), polyBoundaryMesh::findPatchIDs(), for(), forAll(), FreeStream< CloudType >::FreeStream(), fvBoundaryMeshMapper::fvBoundaryMeshMapper(), removeCells::getExposedFaces(), GenericPatchGeoFieldsWriter< PatchType >::getFaceField(), syncTools::getInternalOrCoupledFaces(), syncTools::getInternalOrMasterFaces(), syncTools::getMasterFaces(), combineFaces::getMergeSets(), externalDisplacementMeshMover::getPatch(), surfaceFormatsCore::getSelectedPatches(), globalIndexAndTransform::globalIndexAndTransform(), hexCellFvMesh::hexCellFvMesh(), viewFactor::initialise(), PDRblock::innerMesh(), faBoundaryMesh::interfaces(), fvBoundaryMesh::interfaces(), isoSurfacePoint::isoSurfacePoint(), triSurfaceLoader::load(), localPointRegion::localPointRegion(), patchMeanVelocityForce::magUbarAve(), meshRefinement::makePatch(), volSurfaceMapping::mapInternalToSurface(), meshRefinement::mergePatchFaces(), meshRefinement::mergePatchFacesUndo(), meshRefinement::meshedPatches(), fvBoundaryMesh::movePoints(), processorTopology::New(), age::newField(), faMeshTools::newMesh(), faBoundaryMesh::nNonProcessor(), polyBoundaryMesh::nNonProcessor(), meshSearch::nonCoupledBoundaryTree(), zoneCellStencils::nonEmptyFacesPatch(), faBoundaryMesh::nProcessorPatches(), polyBoundaryMesh::nProcessorPatches(), JohnsonJacksonSchaeffer::nu(), Schaeffer::nu(), polyBoundaryMesh::patchID(), faBoundaryMesh::patchRanges(), faBoundaryMesh::patchStarts(), pointBoundaryMeshMapper::pointBoundaryMeshMapper(), polyBoundaryMesh::polyBoundaryMesh(), faMeshTools::printMeshChecks(), fvMeshDistribute::printMeshInfo(), contactHeatFluxSource::read(), externalFileSource::read(), triSurfaceMesh::regions(), polyBoundaryMesh::reorder(), snappySnapDriver::repatchToSurface(), patchProbes::sample(), patchProbes::sample(), motionSmootherAlgo::scaleMesh(), faBoundaryMesh::setGroup(), polyBoundaryMesh::setGroup(), lumpedPointDisplacementPointPatchVectorField::setPatchControls(), removeCells::setRefinement(), addPatchCellLayer::setRefinement(), perfectInterface::setRefinement(), meshCutAndRemove::setRefinement(), removeFaces::setRefinement(), combineFaces::setRefinement(), duplicatePoints::setRefinement(), perfectInterface::setRefinement(), shapeOptimisation::shapeOptimisation(), triSurface::sortedZones(), oversetFvPatchField< Type >::storeFringeCoefficients(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), syncTools::syncPointMap(), meshRefinement::testSyncBoundaryFaceList(), triSurface::transfer(), liquidFilmBase::Up(), oversetFvMeshBase::updateAddressing(), motionSmootherAlgo::updateMesh(), liquidFilmBase::Uw(), cellToCellStencil::validBoundaryFaces(), cellToFaceStencil::validBoundaryFaces(), zoneCellStencils::validBoundaryFaces(), wallLayerCells::wallLayerCells(), streamLineBase::wallPatch(), polyBoundaryMesh::whichPatchFace(), wallShearStress::write(), yPlus::write(), vtkWrite::write(), faBoundaryMesh::writeData(), polyBoundaryMesh::writeData(), patchMeshWriter::writeNeighIDs(), patchMeshWriter::writePatchIDs(), patchMeshWriter::writePoints(), patchMeshWriter::writePolys(), patchMeshWriter::writePolysLegacy(), writer::writeSolution(), lumpedPointMovement::writeVTP(), lumpedPointMovement::writeZonesVTP(), wallLubricationModel::zeroGradWalls(), and meshRefinement::zonify().
patchIds
labelList patchIds
Initial value:
=
        identity
        (
            patches.size()-patches.nNonProcessor(),
            patches.nNonProcessor()
        )
Definition at line 56 of file convertProcessorPatches.H.
Referenced by ensightMesh::correct(), injectionModelList::correct(), forAll(), GeometricBoundaryField< symmTensor, fvPatchField, volMesh >::GeometricBoundaryField(), if(), filmTurbulenceModel::primaryRegionFriction(), vtkWrite::write(), lumpedPointMovement::writeVTP(), and lumpedPointMovement::writeZonesVTP().
nPatchWriters
label nPatchWriters = 0
Definition at line 74 of file convertProcessorPatches.H.
Referenced by for(), if(), and vtkWrite::write().
nProcPatches
const label nProcPatches = returnReduce(nPatchWriters, sumOp<label>())
Definition at line 160 of file convertProcessorPatches.H.
Referenced by faMeshDecomposition::decomposeMesh(), if(), and faMeshDecomposition::writeDecomposition().