OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/include/correctThermos.H File Reference
correctThermos.H File Reference
Functions
forAll (fluidRegions, i)
forAll (solidRegions, i)
Function Documentation
forAll() [1/2]
forAll (fluidRegions , i)
Definition at line 1 of file correctThermos.H.
References fluidFvOptions(), fvOptions, he, rad, radiation(), and thermoFluid().
forAll() [2/2]
forAll (solidRegions , i)
Definition at line 12 of file correctThermos.H.
References fvOptions, h, solidHeatSources(), and thermos().