OpenFOAM: src/overset/include/correctPhiFaceMask.H File Reference
correctPhiFaceMask.H File Reference
Correct phi on new faces C-I faces.
Functions
surfaceScalarField faceMaskOld (localMin< scalar >(mesh).interpolate(cellMask.oldTime()))
Variables
Uf * Uf = (1-faceMaskOld)*fvc::interpolate(U)
phi = mesh.Sf() & Uf
Detailed Description
Correct phi on new faces C-I faces.
Original source file correctPhiFaceMask.H
Definition in file correctPhiFaceMask.H.
Function Documentation
faceMaskOld()
surfaceScalarField faceMaskOld (localMin< scalar > mesh).interpolate(cellMask.oldTime())
Variable Documentation
Uf
Uf* Uf = (1-faceMaskOld)*fvc::interpolate(U)
Definition at line 33 of file correctPhiFaceMask.H.
phi
phi = mesh.Sf() & Uf
Definition at line 34 of file correctPhiFaceMask.H.
Referenced by extractEulerianParticles::accumulateParticleInfo(), ATCstandard::addATC(), ATCUaGradU::addATC(), fanMomentumSource::addSup(), fanMomentumSource::addSup(), Foam::adjustPhi(), waveTransmissiveFvPatchField< Type >::advectionSpeed(), MassTransferPhaseSystem< BasePhaseSystem >::alphaTransfer(), Implicit< CloudType >::cacheFields(), curvatureSeparation::calcCosAngle(), curvatureSeparation::calcCosAngle(), momentumError::calcMomentError(), Foam::calcTE18(), COxidationIntrinsicRate< CloudType >::calculate(), chemPointISAT< CompType, ThermoType >::checkSolution(), LarsenBorgnakkeVariableHardSphere< CloudType >::collide(), VariableHardSphere< CloudType >::collide(), simple::continuityErrors(), adjointkOmegaSST::convectionScheme(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), kL< BasicTurbulenceModel >::correct(), adjointkOmegaSST::correct(), adjointSpalartAllmaras::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), Foam::MULES::correct(), Foam::MULES::correct(), thixotropicViscosity::correct(), relaxation::correct(), curvatureSeparation::correct(), directionalPressureGradientExplicitSource::correct(), incompressiblePrimalSolver::correctBoundaryConditions(), MRFZoneList::correctBoundaryFlux(), phaseModel::correctInflowOutflow(), waxSolventEvaporation::correctModel(), Foam::CorrectPhi(), Foam::CorrectPhi(), Foam::fvc::correctRhoUf(), Foam::fvc::correctUf(), Foam::correctUphiBCs(), Foam::correctUphiBCs(), Foam::fvc::DDt(), Foam::fvc::ddtCorr(), Foam::fvc::ddtCorr(), Foam::fvc::ddtCorr(), Foam::fvc::ddtCorr(), integrationScheme::delta(), adjointkOmegaSST::dR_dF1(), Foam::eigenVectors(), effectivenessTable::energyDensity(), age::execute(), setFlow::execute(), energyTransport::execute(), scalarTransport::execute(), filmFlux::execute(), integrationScheme::explicitDelta(), Foam::MULES::explicitSolve(), PatchFlowRateInjection< CloudType >::flowRate(), Foam::fvc::flux(), Foam::fvc::flux(), Foam::fvc::flux(), Foam::fvc::flux(), for(), for(), for(), forAll(), forAll(), forAll(), forAllConstIters(), oversetFvPatchField< Type >::fringeFlux(), ddtScheme< Type >::fvcDdtPhiCoeff(), ddtScheme< Type >::fvcDdtPhiCoeff(), ddtScheme< Type >::fvcDdtPhiCoeff(), ddtScheme< Type >::fvcDdtPhiCoeff(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), boundedDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), steadyStateDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), boundedDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), steadyStateDdtScheme< Type >::fvcDdtPhiCorr(), multiphaseInterSystem::generatePhi(), zoneDistribute::getDatafromOtherProc(), zoneDistribute::getFields(), zoneDistribute::getValue(), chemPointISAT< CompType, ThermoType >::grow(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), Foam::Math::incGammaRatio_Q(), incompressibleInterPhaseTransportModel< Mixture >::incompressibleInterPhaseTransportModel(), chemPointISAT< CompType, ThermoType >::inEOA(), objectivePtLosses::initialize(), objectiveUniformityPatch::initialize(), boundedConvectionScheme< Type >::interpolate(), interpolationCellPointFace< Type >::interpolate(), Foam::MULES::limit(), Foam::MULES::limit(), Foam::MULES::limitCorr(), Foam::limiter(), LimitedScheme< Type, Limiter, LimitFunc >::limiter(), PhiScheme< Type, PhiLimiter >::limiter(), Foam::MULES::limiterCorr(), adjointSimple::mainIter(), simple::mainIter(), MRFZone::makeAbsolute(), MRFZoneList::makeAbsolute(), MRFZone::makeAbsolute(), MRFZoneList::makeAbsolute(), Foam::fvc::makeAbsolute(), Foam::fvc::makeAbsolute(), Foam::fvc::makeAbsolute(), MRFZone::makeRelative(), MRFZoneList::makeRelative(), MRFZone::makeRelative(), MRFZone::makeRelative(), MRFZone::makeRelative(), MRFZoneList::makeRelative(), Foam::fvc::makeRelative(), Foam::fvc::makeRelative(), Foam::fvc::makeRelative(), dynamicRefineFvMesh::mapFields(), backwardDdtScheme< Type >::meshPhi(), CrankNicolsonDdtScheme< Type >::meshPhi(), momentumError::momentumError(), MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransfer(), fvMotionSolverEngineMesh::move(), layeredEngineMesh::move(), PhaseIncompressibleTurbulenceModel< TransportModel >::New(), Foam::incompressible::New(), CompressibleTurbulenceModel< TransportModel >::New(), ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::New(), Foam::compressible::New(), IncompressibleTurbulenceModel< TransportModel >::New(), Foam::incompressible::New(), viscosityModel::New(), reconstructionSchemes::New(), magSqr< Type >::operator()(), rhoMagSqr< Type >::operator()(), null< Type >::operator()(), magSqr< Type >::operator()(), rhoMagSqr< Type >::operator()(), magSqr< Type >::operator()(), magSqr< Type >::operator()(), Foam::oversetAdjustPhi(), Foam::oversetPatchPhiErr(), integrationScheme::partialDelta(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFfs(), extractEulerianParticles::phiU(), randomCoalescence::R(), wakeEntrainmentCoalescence::R(), multiphaseSystem::solveAlphas(), thermalBaffle::solveEnergy(), reactingOneDim::solveSpeciesMass(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi(), fluxSummary::surfaceModeWrite(), searchableSphere::surfaceNormal(), searchableSphere::surfacePoint(), ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::ThermalDiffusivity(), cutFaceAdvect::timeIntegratedFaceFlux(), cutFaceAdvect::timeIntegratedFaceFlux(), dynamicRefineFvMesh::unrefine(), interfaceTrackingFvMesh::update(), rawTopoChangerFvMesh::update(), ETAB< CloudType >::update(), TAB< CloudType >::update(), mappedFlowRateFvPatchVectorField::updateCoeffs(), outletMappedUniformInletFvPatchField< Type >::updateCoeffs(), plenumPressureFvPatchScalarField::updateCoeffs(), pressurePIDControlInletVelocityFvPatchVectorField::updateCoeffs(), swirlFlowRateInletVelocityFvPatchVectorField::updateCoeffs(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), filmPyrolysisVelocityCoupledFvPatchVectorField::updateCoeffs(), outletMachNumberPressureFvPatchScalarField::updateCoeffs(), outletMappedUniformInletHeatAdditionFvPatchField::updateCoeffs(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), ATCstandard::updatePrimalBasedQuantities(), prghPermeableAlphaTotalPressureFvPatchScalarField::updateSnGrad(), Implicit< CloudType >::velocityCorrection(), extendedUpwindCellToFaceStencil::weightedSum(), faNVDscheme< Type, NVDweight >::weights(), limitedSurfaceInterpolationScheme< Type >::weights(), while(), while(), while(), while(), fluxSummary::write(), and MRFZone::zero().