OpenFOAM: src/overset/include/correctRhoPhiFaceMask.H File Reference
correctRhoPhiFaceMask.H File Reference
Correct phi on new faces C-I faces.
Functions
const surfaceScalarField faceMaskOld (localMin< scalar >(mesh).interpolate(cellMask.oldTime()))
rhoUf () *
surfaceVectorField rhoUfint (fvc::interpolate(rho *U))
forAll (rhoUf().boundaryField(), patchI)
Variables
phi = mesh.Sf() & rhoUf()
Detailed Description
Correct phi on new faces C-I faces.
Original source file correctRhoPhiFaceMask.H
Definition in file correctRhoPhiFaceMask.H.
Function Documentation
faceMaskOld()
const surfaceScalarField faceMaskOld (localMin< scalar > mesh).interpolate(cellMask.oldTime())
rhoUf()
rhoUf ()
Definition at line 27 of file createRhoUfIfPresent.H.
Referenced by Foam::fvc::correctRhoUf(), forAll(), if(), and if().
rhoUfint()
surfaceVectorField rhoUfint (fvc::interpolate(rho *U))
Referenced by forAll().
forAll()
forAll (rhoUf().boundaryField() , patchI)
Definition at line 39 of file correctRhoPhiFaceMask.H.
References rhoUf(), and rhoUfint().
Variable Documentation
phi
phi = mesh.Sf() & rhoUf()
Definition at line 45 of file correctRhoPhiFaceMask.H.