OpenFOAM: src/OSspecific/POSIX/cpuInfo/cpuInfo.C File Reference
cpuInfo.C File Reference
Functions
static bool split (const std::string &line, std::string &key, std::string &val)
Detailed Description
Original source file cpuInfo.C
Definition in file cpuInfo.C.
Function Documentation
split()
static bool split (const std::string & line, std::string & key, std::string & val) static
Definition at line 32 of file cpuInfo.C.
References UPtrList< T >::begin(), PtrList< T >::clear(), and UPtrList< T >::end().
Referenced by refinementHistory::clone(), refinementHistory::compact(), refinementHistory::distribute(), meshRefinement::doSplitFaces(), face::nTrianglesQuads(), face::triangles(), and face::trianglesQuads().