OpenFOAM: src/finiteVolume/cfdTools/general/include/createK.H File Reference
createK.H File Reference
Functions
Info<< "Creating field kinetic energy K\n"<< endl;volScalarField K("K", 0.5 *magSqr(U));if(U.nOldTimes()){ volVectorField *Uold=&U.oldTime();volScalarField *Kold=&K.oldTime();*Kold==0.5 *magSqr(*Uold);while(Uold->nOldTimes()) { Uold=&Uold-> oldTime ()
Variables
Kold = &Kold->oldTime()
Function Documentation
oldTime()
rhoCp oldTime ()
Referenced by limitedSnGrad< Type >::correction(), backwardDdtScheme< Type >::meshPhi(), variablesSet::nullifyField(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFfs(), Time::setControls(), plenumPressureFvPatchScalarField::updateCoeffs(), and while().
Variable Documentation
Kold
* Kold = &Kold->oldTime()
Definition at line 13 of file createK.H.