OpenFOAM: src/OpenFOAM/include/createMesh.H File Reference
createMesh.H File Reference
Required Variables.
Functions
if (args.dryRun()||args.found("dry-run-write"))
if (args.readIfPresent("region", regionName))
Variables
Foam::autoPtr< Foam::fvMesh > meshPtr (nullptr)
Foam::word regionName (Foam::polyMesh::defaultRegion)
else
Detailed Description
Required Variables.
Original source file createMesh.H
Provided Variables
Definition in file createMesh.H.
Function Documentation
if() [1/2]
if (args. dryRun)||args.found("dry-run-write")
Definition at line 28 of file createMesh.H.
References FieldBase::allowConstructFromLargerSize, args, Foam::endl(), argList::found(), Foam::Info, meshPtr, functionObject::outputPrefix, argList::readIfPresent(), regionName, autoPtr< T >::reset(), runTime, Time::saNoWriteNow, and Time::saWriteNow.
if() [2/2]
if (args. readIfPresent"region", regionName)
Definition at line 68 of file createMesh.H.
References Foam::Info, and regionName.
Variable Documentation
meshPtr
Foam::autoPtr< Foam::fvMesh > meshPtr(nullptr) (nullptr)
Referenced by if().
regionName
Foam::word regionName(Foam::polyMesh::defaultRegion) (Foam::polyMesh::defaultRegion)
Referenced by if(), and if().
else
else
Initial value:
{
    Foam::Info << "Create mesh"
Definition at line 65 of file createMesh.H.