OpenFOAM: applications/solvers/finiteArea/liquidFilmFoam/createFvFields.H File Reference
createFvFields.H File Reference
Functions
const volSurfaceMapping vsm (aMesh)
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedVector(dimVelocity, Zero))
volScalarField H (IOobject("H", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar(dimLength, Zero))
Function Documentation
vsm()
const volSurfaceMapping vsm (aMesh)
Referenced by contactHeatFluxSource::addSup(), and sensitivitySurface::smoothSensitivities().
U()
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedVector(dimVelocity, Zero))
H()
volScalarField H (IOobject("H", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar(dimLength, Zero))
Referenced by Grimshaw::alfa(), Grimshaw::eta(), McCowan::eta(), LduMatrix< Type, DType, LUType >::H(), lduMatrix::H(), Foam::Math::incGammaRatio_Q(), McCowan::mn(), McCowan::newtonRapsonF1(), Grimshaw::Uf(), McCowan::Uf(), StokesI::UfBase(), and StokesII::UfBase().