OpenFOAM: src/dynamicFvMesh/include/createNamedDynamicFvMesh.H File Reference
createNamedDynamicFvMesh.H File Reference
Required Variables.
Functions
if (args.readIfPresent("region", regionName))
Variables
Foam::word regionName (Foam::polyMesh::defaultRegion)
Foam::autoPtr< Foam::dynamicFvMesh > meshPtr
Detailed Description
Required Variables.
Original source file createNamedDynamicFvMesh.H
Provided Variables
Definition in file createNamedDynamicFvMesh.H.
Function Documentation
if()
if (args. readIfPresent"region", regionName)
Definition at line 31 of file createNamedDynamicFvMesh.H.
References Foam::Info, and regionName.
Variable Documentation
regionName
Foam::word regionName(Foam::polyMesh::defaultRegion) (Foam::polyMesh::defaultRegion)
Referenced by fvMeshTools::createDummyFvMeshFiles(), fvExprDriver::evaluateVariableRemote(), searchableSurfaces::findSurfaceRegionID(), if(), if(), if(), function1Base::mesh(), decompositionMethod::nDomains(), functionObjectList::New(), decompositionMethod::New(), decompositionMethod::optionalRegionDict(), multiRegion::read(), multiphaseMangrovesSource::read(), multiphaseMangrovesTurbulenceModel::read(), fvExprDriver::regionMesh(), searchableSurfaceCollection::regions(), setRegistry(), fvMatrix< Type >::solver(), fvMatrix< Type >::solveSegregatedOrCoupled(), thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField(), and vtkWrite::write().
meshPtr
Foam::autoPtr<Foam::dynamicFvMesh> meshPtr
Definition at line 27 of file createNamedDynamicFvMesh.H.
Referenced by polyMeshAdder::add(), writeFile::baseFileDir(), PDRblock::innerMesh(), blockMesh::mesh(), meshReader::mesh(), FIREMeshReader::mesh(), reader::mesh(), dynamicFvMesh::New(), fvMeshTools::newMesh(), faMeshTools::newMesh(), and fvExprDriver::regionMesh().