OpenFOAM: src/engine/include/createEngineTime.H File Reference
createEngineTime.H File Reference
Functions
Info<< "Create engine time\n"<< endl;autoPtr< engineTime > runTimePtr (engineTime::New(Time::controlDictName, args.rootPath(), args.caseName()))
Variables
engineTime & runTime = runTimePtr()
Function Documentation
runTimePtr()
Info<< "Create engine time\n"<< endl;autoPtr< engineTime > runTimePtr (engineTime::New(Time::controlDictName, args.rootPath(), args.caseName()))
Variable Documentation
runTime
engineTime& runTime = runTimePtr()
Definition at line 13 of file createEngineTime.H.
Referenced by mappedPatchBase::addWorldConnection(), reconstructionSchemes::alreadyReconstructed(), meshRefinement::baffleAndSplitMesh(), columnFvMesh::columnFvMesh(), columnFvMeshInfo::columnFvMeshInfo(), thixotropicViscosity::correct(), Foam::CorrectPhi(), Foam::CorrectPhi(), CrankNicolsonDdtScheme< Type >::ddt0_(), DMD::DMD(), topoSet::findIOobject(), gravity::findObject(), coupleGroupIdentifier::findOtherPatchID(), for(), for(), for(), forAll(), forAll(), forAll(), forAll(), forAll(), forAll(), forAll(), forAll(), forAll(), forAll(), forAll(), forAll(), gravity::getObjectPtr(), mappedPatchBase::getWorldCommunicator(), hydrostaticPressure::hydrostaticPressure(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), gravity::lookupObject(), simpleControl::loop(), SIMPLEControlOpt::loop(), SIMPLEControlSingleRun::loop(), meshRefinement::mergeFreeStandingBaffles(), dynamicFvMesh::New(), functionObjectList::New(), solidBodyMotionFunction::New(), gravity::New(), multiWorldConnections::New(), simplifiedFvMesh::New(), gravity::New(), functionObject::New(), fieldValue::New(), boundaryDataSurfaceReader::readField(), SIMPLEControlSingleRun::readIters(), boundaryDataSurfaceReader::readPoints(), regionProperties::regionProperties(), SIMPLEControlOpt::resetDeltaT(), timeSelector::select0(), timeSelector::selectIfPresent(), Foam::selectReadIO(), refinementIterator::setRefinement(), setRegistry(), sigStopAtWriteNow::sigStopAtWriteNow(), sigWriteNow::sigWriteNow(), multiphaseSystem::solve(), twoPhaseSystem::solve(), UnsortedMeshedSurface< Face >::UnsortedMeshedSurface(), UnsortedMeshedSurface< Face >::UnsortedMeshedSurface(), while(), triSurfaceTools::writeCloseness(), triSurfaceTools::writeCurvature(), Foam::edgeMeshTools::writeFeatureProximity(), Foam::writeMeshObject(), triSurfaceMesh::writeObject(), and writer::writeSolution().