OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/include/createCoupledRegions.H File Reference
createCoupledRegions.H File Reference
Functions
fvSolution solutionDict (runTime)
bool coupled (solutionDict.getOrDefault("coupledEnergyField", false))
forAll (fluidRegions, i)
forAll (solidRegions, i)
if (coupled &&!fvMatrixAssemblyPtr)
Variables
autoPtr< fvMatrix< scalar > > fvMatrixAssemblyPtr
Function Documentation
solutionDict()
fvSolution solutionDict (runTime)
coupled()
bool coupled (solutionDict. getOrDefault"coupledEnergyField", false)
Referenced by meshRefinement::balance(), P1::calculate(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceTets(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceWeights(), faceZone::checkParallelSync(), polyMeshGeometry::checkVolRatio(), oversetFvMeshBase::correctCoupledBoundaryConditions(), cubic< Type >::correction(), cyclicACMIFvPatch::delta(), cyclicAMIFvPatch::delta(), faPatchData::dict(), extendedCellToCellStencil::extendedCellToCellStencil(), extendedCellToFaceStencil::extendedCellToFaceStencil(), extendedFaceToCellStencil::extendedFaceToCellStencil(), polyMeshTetDecomposition::findFaceBasePts(), forAll(), forAll(), PhiScheme< Type, PhiLimiter >::limiter(), Foam::MULES::limitSum(), Foam::MULES::limitSum(), localPointRegion::localPointRegion(), cyclicACMIFvPatch::makeWeights(), cyclicAMIFvPatch::makeWeights(), fvMatrix< Type >::mapContributions(), JohnsonJacksonSchaeffer::nu(), Schaeffer::nu(), kineticTheoryModel::pPrime(), phasePressureModel::pPrime(), phasePressureModel::pPrimef(), motionSmootherAlgo::scaleMesh(), removeCells::setRefinement(), combineFaces::setRefinement(), ReactingCloud< CloudType >::Srho(), ReactingCloud< CloudType >::Srho(), ReactingCloud< CloudType >::SYi(), faNVDscheme< Type, NVDweight >::weights(), clippedLinear< Type >::weights(), midPoint< Type >::weights(), and reverseLinear< Type >::weights().
forAll() [1/2]
forAll (fluidRegions , i)
Definition at line 7 of file createCoupledRegions.H.
References coupled(), forAll, and thermoFluid().
forAll() [2/2]
forAll (solidRegions , i)
Definition at line 21 of file createCoupledRegions.H.
References coupled(), forAll, and thermos().
if()
if (coupled &&! fvMatrixAssemblyPtr)
Definition at line 53 of file createCoupledRegions.H.
References forAll, fvMatrixAssemblyPtr, solidRegions(), and thermos().
Variable Documentation
fvMatrixAssemblyPtr
autoPtr<fvMatrix<scalar> > fvMatrixAssemblyPtr
Definition at line 5 of file createCoupledRegions.H.
Referenced by if(), and if().