OpenFOAM: applications/solvers/lagrangian/icoUncoupledKinematicParcelFoam/createNonInertialFrameFields.H File Reference
createNonInertialFrameFields.H File Reference
Functions
if (linearAccelerationHeader.typeHeaderOk< uniformDimensionedVectorField >(true))
IOobject angularVelocityHeader ("angularVelocity", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE)
if (angularVelocityHeader.typeHeaderOk< uniformDimensionedVectorField >(true))
IOobject angularAccelerationHeader ("angularAcceleration", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE)
if (angularAccelerationHeader.typeHeaderOk< uniformDimensionedVectorField >(true))
IOobject centreOfRotationHeader ("centreOfRotation", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE)
if (centreOfRotationHeader.typeHeaderOk< uniformDimensionedVectorField >(true))
Variables
Info<< "Reading non-inertial frame fields"<< endl;IOobject linearAccelerationHeader("linearAcceleration", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE);autoPtr< uniformDimensionedVectorField > linearAccelerationPtr
autoPtr< uniformDimensionedVectorField > angularVelocityPtr
autoPtr< uniformDimensionedVectorField > angularAccelerationPtr
autoPtr< uniformDimensionedVectorField > centreOfRotationPtr
Function Documentation
if() [1/4]
if (linearAccelerationHeader.typeHeaderOk< uniformDimensionedVectorField > true)
Definition at line 14 of file createNonInertialFrameFields.H.
References linearAccelerationPtr.
angularVelocityHeader()
IOobject angularVelocityHeader ("angularVelocity" , runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::AUTO_WRITE)
Referenced by if().
if() [2/4]
if (angularVelocityHeader.typeHeaderOk< uniformDimensionedVectorField > true)
Definition at line 42 of file createNonInertialFrameFields.H.
References angularVelocityHeader(), and angularVelocityPtr.
angularAccelerationHeader()
IOobject angularAccelerationHeader ("angularAcceleration" , runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::AUTO_WRITE)
Referenced by if().
if() [3/4]
if (angularAccelerationHeader.typeHeaderOk< uniformDimensionedVectorField > true)
Definition at line 64 of file createNonInertialFrameFields.H.
References angularAccelerationHeader(), and angularAccelerationPtr.
centreOfRotationHeader()
IOobject centreOfRotationHeader ("centreOfRotation" , runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::AUTO_WRITE)
Referenced by if().
if() [4/4]
if (centreOfRotationHeader.typeHeaderOk< uniformDimensionedVectorField > true)
Definition at line 92 of file createNonInertialFrameFields.H.
References centreOfRotationHeader(), and centreOfRotationPtr.
Variable Documentation
linearAccelerationPtr
Info<< "Reading non-inertial frame fields" << endl; IOobject linearAccelerationHeader ("linearAcceleration", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE); autoPtr<uniformDimensionedVectorField> linearAccelerationPtr
Definition at line 12 of file createNonInertialFrameFields.H.
Referenced by if().
angularVelocityPtr
autoPtr<uniformDimensionedVectorField> angularVelocityPtr
Definition at line 40 of file createNonInertialFrameFields.H.
Referenced by if().
angularAccelerationPtr
autoPtr<uniformDimensionedVectorField> angularAccelerationPtr
Definition at line 62 of file createNonInertialFrameFields.H.
Referenced by if().
centreOfRotationPtr
autoPtr<uniformDimensionedVectorField> centreOfRotationPtr
Definition at line 90 of file createNonInertialFrameFields.H.
Referenced by if().