OpenFOAM: src/lagrangian/molecularDynamics/molecule/mdTools/createMDFields.H File Reference
createMDFields.H File Reference
Functions
List< scalarField > allSpeciesN_RU (molecules.potential().nIds(), scalarField(mesh.nCells(), Zero))
List< scalarField > allSpeciesM_RU (molecules.potential().nIds(), scalarField(mesh.nCells(), Zero))
List< vectorField > allSpeciesVelocitySum_RU (molecules.potential().nIds(), vectorField(mesh.nCells(), Zero))
List< scalarField > allSpeciesVelocityMagSquaredSum_RU (molecules.potential().nIds(), scalarField(mesh.nCells(), Zero))
Info<< nl<< "Creating fields."<< endl;PtrList< volScalarField > allSpeciesRhoN (molecules.potential().nIds())
forAll (allSpeciesRhoN, rN)
Info<< " Creating total number density field"<< endl;volScalarField totalRhoN(IOobject("rhoN_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimless/dimVolume, fvPatchFieldBase::zeroGradientType());totalRhoN.primitiveFieldRef()=0;totalRhoN.correctBoundaryConditions();PtrList< volScalarField > allSpeciesRhoM (molecules.potential().nIds())
forAll (allSpeciesRhoM, rM)
Info<< " Creating total mass density field"<< endl;volScalarField totalRhoM(IOobject("rhoM_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimMass/dimVolume, fvPatchFieldBase::zeroGradientType());totalRhoM.primitiveFieldRef()=0;totalRhoM.correctBoundaryConditions();PtrList< volVectorField > allSpeciesVelocity (molecules.potential().nIds())
forAll (allSpeciesVelocity, v)
Info<< " Creating total velocity field"<< endl;volVectorField totalVelocity(IOobject("velocity_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedVector(dimVelocity, Zero));PtrList< volScalarField > allSpeciesTemperature (molecules.potential().nIds())
forAll (allSpeciesTemperature, t)
Info<< " Creating total temperature field"<< endl;volScalarField totalTemperature(IOobject("temperature_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimTemperature, fvPatchFieldBase::zeroGradientType());totalTemperature.primitiveFieldRef()=0;totalTemperature.correctBoundaryConditions();PtrList< volScalarField > allSpeciesMeanKE (molecules.potential().nIds())
forAll (allSpeciesMeanKE, mKE)
Function Documentation
allSpeciesN_RU()
List< scalarField > allSpeciesN_RU (molecules. potential).nIds(, scalarField(mesh.nCells(), Zero))
Referenced by forAll(), and if().
allSpeciesM_RU()
List< scalarField > allSpeciesM_RU (molecules. potential).nIds(, scalarField(mesh.nCells(), Zero))
Referenced by forAll(), and if().
allSpeciesVelocitySum_RU()
List< vectorField > allSpeciesVelocitySum_RU (molecules. potential).nIds(, vectorField(mesh.nCells(), Zero))
Referenced by forAll(), and if().
allSpeciesVelocityMagSquaredSum_RU()
List< scalarField > allSpeciesVelocityMagSquaredSum_RU (molecules. potential).nIds(, scalarField(mesh.nCells(), Zero))
Referenced by forAll(), and if().
allSpeciesRhoN()
Info<< nl<< "Creating fields."<< endl;PtrList< volScalarField > allSpeciesRhoN (molecules. potential).nIds()
Referenced by forAll(), and if().
forAll() [1/5]
forAll (allSpeciesRhoN , rN)
Definition at line 40 of file createMDFields.H.
References allSpeciesRhoN(), mesh, and runTime.
allSpeciesRhoM()
Info<< " Creating total number density field"<< endl;volScalarField totalRhoN(IOobject("rhoN_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimless/dimVolume, fvPatchFieldBase::zeroGradientType());totalRhoN.primitiveFieldRef()=0;totalRhoN.correctBoundaryConditions();PtrList< volScalarField > allSpeciesRhoM (molecules. potential).nIds()
Referenced by forAll(), and if().
forAll() [2/5]
forAll (allSpeciesRhoM , rM)
Definition at line 95 of file createMDFields.H.
References allSpeciesRhoM(), mesh, and runTime.
allSpeciesVelocity()
Info<< " Creating total mass density field"<< endl;volScalarField totalRhoM(IOobject("rhoM_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimMass/dimVolume, fvPatchFieldBase::zeroGradientType());totalRhoM.primitiveFieldRef()=0;totalRhoM.correctBoundaryConditions();PtrList< volVectorField > allSpeciesVelocity (molecules. potential).nIds()
Referenced by forAll(), and if().
forAll() [3/5]
forAll (allSpeciesVelocity , v)
Definition at line 150 of file createMDFields.H.
References allSpeciesVelocity(), mesh, and runTime.
allSpeciesTemperature()
Info<< " Creating total velocity field"<< endl;volVectorField totalVelocity(IOobject("velocity_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedVector(dimVelocity, Zero));PtrList< volScalarField > allSpeciesTemperature (molecules. potential).nIds()
Referenced by forAll(), and if().
forAll() [4/5]
forAll (allSpeciesTemperature , t)
Definition at line 220 of file createMDFields.H.
References allSpeciesTemperature(), mesh, and runTime.
allSpeciesMeanKE()
Info<< " Creating total temperature field"<< endl;volScalarField totalTemperature(IOobject("temperature_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimTemperature, fvPatchFieldBase::zeroGradientType());totalTemperature.primitiveFieldRef()=0;totalTemperature.correctBoundaryConditions();PtrList< volScalarField > allSpeciesMeanKE (molecules. potential).nIds()
Referenced by forAll(), and if().
forAll() [5/5]
forAll (allSpeciesMeanKE , mKE)
Definition at line 276 of file createMDFields.H.
References allSpeciesMeanKE(), mesh, and runTime.