OpenFOAM: src/thermophysicalModels/radiation/include/createIncompressibleRadiationModel.H File Reference
createIncompressibleRadiationModel.H File Reference
Functions
autoPtr< radiation::radiationModel > radiation (radiation::radiationModel::New(T))
dimensionedScalar rhoCpRef ("rhoCpRef", dimDensity *dimEnergy/dimMass/dimTemperature, 1.0)
if (radiation->radiation())
Function Documentation
radiation()
autoPtr< radiation::radiationModel > radiation (radiation::radiationModel::New(T))
Referenced by solidAbsorption::a(), boundaryRadiationProperties::boundaryRadiationProperties(), solidAbsorption::e(), forAll(), solidAbsorption::nBands(), greyDiffusiveViewFactorFixedValueFvPatchScalarField::qro(), reactingOneDim::reactingOneDim(), reactingOneDim::reactingOneDim(), thermalBaffle::thermalBaffle(), thermalBaffle::thermalBaffle(), thermo::thermo(), thermo::thermo(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), and fixedIncidentRadiationFvPatchScalarField::updateCoeffs().
rhoCpRef()
dimensionedScalar rhoCpRef ("rhoCpRef" , dimDensity *dimEnergy/dimMass/ dimTemperature, 1. 0)
Referenced by if().
if()
if (radiation-> radiation())
Definition at line 13 of file createIncompressibleRadiationModel.H.
References rhoCpRef(), runTime, and transportProperties().