OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/solid/createSolidMeshes.H File Reference
createSolidMeshes.H File Reference
Functions
const wordList solidNames (rp["solid"])
PtrList< fvMesh > solidRegions (solidNames.size())
forAll (solidNames, i)
Function Documentation
solidNames()
const wordList solidNames (rp ["solid"])
Referenced by forAll(), phasePropertiesList::phasePropertiesList(), ReactingHeterogeneousParcel< ParcelType >::readFields(), ReactingMultiphaseParcel< ParcelType >::readFields(), ReactingMultiphaseParcel< ParcelType >::readObjects(), phaseProperties::reorder(), ReactingHeterogeneousParcel< ParcelType >::writeFields(), ReactingMultiphaseParcel< ParcelType >::writeFields(), ReactingHeterogeneousParcel< ParcelType >::writeObjects(), and ReactingMultiphaseParcel< ParcelType >::writeObjects().
solidRegions()
PtrList< fvMesh > solidRegions (solidNames. size())
Referenced by forAll(), forAll(), and if().
forAll()
forAll (solidNames , i)
Definition at line 5 of file createSolidMeshes.H.
References args, argList::dryRun(), argList::found(), runTime, solidNames(), and solidRegions().