OpenFOAM: applications/solvers/compressible/rhoSimpleFoam/rhoPorousSimpleFoam/createZones.H File Reference
createZones.H File Reference
Functions
IOporosityModelList pZones (mesh)
bool pressureImplicitPorosity (false)
if (pZones.active())
Variables
int nUCorr = 0
Function Documentation
pZones()
IOporosityModelList pZones (mesh)
Referenced by if().
pressureImplicitPorosity()
bool pressureImplicitPorosity (false)
Referenced by if(), and while().
if()
if (pZones. active())
Definition at line 6 of file createZones.H.
References nUCorr, pressureImplicitPorosity(), and simple.
Variable Documentation
nUCorr
int nUCorr = 0
Definition at line 5 of file createZones.H.
Referenced by if(), and if().