OpenFOAM: applications/solvers/multiphase/interIsoFoam/createPorosity.H File Reference
createPorosity.H File Reference
Functions
IOdictionary porosityProperties (IOobject("porosityProperties", runTime.constant(), runTime, IOobject::READ_IF_PRESENT, IOobject::NO_WRITE))
const bool porosityEnabled (porosityProperties.getOrDefault< bool >("porosityEnabled", false))
if (porosityEnabled)
Variables
tmp< volScalarField > tporosity
Function Documentation
porosityProperties()
IOdictionary porosityProperties (IOobject("porosityProperties", runTime.constant(), runTime, IOobject::READ_IF_PRESENT, IOobject::NO_WRITE))
Referenced by if(), and isoAdvection::isoAdvection().
porosityEnabled()
const bool porosityEnabled (porosityProperties.getOrDefault< bool > "porosityEnabled", false)
Referenced by if().
if()
if (porosityEnabled)
Definition at line 20 of file createPorosity.H.
References mesh, runTime, and tporosity.
Variable Documentation
tporosity
tmp<volScalarField> tporosity
Definition at line 19 of file createPorosity.H.
Referenced by if(), and if().