OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/solid/createSolidFields.H File Reference
createSolidFields.H File Reference
Functions
PtrList< coordinateSystem > coordinates (solidRegions.size())
PtrList< solidThermo > thermos (solidRegions.size())
PtrList< radiation::radiationModel > radiations (solidRegions.size())
PtrList< fv::options > solidHeatSources (solidRegions.size())
PtrList< volScalarField > betavSolid (solidRegions.size())
PtrList< volSymmTensorField > aniAlphas (solidRegions.size())
forAll (solidRegions, i)
Function Documentation
coordinates()
PtrList< coordinateSystem > coordinates (solidRegions. size())
Referenced by Dual< Type >::add(), Moment< Type >::add(), triSurfaceMesh::boundingSpheres(), ThermoParcel< ParcelType >::calcHeatTransfer(), ThermoParcel< ParcelType >::calcSurfaceValues(), NURBS3DVolume::computeMaxBoundaryDisplacement(), NURBS3DVolume::computeNewBoundaryPoints(), NURBS3DVolume::computeNewPoints(), NURBS3DVolume::computeParametricCoordinates(), searchableSurfaceCollection::coordinates(), NURBS3DVolume::coordinates(), forAll(), if(), Dual< Type >::interpolate(), Moment< Type >::interpolate(), interpolation< Type >::interpolate(), interpolationCellPointWallModified< Type >::interpolate(), streamLineParticle::move(), KinematicParcel< ParcelType >::setCellValues(), ReactingParcel< ParcelType >::setCellValues(), and ThermoParcel< ParcelType >::setCellValues().
thermos()
PtrList< solidThermo > thermos (solidRegions. size())
Referenced by forAll(), if(), and basicThermo::lookupThermo().
radiations()
PtrList< radiation::radiationModel > radiations (solidRegions. size())
Referenced by forAll().
solidHeatSources()
PtrList< fv::options > solidHeatSources (solidRegions. size())
Referenced by forAll().
betavSolid()
PtrList< volScalarField > betavSolid (solidRegions. size())
Referenced by forAll().
aniAlphas()
PtrList< volSymmTensorField > aniAlphas (solidRegions. size())
Referenced by forAll(), and if().
forAll()
forAll (solidRegions , i)
Definition at line 10 of file createSolidFields.H.
References aniAlphas(), betavSolid(), betavSolidIO(), coordinates(), radiations(), runTime, PtrList< T >::set(), solidHeatSources(), solidRegions(), T, and thermos().