OpenFOAM: src/lagrangian/molecularDynamics/molecule/mdTools/createAutoCorrelationFunctions.H File Reference
createAutoCorrelationFunctions.H File Reference
Functions
Info<< nl<< "Creating autocorrelation functions."<< endl;IOdictionary mdTransportProperitesDict(IOobject("mdTransportProperitesDict", mesh.time().system(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE, IOobject::NO_REGISTER));const dictionary &autocorrelationFunctionDict(mdTransportProperitesDict.subDict("autocorrelationFunctions"));Info<< tab<< "velocty"<< endl;const dictionary &velocityACFDict(autocorrelationFunctionDict.subDict("velocity"));correlationFunction< vector > vacf (mesh, velocityACFDict, molecules.size())
bool writeVacf (velocityACFDict.get< bool >("writeFile"))
Info<< tab<< "pressure"<< endl;const dictionary &pressureACFDict(autocorrelationFunctionDict.subDict("pressure"));correlationFunction< vector > pacf (mesh, pressureACFDict, 1)
bool writePacf (pressureACFDict.get< bool >("writeFile"))
Info<< tab<< "heat flux"<< endl;const dictionary &heatFluxACFDict(autocorrelationFunctionDict.subDict("heatFlux"));correlationFunction< vector > hfacf (mesh, heatFluxACFDict, 1)
bool writeHFacf (heatFluxACFDict.get< bool >("writeFile"))
Detailed Description
Original source file createAutoCorrelationFunctions.H
Definition in file createAutoCorrelationFunctions.H.
Function Documentation
vacf()
Info<< nl<< "Creating autocorrelation functions."<< endl;IOdictionary mdTransportProperitesDict(IOobject("mdTransportProperitesDict", mesh.time().system(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE, IOobject::NO_REGISTER));const dictionary &autocorrelationFunctionDict(mdTransportProperitesDict.subDict("autocorrelationFunctions"));Info<< tab<< "velocty"<< endl;const dictionary &velocityACFDict(autocorrelationFunctionDict.subDict("velocity"));correlationFunction< vector > vacf (mesh , velocityACFDict , molecules. size())
Referenced by if(), and if().
writeVacf()
bool writeVacf (velocityACFDict.get< bool > "writeFile")
pacf()
Info<< tab<< "pressure"<< endl;const dictionary &pressureACFDict(autocorrelationFunctionDict.subDict("pressure"));correlationFunction< vector > pacf (mesh , pressureACFDict , 1)
Referenced by if().
writePacf()
bool writePacf (pressureACFDict.get< bool > "writeFile")
hfacf()
Info<< tab<< "heat flux"<< endl;const dictionary &heatFluxACFDict(autocorrelationFunctionDict.subDict("heatFlux"));correlationFunction< vector > hfacf (mesh , heatFluxACFDict , 1)
Referenced by if().
writeHFacf()
bool writeHFacf (heatFluxACFDict.get< bool > "writeFile")