OpenFOAM: src/thermophysicalModels/specie/thermo/thermo/EtoHthermo.H File Reference
EtoHthermo.H File Reference
Functions
scalar Cp (const scalar p, const scalar T) const
scalar Hs (const scalar p, const scalar T) const
scalar Ha (const scalar p, const scalar T) const
Function Documentation
Cp()
scalar Cp (const scalar p, const scalar T) const inline
Definition at line 1 of file EtoHthermo.H.
References Cv, p, and T.
Hs()
scalar Hs (const scalar p, const scalar T) const inline
Definition at line 16 of file EtoHthermo.H.
References Es(), p, rho, and T.
Referenced by Es(), hConstThermo< EquationOfState >::Ha(), hPowerThermo< EquationOfState >::Ha(), hTabulatedThermo< EquationOfState >::Ha(), and thermo< Thermo, Type >::hs().
Ha()
scalar Ha (const scalar p, const scalar T) const inline
Definition at line 31 of file EtoHthermo.H.
References Ea(), p, rho, and T.
Referenced by Ea(), thermo< Thermo, Type >::G(), thermo< Thermo, Type >::ha(), hPolynomialThermo< EquationOfState, PolySize >::Hs(), and janafThermo< EquationOfState >::Hs().