OpenFOAM: applications/solvers/incompressible/boundaryFoam/evaluateNearWall.H File Reference
evaluateNearWall.H File Reference
Variables
scalar nut = turbulence->nut()().boundaryField()[patchId][faceId]
symmTensor R = turbulence->devReff()().boundaryField()[patchId][faceId]
scalar epsilon = turbulence->epsilon()()[cellId]
scalar k = turbulence->k()()[cellId]
scalar magUp = mag(U[cellId] - U.boundaryField()[patchId][faceId])
scalar tauw = flowDirection & R & wallNormal
scalar uTau = ::sqrt(mag(tauw))
scalar yPlus = uTau*y[cellId]/(nu + ROOTVSMALL)
scalar uPlus = magUp/(uTau + ROOTVSMALL)
scalar nutPlus = nut/nu
scalar kPlus = k/(sqr(uTau) + ROOTVSMALL)
scalar epsilonPlus = epsilon*nu/(pow4(uTau) + ROOTVSMALL)
scalar Rey = magUp*y[cellId]/nu
Variable Documentation
nut
scalar nut = turbulence->nut()().boundaryField()[patchId][faceId]
Definition at line 5 of file evaluateNearWall.H.
Referenced by ObukhovLength::calcOL(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), kL< BasicTurbulenceModel >::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), limitTurbulenceViscosity::correct(), EddyDiffusivity< BasicTurbulenceModel >::correctNut(), ReynoldsStress< BasicTurbulenceModel >::DivDevRhoReff(), objectiveNutSqr::J(), incompressibleRhoTurbulenceModel::mut(), incompressibleTurbulenceModel::mut(), incompressibleRhoTurbulenceModel::mut(), incompressibleTurbulenceModel::mut(), LESModel< BasicTurbulenceModel >::nuEff(), RASModel< BasicTurbulenceModel >::nuEff(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi(), objectiveNutSqr::update_divDxDbMultiplier(), objectiveNutSqr::update_dJdTMvar1(), objectiveNutSqr::update_dJdTMvar2(), and alphatJayatillekeWallFunctionFvPatchScalarField::yPlus().
R
symmTensor R = turbulence->devReff()().boundaryField()[patchId][faceId]
Definition at line 6 of file evaluateNearWall.H.
epsilon
scalar epsilon = turbulence->epsilon()()[cellId]
Definition at line 7 of file evaluateNearWall.H.
Referenced by multiphaseStabilizedTurbulence::addSup(), atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField(), ThermoParcel< ParcelType >::calcHeatTransfer(), kL< BasicTurbulenceModel >::correct(), EDC< ReactionThermo >::correct(), PaSR< ReactionThermo >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), multiphaseStabilizedTurbulence::correct(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), eddy::eddy(), mixtureKEpsilon< BasicTurbulenceModel >::epsilonBoundaryTypes(), epsilonWallFunctionFvPatchScalarField::epsilonPatch(), proudmanAcousticPower::execute(), if(), ThermoCloud< Foam::DSMCCloud >::radAreaPT4(), epsilonWallFunctionFvPatchScalarField::setMaster(), ThermoCloud< CloudType >::sigmap(), GradientDispersionRAS< CloudType >::update(), StochasticDispersionRAS< CloudType >::update(), atmBoundaryLayerInletEpsilonFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs(), and KinematicSurfaceFilm< CloudType >::wetSplashInteraction().
k
scalar k = turbulence->k()()[cellId]
Definition at line 9 of file evaluateNearWall.H.
magUp
scalar magUp = mag(U[cellId] - U.boundaryField()[patchId][faceId])
Definition at line 10 of file evaluateNearWall.H.
Referenced by alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), atmNutWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutUBlendedWallFunctionFvPatchScalarField::calcUTau(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), nutUWallFunctionFvPatchScalarField::calcYPlus(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), nutURoughWallFunctionFvPatchScalarField::yPlus(), nutUTabulatedWallFunctionFvPatchScalarField::yPlus(), and nutUWallFunctionFvPatchScalarField::yPlus().
tauw
scalar tauw = flowDirection & R & wallNormal
Definition at line 12 of file evaluateNearWall.H.
Referenced by atmNutWallFunctionFvPatchScalarField::calcNut().
uTau
scalar uTau = ::sqrt(mag(tauw))
Definition at line 14 of file evaluateNearWall.H.
Referenced by alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and kLowReWallFunctionFvPatchScalarField::updateCoeffs().
yPlus
scalar yPlus = uTau*y[cellId]/(nu + ROOTVSMALL)
Definition at line 16 of file evaluateNearWall.H.
Referenced by adjointkOmegaSST::addWallFunctionTerms(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), atmEpsilonWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), nutUBlendedWallFunctionFvPatchScalarField::calcUTau(), nutUWallFunctionFvPatchScalarField::calcYPlus(), kOmegaSSTSato< BasicTurbulenceModel >::correctNut(), adjointSpalartAllmaras::distanceSensitivities(), kaqRWallFunctionFvPatchScalarField::manipulateMatrix(), adjointWallVelocityFvPatchVectorField::manipulateMatrix(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), nutkWallFunctionFvPatchScalarField::yPlus(), and nutUWallFunctionFvPatchScalarField::yPlus().
uPlus
scalar uPlus = magUp/(uTau + ROOTVSMALL)
Definition at line 18 of file evaluateNearWall.H.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::calcUPlus(), adjointSpalartAllmaras::distanceSensitivities(), and adjointWallVelocityFvPatchVectorField::manipulateMatrix().
nutPlus
scalar nutPlus = nut/nu
Definition at line 20 of file evaluateNearWall.H.
kPlus
scalar kPlus = k/(sqr(uTau) + ROOTVSMALL)
Definition at line 22 of file evaluateNearWall.H.
epsilonPlus
scalar epsilonPlus = epsilon*nu/(pow4(uTau) + ROOTVSMALL)
Definition at line 24 of file evaluateNearWall.H.
Rey
scalar Rey = magUp*y[cellId]/nu
Definition at line 28 of file evaluateNearWall.H.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::calcUPlus(), and nutUTabulatedWallFunctionFvPatchScalarField::yPlus().