OpenFOAM: src/finiteArea/finiteArea/gradSchemes/limitedGradSchemes/faceLimitedFaGrad/faceLimitedFaGrads.C File Reference
faceLimitedFaGrads.C File Reference
Functions
makeFaGradScheme (faceLimitedGrad)
Detailed Description
Original source file faceLimitedFaGrads.C
Definition in file faceLimitedFaGrads.C.
Function Documentation
makeFaGradScheme()
makeFaGradScheme (faceLimitedGrad)
Definition at line 32 of file faceLimitedFaGrads.C.
References faceLimitedGrad< Type >::calcGrad(), Foam::cmptMultiply(), gaussGrad< Type >::correctBoundaryConditions(), Foam::endl(), forAll, g, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::Info, faceLimitedGrad< Type >::limitEdge(), Foam::limiter(), Foam::max(), mesh, Foam::min(), Foam::name(), VectorSpace< Form, Cmpt, Ncmpts >::one, GeometricField< Type, PatchField, GeoMesh >::ref(), x, and y.