OpenFOAM: applications/utilities/finiteArea/makeFaMesh/faMeshWriteEdgesOBJ.H File Reference
faMeshWriteEdgesOBJ.H File Reference
Functions
word outputName ("finiteArea-edges.obj")
if (UPstream::parRun())
OBJstream os (runTime.globalPath()/outputName)
os writeQuoted (("# "+outputName+"\n"), false)
os write (aMesh.patch().edges(), aMesh.patch().localPoints())
Detailed Description
Original source file faMeshWriteEdgesOBJ.H
Definition in file faMeshWriteEdgesOBJ.H.
Function Documentation
outputName()
word outputName ("finiteArea-edges.obj")
Referenced by seriesWriter::base(), distanceSurface::filterFaceProximity(), distanceSurface::filterRegionProximity(), if(), if(), if(), if(), if(), if(), if(), if(), if(), fieldMinMax::output(), Foam::vtkWritePatchEdges(), dataCloud::write(), vtkCloud::write(), vtkWrite::write(), streamLineBase::writeToFile(), and surfaceFieldValue::writeValues().
if()
if (UPstream::parRun())
Definition at line 27 of file faMeshWriteEdgesOBJ.H.
References Foam::name(), and outputName().
os()
OBJstream os (runTime.globalPath()/ outputName)
Referenced by pairPatchAgglomeration::agglomerate(), collatedFileOperation::appendObject(), foamToVtkReportFields::area(), Foam::beginBlock(), Foam::begIndentList(), X3DsurfaceFormatCore::beginGroup(), Foam::vtk::legacy::beginLines(), Foam::vtk::legacy::beginPoints(), Foam::vtk::legacy::beginPolys(), Foam::vtk::legacy::beginVerts(), PDRblock::blockMeshDict(), PDRblock::blockMeshDict(), Pstream::broadcast(), Pstream::broadcasts(), mappedPatchBase::calcAMI(), energySpectrum::calcAndWriteSpectrum(), surfaceNoise::calculate(), refinementFeatures::checkSizes(), clock::clockTime(), commSchedule::commSchedule(), Enum< injectionMethod >::const_iterator::const_iterator(), Enum< injectionMethod >::contains(), dynamicCode::copyAndFilter(), dynamicCode::copyOrCreateFiles(), wallDistAddressing::correct(), propellerInfo::createFiles(), dynamicCode::createMakeFiles(), dynamicCode::createMakeOptions(), Foam::createTree(), List< Foam::glTF::object >::data(), clock::date(), clock::dateTime(), Foam::decrIndent(), messageStream::deprecated(), dictionary::digest(), distributedTriSurfaceMesh::distribute(), vtmWriter::dump(), Foam::endBlock(), Foam::endEntry(), X3DsurfaceFormatCore::endGroup(), Foam::endIndentList(), Foam::endl(), codeStream::evaluate(), Foam::stringOps::evaluate(), Curle::execute(), forceCoeffs::execute(), Foam::vtk::legacy::fileHeader(), Foam::vtk::legacy::fileHeader(), base64Formatter::flush(), legacyRawFormatter::flush(), Foam::flush(), GAMGSolver::GAMGSolver(), globalIndex::get(), HashTable< T * >::HashTable(), if(), Foam::incrIndent(), Foam::indent(), injectionModelList::info(), transferModelList::info(), vtuSizing::info(), CircularBuffer< T >::info(), phaseChangeModel::info(), irregularWaveModel::info(), regularWaveModel::info(), solitaryWaveModel::info(), waveGenerationModel::info(), Boussinesq::info(), cnoidal::info(), Grimshaw::info(), irregularMultiDirectional::info(), McCowan::info(), StokesI::info(), StokesII::info(), StokesV::info(), streamFunction::info(), waveModel::info(), fluxSummary::initialiseCellZoneAndDirection(), writeFile::initStream(), triangle2D::interArea(), foamToVtkReportFields::internal(), interpolationTable< scalar >::interpolateValue(), triangle2D::lineSegmentIntersectionPoint(), inverseDistance::markDonors(), trackingInverseDistance::markDonors(), trackingInverseDistance::markPatchesAsHoles(), inverseDistance::markPatchesAsHoles(), Matrix< RectangularMatrix< Type >, Type >::Matrix(), outputOptions::newFormatter(), Foam::vtk::newFormatter(), Foam::vtk::newFormatter(), messageStream::operator()(), IOerror::operator()(), messageStream::operator()(), messageStream::operator()(), GeometricField< Type, PatchField, GeoMesh >::operator/=(), Field< Type >::operator/=(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::functionObjects::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::RBD::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::RBD::operator<<(), Foam::RBD::operator<<(), Foam::RBD::operator<<(), Foam::RBD::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), HashSet< labelPairPair >::operator=(), Foam::output(), Foam::outputFlatList(), Foam::outputIndent(), Foam::Detail::outputLoop(), blockMesh::patchDicts(), sampledPatch::patchIDs(), cloudInfo::performAction(), primitiveEntry::primitiveEntry(), foamToVtkReportFields::print(), foamToVtkReportFields::print(), foamToVtkReportFields::print(), profiling::print(), ensightMesh::options::print(), STLtriangle::print(), seriesWriter::print(), forceCoeffs::coeffDesc::print(), HashTable< T, Key, Hash >::Iterator< Const >::print(), HashTablePair< K, V >::print(), HashTableSingle< K >::print(), IFstream::print(), OFstream::print(), IOstream::print(), IListStream::print(), OCountStream::print(), OListStream::print(), UIListStream::print(), UOListStream::print(), UIPstreamBase::print(), UOPstreamBase::print(), ISstream::print(), OSstream::print(), prefixOSstream::print(), IStringStream::print(), OStringStream::print(), ITstream::print(), OTstream::print(), SolverPerformance< Type >::print(), isoSurfaceParams::print(), seriesWriter::print(), IOstream::print(), seriesWriter::print(), sampledDistanceSurface::print(), sampledIsoSurface::print(), sampledCuttingPlane::print(), sampledFaceZone::print(), sampledMeshedSurface::print(), sampledPatch::print(), sampledPatchInternalField::print(), sampledPlane::print(), sampledSurface::print(), sampledThresholdCellFaces::print(), cuttingSurface::print(), distanceSurface::print(), sampledInterface::print(), Foam::BitOps::print(), dynamicIndexedOctree< Type >::print(), indexedOctree< Type >::print(), decompositionInformation::printAll(), PackedList< Width >::printBits(), genericRagelLemonDriver::printBuffer(), memorybuf::in::printBufInfo(), memorybuf::out::printBufInfo(), countstreambuf::printBufInfo(), OCountStreamAllocator::printBufInfo(), OListStreamAllocator::printBufInfo(), UIListStreamAllocator::printBufInfo(), UOListStreamAllocator::printBufInfo(), Foam::printColour(), decompositionInformation::printDetails(), Foam::printDOT(), Time::printExecutionTime(), UPstream::commsStruct::printGraph(), ensightCase::printInfo(), HashTable< T, Key, Hash >::printInfo(), mapDistribute::printLayout(), mapDistributeBase::printLayout(), Foam::printMaps(), Foam::printPatchEdges(), Foam::printPatterns(), Foam::printRange(), Caching< DataType >::PrintSelf(), GAMGProcAgglomeration::printStats(), decompositionInformation::printSummary(), Foam::printTable(), Foam::printTable(), basicThermo::printThermoNames(), Foam::printTimeHMS(), ensightCase::printTimeset(), ensightCase::printTimeset(), ensightCase::printTimeset(), Foam::printTimingDetail(), Foam::printTokenError(), Foam::printTokenInfo(), Foam::printTriangle(), pointNoise::processData(), genericPatchFieldBase::putEntry(), FIRECore::putFireLabel(), FIRECore::putFireLabels(), FIRECore::putFireLabels(), FIRECore::putFirePoint(), FIRECore::putFireString(), Foam::putValue(), Curle::read(), masterUncollatedFileOperation::readAndSend(), decomposedBlockData::readBlocks(), decomposedBlockData::readBlocks(), Time::readDict(), masterUncollatedFileOperation::readHeader(), Foam::ensightOutput::readWriteCloudField(), codedFixedValueFvPatchField< Type >::redirectPatchField(), codedMixedFvPatchField< Type >::redirectPatchField(), codedFixedValuePointPatchField< Type >::redirectPatchField(), profilingPstream::report(), fileWriter::reportBadState(), fileWriter::reportBadState(), genericRagelLemonDriver::reportFatal(), genericRagelLemonDriver::reportFatal(), cyclicAMIPolyPatch::resetAMI(), masterUncollatedFileOperation::scatterList(), Foam::serializeFace(), Foam::serializeHex(), Foam::serializeProjectEdge(), Foam::serializeProjectFace(), Foam::serializeProjectPoints(), NASCore::setPrecision(), simpleObjectRegistry::setValues(), externalFileCoupler::shutdown(), clockValue::str(), syncObjects::sync(), dictionary::tokens(), writerCaching::update(), fvPatchField< symmTensor >::updateCoeffs(), externalFileCoupler::useMaster(), Enum< injectionMethod >::const_iterator::val(), foamToVtkReportFields::volume(), dynamicCode::wmakeLibso(), continuityError::write(), ensightWrite::write(), FaceInteraction< CloudType >::write(), FacePostProcessing< CloudType >::write(), ParticleHistogram< CloudType >::write(), ParticlePostProcessing< CloudType >::write(), ParticleZoneInfo< CloudType >::write(), RemoveParcels< CloudType >::write(), abaqusWriter::write(), nastranWriter::write(), rawWriter::write(), JobInfo::write(), ensightMesh::write(), ensightFaMesh::write(), effectivenessTable::write(), referenceTemperature::write(), distribution::write(), edgeMeshFormat::write(), STARCDedgeFormat::write(), OBJedgeFormat::write(), GTSsurfaceFormat< Face >::write(), ABAQUSsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), NASsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), OFFsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), STARCDsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), X3DsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), VTPsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), GTSsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), VTPsurfaceFormat< Face >::write(), triSurface::write(), Distribution< Type >::write(), surfaceFeatures::write(), STARCDMeshWriter::write(), scene::write(), asciiFormatter::write(), gnuplotWriter::write(), rawWriter::write(), xmgraceWriter::write(), asciiFormatter::write(), triSurface::write(), MeshedSurfaceProxy< Face >::write(), asciiFormatter::write(), ensightOutputSurface::write(), ensightMesh::write(), ensightFaMesh::write(), ensightCells::write(), ensightFaces::write(), voxelMeshSearch::write(), FLMAsurfaceFormat< Face >::write(), atmBoundaryLayer::write(), atmBoundaryLayerInletEpsilonFvPatchScalarField::write(), atmBoundaryLayerInletKFvPatchScalarField::write(), atmBoundaryLayerInletOmegaFvPatchScalarField::write(), atmBoundaryLayerInletVelocityFvPatchVectorField::write(), atmTurbulentHeatFluxTemperatureFvPatchScalarField::write(), atmAlphatkWallFunctionFvPatchScalarField::write(), atmEpsilonWallFunctionFvPatchScalarField::write(), atmNutkWallFunctionFvPatchScalarField::write(), atmNutUWallFunctionFvPatchScalarField::write(), atmNutWallFunctionFvPatchScalarField::write(), atmOmegaWallFunctionFvPatchScalarField::write(), freeSurfacePressureFvPatchScalarField::write(), freeSurfaceVelocityFvPatchVectorField::write(), attachDetach::write(), layerAdditionRemoval::write(), solidBodyMotionDisplacementPointPatchVectorField::write(), perfectInterface::write(), setUpdater::write(), slidingInterface::write(), faPatch::write(), calculatedFaePatchField< Type >::write(), coupledFaePatchField< Type >::write(), fixedValueFaePatchField< Type >::write(), calculatedFaPatchField< Type >::write(), coupledFaPatchField< Type >::write(), fixedGradientFaPatchField< Type >::write(), fixedValueFaPatchField< Type >::write(), mixedFaPatchField< Type >::write(), slicedFaPatchField< Type >::write(), clampedPlateFaPatchField< Type >::write(), edgeNormalFixedValueFaPatchVectorField::write(), fixedValueOutflowFaPatchField< Type >::write(), inletOutletFaPatchField< Type >::write(), outletInletFaPatchField< Type >::write(), timeVaryingUniformFixedValueFaPatchField< Type >::write(), SRFFreestreamVelocityFvPatchVectorField::write(), SRFVelocityFvPatchVectorField::write(), SRFWallVelocityFvPatchVectorField::write(), calculatedFvPatchField< Type >::write(), coupledFvPatchField< Type >::write(), directionMixedFvPatchField< Type >::write(), fixedGradientFvPatchField< Type >::write(), fixedValueFvPatchField< Type >::write(), mixedFvPatchField< Type >::write(), slicedFvPatchField< Type >::write(), acousticWaveTransmissiveFvPatchField< Type >::write(), activeBaffleVelocityFvPatchVectorField::write(), activePressureForceBaffleVelocityFvPatchVectorField::write(), advectiveFvPatchField< Type >::write(), codedFixedValueFvPatchField< Type >::write(), codedMixedFvPatchField< Type >::write(), cylindricalInletVelocityFvPatchVectorField::write(), electrostaticDepositionFvPatchScalarField::write(), fixedFluxPressureFvPatchScalarField::write(), fixedJumpAMIFvPatchField< Type >::write(), fixedMeanFvPatchField< Type >::write(), fixedMeanOutletInletFvPatchField< Type >::write(), fixedNormalInletOutletVelocityFvPatchVectorField::write(), fixedNormalSlipFvPatchField< Type >::write(), fixedPressureCompressibleDensityFvPatchScalarField::write(), fixedProfileFvPatchField< Type >::write(), flowRateInletVelocityFvPatchVectorField::write(), flowRateOutletVelocityFvPatchVectorField::write(), fluxCorrectedVelocityFvPatchVectorField::write(), freestreamFvPatchField< Type >::write(), freestreamPressureFvPatchScalarField::write(), freestreamVelocityFvPatchVectorField::write(), inletOutletFvPatchField< Type >::write(), inletOutletTotalTemperatureFvPatchScalarField::write(), interfaceCompressionFvPatchScalarField::write(), interstitialInletVelocityFvPatchVectorField::write(), mappedFieldFvPatchField< Type >::write(), mappedMixedFieldFvPatchField< Type >::write(), mappedFixedPushedInternalValueFvPatchField< Type >::write(), mappedFixedValueFvPatchField< Type >::write(), mappedFlowRateFvPatchVectorField::write(), mappedMixedFvPatchField< Type >::write(), mappedVelocityFluxFixedValueFvPatchField::write(), matchedFlowRateOutletVelocityFvPatchVectorField::write(), movingWallVelocityFvPatchVectorField::write(), noSlipFvPatchVectorField::write(), outletInletFvPatchField< Type >::write(), outletMappedUniformInletFvPatchField< Type >::write(), outletPhaseMeanVelocityFvPatchVectorField::write(), partialSlipFvPatchField< Type >::write(), phaseHydrostaticPressureFvPatchScalarField::write(), plenumPressureFvPatchScalarField::write(), pressureDirectedInletOutletVelocityFvPatchVectorField::write(), pressureDirectedInletVelocityFvPatchVectorField::write(), pressureInletOutletParSlipVelocityFvPatchVectorField::write(), pressureInletOutletVelocityFvPatchVectorField::write(), pressureInletVelocityFvPatchVectorField::write(), pressureNormalInletOutletVelocityFvPatchVectorField::write(), pressurePermeableAlphaInletOutletVelocityFvPatchVectorField::write(), pressurePIDControlInletVelocityFvPatchVectorField::write(), prghPermeableAlphaTotalPressureFvPatchScalarField::write(), prghPressureFvPatchScalarField::write(), prghTotalHydrostaticPressureFvPatchScalarField::write(), prghTotalPressureFvPatchScalarField::write(), rotatingPressureInletOutletVelocityFvPatchVectorField::write(), rotatingTotalPressureFvPatchScalarField::write(), rotatingWallVelocityFvPatchVectorField::write(), scaledFixedValueFvPatchField< Type >::write(), supersonicFreestreamFvPatchVectorField::write(), surfaceNormalFixedValueFvPatchVectorField::write(), swirlFlowRateInletVelocityFvPatchVectorField::write(), swirlInletVelocityFvPatchVectorField::write(), syringePressureFvPatchScalarField::write(), timeVaryingMappedFixedValueFvPatchField< Type >::write(), totalPressureFvPatchScalarField::write(), totalTemperatureFvPatchScalarField::write(), translatingWallVelocityFvPatchVectorField::write(), turbulentDFSEMInletFvPatchVectorField::write(), IntegralScaleBox< Type >::write(), turbulentDigitalFilterInletFvPatchField< Type >::write(), turbulentInletFvPatchField< Type >::write(), turbulentIntensityKineticEnergyInletFvPatchScalarField::write(), uniformDensityHydrostaticPressureFvPatchScalarField::write(), uniformInletOutletFvPatchField< Type >::write(), uniformJumpAMIFvPatchField< Type >::write(), uniformTotalPressureFvPatchScalarField::write(), variableHeightFlowRateFvPatchScalarField::write(), variableHeightFlowRateInletVelocityFvPatchVectorField::write(), waveSurfacePressureFvPatchScalarField::write(), waveTransmissiveFvPatchField< Type >::write(), fvPatchField< Type >::write(), cellMotionFvPatchField< Type >::write(), angularOscillatingDisplacementPointPatchVectorField::write(), angularOscillatingVelocityPointPatchVectorField::write(), oscillatingDisplacementPointPatchVectorField::write(), oscillatingVelocityPointPatchVectorField::write(), surfaceDisplacementPointPatchVectorField::write(), surfaceSlipDisplacementPointPatchVectorField::write(), timeVaryingMappedFixedValuePointPatchField< Type >::write(), uniformInterpolatedDisplacementPointPatchVectorField::write(), waveDisplacementPointPatchVectorField::write(), genericFaePatchField< Type >::write(), genericFaPatchField< Type >::write(), genericFvPatchField< Type >::write(), genericFvsPatchField< Type >::write(), genericPointPatchField< Type >::write(), cyclicACMIPolyPatch::write(), cyclicAMIPolyPatch::write(), cyclicPeriodicAMIPolyPatch::write(), uniformFixedValuePointPatchField< Type >::write(), mappedPolyPatch::write(), mappedVariableThicknessWallPolyPatch::write(), mappedWallPolyPatch::write(), codedFixedValuePointPatchField< Type >::write(), fixedNormalSlipPointPatchField< Type >::write(), timeVaryingUniformFixedValuePointPatchField< Type >::write(), genericPolyPatch::write(), cyclicPolyPatch::write(), oldCyclicPolyPatch::write(), processorPolyPatch::write(), processorCyclicPolyPatch::write(), adjointFarFieldPressureFvPatchScalarField::write(), adjointFarFieldVelocityFvPatchVectorField::write(), adjointInletVelocityFvPatchVectorField::write(), adjointOutletPressureFvPatchScalarField::write(), adjointOutletVelocityFvPatchVectorField::write(), adjointOutletVelocityFluxFvPatchVectorField::write(), adjointRotatingWallVelocityFvPatchVectorField::write(), adjointWallVelocityFvPatchVectorField::write(), adjointWallVelocityLowReFvPatchVectorField::write(), adjointFarFieldNuaTildaFvPatchScalarField::write(), adjointFarFieldTMVar1FvPatchScalarField::write(), adjointFarFieldTMVar2FvPatchScalarField::write(), adjointInletNuaTildaFvPatchScalarField::write(), adjointOutletFluxFvPatchField< Type >::write(), adjointOutletKaFvPatchScalarField::write(), adjointOutletNuaTildaFvPatchScalarField::write(), adjointOutletNuaTildaFluxFvPatchScalarField::write(), adjointOutletWaFvPatchScalarField::write(), kaqRWallFunctionFvPatchScalarField::write(), waWallFunctionFvPatchScalarField::write(), alphaContactAngleFvPatchScalarField::write(), timeVaryingMassSorptionFvPatchScalarField::write(), alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField::write(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::write(), alphatPhaseChangeWallFunctionFvPatchScalarField::write(), alphatWallBoilingWallFunctionFvPatchScalarField::write(), copiedFixedValueFvPatchScalarField::write(), fixedMultiPhaseHeatFluxFvPatchScalarField::write(), JohnsonJacksonParticleSlipFvPatchVectorField::write(), JohnsonJacksonParticleThetaFvPatchScalarField::write(), velocityFilmShellFvPatchVectorField::write(), thermalShellFvPatchScalarField::write(), vibrationShellFvPatchScalarField::write(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::write(), filmPyrolysisTemperatureCoupledFvPatchScalarField::write(), filmPyrolysisVelocityCoupledFvPatchVectorField::write(), filmHeightInletVelocityFvPatchVectorField::write(), inclinedFilmNusseltHeightFvPatchScalarField::write(), inclinedFilmNusseltInletVelocityFvPatchVectorField::write(), alphatFilmWallFunctionFvPatchScalarField::write(), thermalBaffleFvPatchScalarField::write(), compositeBody::write(), cuboid::write(), masslessBody::write(), rigidBody::write(), sphere::write(), subBody::write(), composite::write(), floating::write(), joint::write(), Pa::write(), Ra::write(), externalForce::write(), linearAxialAngularSpring::write(), linearDamper::write(), linearSpring::write(), prescribedRotation::write(), softWall::write(), sphericalAngularDamper::write(), rigidBodyModel::write(), rigidBodyModelState::write(), rigidBodyMotion::write(), sampledSet::write(), sixDoFRigidBodyDisplacementPointPatchVectorField::write(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::write(), axis::write(), line::write(), plane::write(), point::write(), linearSpringDamper::write(), sphericalAngularSpring::write(), tabulatedAxialAngularSpring::write(), sixDoFRigidBodyMotion::write(), sixDoFSolver::write(), energyJumpFvPatchScalarField::write(), energyJumpAMIFvPatchScalarField::write(), gradientEnergyFvPatchScalarField::write(), greyDiffusiveRadiationMixedFvPatchScalarField::write(), greyDiffusiveViewFactorFixedValueFvPatchScalarField::write(), MarshakRadiationFvPatchScalarField::write(), MarshakRadiationFixedTemperatureFvPatchScalarField::write(), specularRadiationMixedFvPatchScalarField::write(), wideBandDiffusiveRadiationMixedFvPatchScalarField::write(), enthalpySorptionFvPatchScalarField::write(), speciesSorptionFvPatchScalarField::write(), IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >::write(), ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::write(), convectiveHeatTransferFvPatchScalarField::write(), externalWallHeatFluxTemperatureFvPatchScalarField::write(), fixedIncidentRadiationFvPatchScalarField::write(), humidityTemperatureCoupledMixedFvPatchScalarField::write(), lumpedMassWallTemperatureFvPatchScalarField::write(), outletMappedUniformInletHeatAdditionFvPatchField::write(), semiPermeableBaffleMassFractionFvPatchScalarField::write(), semiPermeableBaffleVelocityFvPatchVectorField::write(), thermalBaffle1DFvPatchScalarField< solidType >::write(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::write(), alphatJayatillekeWallFunctionFvPatchScalarField::write(), alphatWallFunctionFvPatchScalarField::write(), sorptionWallFunctionFvPatchScalarField::write(), wallHeatTransferFvPatchScalarField::write(), constantAlphaContactAngleFvPatchScalarField::write(), dynamicAlphaContactAngleFvPatchScalarField::write(), temperatureDependentAlphaContactAngleFvPatchScalarField::write(), timeVaryingAlphaContactAngleFvPatchScalarField::write(), alphaFixedPressureFvPatchScalarField::write(), fixedShearStressFvPatchVectorField::write(), porousBafflePressureFvPatchField::write(), epsilonWallFunctionFvPatchScalarField::write(), kLowReWallFunctionFvPatchScalarField::write(), kqRWallFunctionFvPatchField< Type >::write(), nutkRoughWallFunctionFvPatchScalarField::write(), nutkWallFunctionFvPatchScalarField::write(), nutLowReWallFunctionFvPatchScalarField::write(), nutWallFunctionFvPatchScalarField::write(), omegaWallFunctionFvPatchScalarField::write(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::write(), turbulentMixingLengthFrequencyInletFvPatchScalarField::write(), waveAlphaFvPatchScalarField::write(), waveVelocityFvPatchVectorField::write(), waveMakerPointPatchVectorField::write(), GAMGInterface::write(), restraint::write(), blockFace::write(), interpolationLookUpTable< Type >::write(), oversetFvMeshBase::write(), blockDescriptor::write(), Foam::blockMeshTools::write(), blockVertex::write(), edgeMeshFormat::write(), graph::write(), scene::write(), PointIndexHit< PointType >::write(), boundaryPatch::write(), accessor::write(), animation::write(), base::write(), bufferView::write(), mesh::write(), processorFaPatch::write(), faePatchField< Type >::write(), uniformFixedGradientFaPatchField< Type >::write(), uniformFixedValueFaPatchField< Type >::write(), uniformMixedFaPatchField< Type >::write(), faPatchField< Type >::write(), patchExprFieldBase::write(), exprFixedValueFvPatchField< Type >::write(), exprMixedFvPatchField< Type >::write(), exprValuePointPatchField< Type >::write(), cyclicFvPatchField< Type >::write(), cyclicACMIFvPatchField< Type >::write(), cyclicAMIFvPatchField< Type >::write(), fanFvPatchField< Type >::write(), fanPressureFvPatchScalarField::write(), mappedPatchFieldBase< Type >::write(), mappedFixedInternalValueFvPatchField< Type >::write(), swirlFanVelocityFvPatchField::write(), uniformFixedGradientFvPatchField< Type >::write(), uniformFixedValueFvPatchField< Type >::write(), uniformJumpFvPatchField< Type >::write(), uniformMixedFvPatchField< Type >::write(), uniformNormalFixedValueFvPatchVectorField::write(), fvsPatchField< Type >::write(), externalCoupledTemperatureMixedFvPatchScalarField::write(), eulerianParticle::write(), surfaceSlipDisplacementFvPatchField< Type >::write(), CloudSubModelBase< CloudType >::write(), DispersionRASModel< CloudType >::write(), lumpedPointDisplacementPointPatchVectorField::write(), advancingFrontAMI::write(), AMIInterpolation::write(), faceAreaWeightAMI::write(), faceAreaWeightAMI2D::write(), nearestFaceAMI::write(), coordSet::write(), mappedPatchBase::write(), dynamicIndexedOctree< Type >::write(), indexedOctree< Type >::write(), HashPtrTable< T, Key, Hash >::write(), dictionaryEntry::write(), dictionaryListEntry::write(), functionEntry::write(), OutputAdaptor< Container, Delimiters >::write(), pointPatchField< Type >::write(), profilingSysInfo::write(), interpolation2DTable< Type >::write(), csvTableReader< Type >::write(), tableReader< Type >::write(), cyclicGAMGInterface::write(), processorGAMGInterface::write(), coupleGroupIdentifier::write(), patchIdentifier::write(), geometricSurfacePatch::write(), surfZoneIdentifier::write(), zoneIdentifier::write(), cellMatcher::write(), coupledPolyPatch::write(), polyPatch::write(), faceZone::write(), zone::write(), axes::write(), axisAngle::write(), cylindrical::write(), euler::write(), identity::write(), specified::write(), starcd::write(), coordinateSystem::write(), indirect::write(), subModelBase::write(), cpuInfo::write(), memInfo::write(), calculatedProcessorGAMGInterface::write(), oversetFvPatchField< Type >::write(), CHFModel::write(), Zuber::write(), CHFSubCoolModel::write(), HuaXu::write(), Tatsumoto::write(), departureDiameterModel::write(), KocamustafaogullariIshii::write(), TolubinskiKostanchuk::write(), departureFrequencyModel::write(), BreenWestwater::write(), Bromley::write(), filmBoilingModel::write(), LeidenfrostModel::write(), Spiegler::write(), Jeschar::write(), MHFModel::write(), exponential::write(), Kutadeladze::write(), nucleateFluxModel::write(), LemmertChawla::write(), nucleationSiteModel::write(), cosine::write(), Lavieville::write(), linear::write(), partitioningModel::write(), Schroeder::write(), Shirai::write(), TDNBModel::write(), nutkFilmWallFunctionFvPatchScalarField::write(), sixDoFRigidBodyMotionState::write(), surfZone::write(), surfacePatch::write(), triSurface::write(), solidArrheniusReactionRate::write(), solidIsothermalReactionRate::write(), solidReaction< ReactionThermo >::write(), polynomialSolidTransport< Thermo, PolySize >::write(), tabulatedAnIsoSolidTransport< Thermo >::write(), tabulatedSolidTransport< Thermo >::write(), adiabaticPerfectFluid< Specie >::write(), Boussinesq< Specie >::write(), icoPolynomial< Specie, PolySize >::write(), icoTabulated< Specie >::write(), incompressiblePerfectGas< Specie >::write(), linear< Type >::write(), PengRobinsonGas< Specie >::write(), perfectFluid< Specie >::write(), perfectGas< Specie >::write(), rhoConst< Specie >::write(), rPolynomial< Specie >::write(), ArrheniusReactionRate::write(), ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::write(), SRIFallOffFunction::write(), TroeFallOffFunction::write(), FallOffReactionRate< ReactionRate, FallOffFunction >::write(), JanevReactionRate::write(), LandauTellerReactionRate::write(), LangmuirHinshelwoodReactionRate::write(), powerSeriesReactionRate::write(), thirdBodyArrheniusReactionRate::write(), thirdBodyEfficiencies::write(), NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::write(), Reaction< ReactionThermo >::write(), ReactionList< ThermoType >::write(), specie::write(), eConstThermo< EquationOfState >::write(), hConstThermo< EquationOfState >::write(), hPolynomialThermo< EquationOfState, PolySize >::write(), hTabulatedThermo< EquationOfState >::write(), janafThermo< EquationOfState >::write(), thermo< Thermo, Type >::write(), logPolynomialTransport< Thermo, PolySize >::write(), polynomialTransport< Thermo, PolySize >::write(), sutherlandTransport< Thermo >::write(), tabulatedTransport< Thermo >::write(), WLFTransport< Thermo >::write(), outletMachNumberPressureFvPatchScalarField::write(), temperatureCoupledBase::write(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::write(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::write(), alphaContactAngleTwoPhaseFvPatchScalarField::write(), nutUBlendedWallFunctionFvPatchScalarField::write(), nutURoughWallFunctionFvPatchScalarField::write(), nutUSpaldingWallFunctionFvPatchScalarField::write(), nutUTabulatedWallFunctionFvPatchScalarField::write(), nutUWallFunctionFvPatchScalarField::write(), primitiveEntry::write(), profilingInformation::write(), SHA1Digest::write(), dictionary::write(), PtrListDetail< T >::write(), error::write(), IOerror::write(), blockEdge::write(), STLtriangle::write(), surfaceLocation::write(), STLtriangle::write(), List< Type >::write(), dimensionSet::write(), dimensionSet::write(), STLtriangle::write(), properties::writeAllResultEntries(), stateFunctionObject::writeAllResultEntries(), X3DsurfaceFormatCore::writeAppearance(), Foam::writeAreaField(), Foam::ensightOutput::writeAreaField(), Foam::ensightOutput::writeAreaField(), STLsurfaceFormat< Face >::writeAscii(), STLsurfaceFormat< Face >::writeAscii(), correlationFunction< Type >::writeAveraged(), propellerInfo::writeAxialWake(), IOobject::writeBanner(), STLsurfaceFormat< Face >::writeBinary(), STLsurfaceFormat< Face >::writeBinary(), STLCore::writeBinaryHeader(), binModel::writeBinnedData(), decomposedBlockData::writeBlockEntry(), decomposedBlockData::writeBlockEntry(), decomposedBlockData::writeBlockEntry(), PDRblock::writeBlockMeshDict(), decomposedBlockData::writeBlocks(), box::writeBoxes(), writeFile::writeBreak(), coordSetWriter::writeBufferContents(), csvWriter::writeBuffered(), gnuplotWriter::writeBuffered(), rawWriter::writeBuffered(), STARCDedgeFormat::writeCase(), STARCDsurfaceFormatCore::writeCase(), mapDistributePolyMesh::writeCellMapEntries(), Foam::ensightOutput::writeCellShapes(), eddy::writeCentreOBJ(), Foam::writeChars(), Foam::ensightOutput::writeCloudField(), Foam::ensightOutput::writeCloudPositions(), codedBase::writeCodeDict(), writeFile::writeCommented(), dynamicCode::writeCommentSHA1(), fvExprDriver::writeCommon(), meshToMeshMethod::writeConnectivity(), Foam::writeConnectivity(), NASCore::writeCoord(), Foam::writeCoordHeader(), Foam::ensightOutput::Detail::writeCoordinates(), particle< Type >::writeCoordinates(), writeFile::writeCurrentTime(), edgeVertex::writeCut(), edgeVertex::writeCuts(), RegisterDebugSwitch< Type >::writeData(), liquidProperties::writeData(), addstopAtWriteNowSignalToOpt::writeData(), addwriteNowSignalToOpt::writeData(), solidBodyMotionFunction::writeData(), refinementHistory::writeData(), polyTopoChanger::writeData(), option::writeData(), AveragingMethod< Type >::writeData(), extendedFeatureEdgeMesh::writeData(), featureEdgeMesh::writeData(), topoSet::writeData(), CompactIOList< T, BaseType >::writeData(), baseIOdictionary::writeData(), GeometricField< Type, PatchField, GeoMesh >::writeData(), UniformDimensionedField< Type >::writeData(), IOmapDistribute::writeData(), populationBalanceModel::writeData(), powerLawLopesdaCosta::writeData(), optionList::writeData(), faBoundaryMesh::writeData(), MRFZone::writeData(), MRFZoneList::writeData(), DarcyForchheimer::writeData(), fixedCoeff::writeData(), porosityModelList::writeData(), powerLaw::writeData(), solidification::writeData(), fvExprDriverWriter::writeData(), Sampled< Type >::writeData(), externalCoupledTemperatureMixedFvPatchScalarField::writeData(), velocityDampingConstraint::writeData(), IOPosition< CloudType >::writeData(), binned::writeData(), general::writeData(), lumpedPointIOMovement::writeData(), lumpedPointState::writeData(), ConstantField< Type >::writeData(), MappedFile< Type >::writeData(), PatchFunction1< Type >::writeData(), UniformValueField< Type >::writeData(), searchableSurfaceWithGaps::writeData(), fieldDictionary::writeData(), CompactIOField< T, BaseType >::writeData(), decomposedBlockData::writeData(), GlobalIOField< Type >::writeData(), GlobalIOList< Type >::writeData(), IOField< Type >::writeData(), IOFieldRef< Type >::writeData(), IOList< T >::writeData(), IOListRef< T >::writeData(), IOMap< T >::writeData(), IOPtrList< T >::writeData(), rawIOField< Type >::writeData(), exprResultGlobals::writeData(), DimensionedField< Type, GeoMesh >::writeData(), RegisterSwitch< Type >::writeData(), profiling::writeData(), cellModel::writeData(), IOmapDistributePolyMesh::writeData(), IOmapDistributePolyMeshRef::writeData(), polyBoundaryMesh::writeData(), ZoneMesh< ZoneType, MeshType >::writeData(), coordinateSystems::writeData(), Constant< Type >::writeData(), CSV< Type >::writeData(), Function1< Type >::writeData(), FunctionObjectTrigger< Type >::writeData(), FunctionObjectValue< Type >::writeData(), InputValueMapper< Type >::writeData(), None< Type >::writeData(), OneConstant< Type >::writeData(), Polynomial< Type >::writeData(), ramp::writeData(), Scale< Type >::writeData(), Sine< Type >::writeData(), Square< Type >::writeData(), Table< Type >::writeData(), TableBase< Type >::writeData(), TableFile< Type >::writeData(), ZeroConstant< Type >::writeData(), TimeFunction1< Type >::writeData(), objective::writeData(), NURBS3DVolume::writeData(), adjointSolver::writeData(), adjointSimple::writeData(), RASTurbulenceModel::writeData(), simple::writeData(), porousModel::writeData(), surfaceTensionModel::writeData(), BlendedInterfacialModel< ModelType >::writeData(), dragModel::writeData(), virtualMassModel::writeData(), Sample< Type >::writeData(), surfZoneIOList::writeData(), aC10H7CH3::writeData(), Ar::writeData(), bC10H7CH3::writeData(), C10H22::writeData(), C12H26::writeData(), C13H28::writeData(), C14H30::writeData(), C16H34::writeData(), C2H5OH::writeData(), C2H6::writeData(), C2H6O::writeData(), C3H6O::writeData(), C3H8::writeData(), C4H10O::writeData(), C6H14::writeData(), C6H6::writeData(), C7H16::writeData(), C7H8::writeData(), C8H10::writeData(), C8H18::writeData(), C9H20::writeData(), CH3OH::writeData(), CH4N2O::writeData(), H2O::writeData(), iC3H8O::writeData(), IC8H18::writeData(), IDEA::writeData(), liquid::writeData(), MB::writeData(), N2::writeData(), nC3H8O::writeData(), ash::writeData(), C::writeData(), CaCO3::writeData(), solidProperties::writeData(), APIdiffCoefFunc::writeData(), NSRDSfunc0::writeData(), NSRDSfunc1::writeData(), NSRDSfunc14::writeData(), NSRDSfunc2::writeData(), NSRDSfunc3::writeData(), NSRDSfunc4::writeData(), NSRDSfunc5::writeData(), NSRDSfunc6::writeData(), NSRDSfunc7::writeData(), constant::writeData(), temperatureDependent::writeData(), liquidProperties::writeData(), thermophysicalProperties::writeData(), Foam::writeData(), DimensionedField< Type, GeoMesh >::writeData(), topoSet::writeDebug(), topoSet::writeDebug(), topoSet::writeDebug(), topoSet::writeDebug(), cellSet::writeDebug(), cellZoneSet::writeDebug(), faceSet::writeDebug(), faceZoneSet::writeDebug(), pointSet::writeDebug(), pointZoneSet::writeDebug(), cellBitSet::writeDebug(), faceBitSet::writeDebug(), faceBoolSet::writeDebug(), pointBitSet::writeDebug(), boundaryRegion::writeDict(), cellTable::writeDict(), mappedPatchBase::writeDict(), attachDetach::writeDict(), layerAdditionRemoval::writeDict(), perfectInterface::writeDict(), setUpdater::writeDict(), slidingInterface::writeDict(), enginePiston::writeDict(), engineValve::writeDict(), colourTable::writeDict(), lumpedPointState::writeDict(), surfaceFeatures::writeDict(), exprResultDelayed::writeDict(), exprResultStored::writeDict(), geometricSurfacePatch::writeDict(), cellZone::writeDict(), faceZone::writeDict(), pointZone::writeDict(), plane::writeDict(), surfZone::writeDict(), surfacePatch::writeDict(), ensightCells::writeDict(), ensightFaces::writeDict(), exprResult::writeDict(), PDRblock::gridControl::writeDict(), schemesLookup::writeDicts(), dynamicCode::writeDigest(), dynamicCode::writeDigest(), IOobject::writeDivider(), IOobject::writeEndDivider(), pairPotential::writeEnergyAndForceTables(), wallFunctionBlenders::writeEntries(), wallFunctionCoefficients::writeEntries(), MappedFile< Type >::writeEntries(), GeometricBoundaryField< Type, PatchField, GeoMesh >::writeEntries(), mapDistribute::writeEntries(), mapDistributeBase::writeEntries(), mapDistributePolyMesh::writeEntries(), CSV< Type >::writeEntries(), FunctionObjectTrigger< Type >::writeEntries(), FunctionObjectValue< Type >::writeEntries(), InputValueMapper< Type >::writeEntries(), ramp::writeEntries(), Scale< Type >::writeEntries(), Sine< Type >::writeEntries(), Square< Type >::writeEntries(), TableBase< Type >::writeEntries(), Sample< Type >::writeEntries(), dictionary::writeEntries(), dictionary::writeEntry(), PackedList< Width >::writeEntry(), FixedList< T, N >::writeEntry(), UList< T >::writeEntry(), dimensioned< Type >::writeEntry(), exprResult::writeEntry(), Field< Type >::writeEntry(), GeometricBoundaryField< Type, PatchField, GeoMesh >::writeEntry(), axes::writeEntry(), axisAngle::writeEntry(), cylindrical::writeEntry(), euler::writeEntry(), identity::writeEntry(), specified::writeEntry(), starcd::writeEntry(), coordinateSystem::writeEntry(), indirect::writeEntry(), exprString::writeEntry(), coordinateScaling< Type >::writeEntry(), PackedList< Width >::writeEntry(), FixedList< T, 2 >::writeEntry(), FixedList< T, N >::writeEntry(), UList< T >::writeEntry(), UList< CloudFunctionObject< CloudType > * >::writeEntry(), dictionary::writeEntry(), orientedType::writeEntry(), coordinateSystem::writeEntry(), indirect::writeEntry(), Foam::writeEntryIfPresent(), AMIInterpolation::writeFaceConnectivity(), Foam::ensightOutput::writeFaceConnectivity(), Foam::ensightOutput::writeFaceConnectivity(), Foam::ensightOutput::writeFaceConnectivity(), Foam::ensightOutput::writeFaceConnectivityPresorted(), ensightOutputSurface::writeFaceData(), Foam::ensightOutput::writeFaceList(), Foam::ensightOutput::writeFaceList(), Foam::ensightOutput::writeFaceList(), Foam::ensightOutput::Detail::writeFaceLocalField(), Foam::ensightOutput::Detail::writeFaceLocalField(), mapDistributePolyMesh::writeFaceMapEntries(), Foam::ensightOutput::Detail::writeFaceSubField(), Foam::ensightOutput::Detail::writeFaceSubField(), nastranWriter::writeFaceValue(), abaqusWriter::writeFaceValue(), Foam::ensightOutput::writeField(), Foam::ensightOutput::writeField(), Foam::ensightOutput::writeField(), Foam::ensightOutput::writeField(), exprResult::writeField(), Foam::ensightOutput::Detail::writeFieldComponents(), Foam::ensightOutput::Detail::writeFieldComponents(), fluxSummary::writeFileHeader(), multiFieldValue::writeFileHeader(), singleDirectionUniformBin::writeFileHeader(), uniformBin::writeFileHeader(), AMIWeights::writeFileHeader(), continuityError::writeFileHeader(), fieldExtents::writeFileHeader(), fieldMinMax::writeFileHeader(), surfaceFieldValue::writeFileHeader(), histogramModel::writeFileHeader(), momentum::writeFileHeader(), energySpectrum::writeFileHeader(), solverInfo::writeFileHeader(), timeInfo::writeFileHeader(), velocityDampingConstraint::writeFileHeader(), limitTemperature::writeFileHeader(), limitTurbulenceViscosity::writeFileHeader(), limitVelocity::writeFileHeader(), actuationDiskSource::writeFileHeader(), LocalInteraction< CloudType >::writeFileHeader(), PatchInteractionModel< CloudType >::writeFileHeader(), RecycleInteraction< CloudType >::writeFileHeader(), StandardWallInteraction< CloudType >::writeFileHeader(), sixDoFRigidBodyState::writeFileHeader(), blendingFactor::writeFileHeader(), DESModelRegions::writeFileHeader(), volFieldValue::writeFileHeader(), stabilityBlendingFactor::writeFileHeader(), wallHeatFlux::writeFileHeader(), wallShearStress::writeFileHeader(), cloudInfo::writeFileHeader(), valueAverageBase::writeFileHeader(), noiseModel::writeFileHeader(), solverInfo::writeFileHeader(), option::writeFooter(), X3DsurfaceFormatCore::writeFooter(), lumpedPointMovement::writeForcesAndMomentsVTP(), noiseModel::writeFreqDataToFile(), Foam::writeFuncsImpl(), exprDriver::writeFunctions(), genericPatchFieldBase::writeGeneric(), voxelMeshSearch::writeGrid(), option::writeHeader(), X3DsurfaceFormatCore::writeHeader(), externalCoupledMixedFvPatchField< Type >::writeHeader(), externalCoupledTemperatureMixedFvPatchScalarField::writeHeader(), IOobject::writeHeader(), STARCDCore::writeHeader(), writeFile::writeHeader(), AC3DsurfaceFormatCore::writeHeader(), Foam::writeHeader(), IOobject::writeHeader(), decomposedBlockData::writeHeader(), decomposedBlockData::writeHeader(), Foam::writeHeaderArea(), IOobject::writeHeaderContent(), Foam::writeHeaderEntry(), writeFile::writeHeaderValue(), forceCoeffs::writeIntegratedDataFile(), forces::writeIntegratedDataFile(), forceCoeffs::writeIntegratedDataFileHeader(), forces::writeIntegratedDataFileHeader(), advancingFrontAMI::writeIntersectionOBJ(), isoAdvection::writeIsoFaces(), Foam::writeJobDict(), HashTable< T, Key, Hash >::writeKeys(), NASCore::writeKeyword(), Foam::ensightOutput::Detail::writeLabelListList(), Foam::ensightOutput::Detail::writeLabelListList(), coordSetWriter::writeLine(), coordSetWriter::writeLine(), Enum< EnumType >::writeList(), PackedList< Width >::writeList(), CircularBuffer< T >::writeList(), CompactListList< T >::writeList(), IndirectListBase< T, Addr >::writeList(), LList< LListBase, T >::writeList(), UILList< LListBase, T >::writeList(), FixedList< T, N >::writeList(), UList< T >::writeList(), UList< T >::writeList(), atmAlphatkWallFunctionFvPatchScalarField::writeLocalEntries(), atmEpsilonWallFunctionFvPatchScalarField::writeLocalEntries(), atmNutkWallFunctionFvPatchScalarField::writeLocalEntries(), atmNutUWallFunctionFvPatchScalarField::writeLocalEntries(), atmNutWallFunctionFvPatchScalarField::writeLocalEntries(), atmOmegaWallFunctionFvPatchScalarField::writeLocalEntries(), nutkFilmWallFunctionFvPatchScalarField::writeLocalEntries(), epsilonWallFunctionFvPatchScalarField::writeLocalEntries(), kLowReWallFunctionFvPatchScalarField::writeLocalEntries(), nutkWallFunctionFvPatchScalarField::writeLocalEntries(), nutUBlendedWallFunctionFvPatchScalarField::writeLocalEntries(), nutUSpaldingWallFunctionFvPatchScalarField::writeLocalEntries(), nutUTabulatedWallFunctionFvPatchScalarField::writeLocalEntries(), nutUWallFunctionFvPatchScalarField::writeLocalEntries(), nutWallFunctionFvPatchScalarField::writeLocalEntries(), omegaWallFunctionFvPatchScalarField::writeLocalEntries(), nutkRoughWallFunctionFvPatchScalarField::writeLocalEntries(), Foam::writeMaps(), Matrix< Form, Type >::writeMatrix(), Foam::writeMeasured_ascii(), Foam::writeMeasured_binary(), GeometricField< Type, PatchField, GeoMesh >::writeMinMax(), faceAreaWeightAMI2D::writeNoMatch(), AABBTree< Type >::writeOBJ(), coupledPolyPatch::writeOBJ(), coupledPolyPatch::writeOBJ(), cellCuts::writeOBJ(), AABBTree< Type >::writeOBJ(), dynamicIndexedOctree< Type >::writeOBJ(), indexedOctree< Type >::writeOBJ(), Foam::meshTools::writeOBJ(), coupledPolyPatch::writeOBJ(), Foam::meshTools::writeOBJ(), Foam::meshTools::writeOBJ(), Foam::meshTools::writeOBJ(), coupledPolyPatch::writeOBJ(), cellCuts::writeOBJ(), Foam::meshTools::writeOBJ(), AABBTreeBase::writeOBJ(), indexedOctreeBase::writeOBJ(), Foam::meshTools::writeOBJ(), triangle2D::writeOBJ(), Foam::meshTools::writeOBJ(), Foam::meshTools::writeOBJ(), Foam::meshTools::writeOBJ(), collatedFileOperation::writeObject(), fileOperation::writeObject(), masterUncollatedFileOperation::writeObject(), Foam::writeObjEdges(), Foam::writeObjPoints(), mapDistributePolyMesh::writePatchMapEntries(), lumpedPointState::writePlain(), Foam::writePoint(), ensightOutputSurface::writePointData(), Foam::writePointField(), Foam::ensightOutput::writePointField(), Foam::ensightOutput::writePointField(), mapDistributePolyMesh::writePointMapEntries(), ABAQUSCore::writePoints(), STARCDCore::writePoints(), X3DsurfaceFormatCore::writePoints(), Foam::ensightOutput::writePolysPoints(), Foam::ensightOutput::writePolysPoints(), injectedParticle::writePosition(), particle< Type >::writePosition(), passivePositionParticle::writePosition(), Cloud< ParticleType >::writePositions(), propellerInfo::writePropellerPerformance(), injectedParticle::writeProperties(), CollidingParcel< ParcelType >::writeProperties(), ReactingHeterogeneousParcel< ParcelType >::writeProperties(), SprayParcel< ParcelType >::writeProperties(), KinematicParcel< ParcelType >::writeProperties(), MPPICParcel< ParcelType >::writeProperties(), ReactingMultiphaseParcel< ParcelType >::writeProperties(), ReactingParcel< ParcelType >::writeProperties(), ThermoParcel< ParcelType >::writeProperties(), particle< Type >::writeProperty(), particle< Type >::writeProperty(), particle< Type >::writePropertyName(), properties::writeResultEntries(), stateFunctionObject::writeResultEntries(), stateFunctionObject::writeResultEntries(), polyMeshFilterSettings::writeSettings(), edgeMesh::writeStats(), cellClassification::writeStats(), extendedEdgeMesh::writeStats(), surfaceFeatures::writeStats(), distributedTriSurfaceMesh::writeStats(), MeshedSurface< Face >::writeStats(), triSurface::writeStats(), Foam::edgeMeshTools::writeStats(), extendedCellToFaceStencil::writeStencilStats(), eddy::writeSurfaceOBJ(), writeFile::writeTabbed(), graph::writeTable(), coordSetWriter::writeTable(), abaqusWriter::writeTemplate(), boundaryDataWriter::writeTemplate(), debugWriter::writeTemplate(), nastranWriter::writeTemplate(), rawWriter::writeTemplate(), starcdWriter::writeTemplate(), x3dWriter::writeTemplate(), nastranWriter::writeTemplate(), xmgraceWriter::writeTemplate(), nastranWriter::writeTemplate(), csvWriter::writeTemplate(), gnuplotWriter::writeTemplate(), rawWriter::writeTemplate(), xmgraceWriter::writeTemplate(), Foam::writeTrackField(), exprResult::writeValue(), writeFile::writeValue(), nastranWriter::writeValue(), faePatchField< Type >::writeValueEntry(), faPatchField< Type >::writeValueEntry(), fvPatchField< Type >::writeValueEntry(), fvsPatchField< Type >::writeValueEntry(), valuePointPatchField< Type >::writeValueEntry(), momentum::writeValues(), exprDriver::writeVariableStrings(), Foam::writeVolField(), Foam::ensightOutput::writeVolField(), Foam::ensightOutput::writeVolField(), Foam::ensightOutput::writeVolField(), Foam::ensightOutput::writeVolField(), ensightWrite::writeVolFieldsImpl(), interfaceTrackingFvMesh::writeVTKControlPoints(), lumpedPointState::writeVTP(), propellerInfo::writeWake(), Foam::stringOps::writeWrapped(), graph::writer::writeXY(), moleculeCloud::writeXYZ(), Foam::writeZone(), and base64Formatter::~base64Formatter().
writeQuoted()
os writeQuoted (("# "+outputName+"\n") , false)
Referenced by Ostream::beginBlock(), Ostream::write(), OBJstream::write(), OSstream::write(), OBJstream::write(), and Ostream::writeKeyword().
write()
os write (aMesh. patch).edges(, aMesh. patch).localPoints()