OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToEnsight/findCloudFields.H File Reference
findCloudFields.H File Reference
Functions
List< HashTable< HashTable< word > > > regionCloudFields (meshes.size())
if (timeDirs.size() &&doLagrangian)
List< wordList > regionCloudNames (meshes.size())
forAll (regionCloudNames, regioni)
const wordList allCloudNames (allRegionClouds.sortedToc())
if (allRegionClouds.empty())
Variables
else
Detailed Description
Original source file findCloudFields.H
Definition in file findCloudFields.H.
Function Documentation
regionCloudFields()
List< HashTable< HashTable< word > > > regionCloudFields (meshes. size())
Referenced by forAll(), if(), and if().
if() [1/2]
if (timeDirs.size() && doLagrangian)
Definition at line 25 of file findCloudFields.H.
References cloudName(), forAll, forAllConstIters, io(), mesh, meshes(), regionCloudFields(), regionName, regionNames, and timeName.
regionCloudNames()
List< wordList > regionCloudNames (meshes. size())
Referenced by forAll(), and if().
forAll()
forAll (regionCloudNames , regioni)
Definition at line 122 of file findCloudFields.H.
References regionCloudFields(), regionCloudNames(), and HashTable< T, Key, Hash >::sortedToc().
allCloudNames()
const wordList allCloudNames (allRegionClouds. sortedToc())
if() [2/2]
if (allRegionClouds. empty())
Definition at line 131 of file findCloudFields.H.
Variable Documentation
else
else
Initial value:
{
        allRegionClouds.writeList(Info) << endl
Definition at line 135 of file findCloudFields.H.