OpenFOAM: applications/utilities/finiteArea/makeFaMesh/findMeshDefinitionDict.H File Reference
findMeshDefinitionDict.H File Reference
Functions
const word dictName ("faMeshDefinition")
if (args.readIfPresent("dict", dictPath))
else if (exists(runTime.path()/runTime.caseConstant()/regionDir/faMesh::meshSubDir/dictName))
IOobject meshDictIO (dictPath, runTime, IOobject::MUST_READ, IOobject::NO_WRITE, IOobject::NO_REGISTER, true)
if (!meshDictIO.typeHeaderOk< IOdictionary >(true))
Variables
autoPtr< IOdictionary > meshDictPtr
const word & regionDir = polyMesh::regionName(regionName)
else
IOdictionary & meshDefDict = *meshDictPtr
Detailed Description
Original source file findMeshDefinitionDict.H
Definition in file findMeshDefinitionDict.H.
Function Documentation
dictName()
const word dictName ("faMeshDefinition")
Referenced by codedBase::codeDict(), coordinateSystem::coordinateSystem(), cylindrical::cylindrical(), if(), if(), InjectedParticleDistributionInjection< CloudType >::info(), InjectedParticleDistributionInjection< CloudType >::InjectedParticleDistributionInjection(), basicThermo::lookupThermo(), loopControl::loopControl(), loopControl::loopControl(), moleFractions< ThermoType >::moleFractions(), coordinateSystem::New(), fluidThermo::New(), rhoThermo::New(), psiReactionThermo::New(), psiuReactionThermo::New(), rhoReactionThermo::New(), solidThermo::New(), basicThermo::New(), basicThermo::New(), coordinateSystem::New(), engineTime::New(), coordinateSystem::NewIfPresent(), coordinateSystem::NewIfPresent(), writeDictionary::read(), solution::upgradeSolverDict(), binned::writeDict(), general::writeDict(), and dictionary::writeEntry().
if() [1/3]
if (args. readIfPresent"dict", dictPath)
Definition at line 29 of file findMeshDefinitionDict.H.
References dictName().
if() [2/3]
else if (exists(runTime.path()/runTime.caseConstant()/regionDir/faMesh::meshSubDir/dictName))
Definition at line 38 of file findMeshDefinitionDict.H.
References args, dictName(), argList::executable(), regionDir, runTime, and WarningIn.
meshDictIO()
IOobject meshDictIO (dictPath , runTime , IOobject::MUST_READ , IOobject::NO_WRITE , IOobject::NO_REGISTER , true)
Referenced by if().
if() [3/3]
if (!meshDictIO.typeHeaderOk< IOdictionary > true)
Definition at line 84 of file findMeshDefinitionDict.H.
References FatalErrorInFunction, and meshDictIO().
Variable Documentation
meshDictPtr
autoPtr<IOdictionary> meshDictPtr
Definition at line 23 of file findMeshDefinitionDict.H.
regionDir
const word& regionDir = polyMesh::regionName(regionName)
Definition at line 27 of file findMeshDefinitionDict.H.
Referenced by if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), and vtkWrite::write().
else
else
Initial value:
{
        dictPath = runTime.system()/regionDir/dictName
Definition at line 67 of file findMeshDefinitionDict.H.
meshDefDict
IOdictionary& meshDefDict = *meshDictPtr
Definition at line 97 of file findMeshDefinitionDict.H.