OpenFOAM: applications/utilities/mesh/generation/blockMesh/findBlockMeshDict.H File Reference
findBlockMeshDict.H File Reference
Functions
const word dictName ("blockMeshDict")
if (args.readIfPresent("dict", dictPath))
else if (exists(runTime.path()/runTime.constant()/regionDir/polyMesh::meshSubDir/dictName))
IOobject meshDictIO (dictPath, runTime, IOobject::MUST_READ, IOobject::NO_WRITE, IOobject::NO_REGISTER)
if (!meshDictIO.typeHeaderOk< IOdictionary >(true))
Variables
autoPtr< IOdictionary > meshDictPtr
const word & regionDir = polyMesh::regionName(regionName)
else
const IOdictionary & meshDict = *meshDictPtr
Detailed Description
Original source file findBlockMeshDict.H
Definition in file findBlockMeshDict.H.
Function Documentation
dictName()
const word dictName ("blockMeshDict")
Referenced by if(), and if().
if() [1/3]
if (args. readIfPresent"dict", dictPath)
Definition at line 30 of file findBlockMeshDict.H.
References dictName().
if() [2/3]
else if (exists(runTime.path()/runTime.constant()/regionDir/polyMesh::meshSubDir/dictName))
Definition at line 39 of file findBlockMeshDict.H.
References args, dictName(), argList::executable(), regionDir, runTime, and WarningIn.
meshDictIO()
IOobject meshDictIO (dictPath , runTime , IOobject::MUST_READ , IOobject::NO_WRITE , IOobject::NO_REGISTER)
Referenced by if().
if() [3/3]
if (!meshDictIO.typeHeaderOk< IOdictionary > true)
Definition at line 82 of file findBlockMeshDict.H.
References FatalErrorInFunction, and meshDictIO().
Variable Documentation
meshDictPtr
autoPtr<IOdictionary> meshDictPtr
Definition at line 24 of file findBlockMeshDict.H.
regionDir
const word& regionDir = polyMesh::regionName(regionName)
Definition at line 28 of file findBlockMeshDict.H.
Referenced by if().
else
else
Initial value:
{
        dictPath = runTime.system()/regionDir/dictName
Definition at line 66 of file findBlockMeshDict.H.
meshDict
const IOdictionary& meshDict = *meshDictPtr
Definition at line 95 of file findBlockMeshDict.H.