OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/fluid/createFluidFields.H File Reference
createFluidFields.H File Reference
Functions
PtrList< rhoReactionThermo > thermoFluid (fluidRegions.size())
PtrList< volScalarField > rhoFluid (fluidRegions.size())
PtrList< volVectorField > UFluid (fluidRegions.size())
PtrList< surfaceScalarField > phiFluid (fluidRegions.size())
PtrList< uniformDimensionedScalarField > hRefFluid (fluidRegions.size())
PtrList< volScalarField > ghFluid (fluidRegions.size())
PtrList< surfaceScalarField > ghfFluid (fluidRegions.size())
PtrList< compressible::turbulenceModel > turbulenceFluid (fluidRegions.size())
PtrList< CombustionModel< rhoReactionThermo > > reactionFluid (fluidRegions.size())
PtrList< volScalarField > p_rghFluid (fluidRegions.size())
PtrList< radiation::radiationModel > radiation (fluidRegions.size())
PtrList< volScalarField > KFluid (fluidRegions.size())
PtrList< volScalarField > dpdtFluid (fluidRegions.size())
PtrList< multivariateSurfaceInterpolationScheme< scalar >::fieldTable > fieldsFluid (fluidRegions.size())
PtrList< volScalarField > QdotFluid (fluidRegions.size())
PtrList< fvVectorMatrix > UEqFluid (fluidRegions.size())
List< scalar > initialMassFluid (fluidRegions.size())
List< bool > frozenFlowFluid (fluidRegions.size(), false)
PtrList< IOMRFZoneList > MRFfluid (fluidRegions.size())
PtrList< fv::options > fluidFvOptions (fluidRegions.size())
List< label > pRefCellFluid (fluidRegions.size())
List< scalar > pRefValueFluid (fluidRegions.size())
PtrList< dimensionedScalar > rhoMinFluid (fluidRegions.size())
PtrList< dimensionedScalar > rhoMaxFluid (fluidRegions.size())
PtrList< pressureControl > pressureControls (fluidRegions.size())
forAll (fluidRegions, i)
Variables
const uniformDimensionedVectorField & g = meshObjects::gravity::New(runTime)
Function Documentation
thermoFluid()
PtrList< rhoReactionThermo > thermoFluid (fluidRegions. size())
rhoFluid()
PtrList< volScalarField > rhoFluid (fluidRegions. size())
UFluid()
PtrList< volVectorField > UFluid (fluidRegions. size())
phiFluid()
PtrList< surfaceScalarField > phiFluid (fluidRegions. size())
hRefFluid()
PtrList< uniformDimensionedScalarField > hRefFluid (fluidRegions. size())
ghFluid()
PtrList< volScalarField > ghFluid (fluidRegions. size())
ghfFluid()
PtrList< surfaceScalarField > ghfFluid (fluidRegions. size())
turbulenceFluid()
PtrList< compressible::turbulenceModel > turbulenceFluid (fluidRegions. size())
Referenced by forAll().
reactionFluid()
PtrList< CombustionModel< rhoReactionThermo > > reactionFluid (fluidRegions. size())
Referenced by forAll().
p_rghFluid()
PtrList< volScalarField > p_rghFluid (fluidRegions. size())
radiation()
PtrList< radiation::radiationModel > radiation (fluidRegions. size())
KFluid()
PtrList< volScalarField > KFluid (fluidRegions. size())
Referenced by forAll().
dpdtFluid()
PtrList< volScalarField > dpdtFluid (fluidRegions. size())
Referenced by forAll().
fieldsFluid()
PtrList< multivariateSurfaceInterpolationScheme< scalar >::fieldTable > fieldsFluid (fluidRegions. size())
QdotFluid()
PtrList< volScalarField > QdotFluid (fluidRegions. size())
Referenced by forAll().
UEqFluid()
PtrList< fvVectorMatrix > UEqFluid (fluidRegions. size())
initialMassFluid()
List< scalar > initialMassFluid (fluidRegions. size())
frozenFlowFluid()
List< bool > frozenFlowFluid (fluidRegions. size(), false)
MRFfluid()
PtrList< IOMRFZoneList > MRFfluid (fluidRegions. size())
fluidFvOptions()
PtrList< fv::options > fluidFvOptions (fluidRegions. size())
pRefCellFluid()
List< label > pRefCellFluid (fluidRegions. size())
pRefValueFluid()
List< scalar > pRefValueFluid (fluidRegions. size())
rhoMinFluid()
PtrList< dimensionedScalar > rhoMinFluid (fluidRegions. size())
Referenced by forAll().
rhoMaxFluid()
PtrList< dimensionedScalar > rhoMaxFluid (fluidRegions. size())
Referenced by forAll().
pressureControls()
PtrList< pressureControl > pressureControls (fluidRegions. size())
Referenced by forAll().
forAll()
forAll (fluidRegions , i)
Definition at line 38 of file createFluidFields.H.
References composition, dpdtFluid(), fieldsFluid(), fluidFvOptions(), fluidRegions(), forAll, frozenFlowFluid(), g, ghfFluid(), ghFluid(), he, hRefFluid(), initialMassFluid(), KFluid(), MRFfluid(), p, p_rghFluid(), phiFluid(), pimpleDict, pRefCellFluid(), pRefValueFluid(), pressureControl, pressureControls(), QdotFluid(), radiation(), reactionFluid(), rhoFluid(), rhoMaxFluid(), rhoMinFluid(), runTime, setRefCell(), T, thermoFluid(), turbulenceFluid(), UEqFluid(), UFluid(), and Y.
Variable Documentation
g
const uniformDimensionedVectorField& g = meshObjects::gravity::New(runTime)
Definition at line 35 of file createFluidFields.H.