OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/fluid/compressibleMultiRegionCourantNo.H File Reference
compressibleMultiRegionCourantNo.H File Reference
Functions
forAll (fluidRegions, regioni)
Variables
scalar CoNum = -GREAT
Function Documentation
forAll()
forAll (fluidRegions , regioni)
Definition at line 3 of file compressibleMultiRegionCourantNo.H.
References CoNum, fluidRegions(), phiFluid(), rhoFluid(), and runTime.
Variable Documentation
CoNum
scalar CoNum = -GREAT
Definition at line 1 of file compressibleMultiRegionCourantNo.H.