OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToEnsight/convertLagrangian.H File Reference
convertLagrangian.H File Reference
Macros
#define ensight_WRITE_CLOUD_FIELD(PrimitiveType)
Functions
if (doLagrangian)
Detailed Description
Original source file convertLagrangian.H
Definition in file convertLagrangian.H.
Macro Definition Documentation
ensight_WRITE_CLOUD_FIELD
#define ensight_WRITE_CLOUD_FIELD (PrimitiveType)
Value:
                                                                              \
                if (fieldType == IOField<PrimitiveType>::typeName)            \
                {                                                             \
                    autoPtr<ensightFile> os =                                 \
                        ensCase.newCloudData<PrimitiveType>                   \
                        (                                                     \
                            cloudName,                                        \
                            fieldName                                         \
                        );                                                    \
                                                                              \
                    wrote = ensightOutput::readWriteCloudField<PrimitiveType> \
                    (                                                         \
                        os.ref(),                                             \
                        fieldObject,                                          \
                        fieldExists                                           \
                    );                                                        \
                    break;                                                    \
                }
Function Documentation
if()
if (doLagrangian)
Definition at line 22 of file convertLagrangian.H.
References cloudName(), ensight_WRITE_CLOUD_FIELD, mesh, os(), regionCloudFields(), regionCloudNames(), regionDir, and runTime.