OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToVTK/convertVolumeFields.H File Reference
convertVolumeFields.H File Reference
Functions
if (doInternal||doBoundary)
if (doInternal)
fileName vtmOutputBase (outputDir/regionDir/vtkName+timeDesc)
if (doBoundary)
if (oneBoundary &&patchIds.size())
else if (patchIds.size())
if (doPointValues &&(nVolFields||nDimFields))
writeAllDimFields (internalWriter, meshProxy, objects, true, cacheFieldsPtr.get())
if (doPointValues)
if (internalWriter)
for (vtk::patchWriter &writer :patchWriters)
pInterp clear ()
if (UPstream::master())
Variables
const label nVolFields
const label nDimFields
label nPointFields
vtk::vtmWriter vtmWriter
vtk::vtmWriter vtmBoundaries
autoPtr< vtk::internalWriter > internalWriter
autoPtr< volPointInterpolation > pInterp
const polyBoundaryMesh & patches = mesh.boundaryMesh()
PtrList< vtk::patchWriter > patchWriters
PtrList< PrimitivePatchInterpolation< primitivePatch > > patchInterps
labelList patchIds
std::unique_ptr< objectRegistry > cacheFieldsPtr
Detailed Description
Original source file convertVolumeFields.H
Definition in file convertVolumeFields.H.
Function Documentation
if() [1/9]
if (doInternal|| doBoundary)
Definition at line 48 of file convertVolumeFields.H.
if() [2/9]
if (doInternal)
Definition at line 52 of file convertVolumeFields.H.
vtmOutputBase()
fileName vtmOutputBase (outputDir/regionDir/vtkName+ timeDesc)
Referenced by if(), if(), and if().
if() [3/9]
if (doBoundary)
Definition at line 139 of file convertVolumeFields.H.
References patches, and patchIds.
if() [4/9]
if (oneBoundary &&patchIds. size())
Definition at line 144 of file convertVolumeFields.H.
References args, patchIds, patchInterps, patchWriters, regionDir, argList::relativePath(), PtrList< T >::resize(), PtrList< T >::set(), vtmOutputBase(), vtmWriter, and writer().
if() [5/9]
else if (patchIds. size())
Definition at line 186 of file convertVolumeFields.H.
References args, nPatchWriters, patches, patchId(), patchIds, patchInterps, patchWriters, pp(), regionDir, argList::relativePath(), PtrList< T >::resize(), PtrList< T >::set(), vtmBoundaries, vtmOutputBase(), vtmWriter, and writer().
if() [6/9]
if (doPointValues && nVolFields||nDimFields)
Definition at line 270 of file convertVolumeFields.H.
References cacheFieldsPtr, and runTime.
writeAllDimFields()
writeAllDimFields (internalWriter , meshProxy , objects , true , cacheFieldsPtr. get())
Referenced by if(), and if().
if() [7/9]
if (doPointValues)
Definition at line 352 of file convertVolumeFields.H.
References cacheFieldsPtr, forAll, internalWriter, nDimFields, nPointFields, nVolFields, patchInterps, patchWriters, pInterp, and writeAllDimFields().
if() [8/9]
if (internalWriter)
Definition at line 420 of file convertVolumeFields.H.
References internalWriter.
for()
for (vtk::patchWriter &writer :patchWriters)
Definition at line 425 of file convertVolumeFields.H.
References writer().
clear()
pInterp clear ()
if() [9/9]
if (UPstream::master())
Definition at line 437 of file convertVolumeFields.H.
References outputName(), regionDir, regionName, vtmBoundaries, vtmOutputBase(), and vtmWriter.
Variable Documentation
nVolFields
const label nVolFields
Initial value:
=
    (
        (doInternal || doBoundary)
      ? objects.count(stringListOps::foundOp<word>(fieldTypes::volume))
      : 0
    )
Definition at line 26 of file convertVolumeFields.H.
Referenced by if().
nDimFields
const label nDimFields
Initial value:
=
    (
        (doInternal || doBoundary)
      ? objects.count(stringListOps::foundOp<word>(fieldTypes::internal))
      : 0
    )
Definition at line 33 of file convertVolumeFields.H.
Referenced by if(), and vtkWrite::write().
nPointFields
label nPointFields
Initial value:
=
    (
        doPointValues
      ? objects.count(stringListOps::foundOp<word>(fieldTypes::point))
      : 0
    )
Definition at line 40 of file convertVolumeFields.H.
Referenced by if().
vtmWriter
vtk::vtmWriter vtmWriter
Definition at line 67 of file convertVolumeFields.H.
Referenced by if(), if(), if(), and vtkWrite::write().
vtmBoundaries
vtk::vtmWriter vtmBoundaries
Definition at line 70 of file convertVolumeFields.H.
Referenced by if(), if(), if(), and vtkWrite::write().
internalWriter
autoPtr<vtk::internalWriter> internalWriter
Definition at line 73 of file convertVolumeFields.H.
Referenced by if(), and if().
pInterp
autoPtr<volPointInterpolation> pInterp
Definition at line 76 of file convertVolumeFields.H.
Referenced by if(), WeberNumberReacting< CloudType >::postEvolve(), vtkWrite::write(), internalWriter::write(), internalWriter::write(), Foam::writeAllDimFields(), Foam::writeDimFields(), Foam::writeVolFields(), and vtkWrite::writeVolFieldsImpl().
patches
const polyBoundaryMesh& patches = mesh.boundaryMesh()
Definition at line 133 of file convertVolumeFields.H.
Referenced by if(), and if().
patchWriters
PtrList<vtk::patchWriter> patchWriters
Definition at line 135 of file convertVolumeFields.H.
Referenced by if(), if(), and if().
patchInterps
PtrList<PrimitivePatchInterpolation<primitivePatch> > patchInterps
Definition at line 136 of file convertVolumeFields.H.
Referenced by if(), if(), if(), vtkWrite::write(), Foam::writeVolFields(), and vtkWrite::writeVolFieldsImpl().
patchIds
labelList patchIds
Definition at line 138 of file convertVolumeFields.H.
Referenced by if(), if(), and if().
cacheFieldsPtr
std::unique_ptr<objectRegistry> cacheFieldsPtr
Definition at line 268 of file convertVolumeFields.H.
Referenced by if(), and if().