OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToGMV/gmvOutputSpray.H File Reference
gmvOutputSpray.H File Reference
Functions
gmvFile<< "tracers "<< particles.size()<< nl;for(const passiveParticle &p :particles){ gmvFile<< p.position().x()<< " ";}gmvFile<< nl;for(const passiveParticle &p :particles){ gmvFile<< p.position().y()<< " ";}gmvFile<< nl;for(const passiveParticle &p :particles){ gmvFile<< p.position().z()<< " ";}gmvFile<< nl;forAll(lagrangianScalarNames, i){ word name=lagrangianScalarNames[i];IOField< scalar > s (IOobject(name, runTime.timeName(), cloud::prefix, mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
if (s.size())
Function Documentation
s()
gmvFile<< "tracers "<< particles.size()<< nl;for(const passiveParticle &p :particles){ gmvFile<< p.position().x()<< " ";}gmvFile<< nl;for(const passiveParticle &p :particles){ gmvFile<< p.position().y()<< " ";}gmvFile<< nl;for(const passiveParticle &p :particles){ gmvFile<< p.position().z()<< " ";}gmvFile<< nl;forAll(lagrangianScalarNames, i){ word name=lagrangianScalarNames[i]; IOField< scalar > s (IOobject(name, runTime.timeName(), cloud::prefix, mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
Referenced by greyMeanAbsorptionEmission::aCont(), wideBandAbsorptionEmission::aCont(), oversetFvMeshBase::addInterpolation(), Foam::areaInvDistSqrWeightedNormal(), Foam::atan2(), Foam::atan2(), Foam::atan2(), Foam::atan2(), Foam::atan2(), Foam::atan2(), Foam::atan2(), Foam::atan2(), Foam::barycentric01(), barycentric01Impl(), Foam::barycentric2D01(), barycentric2D01Impl(), triSurfaceTools::calcInterpolationWeights(), Foam::calcLeVector(), genericRagelLemonDriver::cbegin(), genericRagelLemonDriver::cend(), voxelMeshSearch::centre(), searchableSurfaces::checkClosed(), primitiveMeshGeometry::checkFaceDotProduct(), searchableSurfaces::checkNormalOrientation(), searchableSurfaces::checkQuality(), triSurfaceTools::classify(), Foam::cmptAv(), Foam::cmptMag(), Foam::cmptMagSqr(), Foam::cmptMax(), Foam::cmptMin(), Foam::cmptSqr(), conjugateGradient::computeCorrection(), rotorDiskSource::constructGeometry(), string::contains(), string::contains(), genericRagelLemonDriver::content(), eddyDissipationModelBase< ReactionThermo, ThermoType >::correct(), infinitelyFastChemistry< ReactionThermo, ThermoType >::correct(), particle< Type >::correctAfterParallelTransfer(), Foam::stringOps::count(), Foam::stringOps::count(), particle< Type >::currentTimeFraction(), cutFaceAdvect::cutPoints(), cutFaceAdvect::cutPoints(), diaedg(), distributedTriSurfaceMesh::distribute(), snappyVoxelMeshDriver::doRefine(), Foam::dot(), Foam::dot(), molecule::constantProperties::electrostaticSite(), string::ends_with(), string::ends_with(), string::endsWith(), energyTransport::energyTransport(), VectorSpaceOps< N, I >::eqOpS(), Grimshaw::eta(), setFlow::execute(), energyTransport::execute(), scalarTransport::execute(), Foam::stringOps::expand(), Foam::stringOps::expand(), Foam::stringOps::expand(), expressionEntry::expand(), Foam::expandLeading(), Foam::expandLeadingTag(), Foam::expandLeadingTilde(), Foam::expandString(), cellQuality::faceNonOrthogonality(), primitiveMeshTools::faceOrthogonality(), searchableSurfaceCollection::findLine(), searchableExtrudedCircle::findNearest(), searchableSurfacesQueries::findNearest(), findParameterAlternative(), Foam::findRootEllipseDistance(), Foam::findRootEllipsoidDistance(), for(), relaxedNonOrthoGaussLaplacianScheme< Type, GType >::fvmLaplacian(), fvsPatchField< scalar >::fvsPatchField(), Foam::gAverage(), FIRECore::getFireString(), triSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getRegion(), fileName::hasExt(), word::hasExt(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), Foam::HSV_to_RGB(), if(), if(), memorybuf::in::in(), voxelMeshSearch::index(), voxelMeshSearch::index3(), fluxSummary::initialiseSurfaceAndDirection(), Foam::stringOps::inplaceExpand(), expressionEntry::inplaceExpand(), Foam::stringOps::inplaceExpand(), Foam::stringOps::inplaceExpand(), Foam::stringOps::inplaceExpand(), Foam::stringOps::inplaceLower(), Foam::stringOps::inplaceRemoveComments(), Foam::stringOps::inplaceRemoveSpace(), Foam::stringOps::inplaceReplaceVar(), Foam::stringOps::inplaceTrim(), Foam::stringOps::inplaceTrimLeft(), Foam::stringOps::inplaceTrimRight(), Foam::stringOps::inplaceUpper(), cellCellStencil::interpolate(), volPointInterpolation::interpolateDimensionedInternalField(), Foam::colourTools::interpolateDiverging(), Foam::colourTools::interpolateDiverging(), Dual< Type >::interpolateGrad(), Foam::colourTools::interpolateHSV(), Foam::colourTools::interpolateHSV(), Foam::colourTools::interpolateRGB(), isoSurfaceTopo::interpolateTemplate(), triangleFuncs::intersectAxesBundle(), treeBoundBox::intersects(), Foam::inv(), Foam::inv(), Foam::Math::invIncGamma(), fileName::isBackup(), isoSurfaceTopo::isoSurfaceTopo(), token::isWord(), TDACChemistryModel< CompType, ThermoType >::jacobian(), TDACChemistryModel< CompType, ThermoType >::jacobian(), updateMethod::leftMult(), triangle2D::lineSegmentIntersectionPoint(), Foam::stringOps::lower(), Foam::LUDecompose(), Foam::mag(), Foam::mag(), Foam::magSqr(), dynamicRefineFvMesh::mapFields(), meshedSurfRef::meshedSurfRef(), Foam::minimaxs(), SVD::minNonZeroS(), trackedParticle::move(), molecule::move(), KinematicParcel< ParcelType >::move(), Foam::name(), Foam::name(), fileName::nameLessExt(), line< Point, PointRef >::nearestDist(), line< Point, PointRef >::nearestDist(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestSamples(), Foam::neg(), Foam::neg(), Foam::neg0(), Foam::neg0(), Foam::negPart(), Foam::negPart(), cellQuality::nonOrthogonality(), surfaceLocation::normal(), Field< Type >::normalise(), quaternion::normalise(), Vector< Cmpt >::normalise(), Foam::normalised(), Foam::normalised(), AMIInterpolation::normaliseWeights(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), StandardChemistryModel< ReactionThermo, ThermoType >::omega(), TDACChemistryModel< CompType, ThermoType >::omega(), StandardChemistryModel< CompType, ThermoType >::omegaI(), token::operator!=(), substance::operator!=(), regExpCxx::meta::operator()(), Foam::operator*(), Foam::operator*(), Foam::operator*(), Foam::operator*(), Foam::operator*(), Foam::operator*(), Foam::operator*(), Foam::operator*(), Foam::operator*(), Foam::operator*(), Foam::operator*(), Foam::operator*(), Foam::operator*(), Foam::operator*(), Foam::operator*(), Foam::operator*(), SubField< Type >::operator*=(), MinMax< T >::operator*=(), dimensioned< Type >::operator*=(), complex::operator*=(), quaternion::operator*=(), faePatchField< Type >::operator*=(), faPatchField< Type >::operator*=(), fvPatchField< Type >::operator*=(), fvsPatchField< Type >::operator*=(), polynomialFunction::operator*=(), septernion::operator*=(), VectorSpace< Form, Cmpt, Ncmpts >::operator*=(), adjointFarFieldPressureFvPatchScalarField::operator*=(), polynomialSolidTransport< Thermo, PolySize >::operator*=(), adiabaticPerfectFluid< Specie >::operator*=(), Boussinesq< Specie >::operator*=(), icoPolynomial< Specie, PolySize >::operator*=(), incompressiblePerfectGas< Specie >::operator*=(), linear< Type >::operator*=(), PengRobinsonGas< Specie >::operator*=(), perfectFluid< Specie >::operator*=(), perfectGas< Specie >::operator*=(), rhoConst< Specie >::operator*=(), rPolynomial< Specie >::operator*=(), specie::operator*=(), hPolynomialThermo< EquationOfState, PolySize >::operator*=(), thermo< Thermo, Type >::operator*=(), constTransport< Thermo >::operator*=(), logPolynomialTransport< Thermo, PolySize >::operator*=(), polynomialTransport< Thermo, PolySize >::operator*=(), sutherlandTransport< Thermo >::operator*=(), WLFTransport< Thermo >::operator*=(), Matrix< Form, Type >::operator*=(), LduMatrix< Type, DType, LUType >::operator*=(), lduMatrix::operator*=(), Foam::operator+(), complex::operator+=(), Matrix< Form, Type >::operator+=(), complex::operator-=(), Matrix< Form, Type >::operator-=(), Foam::operator/(), Foam::operator/(), Foam::operator/(), Foam::operator/(), Foam::operator/(), Foam::operator/(), Foam::operator/(), Foam::operator/(), Foam::operator/(), Foam::operator/(), Foam::operator/(), Foam::operator/(), Foam::operator/(), Foam::operator/(), Foam::operator/(), Foam::operator/(), SubField< Type >::operator/=(), MinMax< T >::operator/=(), dimensioned< Type >::operator/=(), complex::operator/=(), quaternion::operator/=(), faePatchField< Type >::operator/=(), faPatchField< Type >::operator/=(), fvPatchField< Type >::operator/=(), polynomialFunction::operator/=(), septernion::operator/=(), VectorSpace< Form, Cmpt, Ncmpts >::operator/=(), adjointFarFieldPressureFvPatchScalarField::operator/=(), fileName::operator/=(), Matrix< Form, Type >::operator/=(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), word::operator=(), complex::operator=(), quaternion::operator=(), word::operator=(), word::operator=(), word::operator=(), word::operator=(), word::operator=(), token::operator=(), word::operator=(), scaledFixedValueFvPatchField< Type >::operator==(), scaledFixedValueFvPatchField< Type >::operator==(), token::operator==(), substance::operator==(), scaledFixedValueFvPatchField< Type >::operator==(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), VectorSpaceOps< N, I >::opSV(), VectorSpaceOps< N, I >::opVS(), orientedSurface::orient(), orientedSurface::orient(), memorybuf::out::out(), distributedTriSurfaceMesh::overlappingSurface(), distributedTriSurfaceMesh::overlappingSurface(), Pair< point >::Pair(), Pair< T >::Pair(), Pair< T >::Pair(), Pair< T >::Pair(), molecule::constantProperties::pairPotentialSite(), scalarRanges::parse(), Foam::pos(), Foam::pos0(), Foam::pos0(), projectCurveEdge::position(), polyline::positionAndDirection(), Foam::posPart(), Foam::posPart(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow(), Foam::pow025(), Foam::pow3(), Foam::pow4(), Foam::pow5(), Foam::pow6(), quaternion::quaternion(), Foam::Ra(), sampledSets::read(), sampledSurfaces::read(), dimensionSet::read(), ensightSurfaceReader::readCase(), particle< Type >::readData(), functionEntry::readLine(), Foam::recursiveExpand(), DAC< CompType, ThermoType >::reduceMechanism(), DRG< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), EFA< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), Foam::stringOps::removeComments(), meshRefinement::removeGapCells(), FieldField< Field, Type >::replace(), fvFieldDecomposer::reset(), fvFieldDecomposer::reset(), meshedSurfRef::reset(), memorybuf::in::resetg(), memorybuf::out::resetp(), faceAreaWeightAMI::restartUncoveredSourceFace(), cyclicAMIPolyPatch::reverseTransformPosition(), Foam::RGB_to_HSV(), updateMethod::rightMult(), Foam::rotationTensor(), Foam::Rx(), Foam::Ry(), Foam::Rz(), s_len_trim(), PPCG::scalarSolveCG(), scalarTransport::scalarTransport(), scaledFixedValueFvPatchField< Type >::scaledFixedValueFvPatchField(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaces::searchableSurfaces(), VectorSpaceOps< N, I >::SeqOp(), IOobject::setBad(), distributedDILUPreconditioner::setFinished(), UnsortedMeshedSurface< Face >::setSize(), TDACChemistryModel< CompType, ThermoType >::setTabulationResultsAdd(), Foam::sign(), Foam::sign(), Foam::sign(), StandardChemistryModel< CompType, ThermoType >::solve(), oversetFvMeshBase::solveOverset(), SprayParcel< ParcelType >::solveTABEq(), Foam::splitStringToList(), Foam::sqr(), Foam::stabilise(), Foam::stabilise(), Foam::stabilise(), Foam::stabilise(), Foam::stabilise(), Foam::stabilise(), Foam::stabilise(), string::starts_with(), string::starts_with(), string::startsWith(), faceAreaWeightAMI2D::storeInterArea(), StringStreamAllocator< StreamType >::str(), fluxSummary::surfaceModeWrite(), SVD::SVD(), swapec(), StandardChemistryModel< ReactionThermo, ThermoType >::tc(), timestring(), fluxSummary::totalArea(), triSurfaceTools::track(), wallBoundedParticle::trackFaceTri(), triSurfaceTools::trackToEdge(), triSurface::transfer(), sixDoFRigidBodyMotion::transform(), rigidBodyMotion::transformPoints(), cyclicPolyPatch::transformPosition(), cyclicAMIPolyPatch::transformPosition(), cyclicAMIPolyPatch::transformPosition(), cyclicPolyPatch::transformPosition(), triangle< Point, PointRef >::triangleOverlap(), triangulation_print(), Foam::stringOps::trim(), Foam::stringOps::trimLeft(), Foam::stringOps::trimRight(), turbGen::U(), Grimshaw::Uf(), triangle< Point, PointRef >::unitNormal(), face::unitNormal(), line< Point, PointRef >::unitVec(), edge::unitVec(), surfaceFieldValue::update(), cellVolumeWeight::update(), plenumPressureFvPatchScalarField::updateCoeffs(), scaledFixedValueFvPatchField< Type >::updateCoeffs(), timeVaryingMappedFixedValuePointPatchField< Type >::updateCoeffs(), BFGS::updateHessian(), DBFGS::updateHessian(), SR1::updateHessian(), EulerImplicit< ChemistryModel >::updateRRInReactionI(), Foam::stringOps::upper(), word::validate(), colourTable::value(), MappedFile< Type >::value(), Vector2D< scalar >::Vector2D(), surfaceFieldValue::write(), scalarTransport::write(), meshRefinement::write(), appendRawFormatter::write(), foamVtkBase64Layer::write(), legacyRawFormatter::write(), base64Layer::write(), functionEntry::write(), surfaceLocation::write(), voxelMeshSearch::writeGrid(), injectedParticle::writePosition(), particle< Type >::writePosition(), passivePositionParticle::writePosition(), searchableSurfaces::writeStats(), eddy::writeSurfaceOBJ(), memorybuf::in::xsgetn(), and memorybuf::out::xsputn().
if()
if (s. size())
Definition at line 37 of file gmvOutputSpray.H.
References forAll, n, and s().