OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToGMV/gmvOutputHeader.H File Reference
gmvOutputHeader.H File Reference
Variables
const pointField & points = mesh.points()
label nPoints = points.size()
const cellShapeList & cells = mesh.cellShapes()
Variable Documentation
points
const pointField& points = mesh.points()
Definition at line 1 of file gmvOutputHeader.H.
Referenced by AABBTree< Type >::AABBTree(), abaqusWriter::abaqusWriter(), extendedEdgeMesh::add(), boundBox::add(), boundBox::add(), boundBox::add(), boundBox::add(), boundBox::add(), polyMeshAdder::add(), polyTopoChange::addMesh(), pointPatchField< Type >::addToInternalField(), geomDecomp::adjustPoints(), cellToCellStencil::allCoupledFacesPatch(), cellToFaceStencil::allCoupledFacesPatch(), setAndNormalToFaceZone::applyToSet(), polyPatch::areaFraction(), triFace::areaNormal(), boundaryDataWriter::boundaryDataWriter(), treeDataEdge::bounds(), treeDataEdge::bounds(), treeDataEdge::bounds(), Foam::boundsImpl(), triFace::box(), treeDataEdge::boxes(), treeDataEdge::boxes(), treeDataPrimitivePatch< PatchType >::boxes(), PatchTools::calcBounds(), faceCoupleInfo::calcFaceCentres(), faceCoupleInfo::calcFacePointAverages(), coupledPolyPatch::calcFaceTol(), processorPolyPatch::calcGeometry(), triSurfaceTools::calcInterpolationWeights(), Foam::calcNormalDistance_filtered(), Foam::calcNormalDistance_nonzero(), Foam::calcNormalDistance_zero(), cutFaceAdvect::calcSubFace(), cutFace::calcSubFace(), cutFace::calcSubFace(), cutFace::calcSubFace(), deltaBoundary::cellCenters_d(), polyMesh::cellTree(), cellModel::centre(), cellShape::centre(), face::centre(), triFace::centre(), pyramid< Point, PointRef, PolygonRef >::centre(), boundaryMesh::changeFaces(), polyMesh::checkEdgeAlignment(), polyMeshGeometry::checkEdgeLength(), primitiveMesh::checkFaceAngles(), primitiveMesh::checkFaceAngles(), primitiveMesh::checkFaceFlatness(), primitiveMesh::checkFaceFlatness(), primitiveMesh::checkFacePyramids(), primitiveMesh::checkFacePyramids(), MeshedSurface< Face >::checkFaces(), polyMeshGeometry::checkFaceSkewness(), polyMesh::checkFaceSkewness(), primitiveMesh::checkFaceSkewness(), primitiveMesh::checkFaceSkewness(), Foam::checkFireEdges(), Foam::checkFireEdges(), motionSmootherAlgo::checkMesh(), motionSmootherAlgo::checkMesh(), triSurface::checkTriangles(), meshRefinement::collectAndPrint(), collector::collector(), triSurface::compactPoints(), NURBS3DVolume::computeParametricCoordinates(), NURBS3DVolume::computeParametricCoordinates(), pointConstraints::constrainDisplacement(), boundBox::contains(), boundBox::contains(), boundBox::contains(), boundBox::containsAny(), boundBox::containsAny(), boundBox::containsAny(), NURBS3DVolume::coordinates(), polySurface::copySurface(), surfMesh::copySurface(), inversePointDistanceDiffusivity::correct(), pointLinear< Type >::correction(), removePoints::countPointUsage(), cyclicPolyPatch::coupledPoints(), AABBTree< Type >::createBoxes(), Foam::createTree(), multiSolidBodyMotionSolver::curPoints(), solidBodyMotionSolver::curPoints(), displacementMeshMoverMotionSolver::curPoints(), elasticityMotionSolver::curPoints(), volumetricBSplinesMotionSolver::curPoints(), rigidBodyMeshMotion::curPoints(), sixDoFRigidBodyMotionSolver::curPoints(), triSurfaceTools::curvatures(), geomCellLooper::cut(), extendedEdgeMesh::cut(), hexCellLooper::cut(), debugWriter::debugWriter(), multiLevelDecomp::decompose(), hierarchGeomDecomp::decompose(), hierarchGeomDecomp::decompose(), randomDecomp::decompose(), simpleGeomDecomp::decompose(), randomDecomp::decompose(), simpleGeomDecomp::decompose(), manualDecomp::decompose(), decompositionMethod::decompose(), simpleGeomDecomp::decompose(), metisLikeDecomp::decompose(), simpleGeomDecomp::decompose(), triSurfaceTools::delaunay2D(), distributedTriSurfaceMesh::distribute(), extendedEdgeMesh::edgeTree(), extendedEdgeMesh::edgeTreesByType(), ensightWriter::ensightWriter(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), ABAQUSCore::faceDecomposition(), NASCore::faceDecomposition(), FaceInteraction< CloudType >::FaceInteraction(), blockDescriptor::facePoints(), primitiveMeshTools::facePyramidVolume(), faceTriangulation::faceTriangulation(), faceTriangulation::faceTriangulation(), parseDriver::field_pointField(), FilterField::FilterField(), cellVolumeWeightMethod::findInitialSeeds(), treeDataPrimitivePatch< PatchType >::findIntersection(), treeDataFace::findNearest(), treeDataPrimitivePatch< PatchType >::findNearest(), sampledSet::findNearFace(), searchableExtrudedCircle::findParametricNearest(), extendedEdgeMesh::flipNormals(), triFace::FOAM_DEPRECATED_FOR(), foamWriter::foamWriter(), for(), forAll(), faceCorrectedSnGrad< Type >::fullGradCorrection(), coordSet::gatherSort(), coupledPolyPatch::getAnchorPoints(), boundaryMesh::getNearest(), searchableExtrudedCircle::getNormal(), boundaryMesh::getNPoints(), boundaryMesh::getNTris(), coupledPolyPatch::getRotation(), treeDataFace::getVolumeType(), treeDataPrimitivePatch< PatchType >::getVolumeType(), searchableBox::getVolumeType(), searchableCone::getVolumeType(), searchableCylinder::getVolumeType(), searchableRotatedBox::getVolumeType(), searchableSphere::getVolumeType(), triSurfaceMesh::getVolumeType(), pyramid< Point, PointRef, PolygonRef >::height(), if(), if(), if(), triFace::inertia(), movingConeTopoFvMesh::init(), vtuAdaptor::internal(), sampledMeshedSurfaceNormal::interpolate(), patchTransformedInterpolation::interpolate(), volPointInterpolation::interpolateDimensionedInternalField(), isoSurfaceCell::interpolateTemplate(), isoSurfacePoint::interpolateTemplate(), triangleFuncs::intersectBb(), triFace::intersection(), triFace::intersection(), triSurfaceLoader::load(), cellModel::mag(), cellShape::mag(), triFace::mag(), pyramid< Point, PointRef, PolygonRef >::mag(), voxelMeshSearch::makeMesh(), edgeCollapser::markMergeEdges(), edgeCollapser::markSmallEdges(), Foam::mergePoints(), Foam::mergePoints(), extendedEdgeMesh::mergePointsAndSort(), Patch::mesh(), layeredEngineMesh::move(), cyclicACMIFvPatch::movePoints(), pointMesh::movePoints(), rigidBodyMeshMotionSolver::movePoints(), nastranWriter::nastranWriter(), surfaceFeatures::nearestFeatEdge(), triFace::nearestPoint(), triFace::nearestPointClassify(), block::New(), blockEdge::New(), fvMeshTools::newMesh(), surfMesh::nPoints(), face::nTrianglesQuads(), surfaceWriter::open(), surfaceWriter::open(), findNearestMaskedOp< PatchType >::operator()(), treeDataFace::overlaps(), treeDataPrimitivePatch< PatchType >::overlaps(), treeDataFace::overlaps(), treeDataPrimitivePatch< PatchType >::overlaps(), pairPatchAgglomeration::pairPatchAgglomeration(), pairPatchAgglomeration::pairPatchAgglomeration(), lineWriter::piece(), surfaceWriter::piece(), coordSetWriter::piece(), pointHistory::pointHistory(), polyMesh::pointInCell(), searchableSurfaceCollection::points(), extendedEdgeMesh::pointTree(), Foam::polyMeshZipUpCells(), porosityModel::porosityModel(), BSpline::position(), CatmullRomSpline::position(), BSpline::position(), CatmullRomSpline::position(), projectCurveEdge::position(), projectEdge::position(), blockEdge::position(), FaceInteraction< CloudType >::postFace(), sampledCuttingPlane::print(), sampledFaceZone::print(), sampledMeshedSurface::print(), sampledPatch::print(), sampledPatchInternalField::print(), sampledPlane::print(), Foam::printTriangle(), projectFace::project(), PrimitivePatch< FaceList, PointField >::projectFaceCentres(), PrimitivePatch< FaceList, PointField >::projectPoints(), proxyWriter::proxyWriter(), rawWriter::rawWriter(), face::ray(), triFace::ray(), NASedgeFormat::read(), STARCDsurfaceFormat< Face >::read(), STARCDedgeFormat::read(), ensightSurfaceReader::readGeometry(), boundaryDataSurfaceReader::readPoints(), STARCDCore::readPoints(), FIRECore::readPoints(), refinementFeatures::regionEdgeTrees(), randomRenumber::renumber(), renumberMethod::renumber(), randomRenumber::renumber(), randomRenumber::renumber(), randomRenumber::renumber(), renumberMethod::renumber(), manualRenumber::renumber(), structuredRenumber::renumber(), FilterField::reset(), cyclicACMIPolyPatch::resetAMI(), cyclicAMIPolyPatch::resetAMI(), cyclicACMIPolyPatch::resetAMI(), polyMesh::resetPrimitives(), sampledDistanceSurface::sampleOnPoints(), sampledIsoSurface::sampleOnPoints(), sampledCuttingPlane::sampleOnPoints(), sampledCuttingSurface::sampleOnPoints(), sampledFaceZone::sampleOnPoints(), sampledPatch::sampleOnPoints(), sampledPatchInternalField::sampleOnPoints(), sampledPlane::sampleOnPoints(), sampledThresholdCellFaces::sampleOnPoints(), coordSet::scalarCoord(), extendedEdgeMesh::select(), elasticityMotionSolver::setBoundaryConditions(), laplacianMotionSolver::setBoundaryConditions(), refinementSurfaces::setCurvatureMinLevelFields(), extendedEdgeMesh::setFromStatus(), refinementSurfaces::setMinLevelFields(), displacementMethodelasticityMotionSolver::setMotionField(), patchInjectionBase::setPositionAndCell(), meshCutter::setRefinement(), faceCollapser::setRefinement(), refinementIterator::setRefinement(), propellerInfo::setSampleDiskGeometry(), surfaceWriter::setSurface(), surfaceWriter::setSurface(), face::sign(), triFace::sign(), cellDistFuncs::smallestDist(), displacementLayeredMotionMotionSolver::solve(), velocityDisplacementMotionSolver::solve(), displacementMeshMoverMotionSolver::solve(), elasticityMotionSolver::solve(), starcdWriter::starcdWriter(), surfaceFeatures::surfaceFeatures(), triSurfaceTools::surfaceNormal(), triSurfaceTools::surfaceSide(), MeshedSurface< Face >::swapPoints(), wallBoundedParticle::trackToEdge(), polySurface::transfer(), sixDoFRigidBodyMotion::transform(), rigidBodyMotion::transformPoints(), rigidBodyMotion::transformPoints(), rigidBodyMotion::transformPoints(), triSurfaceSearch::tree(), triSurfaceRegionSearch::treeByRegion(), triFace::tri(), face::triangles(), face::triangles(), face::trianglesQuads(), faceAreaIntersect::triangulate(), boundaryMesh::triangulate(), triSurfaceTools::triangulate(), triSurfaceTools::triangulate(), MeshedSurface< Face >::triangulate(), triSurfaceTools::triangulateFaceCentre(), boundaryMesh::triangulateLocal(), advancingFrontAMI::triangulatePatch(), extendedEdgeMesh::trim(), ensightFaces::uniqueMeshPoints(), triFace::unitNormal(), dynamicMotionSolverListFvMesh::update(), dynamicMultiMotionSolverFvMesh::update(), voxelMeshSearch::update(), sampledFaceZone::update(), sampledPatch::update(), dynamicMotionSolverTopoFvMesh::update(), mixerFvMesh::update(), movingConeTopoFvMesh::update(), cellMotionFvPatchField< Type >::updateCoeffs(), waveDisplacementPointPatchVectorField::updateCoeffs(), waveMakerPointPatchVectorField::updateCoeffs(), shapeOptimisation::updateDesignVariables(), componentDisplacementMotionSolver::updateMesh(), points0MotionSolver::updateMesh(), patchInjectionBase::updateMesh(), coordSet::vectorCoord(), triSurfaceTools::vertexNormals(), triSurfaceTools::vertexNormalWeight(), triSurfaceTools::vertexTriads(), vtkWriter::vtkWriter(), surfaceFieldValue::write(), vtkWriter::write(), foamWriter::write(), rawWriter::write(), OBJstream::write(), OBJstream::write(), triSurface::write(), surfMesh::write(), MeshedSurfaceProxy< Face >::write(), OBJstream::write(), OBJstream::write(), OBJstream::write(), ensightFaces::write(), surfaceFieldValue::writeAll(), OBJstream::writeFace(), lumpedPointMovement::writeForcesAndMomentsVTP(), polyWriter::writeLineGeometry(), Foam::writeMeasured_ascii(), Foam::writeMeasured_binary(), faceAreaWeightAMI2D::writeNoMatch(), coupledPolyPatch::writeOBJ(), extendedEdgeMesh::writeObj(), coupledPolyPatch::writeOBJ(), Foam::meshTools::writeOBJ(), Foam::meshTools::writeOBJ(), Foam::meshTools::writeOBJ(), Foam::writeObjEdges(), ABAQUSCore::writePoints(), STARCDCore::writePoints(), polyWriter::writePolyGeometry(), edgeMesh::writeStats(), extendedEdgeMesh::writeStats(), MeshedSurface< Face >::writeStats(), triSurface::writeStats(), rawWriter::writeTemplate(), streamLineBase::writeToFile(), boundaryMesh::writeTriSurface(), and x3dWriter::x3dWriter().
nPoints
label nPoints = points.size()
Definition at line 2 of file gmvOutputHeader.H.
Referenced by fvMeshAdder::add(), polyMeshAdder::add(), snappyLayerDriver::addLayers(), snappyLayerDriver::addLayersSinglePass(), face::areaNormal(), face::average(), Foam::vtk::legacy::beginPointData(), fileWriter::beginPoints(), Foam::vtk::legacy::beginPoints(), PatchTools::calcBounds(), cutCell::calcGeomDataCutFace(), primitiveMesh::calcPointOrder(), cutFace::calcSubFaceCentreAndArea(), dynamicRefineFvMesh::cellToPoint(), face::centre(), primitiveMesh::checkFaceVertices(), Foam::checkFireEdges(), ABAQUSCore::readHelper::compact_nodes(), NURBS3DVolume::coordinates(), polySurface::copySurface(), surfMesh::copySurface(), polySurface::copySurface(), surfMesh::copySurface(), polySurface::copySurface(), surfMesh::copySurface(), pointPatchDist::correct(), inversePointDistanceDiffusivity::correct(), cyclicPolyPatch::coupledPoints(), STARCDMeshReader::cullPoints(), displacementInterpolationMotionSolver::curPoints(), cutFaceAdvect::cutPoints(), cutFaceAdvect::cutPoints(), faMeshDecomposition::decomposeMesh(), triSurfaceMesh::edgeTree(), FilterField::evaluate(), PrimitivePatch< FaceList, PointField >::findEdge(), Foam::ensightOutput::Detail::getPolysFacePoints(), globalMeshData::globalPointNumbering(), dynamicMultiMotionSolverFvMesh::init(), processorFaPatch::initUpdateMesh(), processorPolyPatch::initUpdateMesh(), PDRblock::innerMesh(), isoSurfacePoint::interpolate(), patchTransformedInterpolation::interpolate(), PointEdgeWave< Type, TrackingData >::iterate(), highAspectRatioFvGeometryScheme::makeAverageCentres(), stabilisedFvGeometryScheme::makeFaceCentresAndAreas(), primitiveMeshTools::makeFaceCentresAndAreas(), deltaBoundary::makeFaceCentresAndAreas_d(), deltaBoundary::makeFaceCentresAndAreas_d(), processorFaPatch::makeNonGlobalPatchPoints(), mapPolyMesh::mapPolyMesh(), dynamicRefineFvMesh::maxCellField(), extendedEdgeMesh::mergePointsAndSort(), ensightCells::meshPointMap(), displacementMotionSolverMeshMover::move(), face::nearestPointClassify(), vtuSizing::operator==(), faMesh::pointAreaNormals(), searchableSurfaceCollection::points(), powerLawLopesdaCostaZone::powerLawLopesdaCostaZone(), faMeshTools::printMeshChecks(), PrimitivePatch< FaceList, PointField >::projectPoints(), face::ray(), GTSsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), ensightSurfaceReader::readGeometry(), STARCDMeshReader::readPoints(), lumpedPointController::remapPointLabels(), primitiveMesh::reset(), primitiveMesh::reset(), polyMesh::resetPrimitives(), Foam::rewritePatchLabels(), dynamicRefineFvMesh::selectUnrefinePoints(), polyTopoChange::setCapacity(), boundaryMesh::setFeatureEdges(), meshCutAndRemove::setRefinement(), edgeCollapser::setRefinement(), rigidBodyMeshMotion::solve(), rigidBodyMeshMotionSolver::solve(), sixDoFRigidBodyMotionSolver::solve(), face::sweptVol(), cutFaceAdvect::timeIntegratedFaceFlux(), cutFaceAdvect::timeIntegratedFaceFlux(), triSurfaceSearch::tree(), triSurfaceRegionSearch::treeByRegion(), ensightFaces::uniqueMeshPoints(), interfaceTrackingFvMesh::update(), primitiveMeshTools::updateFaceCentresAndAreas(), processorFaPatch::updateMesh(), processorPolyPatch::updateMesh(), patchWriter::write(), patchWriter::write(), ensightCells::write(), ensightFaces::write(), Foam::ensightOutput::Detail::writeCoordinates(), lumpedPointMovement::writeForcesAndMomentsVTP(), distributedTriSurfaceMesh::writeStats(), csvWriter::writeTemplate(), rawWriter::writeTemplate(), interfaceTrackingFvMesh::writeVTKControlPoints(), and lumpedPointState::writeVTP().
cells
const cellShapeList& cells = mesh.cellShapes()
Definition at line 3 of file gmvOutputHeader.H.
Referenced by MRFZone::addCoriolis(), MRFZone::addCoriolis(), MRFZone::addCoriolis(), polyMeshTetDecomposition::adjustTetBasePtIs(), targetCoeffTrim::calcCoeffs(), maxDeltaxyz::calcDelta(), DarcyForchheimer::calcTransformModelData(), primitiveMesh::cellCells(), primitiveMesh::cellEdges(), primitiveMesh::cellPoints(), FaceCellWave< Type, TrackingData >::cellToFace(), polyMeshGeometry::checkCellDeterminant(), primitiveMeshGeometry::checkCellDeterminant(), primitiveMesh::checkCellsZipUp(), primitiveMesh::checkClosedCells(), primitiveMesh::checkConcaveCells(), primitiveMesh::checkFacePyramids(), primitiveMesh::checkUpperTriangular(), Zuber::CHF(), HuaXu::CHFSubCool(), Tatsumoto::CHFSubCool(), ATCModel::computeLimiter(), adjointBoundaryCondition< Type >::computePatchGrad(), edgeCollapser::consistentCollapse(), outletStabilised< Type >::correction(), heThermo< BasicThermo, MixtureType >::Cp(), heThermo< BasicPsiThermo, MixtureType >::Cpv(), hexCellLooper::cut(), effectivenessTable::energyDensity(), referenceTemperature::energyDensity(), dynamicRefineFvMesh::extendMarkedCells(), Foam::vtk::Tools::Faces(), surfaceSets::getHangingCells(), cellCellStencil::globalCellCells(), meshRefinement::growSet(), heheuPsiThermo< BasicPsiThermo, MixtureType >::heu(), BreenWestwater::htcFilmBoil(), Bromley::htcFilmBoil(), Foam::vtk::Tools::identityVertices(), if(), KinematicCloud< CloudType >::info(), MPPICCloud< CloudType >::info(), dynamicMultiMotionSolverFvMesh::init(), dynamicRefineFvMesh::init(), vtuAdaptor::internal(), patchTransformedInterpolation::interpolate(), MRFZone::makeAbsolute(), MRFZone::makeRelative(), waWallFunctionFvPatchScalarField::manipulateMatrix(), dynamicRefineFvMesh::mapNewInternalFaces(), meshToMeshMethod::maskCells(), Jeschar::MHF(), regionModel1D::moveMesh(), sampledSet::pointInCell(), primitiveMesh::pointInCell(), polyMesh::pointInCell(), porosityModel::porosityModel(), Kutadeladze::qNucleate(), polyMesh::readUpdate(), heThermo< BasicThermo, MixtureType >::rhoEoS(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::setCdSigma(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::setPorosityCoefficient(), edgeCollapser::setRefinement(), refinementIterator::setRefinement(), fvMatrix< Type >::setValuesFromList(), thermoSingleLayer::Sh(), ATCModel::smoothFieldBasedOnCells(), thermalBaffle::solveEnergy(), thermoSingleLayer::Srho(), thermoSingleLayer::Srho(), heThermo< BasicThermo, MixtureType >::THE(), primitiveMeshTools::updateCellCentresAndVols(), edgeVertex::updateLabels(), reactingOneDim::updatePhiGas(), reactingOneDim::updateqr(), cuttingSurfaceBase::walkCellCuts(), outletStabilised< Type >::weights(), and Foam::meshTools::writeOBJ().