OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToGMV/gmvOutputLagrangian.H File Reference
gmvOutputLagrangian.H File Reference
Functions
gmvFile<< "tracers "<< particles.size()<< nl;for(const passiveParticle &p :particles){ gmvFile<< p.position().x()<< ' ';}gmvFile<< nl;for(const passiveParticle &p :particles){ gmvFile<< p.position().y()<< ' ';}gmvFile<< nl;for(const passiveParticle &p :particles){ gmvFile<< p.position().z()<< ' ';}gmvFile<< nl;for(const word &name :lagrangianScalarNames){ IOField< scalar > fld (IOobject(name, runTime.timeName(), cloud::prefix, mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
if (fld.size())
for (const word &name :lagrangianVectorNames)
Function Documentation
fld()
gmvFile<< "tracers "<< particles.size()<< nl;for(const passiveParticle &p :particles){ gmvFile<< p.position().x()<< ' ';}gmvFile<< nl;for(const passiveParticle &p :particles){ gmvFile<< p.position().y()<< ' ';}gmvFile<< nl;for(const passiveParticle &p :particles){ gmvFile<< p.position().z()<< ' ';}gmvFile<< nl;for(const word &name :lagrangianScalarNames){ IOField< scalar > fld (IOobject(name, runTime.timeName(), cloud::prefix, mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
Referenced by for(), and if().
if()
if (fld. size())
Definition at line 35 of file gmvOutputLagrangian.H.
References fld().
for()
for (const word &name :lagrangianVectorNames)
Definition at line 49 of file gmvOutputLagrangian.H.
References fld(), forAll, mesh, n, and runTime.