OpenFOAM: applications/solvers/heatTransfer/buoyantBoussinesqPimpleFoam/TEqn.H File Reference
TEqn.H File Reference
Functions
alphat correctBoundaryConditions ()
volScalarField alphaEff ("alphaEff", turbulence->nu()/Pr+alphat)
fvScalarMatrix TEqn (fvm::ddt(T)+fvm::div(phi, T) - fvm::laplacian(alphaEff, T)==radiation->ST(rhoCpRef, T)+fvOptions(T))
TEqn relax ()
fvOptions constrain (TEqn)
TEqn solve ()
radiation correct ()
fvOptions correct (T)
Variables
rhok = 1.0 - beta*(T - TRef)
Function Documentation
correctBoundaryConditions()
alphat correctBoundaryConditions ()
alphaEff()
volScalarField alphaEff ("alphaEff" , turbulence->nu()/Pr+ alphat)
Referenced by heThermo< BasicThermo, MixtureType >::alphaEff(), heThermo< BasicThermo, MixtureType >::alphahe(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), rotorDiskSource::calculate(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), heatTransferCoeffModel::q(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
TEqn()
fvScalarMatrix TEqn (fvm::ddt(T)+fvm::div(phi, T) - fvm::laplacian(alphaEff, T) = =radiation->ST(rhoCpRef, T)+fvOptions(T))
Referenced by displacementComponentLaplacianFvMotionSolver::solve(), velocityComponentLaplacianFvMotionSolver::solve(), displacementLaplacianFvMotionSolver::solve(), displacementSBRStressFvMotionSolver::solve(), solidBodyDisplacementLaplacianFvMotionSolver::solve(), and thermalShell::solveEnergy().
relax()
TEqn relax ()
constrain()
fvOptions constrain (TEqn)
solve()
TEqn solve ()
correct() [1/2]
radiation correct ()
correct() [2/2]
fvOptions correct (T)
Variable Documentation
rhok
rhok = 1.0 - beta*(T - TRef)
Definition at line 27 of file TEqn.H.
Referenced by if(), if(), and if().