OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/fluid/YEqn.H File Reference
YEqn.H File Reference
Functions
tmp< fv::convectionScheme< scalar > > mvConvection (nullptr)
if (Y.size())
volScalarField Yt (IOobject("Yt", runTime.timeName(), mesh), mesh, dimensionedScalar("Yt", dimless, 0))
forAll (Y, i)
Variables
Qdot = reaction.Qdot()
Function Documentation
mvConvection()
tmp< fv::convectionScheme< scalar > > mvConvection (nullptr)
if()
if (Y. size())
Definition at line 3 of file YEqn.H.
References fields, mesh, mvConvection(), and phi.
Yt()
volScalarField Yt (IOobject("Yt", runTime.timeName(), mesh) , mesh , dimensionedScalar("Yt", dimless, 0))
forAll()
forAll (Y , i)
Definition at line 27 of file YEqn.H.
References composition, fvOptions, inertIndex, mesh, mvConvection(), phi, reaction, rho, turbulence, Y, and Yt().
Variable Documentation
Qdot
Qdot = reaction.Qdot()
Definition at line 19 of file YEqn.H.