OpenFOAM: applications/solvers/heatTransfer/buoyantPimpleFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
const volScalarField psip0 (psi *p)
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phig (-rhorAUf *ghf *fvc::snGrad(rho) *mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA",(fvc::flux(rho *HbyA)+MRF.zeroFilter(rhorAUf *fvc::ddtCorr(rho, U, phi)))+phig)
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p_rgh, rho, U, phiHbyA, rhorAUf, MRF)
fvScalarMatrix p_rghDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p_rgh))+fvc::div(phiHbyA)==fvOptions(psi, p_rgh, rho.name()))
while (pimple.correctNonOrthogonal())
pressureControl limit (p)
if (p_rgh.needReference())
if (thermo.dpdt())
Variables
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
bool compressible = (compressibility.value() > SMALL)
rho = thermo.rho()
p = p_rgh + rho*gh
else
Function Documentation
psip0()
const volScalarField psip0 (psi * p)
rAU()
volScalarField rAU (1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
phig()
surfaceScalarField phig (-rhorAUf *ghf * fvc::snGradrho) *mesh.magSf()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::flux(rho *HbyA)+MRF.zeroFilter(rhorAUf *fvc::ddtCorr(rho, U, phi)))+ phig)
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
constrainPressure()
constrainPressure (p_rgh , rho , U , phiHbyA , rhorAUf , MRF)
p_rghDDtEqn()
fvScalarMatrix p_rghDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p_rgh))+fvc::div(phiHbyA) = =fvOptions(psi, p_rgh, rho.name()))
while()
while (pimple. correctNonOrthogonal())
Definition at line 41 of file pEqn.H.
References compressible, fvOptions, HbyA, mesh, p_rgh, p_rghDDtEqn(), phi, phig(), phiHbyA, pimple, pRefCell, pRefValue, rAU, rhorAUf(), and U.
limit()
pressureControl limit (p)
if() [1/2]
if (p_rgh. needReference())
Definition at line 78 of file pEqn.H.
References compressibility, compressible, gh, initialMass, p, p_rgh, pRefCell, pRefValue, psi, psip0(), rho, rhoMax, and rhoMin.
if() [2/2]
if (thermo. dpdt())
Definition at line 112 of file pEqn.H.
References dpdt, mesh, p, rho, and U.
Variable Documentation
compressibility
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
Definition at line 1 of file pEqn.H.
compressible
bool compressible = (compressibility.value() > SMALL)
Definition at line 2 of file pEqn.H.
rho
rho = thermo.rho()
Definition at line 4 of file pEqn.H.
p
p = p_rgh + rho*gh
Definition at line 74 of file pEqn.H.
else
else
Initial value:
{
    thermo.correctRho(psi*p - psip0, rhoMin, rhoMax)
Definition at line 99 of file pEqn.H.