OpenFOAM: applications/solvers/heatTransfer/buoyantPimpleFoam/overBuoyantPimpleDyMFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
const volScalarField psip0 (psi *p)
volScalarField rAU (1.0/UEqn.A())
mesh interpolate (rAU)
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phig (-rhorAUf *ghf *fvc::snGrad(rho) *mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(rho *HbyA)+phig)
if (adjustFringe)
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p_rgh, rho, U, phiHbyA, rhorAUf, MRF)
fvScalarMatrix p_rghDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p_rgh))+fvc::div(phiHbyA)==fvOptions(psi, p_rgh, rho.name()))
while (pimple.correctNonOrthogonal())
if (p_rgh.needReference())
if (thermo.dpdt())
Variables
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
bool compressible = (compressibility.value() > SMALL)
rho = thermo.rho()
p = p_rgh + rho*gh
else
Function Documentation
psip0()
const volScalarField psip0 (psi * p)
rAU()
volScalarField rAU (1.0/UEqn. A())
interpolate()
mesh interpolate (rAU)
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
phig()
surfaceScalarField phig (-rhorAUf *ghf * fvc::snGradrho) *mesh.magSf()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(rho *HbyA)+ phig)
if() [1/3]
if (adjustFringe)
Definition at line 24 of file pEqn.H.
References phiHbyA, rho, and U.
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
constrainPressure()
constrainPressure (p_rgh , rho , U , phiHbyA , rhorAUf , MRF)
p_rghDDtEqn()
fvScalarMatrix p_rghDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p_rgh))+fvc::div(phiHbyA) = =fvOptions(psi, p_rgh, rho.name()))
while()
while (pimple. correctNonOrthogonal())
Definition at line 45 of file pEqn.H.
References fvOptions, HbyA, mesh, p_rgh, p_rghDDtEqn(), phi, phig(), phiHbyA, pimple, rAU, rhorAUf(), and U.
if() [2/3]
if (p_rgh. needReference())
Definition at line 81 of file pEqn.H.
References compressibility, compressible, gh, initialMass, p, p_rgh, pRefCell, pRefValue, psi, psip0(), and rho.
if() [3/3]
if (thermo. dpdt())
Definition at line 112 of file pEqn.H.
References dpdt, mesh, p, rho, and U.
Variable Documentation
compressibility
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
Definition at line 1 of file pEqn.H.
Referenced by if(), and if().
compressible
bool compressible = (compressibility.value() > SMALL)
Definition at line 2 of file pEqn.H.
Referenced by turbulenceFields::execute(), for(), if(), if(), and while().
rho
rho = thermo.rho()
Definition at line 4 of file pEqn.H.
p
p = p_rgh + rho*gh
Definition at line 76 of file pEqn.H.
else
else
Initial value:
{
    thermo.correctRho(psi*p - psip0)
Definition at line 101 of file pEqn.H.