OpenFOAM: applications/solvers/heatTransfer/buoyantBoussinesqPimpleFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phig (-rAUf *ghf *fvc::snGrad(rhok) *mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA)+MRF.zeroFilter(rAUf *fvc::ddtCorr(U, phi))+phig)
MRF makeRelative (phiHbyA)
constrainPressure (p_rgh, U, phiHbyA, rAUf, MRF)
while (pimple.correctNonOrthogonal())
if (p_rgh.needReference())
Variables
p = p_rgh + rhok*gh
Function Documentation
rAUf()
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
Referenced by Foam::CorrectPhi(), Foam::CorrectPhi(), for(), setFluxRequired(), while(), while(), and while().
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
phig()
surfaceScalarField phig (-rAUf *ghf * fvc::snGradrhok) *mesh.magSf()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA)+MRF.zeroFilter(rAUf *fvc::ddtCorr(U, phi))+ phig)
makeRelative()
MRF makeRelative (phiHbyA)
constrainPressure()
constrainPressure (p_rgh , U , phiHbyA , rAUf , MRF)
while()
while (pimple. correctNonOrthogonal())
Definition at line 21 of file pEqn.H.
References fvOptions, HbyA, mesh, p_rgh, phi, phig(), phiHbyA, pimple, pRefCell, rAU, rAUf(), U, and Uf.
if()
if (p_rgh. needReference())
Definition at line 58 of file pEqn.H.
References gh, p, p_rgh, pRefCell, pRefValue, and rhok.
Variable Documentation
p
p = p_rgh + rhok*gh
Definition at line 56 of file pEqn.H.