OpenFOAM: src/thermophysicalModels/specie/thermo/thermo/HtoEthermo.H File Reference
HtoEthermo.H File Reference
Functions
scalar Cv (const scalar p, const scalar T) const
scalar Es (const scalar p, const scalar T) const
scalar Ea (const scalar p, const scalar T) const
Function Documentation
Cv()
scalar Cv (const scalar p, const scalar T) const inline
Definition at line 1 of file HtoEthermo.H.
References Cp, cp, p, and T.
Es()
scalar Es (const scalar p, const scalar T) const inline
Definition at line 16 of file HtoEthermo.H.
References Hs(), p, rho, and T.
Referenced by eConstThermo< EquationOfState >::Ea(), thermo< Thermo, Type >::es(), and Hs().
Ea()
scalar Ea (const scalar p, const scalar T) const inline
Definition at line 31 of file HtoEthermo.H.
References Ha(), p, rho, and T.
Referenced by thermo< Thermo, Type >::A(), thermo< Thermo, Type >::ea(), Foam::Ek(), pairPotential::energyDerivative(), Ha(), and turbGen::U().