OpenFOAM: applications/solvers/incompressible/pimpleFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA))
if (pimple.ddtCorr())
MRF makeRelative (phiHbyA)
if (p.needReference())
tmp< volScalarField > rAtU (rAU)
if (pimple.nCorrPISO()<=1)
constrainPressure (p, U, phiHbyA, rAtU(), MRF)
while (pimple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
Variables
U = HbyA - rAtU*fvc::grad(p)
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA))
if() [1/3]
if (pimple. ddtCorr())
Definition at line 5 of file pEqn.H.
References MRF, phi, phiHbyA, rAU, U, and Uf.
makeRelative()
MRF makeRelative (phiHbyA)
if() [2/3]
if (p. needReference())
Definition at line 13 of file pEqn.H.
References adjustPhi(), p, phiHbyA, and U.
rAtU()
tmp< volScalarField > rAtU (rAU)
Referenced by if(), while(), and while().
if() [3/3]
if (pimple.nCorrPISO()<= 1)
Definition at line 30 of file pEqn.H.
References tUEqn().
constrainPressure()
constrainPressure (p , U , phiHbyA , rAtU() , MRF)
while()
while (pimple. correctNonOrthogonal())
Definition at line 39 of file pEqn.H.
References mesh, p, phi, phiHbyA, pimple, pRefCell, pRefValue, and rAtU().
relax()
p relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
Variable Documentation
U
U = HbyA - rAtU*fvc::grad(p)
Definition at line 61 of file pEqn.H.