OpenFOAM: applications/solvers/incompressible/simpleFoam/SRFSimpleFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volVectorField HbyA ("HbyA", Urel)
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA))
adjustPhi (phiHbyA, Urel, p)
tmp< volScalarField > rAtUrel (rAUrel)
if (simple.consistent())
tUrelEqn clear ()
constrainPressure (p, Urel, phiHbyA, rAtUrel())
while (simple.correctNonOrthogonal())
p relax ()
Urel correctBoundaryConditions ()
fvOptions correct (Urel)
Variables
HbyA = rAUrel*UrelEqn.H()
Urel = HbyA - rAtUrel()*fvc::grad(p)
Function Documentation
HbyA()
volVectorField HbyA ("HbyA" , Urel)
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA))
adjustPhi()
adjustPhi (phiHbyA , Urel , p)
rAtUrel()
tmp< volScalarField > rAtUrel (rAUrel)
if()
if (simple. consistent())
Definition at line 11 of file pEqn.H.
References HbyA, mesh, p, phiHbyA, rAtUrel(), rAUrel(), and UrelEqn.
clear()
tUrelEqn clear ()
constrainPressure()
constrainPressure (p , Urel , phiHbyA , rAtUrel())
while()
while (simple. correctNonOrthogonal())
Definition at line 25 of file pEqn.H.
References p, phi, phiHbyA, pRefCell, pRefValue, rAtUrel(), and simple.
relax()
p relax ()
correctBoundaryConditions()
Urel correctBoundaryConditions ()
correct()
fvOptions correct (Urel)
Variable Documentation
HbyA
HbyA = rAUrel*UrelEqn.H()
Definition at line 4 of file pEqn.H.
Urel
Urel = HbyA - rAtUrel()*fvc::grad(p)
Definition at line 48 of file pEqn.H.