OpenFOAM: applications/solvers/incompressible/pimpleFoam/SRFPimpleFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAUrel (1.0/UrelEqn.A())
volVectorField HbyA ("HbyA", Urel)
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA)+fvc::interpolate(rAUrel) *fvc::ddtCorr(Urel, phi))
adjustPhi (phiHbyA, Urel, p)
tmp< volScalarField > rAtUrel (rAUrel)
if (pimple.consistent())
if (pimple.nCorrPISO()<=1)
constrainPressure (p, Urel, phiHbyA, rAtUrel())
while (pimple.correctNonOrthogonal())
p relax ()
Urel correctBoundaryConditions ()
fvOptions correct (Urel)
Variables
HbyA = rAUrel*UrelEqn.H()
Urel = HbyA - rAtUrel()*fvc::grad(p)
Function Documentation
rAUrel()
volScalarField rAUrel (1.0/UrelEqn. A())
Referenced by if(), and if().
HbyA()
volVectorField HbyA ("HbyA" , Urel)
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA)+fvc::interpolate(rAUrel) *fvc::ddtCorr(Urel, phi))
adjustPhi()
adjustPhi (phiHbyA , Urel , p)
rAtUrel()
tmp< volScalarField > rAtUrel (rAUrel)
Referenced by if(), if(), while(), and while().
if() [1/2]
if (pimple. consistent())
Definition at line 16 of file pEqn.H.
References HbyA, mesh, p, phiHbyA, rAtUrel(), rAUrel(), and UrelEqn.
if() [2/2]
if (pimple.nCorrPISO()<= 1)
Definition at line 24 of file pEqn.H.
References tUrelEqn().
constrainPressure()
constrainPressure (p , Urel , phiHbyA , rAtUrel())
while()
while (pimple. correctNonOrthogonal())
Definition at line 33 of file pEqn.H.
References mesh, p, phi, phiHbyA, pimple, pRefCell, pRefValue, and rAtUrel().
relax()
p relax ()
correctBoundaryConditions()
Urel correctBoundaryConditions ()
correct()
fvOptions correct (Urel)
Variable Documentation
HbyA
HbyA = rAUrel*UrelEqn.H()
Definition at line 3 of file pEqn.H.
Urel
Urel = HbyA - rAtUrel()*fvc::grad(p)
Definition at line 56 of file pEqn.H.
Referenced by KinematicSurfaceFilm< CloudType >::absorbInteraction(), KinematicSurfaceFilm< CloudType >::bounceInteraction(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), KinematicSurfaceFilm< CloudType >::drySplashInteraction(), if(), SRFModel::New(), KinematicSurfaceFilm< CloudType >::splashInteraction(), ReitzKHRT< CloudType >::update(), BlobsSheetAtomization< CloudType >::update(), LISAAtomization< CloudType >::update(), and KinematicSurfaceFilm< CloudType >::wetSplashInteraction().