OpenFOAM: applications/solvers/incompressible/pimpleFoam/overPimpleDyMFoam/correctPhi.H File Reference
correctPhi.H File Reference
Functions
if (mesh.changing())
wordList pcorrTypes (p.boundaryField().size(), fvPatchFieldBase::zeroGradientType())
forAll (p.boundaryField(), patchi)
volScalarField pcorr (IOobject("pcorr", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar(p.dimensions(), Zero), pcorrTypes)
while (pimple.correctNonOrthogonal())
Variables
const cellCellStencilObject & overlap = Stencil::New(mesh)
const labelList & cellTypes = overlap.cellTypes()
const labelIOList & zoneIDs = overlap.zoneID()
Function Documentation
if()
if (mesh. changing())
Definition at line 1 of file correctPhi.H.
References forAll, mesh, phi, and U.
pcorrTypes()
wordList pcorrTypes (p. boundaryField).size(, fvPatchFieldBase::zeroGradientType())
forAll()
forAll (p. boundaryField(), patchi)
Definition at line 31 of file correctPhi.H.
References p, and pcorrTypes().
pcorr()
volScalarField pcorr (IOobject("pcorr", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedScalar(p.dimensions(), Zero) , pcorrTypes)
while()
while (pimple. correctNonOrthogonal())
Definition at line 61 of file correctPhi.H.
References cellTypes, forAll, mesh, pcorr(), phi, pimple, rAUf(), and zoneIDs.
Variable Documentation
overlap
const cellCellStencilObject& overlap = Stencil::New(mesh)
Definition at line 57 of file correctPhi.H.
Referenced by oversetFvMeshBase::addInterpolation(), oversetFvPatchField< Type >::adjustPsi(), oversetFvPatchField< Type >::fringeFlux(), oversetFvPatchField< Type >::initEvaluate(), cellCellStencil::interpolate(), cellCellStencil::interpolate(), cellCellStencil::interpolate(), oversetFvMeshBase::interpolateFields(), oversetFvPatchField< Type >::manipulateMatrix(), oversetFvMeshBase::normalisation(), Foam::oversetAdjustPhi(), cellSetOption::setCellSelection(), oversetFvMeshBase::solveOverset(), oversetFvPatchField< Type >::storeFringeCoefficients(), oversetFvMeshBase::updateAddressing(), and oversetFvMeshBase::writeObject().
cellTypes
const labelList& cellTypes = overlap.cellTypes()
Definition at line 58 of file correctPhi.H.
Referenced by while().
zoneIDs
const labelIOList& zoneIDs = overlap.zoneID()
Definition at line 59 of file correctPhi.H.
Referenced by preserveFaceZones::add(), refinementParameters::addCellZonesToMesh(), preserveFaceZones::apply(), objectiveIncompressible::checkCellZonesSize(), meshRefinement::createZoneBaffles(), FaceInteraction< CloudType >::FaceInteraction(), FacePostProcessing< CloudType >::FacePostProcessing(), meshRefinement::getZoneFaces(), meshRefinement::getZones(), dynamicMultiMotionSolverFvMesh::init(), meshRefinement::mergeZoneBaffles(), multiSolidBodyMotionSolver::multiSolidBodyMotionSolver(), binModel::read(), RemoveParcels< CloudType >::RemoveParcels(), cellSetOption::setCellSelection(), faceSetOption::setFaceSelection(), ZoneMesh< ZoneType, MeshType >::setGroup(), meshRefinement::subsetBaffles(), sampledFaceZone::update(), while(), zoneMotion::zoneMotion(), zoneToCell::zones(), zoneToFace::zones(), and zoneToPoint::zones().