OpenFOAM: applications/solvers/multiphase/interPhaseChangeFoam/alphaEqn.H File Reference
alphaEqn.H File Reference
Functions
word alpharScheme ("div(phirb,alpha)")
surfaceScalarField phir ("phir", phic *interface.nHatf())
const volScalarField vDotvmcAlphal (vDotvAlphal - vDotcAlphal)
if (MULESCorr)
volScalarField alpha10 ("alpha10", alpha1)
for (int aCorr=0;aCorr< nAlphaCorr;aCorr++)
Variables
Pair< tmp< volScalarField > > vDotAlphal
const volScalarField & vDotcAlphal = vDotAlphal[0]()
const volScalarField & vDotvAlphal = vDotAlphal[1]()
tmp< surfaceScalarField > talphaPhi
rhoPhi = talphaPhi()*(rho1 - rho2) + phi*rho2
alphaPhi10 = talphaPhi()
Function Documentation
alpharScheme()
word alpharScheme ("div(phirb,alpha)")
phir()
surfaceScalarField phir ("phir" , phic *interface. nHatf())
vDotvmcAlphal()
const volScalarField vDotvmcAlphal (vDotvAlphal - vDotcAlphal)
Referenced by for(), and if().
if()
if (MULESCorr)
Definition at line 15 of file alphaEqn.H.
References alpha1, divU, mesh, phi, talphaPhi, vDotcAlphal, and vDotvmcAlphal().
alpha10()
volScalarField alpha10 ("alpha10" , alpha1)
Referenced by for().
for()
for ()
Definition at line 45 of file alphaEqn.H.
References alpha1, alpha10(), alpha2, alpharScheme(), divU, MULESCorr(), phi, phir(), talphaPhi, vDotcAlphal, and vDotvmcAlphal().
Variable Documentation
vDotAlphal
Pair<tmp<volScalarField> > vDotAlphal
Initial value:
=
        mixture->vDotAlphal()
Definition at line 7 of file alphaEqn.H.
vDotcAlphal
const volScalarField& vDotcAlphal = vDotAlphal[0]()
Definition at line 9 of file alphaEqn.H.
Referenced by for(), and if().
vDotvAlphal
const volScalarField& vDotvAlphal = vDotAlphal[1]()
Definition at line 10 of file alphaEqn.H.
talphaPhi
tmp<surfaceScalarField> talphaPhi
Definition at line 13 of file alphaEqn.H.
Referenced by for(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), and if().
rhoPhi
rhoPhi = talphaPhi()*(rho1 - rho2) + phi*rho2
Definition at line 116 of file alphaEqn.H.
alphaPhi10
alphaPhi10 = talphaPhi()
Definition at line 119 of file alphaEqn.H.