OpenFOAM: applications/solvers/incompressible/boundaryFoam/interrogateWallPatches.H File Reference
interrogateWallPatches.H File Reference
Functions
label faceId (-1)
label patchId (-1)
label nWallFaces (0)
forAll (patches, patchi)
if (nWallFaces==0)
scalarField y (wallNormal &(mesh.C().primitiveField() - mesh.C().boundaryField()[patchId][faceId]))
Variables
vector wallNormal (Zero)
const fvPatchList & patches = mesh.boundary()
else
label cellId = patches[patchId].faceCells()[faceId]
Function Documentation
faceId()
label faceId (- 1)
Referenced by ensightFaces::classify(), Patch::faceNormals(), forAll(), Foam::ensightOutput::Detail::getPolysFacePoints(), heatExchangerModel::initialise(), fluxSummary::initialiseFaceZone(), fluxSummary::initialiseFaceZoneAndDirection(), fvMatrix< Type >::mapContributions(), FacePostProcessing< CloudType >::postFace(), FIREMeshReader::readSelections(), faMatrix< Type >::setReferences(), faMatrix< Type >::setReferences(), sampledFaceZone::update(), Foam::ensightOutput::writePolysPoints(), Foam::ensightOutput::writePolysPoints(), and Foam::ensightOutput::writeVolField().
patchId()
label patchId (- 1)
Referenced by patchMeshWriter::beginPiece(), ensightMesh::correct(), faBoundaryMesh::findPatchID(), polyBoundaryMesh::findPatchID(), for(), forAll(), if(), faBoundaryMesh::indices(), polyBoundaryMesh::indices(), processorFvPatchField< Type >::initInterfaceMatrixUpdate(), calculatedProcessorFvPatchField< Type >::initInterfaceMatrixUpdate(), processorFvPatchField< Type >::initInterfaceMatrixUpdate(), lduCalculatedProcessorField< Type >::initInterfaceMatrixUpdate(), triSurfaceLoader::load(), structuredRenumber::renumber(), sampledPatchInternalField::sampleOnPoints(), cyclicACMIFvPatchField< Type >::updateInterfaceMatrix(), cyclicAMIFvPatchField< Type >::updateInterfaceMatrix(), jumpCyclicFvPatchField< Type >::updateInterfaceMatrix(), jumpCyclicAMIFvPatchField< Type >::updateInterfaceMatrix(), cyclicFvPatchField< Type >::updateInterfaceMatrix(), processorFvPatchField< Type >::updateInterfaceMatrix(), cyclicACMIFvPatchField< Type >::updateInterfaceMatrix(), cyclicAMIFvPatchField< scalar >::updateInterfaceMatrix(), processorFvPatchField< Type >::updateInterfaceMatrix(), cyclicACMIGAMGInterfaceField::updateInterfaceMatrix(), cyclicAMIGAMGInterfaceField::updateInterfaceMatrix(), cyclicGAMGInterfaceField::updateInterfaceMatrix(), processorGAMGInterfaceField::updateInterfaceMatrix(), calculatedProcessorGAMGInterfaceField::updateInterfaceMatrix(), jumpCyclicFvPatchField< Type >::updateInterfaceMatrix(), jumpCyclicAMIFvPatchField< Type >::updateInterfaceMatrix(), vtkWrite::write(), patchWriter::write(), patchWriter::write(), patchWriter::write(), patchMeshWriter::writeNeighIDs(), patchMeshWriter::writePatchIDs(), Foam::ensightOutput::writePointField(), patchMeshWriter::writePoints(), patchMeshWriter::writePolys(), patchMeshWriter::writePolysLegacy(), and Foam::ensightOutput::writeVolField().
nWallFaces()
label nWallFaces (0)
Referenced by forAll().
forAll()
forAll (patches , patchi)
Definition at line 10 of file interrogateWallPatches.H.
References faceId(), FatalErrorInFunction, forAll, nWallFaces(), patches, patchId(), and wallNormal.
if()
if (nWallFaces = = 0)
Definition at line 55 of file interrogateWallPatches.H.
References FatalErrorInFunction.
y()
scalarField y (wallNormal & mesh.C().primitiveField() - mesh.C().boundaryField()[patchId][faceId])
Variable Documentation
wallNormal
vector wallNormal(Zero) (Zero)
Referenced by wallDistAddressing::correct(), and forAll().
patches
const fvPatchList& patches = mesh.boundary()
Definition at line 8 of file interrogateWallPatches.H.
Referenced by forAll().
else
else
Initial value:
{
    Info<< "Generating wall data for patch: " << patches[patchId].name()
        << endl
Definition at line 60 of file interrogateWallPatches.H.
cellId
label cellId = patches[patchId].faceCells()[faceId]
Definition at line 67 of file interrogateWallPatches.H.
Referenced by multiBandZoneAbsorptionEmission::aCont(), directionalPressureGradientExplicitSource::correct(), multiBandZoneAbsorptionEmission::eCont(), Foam::ensightOutput::Detail::getPolysFacePoints(), Foam::ensightOutput::Detail::getPolysNFaces(), Foam::ensightOutput::Detail::getPolysNPointsPerFace(), fvMatrix< Type >::mapContributions(), STARCDMeshReader::readBoundary(), reader::readField(), FIREMeshReader::readSelections(), fvMatrix< Type >::setReferences(), fvMatrix< Type >::setReferences(), thermalBaffle::solveEnergy(), internalWriter::write(), Foam::ensightOutput::writePolysPoints(), and Foam::ensightOutput::writePolysPoints().