OpenFOAM: applications/solvers/multiphase/interFoam/interMixingFoam/alphaEqn.H File Reference
alphaEqn.H File Reference
Functions
word alpharScheme ("div(phirb,alpha)")
surfaceScalarField phir (IOobject("phir", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mixture.cAlpha() *mag(phi/mesh.magSf()) *mixture.nHatf())
for (int gCorr=0;gCorr< nAlphaCorr;gCorr++)
Function Documentation
alpharScheme()
word alpharScheme ("div(phirb,alpha)")
phir()
surfaceScalarField phir (IOobject("phir", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mixture. cAlpha) *mag(phi/mesh.magSf()) *mixture.nHatf()
for()
for ()
Definition at line 18 of file alphaEqn.H.
References alpha1, alpha2, alphaPhi1, alphaPhi2, alpharScheme(), lambda(), LTS, mesh, phi, phir(), rho1, rho2, rhoPhi, runTime, and solve().