OpenFOAM: applications/solvers/lagrangian/reactingParcelFoam/createMeshesPostProcess.H File Reference
createMeshesPostProcess.H File Reference
Functions
IOobject io ("surfaceFilmProperties", mesh.time().constant(), mesh, IOobject::READ_IF_PRESENT, IOobject::NO_WRITE, IOobject::NO_REGISTER)
if (io.typeHeaderOk< IOdictionary >())
Variables
dictionary filmDict
Function Documentation
io()
IOobject io ("surfaceFilmProperties" , mesh. time).constant(, mesh , IOobject::READ_IF_PRESENT , IOobject::NO_WRITE , IOobject::NO_REGISTER)
Referenced by polyMeshAdder::add(), collatedFileOperation::appendObject(), PDRblock::blockMeshDict(), cellVolumeWeight::cellVolumeWeight(), IOobjectList::cfindObject(), surfaceFormatsCore::checkFile(), triSurface::checkFile(), surfaceFormatsCore::checkFile(), triSurface::checkFile(), objectRegistry::checkIn(), objectRegistry::checkIn(), objectRegistry::checkOut(), objectRegistry::checkOut(), IOobjectList::classesImpl(), refinementHistory::clone(), refinementHistory::clone(), IOobjectList::countImpl(), IOobjectList::countTypeImpl(), fvMeshTools::createDummyFvMeshFiles(), nearWallFields::createFields(), fvMatrix< Type >::createOrUpdateLduPrimitiveAssembly(), Foam::dec(), masterUncollatedFileOperation::dirPath(), uncollatedFileOperation::dirPath(), displacementLaplacianFvMotionSolver::displacementLaplacianFvMotionSolver(), displacementLaplacianFvMotionSolver::displacementLaplacianFvMotionSolver(), faMeshDistributor::distribute(), faMeshDistributor::distributeAreaFields(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), faMeshDistributor::distributeEdgeFields(), readFields::execute(), masterUncollatedFileOperation::exists(), fileOperation::exists(), masterUncollatedFileOperation::filePath(), uncollatedFileOperation::filePath(), uncollatedFileOperation::filePathInfo(), masterUncollatedFileOperation::filePathInfo(), surfaceFormatsCore::findFile(), triSurface::findFile(), surfaceFormatsCore::findFile(), triSurface::findFile(), Time::findInstance(), fileOperation::findInstance(), masterUncollatedFileOperation::findInstance(), topoSet::findIOobject(), searchableCone::findLine(), searchableCone::findLineAll(), searchableCone::findLineAny(), Foam::fixed(), genericFaePatchField< Type >::genericFaePatchField(), genericFaPatchField< Type >::genericFaPatchField(), genericPatchFieldBase::genericFatalSolveError(), genericFvPatchField< Type >::genericFvPatchField(), genericFvsPatchField< Type >::genericFvsPatchField(), genericPointPatchField< Type >::genericPointPatchField(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), Foam::getField(), fvExprDriver::getTopoSetLabels(), Foam::hex(), hexRef8Data::hexRef8Data(), hexRef8Data::hexRef8Data(), hexRef8Data::hexRef8Data(), if(), if(), if(), if(), dynamicMultiMotionSolverFvMesh::init(), dynamicMotionSolverListFvMesh::init(), PDRblock::innerMesh(), inverseDistance::inverseDistance(), IOPtrList< T >::IOPtrList(), decomposedBlockData::isCollatedType(), fvExpressionField::loadAndStore(), readFields::loadAndStore(), fvExpressionField::loadField(), readFields::loadField(), fvExpressionField::loadFields(), fvMeshTools::loadOrCreateMesh(), faMeshTools::loadOrCreateMesh(), faMeshTools::loadOrCreateMesh(), fvMeshTools::loadOrCreateMesh(), Foam::loadPointField(), masterUncollatedFileOperation::localObjectPath(), IOobjectList::lookupClassImpl(), IOobjectList::lookupClassTypeImpl(), IOobjectList::lookupImpl(), polyTopoChange::makeMesh(), polyTopoChange::makeMesh(), voxelMeshSearch::makeMesh(), blockMesh::mesh(), PDRblock::mesh(), IOobjectList::namesImpl(), IOobjectList::namesTypeImpl(), surfaceFilmModel::New(), dynamicFvMesh::New(), simplifiedDynamicFvMeshBase::New(), engineMesh::New(), radiationModel::New(), searchableSurface::New(), fvMeshTools::newMesh(), faMeshTools::newMesh(), GeometricField< symmTensor, fvPatchField, volMesh >::normalise(), collatedFileOperation::objectPath(), fileOperation::objectPath(), IOobjectList::objectsTypeImpl(), Foam::oct(), Foam::operator<<(), Foam::operator<<(), IOobject::operator=(), regIOobject::operator=(), PatchCollisionDensity< CloudType >::PatchCollisionDensity(), points0MotionSolver::points0IO(), genericPatchFieldBase::processEntry(), genericPatchFieldBase::processGeneric(), fileOperation::processorsCasePath(), collatedFileOperation::processorsDir(), fileOperation::processorsPath(), extendedEdgeMeshFormat::read(), edgeMeshFormat::read(), masterUncollatedFileOperation::read(), masterUncollatedFileOperation::read(), uncollatedFileOperation::read(), IOdictionary::readContents(), localIOdictionary::readContents(), IOField< Type >::readContents(), IOList< T >::readContents(), IOMap< T >::readContents(), IOPtrList< T >::readContents(), rawIOField< Type >::readContents(), fieldsDistributor::readField(), fieldsDistributor::readField(), boundaryDataSurfaceReader::readField(), lagrangianFieldDecomposer::readFieldFields(), lagrangianFieldDecomposer::readFields(), Foam::readFields(), Cloud< ParcelType >::readFromFiles(), dummyFileOperation::readHeader(), masterUncollatedFileOperation::readHeader(), uncollatedFileOperation::readHeader(), decomposedBlockData::readHeader(), boundaryDataSurfaceReader::readPoints(), Cloud< ParticleType >::readStoreFile(), masterUncollatedFileOperation::readStream(), uncollatedFileOperation::readStream(), Foam::readUniformFields(), Foam::ensightOutput::readWriteCloudField(), faFieldReconstructor::reconstructAreaFields(), faFieldReconstructor::reconstructEdgeFields(), lagrangianReconstructor::reconstructFieldFields(), lagrangianReconstructor::reconstructFields(), fvFieldReconstructor::reconstructInternalFields(), pointFieldReconstructor::reconstructPointFields(), fvFieldReconstructor::reconstructSurfaceFields(), fvFieldReconstructor::reconstructVolumeFields(), codedPoints0MotionSolver::redirectMotionSolver(), refinementFeatures::refinementFeatures(), refinementHistory::refinementHistory(), surfaceFormatsCore::relativeFilePath(), triSurface::relativeFilePath(), IOobjectList::remove(), processorFaMeshes::removeFiles(), hexRef8::removeFiles(), refinementHistory::removeFiles(), meshRefinement::removeFiles(), topoSet::removeFiles(), processorMeshes::removeFiles(), genericPatchFieldBase::reportMissingEntry(), objectRegistry::resetCacheTemporaryObject(), objectRegistry::resetCacheTemporaryObject(), fieldAverage::restoreWindowFieldsType(), Foam::scientific(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaces::searchableSurfaces(), searchableSurfaceWithGaps::searchableSurfaceWithGaps(), IOobject::selectIO(), decompositionModel::selectIO(), cyclicACMIPolyPatch::setUpToDate(), polyMesh::setUpToDatePoints(), solidBodyDisplacementLaplacianFvMotionSolver::solidBodyDisplacementLaplacianFvMotionSolver(), solidBodyDisplacementLaplacianFvMotionSolver::solidBodyDisplacementLaplacianFvMotionSolver(), motionSolver::stealRegistration(), surfMesh::surfMesh(), surfMesh::surfMesh(), surfZoneIOList::surfZoneIOList(), hexRef8Data::sync(), fvExprDriver::topoSetType(), triSurface::triSurface(), triSurfaceMesh::triSurfaceMesh(), triSurfaceMesh::triSurfaceMesh(), Foam::typeFilePath(), Foam::typeFilePath< IOMap< dictionary > >(), uniformInterpolationTable< Type >::uniformInterpolationTable(), UnsortedMeshedSurface< Face >::UnsortedMeshedSurface(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), AveragingMethod< Foam::Vector >::updateGrad(), cyclicACMIPolyPatch::upToDate(), polyMesh::upToDatePoints(), ddt2::write(), edgeMeshFormat::write(), MeshedSurfaceProxy< Face >::write(), decomposedBlockData::writeBlockEntry(), PDRblock::writeBlockMeshDict(), decomposedBlockData::writeData(), decomposedBlockData::writeExtraHeaderContent(), lagrangianWriter::writeFields(), decomposedBlockData::writeHeader(), IOobject::writeHeaderContent(), IOobject::writeHeaderContent(), faMeshReconstructor::writeMesh(), Foam::writeMeshObject(), collatedFileOperation::writeObject(), fileOperation::writeObject(), masterUncollatedFileOperation::writeObject(), Cloud< ParcelType >::writeObject(), writer::writeSolution(), and fvMeshSubsetProxy::zeroGradientField().
if()
if (io.typeHeaderOk< IOdictionary > ())
Definition at line 15 of file createMeshesPostProcess.H.
References filmDict, io(), and runTime.
Variable Documentation
filmDict
dictionary filmDict
Definition at line 3 of file createMeshesPostProcess.H.
Referenced by alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField(), and if().