OpenFOAM: applications/solvers/lagrangian/DPMFoam/DPMDyMFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField phiHbyA ("phiHbyA",(fvc::flux(HbyA)+alphacf *rAUcf *fvc::ddtCorr(Uc, Ucf)))
if (p.needReference())
constrainPressure (p, Uc, phiHbyA, rAUcf)
while (pimple.correctNonOrthogonal())
Variables
phiHbyA = phicForces
Function Documentation
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::flux(HbyA)+alphacf *rAUcf *fvc::ddtCorr(Uc, Ucf)))
if()
if (p. needReference())
Definition at line 13 of file pEqn.H.
References adjustPhi(), p, and phiHbyA.
constrainPressure()
constrainPressure (p , Uc , phiHbyA , rAUcf)
while()
while (pimple. correctNonOrthogonal())
Definition at line 26 of file pEqn.H.
References HbyA, mesh, n, p, phic(), phicForces(), phiHbyA, pimple, pRefCell, pRefValue, rAUc(), and rAUcf().
Variable Documentation
phiHbyA
phiHbyA = phicForces
Definition at line 20 of file pEqn.H.