OpenFOAM: src/lagrangian/spray/submodels/AtomizationModel/LISAAtomization/LISASMDCalcMethod2.H File Reference
LISASMDCalcMethod2.H File Reference
Functions
if (maxValue - minValue< SMALL)
forAll (rrd, n)
while (!success &&(k< 500))
Variables
scalar delta = dD/factorGamma
scalar minValue = dD/10.0
scalar maxValue = dD
scalar range = maxValue - minValue
scalar nExp = 3
FixedList< scalar, 500 > rrd
scalar probFactorMin = exp(-pow(minValue/delta, nExp))
scalar probFactorMax = exp(-pow(maxValue/delta, nExp))
scalar probFactor = 1.0/(probFactorMin - probFactorMax)
bool success = false
scalar y = rndGen.sample01<scalar>()
label k = 0
x = minValue + range*(k - 0.5)/500.0
Function Documentation
if()
if ()
Definition at line 18 of file LISASMDCalcMethod2.H.
References maxValue, and minValue.
forAll()
forAll (rrd , n)
Definition at line 31 of file LISASMDCalcMethod2.H.
References delta, minValue, n, nExp, probFactor, probFactorMin, range, and rrd.
while()
while (!success && k< 500)
Definition at line 43 of file LISASMDCalcMethod2.H.
References k, rrd, success, and y.
Variable Documentation
delta
scalar delta = dD/factorGamma
Definition at line 8 of file LISASMDCalcMethod2.H.
Referenced by Moment< Type >::add(), maxDurationCondition::apply(), DEShybrid< Type >::blendingFactor(), valueAverageBase::calc(), highAspectRatioFvGeometryScheme::calcAspectRatioWeights(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::calculate(), dynamicKEqn< BasicTurbulenceModel >::Ce(), dynamicKEqn< BasicTurbulenceModel >::Ck(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), thixotropicViscosity::correct(), BrunDrippingInjection::correct(), curvatureSeparation::correct(), drippingInjection::correct(), patchInjection::correct(), standardPhaseChange::correctModel(), waxSolventEvaporation::correctModel(), NicenoKEqn< BasicTurbulenceModel >::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), DeardorffDiffStress< BasicTurbulenceModel >::correctNut(), kEqn< BasicTurbulenceModel >::correctNut(), sigma< BasicTurbulenceModel >::correctNut(), Smagorinsky< BasicTurbulenceModel >::correctNut(), WALE< BasicTurbulenceModel >::correctNut(), dynamicLagrangian< BasicTurbulenceModel >::correctNut(), dynamicKEqn< BasicTurbulenceModel >::correctNut(), fvMesh::delta(), SpalartAllmarasIDDES< BasicTurbulenceModel >::dTilda(), LESModel< BasicTurbulenceModel >::epsilon(), sigma< BasicTurbulenceModel >::epsilon(), treeBoundBox::extend(), PDRblock::location::findIndex(), forAll(), kOmegaSSTLM< BasicTurbulenceModel >::Fthetat(), boundBox::grow(), boundBox::grow(), boundBox::inflate(), viewFactor::initialise(), Moment< Type >::interpolate(), StandardChemistryModel< ReactionThermo, ThermoType >::jacobian(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::jacobian(), TDACChemistryModel< ReactionThermo, ThermoType >::jacobian(), sigma< BasicTurbulenceModel >::k(), dynamicLagrangian< BasicTurbulenceModel >::k(), Smagorinsky< BasicTurbulenceModel >::k(), WALE< BasicTurbulenceModel >::k(), kOmegaSSTDES< BasicTurbulenceModel >::lengthScaleLES(), SpalartAllmarasDES< BasicTurbulenceModel >::lengthScaleLES(), faPatch::makeCorrectionVectors(), faPatch::makeDeltaCoeffs(), basicFvGeometryScheme::nonOrthCorrectionVectors(), basicFvGeometryScheme::nonOrthDeltaCoeffs(), ParticleHistogram< CloudType >::ParticleHistogram(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), eddyDissipationDiffusionModel< ReactionThermo, ThermoType >::rtDiff(), PPCG::scalarSolveCG(), globalIndex::setLocalSize(), CompactListList< T >::setLocalSize(), standardRadiation::Shs(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), laminar::Su(), LISAAtomization< CloudType >::update(), adjointFarFieldPressureFvPatchScalarField::updateCoeffs(), adjointFarFieldVelocityFvPatchVectorField::updateCoeffs(), adjointFarFieldNuaTildaFvPatchScalarField::updateCoeffs(), adjointFarFieldTMVar1FvPatchScalarField::updateCoeffs(), adjointFarFieldTMVar2FvPatchScalarField::updateCoeffs(), adjointOutletKaFvPatchScalarField::updateCoeffs(), adjointOutletNuaTildaFvPatchScalarField::updateCoeffs(), adjointOutletWaFvPatchScalarField::updateCoeffs(), reactingOneDim::updateqr(), regionSizeDistribution::write(), sizeDistribution::write(), ParticleHistogram< CloudType >::write(), and equalBinWidth::write().
minValue
scalar minValue = dD/10.0
Definition at line 12 of file LISASMDCalcMethod2.H.
Referenced by NURBS3DVolume::bound(), fieldMinMax::calcMinMaxFieldType(), forAll(), if(), Foam::min(), fieldMinMax::output(), InflationInjection< CloudType >::parcelsToInject(), accessor::set(), and while().
maxValue
scalar maxValue = dD
Definition at line 13 of file LISASMDCalcMethod2.H.
Referenced by if().
range
scalar range = maxValue - minValue
Definition at line 23 of file LISASMDCalcMethod2.H.
Referenced by forAll().
nExp
scalar nExp = 3
Definition at line 25 of file LISASMDCalcMethod2.H.
Referenced by forAll(), and while().
rrd
FixedList<scalar, 500> rrd
Definition at line 26 of file LISASMDCalcMethod2.H.
Referenced by forAll(), and while().
probFactorMin
scalar probFactorMin = exp(-pow(minValue/delta, nExp))
Definition at line 27 of file LISASMDCalcMethod2.H.
Referenced by forAll().
probFactorMax
scalar probFactorMax = exp(-pow(maxValue/delta, nExp))
Definition at line 28 of file LISASMDCalcMethod2.H.
probFactor
scalar probFactor = 1.0/(probFactorMin - probFactorMax)
Definition at line 29 of file LISASMDCalcMethod2.H.
Referenced by forAll().
success
bool success = false
Definition at line 38 of file LISASMDCalcMethod2.H.
Referenced by while().
y
scalar y = rndGen.sample01<scalar>()
Definition at line 40 of file LISASMDCalcMethod2.H.
Referenced by while().
k
label k = 0
Definition at line 41 of file LISASMDCalcMethod2.H.
Referenced by dictionary::add(), dictionary::add(), dictionary::add(), dictionary::add(), dictionary::add(), dictionary::add(), multiphaseStabilizedTurbulence::addSup(), phaseChange::addToDriftRate(), atmAmbientTurbSource::atmAmbientTurbSource(), atmBoundaryLayerInletKFvPatchScalarField::atmBoundaryLayerInletKFvPatchScalarField(), PDRblock::C(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), energySpectrum::calcAndWriteSpectrum(), BrownianMotionForce< CloudType >::calcCoupled(), addPatchCellLayer::calcExtrudeInfo(), LaakkonenAlopaeusAittamaaDsd::calcNik(), uniformBinary::calcNik(), atmNutkWallFunctionFvPatchScalarField::calcNut(), atmNutWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkWallFunctionFvPatchScalarField::calcNut(), MUCSheterogeneousRate< CloudType >::calculate(), atmEpsilonWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), atmOmegaWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), binaryNode< CompType, ThermoType >::calcV(), formatter::canWriteAttr(), ijkMesh::cellLabel(), ijkAddressing::checkIndex(), IntegralScaleBox< Type >::convolve(), diffusionMulticomponent< ReactionThermo, ThermoType >::correct(), EDC< ReactionThermo >::correct(), daughterSizeDistributionModel::correct(), phaseChange::correct(), radiativeIntensityRay::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), multiphaseStabilizedTurbulence::correct(), trackedParticle::correctAfterParallelTransfer(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), DeardorffDiffStress< BasicTurbulenceModel >::correctNut(), Smagorinsky< BasicTurbulenceModel >::correctNut(), WALE< BasicTurbulenceModel >::correctNut(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), LLTMatrix< Type >::decompose(), dmat_uniform(), dtris2(), PDRblock::dz(), eddyViscosity< LESModel< BasicTurbulenceModel > >::eddyViscosity(), blockDescriptor::edge(), Foam::Ek(), pairPotential::energy(), pairPotential::energyTable(), SpalartAllmarasBase< BasicEddyViscosityModel >::epsilon(), LESModel< BasicTurbulenceModel >::epsilon(), sigma< BasicTurbulenceModel >::epsilon(), Foam::Math::erfInv(), comfort::execute(), proudmanAcousticPower::execute(), Foam::facePointN(), blockDescriptor::facePoints(), voxelMeshSearch::fill(), voxelMeshSearch::fill(), inverseDistance::fill(), blockDescriptor::flatFaceOrEdge(), pairPotential::force(), pairPotential::forceTable(), NURBS3DVolume::getCPID(), PDRblock::grid(), Foam::HasherInt(), ijkAddressing::index(), inverseDistance::index3(), distribution::insertMissingKeys(), BlendedInterfacialModel< ModelType >::K(), BlendedInterfacialModel< ModelType >::K(), Kmesh::Kmesh(), kOmegaSSTDES< BasicTurbulenceModel >::lengthScaleRAS(), kOmegaSSTDES< BasicTurbulenceModel >::LESRegion(), Foam::LUDecompose(), Foam::LUDecompose(), faPatch::makeCorrectionVectors(), kaqRWallFunctionFvPatchScalarField::manipulateMatrix(), distribution::mean(), Distribution< Type >::mean(), daughterSizeDistributionModel::nik(), distribution::normalised(), Distribution< Type >::normalised(), Foam::operator&(), Foam::operator&(), IjkField< Type >::operator()(), IjkField< Type >::operator()(), Foam::operator*(), triad::operator+=(), HashSet< labelPairPair >::operator-=(), Foam::operator^(), voxelMeshSearch::overlaps(), inverseDistance::overlaps(), MomentumTransferPhaseSystem< BasePhaseSystem >::partialElimination(), MomentumTransferPhaseSystem< BasePhaseSystem >::partialEliminationf(), ijkMesh::pointLabel(), points_delaunay_naive_2d(), argList::printCompat(), IOobjectList::prune_0(), continuousGasKEpsilon< BasicTurbulenceModel >::R(), distribution::raw(), Distribution< Type >::raw(), energySpectrum::read(), IjkField< Type >::resize(), kOmegaSSTLM< BasicTurbulenceModel >::ReThetat0(), eddyDissipationModelBase< ReactionThermo, ThermoType >::rtTurb(), kOmegaSSTDDES< BasicTurbulenceModel >::S2(), kOmegaSSTDES< BasicTurbulenceModel >::S2(), general::sample(), dictionary::set(), dictionary::set(), pairPotential::setLookupTables(), seulex::seulex(), block::shapes(), QRMatrix< MatrixType >::solve(), SIBS::solve(), seulex::solve(), Foam::solve(), extendedEdgeMesh::sortPointsAndEdges(), PDRblock::span(), SVD::SVD(), triangulation_plot_eps(), triangulation_print(), StokesI::UfBase(), StokesII::UfBase(), GradientDispersionRAS< CloudType >::update(), StochasticDispersionRAS< CloudType >::update(), LISAAtomization< CloudType >::update(), atmBoundaryLayerInletKFvPatchScalarField::updateCoeffs(), atmAlphatkWallFunctionFvPatchScalarField::updateCoeffs(), advectiveFvPatchField< Type >::updateCoeffs(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), reactingOneDim::updatePhiGas(), reactingOneDim::updateqr(), IATEsource::Ut(), PDRblock::V(), blockDescriptor::vertex(), ijkMesh::vertLabels(), while(), PDRblock::width(), ensightWrite::write(), vtkWrite::write(), voxelMeshSearch::write(), formatter::writeAttr(), voxelMeshSearch::writeGrid(), Enum< EnumType >::writeList(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), and nutkWallFunctionFvPatchScalarField::yPlus().
x
x = minValue + range*(k - 0.5)/500.0
Definition at line 52 of file LISASMDCalcMethod2.H.
Referenced by boolVector::all(), Matrix< Form, Type >::Amul(), Matrix< Form, Type >::AmulImpl(), boolVector::any(), obstacleGrouping::append(), Foam::atan2(), Foam::atan2(), Foam::atan2(), atmCoriolisUSource::atmCoriolisUSource(), binaryTree< CompType, ThermoType >::balance(), BarycentricTensor< Cmpt >::BarycentricTensor(), Foam::BitOps::bit_count(), Foam::BitOps::bit_count(), Foam::BitOps::bit_count(), boolVector::boolVector(), buoyancyTurbSource::buoyancyTurbSource(), targetCoeffTrim::calcCoeffs(), LaakkonenAlopaeusAittamaaDsd::calcNik(), uniformBinary::calcNik(), Foam::calcPE15(), Foam::calcQE11(), Foam::calcQE16(), Stochastic< CloudType >::calculate(), Matrix< RectangularMatrix< Type >, Type >::cend(), TableBase< Type >::checkMaxBounds(), TableBase< Type >::checkMinBounds(), Tensor2D< Cmpt >::cols(), EigenMatrix< cmptType >::complexEVecs(), molecule::constantProperties::constantProperties(), rotorDiskSource::constructGeometry(), treeBoundBox::corner(), triSurfaceTools::curvatures(), triad::cx(), triad::cy(), triad::cz(), d_max(), d_min(), binaryTree< CompType, ThermoType >::deleteLeaf(), Polynomial< PolySize >::derivative(), cubicEqn::derivative(), quadraticEqn::derivative(), faMeshDistributor::distribute(), Foam::Math::erfInv(), cubicEqn::error(), linearEqn::error(), quadraticEqn::error(), Grimshaw::eta(), McCowan::eta(), quaternion::eulerAngles(), BlendedInterfacialModel< ModelType >::evaluate(), setFlow::execute(), treeBoundBox::faceBits(), blockDescriptor::facePointLabel(), blockDescriptor::flatFaceOrEdge(), boolVector::flip(), forAll(), rigidBodyModel::forwardDynamics(), exprDriver::getFunctionValue(), Foam::hypot(), Foam::hypot(), Foam::hypot(), Foam::Math::incGamma_P(), Foam::Math::incGamma_Q(), Foam::Math::incGammaRatio_P(), Foam::Math::incGammaRatio_Q(), waveModel::initialiseGeometry(), Polynomial< 8 >::integralMinus1(), patchTransformedInterpolation::interpolate(), uniformInterpolationTable< Type >::interpolate(), uniformInterpolationTable< scalar >::interpolateLog10(), uniformInterpolationTable< Type >::interpolateLog10(), Foam::interpolateSplineXY(), Foam::interpolateXY(), QRMatrix< MatrixType >::inv(), Tensor< scalar >::inv2D(), Vector2D< Cmpt >::isClose(), thermoCoupleProbes::jacobian(), BlendedInterfacialModel< Foam::dragModel >::K(), Foam::kShellIntegration(), Foam::kShellMean(), Foam::LAB_to_XYZ(), Foam::less(), Vector2D< scalar >::less_yx(), Vector< Cmpt >::magSqr(), Vector2D< Cmpt >::magSqr(), makeFaGradScheme(), Foam::makeGraph(), Foam::makeGraph(), Foam::makeGraph(), Foam::minMax(), Foam::minMax(), Foam::minMaxMag(), Foam::minMaxMag(), Foam::minMaxMag(), BlendedInterfacialModel< Foam::dragModel >::model(), McCowan::newtonRapsonF1(), McCowan::newtonRapsonF2(), ObukhovLength::ObukhovLength(), Tensor< scalar >::operator&=(), offsetOp< face >::operator()(), csvTableReader< Type >::operator()(), areaIntegrateOp< Type >::operator()(), volumeIntegrateOp< Type >::operator()(), offsetOp< labelledTri >::operator()(), minMaxOp< T >::operator()(), minMaxOp< T >::operator()(), minMaxMagOp< T >::operator()(), floorOp< Scalar >::operator()(), ceilOp< Scalar >::operator()(), roundOp< Scalar >::operator()(), minMaxMagOp< T >::operator()(), offsetOp< T >::operator()(), minMaxOp< T >::operator()(), hypotOp< T >::operator()(), minMaxOp< T >::operator()(), scalarDivideOp< T, T2 >::operator()(), scalarModuloOp< T, T2 >::operator()(), offsetOp< triFace >::operator()(), reduceFileStates::operator()(), minEqOpFace::operator()(), ifEqEqOp< value >::operator()(), unionEqOp::operator()(), minEqOp< labelPair >::operator()(), faceEqOp< T, CombineOp >::operator()(), listPlusEqOp< T >::operator()(), appendEqOp< T >::operator()(), uniqueEqOp< T >::operator()(), listUpdateOp< Type, TrackingData >::operator()(), minMaxEqOp< T >::operator()(), minMaxEqOp< T >::operator()(), minMaxEqOp< T >::operator()(), nearestFaceAMI::nearestEqOp::operator()(), nearestEqOp::operator()(), mappedPatchBase::nearestEqOp::operator()(), mappedPatchBase::maxProcEqOp::operator()(), mappedPatchBase::nearestWorldEqOp::operator()(), minFirstEqOp< T1 >::operator()(), maxFirstEqOp< T1 >::operator()(), combineConstraintsEqOp::operator()(), minMaxMagEqOp< T >::operator()(), minMaxMagEqOp< T >::operator()(), minMaxMagEqOp< T >::operator()(), globalMeshData::ListPlusEqOp< T >::operator()(), isNotEqOp< T >::operator()(), minFirstEqOp< T1 >::operator()(), maxFirstEqOp< T1 >::operator()(), combine< Type, TrackingData >::operator()(), updateOp< PrimitivePatchType, Type, TrackingData >::operator()(), combineEqOp< Type, TrackingData >::operator()(), combineReduceFileStates::operator()(), volumeCombineOp::operator()(), Foam::operator*(), Foam::operator*(), Foam::operator*(), Foam::operator*(), Foam::operator*(), AveragingMethod< Type >::operator*=(), Foam::operator+(), listOp< N >::result::operator+(), AveragingMethod< Type >::operator+=(), Foam::operator/(), AveragingMethod< Type >::operator/=(), AveragingMethod< Type >::operator=(), triad::operator=(), AveragingMethod< Type >::operator=(), AveragingMethod< Type >::operator=(), InflationInjection< CloudType >::parcelsToInject(), BlendedInterfacialModel< Foam::dragModel >::phaseModel(), Foam::MatrixTools::pinv(), weightedPosition::plusEqOp(), treeBoundBox::posBits(), Foam::pow(), ArdenBuck::pSatPrime(), quaternion::R(), energySpectrum::read(), fixedTrim::read(), NASedgeFormat::read(), GTSsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), general::readDict(), STARCDMeshReader::readPoints(), STARCDCore::readPoints(), Foam::RGB_to_XYZ(), cubicEqn::roots(), quadraticEqn::roots(), Roots< N >::Roots(), Roots< N >::Roots(), Roots< N >::Roots(), SymmTensor< Cmpt >::row(), Tensor< Cmpt >::row(), Tensor2D< Cmpt >::row(), SymmTensor< Cmpt >::row(), Tensor< scalar >::row(), Tensor2D< Cmpt >::row(), Tensor2D< Cmpt >::rows(), SymmTensor< Cmpt >::rows(), massRosinRammler::sample(), normal::sample(), multiNormal::sample(), searchableDisk::searchableDisk(), binaryTree< CompType, ThermoType >::secondaryBTSearch(), scanToken::setVector(), Foam::Sn(), adaptiveSolver::solve(), ODESolver::solve(), QRMatrix< MatrixType >::solve(), QRMatrix< MatrixType >::solve(), LLTMatrix< Type >::solve(), LLTMatrix< Type >::solve(), LUscalarMatrix::solve(), Euler::solve(), EulerSI::solve(), ODESolver::solve(), RKCK45::solve(), RKDP45::solve(), RKF45::solve(), rodas23::solve(), rodas34::solve(), Rosenbrock12::solve(), Rosenbrock23::solve(), Rosenbrock34::solve(), SIBS::solve(), Trapezoid::solve(), ODESolver::solve(), seulex::solve(), triad::sortxyz(), Foam::srange01(), Foam::stabilise(), SVD::SVD(), swapec(), SymmTensor< Cmpt >::SymmTensor(), colourTable::table(), Tensor< scalar >::Tensor(), Tensor< Cmpt >::Tensor(), Tensor2D< Cmpt >::Tensor2D(), Foam::tetCutPrism0(), Foam::tetCutPrism0(), Foam::tetCutPrism01(), Foam::tetCutPrism01(), Foam::tetCutPrism23(), Foam::tetCutPrism23(), Foam::tetCutTet(), Foam::tetCutTet(), Foam::tetReorder(), Foam::tetReorder(), targetCoeffTrim::thetag(), Matrix< Form, Type >::Tmul(), Matrix< Form, Type >::Tmul(), Matrix< Form, Type >::TmulImpl(), CV2D::toPoint2D(), binaryTree< CompType, ThermoType >::treeSuccessor(), Foam::triCutQuad(), Foam::triCutQuad(), Foam::triCutTri(), Foam::triCutTri(), Foam::triReorder(), Foam::triReorder(), irregularMultiDirectional::Uf(), Grimshaw::Uf(), McCowan::Uf(), StokesI::UfBase(), StokesII::UfBase(), pointConstraint::unconstrainedDirections(), azizChen::unscaledEnergy(), Foam::unzip(), Foam::unzip(), Foam::unzip(), Foam::unzip(), Foam::unzipCols(), Foam::unzipCols(), Foam::unzipCols(), Foam::unzipCols(), Foam::unzipCols(), Foam::unzipCols(), Foam::unzipRows(), Foam::unzipRows(), Foam::unzipRows(), Foam::unzipRows(), Foam::unzipRows(), Foam::unzipRows(), SHF< CloudType >::update(), LISAAtomization< CloudType >::update(), timeVaryingMappedFixedValuePointPatchField< Type >::updateCoeffs(), KinematicLookupTableInjection< CloudType >::updateMesh(), ReactingLookupTableInjection< CloudType >::updateMesh(), ReactingMultiphaseLookupTableInjection< CloudType >::updateMesh(), ThermoLookupTableInjection< CloudType >::updateMesh(), colourTable::value(), PatchExprField< Type >::value(), CodedField< Type >::value(), UniformValueField< Type >::value(), Function1Expression< Type >::value(), CodedFunction1< Type >::value(), Polynomial< Type >::value(), TableBase< Type >::value(), polynomialFunction::value(), TimeFunction1< Type >::value(), cubicEqn::value(), linearEqn::value(), quadraticEqn::value(), MappedFile< Type >::value(), Constant< Type >::value(), FieldFunction1< Function1Type >::value(), OneConstant< Type >::value(), sinImplicitFunction::value(), vbedg(), Foam::vectorMag(), Foam::vectorMag(), Foam::vectorMagSqr(), Foam::vectorMagSqr(), Relaxation< CloudType >::velocityCorrection(), while(), regionSizeDistribution::write(), ParticlePostProcessing< CloudType >::write(), equalBinWidth::write(), general::writeDict(), noiseModel::writeFileHeader(), eddy::writeSurfaceOBJ(), x3dWriter::writeTemplate(), graph::writer::writeXY(), general::x(), Foam::XYZ_to_LAB(), Foam::XYZ_to_RGB(), Foam::zip(), Foam::zip(), Foam::zip(), Foam::zip(), Foam::zipCols(), Foam::zipCols(), Foam::zipCols(), Foam::zipCols(), Foam::zipCols(), Foam::zipCols(), Foam::zipRows(), Foam::zipRows(), Foam::zipRows(), Foam::zipRows(), Foam::zipRows(), Foam::zipRows(), and BlendedInterfacialModel< Foam::dragModel >::~BlendedInterfacialModel().