OpenFOAM: applications/utilities/preProcessing/mapFields/setTimeIndex.H File Reference
setTimeIndex.H File Reference
Functions
if (args.found("sourceTime"))
runTimeSource setTime (sourceTimes[sourceTimeIndex], sourceTimeIndex)
Variables
instantList sourceTimes = runTimeSource.times()
label sourceTimeIndex = runTimeSource.timeIndex()
else
Function Documentation
if()
if (args. found"sourceTime")
Definition at line 3 of file setTimeIndex.H.
References args, argList::get(), UList< T >::size(), sourceTimeIndex, and sourceTimes.
setTime()
runTimeSource setTime (sourceTimes [sourceTimeIndex], sourceTimeIndex)
Referenced by coordSetWriter::beginTime(), surfaceWriter::beginTime(), coordSetWriter::beginTime(), surfaceWriter::beginTime(), ensightCase::nextTime(), Time::operator++(), Time::setControls(), Time::setTime(), ensightCase::setTime(), Time::subCycle(), and masterUncollatedFileOperation::writeObject().
Variable Documentation
sourceTimes
instantList sourceTimes = runTimeSource.times()
Definition at line 1 of file setTimeIndex.H.
Referenced by if().
sourceTimeIndex
label sourceTimeIndex = runTimeSource.timeIndex()
Definition at line 2 of file setTimeIndex.H.
Referenced by if().
else
else
Initial value:
{
        sourceTimeIndex = Time::findClosestTimeIndex
        (
            sourceTimes,
            runTimeTarget.time().value()
        )
Definition at line 18 of file setTimeIndex.H.