OpenFOAM: applications/solvers/multiphase/interCondensatingEvaporatingFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phiHbyA ("phiHbyA",(fvc::interpolate(HbyA) &mesh.Sf())+fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, phi))
adjustPhi (phiHbyA, U, p_rgh)
surfaceScalarField phig ((interface.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *rAUf *mesh.magSf())
constrainPressure (p_rgh, U, phiHbyA, rAUf)
while (pimple.correctNonOrthogonal())
if (p_rgh.needReference())
Variables
phiHbyA = phig
Pair< tmp< volScalarField > > vDot = mixture->vDot()
const volScalarField & vDotc = vDot[0]()
const volScalarField & vDotv = vDot[1]()
p = p_rgh + rho*gh
Function Documentation
rAUf()
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::interpolate(HbyA) &mesh.Sf())+fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, phi))
adjustPhi()
adjustPhi (phiHbyA , U , p_rgh)
phig()
surfaceScalarField phig ((interface.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *rAUf *mesh.magSf())
constrainPressure()
constrainPressure (p_rgh , U , phiHbyA , rAUf)
while()
while (pimple. correctNonOrthogonal())
Definition at line 30 of file pEqn.H.
References fvOptions, HbyA, mesh, p_rgh, phi, phig(), phiHbyA, pimple, pRefCell, pRefValue, rAU, rAUf(), U, vDotc, and vDotv.
if()
if (p_rgh. needReference())
Definition at line 56 of file pEqn.H.
References gh, p, p_rgh, pRefCell, pRefValue, and rho.
Variable Documentation
phiHbyA
phiHbyA = phig
Definition at line 21 of file pEqn.H.
vDot
Pair<tmp<volScalarField> > vDot = mixture->vDot()
Definition at line 26 of file pEqn.H.
vDotc
const volScalarField& vDotc = vDot[0]()
Definition at line 27 of file pEqn.H.
Referenced by while().
vDotv
const volScalarField& vDotv = vDot[1]()
Definition at line 28 of file pEqn.H.
Referenced by while().
p
p = p_rgh + rho*gh
Definition at line 54 of file pEqn.H.