OpenFOAM: applications/solvers/multiphase/MPPICInterFoam/UEqn.H File Reference
UEqn.H File Reference
Functions
MRF correctBoundaryVelocity (U)
fvVectorMatrix UEqn (fvm::ddt(alphacRho, U)+MRF.DDt(alphacRho, U) - fvm::Sp(fvc::ddt(rho)+fvc::div(rhoPhi), U)+fvm::div(rhoPhi, U)+turbulence->divDevRhoReff(U)==fvOptions(rho, U)+cloudSU)
UEqn relax ()
fvOptions constrain (UEqn)
volScalarField rAUc (1.0/UEqn.A())
surfaceScalarField rAUcf (fvc::interpolate(rAUc))
surfaceScalarField phicForces ((fvc::interpolate(rAUc *cloudVolSUSu) &mesh.Sf()))
if (pimple.momentumPredictor())
Function Documentation
correctBoundaryVelocity()
MRF correctBoundaryVelocity (U)
UEqn()
fvVectorMatrix UEqn (fvm::ddt(alphacRho, U)+MRF.DDt(alphacRho, U) - fvm::Sp(fvc::ddt(rho)+fvc::div(rhoPhi), U)+fvm::div(rhoPhi, U)+turbulence->divDevRhoReff(U) = =fvOptions(rho, U)+cloudSU)
relax()
UEqn relax ()
constrain()
fvOptions constrain (UEqn)
rAUc()
volScalarField rAUc (1.0/UEqn. A())
rAUcf()
surfaceScalarField rAUcf (fvc::interpolate(rAUc))
Referenced by if().
phicForces()
surfaceScalarField phicForces ((fvc::interpolate(rAUc *cloudVolSUSu) &mesh.Sf()))
Referenced by if().
if()
if (pimple. momentumPredictor())
Definition at line 28 of file UEqn.H.
References alpha1, fvOptions, ghf, mesh, mixture, p_rgh, phicForces(), rAUcf(), rho, solve(), U, and UEqn.