OpenFOAM: applications/solvers/multiphase/twoPhaseEulerFoam/pU/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField alphaf1 ("alphaf1", fvc::interpolate(alpha1))
surfaceScalarField alphaf2 ("alphaf2", scalar(1) - alphaf1)
volScalarField rAU1 (IOobject::groupName("rAU", phase1.name()), 1.0/(U1Eqn.A()+max(phase1.residualAlpha() - alpha1, scalar(0)) *rho1/runTime.deltaT()))
volScalarField rAU2 (IOobject::groupName("rAU", phase2.name()), 1.0/(U2Eqn.A()+max(phase2.residualAlpha() - alpha2, scalar(0)) *rho2/runTime.deltaT()))
surfaceScalarField alpharAUf1 (fvc::interpolate(max(alpha1, phase1.residualAlpha()) *rAU1))
surfaceScalarField alpharAUf2 (fvc::interpolate(max(alpha2, phase2.residualAlpha()) *rAU2))
surfaceScalarField Df1 (fvc::interpolate(rAU1 *(D+phase1.turbulence().pPrime())))
surfaceScalarField Df2 (fvc::interpolate(rAU2 *(D+phase2.turbulence().pPrime())))
if (implicitPhasePressure)
volVectorField F (fluid.F())
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1) *mesh.magSf())
while (pimple.correct())
if (thermo1.dpdt()||thermo2.dpdt())
Variables
tmp< surfaceScalarField > phiF1 = Df1*snGradAlpha1 + fvc::flux(rAU1*F)
tmp< surfaceScalarField > phiF2 = - Df2*snGradAlpha1 - fvc::flux(rAU2*F)
K1 = 0.5*magSqr(U1)
K2 = 0.5*magSqr(U2)
Function Documentation
alphaf1()
surfaceScalarField alphaf1 ("alphaf1" , fvc::interpolate(alpha1))
alphaf2()
surfaceScalarField alphaf2 ("alphaf2" , scalar(1) - alphaf1)
rAU1()
volScalarField rAU1 (IOobject::groupName("rAU", phase1.name()) , 1.0/ U1Eqn.A()+max(phase1.residualAlpha() - alpha1, scalar(0)) *rho1/runTime.deltaT())
rAU2()
volScalarField rAU2 (IOobject::groupName("rAU", phase2.name()) , 1.0/ U2Eqn.A()+max(phase2.residualAlpha() - alpha2, scalar(0)) *rho2/runTime.deltaT())
alpharAUf1()
surfaceScalarField alpharAUf1 (fvc::interpolate(max(alpha1, phase1.residualAlpha()) *rAU1))
alpharAUf2()
surfaceScalarField alpharAUf2 (fvc::interpolate(max(alpha2, phase2.residualAlpha()) *rAU2))
Df1()
surfaceScalarField Df1 (fvc::interpolate(rAU1 *(D+phase1.turbulence().pPrime())))
Referenced by if().
Df2()
surfaceScalarField Df2 (fvc::interpolate(rAU2 *(D+phase2.turbulence().pPrime())))
Referenced by if().
if() [1/2]
if (implicitPhasePressure)
Definition at line 61 of file pEqn.H.
References Df1(), Df2(), and fluid.
F()
volVectorField F (fluid. F())
Referenced by ReactingHeterogeneousParcel< ParcelType >::calcHeterogeneousReactions(), MUCSheterogeneousRate< CloudType >::calculate(), IshiiZuber::CdRe(), TomiyamaAnalytic::CdRe(), interpolated::damp(), interpolated::damp(), noWallDamping::damp(), viewFactor::initialise(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFs(), ReactingHeterogeneousParcel< ParcelType >::readFields(), azizChen::unscaledEnergy(), ReactingHeterogeneousParcel< ParcelType >::writeFields(), and ReactingHeterogeneousParcel< ParcelType >::writeObjects().
snGradAlpha1()
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1) *mesh.magSf())
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::phiFfs(), and MomentumTransferPhaseSystem< BasePhaseSystem >::phiFs().
while()
while (pimple. correct())
Definition at line 81 of file pEqn.H.
References alpha1, alpha2, alphaf1(), alphaf2(), alphaPhi1, alphaPhi2, alpharAUf1(), alpharAUf2(), contErr1, contErr2, fluid, forAll, fvOptions, g, gh, ghf, ghSnGradRho(), Kd(), mesh, MRF, p, p_rgh, p_rgh_0(), phase1, phase2, phi, phi1, phi2, phiF1, phiF2, phiHbyA, phir(), pimple, pMin, psi1, psi2, rAU1, rAU2, rAUf(), rAUKd1(), rAUKd2(), rho, rho1, rho2, runTime, setSnGrad< fixedFluxPressureFvPatchScalarField >(), solve(), U, U1, and U2.
if() [2/2]
if (thermo1. dpdt)||thermo2.dpdt()
Definition at line 413 of file pEqn.H.
References dpdt, and p.
Variable Documentation
phiF1
phiF1 = Df1*snGradAlpha1 + fvc::flux(rAU1*F)
Definition at line 35 of file pEqn.H.
phiF2
phiF2 = - Df2*snGradAlpha1 - fvc::flux(rAU2*F)
Definition at line 36 of file pEqn.H.
K1
K1 = 0.5*magSqr(U1)
Definition at line 409 of file pEqn.H.
K2
K2 = 0.5*magSqr(U2)
Definition at line 410 of file pEqn.H.