OpenFOAM: applications/solvers/multiphase/reactingTwoPhaseEulerFoam/pU/pEqn.H File Reference
pEqn.H File Reference
Functions
const surfaceScalarField alphaf1 ("alphaf1", fvc::interpolate(alpha1))
const surfaceScalarField alphaf2 ("alphaf2", scalar(1) - alphaf1)
rAUs append (new volScalarField(IOobject::groupName("rAU", phase1.name()), 1.0/(U1Eqn.A()+byDt(max(phase1.residualAlpha() - alpha1, scalar(0)) *rho1))))
rAUs append (new volScalarField(IOobject::groupName("rAU", phase2.name()), 1.0/(U2Eqn.A()+byDt(max(phase2.residualAlpha() - alpha2, scalar(0)) *rho2))))
const surfaceScalarField alpharAUf1 (fvc::interpolate(max(alpha1, phase1.residualAlpha()) *rAU1))
const surfaceScalarField alpharAUf2 (fvc::interpolate(max(alpha2, phase2.residualAlpha()) *rAU2))
const volScalarField Kd (fluid.Kd())
const volScalarField rAUKd1 (rAU1 *Kd)
const volScalarField rAUKd2 (rAU2 *Kd)
const surfaceScalarField phiKd1 (fvc::interpolate(rAUKd1))
const surfaceScalarField phiKd2 (fvc::interpolate(rAUKd2))
PtrList< surfaceScalarField > phiFs (fluid.phiFs(rAUs))
while (pimple.correct())
Variables
PtrList< volScalarField > rAUs
const volScalarField & rAU1 = rAUs[0]
const volScalarField & rAU2 = rAUs[1]
const surfaceScalarField & phiF1 = phiFs[0]
const surfaceScalarField & phiF2 = phiFs[1]
Function Documentation
alphaf1()
const surfaceScalarField alphaf1 ("alphaf1" , fvc::interpolate(alpha1))
Referenced by while().
alphaf2()
const surfaceScalarField alphaf2 ("alphaf2" , scalar(1) - alphaf1)
Referenced by while().
append() [1/2]
rAUs append (new volScalarFieldIOobject::groupName("rAU", phase1.name()), 1.0/(U1Eqn.A()+byDt(max(phase1.residualAlpha() - alpha1, scalar(0)) *rho1)))
Referenced by Cloud< ParticleType >::addParticle(), vtmWriter::append(), vtmWriter::append(), dlLibraryTable::append(), vtmWriter::append_vtp(), vtmWriter::append_vtp(), vtmWriter::append_vtu(), vtmWriter::append_vtu(), string::ext(), outputOptions::insitu(), ofstreamPointer::ofstreamPointer(), ReactionList< ThermoType >::readReactionDict(), seriesWriter::scan(), exprResultDelayed::storeValue(), and OFstreamCollator::write().
append() [2/2]
rAUs append (new volScalarFieldIOobject::groupName("rAU", phase2.name()), 1.0/(U2Eqn.A()+byDt(max(phase2.residualAlpha() - alpha2, scalar(0)) *rho2)))
alpharAUf1()
const surfaceScalarField alpharAUf1 (fvc::interpolate(max(alpha1, phase1.residualAlpha()) *rAU1))
Referenced by while().
alpharAUf2()
const surfaceScalarField alpharAUf2 (fvc::interpolate(max(alpha2, phase2.residualAlpha()) *rAU2))
Referenced by while().
Kd()
const volScalarField Kd (fluid. Kd())
Referenced by twoPhaseSystem::Kd(), and while().
rAUKd1()
const volScalarField rAUKd1 (rAU1 * Kd)
Referenced by while().
rAUKd2()
const volScalarField rAUKd2 (rAU2 * Kd)
Referenced by while().
phiKd1()
const surfaceScalarField phiKd1 (fvc::interpolate(rAUKd1))
Referenced by while().
phiKd2()
const surfaceScalarField phiKd2 (fvc::interpolate(rAUKd2))
Referenced by while().
phiFs()
PtrList< surfaceScalarField > phiFs (fluid. phiFsrAUs)
while()
while (pimple. correct())
Definition at line 54 of file pEqn.H.
References alpha1, alpha2, alphaf1(), alphaf2(), alphaPhi1, alphaPhi2, alpharAUf1(), alpharAUf2(), fluid, fvOptions, g, gh, ghf, ghSnGradRho(), mesh, MRF, p, p_rgh, p_rgh_0(), phase1, phase2, phi, phi1, phi2, phiF1, phiF2, phiHbyA, phiKd1(), phiKd2(), phir(), pimple, pMin, psi1, psi2, rAU1, rAU2, rAUf(), rAUKd1(), rAUKd2(), rAUs, rho, rho1, rho2, setSnGrad< fixedFluxPressureFvPatchScalarField >(), U, U1, and U2.
Variable Documentation
rAUs
PtrList<volScalarField> rAUs
Definition at line 4 of file pEqn.H.
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::ddtCorrByAs(), forAll(), MomentumTransferPhaseSystem< BasePhaseSystem >::KdUByAs(), MomentumTransferPhaseSystem< BasePhaseSystem >::partialElimination(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFs(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiKdPhis(), and while().
rAU1
const volScalarField& rAU1 = rAUs[0]
Definition at line 29 of file pEqn.H.
Referenced by while().
rAU2
const volScalarField& rAU2 = rAUs[1]
Definition at line 30 of file pEqn.H.
Referenced by while().
phiF1
const surfaceScalarField& phiF1 = phiFs[0]
Definition at line 50 of file pEqn.H.
Referenced by while().
phiF2
const surfaceScalarField& phiF2 = phiFs[1]
Definition at line 51 of file pEqn.H.
Referenced by while().