OpenFOAM: applications/solvers/multiphase/reactingMultiphaseEulerFoam/pU/pEqn.H File Reference
pEqn.H File Reference
Functions
PtrList< surfaceScalarField > alphafs (phases.size())
forAll (phases, phasei)
PtrList< volScalarField > rAUs (phases.size())
forAll (fluid.movingPhases(), movingPhasei)
fluid fillFields ("rAU", dimTime/dimDensity, rAUs)
PtrList< surfaceScalarField > alpharAUfs (phases.size())
PtrList< surfaceScalarField > phiFs (fluid.phiFs(rAUs))
while (pimple.correct())
Function Documentation
alphafs()
PtrList< surfaceScalarField > alphafs (phases. size())
Referenced by for(), forAll(), setSnGrad< fixedFluxPressureFvPatchScalarField >(), while(), and while().
forAll() [1/2]
forAll (phases , phasei)
Definition at line 3 of file pEqn.H.
References alpha, alphafs(), phasei, phases, and List< T >::set().
rAUs()
PtrList< volScalarField > rAUs (phases. size())
forAll() [2/2]
forAll (fluid. movingPhases(), movingPhasei)
Definition at line 14 of file pEqn.H.
References alpha, fluid, rAUs, List< T >::set(), and UEqns().
fillFields()
fluid fillFields ("rAU" , dimTime/ dimDensity, rAUs)
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::AFfs(), MomentumTransferPhaseSystem< BasePhaseSystem >::KdUByAs(), MomentumTransferPhaseSystem< BasePhaseSystem >::partialElimination(), MomentumTransferPhaseSystem< BasePhaseSystem >::partialEliminationf(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFfs(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFs(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiKdPhifs(), and MomentumTransferPhaseSystem< BasePhaseSystem >::phiKdPhis().
alpharAUfs()
PtrList< surfaceScalarField > alpharAUfs (phases. size())
Referenced by while().
phiFs()
PtrList< surfaceScalarField > phiFs (fluid. phiFsrAUs)
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::phiFs(), and while().
while()
while (pimple. correct())
Definition at line 55 of file pEqn.H.
References alpha, alphafs(), alpharAUfs(), fluid, forAll, fvOptions, g, gh, ghf, ghSnGradRho(), HbyAs(), mesh, MRF, oldTime(), p, p_rgh, p_rgh_0(), phasei, phases, phi, phib, phid(), phiFs(), phiHbyA, phiHbyAs(), pimple, pMin, rAUf(), rAUs, rho, runTime, List< T >::set(), setSnGrad< fixedFluxPressureFvPatchScalarField >(), solve(), and UEqns().