OpenFOAM: applications/solvers/multiphase/compressibleInterFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA)+MRF.zeroFilter(fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, phi)))
MRF makeRelative (phiHbyA)
surfaceScalarField phig ((mixture.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *rAUf *mesh.magSf())
constrainPressure (p_rgh, U, phiHbyA, rAUf, MRF)
if (pimple.transonic())
volScalarField p_rgh_0 (p_rgh)
while (pimple.correctNonOrthogonal())
mixture thermo1 ().correctRho(psi1 *(p_rgh - p_rgh_0))
mixture thermo2 ().correctRho(psi2 *(p_rgh - p_rgh_0))
p_rgh correctBoundaryConditions ()
Variables
phiHbyA = phig
tmp< fvScalarMatrix > p_rghEqnComp1
tmp< fvScalarMatrix > p_rghEqnComp2
else
rho = alpha1*rho1 + alpha2*rho2
p_rgh = p - rho*gh
K = 0.5*magSqr(U)
Function Documentation
rAUf()
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA)+MRF.zeroFilter(fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, phi)))
makeRelative()
MRF makeRelative (phiHbyA)
phig()
surfaceScalarField phig ((mixture.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *rAUf *mesh.magSf())
constrainPressure()
constrainPressure (p_rgh , U , phiHbyA , rAUf , MRF)
if()
if (pimple. transonic())
Definition at line 29 of file pEqn.H.
References alpha1, alpha2, alphaPhi1, alphaPhi2, fvOptions, mixture, p_rgh, p_rghEqnComp1, p_rghEqnComp2, phi, psi1, psi2, rho1, rho1f(), rho2, and rho2f().
p_rgh_0()
volScalarField p_rgh_0 (p_rgh)
while()
while (pimple. correctNonOrthogonal())
Definition at line 100 of file pEqn.H.
References alpha1, alpha2, fvOptions, gh, HbyA, mesh, p, p_rgh, p_rghEqnComp1, p_rghEqnComp2, phi, phig(), phiHbyA, pimple, pMin, rAU, rAUf(), rho1, rho2, solve(), and U.
thermo1()
mixture thermo1 ()
Definition at line 19 of file setRegionFluidFields.H.
Referenced by for().
thermo2()
mixture thermo2 ()
Definition at line 20 of file setRegionFluidFields.H.
Referenced by for().
correctBoundaryConditions()
p_rgh correctBoundaryConditions ()
Variable Documentation
phiHbyA
phiHbyA = phig
Definition at line 21 of file pEqn.H.
p_rghEqnComp1
tmp<fvScalarMatrix> p_rghEqnComp1
Definition at line 26 of file pEqn.H.
p_rghEqnComp2
p_rghEqnComp2
Initial value:
=
            pos(alpha2)
           *(
               (
                   fvc::ddt(alpha2, rho2) + fvc::div(alphaPhi2*rho2f)
                 - (fvOptions(alpha2, mixture.thermo2().rho())&rho2)
               )/rho2
             - fvc::ddt(alpha2) - fvc::div(alphaPhi2)
             + (alpha2*psi2/rho2)*correction(fvm::ddt(p_rgh))
            )
Definition at line 27 of file pEqn.H.
else
else
Initial value:
{
# 72 "/Volumes/OpenFOAM-v2306/applications/solvers/multiphase/compressibleInterFoam/pEqn.H" 2
        p_rghEqnComp1 =
            pos(alpha1)
           *(
                (
                    fvc::ddt(alpha1, rho1) + fvc::div(alphaPhi1*rho1f)
                  - (fvOptions(alpha1, mixture.thermo1().rho())&rho1)
                )/rho1
              - fvc::ddt(alpha1) - fvc::div(alphaPhi1)
              + (alpha1*psi1/rho1)*correction(fvm::ddt(p_rgh))
            )
Definition at line 70 of file pEqn.H.
rho
rho = alpha1*rho1 + alpha2*rho2
Definition at line 138 of file pEqn.H.
p_rgh
p_rgh = p - rho*gh
Definition at line 141 of file pEqn.H.
K
K = 0.5*magSqr(U)
Definition at line 144 of file pEqn.H.