OpenFOAM: applications/solvers/multiphase/cavitatingFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phiGradp (rhorAUf *mesh.magSf() *fvc::snGrad(p))
while (pimple.correctNonOrthogonal())
Variables
phi
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
phiGradp()
surfaceScalarField phiGradp (rhorAUf *mesh. magSf) *fvc::snGrad(p)
while()
while (pimple. correctNonOrthogonal())
Definition at line 25 of file pEqn.H.
References mesh, p, phi, phiGradp(), pimple, psi, rho, rhof(), and rhorAUf().
Variable Documentation
phi
phi
Initial value:
= fvc::flux(HbyA)
         + rhorAUf*fvc::ddtCorr(U, phi)
Definition at line 18 of file pEqn.H.