OpenFOAM: applications/solvers/multiphase/reactingTwoPhaseEulerFoam/pUf/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField alphaf1 ("alphaf1", fvc::interpolate(alpha1))
surfaceScalarField alphaf2 ("alphaf2", scalar(1) - alphaf1)
surfaceScalarField alphaRhof10 ("alphaRhof10", fvc::interpolate(max(alpha1.oldTime(), phase1.residualAlpha()) *rho1.oldTime()))
surfaceScalarField alphaRhof20 ("alphaRhof20", fvc::interpolate(max(alpha2.oldTime(), phase2.residualAlpha()) *rho2.oldTime()))
const surfaceScalarField Kdf ("Kdf", fluid.Kdf())
PtrList< surfaceScalarField > AFfs (fluid.AFfs())
rAUfs append (new surfaceScalarField(IOobject::groupName("rAUf", phase1.name()), 1.0/(byDt(alphaRhof10)+fvc::interpolate(U1Eqn.A())+AFfs[0])))
rAUfs append (new surfaceScalarField(IOobject::groupName("rAUf", phase2.name()), 1.0/(byDt(alphaRhof20)+fvc::interpolate(U2Eqn.A())+AFfs[0])))
AFfs clear ()
PtrList< surfaceScalarField > phiFfs (fluid.phiFfs(rAUfs))
while (pimple.correct())
Variables
PtrList< surfaceScalarField > rAUfs
const surfaceScalarField & rAUf1 = rAUfs[0]
const surfaceScalarField & rAUf2 = rAUfs[1]
const surfaceScalarField & phiFf1 = phiFfs[0]
const surfaceScalarField & phiFf2 = phiFfs[1]
Function Documentation
alphaf1()
surfaceScalarField alphaf1 ("alphaf1" , fvc::interpolate(alpha1))
alphaf2()
surfaceScalarField alphaf2 ("alphaf2" , scalar(1) - alphaf1)
alphaRhof10()
surfaceScalarField alphaRhof10 ("alphaRhof10" , fvc::interpolate(max(alpha1.oldTime(), phase1.residualAlpha()) *rho1.oldTime()))
Referenced by while().
alphaRhof20()
surfaceScalarField alphaRhof20 ("alphaRhof20" , fvc::interpolate(max(alpha2.oldTime(), phase2.residualAlpha()) *rho2.oldTime()))
Referenced by while().
Kdf()
const surfaceScalarField Kdf ("Kdf" , fluid. Kdf())
Referenced by twoPhaseSystem::Kdf(), and while().
AFfs()
PtrList< surfaceScalarField > AFfs (fluid. AFfs())
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::AFfs(), and forAll().
append() [1/2]
rAUfs append (new surfaceScalarFieldIOobject::groupName("rAUf", phase1.name()), 1.0/(byDt(alphaRhof10)+fvc::interpolate(U1Eqn.A())+AFfs[0]))
append() [2/2]
rAUfs append (new surfaceScalarFieldIOobject::groupName("rAUf", phase2.name()), 1.0/(byDt(alphaRhof20)+fvc::interpolate(U2Eqn.A())+AFfs[0]))
clear()
AFfs clear ()
phiFfs()
PtrList< surfaceScalarField > phiFfs (fluid. phiFfsrAUfs)
while()
while (pimple. correct())
Definition at line 68 of file pEqn.H.
References alpha1, alpha2, alphaf1(), alphaf2(), alphaPhi1, alphaPhi2, alpharAUf1(), alpharAUf2(), alphaRhof10(), alphaRhof20(), fluid, fvOptions, g, gh, ghf, ghSnGradRho(), Kdf(), mesh, MRF, p, p_rgh, p_rgh_0(), phase1, phase2, phi, phi1, phi2, phiFf1, phiFf2, phiHbyA, phir(), pimple, pMin, psi1, psi2, rAUf(), rAUf1, rAUf2, rAUfs, rho, rho1, rho2, setSnGrad< fixedFluxPressureFvPatchScalarField >(), solve(), U1, and U2.
Variable Documentation
rAUfs
PtrList<surfaceScalarField> rAUfs
Definition at line 30 of file pEqn.H.
Referenced by forAll(), MomentumTransferPhaseSystem< BasePhaseSystem >::partialEliminationf(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFfs(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiKdPhifs(), and while().
rAUf1
const surfaceScalarField& rAUf1 = rAUfs[0]
Definition at line 57 of file pEqn.H.
Referenced by if(), and while().
rAUf2
const surfaceScalarField& rAUf2 = rAUfs[1]
Definition at line 58 of file pEqn.H.
Referenced by if(), and while().
phiFf1
const surfaceScalarField& phiFf1 = phiFfs[0]
Definition at line 64 of file pEqn.H.
Referenced by while().
phiFf2
const surfaceScalarField& phiFf2 = phiFfs[1]
Definition at line 65 of file pEqn.H.
Referenced by while().