OpenFOAM: applications/solvers/multiphase/interPhaseChangeFoam/overInterPhaseChangeDyMFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA))
if (p_rgh.needReference())
surfaceScalarField phig ((interface.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *faceMask *rAUf *mesh.magSf())
constrainPressure (p_rgh, U, phiHbyA, rAUf)
while (pimple.correctNonOrthogonal())
surfaceVectorField n (mesh.Sf()/mesh.magSf())
Variables
phiHbyA = phig
Pair< tmp< volScalarField > > vDotP = mixture->vDotP()
const volScalarField & vDotcP = vDotP[0]()
const volScalarField & vDotvP = vDotP[1]()
Uf = n*(phi/mesh.magSf() - (n & Uf))
phi * p == p_rgh + rho*gh
Function Documentation
rAUf()
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA))
if()
if (p_rgh. needReference())
Definition at line 11 of file pEqn.H.
References adjustPhi(), p_rgh, phiHbyA, and U.
phig()
surfaceScalarField phig ((interface.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *faceMask *rAUf *mesh.magSf())
constrainPressure()
constrainPressure (p_rgh , U , phiHbyA , rAUf)
while()
while (pimple. correctNonOrthogonal())
Definition at line 35 of file pEqn.H.
References fvOptions, gh, HbyA, mesh, mixture, p_rgh, phi, phig(), phiHbyA, pimple, pRefCell, rAU, rAUf(), rho, U, vDotcP, and vDotvP.
n()
surfaceVectorField n (mesh. Sf)/mesh.magSf()
Variable Documentation
phiHbyA
phiHbyA = phig
Definition at line 26 of file pEqn.H.
vDotP
Pair<tmp<volScalarField> > vDotP = mixture->vDotP()
Definition at line 31 of file pEqn.H.
vDotcP
const volScalarField& vDotcP = vDotP[0]()
Definition at line 32 of file pEqn.H.
vDotvP
const volScalarField& vDotvP = vDotP[1]()
Definition at line 33 of file pEqn.H.
Uf
Uf = n*(phi/mesh.magSf() - (n & Uf))
Definition at line 70 of file pEqn.H.
p
phi* p == p_rgh + rho*gh
Definition at line 79 of file pEqn.H.