OpenFOAM: applications/solvers/multiphase/multiphaseEulerFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
PtrList< volVectorField > HbyAs (fluid.phases().size())
PtrList< surfaceScalarField > phiHbyAs (fluid.phases().size())
PtrList< volScalarField > rAUs (fluid.phases().size())
PtrList< surfaceScalarField > rAlphaAUfs (fluid.phases().size())
for (phaseModel &phase :fluid.phases())
surfaceScalarField phiHbyA (IOobject("phiHbyA", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar(dimVelocity *dimArea, Zero))
volScalarField rho ("rho", fluid.rho())
surfaceScalarField ghSnGradRho (ghf *fvc::snGrad(rho) *mesh.magSf())
surfaceScalarField rAUf (IOobject("rAUf", runTime.timeName(), mesh), mesh, dimensionedScalar(dimensionSet(-1, 3, 1, 0, 0), Zero))
for (const phaseModel &phase :fluid.phases())
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryFieldRef(),(phiHbyA.boundaryField() - MRF.relative(phib))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
while (pimple.correctNonOrthogonal())
Variables
phasei = 0
phib = 0
Function Documentation
HbyAs()
PtrList< volVectorField > HbyAs (fluid. phases).size()
Referenced by for(), while(), and while().
phiHbyAs()
PtrList< surfaceScalarField > phiHbyAs (fluid. phases).size()
Referenced by for(), while(), and while().
rAUs()
PtrList< volScalarField > rAUs (fluid. phases).size()
rAlphaAUfs()
PtrList< surfaceScalarField > rAlphaAUfs (fluid. phases).size()
Referenced by for(), and while().
for() [1/2]
for (phaseModel &phase :fluid. phases())
Definition at line 34 of file pEqn.H.
References HbyAs(), MRF, phasei, and phiHbyAs().
phiHbyA()
surfaceScalarField phiHbyA (IOobject("phiHbyA", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar(dimVelocity *dimArea, Zero))
rho()
volScalarField rho ("rho" , fluid. rho())
ghSnGradRho()
surfaceScalarField ghSnGradRho (ghf * fvc::snGradrho) *mesh.magSf()
Referenced by while(), and while().
rAUf()
surfaceScalarField rAUf (IOobject("rAUf", runTime.timeName(), mesh) , mesh , dimensionedScalar(dimensionSet(-1, 3, 1, 0, 0), Zero))
for() [2/2]
for (const phaseModel &phase :fluid. phases())
Definition at line 179 of file pEqn.H.
References alphafs(), phasei, rAlphaAUfs(), and rAUf().
setSnGrad< fixedFluxPressureFvPatchScalarField >()
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryFieldRef(), (phiHbyA.boundaryField() - MRF.relative(phib))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
References alphafs(), mesh, phasei, and phib.
Referenced by while().
while()
while (pimple. correctNonOrthogonal())
Definition at line 209 of file pEqn.H.
References alpha, alphafs(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), fluid, g, gh, ghSnGradRho(), HbyAs(), mesh, p, p_rgh, phasei, phi, phiHbyA, phiHbyAs(), pimple, pRefCell, pRefValue, rAlphaAUfs(), rAUf(), rho, solve(), and U.
Variable Documentation
phasei
phasei = 0
Definition at line 33 of file pEqn.H.
phib
phib = 0
Definition at line 189 of file pEqn.H.
Referenced by setSnGrad< fixedFluxPressureFvPatchScalarField >(), and while().