OpenFOAM: applications/solvers/multiphase/interFoam/overInterDyMFoam/correctPhi.H File Reference
correctPhi.H File Reference
Functions
for (label i=0;i< p_rgh.boundaryField().size();i++)
volScalarField pcorr (IOobject("pcorr", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar(p_rgh.dimensions(), Zero), pcorrTypes)
if (pcorr.needReference())
mesh setFluxRequired (pcorr.name())
dimensionedScalar rAUf ("rAUf", dimTime/rho.dimensions(), 1.0)
while (pimple.correctNonOrthogonal())
Variables
const cellCellStencilObject & overlap = Stencil::New(mesh)
const labelList & cellTypes = overlap.cellTypes()
const labelIOList & zoneIDs = overlap.zoneID()
Function Documentation
for()
for ()
Definition at line 33 of file correctPhi.H.
References p_rgh, and pcorrTypes().
pcorr()
volScalarField pcorr (IOobject("pcorr", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedScalar(p_rgh.dimensions(), Zero) , pcorrTypes)
if()
if (pcorr. needReference())
Definition at line 56 of file correctPhi.H.
References adjustPhi(), pcorr(), phi, and U.
setFluxRequired()
mesh setFluxRequired (pcorr. name())
rAUf()
dimensionedScalar rAUf ("rAUf" , dimTime/rho. dimensions(), 1. 0)
while()
while (pimple. correctNonOrthogonal())
Definition at line 71 of file correctPhi.H.
References cellTypes, forAll, mesh, pcorr(), phi, pimple, rAUf(), and zoneIDs.
Variable Documentation
overlap
const cellCellStencilObject& overlap = Stencil::New(mesh)
Definition at line 67 of file correctPhi.H.
cellTypes
const labelList& cellTypes = overlap.cellTypes()
Definition at line 68 of file correctPhi.H.
zoneIDs
const labelIOList& zoneIDs = overlap.zoneID()
Definition at line 69 of file correctPhi.H.