OpenFOAM: applications/solvers/multiphase/icoReactingMultiphaseInterFoam/TEqn.H File Reference
TEqn.H File Reference
Functions
const surfaceScalarField rhoCpPhi (fvc::interpolate(fluid.Cp()) *rhoPhi)
const volScalarField kappaEff ("kappaEff", fluid.kappa()+fluid.Cp() *turbulence->mut()/fluid.Prt())
fvScalarMatrix TEqn (fvm::ddt(rhoCp, T)+fvm::div(rhoCpPhi, T, "div(phi,T)") - fvm::Sp(fvc::ddt(rhoCp)+fvc::div(rhoCpPhi), T) - fvm::laplacian(kappaEff, T, "laplacian(kappa,T)")==fluid.heatTransfer(T)+radiation->ST(T)+fvOptions(rhoCp, T))
TEqn relax ()
fvOptions constrain (TEqn)
TEqn solve ()
fvOptions correct (T)
fluid correct ()
Variables
rhoCp = rho*fluid.Cp()
Function Documentation
rhoCpPhi()
const surfaceScalarField rhoCpPhi (fvc::interpolate(fluid.Cp()) * rhoPhi)
Referenced by energyTransport::execute().
kappaEff()
const volScalarField kappaEff ("kappaEff" , fluid. kappa)+fluid.Cp() *turbulence->mut()/fluid.Prt()
TEqn()
fvScalarMatrix TEqn (fvm::ddt(rhoCp, T)+fvm::div(rhoCpPhi, T, "div(phi,T)") - fvm::Sp(fvc::ddt(rhoCp)+fvc::div(rhoCpPhi), T) - fvm::laplacian(kappaEff, T, "laplacian(kappa,T)") = =fluid.heatTransfer(T)+radiation->ST(T)+fvOptions(rhoCp, T))
relax()
TEqn relax ()
constrain()
fvOptions constrain (TEqn)
solve()
TEqn solve ()
correct() [1/2]
fvOptions correct (T)
correct() [2/2]
fluid correct ()
Variable Documentation
rhoCp
rhoCp = rho*fluid.Cp()
Definition at line 3 of file TEqn.H.
Referenced by energyTransport::execute(), radiationModel::ST(), and radiationModel::ST().