OpenFOAM: applications/solvers/multiphase/VoF/setRDeltaT.H File Reference
setRDeltaT.H File Reference
Functions
scalar maxCo (pimpleDict.getOrDefault< scalar >("maxCo", 0.9))
scalar maxAlphaCo (pimpleDict.getOrDefault< scalar >("maxAlphaCo", 0.2))
scalar rDeltaTSmoothingCoeff (pimpleDict.getOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.1))
label nAlphaSpreadIter (pimpleDict.getOrDefault< label >("nAlphaSpreadIter", 1))
scalar alphaSpreadDiff (pimpleDict.getOrDefault< scalar >("alphaSpreadDiff", 0.2))
scalar alphaSpreadMax (pimpleDict.getOrDefault< scalar >("alphaSpreadMax", 0.99))
scalar alphaSpreadMin (pimpleDict.getOrDefault< scalar >("alphaSpreadMin", 0.01))
label nAlphaSweepIter (pimpleDict.getOrDefault< label >("nAlphaSweepIter", 5))
scalar rDeltaTDampingCoeff (pimpleDict.getOrDefault< scalar >("rDeltaTDampingCoeff", 1.0))
scalar maxDeltaT (pimpleDict.getOrDefault< scalar >("maxDeltaT", GREAT))
volScalarField rDeltaT0 ("rDeltaT0", rDeltaT)
rDeltaT ref ()
if (maxAlphaCo< maxCo)
rDeltaT correctBoundaryConditions ()
Variables
const dictionary & pimpleDict = pimple.dict()
Function Documentation
maxCo()
scalar maxCo (pimpleDict.getOrDefault< scalar > "maxCo", 0.9)
maxAlphaCo()
scalar maxAlphaCo (pimpleDict.getOrDefault< scalar > "maxAlphaCo", 0.2)
rDeltaTSmoothingCoeff()
scalar rDeltaTSmoothingCoeff (pimpleDict.getOrDefault< scalar > "rDeltaTSmoothingCoeff", 0.1)
nAlphaSpreadIter()
label nAlphaSpreadIter (pimpleDict.getOrDefault< label > "nAlphaSpreadIter", 1)
alphaSpreadDiff()
scalar alphaSpreadDiff (pimpleDict.getOrDefault< scalar > "alphaSpreadDiff", 0.2)
alphaSpreadMax()
scalar alphaSpreadMax (pimpleDict.getOrDefault< scalar > "alphaSpreadMax", 0.99)
Referenced by if().
alphaSpreadMin()
scalar alphaSpreadMin (pimpleDict.getOrDefault< scalar > "alphaSpreadMin", 0.01)
Referenced by if().
nAlphaSweepIter()
label nAlphaSweepIter (pimpleDict.getOrDefault< label > "nAlphaSweepIter", 5)
rDeltaTDampingCoeff()
scalar rDeltaTDampingCoeff (pimpleDict.getOrDefault< scalar > "rDeltaTDampingCoeff", 1.0)
maxDeltaT()
scalar maxDeltaT (pimpleDict.getOrDefault< scalar > "maxDeltaT", GREAT)
rDeltaT0()
volScalarField rDeltaT0 ("rDeltaT0" , rDeltaT)
ref()
rDeltaT ref ()
if()
if ()
Definition at line 66 of file setRDeltaT.H.
References alpha1, alphaSpreadMax(), alphaSpreadMin(), maxAlphaCo, mesh, and phi.
correctBoundaryConditions()
rDeltaT correctBoundaryConditions ()
References rDeltaTSmoothingCoeff().
Variable Documentation
pimpleDict
const dictionary& pimpleDict = pimple.dict()
Definition at line 4 of file setRDeltaT.H.