OpenFOAM: applications/solvers/multiphase/twoPhaseEulerFoam/pUf/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField alphaf1 ("alphaf1", fvc::interpolate(alpha1))
surfaceScalarField alphaf2 ("alphaf2", scalar(1) - alphaf1)
surfaceScalarField alphaRhof10 ("alphaRhof10", fvc::interpolate(max(alpha1.oldTime(), phase1.residualAlpha()) *rho1.oldTime()))
surfaceScalarField alphaRhof20 ("alphaRhof20", fvc::interpolate(max(alpha2.oldTime(), phase2.residualAlpha()) *rho2.oldTime()))
surfaceScalarField Kdf ("Kdf", fluid.Kdf())
surfaceScalarField Vmf ("Vmf", fluid.Vmf())
surfaceScalarField rAUf1 (IOobject::groupName("rAUf", phase1.name()), 1.0/((alphaRhof10+Vmf)/runTime.deltaT()+fvc::interpolate(U1Eqn.A())+Kdf))
surfaceScalarField rAUf2 (IOobject::groupName("rAUf", phase2.name()), 1.0/((alphaRhof20+Vmf)/runTime.deltaT()+fvc::interpolate(U2Eqn.A())+Kdf))
surfaceScalarField Df1 (fvc::interpolate(D+phase1.turbulence().pPrime()))
surfaceScalarField Df2 (fvc::interpolate(D+phase2.turbulence().pPrime()))
if (implicitPhasePressure)
surfaceScalarField Ff (fluid.Ff())
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1) *mesh.magSf())
while (pimple.correct())
if (thermo1.dpdt()||thermo2.dpdt())
Variables
tmp< surfaceScalarField > Ff1 = Df1*snGradAlpha1 + Ff
tmp< surfaceScalarField > Ff2 = -Df2*snGradAlpha1 - Ff
K1 = 0.5*magSqr(U1)
K2 = 0.5*magSqr(U2)
Function Documentation
alphaf1()
surfaceScalarField alphaf1 ("alphaf1" , fvc::interpolate(alpha1))
alphaf2()
surfaceScalarField alphaf2 ("alphaf2" , scalar(1) - alphaf1)
alphaRhof10()
surfaceScalarField alphaRhof10 ("alphaRhof10" , fvc::interpolate(max(alpha1.oldTime(), phase1.residualAlpha()) *rho1.oldTime()))
alphaRhof20()
surfaceScalarField alphaRhof20 ("alphaRhof20" , fvc::interpolate(max(alpha2.oldTime(), phase2.residualAlpha()) *rho2.oldTime()))
Kdf()
surfaceScalarField Kdf ("Kdf" , fluid. Kdf())
Vmf()
surfaceScalarField Vmf ("Vmf" , fluid. Vmf())
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::AFfs(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFfs(), and while().
rAUf1()
surfaceScalarField rAUf1 (IOobject::groupName("rAUf", phase1.name()) , 1.0/ (alphaRhof10+Vmf)/runTime.deltaT()+fvc::interpolate(U1Eqn.A())+Kdf)
rAUf2()
surfaceScalarField rAUf2 (IOobject::groupName("rAUf", phase2.name()) , 1.0/ (alphaRhof20+Vmf)/runTime.deltaT()+fvc::interpolate(U2Eqn.A())+Kdf)
Df1()
surfaceScalarField Df1 (fvc::interpolate(D+phase1.turbulence().pPrime()))
Df2()
surfaceScalarField Df2 (fvc::interpolate(D+phase2.turbulence().pPrime()))
if() [1/2]
if (implicitPhasePressure)
Definition at line 74 of file pEqn.H.
References Df1(), Df2(), fluid, rAUf1, and rAUf2.
Ff()
surfaceScalarField Ff (fluid. Ff())
Referenced by interpolated::damp(), noWallDamping::damp(), and MomentumTransferPhaseSystem< BasePhaseSystem >::phiFfs().
snGradAlpha1()
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1) *mesh.magSf())
while()
while (pimple. correct())
Definition at line 93 of file pEqn.H.
References alpha1, alpha2, alphaf1(), alphaf2(), alphaPhi1, alphaPhi2, alpharAUf1(), alpharAUf2(), alphaRhof10(), alphaRhof20(), contErr1, contErr2, ddtPhi1, ddtPhi2, Ff1, Ff2, fluid, fvOptions, g, gh, ghf, ghSnGradRho(), Kdf(), mesh, MRF, p, p_rgh, p_rgh_0(), phase1, phase2, phi, phi1, phi2, phiHbyA, phir(), pimple, pMin, psi1, psi2, rAUf(), rAUf1, rAUf2, rho, rho1, rho2, runTime, setSnGrad< fixedFluxPressureFvPatchScalarField >(), solve(), U, U1, U2, and Vmf().
if() [2/2]
if (thermo1. dpdt)||thermo2.dpdt()
Definition at line 365 of file pEqn.H.
References dpdt, and p.
Variable Documentation
Ff1
Ff1 = Df1*snGradAlpha1 + Ff
Definition at line 54 of file pEqn.H.
Referenced by while().
Ff2
Ff2 = -Df2*snGradAlpha1 - Ff
Definition at line 55 of file pEqn.H.
Referenced by while().
K1
K1 = 0.5*magSqr(U1)
Definition at line 361 of file pEqn.H.
K2
K2 = 0.5*magSqr(U2)
Definition at line 362 of file pEqn.H.