OpenFOAM: applications/solvers/multiphase/multiphaseEulerFoam/UEqns.H File Reference
UEqns.H File Reference
Functions
PtrList< fvVectorMatrix > UEqns (fluid.phases().size())
autoPtr< multiphaseSystem::dragCoeffFields > dragCoeffs (fluid.dragCoeffs())
for (phaseModel &phase :fluid.phases())
Variables
label phasei = 0
Function Documentation
UEqns()
PtrList< fvVectorMatrix > UEqns (fluid. phases).size()
Referenced by for(), forAll(), and while().
dragCoeffs()
autoPtr< multiphaseSystem::dragCoeffFields > dragCoeffs (fluid. dragCoeffs())
Referenced by multiphaseSystem::dragCoeff().
for()
for (phaseModel &phase :fluid. phases())
Definition at line 7 of file UEqns.H.
References alpha, fluid, mesh, MRF, phasei, T, turbulence, U, and UEqns().
Variable Documentation
phasei
label phasei = 0
Definition at line 6 of file UEqns.H.
Referenced by for().