OpenFOAM: applications/solvers/multiphase/cavitatingFoam/cavitatingDyMFoam/correctPhi.H File Reference
correctPhi.H File Reference
Functions
correctUphiBCs (U, phi)
surfaceScalarField rhof (fvc::interpolate(rho, "div(phi,rho)"))
dimensionedScalar rAUf ("rAUf", dimTime, 1.0)
mesh setFluxRequired (pcorr.name())
while (pimple.correctNonOrthogonal())
Function Documentation
correctUphiBCs()
correctUphiBCs (U , phi)
Referenced by Foam::CorrectPhi(), and Foam::CorrectPhi().
rhof()
surfaceScalarField rhof (fvc::interpolate(rho, "div(phi,rho)"))
Referenced by fanMomentumSource::addSup(), MUCSheterogeneousRate< CloudType >::calculate(), hydrostaticPressure::calculateAndWrite(), contactAngleForce::correct(), if(), kinematicSingleLayer::solveThickness(), humidityTemperatureCoupledMixedFvPatchScalarField::updateCoeffs(), and while().
rAUf()
dimensionedScalar rAUf ("rAUf" , dimTime , 1. 0)
setFluxRequired()
mesh setFluxRequired (pcorr. name())
while()
while (pimple. correctNonOrthogonal())
Definition at line 24 of file correctPhi.H.
References pcorr(), phi, pimple, rAUf(), rho, and rhof().