OpenFOAM: Foam::fam Namespace Reference
Foam::fam Namespace Reference
Functions
template<class Type >
tmp< faMatrix< Type > > d2dt2 (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > d2dt2 (const dimensionedScalar &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > d2dt2 (const areaScalarField &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > ddt (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > ddt (const dimensionedScalar &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > ddt (const areaScalarField &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > div (const edgeScalarField &flux, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > div (const tmp< edgeScalarField > &tflux, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > div (const edgeScalarField &flux, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > div (const tmp< edgeScalarField > &tflux, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > laplacian (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > laplacian (const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > laplacian (const dimensionedScalar &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > laplacian (const dimensionedScalar &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > laplacian (const areaScalarField &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > laplacian (const areaScalarField &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > laplacian (const tmp< areaScalarField > &tgamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > laplacian (const tmp< areaScalarField > &tgamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > ndiv (const edgeScalarField &flux, GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > ndiv (const tmp< edgeScalarField > &tflux, GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > ndiv (const edgeScalarField &flux, GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > ndiv (const tmp< edgeScalarField > &tflux, GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
zeroField Su (const Foam::zero, const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< faMatrix< Type > > Su (const dimensioned< Type > &su, const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< faMatrix< Type > > Su (const DimensionedField< Type, areaMesh > &su, const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< faMatrix< Type > > Su (const tmp< DimensionedField< Type, areaMesh > > &, const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< faMatrix< Type > > Su (const tmp< GeometricField< Type, faPatchField, areaMesh > > &, const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
zeroField Sp (const Foam::zero, const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< faMatrix< Type > > Sp (const dimensionedScalar &sp, const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< faMatrix< Type > > Sp (const DimensionedField< scalar, areaMesh > &sp, const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< faMatrix< Type > > Sp (const tmp< DimensionedField< scalar, areaMesh > > &, const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< faMatrix< Type > > Sp (const tmp< GeometricField< scalar, faPatchField, areaMesh > > &, const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
zeroField SuSp (const Foam::zero, const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< faMatrix< Type > > SuSp (const dimensionedScalar &susp, const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< faMatrix< Type > > SuSp (const DimensionedField< scalar, areaMesh > &susp, const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< faMatrix< Type > > SuSp (const tmp< DimensionedField< scalar, areaMesh > > &, const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< faMatrix< Type > > SuSp (const tmp< areaScalarField > &, const GeometricField< Type, faPatchField, areaMesh > &)
template<>
tmp< faMatrix< scalar > > div (const edgeScalarField &flux, const GeometricField< scalar, faPatchField, areaMesh > &vf, const word &name)
template<>
tmp< faMatrix< scalar > > div (const edgeScalarField &flux, const GeometricField< scalar, faPatchField, areaMesh > &vf, const word &name)
Function Documentation
d2dt2() [1/3]
template<class Type > tmp< faMatrix< Type > > d2dt2 (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 39 of file famD2dt2.C.
References faD2dt2Scheme< Type >::New().
Referenced by KirchhoffShell::solveDisplacement().
d2dt2() [2/3]
template<class Type > tmp< faMatrix< Type > > d2dt2 (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 53 of file famD2dt2.C.
References faD2dt2Scheme< Type >::New(), and rho.
d2dt2() [3/3]
template<class Type > tmp< faMatrix< Type > > d2dt2 (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 71 of file famD2dt2.C.
References faD2dt2Scheme< Type >::New(), and rho.
ddt() [1/3]
template<class Type > tmp< faMatrix< Type > > ddt (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 40 of file famDdt.C.
References faDdtScheme< Type >::New().
Referenced by kinematicThinFilm::evolveRegion(), KirchhoffShell::solveDisplacement(), and thermalShell::solveEnergy().
ddt() [2/3]
template<class Type > tmp< faMatrix< Type > > ddt (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 55 of file famDdt.C.
References faDdtScheme< Type >::New(), and rho.
ddt() [3/3]
template<class Type > tmp< faMatrix< Type > > ddt (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 74 of file famDdt.C.
References faDdtScheme< Type >::New(), and rho.
div() [1/6]
template<class Type > tmp< faMatrix< Type > > div (const edgeScalarField & flux, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 40 of file famDiv.C.
References convectionScheme< Type >::facDiv(), convectionScheme< Type >::famDiv(), M, n, and Foam::name().
Referenced by div(), div(), div(), and kinematicThinFilm::evolveRegion().
div() [2/6]
template<class Type > tmp< faMatrix< Type > > div (const tmp< edgeScalarField > & tflux, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 79 of file famDiv.C.
References PtrList< T >::clear(), div(), and Foam::name().
div() [3/6]
template<class Type > tmp< faMatrix< Type > > div (const edgeScalarField & flux, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 95 of file famDiv.C.
References div().
div() [4/6]
template<class Type > tmp< faMatrix< Type > > div (const tmp< edgeScalarField > & tflux, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 106 of file famDiv.C.
References PtrList< T >::clear(), and div().
laplacian() [1/8]
template<class Type > tmp< faMatrix< Type > > laplacian (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 41 of file famLaplacian.C.
References Foam::dimless, laplacian(), and IOobjectOption::NO_READ.
Referenced by jouleHeatingSource::addSup(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), sensitivitySurface::smoothSensitivities(), and thermalShell::solveEnergy().
laplacian() [2/8]
template<class Type > tmp< faMatrix< Type > > laplacian (const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 65 of file famLaplacian.C.
References Foam::dimless, laplacian(), Foam::name(), and IOobjectOption::NO_READ.
laplacian() [3/8]
template<class Type > tmp< faMatrix< Type > > laplacian (const dimensionedScalar & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 90 of file famLaplacian.C.
References gamma, laplacian(), and IOobjectOption::NO_READ.
laplacian() [4/8]
template<class Type > tmp< faMatrix< Type > > laplacian (const dimensionedScalar & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 115 of file famLaplacian.C.
References gamma, laplacian(), Foam::name(), and IOobjectOption::NO_READ.
laplacian() [5/8]
template<class Type > tmp< faMatrix< Type > > laplacian (const areaScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 141 of file famLaplacian.C.
References gamma, and laplacian().
laplacian() [6/8]
template<class Type > tmp< faMatrix< Type > > laplacian (const areaScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 158 of file famLaplacian.C.
References gamma, Foam::name(), and laplacianScheme< Type >::New().
laplacian() [7/8]
template<class Type > tmp< faMatrix< Type > > laplacian (const tmp< areaScalarField > & tgamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 175 of file famLaplacian.C.
References PtrList< T >::clear(), and laplacian().
laplacian() [8/8]
template<class Type > tmp< faMatrix< Type > > laplacian (const tmp< areaScalarField > & tgamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 189 of file famLaplacian.C.
References PtrList< T >::clear(), laplacian(), and Foam::name().
ndiv() [1/4]
template<class Type > tmp< faMatrix< Type > > ndiv (const edgeScalarField & flux, GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 40 of file famNDiv.C.
References Foam::name(), and convectionScheme< Type >::New().
Referenced by ndiv(), ndiv(), and ndiv().
ndiv() [2/4]
template<class Type > tmp< faMatrix< Type > > ndiv (const tmp< edgeScalarField > & tflux, GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 58 of file famNDiv.C.
References PtrList< T >::clear(), Foam::name(), and ndiv().
ndiv() [3/4]
template<class Type > tmp< faMatrix< Type > > ndiv (const edgeScalarField & flux, GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 74 of file famNDiv.C.
References ndiv().
ndiv() [4/4]
template<class Type > tmp< faMatrix< Type > > ndiv (const tmp< edgeScalarField > & tflux, GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 86 of file famNDiv.C.
References PtrList< T >::clear(), and ndiv().
Su() [1/5]
template<class Type > zeroField Su (const Foam::zero , const GeometricField< Type, faPatchField, areaMesh > &)
Su() [2/5]
template<class Type > tmp< faMatrix< Type > > Su (const dimensioned< Type > & su, const GeometricField< Type, faPatchField, areaMesh > &)
Su() [3/5]
template<class Type > tmp< faMatrix< Type > > Su (const DimensionedField< Type, areaMesh > & su, const GeometricField< Type, faPatchField, areaMesh > &)
Su() [4/5]
template<class Type > tmp< faMatrix< Type > > Su (const tmp< DimensionedField< Type, areaMesh > > & , const GeometricField< Type, faPatchField, areaMesh > &)
Su() [5/5]
template<class Type > tmp< faMatrix< Type > > Su (const tmp< GeometricField< Type, faPatchField, areaMesh > > & , const GeometricField< Type, faPatchField, areaMesh > &)
Sp() [1/5]
template<class Type > zeroField Sp (const Foam::zero , const GeometricField< Type, faPatchField, areaMesh > &)
Referenced by contactHeatFluxSource::addSup(), filmTurbulenceModel::primaryRegionFriction(), sensitivitySurface::smoothSensitivities(), and laminar::wallFriction().
Sp() [2/5]
template<class Type > tmp< faMatrix< Type > > Sp (const dimensionedScalar & sp, const GeometricField< Type, faPatchField, areaMesh > &)
Sp() [3/5]
template<class Type > tmp< faMatrix< Type > > Sp (const DimensionedField< scalar, areaMesh > & sp, const GeometricField< Type, faPatchField, areaMesh > &)
Sp() [4/5]
template<class Type > tmp< faMatrix< Type > > Sp (const tmp< DimensionedField< scalar, areaMesh > > & , const GeometricField< Type, faPatchField, areaMesh > &)
Sp() [5/5]
template<class Type > tmp< faMatrix< Type > > Sp (const tmp< GeometricField< scalar, faPatchField, areaMesh > > & , const GeometricField< Type, faPatchField, areaMesh > &)
SuSp() [1/5]
template<class Type > zeroField SuSp (const Foam::zero , const GeometricField< Type, faPatchField, areaMesh > &)
Referenced by externalHeatFluxSource::addSup().
SuSp() [2/5]
template<class Type > tmp< faMatrix< Type > > SuSp (const dimensionedScalar & susp, const GeometricField< Type, faPatchField, areaMesh > &)
SuSp() [3/5]
template<class Type > tmp< faMatrix< Type > > SuSp (const DimensionedField< scalar, areaMesh > & susp, const GeometricField< Type, faPatchField, areaMesh > &)
SuSp() [4/5]
template<class Type > tmp< faMatrix< Type > > SuSp (const tmp< DimensionedField< scalar, areaMesh > > & , const GeometricField< Type, faPatchField, areaMesh > &)
SuSp() [5/5]
template<class Type > tmp< faMatrix< Type > > SuSp (const tmp< areaScalarField > & , const GeometricField< Type, faPatchField, areaMesh > &)
div() [5/6]
template<> tmp< faMatrix< scalar > > div (const edgeScalarField & flux, const GeometricField< scalar, faPatchField, areaMesh > & vf, const word & name)
Definition at line 40 of file vectorFamDiv.C.
References Foam::name(), and convectionScheme< Type >::New().
div() [6/6]
template<> tmp< faMatrix< scalar > > div (const edgeScalarField & flux, const GeometricField< scalar, faPatchField, areaMesh > & vf, const word & name)
Definition at line 40 of file vectorFamDiv.C.
References Foam::name(), and convectionScheme< Type >::New().