OpenFOAM: Foam::fv Namespace Reference
Foam::fv Namespace Reference
Namespace for finite-volume.
Namespaces
namespace gradientLimiters
Classes
class acousticDampingSource
Applies sources on velocity (i.e. U) within a specified region to enable acoustic damping.
class actuationDiskSource
Applies sources on velocity (i.e. U) within a specified region to enable actuator disk models for aero/hydro thrust loading of horizontal axis turbines on surrounding flow field in terms of energy conversion processes.
class atmAmbientTurbSource
Applies sources on k and either epsilon or omega to prevent them droping below a specified ambient value for atmospheric boundary layer modelling. Such adjustment reportedly increases numerical stability for very stable atmospheric stability conditions, and prevents nonphysical oscillations in regions of low shear at higher altitudes.
class atmBuoyancyTurbSource
Applies sources on k and either epsilon or omega to incorporate effects of buoyancy for atmospheric boundary layer modelling.
class atmCoriolisUSource
Applies corrections to incorporate the horizontal and vertical components of the Coriolis force for which the rotating frame is Earth.
class atmLengthScaleTurbSource
Applies sources on either epsilon or omega to correct mixing-length scale estimations for atmospheric boundary layer modelling.
class atmNutSource
Adds/subtracts a given artificial turbulent viscosity field to/from nut for atmospheric boundary layer modelling.
class atmPlantCanopyTSource
Applies sources on temperature, i.e. T, to incorporate effects of plant canopy for atmospheric boundary layer modelling.
class atmPlantCanopyTurbSource
Applies sources on either epsilon or omega to incorporate effects of plant canopy for atmospheric boundary layer modelling.
class atmPlantCanopyUSource
Applies sources on velocity (i.e. U) to incorporate effects of plant canopy for atmospheric boundary layer modelling.
class backwardDdtScheme
Second-order backward-differencing ddt using the current and two previous time-step values.
class boundedConvectionScheme
Bounded form of the selected convection scheme.
class boundedDdtScheme
Bounded form of the selected ddt scheme.
class buoyancyEnergy
Applies buoyancy energy sources (i.e. Sb) to the energy equation for compressible flows.
class buoyancyForce
Applies buoyancy force sources (i.e. Sf) to the momentum equation for incompressible and compressible flows.
class buoyancyTurbSource
Applies sources on turbulent kinetic energy (i.e. k) and either turbulent kinetic energy dissipation rate (i.e. epsilon) or specific dissipation rate (i.e. omega) to incorporate effects of buoyancy on turbulence in incompressible and compressible flows.
class cellLimitedGrad
cellLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
class cellMDLimitedGrad
cellMDLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
class cellSetOption
Intermediate abstract class for handling cell-set options for the derived fvOptions.
class CentredFitSnGradScheme
class CodedSource
class CoEulerDdtScheme
Courant number limited first-order Euler implicit/explicit ddt.
class constantHeatTransfer
Applies a constant heat transfer model for inter-region heat exchanges.
class convectionScheme
Abstract base class for convection schemes.
class correctedSnGrad
Surface gradient scheme with full explicit non-orthogonal correction.
class CrankNicolsonDdtScheme
Second-oder Crank-Nicolson implicit ddt using the current and previous time-step fields as well as the previous time-step ddt.
class d2dt2Scheme
Abstract base class for finite volume d2dt2 schemes.
class ddtScheme
Abstract base class for ddt schemes.
class ddtSchemeBase
Non-templated base class for ddt schemes.
class directionalPressureGradientExplicitSource
Applies an explicit pressure gradient source in such a way to deflect the flow towards an specific direction (flowDir). Alternatively add an extra pressure drop in the flowDir direction using a model.
class divScheme
Abstract base class for div schemes.
class EulerD2dt2Scheme
First-order Euler implicit d2dt2 using the current and two previous time-step values.
class EulerDdtScheme
Basic first-order Euler implicit/explicit ddt using only the current and previous time-step values.
class explicitPorositySource
Applies an explicit porosity source to the momentum equation within a specified region.
class faceCorrectedSnGrad
Surface gradient scheme with full explicit non-orthogonal correction.
class faceLimitedGrad
faceLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
class faceMDLimitedGrad
faceMDLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
class fanMomentumSource
This source term models the action of a fan on the flow. It calculates flow rate through a set of upstream faces of encompassing the cell zone. The set of upstream faces is automatically calculated based on the flow direction and the surrounding face zone. Based on the flow rate, the pressure gradient is calculated based on the fan pressure curve and the thickness of the fan (measurement section). The pressure gradient is then added to the momentum equation.
class fixedTemperatureConstraint
Constrain temperature equation (i.e. T) with a given set of fixed values within a specified region.
class FixedValueConstraint
Constrain values of given fields of Type with a given maximum value within a specified region, where <Type>=Scalar/Vector/SphericalTensor/SymmTensor/Tensor.
class fourthGrad
Second-order gradient scheme using least-squares.
class gaussConvectionScheme
Basic second-order convection using face-gradients and Gauss' theorem.
class gaussDivScheme
Basic second-order div using face-gradients and Gauss' theorem.
class gaussGrad
Basic second-order gradient scheme using face-interpolation and Gauss' theorem.
class gaussLaplacianScheme
Basic second-order laplacian using face-gradients and Gauss' theorem.
class gradScheme
Abstract base class for gradient schemes.
class heatExchangerSource
Heat exchanger source model for compressible flows, where the heat exchanger is modelled as an energy source using a selection of cells.
class interRegionExplicitPorositySource
Applies inter-region explicit porosity source.
class interRegionHeatTransferModel
Intermediate class for handling inter-region heat exchanges.
class interRegionOption
Intermediate class for handling inter-region exchanges.
class iterativeGaussGrad
A second-order gradient scheme using face-interpolation, Gauss' theorem and iterative skew correction.
class jouleHeatingSource
Evolves an electrical potential equation.
class laplacianScheme
Abstract base class for laplacian schemes.
class leastSquaresGrad
Second-order gradient scheme using least-squares.
class LeastSquaresGrad
Gradient calculated using weighted least-squares on an arbitrary stencil. The stencil type is provided via a template argument and any cell-based stencil is supported:
class LeastSquaresVectors
Least-squares gradient scheme vectors.
class limitedSnGrad
Surface gradient scheme with limited explicit non-orthogonal correction.
class limitTemperature
Corrects temperature field (i.e. T) within a specified region by applying limits between a given minimum and maximum.
class limitTurbulenceViscosity
Corrects turbulence viscosity field (e.g. nut) within a specified region by applying a maximum limit, set according to a coefficient multiplied by the laminar viscosity:
class limitVelocity
Corrects velocity field (i.e. T) within a specified region by applying a given maximum velocity magnitude limit.
class localEulerDdt
class localEulerDdtScheme
Local time-step first-order Euler implicit/explicit ddt.
class meanVelocityForce
Applies the force within a specified region to maintain the specified mean velocity for incompressible flows.
class multiphaseMangrovesSource
class multiphaseMangrovesTurbulenceModel
class multiphaseStabilizedTurbulence
Applies corrections to the turbulent kinetic energy equation (i.e. k) and turbulent viscosity field (i.e. nut) for incompressible multiphase flow cases.
class multivariateGaussConvectionScheme
Basic second-order convection using face-gradients and Gauss' theorem.
class option
Base abstract class for handling finite volume options (i.e. fvOption).
class optionList
List of finite volume options.
class options
Finite-volume options.
class orthogonalSnGrad
Surface gradient scheme with no non-orthogonal correction.
class patchCellsSource
Source defined by a boundary condition applied to cells next to patches. This fvOption needs to be used with a boundarySourcePatch type of boundary condition (e.g. speciesSorption and enthalpySorption.)
class patchMeanVelocityForce
Applies the force over the specified patch to maintain the specified mean velocity for incompressible flows.
class PhaseLimitStabilization
Stabilization source for phase transport equations of Type, where <Type>=Scalar/Vector/SphericalTensor/SymmTensor/Tensor.
class radialActuationDiskSource
Applies sources on velocity field (i.e. U) within a specified region to enable actuator disk models with radial thrust distribution for aero/hydro thrust loading of horizontal axis turbines on surrounding flow field in terms of energy conversion processes.
class radiation
Applies radiation sources (i.e. Sh) to the energy equation for compressible flows.
class relaxedNonOrthoGaussLaplacianScheme
Basic second-order laplacian using face-gradients and Gauss' theorem.
class relaxedSnGrad
Surface gradient scheme with under-/over-relaxed full or limited explicit non-orthogonal correction.
class rotorDiskSource
Applies cell-based momentum sources on velocity (i.e. U) within a specified cylindrical region to approximate the mean effects of rotor forces.
class SemiImplicitSource
Applies semi-implicit source within a specified region for Type, where <Type>=Scalar/Vector/SphericalTensor/SymmTensor/Tensor. The source rate coefficients are specified as pairs of Su-Sp coefficients, i.e.:
class skewCorrectedSnGrad
Surface gradient scheme with skewness and full explicit non-orthogonal corrections.
class SLTSDdtScheme
Stabilised local time-step first-order Euler implicit/explicit ddt. The time-step is adjusted locally so that an advective equations remains diagonally dominant.
class snGradScheme
Abstract base class for runtime selected snGrad surface normal gradient schemes.
class solidificationMeltingSource
This source is designed to model the effect of solidification and melting processes, e.g. windhield defrosting, within a specified region. The phase change occurs at the melting temperature, Tmelt.
class steadyStateD2dt2Scheme
SteadyState d2dt2 which returns 0.
class steadyStateDdtScheme
SteadyState implicit/explicit ddt which returns 0.
class tabulatedAccelerationSource
Solid-body 6-DoF acceleration source.
class tabulatedHeatTransfer
Applies a tabulated heat transfer model for inter-region heat exchanges.
class tabulatedNTUHeatTransfer
Applies a tabulated heat transfer model for inter-region heat exchanges. The heat flux is calculated based on the Number of Thermal Units (NTU).
class uncorrectedSnGrad
Surface gradient scheme with no non-orthogonal correction.
class variableHeatTransfer
Applies a variable heat transfer model depending on local values for inter-region heat exchanges.
class velocityDampingConstraint
Constrain given velocity fields to dampen velocity fluctuations exceeding a given value within a specified region.
class viscousDissipation
Applies a viscous dissipation energy source to the energy equation.
class VoFSolidificationMeltingSource
Solidification and melting model for VoF simulations.
Typedefs
typedef LeastSquaresGrad< Foam::scalar, Foam::centredCPCCellToCellStencilObject > LeastSquaresGradscalarcentredCPCCellToCellStencilObject_
typedef LeastSquaresGrad< Foam::vector, Foam::centredCPCCellToCellStencilObject > LeastSquaresGradvectorcentredCPCCellToCellStencilObject_
typedef LeastSquaresGrad< Foam::scalar, Foam::centredCECCellToCellStencilObject > LeastSquaresGradscalarcentredCECCellToCellStencilObject_
typedef LeastSquaresGrad< Foam::vector, Foam::centredCECCellToCellStencilObject > LeastSquaresGradvectorcentredCECCellToCellStencilObject_
typedef laplacianScheme< scalar, scalar > laplacianSchemescalarscalar
typedef laplacianScheme< scalar, symmTensor > laplacianSchemescalarsymmTensor
typedef laplacianScheme< scalar, tensor > laplacianSchemescalartensor
typedef laplacianScheme< vector, scalar > laplacianSchemevectorscalar
typedef laplacianScheme< vector, symmTensor > laplacianSchemevectorsymmTensor
typedef laplacianScheme< vector, tensor > laplacianSchemevectortensor
typedef laplacianScheme< sphericalTensor, scalar > laplacianSchemesphericalTensorscalar
typedef laplacianScheme< sphericalTensor, symmTensor > laplacianSchemesphericalTensorsymmTensor
typedef laplacianScheme< sphericalTensor, tensor > laplacianSchemesphericalTensortensor
typedef laplacianScheme< symmTensor, scalar > laplacianSchemesymmTensorscalar
typedef laplacianScheme< symmTensor, symmTensor > laplacianSchemesymmTensorsymmTensor
typedef laplacianScheme< symmTensor, tensor > laplacianSchemesymmTensortensor
typedef laplacianScheme< tensor, scalar > laplacianSchemetensorscalar
typedef laplacianScheme< tensor, symmTensor > laplacianSchemetensorsymmTensor
typedef laplacianScheme< tensor, tensor > laplacianSchemetensortensor
Functions
defineTypeNameAndDebug (atmAmbientTurbSource, 0)
addToRunTimeSelectionTable (option, atmAmbientTurbSource, dictionary)
defineTypeNameAndDebug (atmBuoyancyTurbSource, 0)
addToRunTimeSelectionTable (option, atmBuoyancyTurbSource, dictionary)
defineTypeNameAndDebug (atmCoriolisUSource, 0)
addToRunTimeSelectionTable (option, atmCoriolisUSource, dictionary)
defineTypeNameAndDebug (atmLengthScaleTurbSource, 0)
addToRunTimeSelectionTable (option, atmLengthScaleTurbSource, dictionary)
defineTypeNameAndDebug (atmNutSource, 0)
addToRunTimeSelectionTable (option, atmNutSource, dictionary)
defineTypeNameAndDebug (atmPlantCanopyTSource, 0)
addToRunTimeSelectionTable (option, atmPlantCanopyTSource, dictionary)
defineTypeNameAndDebug (atmPlantCanopyTurbSource, 0)
addToRunTimeSelectionTable (option, atmPlantCanopyTurbSource, dictionary)
defineTypeNameAndDebug (atmPlantCanopyUSource, 0)
addToRunTimeSelectionTable (option, atmPlantCanopyUSource, dictionary)
defineTypeNameAndDebug (option, 0)
defineRunTimeSelectionTable (option, dictionary)
defineTypeNameAndDebug (optionList, 0)
defineTypeNameAndDebug (options, 0)
defineTemplateRunTimeSelectionTable (convectionScheme< scalar >, Istream)
defineTemplateRunTimeSelectionTable (convectionScheme< scalar >, Multivariate)
defineTemplateRunTimeSelectionTable (convectionScheme< vector >, Istream)
defineTemplateRunTimeSelectionTable (convectionScheme< vector >, Multivariate)
defineTemplateRunTimeSelectionTable (convectionScheme< sphericalTensor >, Istream)
defineTemplateRunTimeSelectionTable (convectionScheme< sphericalTensor >, Multivariate)
defineTemplateRunTimeSelectionTable (convectionScheme< symmTensor >, Istream)
defineTemplateRunTimeSelectionTable (convectionScheme< symmTensor >, Multivariate)
defineTemplateRunTimeSelectionTable (convectionScheme< tensor >, Istream)
defineTemplateRunTimeSelectionTable (convectionScheme< tensor >, Multivariate)
defineTemplateRunTimeSelectionTable (d2dt2Scheme< scalar >, Istream)
defineTemplateRunTimeSelectionTable (d2dt2Scheme< vector >, Istream)
defineTemplateRunTimeSelectionTable (d2dt2Scheme< sphericalTensor >, Istream)
defineTemplateRunTimeSelectionTable (d2dt2Scheme< symmTensor >, Istream)
defineTemplateRunTimeSelectionTable (d2dt2Scheme< tensor >, Istream)
template<class Type >
const FieldField< fvPatchField, Type > & ff (const FieldField< fvPatchField, Type > &bf)
defineTemplateRunTimeSelectionTable (ddtScheme< scalar >, Istream)
defineTemplateRunTimeSelectionTable (ddtScheme< vector >, Istream)
defineTemplateRunTimeSelectionTable (ddtScheme< sphericalTensor >, Istream)
defineTemplateRunTimeSelectionTable (ddtScheme< symmTensor >, Istream)
defineTemplateRunTimeSelectionTable (ddtScheme< tensor >, Istream)
defineTemplateRunTimeSelectionTable (divScheme< vector >, Istream)
defineTemplateRunTimeSelectionTable (divScheme< sphericalTensor >, Istream)
defineTemplateRunTimeSelectionTable (divScheme< symmTensor >, Istream)
defineTemplateRunTimeSelectionTable (divScheme< tensor >, Istream)
NamespaceName ("fv")
defineTemplateRunTimeSelectionTable (gradScheme< scalar >, Istream)
defineTemplateRunTimeSelectionTable (gradScheme< vector >, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemescalarscalar, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemescalarsymmTensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemescalartensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemevectorscalar, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemevectorsymmTensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemevectortensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemesphericalTensorscalar, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemesphericalTensorsymmTensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemesphericalTensortensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemesymmTensorscalar, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemesymmTensorsymmTensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemesymmTensortensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemetensorscalar, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemetensorsymmTensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemetensortensor, Istream)
defineTemplateRunTimeSelectionTable (snGradScheme< scalar >, Mesh)
defineTemplateRunTimeSelectionTable (snGradScheme< vector >, Mesh)
defineTemplateRunTimeSelectionTable (snGradScheme< sphericalTensor >, Mesh)
defineTemplateRunTimeSelectionTable (snGradScheme< symmTensor >, Mesh)
defineTemplateRunTimeSelectionTable (snGradScheme< tensor >, Mesh)
defineTypeNameAndDebug (cellSetOption, 0)
defineTypeNameAndDebug (fixedTemperatureConstraint, 0)
addToRunTimeSelectionTable (option, fixedTemperatureConstraint, dictionary)
defineTypeNameAndDebug (velocityDampingConstraint, 0)
addToRunTimeSelectionTable (option, velocityDampingConstraint, dictionary)
defineTypeNameAndDebug (limitTemperature, 0)
addToRunTimeSelectionTable (option, limitTemperature, dictionary)
defineTypeNameAndDebug (limitTurbulenceViscosity, 0)
addToRunTimeSelectionTable (option, limitTurbulenceViscosity, dictionary)
defineTypeNameAndDebug (limitVelocity, 0)
addToRunTimeSelectionTable (option, limitVelocity, dictionary)
defineTypeNameAndDebug (interRegionOption, 0)
defineTypeNameAndDebug (acousticDampingSource, 0)
addToRunTimeSelectionTable (option, acousticDampingSource, dictionary)
defineTypeNameAndDebug (actuationDiskSource, 0)
addToRunTimeSelectionTable (option, actuationDiskSource, dictionary)
defineTypeNameAndDebug (buoyancyEnergy, 0)
addToRunTimeSelectionTable (option, buoyancyEnergy, dictionary)
defineTypeNameAndDebug (buoyancyForce, 0)
addToRunTimeSelectionTable (option, buoyancyForce, dictionary)
defineTypeNameAndDebug (buoyancyTurbSource, 0)
addToRunTimeSelectionTable (option, buoyancyTurbSource, dictionary)
defineTypeNameAndDebug (directionalPressureGradientExplicitSource, 0)
addToRunTimeSelectionTable (option, directionalPressureGradientExplicitSource, dictionary)
defineTypeNameAndDebug (explicitPorositySource, 0)
addToRunTimeSelectionTable (option, explicitPorositySource, dictionary)
defineTypeNameAndDebug (fanMomentumSource, 0)
addToRunTimeSelectionTable (option, fanMomentumSource, dictionary)
defineTypeNameAndDebug (heatExchangerSource, 0)
addToRunTimeSelectionTable (option, heatExchangerSource, dictionary)
defineTypeNameAndDebug (jouleHeatingSource, 0)
addToRunTimeSelectionTable (option, jouleHeatingSource, dictionary)
defineTypeNameAndDebug (meanVelocityForce, 0)
addToRunTimeSelectionTable (option, meanVelocityForce, dictionary)
defineTypeNameAndDebug (patchMeanVelocityForce, 0)
addToRunTimeSelectionTable (option, patchMeanVelocityForce, dictionary)
defineTypeNameAndDebug (multiphaseStabilizedTurbulence, 0)
addToRunTimeSelectionTable (option, multiphaseStabilizedTurbulence, dictionary)
defineTypeNameAndDebug (patchCellsSource, 0)
addToRunTimeSelectionTable (option, patchCellsSource, dictionary)
defineTypeNameAndDebug (radialActuationDiskSource, 0)
addToRunTimeSelectionTable (option, radialActuationDiskSource, dictionary)
defineTypeNameAndDebug (rotorDiskSource, 0)
addToRunTimeSelectionTable (option, rotorDiskSource, dictionary)
defineTypeNameAndDebug (solidificationMeltingSource, 0)
addToRunTimeSelectionTable (option, solidificationMeltingSource, dictionary)
defineTypeNameAndDebug (tabulatedAccelerationSource, 0)
addToRunTimeSelectionTable (option, tabulatedAccelerationSource, dictionary)
defineTypeNameAndDebug (viscousDissipation, 0)
addToRunTimeSelectionTable (option, viscousDissipation, dictionary)
defineTypeNameAndDebug (interRegionExplicitPorositySource, 0)
addToRunTimeSelectionTable (option, interRegionExplicitPorositySource, dictionary)
defineTypeNameAndDebug (constantHeatTransfer, 0)
addToRunTimeSelectionTable (option, constantHeatTransfer, dictionary)
defineTypeNameAndDebug (interRegionHeatTransferModel, 0)
defineTypeNameAndDebug (tabulatedHeatTransfer, 0)
addToRunTimeSelectionTable (option, tabulatedHeatTransfer, dictionary)
defineTypeNameAndDebug (tabulatedNTUHeatTransfer, 0)
addToRunTimeSelectionTable (option, tabulatedNTUHeatTransfer, dictionary)
defineTypeNameAndDebug (variableHeatTransfer, 0)
addToRunTimeSelectionTable (option, variableHeatTransfer, dictionary)
defineTypeNameAndDebug (radiation, 0)
addToRunTimeSelectionTable (option, radiation, dictionary)
defineTypeNameAndDebug (multiphaseMangrovesSource, 0)
addToRunTimeSelectionTable (option, multiphaseMangrovesSource, dictionary)
defineTypeNameAndDebug (multiphaseMangrovesTurbulenceModel, 0)
addToRunTimeSelectionTable (option, multiphaseMangrovesTurbulenceModel, dictionary)
Variables
gradScheme< Foam::scalar >::addIstreamConstructorToTable< LeastSquaresGrad< Foam::scalar, Foam::centredCPCCellToCellStencilObject > > addpointCellsLeastSquarescentredCPCCellToCellStencilObjectscalarIstreamConstructorToTable_
gradScheme< Foam::vector >::addIstreamConstructorToTable< LeastSquaresGrad< Foam::vector, Foam::centredCPCCellToCellStencilObject > > addpointCellsLeastSquarescentredCPCCellToCellStencilObjectvectorIstreamConstructorToTable_
gradScheme< Foam::scalar >::addIstreamConstructorToTable< LeastSquaresGrad< Foam::scalar, Foam::centredCECCellToCellStencilObject > > addedgeCellsLeastSquarescentredCECCellToCellStencilObjectscalarIstreamConstructorToTable_
gradScheme< Foam::vector >::addIstreamConstructorToTable< LeastSquaresGrad< Foam::vector, Foam::centredCECCellToCellStencilObject > > addedgeCellsLeastSquarescentredCECCellToCellStencilObjectvectorIstreamConstructorToTable_
gradScheme< scalar >::addIstreamConstructorToTable< cellLimitedGrad< scalar, gradientLimiters::minmod > > addcellLimitedGradscalarminmodIstreamConstructorToTable_
gradScheme< vector >::addIstreamConstructorToTable< cellLimitedGrad< vector, gradientLimiters::minmod > > addcellLimitedGradvectorminmodIstreamConstructorToTable_
gradScheme< scalar >::addIstreamConstructorToTable< cellLimitedGrad< scalar, gradientLimiters::Venkatakrishnan > > addcellLimitedGradscalarVenkatakrishnanIstreamConstructorToTable_
Detailed Description
Namespace for finite-volume.
Typedef Documentation
LeastSquaresGradscalarcentredCPCCellToCellStencilObject_
typedef LeastSquaresGrad<Foam:: scalar , Foam:: centredCPCCellToCellStencilObject > LeastSquaresGradscalarcentredCPCCellToCellStencilObject_
Definition at line 38 of file LeastSquaresGrads.C.
LeastSquaresGradvectorcentredCPCCellToCellStencilObject_
typedef LeastSquaresGrad<Foam:: vector , Foam:: centredCPCCellToCellStencilObject > LeastSquaresGradvectorcentredCPCCellToCellStencilObject_
Definition at line 38 of file LeastSquaresGrads.C.
LeastSquaresGradscalarcentredCECCellToCellStencilObject_
typedef LeastSquaresGrad<Foam:: scalar , Foam:: centredCECCellToCellStencilObject > LeastSquaresGradscalarcentredCECCellToCellStencilObject_
Definition at line 44 of file LeastSquaresGrads.C.
LeastSquaresGradvectorcentredCECCellToCellStencilObject_
typedef LeastSquaresGrad<Foam:: vector , Foam:: centredCECCellToCellStencilObject > LeastSquaresGradvectorcentredCECCellToCellStencilObject_
Definition at line 44 of file LeastSquaresGrads.C.
laplacianSchemescalarscalar
typedef laplacianScheme< scalar , scalar > laplacianSchemescalarscalar
Definition at line 45 of file laplacianSchemes.C.
laplacianSchemescalarsymmTensor
typedef laplacianScheme< scalar , symmTensor > laplacianSchemescalarsymmTensor
Definition at line 45 of file laplacianSchemes.C.
laplacianSchemescalartensor
typedef laplacianScheme< scalar , tensor > laplacianSchemescalartensor
Definition at line 45 of file laplacianSchemes.C.
laplacianSchemevectorscalar
typedef laplacianScheme< vector , scalar > laplacianSchemevectorscalar
Definition at line 46 of file laplacianSchemes.C.
laplacianSchemevectorsymmTensor
typedef laplacianScheme< vector , symmTensor > laplacianSchemevectorsymmTensor
Definition at line 46 of file laplacianSchemes.C.
laplacianSchemevectortensor
typedef laplacianScheme< vector , tensor > laplacianSchemevectortensor
Definition at line 46 of file laplacianSchemes.C.
laplacianSchemesphericalTensorscalar
typedef laplacianScheme< sphericalTensor , scalar > laplacianSchemesphericalTensorscalar
Definition at line 47 of file laplacianSchemes.C.
laplacianSchemesphericalTensorsymmTensor
typedef laplacianScheme< sphericalTensor , symmTensor > laplacianSchemesphericalTensorsymmTensor
Definition at line 47 of file laplacianSchemes.C.
laplacianSchemesphericalTensortensor
typedef laplacianScheme< sphericalTensor , tensor > laplacianSchemesphericalTensortensor
Definition at line 47 of file laplacianSchemes.C.
laplacianSchemesymmTensorscalar
typedef laplacianScheme< symmTensor , scalar > laplacianSchemesymmTensorscalar
Definition at line 48 of file laplacianSchemes.C.
laplacianSchemesymmTensorsymmTensor
typedef laplacianScheme< symmTensor , symmTensor > laplacianSchemesymmTensorsymmTensor
Definition at line 48 of file laplacianSchemes.C.
laplacianSchemesymmTensortensor
typedef laplacianScheme< symmTensor , tensor > laplacianSchemesymmTensortensor
Definition at line 48 of file laplacianSchemes.C.
laplacianSchemetensorscalar
typedef laplacianScheme< tensor , scalar > laplacianSchemetensorscalar
Definition at line 49 of file laplacianSchemes.C.
laplacianSchemetensorsymmTensor
typedef laplacianScheme< tensor , symmTensor > laplacianSchemetensorsymmTensor
Definition at line 49 of file laplacianSchemes.C.
laplacianSchemetensortensor
typedef laplacianScheme< tensor , tensor > laplacianSchemetensortensor
Definition at line 49 of file laplacianSchemes.C.
Function Documentation
defineTypeNameAndDebug() [1/46]
defineTypeNameAndDebug (atmAmbientTurbSource , 0)
addToRunTimeSelectionTable() [1/40]
addToRunTimeSelectionTable (option , atmAmbientTurbSource , dictionary)
defineTypeNameAndDebug() [2/46]
defineTypeNameAndDebug (atmBuoyancyTurbSource , 0)
addToRunTimeSelectionTable() [2/40]
addToRunTimeSelectionTable (option , atmBuoyancyTurbSource , dictionary)
defineTypeNameAndDebug() [3/46]
defineTypeNameAndDebug (atmCoriolisUSource , 0)
addToRunTimeSelectionTable() [3/40]
addToRunTimeSelectionTable (option , atmCoriolisUSource , dictionary)
defineTypeNameAndDebug() [4/46]
defineTypeNameAndDebug (atmLengthScaleTurbSource , 0)
addToRunTimeSelectionTable() [4/40]
addToRunTimeSelectionTable (option , atmLengthScaleTurbSource , dictionary)
defineTypeNameAndDebug() [5/46]
defineTypeNameAndDebug (atmNutSource , 0)
addToRunTimeSelectionTable() [5/40]
addToRunTimeSelectionTable (option , atmNutSource , dictionary)
defineTypeNameAndDebug() [6/46]
defineTypeNameAndDebug (atmPlantCanopyTSource , 0)
addToRunTimeSelectionTable() [6/40]
addToRunTimeSelectionTable (option , atmPlantCanopyTSource , dictionary)
defineTypeNameAndDebug() [7/46]
defineTypeNameAndDebug (atmPlantCanopyTurbSource , 0)
addToRunTimeSelectionTable() [7/40]
addToRunTimeSelectionTable (option , atmPlantCanopyTurbSource , dictionary)
defineTypeNameAndDebug() [8/46]
defineTypeNameAndDebug (atmPlantCanopyUSource , 0)
addToRunTimeSelectionTable() [8/40]
addToRunTimeSelectionTable (option , atmPlantCanopyUSource , dictionary)
defineTypeNameAndDebug() [9/46]
defineTypeNameAndDebug (option , 0)
defineRunTimeSelectionTable()
defineRunTimeSelectionTable (option , dictionary)
defineTypeNameAndDebug() [10/46]
defineTypeNameAndDebug (optionList , 0)
defineTypeNameAndDebug() [11/46]
defineTypeNameAndDebug (options , 0)
defineTemplateRunTimeSelectionTable() [1/46]
defineTemplateRunTimeSelectionTable (convectionScheme< scalar > , Istream)
defineTemplateRunTimeSelectionTable() [2/46]
defineTemplateRunTimeSelectionTable (convectionScheme< scalar > , Multivariate)
defineTemplateRunTimeSelectionTable() [3/46]
defineTemplateRunTimeSelectionTable (convectionScheme< vector > , Istream)
defineTemplateRunTimeSelectionTable() [4/46]
defineTemplateRunTimeSelectionTable (convectionScheme< vector > , Multivariate)
defineTemplateRunTimeSelectionTable() [5/46]
defineTemplateRunTimeSelectionTable (convectionScheme< sphericalTensor > , Istream)
defineTemplateRunTimeSelectionTable() [6/46]
defineTemplateRunTimeSelectionTable (convectionScheme< sphericalTensor > , Multivariate)
defineTemplateRunTimeSelectionTable() [7/46]
defineTemplateRunTimeSelectionTable (convectionScheme< symmTensor > , Istream)
defineTemplateRunTimeSelectionTable() [8/46]
defineTemplateRunTimeSelectionTable (convectionScheme< symmTensor > , Multivariate)
defineTemplateRunTimeSelectionTable() [9/46]
defineTemplateRunTimeSelectionTable (convectionScheme< tensor > , Istream)
defineTemplateRunTimeSelectionTable() [10/46]
defineTemplateRunTimeSelectionTable (convectionScheme< tensor > , Multivariate)
defineTemplateRunTimeSelectionTable() [11/46]
defineTemplateRunTimeSelectionTable (d2dt2Scheme< scalar > , Istream)
defineTemplateRunTimeSelectionTable() [12/46]
defineTemplateRunTimeSelectionTable (d2dt2Scheme< vector > , Istream)
defineTemplateRunTimeSelectionTable() [13/46]
defineTemplateRunTimeSelectionTable (d2dt2Scheme< sphericalTensor > , Istream)
defineTemplateRunTimeSelectionTable() [14/46]
defineTemplateRunTimeSelectionTable (d2dt2Scheme< symmTensor > , Istream)
defineTemplateRunTimeSelectionTable() [15/46]
defineTemplateRunTimeSelectionTable (d2dt2Scheme< tensor > , Istream)
ff()
template<class Type > const FieldField< fvPatchField, Type > & ff (const FieldField< fvPatchField, Type > & bf)
Definition at line 267 of file CrankNicolsonDdtScheme.C.
References ff().
Referenced by ff(), CrankNicolsonDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), and CrankNicolsonDdtScheme< Type >::fvmDdt().
defineTemplateRunTimeSelectionTable() [16/46]
defineTemplateRunTimeSelectionTable (ddtScheme< scalar > , Istream)
defineTemplateRunTimeSelectionTable() [17/46]
defineTemplateRunTimeSelectionTable (ddtScheme< vector > , Istream)
defineTemplateRunTimeSelectionTable() [18/46]
defineTemplateRunTimeSelectionTable (ddtScheme< sphericalTensor > , Istream)
defineTemplateRunTimeSelectionTable() [19/46]
defineTemplateRunTimeSelectionTable (ddtScheme< symmTensor > , Istream)
defineTemplateRunTimeSelectionTable() [20/46]
defineTemplateRunTimeSelectionTable (ddtScheme< tensor > , Istream)
defineTemplateRunTimeSelectionTable() [21/46]
defineTemplateRunTimeSelectionTable (divScheme< vector > , Istream)
defineTemplateRunTimeSelectionTable() [22/46]
defineTemplateRunTimeSelectionTable (divScheme< sphericalTensor > , Istream)
defineTemplateRunTimeSelectionTable() [23/46]
defineTemplateRunTimeSelectionTable (divScheme< symmTensor > , Istream)
defineTemplateRunTimeSelectionTable() [24/46]
defineTemplateRunTimeSelectionTable (divScheme< tensor > , Istream)
NamespaceName()
NamespaceName ("fv")
defineTemplateRunTimeSelectionTable() [25/46]
defineTemplateRunTimeSelectionTable (gradScheme< scalar > , Istream)
defineTemplateRunTimeSelectionTable() [26/46]
defineTemplateRunTimeSelectionTable (gradScheme< vector > , Istream)
defineTemplateRunTimeSelectionTable() [27/46]
defineTemplateRunTimeSelectionTable (laplacianSchemescalarscalar , Istream)
defineTemplateRunTimeSelectionTable() [28/46]
defineTemplateRunTimeSelectionTable (laplacianSchemescalarsymmTensor , Istream)
defineTemplateRunTimeSelectionTable() [29/46]
defineTemplateRunTimeSelectionTable (laplacianSchemescalartensor , Istream)
defineTemplateRunTimeSelectionTable() [30/46]
defineTemplateRunTimeSelectionTable (laplacianSchemevectorscalar , Istream)
defineTemplateRunTimeSelectionTable() [31/46]
defineTemplateRunTimeSelectionTable (laplacianSchemevectorsymmTensor , Istream)
defineTemplateRunTimeSelectionTable() [32/46]
defineTemplateRunTimeSelectionTable (laplacianSchemevectortensor , Istream)
defineTemplateRunTimeSelectionTable() [33/46]
defineTemplateRunTimeSelectionTable (laplacianSchemesphericalTensorscalar , Istream)
defineTemplateRunTimeSelectionTable() [34/46]
defineTemplateRunTimeSelectionTable (laplacianSchemesphericalTensorsymmTensor , Istream)
defineTemplateRunTimeSelectionTable() [35/46]
defineTemplateRunTimeSelectionTable (laplacianSchemesphericalTensortensor , Istream)
defineTemplateRunTimeSelectionTable() [36/46]
defineTemplateRunTimeSelectionTable (laplacianSchemesymmTensorscalar , Istream)
defineTemplateRunTimeSelectionTable() [37/46]
defineTemplateRunTimeSelectionTable (laplacianSchemesymmTensorsymmTensor , Istream)
defineTemplateRunTimeSelectionTable() [38/46]
defineTemplateRunTimeSelectionTable (laplacianSchemesymmTensortensor , Istream)
defineTemplateRunTimeSelectionTable() [39/46]
defineTemplateRunTimeSelectionTable (laplacianSchemetensorscalar , Istream)
defineTemplateRunTimeSelectionTable() [40/46]
defineTemplateRunTimeSelectionTable (laplacianSchemetensorsymmTensor , Istream)
defineTemplateRunTimeSelectionTable() [41/46]
defineTemplateRunTimeSelectionTable (laplacianSchemetensortensor , Istream)
defineTemplateRunTimeSelectionTable() [42/46]
defineTemplateRunTimeSelectionTable (snGradScheme< scalar > , Mesh)
defineTemplateRunTimeSelectionTable() [43/46]
defineTemplateRunTimeSelectionTable (snGradScheme< vector > , Mesh)
defineTemplateRunTimeSelectionTable() [44/46]
defineTemplateRunTimeSelectionTable (snGradScheme< sphericalTensor > , Mesh)
defineTemplateRunTimeSelectionTable() [45/46]
defineTemplateRunTimeSelectionTable (snGradScheme< symmTensor > , Mesh)
defineTemplateRunTimeSelectionTable() [46/46]
defineTemplateRunTimeSelectionTable (snGradScheme< tensor > , Mesh)
defineTypeNameAndDebug() [12/46]
defineTypeNameAndDebug (cellSetOption , 0)
defineTypeNameAndDebug() [13/46]
defineTypeNameAndDebug (fixedTemperatureConstraint , 0)
addToRunTimeSelectionTable() [9/40]
addToRunTimeSelectionTable (option , fixedTemperatureConstraint , dictionary)
defineTypeNameAndDebug() [14/46]
defineTypeNameAndDebug (velocityDampingConstraint , 0)
addToRunTimeSelectionTable() [10/40]
addToRunTimeSelectionTable (option , velocityDampingConstraint , dictionary)
defineTypeNameAndDebug() [15/46]
defineTypeNameAndDebug (limitTemperature , 0)
addToRunTimeSelectionTable() [11/40]
addToRunTimeSelectionTable (option , limitTemperature , dictionary)
defineTypeNameAndDebug() [16/46]
defineTypeNameAndDebug (limitTurbulenceViscosity , 0)
addToRunTimeSelectionTable() [12/40]
addToRunTimeSelectionTable (option , limitTurbulenceViscosity , dictionary)
defineTypeNameAndDebug() [17/46]
defineTypeNameAndDebug (limitVelocity , 0)
addToRunTimeSelectionTable() [13/40]
addToRunTimeSelectionTable (option , limitVelocity , dictionary)
defineTypeNameAndDebug() [18/46]
defineTypeNameAndDebug (interRegionOption , 0)
defineTypeNameAndDebug() [19/46]
defineTypeNameAndDebug (acousticDampingSource , 0)
addToRunTimeSelectionTable() [14/40]
addToRunTimeSelectionTable (option , acousticDampingSource , dictionary)
defineTypeNameAndDebug() [20/46]
defineTypeNameAndDebug (actuationDiskSource , 0)
addToRunTimeSelectionTable() [15/40]
addToRunTimeSelectionTable (option , actuationDiskSource , dictionary)
defineTypeNameAndDebug() [21/46]
defineTypeNameAndDebug (buoyancyEnergy , 0)
addToRunTimeSelectionTable() [16/40]
addToRunTimeSelectionTable (option , buoyancyEnergy , dictionary)
defineTypeNameAndDebug() [22/46]
defineTypeNameAndDebug (buoyancyForce , 0)
addToRunTimeSelectionTable() [17/40]
addToRunTimeSelectionTable (option , buoyancyForce , dictionary)
defineTypeNameAndDebug() [23/46]
defineTypeNameAndDebug (buoyancyTurbSource , 0)
addToRunTimeSelectionTable() [18/40]
addToRunTimeSelectionTable (option , buoyancyTurbSource , dictionary)
defineTypeNameAndDebug() [24/46]
defineTypeNameAndDebug (directionalPressureGradientExplicitSource , 0)
addToRunTimeSelectionTable() [19/40]
addToRunTimeSelectionTable (option , directionalPressureGradientExplicitSource , dictionary)
defineTypeNameAndDebug() [25/46]
defineTypeNameAndDebug (explicitPorositySource , 0)
addToRunTimeSelectionTable() [20/40]
addToRunTimeSelectionTable (option , explicitPorositySource , dictionary)
defineTypeNameAndDebug() [26/46]
defineTypeNameAndDebug (fanMomentumSource , 0)
addToRunTimeSelectionTable() [21/40]
addToRunTimeSelectionTable (option , fanMomentumSource , dictionary)
defineTypeNameAndDebug() [27/46]
defineTypeNameAndDebug (heatExchangerSource , 0)
addToRunTimeSelectionTable() [22/40]
addToRunTimeSelectionTable (option , heatExchangerSource , dictionary)
defineTypeNameAndDebug() [28/46]
defineTypeNameAndDebug (jouleHeatingSource , 0)
addToRunTimeSelectionTable() [23/40]
addToRunTimeSelectionTable (option , jouleHeatingSource , dictionary)
defineTypeNameAndDebug() [29/46]
defineTypeNameAndDebug (meanVelocityForce , 0)
addToRunTimeSelectionTable() [24/40]
addToRunTimeSelectionTable (option , meanVelocityForce , dictionary)
defineTypeNameAndDebug() [30/46]
defineTypeNameAndDebug (patchMeanVelocityForce , 0)
addToRunTimeSelectionTable() [25/40]
addToRunTimeSelectionTable (option , patchMeanVelocityForce , dictionary)
defineTypeNameAndDebug() [31/46]
defineTypeNameAndDebug (multiphaseStabilizedTurbulence , 0)
addToRunTimeSelectionTable() [26/40]
addToRunTimeSelectionTable (option , multiphaseStabilizedTurbulence , dictionary)
defineTypeNameAndDebug() [32/46]
defineTypeNameAndDebug (patchCellsSource , 0)
addToRunTimeSelectionTable() [27/40]
addToRunTimeSelectionTable (option , patchCellsSource , dictionary)
defineTypeNameAndDebug() [33/46]
defineTypeNameAndDebug (radialActuationDiskSource , 0)
addToRunTimeSelectionTable() [28/40]
addToRunTimeSelectionTable (option , radialActuationDiskSource , dictionary)
defineTypeNameAndDebug() [34/46]
defineTypeNameAndDebug (rotorDiskSource , 0)
addToRunTimeSelectionTable() [29/40]
addToRunTimeSelectionTable (option , rotorDiskSource , dictionary)
defineTypeNameAndDebug() [35/46]
defineTypeNameAndDebug (solidificationMeltingSource , 0)
addToRunTimeSelectionTable() [30/40]
addToRunTimeSelectionTable (option , solidificationMeltingSource , dictionary)
defineTypeNameAndDebug() [36/46]
defineTypeNameAndDebug (tabulatedAccelerationSource , 0)
addToRunTimeSelectionTable() [31/40]
addToRunTimeSelectionTable (option , tabulatedAccelerationSource , dictionary)
defineTypeNameAndDebug() [37/46]
defineTypeNameAndDebug (viscousDissipation , 0)
addToRunTimeSelectionTable() [32/40]
addToRunTimeSelectionTable (option , viscousDissipation , dictionary)
defineTypeNameAndDebug() [38/46]
defineTypeNameAndDebug (interRegionExplicitPorositySource , 0)
addToRunTimeSelectionTable() [33/40]
addToRunTimeSelectionTable (option , interRegionExplicitPorositySource , dictionary)
defineTypeNameAndDebug() [39/46]
defineTypeNameAndDebug (constantHeatTransfer , 0)
addToRunTimeSelectionTable() [34/40]
addToRunTimeSelectionTable (option , constantHeatTransfer , dictionary)
defineTypeNameAndDebug() [40/46]
defineTypeNameAndDebug (interRegionHeatTransferModel , 0)
defineTypeNameAndDebug() [41/46]
defineTypeNameAndDebug (tabulatedHeatTransfer , 0)
addToRunTimeSelectionTable() [35/40]
addToRunTimeSelectionTable (option , tabulatedHeatTransfer , dictionary)
defineTypeNameAndDebug() [42/46]
defineTypeNameAndDebug (tabulatedNTUHeatTransfer , 0)
addToRunTimeSelectionTable() [36/40]
addToRunTimeSelectionTable (option , tabulatedNTUHeatTransfer , dictionary)
defineTypeNameAndDebug() [43/46]
defineTypeNameAndDebug (variableHeatTransfer , 0)
addToRunTimeSelectionTable() [37/40]
addToRunTimeSelectionTable (option , variableHeatTransfer , dictionary)
defineTypeNameAndDebug() [44/46]
defineTypeNameAndDebug (radiation , 0)
addToRunTimeSelectionTable() [38/40]
addToRunTimeSelectionTable (option , radiation , dictionary)
defineTypeNameAndDebug() [45/46]
defineTypeNameAndDebug (multiphaseMangrovesSource , 0)
addToRunTimeSelectionTable() [39/40]
addToRunTimeSelectionTable (option , multiphaseMangrovesSource , dictionary)
defineTypeNameAndDebug() [46/46]
defineTypeNameAndDebug (multiphaseMangrovesTurbulenceModel , 0)
addToRunTimeSelectionTable() [40/40]
addToRunTimeSelectionTable (option , multiphaseMangrovesTurbulenceModel , dictionary)
Variable Documentation
addpointCellsLeastSquarescentredCPCCellToCellStencilObjectscalarIstreamConstructorToTable_
gradScheme<Foam:: scalar >::addIstreamConstructorToTable<LeastSquaresGrad<Foam:: scalar , Foam:: centredCPCCellToCellStencilObject > > addpointCellsLeastSquarescentredCPCCellToCellStencilObjectscalarIstreamConstructorToTable_
Definition at line 38 of file LeastSquaresGrads.C.
addpointCellsLeastSquarescentredCPCCellToCellStencilObjectvectorIstreamConstructorToTable_
gradScheme<Foam:: vector >::addIstreamConstructorToTable<LeastSquaresGrad<Foam:: vector , Foam:: centredCPCCellToCellStencilObject > > addpointCellsLeastSquarescentredCPCCellToCellStencilObjectvectorIstreamConstructorToTable_
Definition at line 38 of file LeastSquaresGrads.C.
addedgeCellsLeastSquarescentredCECCellToCellStencilObjectscalarIstreamConstructorToTable_
gradScheme<Foam:: scalar >::addIstreamConstructorToTable<LeastSquaresGrad<Foam:: scalar , Foam:: centredCECCellToCellStencilObject > > addedgeCellsLeastSquarescentredCECCellToCellStencilObjectscalarIstreamConstructorToTable_
Definition at line 44 of file LeastSquaresGrads.C.
addedgeCellsLeastSquarescentredCECCellToCellStencilObjectvectorIstreamConstructorToTable_
gradScheme<Foam:: vector >::addIstreamConstructorToTable<LeastSquaresGrad<Foam:: vector , Foam:: centredCECCellToCellStencilObject > > addedgeCellsLeastSquarescentredCECCellToCellStencilObjectvectorIstreamConstructorToTable_
Definition at line 44 of file LeastSquaresGrads.C.
addcellLimitedGradscalarminmodIstreamConstructorToTable_
gradScheme< scalar >::addIstreamConstructorToTable< cellLimitedGrad < scalar , gradientLimiters:: minmod > > addcellLimitedGradscalarminmodIstreamConstructorToTable_
Definition at line 61 of file cellLimitedGrads.C.
addcellLimitedGradvectorminmodIstreamConstructorToTable_
gradScheme< vector >::addIstreamConstructorToTable< cellLimitedGrad < vector , gradientLimiters:: minmod > > addcellLimitedGradvectorminmodIstreamConstructorToTable_
Definition at line 62 of file cellLimitedGrads.C.
addcellLimitedGradscalarVenkatakrishnanIstreamConstructorToTable_
gradScheme< scalar >::addIstreamConstructorToTable< cellLimitedGrad < scalar , gradientLimiters:: Venkatakrishnan > > addcellLimitedGradscalarVenkatakrishnanIstreamConstructorToTable_
Definition at line 64 of file cellLimitedGrads.C.