OpenFOAM: Foam::MatrixTools Namespace Reference
Foam::MatrixTools Namespace Reference
Collection of functions for matrix-related verifications.
Functions
template<class Form1 , class Form2 , class Type >
bool equal (const Matrix< Form1, Type > &A, const Matrix< Form2, Type > &B, const bool verbose=false, const label maxDiffs=10, const scalar relTol=1e-5, const scalar absTol=1e-8)
template<class Container >
Ostream & printMatrix (Ostream &os, const Container &mat)
template<class MatrixType >
MatrixType pinv (const MatrixType &A, scalar tol=1e-5)
Detailed Description
Collection of functions for matrix-related verifications.
Source files
MatrixTools.H
MatrixTools.C
Function Documentation
equal()
template<class Form1 , class Form2 , class Type > bool equal (const Matrix< Form1, Type > & A, const Matrix< Form2, Type > & B, const bool verbose = false, const label maxDiffs = 10, const scalar relTol = 1e-5, const scalar absTol = 1e-8)
Parameters
maxDiffs Stop reporting after maxDiffs (0 to disable)
Definition at line 26 of file MatrixTools.C.
References A, B, Foam::Info, Foam::mag(), and Foam::nl.
printMatrix()
template<class Container > Ostream & printMatrix (Ostream & os, const Container & mat)
pinv()
template<class MatrixType > MatrixType pinv (const MatrixType & A, scalar tol = 1e-5)
Definition at line 576 of file QRMatrix.C.
References A, Foam::abort(), UPtrList< T >::cbegin(), UPtrList< T >::cend(), Foam::diag(), e, UPtrList< T >::empty(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::lessThan(), Foam::mag(), R, PtrList< T >::resize(), UPtrList< T >::size(), WarningInFunction, x, and Foam::Zero.