OpenFOAM: Foam::edgeMeshTools Namespace Reference
Foam::edgeMeshTools Namespace Reference
Collection of static functions related to edgeMesh features.
Functions
void writeStats (Ostream &os, const extendedFeatureEdgeMesh &emesh)
tmp< scalarField > featureProximity (const extendedEdgeMesh &emesh, const triSurface &surf, const scalar searchDistance)
tmp< scalarField > writeFeatureProximity (const Time &runTime, const word &basename, const extendedEdgeMesh &emesh, const triSurface &surf, const scalar searchDistance)
Detailed Description
Collection of static functions related to edgeMesh features.
Source files
edgeMeshTools.H
edgeMeshTools.C
edgeMeshFeatureProximity.C
Function Documentation
writeStats()
void writeStats (Ostream & os, const extendedFeatureEdgeMesh & emesh)
Definition at line 28 of file edgeMeshTools.C.
References Foam::endl(), Foam::nl, os(), and UPtrList< T >::size().
featureProximity()
Foam::tmp< Foam::scalarField > featureProximity (const extendedEdgeMesh & emesh, const triSurface & surf, const scalar searchDistance)
Definition at line 132 of file edgeMeshFeatureProximity.C.
References Foam::calcProximityOfFeatureEdges(), Foam::calcProximityOfFeaturePoints(), triangle< Point, PointRef >::circumCentre(), triangle< Point, PointRef >::circumRadius(), Foam::endl(), featureProximity(), forAll, Foam::Info, Foam::min(), PrimitivePatch< FaceList, PointField >::points(), UList< T >::size(), and Foam::sqr().
Referenced by featureProximity(), and writeFeatureProximity().
writeFeatureProximity()
Foam::tmp< Foam::scalarField > writeFeatureProximity (const Time & runTime, const word & basename, const extendedEdgeMesh & emesh, const triSurface & surf, const scalar searchDistance)
Definition at line 182 of file edgeMeshFeatureProximity.C.
References Foam::dimLength, Foam::endl(), featureProximity(), Foam::Info, Foam::nl, runTime, and UPtrList< T >::swap().