OpenFOAM: Foam::ListOps Namespace Reference
Foam::ListOps Namespace Reference
Various utility functions to work on Lists.
Classes
struct appendEqOp
struct greater
struct less
struct unionEqOp
struct uniqueEqOp
Functions
void identity (labelUList &map, label start=0)
template<class ListType , class UnaryPredicate >
label count_if (const ListType &input, const UnaryPredicate &pred, const label start=0)
template<class ListType , class UnaryPredicate >
label find_if (const ListType &input, const UnaryPredicate &pred, const label start=0)
template<class ListType , class UnaryPredicate >
label find (const ListType &input, const UnaryPredicate &pred, const label start=0)
template<class ListType , class UnaryPredicate >
bool found_if (const ListType &input, const UnaryPredicate &pred, const label start=0)
template<class ListType , class UnaryPredicate >
bool found (const ListType &input, const UnaryPredicate &pred, const label start=0)
template<class ListType , class UnaryPredicate >
labelList findIndices (const ListType &input, const UnaryPredicate &pred, label start=0)
template<class T >
void setValue (UList< T > &list, const labelUList &locations, const T &val)
template<class T >
void setValue (UList< T > &list, const labelHashSet &locations, const T &val)
template<class T >
void setValue (UList< T > &list, const UList< bool > &locations, const T &val)
template<class T >
void setValue (UList< T > &list, const bitSet &locations, const T &val)
template<class T , class T2 , class UnaryOperation >
List< T > create (const UList< T2 > &input, const UnaryOperation &op)
template<class T , class InputIterator , class UnaryOperation >
List< T > create (InputIterator first, InputIterator last, const UnaryOperation &op)
template<class T >
List< T > createWithValue (const label len, const labelUList &locations, const T &val, const T &deflt=T())
template<class T >
List< T > createWithValue (const label len, const labelHashSet &locations, const T &val, const T &deflt=T())
template<class T >
List< T > createWithValue (const label len, const UList< bool > &locations, const T &val, const T &deflt=T())
template<class T >
List< T > createWithValue (const label len, const bitSet &locations, const T &val, const T &deflt=T())
template<class T >
List< T > createWithValue (const label len, const label index, const T &val, const T &deflt=T())
template<class T >
List< T > createWithValue (const label len, const label index, T &&val, const T &deflt=T())
Detailed Description
Various utility functions to work on Lists.
Source files
ListOps.H
ListOps.C
ListOpsTemplates.C
Function Documentation
identity()
void identity (labelUList & map, label start = 0)
Definition at line 196 of file ListOps.C.
References UList< T >::begin(), and UList< T >::end().
Referenced by SortableList< T >::partialReverseSort(), SortableList< T >::partialSort(), SortList< T >::reset(), SortList< T >::sort(), and ensightFaces::write().
count_if()
template<class ListType , class UnaryPredicate > label count_if (const ListType & input, const UnaryPredicate & pred, const label start = 0)
find_if()
template<class ListType , class UnaryPredicate > label find_if (const ListType & input, const UnaryPredicate & pred, const label start = 0)
Referenced by find().
find()
template<class ListType , class UnaryPredicate > label find (const ListType & input, const UnaryPredicate & pred, const label start = 0)
Definition at line 789 of file ListOps.H.
References find_if(), and Foam::input().
found_if()
template<class ListType , class UnaryPredicate > bool found_if (const ListType & input, const UnaryPredicate & pred, const label start = 0)
Definition at line 1159 of file ListOpsTemplates.C.
Referenced by found().
found()
template<class ListType , class UnaryPredicate > bool found (const ListType & input, const UnaryPredicate & pred, const label start = 0)
Definition at line 820 of file ListOps.H.
References found_if(), and Foam::input().
Referenced by areaWrite::write(), writeObjects::write(), starcdWriter::write(), nastranWriter::writeTemplate(), and starcdWriter::writeTemplate().
findIndices()
template<class ListType , class UnaryPredicate > labelList findIndices (const ListType & input, const UnaryPredicate & pred, label start = 0)
Referenced by faMeshDistributor::distribute().
setValue() [1/4]
template<class T > void setValue (UList< T > & list, const labelUList & locations, const T & val)
Definition at line 1220 of file ListOpsTemplates.C.
References UPtrList< T >::size().
setValue() [2/4]
template<class T > void setValue (UList< T > & list, const labelHashSet & locations, const T & val)
Definition at line 1241 of file ListOpsTemplates.C.
References UPtrList< T >::size().
setValue() [3/4]
template<class T > void setValue (UList< T > & list, const UList< bool > & locations, const T & val)
Definition at line 1262 of file ListOpsTemplates.C.
References Foam::min(), and UPtrList< T >::size().
setValue() [4/4]
template<class T > void setValue (UList< T > & list, const bitSet & locations, const T & val)
Definition at line 1285 of file ListOpsTemplates.C.
References UPtrList< T >::find_next(), Foam::pos(), and UPtrList< T >::size().
create() [1/2]
template<class T , class T2 , class UnaryOperation > List< T > create (const UList< T2 > & input, const UnaryOperation & op)
create() [2/2]
template<class T , class InputIterator , class UnaryOperation > List< T > create (InputIterator first, InputIterator last, const UnaryOperation & op)
createWithValue() [1/6]
template<class T > List< T > createWithValue (const label len, const labelUList & locations, const T & val, const T & deflt = T())
createWithValue() [2/6]
template<class T > List< T > createWithValue (const label len, const labelHashSet & locations, const T & val, const T & deflt = T())
createWithValue() [3/6]
template<class T > List< T > createWithValue (const label len, const UList< bool > & locations, const T & val, const T & deflt = T())
createWithValue() [4/6]
template<class T > List< T > createWithValue (const label len, const bitSet & locations, const T & val, const T & deflt = T())
createWithValue() [5/6]
template<class T > List< T > createWithValue (const label len, const label index, const T & val, const T & deflt = T())
createWithValue() [6/6]
template<class T > List< T > createWithValue (const label len, const label index, T && val, const T & deflt = T())