OpenFOAM: Foam::stringOps Namespace Reference
Foam::stringOps Namespace Reference
Collection of static functions for various string-related operations.
Classes
struct natural_sort
Functions
std::string::size_type count (const std::string &s, const char c)
std::string::size_type count (const char *s, const char c)
bool match (const UList< wordRe > &patterns, const std::string &text)
template<class StringType , class UnaryPredicate >
StringType quotemeta (const StringType &str, const UnaryPredicate &meta, const char quote='\\')
string expand (const std::string &s, const HashTable< string > &mapping, const char sigil='$')
void inplaceExpand (std::string &s, const HashTable< string > &mapping, const char sigil='$')
void inplaceExpand (std::string &s, const dictionary &dict, const bool allowEnv, const bool allowEmpty, const bool allowSubDict=false, const char sigil='$')
string expand (const std::string &s, const dictionary &dict, const char sigil='$')
void inplaceExpand (std::string &s, const dictionary &dict, const char sigil='$')
string expand (const std::string &s, const bool allowEmpty=false)
void inplaceExpand (std::string &s, const bool allowEmpty=false)
bool inplaceReplaceVar (std::string &s, const word &varName)
template<class StringType , class UnaryPredicate >
StringType validate (const std::string &str, const UnaryPredicate &accept, const bool invert=false)
std::pair< size_t, size_t > findTrim (const std::string &s, size_t pos=0, size_t len=std::string::npos)
string trimLeft (const std::string &s)
void inplaceTrimLeft (std::string &s)
string trimRight (const std::string &s)
void inplaceTrimRight (std::string &s)
string trim (const std::string &s)
void inplaceTrim (std::string &s)
void inplaceRemoveSpace (std::string &s)
string removeComments (const std::string &s)
void inplaceRemoveComments (std::string &s)
string lower (const std::string &s)
void inplaceLower (std::string &s)
string upper (const std::string &s)
void inplaceUpper (std::string &s)
label splitFunctionArgs (const std::string &str, wordRes &args, List< Tuple2< word, string > > &namedArgs)
template<class StringType >
Foam::SubStrings< StringType > split (const StringType &str, const char delim, const bool keepEmpty=false)
template<class StringType >
Foam::SubStrings< StringType > split (const StringType &str, const std::string &delim, const bool keepEmpty=false)
template<class StringType >
Foam::SubStrings< StringType > splitAny (const StringType &str, const std::string &delim)
template<class StringType >
Foam::SubStrings< StringType > splitFixed (const StringType &str, const std::string::size_type width, const std::string::size_type start=0)
template<class StringType >
Foam::SubStrings< StringType > splitSpace (const StringType &str)
void writeWrapped (OSstream &os, const std::string &str, const std::string::size_type width, const std::string::size_type indent=0, const bool escape=false)
string evaluate (label fieldWidth, const std::string &s, size_t pos=0, size_t len=std::string::npos)
string evaluate (const std::string &s, size_t pos=0, size_t len=std::string::npos)
int natstrcmp (const char *s1, const char *s2)
Detailed Description
Collection of static functions for various string-related operations.
Source files
stringOps.H
stringOps.C
stringOpsTemplates.C
Function Documentation
count() [1/2]
std::string::size_type count (const std::string & s, const char c)
Definition at line 686 of file stringOps.C.
References s().
Referenced by string::count(), ensightSurfaceReader::replaceMask(), OSstream::write(), and OSstream::writeQuoted().
count() [2/2]
std::string::size_type count (const char * s, const char c)
Definition at line 696 of file stringOps.C.
References s().
match()
bool match (const UList< wordRe > & patterns, const std::string & text) inline
Definition at line 70 of file stringOps.H.
Referenced by functionObjectList::execute().
quotemeta()
template<class StringType , class UnaryPredicate > StringType quotemeta (const StringType & str, const UnaryPredicate & meta, const char quote = '\\')
Definition at line 24 of file stringOpsTemplates.C.
References UPtrList< T >::empty(), and UPtrList< T >::size().
Referenced by ddt2::read().
expand() [1/3]
Foam::string expand (const std::string & s, const HashTable< string > & mapping, const char sigil = '$')
Definition at line 703 of file stringOps.C.
References inplaceExpand(), and s().
Referenced by dynamicCode::copyOrCreateFiles(), argList::displayDoc(), and functionObjectList::findDict().
inplaceExpand() [1/4]
void inplaceExpand (std::string & s, const HashTable< string > & mapping, const char sigil = '$')
Definition at line 716 of file stringOps.C.
References findParameterAlternative(), s(), and UPtrList< T >::size().
Referenced by dynamicCode::copyAndFilter(), string::expand(), expand(), expand(), expand(), expressionEntry::inplaceExpand(), dynamicCodeContext::inplaceExpand(), entry::New(), includeEtcEntry::resolveEtcFile(), and includeEntry::resolveFile().
inplaceExpand() [2/4]
void inplaceExpand (std::string & s, const dictionary & dict, const bool allowEnv, const bool allowEmpty, const bool allowSubDict = false, const char sigil = '$')
Definition at line 841 of file stringOps.C.
References dict, Foam::expandString(), and s().
expand() [2/3]
Foam::string expand (const std::string & s, const dictionary & dict, const char sigil = '$')
Definition at line 828 of file stringOps.C.
References dict, inplaceExpand(), and s().
inplaceExpand() [3/4]
void inplaceExpand (std::string & s, const dictionary & dict, const char sigil = '$')
Definition at line 855 of file stringOps.C.
References dict, Foam::expandString(), and s().
expand() [3/3]
Foam::string expand (const std::string & s, const bool allowEmpty = false)
Definition at line 868 of file stringOps.C.
References inplaceExpand(), and s().
inplaceExpand() [4/4]
void inplaceExpand (std::string & s, const bool allowEmpty = false)
Definition at line 880 of file stringOps.C.
References Foam::expandString(), and s().
inplaceReplaceVar()
bool inplaceReplaceVar (std::string & s, const word & varName)
Definition at line 892 of file stringOps.C.
References UPtrList< T >::empty(), Foam::getEnv(), and s().
validate()
template<class StringType , class UnaryPredicate > StringType validate (const std::string & str, const UnaryPredicate & accept, const bool invert = false)
Parameters
invert Invert the test logic
Definition at line 63 of file stringOpsTemplates.C.
References Foam::invert(), and PtrList< T >::resize().
findTrim()
std::pair< size_t, size_t > findTrim (const std::string & s, size_t pos = 0, size_t len = std::string::npos)
trimLeft()
Foam::string trimLeft (const std::string & s)
Definition at line 916 of file stringOps.C.
References Foam::pos(), and s().
inplaceTrimLeft()
void inplaceTrimLeft (std::string & s)
Definition at line 938 of file stringOps.C.
References Foam::pos(), and s().
Referenced by inplaceTrim().
trimRight()
Foam::string trimRight (const std::string & s)
Definition at line 958 of file stringOps.C.
References s().
inplaceTrimRight()
void inplaceTrimRight (std::string & s)
Definition at line 978 of file stringOps.C.
References s().
Referenced by inplaceTrim(), and ensightSurfaceReader::readLine().
trim()
Foam::string trim (const std::string & s)
Definition at line 1032 of file stringOps.C.
References Foam::pos(), and s().
Referenced by exprDriver::addVariables().
inplaceTrim()
void inplaceTrim (std::string & s)
Definition at line 1053 of file stringOps.C.
References inplaceTrimLeft(), inplaceTrimRight(), and s().
Referenced by exprDriver::addVariables(), expressionEntry::inplaceExpand(), dynamicCodeContext::inplaceExpand(), Foam::recursiveExpand(), and exprString::trim().
inplaceRemoveSpace()
void inplaceRemoveSpace (std::string & s)
Definition at line 1060 of file stringOps.C.
References s().
Referenced by Foam::getIdentifier().
removeComments()
Foam::string removeComments (const std::string & s)
Definition at line 1066 of file stringOps.C.
References inplaceRemoveComments(), and s().
inplaceRemoveComments()
void inplaceRemoveComments (std::string & s)
Definition at line 1074 of file stringOps.C.
References n, and s().
Referenced by exprString::inplaceExpand(), and removeComments().
lower()
Foam::string lower (const std::string & s)
Definition at line 1170 of file stringOps.C.
References s().
Referenced by STLAsciiParseManual::execute().
inplaceLower()
void inplaceLower (std::string & s)
Definition at line 1180 of file stringOps.C.
References s().
Referenced by STARCDMeshReader::readBoundary().
upper()
Foam::string upper (const std::string & s)
Definition at line 1186 of file stringOps.C.
References s().
Referenced by ABAQUSCore::readHelper::addNewElset(), Foam::getIdentifier(), argList::printMan(), ABAQUSCore::readHelper::read(), ABAQUSCore::readHelper::readSurfaceElements(), and Foam::writeCoordHeader().
inplaceUpper()
void inplaceUpper (std::string & s)
Definition at line 1196 of file stringOps.C.
References s().
splitFunctionArgs()
Foam::label splitFunctionArgs (const std::string & str, wordRes & args, List< Tuple2< word, string > > & namedArgs)
Definition at line 49 of file stringOpsSplit.C.
References args, PtrList< T >::clear(), UPtrList< T >::first(), Foam::name(), Foam::pos(), PtrList< T >::push_back(), PtrList< T >::resize(), UPtrList< T >::size(), and argList::size().
Referenced by functionObjectList::readFunctionObject().
split() [1/2]
template<class StringType > Foam::SubStrings< StringType > split (const StringType & str, const char delim, const bool keepEmpty = false)
Definition at line 90 of file stringOpsTemplates.C.
References PtrList< T >::append(), UPtrList< T >::cbegin(), UPtrList< T >::cend(), UPtrList< T >::empty(), and UPtrList< T >::size().
Referenced by dictionary::makeScopedDict().
split() [2/2]
template<class StringType > Foam::SubStrings< StringType > split (const StringType & str, const std::string & delim, const bool keepEmpty = false)
Definition at line 126 of file stringOpsTemplates.C.
References PtrList< T >::append(), UPtrList< T >::cbegin(), UPtrList< T >::cend(), UPtrList< T >::empty(), and UPtrList< T >::size().
splitAny()
template<class StringType > Foam::SubStrings< StringType > splitAny (const StringType & str, const std::string & delim)
Definition at line 162 of file stringOpsTemplates.C.
References PtrList< T >::append(), UPtrList< T >::cbegin(), UPtrList< T >::cend(), UPtrList< T >::empty(), and Foam::pos().
Referenced by scalarRanges::parse(), splitSpace(), and Foam::splitStringToList().
splitFixed()
template<class StringType > Foam::SubStrings< StringType > splitFixed (const StringType & str, const std::string::size_type width, const std::string::size_type start = 0)
Definition at line 203 of file stringOpsTemplates.C.
References PtrList< T >::append(), UPtrList< T >::cbegin(), UPtrList< T >::cend(), UPtrList< T >::empty(), Foam::pos(), and UPtrList< T >::size().
splitSpace()
template<class StringType > Foam::SubStrings< StringType > splitSpace (const StringType & str)
Definition at line 238 of file stringOpsTemplates.C.
References splitAny().
Referenced by argList::displayDoc(), OBJedgeFormat::read(), and ensightSurfaceReader::readCase().
writeWrapped()
void writeWrapped (OSstream & os, const std::string & str, const std::string::size_type width, const std::string::size_type indent = 0, const bool escape = false)
Definition at line 1202 of file stringOps.C.
References Foam::indent(), Foam::nl, os(), Foam::pos(), and UPtrList< T >::size().
Referenced by argList::printMan(), Foam::printManOption(), argList::printNotes(), and Foam::printOptionUsage().
evaluate() [1/2]
Foam::string evaluate (label fieldWidth, const std::string & s, size_t pos = 0, size_t len = std::string::npos)
InfoErr<< "Evaluate " << str.substr(pos, len) << nl;
InfoErr<< "Evaluate " << str.substr(pos, len) << nl;
Definition at line 29 of file stringOpsEvaluate.C.
References UPtrList< T >::first(), exprResult::hasValue(), Foam::InfoErr, Foam::nl, os(), Foam::pos(), exprResult::size(), exprResult::writeField(), and exprResult::writeValue().
Referenced by Foam::recursiveExpand().
evaluate() [2/2]
Foam::string evaluate (const std::string & s, size_t pos = 0, size_t len = std::string::npos)
Definition at line 86 of file stringOpsEvaluate.C.
References Foam::pos().
natstrcmp()
int natstrcmp (const char * s1, const char * s2)
Definition at line 118 of file stringOpsSort.C.
Referenced by natural_sort::compare().