OpenFOAM: Foam::colourTools Namespace Reference
Foam::colourTools Namespace Reference
Utility methods for colours and colour spaces.
Functions
void rgbToHsv (const vector &rgb, vector &hsv)
vector rgbToHsv (const vector &rgb)
void hsvToRgb (const vector &hsv, vector &rgb)
vector hsvToRgb (const vector &hsv)
void rgbToXyz (const vector &rgb, vector &xyz)
vector rgbToXyz (const vector &rgb)
void xyzToRgb (const vector &xyz, vector &rgb)
vector xyzToRgb (const vector &xyz)
void labToXyz (const vector &lab, vector &xyz)
vector labToXyz (const vector &lab)
void xyzToLab (const vector &xyz, vector &lab)
vector xyzToLab (const vector &xyz)
void rgbToLab (const vector &rgb, vector &lab)
vector rgbToLab (const vector &rgb)
void labToRgb (const vector &lab, vector &rgb)
vector labToRgb (const vector &lab)
void interpolateDiverging (scalar s, const vector &rgb1, const vector &rgb2, vector &result)
vector interpolateDiverging (scalar s, const vector &rgb1, const vector &rgb2)
void interpolateHSV (scalar s, const vector &rgb1, const vector &rgb2, vector &result)
vector interpolateHSV (scalar s, const vector &rgb1, const vector &rgb2)
vector interpolateRGB (scalar s, const vector &rgb1, const vector &rgb2)
Detailed Description
Utility methods for colours and colour spaces.
Source files
colourTools.H
colourTools.C
Function Documentation
rgbToHsv() [1/2]
void rgbToHsv (const vector & rgb, vector & hsv)
Definition at line 350 of file colourTools.C.
References Foam::RGB_to_HSV().
Referenced by interpolateHSV(), and rgbToHsv().
rgbToHsv() [2/2]
vector rgbToHsv (const vector & rgb) inline
Definition at line 57 of file colourTools.H.
References rgbToHsv().
hsvToRgb() [1/2]
void hsvToRgb (const vector & hsv, vector & rgb)
Definition at line 355 of file colourTools.C.
References Foam::HSV_to_RGB().
Referenced by hsvToRgb(), and interpolateHSV().
hsvToRgb() [2/2]
vector hsvToRgb (const vector & hsv) inline
Definition at line 73 of file colourTools.H.
References hsvToRgb().
rgbToXyz() [1/2]
void rgbToXyz (const vector & rgb, vector & xyz)
Definition at line 361 of file colourTools.C.
References Foam::RGB_to_XYZ().
Referenced by rgbToXyz().
rgbToXyz() [2/2]
vector rgbToXyz (const vector & rgb) inline
Definition at line 89 of file colourTools.H.
References rgbToXyz().
xyzToRgb() [1/2]
void xyzToRgb (const vector & xyz, vector & rgb)
Definition at line 366 of file colourTools.C.
References Foam::XYZ_to_RGB().
Referenced by labToRgb(), and xyzToRgb().
xyzToRgb() [2/2]
vector xyzToRgb (const vector & xyz) inline
Definition at line 104 of file colourTools.H.
References xyzToRgb().
labToXyz() [1/2]
void labToXyz (const vector & lab, vector & xyz)
Definition at line 372 of file colourTools.C.
References Foam::LAB_to_XYZ().
Referenced by labToRgb(), and labToXyz().
labToXyz() [2/2]
vector labToXyz (const vector & lab) inline
Definition at line 120 of file colourTools.H.
References labToXyz().
xyzToLab() [1/2]
void xyzToLab (const vector & xyz, vector & lab)
Definition at line 378 of file colourTools.C.
References Foam::XYZ_to_LAB().
Referenced by xyzToLab().
xyzToLab() [2/2]
vector xyzToLab (const vector & xyz) inline
Definition at line 136 of file colourTools.H.
References xyzToLab().
rgbToLab() [1/2]
void rgbToLab (const vector & rgb, vector & lab)
Definition at line 384 of file colourTools.C.
References Foam::RGB_to_XYZ(), and Foam::XYZ_to_LAB().
Referenced by interpolateDiverging(), and rgbToLab().
rgbToLab() [2/2]
vector rgbToLab (const vector & rgb) inline
Definition at line 152 of file colourTools.H.
References rgbToLab().
labToRgb() [1/2]
void labToRgb (const vector & lab, vector & rgb)
Definition at line 392 of file colourTools.C.
References labToXyz(), and xyzToRgb().
Referenced by interpolateDiverging(), and labToRgb().
labToRgb() [2/2]
vector labToRgb (const vector & lab) inline
Definition at line 168 of file colourTools.H.
References labToRgb().
interpolateDiverging() [1/2]
void interpolateDiverging (scalar s, const vector & rgb1, const vector & rgb2, vector & result)
Definition at line 400 of file colourTools.C.
References Foam::adjustHue(), Foam::angleDiff(), Foam::labToMsh(), labToRgb(), Foam::mshToLab(), Foam::constant::mathematical::pi(), rgbToLab(), and s().
Referenced by interpolateDiverging(), and colourTable::value().
interpolateDiverging() [2/2]
vector interpolateDiverging (scalar s, const vector & rgb1, const vector & rgb2) inline
Definition at line 190 of file colourTools.H.
References interpolateDiverging(), and s().
interpolateHSV() [1/2]
void interpolateHSV (scalar s, const vector & rgb1, const vector & rgb2, vector & result)
Definition at line 464 of file colourTools.C.
References hsvToRgb(), rgbToHsv(), and s().
Referenced by interpolateHSV(), and colourTable::value().
interpolateHSV() [2/2]
vector interpolateHSV (scalar s, const vector & rgb1, const vector & rgb2) inline
Definition at line 217 of file colourTools.H.
References interpolateHSV(), and s().
interpolateRGB()
vector interpolateRGB (scalar s, const vector & rgb1, const vector & rgb2) inline
Definition at line 233 of file colourTools.H.
References s().
Referenced by colourTable::value().