OpenFOAM: CGAL Namespace Reference
CGAL Namespace Reference
Specializations for CGAL-related routines.
Namespaces
namespace indexedCellOps
Operations for indexed cell types.
namespace indexedVertexOps
Operations for indexed vertex types.
Classes
class indexedCell
An indexed form of CGAL::Triangulation_cell_base_3<K> used to keep track of the Delaunay cells (tets) in the tessellation.
class indexedFace
An indexed form of CGAL::Triangulation_face_base_2<K> used to keep track of the vertices in the triangulation.
class indexedVertex
An indexed form of CGAL::Triangulation_vertex_base_3<K> used to keep track of the Delaunay vertices in the tessellation.
Functions
template<class Gt , class Vb >
bool pointPair (const indexedVertex< Gt, Vb > &v0, const indexedVertex< Gt, Vb > &v1)
template<class Gt , class Vb >
bool boundaryTriangle (const indexedVertex< Gt, Vb > &v0, const indexedVertex< Gt, Vb > &v1, const indexedVertex< Gt, Vb > &v2)
template<class Gt , class Vb >
bool outsideTriangle (const indexedVertex< Gt, Vb > &v0, const indexedVertex< Gt, Vb > &v1, const indexedVertex< Gt, Vb > &v2)
Detailed Description
Specializations for CGAL-related routines.
Function Documentation
pointPair()
template<class Gt , class Vb > bool pointPair (const indexedVertex< Gt, Vb > & v0, const indexedVertex< Gt, Vb > & v1)
Definition at line 177 of file indexedVertexI.H.
Referenced by boundaryTriangle().
boundaryTriangle()
template<class Gt , class Vb > bool boundaryTriangle (const indexedVertex< Gt, Vb > & v0, const indexedVertex< Gt, Vb > & v1, const indexedVertex< Gt, Vb > & v2)
Definition at line 188 of file indexedVertexI.H.
References indexedVertex< Gt, Vb >::pairPoint(), and pointPair().
outsideTriangle()
template<class Gt , class Vb > bool outsideTriangle (const indexedVertex< Gt, Vb > & v0, const indexedVertex< Gt, Vb > & v1, const indexedVertex< Gt, Vb > & v2)
Definition at line 202 of file indexedVertexI.H.
References indexedVertex< Gt, Vb >::farPoint(), and indexedVertex< Gt, Vb >::ppSlave().