OpenFOAM: Foam::Elliptic Namespace Reference
Foam::Elliptic Namespace Reference
Functions
void ellipticIntegralsKE (const scalar m, scalar &K, scalar &E)
Foam::scalar JacobiAmp (const scalar u, const scalar mIn)
void JacobiSnCnDn (const scalar u, const scalar m, scalar &Sn, scalar &Cn, scalar &Dn)
Detailed Description
Function Documentation
ellipticIntegralsKE()
void ellipticIntegralsKE (const scalar m, scalar & K, scalar & E)
Definition at line 41 of file Elliptic.H.
References g, Foam::mag(), Foam::constant::mathematical::pi(), Foam::sqrt(), and Foam::sum().
JacobiAmp()
Foam::scalar JacobiAmp (const scalar u, const scalar mIn)
Definition at line 78 of file Elliptic.H.
References Foam::asin(), Foam::atan(), Foam::exp(), g, Foam::mag(), n, Foam::constant::mathematical::pi(), Foam::sin(), and Foam::sqrt().
Referenced by JacobiSnCnDn().
JacobiSnCnDn()
void JacobiSnCnDn (const scalar u, const scalar m, scalar & Sn, scalar & Cn, scalar & Dn)
Definition at line 127 of file Elliptic.H.
References Foam::cos(), JacobiAmp(), Foam::sin(), Foam::Sn(), and Foam::sqrt().