OpenFOAM: Foam::PstreamDetail Namespace Reference
Foam::PstreamDetail Namespace Reference
Classes
struct Request
Functions
template<class Type >
void exchangeBuf (const UList< std::pair< int, stdFoam::span< const Type > > > &sends, const UList< std::pair< int, stdFoam::span< Type > > > &recvs, const int tag, const label comm, const bool wait)
template<class Type >
void exchangeChunkedBuf (const UList< std::pair< int, stdFoam::span< const Type > > > &sends, const UList< std::pair< int, stdFoam::span< Type > > > &recvs, const int tag, const label comm, const bool wait)
template<class Container , class Type >
void exchangeContainer (const UList< Container > &sendBufs, UList< Container > &recvBufs, const int tag, const label comm, const bool wait)
template<class Container , class Type >
void exchangeContainer (const Map< Container > &sendBufs, Map< Container > &recvBufs, const int tag, const label comm, const bool wait)
template<class Container , class Type >
void exchangeConsensus (const UList< Container > &sendBufs, UList< Container > &recvBufs, labelUList &recvSizes, const int tag, const label comm, const bool wait=true, const UPstream::commsTypes recvCommType=UPstream::commsTypes::nonBlocking)
template<class Container , class Type >
void exchangeConsensus (const Map< Container > &sendBufs, Map< Container > &recvBufs, const int tag, const label comm, const bool wait=true, const UPstream::commsTypes recvCommType=UPstream::commsTypes::nonBlocking)
template<class Type >
void broadcast0 (Type *values, int count, MPI_Datatype datatype, const label comm)
template<class Type >
void reduce0 (Type *values, int count, MPI_Datatype datatype, MPI_Op optype, const label comm)
template<class Type >
void allReduce (Type *values, int count, MPI_Datatype datatype, MPI_Op optype, const label comm, UPstream::Request *req=nullptr, label *requestID=nullptr)
template<class Type >
void allToAll (const UList< Type > &sendData, UList< Type > &recvData, MPI_Datatype datatype, const label comm, UPstream::Request *req=nullptr, label *requestID=nullptr)
template<class Type >
void allToAllv (const Type *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, Type *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, MPI_Datatype datatype, const label comm, UPstream::Request *req=nullptr, label *requestID=nullptr)
template<class Type >
void allToAllConsensus (const UList< Type > &sendData, UList< Type > &recvData, MPI_Datatype datatype, const int tag, const label comm)
template<class Type >
void allToAllConsensus (const Map< Type > &sendData, Map< Type > &recvData, MPI_Datatype datatype, const int tag, const label comm)
template<class Type >
void gather (const Type *sendData, Type *recvData, int count, MPI_Datatype datatype, const label comm, UPstream::Request *req=nullptr, label *requestID=nullptr)
template<class Type >
void scatter (const Type *sendData, Type *recvData, int count, MPI_Datatype datatype, const label comm, UPstream::Request *req=nullptr, label *requestID=nullptr)
template<class Type >
void gatherv (const Type *sendData, int sendCount, Type *recvData, const UList< int > &recvCounts, const UList< int > &recvOffsets, MPI_Datatype datatype, const label comm, UPstream::Request *req=nullptr, label *requestID=nullptr)
template<class Type >
void scatterv (const Type *sendData, const UList< int > &sendCounts, const UList< int > &sendOffsets, Type *recvData, int recvCount, MPI_Datatype datatype, const label comm, UPstream::Request *req=nullptr, label *requestID=nullptr)
template<class Type >
void allGather (Type *allData, int count, MPI_Datatype datatype, const label comm, UPstream::Request *req=nullptr, label *requestID=nullptr)
Function Documentation
exchangeBuf()
template<class Type > void exchangeBuf (const UList< std::pair< int, stdFoam::span< const Type > > > & sends, const UList< std::pair< int, stdFoam::span< Type > > > & recvs, const int tag, const label comm, const bool wait)
Definition at line 40 of file PstreamExchange.C.
References Foam::abort(), UPtrList< T >::empty(), Foam::FatalError, FatalErrorInFunction, UPtrList< T >::first(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nRequests(), UIPstream::read(), UPstream::waitRequests(), and UOPstream::write().
exchangeChunkedBuf()
template<class Type > void exchangeChunkedBuf (const UList< std::pair< int, stdFoam::span< const Type > > > & sends, const UList< std::pair< int, stdFoam::span< Type > > > & recvs, const int tag, const label comm, const bool wait)
Definition at line 127 of file PstreamExchange.C.
References Foam::endl(), UPtrList< T >::first(), Foam::flatOutput(), forAll, Foam::Info, Foam::max(), UPstream::maxCommsSize, UPstream::msgType(), UPstream::myProcNo(), Foam::reduce(), and UPtrList< T >::size().
exchangeContainer() [1/2]
template<class Container , class Type > void exchangeContainer (const UList< Container > & sendBufs, UList< Container > & recvBufs, const int tag, const label comm, const bool wait)
Parameters
wait Wait for requests to complete
Definition at line 297 of file PstreamExchange.C.
References Foam::abort(), UPtrList< T >::empty(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nRequests(), UIPstream::read(), UPstream::waitRequests(), and UOPstream::write().
exchangeContainer() [2/2]
template<class Container , class Type > void exchangeContainer (const Map< Container > & sendBufs, Map< Container > & recvBufs, const int tag, const label comm, const bool wait)
Parameters
wait Wait for requests to complete
Definition at line 382 of file PstreamExchange.C.
References Foam::abort(), UPtrList< T >::empty(), Foam::FatalError, FatalErrorInFunction, forAllConstIters, forAllIters, UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nRequests(), UIPstream::read(), UPstream::waitRequests(), and UOPstream::write().
exchangeConsensus() [1/2]
template<class Container , class Type > void exchangeConsensus (const UList< Container > & sendBufs, UList< Container > & recvBufs, labelUList & recvSizes, const int tag, const label comm, const bool wait = true, const UPstream::commsTypes recvCommType = UPstream::commsTypes::nonBlocking)
Definition at line 62 of file PstreamExchangeConsensus.C.
References Foam::abort(), UPstream::barrier(), PtrList< T >::emplace_back(), UPtrList< T >::empty(), Foam::FatalError, FatalErrorInFunction, UPstream::finishedRequest(), UPstream::finishedRequests(), UPtrList< T >::first(), UPstream::is_parallel(), UPstream::is_rank(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nProcs(), UPstream::nRequests(), UPstream::probeMessage(), UIPstream::read(), UPtrList< T >::size(), UPstream::sync, UPstream::tuning_NBX_, UPstream::waitRequests(), UOPstream::write(), and Foam::Zero.
Referenced by Pstream::exchangeConsensus(), and Pstream::exchangeConsensus().
exchangeConsensus() [2/2]
template<class Container , class Type > void exchangeConsensus (const Map< Container > & sendBufs, Map< Container > & recvBufs, const int tag, const label comm, const bool wait = true, const UPstream::commsTypes recvCommType = UPstream::commsTypes::nonBlocking)
Definition at line 253 of file PstreamExchangeConsensus.C.
References Foam::abort(), UPstream::barrier(), PtrList< T >::emplace_back(), UPtrList< T >::empty(), Foam::FatalError, FatalErrorInFunction, UPstream::finishedRequest(), UPstream::finishedRequests(), UPtrList< T >::first(), forAllConstIters, forAllIters, UPstream::is_parallel(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nProcs(), UPstream::nRequests(), UPstream::probeMessage(), UIPstream::read(), UPtrList< T >::size(), UPstream::sync, UPstream::waitRequests(), and UOPstream::write().
broadcast0()
template<class Type > void broadcast0 (Type * values, int count, MPI_Datatype datatype, const label comm)
Definition at line 30 of file UPstreamWrappingTemplates.C.
reduce0()
template<class Type > void reduce0 (Type * values, int count, MPI_Datatype datatype, MPI_Op optype, const label comm)
Definition at line 60 of file UPstreamWrappingTemplates.C.
References Foam::endl(), and Foam::Pout.
allReduce()
template<class Type > void allReduce (Type * values, int count, MPI_Datatype datatype, MPI_Op optype, const label comm, UPstream::Request * req = nullptr, label * requestID = nullptr)
Definition at line 109 of file UPstreamWrappingTemplates.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and Foam::Pout.
allToAll()
template<class Type > void allToAll (const UList< Type > & sendData, UList< Type > & recvData, MPI_Datatype datatype, const label comm, UPstream::Request * req = nullptr, label * requestID = nullptr)
Definition at line 215 of file UPstreamWrappingTemplates.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::Pout, and UPtrList< T >::size().
allToAllv()
template<class Type > void allToAllv (const Type * sendData, const UList< int > & sendCounts, const UList< int > & sendOffsets, Type * recvData, const UList< int > & recvCounts, const UList< int > & recvOffsets, MPI_Datatype datatype, const label comm, UPstream::Request * req = nullptr, label * requestID = nullptr)
Definition at line 340 of file UPstreamWrappingTemplates.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::Pout, and UPtrList< T >::size().
allToAllConsensus() [1/2]
template<class Type > void allToAllConsensus (const UList< Type > & sendData, UList< Type > & recvData, MPI_Datatype datatype, const int tag, const label comm)
Definition at line 490 of file UPstreamWrappingTemplates.C.
References Foam::abort(), PtrList< T >::emplace_back(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, Foam::Pout, and UPtrList< T >::size().
allToAllConsensus() [2/2]
template<class Type > void allToAllConsensus (const Map< Type > & sendData, Map< Type > & recvData, MPI_Datatype datatype, const int tag, const label comm)
Definition at line 712 of file UPstreamWrappingTemplates.C.
References UPtrList< T >::cbegin(), UPtrList< T >::cend(), PtrList< T >::clear(), PtrList< T >::emplace_back(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, Foam::Pout, and UPtrList< T >::size().
gather()
template<class Type > void gather (const Type * sendData, Type * recvData, int count, MPI_Datatype datatype, const label comm, UPstream::Request * req = nullptr, label * requestID = nullptr)
Definition at line 925 of file UPstreamWrappingTemplates.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and Foam::Pout.
scatter()
template<class Type > void scatter (const Type * sendData, Type * recvData, int count, MPI_Datatype datatype, const label comm, UPstream::Request * req = nullptr, label * requestID = nullptr)
Definition at line 1032 of file UPstreamWrappingTemplates.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and Foam::Pout.
gatherv()
template<class Type > void gatherv (const Type * sendData, int sendCount, Type * recvData, const UList< int > & recvCounts, const UList< int > & recvOffsets, MPI_Datatype datatype, const label comm, UPstream::Request * req = nullptr, label * requestID = nullptr)
Definition at line 1139 of file UPstreamWrappingTemplates.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::Pout, and UPtrList< T >::size().
scatterv()
template<class Type > void scatterv (const Type * sendData, const UList< int > & sendCounts, const UList< int > & sendOffsets, Type * recvData, int recvCount, MPI_Datatype datatype, const label comm, UPstream::Request * req = nullptr, label * requestID = nullptr)
Definition at line 1282 of file UPstreamWrappingTemplates.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::Pout, and UPtrList< T >::size().
allGather()
template<class Type > void allGather (Type * allData, int count, MPI_Datatype datatype, const label comm, UPstream::Request * req = nullptr, label * requestID = nullptr)
Definition at line 1418 of file UPstreamWrappingTemplates.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and Foam::Pout.