OpenFOAM: Foam::vtk Namespace Reference
Foam::vtk Namespace Reference
Namespace for handling VTK input/output.
Namespaces
namespace legacy
Namespace for legacy VTK output constants and functions.
namespace Tools
A collection of static methods to assist converting OpenFOAM data structures into VTK internal data structures.
Classes
class appendBase64Formatter
Appended base-64 encoded binary output. Uses an output filter layer to write base-64 encoded content.
class appendRawFormatter
Appended raw binary output.
class asciiFormatter
Inline ASCII output. Adds spaces between entries and a newline every 9 items (for consistency with what VTK itself outputs).
class base64Formatter
Inline base-64 encoded binary output. Uses an output filter layer to write base-64 encoded content.
struct Caching
class coordSetWriter
Write as points/lines, optionally with fields, as a vtp file or a legacy vtk file.
class fileWriter
Base class for VTK output writers that handle geometry and fields (eg, vtp, vtu data). These output formats are structured as DECLARED, FIELD_DATA, PIECE followed by any CELL_DATA or POINT_DATA.
class foamVtkBase64Layer
Base-64 encoded output layer - normally only used indirectly by formatters.
class formatter
Abstract class for a VTK output stream formatter.
class GenericPatchGeoFieldsWriter
A Foam::vtk::GenericPatchWriter with support for geometric fields.
class GenericPatchWriter
Write concrete PrimitivePatch faces/points (optionally with fields) as a vtp file or a legacy vtk file. The patch type is limited to representations of polygon faces and 3D points and must support the following methods:
class internalMeshWriter
Write an OpenFOAM volume (internal) geometry and internal fields as a vtu file or a legacy vtk file.
class internalWriter
Write an OpenFOAM volume (internal) geometry and internal fields as a vtu file or a legacy vtk file.
class lagrangianWriter
Write lagrangian (cloud) positions and fields (as PointData) in VTP format. Legacy VTK format is intentionally not supported since the VTP format provides much better field selection in ParaView, and for consistency with the Foam::functionObjects::vtkCloud function object.
class legacyAsciiFormatter
Formatting as per Foam::vtk::asciiFormatter, but with naming for legacy output.
class legacyRawFormatter
Binary output for the VTK legacy format, always written as big-endian and with 32-bit integers.
class lineWriter
Write edge/points (optionally with fields) as a vtp file or a legacy vtk file.
class outputOptions
Encapsulated combinations of output format options. This is primarily useful when defining the output type based on some command-line arguments or dictionary contents. However, it can also be a useful alternative to using the underlying enumeration directly, since this class provides additional methods not possible with an enum.
class patchMeshWriter
Write OpenFOAM patches and patch fields in VTP or legacy vtk format.
class patchWriter
Write OpenFOAM patches and patch fields in VTP or legacy vtk format.
class polyWriter
Write faces/points (optionally with fields) as a vtp file or a legacy vtk file.
class seriesWriter
Provides a means of accumulating and generating VTK file series.
class surfaceFieldWriter
Write surfaces fields (as PointData) in VTP format. Legacy VTK format is intentionally not supported.
class surfaceWriter
Write faces/points (optionally with fields) as a vtp file or a legacy vtk file.
class vtmWriter
Provides a means of accumulating file entries for generating a vtkMultiBlockDataSet (.vtm) file.
class vtuAdaptor
A low-level backend adaptor for converting OpenFOAM volume meshes/fields to VTK internal representation. The output is a single piece vtkUnstructuredGrid dataset. Multiblock composition is done by the caller.
class vtuCells
A deep-copy description of an OpenFOAM volume mesh in data structures suitable for VTK UnstructuredGrid, including the possibility of decomposing polyhedral cells into primitive cell types.
class vtuSizing
Sizing descriptions and routines for transcribing an OpenFOAM volume mesh into a VTK unstructured grid, with possible decomposition of polyhedral cells into primitive cell types.
Typedefs
typedef GenericPatchGeoFieldsWriter< indirectPrimitivePatch > indirectPatchGeoFieldsWriter
Write indirectPrimitivePatch faces/points as a vtp file or a legacy vtk file with support for geometric fields.
typedef GenericPatchGeoFieldsWriter< uindirectPrimitivePatch > uindirectPatchGeoFieldsWriter
Write uindirectPrimitivePatch faces/points as a vtp file or a legacy vtk file with support for geometric fields.
typedef indirectPatchGeoFieldsWriter surfaceMeshWriter
typedef GenericPatchWriter< indirectPrimitivePatch > indirectPatchWriter
Write indirectPrimitivePatch faces/points (optionally with fields) as a vtp file or a legacy vtk file.
typedef GenericPatchWriter< uindirectPrimitivePatch > uindirectPatchWriter
Write uindirectPrimitivePatch faces/points (optionally with fields) as a vtp file or a legacy vtk file.
typedef GenericPatchWriter< primitivePatch > primitivePatchWriter
Write primitivePatch faces/points (optionally with fields) as a vtp file or a legacy vtk file.
Enumerations
enum OutputContext : uint8_t { INLINE , HEADER , APPEND }
enum class formatType : uint8_t {
INLINE_ASCII = 0 , INLINE_BASE64 = 0x01 , APPEND_BASE64 = 0x11 , APPEND_BINARY = 0x12 ,
LEGACY_ASCII = 0x20 , LEGACY_BINARY = 0x22
}
enum cellType : uint8_t {
VTK_EMPTY_CELL = 0 , VTK_VERTEX = 1 , VTK_POLY_VERTEX = 2 , VTK_LINE = 3 ,
VTK_POLY_LINE = 4 , VTK_TRIANGLE = 5 , VTK_TRIANGLE_STRIP = 6 , VTK_POLYGON = 7 ,
VTK_PIXEL = 8 , VTK_QUAD = 9 , VTK_TETRA = 10 , VTK_VOXEL = 11 ,
VTK_HEXAHEDRON = 12 , VTK_WEDGE = 13 , VTK_PYRAMID = 14 , VTK_PENTAGONAL_PRISM = 15 ,
VTK_HEXAGONAL_PRISM = 16 , VTK_POLYHEDRON = 42
}
enum class fileTag : uint8_t {
VTK_FILE , DATA_ARRAY , BLOCK , PIECE ,
DATA_SET , POINTS , CELLS , POLYS ,
VERTS , LINES , CELL_DATA , POINT_DATA ,
FIELD_DATA , POLY_DATA , UNSTRUCTURED_GRID , MULTI_BLOCK
}
enum class fileAttr : uint8_t {
OFFSET , NUMBER_OF_COMPONENTS , NUMBER_OF_TUPLES , NUMBER_OF_POINTS ,
NUMBER_OF_CELLS , NUMBER_OF_POLYS , NUMBER_OF_VERTS , NUMBER_OF_LINES
}
enum class dataArrayAttr : uint8_t {
POINTS , OFFSETS , CONNECTIVITY , TYPES ,
FACES , FACEOFFSETS
}
Functions
bool isAppend (enum formatType fmt) noexcept
bool isLegacy (enum formatType fmt) noexcept
template<class Type , direction nComp = 1>
uint64_t sizeofData (label count)
autoPtr< vtk::formatter > newFormatter (std::ostream &os, unsigned prec=IOstream::defaultPrecision())
autoPtr< vtk::formatter > newFormatter (std::ostream &os, const enum formatType fmtType, unsigned prec=IOstream::defaultPrecision())
void writeIdentity (vtk::formatter &fmt, const label len, label start=0)
void writeList (vtk::formatter &fmt, const UList< uint8_t > &values)
template<class Type >
void write (vtk::formatter &fmt, const Type &val, const label n=1)
template<class Type >
void writeValueParallel (vtk::formatter &fmt, const Type &val, const label count=1)
template<class Type >
void writeList (vtk::formatter &fmt, const UList< Type > &values)
template<class Type , unsigned N>
void writeList (vtk::formatter &fmt, const FixedList< Type, N > &values)
template<class Type >
void writeList (vtk::formatter &fmt, const UList< Type > &values, const labelUList &addressing)
template<class Type >
void writeList (vtk::formatter &fmt, const UList< Type > &values, const bitSet &selected)
template<class Type >
void writeLists (vtk::formatter &fmt, const UList< Type > &values1, const UList< Type > &values2, const labelUList &addressing)
template<class Type >
void writeListParallel (vtk::formatter &fmt, const UList< Type > &values)
void writeListParallel (vtk::formatter &fmt, const UList< label > &values, const globalIndex &procOffset)
template<class Type >
void writeListParallel (vtk::formatter &fmt, const UList< Type > &values, const labelUList &addressing)
template<class Type >
void writeListParallel (vtk::formatter &fmt, const UList< Type > &values, const bitSet &selected)
template<class Type >
void writeListsParallel (vtk::formatter &fmt, const UList< Type > &values1, const UList< Type > &values2)
template<class Type >
void writeListsParallel (vtk::formatter &fmt, const UList< Type > &values1, const UList< Type > &values2, const labelUList &addressing)
template<>
void write< label > (vtk::formatter &fmt, const label &val, const label n)
template<>
void write< float > (vtk::formatter &fmt, const float &val, const label n)
template<>
void write< double > (vtk::formatter &fmt, const double &val, const label n)
template<>
void write (vtk::formatter &fmt, const symmTensor &val, const label n)
bool writeTopoSet (const polyMesh &mesh, const topoSet &set, const vtk::outputOptions opts, const fileName &file, bool parallel=UPstream::parRun())
bool writeFaceSet (const polyMesh &mesh, const faceSet &set, const vtk::outputOptions opts, const fileName &file, bool parallel=UPstream::parRun())
bool writeCellSetFaces (const polyMesh &mesh, const cellSet &set, const vtk::outputOptions opts, const fileName &file, bool parallel=UPstream::parRun())
bool writePointSet (const polyMesh &mesh, const pointSet &set, const vtk::outputOptions opts, const fileName &file, bool parallel=UPstream::parRun())
Variables
const Foam::Enum< fileTag > fileExtension
const Foam::Enum< fileTag > fileContentVersions
const Foam::Enum< fileTag > fileTagNames
const Foam::Enum< fileAttr > fileAttrNames
const Foam::Enum< dataArrayAttr > dataArrayAttrNames
Detailed Description
Namespace for handling VTK input/output.
Namespace for handling VTK output. Contains classes and functions for writing VTK file content.
Source files
foamVtkCore.H
foamVtkCore.C
Typedef Documentation
indirectPatchGeoFieldsWriter
indirectPatchGeoFieldsWriter
Write indirectPrimitivePatch faces/points as a vtp file or a legacy vtk file with support for geometric fields.
Definition at line 59 of file foamVtkIndPatchGeoFieldsWriter.H.
uindirectPatchGeoFieldsWriter
uindirectPatchGeoFieldsWriter
Write uindirectPrimitivePatch faces/points as a vtp file or a legacy vtk file with support for geometric fields.
See also
Foam::vtk::GenericPatchWriter
Definition at line 63 of file foamVtkIndPatchGeoFieldsWriter.H.
surfaceMeshWriter
typedef indirectPatchGeoFieldsWriter surfaceMeshWriter
Definition at line 37 of file foamVtkSurfaceMeshWriter.H.
indirectPatchWriter
indirectPatchWriter
Write indirectPrimitivePatch faces/points (optionally with fields) as a vtp file or a legacy vtk file.
Definition at line 57 of file foamVtkIndPatchWriter.H.
uindirectPatchWriter
uindirectPatchWriter
Write uindirectPrimitivePatch faces/points (optionally with fields) as a vtp file or a legacy vtk file.
See also
Foam::vtk::GenericPatchWriter
Definition at line 61 of file foamVtkIndPatchWriter.H.
primitivePatchWriter
primitivePatchWriter
Write primitivePatch faces/points (optionally with fields) as a vtp file or a legacy vtk file.
See also
Foam::vtk::GenericPatchWriter
Definition at line 49 of file foamVtkPrimitivePatchWriter.H.
Enumeration Type Documentation
OutputContext
enum OutputContext : uint8_t
Enumerator
INLINE
Generate header and inline data.
HEADER
Generate header only.
APPEND
Generate append-data.
Definition at line 51 of file foamVtkCore.H.
formatType
enum class formatType : uint8_t strong
Enumerator
INLINE_ASCII
XML inline ASCII, asciiFormatter.
INLINE_BASE64
XML inline base64, base64Formatter.
APPEND_BASE64
XML append base64, appendBase64Formatter.
APPEND_BINARY
XML append raw binary, appendRawFormatter.
LEGACY_ASCII
Legacy ASCII, legacyAsciiFormatter.
LEGACY_BINARY
Legacy raw binary, legacyRawFormatter.
Definition at line 61 of file foamVtkCore.H.
cellType
enum cellType : uint8_t
Enumerator
VTK_EMPTY_CELL
VTK_VERTEX
VTK_POLY_VERTEX
VTK_LINE
VTK_POLY_LINE
VTK_TRIANGLE
VTK_TRIANGLE_STRIP
VTK_POLYGON
VTK_PIXEL
VTK_QUAD
VTK_TETRA
VTK_VOXEL
VTK_HEXAHEDRON
VTK_WEDGE
VTK_PYRAMID
VTK_PENTAGONAL_PRISM
VTK_HEXAGONAL_PRISM
VTK_POLYHEDRON
Definition at line 85 of file foamVtkCore.H.
fileTag
enum class fileTag : uint8_t strong
Enumerator
VTK_FILE
"VTKFile"
DATA_ARRAY
"DataArray"
BLOCK
"Block"
PIECE
"Piece"
DATA_SET
"DataSet"
POINTS
"Points"
CELLS
"Cells"
POLYS
"Polys"
VERTS
"Verts"
LINES
"Lines"
CELL_DATA
"CellData"
POINT_DATA
"PointData"
FIELD_DATA
"FieldData"
POLY_DATA
"PolyData"
UNSTRUCTURED_GRID
"UnstructuredGrid"
MULTI_BLOCK
"vtkMultiBlockDataSet"
Definition at line 109 of file foamVtkCore.H.
fileAttr
enum class fileAttr : uint8_t strong
Enumerator
OFFSET
"offset"
NUMBER_OF_COMPONENTS
"NumberOfComponents"
NUMBER_OF_TUPLES
"NumberOfTuples"
NUMBER_OF_POINTS
"NumberOfPoints"
NUMBER_OF_CELLS
"NumberOfCells"
NUMBER_OF_POLYS
"NumberOfPolys"
NUMBER_OF_VERTS
"NumberOfVerts"
NUMBER_OF_LINES
"NumberOfLines"
Definition at line 139 of file foamVtkCore.H.
dataArrayAttr
enum class dataArrayAttr : uint8_t strong
Enumerator
POINTS
"Points"
OFFSETS
"offsets"
CONNECTIVITY
"connectivity"
TYPES
"types"
FACES
"faces"
FACEOFFSETS
"faceoffsets"
Definition at line 155 of file foamVtkCore.H.
Function Documentation
isAppend()
bool isAppend (enum formatType fmt) inline noexcept
Definition at line 72 of file foamVtkCore.H.
isLegacy()
bool isLegacy (enum formatType fmt) inline noexcept
Definition at line 78 of file foamVtkCore.H.
sizeofData()
template<class Type , direction nComp = 1> uint64_t sizeofData (label count) inline
Definition at line 547 of file foamVtkFormatter.H.
newFormatter() [1/2]
Foam::autoPtr< Foam::vtk::formatter > newFormatter (std::ostream & os, unsigned prec = IOstream::defaultPrecision())
Definition at line 41 of file foamVtkOutput.C.
References os().
Referenced by outputOptions::newFormatter(), vtmWriter::write(), lumpedPointMovement::writeForcesAndMomentsVTP(), and lumpedPointState::writeVTP().
newFormatter() [2/2]
Foam::autoPtr< Foam::vtk::formatter > newFormatter (std::ostream & os, const enum formatType fmtType, unsigned prec = IOstream::defaultPrecision())
Definition at line 48 of file foamVtkOutput.C.
References os().
writeIdentity()
void writeIdentity (vtk::formatter & fmt, const label len, label start = 0)
Definition at line 88 of file foamVtkOutput.C.
References formatter::write().
Referenced by lumpedPointMovement::writeForcesAndMomentsVTP(), and lumpedPointState::writeVTP().
writeList() [1/5]
void writeList (vtk::formatter & fmt, const UList< uint8_t > & values)
Definition at line 104 of file foamVtkOutput.C.
References formatter::write().
Referenced by patchWriter::write(), internalWriter::write(), patchWriter::write(), patchWriter::write(), surfaceFieldWriter::write(), fileWriter::writeBasicField(), internalMeshWriter::writeCellData(), VTKsurfaceFormatCore::writeCellData(), VTPsurfaceFormatCore::writeCellData(), internalMeshWriter::writeCellIDs(), lumpedPointMovement::writeForcesAndMomentsVTP(), surfaceFieldWriter::writeGeometry(), lagrangianWriter::writeGeometry(), VTKsurfaceFormatCore::writeHeader(), VTPsurfaceFormatCore::writeHeader(), internalMeshWriter::writePointData(), coordSetWriter::writePointData(), internalMeshWriter::writePointIDs(), patchMeshWriter::writePoints(), patchMeshWriter::writePolys(), patchMeshWriter::writePolysLegacy(), and lumpedPointState::writeVTP().
write() [1/2]
template<class Type > void write (vtk::formatter & fmt, const Type & val, const label n = 1) inline
Definition at line 28 of file foamVtkOutputTemplates.C.
References Foam::component(), n, and formatter::write().
Referenced by internalWriter::write(), VTKsurfaceFormatCore::writeCellData(), VTPsurfaceFormatCore::writeCellData(), patchMeshWriter::writeNeighIDs(), patchMeshWriter::writePatchIDs(), fileWriter::writeProcIDs(), fileWriter::writeUniform(), and lumpedPointState::writeVTP().
writeValueParallel()
template<class Type > void writeValueParallel (vtk::formatter & fmt, const Type & val, const label count = 1) inline
Definition at line 120 of file foamVtkOutputTemplates.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and forAll.
Referenced by fileWriter::writeUniform().
writeList() [2/5]
template<class Type > void writeList (vtk::formatter & fmt, const UList< Type > & values)
Definition at line 48 of file foamVtkOutputTemplates.C.
writeList() [3/5]
template<class Type , unsigned N> void writeList (vtk::formatter & fmt, const FixedList< Type, N > & values)
Definition at line 62 of file foamVtkOutputTemplates.C.
writeList() [4/5]
template<class Type > void writeList (vtk::formatter & fmt, const UList< Type > & values, const labelUList & addressing)
Definition at line 76 of file foamVtkOutputTemplates.C.
writeList() [5/5]
template<class Type > void writeList (vtk::formatter & fmt, const UList< Type > & values, const bitSet & selected)
Definition at line 91 of file foamVtkOutputTemplates.C.
writeLists()
template<class Type > void writeLists (vtk::formatter & fmt, const UList< Type > & values1, const UList< Type > & values2, const labelUList & addressing)
Definition at line 106 of file foamVtkOutputTemplates.C.
Referenced by internalWriter::write(), and internalWriter::write().
writeListParallel() [1/4]
template<class Type > void writeListParallel (vtk::formatter & fmt, const UList< Type > & values)
Definition at line 151 of file foamVtkOutputTemplates.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and procAddr().
Referenced by surfaceFieldWriter::write(), fileWriter::writeBasicField(), internalMeshWriter::writeCellData(), internalMeshWriter::writeCellIDs(), vtkCloud::writeFields(), surfaceFieldWriter::writeGeometry(), lagrangianWriter::writeGeometry(), internalMeshWriter::writePointData(), internalMeshWriter::writePointIDs(), patchMeshWriter::writePolys(), and patchMeshWriter::writePolysLegacy().
writeListParallel() [2/4]
void writeListParallel (vtk::formatter & fmt, const UList< label > & values, const globalIndex & procOffset)
Definition at line 118 of file foamVtkOutput.C.
References procAddr().
writeListParallel() [3/4]
template<class Type > void writeListParallel (vtk::formatter & fmt, const UList< Type > & values, const labelUList & addressing)
Definition at line 213 of file foamVtkOutputTemplates.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, procAddr(), and UPtrList< T >::size().
writeListParallel() [4/4]
template<class Type > void writeListParallel (vtk::formatter & fmt, const UList< Type > & values, const bitSet & selected)
Definition at line 282 of file foamVtkOutputTemplates.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, procAddr(), UPtrList< T >::size(), and Foam::subset().
writeListsParallel() [1/2]
template<class Type > void writeListsParallel (vtk::formatter & fmt, const UList< Type > & values1, const UList< Type > & values2)
Definition at line 352 of file foamVtkOutputTemplates.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::max(), and UPtrList< T >::size().
Referenced by internalWriter::write(), internalWriter::write(), and internalWriter::write().
writeListsParallel() [2/2]
template<class Type > void writeListsParallel (vtk::formatter & fmt, const UList< Type > & values1, const UList< Type > & values2, const labelUList & addressing)
Definition at line 448 of file foamVtkOutputTemplates.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::max(), and UPtrList< T >::size().
write< label >()
template<> void write< label > (vtk::formatter & fmt, const label & val, const label n) inline
Definition at line 32 of file foamVtkOutputI.H.
References n, and formatter::write().
write< float >()
template<> void write< float > (vtk::formatter & fmt, const float & val, const label n) inline
Definition at line 45 of file foamVtkOutputI.H.
References n, and formatter::write().
write< double >()
template<> void write< double > (vtk::formatter & fmt, const double & val, const label n) inline
Definition at line 58 of file foamVtkOutputI.H.
References n, and formatter::write().
write() [2/2]
template<> void write (vtk::formatter & fmt, const symmTensor & val, const label n) inline
Definition at line 73 of file foamVtkOutputI.H.
References Foam::component(), n, formatter::write(), SymmTensor< scalar >::XX, SymmTensor< scalar >::XY, SymmTensor< scalar >::XZ, SymmTensor< scalar >::YY, SymmTensor< scalar >::YZ, and SymmTensor< scalar >::ZZ.
writeTopoSet()
bool writeTopoSet (const polyMesh & mesh, const topoSet & set, const vtk::outputOptions opts, const fileName & file, bool parallel = UPstream::parRun())
Definition at line 30 of file foamVtkWriteTopoSet.C.
References Foam::endl(), mesh, Foam::nl, and WarningInFunction.
writeFaceSet()
bool writeFaceSet (const polyMesh & mesh, const faceSet & set, const vtk::outputOptions opts, const fileName & file, bool parallel = UPstream::parRun())
Definition at line 29 of file foamVtkWriteFaceSet.C.
References globalIndex::localStart(), mesh, pp(), and writer().
writeCellSetFaces()
bool writeCellSetFaces (const polyMesh & mesh, const cellSet & set, const vtk::outputOptions opts, const fileName & file, bool parallel = UPstream::parRun())
Definition at line 29 of file foamVtkWriteCellSetFaces.C.
References forAll, globalIndex::localStart(), mesh, pp(), UPtrList< T >::size(), and writer().
writePointSet()
bool writePointSet (const polyMesh & mesh, const pointSet & set, const vtk::outputOptions opts, const fileName & file, bool parallel = UPstream::parRun())
Definition at line 30 of file foamVtkWritePointSet.C.
References outputOptions::append(), format(), fileName::has_ext(), outputOptions::legacy(), fileName::lessExt(), mesh, mkDir(), outputOptions::newFormatter(), fileName::path(), pointLabels(), Foam::reduce(), and UPtrList< T >::size().
Variable Documentation
fileExtension
const Foam::Enum< Foam::vtk::fileTag > fileExtension extern
Referenced by vtmWriter::append(), vtmWriter::ext(), outputOptions::ext(), surfaceFieldWriter::ext(), lagrangianWriter::ext(), and fileWriter::open().
fileContentVersions
const Foam::Enum< Foam::vtk::fileTag > fileContentVersions extern
Referenced by formatter::beginVTKFile(), and formatter::beginVTKFile().
fileTagNames
const Foam::Enum< Foam::vtk::fileTag > fileTagNames extern
Referenced by formatter::beginVTKFile(), formatter::beginVTKFile(), formatter::beginVTKFile(), formatter::endTag(), fileWriter::exit_File(), formatter::openTag(), and formatter::tag().
fileAttrNames
const Foam::Enum< Foam::vtk::fileAttr > fileAttrNames extern
Referenced by formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), and formatter::xmlAttr().
dataArrayAttrNames
const Foam::Enum< Foam::vtk::dataArrayAttr > dataArrayAttrNames extern
Referenced by formatter::beginDataArray().