OpenFOAM: Foam::PstreamGlobals Namespace Reference
Foam::PstreamGlobals Namespace Reference
Global functions and variables for working with parallel streams, but principally for MPI.
Functions
void checkCommunicator (const label comm, const label toProcNo)
void reset_request (UPstream::Request *requestPtr, label *requestIdx=nullptr)
void push_request (MPI_Request request, UPstream::Request *requestPtr=nullptr, label *requestIdx=nullptr)
Variables
DynamicList< bool > pendingMPIFree_
DynamicList< MPI_Comm > MPICommunicators_
DynamicList< MPI_Request > outstandingRequests_
Detailed Description
Global functions and variables for working with parallel streams, but principally for MPI.
Source files
PstreamGlobals.H
PstreamGlobals.C
Function Documentation
checkCommunicator()
void checkCommunicator (const label comm, const label toProcNo)
Definition at line 33 of file PstreamGlobals.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and UPtrList< T >::size().
reset_request()
void reset_request (UPstream::Request * requestPtr, label * requestIdx = nullptr) inline
Definition at line 84 of file PstreamGlobals.H.
push_request()
void push_request (MPI_Request request, UPstream::Request * requestPtr = nullptr, label * requestIdx = nullptr) inline
Definition at line 101 of file PstreamGlobals.H.
References outstandingRequests_, PtrList< T >::push_back(), and UPtrList< T >::size().
Variable Documentation
pendingMPIFree_
Foam::DynamicList< bool > pendingMPIFree_ extern
Definition at line 26 of file PstreamGlobals.C.
MPICommunicators_
Foam::DynamicList< MPI_Comm > MPICommunicators_ extern
Definition at line 27 of file PstreamGlobals.C.
outstandingRequests_
Foam::DynamicList< MPI_Request > outstandingRequests_ extern
Definition at line 28 of file PstreamGlobals.C.
Referenced by push_request().