OpenFOAM: Foam::fac Namespace Reference
Foam::fac Namespace Reference
Functions
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > average (const GeometricField< Type, faePatchField, edgeMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > average (const tmp< GeometricField< Type, faePatchField, edgeMesh > > &tssf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > average (const GeometricField< Type, faPatchField, areaMesh > &vtf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > average (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvtf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > d2dt2 (const dimensioned< Type > dt, const faMesh &mesh)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > d2dt2 (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > d2dt2 (const dimensionedScalar &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > d2dt2 (const areaScalarField &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > ddt (const dimensioned< Type > dt, const faMesh &mesh)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > ddt (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > ddt (const dimensionedScalar &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > ddt (const areaScalarField &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const GeometricField< Type, faePatchField, edgeMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const tmp< GeometricField< Type, faePatchField, edgeMesh > > &tssf)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > div (const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > div (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvvf, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > div (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > div (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvvf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const edgeScalarField &flux, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const tmp< edgeScalarField > &tflux, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const edgeScalarField &flux, const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const tmp< edgeScalarField > &tflux, const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const edgeScalarField &flux, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const tmp< edgeScalarField > &tflux, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const edgeScalarField &flux, const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const tmp< edgeScalarField > &tflux, const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > edgeIntegrate (const GeometricField< Type, faePatchField, edgeMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > edgeIntegrate (const tmp< GeometricField< Type, faePatchField, edgeMesh > > &tssf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > edgeSum (const GeometricField< Type, faePatchField, edgeMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > edgeSum (const tmp< GeometricField< Type, faePatchField, edgeMesh > > &tssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const GeometricField< Type, faePatchField, edgeMesh > &ssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const tmp< GeometricField< Type, faePatchField, edgeMesh > > &tssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const dimensionedScalar &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const dimensionedScalar &gamma, const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const dimensionedScalar &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const dimensionedScalar &gamma, const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const areaScalarField &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > &tgamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const areaScalarField &gamma, const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > &tgamma, const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const areaScalarField &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > &tgamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const areaScalarField &gamma, const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > &tgamma, const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const GeometricField< Type, faePatchField, edgeMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const tmp< GeometricField< Type, faePatchField, edgeMesh > > &tssf)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > ndiv (const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > ndiv (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvvf, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > ndiv (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > ndiv (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvvf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const edgeScalarField &flux, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > &tflux, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const edgeScalarField &flux, const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > &tflux, const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const edgeScalarField &flux, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > &tflux, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const edgeScalarField &flux, const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > &tflux, const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > ngrad (const GeometricField< Type, faePatchField, edgeMesh > &ssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > ngrad (const tmp< GeometricField< Type, faePatchField, edgeMesh > > &tssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > ngrad (const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > ngrad (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > ngrad (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > ngrad (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf)
template<class Type >
static tmp< edgeInterpolationScheme< Type > > scheme (const edgeScalarField &faceFlux, Istream &schemeData)
template<class Type >
static tmp< edgeInterpolationScheme< Type > > scheme (const edgeScalarField &faceFlux, const word &name)
template<class Type >
static tmp< edgeInterpolationScheme< Type > > scheme (const faMesh &mesh, Istream &schemeData)
template<class Type >
static tmp< edgeInterpolationScheme< Type > > scheme (const faMesh &mesh, const word &name)
template<class Type >
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &tvf, const edgeScalarField &faceFlux, Istream &schemeData)
template<class Type >
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &tvf, const edgeScalarField &faceFlux, const word &name)
template<class Type >
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf, const edgeScalarField &faceFlux, const word &name)
template<class Type >
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &tvf, const tmp< edgeScalarField > &faceFlux, const word &name)
template<class Type >
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf, const tmp< edgeScalarField > &faceFlux, const word &name)
template<class Type >
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &tvf, Istream &schemeData)
template<class Type >
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &tvf, const word &name)
template<class Type >
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf, const word &name)
template<class Type >
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh > > &tvf)
template<class Type >
static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &tvf)
Function Documentation
average() [1/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > average (const GeometricField< Type, faePatchField, edgeMesh > & ssf)
Definition at line 39 of file facAverage.C.
References edgeSum(), forAll, mesh, IOobjectOption::NO_READ, and IOobjectOption::NO_WRITE.
Referenced by average(), average(), and average().
average() [2/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > average (const tmp< GeometricField< Type, faePatchField, edgeMesh > > & tssf)
Definition at line 83 of file facAverage.C.
References average(), and PtrList< T >::clear().
average() [3/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > average (const GeometricField< Type, faPatchField, areaMesh > & vtf)
Definition at line 99 of file facAverage.C.
References average(), and Foam::linearEdgeInterpolate().
average() [4/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > average (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvtf)
Definition at line 110 of file facAverage.C.
References average(), and PtrList< T >::clear().
d2dt2() [1/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > d2dt2 (const dimensioned< Type > dt, const faMesh & mesh)
Definition at line 38 of file facD2dt2.C.
References mesh, and faD2dt2Scheme< Type >::New().
Referenced by KirchhoffShell::solveDisplacement().
d2dt2() [2/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > d2dt2 (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 53 of file facD2dt2.C.
References faD2dt2Scheme< Type >::New().
d2dt2() [3/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > d2dt2 (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 67 of file facD2dt2.C.
References faD2dt2Scheme< Type >::New(), and rho.
d2dt2() [4/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > d2dt2 (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 85 of file facD2dt2.C.
References faD2dt2Scheme< Type >::New(), and rho.
ddt() [1/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > ddt (const dimensioned< Type > dt, const faMesh & mesh)
Definition at line 39 of file facDdt.C.
References mesh, and faDdtScheme< Type >::New().
Referenced by KirchhoffShell::solveDisplacement().
ddt() [2/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > ddt (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 55 of file facDdt.C.
References faDdtScheme< Type >::New().
ddt() [3/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > ddt (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 70 of file facDdt.C.
References faDdtScheme< Type >::New(), and rho.
ddt() [4/4]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > ddt (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 89 of file facDdt.C.
References faDdtScheme< Type >::New(), and rho.
div() [1/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > div (const GeometricField< Type, faePatchField, edgeMesh > & ssf)
Definition at line 42 of file facDiv.C.
References edgeIntegrate(), Tensor< scalar >::I, n, Foam::sqr(), and Foam::transform().
Referenced by div(), div(), div(), div(), div(), div(), div(), div(), div(), div(), div(), gaussLaplacianScheme< Type >::facLaplacian(), gaussLaplacianScheme< Type >::facLaplacian(), gaussLaplacianScheme< Type >::famLaplacian(), interfaceTrackingFvMesh::freeSurfaceSnGradU(), and interfaceTrackingFvMesh::freeSurfaceSnGradUn().
div() [2/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > div (const tmp< GeometricField< Type, faePatchField, edgeMesh > > & tssf)
Definition at line 64 of file facDiv.C.
References PtrList< T >::clear(), and div().
div() [3/14]
template<class Type > tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > div (const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 83 of file facDiv.C.
References divScheme< Type >::facDiv(), Tensor< scalar >::I, n, Foam::name(), Foam::sqr(), and Foam::transform().
div() [4/14]
template<class Type > tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > div (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvvf, const word & name)
Definition at line 130 of file facDiv.C.
References PtrList< T >::clear(), div(), and Foam::name().
div() [5/14]
template<class Type > tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > div (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 153 of file facDiv.C.
References div().
div() [6/14]
template<class Type > tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > div (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvvf)
Definition at line 170 of file facDiv.C.
References PtrList< T >::clear(), and div().
div() [7/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > div (const edgeScalarField & flux, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 188 of file facDiv.C.
References convectionScheme< Type >::facDiv(), Tensor< scalar >::I, n, Foam::name(), Foam::sqr(), and Foam::transform().
div() [8/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > div (const tmp< edgeScalarField > & tflux, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 218 of file facDiv.C.
References PtrList< T >::clear(), div(), and Foam::name().
div() [9/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > div (const edgeScalarField & flux, const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf, const word & name)
Definition at line 236 of file facDiv.C.
References PtrList< T >::clear(), div(), and Foam::name().
div() [10/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > div (const tmp< edgeScalarField > & tflux, const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf, const word & name)
Definition at line 254 of file facDiv.C.
References PtrList< T >::clear(), div(), and Foam::name().
div() [11/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > div (const edgeScalarField & flux, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 273 of file facDiv.C.
References div().
div() [12/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > div (const tmp< edgeScalarField > & tflux, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 288 of file facDiv.C.
References PtrList< T >::clear(), and div().
div() [13/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > div (const edgeScalarField & flux, const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf)
Definition at line 305 of file facDiv.C.
References PtrList< T >::clear(), and div().
div() [14/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > div (const tmp< edgeScalarField > & tflux, const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf)
Definition at line 322 of file facDiv.C.
References PtrList< T >::clear(), and div().
edgeIntegrate() [1/2]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > edgeIntegrate (const GeometricField< Type, faePatchField, edgeMesh > & ssf)
Definition at line 39 of file facEdgeIntegrate.C.
References Foam::dimArea, forAll, mesh, Foam::Zero, and faPatchFieldBase::zeroGradientType().
Referenced by gaussGrad< Type >::calcGrad(), div(), edgeIntegrate(), gaussConvectionScheme< Type >::facDiv(), gaussDivScheme< Type >::facDiv(), gaussConvectionScheme< Type >::famDiv(), gaussGrad< Type >::gradf(), ndiv(), and ngrad().
edgeIntegrate() [2/2]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > edgeIntegrate (const tmp< GeometricField< Type, faePatchField, edgeMesh > > & tssf)
Definition at line 95 of file facEdgeIntegrate.C.
References PtrList< T >::clear(), and edgeIntegrate().
edgeSum() [1/2]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > edgeSum (const GeometricField< Type, faePatchField, edgeMesh > & ssf)
Definition at line 111 of file facEdgeIntegrate.C.
References forAll, mesh, Foam::Zero, and faPatchFieldBase::zeroGradientType().
Referenced by average(), and edgeSum().
edgeSum() [2/2]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > edgeSum (const tmp< GeometricField< Type, faePatchField, edgeMesh > > & tssf)
Definition at line 164 of file facEdgeIntegrate.C.
References PtrList< T >::clear(), and edgeSum().
grad() [1/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const GeometricField< Type, faePatchField, edgeMesh > & ssf)
Definition at line 50 of file facGrad.C.
References gaussGrad< Type >::gradf().
Referenced by jouleHeatingSource::addSup(), contactAngleForce::correct(), kinematicThinFilm::evolveRegion(), interfaceTrackingFvMesh::freeSurfaceSnGradU(), grad(), grad(), grad(), grad(), grad(), interfaceTrackingFvMesh::surfaceTensionGrad(), and faNVDscheme< Type, NVDweight >::weights().
grad() [2/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const tmp< GeometricField< Type, faePatchField, edgeMesh > > & tssf)
Definition at line 67 of file facGrad.C.
References PtrList< T >::clear(), and grad().
grad() [3/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 90 of file facGrad.C.
References grad(), Foam::name(), and gradScheme< Type >::New().
grad() [4/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf, const word & name)
Definition at line 112 of file facGrad.C.
References PtrList< T >::clear(), grad(), and Foam::name().
grad() [5/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 141 of file facGrad.C.
References grad().
grad() [6/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > grad (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf)
Definition at line 158 of file facGrad.C.
References PtrList< T >::clear(), and grad().
laplacian() [1/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 39 of file facLaplacian.C.
References Foam::name(), and laplacianScheme< Type >::New().
Referenced by liquidFilmModel::correctThermoFields(), kinematicThinFilm::evolveRegion(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), and KirchhoffShell::solveDisplacement().
laplacian() [2/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf, const word & name)
Definition at line 54 of file facLaplacian.C.
References PtrList< T >::clear(), laplacian(), and Foam::name().
laplacian() [3/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 71 of file facLaplacian.C.
References laplacian().
laplacian() [4/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf)
Definition at line 81 of file facLaplacian.C.
References PtrList< T >::clear(), and laplacian().
laplacian() [5/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const dimensionedScalar & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 97 of file facLaplacian.C.
References gamma, laplacian(), and Foam::name().
laplacian() [6/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const dimensionedScalar & gamma, const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf, const word & name)
Definition at line 109 of file facLaplacian.C.
References PtrList< T >::clear(), gamma, laplacian(), and Foam::name().
laplacian() [7/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const dimensionedScalar & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 127 of file facLaplacian.C.
References gamma, and laplacian().
laplacian() [8/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const dimensionedScalar & gamma, const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf)
Definition at line 141 of file facLaplacian.C.
References PtrList< T >::clear(), gamma, and laplacian().
laplacian() [9/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const areaScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 158 of file facLaplacian.C.
References gamma, Foam::name(), and laplacianScheme< Type >::New().
laplacian() [10/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > & tgamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 174 of file facLaplacian.C.
References PtrList< T >::clear(), laplacian(), and Foam::name().
laplacian() [11/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const areaScalarField & gamma, const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf, const word & name)
Definition at line 191 of file facLaplacian.C.
References PtrList< T >::clear(), gamma, laplacian(), and Foam::name().
laplacian() [12/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > & tgamma, const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf, const word & name)
Definition at line 208 of file facLaplacian.C.
References PtrList< T >::clear(), laplacian(), and Foam::name().
laplacian() [13/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const areaScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 227 of file facLaplacian.C.
References gamma, and laplacian().
laplacian() [14/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > & tgamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 243 of file facLaplacian.C.
References laplacian(), and Foam::name().
laplacian() [15/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const areaScalarField & gamma, const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf)
Definition at line 259 of file facLaplacian.C.
References gamma, laplacian(), and Foam::name().
laplacian() [16/16]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > & tgamma, const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf)
Definition at line 275 of file facLaplacian.C.
References laplacian(), and Foam::name().
lnGrad() [1/4]
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 39 of file facLnGrad.C.
References Foam::name(), and lnGradScheme< Type >::New().
Referenced by kinematicThinFilm::evolveRegion(), lnGrad(), lnGrad(), and lnGrad().
lnGrad() [2/4]
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf, const word & name)
Definition at line 55 of file facLnGrad.C.
References PtrList< T >::clear(), lnGrad(), and Foam::name().
lnGrad() [3/4]
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 72 of file facLnGrad.C.
References lnGrad().
lnGrad() [4/4]
template<class Type > tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf)
Definition at line 83 of file facLnGrad.C.
References PtrList< T >::clear(), and lnGrad().
ndiv() [1/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const GeometricField< Type, faePatchField, edgeMesh > & ssf)
Definition at line 42 of file facNDiv.C.
References edgeIntegrate(), and n.
Referenced by ndiv(), ndiv(), ndiv(), ndiv(), ndiv(), ndiv(), ndiv(), ndiv(), ndiv(), ndiv(), and ndiv().
ndiv() [2/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const tmp< GeometricField< Type, faePatchField, edgeMesh > > & tssf)
Definition at line 63 of file facNDiv.C.
References PtrList< T >::clear(), and ndiv().
ndiv() [3/14]
template<class Type > tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > ndiv (const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 82 of file facNDiv.C.
References divScheme< Type >::facDiv(), n, and Foam::name().
ndiv() [4/14]
template<class Type > tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > ndiv (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvvf, const word & name)
Definition at line 114 of file facNDiv.C.
References PtrList< T >::clear(), Foam::name(), and ndiv().
ndiv() [5/14]
template<class Type > tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > ndiv (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 138 of file facNDiv.C.
References ndiv().
ndiv() [6/14]
template<class Type > tmp< GeometricField< typename innerProduct< vector, Type >::type, faPatchField, areaMesh > > ndiv (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvvf)
Definition at line 155 of file facNDiv.C.
References PtrList< T >::clear(), and ndiv().
ndiv() [7/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const edgeScalarField & flux, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 173 of file facNDiv.C.
References convectionScheme< Type >::facDiv(), n, and Foam::name().
ndiv() [8/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > & tflux, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 204 of file facNDiv.C.
References PtrList< T >::clear(), Foam::name(), and ndiv().
ndiv() [9/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const edgeScalarField & flux, const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf, const word & name)
Definition at line 223 of file facNDiv.C.
References PtrList< T >::clear(), Foam::name(), and ndiv().
ndiv() [10/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > & tflux, const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf, const word & name)
Definition at line 242 of file facNDiv.C.
References PtrList< T >::clear(), Foam::name(), and ndiv().
ndiv() [11/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const edgeScalarField & flux, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 262 of file facNDiv.C.
References ndiv().
ndiv() [12/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > & tflux, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 277 of file facNDiv.C.
References PtrList< T >::clear(), and ndiv().
ndiv() [13/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const edgeScalarField & flux, const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf)
Definition at line 294 of file facNDiv.C.
References PtrList< T >::clear(), and ndiv().
ndiv() [14/14]
template<class Type > tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > & tflux, const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf)
Definition at line 311 of file facNDiv.C.
References PtrList< T >::clear(), and ndiv().
ngrad() [1/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > ngrad (const GeometricField< Type, faePatchField, edgeMesh > & ssf)
Definition at line 49 of file facNGrad.C.
References edgeIntegrate(), and n.
Referenced by ngrad(), ngrad(), ngrad(), and ngrad().
ngrad() [2/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > ngrad (const tmp< GeometricField< Type, faePatchField, edgeMesh > > & tssf)
Definition at line 77 of file facNGrad.C.
References PtrList< T >::clear(), and ngrad().
ngrad() [3/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > ngrad (const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 101 of file facNGrad.C.
References n, Foam::name(), and gradScheme< Type >::New().
ngrad() [4/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > ngrad (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf, const word & name)
Definition at line 134 of file facNGrad.C.
References PtrList< T >::clear(), Foam::name(), and ngrad().
ngrad() [5/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > ngrad (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 164 of file facNGrad.C.
References ngrad().
ngrad() [6/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, faPatchField, areaMesh > > ngrad (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf)
Definition at line 181 of file facNGrad.C.
References PtrList< T >::clear(), and ngrad().
scheme() [1/4]
template<class Type > static tmp< edgeInterpolationScheme< Type > > scheme (const edgeScalarField & faceFlux, Istream & schemeData) static
scheme() [2/4]
template<class Type > static tmp< edgeInterpolationScheme< Type > > scheme (const edgeScalarField & faceFlux, const word & name) static
scheme() [3/4]
template<class Type > static tmp< edgeInterpolationScheme< Type > > scheme (const faMesh & mesh, Istream & schemeData) static
scheme() [4/4]
template<class Type > static tmp< edgeInterpolationScheme< Type > > scheme (const faMesh & mesh, const word & name) static
interpolate() [1/10]
template<class Type > static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > & tvf, const edgeScalarField & faceFlux, Istream & schemeData) static
Referenced by kinematicThinFilm::evolveRegion().
interpolate() [2/10]
template<class Type > static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > & tvf, const edgeScalarField & faceFlux, const word & name) static
interpolate() [3/10]
template<class Type > static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf, const edgeScalarField & faceFlux, const word & name) static
interpolate() [4/10]
template<class Type > static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > & tvf, const tmp< edgeScalarField > & faceFlux, const word & name) static
interpolate() [5/10]
template<class Type > static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf, const tmp< edgeScalarField > & faceFlux, const word & name) static
interpolate() [6/10]
template<class Type > static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > & tvf, Istream & schemeData) static
interpolate() [7/10]
template<class Type > static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > & tvf, const word & name) static
interpolate() [8/10]
template<class Type > static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf, const word & name) static
interpolate() [9/10]
template<class Type > static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh > > & tvf) static
interpolate() [10/10]
template<class Type > static tmp< GeometricField< Type, faePatchField, edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > & tvf) static