OpenFOAM: Foam::BitSetOps Namespace Reference
Foam::BitSetOps Namespace Reference
Factory and other methods for bitSet. Adaptor methods for other containers that are somewhat similar to bitSet (eg, boolList, labelHashSet).
Functions
bitSet create (const label n, const labelHashSet &locations, const bool on=true)
bitSet create (const label n, const labelUList &locations, const bool on=true)
bitSet create (const label n, const label select, const labelUList &values, const bool on=true)
Detailed Description
Factory and other methods for bitSet. Adaptor methods for other containers that are somewhat similar to bitSet (eg, boolList, labelHashSet).
Function Documentation
create() [1/3]
Foam::bitSet create (const label n, const labelHashSet & locations, const bool on = true)
Definition at line 227 of file BitOps.C.
References n, and bitSet::set().
Referenced by Foam::invertCellSelection(), fvMeshSubset::reset(), fvMeshSubset::reset(), and fvMeshSubset::reset().
create() [2/3]
Foam::bitSet create (const label n, const labelUList & locations, const bool on = true)
Definition at line 249 of file BitOps.C.
References n, and bitSet::set().
create() [3/3]
Foam::bitSet create (const label n, const label select, const labelUList & values, const bool on = true)
Definition at line 271 of file BitOps.C.
References n, and bitSet::set().