OpenFOAM: Foam::ensightOutput Namespace Reference
Foam::ensightOutput Namespace Reference
A collection of functions for writing ensight file content.
Namespaces
namespace Detail
Classes
class writerCaching
State information for writers with collated times.
Typedefs
typedef DynamicList< float > floatBufferType
Functions
template<class Type >
bool writeAreaField (ensightOutput::floatBufferType &scratch, ensightFile &os, const GeometricField< Type, faPatchField, areaMesh > &fld, const ensightFaMesh &ensMesh)
template<class Type >
bool writeAreaField (ensightFile &os, const GeometricField< Type, faPatchField, areaMesh > &fld, const ensightFaMesh &ensMesh)
template<class Type >
bool writeVolField (ensightOutput::floatBufferType &scratch, ensightFile &os, const GeometricField< Type, fvPatchField, volMesh > &vf, const ensightMesh &ensMesh)
template<class Type >
bool writeVolField (ensightFile &os, const GeometricField< Type, fvPatchField, volMesh > &vf, const ensightMesh &ensMesh)
template<class Type >
bool writeVolField (ensightOutput::floatBufferType &scratch, ensightFile &os, const GeometricField< Type, fvPatchField, volMesh > &vf, const ensightMesh &ensMesh, const bool nodeValues)
template<class Type >
bool writeVolField (ensightFile &os, const GeometricField< Type, fvPatchField, volMesh > &vf, const ensightMesh &ensMesh, const bool nodeValues)
template<class Type >
bool writePointField (ensightOutput::floatBufferType &scratch, ensightFile &os, const GeometricField< Type, pointPatchField, pointMesh > &pf, const ensightMesh &ensMesh)
template<class Type >
bool writePointField (ensightFile &os, const GeometricField< Type, pointPatchField, pointMesh > &pf, const ensightMesh &ensMesh)
void writeFaceList (ensightGeoFile &os, const UList< face > &faces, const label pointOffset=0)
void writeFaceList (ensightGeoFile &os, const UIndirectList< face > &faces, const label pointOffset=0)
void writeFaceList (ensightGeoFile &os, const CompactListList< label > &faces, const label pointOffset=0)
void writeCellShapes (ensightGeoFile &os, const UList< cellShape > &shapes, const label pointOffset=0)
void writePolysPoints (ensightGeoFile &os, const cellUList &meshCells, const labelUList &addr, const faceUList &meshFaces, const labelUList &faceOwner)
void writePolysPoints (ensightGeoFile &os, const polyMesh &mesh, const labelUList &addr, const labelList &pointMap)
void writeFaceConnectivity (ensightGeoFile &os, const ensightFaces::elemType etype, const label nTotal, const UIndirectList< face > &faces, bool parallel)
void writeFaceConnectivity (ensightGeoFile &os, const ensightFaces::elemType etype, const label nTotal, const faceUList &faces, bool parallel)
void writeFaceConnectivity (ensightGeoFile &os, const ensightFaces &part, const faceUList &faces, bool parallel)
void writeFaceConnectivityPresorted (ensightGeoFile &os, const ensightFaces &part, const faceUList &faces, bool parallel)
template<class Type >
bool writeField (ensightOutput::floatBufferType &scratch, ensightFile &os, const Field< Type > &fld, const ensightCells &part, bool parallel)
template<class Type >
bool writeField (ensightOutput::floatBufferType &scratch, ensightFile &os, const Field< Type > &fld, const ensightFaces &part, bool parallel)
template<class Type >
bool writeField (ensightFile &os, const Field< Type > &fld, const ensightCells &part, bool parallel)
template<class Type >
bool writeField (ensightFile &os, const Field< Type > &fld, const ensightFaces &part, bool parallel)
bool writeCloudPositions (ensightFile &os, const fvMesh &mesh, const word &cloudName, bool exists)
template<class Type >
bool writeCloudField (ensightFile &os, const IOField< Type > &field)
template<class Type >
bool readWriteCloudField (ensightFile &os, const IOobject &fieldObject, bool existsAny)
Variables
int debug
int maxChunk_
Detailed Description
A collection of functions for writing ensight file content.
Source files
ensightOutput.H
ensightOutput.C
ensightOutputTemplates.C
Typedef Documentation
floatBufferType
typedef DynamicList<float> floatBufferType
Definition at line 55 of file ensightOutputFwd.H.
Function Documentation
writeAreaField() [1/2]
template<class Type > bool writeAreaField (ensightOutput::floatBufferType & scratch, ensightFile & os, const GeometricField< Type, faPatchField, areaMesh > & fld, const ensightFaMesh & ensMesh)
Parameters
scratch Component scratch buffer
os Output file (must be valid on master)
fld The field content to be written
ensMesh The addressing into the field
Definition at line 28 of file ensightOutputAreaFieldTemplates.C.
References ensightFaMesh::areaPart(), fld(), and os().
Referenced by writeAreaField().
writeAreaField() [2/2]
template<class Type > bool writeAreaField (ensightFile & os, const GeometricField< Type, faPatchField, areaMesh > & fld, const ensightFaMesh & ensMesh)
Parameters
os Output file (must be valid on master)
fld The field content to be written
ensMesh The addressing into the field
Definition at line 74 of file ensightOutputAreaField.H.
References fld(), os(), and writeAreaField().
writeVolField() [1/4]
template<class Type > bool writeVolField (ensightOutput::floatBufferType & scratch, ensightFile & os, const GeometricField< Type, fvPatchField, volMesh > & vf, const ensightMesh & ensMesh)
Parameters
scratch Component scratch buffer
os Output file (must be valid on master)
vf The field content to be written
ensMesh The addressing (element-wise) into the field
Definition at line 34 of file ensightOutputVolFieldTemplates.C.
References ensightMesh::boundaryParts(), ensightMesh::cellZoneParts(), UPtrList< T >::empty(), faceId(), ensightFaces::faceIds(), ensightMesh::faceZoneParts(), forAll, forAllConstIters, Foam::linearInterpolate(), Foam::max(), mesh, os(), patchId(), pp(), UPtrList< T >::size(), and ensightFaces::size().
writeVolField() [2/4]
template<class Type > bool writeVolField (ensightFile & os, const GeometricField< Type, fvPatchField, volMesh > & vf, const ensightMesh & ensMesh)
Parameters
os Output file (must be valid on master)
vf The field content to be written
ensMesh The addressing (element-wise) into the field
Definition at line 74 of file ensightOutputVolField.H.
References os().
writeVolField() [3/4]
template<class Type > bool writeVolField (ensightOutput::floatBufferType & scratch, ensightFile & os, const GeometricField< Type, fvPatchField, volMesh > & vf, const ensightMesh & ensMesh, const bool nodeValues)
Parameters
scratch Component scratch buffer
os Output file (must be valid on master)
vf The field content to be written
ensMesh The addressing (element-wise) into the field
nodeValues Interpolate values to points
Definition at line 362 of file ensightOutputVolFieldTemplates.C.
References os().
writeVolField() [4/4]
template<class Type > bool writeVolField (ensightFile & os, const GeometricField< Type, fvPatchField, volMesh > & vf, const ensightMesh & ensMesh, const bool nodeValues)
Parameters
os Output file (must be valid on master)
vf The field content to be written
ensMesh The addressing (element-wise) into the field
nodeValues Interpolate values to points
Definition at line 116 of file ensightOutputVolField.H.
References os().
writePointField() [1/2]
template<class Type > bool writePointField (ensightOutput::floatBufferType & scratch, ensightFile & os, const GeometricField< Type, pointPatchField, pointMesh > & pf, const ensightMesh & ensMesh)
Parameters
scratch Component scratch buffer
os Output file (must be valid on master)
pf The field content to be written
ensMesh The addressing (element-wise) into the field
Definition at line 197 of file ensightOutputVolFieldTemplates.C.
References polyPatch::boundaryMesh(), ensightMesh::boundaryParts(), ensightMesh::cellZoneParts(), UPtrList< T >::empty(), ensightMesh::faceZoneParts(), ensightPart::index(), mesh, ensightMesh::mesh(), os(), patchId(), pp(), Foam::returnReduceAnd(), ensightCells::uniqueMeshPoints(), and ensightFaces::uniqueMeshPoints().
writePointField() [2/2]
template<class Type > bool writePointField (ensightFile & os, const GeometricField< Type, pointPatchField, pointMesh > & pf, const ensightMesh & ensMesh)
Parameters
os Output file (must be valid on master)
pf The field content to be written
ensMesh The addressing (element-wise) into the field
Definition at line 161 of file ensightOutputVolField.H.
References os().
writeFaceList() [1/3]
void writeFaceList (ensightGeoFile & os, const UList< face > & faces, const label pointOffset = 0)
Parameters
pointOffset Additional point offset for each face
Definition at line 175 of file ensightOutput.C.
References os().
Referenced by writeFaceConnectivity(), and writeFaceConnectivity().
writeFaceList() [2/3]
void writeFaceList (ensightGeoFile & os, const UIndirectList< face > & faces, const label pointOffset = 0)
Parameters
pointOffset Additional point offset for each face
Definition at line 186 of file ensightOutput.C.
References os().
writeFaceList() [3/3]
void writeFaceList (ensightGeoFile & os, const CompactListList< label > & faces, const label pointOffset = 0)
Parameters
pointOffset Additional point offset for each face
Definition at line 197 of file ensightOutput.C.
References os().
writeCellShapes()
void writeCellShapes (ensightGeoFile & os, const UList< cellShape > & shapes, const label pointOffset = 0)
Parameters
pointOffset Additional point offset
Definition at line 208 of file ensightOutput.C.
References os().
writePolysPoints() [1/2]
void writePolysPoints (ensightGeoFile & os, const cellUList & meshCells, const labelUList & addr, const faceUList & meshFaces, const labelUList & faceOwner)
Parameters
addr Cell ids to write
Definition at line 341 of file ensightOutput.C.
References cellId, f(), faceId(), os(), UPtrList< T >::size(), and UList< T >::size().
writePolysPoints() [2/2]
void writePolysPoints (ensightGeoFile & os, const polyMesh & mesh, const labelUList & addr, const labelList & pointMap)
const cellList& meshCells = mesh.cells();
Parameters
addr Cell ids to write
pointMap Point map to use
Definition at line 295 of file ensightOutput.C.
References cellId, f(), faceId(), mesh, os(), UPtrList< T >::size(), and UList< T >::size().
writeFaceConnectivity() [1/3]
void writeFaceConnectivity (ensightGeoFile & os, const ensightFaces::elemType etype, const label nTotal, const UIndirectList< face > & faces, bool parallel)
Parameters
parallel Prefer collective write?
Definition at line 474 of file ensightOutput.C.
References os(), and writeFaceList().
Referenced by ensightOutputSurface::write(), writeFaceConnectivity(), and writeFaceConnectivityPresorted().
writeFaceConnectivity() [2/3]
void writeFaceConnectivity (ensightGeoFile & os, const ensightFaces::elemType etype, const label nTotal, const faceUList & faces, bool parallel)
Parameters
parallel Prefer collective write?
Definition at line 383 of file ensightOutput.C.
References os(), and writeFaceList().
writeFaceConnectivity() [3/3]
void writeFaceConnectivity (ensightGeoFile & os, const ensightFaces & part, const faceUList & faces, bool parallel)
Parameters
parallel Prefer collective write?
Definition at line 567 of file ensightOutput.C.
References ensightFaces::faceIds(), os(), ensightFaces::total(), and writeFaceConnectivity().
writeFaceConnectivityPresorted()
void writeFaceConnectivityPresorted (ensightGeoFile & os, const ensightFaces & part, const faceUList & faces, bool parallel)
Parameters
parallel Prefer collective write?
Definition at line 591 of file ensightOutput.C.
References os(), ensightFaces::range(), ensightFaces::total(), and writeFaceConnectivity().
Referenced by ensightFaces::write().
writeField() [1/4]
template<class Type > bool writeField (ensightOutput::floatBufferType & scratch, ensightFile & os, const Field< Type > & fld, const ensightCells & part, bool parallel)
Parameters
scratch Component scratch buffer
os Output file (must be valid on master)
fld The field content to be written
part The addressing (element-wise) into the field
parallel Prefer collective write?
Definition at line 414 of file ensightOutputTemplates.C.
References ensightCells::cellIds(), fld(), ensightPart::index(), os(), Foam::returnReduceOr(), UPtrList< T >::size(), ensightCells::size(), and ensightCells::total().
Referenced by ensightOutputSurface::writeFaceData(), writeField(), and writeField().
writeField() [2/4]
template<class Type > bool writeField (ensightOutput::floatBufferType & scratch, ensightFile & os, const Field< Type > & fld, const ensightFaces & part, bool parallel)
Parameters
scratch Component scratch buffer
os Output file (must be valid on master)
fld The field content to be written
part The addressing (element-wise) into the field
parallel Prefer collective write?
Definition at line 467 of file ensightOutputTemplates.C.
References ensightFaces::faceIds(), fld(), ensightPart::index(), os(), Foam::returnReduceOr(), UPtrList< T >::size(), ensightFaces::size(), and ensightFaces::total().
writeField() [3/4]
template<class Type > bool writeField (ensightFile & os, const Field< Type > & fld, const ensightCells & part, bool parallel)
Parameters
os Output file (must be valid on master)
fld The field content to be written
part The addressing (element-wise) into the field
parallel Prefer collective write?
Definition at line 310 of file ensightOutput.H.
References fld(), os(), and writeField().
writeField() [4/4]
template<class Type > bool writeField (ensightFile & os, const Field< Type > & fld, const ensightFaces & part, bool parallel)
Parameters
os Output file (must be valid on master)
fld The field content to be written
part The addressing (element-wise) into the field
parallel Prefer collective write?
Definition at line 335 of file ensightOutput.H.
References fld(), os(), and writeField().
writeCloudPositions()
bool writeCloudPositions (ensightFile & os, const fvMesh & mesh, const word & cloudName, bool exists)
Parameters
os Output file (must be valid on master)
mesh The associated volume mesh
cloudName The name of the cloud
exists The processor-local existence
Definition at line 76 of file ensightOutputCloud.C.
References UPtrList< T >::begin(), cloudName(), Foam::exists(), mesh, Foam::narrowFloat(), os(), p, Foam::pos(), procAddr(), Foam::returnReduce(), UPtrList< T >::size(), Foam::writeMeasured_ascii(), and Foam::writeMeasured_binary().
writeCloudField()
template<class Type > bool writeCloudField (ensightFile & os, const IOField< Type > & field)
Parameters
os Output file (must be valid on master)
field The cloud field
Definition at line 63 of file ensightOutputCloudTemplates.C.
References field(), os(), procAddr(), and Foam::returnReduceAnd().
Referenced by readWriteCloudField().
readWriteCloudField()
template<class Type > bool readWriteCloudField (ensightFile & os, const IOobject & fieldObject, bool existsAny)
Parameters
os Output file (must be valid on master)
fieldObject The field object name/location for reading
existsAny Exists anywhere? May still be missing on a local processor
Definition at line 143 of file ensightOutputCloudTemplates.C.
References field(), io(), os(), and writeCloudField().
Variable Documentation
debug
int debug extern
Referenced by Foam::ensightOutput::Detail::writeFieldComponents().
maxChunk_
int maxChunk_ extern