OpenFOAM: Foam::constant::thermodynamic Namespace Reference
Foam::constant::thermodynamic Namespace Reference
Thermodynamic scalar constants.
Variables
const scalar RR = 1e3*physicoChemical::R.value()
const scalar Pstd = standard::Pstd.value()
const scalar Tstd = standard::Tstd.value()
Detailed Description
Thermodynamic scalar constants.
Variable Documentation
RR
const scalar RR = 1e3*physicoChemical::R.value()
Definition at line 39 of file thermodynamicConstants.C.
Referenced by SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), ReactingParcel< ParcelType >::calcPhaseChange(), LiquidEvaporation< CloudType >::calculate(), LiquidEvaporationBoil< CloudType >::calculate(), ReactingParcel< ParcelType >::correctSurfaceValues(), thermo< Thermo, Type >::dKcdTbyKc(), thermo< Thermo, Type >::K(), thermo< Thermo, Type >::Kc(), liquidMixtureProperties::Ppc(), and specie::R().
Pstd
const scalar Pstd = standard::Pstd.value()
Definition at line 41 of file thermodynamicConstants.C.
Referenced by thermo< Thermo, Type >::dKcdTbyKc(), thermo< Thermo, Type >::K(), thermo< Thermo, Type >::Kc(), thermo< Thermo, Type >::Kn(), thermo< Thermo, Type >::Kx(), perfectFluid< Specie >::S(), and perfectGas< Specie >::S().
Tstd
const scalar Tstd = standard::Tstd.value()
Definition at line 42 of file thermodynamicConstants.C.
Referenced by hPowerThermo< EquationOfState >::Gstd(), janafThermo< EquationOfState >::Hc(), hPowerThermo< EquationOfState >::Hs(), solidProperties::Hs(), and hPowerThermo< EquationOfState >::S().