OpenFOAM: Foam::fvc Namespace Reference
Foam::fvc Namespace Reference
Namespace of functions to calculate explicit derivatives.
Functions
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvPatchField, volMesh > &vtf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvtf)
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > cellReduce (const GeometricField< Type, fvsPatchField, surfaceMesh > &, const CombineOp &cop, const Type &nullValue=pTraits< Type >::zero)
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > cellReduce (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &, const CombineOp &cop, const Type &nullValue=pTraits< Type >::zero)
tmp< GeometricField< scalar, fvsPatchField, surfaceMesh > > alphaCorr (const GeometricField< vector, fvPatchField, volMesh > &U, const GeometricField< scalar, fvsPatchField, surfaceMesh > &phiU, const bool finalIter)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &psi)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const tmp< surfaceScalarField > &tphi, const GeometricField< Type, fvPatchField, volMesh > &psi)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensioned< Type > dt, const fvMesh &mesh)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensionedScalar &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > ddt (const GeometricField< Type, fvsPatchField, surfaceMesh > &sf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const one &, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > &vf, const one &)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > &phi, const autoPtr< GeometricField< Type, fvsPatchField, surfaceMesh > > &Uf)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > &phi, const autoPtr< GeometricField< Type, fvsPatchField, surfaceMesh > > &Uf)
geometricZeroField ddt (const one &, const one &)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > &phi, const autoPtr< GeometricField< Type, fvsPatchField, surfaceMesh > > &Uf)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > &phi, const autoPtr< GeometricField< Type, fvsPatchField, surfaceMesh > > &Uf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvvf, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
tmp< surfaceScalarField > flux (const volVectorField &vvf)
tmp< surfaceScalarField > flux (const tmp< volVectorField > &tvvf)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &, const GeometricField< Type, fvPatchField, volMesh > &, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const tmp< GeometricField< Type, fvPatchField, volMesh > > &, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &, const tmp< GeometricField< Type, fvPatchField, volMesh > > &, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &, const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< volScalarField > magSqrGradGrad (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< volScalarField > magSqrGradGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
tmp< surfaceScalarField > meshPhi (const volVectorField &U)
tmp< surfaceScalarField > meshPhi (const dimensionedScalar &rho, const volVectorField &U)
tmp< surfaceScalarField > meshPhi (const volScalarField &rho, const volVectorField &U)
void makeRelative (surfaceScalarField &phi, const volVectorField &U)
void makeRelative (surfaceScalarField &phi, const dimensionedScalar &rho, const volVectorField &U)
void makeRelative (surfaceScalarField &phi, const volScalarField &rho, const volVectorField &U)
void makeAbsolute (surfaceScalarField &phi, const volVectorField &U)
void makeAbsolute (surfaceScalarField &phi, const dimensionedScalar &rho, const volVectorField &U)
void makeAbsolute (surfaceScalarField &phi, const volScalarField &rho, const volVectorField &U)
tmp< surfaceScalarField > relative (const tmp< surfaceScalarField > &tphi, const volVectorField &U)
tmp< surfaceScalarField > relative (const tmp< surfaceScalarField > &tphi, const volScalarField &rho, const volVectorField &U)
tmp< surfaceScalarField > absolute (const tmp< surfaceScalarField > &tphi, const volVectorField &U)
tmp< surfaceScalarField > absolute (const tmp< surfaceScalarField > &tphi, const volScalarField &rho, const volVectorField &U)
void correctUf (autoPtr< surfaceVectorField > &Uf, const volVectorField &U, const surfaceScalarField &phi)
void correctRhoUf (autoPtr< surfaceVectorField > &rhoUf, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &phi)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
tmp< volScalarField > reconstructMag (const surfaceScalarField &)
tmp< volScalarField > reconstructMag (const tmp< surfaceScalarField > &)
void smooth (volScalarField &field, const scalar coeff)
void spread (volScalarField &field, const volScalarField &alpha, const label nLayers, const scalar alphaDiff=0.2, const scalar alphaMax=0.99, const scalar alphaMin=0.01)
void sweep (volScalarField &field, const volScalarField &alpha, const label nLayers, const scalar alphaDiff=0.2)
void spreadSource (volScalarField &mDotOut, const volScalarField &mDotIn, const volScalarField &alpha1, const volScalarField &alpha2, const dimensionedScalar &D, const scalar cutoff)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const GeometricField< Type, fvPatchField, volMesh > &su, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tsu, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const volScalarField &sp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const tmp< volScalarField > &tsp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const dimensionedScalar &sp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const volScalarField &sp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const tmp< volScalarField > &tsp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
void surfaceIntegrate (Field< Type > &ivf, const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const DimensionedField< Type, volMesh > &df)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const tmp< DimensionedField< Type, volMesh > > &tdf)
template<class Type >
dimensioned< Type > domainIntegrate (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
dimensioned< Type > domainIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
dimensioned< Type > domainIntegrate (const DimensionedField< Type, volMesh > &df)
template<class Type >
dimensioned< Type > domainIntegrate (const tmp< DimensionedField< Type, volMesh > > &tdf)
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const surfaceScalarField &faceFlux, Istream &schemeData)
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const surfaceScalarField &faceFlux, const word &name)
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const fvMesh &mesh, Istream &schemeData)
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const fvMesh &mesh, const word &name)
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const surfaceScalarField &faceFlux, Istream &schemeData)
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const surfaceScalarField &faceFlux, const word &name)
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const surfaceScalarField &faceFlux, const word &name)
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const tmp< surfaceScalarField > &faceFlux, const word &name)
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const tmp< surfaceScalarField > &faceFlux, const word &name)
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, Istream &schemeData)
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const word &name)
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf)
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
static tmp< FieldField< fvsPatchField, Type > > interpolate (const FieldField< fvPatchField, Type > &fvpff)
template<class Type >
static tmp< FieldField< fvsPatchField, Type > > interpolate (const tmp< FieldField< fvPatchField, Type > > &tfvpff)
Foam::one interpolate (const Foam::one &)
template<class Type >
static tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &tvf)
template<class Type >
static tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
Detailed Description
Namespace of functions to calculate explicit derivatives.
Function Documentation
average() [1/4]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 40 of file fvcAverage.C.
References forAll, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and surfaceSum().
Referenced by average(), average(), average(), ATCModel::computeLimiter(), IATE::correct(), and MomentumTransferPhaseSystem< BasePhaseSystem >::ddtCorrByAs().
average() [2/4]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 87 of file fvcAverage.C.
References average(), and PtrList< T >::clear().
average() [3/4]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvPatchField, volMesh > & vtf)
Definition at line 103 of file fvcAverage.C.
References average(), and Foam::linearInterpolate().
average() [4/4]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvtf)
Definition at line 114 of file fvcAverage.C.
References average(), and PtrList< T >::clear().
cellReduce() [1/2]
template<class Type , class CombineOp > tmp< GeometricField< Type, fvPatchField, volMesh > > cellReduce (const GeometricField< Type, fvsPatchField, surfaceMesh > & , const CombineOp & cop, const Type & nullValue = pTraits< Type >::zero)
Referenced by limitedSnGrad< Type >::correction().
cellReduce() [2/2]
template<class Type , class CombineOp > tmp< GeometricField< Type, fvPatchField, volMesh > > cellReduce (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & , const CombineOp & cop, const Type & nullValue = pTraits< Type >::zero)
alphaCorr()
tmp< GeometricField< scalar, fvsPatchField, surfaceMesh > > alphaCorr (const GeometricField< vector, fvPatchField, volMesh > & U, const GeometricField< scalar, fvsPatchField, surfaceMesh > & phiU, const bool finalIter)
Definition at line 49 of file fvcCorrectAlpha.C.
References alpha, interpolate(), mesh, and U.
curl() [1/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 39 of file fvcCurl.C.
References grad(), and Foam::skew().
Referenced by LiftForce< CloudType >::cacheFields(), curl(), and liftModel::Fi().
curl() [2/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 62 of file fvcCurl.C.
References PtrList< T >::clear(), and curl().
d2dt2() [1/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 39 of file fvcD2dt2.C.
References d2dt2Scheme< Type >::New().
d2dt2() [2/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 54 of file fvcD2dt2.C.
References d2dt2Scheme< Type >::New(), and rho.
DDt() [1/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & psi)
Definition at line 39 of file fvcDDt.C.
References ddt(), div(), phi, and psi.
Referenced by DDt().
DDt() [2/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const tmp< surfaceScalarField > & tphi, const GeometricField< Type, fvPatchField, volMesh > & psi)
Definition at line 61 of file fvcDDt.C.
References PtrList< T >::clear(), DDt(), and psi.
ddt() [1/9]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensioned< Type > dt, const fvMesh & mesh)
Definition at line 39 of file fvcDdt.C.
References mesh, and ddtScheme< Type >::New().
Referenced by densityChangeDrift::addToDriftRate(), PressureGradientForce< CloudType >::cacheFields(), Implicit< CloudType >::cacheFields(), kineticTheoryModel::correct(), IATE::correct(), phaseSystem::correctKinematics(), ddt(), ddt(), DDt(), MovingPhaseModel< BasePhaseModel >::DUDt(), Curle::execute(), energyTransport::execute(), boundedDdtScheme< Type >::fvcDdt(), boundedDdtScheme< Type >::fvcDdt(), boundedDdtScheme< Type >::fvmDdt(), boundedDdtScheme< Type >::fvmDdt(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), populationBalanceModel::solve(), twoPhaseSystem::solve(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::YiEqn().
ddt() [2/9]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 55 of file fvcDdt.C.
References ddtScheme< Type >::New().
ddt() [3/9]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 70 of file fvcDdt.C.
References ddtScheme< Type >::New(), and rho.
ddt() [4/9]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 86 of file fvcDdt.C.
References ddtScheme< Type >::New(), and rho.
ddt() [5/9]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 102 of file fvcDdt.C.
References alpha, ddtScheme< Type >::New(), and rho.
ddt() [6/9]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > ddt (const GeometricField< Type, fvsPatchField, surfaceMesh > & sf)
Definition at line 125 of file fvcDdt.C.
References ddtScheme< Type >::New().
ddt() [7/9]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const one & , const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 140 of file fvcDdt.C.
References ddt().
ddt() [8/9]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > & vf, const one &)
Definition at line 152 of file fvcDdt.C.
References ddt().
ddtCorr() [1/12]
template<class Type > tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 164 of file fvcDdt.C.
References ddtScheme< Type >::New(), U, and Uf.
Referenced by ddtCorr(), and ddtCorr().
ddtCorr() [2/12]
template<class Type > tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 180 of file fvcDdt.C.
References ddtScheme< Type >::New(), phi, and U.
ddtCorr() [3/12]
template<class Type > tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > & phi, const autoPtr< GeometricField< Type, fvsPatchField, surfaceMesh > > & Uf)
Definition at line 201 of file fvcDdt.C.
References ddtCorr(), phi, U, and Uf.
ddtCorr() [4/12]
template<class Type > tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 226 of file fvcDdt.C.
References ddtScheme< Type >::New(), rho, U, and Uf.
ddtCorr() [5/12]
template<class Type > tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 243 of file fvcDdt.C.
References ddtScheme< Type >::New(), phi, rho, and U.
ddtCorr() [6/12]
template<class Type > tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > & phi, const autoPtr< GeometricField< Type, fvsPatchField, surfaceMesh > > & Uf)
Definition at line 265 of file fvcDdt.C.
References ddtCorr(), phi, rho, U, and Uf.
ddt() [9/9]
geometricZeroField ddt (const one & , const one &) inline
Definition at line 109 of file fvcDdt.H.
ddtCorr() [7/12]
template<class Type > tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 164 of file fvcDdt.C.
References ddtScheme< Type >::New(), U, and Uf.
Referenced by ddtCorr(), and ddtCorr().
ddtCorr() [8/12]
template<class Type > tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 180 of file fvcDdt.C.
References ddtScheme< Type >::New(), phi, and U.
ddtCorr() [9/12]
template<class Type > tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > & phi, const autoPtr< GeometricField< Type, fvsPatchField, surfaceMesh > > & Uf)
Definition at line 201 of file fvcDdt.C.
References ddtCorr(), phi, U, and Uf.
ddtCorr() [10/12]
template<class Type > tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 226 of file fvcDdt.C.
References ddtScheme< Type >::New(), rho, U, and Uf.
ddtCorr() [11/12]
template<class Type > tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 243 of file fvcDdt.C.
References ddtScheme< Type >::New(), phi, rho, and U.
ddtCorr() [12/12]
template<class Type > tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > & phi, const autoPtr< GeometricField< Type, fvsPatchField, surfaceMesh > > & Uf)
Definition at line 265 of file fvcDdt.C.
References ddtCorr(), phi, rho, U, and Uf.
div() [1/14]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > div (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 41 of file fvcDiv.C.
References surfaceIntegrate().
Referenced by adjointSensitivity::adjointMeshMovementSource(), MassTransferPhaseSystem< BasePhaseSystem >::alphaTransfer(), sensitivityBezierFI::assembleSensitivities(), sensitivityVolBSplinesFI::assembleSensitivities(), momentumError::calcMomentError(), hydrostaticPressure::calculateAndWrite(), adjointkOmegaSST::coeffsDifferentiation(), adjointSpalartAllmaras::conservativeMomentumSource(), adjointSimple::continuityErrors(), simple::continuityErrors(), adjointkOmegaSST::convectionMeanFlowSource(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), kL< BasicTurbulenceModel >::correct(), adjointkOmegaSST::correct(), kineticTheoryModel::correct(), IATE::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), thixotropicViscosity::correct(), advectionDiffusion::correct(), incompressiblePrimalSolver::correctBoundaryConditions(), DDt(), kineticTheoryModel::devRhoReff(), adjointkOmegaSST::diffusionNutMeanFlowMult(), div(), div(), div(), div(), div(), div(), div(), div(), div(), div(), div(), adjointkOmegaSST::divDevReff(), adjointLaminar::divDevReff(), adjointSpalartAllmaras::divDevReff(), momentumError::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::DivDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), nonlinearEddyViscosity< BasicTurbulenceModel >::divDevRhoReff(), kineticTheoryModel::divDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), adjointkOmegaSST::divUMeanFlowSource(), adjointkOmegaSST::dNutdbMult(), adjointkOmegaSST::dNutdbMult(), adjointkOmegaSST::dR_dF1(), MovingPhaseModel< BasePhaseModel >::DUDt(), energyTransport::execute(), adjointkOmegaSST::FISensitivityTerm(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), relaxedNonOrthoGaussLaplacianScheme< Type, GType >::fvcLaplacian(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), relaxedNonOrthoGaussLaplacianScheme< Type, GType >::fvcLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), relaxedNonOrthoGaussLaplacianScheme< Type, GType >::fvmLaplacian(), adjointkOmegaSST::GMeanFlowSource(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), multiphaseInterSystem::K(), adjointkOmegaSST::kaEqnSourceFromCDkOmega(), adjointkOmegaSST::kaEqnSourceFromF1(), adjointSimple::mainIter(), simple::mainIter(), MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransfer(), MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransferf(), adjointkOmegaSST::nutMeanFlowSource(), kineticTheoryModel::R(), displacementSBRStressFvMotionSolver::solve(), surfaceAlignedSBRStressFvMotionSolver::solve(), elasticityMotionSolver::solve(), adjointMeshMovementSolver::solve(), populationBalanceModel::solve(), twoPhaseSystem::solve(), kinematicSingleLayer::solveContinuity(), reactingOneDim::solveEnergy(), thermalBaffle::solveEnergy(), reactingOneDim::solveSpeciesMass(), MovingPhaseModel< BasePhaseModel >::UfEqn(), objectivePowerDissipation::update_dJdv(), adjointkOmegaSST::waEqnSourceFromCDkOmega(), adjointkOmegaSST::waEqnSourceFromF1(), continuityError::write(), and electricPotential::write().
div() [2/14]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 59 of file fvcDiv.C.
References PtrList< T >::clear(), and div().
div() [3/14]
template<class Type > tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 78 of file fvcDiv.C.
References Foam::name(), and divScheme< Type >::New().
div() [4/14]
template<class Type > tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvvf, const word & name)
Definition at line 99 of file fvcDiv.C.
References PtrList< T >::clear(), div(), and Foam::name().
div() [5/14]
template<class Type > tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 122 of file fvcDiv.C.
References div().
div() [6/14]
template<class Type > tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvvf)
Definition at line 139 of file fvcDiv.C.
References PtrList< T >::clear(), and div().
div() [7/14]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField & flux, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 153 of file fvcDiv.C.
References Foam::name(), and convectionScheme< Type >::New().
div() [8/14]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > & tflux, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 171 of file fvcDiv.C.
References PtrList< T >::clear(), div(), and Foam::name().
div() [9/14]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField & flux, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 189 of file fvcDiv.C.
References PtrList< T >::clear(), div(), and Foam::name().
div() [10/14]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > & tflux, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 207 of file fvcDiv.C.
References PtrList< T >::clear(), div(), and Foam::name().
div() [11/14]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField & flux, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 226 of file fvcDiv.C.
References div().
div() [12/14]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > & tflux, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 241 of file fvcDiv.C.
References PtrList< T >::clear(), and div().
div() [13/14]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField & flux, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 258 of file fvcDiv.C.
References PtrList< T >::clear(), and div().
div() [14/14]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > & tflux, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 275 of file fvcDiv.C.
References PtrList< T >::clear(), and div().
flux() [1/10]
Foam::tmp< Foam::surfaceScalarField > flux (const volVectorField & vvf)
Definition at line 26 of file fvcFlux.C.
Referenced by incompressiblePrimalSolver::correctBoundaryConditions(), MomentumTransferPhaseSystem< BasePhaseSystem >::ddtCorrByAs(), liftModel::Ff(), wallLubricationModel::Ff(), flux(), flux(), flux(), flux(), flux(), flux(), flux(), kinematicSingleLayer::kinematicSingleLayer(), adjointSimple::mainIter(), simple::mainIter(), phaseModel::phaseModel(), phaseModel::phaseModel(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFs(), twoPhaseSystem::solve(), multiphaseSystem::solveAlphas(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi(), and thermoSingleLayer::thermoSingleLayer().
flux() [2/10]
Foam::tmp< Foam::surfaceScalarField > flux (const tmp< volVectorField > & tvvf)
Definition at line 39 of file fvcFlux.C.
References PtrList< T >::clear().
flux() [3/10]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & , const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
Definition at line 144 of file fvcFluxTemplates.C.
References PtrList< T >::clear(), flux(), and phi.
flux() [4/10]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 39 of file fvcFluxTemplates.C.
References Foam::name(), convectionScheme< Type >::New(), and phi.
flux() [5/10]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 57 of file fvcFluxTemplates.C.
References PtrList< T >::clear(), flux(), and Foam::name().
flux() [6/10]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 75 of file fvcFluxTemplates.C.
References PtrList< T >::clear(), flux(), Foam::name(), and phi.
flux() [7/10]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 93 of file fvcFluxTemplates.C.
References PtrList< T >::clear(), flux(), and Foam::name().
flux() [8/10]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 112 of file fvcFluxTemplates.C.
References flux(), and phi.
flux() [9/10]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 127 of file fvcFluxTemplates.C.
References PtrList< T >::clear(), and flux().
flux() [10/10]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 161 of file fvcFluxTemplates.C.
References PtrList< T >::clear(), and flux().
grad() [1/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 46 of file fvcGrad.C.
References gaussGrad< Type >::gradf().
Referenced by sensitivitySurface::accumulateIntegrand(), sensitivitySurfacePoints::accumulateIntegrand(), ATCstandard::addATC(), ATCUaGradU::addATC(), jouleHeatingSource::addSup(), viscousDissipation::addSup(), multiphaseStabilizedTurbulence::addSup(), densityChangeDrift::addToDriftRate(), sensitivityBezierFI::assembleSensitivities(), sensitivityVolBSplinesFI::assembleSensitivities(), InterfaceForce< CloudType >::cacheFields(), PressureGradientForce< CloudType >::cacheFields(), GradientDispersionRAS< CloudType >::cacheFields(), forces::calcForcesMoments(), momentumError::calcMomentError(), ObukhovLength::calcOL(), dynamicKEqn< BasicTurbulenceModel >::Ce(), LegendreMagnaudet::Cl(), Moraga::Cl(), kOmegaSST::computeG(), incompressibleAdjointSolver::computeGradDxDbMultiplier(), adjointEikonalSolver::computeYPhi(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), kL< BasicTurbulenceModel >::correct(), diffusion< ReactionThermo, ThermoType >::correct(), diffusionMulticomponent< ReactionThermo, ThermoType >::correct(), adjointSpalartAllmaras::correct(), kineticTheoryModel::correct(), kkLOmega::correct(), LamBremhorstKE::correct(), LienCubicKE::correct(), LienLeschziner::correct(), qZeta::correct(), ShihQuadraticKE::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), SpalartAllmarasBase< BasicEddyViscosityModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), EBRSM< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::correct(), multiphaseStabilizedTurbulence::correct(), advectionDiffusion::correct(), Poisson::correct(), contactAngleForce::correct(), thermocapillaryForce::correct(), kOmegaSST::correctBoundaryConditions(), LienCubicKE::correctNut(), ShihQuadraticKE::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), kOmegaSSTBase< BasicEddyViscosityModel >::correctNut(), kOmegaSSTDES< BasicTurbulenceModel >::correctNut(), dynamicKEqn< BasicTurbulenceModel >::correctNut(), dynamicLagrangian< BasicTurbulenceModel >::correctNut(), sigma< BasicTurbulenceModel >::correctNut(), Smagorinsky< BasicTurbulenceModel >::correctNut(), WALE< BasicTurbulenceModel >::correctNut(), kOmegaSST< BasicTurbulenceModel >::correctNut(), realizableKE< BasicTurbulenceModel >::correctNut(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), curl(), ReynoldsAnalogy::devReff(), RASModelVariables::devReff(), adjointkOmegaSST::devReff(), adjointLaminar::devReff(), adjointSpalartAllmaras::devReff(), filmTurbulenceModel::devRhoReff(), kineticTheoryModel::devRhoReff(), Maxwell< BasicTurbulenceModel >::devRhoReff(), ReynoldsStress< BasicTurbulenceModel >::devRhoReff(), adjointkOmegaSST::divDevReff(), adjointLaminar::divDevReff(), adjointSpalartAllmaras::divDevReff(), momentumError::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::DivDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), kineticTheoryModel::divDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), shapeSensitivities::dvdbMult(), electricPotential::electricPotential(), electricPotential::execute(), turbulentDispersionModel::F(), kOmegaSSTDDES< BasicTurbulenceModel >::fd(), kOmegaSSTIDDES< BasicTurbulenceModel >::fd(), SpalartAllmarasDDES< BasicTurbulenceModel >::fd(), SpalartAllmarasIDDES< BasicTurbulenceModel >::fd(), adjointkOmegaSST::FISensitivityTerm(), adjointSpalartAllmaras::FISensitivityTerm(), buoyantKEpsilon< BasicTurbulenceModel >::Gcoef(), ATCstandard::getFISensitivityTerm(), ATCUaGradU::getFISensitivityTerm(), adjointEikonalSolver::getFISensitivityTerm(), grad(), grad(), grad(), grad(), grad(), adjointEikonalSolver::gradEikonal(), objectivePowerDissipation::J(), segregated::K(), SpalartAllmarasBase< BasicEddyViscosityModel >::k(), dynamicLagrangian< BasicTurbulenceModel >::k(), sigma< BasicTurbulenceModel >::k(), Smagorinsky< BasicTurbulenceModel >::k(), WALE< BasicTurbulenceModel >::k(), diffusionGasEvaporation< Thermo, OtherThermo >::Kexp(), kOmegaSSTDES< BasicTurbulenceModel >::LESRegion(), SpalartAllmarasDES< BasicTurbulenceModel >::LESRegion(), magSqrGradGrad(), adjointSimple::mainIter(), simple::mainIter(), multiphaseInterSystem::nHatfv(), adjointkOmegaSST::nutJacobianTMVar1(), adjointkOmegaSST::nutJacobianTMVar2(), adjointkOmegaSST::nutJacobianU(), multiphaseInterSystem::nVolHatfv(), ParticleTrap< CloudType >::preEvolve(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), kineticTheoryModel::R(), continuousGasKEpsilon< BasicTurbulenceModel >::R(), kOmegaSSTDDES< BasicTurbulenceModel >::S2(), kOmegaSSTDES< BasicTurbulenceModel >::S2(), displacementSBRStressFvMotionSolver::solve(), surfaceAlignedSBRStressFvMotionSolver::solve(), elasticityMotionSolver::solve(), viscosityModel::strainRate(), generalizedNewtonian< BasicMomentumTransportModel >::strainRate(), objectiveForce::update_boundarydJdnut(), objectiveMoment::update_boundarydJdnut(), objectivePowerDissipation::update_divDxDbMultiplier(), objectivePowerDissipation::update_dJdTMvar1(), objectivePowerDissipation::update_dJdTMvar2(), objectivePowerDissipation::update_dJdv(), objectiveForce::update_dxdbMultiplier(), objectiveMoment::update_dxdbMultiplier(), objectivePowerDissipation::update_gradDxDbMultiplier(), ATCstandard::updatePrimalBasedQuantities(), adjointkOmegaSST::updatePrimalRelatedFields(), adjointSpalartAllmaras::updatePrimalRelatedFields(), XiReactionRate::write(), and electricPotential::write().
grad() [2/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 63 of file fvcGrad.C.
References PtrList< T >::clear(), and grad().
grad() [3/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 86 of file fvcGrad.C.
References grad(), Foam::name(), and gradScheme< Type >::New().
grad() [4/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 108 of file fvcGrad.C.
References PtrList< T >::clear(), grad(), and Foam::name().
grad() [5/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 137 of file fvcGrad.C.
References grad().
grad() [6/6]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 154 of file fvcGrad.C.
References PtrList< T >::clear(), and grad().
laplacian() [1/24]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 39 of file fvcLaplacian.C.
References Foam::name(), and laplacianScheme< Type, GType >::New().
Referenced by adjointSpalartAllmaras::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), momentumError::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::DivDevRhoReff(), thermo::evolveRegion(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplaceFilter::operator()(), laplaceFilter::operator()(), laplaceFilter::operator()(), laplaceFilter::operator()(), kinematicSingleLayer::pu(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), adjointEikonalSolver::solve(), and reactingOneDim::solveEnergy().
laplacian() [2/24]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 55 of file fvcLaplacian.C.
References PtrList< T >::clear(), laplacian(), and Foam::name().
laplacian() [3/24]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 72 of file fvcLaplacian.C.
References laplacian().
laplacian() [4/24]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 83 of file fvcLaplacian.C.
References PtrList< T >::clear(), and laplacian().
laplacian() [5/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 101 of file fvcLaplacian.C.
References gamma, laplacian(), Foam::name(), and IOobjectOption::NO_READ.
laplacian() [6/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 127 of file fvcLaplacian.C.
References PtrList< T >::clear(), gamma, laplacian(), and Foam::name().
laplacian() [7/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 145 of file fvcLaplacian.C.
References gamma, laplacian(), and IOobjectOption::NO_READ.
laplacian() [8/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 170 of file fvcLaplacian.C.
References PtrList< T >::clear(), gamma, and laplacian().
laplacian() [9/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 189 of file fvcLaplacian.C.
References gamma, Foam::name(), and laplacianScheme< Type, GType >::New().
laplacian() [10/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 206 of file fvcLaplacian.C.
References PtrList< T >::clear(), laplacian(), and Foam::name().
laplacian() [11/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 224 of file fvcLaplacian.C.
References PtrList< T >::clear(), gamma, laplacian(), and Foam::name().
laplacian() [12/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 242 of file fvcLaplacian.C.
References PtrList< T >::clear(), laplacian(), and Foam::name().
laplacian() [13/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 261 of file fvcLaplacian.C.
References gamma, and laplacian().
laplacian() [14/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 278 of file fvcLaplacian.C.
References laplacian(), and Foam::name().
laplacian() [15/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 295 of file fvcLaplacian.C.
References gamma, laplacian(), and Foam::name().
laplacian() [16/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 312 of file fvcLaplacian.C.
References laplacian(), and Foam::name().
laplacian() [17/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 331 of file fvcLaplacian.C.
References gamma, Foam::name(), and laplacianScheme< Type, GType >::New().
laplacian() [18/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 348 of file fvcLaplacian.C.
References PtrList< T >::clear(), laplacian(), and Foam::name().
laplacian() [19/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 366 of file fvcLaplacian.C.
References PtrList< T >::clear(), gamma, laplacian(), and Foam::name().
laplacian() [20/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 383 of file fvcLaplacian.C.
References PtrList< T >::clear(), laplacian(), and Foam::name().
laplacian() [21/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 402 of file fvcLaplacian.C.
References gamma, and laplacian().
laplacian() [22/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 419 of file fvcLaplacian.C.
References PtrList< T >::clear(), and laplacian().
laplacian() [23/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 436 of file fvcLaplacian.C.
References PtrList< T >::clear(), gamma, and laplacian().
laplacian() [24/24]
template<class Type , class GType > tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 452 of file fvcLaplacian.C.
References PtrList< T >::clear(), and laplacian().
magSqrGradGrad() [1/2]
template<class Type > tmp< volScalarField > magSqrGradGrad (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 38 of file fvcMagSqrGradGrad.C.
References grad(), and Foam::magSqr().
Referenced by qZeta::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), and magSqrGradGrad().
magSqrGradGrad() [2/2]
template<class Type > tmp< volScalarField > magSqrGradGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 61 of file fvcMagSqrGradGrad.C.
References PtrList< T >::clear(), and magSqrGradGrad().
meshPhi() [1/3]
Foam::tmp< Foam::surfaceScalarField > meshPhi (const volVectorField & U)
Definition at line 28 of file fvcMeshPhi.C.
References ddtScheme< Type >::meshPhi().
Referenced by fvMotionSolverEngineMesh::move(), layeredEngineMesh::move(), and movingWallVelocityFvPatchVectorField::Uwall().
meshPhi() [2/3]
Foam::tmp< Foam::surfaceScalarField > meshPhi (const dimensionedScalar & rho, const volVectorField & U)
Definition at line 41 of file fvcMeshPhi.C.
References ddtScheme< Type >::meshPhi(), and rho.
meshPhi() [3/3]
Foam::tmp< Foam::surfaceScalarField > meshPhi (const volScalarField & rho, const volVectorField & U)
Definition at line 55 of file fvcMeshPhi.C.
References ddtScheme< Type >::meshPhi(), and rho.
makeRelative() [1/3]
void makeRelative (surfaceScalarField & phi, const volVectorField & U)
Definition at line 69 of file fvcMeshPhi.C.
References phi, and U.
makeRelative() [2/3]
void makeRelative (surfaceScalarField & phi, const dimensionedScalar & rho, const volVectorField & U)
Definition at line 81 of file fvcMeshPhi.C.
References phi, rho, and U.
makeRelative() [3/3]
void makeRelative (surfaceScalarField & phi, const volScalarField & rho, const volVectorField & U)
Definition at line 94 of file fvcMeshPhi.C.
References phi, rho, and U.
makeAbsolute() [1/3]
void makeAbsolute (surfaceScalarField & phi, const volVectorField & U)
Definition at line 108 of file fvcMeshPhi.C.
References phi, and U.
makeAbsolute() [2/3]
void makeAbsolute (surfaceScalarField & phi, const dimensionedScalar & rho, const volVectorField & U)
Definition at line 120 of file fvcMeshPhi.C.
References phi, rho, and U.
makeAbsolute() [3/3]
void makeAbsolute (surfaceScalarField & phi, const volScalarField & rho, const volVectorField & U)
Definition at line 133 of file fvcMeshPhi.C.
References phi, rho, and U.
relative() [1/2]
Foam::tmp< Foam::surfaceScalarField > relative (const tmp< surfaceScalarField > & tphi, const volVectorField & U)
Definition at line 147 of file fvcMeshPhi.C.
References mesh, and U.
relative() [2/2]
Foam::tmp< Foam::surfaceScalarField > relative (const tmp< surfaceScalarField > & tphi, const volScalarField & rho, const volVectorField & U)
Definition at line 164 of file fvcMeshPhi.C.
References mesh, rho, and U.
absolute() [1/2]
Foam::tmp< Foam::surfaceScalarField > absolute (const tmp< surfaceScalarField > & tphi, const volVectorField & U)
Definition at line 182 of file fvcMeshPhi.C.
References mesh, and U.
Referenced by kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), kL< BasicTurbulenceModel >::correct(), adjointkOmegaSST::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), adjointkOmegaSST::dR_dF1(), and AnisothermalPhaseModel< BasePhaseModel >::heEqn().
absolute() [2/2]
Foam::tmp< Foam::surfaceScalarField > absolute (const tmp< surfaceScalarField > & tphi, const volScalarField & rho, const volVectorField & U)
Definition at line 199 of file fvcMeshPhi.C.
References mesh, rho, and U.
correctUf()
void correctUf (autoPtr< surfaceVectorField > & Uf, const volVectorField & U, const surfaceScalarField & phi)
Definition at line 217 of file fvcMeshPhi.C.
References mesh, n, phi, U, and Uf.
correctRhoUf()
void correctRhoUf (autoPtr< surfaceVectorField > & rhoUf, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & phi)
Definition at line 235 of file fvcMeshPhi.C.
References mesh, n, phi, rho, rhoUf, and U.
reconstruct() [1/2]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 48 of file fvcReconstruct.C.
References fvPatchFieldBase::extrapolatedCalculatedType(), Foam::inv(), mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and surfaceSum().
Referenced by ATCUaGradU::addATC(), Implicit< CloudType >::cacheFields(), reconstruct(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), and ATCstandard::updatePrimalBasedQuantities().
reconstruct() [2/2]
template<class Type > tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 90 of file fvcReconstruct.C.
References PtrList< T >::clear(), and reconstruct().
reconstructMag() [1/2]
tmp< volScalarField > reconstructMag (const surfaceScalarField & ssf)
Definition at line 39 of file fvcReconstructMag.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::dimArea, fvPatchFieldBase::extrapolatedCalculatedType(), forAll, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and Foam::Zero.
Referenced by reconstructMag().
reconstructMag() [2/2]
tmp< volScalarField > reconstructMag (const tmp< surfaceScalarField > & tssf)
Definition at line 107 of file fvcReconstructMag.C.
References PtrList< T >::clear(), and reconstructMag().
smooth()
void smooth (volScalarField & field, const scalar coeff)
Definition at line 36 of file fvcSmooth.C.
References PtrList< T >::append(), field(), forAll, mesh, and UPtrList< T >::size().
Referenced by surfaceAlignedSBRStressFvMotionSolver::solve().
spread()
void spread (volScalarField & field, const volScalarField & alpha, const label nLayers, const scalar alphaDiff = 0.2, const scalar alphaMax = 0.99, const scalar alphaMin = 0.01)
Definition at line 125 of file fvcSmooth.C.
References alpha, PtrList< T >::append(), field(), forAll, Foam::mag(), Foam::max(), mesh, and UPtrList< T >::size().
sweep()
void sweep (volScalarField & field, const volScalarField & alpha, const label nLayers, const scalar alphaDiff = 0.2)
Definition at line 223 of file fvcSmooth.C.
References alpha, PtrList< T >::append(), field(), forAll, Foam::mag(), Foam::max(), mesh, and UPtrList< T >::size().
spreadSource()
void spreadSource (volScalarField & mDotOut, const volScalarField & mDotIn, const volScalarField & alpha1, const volScalarField & alpha2, const dimensionedScalar & D, const scalar cutoff)
Definition at line 317 of file fvcSmooth.C.
References alpha1, alpha2, D, Foam::dimless, Foam::dimMass, Foam::dimTime, forAll, mesh, and Foam::reduce().
Referenced by interfaceHeatResistance< Thermo, OtherThermo >::Kexp().
snGrad() [1/4]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 39 of file fvcSnGrad.C.
References Foam::name(), snGradScheme< Type >::New(), and snGrad().
Referenced by hydrostaticPressure::calculateAndWrite(), adjointkOmegaSST::coeffsDifferentiation(), adjointkOmegaSST::diffusionNutMeanFlowMult(), adjointkOmegaSST::dNutdbMult(), adjointkOmegaSST::dNutdbMult(), turbulentDispersionModel::Ff(), adjointSimple::mainIter(), simple::mainIter(), anisotropicFilter::operator()(), anisotropicFilter::operator()(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFfs(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFs(), snGrad(), snGrad(), snGrad(), snGrad(), twoPhaseSystem::solve(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), multiphaseSystem::surfaceTension(), multiphaseInterSystem::surfaceTensionForce(), and interfaceProperties::surfaceTensionForce().
snGrad() [2/4]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 55 of file fvcSnGrad.C.
References PtrList< T >::clear(), Foam::name(), and snGrad().
snGrad() [3/4]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 72 of file fvcSnGrad.C.
References snGrad().
snGrad() [4/4]
template<class Type > tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 83 of file fvcSnGrad.C.
References PtrList< T >::clear(), and snGrad().
Su() [1/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const GeometricField< Type, fvPatchField, volMesh > & su, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 38 of file fvcSup.C.
Referenced by populationBalanceModel::solve().
Su() [2/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tsu, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 49 of file fvcSup.C.
Sp() [1/3]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const volScalarField & sp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 61 of file fvcSup.C.
Referenced by kineticTheoryModel::correct().
Sp() [2/3]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const tmp< volScalarField > & tsp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 72 of file fvcSup.C.
Sp() [3/3]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const dimensionedScalar & sp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 84 of file fvcSup.C.
SuSp() [1/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const volScalarField & sp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 96 of file fvcSup.C.
SuSp() [2/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const tmp< volScalarField > & tsp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 107 of file fvcSup.C.
surfaceIntegrate() [1/3]
template<class Type > void surfaceIntegrate (Field< Type > & ivf, const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 38 of file fvcSurfaceIntegrate.C.
References forAll, and mesh.
Referenced by isoAdvection::advect(), div(), setFlow::execute(), gaussDivScheme< Type >::fvcDiv(), boundedConvectionScheme< Type >::fvcDiv(), gaussConvectionScheme< Type >::fvcDiv(), boundedConvectionScheme< Type >::fvmDiv(), gaussConvectionScheme< Type >::fvmDiv(), anisotropicFilter::operator()(), anisotropicFilter::operator()(), surfaceIntegrate(), and surfaceIntegrate().
surfaceIntegrate() [2/3]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 76 of file fvcSurfaceIntegrate.C.
References Foam::dimVol, fvPatchFieldBase::extrapolatedCalculatedType(), mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, surfaceIntegrate(), and Foam::Zero.
surfaceIntegrate() [3/3]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 111 of file fvcSurfaceIntegrate.C.
References PtrList< T >::clear(), and surfaceIntegrate().
surfaceSum() [1/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 127 of file fvcSurfaceIntegrate.C.
References fvPatchFieldBase::extrapolatedCalculatedType(), forAll, mesh, IOobjectOption::NO_READ, IOobjectOption::NO_WRITE, and Foam::Zero.
Referenced by anisotropicFilter::anisotropicFilter(), anisotropicFilter::anisotropicFilter(), average(), cellCoBlended< Type >::blendingFactor(), kinematicSingleLayer::CourantNumber(), simpleFilter::operator()(), simpleFilter::operator()(), simpleFilter::operator()(), simpleFilter::operator()(), reconstruct(), and surfaceSum().
surfaceSum() [2/2]
template<class Type > tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 182 of file fvcSurfaceIntegrate.C.
References PtrList< T >::clear(), and surfaceSum().
volumeIntegrate() [1/4]
template<class Type > tmp< Field< Type > > volumeIntegrate (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 39 of file fvcVolumeIntegrate.C.
Referenced by domainIntegrate(), and domainIntegrate().
volumeIntegrate() [2/4]
template<class Type > tmp< Field< Type > > volumeIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 50 of file fvcVolumeIntegrate.C.
References PtrList< T >::clear().
volumeIntegrate() [3/4]
template<class Type > tmp< Field< Type > > volumeIntegrate (const DimensionedField< Type, volMesh > & df)
Definition at line 62 of file fvcVolumeIntegrate.C.
volumeIntegrate() [4/4]
template<class Type > tmp< Field< Type > > volumeIntegrate (const tmp< DimensionedField< Type, volMesh > > & tdf)
Definition at line 70 of file fvcVolumeIntegrate.C.
References PtrList< T >::clear().
domainIntegrate() [1/4]
template<class Type > dimensioned< Type > domainIntegrate (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 80 of file fvcVolumeIntegrate.C.
References Foam::dimVol, Foam::gSum(), and volumeIntegrate().
Referenced by interRegionHeatTransferModel::addSup(), reactingOneDim::calculateMassTransfer(), kinematicSingleLayer::continuityCheck(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), domainIntegrate(), domainIntegrate(), regionSizeDistribution::write(), and specieReactionRates< ChemistryModelType >::write().
domainIntegrate() [2/4]
template<class Type > dimensioned< Type > domainIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 95 of file fvcVolumeIntegrate.C.
References PtrList< T >::clear(), and domainIntegrate().
domainIntegrate() [3/4]
template<class Type > dimensioned< Type > domainIntegrate (const DimensionedField< Type, volMesh > & df)
Definition at line 107 of file fvcVolumeIntegrate.C.
References Foam::dimVol, Foam::gSum(), and volumeIntegrate().
domainIntegrate() [4/4]
template<class Type > dimensioned< Type > domainIntegrate (const tmp< DimensionedField< Type, volMesh > > & tdf)
Definition at line 122 of file fvcVolumeIntegrate.C.
References PtrList< T >::clear(), and domainIntegrate().
scheme() [1/4]
template<class Type > static tmp< surfaceInterpolationScheme< Type > > scheme (const surfaceScalarField & faceFlux, Istream & schemeData) static
scheme() [2/4]
template<class Type > static tmp< surfaceInterpolationScheme< Type > > scheme (const surfaceScalarField & faceFlux, const word & name) static
scheme() [3/4]
template<class Type > static tmp< surfaceInterpolationScheme< Type > > scheme (const fvMesh & mesh, Istream & schemeData) static
scheme() [4/4]
template<class Type > static tmp< surfaceInterpolationScheme< Type > > scheme (const fvMesh & mesh, const word & name) static
interpolate() [1/13]
template<class Type > static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const surfaceScalarField & faceFlux, Istream & schemeData) static
Referenced by extractEulerianParticles::accumulateParticleInfo(), fanMomentumSource::addSup(), alphaCorr(), cellCoBlended< Type >::blendingFactor(), CoBlended< Type >::blendingFactor(), Implicit< CloudType >::cacheFields(), phaseSystem::calcPhi(), hydrostaticPressure::calculateAndWrite(), parseDriver::cellToFace(), adjointEikonalSolver::computeYPhi(), inverseDistanceDiffusivity::correct(), inverseVolumeDiffusivity::correct(), motionDirectionalDiffusivity::correct(), thixotropicViscosity::correct(), advectionDiffusion::correct(), interpolated::damp(), MomentumTransferPhaseSystem< BasePhaseSystem >::ddtCorrByAs(), StaticPhaseModel< BasePhaseModel >::diffNo(), effectivenessTable::energyDensity(), extractEulerianParticles::execute(), energyTransport::execute(), filmFlux::execute(), liftModel::Ff(), turbulentDispersionModel::Ff(), wallLubricationModel::Ff(), ddtScheme< Type >::fvcDdtPhiCoeff(), ddtScheme< Type >::fvcDdtPhiCoeff(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), multiphaseInterSystem::generatePhi(), isoAdvection::getRhoPhi(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), Foam::interpolate(), blendedInterfacialModel::interpolate(), AttouFerschneider::Kf(), dragModel::Kf(), segregated::Kf(), virtualMassModel::Kf(), PhiScheme< Type, PhiLimiter >::limiter(), adjointSimple::mainIter(), simple::mainIter(), dynamicRefineFvMesh::mapFields(), mixtureKEpsilon< BasicTurbulenceModel >::mixFlux(), fvMotionSolverEngineMesh::move(), layeredEngineMesh::move(), incompressibleTwoPhaseMixture::muf(), multiphaseInterSystem::nHatfv(), incompressibleTwoPhaseMixture::nuf(), simpleFilter::operator()(), simpleFilter::operator()(), simpleFilter::operator()(), simpleFilter::operator()(), MomentumTransferPhaseSystem< BasePhaseSystem >::partialElimination(), compressibleTurbulenceModel::phi(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFfs(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFs(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiKdPhis(), extractEulerianParticles::phiU(), kineticTheoryModel::pPrimef(), phasePressureModel::pPrimef(), reactingOneDim::solidRegionDiffNo(), displacementSBRStressFvMotionSolver::solve(), surfaceAlignedSBRStressFvMotionSolver::solve(), twoPhaseSystem::solve(), multiphaseSystem::solveAlphas(), reactingOneDim::solveEnergy(), thermalBaffle::solveEnergy(), kinematicSingleLayer::solveMomentum(), reactingOneDim::solveSpeciesMass(), kinematicSingleLayer::solveThickness(), multiphaseSystem::surfaceTension(), multiphaseInterSystem::surfaceTensionForce(), interfaceProperties::surfaceTensionForce(), dynamicRefineFvMesh::unrefine(), dynamicMotionSolverFvMeshAMI::update(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::YiEqn().
interpolate() [2/13]
template<class Type > static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const surfaceScalarField & faceFlux, const word & name) static
interpolate() [3/13]
template<class Type > static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const surfaceScalarField & faceFlux, const word & name) static
interpolate() [4/13]
template<class Type > static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const tmp< surfaceScalarField > & faceFlux, const word & name) static
interpolate() [5/13]
template<class Type > static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const tmp< surfaceScalarField > & faceFlux, const word & name) static
interpolate() [6/13]
template<class Type > static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, Istream & schemeData) static
interpolate() [7/13]
template<class Type > static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const word & name) static
interpolate() [8/13]
template<class Type > static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name) static
interpolate() [9/13]
template<class Type > static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf) static
interpolate() [10/13]
template<class Type > static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf) static
interpolate() [11/13]
template<class Type > static tmp< FieldField< fvsPatchField, Type > > interpolate (const FieldField< fvPatchField, Type > & fvpff) static
interpolate() [12/13]
template<class Type > static tmp< FieldField< fvsPatchField, Type > > interpolate (const tmp< FieldField< fvPatchField, Type > > & tfvpff) static
interpolate() [13/13]
Foam::one interpolate (const Foam::one &) inline
Definition at line 188 of file surfaceInterpolate.H.
dotInterpolate() [1/2]
template<class Type > static tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField & Sf, const GeometricField< Type, fvPatchField, volMesh > & tvf) static
Referenced by ddtScheme< Type >::fvcDdtPhiCoeff(), ddtScheme< Type >::fvcDdtPhiCoeff(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), and displacementSBRStressFvMotionSolver::solve().
dotInterpolate() [2/2]
template<class Type > static tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField & Sf, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf) static