OpenFOAM: Foam::parsing Namespace Reference
Foam::parsing Namespace Reference
Collection of static functions and data related to parsing and an isolated namespace for lexers, parsers, scanners.
Classes
class genericRagelLemonDriver
Generic interface code for Ragel/Lemon combination Subclasses should implement one or more process() methods.
Enumerations
enum class errorType { NONE = 0 , GENERAL = 1 , RANGE = 2 , TRAILING = 3 }
Functions
errorType checkConversion (const char *buf, char *endptr)
Variables
const Foam::Enum< errorType > errorNames
Detailed Description
Collection of static functions and data related to parsing and an isolated namespace for lexers, parsers, scanners.
Source files
parsing.H
parsing.C
parsingI.H
Enumeration Type Documentation
errorType
enum class errorType strong
Enumerator
NONE
No error encountered.
GENERAL
General parsing error.
RANGE
Range error.
TRAILING
Trailing content detected.
Definition at line 53 of file parsing.H.
Function Documentation
checkConversion()
Foam::parsing::errorType checkConversion (const char * buf, char * endptr) inline
Definition at line 21 of file parsingI.H.
References Foam::isspace().
Referenced by Foam::ScalarRead(), and Foam::ScalarRead().
Variable Documentation
errorNames
const Foam::Enum< Foam::parsing::errorType > errorNames extern
Referenced by NASCore::readNasScalar(), and Foam::ScalarRead().