OpenFOAM: Foam::MULES Namespace Reference
Foam::MULES Namespace Reference
Functions
template<class RdeltaTType , class RhoType , class SpType , class SuType >
void correct (const RdeltaTType &rDeltaT, const RhoType &rho, volScalarField &psi, const surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su)
template<class RhoType >
void correct (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phiCorr)
template<class RhoType , class SpType , class SuType >
void correct (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su)
template<class RhoType , class PsiMaxType , class PsiMinType >
void correct (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phi, surfaceScalarField &phiCorr, const PsiMaxType &psiMax, const PsiMinType &psiMin)
template<class RhoType , class SpType , class SuType , class PsiMaxType , class PsiMinType >
void correct (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phi, surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su, const PsiMaxType &psiMax, const PsiMinType &psiMin)
template<class RdeltaTType , class RhoType , class SpType , class SuType , class PsiMaxType , class PsiMinType >
void limiterCorr (scalarField &allLambda, const RdeltaTType &rDeltaT, const RhoType &rho, const volScalarField &psi, const surfaceScalarField &phi, const surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su, const PsiMaxType &psiMax, const PsiMinType &psiMin)
template<class RdeltaTType , class RhoType , class SpType , class SuType , class PsiMaxType , class PsiMinType >
void limitCorr (const RdeltaTType &rDeltaT, const RhoType &rho, const volScalarField &psi, const surfaceScalarField &phi, surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su, const PsiMaxType &psiMax, const PsiMinType &psiMin)
template<class RdeltaTType , class RhoType , class SpType , class SuType >
void explicitSolve (const RdeltaTType &rDeltaT, const RhoType &rho, volScalarField &psi, const surfaceScalarField &phiPsi, const SpType &Sp, const SuType &Su)
template<class RhoType >
void explicitSolve (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phiPsi)
template<class RhoType , class SpType , class SuType >
void explicitSolve (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phiPsi, const SpType &Sp, const SuType &Su)
template<class RhoType , class PsiMaxType , class PsiMinType >
void explicitSolve (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phiBD, surfaceScalarField &phiPsi, const PsiMaxType &psiMax, const PsiMinType &psiMin)
template<class RhoType , class SpType , class SuType , class PsiMaxType , class PsiMinType >
void explicitSolve (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phiBD, surfaceScalarField &phiPsi, const SpType &Sp, const SuType &Su, const PsiMaxType &psiMax, const PsiMinType &psiMin)
template<class RdeltaTType , class RhoType , class SpType , class SuType , class PsiMaxType , class PsiMinType >
void limiter (scalarField &allLambda, const RdeltaTType &rDeltaT, const RhoType &rho, const volScalarField &psi, const surfaceScalarField &phiBD, const surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su, const PsiMaxType &psiMax, const PsiMinType &psiMin)
template<class RdeltaTType , class RhoType , class SpType , class SuType , class PsiMaxType , class PsiMinType >
void limit (const RdeltaTType &rDeltaT, const RhoType &rho, const volScalarField &psi, const surfaceScalarField &phi, surfaceScalarField &phiPsi, const SpType &Sp, const SuType &Su, const PsiMaxType &psiMax, const PsiMinType &psiMin, const bool returnCorr)
template<class RhoType , class SpType , class SuType , class PsiMaxType , class PsiMinType >
void limit (const RhoType &rho, const volScalarField &psi, const surfaceScalarField &phi, surfaceScalarField &phiPsi, const SpType &Sp, const SuType &Su, const PsiMaxType &psiMax, const PsiMinType &psiMin, const bool returnCorr)
void limitSum (UPtrList< scalarField > &phiPsiCorrs)
template<class SurfaceScalarFieldList >
void limitSum (SurfaceScalarFieldList &phiPsiCorrs)
void limitSum (const UPtrList< const scalarField > &alphas, UPtrList< scalarField > &phiPsiCorrs, const labelHashSet &fixed)
template<class SurfaceScalarFieldList >
void limitSum (const SurfaceScalarFieldList &alphas, SurfaceScalarFieldList &phiPsiCorrs, const labelHashSet &fixed)
Function Documentation
correct() [1/5]
template<class RdeltaTType , class RhoType , class SpType , class SuType > void correct (const RdeltaTType & rDeltaT, const RhoType & rho, volScalarField & psi, const surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su)
Definition at line 32 of file CMULESTemplates.C.
References Foam::endl(), Foam::Info, mesh, psi, rho, Sp, and Su.
correct() [2/5]
template<class RhoType > void correct (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phiCorr)
Definition at line 73 of file CMULESTemplates.C.
References correct(), psi, and rho.
correct() [3/5]
template<class RhoType , class SpType , class SuType > void correct (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su)
Definition at line 85 of file CMULESTemplates.C.
References correct(), mesh, psi, rho, Sp, and Su.
correct() [4/5]
template<class RhoType , class PsiMaxType , class PsiMinType > void correct (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phi, surfaceScalarField & phiCorr, const PsiMaxType & psiMax, const PsiMinType & psiMin)
Definition at line 110 of file CMULESTemplates.C.
References correct(), phi, psi, and rho.
correct() [5/5]
template<class RhoType , class SpType , class SuType , class PsiMaxType , class PsiMinType > void correct (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phi, surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su, const PsiMaxType & psiMax, const PsiMinType & psiMin)
Definition at line 132 of file CMULESTemplates.C.
References correct(), limitCorr(), mesh, phi, psi, rho, Sp, and Su.
limiterCorr()
template<class RdeltaTType , class RhoType , class SpType , class SuType , class PsiMaxType , class PsiMinType > void limiterCorr (scalarField & allLambda, const RdeltaTType & rDeltaT, const RhoType & rho, const volScalarField & psi, const surfaceScalarField & phi, const surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su, const PsiMaxType & psiMax, const PsiMinType & psiMin)
Definition at line 196 of file CMULESTemplates.C.
References Foam::dimless, forAll, UPtrList< T >::get(), lambda(), Foam::max(), mesh, Foam::min(), phi, psi, rho, UPtrList< T >::size(), Sp, and Su.
Referenced by limitCorr().
limitCorr()
template<class RdeltaTType , class RhoType , class SpType , class SuType , class PsiMaxType , class PsiMinType > void limitCorr (const RdeltaTType & rDeltaT, const RhoType & rho, const volScalarField & psi, const surfaceScalarField & phi, surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su, const PsiMaxType & psiMax, const PsiMinType & psiMin)
Definition at line 572 of file CMULESTemplates.C.
References Foam::dimless, lambda(), limiterCorr(), mesh, phi, psi, rho, Sp, and Su.
Referenced by correct().
explicitSolve() [1/5]
template<class RdeltaTType , class RhoType , class SpType , class SuType > void explicitSolve (const RdeltaTType & rDeltaT, const RhoType & rho, volScalarField & psi, const surfaceScalarField & phiPsi, const SpType & Sp, const SuType & Su)
Definition at line 33 of file MULESTemplates.C.
References Foam::endl(), field(), Foam::Info, mesh, psi, rho, Sp, and Su.
Referenced by scalarTransport::execute(), explicitSolve(), explicitSolve(), explicitSolve(), explicitSolve(), twoPhaseSystem::solve(), multiphaseSystem::solveAlphas(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi().
explicitSolve() [2/5]
template<class RhoType > void explicitSolve (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phiPsi)
Definition at line 78 of file MULESTemplates.C.
References explicitSolve(), psi, and rho.
explicitSolve() [3/5]
template<class RhoType , class SpType , class SuType > void explicitSolve (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phiPsi, const SpType & Sp, const SuType & Su)
Definition at line 90 of file MULESTemplates.C.
References explicitSolve(), mesh, psi, rho, Sp, and Su.
explicitSolve() [4/5]
template<class RhoType , class PsiMaxType , class PsiMinType > void explicitSolve (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phiBD, surfaceScalarField & phiPsi, const PsiMaxType & psiMax, const PsiMinType & psiMin)
Definition at line 115 of file MULESTemplates.C.
References explicitSolve(), psi, and rho.
explicitSolve() [5/5]
template<class RhoType , class SpType , class SuType , class PsiMaxType , class PsiMinType > void explicitSolve (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phiBD, surfaceScalarField & phiPsi, const SpType & Sp, const SuType & Su, const PsiMaxType & psiMax, const PsiMinType & psiMin)
Definition at line 147 of file MULESTemplates.C.
References explicitSolve(), limit(), mesh, phi, psi, rho, Sp, and Su.
limiter()
template<class RdeltaTType , class RhoType , class SpType , class SuType , class PsiMaxType , class PsiMinType > void limiter (scalarField & allLambda, const RdeltaTType & rDeltaT, const RhoType & rho, const volScalarField & psi, const surfaceScalarField & phiBD, const surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su, const PsiMaxType & psiMax, const PsiMinType & psiMin)
Definition at line 187 of file MULESTemplates.C.
References Foam::dimless, forAll, lambda(), Foam::max(), mesh, Foam::min(), psi, rho, UPtrList< T >::size(), Sp, and Su.
limit() [1/2]
template<class RdeltaTType , class RhoType , class SpType , class SuType , class PsiMaxType , class PsiMinType > void limit (const RdeltaTType & rDeltaT, const RhoType & rho, const volScalarField & psi, const surfaceScalarField & phi, surfaceScalarField & phiPsi, const SpType & Sp, const SuType & Su, const PsiMaxType & psiMax, const PsiMinType & psiMin, const bool returnCorr)
Definition at line 573 of file MULESTemplates.C.
References Foam::dimless, forAll, lambda(), Foam::limiter(), mesh, phi, psi, rho, Sp, and Su.
Referenced by multiphaseSystem::solveAlphas(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi().
limit() [2/2]
template<class RhoType , class SpType , class SuType , class PsiMaxType , class PsiMinType > void limit (const RhoType & rho, const volScalarField & psi, const surfaceScalarField & phi, surfaceScalarField & phiPsi, const SpType & Sp, const SuType & Su, const PsiMaxType & psiMax, const PsiMinType & psiMin, const bool returnCorr)
Definition at line 659 of file MULESTemplates.C.
References limit(), mesh, phi, psi, rho, Sp, and Su.
limitSum() [1/4]
void limitSum (UPtrList< scalarField > & phiPsiCorrs)
Definition at line 27 of file MULES.C.
References forAll, lambda(), phasei, UPtrList< T >::size(), and Foam::sum().
Referenced by limitSum(), limitSum(), and multiphaseSystem::solveAlphas().
limitSum() [2/4]
template<class SurfaceScalarFieldList > void limitSum (SurfaceScalarFieldList & phiPsiCorrs)
Definition at line 688 of file MULESTemplates.C.
References boundaryFieldRef(), coupled(), forAll, limitSum(), phasei, PtrList< T >::set(), and UPtrList< T >::size().
limitSum() [3/4]
void limitSum (const UPtrList< const scalarField > & alphas, UPtrList< scalarField > & phiPsiCorrs, const labelHashSet & fixed)
Definition at line 78 of file MULES.C.
References Foam::fixed(), forAll, Foam::identity(), lambda(), phasei, and UPtrList< T >::size().
limitSum() [4/4]
template<class SurfaceScalarFieldList > void limitSum (const SurfaceScalarFieldList & alphas, SurfaceScalarFieldList & phiPsiCorrs, const labelHashSet & fixed)
Definition at line 724 of file MULESTemplates.C.
References boundaryFieldRef(), coupled(), Foam::fixed(), forAll, limitSum(), phasei, PtrList< T >::set(), and UPtrList< T >::size().