OpenFOAM: Foam::exprTools Namespace Reference
Foam::exprTools Namespace Reference
Helper methods for creating expressions.
Classes
class boolEntry
Expression representation of a bool : (false/true)
struct dimensionedScalarEntry
Create an expression string from a dimensionedScalar as its value.
struct dimensionedSphericalTensorEntry
Create an expression string from a dimensionedSphericalTensor as its value.
struct dimensionedSymmTensorEntry
Create an expression string from a dimensionedSymmTensor as its value.
struct dimensionedTensorEntry
Create an expression string from a dimensionedTensor as its value.
struct dimensionedVectorEntry
Create an expression string from a dimensionedVector as its value.
class expressionEntry
Convert dictionary entry to a stringified expression.
struct sphericalTensorEntry
Create an expression string from a sphericalTensor.
class stringEntry
Creates an expression from a string (removing surrounding quotes)
struct symmTensorEntry
Create an expression string from a symmTensor.
struct tensorEntry
Create an expression string from a tensor.
struct vectorEntry
Create an expression string from a vector.
Functions
defineTypeName (expressionEntry)
defineRunTimeSelectionTable (expressionEntry, empty)
addNamedToRunTimeSelectionTable (expressionEntry, expressionEntry, empty, direct)
addNamedToRunTimeSelectionTable (expressionEntry, expressionEntry, empty, label)
addNamedToRunTimeSelectionTable (expressionEntry, expressionEntry, empty, scalar)
addNamedToRunTimeSelectionTable (expressionEntry, expressionEntry, empty, word)
addNamedToRunTimeSelectionTable (expressionEntry, boolEntry, empty, bool)
addNamedToRunTimeSelectionTable (expressionEntry, dimensionedScalarEntry, empty, dimensionedScalar)
addNamedToRunTimeSelectionTable (expressionEntry, dimensionedVectorEntry, empty, dimensionedVector)
addNamedToRunTimeSelectionTable (expressionEntry, dimensionedTensorEntry, empty, dimensionedTensor)
addNamedToRunTimeSelectionTable (expressionEntry, dimensionedSymmTensorEntry, empty, dimensionedSymmTensor)
addNamedToRunTimeSelectionTable (expressionEntry, dimensionedSphericalTensorEntry, empty, dimensionedSphericalTensor)
addNamedToRunTimeSelectionTable (expressionEntry, stringEntry, empty, string)
addNamedToRunTimeSelectionTable (expressionEntry, stringEntry, empty, fileName)
addNamedToRunTimeSelectionTable (expressionEntry, vectorEntry, empty, vector)
addNamedToRunTimeSelectionTable (expressionEntry, tensorEntry, empty, tensor)
addNamedToRunTimeSelectionTable (expressionEntry, symmTensorEntry, empty, symmTensor)
addNamedToRunTimeSelectionTable (expressionEntry, sphericalTensorEntry, empty, sphericalTensor)
template<class Type >
string zeroValue ()
template<class Type >
string toString (const Type &data, const word &prefix)
template<class Type >
string toString (const Type &data)
template<class Type >
string toString (ITstream &is)
List< expressions::exprString > getList (const word &keyword, const dictionary &dict, bool mandatory=true, label recursionDepth=0)
Detailed Description
Helper methods for creating expressions.
Source files
exprTools.H
exprTools.C
exprToolsTemplates.C
Function Documentation
defineTypeName()
defineTypeName (expressionEntry)
defineRunTimeSelectionTable()
defineRunTimeSelectionTable (expressionEntry , empty)
addNamedToRunTimeSelectionTable() [1/16]
addNamedToRunTimeSelectionTable (expressionEntry , expressionEntry , empty , direct)
addNamedToRunTimeSelectionTable() [2/16]
addNamedToRunTimeSelectionTable (expressionEntry , expressionEntry , empty , label)
addNamedToRunTimeSelectionTable() [3/16]
addNamedToRunTimeSelectionTable (expressionEntry , expressionEntry , empty , scalar)
addNamedToRunTimeSelectionTable() [4/16]
addNamedToRunTimeSelectionTable (expressionEntry , expressionEntry , empty , word)
addNamedToRunTimeSelectionTable() [5/16]
addNamedToRunTimeSelectionTable (expressionEntry , boolEntry , empty , bool)
addNamedToRunTimeSelectionTable() [6/16]
addNamedToRunTimeSelectionTable (expressionEntry , dimensionedScalarEntry , empty , dimensionedScalar)
addNamedToRunTimeSelectionTable() [7/16]
addNamedToRunTimeSelectionTable (expressionEntry , dimensionedVectorEntry , empty , dimensionedVector)
addNamedToRunTimeSelectionTable() [8/16]
addNamedToRunTimeSelectionTable (expressionEntry , dimensionedTensorEntry , empty , dimensionedTensor)
addNamedToRunTimeSelectionTable() [9/16]
addNamedToRunTimeSelectionTable (expressionEntry , dimensionedSymmTensorEntry , empty , dimensionedSymmTensor)
addNamedToRunTimeSelectionTable() [10/16]
addNamedToRunTimeSelectionTable (expressionEntry , dimensionedSphericalTensorEntry , empty , dimensionedSphericalTensor)
addNamedToRunTimeSelectionTable() [11/16]
addNamedToRunTimeSelectionTable (expressionEntry , stringEntry , empty , string)
addNamedToRunTimeSelectionTable() [12/16]
addNamedToRunTimeSelectionTable (expressionEntry , stringEntry , empty , fileName)
addNamedToRunTimeSelectionTable() [13/16]
addNamedToRunTimeSelectionTable (expressionEntry , vectorEntry , empty , vector)
addNamedToRunTimeSelectionTable() [14/16]
addNamedToRunTimeSelectionTable (expressionEntry , tensorEntry , empty , tensor)
addNamedToRunTimeSelectionTable() [15/16]
addNamedToRunTimeSelectionTable (expressionEntry , symmTensorEntry , empty , symmTensor)
addNamedToRunTimeSelectionTable() [16/16]
addNamedToRunTimeSelectionTable (expressionEntry , sphericalTensorEntry , empty , sphericalTensor)
zeroValue()
template<class Type > string zeroValue ()
toString() [1/3]
template<class Type > string toString (const Type & data, const word & prefix)
toString() [2/3]
template<class Type > string toString (const Type & data)
toString() [3/3]
template<class Type > string toString (ITstream & is)
getList()
Foam::List< Foam::expressions::exprString > getList (const word & keyword, const dictionary & dict, bool mandatory = true, label recursionDepth = 0)
Definition at line 115 of file exprTools.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::nl, and PtrList< T >::resize().
Referenced by exprDriver::readVariableStrings().