OpenFOAM: Foam::BitOps Namespace Reference
Foam::BitOps Namespace Reference
Various bit-wise operations and adaptor methods for containers that are somewhat similar to bitSet (eg, boolList, labelHashSet).
Classes
struct bitInfo
Functions
unsigned int count (const UList< bool > &bools, const bool val=true)
bool all (const UList< bool > &bools)
bool any (const UList< bool > &bools)
bool none (const UList< bool > &bools)
void set (List< bool > &bools, const labelUList &locations)
void set (List< bool > &bools, const labelRange &range)
void set (labelHashSet &hashset, const labelRange &range)
void set (bitSet &bitset, const labelRange &range)
void unset (List< bool > &bools, const labelUList &locations)
void unset (List< bool > &bools, const labelRange &range)
void unset (labelHashSet &hashset, const labelRange &range)
void unset (bitSet &bitset, const labelRange &range)
List< bool > select (const label n, const labelUList &locations)
List< bool > select (const labelUList &locations)
List< label > toc (const UList< bool > &bools)
List< label > sortedToc (const UList< bool > &bools)
List< label > toc (const bitSet &bitset)
List< label > sortedToc (const bitSet &bitset)
List< label > toc (const labelHashSet &hashset)
List< label > sortedToc (const labelHashSet &hashset)
template<class UIntType >
unsigned int bit_count (UIntType x)
template<>
unsigned int bit_count (uint32_t x)
template<>
unsigned int bit_count (uint64_t x)
template<class UIntType , unsigned BitWidth>
UIntType repeat_value (unsigned val)
template<class UIntType >
Ostream & print (Ostream &os, UIntType value, char off='0', char on='1')
Detailed Description
Various bit-wise operations and adaptor methods for containers that are somewhat similar to bitSet (eg, boolList, labelHashSet).
The population count uses the Hamming weight (http://en.wikipedia.org/wiki/Hamming_weight).
Function Documentation
count()
unsigned int count (const UList< bool > & bools, const bool val = true) inline
Definition at line 73 of file BitOps.H.
References UList< T >::begin(), and UList< T >::end().
Referenced by geometric::add(), decompositionMethod::decompose(), and toc().
all()
bool all (const UList< bool > & bools) inline
Definition at line 83 of file BitOps.H.
References UList< T >::begin(), and UList< T >::end().
Referenced by decompositionMethod::decompose().
any()
bool any (const UList< bool > & bools) inline
Definition at line 93 of file BitOps.H.
References UList< T >::begin(), and UList< T >::end().
none()
bool none (const UList< bool > & bools) inline
Definition at line 103 of file BitOps.H.
References UList< T >::begin(), and UList< T >::end().
set() [1/4]
void set (List< bool > & bools, const labelUList & locations)
Definition at line 30 of file BitOps.C.
References UPtrList< T >::begin(), UPtrList< T >::end(), Foam::max(), List< T >::resize(), and UList< T >::size().
set() [2/4]
void set (List< bool > & bools, const labelRange & range)
Definition at line 52 of file BitOps.C.
References labelRange::adjust(), IntRange< IntType >::empty(), IntRange< IntType >::end_value(), range, List< T >::resize(), List< T >::set(), and UList< T >::size().
set() [3/4]
void set (labelHashSet & hashset, const labelRange & range)
Definition at line 81 of file BitOps.C.
References labelRange::adjust(), range, and PtrList< T >::set().
set() [4/4]
void set (bitSet & bitset, const labelRange & range)
Definition at line 93 of file BitOps.C.
References range, and bitSet::set().
unset() [1/4]
void unset (List< bool > & bools, const labelUList & locations)
Definition at line 99 of file BitOps.C.
References UList< T >::unset().
unset() [2/4]
void unset (List< bool > & bools, const labelRange & range)
Definition at line 109 of file BitOps.C.
References range, and UList< T >::unset().
unset() [3/4]
void unset (labelHashSet & hashset, const labelRange & range)
Definition at line 118 of file BitOps.C.
References range.
unset() [4/4]
void unset (bitSet & bitset, const labelRange & range)
Definition at line 127 of file BitOps.C.
References range, and bitSet::unset().
select() [1/2]
Foam::List< bool > select (const label n, const labelUList & locations)
Definition at line 133 of file BitOps.C.
References n.
select() [2/2]
Foam::List< bool > select (const labelUList & locations)
Definition at line 147 of file BitOps.C.
toc() [1/3]
Foam::List< Foam::label > toc (const UList< bool > & bools)
Definition at line 158 of file BitOps.C.
References b, count(), and UList< T >::size().
sortedToc() [1/3]
Foam::List< Foam::label > sortedToc (const UList< bool > & bools)
Definition at line 195 of file BitOps.C.
toc() [2/3]
Foam::List< Foam::label > toc (const bitSet & bitset)
Definition at line 201 of file BitOps.C.
References bitSet::toc().
sortedToc() [2/3]
Foam::List< Foam::label > sortedToc (const bitSet & bitset)
Definition at line 207 of file BitOps.C.
References bitSet::sortedToc().
toc() [3/3]
Foam::List< Foam::label > toc (const labelHashSet & hashset)
Definition at line 213 of file BitOps.C.
sortedToc() [3/3]
Foam::List< Foam::label > sortedToc (const labelHashSet & hashset)
Definition at line 219 of file BitOps.C.
bit_count() [1/3]
template<class UIntType > unsigned int bit_count (UIntType x) inline
Definition at line 245 of file BitOps.H.
References n, and x.
Referenced by bitSet::count().
bit_count() [2/3]
template<> unsigned int bit_count (uint32_t x) inline
Definition at line 259 of file BitOps.H.
References x.
bit_count() [3/3]
template<> unsigned int bit_count (uint64_t x) inline
Definition at line 272 of file BitOps.H.
References x.
repeat_value()
template<class UIntType , unsigned BitWidth> UIntType repeat_value (unsigned val) inline
Definition at line 292 of file BitOps.H.
print()
template<class UIntType > Ostream & print (Ostream & os, UIntType value, char off = '0', char on = '1') inline
Definition at line 323 of file BitOps.H.
References IOstreamOption::BINARY, and os().
Referenced by Foam::operator<<(), and PackedList< Width >::printBits().