OpenFOAM: Foam::lumpedPointTools Namespace Reference
Foam::lumpedPointTools Namespace Reference
A collection of utility functions for handling IO related to the lumped-mass movement.
Functions
List< lumpedPointStateTuple > lumpedPointStates (const dictionary &dict, quaternion::eulerOrder rotOrder=quaternion::eulerOrder::ZXZ, bool degrees=false)
List< lumpedPointStateTuple > lumpedPointStates (Istream &is, quaternion::eulerOrder rotOrder=quaternion::eulerOrder::ZXZ, bool degrees=false)
List< lumpedPointStateTuple > lumpedPointStates (const fileName &file, quaternion::eulerOrder rotOrder=quaternion::eulerOrder::ZXZ, bool degrees=false)
pointIOField points0Field (const polyMesh &mesh)
labelList lumpedPointPatchList (const pointVectorField &pvf)
labelList lumpedPointPatchList (const polyMesh &mesh)
label setPatchControls (const pointVectorField &pvf, const pointField &points0)
label setPatchControls (const fvMesh &mesh, const pointField &points0)
label setPatchControls (const fvMesh &mesh)
label setInterpolators (const pointVectorField &pvf, const pointField &points0)
label setInterpolators (const fvMesh &mesh, const pointField &points0)
label setInterpolators (const fvMesh &mesh)
Detailed Description
A collection of utility functions for handling IO related to the lumped-mass movement.
Source files
lumpedPointTools.H
lumpedPointTools.C
Function Documentation
lumpedPointStates() [1/3]
Foam::List< Foam::lumpedPointStateTuple > lumpedPointStates (const dictionary & dict, quaternion::eulerOrder rotOrder = quaternion::eulerOrder::ZXZ, bool degrees = false)
Definition at line 69 of file lumpedPointTools.C.
References PtrList< T >::append(), dict, Foam::Info, and UPtrList< T >::size().
Referenced by lumpedPointStates(), and lumpedPointStates().
lumpedPointStates() [2/3]
Foam::List< Foam::lumpedPointStateTuple > lumpedPointStates (Istream & is, quaternion::eulerOrder rotOrder = quaternion::eulerOrder::ZXZ, bool degrees = false)
Definition at line 107 of file lumpedPointTools.C.
References dict, and lumpedPointStates().
lumpedPointStates() [3/3]
Foam::List< Foam::lumpedPointStateTuple > lumpedPointStates (const fileName & file, quaternion::eulerOrder rotOrder = quaternion::eulerOrder::ZXZ, bool degrees = false)
Definition at line 120 of file lumpedPointTools.C.
References lumpedPointStates().
points0Field()
Foam::pointIOField points0Field (const polyMesh & mesh)
Definition at line 133 of file lumpedPointTools.C.
References mesh.
Referenced by setInterpolators(), and setPatchControls().
lumpedPointPatchList() [1/2]
Foam::labelList lumpedPointPatchList (const pointVectorField & pvf)
Definition at line 140 of file lumpedPointTools.C.
Referenced by lumpedPointPatchList().
lumpedPointPatchList() [2/2]
Foam::labelList lumpedPointPatchList (const polyMesh & mesh)
Definition at line 146 of file lumpedPointTools.C.
References Foam::endl(), Foam::Info, lumpedPointPatchList(), and mesh.
setPatchControls() [1/3]
Foam::label setPatchControls (const pointVectorField & pvf, const pointField & points0)
Definition at line 173 of file lumpedPointTools.C.
References points0().
Referenced by setPatchControls(), and setPatchControls().
setPatchControls() [2/3]
Foam::label setPatchControls (const fvMesh & mesh, const pointField & points0)
Definition at line 188 of file lumpedPointTools.C.
References Foam::endl(), Foam::Info, mesh, points0(), and setPatchControls().
setPatchControls() [3/3]
Foam::label setPatchControls (const fvMesh & mesh)
Definition at line 215 of file lumpedPointTools.C.
References mesh, points0(), points0Field(), and setPatchControls().
setInterpolators() [1/3]
Foam::label setInterpolators (const pointVectorField & pvf, const pointField & points0)
Definition at line 226 of file lumpedPointTools.C.
References points0().
Referenced by setInterpolators(), and setInterpolators().
setInterpolators() [2/3]
Foam::label setInterpolators (const fvMesh & mesh, const pointField & points0)
Definition at line 241 of file lumpedPointTools.C.
References Foam::endl(), Foam::Info, mesh, points0(), and setInterpolators().
setInterpolators() [3/3]
Foam::label setInterpolators (const fvMesh & mesh)
Definition at line 268 of file lumpedPointTools.C.
References mesh, points0(), points0Field(), and setInterpolators().