OpenFOAM: Foam::meshTools Namespace Reference
Foam::meshTools Namespace Reference
Collection of static functions to do various simple mesh related things.
Functions
bool visNormal (const vector &n, const vectorField &faceNormals, const labelList &faceLabels)
vectorField calcBoxPointNormals (const primitivePatch &pp)
vector normEdgeVec (const primitiveMesh &, const label edgeI)
void writeOBJ (Ostream &os, const point &pt)
void writeOBJ (Ostream &os, const UList< point > &pts)
void writeOBJ (Ostream &os, const triad &t, const point &origin)
void writeOBJ (Ostream &os, const point &p1, const point &p2, label &count)
void writeOBJ (Ostream &os, const point &p1, const point &p2)
void writeOBJ (Ostream &os, const treeBoundBox &bb)
template<class FaceType >
void writeOBJ (Ostream &os, const UList< FaceType > &faces, const UList< point > &points, const labelList &faceLabels)
template<class FaceType >
void writeOBJ (Ostream &os, const UList< FaceType > &faces, const UList< point > &points)
void writeOBJ (Ostream &os, const cellList &cells, const faceList &faces, const UList< point > &points, const labelList &cellLabels)
bool edgeOnCell (const primitiveMesh &mesh, const label celli, const label edgeI)
bool edgeOnFace (const primitiveMesh &mesh, const label facei, const label edgeI)
bool faceOnCell (const primitiveMesh &mesh, const label celli, const label facei)
label findEdge (const edgeList &edges, const labelList &candidates, const label v0, const label v1)
label findEdge (const primitiveMesh &mesh, const label v0, const label v1)
label getSharedEdge (const primitiveMesh &mesh, const label f0, const label f1)
label getSharedFace (const primitiveMesh &mesh, const label cell0, const label cell1)
void getEdgeFaces (const primitiveMesh &mesh, const label celli, const label edgeI, label &face0, label &face1)
label otherEdge (const primitiveMesh &mesh, const labelList &edgeLabels, const label thisEdgeI, const label thisVertI)
label otherFace (const primitiveMesh &mesh, const label celli, const label facei, const label edgeI)
label otherCell (const primitiveMesh &mesh, const label celli, const label facei)
label walkFace (const primitiveMesh &mesh, const label facei, const label startEdgeI, const label startVertI, const label nEdges)
void constrainToMeshCentre (const polyMesh &mesh, point &pt)
void constrainToMeshCentre (const polyMesh &mesh, pointField &pt)
void constrainDirection (const polyMesh &mesh, const Vector< label > &dirs, vector &d)
void constrainDirection (const polyMesh &mesh, const Vector< label > &dirs, vectorField &d)
void getParallelEdges (const primitiveMesh &mesh, const label celli, const label e0, label &e1, label &e2, label &e3)
vector edgeToCutDir (const primitiveMesh &mesh, const label celli, const label edgeI)
label cutDirToEdge (const primitiveMesh &mesh, const label celli, const vector &cutDir)
labelList bandCompression (const CompactListList< label > &addressing)
labelList bandCompression (const labelListList &addressing)
labelList bandCompression (const labelUList &cellCells, const labelUList &offsets)
Variables
static const label mXmYmZ = 0
static const label pXmYmZ = 1
static const label mXpYmZ = 2
static const label pXpYmZ = 3
static const label mXmYpZ = 4
static const label pXmYpZ = 5
static const label mXpYpZ = 6
static const label pXpYpZ = 7
static const label mXmYmZMask = 1 << mXmYmZ
static const label pXmYmZMask = 1 << pXmYmZ
static const label mXpYmZMask = 1 << mXpYmZ
static const label pXpYmZMask = 1 << pXpYmZ
static const label mXmYpZMask = 1 << mXmYpZ
static const label pXmYpZMask = 1 << pXmYpZ
static const label mXpYpZMask = 1 << mXpYpZ
static const label pXpYpZMask = 1 << pXpYpZ
Detailed Description
Collection of static functions to do various simple mesh related things.
Source files
meshTools.H
meshTools.C
Function Documentation
visNormal()
bool visNormal (const vector & n, const vectorField & faceNormals, const labelList & faceLabels)
Definition at line 29 of file meshTools.C.
References faceLabels(), forAll, and n.
Referenced by calcBoxPointNormals().
calcBoxPointNormals()
Foam::vectorField calcBoxPointNormals (const primitivePatch & pp)
Definition at line 49 of file meshTools.C.
References Foam::endl(), forAll, Foam::mag(), n, Foam::nl, pFaces, pp(), visNormal(), and WarningInFunction.
normEdgeVec()
Foam::vector normEdgeVec (const primitiveMesh & mesh, const label edgeI)
Definition at line 185 of file meshTools.C.
References mesh.
Referenced by edgeToCutDir(), and cellLooper::getMisAlignedEdge().
writeOBJ() [1/9]
void writeOBJ (Ostream & os, const point & pt)
Definition at line 195 of file meshTools.C.
References Foam::endl(), os(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by mappedPatchBase::calcAMI(), polyDualMesh::calcFeatures(), mappedPatchBase::calcMapping(), hexCellLooper::cut(), Foam::drawHitProblem(), meshRefinement::dumpIntersections(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSamples(), Foam::operator<<(), cyclicAMIPolyPatch::resetAMI(), motionSmootherAlgo::setDisplacement(), hexRef8::setRefinement(), faceCollapser::setRefinement(), removeFaces::setRefinement(), refinementIterator::setRefinement(), duplicatePoints::setRefinement(), box::writeBoxes(), AMIInterpolation::writeFaceConnectivity(), advancingFrontAMI::writeIntersectionOBJ(), enrichedPatch::writeOBJ(), surfaceFeatures::writeObj(), writeOBJ(), writeOBJ(), writeOBJ(), writeOBJ(), and writeOBJ().
writeOBJ() [2/9]
void writeOBJ (Ostream & os, const UList< point > & pts)
Definition at line 205 of file meshTools.C.
References forAll, Foam::nl, os(), pts, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
writeOBJ() [3/9]
void writeOBJ (Ostream & os, const triad & t, const point & origin)
Definition at line 220 of file meshTools.C.
References forAll, os(), and writeOBJ().
writeOBJ() [4/9]
void writeOBJ (Ostream & os, const point & p1, const point & p2, label & count)
Definition at line 234 of file meshTools.C.
References Foam::endl(), Foam::nl, os(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
writeOBJ() [5/9]
void writeOBJ (Ostream & os, const point & p1, const point & p2)
Definition at line 250 of file meshTools.C.
References Foam::endl(), Foam::nl, os(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
writeOBJ() [6/9]
void writeOBJ (Ostream & os, const treeBoundBox & bb)
Definition at line 265 of file meshTools.C.
References e, Foam::nl, os(), treeBoundBox::points(), and writeOBJ().
writeOBJ() [7/9]
template<class FaceType > void writeOBJ (Ostream & os, const UList< FaceType > & faces, const UList< point > & points, const labelList & faceLabels)
Definition at line 23 of file meshToolsTemplates.C.
References Foam::endl(), f(), faceLabels(), forAll, os(), points, and writeOBJ().
writeOBJ() [8/9]
template<class FaceType > void writeOBJ (Ostream & os, const UList< FaceType > & faces, const UList< point > & points)
Definition at line 59 of file meshToolsTemplates.C.
References forAll, os(), points, UPtrList< T >::size(), and writeOBJ().
writeOBJ() [9/9]
void writeOBJ (Ostream & os, const cellList & cells, const faceList & faces, const UList< point > & points, const labelList & cellLabels)
Definition at line 280 of file meshTools.C.
References cells, os(), points, UList< T >::size(), and writeOBJ().
edgeOnCell()
bool edgeOnCell (const primitiveMesh & mesh, const label celli, const label edgeI)
Definition at line 300 of file meshTools.C.
References mesh.
Referenced by cellLooper::getVertEdgesNonFace().
edgeOnFace()
bool edgeOnFace (const primitiveMesh & mesh, const label facei, const label edgeI)
Definition at line 311 of file meshTools.C.
References mesh.
Referenced by cellFeatures::isFeatureVertex().
faceOnCell()
bool faceOnCell (const primitiveMesh & mesh, const label celli, const label facei)
Definition at line 322 of file meshTools.C.
References mesh.
Referenced by getEdgeFaces(), and cellLooper::getVertFacesNonEdge().
findEdge() [1/2]
Foam::label findEdge (const edgeList & edges, const labelList & candidates, const label v0, const label v1)
Definition at line 351 of file meshTools.C.
References e, and forAll.
Referenced by edgeVertex::cutPairToEdge().
findEdge() [2/2]
Foam::label findEdge (const primitiveMesh & mesh, const label v0, const label v1)
Definition at line 374 of file meshTools.C.
References e, forAll, and mesh.
getSharedEdge()
Foam::label getSharedEdge (const primitiveMesh & mesh, const label f0, const label f1)
Definition at line 400 of file meshTools.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, and mesh.
getSharedFace()
Foam::label getSharedFace (const primitiveMesh & mesh, const label cell0, const label cell1)
Definition at line 433 of file meshTools.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, and mesh.
Referenced by undoableMeshCutter::getSplitFaces().
getEdgeFaces()
void getEdgeFaces (const primitiveMesh & mesh, const label celli, const label edgeI, label & face0, label & face1)
Definition at line 471 of file meshTools.C.
References Foam::abort(), faceOnCell(), Foam::FatalError, FatalErrorInFunction, forAll, and mesh.
Referenced by hexCellLooper::cut(), topoCellLooper::cut(), directionInfo::edgeToFaceIndex(), cellLooper::getVertFacesNonEdge(), and otherFace().
otherEdge()
Foam::label otherEdge (const primitiveMesh & mesh, const labelList & edgeLabels, const label thisEdgeI, const label thisVertI)
Definition at line 513 of file meshTools.C.
References Foam::abort(), e, Foam::FatalError, FatalErrorInFunction, forAll, and mesh.
Referenced by directionInfo::updateCell(), and walkFace().
otherFace()
Foam::label otherFace (const primitiveMesh & mesh, const label celli, const label facei, const label edgeI)
Definition at line 547 of file meshTools.C.
References getEdgeFaces(), and mesh.
Referenced by directionInfo::updateCell().
otherCell()
Foam::label otherCell (const primitiveMesh & mesh, const label celli, const label facei)
Definition at line 571 of file meshTools.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and mesh.
walkFace()
Foam::label walkFace (const primitiveMesh & mesh, const label facei, const label startEdgeI, const label startVertI, const label nEdges)
Definition at line 595 of file meshTools.C.
References mesh, and otherEdge().
Referenced by directionInfo::edgeToFaceIndex().
constrainToMeshCentre() [1/2]
void constrainToMeshCentre (const polyMesh & mesh, point & pt)
Definition at line 621 of file meshTools.C.
References Foam::max(), mesh, and Foam::min().
Referenced by twoDPointCorrector::correctDisplacement(), twoDPointCorrector::correctPoints(), particle< Type >::deviationFromMeshCentre(), InjectionModel< CloudType >::inject(), and InjectionModel< CloudType >::injectSteadyState().
constrainToMeshCentre() [2/2]
void constrainToMeshCentre (const polyMesh & mesh, pointField & pt)
Definition at line 642 of file meshTools.C.
References forAll, Foam::max(), mesh, Foam::min(), and pts.
constrainDirection() [1/2]
void constrainDirection (const polyMesh & mesh, const Vector< label > & dirs, vector & d)
Definition at line 679 of file meshTools.C.
Referenced by KinematicParcel< ParcelType >::calcVelocity(), InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::injectSteadyState(), DSMCParcel< ParcelType >::move(), and KinematicSurfaceFilm< CloudType >::splashInteraction().
constrainDirection() [2/2]
void constrainDirection (const polyMesh & mesh, const Vector< label > & dirs, vectorField & d)
Definition at line 696 of file meshTools.C.
References forAll.
getParallelEdges()
void getParallelEdges (const primitiveMesh & mesh, const label celli, const label e0, label & e1, label & e2, label & e3)
Definition at line 729 of file meshTools.C.
References UPtrList< T >::end(), and mesh.
Referenced by cutDirToEdge().
edgeToCutDir()
Foam::vector edgeToCutDir (const primitiveMesh & mesh, const label celli, const label edgeI)
Definition at line 755 of file meshTools.C.
References Foam::abort(), UPtrList< T >::end(), Foam::FatalError, FatalErrorInFunction, mesh, and normEdgeVec().
Referenced by cutDirToEdge().
cutDirToEdge()
Foam::label cutDirToEdge (const primitiveMesh & mesh, const label celli, const vector & cutDir)
Definition at line 802 of file meshTools.C.
References Foam::abort(), edgeToCutDir(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, getParallelEdges(), Foam::mag(), mesh, and UPtrList< T >::size().
Referenced by hexCellLooper::cut().
bandCompression() [1/3]
Foam::labelList bandCompression (const CompactListList< label > & addressing)
Definition at line 308 of file bandCompression.C.
Referenced by Foam::bandCompression(), Foam::bandCompression(), PrimitivePatch< FaceList, PointField >::projectFaceCentres(), CuthillMcKeeRenumber::renumber(), CuthillMcKeeRenumber::renumber(), CuthillMcKeeRenumber::renumber(), and CuthillMcKeeRenumber::renumber().
bandCompression() [2/3]
Foam::labelList bandCompression (const labelListList & addressing)
Definition at line 317 of file bandCompression.C.
bandCompression() [3/3]
Foam::labelList bandCompression (const labelUList & cellCells, const labelUList & offsets)
Definition at line 162 of file bandCompression.C.
References PtrList< T >::clear(), UPtrList< T >::empty(), UPtrList< T >::front(), Foam::labelMax, Foam::max(), PtrList< T >::push_back(), UPtrList< T >::size(), UList< T >::size(), Foam::sortedOrder(), and UPtrList< T >::test().
Variable Documentation
mXmYmZ
const label mXmYmZ = 0 static
Definition at line 62 of file meshTools.H.
pXmYmZ
const label pXmYmZ = 1 static
Definition at line 63 of file meshTools.H.
mXpYmZ
const label mXpYmZ = 2 static
Definition at line 64 of file meshTools.H.
pXpYmZ
const label pXpYmZ = 3 static
Definition at line 65 of file meshTools.H.
mXmYpZ
const label mXmYpZ = 4 static
Definition at line 67 of file meshTools.H.
pXmYpZ
const label pXmYpZ = 5 static
Definition at line 68 of file meshTools.H.
mXpYpZ
const label mXpYpZ = 6 static
Definition at line 69 of file meshTools.H.
pXpYpZ
const label pXpYpZ = 7 static
Definition at line 70 of file meshTools.H.
mXmYmZMask
const label mXmYmZMask = 1 << mXmYmZ static
Definition at line 72 of file meshTools.H.
pXmYmZMask
const label pXmYmZMask = 1 << pXmYmZ static
Definition at line 73 of file meshTools.H.
mXpYmZMask
const label mXpYmZMask = 1 << mXpYmZ static
Definition at line 74 of file meshTools.H.
pXpYmZMask
const label pXpYmZMask = 1 << pXpYmZ static
Definition at line 75 of file meshTools.H.
mXmYpZMask
const label mXmYpZMask = 1 << mXmYpZ static
Definition at line 77 of file meshTools.H.
pXmYpZMask
const label pXmYpZMask = 1 << pXmYpZ static
Definition at line 78 of file meshTools.H.
mXpYpZMask
const label mXpYpZMask = 1 << mXpYpZ static
Definition at line 79 of file meshTools.H.
pXpYpZMask
const label pXpYpZMask = 1 << pXpYpZ static
Definition at line 80 of file meshTools.H.