OpenFOAM: Foam::RBD Namespace Reference
Foam::RBD Namespace Reference
Namespaces
namespace joints
Namespace for rigid-body joints.
namespace restraints
Namespace for rigid-body dynamics restraints.
namespace rigidBodySolvers
Classes
class compositeBody
class cuboid
class joint
Abstract base-class for all rigid-body joints.
class jointBody
class masslessBody
class restraint
Base class for defining restraints for rigid-body dynamics.
class rigidBody
class rigidBodyInertia
class rigidBodyModel
Basic rigid-body model representing a system of rigid-bodies connected by 1-6 DoF joints.
class rigidBodyModelState
Holds the motion state of rigid-body model.
class rigidBodyMotion
Six degree of freedom motion for a rigid body.
class rigidBodySolver
class sphere
class subBody
Functions
defineTypeNameAndDebug (cuboid, 0)
addToRunTimeSelectionTable (rigidBody, cuboid, dictionary)
defineTypeNameAndDebug (jointBody, 0)
addToRunTimeSelectionTable (rigidBody, jointBody, dictionary)
defineTypeNameAndDebug (masslessBody, 0)
addToRunTimeSelectionTable (rigidBody, masslessBody, dictionary)
defineTypeNameAndDebug (rigidBody, 0)
defineRunTimeSelectionTable (rigidBody, dictionary)
addToRunTimeSelectionTable (rigidBody, rigidBody, dictionary)
Ostream & operator<< (Ostream &, const rigidBody &)
defineTypeNameAndDebug (sphere, 0)
addToRunTimeSelectionTable (rigidBody, sphere, dictionary)
defineTypeNameAndDebug (joint, 0)
defineRunTimeSelectionTable (joint, dictionary)
Ostream & operator<< (Ostream &, const joint &)
defineTypeNameAndDebug (restraint, 0)
defineRunTimeSelectionTable (restraint, dictionary)
Istream & operator>> (Istream &, rigidBodyInertia &)
Ostream & operator<< (Ostream &, const rigidBodyInertia &)
rigidBodyInertia operator+ (const rigidBodyInertia &rbi1, const rigidBodyInertia &rbi2)
spatialVector operator& (const rigidBodyInertia &rbi, const spatialVector &sv)
rigidBodyInertia transform (const spatialTransform &X, const rigidBodyInertia &I)
defineTypeNameAndDebug (rigidBodyModel, 0)
Ostream & operator<< (Ostream &, const rigidBodyModel &)
Istream & operator>> (Istream &, rigidBodyModelState &)
Ostream & operator<< (Ostream &, const rigidBodyModelState &)
defineTypeNameAndDebug (rigidBodySolver, 0)
defineRunTimeSelectionTable (rigidBodySolver, dictionary)
Function Documentation
defineTypeNameAndDebug() [1/9]
defineTypeNameAndDebug (cuboid , 0)
addToRunTimeSelectionTable() [1/5]
addToRunTimeSelectionTable (rigidBody , cuboid , dictionary)
defineTypeNameAndDebug() [2/9]
defineTypeNameAndDebug (jointBody , 0)
addToRunTimeSelectionTable() [2/5]
addToRunTimeSelectionTable (rigidBody , jointBody , dictionary)
defineTypeNameAndDebug() [3/9]
defineTypeNameAndDebug (masslessBody , 0)
addToRunTimeSelectionTable() [3/5]
addToRunTimeSelectionTable (rigidBody , masslessBody , dictionary)
defineTypeNameAndDebug() [4/9]
defineTypeNameAndDebug (rigidBody , 0)
defineRunTimeSelectionTable() [1/4]
defineRunTimeSelectionTable (rigidBody , dictionary)
addToRunTimeSelectionTable() [4/5]
addToRunTimeSelectionTable (rigidBody , rigidBody , dictionary)
operator<<() [1/5]
Foam::Ostream & operator<< (Ostream & os, const rigidBody & rb) inline
Definition at line 68 of file rigidBodyI.H.
References os().
defineTypeNameAndDebug() [5/9]
defineTypeNameAndDebug (sphere , 0)
addToRunTimeSelectionTable() [5/5]
addToRunTimeSelectionTable (rigidBody , sphere , dictionary)
defineTypeNameAndDebug() [6/9]
defineTypeNameAndDebug (joint , 0)
defineRunTimeSelectionTable() [2/4]
defineRunTimeSelectionTable (joint , dictionary)
operator<<() [2/5]
Foam::Ostream & operator<< (Ostream & os, const joint & j) inline
Definition at line 108 of file jointI.H.
References Ostream::beginBlock(), os(), and joint::write().
defineTypeNameAndDebug() [7/9]
defineTypeNameAndDebug (restraint , 0)
defineRunTimeSelectionTable() [3/4]
defineRunTimeSelectionTable (restraint , dictionary)
operator>>() [1/2]
Foam::Istream & operator>> (Istream & is, rigidBodyInertia & rbi) inline
Definition at line 134 of file rigidBodyInertiaI.H.
operator<<() [3/5]
Foam::Ostream & operator<< (Ostream & os, const rigidBodyInertia & rbi) inline
Definition at line 145 of file rigidBodyInertiaI.H.
References Foam::endl(), Foam::nl, and os().
operator+()
rigidBodyInertia operator+ (const rigidBodyInertia & rbi1, const rigidBodyInertia & rbi2) inline
Definition at line 168 of file rigidBodyInertiaI.H.
operator&()
spatialVector operator& (const rigidBodyInertia & rbi, const spatialVector & sv) inline
Definition at line 189 of file rigidBodyInertiaI.H.
transform()
rigidBodyInertia transform (const spatialTransform & X, const rigidBodyInertia & I) inline
Definition at line 209 of file rigidBodyInertiaI.H.
References rigidBodyInertia::c(), spatialTransform::E(), rigidBodyInertia::Ic(), rigidBodyInertia::m(), spatialTransform::r(), and Foam::transform().
Referenced by rigidBody::merge().
defineTypeNameAndDebug() [8/9]
defineTypeNameAndDebug (rigidBodyModel , 0)
operator<<() [4/5]
Foam::Ostream & operator<< (Ostream & os, const rigidBodyModel & rbm)
Definition at line 460 of file rigidBodyModel.C.
References os().
operator>>() [2/2]
Foam::Istream & operator>> (Istream & is, rigidBodyModelState & state)
Definition at line 48 of file rigidBodyModelStateIO.C.
References FUNCTION_NAME.
operator<<() [5/5]
Foam::Ostream & operator<< (Ostream & os, const rigidBodyModelState & state)
Definition at line 65 of file rigidBodyModelStateIO.C.
References IOstream::check(), FUNCTION_NAME, os(), and token::SPACE.
defineTypeNameAndDebug() [9/9]
defineTypeNameAndDebug (rigidBodySolver , 0)
defineRunTimeSelectionTable() [4/4]
defineRunTimeSelectionTable (rigidBodySolver , dictionary)