OpenFOAM: Foam::ListListOps Namespace Reference
Foam::ListListOps Namespace Reference
Various utility functions to work on Lists of Lists (usually resulting from 'gather'ing and combining information from individual processors)
Functions
template<class T , class Addr , class AccessOp >
labelList subSizes (const IndirectListBase< T, Addr > &lists, AccessOp aop)
template<class IntListType >
void inplaceRenumber (const labelUList &oldToNew, IntListType &lists)
template<class T , class AccessOp >
labelList subSizes (const UList< T > &lists, AccessOp aop=accessOp< T >())
template<class T , class AccessOp >
label sumSizes (const UList< T > &lists, AccessOp aop=accessOp< T >())
template<class AccessType , class T , class AccessOp >
AccessType combine (const UList< T > &lists, AccessOp aop=accessOp< T >())
template<class AccessType , class T , class AccessOp , class OffsetOp >
AccessType combineOffset (const UList< T > &lists, const labelUList &offsets, AccessOp aop, OffsetOp oop=offsetOp< T >())
Detailed Description
Various utility functions to work on Lists of Lists (usually resulting from 'gather'ing and combining information from individual processors)
combine :
takes (elements of) sublists and appends them into one big list.
combineOffset :
similar and also adds offset.
The access of data is through an AccessOp so that data can be 'gather'ed in one go, minimizing communication, and then picked apart and recombined.
Example:
// Assuming myContainer defined which holds all the data I want to
// transfer (say a pointField and a faceList). myContainer also defines
// access operators to
// access the individual elements, say myContainerPoints::operator(),
// and myContainerFaces::operator()
List<myContainer> gatheredData(Pstream::nProcs());
gatheredData[Pstream::myProcNo()] = myContainer(points, faces);
// Gather data onto master
Pstream::gatherList(gatheredData);
// Combine
pointField combinedPoints
(
    ListListOps::combine<pointField>
    (
        gatheredData,
        myContainerPoints()
    )
);
// Combine and renumber (so combinedFaces indexes combinedPoints)
// Extract sizes of individual lists
labelList sizes
(
    ListListOps::subSizes(gatheredData, myContainerPoints())
);
// Renumber using user-defined operator offsetOp<face>()
faceList combinedFaces
(
    ListListOps::combineOffset<faceList>
    (
        gatheredData, sizes, myContainerFaces(), offsetOp<face>()
    )
);
Source files
ListListOps.H
ListListOps.C
Function Documentation
subSizes() [1/2]
template<class T , class Addr , class AccessOp > labelList subSizes (const IndirectListBase< T, Addr > & lists, AccessOp aop)
Definition at line 66 of file ensightOutput.H.
References UPtrList< T >::begin(), Foam::output(), UPtrList< T >::size(), and T.
inplaceRenumber()
template<class IntListType > void inplaceRenumber (const labelUList & oldToNew, IntListType & lists)
Definition at line 91 of file ensightOutput.H.
Referenced by ensightFaces::write().
subSizes() [2/2]
template<class T , class AccessOp > labelList subSizes (const UList< T > & lists, AccessOp aop = accessOp< T >())
sumSizes()
template<class T , class AccessOp > label sumSizes (const UList< T > & lists, AccessOp aop = accessOp< T >())
combine()
template<class AccessType , class T , class AccessOp > AccessType combine (const UList< T > & lists, AccessOp aop = accessOp<T>())
Definition at line 61 of file ListListOps.C.
References UPtrList< T >::begin(), UPtrList< T >::size(), and T.
Referenced by InflationInjection< CloudType >::parcelsToInject().
combineOffset()
template<class AccessType , class T , class AccessOp , class OffsetOp > AccessType combineOffset (const UList< T > & lists, const labelUList & offsets, AccessOp aop, OffsetOp oop = offsetOp<T>())
Definition at line 91 of file ListListOps.C.
References UPtrList< T >::begin(), UList< T >::begin(), UPtrList< T >::size(), and T.