OpenFOAM: Foam::PtrListOps Namespace Reference
Foam::PtrListOps Namespace Reference
Various utility functions to operate on Pointer Lists.
Functions
template<class ReturnType , class T , class AccessOp >
List< ReturnType > get (const UPtrList< T > &list, const AccessOp &aop)
template<class T , class UnaryMatchPredicate >
List< word > names (const UPtrList< T > &list, const UnaryMatchPredicate &matcher)
template<class T >
List< word > names (const UPtrList< T > &list)
template<class T , class UnaryMatchPredicate >
label firstMatching (const UPtrList< T > &list, const UnaryMatchPredicate &matcher)
template<class T , class UnaryMatchPredicate >
labelList findMatching (const UPtrList< T > &list, const UnaryMatchPredicate &matcher)
Detailed Description
Various utility functions to operate on Pointer Lists.
Source files
PtrListOps.H
PtrListOpsTemplates.C
Function Documentation
get()
template<class ReturnType , class T , class AccessOp > List< ReturnType > get (const UPtrList< T > & list, const AccessOp & aop)
names() [1/2]
template<class T , class UnaryMatchPredicate > List< word > names (const UPtrList< T > & list, const UnaryMatchPredicate & matcher)
Referenced by faFieldDecomposer::fieldsCache::privateCache::decompose(), fvFieldDecomposer::fieldsCache::privateCache::decompose(), pointFieldDecomposer::fieldsCache::privateCache::decompose(), coordinateSystems::names(), coordinateSystems::names(), ZoneMesh< ZoneType, MeshType >::names(), coordinateSystems::names(), and ZoneMesh< pointZone, polyMesh >::updateMetaData().
names() [2/2]
template<class T > List< word > names (const UPtrList< T > & list)
firstMatching()
template<class T , class UnaryMatchPredicate > label firstMatching (const UPtrList< T > & list, const UnaryMatchPredicate & matcher)
Referenced by coordinateSystems::cfind(), faBoundaryMesh::findIndex(), polyBoundaryMesh::findIndex(), ZoneMesh< ZoneType, MeshType >::findIndex(), coordinateSystems::findIndex(), ZoneMesh< ZoneType, MeshType >::findIndex(), coordinateSystems::findIndex(), faBoundaryMesh::findPatchID(), polyBoundaryMesh::findPatchID(), ZoneMesh< ZoneType, MeshType >::findZoneID(), faBoundaryMesh::indices(), polyBoundaryMesh::indices(), and ZoneMesh< ZoneType, MeshType >::indices().
findMatching()
template<class T , class UnaryMatchPredicate > labelList findMatching (const UPtrList< T > & list, const UnaryMatchPredicate & matcher)
Referenced by coordinateSystems::indices(), faBoundaryMesh::indices(), polyBoundaryMesh::indices(), ZoneMesh< ZoneType, MeshType >::indices(), coordinateSystems::indices(), faBoundaryMesh::indices(), polyBoundaryMesh::indices(), and ZoneMesh< ZoneType, MeshType >::indices().