OpenFOAM: Foam::fvm Namespace Reference
Foam::fvm Namespace Reference
Namespace of functions to calculate implicit derivatives returning a matrix.
Functions
template<class Type >
tmp< fvMatrix< Type > > d2dt2 (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > d2dt2 (const dimensionedScalar &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > d2dt2 (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const one &, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const dimensionedScalar &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const one &, const one &, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const one &, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const volScalarField &alpha, const one &, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > div (const surfaceScalarField &flux, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< fvMatrix< Type > > div (const tmp< surfaceScalarField > &tflux, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< fvMatrix< Type > > div (const surfaceScalarField &flux, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > div (const tmp< surfaceScalarField > &tflux, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > laplacian (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< fvMatrix< Type > > laplacian (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > laplacian (const zero &, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< fvMatrix< Type > > laplacian (const zero &, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > laplacian (const one &, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< fvMatrix< Type > > laplacian (const one &, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const dimensioned< GType > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const dimensioned< GType > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > &tGamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
zeroField Su (const Foam::zero, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > Su (const dimensioned< Type > &su, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > Su (const DimensionedField< Type, volMesh > &su, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > Su (const tmp< DimensionedField< Type, volMesh > > &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > Su (const tmp< GeometricField< Type, fvPatchField, volMesh > > &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
zeroField Sp (const Foam::zero, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > Sp (const dimensionedScalar &sp, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > Sp (const DimensionedField< scalar, volMesh > &sp, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > Sp (const tmp< DimensionedField< scalar, volMesh > > &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > Sp (const tmp< volScalarField > &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
zeroField SuSp (const Foam::zero, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > SuSp (const dimensionedScalar &susp, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > SuSp (const DimensionedField< scalar, volMesh > &susp, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > SuSp (const tmp< DimensionedField< scalar, volMesh > > &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > SuSp (const tmp< volScalarField > &, const GeometricField< Type, fvPatchField, volMesh > &)
Detailed Description
Namespace of functions to calculate implicit derivatives returning a matrix.
Temporal derivatives are calculated using Euler-implicit, backward differencing or Crank-Nicolson. Spatial derivatives are calculated using Gauss' Theorem.
Function Documentation
d2dt2() [1/3]
template<class Type > tmp< fvMatrix< Type > > d2dt2 (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 40 of file fvmD2dt2.C.
References d2dt2Scheme< Type >::New().
d2dt2() [2/3]
template<class Type > tmp< fvMatrix< Type > > d2dt2 (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 55 of file fvmD2dt2.C.
References d2dt2Scheme< Type >::New(), and rho.
d2dt2() [3/3]
template<class Type > tmp< fvMatrix< Type > > d2dt2 (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 71 of file fvmD2dt2.C.
References d2dt2Scheme< Type >::New(), and rho.
ddt() [1/8]
template<class Type > tmp< fvMatrix< Type > > ddt (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 40 of file fvmDdt.C.
References ddtScheme< Type >::New().
Referenced by multiphaseMangrovesSource::addSup(), multiphaseMangrovesSource::addSup(), Implicit< CloudType >::cacheFields(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), kL< BasicTurbulenceModel >::correct(), adjointSpalartAllmaras::correct(), kineticTheoryModel::correct(), IATE::correct(), kkLOmega::correct(), LamBremhorstKE::correct(), LienCubicKE::correct(), LienLeschziner::correct(), qZeta::correct(), ShihQuadraticKE::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), SpalartAllmarasBase< BasicEddyViscosityModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), EBRSM< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::correct(), thixotropicViscosity::correct(), relaxation::correct(), waxSolventEvaporation::correctModel(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), ddt(), ddt(), ddt(), ddt(), thermo::evolveRegion(), energyTransport::execute(), scalarTransport::execute(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransfer(), populationBalanceModel::solve(), twoPhaseSystem::solve(), reactingOneDim::solveContinuity(), kinematicSingleLayer::solveContinuity(), reactingOneDim::solveEnergy(), thermoSingleLayer::solveEnergy(), thermalBaffle::solveEnergy(), kinematicSingleLayer::solveMomentum(), reactingOneDim::solveSpeciesMass(), kinematicSingleLayer::solveThickness(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi(), MovingPhaseModel< BasePhaseModel >::UEqn(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::YiEqn().
ddt() [2/8]
template<class Type > tmp< fvMatrix< Type > > ddt (const one & , const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 55 of file fvmDdt.C.
References ddt().
ddt() [3/8]
template<class Type > tmp< fvMatrix< Type > > ddt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 67 of file fvmDdt.C.
References ddtScheme< Type >::New(), and rho.
ddt() [4/8]
template<class Type > tmp< fvMatrix< Type > > ddt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 83 of file fvmDdt.C.
References ddtScheme< Type >::New(), and rho.
ddt() [5/8]
template<class Type > tmp< fvMatrix< Type > > ddt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 99 of file fvmDdt.C.
References alpha, ddtScheme< Type >::New(), and rho.
ddt() [6/8]
template<class Type > tmp< fvMatrix< Type > > ddt (const one & , const one & , const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 122 of file fvmDdt.C.
References ddt().
ddt() [7/8]
template<class Type > tmp< fvMatrix< Type > > ddt (const one & , const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 135 of file fvmDdt.C.
References ddt(), and rho.
ddt() [8/8]
template<class Type > tmp< fvMatrix< Type > > ddt (const volScalarField & alpha, const one & , const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 148 of file fvmDdt.C.
References alpha, and ddt().
div() [1/4]
template<class Type > tmp< fvMatrix< Type > > div (const surfaceScalarField & flux, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 40 of file fvmDiv.C.
References Foam::name(), and convectionScheme< Type >::New().
Referenced by ATCstandard::addATC(), ATCUaGradU::addATC(), Implicit< CloudType >::cacheFields(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), kL< BasicTurbulenceModel >::correct(), adjointkOmegaSST::correct(), adjointSpalartAllmaras::correct(), kineticTheoryModel::correct(), IATE::correct(), radiativeIntensityRay::correct(), kkLOmega::correct(), LamBremhorstKE::correct(), LienCubicKE::correct(), LienLeschziner::correct(), qZeta::correct(), ShihQuadraticKE::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), SpalartAllmarasBase< BasicEddyViscosityModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), EBRSM< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::correct(), thixotropicViscosity::correct(), relaxation::correct(), advectionDiffusion::correct(), incompressiblePrimalSolver::correctBoundaryConditions(), waxSolventEvaporation::correctModel(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), div(), div(), div(), age::execute(), energyTransport::execute(), scalarTransport::execute(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), adjointSimple::mainIter(), simple::mainIter(), MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransfer(), MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransferf(), adjointEikonalSolver::solve(), thermoSingleLayer::solveEnergy(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), MovingPhaseModel< BasePhaseModel >::UEqn(), MovingPhaseModel< BasePhaseModel >::UfEqn(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::YiEqn().
div() [2/4]
template<class Type > tmp< fvMatrix< Type > > div (const tmp< surfaceScalarField > & tflux, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 57 of file fvmDiv.C.
References PtrList< T >::clear(), div(), and Foam::name().
div() [3/4]
template<class Type > tmp< fvMatrix< Type > > div (const surfaceScalarField & flux, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 72 of file fvmDiv.C.
References div().
div() [4/4]
template<class Type > tmp< fvMatrix< Type > > div (const tmp< surfaceScalarField > & tflux, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 83 of file fvmDiv.C.
References PtrList< T >::clear(), and div().
laplacian() [1/16]
template<class Type > tmp< fvMatrix< Type > > laplacian (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 40 of file fvmLaplacian.C.
References Foam::dimless, laplacian(), Foam::name(), and IOobjectOption::NO_READ.
Referenced by jouleHeatingSource::addSup(), Implicit< CloudType >::cacheFields(), P1::calculate(), hydrostaticPressure::calculateAndWrite(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), kL< BasicTurbulenceModel >::correct(), adjointkOmegaSST::correct(), adjointSpalartAllmaras::correct(), kineticTheoryModel::correct(), kkLOmega::correct(), LamBremhorstKE::correct(), LienCubicKE::correct(), LienLeschziner::correct(), qZeta::correct(), ShihQuadraticKE::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), SpalartAllmarasBase< BasicEddyViscosityModel >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), EBRSM< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::correct(), advectionDiffusion::correct(), Poisson::correct(), incompressiblePrimalSolver::correctBoundaryConditions(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), adjointkOmegaSST::divDevReff(), adjointLaminar::divDevReff(), adjointSpalartAllmaras::divDevReff(), ReynoldsStress< BasicTurbulenceModel >::DivDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), kineticTheoryModel::divDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), thermo::evolveRegion(), age::execute(), electricPotential::execute(), energyTransport::execute(), scalarTransport::execute(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), laplacian(), adjointSimple::mainIter(), simple::mainIter(), displacementComponentLaplacianFvMotionSolver::solve(), velocityComponentLaplacianFvMotionSolver::solve(), displacementLaplacianFvMotionSolver::solve(), displacementSBRStressFvMotionSolver::solve(), solidBodyDisplacementLaplacianFvMotionSolver::solve(), surfaceAlignedSBRStressFvMotionSolver::solve(), velocityLaplacianFvMotionSolver::solve(), elasticityMotionSolver::solve(), laplacianMotionSolver::solve(), adjointEikonalSolver::solve(), adjointMeshMovementSolver::solve(), twoPhaseSystem::solve(), reactingOneDim::solveEnergy(), thermalBaffle::solveEnergy(), sensitivityBezierFI::solveMeshMovementEqn(), kinematicSingleLayer::solveThickness(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::YiEqn().
laplacian() [2/16]
template<class Type > tmp< fvMatrix< Type > > laplacian (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 65 of file fvmLaplacian.C.
References Foam::dimless, laplacian(), and IOobjectOption::NO_READ.
laplacian() [3/16]
template<class Type > tmp< fvMatrix< Type > > laplacian (const zero & , const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 94 of file fvmLaplacian.C.
laplacian() [4/16]
template<class Type > tmp< fvMatrix< Type > > laplacian (const zero & , const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 110 of file fvmLaplacian.C.
laplacian() [5/16]
template<class Type > tmp< fvMatrix< Type > > laplacian (const one & , const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 125 of file fvmLaplacian.C.
References laplacian(), and Foam::name().
laplacian() [6/16]
template<class Type > tmp< fvMatrix< Type > > laplacian (const one & , const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 138 of file fvmLaplacian.C.
References laplacian().
laplacian() [7/16]
template<class Type , class GType > tmp< fvMatrix< Type > > laplacian (const dimensioned< GType > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 150 of file fvmLaplacian.C.
References gamma, laplacian(), Foam::name(), and IOobjectOption::NO_READ.
laplacian() [8/16]
template<class Type , class GType > tmp< fvMatrix< Type > > laplacian (const dimensioned< GType > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 176 of file fvmLaplacian.C.
References gamma, laplacian(), and IOobjectOption::NO_READ.
laplacian() [9/16]
template<class Type , class GType > tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 203 of file fvmLaplacian.C.
References gamma, Foam::name(), and laplacianScheme< Type, GType >::New().
laplacian() [10/16]
template<class Type , class GType > tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 220 of file fvmLaplacian.C.
References PtrList< T >::clear(), laplacian(), and Foam::name().
laplacian() [11/16]
template<class Type , class GType > tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 235 of file fvmLaplacian.C.
References gamma, and laplacian().
laplacian() [12/16]
template<class Type , class GType > tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 252 of file fvmLaplacian.C.
References PtrList< T >::clear(), and laplacian().
laplacian() [13/16]
template<class Type , class GType > tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 268 of file fvmLaplacian.C.
References gamma, Foam::name(), and laplacianScheme< Type, GType >::New().
laplacian() [14/16]
template<class Type , class GType > tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 285 of file fvmLaplacian.C.
References PtrList< T >::clear(), laplacian(), and Foam::name().
laplacian() [15/16]
template<class Type , class GType > tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 300 of file fvmLaplacian.C.
References gamma, and laplacian().
laplacian() [16/16]
template<class Type , class GType > tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > & tGamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 317 of file fvmLaplacian.C.
References PtrList< T >::clear(), and laplacian().
Su() [1/5]
template<class Type > zeroField Su (const Foam::zero , const GeometricField< Type, fvPatchField, volMesh > &)
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::epsilonSource(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::epsilonSource(), mixtureKEpsilon< BasicTurbulenceModel >::kSource(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::kSource(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), dummy::R(), and turbulentBreakUp::R().
Su() [2/5]
template<class Type > tmp< fvMatrix< Type > > Su (const dimensioned< Type > & su, const GeometricField< Type, fvPatchField, volMesh > &)
Su() [3/5]
template<class Type > tmp< fvMatrix< Type > > Su (const DimensionedField< Type, volMesh > & su, const GeometricField< Type, fvPatchField, volMesh > &)
Su() [4/5]
template<class Type > tmp< fvMatrix< Type > > Su (const tmp< DimensionedField< Type, volMesh > > & , const GeometricField< Type, fvPatchField, volMesh > &)
Su() [5/5]
template<class Type > tmp< fvMatrix< Type > > Su (const tmp< GeometricField< Type, fvPatchField, volMesh > > & , const GeometricField< Type, fvPatchField, volMesh > &)
Sp() [1/5]
template<class Type > zeroField Sp (const Foam::zero , const GeometricField< Type, fvPatchField, volMesh > &)
Referenced by solver::addOptimisationTypeSource(), PhaseLimitStabilization< Type >::addSup(), atmPlantCanopyUSource::addSup(), acousticDampingSource::addSup(), multiphaseMangrovesTurbulenceModel::addSup(), atmPlantCanopyUSource::addSup(), acousticDampingSource::addSup(), multiphaseMangrovesSource::addSup(), interRegionHeatTransferModel::addSup(), multiphaseMangrovesTurbulenceModel::addSup(), atmPlantCanopyUSource::addSup(), acousticDampingSource::addSup(), multiphaseMangrovesSource::addSup(), P1::calculate(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), adjointkOmegaSST::correct(), adjointSpalartAllmaras::correct(), kineticTheoryModel::correct(), IATE::correct(), radiativeIntensityRay::correct(), kkLOmega::correct(), LamBremhorstKE::correct(), LienCubicKE::correct(), LienLeschziner::correct(), qZeta::correct(), ShihQuadraticKE::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), SpalartAllmarasBase< BasicEddyViscosityModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), EBRSM< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::correct(), thixotropicViscosity::correct(), advectionDiffusion::correct(), waxSolventEvaporation::correctModel(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), continuousGasKEpsilon< BasicTurbulenceModel >::epsilonSource(), LaheyKEpsilon< BasicTurbulenceModel >::epsilonSource(), energyTransport::execute(), boundedDdtScheme< Type >::fvmDdt(), boundedDdtScheme< Type >::fvmDdt(), boundedConvectionScheme< Type >::fvmDiv(), OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), MassTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), continuousGasKEqn< BasicTurbulenceModel >::kSource(), NicenoKEqn< BasicTurbulenceModel >::kSource(), continuousGasKEpsilon< BasicTurbulenceModel >::kSource(), LaheyKEpsilon< BasicTurbulenceModel >::kSource(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::massTransfer(), PhaseTransferPhaseSystem< BasePhaseSystem >::massTransfer(), PopulationBalancePhaseSystem< BasePhaseSystem >::massTransfer(), MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransfer(), MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransferf(), thermoSingleLayer::q(), randomCoalescence::R(), wallBoiling::R(), singleStepCombustion< ReactionThermo, ThermoType >::R(), radiationModel::Sh(), populationBalanceModel::solve(), multiphaseSystem::solveAlphas(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi(), radiationModel::ST(), radiationModel::ST(), radiationModel::ST(), laminar::Su(), ReactingCloud< CloudType >::SYi(), MovingPhaseModel< BasePhaseModel >::UfEqn(), and MassTransferPhaseSystem< BasePhaseSystem >::volTransfer().
Sp() [2/5]
template<class Type > tmp< fvMatrix< Type > > Sp (const dimensionedScalar & sp, const GeometricField< Type, fvPatchField, volMesh > &)
Sp() [3/5]
template<class Type > tmp< fvMatrix< Type > > Sp (const DimensionedField< scalar, volMesh > & sp, const GeometricField< Type, fvPatchField, volMesh > &)
Sp() [4/5]
template<class Type > tmp< fvMatrix< Type > > Sp (const tmp< DimensionedField< scalar, volMesh > > & , const GeometricField< Type, fvPatchField, volMesh > &)
Sp() [5/5]
template<class Type > tmp< fvMatrix< Type > > Sp (const tmp< volScalarField > & , const GeometricField< Type, fvPatchField, volMesh > &)
SuSp() [1/5]
template<class Type > zeroField SuSp (const Foam::zero , const GeometricField< Type, fvPatchField, volMesh > &)
Referenced by SemiImplicitSource< Type >::addSup(), multiphaseStabilizedTurbulence::addSup(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), kL< BasicTurbulenceModel >::correct(), adjointkOmegaSST::correct(), adjointSpalartAllmaras::correct(), kineticTheoryModel::correct(), IATE::correct(), kkLOmega::correct(), qZeta::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), thixotropicViscosity::correct(), relaxation::correct(), buoyantKEpsilon< BasicTurbulenceModel >::epsilonSource(), buoyantKEpsilon< BasicTurbulenceModel >::kSource(), phaseChange::R(), wakeEntrainmentCoalescence::R(), adjointEikonalSolver::solve(), populationBalanceModel::solve(), MovingPhaseModel< BasePhaseModel >::UEqn(), MovingPhaseModel< BasePhaseModel >::UfEqn(), and adjointkOmegaSST::waEqnSourceFromCDkOmega().
SuSp() [2/5]
template<class Type > tmp< fvMatrix< Type > > SuSp (const dimensionedScalar & susp, const GeometricField< Type, fvPatchField, volMesh > &)
SuSp() [3/5]
template<class Type > tmp< fvMatrix< Type > > SuSp (const DimensionedField< scalar, volMesh > & susp, const GeometricField< Type, fvPatchField, volMesh > &)
SuSp() [4/5]
template<class Type > tmp< fvMatrix< Type > > SuSp (const tmp< DimensionedField< scalar, volMesh > > & , const GeometricField< Type, fvPatchField, volMesh > &)
SuSp() [5/5]
template<class Type > tmp< fvMatrix< Type > > SuSp (const tmp< volScalarField > & , const GeometricField< Type, fvPatchField, volMesh > &)