OpenFOAM: stdFoam Namespace Reference
stdFoam Namespace Reference
Classes
class span
Functions
template<class C >
constexpr auto begin (C &c) -> decltype(c.begin())
template<class C >
constexpr auto begin (const C &c) -> decltype(c.begin())
template<class C >
constexpr auto cbegin (const C &c) -> decltype(c.begin())
template<class C >
constexpr auto end (C &c) -> decltype(c.end())
template<class C >
constexpr auto end (const C &c) -> decltype(c.end())
template<class C >
constexpr auto cend (const C &c) -> decltype(c.end())
template<class C >
constexpr auto rbegin (C &c) -> decltype(c.rbegin())
template<class C >
constexpr auto rbegin (const C &c) -> decltype(c.rbegin())
template<class C >
constexpr auto crbegin (const C &c) -> decltype(c.rbegin())
template<class C >
constexpr auto rend (C &c) -> decltype(c.rend())
template<class C >
constexpr auto rend (const C &c) -> decltype(c.rend())
template<class C >
constexpr auto crend (const C &c) -> decltype(c.rend())
template<class T >
constexpr const T & min (const T &a, const T &b)
template<class T >
constexpr const T & max (const T &a, const T &b)
Function Documentation
begin() [1/2]
template<class C > constexpr auto begin (C & c) -> decltype(c.begin()) constexpr
Definition at line 161 of file stdFoam.H.
References UPtrList< T >::begin().
begin() [2/2]
template<class C > constexpr auto begin (const C & c) -> decltype(c.begin()) constexpr
Definition at line 172 of file stdFoam.H.
References UPtrList< T >::begin().
cbegin()
template<class C > constexpr auto cbegin (const C & c) -> decltype(c.begin()) constexpr
Definition at line 183 of file stdFoam.H.
References UPtrList< T >::begin().
end() [1/2]
template<class C > constexpr auto end (C & c) -> decltype(c.end()) constexpr
Definition at line 194 of file stdFoam.H.
References UPtrList< T >::end().
end() [2/2]
template<class C > constexpr auto end (const C & c) -> decltype(c.end()) constexpr
Definition at line 205 of file stdFoam.H.
References UPtrList< T >::end().
cend()
template<class C > constexpr auto cend (const C & c) -> decltype(c.end()) constexpr
Definition at line 216 of file stdFoam.H.
References UPtrList< T >::end().
rbegin() [1/2]
template<class C > constexpr auto rbegin (C & c) -> decltype(c.rbegin()) constexpr
Definition at line 230 of file stdFoam.H.
rbegin() [2/2]
template<class C > constexpr auto rbegin (const C & c) -> decltype(c.rbegin()) constexpr
Definition at line 241 of file stdFoam.H.
crbegin()
template<class C > constexpr auto crbegin (const C & c) -> decltype(c.rbegin()) constexpr
Definition at line 252 of file stdFoam.H.
rend() [1/2]
template<class C > constexpr auto rend (C & c) -> decltype(c.rend()) constexpr
Definition at line 263 of file stdFoam.H.
rend() [2/2]
template<class C > constexpr auto rend (const C & c) -> decltype(c.rend()) constexpr
Definition at line 274 of file stdFoam.H.
crend()
template<class C > constexpr auto crend (const C & c) -> decltype(c.rend()) constexpr
Definition at line 285 of file stdFoam.H.
min()
template<class T > constexpr const T & min (const T & a, const T & b) inline constexpr
Definition at line 296 of file stdFoam.H.
References b.
max()
template<class T > constexpr const T & max (const T & a, const T & b) inline constexpr
Definition at line 307 of file stdFoam.H.
References b.