OpenFOAM: Foam::ensightOutput::Detail Namespace Reference
Foam::ensightOutput::Detail Namespace Reference
Functions
labelList getFaceSizes (const UList< face > &faces)
labelList getFaceSizes (const UIndirectList< face > &faces)
labelList getPolysNFaces (const polyMesh &mesh, const labelUList &addr)
labelList getPolysNPointsPerFace (const polyMesh &mesh, const labelUList &addr)
CompactListList< label > getPolysFacePoints (const polyMesh &mesh, const labelUList &addr, const labelList &pointMap)
void writeLabelListList (ensightGeoFile &os, const labelUList &offsets, const labelUList &values, const label pointOffset)
template<class LabelListListType >
void writeLabelListList (ensightGeoFile &os, const LabelListListType &listOfLists, const label pointOffset)
template<template< typename > class FieldContainer, class Type >
void copyComponent (const FieldContainer< Type > &input, const direction cmpt, UList< float > &cmptBuffer)
template<template< typename > class FieldContainer>
bool writeCoordinates (ensightGeoFile &os, const label partId, const word &partName, const label nPoints, const FieldContainer< Foam::point > &fld, bool parallel)
template<template< typename > class FieldContainer, class Type >
void writeFieldComponents (ensightOutput::floatBufferType &scratch, ensightFile &os, const char *key, const FieldContainer< Type > &fld, bool parallel)
template<template< typename > class FieldContainer, class Type >
void writeFieldComponents (ensightFile &os, const char *key, const FieldContainer< Type > &fld, bool parallel)
template<class Type >
bool writeFaceSubField (ensightOutput::floatBufferType &scratch, ensightFile &os, const Field< Type > &fld, const ensightFaces &part, bool parallel)
template<class Type >
bool writeFaceSubField (ensightFile &os, const Field< Type > &fld, const ensightFaces &part, bool parallel)
template<class Type >
bool writeFaceLocalField (ensightOutput::floatBufferType &scratch, ensightFile &os, const Field< Type > &fld, const ensightFaces &part, bool parallel)
template<class Type >
bool writeFaceLocalField (ensightFile &os, const Field< Type > &fld, const ensightFaces &part, bool parallel)
template<class Type >
label writeCloudFieldContent (ensightFile &os, const UList< Type > &fld, label count=0)
Function Documentation
getFaceSizes() [1/2]
Foam::labelList getFaceSizes (const UList< face > & faces)
Definition at line 50 of file ensightOutput.C.
References UList< T >::begin(), f(), and UPtrList< T >::size().
getFaceSizes() [2/2]
Foam::labelList getFaceSizes (const UIndirectList< face > & faces)
Definition at line 69 of file ensightOutput.C.
References UList< T >::begin(), f(), and UPtrList< T >::size().
getPolysNFaces()
Foam::labelList getPolysNFaces (const polyMesh & mesh, const labelUList & addr)
const cellList& meshCells = mesh.cells();
Definition at line 88 of file ensightOutput.C.
References UList< T >::begin(), cellId, mesh, UPtrList< T >::size(), and UList< T >::size().
getPolysNPointsPerFace()
Foam::labelList getPolysNPointsPerFace (const polyMesh & mesh, const labelUList & addr)
const cellList& meshCells = mesh.cells();
Definition at line 112 of file ensightOutput.C.
References UList< T >::begin(), cellId, mesh, and UList< T >::size().
getPolysFacePoints()
Foam::CompactListList< Foam::label > getPolysFacePoints (const polyMesh & mesh, const labelUList & addr, const labelList & pointMap)
const cellList& meshCells = mesh.cells();
Parameters
addr Cell ids to write
pointMap Point map to use
Definition at line 220 of file ensightOutput.C.
References cellId, f(), faceId(), mesh, nPoints, UPtrList< T >::size(), and UList< T >::size().
writeLabelListList() [1/2]
void writeLabelListList (ensightGeoFile & os, const labelUList & offsets, const labelUList & values, const label pointOffset)
Definition at line 148 of file ensightOutput.C.
References os(), and UList< T >::size().
writeLabelListList() [2/2]
template<class LabelListListType > void writeLabelListList (ensightGeoFile & os, const LabelListListType & listOfLists, const label pointOffset)
Definition at line 28 of file ensightOutputTemplates.C.
References forAll, and os().
copyComponent()
template<template< typename > class FieldContainer, class Type > void copyComponent (const FieldContainer< Type > & input, const direction cmpt, UList< float > & cmptBuffer)
Parameters
input Input field data
cmpt Component to be extracted
[out] cmptBuffer Component scratch buffer
Definition at line 49 of file ensightOutputTemplates.C.
References UPtrList< T >::begin(), Foam::component(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::narrowFloat(), Foam::nl, and UPtrList< T >::size().
Referenced by writeFieldComponents().
writeCoordinates()
template<template< typename > class FieldContainer> bool writeCoordinates (ensightGeoFile & os, const label partId, const word & partName, const label nPoints, const FieldContainer< Foam::point > & fld, bool parallel)
Parameters
os Output file (must be valid on master)
partId The ensight part id
partName The ensight part description
nPoints The total number of points
fld The point field to be written
parallel Prefer collective write?
Definition at line 251 of file ensightOutputTemplates.C.
References fld(), nPoints, and os().
Referenced by ensightOutputSurface::write(), ensightCells::write(), and ensightFaces::write().
writeFieldComponents() [1/2]
template<template< typename > class FieldContainer, class Type > void writeFieldComponents (ensightOutput::floatBufferType & scratch, ensightFile & os, const char * key, const FieldContainer< Type > & fld, bool parallel)
Parameters
scratch Component scratch buffer
os Output file (must be valid on master)
key The ensight element type (ignored if nullptr)
fld The field content to be written for this element type
parallel Prefer collective write?
Definition at line 88 of file ensightOutputTemplates.C.
References copyComponent(), Foam::ensightOutput::debug, Foam::endl(), fld(), Foam::Info, Foam::max(), Foam::min(), os(), procAddr(), and UPtrList< T >::size().
Referenced by writeFieldComponents(), ensightOutputSurface::writePointData(), and Foam::writeTrackField().
writeFieldComponents() [2/2]
template<template< typename > class FieldContainer, class Type > void writeFieldComponents (ensightFile & os, const char * key, const FieldContainer< Type > & fld, bool parallel)
Parameters
os Output file (must be valid on master)
key The ensight element type (can be nullptr)
fld The field content to be written for this element type Prefer collective write?
Definition at line 497 of file ensightOutput.H.
References fld(), os(), and writeFieldComponents().
writeFaceSubField() [1/2]
template<class Type > bool writeFaceSubField (ensightOutput::floatBufferType & scratch, ensightFile & os, const Field< Type > & fld, const ensightFaces & part, bool parallel)
Parameters
scratch Component scratch buffer
os Output file (must be valid on master)
fld The field content to be written
part The addressing (element-wise) into the field
parallel Prefer collective write?
Definition at line 291 of file ensightOutputTemplates.C.
References fld(), ensightPart::index(), os(), ensightFaces::range(), Foam::returnReduceOr(), UPtrList< T >::size(), ensightFaces::size(), and ensightFaces::total().
Referenced by writeFaceSubField().
writeFaceSubField() [2/2]
template<class Type > bool writeFaceSubField (ensightFile & os, const Field< Type > & fld, const ensightFaces & part, bool parallel)
Parameters
os Output file (must be valid on master)
fld The field content to be written
part The addressing (element-wise) into the field
parallel Prefer collective write?
Definition at line 546 of file ensightOutput.H.
References fld(), os(), and writeFaceSubField().
writeFaceLocalField() [1/2]
template<class Type > bool writeFaceLocalField (ensightOutput::floatBufferType & scratch, ensightFile & os, const Field< Type > & fld, const ensightFaces & part, bool parallel)
Parameters
scratch Component scratch buffer
os Output file (must be valid on master)
fld The field content to be written
part The addressing (element-wise) into the field
parallel Prefer collective write?
Definition at line 344 of file ensightOutputTemplates.C.
References Foam::exit(), ensightFaces::faceOrder(), Foam::FatalError, FatalErrorInFunction, fld(), ensightPart::index(), Foam::nl, os(), Foam::returnReduceOr(), UPtrList< T >::size(), ensightFaces::size(), and ensightFaces::total().
Referenced by writeFaceLocalField().
writeFaceLocalField() [2/2]
template<class Type > bool writeFaceLocalField (ensightFile & os, const Field< Type > & fld, const ensightFaces & part, bool parallel)
Parameters
os Output file (must be valid on master)
fld The field content to be written
part The addressing (element-wise) into the field
parallel Prefer collective write?
Definition at line 594 of file ensightOutput.H.
References fld(), os(), and writeFaceLocalField().
writeCloudFieldContent()
template<class Type > label writeCloudFieldContent (ensightFile & os, const UList< Type > & fld, label count = 0)
Parameters
os Output file (must be valid on master)
count The current output count