OpenFOAM: Foam::constant::mathematical Namespace Reference
Foam::constant::mathematical Namespace Reference
Mathematical constants.
Functions
constexpr scalar e (M_E)
constexpr scalar pi (M_PI)
constexpr scalar twoPi (2 *M_PI)
constexpr scalar piByTwo (0.5 *M_PI)
constexpr scalar Eu (0.57721566490153286060651209)
Variables
constexpr const char *const group = "mathematical"
Detailed Description
Mathematical constants.
Function Documentation
e()
constexpr scalar e (M_E) constexpr
pi()
constexpr scalar pi (M_PI) constexpr
References pi().
Referenced by Foam::adjustHue(), Foam::angleDiff(), KinematicParcel< ParcelType >::areaS(), ReactingHeterogeneousParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), ReactingParcel< ParcelType >::calc(), targetCoeffTrim::calcCoeffs(), BrownianMotionForce< CloudType >::calcCoupled(), rotorDiskSource::calculate(), LiquidEvaporation< CloudType >::calculate(), LiquidEvaporationBoil< CloudType >::calculate(), LiquidEvapFuchsKnudsen< CloudType >::calculate(), COxidationDiffusionLimitedRate< CloudType >::calculate(), COxidationHurtMitchell< CloudType >::calculate(), COxidationIntrinsicRate< CloudType >::calculate(), COxidationKineticDiffusionLimitedRate< CloudType >::calculate(), COxidationMurphyShaddix< CloudType >::calculate(), MUCSheterogeneousRate< CloudType >::calculate(), LegendreMagnaudet::Cl(), extractEulerianParticles::collectParticle(), ORourkeCollision< CloudType >::collide(), ORourkeCollision< CloudType >::collideParcels(), diffusionMulticomponent< ReactionThermo, ThermoType >::correct(), kineticTheoryModel::correct(), radiativeIntensityRay::correct(), drippingInjection::correct(), rotorDiskSource::createCoordinateSystem(), thermoCoupleProbes::derivatives(), Foam::Elliptic::ellipticIntegralsKE(), Curle::execute(), setFlow::execute(), FieldActivatedInjection< CloudType >::FieldActivatedInjection(), cosine::fLiquid(), multiphaseMangrovesSource::inertiaCoeff(), FreeStream< CloudType >::inflow(), movingConeTopoFvMesh::init(), InjectedParticleDistributionInjection< CloudType >::initialise(), InjectedParticleInjection< CloudType >::initialise(), Foam::colourTools::interpolateDiverging(), Foam::Elliptic::JacobiAmp(), Gidaspow::kappa(), HrenyaSinclair::kappa(), Syamlal::kappa(), kineticGasEvaporation< Thermo, OtherThermo >::Kexp(), cosine::limiter(), ManualInjection< CloudType >::ManualInjection(), DSMCCloud< ParcelType >::maxwellianAverageSpeed(), DSMCCloud< ParcelType >::maxwellianAverageSpeed(), normal::meanValue(), Gidaspow::nu(), HrenyaSinclair::nu(), Syamlal::nu(), equilibrium::oneByTau(), isotropic::oneByTau(), nonEquilibrium::oneByTau(), cloudInfo::performAction(), IATEsource::phi(), pi(), InjectionModel< Foam::KinematicCloud< Foam::DSMCCloud > >::postInjectCheck(), rigidBodyMeshMotion::rigidBodyMeshMotion(), acousticDampingSource::setBlendingFactor(), SurfaceFilmModel< CloudType >::setParcelProperties(), ConeNozzleInjection< CloudType >::setProperties(), DSMCParcel< ParcelType >::constantProperties::sigmaT(), LarsenBorgnakkeVariableHardSphere< CloudType >::sigmaTcR(), VariableHardSphere< CloudType >::sigmaTcR(), sixDoFRigidBodyMotionSolver::sixDoFRigidBodyMotionSolver(), KinematicSurfaceFilm< CloudType >::splashInteraction(), DESModel< BasicTurbulenceModel >::Ssigma(), SDA::transformation(), controlPointsDefinition::transformControlPoints(), movingConeTopoFvMesh::update(), ReitzKHRT< CloudType >::update(), SHF< CloudType >::update(), BlobsSheetAtomization< CloudType >::update(), LISAAtomization< CloudType >::update(), fanPressureFvPatchScalarField::updateCoeffs(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), JohnsonJacksonParticleSlipFvPatchVectorField::updateCoeffs(), JohnsonJacksonParticleThetaFvPatchScalarField::updateCoeffs(), greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), waveMakerPointPatchVectorField::updateCoeffs(), CellZoneInjection< CloudType >::updateMesh(), halfCosineRamp::value(), quarterCosineRamp::value(), quarterSineRamp::value(), sinImplicitFunction::value(), eddy::volume(), KinematicParcel< ParcelType >::volume(), irregularMultiDirectional::waveLength(), StokesI::waveLength(), waveMakerPointPatchVectorField::waveMakerPointPatchVectorField(), regularWaveModel::waveType(), regionSizeDistribution::write(), eulerianParticle::write(), eulerianParticle::writeDict(), eddy::writeSurfaceOBJ(), and PengRobinsonGas< Specie >::Z().
twoPi()
constexpr scalar twoPi (2 * M_PI) constexpr
Referenced by Foam::angleDiff(), rotorDiskSource::calculate(), LarsenBorgnakkeVariableHardSphere< CloudType >::collide(), VariableHardSphere< CloudType >::collide(), Hanning::Hanning(), Kmesh::Kmesh(), energySpectrum::read(), propellerInfo::setCoordinateSystem(), cnoidal::setLevel(), irregularMultiDirectional::setLevel(), StokesI::setLevel(), StokesII::setLevel(), StokesV::setLevel(), streamFunction::setLevel(), ConeNozzleInjection< CloudType >::setPositionAndCell(), ConeInjection< CloudType >::setProperties(), propellerInfo::setRotationalSpeed(), propellerInfo::setSampleDiskGeometry(), cnoidal::setVelocity(), StokesI::setVelocity(), StokesV::setVelocity(), streamFunction::setVelocity(), KinematicSurfaceFilm< CloudType >::splashDirection(), SDA::transformation(), turbGen::U(), irregularMultiDirectional::Uf(), dynamicInkJetFvMesh::update(), StochasticDispersionRAS< CloudType >::update(), ETAB< CloudType >::update(), ReitzKHRT< CloudType >::update(), SHF< CloudType >::update(), TAB< CloudType >::update(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), waveMakerPointPatchVectorField::updateCoeffs(), waveMakerPointPatchVectorField::waveLength(), propellerInfo::writePropellerPerformance(), and eddy::writeSurfaceOBJ().
piByTwo()
constexpr scalar piByTwo (0.5 * M_PI) constexpr
Referenced by sine::limiter(), Foam::pseudoAngle(), SDA::transformation(), and KinematicSurfaceFilm< CloudType >::wetSplashInteraction().
Eu()
constexpr scalar Eu (0. 57721566490153286060651209) constexpr
Referenced by Foam::Math::invIncGamma().
Variable Documentation
group
constexpr const char* const group = "mathematical" constexpr
Definition at line 46 of file mathematicalConstants.H.
Referenced by alphatWallBoilingWallFunctionFvPatchScalarField::activePhasePair(), alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField(), and alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs().