OpenFOAM: Foam::functionObjects Namespace Reference
Foam::functionObjects Namespace Reference
Function objects are OpenFOAM utilities to ease workflow configurations and enhance workflows by producing additional user-requested data both during runtime and postprocessing calculations, typically in the form of additional logging to the screen, or generating text, image and field files.
Namespaces
namespace fieldValues
namespace runTimeControls
Classes
class abort
Watches for presence of the named trigger file in the case directory and signals a simulation stop (or other) event if found.
class add
Sums a given list of (at least two or more) fields and outputs the result into a new field, where the fields possess the same sizes and dimensions:
class age
Calculates and writes out the time taken for a particle to travel from an inlet to the location. Solves the following equation when incompressible:
class AMIWeights
Computes the min/max/average weights of arbitrary mesh interface (AMI) patches, and optionally reports to a text file or writes VTK surfaces of the sum of the weights and mask fields for arbitrarily coupled mesh interface (ACMI) patches.
class BilgerMixtureFraction
Calculates the Bilger mixture-fraction field (i.e.) based on the elemental composition of the mixture. Elements C, H, S and O are considered.
class binField
Calculates binned data, where specified patches are divided into segments according to various input bin characteristics, so that spatially-localised information can be output for each segment.
class blendingFactor
Computes blending factor as an indicator about which of the schemes is active across the domain.
class cloudInfo
Outputs Lagrangian cloud information to a file.
class codedFunctionObject
Provides a general interface to enable dynamic code compilation.
class columnAverage
Computes the arithmetic average of given quantities along columns of cells in a given direction for structured-like layered meshes. It is, for example, useful for channel-like cases where spanwise average of a field is desired. However, the columnAverage function object does not operate on arbitrary unstructured meshes.
class comfort
Calculates the thermal comfort quantities predicted mean vote (PMV), predicted percentage of dissatisfaction (PPD) and the draught rate (DR) based on DIN ISO EN 7730:2005.
class components
Extracts the components of elements of a field and outputs the result into new fields, where the fields possess the same sizes and dimensions.
class continuityError
Computes local, global and cumulative continuity errors for a flux field.
class CourantNo
Computes the Courant number field for time-variant simulations.
class Curle
Computes the acoustic pressure based on Curle's analogy.
class dataCloud
This functionObject writes a cloud position and in ASCII.
class ddt
Computes the Eulerian time derivative of an input volume field for time-variant simulations (not appropriate to steady-state simulations).
class ddt2
Computes the magnitude or magnitude squared of the Eulerian time derivative of an input volume field for time-variant simulations (not appropriate to steady-state simulations).
class derivedFields
Computes two predefined derived fields, i.e. rhoU, and pTotal, where the defined fields are hard-coded as follows:
class DESModelRegions
Computes an indicator field for detached eddy simulation (DES) turbulence calculations, where the values of the indicator mean:
class div
Computes the divergence of an input field.
class DMD
Computes a dynamic mode decomposition model on a specified field.
class dsmcFields
This function object calculates and outputs the intensive fields:
class electricPotential
Computes the steady-state equation of charge conservation to obtain the electric potential by strictly assuming a quasi-static electrostatic field for single-phase and multiphase applications.
class energySpectrum
Calculates the energy spectrum for a structured IJK mesh.
class energyTransport
Evolves a simplified energy transport equation for incompressible flows. It takes into account the inertia, conduction and convection terms plus a source.
class ensightWrite
Writes fields in ensight format.
class enstrophy
Computes the enstrophy of an input volVectorField.
class eulerianParticle
class externalCoupled
Provides a simple file-based communication interface for explicit coupling with an external application, so that data is transferred to- and from OpenFOAM. The data exchange employs specialised boundary conditions to provide either one-way or two-way coupling models.
class extractEulerianParticles
Generates particle size information from Eulerian calculations, e.g. VoF.
class fieldAverage
Computes ensemble- and/or time-based field averages, with optional windowing, for a user-specified selection of volumetric and/or surface fields.
class fieldAverageItem
Helper class to describe what form of averaging to apply. A set will be applied to each base field in Foam::fieldAverage, of the following form.
class fieldExpression
Intermediate class for handling field expression function objects (e.g. blendingFactor etc.) whereinto a single field is input.
class fieldExtents
Computes the spatial minimum and maximum extents of an input field.
class fieldInfo
Helper class to store a wordRe and label used by Foam::functionObjects::fieldSelection.
class fieldMinMax
Computes the values and locations of field minima and maxima. These are good indicators of calculation performance, e.g. to confirm that predicted results are within expected bounds, or how well a case is converging.
class fieldSelection
Helper class to manage field selections.
class fieldsExpression
Intermediate class for handling field expression function objects (e.g. add, subtract etc.) whereinto more than one fields are input.
class fieldValue
Intermediate class for handling field value-based function objects.
class fileFieldSelection
Helper class to manage file-based field selections.
class filmFlux
Calculates the mass flux for surface film models.
class flowType
Computes the flow type indicator of an input velocity field.
class flux
Computes the flux of an input vector field.
class fluxSummary
Computes the volumetric- or mass-flux information across selections of face zones.
class forceCoeffs
Computes force and moment coefficients over a given list of patches, and optionally over given porous zones. The following coefficients can be selected and output:
class forces
Computes forces and moments over a given list of patches by integrating pressure and viscous forces and moments, and optionally resistance forces and moments from porous zones.
class fvExpressionField
Function object that generates or modifies a field based on expressions.
class fvMeshFunctionObject
Specialization of Foam::functionObject for an Foam::fvMesh, providing a reference to the Foam::fvMesh.
class grad
Computes the gradient of an input field.
class heatTransferCoeff
Computes the heat transfer coefficient [W/(m^2 K)] as a volScalarField for a given set of patches.
class histogram
Computes the volume-weighted histogram of an input volScalarField.
class hydrostaticPressure
Calculates and outputs the pressure fields p_rgh and ph_rgh.
class icoUncoupledKinematicCloud
This functionObject tracks a uncoupled kinematic particle cloud in the specified velocity field of an incompressible flow (laminar, RANS or LES).
class interfaceHeight
This function object reports the height of the interface above a set of locations.
class Lambda2
Computes the second largest eigenvalue of the sum of the square of the symmetrical and anti-symmetrical parts of the velocity gradient tensor.
class LambVector
Computes Lamb vector, i.e. the cross product of vorticity and velocity. Calculation of the divergence of the Lamb vector can be performed by using div function object on this LambVector function object.
class limitFields
Limits input fields to user-specified min and max bounds.
class log
Computes the natural logarithm of an input volScalarField.
class logFiles
functionObject base class for creating, maintaining and writing log files e.g. integrated or averaged field data vs time.
class MachNo
Computes the Mach number as a volScalarField.
class mag
Computes the magnitude of an input field.
class magSqr
Computes the magnitude of the square of an input field.
class mapFields
Maps input fields from local mesh to secondary mesh at runtime.
class momentum
Computes linear/angular momentum, reporting integral values and optionally writing the fields.
class momentumError
Computes balance terms for the steady momentum equation.
class multiphaseInterHtcModel
A heat transfer coefficient for multiphase inter solvers (e.g. icoReactingMultiphaseFoam).
class multiply
Multiplies a given list of (at least two or more) fields and outputs the result into a new field.
class multiRegion
Wrapper that clones the supplied function object for each region.
class nearWallFields
Samples near-patch volume fields within an input distance range.
class norm
Normalises an input field with a chosen norm, and outputs a new normalised field.
class ObukhovLength
Computes the Obukhov length field and associated friction velocity field.
class parProfiling
Simple (simplistic) mpi-profiling.
class particleDistribution
Generates a particle distribution for lagrangian data at a given time.
class PecletNo
Computes the Peclet number as a surfaceScalarField.
class phaseForces
This function object calculates and outputs the blended interfacial forces acting on a given phase, i.e. drag, virtual mass, lift, wall-lubrication and turbulent dispersion. Note that it works only in run-time processing mode and in combination with the reactingEulerFoam solvers.
class pow
Computes the power of an input volScalarField.
class pressure
Provides several methods to convert an input pressure field into derived forms, including:
class processorField
Writes a scalar field whose value is the local processor ID. The output field name is processorID.
class propellerInfo
Calculates propeller performance and wake field properties.
class properties
Storage for function object properties, derived from IOdictionary. Provides functionality to read/write state information (data required for smooth restart behaviour) and results to/from the state dictionary.
class proudmanAcousticPower
Computes the acoustic power due to the volume of isotropic turbulence using Proudman's formula.
class Q
Computes the second invariant of the velocity gradient tensor .
class randomise
Adds a random component to an input field, with a specified perturbation magnitude.
class reactingEulerHtcModel
A heat transfer coefficient for reactingEuler solvers.
class reactionsSensitivityAnalysis
Computes indicators for reaction rates of creation or destruction of species in each reaction.
class readFields
Reads fields from the time directories and adds them to the mesh database for further post-processing.
class reference
Computes a field whose values are offset to a reference value obtained by from a Function1.
class regionFunctionObject
Specialization of Foam::functionObject for a region and providing a reference to the region Foam::objectRegistry.
class regionSizeDistribution
Creates a droplet size distribution via interrogating a continuous phase fraction field.
class removeRegisteredObject
Removes registered objects if present in the database.
class resolutionIndex
Computes a single-mesh resolution index according to the specified model, which is used as a LES/DES quality/post-verification metric that does not require any experimental or DNS data.
class scalarTransport
Evolves a passive scalar transport equation.
class setFlow
Provides options to set the velocity and flux fields as a function of time.
class setTimeStepFaRegionsFunctionObject
This function object controls the time step for classes of the type regionFaModel. It reads regionFaMaxCo entry from controlDict and evaluate the time step based on the finite area Courant Number.
class setTimeStepFunctionObject
This function object overrides the calculation time step.
class sixDoFRigidBodyState
Writes the 6-DoF motion state.
class sizeDistribution
This function object calculates and outputs information about the size distribution of the dispersed phase, such as the number density function or its moments. It is designed to be used exclusively with the population balance modeling functionality of the reactingEulerFoam solvers. It can be applied to a specific cellZone or the entire domain.
class solverFieldSelection
class solverInfo
Writes solver information for a list of user-specified fields.
class specieReactionRates
Writes the domain averaged reaction rates for each specie for each reaction into the file <timeDir>/specieReactionRates.dat.
class stabilityBlendingFactor
Computes the stabilityBlendingFactor to be used by the local blended convection scheme. The output is a surface field weight between 0-1.
class stateFunctionObject
Base class for function objects, adding functionality to read/write state information (data required for smooth restart behaviour) and results to/from the state dictionary.
class streamFunction
Computes the stream function (i.e. https://w.wiki/Ncm).
class streamLine
Generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field.
class streamLineBase
class subtract
Subtracts a given list of (at least one or more) fields from a field and produces a new field, where the fields possess the same sizes and dimensions.
class sumParticleOp
class surfaceDistance
Computes the distance to the nearest surface from a given geometry.
class surfaceInterpolate
Linearly interpolates volume fields to generate surface fields.
class syncObjects
Copies content of local objectRegistry to all processors.
class systemCall
Executes system calls, entered in the form of string lists.
class thermoCoupleProbes
Sample probe for temperature using a thermocouple.
class timeActivatedFileUpdate
Performs a file copy/replacement once a specified time has been reached.
class timeControl
Wrapper around functionObjects to add time control.
class timeFunctionObject
Virtual base class for function objects with a reference to Time.
class timeInfo
Writes the run time (time-step), cpuTime and clockTime - optionally with cpuTime and clockTime change for each time step.
class turbulenceFields
Computes various turbulence-related quantities that are not typically output during calculations, and stores/writes them on the mesh database for further manipulation.
class valueAverage
Computes the ensemble- or time-based singular-value average values, with optional windowing, from the output of function objects that generate non-field type values (e.g. Cd of forceCoeffs or momentum_x in momentum function objects).
class valueAverageBase
Base class that computes the ensemble- or time-based singular-value average values, with optional windowing, from the output of function objects that generate non-field type values, e.g. Cd of forceCoeffs or momentum_x in momentum function objects.
class volFieldSelection
Helper class to manage solver field selections.
class volRegion
Volume (cell) region selection class.
class vorticity
Computes the vorticity, the curl of the velocity.
class vtkCloud
This functionObject writes cloud(s) in VTK PolyData format (.vtp extension) with the time information saved in a '.series' file.
class vtkWrite
Writes fields in VTK (xml or legacy) format. Writes cell-values or point-interpolated values for volFields.
class wallBoundedStreamLine
Generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field, constrained to a patch.
class wallHeatFlux
Computes the wall-heat flux at selected wall patches.
class wallShearStress
Computes the wall-shear stress at selected wall patches.
class writeCellCentres
Writes the cell-centres volVectorField and the three component fields as volScalarFields.
class writeCellVolumes
Writes the cell-volumes volScalarField.
class writeDictionary
Reports dictionary contents on change.
class writeFile
Base class for writing single files from the function objects.
class writeObjects
Allows specification of different writing frequency of objects registered to the database.
class XiReactionRate
Writes the turbulent flame-speed and reaction-rate volScalarFields for the Xi-based combustion models.
class yPlus
Computes the near wall for turbulence models.
class zeroGradient
Creates a volume field with zero-gradient boundary conditions from another volume field.
Functions
defineTypeNameAndDebug (ObukhovLength, 0)
addToRunTimeSelectionTable (functionObject, ObukhovLength, dictionary)
Istream & operator>> (Istream &, fieldInfo &)
Ostream & operator<< (Ostream &, const fieldInfo &)
defineTypeNameAndDebug (fvMeshFunctionObject, 0)
defineTypeNameAndDebug (volRegion, 0)
defineTypeNameAndDebug (add, 0)
addToRunTimeSelectionTable (functionObject, add, dictionary)
defineTypeNameAndDebug (age, 0)
addToRunTimeSelectionTable (functionObject, age, dictionary)
defineTypeNameAndDebug (AMIWeights, 0)
addToRunTimeSelectionTable (functionObject, AMIWeights, dictionary)
defineTypeNameAndDebug (binField, 0)
addToRunTimeSelectionTable (functionObject, binField, dictionary)
defineTypeNameAndDebug (blendingFactor, 0)
addToRunTimeSelectionTable (functionObject, blendingFactor, dictionary)
defineTypeNameAndDebug (columnAverage, 0)
addToRunTimeSelectionTable (functionObject, columnAverage, dictionary)
defineTypeNameAndDebug (comfort, 0)
addToRunTimeSelectionTable (functionObject, comfort, dictionary)
defineTypeNameAndDebug (components, 0)
addToRunTimeSelectionTable (functionObject, components, dictionary)
defineTypeNameAndDebug (continuityError, 0)
addToRunTimeSelectionTable (functionObject, continuityError, dictionary)
defineTypeNameAndDebug (CourantNo, 0)
addToRunTimeSelectionTable (functionObject, CourantNo, dictionary)
defineTypeNameAndDebug (Curle, 0)
addToRunTimeSelectionTable (functionObject, Curle, dictionary)
defineTypeNameAndDebug (ddt, 0)
addToRunTimeSelectionTable (functionObject, ddt, dictionary)
defineTypeNameAndDebug (ddt2, 0)
addToRunTimeSelectionTable (functionObject, ddt2, dictionary)
defineTypeNameAndDebug (derivedFields, 0)
addToRunTimeSelectionTable (functionObject, derivedFields, dictionary)
defineTypeNameAndDebug (DESModelRegions, 0)
addToRunTimeSelectionTable (functionObject, DESModelRegions, dictionary)
defineTypeNameAndDebug (div, 0)
addToRunTimeSelectionTable (functionObject, div, dictionary)
defineTypeNameAndDebug (DMD, 0)
addToRunTimeSelectionTable (functionObject, DMD, dictionary)
defineTypeNameAndDebug (enstrophy, 0)
addToRunTimeSelectionTable (functionObject, enstrophy, dictionary)
defineTypeNameAndDebug (fvExpressionField, 0)
addToRunTimeSelectionTable (functionObject, fvExpressionField, dictionary)
defineTypeNameAndDebug (externalCoupled, 0)
addToRunTimeSelectionTable (functionObject, externalCoupled, dictionary)
defineTypeNameAndDebug (extractEulerianParticles, 0)
addToRunTimeSelectionTable (functionObject, extractEulerianParticles, dictionary)
defineTypeNameAndDebug (fieldAverage, 0)
addToRunTimeSelectionTable (functionObject, fieldAverage, dictionary)
Istream & operator>> (Istream &, fieldAverageItem &)
Ostream & operator<< (Ostream &, const fieldAverageItem &)
defineTypeNameAndDebug (fieldCoordinateSystemTransform, 0)
addToRunTimeSelectionTable (functionObject, fieldCoordinateSystemTransform, dictionary)
defineTypeNameAndDebug (fieldExpression, 0)
defineTypeNameAndDebug (fieldExtents, 0)
addToRunTimeSelectionTable (functionObject, fieldExtents, dictionary)
defineTypeNameAndDebug (fieldMinMax, 0)
addToRunTimeSelectionTable (functionObject, fieldMinMax, dictionary)
defineTypeNameAndDebug (fieldsExpression, 0)
defineTypeNameAndDebug (fieldValue, 0)
defineRunTimeSelectionTable (fieldValue, runTime)
defineTypeNameAndDebug (flowType, 0)
addToRunTimeSelectionTable (functionObject, flowType, dictionary)
defineTypeNameAndDebug (flux, 0)
addToRunTimeSelectionTable (functionObject, flux, dictionary)
defineTypeNameAndDebug (fluxSummary, 0)
addToRunTimeSelectionTable (functionObject, fluxSummary, dictionary)
defineTypeNameAndDebug (grad, 0)
addToRunTimeSelectionTable (functionObject, grad, dictionary)
defineTypeNameAndDebug (heatTransferCoeff, 0)
addToRunTimeSelectionTable (functionObject, heatTransferCoeff, dictionary)
defineTypeNameAndDebug (multiphaseInterHtcModel, 0)
addToRunTimeSelectionTable (functionObject, multiphaseInterHtcModel, dictionary)
defineTypeNameAndDebug (reactingEulerHtcModel, 0)
addToRunTimeSelectionTable (functionObject, reactingEulerHtcModel, dictionary)
defineTypeNameAndDebug (histogram, 0)
addToRunTimeSelectionTable (functionObject, histogram, dictionary)
defineTypeNameAndDebug (interfaceHeight, 0)
addToRunTimeSelectionTable (functionObject, interfaceHeight, dictionary)
defineTypeNameAndDebug (Lambda2, 0)
addToRunTimeSelectionTable (functionObject, Lambda2, dictionary)
defineTypeNameAndDebug (LambVector, 0)
addToRunTimeSelectionTable (functionObject, LambVector, dictionary)
defineTypeNameAndDebug (limitFields, 0)
addToRunTimeSelectionTable (functionObject, limitFields, dictionary)
defineTypeNameAndDebug (log, 0)
addToRunTimeSelectionTable (functionObject, log, dictionary)
defineTypeNameAndDebug (MachNo, 0)
addToRunTimeSelectionTable (functionObject, MachNo, dictionary)
defineTypeNameAndDebug (mag, 0)
addToRunTimeSelectionTable (functionObject, mag, dictionary)
defineTypeNameAndDebug (magSqr, 0)
addToRunTimeSelectionTable (functionObject, magSqr, dictionary)
defineTypeNameAndDebug (mapFields, 0)
addToRunTimeSelectionTable (functionObject, mapFields, dictionary)
defineTypeNameAndDebug (momentum, 0)
addToRunTimeSelectionTable (functionObject, momentum, dictionary)
defineTypeNameAndDebug (momentumError, 0)
addToRunTimeSelectionTable (functionObject, momentumError, dictionary)
defineTypeNameAndDebug (multiply, 0)
addToRunTimeSelectionTable (functionObject, multiply, dictionary)
defineTypeNameAndDebug (nearWallFields, 0)
addToRunTimeSelectionTable (functionObject, nearWallFields, dictionary)
defineTypeNameAndDebug (norm, 0)
addToRunTimeSelectionTable (functionObject, norm, dictionary)
defineTypeNameAndDebug (particleDistribution, 0)
addToRunTimeSelectionTable (functionObject, particleDistribution, dictionary)
defineTypeNameAndDebug (PecletNo, 0)
addToRunTimeSelectionTable (functionObject, PecletNo, dictionary)
defineTypeNameAndDebug (pow, 0)
addToRunTimeSelectionTable (functionObject, pow, dictionary)
defineTypeNameAndDebug (pressure, 0)
addToRunTimeSelectionTable (functionObject, pressure, dictionary)
defineTypeNameAndDebug (processorField, 0)
addToRunTimeSelectionTable (functionObject, processorField, dictionary)
defineTypeNameAndDebug (proudmanAcousticPower, 0)
addToRunTimeSelectionTable (functionObject, proudmanAcousticPower, dictionary)
defineTypeNameAndDebug (Q, 0)
addToRunTimeSelectionTable (functionObject, Q, dictionary)
defineTypeNameAndDebug (randomise, 0)
addToRunTimeSelectionTable (functionObject, randomise, dictionary)
addToRunTimeSelectionTable (functionObject, psiReactionsSensitivityAnalysisFunctionObject, dictionary)
addToRunTimeSelectionTable (functionObject, rhoReactionsSensitivityAnalysisFunctionObject, dictionary)
defineTypeNameAndDebug (readFields, 0)
addToRunTimeSelectionTable (functionObject, readFields, dictionary)
defineTypeNameAndDebug (reference, 0)
addToRunTimeSelectionTable (functionObject, reference, dictionary)
defineTypeNameAndDebug (regionSizeDistribution, 0)
addToRunTimeSelectionTable (functionObject, regionSizeDistribution, dictionary)
defineTypeNameAndDebug (resolutionIndex, 0)
addToRunTimeSelectionTable (functionObject, resolutionIndex, dictionary)
defineTypeNameAndDebug (setFlow, 0)
addToRunTimeSelectionTable (functionObject, setFlow, dictionary)
defineTypeNameAndDebug (stabilityBlendingFactor, 0)
addToRunTimeSelectionTable (functionObject, stabilityBlendingFactor, dictionary)
defineTypeNameAndDebug (streamFunction, 0)
addToRunTimeSelectionTable (functionObject, streamFunction, dictionary)
defineTypeNameAndDebug (streamLine, 0)
addToRunTimeSelectionTable (functionObject, streamLine, dictionary)
defineTypeNameAndDebug (streamLineBase, 0)
defineTypeNameAndDebug (subtract, 0)
addToRunTimeSelectionTable (functionObject, subtract, dictionary)
defineTypeNameAndDebug (surfaceDistance, 0)
addToRunTimeSelectionTable (functionObject, surfaceDistance, dictionary)
defineTypeNameAndDebug (surfaceInterpolate, 0)
addToRunTimeSelectionTable (functionObject, surfaceInterpolate, dictionary)
defineTypeNameAndDebug (turbulenceFields, 0)
addToRunTimeSelectionTable (functionObject, turbulenceFields, dictionary)
defineTypeNameAndDebug (valueAverage, 0)
addToRunTimeSelectionTable (functionObject, valueAverage, dictionary)
defineTypeNameAndDebug (vorticity, 0)
addToRunTimeSelectionTable (functionObject, vorticity, dictionary)
defineTypeNameAndDebug (wallBoundedStreamLine, 0)
addToRunTimeSelectionTable (functionObject, wallBoundedStreamLine, dictionary)
defineTypeNameAndDebug (wallHeatFlux, 0)
addToRunTimeSelectionTable (functionObject, wallHeatFlux, dictionary)
defineTypeNameAndDebug (wallShearStress, 0)
addToRunTimeSelectionTable (functionObject, wallShearStress, dictionary)
defineTypeNameAndDebug (writeCellCentres, 0)
addToRunTimeSelectionTable (functionObject, writeCellCentres, dictionary)
defineTypeNameAndDebug (writeCellVolumes, 0)
addToRunTimeSelectionTable (functionObject, writeCellVolumes, dictionary)
defineTypeNameAndDebug (XiReactionRate, 0)
addToRunTimeSelectionTable (functionObject, XiReactionRate, dictionary)
defineTypeNameAndDebug (yPlus, 0)
addToRunTimeSelectionTable (functionObject, yPlus, dictionary)
defineTypeNameAndDebug (zeroGradient, 0)
addToRunTimeSelectionTable (functionObject, zeroGradient, dictionary)
defineTypeNameAndDebug (forceCoeffs, 0)
addToRunTimeSelectionTable (functionObject, forceCoeffs, dictionary)
defineTypeNameAndDebug (forces, 0)
addToRunTimeSelectionTable (functionObject, forces, dictionary)
defineTypeNameAndDebug (propellerInfo, 0)
addToRunTimeSelectionTable (functionObject, propellerInfo, dictionary)
defineTypeNameAndDebug (hydrostaticPressure, 0)
addToRunTimeSelectionTable (functionObject, hydrostaticPressure, dictionary)
defineTypeNameAndDebug (cloudInfo, 0)
addToRunTimeSelectionTable (functionObject, cloudInfo, dictionary)
defineTypeNameAndDebug (dataCloud, 0)
addToRunTimeSelectionTable (functionObject, dataCloud, dictionary)
defineTypeNameAndDebug (dsmcFields, 0)
addToRunTimeSelectionTable (functionObject, dsmcFields, dictionary)
defineTypeNameAndDebug (icoUncoupledKinematicCloud, 0)
addToRunTimeSelectionTable (functionObject, icoUncoupledKinematicCloud, dictionary)
defineTypeNameAndDebug (vtkCloud, 0)
addToRunTimeSelectionTable (functionObject, vtkCloud, dictionary)
defineTypeNameAndDebug (phaseForces, 0)
addToRunTimeSelectionTable (functionObject, phaseForces, dictionary)
defineTypeNameAndDebug (sizeDistribution, 0)
addToRunTimeSelectionTable (functionObject, sizeDistribution, dictionary)
defineTypeNameAndDebug (energySpectrum, 0)
addToRunTimeSelectionTable (functionObject, energySpectrum, dictionary)
defineTypeNameAndDebug (electricPotential, 0)
addToRunTimeSelectionTable (functionObject, electricPotential, dictionary)
defineTypeNameAndDebug (energyTransport, 0)
addToRunTimeSelectionTable (functionObject, energyTransport, dictionary)
defineTypeNameAndDebug (scalarTransport, 0)
addToRunTimeSelectionTable (functionObject, scalarTransport, dictionary)
defineTypeNameAndDebug (abort, 0)
addToRunTimeSelectionTable (functionObject, abort, dictionary)
defineTypeNameAndDebug (codedFunctionObject, 0)
addToRunTimeSelectionTable (functionObject, codedFunctionObject, dictionary)
defineTypeNameAndDebug (ensightWrite, 0)
addToRunTimeSelectionTable (functionObject, ensightWrite, dictionary)
defineTypeNameAndDebug (multiRegion, 0)
addToRunTimeSelectionTable (functionObject, multiRegion, dictionary)
defineTypeNameAndDebug (parProfiling, 0)
addToRunTimeSelectionTable (functionObject, parProfiling, dictionary)
defineTypeNameAndDebug (removeRegisteredObject, 0)
addToRunTimeSelectionTable (functionObject, removeRegisteredObject, dictionary)
defineTypeNameAndDebug (setTimeStepFunctionObject, 0)
addToRunTimeSelectionTable (functionObject, setTimeStepFunctionObject, dictionary)
defineTypeNameAndDebug (solverInfo, 0)
addToRunTimeSelectionTable (functionObject, solverInfo, dictionary)
defineTypeNameAndDebug (syncObjects, 0)
addToRunTimeSelectionTable (functionObject, syncObjects, dictionary)
defineTypeNameAndDebug (systemCall, 0)
addToRunTimeSelectionTable (functionObject, systemCall, dictionary)
defineTypeNameAndDebug (thermoCoupleProbes, 0)
addToRunTimeSelectionTable (functionObject, thermoCoupleProbes, dictionary)
defineTypeNameAndDebug (timeActivatedFileUpdate, 0)
addToRunTimeSelectionTable (functionObject, timeActivatedFileUpdate, dictionary)
defineTypeNameAndDebug (timeInfo, 0)
addToRunTimeSelectionTable (functionObject, timeInfo, dictionary)
defineTypeNameAndDebug (vtkWrite, 0)
addToRunTimeSelectionTable (functionObject, vtkWrite, dictionary)
defineTypeNameAndDebug (writeDictionary, 0)
addToRunTimeSelectionTable (functionObject, writeDictionary, dictionary)
defineTypeNameAndDebug (writeObjects, 0)
addToRunTimeSelectionTable (functionObject, writeObjects, dictionary)
defineTypeNameAndDebug (regionFunctionObject, 0)
defineTypeNameAndDebug (timeControl, 0)
defineTypeNameAndDebug (setTimeStepFaRegionsFunctionObject, 0)
addToRunTimeSelectionTable (functionObject, setTimeStepFaRegionsFunctionObject, dictionary)
defineTypeNameAndDebug (filmFlux, 0)
addToRunTimeSelectionTable (functionObject, filmFlux, dictionary)
defineTypeNameAndDebug (sixDoFRigidBodyState, 0)
addToRunTimeSelectionTable (functionObject, sixDoFRigidBodyState, dictionary)
defineTypeNameAndDebug (BilgerMixtureFraction, 0)
addToRunTimeSelectionTable (functionObject, BilgerMixtureFraction, dictionary)
Detailed Description
Function objects are OpenFOAM utilities to ease workflow configurations and enhance workflows by producing additional user-requested data both during runtime and postprocessing calculations, typically in the form of additional logging to the screen, or generating text, image and field files.
Function objects eliminate the need to store all runtime generated data, hence saving considerable resources. Furthermore, function objects are readily applied to batch-driven processes, improving reliability by standardising the sequence of operations and reducing the amount of manual interaction.
In addition, the output of most function objects, e.g. output fields, are stored on the mesh database so that it can be retrieved and used for other applications (e.g. directly using wallShearStress function object output in fieldAverage function object to produce wallShearStressMean field).
Function objects
Function objects can be executed by using two methods:
functions sub-dictionary in the system/controlDict file
postProcess command-line utility
For the first method, each selected function object should be listed inside functions sub-dictionary of the system/controlDict file as a nested sub-dictionary, typically as in the following example:
functions   // sub-dictionary name under the system/controlDict file
{
    ..optional entries..
    <dictName1>
    {
        // Mandatory entries
        type    <functionObjectTypeName>;
        libs    (<libType>FunctionObjects);
        // Mandatory entries defined in <functionObjectType>
        ...
        // Optional entries defined in <functionObjectType>
        ...
        // Optional (inherited) entries
        region              region0;
        enabled             true;
        log                 true;
        timeStart           0;
        timeEnd             1000;
        executeControl      timeStep;
        executeInterval     1;
        writeControl        timeStep;
        writeInterval       1;
    }
    <dictName2>
    {
        ...
    }
    ...
    <dictNameN>
    {
        ...
    }
}
where the entries mean:
Property Description Type Reqd Deflt
type Type name of function object word yes -
libs Library name(s) for implementation words no -
enabled Switch to turn function object on/off bool no true
errors Error handling (default/warn/ignore/strict) word no inherits
log Switch to write log info to standard output bool no true
useNamePrefix Add scoping prefix to names bool no inherits
region Name of region for multi-region cases word no region0
timeStart Start time for function object execution scalar no 0
timeEnd End time for function object execution scalar no inf
executeControl See time controls below word no timeStep
executeInterval Steps/time between execute phases label no 1
writeControl See time controls below word no timeStep
writeInterval Steps/time between write phases label no 1
If the errors entry is missing, it uses the value (if any) specified within the top-level functionObjectList.
If the useNamePrefix entry is missing, it uses the value (if any) specified within the top-level functionObjectList or otherwise uses the current value of functionObject::defaultUseNamePrefix
Time controls:
Option Description
none Trigger is disabled
timeStep Trigger every 'Interval' time-steps
writeTime Trigger every 'Interval' output times
runTime Trigger every 'Interval' run time period
adjustableRunTime Currently identical to "runTime"
clockTime Trigger every 'Interval' clock time period
cpuTime Trigger every 'Interval' CPU time period
onEnd Trigger on end of simulation run
The sub-dictionary name <userDefinedSubDictName> is chosen by the user, and is typically used as the name of the output directory for any data written by the function object.
As the base mandatory entries, the type entry defines the type of function object properties that follow. Function objects are packaged into separate libraries for flexibility and the libs entry is used to specify which library should be loaded.
Each function object has two separate run phases:
The execute phase is meant to be used for updating calculations or for management tasks.
The write phase is meant for writing the calculated data to disk.
For each phase the respective time controls are provided, as listed above.
The second method of executing function objects is to use postProcess utility.
When specified without additional arguments, the postProcess utility executes all function objects defined in the system/controlDict file for all time directories:
        postProcess
Most function objects can be invoked directly without the need to specify the input dictionary using the -func option, e.g. to execute the Courant number function object:
        postProcess -func CourantNo
In addition, the -postProcess option is available to all solvers, and operates similarly to the stand-alone postProcess utility. For example, having completed a simpleFoam calculation, the following will execute all function objects defined in the system/controlDict file for all time directories:
        simpleFoam -postProcess
Function Documentation
defineTypeNameAndDebug() [1/121]
defineTypeNameAndDebug (ObukhovLength , 0)
addToRunTimeSelectionTable() [1/115]
addToRunTimeSelectionTable (functionObject , ObukhovLength , dictionary)
operator>>() [1/2]
Istream & operator>> (Istream & , fieldInfo &)
Definition at line 132 of file fieldInfo.H.
operator<<() [1/2]
Ostream & operator<< (Ostream & , const fieldInfo &)
Definition at line 137 of file fieldInfo.H.
defineTypeNameAndDebug() [2/121]
defineTypeNameAndDebug (fvMeshFunctionObject , 0)
defineTypeNameAndDebug() [3/121]
defineTypeNameAndDebug (volRegion , 0)
defineTypeNameAndDebug() [4/121]
defineTypeNameAndDebug (add , 0)
addToRunTimeSelectionTable() [2/115]
addToRunTimeSelectionTable (functionObject , add , dictionary)
defineTypeNameAndDebug() [5/121]
defineTypeNameAndDebug (age , 0)
addToRunTimeSelectionTable() [3/115]
addToRunTimeSelectionTable (functionObject , age , dictionary)
defineTypeNameAndDebug() [6/121]
defineTypeNameAndDebug (AMIWeights , 0)
addToRunTimeSelectionTable() [4/115]
addToRunTimeSelectionTable (functionObject , AMIWeights , dictionary)
defineTypeNameAndDebug() [7/121]
defineTypeNameAndDebug (binField , 0)
addToRunTimeSelectionTable() [5/115]
addToRunTimeSelectionTable (functionObject , binField , dictionary)
defineTypeNameAndDebug() [8/121]
defineTypeNameAndDebug (blendingFactor , 0)
addToRunTimeSelectionTable() [6/115]
addToRunTimeSelectionTable (functionObject , blendingFactor , dictionary)
defineTypeNameAndDebug() [9/121]
defineTypeNameAndDebug (columnAverage , 0)
addToRunTimeSelectionTable() [7/115]
addToRunTimeSelectionTable (functionObject , columnAverage , dictionary)
defineTypeNameAndDebug() [10/121]
defineTypeNameAndDebug (comfort , 0)
addToRunTimeSelectionTable() [8/115]
addToRunTimeSelectionTable (functionObject , comfort , dictionary)
defineTypeNameAndDebug() [11/121]
defineTypeNameAndDebug (components , 0)
addToRunTimeSelectionTable() [9/115]
addToRunTimeSelectionTable (functionObject , components , dictionary)
defineTypeNameAndDebug() [12/121]
defineTypeNameAndDebug (continuityError , 0)
addToRunTimeSelectionTable() [10/115]
addToRunTimeSelectionTable (functionObject , continuityError , dictionary)
defineTypeNameAndDebug() [13/121]
defineTypeNameAndDebug (CourantNo , 0)
addToRunTimeSelectionTable() [11/115]
addToRunTimeSelectionTable (functionObject , CourantNo , dictionary)
defineTypeNameAndDebug() [14/121]
defineTypeNameAndDebug (Curle , 0)
addToRunTimeSelectionTable() [12/115]
addToRunTimeSelectionTable (functionObject , Curle , dictionary)
defineTypeNameAndDebug() [15/121]
defineTypeNameAndDebug (ddt , 0)
addToRunTimeSelectionTable() [13/115]
addToRunTimeSelectionTable (functionObject , ddt , dictionary)
defineTypeNameAndDebug() [16/121]
defineTypeNameAndDebug (ddt2 , 0)
addToRunTimeSelectionTable() [14/115]
addToRunTimeSelectionTable (functionObject , ddt2 , dictionary)
defineTypeNameAndDebug() [17/121]
defineTypeNameAndDebug (derivedFields , 0)
addToRunTimeSelectionTable() [15/115]
addToRunTimeSelectionTable (functionObject , derivedFields , dictionary)
defineTypeNameAndDebug() [18/121]
defineTypeNameAndDebug (DESModelRegions , 0)
addToRunTimeSelectionTable() [16/115]
addToRunTimeSelectionTable (functionObject , DESModelRegions , dictionary)
defineTypeNameAndDebug() [19/121]
defineTypeNameAndDebug (div , 0)
addToRunTimeSelectionTable() [17/115]
addToRunTimeSelectionTable (functionObject , div , dictionary)
defineTypeNameAndDebug() [20/121]
defineTypeNameAndDebug (DMD , 0)
addToRunTimeSelectionTable() [18/115]
addToRunTimeSelectionTable (functionObject , DMD , dictionary)
defineTypeNameAndDebug() [21/121]
defineTypeNameAndDebug (enstrophy , 0)
addToRunTimeSelectionTable() [19/115]
addToRunTimeSelectionTable (functionObject , enstrophy , dictionary)
defineTypeNameAndDebug() [22/121]
defineTypeNameAndDebug (fvExpressionField , 0)
addToRunTimeSelectionTable() [20/115]
addToRunTimeSelectionTable (functionObject , fvExpressionField , dictionary)
defineTypeNameAndDebug() [23/121]
defineTypeNameAndDebug (externalCoupled , 0)
addToRunTimeSelectionTable() [21/115]
addToRunTimeSelectionTable (functionObject , externalCoupled , dictionary)
defineTypeNameAndDebug() [24/121]
defineTypeNameAndDebug (extractEulerianParticles , 0)
addToRunTimeSelectionTable() [22/115]
addToRunTimeSelectionTable (functionObject , extractEulerianParticles , dictionary)
defineTypeNameAndDebug() [25/121]
defineTypeNameAndDebug (fieldAverage , 0)
addToRunTimeSelectionTable() [23/115]
addToRunTimeSelectionTable (functionObject , fieldAverage , dictionary)
operator>>() [2/2]
Foam::Istream & operator>> (Istream & is, fieldAverageItem & faItem)
Definition at line 53 of file fieldAverageItemIO.C.
References dict, UPtrList< T >::empty(), Foam::endl(), fieldAverageItem::EXACT, Foam::exit(), fieldAverageItem::EXT_MEAN, fieldAverageItem::EXT_PRIME2MEAN, Foam::FatalIOError, FatalIOErrorInFunction, FUNCTION_NAME, UPtrList< T >::get(), fieldAverageItem::NONE, dictionary::null, and WarningInFunction.
operator<<() [2/2]
Foam::Ostream & operator<< (Ostream & os, const fieldAverageItem & faItem)
Definition at line 136 of file fieldAverageItemIO.C.
References IOstream::check(), UPtrList< T >::empty(), FUNCTION_NAME, and os().
defineTypeNameAndDebug() [26/121]
defineTypeNameAndDebug (fieldCoordinateSystemTransform , 0)
addToRunTimeSelectionTable() [24/115]
addToRunTimeSelectionTable (functionObject , fieldCoordinateSystemTransform , dictionary)
defineTypeNameAndDebug() [27/121]
defineTypeNameAndDebug (fieldExpression , 0)
defineTypeNameAndDebug() [28/121]
defineTypeNameAndDebug (fieldExtents , 0)
addToRunTimeSelectionTable() [25/115]
addToRunTimeSelectionTable (functionObject , fieldExtents , dictionary)
defineTypeNameAndDebug() [29/121]
defineTypeNameAndDebug (fieldMinMax , 0)
addToRunTimeSelectionTable() [26/115]
addToRunTimeSelectionTable (functionObject , fieldMinMax , dictionary)
defineTypeNameAndDebug() [30/121]
defineTypeNameAndDebug (fieldsExpression , 0)
defineTypeNameAndDebug() [31/121]
defineTypeNameAndDebug (fieldValue , 0)
defineRunTimeSelectionTable()
defineRunTimeSelectionTable (fieldValue , runTime)
defineTypeNameAndDebug() [32/121]
defineTypeNameAndDebug (flowType , 0)
addToRunTimeSelectionTable() [27/115]
addToRunTimeSelectionTable (functionObject , flowType , dictionary)
defineTypeNameAndDebug() [33/121]
defineTypeNameAndDebug (flux , 0)
addToRunTimeSelectionTable() [28/115]
addToRunTimeSelectionTable (functionObject , flux , dictionary)
defineTypeNameAndDebug() [34/121]
defineTypeNameAndDebug (fluxSummary , 0)
addToRunTimeSelectionTable() [29/115]
addToRunTimeSelectionTable (functionObject , fluxSummary , dictionary)
defineTypeNameAndDebug() [35/121]
defineTypeNameAndDebug (grad , 0)
addToRunTimeSelectionTable() [30/115]
addToRunTimeSelectionTable (functionObject , grad , dictionary)
defineTypeNameAndDebug() [36/121]
defineTypeNameAndDebug (heatTransferCoeff , 0)
addToRunTimeSelectionTable() [31/115]
addToRunTimeSelectionTable (functionObject , heatTransferCoeff , dictionary)
defineTypeNameAndDebug() [37/121]
defineTypeNameAndDebug (multiphaseInterHtcModel , 0)
addToRunTimeSelectionTable() [32/115]
addToRunTimeSelectionTable (functionObject , multiphaseInterHtcModel , dictionary)
defineTypeNameAndDebug() [38/121]
defineTypeNameAndDebug (reactingEulerHtcModel , 0)
addToRunTimeSelectionTable() [33/115]
addToRunTimeSelectionTable (functionObject , reactingEulerHtcModel , dictionary)
defineTypeNameAndDebug() [39/121]
defineTypeNameAndDebug (histogram , 0)
addToRunTimeSelectionTable() [34/115]
addToRunTimeSelectionTable (functionObject , histogram , dictionary)
defineTypeNameAndDebug() [40/121]
defineTypeNameAndDebug (interfaceHeight , 0)
addToRunTimeSelectionTable() [35/115]
addToRunTimeSelectionTable (functionObject , interfaceHeight , dictionary)
defineTypeNameAndDebug() [41/121]
defineTypeNameAndDebug (Lambda2 , 0)
addToRunTimeSelectionTable() [36/115]
addToRunTimeSelectionTable (functionObject , Lambda2 , dictionary)
defineTypeNameAndDebug() [42/121]
defineTypeNameAndDebug (LambVector , 0)
addToRunTimeSelectionTable() [37/115]
addToRunTimeSelectionTable (functionObject , LambVector , dictionary)
defineTypeNameAndDebug() [43/121]
defineTypeNameAndDebug (limitFields , 0)
addToRunTimeSelectionTable() [38/115]
addToRunTimeSelectionTable (functionObject , limitFields , dictionary)
defineTypeNameAndDebug() [44/121]
defineTypeNameAndDebug (log , 0)
addToRunTimeSelectionTable() [39/115]
addToRunTimeSelectionTable (functionObject , log , dictionary)
defineTypeNameAndDebug() [45/121]
defineTypeNameAndDebug (MachNo , 0)
addToRunTimeSelectionTable() [40/115]
addToRunTimeSelectionTable (functionObject , MachNo , dictionary)
defineTypeNameAndDebug() [46/121]
defineTypeNameAndDebug (mag , 0)
addToRunTimeSelectionTable() [41/115]
addToRunTimeSelectionTable (functionObject , mag , dictionary)
defineTypeNameAndDebug() [47/121]
defineTypeNameAndDebug (magSqr , 0)
addToRunTimeSelectionTable() [42/115]
addToRunTimeSelectionTable (functionObject , magSqr , dictionary)
defineTypeNameAndDebug() [48/121]
defineTypeNameAndDebug (mapFields , 0)
addToRunTimeSelectionTable() [43/115]
addToRunTimeSelectionTable (functionObject , mapFields , dictionary)
defineTypeNameAndDebug() [49/121]
defineTypeNameAndDebug (momentum , 0)
addToRunTimeSelectionTable() [44/115]
addToRunTimeSelectionTable (functionObject , momentum , dictionary)
defineTypeNameAndDebug() [50/121]
defineTypeNameAndDebug (momentumError , 0)
addToRunTimeSelectionTable() [45/115]
addToRunTimeSelectionTable (functionObject , momentumError , dictionary)
defineTypeNameAndDebug() [51/121]
defineTypeNameAndDebug (multiply , 0)
addToRunTimeSelectionTable() [46/115]
addToRunTimeSelectionTable (functionObject , multiply , dictionary)
defineTypeNameAndDebug() [52/121]
defineTypeNameAndDebug (nearWallFields , 0)
addToRunTimeSelectionTable() [47/115]
addToRunTimeSelectionTable (functionObject , nearWallFields , dictionary)
defineTypeNameAndDebug() [53/121]
defineTypeNameAndDebug (norm , 0)
addToRunTimeSelectionTable() [48/115]
addToRunTimeSelectionTable (functionObject , norm , dictionary)
defineTypeNameAndDebug() [54/121]
defineTypeNameAndDebug (particleDistribution , 0)
addToRunTimeSelectionTable() [49/115]
addToRunTimeSelectionTable (functionObject , particleDistribution , dictionary)
defineTypeNameAndDebug() [55/121]
defineTypeNameAndDebug (PecletNo , 0)
addToRunTimeSelectionTable() [50/115]
addToRunTimeSelectionTable (functionObject , PecletNo , dictionary)
defineTypeNameAndDebug() [56/121]
defineTypeNameAndDebug (pow , 0)
addToRunTimeSelectionTable() [51/115]
addToRunTimeSelectionTable (functionObject , pow , dictionary)
defineTypeNameAndDebug() [57/121]
defineTypeNameAndDebug (pressure , 0)
addToRunTimeSelectionTable() [52/115]
addToRunTimeSelectionTable (functionObject , pressure , dictionary)
defineTypeNameAndDebug() [58/121]
defineTypeNameAndDebug (processorField , 0)
addToRunTimeSelectionTable() [53/115]
addToRunTimeSelectionTable (functionObject , processorField , dictionary)
defineTypeNameAndDebug() [59/121]
defineTypeNameAndDebug (proudmanAcousticPower , 0)
addToRunTimeSelectionTable() [54/115]
addToRunTimeSelectionTable (functionObject , proudmanAcousticPower , dictionary)
defineTypeNameAndDebug() [60/121]
defineTypeNameAndDebug (Q , 0)
addToRunTimeSelectionTable() [55/115]
addToRunTimeSelectionTable (functionObject , Q , dictionary)
defineTypeNameAndDebug() [61/121]
defineTypeNameAndDebug (randomise , 0)
addToRunTimeSelectionTable() [56/115]
addToRunTimeSelectionTable (functionObject , randomise , dictionary)
addToRunTimeSelectionTable() [57/115]
addToRunTimeSelectionTable (functionObject , psiReactionsSensitivityAnalysisFunctionObject , dictionary)
addToRunTimeSelectionTable() [58/115]
addToRunTimeSelectionTable (functionObject , rhoReactionsSensitivityAnalysisFunctionObject , dictionary)
defineTypeNameAndDebug() [62/121]
defineTypeNameAndDebug (readFields , 0)
addToRunTimeSelectionTable() [59/115]
addToRunTimeSelectionTable (functionObject , readFields , dictionary)
defineTypeNameAndDebug() [63/121]
defineTypeNameAndDebug (reference , 0)
addToRunTimeSelectionTable() [60/115]
addToRunTimeSelectionTable (functionObject , reference , dictionary)
defineTypeNameAndDebug() [64/121]
defineTypeNameAndDebug (regionSizeDistribution , 0)
addToRunTimeSelectionTable() [61/115]
addToRunTimeSelectionTable (functionObject , regionSizeDistribution , dictionary)
defineTypeNameAndDebug() [65/121]
defineTypeNameAndDebug (resolutionIndex , 0)
addToRunTimeSelectionTable() [62/115]
addToRunTimeSelectionTable (functionObject , resolutionIndex , dictionary)
defineTypeNameAndDebug() [66/121]
defineTypeNameAndDebug (setFlow , 0)
addToRunTimeSelectionTable() [63/115]
addToRunTimeSelectionTable (functionObject , setFlow , dictionary)
defineTypeNameAndDebug() [67/121]
defineTypeNameAndDebug (stabilityBlendingFactor , 0)
addToRunTimeSelectionTable() [64/115]
addToRunTimeSelectionTable (functionObject , stabilityBlendingFactor , dictionary)
defineTypeNameAndDebug() [68/121]
defineTypeNameAndDebug (streamFunction , 0)
addToRunTimeSelectionTable() [65/115]
addToRunTimeSelectionTable (functionObject , streamFunction , dictionary)
defineTypeNameAndDebug() [69/121]
defineTypeNameAndDebug (streamLine , 0)
addToRunTimeSelectionTable() [66/115]
addToRunTimeSelectionTable (functionObject , streamLine , dictionary)
defineTypeNameAndDebug() [70/121]
defineTypeNameAndDebug (streamLineBase , 0)
defineTypeNameAndDebug() [71/121]
defineTypeNameAndDebug (subtract , 0)
addToRunTimeSelectionTable() [67/115]
addToRunTimeSelectionTable (functionObject , subtract , dictionary)
defineTypeNameAndDebug() [72/121]
defineTypeNameAndDebug (surfaceDistance , 0)
addToRunTimeSelectionTable() [68/115]
addToRunTimeSelectionTable (functionObject , surfaceDistance , dictionary)
defineTypeNameAndDebug() [73/121]
defineTypeNameAndDebug (surfaceInterpolate , 0)
addToRunTimeSelectionTable() [69/115]
addToRunTimeSelectionTable (functionObject , surfaceInterpolate , dictionary)
defineTypeNameAndDebug() [74/121]
defineTypeNameAndDebug (turbulenceFields , 0)
addToRunTimeSelectionTable() [70/115]
addToRunTimeSelectionTable (functionObject , turbulenceFields , dictionary)
defineTypeNameAndDebug() [75/121]
defineTypeNameAndDebug (valueAverage , 0)
addToRunTimeSelectionTable() [71/115]
addToRunTimeSelectionTable (functionObject , valueAverage , dictionary)
defineTypeNameAndDebug() [76/121]
defineTypeNameAndDebug (vorticity , 0)
addToRunTimeSelectionTable() [72/115]
addToRunTimeSelectionTable (functionObject , vorticity , dictionary)
defineTypeNameAndDebug() [77/121]
defineTypeNameAndDebug (wallBoundedStreamLine , 0)
addToRunTimeSelectionTable() [73/115]
addToRunTimeSelectionTable (functionObject , wallBoundedStreamLine , dictionary)
defineTypeNameAndDebug() [78/121]
defineTypeNameAndDebug (wallHeatFlux , 0)
addToRunTimeSelectionTable() [74/115]
addToRunTimeSelectionTable (functionObject , wallHeatFlux , dictionary)
defineTypeNameAndDebug() [79/121]
defineTypeNameAndDebug (wallShearStress , 0)
addToRunTimeSelectionTable() [75/115]
addToRunTimeSelectionTable (functionObject , wallShearStress , dictionary)
defineTypeNameAndDebug() [80/121]
defineTypeNameAndDebug (writeCellCentres , 0)
addToRunTimeSelectionTable() [76/115]
addToRunTimeSelectionTable (functionObject , writeCellCentres , dictionary)
defineTypeNameAndDebug() [81/121]
defineTypeNameAndDebug (writeCellVolumes , 0)
addToRunTimeSelectionTable() [77/115]
addToRunTimeSelectionTable (functionObject , writeCellVolumes , dictionary)
defineTypeNameAndDebug() [82/121]
defineTypeNameAndDebug (XiReactionRate , 0)
addToRunTimeSelectionTable() [78/115]
addToRunTimeSelectionTable (functionObject , XiReactionRate , dictionary)
defineTypeNameAndDebug() [83/121]
defineTypeNameAndDebug (yPlus , 0)
addToRunTimeSelectionTable() [79/115]
addToRunTimeSelectionTable (functionObject , yPlus , dictionary)
defineTypeNameAndDebug() [84/121]
defineTypeNameAndDebug (zeroGradient , 0)
addToRunTimeSelectionTable() [80/115]
addToRunTimeSelectionTable (functionObject , zeroGradient , dictionary)
defineTypeNameAndDebug() [85/121]
defineTypeNameAndDebug (forceCoeffs , 0)
addToRunTimeSelectionTable() [81/115]
addToRunTimeSelectionTable (functionObject , forceCoeffs , dictionary)
defineTypeNameAndDebug() [86/121]
defineTypeNameAndDebug (forces , 0)
addToRunTimeSelectionTable() [82/115]
addToRunTimeSelectionTable (functionObject , forces , dictionary)
defineTypeNameAndDebug() [87/121]
defineTypeNameAndDebug (propellerInfo , 0)
addToRunTimeSelectionTable() [83/115]
addToRunTimeSelectionTable (functionObject , propellerInfo , dictionary)
defineTypeNameAndDebug() [88/121]
defineTypeNameAndDebug (hydrostaticPressure , 0)
addToRunTimeSelectionTable() [84/115]
addToRunTimeSelectionTable (functionObject , hydrostaticPressure , dictionary)
defineTypeNameAndDebug() [89/121]
defineTypeNameAndDebug (cloudInfo , 0)
addToRunTimeSelectionTable() [85/115]
addToRunTimeSelectionTable (functionObject , cloudInfo , dictionary)
defineTypeNameAndDebug() [90/121]
defineTypeNameAndDebug (dataCloud , 0)
addToRunTimeSelectionTable() [86/115]
addToRunTimeSelectionTable (functionObject , dataCloud , dictionary)
defineTypeNameAndDebug() [91/121]
defineTypeNameAndDebug (dsmcFields , 0)
addToRunTimeSelectionTable() [87/115]
addToRunTimeSelectionTable (functionObject , dsmcFields , dictionary)
defineTypeNameAndDebug() [92/121]
defineTypeNameAndDebug (icoUncoupledKinematicCloud , 0)
addToRunTimeSelectionTable() [88/115]
addToRunTimeSelectionTable (functionObject , icoUncoupledKinematicCloud , dictionary)
defineTypeNameAndDebug() [93/121]
defineTypeNameAndDebug (vtkCloud , 0)
addToRunTimeSelectionTable() [89/115]
addToRunTimeSelectionTable (functionObject , vtkCloud , dictionary)
defineTypeNameAndDebug() [94/121]
defineTypeNameAndDebug (phaseForces , 0)
addToRunTimeSelectionTable() [90/115]
addToRunTimeSelectionTable (functionObject , phaseForces , dictionary)
defineTypeNameAndDebug() [95/121]
defineTypeNameAndDebug (sizeDistribution , 0)
addToRunTimeSelectionTable() [91/115]
addToRunTimeSelectionTable (functionObject , sizeDistribution , dictionary)
defineTypeNameAndDebug() [96/121]
defineTypeNameAndDebug (energySpectrum , 0)
addToRunTimeSelectionTable() [92/115]
addToRunTimeSelectionTable (functionObject , energySpectrum , dictionary)
defineTypeNameAndDebug() [97/121]
defineTypeNameAndDebug (electricPotential , 0)
addToRunTimeSelectionTable() [93/115]
addToRunTimeSelectionTable (functionObject , electricPotential , dictionary)
defineTypeNameAndDebug() [98/121]
defineTypeNameAndDebug (energyTransport , 0)
addToRunTimeSelectionTable() [94/115]
addToRunTimeSelectionTable (functionObject , energyTransport , dictionary)
defineTypeNameAndDebug() [99/121]
defineTypeNameAndDebug (scalarTransport , 0)
addToRunTimeSelectionTable() [95/115]
addToRunTimeSelectionTable (functionObject , scalarTransport , dictionary)
defineTypeNameAndDebug() [100/121]
defineTypeNameAndDebug (abort , 0)
addToRunTimeSelectionTable() [96/115]
addToRunTimeSelectionTable (functionObject , abort , dictionary)
defineTypeNameAndDebug() [101/121]
defineTypeNameAndDebug (codedFunctionObject , 0)
addToRunTimeSelectionTable() [97/115]
addToRunTimeSelectionTable (functionObject , codedFunctionObject , dictionary)
defineTypeNameAndDebug() [102/121]
defineTypeNameAndDebug (ensightWrite , 0)
addToRunTimeSelectionTable() [98/115]
addToRunTimeSelectionTable (functionObject , ensightWrite , dictionary)
defineTypeNameAndDebug() [103/121]
defineTypeNameAndDebug (multiRegion , 0)
addToRunTimeSelectionTable() [99/115]
addToRunTimeSelectionTable (functionObject , multiRegion , dictionary)
defineTypeNameAndDebug() [104/121]
defineTypeNameAndDebug (parProfiling , 0)
addToRunTimeSelectionTable() [100/115]
addToRunTimeSelectionTable (functionObject , parProfiling , dictionary)
defineTypeNameAndDebug() [105/121]
defineTypeNameAndDebug (removeRegisteredObject , 0)
addToRunTimeSelectionTable() [101/115]
addToRunTimeSelectionTable (functionObject , removeRegisteredObject , dictionary)
defineTypeNameAndDebug() [106/121]
defineTypeNameAndDebug (setTimeStepFunctionObject , 0)
addToRunTimeSelectionTable() [102/115]
addToRunTimeSelectionTable (functionObject , setTimeStepFunctionObject , dictionary)
defineTypeNameAndDebug() [107/121]
defineTypeNameAndDebug (solverInfo , 0)
addToRunTimeSelectionTable() [103/115]
addToRunTimeSelectionTable (functionObject , solverInfo , dictionary)
defineTypeNameAndDebug() [108/121]
defineTypeNameAndDebug (syncObjects , 0)
addToRunTimeSelectionTable() [104/115]
addToRunTimeSelectionTable (functionObject , syncObjects , dictionary)
defineTypeNameAndDebug() [109/121]
defineTypeNameAndDebug (systemCall , 0)
addToRunTimeSelectionTable() [105/115]
addToRunTimeSelectionTable (functionObject , systemCall , dictionary)
defineTypeNameAndDebug() [110/121]
defineTypeNameAndDebug (thermoCoupleProbes , 0)
addToRunTimeSelectionTable() [106/115]
addToRunTimeSelectionTable (functionObject , thermoCoupleProbes , dictionary)
defineTypeNameAndDebug() [111/121]
defineTypeNameAndDebug (timeActivatedFileUpdate , 0)
addToRunTimeSelectionTable() [107/115]
addToRunTimeSelectionTable (functionObject , timeActivatedFileUpdate , dictionary)
defineTypeNameAndDebug() [112/121]
defineTypeNameAndDebug (timeInfo , 0)
addToRunTimeSelectionTable() [108/115]
addToRunTimeSelectionTable (functionObject , timeInfo , dictionary)
defineTypeNameAndDebug() [113/121]
defineTypeNameAndDebug (vtkWrite , 0)
addToRunTimeSelectionTable() [109/115]
addToRunTimeSelectionTable (functionObject , vtkWrite , dictionary)
defineTypeNameAndDebug() [114/121]
defineTypeNameAndDebug (writeDictionary , 0)
addToRunTimeSelectionTable() [110/115]
addToRunTimeSelectionTable (functionObject , writeDictionary , dictionary)
defineTypeNameAndDebug() [115/121]
defineTypeNameAndDebug (writeObjects , 0)
addToRunTimeSelectionTable() [111/115]
addToRunTimeSelectionTable (functionObject , writeObjects , dictionary)
defineTypeNameAndDebug() [116/121]
defineTypeNameAndDebug (regionFunctionObject , 0)
defineTypeNameAndDebug() [117/121]
defineTypeNameAndDebug (timeControl , 0)
defineTypeNameAndDebug() [118/121]
defineTypeNameAndDebug (setTimeStepFaRegionsFunctionObject , 0)
addToRunTimeSelectionTable() [112/115]
addToRunTimeSelectionTable (functionObject , setTimeStepFaRegionsFunctionObject , dictionary)
defineTypeNameAndDebug() [119/121]
defineTypeNameAndDebug (filmFlux , 0)
addToRunTimeSelectionTable() [113/115]
addToRunTimeSelectionTable (functionObject , filmFlux , dictionary)
defineTypeNameAndDebug() [120/121]
defineTypeNameAndDebug (sixDoFRigidBodyState , 0)
addToRunTimeSelectionTable() [114/115]
addToRunTimeSelectionTable (functionObject , sixDoFRigidBodyState , dictionary)
defineTypeNameAndDebug() [121/121]
defineTypeNameAndDebug (BilgerMixtureFraction , 0)
addToRunTimeSelectionTable() [115/115]
addToRunTimeSelectionTable (functionObject , BilgerMixtureFraction , dictionary)