OpenFOAM: Foam::stringListOps Namespace Reference
Foam::stringListOps Namespace Reference
Various utility functions to work on lists of strings.
Classes
struct foundOp
Functions
template<class StringListType , class AccessOp = identityOp>
labelList findMatching (const StringListType &input, const wordRes::filter &pred, AccessOp aop=identityOp())
template<class StringListType , class AccessOp = identityOp>
labelList findMatching (const StringListType &input, const wordRes &allow, const wordRes &deny=wordRes::null(), AccessOp aop=identityOp())
Detailed Description
Various utility functions to work on lists of strings.
Source files
stringListOps.H
stringListOpsTemplates.C
Function Documentation
findMatching() [1/2]
template<class StringListType , class AccessOp = identityOp> labelList findMatching (const StringListType & input, const wordRes::filter & pred, AccessOp aop = identityOp())
Referenced by ensightMesh::correct(), surfaceFormatsCore::getSelectedPatches(), sampledMeshedSurface::sampledMeshedSurface(), and triSurface::subsetMesh().
findMatching() [2/2]
template<class StringListType , class AccessOp = identityOp> labelList findMatching (const StringListType & input, const wordRes & allow, const wordRes & deny = wordRes::null(), AccessOp aop = identityOp())