OpenFOAM: Foam::Detail Namespace Reference
Foam::Detail Namespace Reference
Namespaces
namespace ListPolicy
Additional compile-time controls of List behaviour.
Classes
class HashTablePair
Internal storage type for HashTable.
struct HashTableSingle
class IListStreamAllocator
struct isPointerLike
struct isPointerLike< autoPtr< T > >
struct isPointerLike< std::unique_ptr< T > >
class MeshedSurfaceIOAllocator
A helper class for storing points and faces with IO capabilities.
class OCountStreamAllocator
class OListStreamAllocator
class OSHA1streamAllocator
class PackedListCore
Implementation of template-invariant details for Foam::PackedList.
class parcelSelection
Selection of parcels based on their objectRegistry entries. Normally accessed via a dictionary entry.
class PtrListDetail
A rudimentary list of pointers used for PtrList, UPtrList, etc. This class is considered implementation detail and should not normally be used other than by OpenFOAM container classes.
class STLAsciiParse
Internal class used when parsing STL ASCII format.
class STLAsciiParseManual
class StringStreamAllocator
class UIListStreamAllocator
class UOListStreamAllocator
class zoneSubSet
Functions
defineTypeNameAndDebug (zoneSubSet, 0)
defineTypeName (PackedListCore)
template<class IS >
void inputLoop (IS &)
template<class OS >
void outputLoop (OS &)
template<class IS , class Type , class... Args>
void inputLoop (IS &is, Type &arg1, Args &&... args)
template<class OS , class Type , class... Args>
void outputLoop (OS &os, const Type &arg1, Args &&... args)
template<class T >
void readContiguous (Istream &is, char *data, std::streamsize byteCount)
template<class Type , template< class > class PatchField, class GeoMesh >
bool reusable (const tmp< GeometricField< Type, PatchField, GeoMesh > > &tfld)
template<class PointList , class IndexerOp >
label mergePoints (const PointList &points, const IndexerOp &indexer, const label nSubPoints, labelList &pointToUnique, labelList &uniquePoints, const scalar mergeTol, const bool verbose)
template<class T >
std::enable_if<!std::is_same< complex, T >::value, constT & >::type conj (const T &val)
template<class T >
std::enable_if< std::is_same< complex, T >::value, complex >::type conj (const T &val)
Function Documentation
defineTypeNameAndDebug()
defineTypeNameAndDebug (zoneSubSet , 0)
defineTypeName()
defineTypeName (PackedListCore)
inputLoop() [1/2]
template<class IS > void inputLoop (IS &) inline
Definition at line 473 of file IOstream.H.
Referenced by Pstream::broadcasts(), and inputLoop().
outputLoop() [1/2]
template<class OS > void outputLoop (OS &) inline
Definition at line 478 of file IOstream.H.
Referenced by Pstream::broadcasts(), and outputLoop().
inputLoop() [2/2]
template<class IS , class Type , class... Args> void inputLoop (IS & is, Type & arg1, Args &&... args) inline
Definition at line 484 of file IOstream.H.
References args, and inputLoop().
outputLoop() [2/2]
template<class OS , class Type , class... Args> void outputLoop (OS & os, const Type & arg1, Args &&... args) inline
Definition at line 494 of file IOstream.H.
References args, os(), and outputLoop().
readContiguous()
template<class T > void readContiguous (Istream & is, char * data, std::streamsize byteCount)
Definition at line 239 of file Istream.H.
References readContiguous(), and Foam::readRawLabel().
Referenced by readContiguous().
reusable()
template<class Type , template< class > class PatchField, class GeoMesh > bool reusable (const tmp< GeometricField< Type, PatchField, GeoMesh > > & tfld) inline
Definition at line 42 of file GeometricFieldReuseFunctions.H.
References polyPatch::constraintType(), Foam::endl(), p, and WarningInFunction.
Referenced by reuseTmpTmpGeometricField< TypeR, Type1, Type12, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, Type2, PatchField, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, TypeR, PatchField, GeoMesh >::New(), and reuseTmpGeometricField< TypeR, TypeR, PatchField, GeoMesh >::New().
mergePoints()
template<class PointList , class IndexerOp > label mergePoints (const PointList & points, const IndexerOp & indexer, const label nSubPoints, labelList & pointToUnique, labelList & uniquePoints, const scalar mergeTol, const bool verbose)
Parameters
points The input of all (unmerged) points
indexer Indexer for sub-points into all points
nSubPoints The number of sub-points
pointToUnique An old-to-new mapping
uniquePoints List of unique points from full list
mergeTol Geometric merge tolerance
verbose Debug verbosity
conj() [1/2]
template<class T > std::enable_if<!std::is_same< complex, T >::value, constT & >::type conj (const T & val)
Definition at line 310 of file complex.H.
Referenced by Foam::operator&(), Foam::operator^(), and Matrix< Form, Type >::T().
conj() [2/2]
template<class T > std::enable_if< std::is_same< complex, T >::value, complex >::type conj (const T & val)
Definition at line 321 of file complex.H.
References complex::conjugate().