OpenFOAM: Foam::HashTableOps Namespace Reference
Foam::HashTableOps Namespace Reference
Various operations for HashTable.
Classes
struct plusEqOp
Functions
template<class T , class Key , class Hash >
List< T > values (const HashTable< T, Key, Hash > &tbl, const bool doSort=false)
Detailed Description
Various operations for HashTable.
Source files
HashOps.H
HashOps.H
Function Documentation
values()
template<class T , class Key , class Hash > List< T > values (const HashTable< T, Key, Hash > & tbl, const bool doSort = false)
Definition at line 163 of file HashOps.H.
References forAllConstIters, Foam::output(), UPtrList< T >::size(), and Foam::sort().
Referenced by cuttingSurfaceBase::walkCellCuts().