OpenFOAM: Foam::blockMeshTools Namespace Reference
Foam::blockMeshTools Namespace Reference
Tools for parsing label(List) with dictionary lookup.
Functions
void read (Istream &, label &val, const dictionary &)
template<class T >
void read (Istream &, List< T > &list, const dictionary &)
label read (Istream &, const dictionary &)
template<class T >
List< T > read (Istream &is, const dictionary &)
void write (Ostream &, const label val, const dictionary &)
const entry * findEntry (const dictionary &dict, const label val)
Detailed Description
Tools for parsing label(List) with dictionary lookup.
Source files
blockMeshTools.H
blockMeshTools.C
blockMeshToolsTemplates.C
Function Documentation
read() [1/4]
void read (Istream & is, label & val, const dictionary & dict)
Definition at line 49 of file blockMeshTools.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FUNCTION_NAME, token::info(), token::isLabel(), token::isWord(), token::labelToken(), Foam::readLabel(), and token::wordToken().
Referenced by read(), blockVertex::read(), and read().
read() [2/4]
template<class T > void read (Istream & is, List< T > & list, const dictionary & dict)
Definition at line 25 of file blockMeshToolsTemplates.C.
References PtrList< T >::append(), dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FUNCTION_NAME, Foam::nl, read(), PtrList< T >::resize(), and T.
read() [3/4]
Foam::label read (Istream & is, const dictionary & dict)
Definition at line 92 of file blockMeshTools.C.
References dict, and read().
read() [4/4]
template<class T > List< T > read (Istream & is, const dictionary &)
write()
void write (Ostream & os, const label val, const dictionary & dict)
Definition at line 104 of file blockMeshTools.C.
References dict, e, os(), and Foam::resolveLabel().
Referenced by blockDescriptor::write(), and blockVertex::write().
findEntry()
const Foam::entry * findEntry (const dictionary & dict, const label val)
Definition at line 124 of file blockMeshTools.C.
References dict, e, and Foam::resolveLabel().