OpenFOAM: applications/solvers/acoustic/acousticFoam/paEqn.H File Reference
paEqn.H File Reference
Functions
fvScalarMatrix paEqn (fvm::d2dt2(pa) - sqr(c0) *fvc::laplacian(pa))
if (solvePrimaryRegion)
Variables
else
Function Documentation
paEqn()
fvScalarMatrix paEqn (fvm::d2dt2(pa) - sqr(c0) *fvc::laplacian(pa))
Referenced by objectiveManagerIncompressible::addPaEqnSource(), if(), and adjointSimple::mainIter().
if()
if (solvePrimaryRegion)
Definition at line 7 of file paEqn.H.
References paEqn().
Variable Documentation
else
else
Initial value:
{
    pa.correctBoundaryConditions()
Definition at line 12 of file paEqn.H.