OpenFOAM: src/functionObjects/utilities/parProfiling/parProfilingSolver.C File Reference
parProfilingSolver.C File Reference
Namespaces
namespace Foam
Typedefs
typedef lduMatrix::solver baseType
Functions
defineTypeNameAndDebug (parProfilingSolver, 0)
addNamedToRunTimeSelectionTable (baseType, parProfilingSolver, symMatrix, parProfiling)
addNamedToRunTimeSelectionTable (baseType, parProfilingSolver, asymMatrix, parProfiling)
static bool initialised_ (false)
Detailed Description
Original source file parProfilingSolver.C
Definition in file parProfilingSolver.C.
Function Documentation
initialised_()
static bool initialised_ (false) static
Referenced by maxDurationCondition::apply(), fieldAverage::calcAverages(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), turbulenceFields::execute(), solverInfo::execute(), momentum::initialise(), forces::initialise(), simpleControl::loop(), SIMPLEControlSingleRun::loop(), parProfilingSolver::parProfilingSolver(), fieldAverage::read(), momentum::read(), turbulenceFields::read(), solverInfo::read(), forceCoeffs::read(), forces::read(), maxDurationCondition::reset(), and maxDurationCondition::write().