OpenFOAM: applications/solvers/combustion/PDRFoam/ftEqn.H File Reference
ftEqn.H File Reference
Functions
if (composition.contains("ft"))
Function Documentation
if()
if (composition. contains"ft")
Definition at line 1 of file ftEqn.H.
References betav, composition, Db(), mvConvection(), phi, rho, and solve().