OpenFOAM: applications/solvers/combustion/PDRFoam/bEqn.H File Reference
bEqn.H File Reference
Functions
tmp< fv::convectionScheme< scalar > > mvConvection (fv::convectionScheme< scalar >::New(mesh, fields, phi, mesh.divScheme("div(phi,ft_b_ha_hau)")))
volScalarField Db ("Db", turbulence->muEff())
if (ign.ignited())
Function Documentation
mvConvection()
tmp< fv::convectionScheme< scalar > > mvConvection (fv::convectionScheme< scalar > ::Newmesh, fields, phi, mesh.divScheme("div(phi,ft_b_ha_hau)"))
Referenced by if().
Db()
volScalarField Db ("Db" , turbulence-> muEff())
Referenced by if(), and if().
if()
if (ign. ignited())
Definition at line 14 of file bEqn.H.
References b, betav, composition, Db(), flameWrinkling, fvOptions, mesh, mvConvection(), n, phi, rho, StCorr(), Su, and unstrainedLaminarFlameSpeed().