OpenFOAM: applications/solvers/combustion/fireFoam/phrghEqn.H File Reference
phrghEqn.H File Reference
Functions
if (pimple.dict().getOrDefault("hydrostaticInitialization", false))
Function Documentation
if()
if (pimple. dict).getOrDefault("hydrostaticInitialization", false)
Definition at line 1 of file phrghEqn.H.
References gh, ghf, mesh, nCorr, p, p_rgh, phig(), pimple, rho, rhof(), runTime, U, and Ostream::write().