OpenFOAM: applications/solvers/incompressible/pimpleFoam/SRFPimpleFoam/UrelEqn.H File Reference
UrelEqn.H File Reference
Functions
tmp< fvVectorMatrix > tUrelEqn (fvm::ddt(Urel)+fvm::div(phi, Urel)+turbulence->divDevReff(Urel)+SRF->Su()==fvOptions(Urel))
UrelEqn relax ()
fvOptions constrain (UrelEqn)
solve (UrelEqn==-fvc::grad(p))
fvOptions correct (Urel)
Variables
fvVectorMatrix & UrelEqn = tUrelEqn.ref()
Function Documentation
tUrelEqn()
tmp< fvVectorMatrix > tUrelEqn (fvm::ddt(Urel)+fvm::div(phi, Urel)+turbulence->divDevReff(Urel)+SRF->Su() = =fvOptions(Urel))
Referenced by if().
relax()
UrelEqn relax ()
constrain()
fvOptions constrain (UrelEqn)
solve()
solve (UrelEqn = =-fvc::grad(p))
correct()
fvOptions correct (Urel)
Variable Documentation
UrelEqn
fvVectorMatrix& UrelEqn = tUrelEqn.ref()
Definition at line 11 of file UrelEqn.H.
Referenced by if(), if(), and if().