OpenFOAM: src/OSspecific/POSIX/POSIX.C File Reference
POSIX.C File Reference
POSIX versions of the functions declared in OSspecific.H.
Classes
class directoryIterator
Namespaces
namespace Foam
namespace Foam::POSIX
OS-specific functions implemented in POSIX.
Macros
#define EXT_SO "so"
Functions
defineTypeNameAndDebug (POSIX, 0)
static bool cwdPreference_ (Foam::debug::optimisationSwitch("cwd", 0))
static void redirects (const bool bg)
static void * loadLibrary (const Foam::fileName &libName)
static Foam::fileName cwd_P ()
static Foam::fileName cwd_L ()
static int collectLibsCallback (struct dl_phdr_info *info, size_t size, void *data)
Detailed Description
POSIX versions of the functions declared in OSspecific.H.
Original source file POSIX.C
Definition in file POSIX.C.
Macro Definition Documentation
EXT_SO
#define EXT_SO "so"
Definition at line 63 of file POSIX.C.
Function Documentation
cwdPreference_()
static bool cwdPreference_ (Foam::debug::optimisationSwitch("cwd", 0)) static
Referenced by Foam::cwd().
redirects()
static void redirects (const bool bg) inline static
Definition at line 89 of file POSIX.C.
References Foam::infoDetailLevel.
Referenced by Foam::system(), and Foam::system().
loadLibrary()
static void * loadLibrary (const Foam::fileName & libName) inline static
Definition at line 111 of file POSIX.C.
References fileName::isAbsolute(), and p.
Referenced by Foam::dlOpen(), and codedBase::updateLibrary().
collectLibsCallback()
static int collectLibsCallback (struct dl_phdr_info * info, size_t size, void * data) static
Definition at line 1956 of file POSIX.C.
References PtrList< T >::append().
Referenced by Foam::dlLoaded().