OpenFOAM: src/OpenFOAM/db/functionObjects/functionObjectList/postProcess.H File Reference
postProcess.H File Reference
Execute application functionObjects to post-process existing results.
Macros
#define CREATE_TIME createTime.H
#define CREATE_MESH createMesh.H
#define CREATE_FIELDS createFields.H
#define CREATE_CONTROL createControl.H
#define INCLUDE_FILE(X) INCLUDE_FILE2(X)
#define INCLUDE_FILE2(X) #X
Functions
if (argList::postProcess(argc, argv))
Detailed Description
Execute application functionObjects to post-process existing results.
Original source file postProcess.H
If the "dict" argument is specified the functionObjectList is constructed from that dictionary otherwise the functionObjectList is constructed from the "functions" sub-dictionary of "system/controlDict"
Multiple time-steps may be processed and the standard utility time controls are provided.
Definition in file postProcess.H.
Macro Definition Documentation
CREATE_TIME
#define CREATE_TIME createTime.H
Definition at line 36 of file postProcess.H.
CREATE_MESH
#define CREATE_MESH createMesh.H
Definition at line 40 of file postProcess.H.
CREATE_FIELDS
#define CREATE_FIELDS createFields.H
Definition at line 44 of file postProcess.H.
CREATE_CONTROL
#define CREATE_CONTROL createControl.H
Definition at line 48 of file postProcess.H.
INCLUDE_FILE
#define INCLUDE_FILE (X) INCLUDE_FILE2(X)
Definition at line 53 of file postProcess.H.
INCLUDE_FILE2
#define INCLUDE_FILE2 (X) #X
Definition at line 54 of file postProcess.H.
Function Documentation
if()
if (argList::postProcess(argc, argv))
Definition at line 64 of file postProcess.H.
References timeSelector::addOptions(), args, UPtrList< T >::end(), argList::executable(), FatalErrorIn, forAll, argList::found(), mesh, runTime, timeSelector::select0(), UList< T >::size(), and error::throwing().