OpenFOAM: applications/utilities/preProcessing/mapFieldsPar/createTimes.H File Reference
createTimes.H File Reference
Functions
Info<< "\nCreate databases as time"<< endl;HashTable< string > srcOptions (args.options())
srcOptions erase ("case")
srcOptions insert ("case", fileName(rootDirSource/caseDirSource))
argList argsSrc (args, srcOptions, false, false, false)
Time runTimeSource (Time::controlDictName, argsSrc)
Time runTimeTarget (Time::controlDictName, args)
Function Documentation
srcOptions()
Info<< "\nCreate databases as time"<< endl; HashTable< string > srcOptions (args. options())
erase()
srcOptions erase ("case")
Referenced by cellTable::combine(), edge::erase(), HashTable< T, Key, Hash >::erase(), HashPtrTable< T, Key, Hash >::erase(), edge::erase(), objectRegistry::erase(), HashTable< T, Key, Hash >::erase(), edge::erase(), HashTable< T, Key, Hash >::erase(), edge::erase(), IOobjectList::filterClasses(), HashTable< T, Key, Hash >::filterEntries(), HashTable< T, Key, Hash >::filterKeys(), IOobjectList::filterObjects(), HashTable< T, Key, Hash >::filterValues(), HashTable< T * >::merge(), HashTable< T * >::operator!=(), HashSet< labelPairPair >::operator[](), string::remove_ext(), string::remove_path(), string::removeEnd(), string::removeEnd(), string::removeRepeated(), string::removeStart(), string::removeStart(), string::replaceAny(), HashTable< T, Key, Hash >::retain(), and processorField::updateMesh().
insert()
srcOptions insert ("case" , fileName(rootDirSource/caseDirSource))
argsSrc()
argList argsSrc (args , srcOptions , false , false , false)
runTimeSource()
Time runTimeSource (Time::controlDictName , argsSrc)
Referenced by if().
runTimeTarget()
Time runTimeTarget (Time::controlDictName , args)