OpenFOAM: applications/solvers/multiphase/reactingMultiphaseEulerFoam/pU/UEqns.H File Reference
UEqns.H File Reference
Functions
Info<< "Constructing momentum equations"<< endl;PtrList< fvVectorMatrix > UEqns (phases.size())
phaseSystem::momentumTransferTable & momentumTransfer (momentumTransferPtr())
forAll (fluid.movingPhases(), movingPhasei)
Function Documentation
UEqns()
Info<< "Constructing momentum equations"<< endl;PtrList< fvVectorMatrix > UEqns (phases. size())
momentumTransfer()
phaseSystem::momentumTransferTable & momentumTransfer (momentumTransferPtr())
Referenced by forAll().
forAll()
forAll (fluid. movingPhases(), movingPhasei)
Definition at line 12 of file UEqns.H.
References alpha, fluid, fvOptions, momentumTransfer(), rho, List< T >::set(), U, and UEqns().