OpenFOAM: applications/solvers/multiphase/reactingMultiphaseEulerFoam/YEqns.H File Reference
YEqns.H File Reference
Functions
phaseSystem::massTransferTable & massTransfer (massTransferPtr())
forAll (fluid.multiComponentPhases(), multiComponentPhasei)
Function Documentation
massTransfer()
phaseSystem::massTransferTable & massTransfer (massTransferPtr())
Referenced by forAll(), if(), and if().
forAll()
forAll (fluid. multiComponentPhases(), multiComponentPhasei)
Definition at line 8 of file YEqns.H.
References alpha, fluid, forAll, fvOptions, massTransfer(), mesh, rho, and Y.