OpenFOAM: applications/solvers/combustion/chemFoam/readInitialConditions.H File Reference
readInitialConditions.H File Reference
Functions
word constProp (initialConditions.get< word >("constantProperty"))
if (constProp !="pressure" &&constProp !="volume")
word fractionBasis (initialConditions.get< word >("fractionBasis"))
if (fractionBasis !="mass" &&fractionBasis !="mole")
PtrList< gasHThermoPhysics > specieData (Y.size())
forAll (specieData, i)
scalarList Y0 (nSpecie, Zero)
scalarList X0 (nSpecie, Zero)
dictionary fractions (initialConditions.subDict("fractions"))
if (fractionBasis=="mole")
forAll (Y, i)
thermo he ()
thermo correct ()
Variables
label nSpecie = Y.size()
else
const scalar mTot = sum(Y0)
const scalar mw = 1.0/invW
scalar h0 = 0.0
rho = thermo.rho()
scalar rho0 = rho[0]
scalar u0 = h0 - p0/rho0
scalar R0 = p0/(rho0*T0)
Rspecific [0] = R0
scalar integratedHeat = 0.0
Function Documentation
constProp()
word constProp (initialConditions.get< word > "constantProperty")
Referenced by if().
if() [1/3]
if (constProp ! = "pressure" && constProp != "volume")
Definition at line 2 of file readInitialConditions.H.
References constProp().
fractionBasis()
word fractionBasis (initialConditions.get< word > "fractionBasis")
Referenced by if().
if() [2/3]
if (fractionBasis ! = "mass" && fractionBasis != "mole")
Definition at line 10 of file readInitialConditions.H.
References fractionBasis().
specieData()
PtrList< gasHThermoPhysics > specieData (Y. size())
Referenced by forAll(), forAll(), if(), and if().
forAll() [1/2]
forAll (specieData , i)
Definition at line 19 of file readInitialConditions.H.
References specieData().
Y0()
scalarList Y0 (nSpecie , Zero)
Referenced by forAll(), and if().
X0()
scalarList X0 (nSpecie , Zero)
Referenced by SprayParcel< ParcelType >::calc(), rigidBodyMotion::cCofR(), Grimshaw::eta(), McCowan::eta(), if(), rigidBodyMotion::status(), rigidBodyMotion::transformPoints(), rigidBodyMotion::transformPoints(), rigidBodyMotion::transformPoints(), Grimshaw::Uf(), and McCowan::Uf().
fractions()
dictionary fractions (initialConditions. subDict"fractions")
Referenced by if().
if() [3/3]
if (fractionBasis = = "mole")
Definition at line 36 of file readInitialConditions.H.
References forAll, fractions(), mTot, mw, specieData(), X0(), Y, and Y0().
forAll() [2/2]
forAll (Y , i)
Definition at line 65 of file readInitialConditions.H.
References mTot, specieData(), and Y0().
he()
thermo he ()
Definition at line 52 of file YEEqn.H.
Referenced by interRegionHeatTransferModel::addSup(), wallHeatFlux::calcHeatFlux(), limitTemperature::correct(), heThermo< BasicPsiThermo, MixtureType >::Cpv(), forAll(), OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), if(), if(), heatTransferCoeffModel::q(), reactingEulerHtcModel::q(), radiationModel::Sh(), thermo< Thermo, Type >::THE(), basicThermo::validate(), basicThermo::validate(), basicThermo::validate(), and basicThermo::validate().
correct()
thermo correct ()
Variable Documentation
nSpecie
label nSpecie = Y.size()
Definition at line 17 of file readInitialConditions.H.
Referenced by TDACChemistryModel< ReactionThermo, ThermoType >::derivatives(), TDACChemistryModel< ReactionThermo, ThermoType >::jacobian(), TDACChemistryModel< ReactionThermo, ThermoType >::solve(), EulerImplicit< ChemistryModel >::solve(), ode< ChemistryModel >::solve(), and specieReactionRates< ChemistryModelType >::write().
else
else
Initial value:
{
        forAll(Y, i)
        {
            fractions.readIfPresent(Y[i].name(), Y0[i]);
        }
        scalar invW = 0.0
Definition at line 56 of file readInitialConditions.H.
mTot
const scalar mTot = sum(Y0)
Definition at line 64 of file readInitialConditions.H.
Referenced by ORourkeCollision< CloudType >::collideSorted(), forAll(), and if().
mw
const scalar mw = 1.0/invW
Definition at line 70 of file readInitialConditions.H.
Referenced by if().
h0
scalar h0 = 0.0
Definition at line 78 of file readInitialConditions.H.
Referenced by filmTurbulenceModel::Cw().
rho
thermo rho = thermo.rho()
Definition at line 88 of file readInitialConditions.H.
Referenced by Foam::fvc::absolute(), ISAT< CompType, ThermoType >::add(), MRFZoneList::addAcceleration(), MRFZone::addCoriolis(), porosityModel::addResistance(), porosityModelList::addResistance(), atmAmbientTurbSource::addSup(), atmBuoyancyTurbSource::addSup(), atmLengthScaleTurbSource::addSup(), atmPlantCanopyTSource::addSup(), atmPlantCanopyTurbSource::addSup(), option::addSup(), buoyancyTurbSource::addSup(), option::addSup(), option::addSup(), option::addSup(), PhaseLimitStabilization< Type >::addSup(), atmCoriolisUSource::addSup(), atmPlantCanopyUSource::addSup(), option::addSup(), acousticDampingSource::addSup(), actuationDiskSource::addSup(), atmAmbientTurbSource::addSup(), atmBuoyancyTurbSource::addSup(), atmLengthScaleTurbSource::addSup(), atmPlantCanopyTSource::addSup(), atmPlantCanopyTurbSource::addSup(), buoyancyEnergy::addSup(), buoyancyTurbSource::addSup(), solidificationMeltingSource::addSup(), multiphaseMangrovesTurbulenceModel::addSup(), CodedSource< Type >::addSup(), SemiImplicitSource< Type >::addSup(), atmCoriolisUSource::addSup(), atmPlantCanopyUSource::addSup(), acousticDampingSource::addSup(), actuationDiskSource::addSup(), buoyancyForce::addSup(), fanMomentumSource::addSup(), radialActuationDiskSource::addSup(), rotorDiskSource::addSup(), tabulatedAccelerationSource::addSup(), interRegionExplicitPorositySource::addSup(), multiphaseMangrovesSource::addSup(), multiphaseStabilizedTurbulence::addSup(), constantDrift::addToDriftRate(), densityChangeDrift::addToDriftRate(), constantNucleation::addToNucleationRate(), wallBoiling::addToNucleationRate(), cellCoBlended< Type >::blendingFactor(), CoBlended< Type >::blendingFactor(), Implicit< CloudType >::cacheFields(), SprayParcel< ParcelType >::calc(), Foam::calc_pTotal(), Foam::calc_rhoU(), SprayParcel< ParcelType >::calcAtomization(), targetCoeffTrim::calcCoeffs(), powerLawLopesdaCosta::calcForce(), DarcyForchheimer::calcForce(), powerLaw::calcForce(), solidification::calcForce(), forces::calcForcesMoments(), ThermoParcel< ParcelType >::calcHeatTransfer(), ObukhovLength::calcOL(), ReactingParcel< ParcelType >::calcPhaseChange(), StandardChemistryModel< ReactionThermo, ThermoType >::calculate(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::calculate(), rotorDiskSource::calculate(), LiquidEvapFuchsKnudsen< CloudType >::calculate(), hydrostaticPressure::calculateAndWrite(), tabulatedNTUHeatTransfer::calculateHtc(), StandardChemistryModel< ReactionThermo, ThermoType >::calculateRR(), coalCloudList::coalCloudList(), Foam::constrainPressure(), Foam::constrainPressure(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), kL< BasicTurbulenceModel >::correct(), EDC< ReactionThermo >::correct(), eddyDissipationModelBase< ReactionThermo, ThermoType >::correct(), infinitelyFastChemistry< ReactionThermo, ThermoType >::correct(), PaSR< ReactionThermo >::correct(), kineticTheoryModel::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), SpalartAllmarasBase< BasicEddyViscosityModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), EBRSM< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::correct(), powerLawLopesdaCosta::correct(), DarcyForchheimer::correct(), fixedCoeff::correct(), powerLaw::correct(), solidification::correct(), Foam::MULES::correct(), Foam::MULES::correct(), Foam::MULES::correct(), Foam::MULES::correct(), Foam::MULES::correct(), relaxation::correct(), targetCoeffTrim::correct(), powerLawLopesdaCosta::correct(), DarcyForchheimer::correct(), fixedCoeff::correct(), powerLaw::correct(), solidification::correct(), powerLawLopesdaCosta::correct(), DarcyForchheimer::correct(), fixedCoeff::correct(), powerLaw::correct(), solidification::correct(), BrunDrippingInjection::correct(), curvatureSeparation::correct(), drippingInjection::correct(), patchInjection::correct(), directionalPressureGradientExplicitSource::correct(), standardPhaseChange::correctModel(), waxSolventEvaporation::correctModel(), Foam::CorrectPhi(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), Foam::fvc::correctRhoUf(), targetCoeffTrim::correctTrim(), Foam::correctUphiBCs(), perfectFluid< Specie >::CpMCv(), Foam::fac::d2dt2(), Foam::fam::d2dt2(), Foam::fac::d2dt2(), Foam::fam::d2dt2(), Foam::fvm::d2dt2(), Foam::fvc::d2dt2(), Foam::fvm::d2dt2(), Foam::fac::ddt(), Foam::fam::ddt(), Foam::fac::ddt(), Foam::fam::ddt(), Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::fvm::ddt(), Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::fvc::ddt(), Foam::fvm::ddt(), MRFZoneList::DDt(), Foam::fvc::ddtCorr(), Foam::fvc::ddtCorr(), Foam::fvc::ddtCorr(), StandardChemistryModel< ReactionThermo, ThermoType >::derivatives(), TDACChemistryModel< ReactionThermo, ThermoType >::derivatives(), forces::devRhoReff(), ReynoldsStress< BasicTurbulenceModel >::DivDevRhoReff(), incompressibleInterPhaseTransportModel< Mixture >::divDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), nonlinearEddyViscosity< BasicTurbulenceModel >::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), KinematicSurfaceFilm< CloudType >::drySplashInteraction(), Ea(), KinematicParcel< ParcelType >::Eo(), LaheyKEpsilon< BasicTurbulenceModel >::epsilonSource(), Es(), age::execute(), energyTransport::execute(), scalarTransport::execute(), Foam::MULES::explicitSolve(), Foam::MULES::explicitSolve(), Foam::MULES::explicitSolve(), Foam::MULES::explicitSolve(), Foam::MULES::explicitSolve(), EulerFaD2dt2Scheme< Type >::facD2dt2(), EulerFaD2dt2Scheme< Type >::facD2dt2(), boundedBackwardFaDdtScheme::facDdt(), backwardFaDdtScheme< Type >::facDdt(), EulerFaDdtScheme< Type >::facDdt(), steadyStateFaDdtScheme< Type >::facDdt(), boundedBackwardFaDdtScheme::facDdt(), backwardFaDdtScheme< Type >::facDdt(), EulerFaDdtScheme< Type >::facDdt(), steadyStateFaDdtScheme< Type >::facDdt(), boundedBackwardFaDdtScheme::facDdt0(), backwardFaDdtScheme< Type >::facDdt0(), EulerFaDdtScheme< Type >::facDdt0(), steadyStateFaDdtScheme< Type >::facDdt0(), boundedBackwardFaDdtScheme::facDdt0(), backwardFaDdtScheme< Type >::facDdt0(), EulerFaDdtScheme< Type >::facDdt0(), steadyStateFaDdtScheme< Type >::facDdt0(), EulerFaD2dt2Scheme< Type >::famD2dt2(), EulerFaD2dt2Scheme< Type >::famD2dt2(), boundedBackwardFaDdtScheme::famDdt(), backwardFaDdtScheme< Type >::famDdt(), EulerFaDdtScheme< Type >::famDdt(), steadyStateFaDdtScheme< Type >::famDdt(), boundedBackwardFaDdtScheme::famDdt(), backwardFaDdtScheme< Type >::famDdt(), EulerFaDdtScheme< Type >::famDdt(), steadyStateFaDdtScheme< Type >::famDdt(), PatchFlowRateInjection< CloudType >::flowRate(), for(), forAll(), forAll(), forAll(), forAll(), forAll(), forAllConstIters(), EulerD2dt2Scheme< Type >::fvcD2dt2(), steadyStateD2dt2Scheme< Type >::fvcD2dt2(), backwardDdtScheme< Type >::fvcDdt(), boundedDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), steadyStateDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), boundedDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), steadyStateDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), boundedDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), steadyStateDdtScheme< Type >::fvcDdt(), ddtScheme< Type >::fvcDdtPhiCoeff(), ddtScheme< Type >::fvcDdtPhiCoeff(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), boundedDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), steadyStateDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), boundedDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), steadyStateDdtScheme< Type >::fvcDdtUfCorr(), EulerD2dt2Scheme< Type >::fvmD2dt2(), steadyStateD2dt2Scheme< Type >::fvmD2dt2(), EulerD2dt2Scheme< Type >::fvmD2dt2(), steadyStateD2dt2Scheme< Type >::fvmD2dt2(), backwardDdtScheme< Type >::fvmDdt(), boundedDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), EulerDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), steadyStateDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), boundedDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), EulerDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), steadyStateDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), boundedDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), EulerDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), steadyStateDdtScheme< Type >::fvmDdt(), ddtScheme< Type >::fvmDdt(), icoTabulated< Specie >::H(), Ha(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), Hs(), ReynoldsAnalogy::htc(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), incompressibleInterPhaseTransportModel< Mixture >::incompressibleInterPhaseTransportModel(), Lee< Thermo, OtherThermo >::Kexp(), NicenoKEqn< BasicTurbulenceModel >::kSource(), LaheyKEpsilon< BasicTurbulenceModel >::kSource(), Lee< Thermo, OtherThermo >::KSp(), Lee< Thermo, OtherThermo >::KSu(), Foam::MULES::limit(), Foam::MULES::limit(), Foam::MULES::limitCorr(), PhiScheme< Type, PhiLimiter >::limiter(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), MRFZone::makeAbsolute(), MRFZoneList::makeAbsolute(), Foam::fvc::makeAbsolute(), Foam::fvc::makeAbsolute(), MRFZone::makeRelative(), MRFZoneList::makeRelative(), Foam::fvc::makeRelative(), Foam::fvc::makeRelative(), Foam::fvc::meshPhi(), Foam::fvc::meshPhi(), phasePair::Mo(), IATEsource::Mo(), fvMotionSolverEngineMesh::move(), layeredEngineMesh::move(), solidParticleCloud::move(), forces::mu(), PhaseIncompressibleTurbulenceModel< TransportModel >::New(), Foam::incompressible::New(), CompressibleTurbulenceModel< TransportModel >::New(), ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::New(), Foam::compressible::New(), multiphaseSystem::nu(), fluidThermo::nu(), multiphaseSystem::nu(), fluidThermo::nu(), continuousGasKEpsilon< BasicTurbulenceModel >::nuEff(), optionList::operator()(), optionList::operator()(), optionList::operator()(), rhoMagSqr< Type >::operator()(), optionList::operator()(), optionList::operator()(), optionList::operator()(), rhoMagSqr< Type >::operator()(), optionList::operator()(), optionList::operator()(), cloudInfo::performAction(), PhaseCompressibleTurbulenceModel< phaseModel >::PhaseCompressibleTurbulenceModel(), continuousGasKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), NicenoKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), continuousGasKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), LaheyKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), extractEulerianParticles::phiU(), InjectionModel< Foam::KinematicCloud< Foam::DSMCCloud > >::postInjectCheck(), kineticTheoryModel::pPrime(), pressureControl::pressureControl(), rPolynomial< Specie >::psi(), phaseChange::R(), wallBoiling::R(), KinematicParcel< ParcelType >::readFields(), KinematicParcel< ParcelType >::readObjects(), Foam::fvc::relative(), multiphaseSystem::rho(), multiphaseInterSystem::rho(), phaseSystem::rho(), ReynoldsAnalogy::rho(), forces::rho(), multiphaseSystem::rho(), multiphaseInterSystem::rho(), liquidMixtureProperties::rho(), CompositionModel< CloudType >::rho(), heThermo< BasicThermo, MixtureType >::rhoEoS(), ConeNozzleInjection< CloudType >::setProperties(), populationBalanceModel::solve(), StandardChemistryModel< ReactionThermo, ThermoType >::solve(), TDACChemistryModel< ReactionThermo, ThermoType >::solve(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), SprayParcel< ParcelType >::solveTABEq(), coalCloudList::Srho(), exponential::tau(), Lun::tau(), ParticleStressModel::tau(), StandardChemistryModel< ReactionThermo, ThermoType >::tc(), ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::ThermalDiffusivity(), MovingPhaseModel< BasePhaseModel >::UEqn(), MovingPhaseModel< BasePhaseModel >::UfEqn(), ETAB< CloudType >::update(), PilchErdman< CloudType >::update(), ReitzDiwakar< CloudType >::update(), ReitzKHRT< CloudType >::update(), SHF< CloudType >::update(), TAB< CloudType >::update(), BlobsSheetAtomization< CloudType >::update(), LISAAtomization< CloudType >::update(), matchedFlowRateOutletVelocityFvPatchVectorField::updateCoeffs(), pressurePIDControlInletVelocityFvPatchVectorField::updateCoeffs(), vibrationShellFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), outletMachNumberPressureFvPatchScalarField::updateCoeffs(), alphaFixedPressureFvPatchScalarField::updateCoeffs(), totalPressureFvPatchScalarField::updateCoeffs(), uniformTotalPressureFvPatchScalarField::updateCoeffs(), IATEsource::Ur(), KinematicSurfaceFilm< CloudType >::wetSplashInteraction(), while(), while(), while(), KinematicParcel< ParcelType >::writeFields(), KinematicParcel< ParcelType >::writeObjects(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::YiEqn().
rho0
scalar rho0 = rho[0]
Definition at line 89 of file readInitialConditions.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::calc(), ReactingParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calc(), if(), and Foam::operator<<().
u0
scalar u0 = h0 - p0/rho0
Definition at line 90 of file readInitialConditions.H.
Referenced by if(), and triangleFuncs::intersectAxesBundle().
R0
scalar R0 = p0/(rho0*T0)
Definition at line 91 of file readInitialConditions.H.
Rspecific
Rspecific[0] = R0
Definition at line 92 of file readInitialConditions.H.
Referenced by if().
integratedHeat
scalar integratedHeat = 0.0
Definition at line 94 of file readInitialConditions.H.
Referenced by if().