OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToGMV/readConversionProperties.H File Reference
readConversionProperties.H File Reference
Functions
IOdictionary conversionProperties (IOobject("conversionProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
scalar startTime (conversionProperties.get< scalar >("startTime"))
word vComp (conversionProperties.get< word >("vector"))
word format (conversionProperties.get< word >("format"))
if ((format !="ascii") &&(format !="ieeei4r8"))
word cells (conversionProperties.get< word >("cells"))
if ((cells !="hex"))
Function Documentation
conversionProperties()
IOdictionary conversionProperties (IOobject("conversionProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
startTime()
scalar startTime (conversionProperties.get< scalar > "startTime")
vComp()
word vComp (conversionProperties.get< word > "vector")
Referenced by for().
format()
word format (conversionProperties.get< word > "format")
Referenced by fileWriter::beginFieldData(), fileWriter::beginFile(), fileWriter::beginPoints(), UIPstreamBase::beginRawRead(), ISstream::beginRawRead(), UOPstreamBase::beginRawWrite(), OSstream::beginRawWrite(), OTstream::beginRawWrite(), fileWriter::endCellData(), fileWriter::endDataArray(), fileWriter::endFieldData(), fileWriter::endPiece(), fileWriter::endPointData(), fileWriter::endPoints(), fileWriter::enter_CellData(), fileWriter::enter_PointData(), fileWriter::exit_File(), if(), STLCore::isBinaryName(), ensightCase::newGeometry(), ensightFile::newline(), IOstream::print(), ensightCase::printInfo(), ensightReadFile::read(), ensightReadFile::read(), ensightReadFile::read(), masterUncollatedFileOperation::read(), uncollatedFileOperation::read(), ensightReadFile::read(), ensightReadFile::readBinaryHeader(), NASCore::setPrecision(), STLReader::STLReader(), UOPstreamBase::write(), OTstream::write(), internalWriter::write(), vtmWriter::write(), STLsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), VTPsurfaceFormat< Face >::write(), STLsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), VTPsurfaceFormat< Face >::write(), graph::write(), graph::write(), ensightFile::write(), patchWriter::write(), internalWriter::write(), patchWriter::write(), ensightFile::write(), ensightFile::write(), graph::write(), fileWriter::writeBasicField(), ensightFile::writeBinaryHeader(), internalMeshWriter::writeCellData(), VTKsurfaceFormatCore::writeCellData(), VTPsurfaceFormatCore::writeCellData(), VTKsurfaceFormatCore::writeCellData(), VTPsurfaceFormatCore::writeCellData(), internalMeshWriter::writeCellIDs(), NASCore::writeCoord(), nastranWriter::writeFaceValue(), vtkCloud::writeFields(), VTPsurfaceFormatCore::writeFooter(), lumpedPointMovement::writeForcesAndMomentsVTP(), surfaceFieldWriter::writeGeometry(), lagrangianWriter::writeGeometry(), internalMeshWriter::writeGeometry(), VTKsurfaceFormatCore::writeHeader(), VTPsurfaceFormatCore::writeHeader(), NASCore::writeKeyword(), patchMeshWriter::writeNeighIDs(), patchMeshWriter::writePatchIDs(), internalMeshWriter::writePointData(), internalMeshWriter::writePointIDs(), patchMeshWriter::writePoints(), Foam::vtk::writePointSet(), patchMeshWriter::writePolys(), patchMeshWriter::writePolysLegacy(), fileWriter::writeProcIDs(), ensightFile::writeString(), nastranWriter::writeTemplate(), fileWriter::writeTimeValue(), fileWriter::writeUniform(), and lumpedPointState::writeVTP().
if() [1/2]
if ((format !="ascii") &&(format !="ieeei4r8"))
Definition at line 29 of file readConversionProperties.H.
References format().
cells()
word cells (conversionProperties.get< word > "cells")
if() [2/2]
if ((cells !="hex"))
Definition at line 43 of file readConversionProperties.H.
References cells.