OpenFOAM: applications/solvers/stressAnalysis/solidDisplacementFoam/readMechanicalProperties.H File Reference
readMechanicalProperties.H File Reference
Functions
IOobject rhoIO ("rho", runTime.timeName(0), mesh, IOobject::NO_READ, IOobject::NO_WRITE)
if (rhoType=="uniform")
const dictionary & EDict (mechanicalProperties.subDict("E"))
word EType (EDict.get< word >("type"))
IOobject EHeader ("E", runTime.timeName(0), mesh, IOobject::NO_READ, IOobject::NO_WRITE)
if (EType=="uniform")
IOobject nuIO ("nu", runTime.timeName(0), mesh, IOobject::NO_READ, IOobject::NO_WRITE)
const dictionary & nuDict (mechanicalProperties.subDict("nu"))
word nuType (nuDict.get< word >("type"))
if (nuType=="uniform")
Variables
Info<< "Reading mechanical properties\n"<< endl;IOdictionary mechanicalProperties(IOobject("mechanicalProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));const dictionary &rhoDict(mechanicalProperties.subDict("rho"));word rhoType(rhoDict.get< word >("type"));autoPtr< volScalarField > rhoPtr
else
volScalarField & rho = rhoPtr()
autoPtr< volScalarField > EPtr
volScalarField & rhoE = EPtr()
autoPtr< volScalarField > nuPtr
volScalarField & nu = nuPtr()
Function Documentation
rhoIO()
IOobject rhoIO ("rho" , runTime. timeName0, mesh , IOobject::NO_READ , IOobject::NO_WRITE)
Referenced by if().
if() [1/3]
else if (rhoType = = "uniform")
Definition at line 29 of file readMechanicalProperties.H.
References mesh, rhoIO(), and rhoPtr.
EDict()
const dictionary & EDict (mechanicalProperties. subDict"E")
Referenced by if().
EType()
word EType (EDict.get< word > "type")
EHeader()
IOobject EHeader ("E" , runTime. timeName0, mesh , IOobject::NO_READ , IOobject::NO_WRITE)
Referenced by if().
if() [2/3]
else if (EType = = "uniform")
Definition at line 84 of file readMechanicalProperties.H.
References EDict(), EHeader(), EPtr, and mesh.
nuIO()
IOobject nuIO ("nu" , runTime. timeName0, mesh , IOobject::NO_READ , IOobject::NO_WRITE)
Referenced by if().
nuDict()
const dictionary & nuDict (mechanicalProperties. subDict"nu")
Referenced by if().
nuType()
word nuType (nuDict.get< word > "type")
if() [3/3]
else if (nuType = = "uniform")
Definition at line 139 of file readMechanicalProperties.H.
References mesh, nuDict(), nuIO(), and nuPtr.
Variable Documentation
rhoPtr
Info<< "Reading mechanical properties\n" << endl; IOdictionary mechanicalProperties (IOobject ("mechanicalProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE)); const dictionary& rhoDict(mechanicalProperties.subDict("rho")); word rhoType(rhoDict.get<word>("type")); autoPtr<volScalarField> rhoPtr
Definition at line 18 of file readMechanicalProperties.H.
Referenced by Foam::calc_pTotal(), Foam::calc_rhoU(), ObukhovLength::calcOL(), and if().
else
else
Initial value:
{
        FatalErrorInFunction
            << "Valid type entries are uniform or field for rho"
            << abort(FatalError)
Definition at line 61 of file readMechanicalProperties.H.
rho
volScalarField& rho = rhoPtr()
Definition at line 68 of file readMechanicalProperties.H.
EPtr
autoPtr<volScalarField> EPtr
Definition at line 73 of file readMechanicalProperties.H.
Referenced by if().
rhoE
volScalarField& rhoE = EPtr()
Definition at line 123 of file readMechanicalProperties.H.
nuPtr
autoPtr<volScalarField> nuPtr
Definition at line 125 of file readMechanicalProperties.H.
Referenced by if().
nu
volScalarField& nu = nuPtr()
Definition at line 176 of file readMechanicalProperties.H.
Referenced by ReactingHeterogeneousParcel< ParcelType >::calcHeterogeneousReactions(), ReactingMultiphaseParcel< ParcelType >::calcSurfaceReactions(), LiquidEvaporation< CloudType >::calculate(), LiquidEvaporationBoil< CloudType >::calculate(), LiquidEvapFuchsKnudsen< CloudType >::calculate(), MUCSheterogeneousRate< CloudType >::calculate(), SpalartAllmarasBase< BasicEddyViscosityModel >::chi(), ORourkeCollision< CloudType >::collideParcels(), EDC< ReactionThermo >::correct(), kkLOmega::correct(), qZeta::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), generalizedNewtonian< BasicMomentumTransportModel >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), DarcyForchheimer::correct(), DarcyForchheimer::correct(), limitTurbulenceViscosity::correct(), directionalPressureGradientExplicitSource::correct(), kOmegaSSTSato< BasicTurbulenceModel >::correctNut(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), KirchhoffShell::D(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::DepsilonEff(), LamBremhorstKE::DepsilonEff(), LienCubicKE::DepsilonEff(), LienLeschziner::DepsilonEff(), ShihQuadraticKE::DepsilonEff(), kEpsilon< BasicTurbulenceModel >::DepsilonEff(), kEpsilonPhitF< BasicTurbulenceModel >::DepsilonEff(), LaunderSharmaKE< BasicTurbulenceModel >::DepsilonEff(), LRR< BasicTurbulenceModel >::DepsilonEff(), realizableKE< BasicTurbulenceModel >::DepsilonEff(), RNGkEpsilon< BasicTurbulenceModel >::DepsilonEff(), SSG< BasicTurbulenceModel >::DepsilonEff(), ReynoldsAnalogy::devReff(), filmTurbulenceModel::devRhoReff(), forces::devRhoReff(), kOmegaSSTLM< BasicTurbulenceModel >::DgammaIntEff(), ReynoldsStress< BasicTurbulenceModel >::DivDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::DkEff(), kL< BasicTurbulenceModel >::DkEff(), LamBremhorstKE::DkEff(), LienCubicKE::DkEff(), LienLeschziner::DkEff(), ShihQuadraticKE::DkEff(), dynamicKEqn< BasicTurbulenceModel >::DkEff(), dynamicLagrangian< BasicTurbulenceModel >::DkEff(), kEqn< BasicTurbulenceModel >::DkEff(), kEpsilon< BasicTurbulenceModel >::DkEff(), kEpsilonPhitF< BasicTurbulenceModel >::DkEff(), kOmega< BasicTurbulenceModel >::DkEff(), LaunderSharmaKE< BasicTurbulenceModel >::DkEff(), realizableKE< BasicTurbulenceModel >::DkEff(), RNGkEpsilon< BasicTurbulenceModel >::DkEff(), kkLOmega::DkEff(), kOmegaSSTBase< BasicEddyViscosityModel >::DkEff(), kOmega< BasicTurbulenceModel >::DomegaEff(), kkLOmega::DomegaEff(), kOmegaSSTBase< BasicEddyViscosityModel >::DomegaEff(), kEpsilonPhitF< BasicTurbulenceModel >::DphitEff(), qZeta::DqEff(), LRR< BasicTurbulenceModel >::DREff(), SSG< BasicTurbulenceModel >::DREff(), kOmegaSSTLM< BasicTurbulenceModel >::DReThetatEff(), qZeta::DzetaEff(), LienCubicKE::E(), LienLeschziner::E(), CelikNuIndex::execute(), kOmegaSSTLM< BasicTurbulenceModel >::F1(), LienCubicKE::f2(), LienLeschziner::f2(), qZeta::f2(), LaunderSharmaKE< BasicTurbulenceModel >::f2(), kOmegaSSTLM< BasicTurbulenceModel >::Flength(), LienCubicKE::fMu(), LienLeschziner::fMu(), qZeta::fMu(), LaunderSharmaKE< BasicTurbulenceModel >::fMu(), interfaceTrackingFvMesh::freeSurfacePressureJump(), interfaceTrackingFvMesh::freeSurfaceSnGradU(), kOmegaSSTLM< BasicTurbulenceModel >::Fthetat(), boundaryAdjointContributionIncompressible::laminarDiffusivity(), kEpsilonPhitF< BasicTurbulenceModel >::Ls(), adjointWallVelocityFvPatchVectorField::manipulateMatrix(), phasePair::Mo(), IATEsource::Mo(), solidParticleCloud::move(), forces::mu(), incompressibleRhoTurbulenceModel::mu(), incompressibleTurbulenceModel::mu(), incompressibleRhoTurbulenceModel::mu(), incompressibleTurbulenceModel::mu(), multiphaseInterSystem::nu(), multiphaseInterSystem::nu(), Maxwell< BasicTurbulenceModel >::nu0(), continuousGasKEpsilon< BasicTurbulenceModel >::nuEff(), laminarModel< BasicTurbulenceModel >::nuEff(), Stokes< BasicTurbulenceModel >::nuEff(), LESModel< BasicTurbulenceModel >::nuEff(), RASModel< BasicTurbulenceModel >::nuEff(), SpalartAllmaras::nutJacobianVar1(), PairSpringSliderDashpot< CloudType >::PairSpringSliderDashpot(), IATEsource::Re(), kOmegaSSTLM< BasicTurbulenceModel >::ReThetat0(), kEpsilonPhitF< BasicTurbulenceModel >::Ts(), LISAAtomization< CloudType >::update(), JohnsonJacksonParticleSlipFvPatchVectorField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), and WallSpringSliderDashpot< CloudType >::WallSpringSliderDashpot().