OpenFOAM: applications/solvers/stressAnalysis/solidDisplacementFoam/readThermalProperties.H File Reference
readThermalProperties.H File Reference
Functions
IOobject CIO ("C", runTime.timeName(0), mesh, IOobject::NO_READ, IOobject::NO_WRITE)
const dictionary & CDict (thermalProperties.subDict("C"))
word CType (CDict.get< word >("type"))
if (CType=="uniform")
IOobject rhoKIO ("k", runTime.timeName(0), mesh, IOobject::NO_READ, IOobject::NO_WRITE)
const dictionary & kDict (thermalProperties.subDict("k"))
word kType (kDict.get< word >("type"))
if (kType=="uniform")
IOobject alphaIO ("alpha", runTime.timeName(0), mesh, IOobject::NO_READ, IOobject::NO_WRITE)
const dictionary & alphaDict (thermalProperties.subDict("alpha"))
word alphaType (alphaDict.get< word >("type"))
if (alphaType=="uniform")
Variables
Info<< "Reading thermal properties\n"<< endl;IOdictionary thermalProperties(IOobject("thermalProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));bool thermalStress(thermalProperties.get< bool >("thermalStress"));volScalarField threeKalpha(IOobject("threeKalpha", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar(dimensionSet(0, 2, -2, -1, 0), Zero));volScalarField DT(IOobject("DT", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar(dimensionSet(0, 2, -1, 0, 0), Zero));if(thermalStress){ autoPtr< volScalarField > CPtr
else
volScalarField & C = CPtr()
autoPtr< volScalarField > rhoKPtr
volScalarField & rhoK = rhoKPtr()
autoPtr< volScalarField > alphaPtr
volScalarField & alpha = alphaPtr()
Function Documentation
CIO()
IOobject CIO ("C" , runTime. timeName0, mesh , IOobject::NO_READ , IOobject::NO_WRITE)
Referenced by if().
CDict()
const dictionary & CDict (thermalProperties. subDict"C")
Referenced by if().
CType()
word CType (CDict.get< word > "type")
if() [1/3]
else if (CType = = "uniform")
Definition at line 62 of file readThermalProperties.H.
References CDict(), CIO(), CPtr, and mesh.
rhoKIO()
IOobject rhoKIO ("k" , runTime. timeName0, mesh , IOobject::NO_READ , IOobject::NO_WRITE)
Referenced by if().
kDict()
const dictionary & kDict (thermalProperties. subDict"k")
Referenced by if().
kType()
word kType (kDict.get< word > "type")
if() [2/3]
else if (kType = = "uniform")
Definition at line 117 of file readThermalProperties.H.
References kDict(), mesh, rhoKIO(), and rhoKPtr.
alphaIO()
IOobject alphaIO ("alpha" , runTime. timeName0, mesh , IOobject::NO_READ , IOobject::NO_WRITE)
Referenced by if().
alphaDict()
const dictionary & alphaDict (thermalProperties. subDict"alpha")
Referenced by if().
alphaType()
word alphaType (alphaDict.get< word > "type")
if() [3/3]
else if (alphaType = = "uniform")
Definition at line 174 of file readThermalProperties.H.
References alphaDict(), alphaIO(), alphaPtr, and mesh.
Variable Documentation
CPtr
Info<< "Reading thermal properties\n" << endl;IOdictionary thermalProperties(IOobject ("thermalProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));bool thermalStress(thermalProperties.get<bool>("thermalStress"));volScalarField threeKalpha(IOobject ("threeKalpha", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar(dimensionSet(0, 2, -2 , -1, 0), Zero));volScalarField DT(IOobject ("DT", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar(dimensionSet(0, 2, -1 , 0, 0), Zero));if (thermalStress){ autoPtr<volScalarField> CPtr
Definition at line 49 of file readThermalProperties.H.
Referenced by if().
else
else
Initial value:
{
        FatalErrorInFunction
            << "Valid type entries are uniform or field for C"
            << abort(FatalError)
Definition at line 95 of file readThermalProperties.H.
C
volScalarField& C = CPtr()
Definition at line 102 of file readThermalProperties.H.
rhoKPtr
autoPtr<volScalarField> rhoKPtr
Definition at line 104 of file readThermalProperties.H.
Referenced by if().
rhoK
volScalarField& rhoK = rhoKPtr()
Definition at line 157 of file readThermalProperties.H.
alphaPtr
autoPtr<volScalarField> alphaPtr
Definition at line 159 of file readThermalProperties.H.
Referenced by if().
alpha
volScalarField& alpha = alphaPtr()
Definition at line 212 of file readThermalProperties.H.
Referenced by scene::addColourToMesh(), atmAmbientTurbSource::addSup(), atmBuoyancyTurbSource::addSup(), atmLengthScaleTurbSource::addSup(), atmPlantCanopyTSource::addSup(), atmPlantCanopyTurbSource::addSup(), option::addSup(), buoyancyTurbSource::addSup(), option::addSup(), option::addSup(), option::addSup(), PhaseLimitStabilization< Type >::addSup(), atmCoriolisUSource::addSup(), atmPlantCanopyUSource::addSup(), option::addSup(), acousticDampingSource::addSup(), actuationDiskSource::addSup(), explicitPorositySource::addSup(), Foam::fvc::alphaCorr(), multiphaseInterSystem::alphaEff(), multiphaseInterSystem::alphaEff(), multiphaseInterSystem::alphaEff(), phaseModel::alphaEff(), multiphaseInterSystem::alphaEff(), phaseModel::alphaEff(), InterfaceForce< CloudType >::cacheFields(), BrownianMotionForce< CloudType >::calcCoupled(), wallHeatFlux::calcHeatFlux(), MUCSheterogeneousRate< CloudType >::calculate(), pointMVCWeight::calcWeights(), lookupProfile::Cdl(), seriesProfile::Cdl(), TrajectoryCollision< CloudType >::collideParcels(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), kL< BasicTurbulenceModel >::correct(), kineticTheoryModel::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), SpalartAllmarasBase< BasicEddyViscosityModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), EBRSM< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::correct(), contactAngleForce::correct(), thixotropicViscosity::correct(), contactAngleForce::correct(), thermocapillaryForce::correct(), solidification::correctModel(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), PengRobinsonGas< Specie >::Cp(), PengRobinsonGas< Specie >::CpMCv(), Foam::fvm::ddt(), Foam::fvc::ddt(), Foam::fvm::ddt(), MomentumTransferPhaseSystem< BasePhaseSystem >::ddtCorrByAs(), exponential::dTaudTheta(), HarrisCrighton::dTaudTheta(), SpalartAllmarasIDDES< BasicTurbulenceModel >::dTilda(), kOmegaSSTIDDES< BasicTurbulenceModel >::dTilda(), PengRobinsonGas< Specie >::E(), effectivenessTable::energyDensity(), LaheyKEpsilon< BasicTurbulenceModel >::epsilonSource(), thermo::evolveRegion(), extractEulerianParticles::execute(), scalarTransport::execute(), kOmegaSSTIDDES< BasicTurbulenceModel >::fd(), SpalartAllmarasIDDES< BasicTurbulenceModel >::fd(), for(), for(), forAll(), forAll(), forAll(), forAll(), JohnsonJackson::frictionalPressure(), JohnsonJacksonSchaeffer::frictionalPressure(), Schaeffer::frictionalPressure(), JohnsonJackson::frictionalPressurePrime(), JohnsonJacksonSchaeffer::frictionalPressurePrime(), Schaeffer::frictionalPressurePrime(), backwardDdtScheme< Type >::fvcDdt(), boundedDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), steadyStateDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvmDdt(), boundedDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), EulerDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), steadyStateDdtScheme< Type >::fvmDdt(), ddtScheme< Type >::fvmDdt(), CarnahanStarling::g0(), LunSavage::g0(), SinclairJackson::g0(), CarnahanStarling::g0prime(), LunSavage::g0prime(), SinclairJackson::g0prime(), PengRobinsonGas< Specie >::H(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), if(), Foam::Math::incGammaRatio_Q(), KinematicCloud< CloudType >::info(), MPPICCloud< CloudType >::info(), triangleFuncs::intersectAxesBundle(), NicenoKEqn< BasicTurbulenceModel >::kSource(), LaheyKEpsilon< BasicTurbulenceModel >::kSource(), JohnsonJacksonSchaeffer::nu(), Schaeffer::nu(), equilibrium::oneByTau(), isotropic::oneByTau(), nonEquilibrium::oneByTau(), optionList::operator()(), optionList::operator()(), optionList::operator()(), SprayCloud< CloudType >::penetration(), PhaseCompressibleTurbulenceModel< phaseModel >::PhaseCompressibleTurbulenceModel(), continuousGasKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), NicenoKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), continuousGasKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), LaheyKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), ParticleErosion< CloudType >::postPatch(), ParticleTrap< CloudType >::preEvolve(), heatTransferCoeffModel::q(), reactingEulerHtcModel::q(), cutFaceAdvect::quadAreaCoeffs(), randomCoalescence::R(), randomCoalescence::R(), faMatrix< Type >::relax(), fvMatrix< Type >::relax(), GeometricField< Type, PatchField, GeoMesh >::relax(), lumpedPointState::relax(), phaseSystem::rho(), KinematicCloud< Foam::DSMCCloud >::rhoEff(), general::sample(), FPCG::scalarSolve(), PBiCGStab::scalarSolve(), PCG::scalarSolve(), PPCG::scalarSolveCG(), shallowWaterAbsorption::setAlpha(), ConeInjection< CloudType >::setProperties(), ConeNozzleInjection< CloudType >::setProperties(), constantRadiation::Shs(), primaryRadiation::Shs(), standardRadiation::Shs(), multiphaseSystem::solve(), populationBalanceModel::solve(), QRMatrix< MatrixType >::solve(), PBiCCCG< Type, DType, LUType >::solve(), PBiCICG< Type, DType, LUType >::solve(), PCICG< Type, DType, LUType >::solve(), PBiCG::solve(), multiphaseSystem::solveAlphas(), reactingOneDim::solveEnergy(), thermalBaffle::solveEnergy(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi(), KinematicSurfaceFilm< CloudType >::splashDirection(), Foam::fvc::spread(), Foam::fvc::sweep(), exponential::tau(), HarrisCrighton::tau(), Lun::tau(), ParticleStressModel::tau(), ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::ThermalDiffusivity(), cutFaceAdvect::timeIntegratedArea(), cutFaceAdvect::timeIntegratedArea(), phaseSystem::U(), MovingPhaseModel< BasePhaseModel >::UEqn(), MovingPhaseModel< BasePhaseModel >::UfEqn(), advectiveFvPatchField< Type >::updateCoeffs(), fixedMultiPhaseHeatFluxFvPatchScalarField::updateCoeffs(), JohnsonJacksonParticleSlipFvPatchVectorField::updateCoeffs(), JohnsonJacksonParticleThetaFvPatchScalarField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), humidityTemperatureCoupledMixedFvPatchScalarField::updateCoeffs(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), reconstructedDistanceFunction::updateContactAngle(), Explicit< CloudType >::velocityCorrection(), cuttingSurfaceBase::walkCellCuts(), waveModel::waterLevel(), while(), while(), regionSizeDistribution::write(), sizeDistribution::write(), FacePostProcessing< CloudType >::write(), ParticleCollector< CloudType >::write(), gltfWriter::writeTemplate(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::YiEqn(), and PengRobinsonGas< Specie >::Z().