OpenFOAM: applications/utilities/mesh/conversion/kivaToFoam/readKivaGrid.H File Reference
readKivaGrid.H File Reference
Functions
std::ifstream kivaFile (kivaFileName)
if (!kivaFile.good())
pointField points (nPoints)
labelList idface (nPoints)
labelList fv (nPoints)
for (label i=0;i< nPoints;i++)
labelList i1tab (nPoints)
labelList i3tab (nPoints)
labelList i8tab (nPoints)
labelList idreg (nPoints)
labelList f (nPoints)
labelList bcl (nPoints)
labelList bcf (nPoints)
labelList bcb (nPoints)
if (mTable==0)
labelList imtab (nPoints)
labelList jmtab (nPoints)
labelList kmtab (nPoints)
face quadFace (4)
face triFace (3)
if (pFaces[LINER].size() &&pFaces[LINER][0].size() &&pFaces[CYLINDERHEAD].size() &&pFaces[CYLINDERHEAD][0].size())
if (pFaces[WEDGE].size() &&pFaces[WEDGE][0].size())
faceListList boundary (nPatches)
wordList patchNames (nPatches)
wordList patchTypes (nPatches)
labelList pointLabels (nPoints, -1)
forAll (cellShapes, celli)
forAll (pointLabels, pointi)
points setSize (newPointi)
forAll (boundary, patchi)
preservePatchTypes (runTime, runTime.constant(), polyMesh::meshSubDir, patchNames, patchDicts, defaultFacesName, defaultFacesType)
forAll (patchNames, patchi)
polyMesh pShapeMesh (IOobject(polyMesh::defaultRegion, runTime.constant(), runTime), std::move(points), cellShapes, boundary, patchNames, patchDicts, defaultFacesName, defaultFacesType)
Variables
Info<< "Reading kiva grid from file "<< kivaFileName<< endl;char title[120];kivaFile.getline(title, 120, '\n');label nPoints, nCells, nRegs;kivaFile > nCells nPoints nRegs
label i4
label mTable
Info<< "Finished reading KIVA file"<< endl;cellShapeList cellShapes(nPoints);labelList cellZoning(nPoints, -1);const cellModel &hex=cellModel::ref(cellModel::HEX);labelList hexLabels(8);label activeCells=0;labelList pointMap(nPoints);forAll(pointMap, i){ pointMap[i]=i;}for(label i=0;i< nPoints;i++){ if(f[i] > 0.0) { hexLabels[0]=i;hexLabels[1]=i1tab[i];hexLabels[2]=i3tab[i1tab[i]];hexLabels[3]=i3tab[i];hexLabels[4]=i8tab[i];hexLabels[5]=i1tab[i8tab[i]];hexLabels[6]=i3tab[i1tab[i8tab[i]]];hexLabels[7]=i3tab[i8tab[i]];cellShapes[activeCells].reset(hex, hexLabels);edgeList edges=cellShapes[activeCells].edges();forAll(edges, ei) { if(edges[ei].mag(points)< SMALL) { label start=pointMap[edges[ei].start()];while(start !=pointMap[start]) { start=pointMap[start];} label end=pointMap[edges[ei].end()];while(end !=pointMap[end]) { end=pointMap[end];} label minLabel=min(start, end);pointMap[start]=pointMap[end]=minLabel;} } cellZoning[activeCells]=idreg[i];activeCells++;}}cellShapes.setSize(activeCells);cellZoning.setSize(activeCells);forAll(cellShapes, celli){ cellShape &cs=cellShapes[celli];forAll(cs, i) { cs[i]=pointMap[cs[i]];} cs.collapse();}label bcIDs[11]={-1, 0, 2, 4, -1, 5, -1, 6, 7, 8, 9};const label nBCs=12;const word *kivaPatchTypes[nBCs]={ &wallPolyPatch::typeName, &wallPolyPatch::typeName, &wallPolyPatch::typeName, &wallPolyPatch::typeName, &symmetryPolyPatch::typeName, &wedgePolyPatch::typeName, &polyPatch::typeName, &polyPatch::typeName, &polyPatch::typeName, &polyPatch::typeName, &symmetryPolyPatch::typeName, &oldCyclicPolyPatch::typeName};enum patchTypeNames{ PISTON, VALVE, LINER, CYLINDERHEAD, AXIS, WEDGE, INFLOW, OUTFLOW, PRESIN, PRESOUT, SYMMETRYPLANE, CYCLIC};const char *kivaPatchNames[nBCs]={ "piston", "valve", "liner", "cylinderHead", "axis", "wedge", "inflow", "outflow", "presin", "presout", "symmetryPlane", "cyclic"};List< SLList< face > > pFaces [nBCs]
label nPatches = 0
word defaultFacesName = "defaultFaces"
word defaultFacesType = emptyPolyPatch::typeName
label nAddedPatches = 0
label newPointi = 0
PtrList< dictionary > patchDicts
Function Documentation
kivaFile()
std::ifstream kivaFile (kivaFileName)
Referenced by for().
if() [1/4]
if (!kivaFile. good())
Definition at line 3 of file readKivaGrid.H.
References FatalErrorInFunction.
points()
pointField points (nPoints)
idface()
labelList idface (nPoints)
Referenced by for(), and if().
fv()
labelList fv (nPoints)
Referenced by acousticDampingSource::acousticDampingSource(), actuationDiskSource::actuationDiskSource(), atmBuoyancyTurbSource::atmBuoyancyTurbSource(), atmCoriolisUSource::atmCoriolisUSource(), atmLengthScaleTurbSource::atmLengthScaleTurbSource(), atmPlantCanopyTurbSource::atmPlantCanopyTurbSource(), atmPlantCanopyUSource::atmPlantCanopyUSource(), boundedConvectionScheme< Type >::boundedConvectionScheme(), boundedDdtScheme< Type >::boundedDdtScheme(), buoyancyTurbSource::buoyancyTurbSource(), cellLimitedGrad< Type, Limiter >::cellLimitedGrad(), cellMDLimitedGrad< Type >::cellMDLimitedGrad(), cellSetOption::cellSetOption(), kkLOmega::correct(), directionalPressureGradientExplicitSource::directionalPressureGradientExplicitSource(), faceLimitedGrad< Type >::faceLimitedGrad(), faceMDLimitedGrad< Type >::faceMDLimitedGrad(), fanMomentumSource::fanMomentumSource(), for(), if(), jouleHeatingSource::jouleHeatingSource(), limitTemperature::limitTemperature(), limitTurbulenceViscosity::limitTurbulenceViscosity(), limitVelocity::limitVelocity(), linearUpwindNormal< Type >::linearUpwindNormal(), linearUpwindNormal< Type >::linearUpwindNormal(), linearUpwindNormal< Type >::linearUpwindNormal(), linearUpwindV< Type >::linearUpwindV(), linearUpwindV< Type >::linearUpwindV(), linearUpwindV< Type >::linearUpwindV(), meanVelocityForce::meanVelocityForce(), multiphaseMangrovesSource::multiphaseMangrovesSource(), multiphaseMangrovesTurbulenceModel::multiphaseMangrovesTurbulenceModel(), optionList::optionList(), optionList::optionList(), rotorDiskSource::rotorDiskSource(), solidificationMeltingSource::solidificationMeltingSource(), velocityDampingConstraint::velocityDampingConstraint(), and viscousDissipation::viscousDissipation().
for()
for ()
Definition at line 23 of file readKivaGrid.H.
References fv(), i4, idface(), kivaFile(), and points.
i1tab()
labelList i1tab (nPoints)
i3tab()
labelList i3tab (nPoints)
i8tab()
labelList i8tab (nPoints)
idreg()
labelList idreg (nPoints)
f()
labelList f (nPoints)
Referenced by oversetFvMeshBase::active(), isoSurfacePoint::adaptPatchFields(), multivariateSurfaceInterpolationScheme< Type >::fieldTable::add(), singleProcessorFaceSets::add(), polyMeshAdder::add(), vtmWriter::add(), polyTopoChange::addFace(), oversetFvMeshBase::addInterpolation(), forces::addToInternalField(), unwatchedIOdictionary::addWatch(), regIOobject::addWatch(), unwatchedIOdictionary::addWatch(), regIOobject::addWatch(), fileOperation::addWatches(), masterUncollatedFileOperation::addWatches(), polyMeshTetDecomposition::adjustTetBasePtIs(), singleProcessorFaceSets::apply(), Field< T >::assign(), Field< T >::assign(), fvPatchField< Type >::autoMap(), Foam::average(), averageNeighbourFvGeometryScheme::averageCentres(), patchMeshWriter::beginPiece(), booleanSurface::booleanSurface(), primitiveMeshTools::boundaryFaceSkewness(), searchableBox::boundingSpheres(), triSurfaceMesh::boundingSpheres(), PrimitivePatch< FaceList, PointField >::box(), treeDataPrimitivePatch< PatchType >::boxes(), nearWallFields::calcAddressing(), PatchTools::calcBounds(), holeToFace::calcClosure(), BrownianMotionForce< CloudType >::calcCoupled(), cellMatcher::calcEdgeAddressing(), coupledPolyPatch::calcFaceTol(), triSurfaceTools::calcInterpolationWeights(), cellMatcher::calcLocalFaces(), cellMatcher::calcPointFaceIndex(), primitiveMesh::calcPointOrder(), createShellMesh::calcPointRegions(), cutFaceAdvect::calcSubFace(), cutFace::calcSubFace(), cutFaceAdvect::calcSubFace(), cutFaceIso::calcSubFace(), cutFace::calcSubFace(), cutFace::calcSubFace(), cutFaceAdvect::calcSubFace(), cutFacePLIC::calcSubFace(), rotorDiskSource::calculate(), MUCSheterogeneousRate< CloudType >::calculate(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), pointMVCWeight::calcWeights(), pointMVCWeight::calcWeights(), cellMatcher::cellMatcher(), cellModel::centre(), cell::centre(), repatchPolyTopoChanger::changeAnchorPoint(), primitiveMesh::checkCellsZipUp(), polyMeshGeometry::checkEdgeLength(), primitiveMesh::checkEdgeLength(), polyMeshGeometry::checkFaceAngles(), primitiveMeshGeometry::checkFaceAngles(), polyMeshGeometry::checkFaceFlatness(), polyMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFacePyramids(), primitiveMesh::checkFacePyramids(), MeshedSurface< Face >::checkFaces(), Foam::checkFaceSizeMatch(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), primitiveMeshGeometry::checkFaceTwist(), primitiveMesh::checkFaceVertices(), Foam::checkFireEdges(), hexRef8::checkMesh(), edgeCollapser::checkMeshQuality(), PatchTools::checkOrientation(), searchableSurfaces::checkQuality(), triSurface::checkTriangles(), polyMeshGeometry::checkTriangleTwist(), TomiyamaLift::Cl(), averageNeighbourFvGeometryScheme::clipFaceTet(), Foam::cmptAv(), Foam::cmptAv(), Foam::cmptMag(), Foam::cmptMag(), Foam::cmptMax(), Foam::cmptMax(), Foam::cmptMin(), Foam::cmptMin(), cellShape::collapsedFaces(), triSurfaceTools::collapseEdges(), ORourkeCollision< CloudType >::collideSorted(), triSurface::compactPoints(), Foam::component(), Foam::component(), Foam::component(), processorLduInterface::compressedReceive(), processorLduInterface::compressedSend(), edgeCollapser::consistentCollapse(), inversePointDistanceDiffusivity::correct(), CentredFitScheme< Type, Polynomial, Stencil >::correction(), pointLinear< Type >::correction(), Foam::countConnectivity(), removePoints::countPointUsage(), wallBoundedParticle::crossDiagonalEdge(), wallBoundedParticle::crossEdgeConnectedFace(), wallBoundedParticle::crossEdgeConnectedFace(), STARCDMeshReader::cullPoints(), wallBoundedParticle::currentEdge(), triSurfaceTools::curvatures(), cutFaceAdvect::cutPoints(), cutFaceAdvect::cutPoints(), decompositionMethod::decompose(), meshRefinement::doSplitFaces(), meshRefinement::dupNonManifoldBoundaryPoints(), primitiveMesh::edgeFaces(), PatchTools::edgeOwner(), directionInfo::edgeToFaceIndex(), directionInfo::enterDomain(), turbulenceFields::execute(), multiRegion::execute(), hexCell::face(), Patch::faceCentres(), primitiveMeshTools::faceConcavity(), ABAQUSCore::faceDecomposition(), NASCore::faceDecomposition(), primitiveMesh::faceEdges(), primitiveMesh::faceEdges(), primitiveMeshTools::faceFlatness(), hexRef8::faceLevel(), Patch::faceNormals(), mappedPatchBase::facePoint(), primitiveMeshTools::facePyramidVolume(), hexCell::faces(), Foam::vtk::Tools::Faces(), primitiveMeshTools::faceSkewness(), polyMeshTetDecomposition::faceTetIndices(), faceTriangulation::faceTriangulation(), faceTriangulation::faceTriangulation(), tetIndices::faceTriIs(), boundaryDataSurfaceReader::fieldNames(), fieldSelection::filters(), polyMeshTetDecomposition::findBasePoint(), localPointRegion::findDuplicateFaces(), patchProbes::findElements(), treeDataPrimitivePatch< PatchType >::findIntersection(), treeDataFace::findNearest(), treeDataPrimitivePatch< PatchType >::findNearest(), meshSearch::findNearestBoundaryFace(), wallBoundedStreamLine::findNearestTet(), sampledSet::findNearFace(), polyMeshTetDecomposition::findSharedBasePoint(), polyMeshTetDecomposition::findTet(), ISstream::flags(), OSstream::flags(), for(), forAll(), pairPotentialList::force(), pairPotential::force(), noiseFFT::frequencies(), noiseModel::gainA(), noiseModel::gainB(), noiseModel::gainC(), noiseModel::gainD(), PatchTools::gatherAndMerge(), PatchTools::gatherAndMerge(), Foam::gAverage(), isoSurfacePoint::generateFaceTriPoints(), coupledPolyPatch::getAnchorPoints(), Foam::getBoundedColours(), isoSurfaceBase::getCellCutType(), snappySnapDriver::getFacePoints(), Foam::ensightOutput::Detail::getFaceSizes(), Foam::ensightOutput::Detail::getFaceSizes(), surfaceSets::getHangingCells(), edgeFaceCirculator::getMinIndex(), boundaryMesh::getNearest(), boundaryMesh::getNTris(), cellDistFuncs::getPointNeighbours(), Foam::ensightOutput::Detail::getPolysFacePoints(), coupledPolyPatch::getRotation(), hexRef8::getSplitPoints(), treeDataFace::getVolumeType(), treeDataPrimitivePatch< PatchType >::getVolumeType(), wallBoundedParticle::hitProcessorPatch(), FreeStream< CloudType >::inflow(), dynamicRefineFvMesh::init(), turbulenceFields::initialise(), waveModel::initialiseGeometry(), streamLineBase::initInterpolations(), processorPolyPatch::initUpdateMesh(), patchTransformedInterpolation::interpolate(), cellCellStencil::interpolate(), blendedInterfacialModel::interpolate(), meshToMesh0::interpolateField(), meshToMesh0::interpolateField(), Foam::interpolatePointToCell(), meshRefinement::intersectedPoints(), face::intersection(), fileOperation::isFileOrDir(), isoSurfacePoint::isoSurfacePoint(), isoSurfaceTopo::isoSurfaceTopo(), triSurfaceMesh::isSurfaceClosed(), Foam::levelSetFraction(), triSurfaceLoader::load(), Foam::mag(), cellModel::mag(), cell::mag(), Foam::mag(), Foam::magSqr(), Foam::magSqr(), highAspectRatioFvGeometryScheme::makeAverageCentres(), stabilisedFvGeometryScheme::makeFaceCentresAndAreas(), primitiveMeshTools::makeFaceCentresAndAreas(), Field< T >::map(), Field< T >::map(), Field< T >::map(), Field< Type >::map(), edgeCollapser::markFaceZoneEdges(), edgeCollapser::markSmallSliverFaces(), momentOfInertia::massPropertiesPatch(), CollisionRecordList< vector, vector >::matchPairRecord(), CollisionRecordList< vector, vector >::matchWallRecord(), Foam::max(), noiseFFT::meanPf(), propellerInfo::meanSampleDiskField(), polyMeshAdder::mergePoints(), triSurfaceTools::mergePoints(), Foam::min(), Foam::minMax(), Foam::minMaxMag(), polyMeshTetDecomposition::minQuality(), hexCell::modelFaces(), tetCell::modelFaces(), polyTopoChange::modifyFace(), findCellParticle::move(), trackedParticle::move(), molecule::move(), solidParticle::move(), DSMCParcel< ParcelType >::move(), KinematicParcel< ParcelType >::move(), MPPICParcel< ParcelType >::move(), regionModel1D::moveMesh(), solidBodyFvGeometryScheme::movePoints(), cyclicAMIFvPatch::movePoints(), face::nearestPointClassify(), Field< Type >::NewCalculatedType(), MeshedSurfaceProxy< Face >::nTriangles(), MeshedSurface< Face >::nTriangles(), noiseFFT::octaveBandInfo(), noiseFFT::octaves(), noiseModel::octaves(), isotropic::oneByTau(), nonEquilibrium::oneByTau(), ConstMatrixBlock< MatrixType >::operator Field< cmptType >(), MatrixBlock< MatrixType >::operator Field< cmptType >(), spatialTransform::transpose::operator&(), spatialTransform::dual::operator&(), parallelFvGeometryScheme::transformOriented::operator()(), offsetOp< face >::operator()(), masterUncollatedFileOperation::mkDirOp::operator()(), masterUncollatedFileOperation::chModOp::operator()(), masterUncollatedFileOperation::modeOp::operator()(), masterUncollatedFileOperation::typeOp::operator()(), masterUncollatedFileOperation::existsOp::operator()(), masterUncollatedFileOperation::isDirOp::operator()(), masterUncollatedFileOperation::isFileOp::operator()(), masterUncollatedFileOperation::fileSizeOp::operator()(), masterUncollatedFileOperation::lastModifiedOp::operator()(), masterUncollatedFileOperation::highResLastModifiedOp::operator()(), masterUncollatedFileOperation::mvBakOp::operator()(), masterUncollatedFileOperation::rmOp::operator()(), masterUncollatedFileOperation::rmDirOp::operator()(), masterUncollatedFileOperation::fileOrNullOp::operator()(), masterUncollatedFileOperation::readDirOp::operator()(), treeDataPrimitivePatch< PatchType >::findSelfIntersectOp::operator()(), treeDataCell::findIntersectOp::operator()(), offsetOp< labelledTri >::operator()(), findNearestMaskedOp< PatchType >::operator()(), offsetOp< triFace >::operator()(), Field< Type >::operator/=(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), MatrixBlock< MatrixType >::operator=(), Foam::operator>>(), Foam::operator>>(), Foam::operator^(), Foam::operator^(), cell::opposingFaceLabel(), OppositeFaceCellWave< Type, TrackingData >::opposingFaceLabels(), triSurfaceTools::oppositeVertex(), oldCyclicPolyPatch::order(), triSurfaceTools::otherVertices(), distributedTriSurfaceMesh::overlappingSurface(), searchableRotatedBox::overlaps(), treeDataFace::overlaps(), treeDataPrimitivePatch< PatchType >::overlaps(), treeDataFace::overlaps(), treeDataPrimitivePatch< PatchType >::overlaps(), Pair< point >::Pair(), Pair< T >::Pair(), Pair< T >::Pair(), Pair< T >::Pair(), CollisionRecordList< PairType, WallType >::pairAccessed(), CollisionRecordList< PairType, WallType >::pairData(), CollisionRecordList< PairType, WallType >::pairOrigIdOfOther(), CollisionRecordList< PairType, WallType >::pairOrigProcOfOther(), KinematicCloud< CloudType >::patchData(), LBFGS::pivotFields(), primitiveMesh::pointInCell(), polyMesh::pointInCell(), pointMVCWeight::pointMVCWeight(), PatchTools::pointNormals(), FaceInteraction< CloudType >::postFace(), Foam::pow(), Foam::pow(), Foam::printTriangle(), pointNoise::processData(), noiseFFT::PSDf(), noiseModel::RAf(), face::ray(), noiseModel::RBf(), noiseModel::RCf(), noiseModel::RDf(), turbulenceFields::read(), wallBoundedStreamLine::read(), multiRegion::read(), AC3DsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OBJsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), VTKsurfaceFormat< Face >::read(), boundaryMesh::read(), STARCDMeshReader::readCells(), triSurfaceLoader::readDir(), FIREMeshReader::readFaces(), CollidingParcel< ParcelType >::readFields(), ensightSurfaceReader::readGeometry(), liquidProperties::readIfPresent(), CollidingParcel< ParcelType >::readObjects(), processorLduInterface::receive(), fileName::relative(), surfaceFormatsCore::relativeFilePath(), triSurface::relativeFilePath(), snappySnapDriver::repatchToSurface(), vtuSizing::reset(), ODESolver::resizeField(), ODESolver::resizeField(), includeEtcEntry::resolveEtcFile(), includeEntry::resolveFile(), faceAreaWeightAMI::restartUncoveredSourceFace(), Foam::rewritePatchLabels(), Field< Type >::rmap(), Field< Type >::rmap(), noiseFFT::RMSmeanPf(), edgeFaceCirculator::sameOrder(), sampledFaceZone::sampleOnPoints(), sampledPatch::sampleOnPoints(), sampledSurface::sampleOnPoints(), oversetFvMeshBase::scaleConnection(), processorLduInterface::send(), edgeFaceCirculator::setCanonical(), refinementSurfaces::setCurvatureMinLevelFields(), IOstream::setf(), IOstream::setf(), fvGeometryScheme::setMeshPhi(), noiseModel::setOctaveBands(), removeCells::setRefinement(), removePoints::setRefinement(), meshCutter::setRefinement(), tetDecomposer::setRefinement(), addPatchCellLayer::setRefinement(), perfectInterface::setRefinement(), meshCutAndRemove::setRefinement(), hexRef8::setRefinement(), faceCollapser::setRefinement(), removeFaces::setRefinement(), combineFaces::setRefinement(), edgeCollapser::setRefinement(), duplicatePoints::setRefinement(), boundaryCutter::setRefinement(), createShellMesh::setRefinement(), combineFaces::setUnrefinement(), ThermoCloud< CloudType >::sigmap(), sizeGroup::sizeGroup(), rigidBodyMeshMotion::solve(), rigidBodyMeshMotionSolver::solve(), sixDoFRigidBodyMotionSolver::solve(), PatchTools::sortedEdgeFaces(), noiseModel::SPL(), noiseModel::SPL(), Foam::sqr(), Foam::sqr(), AMIInterpolation::srcPointFace(), Foam::stabilise(), MeshedSurface< Face >::stitchFaces(), Foam::sum(), Foam::sumMag(), triSurfaceTools::surfaceNormal(), triSurfaceTools::surfaceSide(), SVD::SVD(), swapec(), face::symmhash_code(), syncTools::syncEdgeMap(), Foam::tetCutPrism0(), Foam::tetCutPrism0(), Foam::tetCutPrism01(), Foam::tetCutPrism01(), Foam::tetCutPrism23(), Foam::tetCutPrism23(), Foam::tetCutTet(), Foam::tetCutTet(), AMIInterpolation::tgtPointFace(), cutFaceAdvect::timeIntegratedFaceFlux(), fileName::toAbsolute(), particle< Type >::track(), wallBoundedParticle::trackToEdge(), particle< Type >::trackToFace(), cyclicACMILduInterfaceField::transformCoupleField(), cyclicAMILduInterfaceField::transformCoupleField(), cyclicLduInterfaceField::transformCoupleField(), processorLduInterfaceField::transformCoupleField(), cyclicLduInterfaceField::transformCoupleField(), processorLduInterfaceField::transformCoupleField(), cyclicACMILduInterfaceField::transformCoupleField(), cyclicAMILduInterfaceField::transformCoupleField(), faceAreaIntersect::triangleFan(), faceAreaIntersect::triangulate(), boundaryMesh::triangulate(), triSurfaceTools::triangulate(), triSurfaceTools::triangulate(), MeshedSurface< Face >::triangulate(), triSurfaceTools::triangulateFaceCentre(), boundaryMesh::triangulateLocal(), advancingFrontAMI::triangulatePatch(), Foam::triCutQuad(), Foam::triCutQuad(), Foam::triCutTri(), Foam::triCutTri(), tetIndices::triIs(), noiseModel::uniformFrequencies(), IOstream::unsetf(), KinematicParcel< ParcelType >::trackingData::updateAverages(), MPPICParcel< ParcelType >::trackingData::updateAverages(), directionInfo::updateCell(), outletMappedUniformInletFvPatchField< Type >::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), patchFaceOrientation::updateEdge(), patchEdgeFaceRegions::updateEdge(), patchFaceOrientation::updateFace(), patchEdgeFaceRegions::updateFace(), primitiveMeshTools::updateFaceCentresAndAreas(), combineFaces::updateMesh(), removePoints::updateMesh(), patchInjectionBase::updateMesh(), processorPolyPatch::updateMesh(), exprResultDelayed::updateReadValue(), triSurfaceTools::validTri(), triSurfaceTools::validTri(), forceCoeffs::coeffDesc::value(), triSurfaceTools::vertexNormals(), triSurfaceTools::vertexNormalWeight(), surfaceIteratorIso::vofCutCell(), surfaceIteratorPLIC::vofCutCell(), cuttingSurfaceBase::walkCellCuts(), CollisionRecordList< PairType, WallType >::wallAccessed(), CollisionRecordList< PairType, WallType >::wallData(), wallLayerCells::wallLayerCells(), multiFieldValue::write(), turbulenceFields::write(), multiRegion::write(), rawWriter::write(), OBJstream::write(), ABAQUSsurfaceFormat< Face >::write(), NASsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), OFFsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), STARCDsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), X3DsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), VTPsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), OBJstream::write(), OBJstream::write(), OBJstream::write(), ensightFaces::write(), FLMAsurfaceFormat< Face >::write(), mesh::write(), STLsurfaceFormat< Face >::writeAscii(), STLsurfaceFormat< Face >::writeAscii(), STLsurfaceFormat< Face >::writeBinary(), box::writeBoxes(), CollidingParcel< ParcelType >::writeFields(), fieldAverage::writeFieldType(), noiseModel::writeFreqDataToFile(), coupledPolyPatch::writeOBJ(), enrichedPatch::writeOBJ(), AABBTreeBase::writeOBJ(), indexedOctreeBase::writeOBJ(), Foam::meshTools::writeOBJ(), CollidingParcel< ParcelType >::writeObjects(), patchMeshWriter::writePolys(), patchMeshWriter::writePolysLegacy(), Foam::ensightOutput::writePolysPoints(), Foam::ensightOutput::writePolysPoints(), MeshedSurface< Face >::writeStats(), triSurface::writeStats(), abaqusWriter::writeTemplate(), nastranWriter::writeTemplate(), rawWriter::writeTemplate(), x3dWriter::writeTemplate(), noiseModel::writeWeightings(), Foam::writeZone(), alphatJayatillekeWallFunctionFvPatchScalarField::yPlusTherm(), and alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
bcl()
labelList bcl (nPoints)
bcf()
labelList bcf (nPoints)
bcb()
labelList bcb (nPoints)
if() [2/4]
if (mTable = = 0)
Definition at line 77 of file readKivaGrid.H.
References FatalErrorInFunction.
imtab()
labelList imtab (nPoints)
jmtab()
labelList jmtab (nPoints)
kmtab()
labelList kmtab (nPoints)
quadFace()
face quadFace (4)
Referenced by if().
triFace()
face triFace (3)
Referenced by if().
if() [3/4]
if (pFaces. size() &&pFaces.size() &&pFaces.size() &&pFaces.size()[LINER][LINER][0][CYLINDERHEAD][CYLINDERHEAD][0])
Definition at line 320 of file readKivaGrid.H.
References forAll, pFaces, and points.
if() [4/4]
if (pFaces. size() &&pFaces.size()[WEDGE][WEDGE][0])
Definition at line 410 of file readKivaGrid.H.
References cellShapes, nPatches, pFaces, points, and Foam::tan().
boundary()
faceListList boundary (nPatches)
patchNames()
wordList patchNames (nPatches)
Referenced by snappyRefineDriver::addFaceZones(), polyBoundaryMesh::checkDefinition(), ensightMesh::correct(), extrudePatchMesh::extrudePatchMesh(), cellDistFuncs::getPatchIDs(), voxelMeshSearch::makeMesh(), Foam::nonProcessorPatchNames(), ParticleErosion< CloudType >::ParticleErosion(), patchInjection::patchInjection(), polyBoundaryMesh::patchSet(), Foam::preservePatchTypes(), sampledPatchInternalField::print(), fieldExtents::read(), fvMeshSubset::reset(), and wallLayerCells::wallLayerCells().
patchTypes()
wordList patchTypes (nPatches)
Referenced by age::execute(), extrudePatchMesh::extrudePatchMesh(), forAll(), cellVolumeWeight::interpolatePatchTypes(), cellVolumeWeight::interpolatePatchTypes(), inverseDistance::markBoundaries(), trackingInverseDistance::markBoundaries(), and searchableSurfaces::writeStats().
pointLabels()
labelList pointLabels (nPoints , - 1)
Referenced by polyMeshAdder::add(), polyTopoChange::addMesh(), setToPointZone::applyToSet(), faPatch::calcPointEdges(), cellModel::centre(), cellModel::edge(), cellModel::edges(), cellModel::face(), cellModel::faces(), forAll(), forAll(), forAll(), processorFaPatch::initUpdateMesh(), cell::labels(), cellModel::mag(), processorFaPatch::makeNonGlobalPatchPoints(), surfaceFeatures::nearestSamples(), cell::points(), setSize(), globalMeshData::sharedPointGlobalLabels(), globalMeshData::sharedPoints(), processorFaPatch::updateMesh(), coupledPolyPatch::writeOBJ(), and Foam::vtk::writePointSet().
forAll() [1/4]
forAll (cellShapes , celli)
Definition at line 487 of file readKivaGrid.H.
References cellShapes, forAll, and pointLabels().
forAll() [2/4]
forAll (pointLabels , pointi)
Definition at line 497 of file readKivaGrid.H.
References newPointi, pointLabels(), and points.
setSize()
points setSize (newPointi)
References cellShapes, forAll, and pointLabels().
Referenced by polyTopoChanger::addTopologyModifiers(), pairPotentialList::buildPotentials(), tetherPotentialList::buildPotentials(), face::collapse(), nearWallDist::correct(), patchPatchDist::correct(), and ParSortableList< Type >::sort().
forAll() [3/4]
forAll (boundary , patchi)
Definition at line 519 of file readKivaGrid.H.
References boundary, f(), forAll, and pointLabels().
preservePatchTypes()
preservePatchTypes (runTime , runTime. constant(), polyMesh::meshSubDir , patchNames , patchDicts , defaultFacesName , defaultFacesType)
forAll() [4/4]
forAll (patchNames , patchi)
Definition at line 544 of file readKivaGrid.H.
References patchDicts, and patchTypes().
pShapeMesh()
polyMesh pShapeMesh (IOobject(polyMesh::defaultRegion, runTime.constant(), runTime) , std::move(points) , cellShapes , boundary , patchNames , patchDicts , defaultFacesName , defaultFacesType)
Variable Documentation
nRegs
Info<< "Reading kiva grid from file " << kivaFileName << endl;char title[120];kivaFile.getline(title, 120, '\n');label nPoints, nCells, nRegs;kivaFile > nCells nPoints nRegs
Definition at line 17 of file readKivaGrid.H.
i4
label i4
Definition at line 20 of file readKivaGrid.H.
Referenced by for().
mTable
kivaFile mTable
Definition at line 74 of file readKivaGrid.H.
pFaces
Info<< "Finished reading KIVA file" << endl;cellShapeList cellShapes(nPoints);labelList cellZoning(nPoints, -1);const cellModel& hex = cellModel::ref(cellModel::HEX);labelList hexLabels(8);label activeCells = 0;labelList pointMap(nPoints);forAll(pointMap, i){ pointMap[i] = i;}for (label i=0; i<nPoints; i++){ if (f[i] > 0.0) { hexLabels[0] = i; hexLabels[1] = i1tab[i]; hexLabels[2] = i3tab[i1tab[i]]; hexLabels[3] = i3tab[i]; hexLabels[4] = i8tab[i]; hexLabels[5] = i1tab[i8tab[i]]; hexLabels[6] = i3tab[i1tab[i8tab[i]]]; hexLabels[7] = i3tab[i8tab[i]]; cellShapes[activeCells].reset(hex, hexLabels); edgeList edges = cellShapes[activeCells].edges(); forAll(edges, ei) { if (edges[ei].mag(points) < SMALL) { label start = pointMap[edges[ei].start()]; while (start != pointMap[start]) { start = pointMap[start]; } label end = pointMap[edges[ei].end()]; while (end != pointMap[end]) { end = pointMap[end]; } label minLabel = min(start, end); pointMap[start] = pointMap[end] = minLabel; } } cellZoning[activeCells] = idreg[i]; activeCells++; }}cellShapes.setSize(activeCells);cellZoning.setSize(activeCells);forAll(cellShapes, celli){ cellShape& cs = cellShapes[celli]; forAll(cs, i) { cs[i] = pointMap[cs[i]]; } cs.collapse();}label bcIDs[11] = {-1, 0, 2, 4, -1, 5, -1, 6, 7, 8, 9};const label nBCs = 12;const word* kivaPatchTypes[nBCs] ={ &wallPolyPatch::typeName, &wallPolyPatch::typeName, &wallPolyPatch::typeName, &wallPolyPatch::typeName, &symmetryPolyPatch::typeName, &wedgePolyPatch::typeName, &polyPatch::typeName, &polyPatch::typeName, &polyPatch::typeName, &polyPatch::typeName, &symmetryPolyPatch::typeName, &oldCyclicPolyPatch::typeName};enum patchTypeNames{ PISTON, VALVE, LINER, CYLINDERHEAD, AXIS, WEDGE, INFLOW, OUTFLOW, PRESIN, PRESOUT, SYMMETRYPLANE, CYCLIC};const char* kivaPatchNames[nBCs] ={ "piston", "valve", "liner", "cylinderHead", "axis", "wedge", "inflow", "outflow", "presin", "presout", "symmetryPlane", "cyclic"};List<SLList<face> > pFaces[nBCs]
Definition at line 235 of file readKivaGrid.H.
Referenced by singleProcessorFaceSets::add(), singleProcessorFaceSets::apply(), snappySnapDriver::avgCellCentres(), Foam::meshTools::calcBoxPointNormals(), polyMeshTetDecomposition::cellTetIndices(), motionSmootherAlgo::checkMesh(), motionSmootherAlgo::checkMesh(), PrimitivePatch< FaceList, PointField >::checkPointManifold(), wallBoundedParticle::crossEdgeConnectedFace(), decompositionMethod::decompose(), polyMeshTetDecomposition::faceTetIndices(), cellClassification::fillRegionPoints(), polyMeshTetDecomposition::findBasePoint(), localPointRegion::findDuplicateFaces(), polyMeshTetDecomposition::findSharedBasePoint(), polyMeshTetDecomposition::findTet(), cellLooper::getVertFacesNonEdge(), if(), if(), if(), volPointInterpolation::interpolateBoundaryField(), mappedPolyPatch::newInternalProcFaces(), mappedWallPolyPatch::newInternalProcFaces(), oldCyclicPolyPatch::order(), boundaryMesh::patchify(), primitiveMesh::pointCells(), PatchTools::pointNormals(), Foam::polyMeshZipUpCells(), removePoints::setRefinement(), perfectInterface::setRefinement(), hexRef8::setUnrefinement(), triSurfaceTools::trackToEdge(), dynamicRefineFvMesh::unrefine(), and triSurfaceTools::vertexNormals().
nPatches
label nPatches = 0
Definition at line 396 of file readKivaGrid.H.
Referenced by addPatchCellLayer::calcExtrudeInfo(), PointEdgeWave< Type, TrackingData >::countPatchType(), faMeshDecomposition::decomposeMesh(), faMeshDistributor::distribute(), if(), fvMeshTools::newMesh(), faMeshTools::newMesh(), faMeshTools::printMeshChecks(), STARCDMeshReader::readBoundary(), FIREMeshReader::reorganize(), polyTopoChange::setNumPatches(), patchWriter::write(), patchWriter::write(), patchWriter::write(), faMeshDecomposition::writeDecomposition(), and patchMeshWriter::writePoints().
defaultFacesName
word defaultFacesName = "defaultFaces"
Definition at line 455 of file readKivaGrid.H.
Referenced by Foam::preservePatchTypes().
defaultFacesType
word defaultFacesType = emptyPolyPatch::typeName
Definition at line 456 of file readKivaGrid.H.
Referenced by Foam::preservePatchTypes().
nAddedPatches
label nAddedPatches = 0
Definition at line 458 of file readKivaGrid.H.
newPointi
label newPointi = 0
Definition at line 496 of file readKivaGrid.H.
Referenced by extendedEdgeMesh::add(), polyTopoChange::changeMesh(), extendedEdgeMesh::flipNormals(), forAll(), triSurfaceTools::greenRefine(), hexRef8::subset(), triSurfaceTools::triangulateFaceCentre(), boundaryCutter::updateMesh(), hexRef8Data::updateMesh(), localPointRegion::updateMesh(), addPatchCellLayer::updateMesh(), hexRef8::updateMesh(), pointZoneSet::updateMesh(), and polyMesh::updateMesh().
patchDicts
PtrList<dictionary> patchDicts
Definition at line 532 of file readKivaGrid.H.
Referenced by forAll(), blockMesh::patchDicts(), and Foam::preservePatchTypes().