OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/chtMultiRegionSimpleFoam/fluid/readFluidMultiRegionSIMPLEControls.H File Reference
readFluidMultiRegionSIMPLEControls.H File Reference
Functions
simple readIfPresent ("frozenFlow", frozenFlowFluid[i])
Variables
const dictionary & simple = fluidRegions[i].solutionDict().subDict("SIMPLE")
const int nNonOrthCorr
const bool momentumPredictor
Function Documentation
readIfPresent()
simple readIfPresent ("frozenFlow" , frozenFlowFluid [i])
Variable Documentation
simple
const dictionary& simple = fluidRegions[i].solutionDict().subDict("SIMPLE")
Definition at line 1 of file readFluidMultiRegionSIMPLEControls.H.
Referenced by if(), if(), and while().
nNonOrthCorr
const int nNonOrthCorr
Initial value:
=
        simple.getOrDefault<int>("nNonOrthogonalCorrectors", 0)
Definition at line 3 of file readFluidMultiRegionSIMPLEControls.H.
Referenced by for(), and velocityLaplacianFvMotionSolver::solve().
momentumPredictor
const bool momentumPredictor
Initial value:
=
        simple.getOrDefault("momentumPredictor", true)
Definition at line 6 of file readFluidMultiRegionSIMPLEControls.H.
Referenced by adjointSimple::mainIter(), and simple::mainIter().