OpenFOAM: applications/solvers/compressible/rhoPimpleAdiabaticFoam/resetBoundaries.H File Reference
resetBoundaries.H File Reference
Functions
forAll (U.boundaryField(), patchi)
Variables
const Foam::FieldField< Foam::fvsPatchField, vector > rhoHbyA_orig (fvc::interpolate(rho.boundaryField() *HbyA.boundaryField()))
surfaceScalarField::Boundary & rhorAUfbf = rhorAUf.boundaryFieldRef()
surfaceVectorField::Boundary & rhoHbyAfbf = rhoHbyAf.boundaryFieldRef()
Function Documentation
forAll()
forAll (U. boundaryField(), patchi)
Definition at line 17 of file resetBoundaries.H.
References rhoHbyA_orig, rhoHbyAfbf, rhorAUfbf, and U.
Variable Documentation
rhoHbyA_orig
const Foam::FieldField< Foam::fvsPatchField, vector > rhoHbyA_orig(fvc::interpolate(rho.boundaryField() *HbyA.boundaryField())) (fvc::interpolate(rho.boundaryField() *HbyA.boundaryField()))
Initial value:
{
    const Foam::FieldField<Foam::fvsPatchField, scalar> rhorAUf_orig
    (
        fvc::interpolate(rho.boundaryField()*rAU.boundaryField())
    )
Referenced by forAll().
rhorAUfbf
surfaceScalarField::Boundary& rhorAUfbf = rhorAUf.boundaryFieldRef()
Definition at line 14 of file resetBoundaries.H.
Referenced by forAll().
rhoHbyAfbf
surfaceVectorField::Boundary& rhoHbyAfbf = rhoHbyAf.boundaryFieldRef()
Definition at line 15 of file resetBoundaries.H.
Referenced by forAll().