OpenFOAM: applications/utilities/preProcessing/viewFactorsGen/searchingEngine_CGAL.H File Reference
searchingEngine_CGAL.H File Reference
Functions
Random rndGen (653213)
List< treeBoundBox > meshBb (1, treeBoundBox(coarseMesh.points()).extend(rndGen, 1e-3))
dict add ("bounds", meshBb)
dict add ("distributionType", distributedTriSurfaceMesh::distributionTypeNames_[distributedTriSurfaceMesh::FROZEN])
dict add ("mergeDistance", SMALL)
labelList triSurfaceToAgglom (5 *nFineFaces)
distributedTriSurfaceMesh surfacesMesh (IOobject("wallSurface.stl", runTime.constant(), "triSurface", runTime, IOobject::NO_READ, IOobject::NO_WRITE), localSurface, dict)
triSurfaceToAgglom resize (surfacesMesh.size())
surfacesMesh setField (triSurfaceToAgglom)
triangles reserve (surf.size())
for (const auto &f :surf)
Tree tree (triangles.begin(), triangles.end())
Variables
dictionary dict
const triSurface localSurface
std::vector< Triangle > triangles
const pointField & pts = surf.points()
Function Documentation
rndGen()
Random rndGen (653213)
meshBb()
List< treeBoundBox > meshBb (1 , treeBoundBox(coarseMesh.points()).extend(rndGen, 1e-3))
add() [1/3]
dict add ("bounds" , meshBb)
add() [2/3]
dict add ("distributionType" , distributedTriSurfaceMesh::distributionTypeNames_ [distributedTriSurfaceMesh::FROZEN])
add() [3/3]
dict add ("mergeDistance" , SMALL)
triSurfaceToAgglom()
labelList triSurfaceToAgglom (5 * nFineFaces)
surfacesMesh()
distributedTriSurfaceMesh surfacesMesh (IOobject("wallSurface.stl", runTime.constant(), "triSurface", runTime, IOobject::NO_READ, IOobject::NO_WRITE) , localSurface , dict)
resize()
triSurfaceToAgglom resize (surfacesMesh. size())
setField()
surfacesMesh setField (triSurfaceToAgglom)
reserve()
triangles reserve (surf. size())
Referenced by fileName::fileName(), fileName::fileName(), CircularBuffer< T >::operator=(), CircularBuffer< T >::push_back(), CircularBuffer< T >::push_back(), CircularBuffer< T >::push_back(), PackedList< Width >::push_back(), CircularBuffer< T >::push_back(), CircularBuffer< T >::push_front(), CircularBuffer< T >::push_front(), bitSet::set(), and bitSet::setMany().
for()
for (const auto &f :surf)
Definition at line 66 of file searchingEngine_CGAL.H.
References b, PtrList< T >::emplace_back(), f(), pts, and triangles.
tree()
Tree tree (triangles. begin(), triangles. end())
Referenced by extendedEdgeMesh::allNearestFeatureEdges(), triSurfaceSearch::calcInside(), faceAreaWeightAMI2D::calculate(), Foam::createTree(), polyMesh::findCellFacePt(), treeDataPrimitivePatch< PatchType >::findIntersection(), triSurfaceSearch::findLine(), triSurfaceSearch::findLineAll(), triSurfaceSearch::findLineAny(), mappedPatchBase::findLocalSamples(), searchableExtrudedCircle::findNearest(), triSurfaceSearch::findNearest(), meshSearch::findNearestBoundaryFace(), refinementFeatures::findNearestEdge(), refinementFeatures::findNearestPoint(), searchableExtrudedCircle::findParametricNearest(), for(), searchableExtrudedCircle::getNormal(), distributedTriSurfaceMesh::getVolumeType(), triSurfaceMesh::getVolumeType(), triSurfaceSearch::nearest(), extendedEdgeMesh::nearestFeatureEdgeByType(), faceAreaWeightAMI2D::overlappingTgtFaces(), triSurfaceMesh::overlaps(), and propellerInfo::updateSampleDiskCells().
Variable Documentation
dict
dictionary dict
Definition at line 11 of file searchingEngine_CGAL.H.
localSurface
const triSurface localSurface
Initial value:
= triangulate
(
    patches,
    includePatches,
    finalAgglom,
    triSurfaceToAgglom,
    globalNumbering,
    coarsePatches
)
Definition at line 25 of file searchingEngine_CGAL.H.
triangles
std::vector<Triangle> triangles
Definition at line 57 of file searchingEngine_CGAL.H.
Referenced by for(), triSurfaceTools::triangulate(), triSurfaceTools::triangulate(), and triSurfaceTools::triangulateFaceCentre().
pts
const pointField& pts = surf.points()
Definition at line 64 of file searchingEngine_CGAL.H.
Referenced by tetIndices::barycentricToPoint(), booleanSurface::booleanSurface(), searchableBox::boundingSpheres(), triSurfaceMesh::boundingSpheres(), edge::box(), face::box(), meshRefinement::calculateEdgeWeights(), edge::centre(), Foam::meshTools::constrainToMeshCentre(), edgeVertex::coord(), searchableBox::coordinates(), triSurfaceMesh::coordinates(), distanceSurface::createGeometry(), cutFaceAdvect::cutPoints(), triSurfaceTools::delaunay2D(), face::edge(), triFace::edge(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), boundBox::faceCentres(), cellVolumeWeightMethod::findInitialSeeds(), for(), triSurfaceMesh::getNormal(), triSurfaceMeshPointSet::getRefPoint(), boundBox::hexCorners(), PDRblock::innerMesh(), blockMesh::inplacePointTransforms(), triangleFuncs::intersect(), vectorTensorTransform::invTransformPosition(), isoSurfaceCell::isoSurfaceCell(), isoSurfacePoint::isoSurfacePoint(), triSurfaceMesh::isSurfaceClosed(), edge::line(), face::longestEdge(), edge::mag(), edge::magSqr(), momentOfInertia::massPropertiesShell(), momentOfInertia::massPropertiesSolid(), Patch::mesh(), faceZone::movePoints(), ZoneMesh< ZoneType, MeshType >::movePoints(), triSurface::movePoints(), meshedSurfRef::movePoints(), tetIndices::oldTet(), processorPolyPatch::order(), cuttingPlane::performCut(), searchableCone::points(), searchableCylinder::points(), searchablePlate::points(), searchableSurfaceCollection::points(), treeBoundBox::points(), vtuAdaptor::points(), vtuAdaptor::points(), Foam::vtk::Tools::Points(), face::points(), triFace::points(), Foam::vtk::Tools::Points(), AMIInterpolation::projectPointsToSurface(), face::rcEdge(), triFace::rcEdge(), NASedgeFormat::read(), STARCDedgeFormat::read(), sampledSurface::sampleOnFaces(), sampledSurface::sampleOnPoints(), extendedEdgeMesh::sortPointsAndEdges(), surfaceFeatures::subsetPlane(), reconstructionSchemes::surface(), triSurface::swapPoints(), tetIndices::tet(), tetPoints::tetPoints(), triSurface::transfer(), vectorTensorTransform::transformPosition(), triPoints::triPoints(), edge::unitVec(), edge::vec(), Foam::vtk::Tools::Vertices(), Foam::vtk::Tools::Vertices(), momentum::write(), areaWrite::write(), vtkWriter::write(), box::writeBoxes(), STARCDsurfaceFormatCore::writeCase(), meshToMeshMethod::writeConnectivity(), VTKsurfaceFormatCore::writeHeader(), VTPsurfaceFormatCore::writeHeader(), triSurfaceTools::writeOBJ(), AABBTreeBase::writeOBJ(), indexedOctreeBase::writeOBJ(), Foam::meshTools::writeOBJ(), Foam::writeObjPoints(), X3DsurfaceFormatCore::writePoints(), csvWriter::writeTemplate(), and rawWriter::writeTemplate().