OpenFOAM: src/overset/include/setCellMask.H File Reference
setCellMask.H File Reference
Sets blocked cells mask field.
Functions
cellMask primitiveFieldRef ()
forAll (cellMask, cellI)
cellMask correctBoundaryConditions ()
Variables
const labelList & cellTypes = overlap.cellTypes()
faceMask = localMin<scalar>(mesh).interpolate(cellMask)
Detailed Description
Sets blocked cells mask field.
Original source file setCellMask.H
Definition in file setCellMask.H.
Function Documentation
primitiveFieldRef()
cellMask primitiveFieldRef ()
forAll()
forAll (cellMask , cellI)
Definition at line 30 of file setCellMask.H.
References cellTypes.
correctBoundaryConditions()
U2 correctBoundaryConditions ()
Referenced by gaussGrad< Type >::calcGrad(), gaussGrad< Type >::calcGrad(), motionSmootherAlgo::curPoints(), anisotropicFilter::operator()(), laplaceFilter::operator()(), simpleFilter::operator()(), anisotropicFilter::operator()(), laplaceFilter::operator()(), simpleFilter::operator()(), anisotropicFilter::operator()(), laplaceFilter::operator()(), simpleFilter::operator()(), anisotropicFilter::operator()(), laplaceFilter::operator()(), simpleFilter::operator()(), oversetFvMeshBase::solveOverset(), and oversetFvMeshBase::writeAgglomeration().
Variable Documentation
cellTypes
const labelList& cellTypes = overlap.cellTypes()
Definition at line 27 of file setCellMask.H.
Referenced by oversetFvPatchField< Type >::adjustPsi(), inverseDistance::findHoles(), forAll(), oversetFvPatchField< Type >::fringeFlux(), vtuAdaptor::internal(), Foam::operator<<(), Foam::oversetAdjustPhi(), vtuSizing::populateLegacy(), vtuSizing::populateShapesLegacy(), vtuSizing::populateShapesXml(), vtuSizing::populateXml(), cellSetOption::setCellSelection(), oversetFvPatchField< Type >::storeFringeCoefficients(), and oversetFvMeshBase::writeObject().
faceMask
faceMask = localMin<scalar>(mesh).interpolate(cellMask)
Definition at line 43 of file setCellMask.H.