OpenFOAM: src/OpenFOAM/include/setRootCase.H File Reference
setRootCase.H File Reference
Functions
if (!args.checkRootCase())
Variables
Foam::argList args (argc, argv)
Function Documentation
if()
if (!args. checkRootCase())
Definition at line 6 of file setRootCase.H.
References error::exit(), and Foam::FatalError.
Variable Documentation
args
Foam::argList args(argc, argv) (argc , argv)
Referenced by Pstream::broadcasts(), PtrList< T >::clone(), autoPtr< T >::clone(), AC3DsurfaceFormatCore::cueTo(), AC3DsurfaceFormatCore::cueToOrDie(), HashPtrTable< T, Key, Hash >::emplace(), HashTable< T, Key, Hash >::emplace(), PtrDynList< T, SizeMin >::emplace(), PtrList< T >::emplace(), DynamicList< T, SizeMin >::emplace_back(), List< T >::emplace_back(), PtrDynList< T, SizeMin >::emplace_back(), DynamicField< T, SizeMin >::emplace_back(), HashTable< T, Key, Hash >::emplace_set(), PtrList< T >::emplace_set(), forAll(), forAll(), PtrListDetail< CloudFunctionObject< CloudType > >::free(), HashPtrTable< IOobject >::HashPtrTable(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), if(), Foam::Detail::inputLoop(), autoPtr< T >::New(), refPtr< T >::New(), tmp< T >::New(), Time::New(), dynamicFvMesh::New(), functionObjectList::New(), MeshObject< Mesh, MeshObjectType, Type >::New(), autoPtr< T >::NewFrom(), refPtr< T >::NewFrom(), tmp< T >::NewFrom(), tmp< T >::NewImmovable(), formatter::openTag(), formatter::openTag(), Foam::Detail::outputLoop(), PtrList< CloudFunctionObject< CloudType > >::PtrList(), AC3DsurfaceFormat< Face >::read(), AC3DsurfaceFormatCore::readCmd(), functionObjectList::readFunctionObject(), zoltanRenumber::renumber(), timeSelector::select(), timeSelector::select0(), timeSelector::selectIfPresent(), Foam::stringOps::splitFunctionArgs(), formatter::tag(), formatter::tag(), Time::Time(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlAttr(), formatter::xmlComment(), formatter::xmlCommentLoop(), and BlendedInterfacialModel< Foam::dragModel >::~BlendedInterfacialModel().