OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/solid/setRegionSolidFields.H File Reference
setRegionSolidFields.H File Reference
Functions
if (!thermo.isotropic())
Variables
solidThermo & thermo = thermos[i]
tmp< volScalarField > trho = thermo.rho()
const volScalarField & rho = trho()
tmp< volScalarField > tcp = thermo.Cp()
const volScalarField & cp = tcp()
tmp< volSymmTensorField > taniAlpha
volScalarField & h = thermo.he()
const volScalarField & betav = betavSolid[i]
fv::options & fvOptions = solidHeatSources[i]
Function Documentation
if()
if (!thermo. isotropic())
Definition at line 10 of file setRegionSolidFields.H.
References aniAlphas(), coordinates(), cp, mesh, and taniAlpha.
Variable Documentation
thermo
solidThermo& thermo = thermos[i]
Definition at line 1 of file setRegionSolidFields.H.
trho
tmp<volScalarField> trho = thermo.rho()
Definition at line 3 of file setRegionSolidFields.H.
Referenced by StandardChemistryModel< ReactionThermo, ThermoType >::calculate(), StandardChemistryModel< ReactionThermo, ThermoType >::calculateRR(), EDC< ReactionThermo >::correct(), PaSR< ReactionThermo >::correct(), momentumError::divDevRhoReff(), forAll(), multiphaseSystem::rho(), phaseSystem::rho(), constantFilmThermo::rho(), liquidFilmThermo::rho(), multiphaseSystem::rho(), StandardChemistryModel< ReactionThermo, ThermoType >::solve(), and StandardChemistryModel< ReactionThermo, ThermoType >::tc().
rho
const volScalarField& rho = trho()
Definition at line 4 of file setRegionSolidFields.H.
tcp
tmp<volScalarField> tcp = thermo.Cp()
Definition at line 6 of file setRegionSolidFields.H.
Referenced by forAll().
cp
const volScalarField& cp = tcp()
Definition at line 7 of file setRegionSolidFields.H.
Referenced by heThermo< BasicThermo, MixtureType >::Cp(), heThermo< BasicThermo, MixtureType >::Cp(), absoluteEnthalpy< Thermo >::Cpv(), sensibleEnthalpy< Thermo >::Cpv(), Cv(), StandardChemistryModel< ReactionThermo, ThermoType >::derivatives(), TDACChemistryModel< ReactionThermo, ThermoType >::derivatives(), forAll(), if(), triangle< Point, PointRef >::nearestPointClassify(), faFieldReconstructor::reconstructField(), faFieldReconstructor::reconstructField(), fvFieldReconstructor::reconstructField(), fvFieldReconstructor::reconstructField(), timeVaryingMassSorptionFvPatchScalarField::source(), plenumPressureFvPatchScalarField::updateCoeffs(), timeVaryingMassSorptionFvPatchScalarField::updateCoeffs(), and humidityTemperatureCoupledMixedFvPatchScalarField::updateCoeffs().
taniAlpha
tmp<volSymmTensorField> taniAlpha
Definition at line 9 of file setRegionSolidFields.H.
Referenced by if().
h
volScalarField& h = thermo.he()
Definition at line 32 of file setRegionSolidFields.H.
Referenced by jouleHeatingSource::addSup(), Grimshaw::alfa(), limitHeight::correct(), filmTurbulenceModel::Cw(), Foam::Math::erfInv(), Grimshaw::eta(), McCowan::eta(), thermo::evolveRegion(), forAll(), liquidProperties::Ha(), heThermo< BasicThermo, MixtureType >::heBoundaryCorrection(), liquidProperties::Hs(), Foam::HSV_to_RGB(), if(), if(), if(), McCowan::mn(), McCowan::newtonRapsonF1(), McCowan::newtonRapsonF2(), optionList::operator()(), optionList::operator()(), optionList::operator()(), optionList::operator()(), speciesSorptionFvPatchScalarField::patchSource(), waveGenerationModel::readWaveHeight(), Foam::RGB_to_HSV(), SIBS::solve(), optionList::source(), SVD::SVD(), heThermo< BasicThermo, MixtureType >::THE(), heThermo< BasicThermo, MixtureType >::THE(), absoluteEnthalpy< Thermo >::THE(), sensibleEnthalpy< Thermo >::THE(), irregularMultiDirectional::Uf(), Grimshaw::Uf(), McCowan::Uf(), StokesI::UfBase(), StokesII::UfBase(), LISAAtomization< CloudType >::update(), waveMakerPointPatchVectorField::waveLength(), irregularMultiDirectional::waveLength(), and StokesI::waveLength().
betav
const volScalarField& betav = betavSolid[i]
Definition at line 34 of file setRegionSolidFields.H.
Referenced by if(), if(), if(), if(), if(), and while().
fvOptions
fv::options& fvOptions = solidHeatSources[i]
Definition at line 36 of file setRegionSolidFields.H.