OpenFOAM: src/OpenFOAM/primitives/hashes/SHA1/SHA1Digest.C File Reference
SHA1Digest.C File Reference
Namespaces
namespace Foam
Functions
static unsigned char readHexDigit (Istream &is)
Variables
static const char hexChars [] = "0123456789abcdef"
static constexpr int offsetZero = int('0')
static constexpr int offsetAlpha = int('A') - 10
Detailed Description
Original source file SHA1Digest.C
Definition in file SHA1Digest.C.
Variable Documentation
hexChars
const char hexChars[] = "0123456789abcdef" static
Definition at line 30 of file SHA1Digest.C.
Referenced by SHA1Digest::str(), and SHA1Digest::write().
offsetZero
constexpr int offsetZero = int('0') static constexpr
Definition at line 33 of file SHA1Digest.C.
Referenced by Foam::ReadHex(), and Foam::readHexDigit().
offsetAlpha
constexpr int offsetAlpha = int('A') - 10 static constexpr
Definition at line 36 of file SHA1Digest.C.
Referenced by Foam::ReadHex(), and Foam::readHexDigit().