OpenFOAM: applications/utilities/preProcessing/viewFactorsGen/shootRays_CGAL.H File Reference
shootRays_CGAL.H File Reference
Functions
const label maxDynListLength (viewFactorDict.getOrDefault< label >("maxDynListLength", 1000000000))
for (const int proci :Pstream::allProcs())
Function Documentation
maxDynListLength()
const label maxDynListLength (viewFactorDict.getOrDefault< label > "maxDynListLength", 1000000000)
Referenced by for().
for()
for (const int proci :Pstream::allProcs())
Definition at line 7 of file shootRays_CGAL.H.
References FatalErrorInFunction, maxDynListLength(), s(), and tree().