OpenFOAM: applications/utilities/preProcessing/viewFactorsGen/shootRays.H File Reference
shootRays.H File Reference
Functions
if (Pstream::master())
const label maxDynListLength (viewFactorDict.getOrDefault< label >("maxDynListLength", 1000000))
for (const int proci :Pstream::allProcs())
Function Documentation
if()
if (Pstream::master())
Definition at line 5 of file shootRays.H.
maxDynListLength()
const label maxDynListLength (viewFactorDict.getOrDefault< label > "maxDynListLength", 1000000)
Referenced by for().
for()
for (const int proci :Pstream::allProcs())
Definition at line 19 of file shootRays.H.
References PtrList< T >::append(), List< T >::append(), PtrList< T >::clear(), FatalErrorInFunction, forAll, maxDynListLength(), surfacesMesh(), and List< T >::transfer().