OpenFOAM: applications/solvers/combustion/chemFoam/createFields.H File Reference
createFields.H File Reference
Functions
if (mesh.nCells() !=1)
Info<< "Reading initial conditions.\n"<< endl;IOdictionary initialConditions(IOobject("initialConditions", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));scalar p0=initialConditions.get< scalar > ("p")
Info<< "Reading thermophysical properties\n"<< endl;autoPtr< psiReactionThermo > pThermo (psiReactionThermo::New(mesh))
thermo validate (args.executable(), "h")
autoPtr< BasicChemistryModel< psiReactionThermo > > pChemistry (BasicChemistryModel< psiReactionThermo >::New(thermo))
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
volScalarField Rspecific (IOobject("Rspecific", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar(dimEnergy/dimMass/dimTemperature, Zero))
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedVector(dimVelocity, Zero))
OFstream post (args.path()/"chemFoam.out")
Variables
scalar T0 = initialConditions.get<scalar>("T")
psiReactionThermo & thermo = pThermo()
Function Documentation
if()
if (mesh.nCells() ! = 1)
Definition at line 1 of file createFields.H.
References FatalErrorInFunction.
Info<< "Reading initial conditions.\n"<< endl;IOdictionary initialConditions(IOobject("initialConditions", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));scalar p0=initialConditions.get< scalar >()
Info<< "Reading initial conditions.\n"<< endl;IOdictionary initialConditions(IOobject("initialConditions", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));scalar p0=initialConditions.get< scalar > ("p")
pThermo()
Info<< "Reading thermophysical properties\n"<< endl; autoPtr< psiReactionThermo > pThermo (psiReactionThermo::New(mesh))
validate()
thermo validate (args. executable(), "h")
Referenced by surfMesh::addZones(), surfMesh::copySurface(), and surfMesh::transfer().
pChemistry()
autoPtr< BasicChemistryModel< psiReactionThermo > > pChemistry (BasicChemistryModel< psiReactionThermo > ::Newthermo)
rho()
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
Rspecific()
volScalarField Rspecific (IOobject("Rspecific", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar(dimEnergy/dimMass/dimTemperature, Zero))
U()
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedVector(dimVelocity, Zero))
post()
OFstream post (args.path()/"chemFoam.out")
Variable Documentation
T0
scalar T0 = initialConditions.get<scalar>("T")
Definition at line 22 of file createFields.H.
Referenced by ReactingHeterogeneousParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), ReactingParcel< ParcelType >::calc(), ThermoParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::chi(), if(), interfaceHeatResistance< Thermo, OtherThermo >::Kexp(), kineticGasEvaporation< Thermo, OtherThermo >::Kexp(), ReactingMultiphaseCloud< Foam::DSMCCloud >::ReactingMultiphaseCloud(), noiseFFT::setData(), thermo< Thermo, Type >::TEa(), thermo< Thermo, Type >::TEs(), thermo< Thermo, Type >::THa(), thermo< Thermo, Type >::THE(), heThermo< BasicThermo, MixtureType >::THE(), heThermo< BasicThermo, MixtureType >::THE(), absoluteInternalEnergy< Thermo >::THE(), sensibleInternalEnergy< Thermo >::THE(), absoluteEnthalpy< Thermo >::THE(), sensibleEnthalpy< Thermo >::THE(), and thermo< Thermo, Type >::THs().
thermo
psiReactionThermo& thermo = pThermo()
Definition at line 28 of file createFields.H.