OpenFOAM: applications/solvers/heatTransfer/solidFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading thermophysical properties\n"<< endl;autoPtr< solidThermo > pThermo (solidThermo::New(mesh))
if (!thermo.isotropic())
IOobject betavSolidIO ("betavSolid", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE)
if (betavSolidIO.typeHeaderOk< volScalarField >(true))
bool meshFluxCorr (false)
if (mesh.solutionDict().found("SIMPLE"))
else if (mesh.solutionDict().found("PIMPLE"))
Variables
solidThermo & thermo = pThermo()
tmp< volScalarField > trho = thermo.rho()
autoPtr< coordinateSystem > coordinatesPtr
autoPtr< volSymmTensorField > taniAlpha
autoPtr< volScalarField > betavPtr
else
Function Documentation
pThermo()
Info<< "Reading thermophysical properties\n"<< endl;autoPtr< solidThermo > pThermo (solidThermo::New(mesh))
if() [1/4]
if (!thermo. isotropic())
Definition at line 11 of file createFields.H.
References coordinatesPtr, mesh, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), runTime, and taniAlpha.
betavSolidIO()
IOobject betavSolidIO ("betavSolid" , runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::AUTO_WRITE)
Referenced by forAll(), and if().
if() [2/4]
if (betavSolidIO.typeHeaderOk< volScalarField > true)
Definition at line 62 of file createFields.H.
References betavPtr, betavSolidIO(), and mesh.
meshFluxCorr()
bool meshFluxCorr (false)
Referenced by if(), and if().
if() [3/4]
if (mesh. solutionDict).found("SIMPLE")
Definition at line 95 of file createFields.H.
References mesh, and meshFluxCorr().
if() [4/4]
else if (mesh. solutionDict).found("PIMPLE")
Definition at line 103 of file createFields.H.
References mesh, and meshFluxCorr().
Variable Documentation
thermo
solidThermo& thermo = pThermo()
Definition at line 4 of file createFields.H.
trho
tmp<volScalarField> trho = thermo.rho()
Definition at line 6 of file createFields.H.
coordinatesPtr
autoPtr<coordinateSystem> coordinatesPtr
Definition at line 8 of file createFields.H.
Referenced by if().
taniAlpha
autoPtr<volSymmTensorField> taniAlpha
Definition at line 9 of file createFields.H.
Referenced by if().
betavPtr
autoPtr<volScalarField> betavPtr
Definition at line 61 of file createFields.H.
Referenced by if().
else
else
Initial value:
{
    betavPtr.reset
    (
        new volScalarField
        (
            IOobject
            (
                "betavSolid",
                runTime.timeName(),
                mesh,
                IOobject::NO_READ,
                IOobject::NO_WRITE
            ),
            mesh,
            dimensionedScalar("1", dimless, scalar(1))
        )
    )
Definition at line 73 of file createFields.H.