OpenFOAM: applications/solvers/multiphase/interCondensatingEvaporatingFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading field p_rgh\n"<< endl;volScalarField p_rgh(IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);autoPtr< twoPhaseMixtureEThermo > thermo (new twoPhaseMixtureEThermo(U, phi))
volScalarField & alpha1 (thermo->alpha1())
volScalarField & alpha2 (thermo->alpha2())
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE), alpha1 *rho1+alpha2 *rho2)
rho oldTime ()
surfaceScalarField rhoPhi (IOobject("rhoPhi", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), fvc::interpolate(rho) *phi)
interfaceProperties interface (alpha1, U, thermo->transportPropertiesDict())
autoPtr< incompressible::turbulenceModel > turbulence (incompressible::turbulenceModel::New(U, phi, thermo()))
setRefCell (p, p_rgh, pimple.dict(), pRefCell, pRefValue)
if (p_rgh.needReference())
mesh setFluxRequired (p_rgh.name())
mesh setFluxRequired (alpha1.name())
dimensionedScalar Prt ("Prt", dimless, thermo->transportPropertiesDict())
volScalarField kappaEff (IOobject("kappaEff", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), thermo->kappa())
volScalarField rhoCp (IOobject("rhoCp", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho *thermo->Cp())
Variables
Info<< "Creating temperaturePhaseChangeTwoPhaseMixture\n"<< endl;autoPtr< temperaturePhaseChangeTwoPhaseMixture > mixture
const dimensionedScalar & rho1 = thermo->rho1()
const dimensionedScalar & rho2 = thermo->rho2()
volScalarField & p = thermo->p()
label pRefCell = 0
scalar pRefValue = 0.0
Function Documentation
thermo()
Info<< "Reading field p_rgh\n"<< endl;volScalarField p_rgh(IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);autoPtr< twoPhaseMixtureEThermo > thermo (new twoPhaseMixtureEThermoU, phi)
alpha1()
volScalarField & alpha1 (thermo-> alpha1())
alpha2()
volScalarField & alpha2 (thermo-> alpha2())
rho()
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE) , alpha1 *rho1+alpha2 * rho2)
oldTime()
rho oldTime ()
rhoPhi()
surfaceScalarField rhoPhi (IOobject("rhoPhi", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , fvc::interpolate(rho) * phi)
interface()
interfaceProperties interface (alpha1 , U , thermo-> transportPropertiesDict())
Referenced by lduPrimitiveMesh::gather(), if(), if(), if(), procLduInterface::procLduInterface(), reconstructionSchemes::surface(), and oversetFvMeshBase::updateAddressing().
turbulence()
autoPtr< incompressible::turbulenceModel > turbulence (incompressible::turbulenceModel::New(U, phi, thermo()))
setRefCell()
setRefCell (p , p_rgh , pimple. dict(), pRefCell , pRefValue)
if()
if (p_rgh. needReference())
Definition at line 109 of file createFields.H.
References gh, p, p_rgh, pRefCell, pRefValue, and rho.
setFluxRequired() [1/2]
mesh setFluxRequired (p_rgh. name())
setFluxRequired() [2/2]
mesh setFluxRequired (alpha1. name())
Prt()
dimensionedScalar Prt ("Prt" , dimless , thermo-> transportPropertiesDict())
kappaEff()
volScalarField kappaEff (IOobject("kappaEff", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , thermo-> kappa())
rhoCp()
volScalarField rhoCp (IOobject("rhoCp", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , rho *thermo-> Cp())
Variable Documentation
mixture
Info<< "Creating temperaturePhaseChangeTwoPhaseMixture\n" << endl;autoPtr<temperaturePhaseChangeTwoPhaseMixture> mixture
Initial value:
=
    temperaturePhaseChangeTwoPhaseMixture::New(thermo(), mesh)
Definition at line 39 of file createFields.H.
Referenced by for(), if(), if(), if(), if(), if(), if(), and while().
rho1
const dimensionedScalar& rho1 = thermo->rho1()
Definition at line 46 of file createFields.H.
rho2
const dimensionedScalar& rho2 = thermo->rho2()
Definition at line 47 of file createFields.H.
p
volScalarField& p = thermo->p()
Definition at line 96 of file createFields.H.
pRefCell
label pRefCell = 0
Definition at line 98 of file createFields.H.
pRefValue
scalar pRefValue = 0.0
Definition at line 99 of file createFields.H.