OpenFOAM: applications/solvers/lagrangian/icoUncoupledKinematicParcelFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);singlePhaseTransportModel laminarTransport(U, phi);dimensionedScalar rhoInfValue("rhoInf", dimDensity, laminarTransport);volScalarField rhoInf(IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, rhoInfValue);autoPtr< incompressible::turbulenceModel > turbulence (incompressible::turbulenceModel::New(U, phi, laminarTransport))
volScalarField mu (IOobject("mu", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), laminarTransport.nu() *rhoInfValue)
const word kinematicCloudName (args.getOrDefault< word >("cloud", "kinematicCloud"))
if (Hheader.typeHeaderOk< volVectorField >(true))
IOobject HdotGradHheader ("HdotGradH", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE)
if (HdotGradHheader.typeHeaderOk< volVectorField >(true))
Variables
Info<< "Constructing kinematicCloud "<< kinematicCloudName<< endl;basicKinematicCollidingCloud kinematicCloud(kinematicCloudName, rhoInf, U, mu, g);IOobject Hheader("H", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE);autoPtr< volVectorField > HPtr
autoPtr< volVectorField > HdotGradHPtr
Function Documentation
turbulence()
Info<< "Reading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);singlePhaseTransportModel laminarTransport(U, phi);dimensionedScalar rhoInfValue("rhoInf", dimDensity, laminarTransport);volScalarField rhoInf(IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, rhoInfValue);autoPtr< incompressible::turbulenceModel > turbulence (incompressible::turbulenceModel::New(U, phi, laminarTransport))
mu()
volScalarField mu (IOobject("mu", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , laminarTransport.nu() * rhoInfValue)
kinematicCloudName()
const word kinematicCloudName (args.getOrDefault< word > "cloud", "kinematicCloud")
if() [1/2]
if (Hheader.typeHeaderOk< volVectorField > true)
Definition at line 86 of file createFields.H.
References HPtr, and mesh.
HdotGradHheader()
IOobject HdotGradHheader ("HdotGradH" , runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::AUTO_WRITE)
Referenced by if().
if() [2/2]
if (HdotGradHheader.typeHeaderOk< volVectorField > true)
Definition at line 104 of file createFields.H.
References HdotGradHheader(), HdotGradHPtr, and mesh.
Variable Documentation
HPtr
Info<< "Constructing kinematicCloud " << kinematicCloudName << endl;basicKinematicCollidingCloud kinematicCloud(kinematicCloudName, rhoInf, U, mu, g);IOobject Hheader("H", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE);autoPtr<volVectorField> HPtr
Definition at line 84 of file createFields.H.
Referenced by if().
HdotGradHPtr
autoPtr<volVectorField> HdotGradHPtr
Definition at line 102 of file createFields.H.
Referenced by if().