OpenFOAM: applications/solvers/multiphase/interFoam/overInterDyMFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading field p_rgh\n"<< endl;volScalarField p_rgh(IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);{ wordHashSet &nonInt=const_cast< wordHashSet & > (Stencil::New(mesh).nonInterpolatedFields())
nonInt insert ("HbyA")
nonInt insert ("grad(p_rgh)")
nonInt insert ("nHat")
nonInt insert ("surfaceIntegrate(nHatf)")
nonInt insert ("surfaceIntegrate(phi+meshPhi)")
nonInt insert ("surfaceIntegrate(phi)")
nonInt insert ("surfaceIntegrate(phiHbyA)")
nonInt insert ("surfaceSum(((S|magSf)*S)")
nonInt insert ("surfaceIntegrate(((rAUf*magSf)*snGradCorr(p_rgh)))")
nonInt insert ("cellMask")
nonInt insert ("cellDisplacement")
nonInt insert ("interpolatedCells")
nonInt insert ("cellInterpolationWeight")
nonInt insert ("pcorr")
Info<< "Reading transportProperties\n"<< endl;immiscibleIncompressibleTwoPhaseMixture mixture(U, phi);volScalarField &alpha1(mixture.alpha1());volScalarField &alpha2(mixture.alpha2());const dimensionedScalar &rho1=mixture.rho1();const dimensionedScalar &rho2=mixture.rho2();volScalarField rho(IOobject("rho", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT), alpha1 *rho1+alpha2 *rho2);rho.oldTime();surfaceScalarField rhoPhi(IOobject("rhoPhi", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), fvc::interpolate(rho) *phi);autoPtr< incompressible::turbulenceModel > turbulence (incompressible::turbulenceModel::New(U, phi, mixture))
volScalarField p (IOobject("p", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), p_rgh+rho *gh)
setRefCell (p, p_rgh, pimple.dict(), pRefCell, pRefValue)
if (p_rgh.needReference())
mesh setFluxRequired (p_rgh.name())
mesh setFluxRequired (alpha1.name())
Variables
label pRefCell = 0
scalar pRefValue = 0.0
Function Documentation
Info<< "Reading field p_rgh\n"<< endl;volScalarField p_rgh(IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);{ wordHashSet &nonInt=const_cast< wordHashSet & >()
Info<< "Reading field p_rgh\n"<< endl;volScalarField p_rgh(IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);{ wordHashSet &nonInt=const_cast< wordHashSet & > (Stencil::New(mesh).nonInterpolatedFields())
insert() [1/14]
nonInt insert ("HbyA")
insert() [2/14]
nonInt insert ("grad(p_rgh)")
insert() [3/14]
nonInt insert ("nHat")
insert() [4/14]
nonInt insert ("surfaceIntegrate(nHatf)")
insert() [5/14]
nonInt insert ("surfaceIntegrate(phi+meshPhi)")
insert() [6/14]
nonInt insert ("surfaceIntegrate(phi)")
insert() [7/14]
nonInt insert ("surfaceIntegrate(phiHbyA)")
insert() [8/14]
nonInt insert ()
Referenced by IOobjectList::add(), IOobjectList::add(), multivariateSurfaceInterpolationScheme< Type >::fieldTable::add(), distribution::add(), boundaryRegion::append(), cellTable::append(), HashSet< Key, Hash >::assignMany(), atomicWeightTable::atomicWeightTable(), HashSet< labelPairPair >::cbegin(), dynamicIndexedOctree< Type >::dynamicIndexedOctree(), HashSet< Key, Hash >::HashSet(), HashSet< labelPairPair >::HashSet(), HashSet< Key, Hash >::HashSet(), HashSet< Key, Hash >::HashSet(), HashSet< Key, Hash >::HashSet(), HashSet< Key, Hash >::HashSet(), HashSet< labelPairPair >::HashSet(), HashSet< Key, Hash >::insert(), edge::insert(), HashPtrTable< T, Key, Hash >::insert(), edge::insert(), HashSet< Key, Hash >::insert(), edge::insert(), HashSet< Key, Hash >::insert(), edge::insert(), distribution::insertMissingKeys(), IOobjectList::IOobjectList(), CV2D::movePoint(), HashTable< T, Key, Hash >::operator+=(), PtrListDictionary< phaseModel >::PtrListDictionary(), HashSet< Key, Hash >::set(), HashSet< Key, Hash >::set(), PtrListDictionary< phaseModel >::set(), PtrListDictionary< T >::set(), HashSet< Key, Hash >::set(), HashSet< Key, Hash >::set(), HashSet< Key, Hash >::set(), HashSet< Key, Hash >::setMany(), faceCollapser::setRefinement(), and VarName::stripInvalid().
insert() [9/14]
nonInt insert ("surfaceIntegrate(((rAUf*magSf)*snGradCorr(p_rgh)))")
insert() [10/14]
nonInt insert ("cellMask")
insert() [11/14]
nonInt insert ("cellDisplacement")
insert() [12/14]
nonInt insert ("interpolatedCells")
insert() [13/14]
nonInt insert ("cellInterpolationWeight")
insert() [14/14]
nonInt insert ("pcorr")
turbulence()
Info<< "Reading transportProperties\n"<< endl;immiscibleIncompressibleTwoPhaseMixture mixture(U, phi);volScalarField &alpha1(mixture.alpha1());volScalarField &alpha2(mixture.alpha2());const dimensionedScalar &rho1=mixture.rho1();const dimensionedScalar &rho2=mixture.rho2();volScalarField rho(IOobject("rho", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT), alpha1 *rho1+alpha2 *rho2);rho.oldTime();surfaceScalarField rhoPhi(IOobject("rhoPhi", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), fvc::interpolate(rho) *phi);autoPtr< incompressible::turbulenceModel > turbulence (incompressible::turbulenceModel::New(U, phi, mixture))
p()
volScalarField p (IOobject("p", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , p_rgh+rho * gh)
setRefCell()
setRefCell (p , p_rgh , pimple. dict(), pRefCell , pRefValue)
if()
if (p_rgh. needReference())
Definition at line 142 of file createFields.H.
References gh, p, p_rgh, pRefCell, pRefValue, and rho.
setFluxRequired() [1/2]
mesh setFluxRequired (p_rgh. name())
setFluxRequired() [2/2]
mesh setFluxRequired (alpha1. name())
Variable Documentation
pRefCell
label pRefCell = 0
Definition at line 131 of file createFields.H.
pRefValue
scalar pRefValue = 0.0
Definition at line 132 of file createFields.H.