OpenFOAM: applications/solvers/combustion/chemFoam/solveChemistry.H File Reference
solveChemistry.H File Reference
Variables
dtChem = chemistry.solve(runTime.deltaT().value())
scalar Qdot = chemistry.Qdot()()[0]/rho[0]
integratedHeat = Qdot*runTime.deltaT().value()
Variable Documentation
dtChem
dtChem = chemistry.solve(runTime.deltaT().value())
Definition at line 1 of file solveChemistry.H.
Qdot
scalar Qdot = chemistry.Qdot()()[0]/rho[0]
Definition at line 2 of file solveChemistry.H.
Referenced by greyMeanAbsorptionEmission::ECont(), wideBandAbsorptionEmission::ECont(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), diffusionMulticomponent< ReactionThermo, ThermoType >::Qdot(), StandardChemistryModel< ReactionThermo, ThermoType >::Qdot(), and solidChemistryModel< CompType, SolidThermo >::Qdot().
integratedHeat
integratedHeat = Qdot*runTime.deltaT().value()
Definition at line 3 of file solveChemistry.H.