OpenFOAM: src/dynamicFaMesh/interfaceTrackingFvMesh/solveBulkSurfactant.H File Reference
solveBulkSurfactant.H File Reference
Functions
if (C.boundaryField()[fsPatchIndex()].type()==fixedGradientFvPatchScalarField::typeName)
fvScalarMatrix CEqn (fvm::ddt(C)+fvm::div(phi(), C, "div(phi,C)") - fvm::laplacian(D, C, "laplacian(D,C)"))
CEqn solve ()
Variables
const dimensionedScalar & D = surfactant().bulkDiffusion()
scalar ka = surfactant().adsorptionCoeff().value()
scalar kb = surfactant().desorptionCoeff().value()
scalar CsInf = surfactant().saturatedConc().value()
const scalarField & Cs
else
Function Documentation
if()
if (C. boundaryField().type()[fsPatchIndex()] = = fixedGradientFvPatchScalarField::typeName)
Definition at line 15 of file solveBulkSurfactant.H.
References Cs, CsInf, D, ka, and kb.
CEqn()
fvScalarMatrix CEqn (fvm::ddt(C)+fvm::div(phi(), C, "div(phi,C)") - fvm::laplacian(D, C, "laplacian(D,C)"))
solve()
E2Eqn solve ()
Referenced by P1::calculate(), SprayCloud< Foam::DSMCCloud >::checkParcelProperties(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::correct(), kL< BasicTurbulenceModel >::correct(), motionDirectionalDiffusivity::correct(), adjointSpalartAllmaras::correct(), radiativeIntensityRay::correct(), kkLOmega::correct(), LamBremhorstKE::correct(), LienCubicKE::correct(), LienLeschziner::correct(), qZeta::correct(), ShihQuadraticKE::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), SpalartAllmarasBase< BasicEddyViscosityModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), EBRSM< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kEpsilonPhitF< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::correct(), relaxation::correct(), Poisson::correct(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), CollidingCloud< CloudType >::evolve(), KinematicCloud< CloudType >::evolve(), MPPICCloud< CloudType >::evolve(), ThermoCloud< CloudType >::evolve(), kinematicThinFilm::evolveRegion(), for(), if(), if(), if(), if(), if(), if(), lduMatrix::solver::scalarSolve(), faMatrix< Type >::faSolver::solve(), faMatrix< Type >::solve(), fvMatrix< Type >::fvSolver::solve(), fvMatrix< Type >::solve(), StandardChemistryModel< ReactionThermo, ThermoType >::solve(), TDACChemistryModel< ReactionThermo, ThermoType >::solve(), LLTMatrix< Type >::solve(), adaptiveSolver::solve(), StandardChemistryModel< ReactionThermo, ThermoType >::solve(), TDACChemistryModel< ReactionThermo, ThermoType >::solve(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), ODESolver::solve(), LLTMatrix< Type >::solve(), LUscalarMatrix::solve(), Foam::solve(), ODESolver::solve(), ODESolver::solve(), smoothSolver::solve(), kinematicSingleLayer::solveContinuity(), thermoSingleLayer::solveEnergy(), kinematicSingleLayer::solveMomentum(), fvMatrix< Type >::solver(), fvMatrix< Type >::solveSegregatedOrCoupled(), while(), and while().
Variable Documentation
D
const dimensionedScalar& D = surfactant().bulkDiffusion()
Definition at line 4 of file solveBulkSurfactant.H.
Referenced by faMatrix< Type >::A(), fvMatrix< Type >::A(), PrintTable< KeyType, DataType >::add(), InterfaceCompositionModel< Thermo, OtherThermo >::addMDotL(), viscousDissipation::addSup(), Barycentric< Cmpt >::Barycentric(), COxidationMurphyShaddix< CloudType >::calculate(), dynamicKEqn< BasicTurbulenceModel >::Ce(), dynamicKEqn< BasicTurbulenceModel >::Ce(), chemPointISAT< CompType, ThermoType >::chemPointISAT(), dynamicKEqn< BasicTurbulenceModel >::Ck(), motionDirectionalDiffusivity::correct(), kineticTheoryModel::correct(), kkLOmega::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), EBRSM< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), directionalPressureGradientExplicitSource::correct(), dynamicKEqn< BasicTurbulenceModel >::correctNut(), cubicEqn::cubicEqn(), InterfaceCompositionModel< Thermo, OtherThermo >::D(), iC3H8O::D(), nC3H8O::D(), InterfaceCompositionModel< Thermo, OtherThermo >::Dfrom(), InterfaceCompositionModel< Thermo, OtherThermo >::Dto(), scalarTransport::execute(), turbulentDispersionModel::F(), turbulentDispersionModel::Ff(), if(), Foam::interpolate(), Foam::Math::invIncGamma(), Smagorinsky< BasicTurbulenceModel >::k(), interfaceHeatResistance< Thermo, OtherThermo >::Kexp(), JohnsonJacksonSchaeffer::nu(), Schaeffer::nu(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFfs(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiFs(), ParticleDose< CloudType >::postEvolve(), ArdenBuck::pSatPrime(), cutFaceAdvect::quadAreaCoeffs(), faMatrix< Type >::relax(), fvMatrix< Type >::relax(), Foam::fvc::spreadSource(), porousBafflePressureFvPatchField::updateCoeffs(), Foam::Xinterpolate(), and PengRobinsonGas< Specie >::Z().
ka
scalar ka = surfactant().adsorptionCoeff().value()
Definition at line 6 of file solveBulkSurfactant.H.
Referenced by if().
kb
scalar kb = surfactant().desorptionCoeff().value()
Definition at line 7 of file solveBulkSurfactant.H.
Referenced by BrownianMotionForce< CloudType >::calcCoupled(), adjointkOmegaSST::dR_dF1(), if(), and adjointkOmegaSST::kaEqnSourceFromCDkOmega().
CsInf
scalar CsInf = surfactant().saturatedConc().value()
Definition at line 8 of file solveBulkSurfactant.H.
Referenced by if().
Cs
const scalarField& Cs
Initial value:
=
        surfactantConcentration().internalField()
Definition at line 10 of file solveBulkSurfactant.H.
Referenced by ReactingHeterogeneousParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), ReactingParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), ReactingParcel< ParcelType >::calcPhaseChange(), LiquidEvaporation< CloudType >::calculate(), ReactingParcel< ParcelType >::correctSurfaceValues(), if(), and laminar::Su().
else
else
Initial value:
{
        FatalErrorInFunction
            << "Bulk concentration boundary condition "
            << "at the free-surface patch is not "
            << fixedGradientFvPatchScalarField::typeName
            << exit(FatalError)
Definition at line 29 of file solveBulkSurfactant.H.
Referenced by fileStat::dmodTime().