OpenFOAM: applications/solvers/combustion/PDRFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading thermophysical properties\n"<< endl;autoPtr< psiuReactionThermo > pThermo (psiuReactionThermo::New(mesh))
thermo validate (args.executable(), "ha", "ea")
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
Info<< "min(b) = "<< min(b).value()<< endl;Info<< "\nReading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());Info<< "Creating turbulence model\n"<< endl;autoPtr< compressible::RASModel > turbulence (compressible::New< compressible::RASModel >(rho, U, phi, thermo))
Info<< "Creating the unstrained laminar flame speed\n"<< endl;autoPtr< laminarFlameSpeed > unstrainedLaminarFlameSpeed (laminarFlameSpeed::New(thermo))
if (composition.contains("ft"))
fields add (b)
fields add (thermo.he())
flameWrinkling addXi (fields)
Variables
psiuReactionThermo & thermo = pThermo()
basicSpecieMixture & composition = thermo.composition()
volScalarField & p = thermo.p()
volScalarField & b = composition.Y("b")
Info<< "Reading strained laminar flame speed field Su\n"<< endl;volScalarField Su(IOobject("Su", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field betav\n"<< endl;volScalarField betav(IOobject("betav", mesh.facesInstance(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE), mesh);Info<< "Reading field Lobs\n"<< endl;volScalarField Lobs(IOobject("Lobs", mesh.facesInstance(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE), mesh);Info<< "Reading field CT\n"<< endl;volSymmTensorField CT(IOobject("CT", mesh.facesInstance(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE), mesh);Info<< "Reading field Nv\n"<< endl;volScalarField Nv(IOobject("Nv", mesh.facesInstance(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE), mesh);Info<< "Reading field nsv\n"<< endl;volSymmTensorField nsv(IOobject("nsv", mesh.facesInstance(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE), mesh);IOdictionary PDRProperties(IOobject("PDRProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));autoPtr< PDRDragModel > drag
autoPtr< XiModel > flameWrinkling
Info<<"CalculatingturbulentflamespeedfieldSt\n"<< endl;volScalarFieldSt(IOobject("St", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), flameWrinkling->Xi() *Su);multivariateSurfaceInterpolationScheme< scalar >::fieldTable fields
Function Documentation
pThermo()
Info<< "Reading thermophysical properties\n"<< endl;autoPtr< psiuReactionThermo > pThermo (psiuReactionThermo::New(mesh))
validate()
thermo validate (args. executable(), "ha" , "ea")
rho()
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
turbulence()
Info<< "min(b) = "<< min(b).value()<< endl;Info<< "\nReading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());Info<< "Creating turbulence model\n"<< endl;autoPtr< compressible::RASModel > turbulence (compressible::New< compressible::RASModel > rho, U, phi, thermo)
unstrainedLaminarFlameSpeed()
Info<< "Creating the unstrained laminar flame speed\n"<< endl;autoPtr< laminarFlameSpeed > unstrainedLaminarFlameSpeed (laminarFlameSpeed::New(thermo))
Referenced by if().
if()
if (composition. contains"ft")
Definition at line 207 of file createFields.H.
References composition, and fields.
add() [1/2]
fields add (b)
add() [2/2]
fields add (thermo. he())
addXi()
flameWrinkling addXi (fields)
Variable Documentation
thermo
psiuReactionThermo& thermo = pThermo()
Definition at line 7 of file createFields.H.
composition
basicSpecieMixture& composition = thermo.composition()
Definition at line 10 of file createFields.H.
p
volScalarField& p = thermo.p()
Definition at line 25 of file createFields.H.
b
volScalarField& b = composition.Y("b")
Definition at line 27 of file createFields.H.
Referenced by greyMeanAbsorptionEmission::aCont(), wideBandAbsorptionEmission::aCont(), LuoSvendsen::addToBinaryBreakupRate(), SubStrings< StringType >::append(), Foam::appendTriLabels(), triangle2D::area(), Foam::vectorTools::areAcute(), Foam::areaInvDistSqrWeightedNormal(), triPoints::areaNormal(), triFace::areaNormal(), Foam::vectorTools::areObtuse(), Foam::vectorTools::areOrthogonal(), Foam::vectorTools::areParallel(), Foam::FieldOps::assign(), Foam::FieldOps::assign(), BarycentricTensor< Cmpt >::BarycentricTensor(), tetIndices::barycentricToPoint(), linePoints::box(), tetPoints::box(), triPoints::box(), triFace::box(), linePoints::centre(), triPoints::centre(), triFace::centre(), Foam::checkDims(), orientedType::checkType(), Foam::checkTypes(), tetrahedron< Point, PointRef >::circumCentre(), tetrahedron< Point, PointRef >::circumRadius(), WallCollisionRecord< vector >::collisionData(), face::compare(), Pair< T >::compare(), tetIndices::compare(), SSG< BasicTurbulenceModel >::correct(), Foam::vectorTools::cosPhi(), cyclicPolyPatch::coupledEdges(), cyclicPolyPatch::coupledPoints(), PengRobinsonGas< Specie >::Cp(), PengRobinsonGas< Specie >::CpMCv(), cubicEqn::cubicEqn(), PengRobinsonGas< Specie >::Cv(), Foam::vectorTools::degAngleBetween(), cubicEqn::derivative(), quadraticEqn::derivative(), Vector2D< scalar >::dist(), dmat_uniform(), pairPotentialList::dr(), triFace::edgeDirection(), faMesh::edgeLengthCorrection(), triFace::edges(), Foam::eigenValues(), Foam::eigenValues(), globalIndexAndTransform::encodeTransformIndex(), pairPotentialList::energy(), Foam::equal(), Foam::equal(), cubicEqn::error(), linearEqn::error(), quadraticEqn::error(), Pstream::exchange(), Foam::expandLeadingTag(), NURBS3DSurface::findClosestSurfacePoint(), NURBS3DSurface::findClosestSurfacePoint(), searchableCone::findLine(), searchableCylinder::findLine(), searchableSphere::findLine(), searchableCone::findLineAny(), searchableCylinder::findLineAny(), searchableSphere::findLineAny(), Foam::findTimeIndex(), triPoints::flip(), for(), forAll(), pairPotentialList::force(), Foam::getSTLpoint(), triFace::good(), Foam::HasherInt(), Foam::HSV_to_RGB(), if(), if(), Foam::interpolate(), topoBoolSet::invert(), Vector2D< Cmpt >::isClose(), Smagorinsky< BasicTurbulenceModel >::k(), reader::options::keepFluid(), reader::options::keepPorous(), reader::options::keepSolid(), Foam::LAB_to_XYZ(), Foam::labToMsh(), LBFGS::LBFGSUpdate(), Foam::lerp(), Foam::lerp(), Foam::lerp(), Foam::lerp(), Foam::lerp(), Foam::lerp(), Foam::lerp(), Foam::lerp(), Foam::lerp(), Vector2D< scalar >::less_yx(), Vector< Cmpt >::less_yzx(), Vector< Cmpt >::less_zxy(), linearEqn::linearEqn(), triangle2D::lineIntersectionPoint(), triangle2D::lineIntersects(), linePoints::ln(), linePoints::mag(), line< Point, PointRef >::mag(), voxelMeshSearch::makeMesh(), processorPolyPatch::matchFace(), Foam::max(), Foam::max(), stdFoam::max(), Foam::max(), normal::meanValue(), reader::options::mergeInterfaces(), blockMesh::mesh(), Foam::min(), Foam::min(), stdFoam::min(), Foam::min(), homogeneousMixture< ThermoType >::mixture(), inhomogeneousMixture< ThermoType >::mixture(), egrMixture< ThermoType >::mixture(), slidingInterface::modifyMotionPoints(), Moment< Type >::Moment(), token::compound::moved(), Switch::name(), line< Point, PointRef >::nearestDist(), line< Point, PointRef >::nearestDist(), McCowan::newtonRapsonF1(), Foam::notEqual(), offsetSurface::offsetSurface(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator!=(), Foam::operator&(), Foam::operator&(), Foam::operator&(), MinMax< T >::operator&=(), seriesLess::operator()(), Instant< T >::less::operator()(), lessProcPatches::operator()(), structuredRenumber::layerLess::operator()(), SortableListDRGEP< Type >::less::operator()(), SortableListEFA< Type >::more::operator()(), normalLess::operator()(), UList< T >::less::operator()(), UList< T >::greater::operator()(), less< ListType >::operator()(), greater< ListType >::operator()(), natural_sort::less< T >::operator()(), natural_sort::greater< T >::operator()(), vectorLessOp::operator()(), UPtrList< T >::less::operator()(), UPtrList< T >::greater::operator()(), globalIndexAndTransform::less::operator()(), minFirstOp< T1 >::operator()(), maxFirstOp< T1 >::operator()(), swakModuloOp::operator()(), compareOp< Scalar >::operator()(), equalOp< Scalar >::operator()(), notEqualOp< Scalar >::operator()(), boolAndOp< T >::operator()(), boolOrOp< T >::operator()(), boolXorOp< T >::operator()(), compareOp< T >::operator()(), lerpOp1< T >::operator()(), nameOp< T >::operator()(), typeOp< T >::operator()(), lerpOp< T >::operator()(), UPtrList< T >::value_compare< Compare >::operator()(), minFirstOp< T1 >::operator()(), maxFirstOp< T1 >::operator()(), worldConnectBitOrEq::operator()(), plusEqOp< Key, HashType >::operator()(), plusEqOp< T, Key, HashType >::operator()(), Foam::operator*(), Foam::operator*(), exprResult::operator*=(), Foam::operator+(), Foam::operator+(), Boussinesq< Specie >::operator+=(), exprResult::operator+=(), MinMax< T >::operator+=(), Foam::operator-(), Foam::operator-(), HashSet< labelPairPair >::operator-=(), Foam::operator<(), Foam::operator<(), Foam::operator<(), Foam::operator<(), Foam::operator<(), Foam::operator<(), Foam::operator<(), Foam::operator<(), Foam::operator<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<=(), Foam::operator<=(), Foam::operator<=(), Foam::operator<=(), Foam::operator<=(), Foam::operator<=(), Foam::operator<=(), Switch::operator=(), Boussinesq< Specie >::operator=(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator==(), Foam::operator>(), Foam::operator>(), Foam::operator>(), Foam::operator>(), Foam::operator>(), Foam::operator>(), Foam::operator>(), Foam::operator>(), Foam::operator>=(), Foam::operator>=(), Foam::operator>=(), Foam::operator>=(), Foam::operator>=(), Foam::operator>=(), Foam::operator>=(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator^(), Foam::operator|(), updateMethod::outerProd(), MinMax< T >::overlaps(), pairPotentialList::pairPotentialFunction(), plane::plane(), plane::planePlaneIntersect(), triFace::points(), Foam::pow(), Foam::pow(), quadraticEqn::quadraticEqn(), Foam::vectorTools::radAngleBetween(), triFace::rcEdges(), pairPotentialList::rCut(), pairPotentialList::rCutSqr(), pairPotentialList::rCutSqr(), NASedgeFormat::read(), NASsurfaceFormat< Face >::read(), reader::options::removeBaffles(), reader::options::renameInterfaces(), MinMax< scalar >::reset(), triFace::reverseFace(), Foam::RGB_to_HSV(), Foam::RGB_to_XYZ(), pairPotentialList::rMin(), linearEqn::roots(), face::sameVertices(), normal::sample(), multiNormal::sample(), QRMatrix< MatrixType >::solve(), SortList< T >::sort(), Foam::sort(), Foam::sqrtSumSqr(), Foam::Swap(), Foam::Swap(), Foam::Swap(), Foam::Swap(), Foam::Swap(), swapec(), Foam::FieldOps::ternary(), Foam::FieldOps::ternary(), Foam::FieldOps::ternarySelect(), Foam::FieldOps::ternarySelect(), Foam::FieldOps::ternarySelect(), Foam::FieldOps::ternarySelect(), Foam::FieldOps::ternarySelect(), tetPoints::tet(), tetPoints::tetPoints(), Foam::BitOps::toc(), particle< Type >::trackToMovingTri(), globalIndexAndTransform::transformIndicesForPatches(), triPoints::tri(), triFace::tri(), triangle2D::triangle2D(), triFace::triFace(), lduAddressing::triIndex(), fvMeshPrimitiveLduAddressing::triIndex(), triPoints::triPoints(), triPoints::unitNormal(), triFace::unitNormal(), linePoints::unitVec(), pressurePIDControlInletVelocityFvPatchVectorField::updateCoeffs(), humidityTemperatureCoupledMixedFvPatchScalarField::updateCoeffs(), regIOobject::upToDate(), regIOobject::upToDate(), regIOobject::upToDate(), reader::options::useNumberedNames(), basicThermo::validate(), basicThermo::validate(), basicThermo::validate(), cubicEqn::value(), linearEqn::value(), quadraticEqn::value(), vbedg(), linePoints::vec(), line< Point, PointRef >::vec(), triPoints::vecA(), triPoints::vecC(), XiReactionRate::write(), Foam::XYZ_to_LAB(), Foam::XYZ_to_RGB(), PengRobinsonGas< Specie >::Z(), and bufferedAccumulator< scalar >::~bufferedAccumulator().
drag
Info<< "Reading strained laminar flame speed field Su\n" << endl;volScalarField Su(IOobject ("Su", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field betav\n" << endl;volScalarField betav(IOobject ("betav", mesh.facesInstance(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE), mesh);Info<< "Reading field Lobs\n" << endl;volScalarField Lobs(IOobject ("Lobs", mesh.facesInstance(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE), mesh);Info<< "Reading field CT\n" << endl;volSymmTensorField CT(IOobject ("CT", mesh.facesInstance(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE), mesh);Info<< "Reading field Nv\n" << endl;volScalarField Nv(IOobject ("Nv", mesh.facesInstance(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE), mesh);Info<< "Reading field nsv\n" << endl;volSymmTensorField nsv(IOobject ("nsv", mesh.facesInstance(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE), mesh);IOdictionary PDRProperties(IOobject ("PDRProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));autoPtr<PDRDragModel> drag
Initial value:
= PDRDragModel::New
(
    PDRProperties,
    *turbulence,
    rho,
    U,
    phi
)
Definition at line 167 of file createFields.H.
Referenced by NicenoKEqn< BasicTurbulenceModel >::bubbleG(), LaheyKEpsilon< BasicTurbulenceModel >::bubbleG(), mixtureKEpsilon< BasicTurbulenceModel >::bubbleG(), Burns::D(), and Gosman::D().
flameWrinkling
autoPtr<XiModel> flameWrinkling
Initial value:
= XiModel::New
(
    PDRProperties,
    thermo,
    *turbulence,
    Su,
    rho,
    b,
    phi
)
Definition at line 179 of file createFields.H.
Referenced by if().
fields
Info<<"CalculatingturbulentflamespeedfieldSt\n"<<endl;volScalarFieldSt(IOobject("St",runTime.timeName(),mesh,IOobject::NO_READ,IOobject::AUTO_WRITE),flameWrinkling->Xi()*Su);multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 205 of file createFields.H.