OpenFOAM: applications/solvers/heatTransfer/buoyantBoussinesqSimpleFoam/readTransportProperties.H File Reference
readTransportProperties.H File Reference
Functions
singlePhaseTransportModel laminarTransport (U, phi)
dimensionedScalar beta ("beta", dimless/dimTemperature, laminarTransport)
dimensionedScalar TRef ("TRef", dimTemperature, laminarTransport)
dimensionedScalar Pr ("Pr", dimless, laminarTransport)
dimensionedScalar Prt ("Prt", dimless, laminarTransport)
Function Documentation
laminarTransport()
singlePhaseTransportModel laminarTransport (U , phi)
Referenced by RASModelVariables::devReff(), and SpalartAllmaras::nutJacobianVar1().
beta()
dimensionedScalar beta ("beta" , dimless/ dimTemperature, laminarTransport)
Referenced by valueAverageBase::calc(), ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), fieldAverageItem::calculateMeanField(), fieldAverageItem::calculatePrime2MeanField(), TrajectoryCollision< CloudType >::collideParcels(), conjugateGradient::computeCorrection(), rotorDiskSource::constructGeometry(), kineticTheoryModel::correct(), kOmegaSSTBase< BasicEddyViscosityModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::Ct2(), if(), triangleFuncs::intersectAxesBundle(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), cutFaceAdvect::quadAreaCoeffs(), FPCG::scalarSolve(), PBiCGStab::scalarSolve(), PCG::scalarSolve(), PPCG::scalarSolveCG(), ConeNozzleInjection< CloudType >::setPositionAndCell(), ConeInjection< CloudType >::setProperties(), PBiCCCG< Type, DType, LUType >::solve(), PBiCICG< Type, DType, LUType >::solve(), PCICG< Type, DType, LUType >::solve(), PBiCG::solve(), cutFaceAdvect::timeIntegratedArea(), cutFaceAdvect::timeIntegratedArea(), FacePostProcessing< CloudType >::write(), and ParticleCollector< CloudType >::write().
TRef()
dimensionedScalar TRef ("TRef" , dimTemperature , laminarTransport)
Referenced by KinematicSurfaceFilm< CloudType >::transferParcel().
Pr()
dimensionedScalar Pr ("Pr" , dimless , laminarTransport)
Referenced by ThermoParcel< ParcelType >::calc(), alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::calcAlphat(), ThermoParcel< ParcelType >::calcHeatTransfer(), ReactingParcel< ParcelType >::calcPhaseChange(), ThermoParcel< ParcelType >::calcSurfaceValues(), thermoCoupleProbes::derivatives(), PengRobinsonGas< Specie >::E(), PengRobinsonGas< Specie >::H(), HeatTransferModel< CloudType >::htc(), RanzMarshall< CloudType >::Nu(), ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::operator()(), FallOffReactionRate< ReactionRate, FallOffFunction >::operator()(), SRIFallOffFunction::operator()(), TroeFallOffFunction::operator()(), HeatTransferCoeff< CloudType >::postEvolve(), NusseltNumber< CloudType >::postEvolve(), ThermoReynoldsNumber< CloudType >::postEvolve(), PengRobinsonGas< Specie >::S(), atmAlphatkWallFunctionFvPatchScalarField::updateCoeffs(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), convectiveHeatTransferFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
Prt()
dimensionedScalar Prt ("Prt" , dimless , laminarTransport)
Referenced by atmAlphatkWallFunctionFvPatchScalarField::updateCoeffs().