OpenFOAM: applications/solvers/finiteArea/liquidFilmFoam/readTransportProperties.H File Reference
readTransportProperties.H File Reference
Functions
IOdictionary transportProperties (IOobject("transportProperties", runTime.constant(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
dimensionedScalar mug ("mug", dimViscosity, transportProperties)
dimensionedScalar mul ("mul", dimViscosity, transportProperties)
dimensionedScalar rhog ("rhog", dimDensity, transportProperties)
dimensionedScalar rhol ("rhol", dimDensity, transportProperties)
dimensionedScalar sigma ("sigma", dimMass/sqr(dimTime), transportProperties)
dimensionedScalar h0 ("h0", dimLength, transportProperties)
Function Documentation
transportProperties()
IOdictionary transportProperties (IOobject("transportProperties", runTime.constant(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
Referenced by ReynoldsAnalogy::devReff(), filmTurbulenceModel::devRhoReff(), forces::devRhoReff(), forAll(), if(), forces::mu(), vibrationShellFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
mug()
dimensionedScalar mug ("mug" , dimViscosity , transportProperties)
mul()
dimensionedScalar mul ("mul" , dimViscosity , transportProperties)
rhog()
dimensionedScalar rhog ("rhog" , dimDensity , transportProperties)
Referenced by LiquidEvapFuchsKnudsen< CloudType >::calculate(), and diffusionGasEvaporation< Thermo, OtherThermo >::Kexp().
rhol()
dimensionedScalar rhol ("rhol" , dimDensity , transportProperties)
sigma()
dimensionedScalar sigma ("sigma" , dimMass/ sqrdimTime, transportProperties)
h0()
dimensionedScalar h0 ("h0" , dimLength , transportProperties)