OpenFOAM: applications/solvers/incompressible/adjointShapeOptimizationFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading field p\n"<< endl;volScalarField p(IOobject("p", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);label pRefCell=0;scalar pRefValue=0.0;setRefCell(p, simple.dict(), pRefCell, pRefValue);mesh.setFluxRequired(p.name());Info<< "Reading field pa\n"<< endl;volScalarField pa(IOobject("pa", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field Ua\n"<< endl;volVectorField Ua(IOobject("Ua", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);label paRefCell=0;scalar paRefValue=0.0;setRefCell(pa, simple.dict(), paRefCell, paRefValue);mesh.setFluxRequired(pa.name());singlePhaseTransportModel laminarTransport(U, phi);autoPtr< incompressible::turbulenceModel > turbulence (incompressible::turbulenceModel::New(U, phi, laminarTransport))
dimensionedScalar zeroSensitivity (dimVelocity *dimVelocity, Zero)
dimensionedScalar zeroAlpha (dimless/dimTime, Zero)
dimensionedScalar lambda ("lambda", dimTime/sqr(dimLength), laminarTransport)
dimensionedScalar alphaMax ("alphaMax", dimless/dimTime, laminarTransport)
volScalarField alpha (IOobject("alpha", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE), lambda *max(Ua &U, zeroSensitivity))
zeroCells (alpha, inletCells)
Variables
const labelList & inletCells = mesh.boundary()["inlet"].faceCells()
Function Documentation
turbulence()
Info<< "Reading field p\n"<< endl;volScalarField p(IOobject("p", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);label pRefCell=0;scalar pRefValue=0.0;setRefCell(p, simple.dict(), pRefCell, pRefValue);mesh.setFluxRequired(p.name());Info<< "Reading field pa\n"<< endl;volScalarField pa(IOobject("pa", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field Ua\n"<< endl;volVectorField Ua(IOobject("Ua", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);label paRefCell=0;scalar paRefValue=0.0;setRefCell(pa, simple.dict(), paRefCell, paRefValue);mesh.setFluxRequired(pa.name());singlePhaseTransportModel laminarTransport(U, phi);autoPtr< incompressible::turbulenceModel > turbulence (incompressible::turbulenceModel::New(U, phi, laminarTransport))
zeroSensitivity()
dimensionedScalar zeroSensitivity (dimVelocity * dimVelocity, Zero)
zeroAlpha()
dimensionedScalar zeroAlpha (dimless/ dimTime, Zero)
lambda()
dimensionedScalar lambda ("lambda" , dimTime/ sqrdimLength, laminarTransport)
Referenced by fourthGrad< Type >::calcGrad(), Foam::calcTE18(), tetrahedron< Point, PointRef >::circumCentre(), tetrahedron< Point, PointRef >::circumRadius(), cubic< Type >::correction(), blackBodyEmission::EblambdaT(), eddy::eddy(), edgeInterpolationScheme< Type >::euclidianInterpolate(), for(), Foam::Math::incGammaRatio_Q(), edgeInterpolationScheme< Type >::interpolate(), segregated::K(), Foam::MULES::limit(), Foam::MULES::limitCorr(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), Foam::MULES::limitSum(), Foam::MULES::limitSum(), blockEdge::linearPosition(), polyLine::localParameter(), arcEdge::position(), bezier::position(), BSpline::position(), polyLineEdge::position(), CatmullRomSpline::position(), lineEdge::position(), polyLine::position(), projectEdge::position(), polyline::positionAndDirection(), kOmegaSSTLM< BasicTurbulenceModel >::ReThetat0(), fieldSmoother::smoothLambdaMuDisplacement(), surfaceAlignedSBRStressFvMotionSolver::solve(), and rigidBodyMotion::transformPoints().
alphaMax()
dimensionedScalar alphaMax ("alphaMax" , dimless/ dimTime, laminarTransport)
Referenced by JohnsonJackson::frictionalPressure(), JohnsonJacksonSchaeffer::frictionalPressure(), JohnsonJackson::frictionalPressurePrime(), JohnsonJacksonSchaeffer::frictionalPressurePrime(), LunSavage::g0(), SinclairJackson::g0(), LunSavage::g0prime(), SinclairJackson::g0prime(), KinematicCloud< CloudType >::info(), MPPICCloud< CloudType >::info(), randomCoalescence::R(), randomCoalescence::R(), JohnsonJacksonParticleSlipFvPatchVectorField::updateCoeffs(), and JohnsonJacksonParticleThetaFvPatchScalarField::updateCoeffs().
alpha()
volScalarField alpha (IOobject("alpha", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE) , lambda * maxUa &U, zeroSensitivity)
zeroCells()
zeroCells (alpha , inletCells)
Referenced by ATCModel::createLimiter().
Variable Documentation
inletCells
const labelList& inletCells = mesh.boundary()["inlet"].faceCells()
Definition at line 106 of file createFields.H.