OpenFOAM: applications/solvers/multiphase/reactingMultiphaseEulerFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Creating phaseSystem\n"<< endl;autoPtr< multiphaseSystem > fluidPtr (multiphaseSystem::New(mesh))
dimensionedScalar pMin ("pMin", dimPressure, fluid)
Variables
multiphaseSystem & fluid = fluidPtr()
multiphaseSystem::phaseModelList & phases = fluid.phases()
volScalarField & p = phases[0].thermoRef().p()
Function Documentation
fluidPtr()
Info<< "Creating phaseSystem\n"<< endl;autoPtr< multiphaseSystem > fluidPtr (multiphaseSystem::New(mesh))
pMin()
dimensionedScalar pMin ("pMin" , dimPressure , fluid)
Variable Documentation
fluid
multiphaseSystem& fluid = fluidPtr()
Definition at line 11 of file createFields.H.
phases
multiphaseSystem::phaseModelList& phases = fluid.phases()
Definition at line 12 of file createFields.H.
Referenced by forAll(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::iDmdt(), if(), MomentumTransferPhaseSystem< BasePhaseSystem >::partialElimination(), MomentumTransferPhaseSystem< BasePhaseSystem >::partialEliminationf(), MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi(), and while().
p
volScalarField& p = phases[0].thermoRef().p()
Definition at line 23 of file createFields.H.