OpenFOAM: applications/solvers/electromagnetics/magneticFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading field psi\n"<< endl;volScalarField psi(IOobject("psi", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading transportProperties\n"<< endl;IOdictionary transportProperties(IOobject("transportProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));List< magnet > magnets (transportProperties.lookup("magnets"))
surfaceScalarField murf (IOobject("murf", runTime.timeName(), mesh), mesh, dimensionedScalar("one", dimless, 1.0))
surfaceScalarField Mrf (IOobject("Mrf", runTime.timeName(), mesh), mesh, dimensionedScalar(dimensionSet(0, 1, 0, 0, 0, 1, 0), Zero))
Mrf setOriented (true)
forAll (magnets, i)
Function Documentation
magnets()
Info<< "Reading field psi\n"<< endl; volScalarField psi(IOobject("psi", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh); Info<< "Reading transportProperties\n"<< endl; IOdictionary transportProperties(IOobject("transportProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE)); List< magnet > magnets (transportProperties. lookup"magnets")
Referenced by forAll().
murf()
surfaceScalarField murf (IOobject("murf", runTime.timeName(), mesh) , mesh , dimensionedScalar("one", dimless, 1.0))
Referenced by forAll().
Mrf()
surfaceScalarField Mrf (IOobject("Mrf", runTime.timeName(), mesh) , mesh , dimensionedScalar(dimensionSet(0, 1, 0, 0, 0, 1, 0), Zero))
Referenced by forAll().
setOriented()
Mrf setOriented (true)
Referenced by orientedType::operator*=(), and orientedType::operator/=().
forAll()
forAll (magnets , i)
Definition at line 56 of file createFields.H.
References FatalIOErrorInFunction, magnets(), mesh, Mrf(), murf(), and transportProperties().