OpenFOAM: applications/solvers/compressible/rhoCentralFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading thermophysical properties\n"<< endl;autoPtr< psiThermo > pThermo (psiThermo::New(mesh))
Info<< "Reading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);volScalarField rho(IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho());volVectorField rhoU(IOobject("rhoU", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho *U);volScalarField rhoE(IOobject("rhoE", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho *(e+0.5 *magSqr(U)));surfaceScalarField pos(IOobject("pos", runTime.timeName(), mesh), mesh, dimensionedScalar("pos", dimless, 1.0));surfaceScalarField neg(IOobject("neg", runTime.timeName(), mesh), mesh, dimensionedScalar("neg", dimless, -1.0));surfaceScalarField phi("phi", fvc::flux(rhoU));Info<< "Creating turbulence model\n"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Variables
psiThermo & thermo = pThermo()
volScalarField & e = thermo.he()
Function Documentation
pThermo()
Info<< "Reading thermophysical properties\n"<< endl;autoPtr< psiThermo > pThermo (psiThermo::New(mesh))
turbulence()
Info<< "Reading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);volScalarField rho(IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho());volVectorField rhoU(IOobject("rhoU", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho *U);volScalarField rhoE(IOobject("rhoE", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho *(e+0.5 *magSqr(U)));surfaceScalarField pos(IOobject("pos", runTime.timeName(), mesh), mesh, dimensionedScalar("pos", dimless, 1.0));surfaceScalarField neg(IOobject("neg", runTime.timeName(), mesh), mesh, dimensionedScalar("neg", dimless, -1.0));surfaceScalarField phi("phi", fvc::flux(rhoU));Info<< "Creating turbulence model\n"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Variable Documentation
thermo
psiThermo& thermo = pThermo()
Definition at line 9 of file createFields.H.
e
volScalarField& e = thermo.he()
Definition at line 11 of file createFields.H.
Referenced by dictionary::add(), extendedEdgeMesh::add(), vtmWriter::add(), velocityDampingConstraint::addDamping(), triSurfaceMesh::addFaceToEdge(), edgeSurface::addIntersectionEdges(), columnFvMeshInfo::addLocalPatches(), Foam::adjustPhi(), SubStrings< StringType >::append(), pointConstraint::applyConstraint(), motionSmootherAlgo::avg(), meshRefinement::blockLeakFaces(), PDRblock::blockMeshDict(), treeDataEdge::bounds(), treeDataEdge::bounds(), Foam::boundsImpl(), treeDataEdge::boxes(), nearWallFields::calcAddressing(), holeToFace::calcClosure(), enrichedPatch::calcEnrichedFaces(), addPatchCellLayer::calcExtrudeInfo(), polyDualMesh::calcFeatures(), processorFaPatch::calcGeometry(), curvatureSeparation::calcInvR1(), curvatureSeparation::calcInvR1(), cutCell::calcIsoFacePointsFromEdges(), atmNutkWallFunctionFvPatchScalarField::calcNut(), atmNutUWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), faPatch::calcPointEdges(), faPatch::calcPointLabels(), createShellMesh::calcPointRegions(), Foam::calcQE11(), snappySnapDriver::calcSnapDistance(), viewFactor::calculate(), LiquidEvaporationBoil< CloudType >::calculate(), cellVolumeWeightMethod::calculateAddressing(), correctedCellVolumeWeightMethod::calculateAddressing(), meshRefinement::calculateEdgeWeights(), parcelSelection::calculateFilter(), nutUBlendedWallFunctionFvPatchScalarField::calcUTau(), IshiiZuber::CdRe(), polyMesh::cellTree(), treeDataEdge::centres(), layerAdditionRemoval::changeTopology(), searchableSurfaces::checkIntersection(), hexRef8::checkMesh(), PatchTools::checkOrientation(), PrimitivePatch< FaceList, PointField >::checkTopology(), noiseModel::checkUniformTimeStep(), triSurfaceTools::collapseEdges(), triSurfaceTools::collapseEdges(), pointConstraint::combine(), blockEdge::compare(), blockEdge::compare(), Foam::consistentEdge(), molecule::constantProperties::constantProperties(), Enum< injectionMethod >::contains(), edgeVertex::coord(), Foam::copyFilteredDict(), diffusionMulticomponent< ReactionThermo, ThermoType >::correct(), EDC< ReactionThermo >::correct(), patchPatchDist::correct(), kineticTheoryModel::correct(), limitHeight::correct(), limitVelocity::correct(), relaxation::correct(), curvatureSeparation::correct(), limitTemperature::correct(), limitTurbulenceViscosity::correct(), limitVelocity::correct(), twoDPointCorrector::correctDisplacement(), removePoints::countPointUsage(), cyclicPolyPatch::coupledEdges(), Foam::createTree(), wallBoundedParticle::crossEdgeConnectedFace(), motionSmootherAlgo::curPoints(), triSurfaceTools::curvatures(), geomCellLooper::cut(), extendedEdgeMesh::cut(), hierarchGeomDecomp::decompose(), hierarchGeomDecomp::decompose(), faMeshDecomposition::decomposeMesh(), faPatch::delta(), dictionary::dictionary(), dictionary::dictionary(), dictionary::digest(), dimensioned< Type >::dimensioned(), dimensioned< scalar >::dimensioned(), meshRefinement::distribute(), fileStat::dmodTime(), dtris2(), vtmWriter::dump(), solidAbsorption::e(), multiBandZoneAbsorptionEmission::eCont(), eddy::eddy(), face::edgeDirection(), triFace::edgeDirection(), extendedEdgeMesh::edgeDirection(), primitiveMesh::edgeFaces(), hexCell::edges(), edgeSurface::edgeSurface(), directionInfo::edgeToFaceIndex(), PointEdgeWave< Type, TrackingData >::edgeToPoint(), extendedEdgeMesh::edgeTree(), triSurfaceMesh::edgeTree(), extendedEdgeMesh::edgeTreesByType(), vtmWriter::empty(), Enum< injectionMethod >::empty(), pairPotentialList::energy(), pairPotential::energy(), expressionEntry::evaluate(), boolEntry::evaluate(), dimensionedScalarEntry::evaluate(), stringEntry::evaluate(), proudmanAcousticPower::execute(), ifeqEntry::execute(), Foam::expandLeadingTag(), Field< Type >::Field(), Field< T >::Field(), Enum< EnumType >::find(), PrimitivePatch< FaceList, PointField >::findEdge(), Foam::meshTools::findEdge(), Foam::meshTools::findEdge(), patchProbes::findElements(), Foam::blockMeshTools::findEntry(), searchableSurfaceWithGaps::findLine(), mappedPatchBase::findLocalSamples(), searchableSurfacesQueries::findNearest(), cyclicACMIFvPatchField< Type >::fixesValue(), kOmegaSSTLM< BasicTurbulenceModel >::Flength(), extendedEdgeMesh::flipNormals(), forAll(), Enum< EnumType >::found(), SinclairJackson::g0prime(), Enum< EnumType >::get(), triSurfaceTools::getEdge(), cellLooper::getFirstVertEdge(), lduMatrix::smoother::getName(), lduMatrix::preconditioner::getName(), boundaryMesh::getNearest(), combineFaces::getOutsideFace(), triSurfaceTools::getVertexTriangles(), triSurfaceTools::getVertexVertices(), treeDataFace::getVolumeType(), treeDataPrimitivePatch< PatchType >::getVolumeType(), Lun::granularPressureCoeff(), SyamlalRogersOBrien::granularPressureCoeff(), Lun::granularPressureCoeffPrime(), SyamlalRogersOBrien::granularPressureCoeffPrime(), triSurfaceTools::greenRefine(), BreenWestwater::htcFilmBoil(), Bromley::htcFilmBoil(), if(), viewFactor::initialise(), processorFaPatch::initUpdateMesh(), triangleFuncs::intersectBb(), intersectedSurface::intersectedSurface(), Foam::Math::invIncGamma(), isoSurfaceTopo::isoSurfaceTopo(), TDACChemistryModel< ReactionThermo, ThermoType >::jacobian(), GidaspowSchillerNaumann::K(), Gidaspow::kappa(), HrenyaSinclair::kappa(), Syamlal::kappa(), interfaceHeatResistance< Thermo, OtherThermo >::Kexp(), interfaceOxideRate< Thermo, OtherThermo >::Kexp(), dictionary::keys(), kineticGasEvaporation< Thermo, OtherThermo >::kineticGasEvaporation(), Foam::levelSetFraction(), LuoSvendsen::LuoSvendsen(), edgeCollapser::markSmallEdges(), Foam::markupBoundaryPoints(), triSurfaceTools::maxEdge(), dictionary::merge(), edgeMesh::mergeEdges(), surfaceIntersection::mergeEdges(), edgeMesh::mergePoints(), surfaceIntersection::mergePoints(), PrimitivePatch< FaceList, PointField >::meshEdge(), cellShape::meshEdges(), triSurfaceTools::minEdge(), hexCell::modelEdges(), tetCell::modelEdges(), motionSmootherAlgo::modifyMotionPoints(), InterfaceCompositionModel< Thermo, OtherThermo >::MwMixture(), line< Point, PointRef >::nearestDist(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), polyBoundaryMesh::neighbourEdges(), lduMatrix::preconditioner::New(), lduMatrix::smoother::New(), fvMeshTools::newMesh(), faMeshTools::newMesh(), multiphaseInterSystem::nHatfv(), Gidaspow::nu(), HrenyaSinclair::nu(), Syamlal::nu(), multiphaseInterSystem::nVolHatfv(), entry::operator!=(), Enum< EnumType >::operator()(), treeDataPrimitivePatch< PatchType >::findSelfIntersectOp::operator()(), dictionary::operator+=(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), Foam::operator<<(), dictionary::operator<<=(), dictionary::operator=(), eddy::operator=(), entry::operator=(), entry::operator==(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Foam::operator>>(), Enum< EnumType >::operator[](), dictionary::operator|=(), cell::opposingFace(), triSurfaceTools::oppositeEdge(), triSurfaceTools::oppositeVertex(), Foam::meshTools::otherEdge(), searchableRotatedBox::overlaps(), speciesSorptionFvPatchScalarField::patchSource(), cuttingPlane::performCut(), cuttingSurface::performCut(), Foam::MatrixTools::pinv(), extendedEdgeMesh::pointTree(), projectCurveEdge::position(), projectEdge::position(), Foam::printPatchEdges(), SpalartAllmarasDES< BasicTurbulenceModel >::psi(), sampledSet::pushIn(), genericPatchFieldBase::putEntry(), singleStepCombustion< ReactionThermo, ThermoType >::R(), IATEsource::Re(), adjointEikonalSolver::read(), adjointMeshMovementSolver::read(), age::read(), comfort::read(), wallBoundedStreamLine::read(), energySpectrum::read(), BilgerMixtureFraction::read(), ObukhovLength::read(), STDMD::read(), NASedgeFormat::read(), OBJedgeFormat::read(), STARCDedgeFormat::read(), mappedPatchBase::readDict(), dimensionSet::readEntry(), refinementFeatures::regionEdgeTrees(), edgeMesh::regions(), vtmWriter::repair(), Foam::resolveLabel(), Foam::reverse(), VollerPrakash::S(), pairPotential::scaledEnergy(), doubleSigmoid::scaleEnergy(), shifted::scaleEnergy(), shiftedForce::scaleEnergy(), sigmoid::scaleEnergy(), pairPotential::scaleEnergy(), extendedEdgeMesh::select(), Foam::serializeProjectEdge(), dictionary::set(), boundaryMesh::setFeatureEdges(), meshCutter::setRefinement(), tetDecomposer::setRefinement(), addPatchCellLayer::setRefinement(), meshCutAndRemove::setRefinement(), hexRef8::setRefinement(), faceCollapser::setRefinement(), removeFaces::setRefinement(), boundaryCutter::setRefinement(), createShellMesh::setRefinement(), vtmWriter::size(), Foam::Sn(), twoPhaseSystem::solve(), EulerImplicit< ChemistryModel >::solve(), Foam::solve(), thermoSingleLayer::solveEnergy(), SprayParcel< ParcelType >::solveTABEq(), PatchTools::sortedEdgeFaces(), surfaceFeatures::subsetPlane(), dictionary::substituteKeyword(), dictionary::substituteScopedKeyword(), triSurfaceTools::surfaceSide(), swapec(), syncTools::syncEdgeMap(), syncTools::syncPointMap(), Schroeder::TDNB(), fvMeshDistribute::testField(), absoluteInternalEnergy< Thermo >::THE(), sensibleInternalEnergy< Thermo >::THE(), cutFaceAdvect::timeIntegratedArea(), cutFaceAdvect::timeIntegratedArea(), cutFaceAdvect::timeIntegratedFaceFlux(), dictionary::toc(), expressionEntry::toExpr(), boolEntry::toExpr(), stringEntry::toExpr(), dictionary::tokens(), triSurfaceSearch::tree(), triSurfaceRegionSearch::treeByRegion(), triangulation_plot_eps(), pointConstraint::unconstrainedDirections(), inverseDistance::update(), trackingInverseDistance::update(), sampledMeshedSurface::update(), LISAAtomization< CloudType >::update(), directionInfo::updateCell(), atmAlphatkWallFunctionFvPatchScalarField::updateCoeffs(), activeBaffleVelocityFvPatchVectorField::updateCoeffs(), activePressureForceBaffleVelocityFvPatchVectorField::updateCoeffs(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), patchFaceOrientation::updateEdge(), externalPointEdgePoint::updateEdge(), pointEdgePoint::updateEdge(), patchEdgeFaceRegions::updateEdge(), patchEdgeFaceInfo::updateEdge(), patchFaceOrientation::updateFace(), patchEdgeFaceRegions::updateFace(), boundaryCutter::updateMesh(), meshCutAndRemove::updateMesh(), meshCutter::updateMesh(), processorFaPatch::updateMesh(), vbedg(), velocityGroup::velocityGroup(), triSurfaceTools::vertexTriads(), surfaceIteratorIso::vofCutCell(), surfaceIteratorPLIC::vofCutCell(), voxelMeshSearch::voxelMeshSearch(), cuttingSurfaceBase::walkCellCuts(), meshRefinement::weightedSum(), multiFieldValue::write(), OBJstream::write(), vtmWriter::write(), OBJedgeFormat::write(), GTSsurfaceFormat< Face >::write(), GTSsurfaceFormat< Face >::write(), OBJstream::write(), OBJstream::write(), OBJstream::write(), timeVaryingMappedFixedValuePointPatchField< Type >::write(), genericPolyPatch::write(), Foam::blockMeshTools::write(), surfaceLocation::write(), edgeVertex::writeCut(), externalCoupledTemperatureMixedFvPatchScalarField::writeData(), pairPotential::writeEnergyAndForceTables(), MappedFile< Type >::writeEntries(), dictionary::writeEntries(), extendedEdgeMesh::writeObj(), surfaceFeatures::writeObj(), Foam::meshTools::writeOBJ(), AABBTreeBase::writeOBJ(), indexedOctreeBase::writeOBJ(), and Foam::writeObjEdges().