OpenFOAM: applications/solvers/finiteArea/sphereSurfactantFoam/createFaFields.H File Reference
createFaFields.H File Reference
Functions
Info<< "Reading field Cs"<< endl;areaScalarField Cs(IOobject("Cs", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), aMesh);dimensionedScalar Cs0("Cs0", dimMass/dimArea, 1.0);const areaVectorField &R=aMesh.areaCentres();Cs=Cs0 *(1.0+R.component(vector::X)/mag(R));dimensionedScalar Ds("Ds", dimViscosity, 1.0);areaVectorField Us(IOobject("Us", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), aMesh, dimensionedVector(dimVelocity, Zero));dimensioned< scalar > Uinf ("Uinf", dimVelocity, 1.0)
forAll (Us, faceI)
Us boundaryFieldRef ().evaluateCoupled< coupledFaPatch >()
edgeScalarField phis (IOobject("phis", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), linearEdgeInterpolate(Us) &aMesh.Le())
Variables
Us = aMesh.faceAreaNormals()*(aMesh.faceAreaNormals() & Us)
Function Documentation
Uinf()
Info<< "Reading field Cs"<< endl;areaScalarField Cs(IOobject("Cs", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), aMesh);dimensionedScalar Cs0("Cs0", dimMass/dimArea, 1.0);const areaVectorField &R=aMesh.areaCentres();Cs=Cs0 *(1.0+R.component(vector::X)/mag(R));dimensionedScalar Ds("Ds", dimViscosity, 1.0);areaVectorField Us(IOobject("Us", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), aMesh, dimensionedVector(dimVelocity, Zero));dimensioned< scalar > Uinf ("Uinf" , dimVelocity , 1. 0)
Referenced by forAll().
forAll()
forAll (Us , faceI)
Definition at line 39 of file createFaFields.H.
References R, Uinf(), Us, and x.
boundaryFieldRef()
Us boundaryFieldRef ()
Referenced by oversetFvMeshBase::addInterpolation(), adjointkOmegaSST::addWallFunctionTerms(), adjointkOmegaSST::adjointMeanFlowSource(), GeometricField< Type, PatchField, GeoMesh >::clamp_max(), GeometricField< Type, PatchField, GeoMesh >::clamp_min(), GeometricField< Type, PatchField, GeoMesh >::clamp_range(), GeometricField< Type, PatchField, GeoMesh >::clamp_range(), wallDistData< TransferType >::correct(), adjointkOmegaSST::correct(), Foam::MULES::limitSum(), Foam::MULES::limitSum(), GeometricField< Type, PatchField, GeoMesh >::negate(), GeometricField< Type, PatchField, GeoMesh >::normalise(), GeometricField< Type, PatchField, GeoMesh >::operator=(), GeometricField< Type, PatchField, GeoMesh >::operator=(), GeometricField< Type, PatchField, GeoMesh >::operator=(), GeometricField< Type, PatchField, GeoMesh >::operator==(), GeometricField< Type, PatchField, GeoMesh >::operator==(), GeometricField< Type, PatchField, GeoMesh >::replace(), sizeGroup::sizeGroup(), oversetFvMeshBase::solveOverset(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), and reconstructedDistanceFunction::updateContactAngle().
phis()
edgeScalarField phis (IOobject("phis", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , linearEdgeInterpolate(Us) &aMesh.Le())
Referenced by if(), realizableKE< BasicTurbulenceModel >::rCmu(), and fluxSummary::surfaceModeWrite().
Variable Documentation
Us
Us = aMesh.faceAreaNormals()*(aMesh.faceAreaNormals() & Us)
Definition at line 52 of file createFaFields.H.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), interfaceTrackingFvMesh::correctUsBoundaryConditions(), forAll(), interfaceTrackingFvMesh::freeSurfaceSnGradU(), interfaceTrackingFvMesh::freeSurfaceSnGradUn(), kOmegaSSTLM< BasicTurbulenceModel >::Fthetat(), realizableKE< BasicTurbulenceModel >::rCmu(), kOmegaSSTLM< BasicTurbulenceModel >::ReThetat0(), and interfaceTrackingFvMesh::updateUs().