OpenFOAM: applications/solvers/finiteArea/sphereSurfactantFoam/createVolFields.H File Reference
createVolFields.H File Reference
Functions
const volSurfaceMapping vsm (aMesh)
volScalarField Cvf (IOobject("Cvf", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar(dimless/dimLength, Zero))
vsm mapToVolume (Cs, Cvf.boundaryFieldRef())
Cvf write ()
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedVector(dimVelocity, Zero))
vsm mapToVolume (Us, U.boundaryFieldRef())
Function Documentation
vsm()
const volSurfaceMapping vsm (aMesh)
Cvf()
volScalarField Cvf (IOobject("Cvf", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar(dimless/dimLength, Zero))
mapToVolume() [1/2]
vsm mapToVolume (Cs , Cvf. boundaryFieldRef())
Referenced by volSurfaceMapping::mapToVolume(), volSurfaceMapping::mapToVolume(), volSurfaceMapping::mapToVolume(), volSurfaceMapping::mapToVolume(), and volSurfaceMapping::mapToVolume().
write()
Cvf write ()
U()
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedVector(dimVelocity, Zero))
mapToVolume() [2/2]
vsm mapToVolume (Us , U. boundaryFieldRef())