OpenFOAM: src/finiteVolume/cfdTools/general/include/alphaControls.H File Reference
alphaControls.H File Reference
Functions
label nAlphaCorr (alphaControls.get< label >("nAlphaCorr"))
label nAlphaSubCycles (alphaControls.get< label >("nAlphaSubCycles"))
bool MULESCorr (alphaControls.getOrDefault("MULESCorr", false))
bool alphaApplyPrevCorr (alphaControls.getOrDefault("alphaApplyPrevCorr", false))
scalar icAlpha (alphaControls.getOrDefault< scalar >("icAlpha", 0))
scalar scAlpha (alphaControls.getOrDefault< scalar >("scAlpha", 0))
Variables
const dictionary & alphaControls = mesh.solverDict(alpha1.name())
Function Documentation
nAlphaCorr()
label nAlphaCorr (alphaControls.get< label > "nAlphaCorr")
Referenced by twoPhaseSystem::solve(), and multiphaseSystem::solveAlphas().
nAlphaSubCycles()
label nAlphaSubCycles (alphaControls.get< label > "nAlphaSubCycles")
Referenced by if(), if(), localEulerDdt::localRSubDeltaT(), multiphaseSystem::solve(), and twoPhaseSystem::solve().
MULESCorr()
bool MULESCorr (alphaControls. getOrDefault"MULESCorr", false)
Referenced by for().
alphaApplyPrevCorr()
bool alphaApplyPrevCorr (alphaControls. getOrDefault"alphaApplyPrevCorr", false)
Referenced by if().
icAlpha()
scalar icAlpha (alphaControls.getOrDefault< scalar > "icAlpha", 0)
Referenced by if().
scAlpha()
scalar scAlpha (alphaControls.getOrDefault< scalar > "scAlpha", 0)
Referenced by if().
Variable Documentation
alphaControls
const dictionary& alphaControls = mesh.solverDict(alpha1.name())
Definition at line 1 of file alphaControls.H.
Referenced by multiphaseSystem::solve(), twoPhaseSystem::solve(), and multiphaseSystem::solveAlphas().