OpenFOAM: foamToVtkReportFields Class Reference
foamToVtkReportFields Class Reference
Collection of simple static methods for reporting field names by category, which is used by foamToVTK.
#include <reportFields.H>
Static Public Member Functions
template<class GeoField >
static void print (const char *msg, Ostream &os, const UPtrList< const GeoField > &flds)
static void print (const char *msg, Ostream &os, const wordList &fieldNames)
template<class FieldType >
static void print (const char *msg, Ostream &os, const IOobjectList &objects)
static void volume (Ostream &os, const IOobjectList &objects)
static void internal (Ostream &os, const IOobjectList &objects)
static void point (Ostream &os, const IOobjectList &objects)
static void area (Ostream &os, const IOobjectList &objects)
Detailed Description
Collection of simple static methods for reporting field names by category, which is used by foamToVTK.
Definition at line 47 of file reportFields.H.
Member Function Documentation
print() [1/3]
template<class GeoField > static void print (const char * msg, Ostream & os, const UPtrList< const GeoField > & flds) inline static
Definition at line 50 of file reportFields.H.
References Foam::endl(), fld(), os(), and UPtrList< T >::size().
Referenced by foamToVtkReportFields::print().
print() [2/3]
static void print (const char * msg, Ostream & os, const wordList & fieldNames) inline static
Definition at line 69 of file reportFields.H.
References Foam::endl(), os(), and UList< T >::size().
print() [3/3]
template<class FieldType > static void print (const char * msg, Ostream & os, const IOobjectList & objects) inline static
Definition at line 89 of file reportFields.H.
References os(), and foamToVtkReportFields::print().
volume()
static void volume (Ostream & os, const IOobjectList & objects) inline static
Definition at line 101 of file reportFields.H.
References os().
internal()
static void internal (Ostream & os, const IOobjectList & objects) inline static
Definition at line 127 of file reportFields.H.
References os().
point()
static void point (Ostream & os, const IOobjectList & objects) inline static
Definition at line 153 of file reportFields.H.
area()
static void area (Ostream & os, const IOobjectList & objects) inline static
Definition at line 159 of file reportFields.H.
References os().
The documentation for this class was generated from the following file:
applications/utilities/postProcessing/dataConversion/foamToVTK/reportFields.H