OpenFOAM: VectorSpaceOps< N, I > Class Template Reference
VectorSpaceOps< N, I > Class Template Reference
Operator functions for VectorSpace.
#include <VectorSpaceOps.H>
Static Public Member Functions
template<class V , class S , class EqOp >
static void eqOpS (V &vs, const S &s, EqOp eo)
template<class S , class V , class EqOp >
static void SeqOp (S &s, const V &vs, EqOp eo)
template<class V1 , class V2 , class EqOp >
static void eqOp (V1 &vs1, const V2 &vs2, EqOp eo)
template<class V , class V1 , class S , class Op >
static void opVS (V &vs, const V1 &vs1, const S &s, Op o)
template<class V , class S , class V1 , class Op >
static void opSV (V &vs, const S &s, const V1 &vs1, Op o)
template<class V , class V1 , class Op >
static void op (V &vs, const V1 &vs1, const V1 &vs2, Op o)
Detailed Description
template<direction N, direction I>
class Foam::VectorSpaceOps< N, I >
Operator functions for VectorSpace.
Definition at line 41 of file VectorSpaceOps.H.
Member Function Documentation
eqOpS()
template<direction N, direction I> template<class V , class S , class EqOp > static void eqOpS (V & vs, const S & s, EqOp eo) inline static
Definition at line 44 of file VectorSpaceOps.H.
References VectorSpaceOps< N, I >::eqOpS(), Foam::I, and s().
Referenced by VectorSpaceOps< N, I >::eqOpS(), VectorSpace< Form, Cmpt, Ncmpts >::operator*=(), VectorSpace< Form, Cmpt, Ncmpts >::operator/=(), VectorSpace< Form, Cmpt, Ncmpts >::operator=(), and VectorSpace< Form, Cmpt, Ncmpts >::VectorSpace().
SeqOp()
template<direction N, direction I> template<class S , class V , class EqOp > static void SeqOp (S & s, const V & vs, EqOp eo) inline static
Definition at line 51 of file VectorSpaceOps.H.
References Foam::I, s(), and VectorSpaceOps< N, I >::SeqOp().
Referenced by VectorSpaceOps< N, I >::SeqOp().
eqOp()
template<direction N, direction I> template<class V1 , class V2 , class EqOp > static void eqOp (V1 & vs1, const V2 & vs2, EqOp eo) inline static
Definition at line 58 of file VectorSpaceOps.H.
References VectorSpaceOps< N, I >::eqOp(), and Foam::I.
Referenced by VectorSpaceOps< N, I >::eqOp(), VectorSpace< Form, Cmpt, Ncmpts >::operator+=(), VectorSpace< Form, Cmpt, Ncmpts >::operator-=(), VectorSpace< Form, Cmpt, Ncmpts >::operator=(), VectorSpace< Form, Cmpt, Ncmpts >::VectorSpace(), and VectorSpace< Form, Cmpt, Ncmpts >::VectorSpace().
opVS()
template<direction N, direction I> template<class V , class V1 , class S , class Op > static void opVS (V & vs, const V1 & vs1, const S & s, Op o) inline static
Definition at line 66 of file VectorSpaceOps.H.
References Foam::I, VectorSpaceOps< N, I >::opVS(), and s().
Referenced by VectorSpaceOps< N, I >::opVS().
opSV()
template<direction N, direction I> template<class V , class S , class V1 , class Op > static void opSV (V & vs, const S & s, const V1 & vs1, Op o) inline static
Definition at line 73 of file VectorSpaceOps.H.
References Foam::I, VectorSpaceOps< N, I >::opSV(), and s().
Referenced by VectorSpaceOps< N, I >::opSV().
op()
template<direction N, direction I> template<class V , class V1 , class Op > static void op (V & vs, const V1 & vs1, const V1 & vs2, Op o) inline static
Definition at line 80 of file VectorSpaceOps.H.
References Foam::I, and VectorSpaceOps< N, I >::op().
Referenced by VectorSpaceOps< N, I >::op().
The documentation for this class was generated from the following file:
src/OpenFOAM/primitives/VectorSpace/VectorSpaceOps.H