OpenFOAM: minMaxMagEqOp< T > Struct Template Reference
minMaxMagEqOp< T > Struct Template Reference
#include <MinMaxOps.H>
Public Member Functions
scalarMinMax & operator() (scalarMinMax &x, const T &y) const
scalarMinMax & operator() (scalarMinMax &x, const MinMax< T > &y) const
scalarMinMax & operator() (scalarMinMax &x, const UList< T > &y) const
Detailed Description
template<class T>
struct Foam::minMaxMagEqOp< T >
Definition at line 306 of file MinMaxOps.H.
Member Function Documentation
operator()() [1/3]
template<class T > scalarMinMax & operator() (scalarMinMax & x, const T & y) const inline
Definition at line 308 of file MinMaxOps.H.
References Foam::mag(), Foam::minMaxMag(), x, and y.
operator()() [2/3]
template<class T > scalarMinMax & operator() (scalarMinMax & x, const MinMax< T > & y) const inline
Definition at line 314 of file MinMaxOps.H.
References Foam::add(), Foam::mag(), Foam::minMaxMag(), x, and y.
operator()() [3/3]
template<class T > scalarMinMax & operator() (scalarMinMax & x, const UList< T > & y) const inline
Definition at line 326 of file MinMaxOps.H.
References Foam::mag(), Foam::minMaxMag(), T, x, and y.
The documentation for this struct was generated from the following file:
src/OpenFOAM/primitives/ranges/MinMax/MinMaxOps.H