OpenFOAM: reuseTmpFieldField< Field, TypeR, Type1 > Struct Template Reference
reuseTmpFieldField< Field, TypeR, Type1 > Struct Template Reference
#include <FieldFieldReuseFunctions.H>
Static Public Member Functions
static tmp< FieldField< Field, TypeR > > New (const FieldField< Field, Type1 > &f1)
static tmp< FieldField< Field, TypeR > > New (const tmp< FieldField< Field, Type1 > > &tf1)
Detailed Description
template<template< class > class Field, class TypeR, class Type1>
struct Foam::reuseTmpFieldField< Field, TypeR, Type1 >
Definition at line 34 of file FieldFieldReuseFunctions.H.
Member Function Documentation
New() [1/2]
template<template< class > class Field, class TypeR , class Type1 > static tmp< FieldField< Field, TypeR > > New (const FieldField< Field, Type1 > & f1) inline static
Definition at line 37 of file FieldFieldReuseFunctions.H.
References FieldField< Field, Type >::NewCalculatedType().
Referenced by Foam::cmptAv(), Foam::cmptMax(), Foam::cmptMin(), Foam::mag(), Foam::magSqr(), Foam::New(), Foam::pow(), and Foam::sqr().
New() [2/2]
template<template< class > class Field, class TypeR , class Type1 > static tmp< FieldField< Field, TypeR > > New (const tmp< FieldField< Field, Type1 > > & tf1) inline static
Definition at line 46 of file FieldFieldReuseFunctions.H.
References FieldField< Field, Type >::NewCalculatedType().
The documentation for this struct was generated from the following file:
src/OpenFOAM/fields/FieldFields/FieldField/FieldFieldReuseFunctions.H