OpenFOAM: ABAQUSCore::readHelper Struct Reference
ABAQUSCore::readHelper Struct Reference
#include <ABAQUSCore.H>
Public Member Functions
readHelper (bool verbosity=false)
void clear ()
label addNewElset (const std::string &setName)
void read (ISstream &is)
label readPoints (ISstream &is)
label readElements (ISstream &is, const ABAQUSCore::shapeType shape, const label setId=0)
label readSurfaceElements (ISstream &is, const label setId=0)
void purge_solids ()
void compact_nodes ()
void renumber_elements_1to0 ()
Public Attributes
bool verbose_
DynamicList< point > points_
DynamicList< label > nodeIds_
DynamicList< labelList > connectivity_
DynamicList< label > elemIds_
DynamicList< ABAQUSCore::shapeType > elemTypes_
DynamicList< label > elsetIds_
HashTable< label, string > elsetMap_
Detailed Description
Definition at line 353 of file ABAQUSCore.H.
Constructor & Destructor Documentation
readHelper()
readHelper (bool verbosity = false) inline explicit
Definition at line 393 of file ABAQUSCore.H.
Member Function Documentation
clear()
void clear () inline
Definition at line 402 of file ABAQUSCore.H.
References PtrList< T >::clear(), DynamicList< T, SizeMin >::clear(), ABAQUSCore::readHelper::connectivity_, ABAQUSCore::readHelper::elemIds_, ABAQUSCore::readHelper::elemTypes_, ABAQUSCore::readHelper::elsetIds_, ABAQUSCore::readHelper::elsetMap_, ABAQUSCore::readHelper::nodeIds_, and ABAQUSCore::readHelper::points_.
addNewElset()
Foam::label addNewElset (const std::string & setName)
Definition at line 261 of file ABAQUSCore.C.
References forAllConstIters, string::null, PtrList< T >::set(), UPtrList< T >::size(), and Foam::stringOps::upper().
read()
void read (ISstream & is)
Definition at line 524 of file ABAQUSCore.C.
References clear(), UPtrList< T >::empty(), Foam::getIdentifier(), Foam::Info, Foam::InfoErr, Foam::nl, ABAQUSCore::nPoints(), Foam::skipComments(), and Foam::stringOps::upper().
Referenced by ABAQUSsurfaceFormat< Face >::read().
readPoints()
Foam::label readPoints (ISstream & is)
Definition at line 309 of file ABAQUSCore.C.
References PtrList< T >::append(), p, and UPtrList< T >::size().
readElements()
Foam::label readElements (ISstream & is, const ABAQUSCore::shapeType shape, const label setId = 0)
Definition at line 346 of file ABAQUSCore.C.
References Foam::appendCsvLabels(), ABAQUSCore::nPoints(), UPtrList< T >::size(), and Foam::Zero.
readSurfaceElements()
Foam::label readSurfaceElements (ISstream & is, const label setId = 0)
Definition at line 401 of file ABAQUSCore.C.
References ABAQUSCore::encodeSolidId(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::hex(), cellModel::HEX, Foam::Info, cellModel::modelFaces(), Foam::nl, cellModel::PRISM, cellModel::ref(), UPtrList< T >::size(), cellModel::TET, Foam::stringOps::upper(), and word::validate().
purge_solids()
void purge_solids ()
Definition at line 652 of file ABAQUSCore.C.
References forAll, Foam::inplaceSubset(), and List< T >::set().
Referenced by ABAQUSsurfaceFormat< Face >::read().
compact_nodes()
void compact_nodes ()
Definition at line 678 of file ABAQUSCore.C.
References PtrList< T >::clear(), forAll, Foam::inplaceRenumber(), Foam::inplaceReorder(), Foam::invert(), nPoints, and PtrList< T >::set().
Referenced by ABAQUSsurfaceFormat< Face >::read().
renumber_elements_1to0()
void renumber_elements_1to0 ()
Definition at line 772 of file ABAQUSCore.C.
Referenced by ABAQUSsurfaceFormat< Face >::read().
Member Data Documentation
verbose_
bool verbose_
Definition at line 358 of file ABAQUSCore.H.
points_
DynamicList<point> points_
Definition at line 364 of file ABAQUSCore.H.
Referenced by ABAQUSCore::readHelper::clear(), and ABAQUSsurfaceFormat< Face >::read().
nodeIds_
DynamicList<label> nodeIds_
Definition at line 367 of file ABAQUSCore.H.
Referenced by ABAQUSCore::readHelper::clear().
connectivity_
DynamicList<labelList> connectivity_
Definition at line 375 of file ABAQUSCore.H.
Referenced by ABAQUSCore::readHelper::clear(), and ABAQUSsurfaceFormat< Face >::read().
elemIds_
DynamicList<label> elemIds_
Definition at line 378 of file ABAQUSCore.H.
Referenced by ABAQUSCore::readHelper::clear(), and ABAQUSsurfaceFormat< Face >::read().
elemTypes_
DynamicList<ABAQUSCore::shapeType> elemTypes_
Definition at line 381 of file ABAQUSCore.H.
Referenced by ABAQUSCore::readHelper::clear().
elsetIds_
DynamicList<label> elsetIds_
Definition at line 384 of file ABAQUSCore.H.
Referenced by ABAQUSCore::readHelper::clear(), and ABAQUSsurfaceFormat< Face >::read().
elsetMap_
HashTable<label, string> elsetMap_
Definition at line 387 of file ABAQUSCore.H.
Referenced by ABAQUSCore::readHelper::clear(), and ABAQUSsurfaceFormat< Face >::read().
The documentation for this struct was generated from the following files:
src/fileFormats/abaqus/ABAQUSCore.H
src/fileFormats/abaqus/ABAQUSCore.C