OpenFOAM: natural_sort Struct Reference
natural_sort Struct Reference
#include <stringOpsSort.H>
Classes
struct greater
struct less
struct reverse
Public Member Functions
bool operator() (const std::string &s1, const std::string &s2) const
Static Public Member Functions
static int compare (const std::string &s1, const std::string &s2)
Detailed Description
Definition at line 58 of file stringOpsSort.H.
Member Function Documentation
compare()
static int compare (const std::string & s1, const std::string & s2) inline static
Definition at line 62 of file stringOpsSort.H.
References Foam::stringOps::natstrcmp().
Referenced by seriesLess::operator()(), natural_sort::less< T >::operator()(), natural_sort::greater< T >::operator()(), natural_sort::operator()(), and natural_sort::reverse::operator()().
operator()()
bool operator() (const std::string & s1, const std::string & s2) const inline
Definition at line 72 of file stringOpsSort.H.
References natural_sort::compare().
The documentation for this struct was generated from the following file:
src/OpenFOAM/primitives/strings/stringOps/stringOpsSort.H