OpenFOAM: LList< LListBase, T >::link Struct Reference
LList< LListBase, T >::link Struct Reference
#include <LList.H>
Public Member Functions
link (const T &elem)
link (T &&elem)
Static Public Member Functions
static T remove (typename LListBase::link *node)
static constexpr T * ptr (typename LListBase::link *node)
static constexpr const T * ptr (const typename LListBase::link *node)
static constexpr T & ref (typename LListBase::link *node)
static constexpr const T & ref (const typename LListBase::link *node)
Public Attributes
T val_
Detailed Description
template<class LListBase, class T>
struct Foam::LList< LListBase, T >::link
Definition at line 108 of file LList.H.
Constructor & Destructor Documentation
link() [1/2]
template<class LListBase , class T > link (const T & elem) inline
Definition at line 116 of file LList.H.
link() [2/2]
template<class LListBase , class T > link (T && elem) inline
Definition at line 122 of file LList.H.
Member Function Documentation
remove()
template<class LListBase , class T > static T remove (typename LListBase::link * node) inline static
Definition at line 129 of file LList.H.
References p, and T.
Referenced by LList< LListBase, T >::remove(), LList< LListBase, T >::remove(), and LList< LListBase, T >::removeHead().
ptr() [1/2]
template<class LListBase , class T > static constexpr T * ptr (typename LListBase::link * node) inline static constexpr
Definition at line 138 of file LList.H.
References LList< LListBase, T >::link::val_.
Referenced by LList< LListBase, T >::iterator::operator->(), LList< LListBase, T >::const_iterator::operator->(), LList< LListBase, T >::reverse_iterator::operator->(), and LList< LListBase, T >::const_reverse_iterator::operator->().
ptr() [2/2]
template<class LListBase , class T > static constexpr const T * ptr (const typename LListBase::link * node) inline static constexpr
Definition at line 144 of file LList.H.
References LList< LListBase, T >::link::val_.
ref() [1/2]
template<class LListBase , class T > static constexpr T & ref (typename LListBase::link * node) inline static constexpr
Definition at line 150 of file LList.H.
References LList< LListBase, T >::link::val_.
Referenced by LList< LListBase, T >::back(), LList< LListBase, T >::back(), LList< LListBase, T >::front(), LList< LListBase, T >::front(), LList< LListBase, T >::iterator::operator*(), LList< LListBase, T >::const_iterator::operator*(), LList< LListBase, T >::reverse_iterator::operator*(), and LList< LListBase, T >::const_reverse_iterator::operator*().
ref() [2/2]
template<class LListBase , class T > static constexpr const T & ref (const typename LListBase::link * node) inline static constexpr
Definition at line 156 of file LList.H.
References LList< LListBase, T >::link::val_.
Member Data Documentation
val_
template<class LListBase , class T > T val_
Definition at line 113 of file LList.H.
Referenced by LList< LListBase, T >::link::ptr(), LList< LListBase, T >::link::ptr(), LList< LListBase, T >::link::ref(), and LList< LListBase, T >::link::ref().
The documentation for this struct was generated from the following file:
src/OpenFOAM/containers/LinkedLists/accessTypes/LList/LList.H