OpenFOAM: src/lagrangian/molecularDynamics/molecule/mdTools/temperatureAndPressureVariables.H File Reference
temperatureAndPressureVariables.H File Reference
Provides accumulation variables for temperatureAndPressure.H.
Functions
if (Pstream::parRun())
Variables
vector accumulatedTotalLinearMomentum (Zero)
scalar accumulatedTotalMass = 0.0
scalar accumulatedTotalAngularKE = 0.0
scalar accumulatedTotalLinearKE = 0.0
scalar accumulatedTotalPE = 0.0
scalar accumulatedTotalrDotfSum = 0.0
label accumulatedNMols = 0
label accumulatedDOFs = 0
scalar averageTemperature = 0.0
scalar averagePressure = 0.0
const scalarField & cellVols = mesh.cellVolumes()
scalar meshVolume = sum(cellVols)
Detailed Description
Provides accumulation variables for temperatureAndPressure.H.
Original source file temperatureAndPressureVariables.H
Definition in file temperatureAndPressureVariables.H.
Function Documentation
if()
if (Pstream::parRun())
Definition at line 49 of file temperatureAndPressureVariables.H.
References meshVolume.
Variable Documentation
accumulatedTotalLinearMomentum
vector accumulatedTotalLinearMomentum(Zero) (Zero)
accumulatedTotalMass
scalar accumulatedTotalMass = 0.0
Definition at line 27 of file temperatureAndPressureVariables.H.
accumulatedTotalAngularKE
scalar accumulatedTotalAngularKE = 0.0
Definition at line 29 of file temperatureAndPressureVariables.H.
accumulatedTotalLinearKE
scalar accumulatedTotalLinearKE = 0.0
Definition at line 31 of file temperatureAndPressureVariables.H.
accumulatedTotalPE
scalar accumulatedTotalPE = 0.0
Definition at line 33 of file temperatureAndPressureVariables.H.
accumulatedTotalrDotfSum
scalar accumulatedTotalrDotfSum = 0.0
Definition at line 35 of file temperatureAndPressureVariables.H.
accumulatedNMols
label accumulatedNMols = 0
Definition at line 37 of file temperatureAndPressureVariables.H.
accumulatedDOFs
label accumulatedDOFs = 0
Definition at line 39 of file temperatureAndPressureVariables.H.
averageTemperature
scalar averageTemperature = 0.0
Definition at line 41 of file temperatureAndPressureVariables.H.
Referenced by if().
averagePressure
scalar averagePressure = 0.0
Definition at line 43 of file temperatureAndPressureVariables.H.
Referenced by if().
cellVols
const scalarField& cellVols = mesh.cellVolumes()
Definition at line 45 of file temperatureAndPressureVariables.H.
Referenced by primitiveMesh::calcCellCentresAndVols(), polyMesh::checkMeshMotion(), deltaBoundary::makeCellCentres_d(), primitiveMeshTools::makeCellCentresAndVols(), and primitiveMeshTools::updateCellCentresAndVols().
meshVolume
scalar meshVolume = sum(cellVols)
Definition at line 47 of file temperatureAndPressureVariables.H.
Referenced by if(), and if().