OpenFOAM: applications/solvers/multiphase/twoLiquidMixingFoam/alphaEqn.H File Reference
alphaEqn.H File Reference
Functions
surfaceScalarField alphaPhi (phi.name()+alpha1.name(), fvc::flux(phi, alpha1, alphaScheme))
Variables
rhoPhi = alphaPhi*(rho1 - rho2) + phi*rho2
Function Documentation
alphaPhi()
surfaceScalarField alphaPhi (phi. name)+alpha1.name(, fvc::flux(phi, alpha1, alphaScheme))
Referenced by phaseModel::correctInflowOutflow(), for(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), if(), if(), and if().
Variable Documentation
rhoPhi
rhoPhi = alphaPhi*(rho1 - rho2) + phi*rho2
Definition at line 25 of file alphaEqn.H.