OpenFOAM: applications/solvers/multiphase/twoPhaseEulerFoam/EEqns.H File Reference
EEqns.H File Reference
Functions
volScalarField Cpv1 ("Cpv1", thermo1.Cpv())
volScalarField Cpv2 ("Cpv2", thermo2.Cpv())
volScalarField Kh (fluid.Kh())
fvScalarMatrix E1Eqn (fvm::ddt(alpha1, rho1, he1)+fvm::div(alphaRhoPhi1, he1) - fvm::Sp(contErr1, he1)+fvc::ddt(alpha1, rho1, K1)+fvc::div(alphaRhoPhi1, K1) - contErr1 *K1+(he1.name()==thermo1.phasePropertyName("e") ? fvc::div(fvc::absolute(alphaPhi1, alpha1, U1), p)+p *fvc::ddt(alpha1) :-alpha1 *dpdt) - fvm::laplacian(fvc::interpolate(alpha1) *fvc::interpolate(thermo1.alphaEff(phase1.turbulence().mut())), he1))
E1Eqn relax ()
fvScalarMatrix E2Eqn (fvm::ddt(alpha2, rho2, he2)+fvm::div(alphaRhoPhi2, he2) - fvm::Sp(contErr2, he2)+fvc::ddt(alpha2, rho2, K2)+fvc::div(alphaRhoPhi2, K2) - contErr2 *K2+(he2.name()==thermo2.phasePropertyName("e") ? fvc::div(fvc::absolute(alphaPhi2, alpha2, U2), p)+p *fvc::ddt(alpha1) :-alpha2 *dpdt) - fvm::laplacian(fvc::interpolate(alpha2) *fvc::interpolate(thermo2.alphaEff(phase2.turbulence().mut())), he2))
fvOptions constrain (E1Eqn)
E1Eqn solve ()
fvOptions correct (he1)
fvOptions constrain (E2Eqn)
fvOptions correct (he2)
thermo1 correct ()
Variables
volScalarField & he2 = thermo2.he()
E1Eqn
E2Eqn
Function Documentation
Cpv1()
volScalarField Cpv1 ("Cpv1" , thermo1. Cpv())
Cpv2()
volScalarField Cpv2 ("Cpv2" , thermo2. Cpv())
Kh()
volScalarField Kh (fluid. Kh())
E1Eqn()
fvScalarMatrix E1Eqn (fvm::ddt(alpha1, rho1, he1)+fvm::div(alphaRhoPhi1, he1) - fvm::Sp(contErr1, he1)+fvc::ddt(alpha1, rho1, K1)+fvc::div(alphaRhoPhi1, K1) - contErr1 *K1+(he1.name()==thermo1.phasePropertyName("e") ? fvc::div(fvc::absolute(alphaPhi1, alpha1, U1), p)+p *fvc::ddt(alpha1) :-alpha1 *dpdt) - fvm::laplacian(fvc::interpolate(alpha1) *fvc::interpolate(thermo1.alphaEff(phase1.turbulence().mut())), he1))
relax()
E1Eqn relax ()
E2Eqn()
fvScalarMatrix E2Eqn (fvm::ddt(alpha2, rho2, he2)+fvm::div(alphaRhoPhi2, he2) - fvm::Sp(contErr2, he2)+fvc::ddt(alpha2, rho2, K2)+fvc::div(alphaRhoPhi2, K2) - contErr2 *K2+(he2.name()==thermo2.phasePropertyName("e") ? fvc::div(fvc::absolute(alphaPhi2, alpha2, U2), p)+p *fvc::ddt(alpha1) :-alpha2 *dpdt) - fvm::laplacian(fvc::interpolate(alpha2) *fvc::interpolate(thermo2.alphaEff(phase2.turbulence().mut())), he2))
constrain() [1/2]
fvOptions constrain (E1Eqn)
solve()
E1Eqn solve ()
correct() [1/3]
fvOptions correct (he1)
constrain() [2/2]
fvOptions constrain (E2Eqn)
correct() [2/3]
fvOptions correct (he2)
correct() [3/3]
thermo1 correct ()
Variable Documentation
he2
volScalarField& he2 = thermo2.he()
Definition at line 3 of file EEqns.H.
Referenced by ThermalPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), and TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer().
E1Eqn
E1Eqn
Initial value:
=
    (
        Kh*(thermo2.T() - thermo1.T())
      + Kh*he1/Cpv1
      - fvm::Sp(Kh/Cpv1, he1)
      + alpha1*rho1*(U1&g)
      + fvOptions(alpha1, rho1, he1)
    )
Definition at line 34 of file EEqns.H.
Referenced by for().
E2Eqn
E2Eqn
Initial value:
=
    (
        Kh*(thermo1.T() - thermo2.T())
      + Kh*he2/Cpv2
      - fvm::Sp(Kh/Cpv2, he2)
      + alpha2*rho2*(U2&g)
      + fvOptions(alpha2, rho2, he2)
    )
Definition at line 67 of file EEqns.H.
Referenced by for().