OpenFOAM: applications/solvers/lagrangian/DPMFoam/UcEqn.H File Reference
UcEqn.H File Reference
Functions
fvVectorMatrix UcEqn (fvm::ddt(alphac, Uc)+fvm::div(alphaPhic, Uc) - fvm::Sp(fvc::ddt(alphac)+fvc::div(alphaPhic), Uc)+continuousPhaseTurbulence->divDevRhoReff(Uc)==(1.0/rhoc) *cloudSU)
UcEqn relax ()
volScalarField rAUc (1.0/UcEqn.A())
surfaceScalarField rAUcf ("Dp", fvc::interpolate(rAUc))
surfaceScalarField phicForces (fvc::flux(rAUc *cloudVolSUSu/rhoc)+rAUcf *(g &mesh.Sf()))
if (pimple.momentumPredictor())
Function Documentation
UcEqn()
fvVectorMatrix UcEqn (fvm::ddt(alphac, Uc)+fvm::div(alphaPhic, Uc) - fvm::Sp(fvc::ddt(alphac)+fvc::div(alphaPhic), Uc)+continuousPhaseTurbulence->divDevRhoReff(Uc) = =(1.0/rhoc) *cloudSU)
Referenced by if().
relax()
UcEqn relax ()
rAUc()
volScalarField rAUc (1.0/UcEqn. A())
Referenced by while().
rAUcf()
surfaceScalarField rAUcf ("Dp" , fvc::interpolate(rAUc))
Referenced by if(), and while().
phicForces()
surfaceScalarField phicForces (fvc::flux(rAUc *cloudVolSUSu/rhoc)+rAUcf *(g &mesh.Sf()))
Referenced by if(), and while().
if()
if (pimple. momentumPredictor())
Definition at line 20 of file UcEqn.H.
References mesh, p, phicForces(), rAUcf(), solve(), and UcEqn().