OpenFOAM: applications/utilities/postProcessing/optimisation/cumulativeDisplacement/createFields.H File Reference
createFields.H File Reference
Functions
pointField points0 (pointIOField(IOobject("points", mesh.time().constant(), polyMesh::meshSubDir, mesh, IOobject::MUST_READ, IOobject::NO_WRITE, IOobject::NO_REGISTER)))
Function Documentation
points0()
pointField points0 (pointIOField(IOobject("points", mesh.time().constant(), polyMesh::meshSubDir, mesh, IOobject::MUST_READ, IOobject::NO_WRITE, IOobject::NO_REGISTER)))
Referenced by displacementInterpolationMotionSolver::curPoints(), displacementLayeredMotionMotionSolver::curPoints(), displacementLaplacianFvMotionSolver::curPoints(), displacementSBRStressFvMotionSolver::curPoints(), solidBodyDisplacementLaplacianFvMotionSolver::curPoints(), rigidBodyMeshMotion::curPoints(), sixDoFRigidBodyMotionSolver::curPoints(), solidBodyMotionDisplacementPointPatchVectorField::localPoints0(), displacementMotionSolver::New(), Foam::lumpedPointTools::setInterpolators(), Foam::lumpedPointTools::setInterpolators(), lumpedPointDisplacementPointPatchVectorField::setInterpolators(), Foam::lumpedPointTools::setInterpolators(), Foam::lumpedPointTools::setPatchControls(), Foam::lumpedPointTools::setPatchControls(), Foam::lumpedPointTools::setPatchControls(), rigidBodyMeshMotion::solve(), sixDoFRigidBodyMotionSolver::solve(), lumpedPointDisplacementPointPatchVectorField::updateCoeffs(), velocityDisplacementMotionSolver::velocityDisplacementMotionSolver(), lumpedPointMovement::writeVTP(), lumpedPointMovement::writeVTP(), and lumpedPointMovement::writeZonesVTP().