OpenFOAM: applications/utilities/preProcessing/createBoxTurb/createFields.H File Reference
createFields.H File Reference
Functions
IOdictionary dict (IOobject("createBoxTurbDict", runTime.constant(), runTime, IOobject::MUST_READ))
const Vector< label > N (dict.get< Vector< label > >("N"))
autoPtr< Function1< scalar > > Ek (Function1< scalar >::New("Ek", dict, &runTime))
const vector delta (L.x()/scalar(N.x()), L.y()/scalar(N.y()), L.z()/scalar(N.z()))
Random rndGen (1234)
Variables
const vector L (dict.get< vector >("L"))
const label nModes = dict.get<label>("nModes")
Function Documentation
dict()
IOdictionary dict (IOobject("createBoxTurbDict", runTime.constant(), runTime, IOobject::MUST_READ))
N()
const Vector< label > N (dict.get< Vector< label > > "N")
Referenced by FixedList< T, 2 >::back(), energySpectrum::calcAndWriteSpectrum(), ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), ReactingParcel< ParcelType >::calcPhaseChange(), Foam::calcQE16(), ReactingMultiphaseParcel< ParcelType >::calcSurfaceReactions(), COxidationMurphyShaddix< CloudType >::calculate(), FixedList< T, 2 >::cbegin(), FixedList< T, N >::cend(), FixedList< T, N >::checkStart(), interfaceTrackingFvMesh::correctUsBoundaryConditions(), PengRobinsonGas< Specie >::Cp(), PengRobinsonGas< Specie >::CpMCv(), FixedList< T, 2 >::data(), multiphaseMangrovesSource::dragCoeff(), FixedList< T, N >::empty(), FixedList< T, N >::end(), FixedList< T, N >::end(), multiphaseMangrovesTurbulenceModel::epsilonCoeff(), edgeInterpolationScheme< Type >::euclidianInterpolate(), FixedList< T, 2 >::fcValue(), FixedList< T, 2 >::fill(), FixedList< T, N >::find(), FixedList< T, N >::FixedList(), FixedList< T, N >::FixedList(), FixedList< T, N >::FixedList(), FixedList< T, N >::FixedList(), FixedList< T, N >::FixedList(), FixedList< T, N >::FixedList(), FixedList< T, N >::FixedList(), noiseFFT::frequencies(), multiphaseMangrovesSource::inertiaCoeff(), edgeInterpolationScheme< Type >::interpolate(), multiphaseMangrovesTurbulenceModel::kCoeff(), List< T >::List(), FixedList< T, N >::max_size(), noiseModel::meanPf(), noiseFFT::meanPf(), FixedList< T, N >::moveLast(), McCowan::newtonRapsonF1(), McCowan::newtonRapsonF2(), FixedList< T, N >::operator<(), FixedList< T, N >::operator=(), List< T >::operator=(), FixedList< T, N >::operator=(), FixedList< T, N >::operator=(), FixedList< T, N >::operator=(), FixedList< T, N >::operator=(), FixedList< T, N >::operator=(), FixedList< T, N >::operator==(), noiseModel::PSDf(), noiseFFT::PSDf(), FixedList< T, 2 >::resize(), FixedList< T, N >::rfind(), noiseModel::RMSmeanPf(), noiseFFT::RMSmeanPf(), Roots< N >::Roots(), pairPotential::setLookupTables(), FixedList< T, N >::size(), FixedList< T, N >::size_bytes(), Foam::Swap(), FixedList< T, N >::swapLast(), fft::transform(), FixedList< T, N >::uniform(), noiseModel::uniformFrequencies(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), FixedList< T, 2 >::writeEntry(), and FixedList< T, N >::writeEntry().
Ek()
autoPtr< Function1< scalar > > Ek (Function1< scalar > ::New"Ek", dict, &runTime)
Referenced by Foam::kShellIntegration(), and Foam::kShellMean().
delta()
const vector delta (L. x)/scalar(N.x(), L. y)/scalar(N.y(), L. z)/scalar(N.z())
rndGen()
Random rndGen (1234)
Variable Documentation
L
const vector L(dict.get< vector >("L")) (dict.get< vector > "L")
Referenced by InterfaceCompositionModel< Thermo, OtherThermo >::addMDotL(), LehrMilliesMewes::addToBinaryBreakupRate(), MassTransferPhaseSystem< BasePhaseSystem >::calculateL(), Zuber::CHF(), HuaXu::CHFSubCool(), Tatsumoto::CHFSubCool(), SQP::computeMeritFunction(), dynamicLagrangian< BasicTurbulenceModel >::correct(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::correctInterfaceThermo(), turbulenceFields::execute(), MassTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), BreenWestwater::htcFilmBoil(), Bromley::htcFilmBoil(), Foam::Math::incGammaRatio_Q(), segregated::K(), interfaceHeatResistance< Thermo, OtherThermo >::Kexp(), kineticGasEvaporation< Thermo, OtherThermo >::Kexp(), InterfaceCompositionModel< Thermo, OtherThermo >::L(), Foam::LAB_to_XYZ(), Foam::labToMsh(), Jeschar::MHF(), Kutadeladze::qNucleate(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), energySpectrum::read(), Schroeder::TDNB(), pressurePIDControlInletVelocityFvPatchVectorField::updateCoeffs(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), waveMakerPointPatchVectorField::waveLength(), irregularMultiDirectional::waveLength(), StokesI::waveLength(), cuboid::write(), and Foam::XYZ_to_LAB().
nModes
const label nModes = dict.get<label>("nModes")
Definition at line 22 of file createFields.H.