OpenFOAM: applications/utilities/postProcessing/miscellaneous/pdfPlot/createFields.H File Reference
createFields.H File Reference
Functions
IOdictionary pdfDictionary (IOobject("pdfDict", runTime.constant(), runTime, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
const label nIntervals (pdfDictionary.get< label >("nIntervals"))
const label nSamples (pdfDictionary.get< label >("nSamples"))
const bool writeData (pdfDictionary.get< bool >("writeData"))
mkDir (pdfPath)
autoPtr< distributionModel > p (distributionModel::New(pdfDictionary, rndGen))
if (writeData)
scalarField samples (nIntervals, Zero)
Variables
const fileName pdfPath = runTime.path()/"pdf"
Random rndGen
const scalar xMin = p->minValue()
const scalar xMax = p->maxValue()
autoPtr< OFstream > filePtr
Function Documentation
pdfDictionary()
IOdictionary pdfDictionary (IOobject("pdfDict", runTime.constant(), runTime, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
nIntervals()
const label nIntervals (pdfDictionary.get< label > "nIntervals")
Referenced by uniformInterpolationTable< Type >::uniformInterpolationTable().
nSamples()
const label nSamples (pdfDictionary.get< label > "nSamples")
Referenced by inverseDistance::createStencil(), windowModel::nWindowsTotal(), ParticleTracks< CloudType >::postFace(), and windowModel::validate().
writeData()
const bool writeData (pdfDictionary.get< bool > "writeData")
mkDir()
mkDir (pdfPath)
Referenced by Foam::cp(), Foam::makeGraph(), Foam::mkDir(), Foam::writeCellGraph(), and Foam::vtk::writePointSet().
p()
autoPtr< distributionModel > p (distributionModel::New(pdfDictionary, rndGen))
if()
if (writeData)
Definition at line 38 of file createFields.H.
References filePtr, p, and pdfPath.
samples()
scalarField samples (nIntervals , Zero)
Referenced by triSurfaceSearch::calcInside(), mappedPatchBase::calcMapping(), mappedPatchBase::collectSamples(), inverseDistance::createStencil(), mappedPatchBase::findLocalSamples(), refinementSurfaces::findNearest(), refinementSurfaces::findNearest(), searchableSurfaces::findNearest(), searchableSurfaces::findNearest(), triSurfaceMesh::findNearest(), searchableBox::findNearest(), searchableCone::findNearest(), searchableCylinder::findNearest(), searchableDisk::findNearest(), searchableExtrudedCircle::findNearest(), searchablePlane::findNearest(), searchablePlate::findNearest(), searchableRotatedBox::findNearest(), searchableSphere::findNearest(), searchableSurfaceCollection::findNearest(), triSurfaceMesh::findNearest(), distributedTriSurfaceMesh::findNearest(), searchableSurface::findNearest(), triSurfaceRegionSearch::findNearest(), distributedTriSurfaceMesh::findNearest(), triSurfaceSearch::findNearest(), searchableSurfacesQueries::findNearest(), searchableSurfacesQueries::findNearest(), refinementFeatures::findNearestEdge(), refinementFeatures::findNearestPoint(), refinementSurfaces::findNearestRegion(), refinementSurfaces::findNearestRegion(), refinementSurfaces::findNearestRegion(), refinementFeatures::findNearestRegionEdge(), mappedPatchBase::findSamples(), distributedTriSurfaceMesh::getVolumeType(), searchableSurfaceWithGaps::getVolumeType(), TableBase< Type >::interpolator(), mappedPatchFieldBase< Type >::mappedField(), inverseDistance::markDonors(), trackingInverseDistance::markDonors(), extendedEdgeMesh::nearestFeatureEdge(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), interpolationWeights::New(), offsetSurface::operator()(), sampledPatchInternalField::sampleOnPoints(), searchableSurfacesQueries::signedDistance(), splineInterpolationWeights::splineInterpolationWeights(), and Sampled< Type >::value().
Variable Documentation
pdfPath
const fileName pdfPath = runTime.path()/"pdf"
Definition at line 20 of file createFields.H.
Referenced by if().
rndGen
Random rndGen
Definition at line 23 of file createFields.H.
Referenced by procFacesGAMGProcAgglomeration::agglomerate(), Foam::barycentric01(), Foam::barycentric2D01(), Stochastic< CloudType >::calculate(), polyMesh::cellTree(), LarsenBorgnakkeVariableHardSphere< CloudType >::collide(), VariableHardSphere< CloudType >::collide(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), meshRefinement::distribute(), eddy::eddy(), extendedEdgeMesh::edgeTree(), triSurfaceMesh::edgeTree(), extendedEdgeMesh::edgeTreesByType(), eddy::epsilon(), treeBoundBox::extend(), treeBoundBox::extend(), patchProbes::findElements(), mappedPatchBase::findLocalSamples(), boundBox::inflate(), boundBox::inflate(), FreeStream< CloudType >::inflow(), InjectedParticleDistributionInjection< CloudType >::initialise(), InjectedParticleDistributionInjection< CloudType >::InjectedParticleDistributionInjection(), distributionModel::New(), extendedEdgeMesh::pointTree(), RecycleInteraction< CloudType >::postEvolve(), tetrahedron< Point, PointRef >::randomPoint(), triangle< Point, PointRef >::randomPoint(), refinementFeatures::regionEdgeTrees(), edgeIntersections::removeDegenerates(), randomRenumber::renumber(), ConeNozzleInjection< CloudType >::setPositionAndCell(), PatchFlowRateInjection< CloudType >::setPositionAndCell(), PatchInjection< CloudType >::setPositionAndCell(), ConeNozzleInjection< CloudType >::setProperties(), triSurfaceSearch::tree(), triSurfaceRegionSearch::treeByRegion(), SHF< CloudType >::update(), TAB< CloudType >::update(), and while().
xMin
const scalar xMin = p->minValue()
Definition at line 34 of file createFields.H.
Referenced by waveMakerPointPatchVectorField::initialiseGeometry(), and waveModel::initialiseGeometry().
xMax
const scalar xMax = p->maxValue()
Definition at line 35 of file createFields.H.
Referenced by waveMakerPointPatchVectorField::initialiseGeometry(), waveModel::initialiseGeometry(), and uniformInterpolationTable< Type >::interpolate().
filePtr
autoPtr<OFstream> filePtr
Definition at line 37 of file createFields.H.
Referenced by surfaceNoise::calculate(), if(), and pointNoise::processData().