OpenFOAM: applications/solvers/multiphase/VoF/alphaEqn.H File Reference
alphaEqn.H File Reference
Functions
word alpharScheme ("div(phirb,alpha)")
if (isType< fv::EulerDdtScheme< scalar > >(ddtAlpha)||isType< fv::localEulerDdtScheme< scalar > >(ddtAlpha))
else if (isType< fv::CrankNicolsonDdtScheme< scalar > >(ddtAlpha))
surfaceScalarField phic (mixture.cAlpha() *mag(phi/mesh.magSf()))
if (icAlpha > 0)
if (scAlpha > 0)
forAll (phic.boundaryField(), patchi)
tmp< surfaceScalarField > phiCN (phi)
if (ocCoeff > 0)
if (MULESCorr)
for (int aCorr=0;aCorr< nAlphaCorr;aCorr++)
if (alphaApplyPrevCorr &&MULESCorr)
if (word(mesh.ddtScheme("ddt(rho,U)"))==fv::EulerDdtScheme< vector >::typeName||word(mesh.ddtScheme("ddt(rho,U)"))==fv::localEulerDdtScheme< vector >::typeName)
Variables
scalar ocCoeff = 0
const fv::ddtScheme< scalar > & ddtAlpha = tddtAlpha()
else
scalar cnCoeff = 1.0/(1.0 + ocCoeff)
surfaceScalarField::Boundary & phicBf
Function Documentation
alpharScheme()
word alpharScheme ("div(phirb,alpha)")
if() [1/8]
if (isType< fv::EulerDdtScheme< scalar > > ddtAlpha)||isType< fv::localEulerDdtScheme< scalar > >(ddtAlpha)
Definition at line 18 of file alphaEqn.H.
References ocCoeff.
if() [2/8]
else if (isType< fv::CrankNicolsonDdtScheme< scalar > > ddtAlpha)
Definition at line 26 of file alphaEqn.H.
References alphaRestart, ddtAlpha, FatalErrorInFunction, mesh, nAlphaSubCycles(), and ocCoeff.
phic()
surfaceScalarField phic (mixture. cAlpha) *mag(phi/mesh.magSf())
if() [3/8]
if (icAlpha , 0)
Definition at line 62 of file alphaEqn.H.
References icAlpha(), mixture, phic(), and U.
if() [4/8]
if (scAlpha , 0)
Definition at line 69 of file alphaEqn.H.
References mesh, phic(), scAlpha(), and U.
forAll()
forAll (phic. boundaryField(), patchi)
Definition at line 81 of file alphaEqn.H.
References phicBf.
phiCN()
tmp< surfaceScalarField > phiCN (phi)
if() [5/8]
if (ocCoeff , 0)
Definition at line 94 of file alphaEqn.H.
References cnCoeff, phi, and phiCN().
if() [6/8]
if (MULESCorr)
Definition at line 99 of file alphaEqn.H.
References alpha1, alpha2, alphaApplyPrevCorr(), alphaPhi10, divU, LTS, mesh, mixture, phiCN(), Sp, Su, and talphaPhi1Corr0.
for()
for ()
Definition at line 158 of file alphaEqn.H.
References alpha1, alpha10(), alpha2, alphaPhi10, alphaPhiUn(), alpharScheme(), divU, mixture, MULESCorr(), phi, phic(), phiCN(), phir(), Sp, and Su.
if() [7/8]
if (alphaApplyPrevCorr && MULESCorr)
Definition at line 228 of file alphaEqn.H.
References alphaPhi10, and talphaPhi1Corr0.
if() [8/8]
if (word(mesh.ddtScheme("ddt(rho,U)")) = = fv::EulerDdtScheme<vector>::typeName || word(mesh.ddtScheme("ddt(rho,U)")) == fv::localEulerDdtScheme<vector>::typeName)
Definition at line 240 of file alphaEqn.H.
References alphaPhi10, phiCN(), rho1f(), rho2f(), and rhoPhi.
Variable Documentation
ocCoeff
scalar ocCoeff = 0
Definition at line 6 of file alphaEqn.H.
ddtAlpha
const fv::ddtScheme<scalar>& ddtAlpha = tddtAlpha()
Definition at line 16 of file alphaEqn.H.
else
else
Initial value:
{
            FatalErrorInFunction
                << "Only Euler and CrankNicolson ddt schemes are supported"
                << exit(FatalError)
Definition at line 47 of file alphaEqn.H.
cnCoeff
scalar cnCoeff = 1.0/(1.0 + ocCoeff)
Definition at line 56 of file alphaEqn.H.
phicBf
surfaceScalarField::Boundary& phicBf
Initial value:
=
        phic.boundaryFieldRef()
Definition at line 76 of file alphaEqn.H.