OpenFOAM: src/finiteVolume/cfdTools/general/include/volContinuity.H File Reference
volContinuity.H File Reference
Functions
conserve primitiveFieldRef ()+
Variables
scalar sumLocalContErr
scalar globalContErr
Function Documentation
primitiveFieldRef()
conserve primitiveFieldRef ()
Referenced by GeometricField< Type, PatchField, GeoMesh >::clamp_max(), GeometricField< Type, PatchField, GeoMesh >::clamp_min(), GeometricField< Type, PatchField, GeoMesh >::clamp_range(), GeometricField< Type, PatchField, GeoMesh >::clamp_range(), displacementComponentLaplacianFvMotionSolver::curPoints(), displacementLaplacianFvMotionSolver::curPoints(), solidBodyDisplacementLaplacianFvMotionSolver::curPoints(), GeometricField< Type, PatchField, GeoMesh >::negate(), GeometricField< Type, PatchField, GeoMesh >::normalise(), GeometricField< Type, PatchField, GeoMesh >::operator=(), GeometricField< Type, PatchField, GeoMesh >::replace(), fvMatrix< Type >::setValuesFromList(), faMatrix< Type >::setValuesFromList(), and fvMatrix< Type >::solveSegregated().
Variable Documentation
sumLocalContErr
scalar sumLocalContErr
Initial value:
= runTime.deltaTValue()*
        mag(conserve)().weightedAverage(mesh.V()).value()
Definition at line 9 of file volContinuity.H.
globalContErr
scalar globalContErr
Initial value:
= runTime.deltaTValue()*
        conserve.weightedAverage(mesh.V()).value()
Definition at line 12 of file volContinuity.H.