OpenFOAM: applications/solvers/combustion/fireFoam/YEEqn.H File Reference
YEEqn.H File Reference
Functions
tmp< fv::convectionScheme< scalar > > mvConvection (fv::convectionScheme< scalar >::New(mesh, fields, phi, mesh.divScheme("div(phi,Yi_h)")))
volScalarField Yt (0.0 *Y[0])
forAll (Y, i)
Y[inertIndex] clamp_min (0)
radiation correct ()
fvScalarMatrix EEqn (fvm::ddt(rho, he)+mvConvection->fvmDiv(phi, he)+fvc::ddt(rho, K)+fvc::div(phi, K)+(he.name()=="e" ? fvc::div(fvc::absolute(phi/fvc::interpolate(rho), U), p, "div(phiv,p)") :-dpdt) - fvm::laplacian(turbulence->alphaEff(), he)==Qdot+radiation->Sh(thermo, he)+parcels.Sh(he)+surfaceFilm.Sh()+fvOptions(rho, he))
EEqn relax ()
fvOptions constrain (EEqn)
EEqn solve ()
fvOptions correct (he)
Variables
Qdot = combustion->Qdot()
Y [inertIndex] = scalar(1) - Yt
volScalarField & he = thermo.he()
Function Documentation
mvConvection()
tmp< fv::convectionScheme< scalar > > mvConvection (fv::convectionScheme< scalar > ::Newmesh, fields, phi, mesh.divScheme("div(phi,Yi_h)"))
Referenced by forAll(), if(), and if().
Yt()
volScalarField Yt (0.0 * Y[0])
Referenced by MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::correctThermo(), forAll(), reactingOneDim::solveSpeciesMass(), and MultiComponentPhaseModel< BasePhaseModel, phaseThermo >::solveYi().
forAll()
forAll (Y , i)
Definition at line 16 of file YEEqn.H.
References combustion(), composition, fvOptions, inertIndex, mesh, mvConvection(), phi, rho, surfaceFilm, turbulence, Y, and Yt().
clamp_min()
Y[inertIndex] clamp_min (0)
Referenced by GeometricField< Type, PatchField, GeoMesh >::clamp_min().
correct() [1/2]
radiation correct ()
EEqn()
fvScalarMatrix EEqn (fvm::ddt(rho, he)+mvConvection->fvmDiv(phi, he)+fvc::ddt(rho, K)+fvc::div(phi, K)+(he.name()=="e" ? fvc::div(fvc::absolute(phi/fvc::interpolate(rho), U), p, "div(phiv,p)") :-dpdt) - fvm::laplacian(turbulence->alphaEff(), he) = =Qdot+radiation->Sh(thermo, he)+parcels.Sh(he)+surfaceFilm.Sh()+fvOptions(rho, he))
Referenced by for().
relax()
EEqn relax ()
constrain()
fvOptions constrain (EEqn)
solve()
EEqn solve ()
correct() [2/2]
fvOptions correct (he)
Variable Documentation
Qdot
Qdot = combustion->Qdot()
Definition at line 13 of file YEEqn.H.
Y
Y[inertIndex] = scalar(1) - Yt
Definition at line 47 of file YEEqn.H.
Referenced by forAll().
he
volScalarField& he = thermo.he()
Definition at line 52 of file YEEqn.H.
Referenced by interRegionHeatTransferModel::addSup(), wallHeatFlux::calcHeatFlux(), limitTemperature::correct(), heThermo< BasicPsiThermo, MixtureType >::Cpv(), forAll(), OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransfer(), AnisothermalPhaseModel< BasePhaseModel >::heEqn(), if(), if(), heatTransferCoeffModel::q(), reactingEulerHtcModel::q(), radiationModel::Sh(), thermo< Thermo, Type >::THE(), basicThermo::validate(), basicThermo::validate(), basicThermo::validate(), and basicThermo::validate().