var searchData=
[
  ['kahipdecomp_0',['kahipDecomp',['../classFoam_1_1kahipDecomp.html',1,'Foam']]],
  ['kaqrwallfunctionfvpatchscalarfield_1',['kaqRWallFunctionFvPatchScalarField',['../classFoam_1_1kaqRWallFunctionFvPatchScalarField.html',1,'Foam']]],
  ['kepsilon_2',['kepsilon',['../classFoam_1_1incompressible_1_1RASVariables_1_1kEpsilon.html',1,'kEpsilon'],['../classFoam_1_1RASModels_1_1kEpsilon.html',1,'kEpsilon&lt; BasicTurbulenceModel &gt;']]],
  ['kepsilon_3c_20eddydiffusivity_3c_20compressible_3a_3aturbulencemodel_20_3e_20_3e_3',['kEpsilon&lt; EddyDiffusivity&lt; compressible::turbulenceModel &gt; &gt;',['../classFoam_1_1RASModels_1_1kEpsilon.html',1,'Foam::RASModels']]],
  ['kepsilonlopesdacosta_4',['kEpsilonLopesdaCosta',['../classFoam_1_1RASModels_1_1kEpsilonLopesdaCosta.html',1,'Foam::RASModels']]],
  ['kepsilonphitf_5',['kEpsilonPhitF',['../classFoam_1_1RASModels_1_1kEpsilonPhitF.html',1,'Foam::RASModels']]],
  ['keqn_6',['kEqn',['../classFoam_1_1LESModels_1_1kEqn.html',1,'Foam::LESModels']]],
  ['key_5fiterator_5fbase_7',['key_iterator_base',['../classFoam_1_1HashTable_1_1key__iterator__base.html',1,'Foam::HashTable']]],
  ['keytype_8',['keyType',['../classFoam_1_1keyType.html',1,'Foam']]],
  ['kinematiccloud_9',['kinematiccloud',['../classFoam_1_1kinematicCloud.html',1,'kinematicCloud'],['../classFoam_1_1KinematicCloud.html',1,'KinematicCloud&lt; CloudType &gt;']]],
  ['kinematiccloud_3c_20cloud_3c_20basickinematiccollidingparcel_20_3e_20_3e_10',['KinematicCloud&lt; Cloud&lt; basicKinematicCollidingParcel &gt; &gt;',['../classFoam_1_1KinematicCloud.html',1,'Foam']]],
  ['kinematiccloud_3c_20foam_3a_3adsmccloud_20_3e_11',['KinematicCloud&lt; Foam::DSMCCloud &gt;',['../classFoam_1_1KinematicCloud.html',1,'Foam']]],
  ['kinematiclookuptableinjection_12',['KinematicLookupTableInjection',['../classFoam_1_1KinematicLookupTableInjection.html',1,'Foam']]],
  ['kinematicparcel_13',['KinematicParcel',['../classFoam_1_1KinematicParcel.html',1,'Foam']]],
  ['kinematicparcelinjectiondata_14',['kinematicParcelInjectionData',['../classFoam_1_1kinematicParcelInjectionData.html',1,'Foam']]],
  ['kinematicparcelinjectiondataiolist_15',['kinematicParcelInjectionDataIOList',['../classFoam_1_1kinematicParcelInjectionDataIOList.html',1,'']]],
  ['kinematicreynoldsnumber_16',['KinematicReynoldsNumber',['../classFoam_1_1KinematicReynoldsNumber.html',1,'Foam']]],
  ['kinematicsinglelayer_17',['kinematicSingleLayer',['../classFoam_1_1regionModels_1_1surfaceFilmModels_1_1kinematicSingleLayer.html',1,'Foam::regionModels::surfaceFilmModels']]],
  ['kinematicsurfacefilm_18',['KinematicSurfaceFilm',['../classFoam_1_1KinematicSurfaceFilm.html',1,'Foam']]],
  ['kinematicthinfilm_19',['kinematicthinfilm',['../classFoam_1_1regionFaModels_1_1kinematicThinFilm.html',1,'kinematicThinFilm'],['../classFoam_1_1regionModels_1_1areaSurfaceFilmModels_1_1kinematicThinFilm.html',1,'kinematicThinFilm']]],
  ['kineticgasevaporation_20',['kineticGasEvaporation',['../classFoam_1_1meltingEvaporationModels_1_1kineticGasEvaporation.html',1,'Foam::meltingEvaporationModels']]],
  ['kinetictheorymodel_21',['kinetictheorymodel',['../classFoam_1_1kineticTheoryModel.html',1,'kineticTheoryModel'],['../classFoam_1_1RASModels_1_1kineticTheoryModel.html',1,'kineticTheoryModel']]],
  ['kirchhoffshell_22',['kirchhoffshell',['../classFoam_1_1regionFaModels_1_1KirchhoffShell.html',1,'KirchhoffShell'],['../classFoam_1_1regionModels_1_1KirchhoffShell.html',1,'KirchhoffShell']]],
  ['kklomega_23',['kkLOmega',['../classFoam_1_1incompressible_1_1RASModels_1_1kkLOmega.html',1,'Foam::incompressible::RASModels']]],
  ['kl_24',['kL',['../classFoam_1_1RASModels_1_1kL.html',1,'Foam::RASModels']]],
  ['klowrewallfunctionfvpatchscalarfield_25',['kLowReWallFunctionFvPatchScalarField',['../classFoam_1_1kLowReWallFunctionFvPatchScalarField.html',1,'Foam']]],
  ['kmesh_26',['Kmesh',['../classFoam_1_1Kmesh.html',1,'Foam']]],
  ['kocamustafaogullariishii_27',['KocamustafaogullariIshii',['../classFoam_1_1wallBoilingModels_1_1departureDiameterModels_1_1KocamustafaogullariIshii.html',1,'Foam::wallBoilingModels::departureDiameterModels']]],
  ['komega_28',['kOmega',['../classFoam_1_1RASModels_1_1kOmega.html',1,'Foam::RASModels']]],
  ['komegasst_29',['komegasst',['../classFoam_1_1incompressible_1_1RASVariables_1_1kOmegaSST.html',1,'kOmegaSST'],['../classFoam_1_1RASModels_1_1kOmegaSST.html',1,'kOmegaSST&lt; BasicTurbulenceModel &gt;']]],
  ['komegasstbase_30',['kOmegaSSTBase',['../classFoam_1_1kOmegaSSTBase.html',1,'Foam']]],
  ['komegasstbase_3c_20desmodel_3c_20basicturbulencemodel_20_3e_20_3e_31',['kOmegaSSTBase&lt; DESModel&lt; BasicTurbulenceModel &gt; &gt;',['../classFoam_1_1kOmegaSSTBase.html',1,'Foam']]],
  ['komegasstbase_3c_20eddyviscosity_3c_20rasmodel_3c_20basicturbulencemodel_20_3e_20_3e_20_3e_32',['kOmegaSSTBase&lt; eddyViscosity&lt; RASModel&lt; BasicTurbulenceModel &gt; &gt; &gt;',['../classFoam_1_1kOmegaSSTBase.html',1,'Foam']]],
  ['komegasstddes_33',['kOmegaSSTDDES',['../classFoam_1_1LESModels_1_1kOmegaSSTDDES.html',1,'Foam::LESModels']]],
  ['komegasstdes_34',['kOmegaSSTDES',['../classFoam_1_1LESModels_1_1kOmegaSSTDES.html',1,'Foam::LESModels']]],
  ['komegasstiddes_35',['kOmegaSSTIDDES',['../classFoam_1_1LESModels_1_1kOmegaSSTIDDES.html',1,'Foam::LESModels']]],
  ['komegasstlm_36',['kOmegaSSTLM',['../classFoam_1_1RASModels_1_1kOmegaSSTLM.html',1,'Foam::RASModels']]],
  ['komegasstsas_37',['kOmegaSSTSAS',['../classFoam_1_1RASModels_1_1kOmegaSSTSAS.html',1,'Foam::RASModels']]],
  ['komegasstsato_38',['kOmegaSSTSato',['../classFoam_1_1RASModels_1_1kOmegaSSTSato.html',1,'Foam::RASModels']]],
  ['kqrwallfunctionfvpatchfield_39',['kqRWallFunctionFvPatchField',['../classFoam_1_1kqRWallFunctionFvPatchField.html',1,'Foam']]],
  ['kqrwallfunctionfvpatchfield_3c_20scalar_20_3e_40',['kqRWallFunctionFvPatchField&lt; scalar &gt;',['../classFoam_1_1kqRWallFunctionFvPatchField.html',1,'Foam']]],
  ['kts_41',['KTS',['../classFoam_1_1XiGModels_1_1KTS.html',1,'Foam::XiGModels']]],
  ['kunz_42',['Kunz',['../classFoam_1_1phaseChangeTwoPhaseMixtures_1_1Kunz.html',1,'Foam::phaseChangeTwoPhaseMixtures']]],
  ['kutadeladze_43',['Kutadeladze',['../classFoam_1_1wallBoilingModels_1_1nucleateFluxModels_1_1Kutadeladze.html',1,'Foam::wallBoilingModels::nucleateFluxModels']]]
];
